### ISSUE TITLE
Help request for setting WebAppPool Identity

### ISSUE THREAD

**Issue by bob53050** [oleg-shilo/wixsharp#100]
I can't seem to get this code snippet to work for setting the WeAppPool Identity:

```C#
new IISVirtualDir
                {
                    Name = "InFlowConvertWeb",
                    AppName = "InFlowConvertWeb",
                    WebSite = defaultWebSite,
                    WebAppPool = new WebAppPool(
                        "InFlowConvertWeb",
                        "Identity:other, User:username")
                }
```

When I rebuild the installer project, I get unresolved reference to symbol 'User=[local username I am using]'

I will appreciate any help,

Bob

**Comment by oleg-shilo** [comment]
There are a few problems here. 
I am not sure you provided the accurate code snippet. The attributes definition `"Identity:other, User:username"` is in illegal form and it prevents WiX code generation. The following change unblocks the code compilation:
```C#
new WebAppPool( "InFlowConvertWeb",  "Identity=other; User=username")
```
After the change the Wix# produces the correct WiX XML:
```XML
<WebAppPool Id="MyWebApp2_AppPool" 
            Name="MyWebApp2" 
            Identity="other" 
            User="username" 
            xmlns="http://schemas.microsoft.com/wix/IIsExtension" />
```
The XML above is valid according the WiX [documentation](http://wixtoolset.org/documentation/manual/v3/xsd/iis/webapppool.html):

Name | Type  | Description
-------|-------|-------------
User   | String | User account to run the AppPool as. To use this, you must set the Identity attribute to 'other'.

However I seriously doubt that this official WiX description is accurate. Most likely the "user" attribute has to be an Id of the `User` element (with name, password, ...) within the same XML. That is why 'light' gives you "unresolved reference to symbol".

Sorry I cannot help you much with that as the problem has nothing to do with Wix# and the question is in fact a pure WiX question. Though you can experiment by adding `User` element with an explicit Id and then placing this ID into your WebAppPool's User attribute. Have a look at `Wix# Samples\CreateUser` sample.
