### ISSUE TITLE
When using Wix nuget package SDK location is not resolved correctly by Wix#

### ISSUE THREAD

**Issue by Davidvanluijk** [oleg-shilo/wixsharp#1001]
In an attempt to not having to install Wix on the buildserver I want to use the Wix nuget package for tooling and the SDK. For doing this I copied the target from WixSharp nuget package to my project file and modified the bin parameter (see below). This works for resolving the bin folder, but fails to resolve the SDK folder as an exception is thrown:

1>Unhandled Exception: System.ArgumentNullException: Value cannot be null.
1>Parameter name: path1
1>   at System.IO.Path.Combine(String path1, String path2)
1>   at WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String configFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
1>   at WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
1>   at WixSharp.Compiler.GenerateWixProj(Project project)
1>   at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
1>   at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
1>   at WixSharp.Compiler.Build(Project project, String path, OutputType type)
1>   at WixSharp.Compiler.Build(Project project, OutputType type)
1>   at WixSharp.Project.BuildMsi(String path)
1>   at IAI.BMO.MachineConfiguration.Installer.Program.Main() in 

This can be traced back to WixBinLocater FindWixSdkLocation which returns null always in case of the SDK folder being inside the wixLocation. Removing the "return null" on line 29 resolves the issue (tested locally).

**Comment by oleg-shilo** [comment]
Hi David, if SDK has an unexpected structure the user needs to set the correct path to the SDK tools explicitly as it is suggested in the exception message.

I am not sure I see how avoiding returning null solves the problem. `null` in this case is a required indication that the path to SDK is unknown.

**Comment by Davidvanluijk** [comment]
Hi Oleg,

Yes, but it now also returns null if it has found the correct location of the SDK. My suggestion indeed does not work in case of throwOnError false, so another if is needed (I would say).

Kind regards,
David

**Comment by oleg-shilo** [comment]
Yep, you are absolutely right. After you have added this extra if it makes sense. Merged.
