### ISSUE TITLE
Request: Arm64 support

### ISSUE THREAD

**Issue by rolikoff** [oleg-shilo/wixsharp#1005]
Package's Platform attribute has Arm (arm32) and Arm64.  It looks like it was added in wix 3.14.
https://wixtoolset.org/documentation/manual/v3/xsd/wix/package.html
At the moment, wixsharp has only `arm` in Platform, there's no `arm64`.

Can you please add arm64 support in the next release?
Thank you.

**Comment by oleg-shilo** [comment]
Done, will be available in the very next release
