### ISSUE TITLE
Is WixStandardBootstrapperApplication.HyperlinkSidebarLicense Supported?

### ISSUE THREAD

**Issue by allenlooplee** [oleg-shilo/wixsharp#1006]
Hello,

I want to use HyperlinkSidebarLicense with a custom layout (.xml) via ThemeFile property of the BA. I'm currently using LicenseBootstrapperApplication which is the default option of Bundle. I noticed that the compiler will resolve in either WixStandardBootstrapperApplication.RtfLicense or WixStandardBootstrapperApplication.HyperlinkLicense based on LicensePath. How can I configure it to be HyperlinkSidebarLicense or is it supported?

Thanks/Allen

**Comment by oleg-shilo** [comment]
It is somewhat supported.

You are right the out of box implementation emits `RtfLicense` and `HyperlinkLicense` app refs only. Though changing it to `HyperlinkSidebarLisense` is simple.

```C#
bootstrapper.WixSourceGenerated += document => document
                                       .FindSingle("BootstrapperApplicationRef")
                                       .SetAttribute("Id=WixStandardBootstrapperApplication.HyperlinkSidebarLicense");

bootstrapper.Build();
```
The code above will emit:

```xml
<BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkSidebarLicense">
  <Payload SourceFile="logo.png" />

  <bal:WixStandardBootstrapperApplication ShowVersion="yes" ShowFilesInUse="yes" LogoFile="logo.png" LicenseFile="licence.rtf" />
</BootstrapperApplicationRef>
``` 
Great, but.... WiX burn does not like some of the attributes of `bal:WixStandardBootstrapperApplication`. It's not WixSharp but WiX challenge.

I cannot verify what is wrong with the XML there as I do not see any WiX samples on the matter.
I suggest you 
- Dig the WiX documentation and find out the required XML
- Implement it using the technique I shared with you
- When you are happy with the solution you can share it with me and I will incorporate it in WixSharp so it is available directly without manipulating XML.

**Comment by allenlooplee** [comment]
Hi @oleg-shilo,

Thanks for the quick response and also the great tool. Allow me to provide a little background where this question raised.

I'm currently rebuilding my bootstrapper and installer with WixSharp. Originally the bootstrapper used `HyperlinkSideBarLicense` with a custom theme file tailored for `HyperlinkSideBarLicense` as well as a localization file in the Bundle.wxs file of Wix project. When I used the `LicenseBootstrapperApplication` provided by WixSharp with the `ThemeFile` property set to that custom theme file, the output bootstrapper didn't show when launched. I checked the log and found the errors said "Failed to load theme controls" and "Failed to create main window".

I read the code `LicenseBootstrapperApplication` in [BootstrapperApplication.cs](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp/Bootstrapper/BootstrapperApplication.cs) and figured out a simple solution. The `WixStandardBootstrapperApplication` already has the `LogoSideFile` property which is `null` by default and used only for `HyperlinkSideBarLicense`. We can use it as a clue to determine if `HyperlinkSideBarLicense` should be used and then set the `Id` of the `root` accordingly.

Below is the code snippet that can be used to replace [the current line of code](https://github.com/oleg-shilo/wixsharp/blob/700c8063dda53b0641b80f6a78110443eeadb139/Source/src/WixSharp/Bootstrapper/BootstrapperApplication.cs#L482):

``` C#
if (LogoSideFile.IsEmpty())
{
    root.SetAttribute("Id", "WixStandardBootstrapperApplication.HyperlinkLicense");
}
else
{
    root.SetAttribute("Id", "WixStandardBootstrapperApplication.HyperlinkSidebarLicense");
}
```

With this change applied, if `LicensePath` is set to a URL and `LogoSideFile` is set to an image, then `HyperlinkSideBarLicense` will be used. Otherwise, the current behavior applies.

I can create a pull request or provide the complete code of `LicenseBootstrapperApplication` for my changes if you need.

Regards/Allen

**Comment by allenlooplee** [comment]
@oleg-shilo I created a PR which included my changes for your review.

**Comment by oleg-shilo** [comment]
Excellent. Thank you.
Makes perfect sense.
Merged now.

**Comment by oleg-shilo** [comment]
Will be available in the next release.
In a mean time you can use XML-Injection from my first response in this thread.

Though. The linking problem remains:
 
```ps
setup.wxs
Windows Installer XML Toolset Linker version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

C:\agent\_work\66\s\src\ext\BalExtension\wixlib\wixstdba.wxs(80) : error LGHT0197 : The Windows Installer XML variable !(wix.WixStdbaLicenseUrl) is unknown.  Please ensure the variable is declared on the command line for light.exe, via a WixVariable element, or inline using the syntax !(wix.WixStdbaLicenseUrl=some value which doesn't contain parenthesis).
```  

Does light.exe it behave the same way on your system?

**Comment by allenlooplee** [comment]
@oleg-shilo Just tried your code in the first response and had no issue on my system as below fragment of output. I also ran the boostrapper and verified that it worked as expected.

>  setup.wxs
>  NetFx48.wxs
>  Windows Installer XML Toolset Linker version 3.11.2.4516
>  Copyright (c) .NET Foundation and contributors. All rights reserved.
>  
>  Bootstrapper file has been built: C:\Users\allenlooplee\source\repos\AclassInstaller\BuildInstallerWithWixSharp\Aclass-setup.exe

BTW, I created a console application that targeted .NET Framework 4.8 in Visual Studio 2019 and installed the latest WixSharp NuGet package (v1.18.0) for it to work.

**Comment by oleg-shilo** [comment]
Great, thank you. Then it means something is wrong with my environment.
