### ISSUE TITLE
ignore SubDirectories

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1008]
We have filter to ignore file extension.
Do you have any filter to ignore SubDirectories. Could you help me out.

**Comment by oleg-shilo** [comment]
Sorry for such a delay. Just missed your post. You can use the s same filter as filters are designed to control file/folder inclusion but not the file extensions.

```C#
new Files(@"..\Release Folder\Release\*.*",
                              f => !f.Contains("subdir name"))
```

**Comment by saiprabhur** [comment]
Thanks
