### ISSUE TITLE
Install windows service with property values set during installation depending on custom MsiProperty

### ISSUE THREAD

**Issue by n3xX0r** [oleg-shilo/wixsharp#1010]
Hello,
I am currently trying to figure out the best way to change WixSharp.File.ServiceInstaller properties during installation.
E.g. depending on a custom MsiProperty value I need to change the service dependencies of that service. 
The ServiceInstaller properties are initialized at compile time but I was wondering if and how I could adapt it during installation  once the session properties are available and before the service installation step. Or alternatively what would be the best approach to achieve this without handling and managing the whole windows service initialization, installation, start, stop, etc. in custom actions?
Thank you very much!

**Comment by oleg-shilo** [comment]
Normally you can reference the property value at runtime by enclosing its name in the square brackets:
```C#
 DependsOn = new[]
             {
                 new ServiceDependency("[prop_name_A]"),
                 new ServiceDependency("[prop_name_B]"),
             }
```
But it will work only if WiX element `ServiceDependency` supports expanding properties at runtime

```xml
<ServiceInstall Id="WixSharp.TestSvc" Name="WixSharp.TestSvc" DisplayName . . .>
  <ServiceDependency Id="[prop_name_A]" />
  <ServiceDependency Id="[prop_name_B]" />
  . . .
```
I am guessing you need to try.

The chance it will work is not very good as the WiX model implies that you need to decide on the number of dependencies at compile time. And the documentation does not suggest you can customize at least the names: https://wixtoolset.org/documentation/manual/v3/xsd/wix/servicedependency.html

Thus most likely you need to have multiple `features` which include different set of service dependencies and depending on the runtime conditions or user input you will enable only the one that is required.

Alternatively you can modify the registry with the right dependency expression on after install event. It's rather and anti-pattern solution but if you have no other choice... it will work.
