### ISSUE TITLE
WixSharp in build pipeline of Azure DevOps

### ISSUE THREAD

**Issue by Beautyod** [oleg-shilo/wixsharp#1013]
Is it possible to use WixSharp in a build pipeline of Azure DevOps?

I didn't find any information about that. Neither here nor by searching on Google and StackOverflow.

P.S.
Unfortunately I don't see how to mark this issue as question.

**Comment by oleg-shilo** [comment]
On GitHub everything is an issue. I know, it's not that intuitive :)
WixSharp is just an ordinary VS C# project so you can build it the same way as any other VS project.

- Create a project from the WoxSharp template (install "WixSharp" VS2019 Extension for that)
- Build the project
- Commit to your source control
- Configure your Azure DevOps pipeline to build the project from your source control.
-

**Comment by Beautyod** [comment]
Thanks Oleg (-:
