### ISSUE TITLE
Antivirus false positive due to Custom actions

### ISSUE THREAD

**Issue by maulik-devitpl** [oleg-shilo/wixsharp#1015]
I have created an installer with couple of custom actions and when I try to install EMSISOFT virus  raise it as an infected file. And it does not allow me to install my software. It worked perfectly without any false positive detection after commenting all custom actions.

Does anyone faced such scenario? does anyone have any solution for this?

**Comment by maulik-devitpl** [comment]
I have also signed msi file with licensed EV signed certificate but still it is raising false positive.

**Comment by oleg-shilo** [comment]
False positives are unfortunate part of our reality. I can only recommend educate your users about using comprehensive multi vendor scans as by https://www.virustotal.com. And then possibly tuning up the virus scanner (EMSISOFT) to do less aggressive scans.

**Comment by maulik-devitpl** [comment]
Thank you for your prompt response. 

This happens only if we are working with custom action so I thought if we can do something to prevent false positive. As per the investigation, a temp file is creating for each custom action and this triggers false positive. I was thinking that if we can implement an alternative without creating a temp file may solve this scenario.

But thanks for the details.

**Comment by oleg-shilo** [comment]
Unfortunately it is  something that WixSharp has no control  over  :o(

The temp files are created by the two runtimes working together when extracting and executing managed custom actions: MSI and WiX. If you just build the same msi file but with WiX only you would be facing the same problem.
