### ISSUE TITLE
Manufacturer value missing. After installed  .exe that Bundle from .msi

### ISSUE THREAD

**Issue by psimla** [oleg-shilo/wixsharp#1016]
Manufacturer value missing in Control Panel. How do I fix this

Thank you

**Comment by Torchok19081986** [comment]
Hiho, Is Manufacturer Value set on Msi package or Bootstraper itself?
On MSI  project.ControlPanelInfo.Manufacturer = "My Firma";
an bootstrapper Installer  is Property of Bundle  Manufacturer = "My Firma". Only works for .Net Framework , Not core or net 5.0
