### ISSUE TITLE
Compressed file (7z) release deliverable request

### ISSUE THREAD

**Issue by ZeroAbility** [oleg-shilo/wixsharp#1017]
The previous release has a `7z` compressed file. Would it be possible to continue releasing compressed deliverables? We use it in our CI along with CMake so we don't have to create a Visual Studio project and can just use `Ninja`.

**Comment by oleg-shilo** [comment]
Apologies. It was a release mistake. 7z was supposed to be published.
Fixed now: https://github.com/oleg-shilo/wixsharp/releases/tag/1.18.0.0

**Comment by Krzmbrzl** [comment]
Cool, thank you! :+1:
