### ISSUE TITLE
Removing license dialog from WixSharp project

### ISSUE THREAD

**Issue by vadimLevin1977** [oleg-shilo/wixsharp#1019]
Hi Oleg,

I hope you are well.
We are using WixSharp installers for our services, and we need to remove license dialogs from them.

If we do not provide a license file for the project, it is still shown with a default one.
I would welcome your help.

Thank you,
Vadim Levin

**Comment by oleg-shilo** [comment]
Hi Vadim,

The easiest way to do it is to use Managed dialogs and simply....remove the licence dialog:

_See CustomUI.Sequence sample_

```C#
project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                // .Add(Dialogs.Licence) 
                                .Add(Dialogs.Features)
                                .Add(Dialogs.SetupType)
                                .Add(Dialogs.InstallDir)
                                .Add(Dialogs.Progress)
                                .Add(Dialogs.Exit);
```

**Comment by HavenDV** [comment]
Hello, is there an easy way to do the same without using `ManagedProject`?
`UI`/`CustomUI` only, no separate method/class for defining links between screens.

**Comment by HavenDV** [comment]
Maybe you should add a new type to this enum and implement `MinimalWithoutLicense`? I think this would be the easiest way for end-users.

**Comment by oleg-shilo** [comment]
@HavenDV ManagedProject was exactly introduced to make custom UI easy. Raw WiX is never easy. Particularly UI.

You can post-modify the produced wxs XML to remove licence dialog. WixSharp support for MSI UI even had an example for it. So you can check...

But tbh I would never consider native UI customization unless I have no choice. 

> MinimalWithoutLicense

This enum value is not supported by WiX so WixSharp cannot make WiX compilers to handle it. 
But WixSharp can address this gap by introducing its own UI customization. And it is exactly what Managed UI is.
