### ISSUE TITLE
Update nuget package WixSharp.bin to include WIX (Windows Installer Xml) Toolset v3.11

### ISSUE THREAD

**Issue by PawelTroka** [oleg-shilo/wixsharp#102]
Please update WixSharp.bin to WIX v3.11. I have tested it with v3.11 and it works correctly.
This is kind of important as WIX v3.10 is lacking some basic functionality like WixNetfxExtension PackageGroups NetFx461Web and Properties WIX_IS_NETFRAMEWORK_461_OR_LATER_INSTALLED

**Comment by oleg-shilo** [comment]
OK, I will do it right away. Though I thing you meant "WixSharp.wix.bin" nuget package. Am I right?

**Comment by PawelTroka** [comment]
Yeah, I mean the one that contains WIX binaries 👍

**Comment by oleg-shilo** [comment]
All done. You can update the package.

**Comment by PawelTroka** [comment]
Great, thanks 🥇
