### ISSUE TITLE
Header for ManagedUI cutting into text for dialog

### ISSUE THREAD

**Issue by gregvis** [oleg-shilo/wixsharp#1021]
See image below...any way to format this? 

![image](https://user-images.githubusercontent.com/8760745/125991423-90f5925d-f222-4e84-aae8-4c2d72899bc1.png)

**Comment by oleg-shilo** [comment]
Absolutely.

You can just create your project from the WixSharp VS project template "Custom UI" and you will access to the all dialogs and can adjust the all UI elements as needed.

This sort of problems can happens from time to time as the UI that you are using is WinForm based and as any WinForm dialog it does not handle well custom scaling (display settings). 

WPF will solve this problem. The support ahs been added already but the stock UI sequence has not been ported just yet.
