### ISSUE TITLE
Copy File Not working

### ISSUE THREAD

**Issue by Manvish1230** [oleg-shilo/wixsharp#1023]
Hi, I am trying to use CopyFile class to copy the file to destination directory
But I keep getting "is not a legal identifier. Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.). Every identifier must begin with either " error

Do you have any samples on how to use CopyFile class ?

Thanks

**Comment by oleg-shilo** [comment]
I have never tried to use it. 
It was implemented on one user request but `CopyFile` is pretty much WiX creature and it's use goes against WixSharp paradigm. Even though it does not conflict with it.

WiX way (example I found):
```xml
<Property Id="MY_CUSTOM_DESTINATION" Value="D:\MyCustomFolder" />
<File Id="MyFileXml" ... />

<DirectoryRef Id="MyAppFolderThatIsInProgramFiles">
     <Component Id="MyComponent" Guid="some_guid">
      <File Id="MyFileXml" Source="MyFile.xml" KeyPath="yes" >
          <RemoveFile Id="MyFileRemoveId" Name="MyFile.xml" On="install" Directory="MY_CUSTOM_DESTINATION" />      
          <CopyFile Id="Copy_MyFileXml" DestinationProperty="MY_CUSTOM_DESTINATION"/>
      </File>
     </Component>
</DirectoryRef>
```

WixSharp way:

```c#
project.AfterInstall += args =>
{
    if (!args.IsInstalling)
        IO.File.Copy(args.InstallDir.PathJoin("MyFile.xml"), @"D:\MyCustomFolder\MyFile.xml"), true);
}
```
  If you are still keen to get `CopyFile` working then have a look at the generated wxs file. Most likely it will have a clue about "_...is not a legal identifier..._".

**Comment by hughpons** [comment]
@oleg-shilo Is this a typo in CopyFile,  public string **Field**; supose to be **FileId**

**Comment by oleg-shilo** [comment]
Yes you are right. It is a typo.
Fixed. Will be available in the next release.

Until then you can use `AttributesDefinition`:
```C#

new CopyFile
{
    AttributesDefinition = "FileId=MyFile"
}
```
