### ISSUE TITLE
COM server objects outputting invalid XML

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#1027]
Due to lack of understanding and rushing due to a time crunch, I implemented #1025 incorrectly. I think I have fixed it, but I would like assistance writing tests for this to ensure it actually creates valid WiX XML. I will create a draft pull request, and would like to make sure the classes are structured properly and then learn how to write tests.

**Comment by oleg-shilo** [comment]
Fixed by #1025
The fix will be available in the very next release.
It is a perfect issue report: the person who reported it has also provided the fix :)
