### ISSUE TITLE
Compiler.WixLocation, WixSharp.wix.bin and new csproj format in Visual Studio 2017

### ISSUE THREAD

**Issue by PawelTroka** [oleg-shilo/wixsharp#103]
When environment variable WIXSHARP_WIXDIR is not set and WIX is not installed Wix# will look for Wix binaries in `<solution_dir>\packages\WixSharp.wix.bin\<max_version>\tools\bin`.

This is fine as long as developer uses Visual Studio 2015 or lower. This is also fine when using Visual Studio 2017 with `packages.config` file.

However since Visual Studio 2017 has built-in new NuGet client and new csproj format allows you to define NuGet dependencies directly in csproj file, packages are pulled into different location.

This location is for WixSharp.wix.bin package typically, at least on Windows: `C:\Users\<USER>\.nuget\packages\wixsharp.wix.bin\<max_version>\tools\bin`.

So I guess the way we set Compiler.WixLocation needs to be changed to also include this possible location.

**Comment by briangbutterfield** [comment]
This is a current issue for me as well @PawelTroka.

**Comment by oleg-shilo** [comment]
Thank you for letting me know. The "WiX probing" algorithm definitely needs to reflect that.

**Comment by oleg-shilo** [comment]
Done in 23b3863.
Will be available in the next release.

**Comment by MHHenriksen** [comment]
Doesn't look like this fully solves the issue. You're still using `"WixSharp.wix.bin.*"` as the directory name pattern, but that's not how packages are organized anymore, it's `WixSharp.wix.bin\<version>` (it was noted in the first post, but it's easy to miss :).

**Comment by oleg-shilo** [comment]
Reopening it...

**Comment by oleg-shilo** [comment]
Indeed I have missed that point and only handled an extra location. The fix seems obvious but... I would like to better understand your use case. In my tests I haven't pick the problem because my VS2017 placed the downloaded package in the same dir structure as usual. 

This is my understanding that in order to trigger that new NuGet placement it has to be either _.NET Core_ or _.NEt Standard_ project. None of them is compatible with any WixSharp NuGet packages anyway. Thus how exactly you trigger the problem you described?

**Comment by MHHenriksen** [comment]
No, all it needs to do is use the new .csproj format that uses `<packageref>` for Nuget dependencies (as opposed to packages.config). It can still be a regular .Net Framework project in all other ways.

**Comment by MHHenriksen** [comment]
Here's a reference specifically explaining this use case :) https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html#what-about-other-project-types-that-are-not-net-core

**Comment by oleg-shilo** [comment]
Thank you for the explanations. 
Fixed. Will be available in the next release (in a day or two).
