### ISSUE TITLE
Simplify ProgID registration for COM Classes

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#1031]
To reduce the amount of boilerplate code (arrays with single entries), introduce members `ProgId` and `VersionIndependentProgId` to `ComRegistration` class. This makes it easier to understand and harder to mix up (as even the COM Registration example provided in the repo has the version-dependent ProgId listed as the version-independent ProgId).

If those fields aren't set, the current behavior should be followed. Otherwise, the existing `ProgIds` field should be exclusively for aliases.

This is just a suggestion, and might not be as useful as I imagine, but I figure it couldn't hurt to offer it up as an enhancement. If you decide that it would be beneficial, I would be willing to do this task.

**Comment by oleg-shilo** [comment]
Hi Charles, I am happy for you to give it a try.
It seems like you are on top of all COM related functionality.
