### ISSUE TITLE
Replace redundant Extension, MIME, and Verb classes with FileAssociation

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#1032]
`FileAssociation` should implement `IGenericEntity` and the `Extensions` member of `ProgId` should be changed to type `FileAssociation[]`.

In `ProcessDirectoryFiles` (starting at line 1749), the processing for `FileAssociation` should be moved to `FileAssociation.Process` and compiler should use the `ProgId` class to simplify the function.

When I was fleshing out the ComRegistration.cs classes, I didn't realize that `FileExtension` was a simplified version of the Extension/MIME/Verb hierarchy or I would have used it instead.

**Comment by oleg-shilo** [comment]
Hi Charles, I am happy for you to give it a try if you can find some time. Sorry I an still heavily involved with my other OS projects.
At this moment, for WixSharp, I can only spare time for defect fixes.
