### ISSUE TITLE
Is it possible to make a WixLib?

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#1033]
I see that Wix# can generate MSIs and MSMs. Can it also make WixLibs or is that redundant or unnecessary?

**Comment by oleg-shilo** [comment]
You guessed right :)
WixLib offers some opportunities for WiX users but from the WoxSharp prospective it does not give much and yet it would be difficult to integrate.

It's like *.lib has its place in C++. But in C#, not really....
