### ISSUE TITLE
Help to backup folder before installation

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1039]
Guide me how to take backup folder before installation and also delete folder.

Tried BeforeInstall i am getting error when i used 
 Directory.Move(e.InstallDir, @"%CommonAppDataFolder%\Test\Previous");

Do i am doing wrong.

**Comment by sonicbhoc** [comment]
What directory are you trying to back up and why? Windows Installer is transactional and should roll back the environment to its previous state should something go wrong.

If your program wants to back-up files in an old format or something, that should be handled in the program itself and not in the installer, in my opinion. This also opens up the ability to validate and migrate old files to a new format.

If you really wanted to do it in the installer, I suggest using a Custom Action to do so. `ManagedProject`s have support for event handlers that can run `BeforeInstall`, Look into that.

**Comment by oleg-shilo** [comment]
I might be wrong, but I do not think `Directory.Move` can automatically expand environment variables. 
You will need to expand it explicitly:
```C#
Directory.Move(e.InstallDir, @"%CommonAppDataFolder%\Test\Previous".ExpandEnvVars());
```

**Comment by oleg-shilo** [comment]
And, I just checked. `%CommonAppDataFolder%` is not even an envar variable.
you need to pass the actual path then

**Comment by saiprabhur** [comment]
Thanks for the reply. i have tried it was working. 
Anytime i have to keep only one previous folder. When i tried to delete existing previous folder. i am getting below error.

System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\companyname\Product\Previous\modules\Folder\File.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at MoveFolder.Program.msi_BeforeInstall(SetupEventArgs e)
   --- End of inner exception stack trace ---

Any help to over come this issue.

**Comment by saiprabhur** [comment]
Found the cause and fixed by giving permission to the folder during install using 
DirPermission()..
then try to delete the folder it worked. Closing this issue.

**Comment by Zerpico** [comment]
> Found the cause and fixed by giving permission to the folder during install using DirPermission().. then try to delete the folder it worked. Closing this issue.

Can you show a code example of how you solved this problem?
