### ISSUE TITLE
Unable to install WixSharp package in VS2017 :(

### ISSUE THREAD

**Issue by igorushi** [oleg-shilo/wixsharp#104]
I'm trying to install WixSharp using project templates and plain nuget, unfortunately with no success.
What I'm doing wrong?
There is my nuget console log:

PM> Install-Package WixSharp

Attempting to gather dependency information for package 'WixSharp.1.4.6.2' with respect to project 'WixSharpSetup1', targeting '.NETFramework,Version=v3.5'
Gathering dependency information took 551.82 ms
Attempting to resolve dependencies for package 'WixSharp.1.4.6.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'WixSharp.1.4.6.2'
Resolved actions to install package 'WixSharp.1.4.6.2'
Retrieving package 'WixSharp 1.4.6.2' from 'nuget.org'.
Retrieving package 'WixSharp.bin 1.4.6.2' from 'nuget.org'.
Adding package 'WixSharp.bin.1.4.6.2' to folder 'C:\Install\WixSharpSetup1\packages'
Added package 'WixSharp.bin.1.4.6.2' to folder 'C:\Install\WixSharpSetup1\packages'
Install failed. Rolling back...
Package 'WixSharp.bin.1.4.6.2' does not exist in project 'WixSharpSetup1'
Removing package 'WixSharp.bin.1.4.6.2' from folder 'C:\Install\WixSharpSetup1\packages'
Removed package 'WixSharp.bin.1.4.6.2' from folder 'C:\Install\WixSharpSetup1\packages'
Executing nuget actions took 330.24 ms
Install-Package : Failed to add reference to 'BootstrapperCore'.
  Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))
At line:1 char:1
+ Install-Package WixSharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by oleg-shilo** [comment]
Most likely @johnferry0 is right.

Less chancees but still worth to checking if the dependency package WixSharp.bin.1.4.6.2 is present in the `packages` folder.

**Comment by igorushi** [comment]
@johnferry0 no, I even didn't tried it yet :)  
Checked with  .net 3.5 and .net 4.62 projects both fail.  

@oleg-shilo , I've tried to install `WixSharp.bin` package before and it fails ... so it looks like this is a problematic one. What is a right way to install it?
![image](https://user-images.githubusercontent.com/7131092/28056263-f7a5b76e-6624-11e7-83a7-5ae3c4d104e8.png)

**Comment by oleg-shilo** [comment]
The anticipated way is to install it with the 
 ```
Install-Package WixSharp
```
"WixSharp" package should automatically bring the dependency package "WixSharp.bin". If for whatever reason dependency package is not triggered then you can try to install it manually:
```
 Install-Package WixSharp.bin
```
It this does not help then I can only assume that somehow your NuGet integration is broken. 

But you can always download do the the Wix# binaries from GitHub release and manually reference all the assemblies from the "Samples" folder. 

BTW this way you will also be able to have a look at a few samples that are composed as a VS project without any dependency on NuGet. You can even use one of these samples as your project template.

**Comment by wkit23** [comment]
I'm able to install-package without any issue in Visual Studio 2017 update 2.
Tested with targeting .Net 3.5 and also .Net 4.6.

**Comment by oleg-shilo** [comment]
Excellent. Thank you for letting me know.
