### ISSUE TITLE
Resume the msi installation after .NET framework 4.7.2 installation with a reboot

### ISSUE THREAD

**Issue by rekhasasidharan** [oleg-shilo/wixsharp#1041]
I am building an application with the wixinstaller which needs .NET Framework 4.7.2 as one of the prerequisites. Added a custom action to install the .netframework through the exe ndp472_kb4054531_web.exe, through a powershell script. Since the target machine doesn't have the internet connection, the exe is downloaded and included in the project, which is installing through the script.  Now the scripts executes and installs the .NET framework 4.7.2 in the target machine and reboot the machine. Now I need to find a way to resume the installation after the reboot. Can anyone suggest an idea to move forward.

The call from the C# code is as

dotNetInstallScriptFile = tempDirectory.PathJoin(@"installDotnet.ps1");
 var exitCode = StartProcess("Powershell.exe", $"-file \"{dotNetInstallScriptFile}\"");

The installDotnet.ps1 is 

Start-Process -FilePath 'ndp472_kb4054531_web.exe' /passive -Wait -Passthru

I have tried out /norestart /q options in the script and the system reboot was not happened with out the .NET framework installation. Thank you.

**Comment by rekhasasidharan** [comment]
Adding RunOnce registry key is a solution

**Comment by hvandrie** [comment]
Either Scheduled Task that runs in System context configured to run at start-up or logon, or write your own installer service that continues work flow to install prereqs before your application is.
