### ISSUE TITLE
it will be added to the startup item

### ISSUE THREAD

**Issue by BluceBosen** [oleg-shilo/wixsharp#1042]
When installing the WixBootstrapper_ UI, it will be added to the startup item and then deleted immediately. As a result, the security defense software on some computers will report "add to system item", so as to prevent its installation. Unless the user chooses trust, is there a good solution?

The Registry key:
HKEY_ LOCAL_ MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\RunOnce - [{20979c74-a3d9-49d5-82fe-08472efd2bb6}]

**Comment by oleg-shilo** [comment]
Sorry for the delay with the response. This behaviour is not introduced by WixSharp but rather a default behaviour implemented by WiX/Burn. 

Thus the chances are that you may find the answer on WiX forums since it is a WiX question.

**Comment by BluceBosen** [comment]
Thank you very much. I'll try
