### ISSUE TITLE
AllFiles

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#105]
In the InfoQ interview, the extensibility of WIX# was discussed with a very useful example for "AllFiles". Has anyone written an AllFiles extension method or any other extensions?

**Comment by oleg-shilo** [comment]
Sorry, for some reason your post did not trigger any GitHub notification. Thus, the good chances are tha no one read it yet.

Anyway the `AllFiles` feature I was talking about already exist though it's named a bit differently.
```C#
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new Files(@"..\Release Folder\Release\*.*"),
            ...
```
You can also have a _wildcard path_ for all top-level directory files and user defined file filters (delegates). You will find two examples (in the distro) that illustrate the usage: "ReleaseFolder" and "WildCard Files".

**Comment by johnferry0** [comment]
I had trouble with this detecting all sub-directories and their files. This seemed to work:
```
var serviceDirectory = new Dir
{
    Id = "SERVICEDIR",
    Name = Configuration.SERVICE_INSTALL_DIRECTORY + @"\" + directoryName,
    // Parent Directory
    Files = GetWixFilesCollectionForService(Configuration.SERVICEPATH, serviceName, displayName, serviceDescription, hostExe),
    Dirs = GetSubDirectories(Configuration.SERVICEPATH).ToArray()
 };

 
private static List<Dir> GetSubDirectories(string directory)
{
    var subDirectoryInfosCollection = new List<Dir>();

    foreach (var subDirectory in Directory.GetDirectories(directory))
    {
        var subDirectoryName = subDirectory.Remove(0, subDirectory.LastIndexOf('\\') + 1);
        var newDir = new Dir(subDirectoryName, new Files(subDirectory + @"\*.*"))
        {
            Name = subDirectoryName
        };
        subDirectoryInfosCollection.Add(newDir);

        // Recursively traverse nested directories
        GetSubDirectories(subDirectory);
    }
    return subDirectoryInfosCollection;
}
```

**Comment by johnferry0** [comment]
This seems to be a very useful advantage that WIX# has over regular WIX.
