### ISSUE TITLE
Restrict Windows 7 OS 

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1051]
I am using Bundle class to build exe with MSI and msms.
I want restrict setup should be install in windows 7. 
Could any one share problems.

**Comment by Torchok19081986** [comment]
Morning, i would start mit CustomAction OnBeforeInstall Event. Maybe following links can helps you with https://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/block_install_on_os.html
https://docs.microsoft.com/de-de/windows/win32/msi/operating-system-property-values?redirectedfrom=MSDN

Best regards.

**Comment by saiprabhur** [comment]
Thanks for the support
