### ISSUE TITLE
Change Default log path.

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1052]
How to change log path of MSI and Bundle setup.
Currently log file is created in the temp folder.

I know how to use msiexec to create log file from command prompt. During installation the log file should created in different path.

Please any one help me out.

**Comment by oleg-shilo** [comment]
The bootsrtapper will automatically log to the %TEMP% based location. 
A specific location for the log file can be set by passing a path to -l (-log): 
```c#
setup.exe -l "<your log file>"
```

**Comment by saiprabhur** [comment]
yes your correct. the setup will be shared to end user. Basically  they will not run setup with parameters.
taught there will be option to change the path.

**Comment by oleg-shilo** [comment]
Most likely there is but Bundle normally requires it at compile time (not runtime):
This is what I found:
> You can also add a `<Log PathVariable="c:\TEMP\installerlog.txt"/>` line under `<Bundle>`.

But if you need to change it during the installation then search in WiX documentation may give you something.

**Comment by saiprabhur** [comment]
in our project we plan to go with default log path. closing this issue
