### ISSUE TITLE
Bundle setup how identifies already installed version.

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1053]
In the bundle setup i have not set control panel info for the setup.
Only enable controlpanel info in the MSI.
When i install the setup application installed successfully. i could see MSI in the control panel.
Using Add/remove program i have uninstalled the MSI successfully.

When i run Setup exe it asks for Repair/Uninstall option.
If i do uninstall.
Uninstall not happening properly. I tried to find key in Wow64....\...\uninstall could not found. 
Since i am not added controlpanelinfo for bundle its not added key.

Question: How setup finds there is version already installed. Could anyone help me out.

**Comment by Torchok19081986** [comment]
hiho. 
1. what is meaning of "uninstall not happening properly" ? Any errors or packages still remain in controlpanelinfo?
2. Sample of Bundle in Sample of WixSharp could help you. 
3. Bundle ist only GUI for Install , nothing more.  MSI do job for install/uninstall.
4. In you have to add controlpanelinfo in msi , not bundle. Bundle itselft doesnt have any properties for Controlpanel info.
5. if you want your bundle work correctly, let msi handle install/uninstall your package.  MSI looking for you at start after package and handle it for new install / uninstall or maybe update / upgrade.  
6. your msi and output bundle .exe should be same architecture , not different. for msi exists only x86 treeviw or only x64 treeview in registry. means, if you set different ways , msi doenst find it.

Try samples on Bundles. May it helps you with your problem. Oleg do good job for samples.
