### ISSUE TITLE
Question: How to delete all remains files and folders at uninstalling app

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1058]
Hallo, i have difficulty to remove / delete all remain files or directories if app should be uninstall. In InstallDir remains files and dirs, which comes from app itself, some settings files. How do i remove all remain files from installdir and installdir itself, if my app should be uninstall by msi. I tried at beforeinstall with notbeinginstalled and not upgraded, but it doesnt work.
Can someone pls help me ??

following code doesnt work in my msi package.
```csharp

 private static void Project_AfterInstall(SetupEventArgs e)
  {
            if (e.IsUninstalling && !e.IsUpgrading)
                e.InstallDir.DeleteIfExists();
 }

```

Best regards.

**Comment by oleg-shilo** [comment]
[DeleteIfExists](https://github.com/oleg-shilo/wixsharp/blob/c27a9cebaa4b75b94e5a14b5f6e82877037eabef/Source/src/WixSharp/Extensions.cs#L1068-L1117)
 is an extension that deletes file/directory and is to be used in simple straightforward scenarios. It will fail if you have files locked or some other more complicated conditions. 

The use of `AfterInstall` is something that I would suggest if you are to do cleanup manually but you need to debug and see why the deletion is failing. 

Though... I would encourage you even more to reconsider your deployment approach. Normally the app should not write the runtime configuration/logs to the deployment location. If possible, of course.

**Comment by oleg-shilo** [comment]
I think there is confusion here.

MSI runtime will only create/repair and delete artifacts (files/regvals) that are part of the MSI definition and as such, they are **deployment artifacts**. 

Settings, log files are not part of the deployment but runtime artifacts. And as such, they are not to be managed by the MSI. Meaning that MSI will never touch them regardless of where you place them. And it is a good thing. This way you can persist your settings (if required) between upgrades, reinstalls and even have your settings being different depending on the current user.

These are the _good deployment design_ principles that were first articulated long time ago when WinVista was introduced. At that time you could not get your app certified as "Designed For Vista" if your app creates any file in the `Program Files`

Anyway, you still believe you need to manually delete some files the `AfterInstall` event is your friend. But not creating the files in the installation dir has nothing to do with that. It was just a comment about your deployment approach.

**Comment by Torchok19081986** [comment]
Many thanks, Oleg.  I going use regvalues for settings and logs .  With this approach i don't create any files or dirs in deployment path and can update app without any problems and i don't have to delete files manually at uninstall :-) . 
Question ist completelly answered. Close the question.
