### ISSUE TITLE
How to detect package platform during install?

### ISSUE THREAD

**Issue by NickeManarin** [oleg-shilo/wixsharp#1059]
I'm going to create three installers setting the project.Platform as x86, x64, or Arm64 for my application and I want to detect the platform during the installation, to warn the use if the package is not quite the correct one.

Is there any way to detect the platform during the install process?

**Comment by Torchok19081986** [comment]
hiho,  i would going with LaunchConditions. Some Wix Toolset Trick or if you dont find some solutions then witch CustomAction at Start / Launchconditions or even BeforeInstall.  
for detection on x86 and x64 you can use  Environment.Is64BitOperatingSystem. for Arm64, dont know. Just create CA and get value of it .  
There ist sample from Oleg on X64 Installtion, you can use it, i both. 
best regards.

**Comment by NickeManarin** [comment]
I was thinking of passing properties during the package assembly, but wanted first to know if there's any built-in way of getting the package arch.

**Comment by oleg-shilo** [comment]
> I was thinking of passing properties during the package assembly...
> I want to detect the platform during the installation...

These two statements are mutually exclusive. What I am guessing is that the most important requirement is to warn users about the incompatible OS. So something like this will work:
Very similar to @Torchok19081986  suggestion:

```C#
    static public void Main(string[] args)
    {
        var project =  . . . 
       
        . . . 

        if (Enum.TryParse(args.FirstOrDefault(), out Platform p))
            project.Platform = p; // "x64", "x86" and "arm64"
        else
            project.Platform = Platform.x86;

        project.AddProperty(new Property("Platform", project.Platform.ToString()));

        project.UIInitialized += e =>
        {
            var compatible = false;
            var architecture = Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE");

            switch (e.Session.Property("Platform"))
            {
                case "x86": compatible = (architecture == "X86"); break;
                case "x64": compatible = (architecture == "AMD64"); break;
                case "arm64": compatible = (architecture == "ARM64"); break;
            };

            if (!compatible)
            {
                MessageBox.Show("Wrong platform!");
                e.Result = ActionResult.Failure;
            }
        };

    . . .
```
 
And when you build msi you will need to run it three times:
![image](https://user-images.githubusercontent.com/16729806/135715959-1d1e13c5-fd6e-42b9-a58a-166cebd728fd.png)
In this case do not forget to remove your prokjcet targets that were injected if you used `WixSharp` nuget package. Note `WixSharp.bin` package does not inject targets so it is actually better suitable for your case.

**Comment by NickeManarin** [comment]
> These two statements are mutually exclusive.

Not sure if I understood you. 
I wanted to check if the user is installing the correct package for the OS architecture, and one way was to check the project platform that the project was set to use.

**This is the flow:**
`x86` package, `x64` OS: Possible, but not recommended.
`x64` package, `x86` OS: Not possible (I don't think it even lets you run the MSI).
`x86/x64` package, `Arm64` OS: Possible, but not recommended (I believe).
`Arm64` package, `x86/x64` OS: Not possible (error message appears, invalid architecture).

-------------

At first, I wanted to know if the `project.Platform` property was available somewhere during the install process.
If not, I would do something like you did in here:

> project.AddProperty(new Property("Platform", project.Platform.ToString()));

Then I would just need to check the OS architecture (not processor).

----------------

> In this case do not forget to remove your prokjcet targets that were injected if you used WixSharp nuget package. Note WixSharp.bin package does not inject targets so it is actually better suitable for your case.

I didnt undertand this part. I actually have both nuget packages.

**Comment by oleg-shilo** [comment]
> Not sure if I understood you.
> I wanted to check if the user is installing the correct package for the OS architecture.

Nevermind 😄 we are on the same page. You want to check the OS at runtime.

>  I wanted to know if the project.Platform property was available...

No, it's not. The instance of `Project` only exists during the build time. So you will have to use the property to tunnel the value to the runtime phase.

> check the OS architecture (not processor).

I was only an example. Of course, you can use any other criteria to identify the OS architecture. The great thing about the proposed approach is that you can use C# - meaning you can do anything. 😄 

>  actually have both nuget packages. What should I do?

Either create a new equivalent project but add only `WixSharp.bin` package.
Or remove `WixSharp` package from the existing project

**Comment by NickeManarin** [comment]
Thanks!
