### ISSUE TITLE
Issue in Dir initialization

### ISSUE THREAD

**Issue by FreeFlyingEnchilada** [oleg-shilo/wixsharp#106]
According to the documentation ( https://wixsharp.codeplex.com/wikipage?title=Developer%27s%20Guide ) these two code blocks should produce identical objects.
```C#
            Project project1;
            {
                project1 = new Project("MyProduct",
                    new Dir(@"%ProgramFiles%\My Company\My Product",
                         new File(@"Files\Docs\Manual.txt"),
                         new File(@"Files\Bin\MyApp.exe")));
            }

            Project project2;
            {
                var docFile = new File(@"Files\Docs\Manual.txt");
                var exeFile = new File(@"Files\Bin\MyApp.exe");
                var dir = new Dir(@"%ProgramFiles%\My Company\My Product");

                dir.Files = new[] { docFile, exeFile };

                project2 = new Project();
                project2.Dirs = new[] { dir };
                project2.Name = "MyProduct";
            }
```
However, they do not. The statement 

    var dir = new Dir(@"%ProgramFiles%\My Company\My Product");

returns a reference to the parent directory instead of the child directory. So the files all end up getting added to the %Program Files% Dir instead of the My Product Dir.

**Comment by oleg-shilo** [comment]
The documentation section you are quoting is definitely wrong. 
While the `Dir` constructor works correctly the code sample is wrong and does not serve the purpose.   
The documentation has been reworked on both CodePlex and GitHub

Thank you.

**Comment by FreeFlyingEnchilada** [comment]
Thanks, glad to be of help.
