### ISSUE TITLE
What diffrences in WixSharp projects?

### ISSUE THREAD

**Issue by RachelGanonNew** [oleg-shilo/wixsharp#1063]
I need to create a wixsharp project to build windows service installer.
I don't need UI at all, but I need a complex installer (complicated custom action)
what project should I choose?
I see you have` WixSharp Setup, WixSharp Managed Setup`, etc.
which one fit me?
thank you

**Comment by oleg-shilo** [comment]
`WixSharp Managed Setup` in my opinion offers a better opportunity for handling complex scenarios.
The difference is that with "WixSharp Managed Setup" you can use more convenient events (e.g. `project.AfterInstall += ... `).

If you are to use "WixSharp Setup" then you have to use more convoluted custom actions.

**Comment by RachelXGanon** [comment]
Can I use WixSharp Managed Setup with no UI?
I mean, double click on *.msi file install the Installer silently?
 with no user Interaction like agree to  license etc.
thank you.

**Comment by RachelXGanon** [comment]
Yes. Just to make sure I get you right,
 Using `ProgressOnly` is silent install and rejecting the  license.
Is there a way of using `ProgressOnly` and agreeing to license?
As running from cmd: `msiexec.exe /i "C:\example.msi" /quiet /qn ` install silently and agreed to license automatically without show the user license dialog.
Thank you

**Comment by RachelXGanon** [comment]
Hi,
Is there a way to NOT show error messages such as` DowngradeErrorMessage` when **double click** on `*.msi`
though the error YES will be present at the `Event Viewer` ?
Thank you

**Comment by oleg-shilo** [comment]
![image](https://user-images.githubusercontent.com/16729806/136695351-89ea9b4b-d8d3-46b4-bbc6-33c9fcbe804a.png)

As for event viewer, you will need to log it by yourself as if you allow downgrading it is no longer an error.
