### ISSUE TITLE
WpfDialog.DialogTitle does not work for the first WPF dialog in a sequence

### ISSUE THREAD

**Issue by GarrenMiller** [oleg-shilo/wixsharp#1064]
A while ago I opened #1034, and the issues I mentioned were fixed in the `1.18.3-pre` release.  I was able to rebuild the default WinForms dialogs using WPF and I have implemented them in my installer project.  I am very happy with this release and it has helped me with my project a ton.  Thanks!  There is one (very small) issue that I noticed:

The first WPF dialog in a sequence (i.e. the ManagedUI.InstallDialogs or ManagedUI.ModifyDialogs sequences) does not show its title.  Here's the opening XAML tag for my rendition of the license dialog:

```
<wixsharp:WpfDialog
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:wixsharp="clr-namespace:WixSharp.UI.WPF;assembly=WixSharp.UI.WPF" x:Name="LicenseDialog"
             x:Class="WindowsInstaller.Dialogs.LicenseDialogWpf"
             mc:Ignorable="d"
             DialogTitle="[ProductName] Setup"
             d:DesignHeight="331.333" d:DesignWidth="588.668" Width="550" Height="400">
```

Currently, this is the second dialog in my install sequence, and the title works just as I would expect it to.  `[Product Name]` is replaced with the actual product name and the title is shown at the very top of the dialog.  Here's the opening tag for my WelcomeDialog:

```
<wixsharp:WpfDialog
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:wixsharp="clr-namespace:WixSharp.UI.WPF;assembly=WixSharp.UI.WPF" x:Name="WelcomeDialog"
             x:Class="WindowsInstaller.Dialogs.WelcomeDialogWpf"
             mc:Ignorable="d"
             DialogTitle="[ProductName] Setup"
             d:DesignHeight="331.333" d:DesignWidth="588.668" Width="550" Height="400">
```
This is the first dialog in my install sequence, and I have noticed that the title does not show at all.  There is just the MSI icon and then blank white space where the title should be.  I noticed that this behavior also extends to the first dialog of the modification sequence.  Here's the XAML for my rendition of the MaintenanceTypeDialog, which is the first dialog in the modification sequence:

```
<wixsharp:WpfDialog
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:wixsharp="clr-namespace:WixSharp.UI.WPF;assembly=WixSharp.UI.WPF" x:Name="MaintenanceTypeDialog"
             x:Class="WindowsInstaller.Dialogs.MaintenanceTypeDialogWpf"
             mc:Ignorable="d"
             DialogTitle="[ProductName] Setup"
             d:DesignHeight="331.333" d:DesignWidth="588.668" Width="550" Height="400">
```

Furthermore, I tried swapping dialog positions.  Initially the LicenseDialog title showed when the dialog was not the first in the sequence.  But then when I removed the WelcomeDialog and made the LicenseDialog the first in the sequence, its title was no longer visible.  This leads me to believe that the dialogs are probably built fine and there is an issue elsewhere.  This is not a big issue at all, and does not affect performance or usability.  Just wanted to document it and have visibility to the issue.  Thanks for the pre-release!  It was super helpful.

**Comment by oleg-shilo** [comment]
Really glad to hear that you have progressed so far.

I think it is the problem with the initialization of the dialogs shell, not your dialogs.
Will have a look on weekend.

BTW, this a selfish question. Is your dialog sequence something that you would share with the project?

**Comment by GarrenMiller** [comment]
@oleg-shilo I would be happy to share the ones I have rebuilt with the project (there are a few dialogs that I haven't rebuilt because my job didn't need it, like the features dialog).  I would have to take a little time to remove company-related code from my rebuilds, but that would not be too difficult.  I will take some time at nights and during the weekend to get a PR together.
