### ISSUE TITLE
Directory warning.

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1068]
warning LGHT1124: The Directory 'CommonAppDataFolder.Company name' starts with the same Id as the standard folder in Windows Installer 'CommonAppDataFolder'. A directory Id that begins with the same Id as a standard folder that is in an MSM may encounter a conflict when merging the MSM into an MSI. This may result in the contents of this merge module being installed to an unexpected location. To eliminate this warning, change your directory Id to not start with the same Id as any standard folders.

How to fix this warning. I have to use same path for MSM and MSI.

**Comment by oleg-shilo** [comment]
you can give the directory an explicit Id:
```C#
new Dir(new Id("MyExplicitDir"), @"...
```
