### ISSUE TITLE
ManagedBootstrapperApplication Payloads

### ISSUE THREAD

**Issue by virulentt** [oleg-shilo/wixsharp#107]
wixsharp/Source/src/WixSharp/Bootstrapper/BootstrapperApplication.cs

Its more of a suggestion than an issue, but i'm trying to have localized resources and the fact that all payloads are placed in the root of the temp folder when executing, my resources are not found. I would love a way to specify the name of the payload as well.

**Comment by oleg-shilo** [comment]
> I would love a way to specify the name of the payload as well

Can you please elaborate?
Currently you can specify the name of the pyloads:
```C#
Payloads = new[] { @"Samples\setup1.dll", @"Samples\setup2.dll", }, 
```
Most likely you have something else in mind...

**Comment by virulentt** [comment]
If i'm not mistaken, this line of code would add this :

<Payload SourceFile="Samples\setup1.dll" />
<Payload SourceFile="Samples\setup2.dll" />

. By default, when the installer starts, they will be extracted in the root of the installer. I wanted to add localization with different resources, which are placed in a fr folder, and the installer is looking in a fr folder to load them. Example :

Payload SourceFile="Samples\setup1.dll" Name="fr\setup1.dll" />
Payload SourceFile="Samples\setup1.dll" Name="fr\setup2.dll" />

Then, in the Temp folder of the extracted installation, these dll will be located in the fr folder.

**Comment by oleg-shilo** [comment]
OK, I see.

I'll see what can be done about that. The API can be tricky as I am not sure I want to elevate _payload_ from being a string to a rich class. But I just may have to...

In a mean time please use the following XML injection to achieve the desired functionality.
```C#
bootstrapper.WixSourceGenerated += (doc) =>
{
    doc.FindAll("Payload")
       .Select(x => new 
               { 
                   Element = x, 
                   File = x.Attribute("SourceFile").Value.PathGetFileName()
               })
       .Where(x => x.File.EndsWith(".dll"))
       .ForEach(x => x.Element.AddAttributes($"Name=fr\\{x.File}"));
};
```

**Comment by virulentt** [comment]
Maybe a Dictionary<string, string> could do the trick!

Thank you for your help!

**Comment by oleg-shilo** [comment]
Done. The release will be available in a few days.
```C#
var bootstrapper =
    new Bundle("My Product",         
        new MsiPackage(productMsi)         
        {
             DisplayInternalUI = true,
             Payloads = new[] {
                                  new Payload("script.dll") { Name = @"fr\script.dll" },
                                  new Payload("utils_a.dll"),
                                  "utils_b.dll".ToPayload()
                              }
             ...
```

**Comment by virulentt** [comment]
Wow thank you! I really appreciate your support!

**Comment by oleg-shilo** [comment]
The latest NuGet package contains the fix.
