### ISSUE TITLE
Is there a way to a fully customize exit dialog?

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1071]
Hi,
I want to show the user a customized exit dialog,
For example:
After `installation` the dialog will say: `"Installation of product 'x.y.x' succeed"`,
after update the dialog will say:` "An upgrade of product 'x.y.x' succeed"`,
In case of failure:` "Downgrade process failed because..."  `
and so on.
Thank you.

**Comment by Torchok19081986** [comment]
Morning, if you want to style exitdialog, dont know, only one way to use CustomUI and add your custom Dialog at end of installaion.  right click on project and if you use Visual Studio, add Custom Dialog. 
for Exitmessage also only custom UI way. Use CustomMessage. There is sample in Samples from @oleg-shilo.  Download Samples Folder. May be it will help.

**Comment by RachelXGanon** [comment]
@Torchok19081986
 in case of creating a custom dialog , should I create a a new custom dialog for each process(e.g custom dialog for install, custom dialog for uninstall etc.)?
and I'm not sure I understand you. To implement custom exit dialogs :
 or I'm using `custom dialog/create ui project/custom message`?

**Comment by RachelXGanon** [comment]
O.K, Thank you.
