### ISSUE TITLE
How prevents the MSI entry from appearing in Windows "Add/Remove Program"  

### ISSUE THREAD

**Issue by JorgelGtzGtz** [oleg-shilo/wixsharp#1074]
Hello, 

How prevents the MSI entry from appearing in Windows "Add/Remove Program", I don't found information about this I see only is possible add the property "ARPSYSTEMCOMPONENT " but I am not familiar with this.

I hope can help me with my problem

Thanks

**Comment by snechaev** [comment]
Are you using bootstrapper to install your msi or just use a raw msi?
