### ISSUE TITLE
Prevent taskbar icon from breaking after an update

### ISSUE THREAD

**Issue by NickeManarin** [oleg-shilo/wixsharp#1077]
If the user had the app's icon pinned to the taskbar when updating it, the pin breaks, turning into a white paper icon and if clicked it prompts the user to remove it.
The icon is moved to the "Tombstone" folder in the `Quick Launch\User Pinned\TaskBar` folder. 

Is there any way to prevent that from happening?

I read that it's possible to disable the action to remove the shortcuts: 
https://stackoverflow.com/questions/21241828/wix-do-not-remove-pinned-taskbar-on-install

**Comment by snechaev** [comment]
I can confirm that this approach works for me. 
I used following code in the `WixSourceGenerated` event handler

```
var installExecuteSequence = document.FindFirst("InstallExecuteSequence");
installExecuteSequence.AddFirst(new XElement("RemoveShortcuts", "REMOVE=\"ALL\" AND NOT UPGRADINGPRODUCTCODE"));
```

**Comment by NickeManarin** [comment]
The only issue is that pinned shortcuts are not removed once the app is uninstalled.
