### ISSUE TITLE
detect if upgrade succeed or not

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1078]
Hi !
I'm using` Major Upgrade `element to implement upgrade.
Just as in your example "major upgrade" and it works fine.
I have a special need that in case of a failed upgrade, the previous version must be installed and work seamlessly.
How can I detect that the `upgrade` succeed/failed and how can I make the previous version be installed?
Thanks.

**Comment by oleg-shilo** [comment]
> Do you think WixSharp/Wix implement a rollback to the previous version ?
I do not think so. It is in fact MSI (not even WiX) who is responsible for the upgrade implementation. And for the major upgrade scenario it uninstalls the prev version (version A) and then tries it install the new one (*version B). If the installation fails half ways through then it rolls back the installation of version B. But not the uninstall of version A.

**Comment by RachelXGanon** [comment]
But this is write in the documentation
https://wixtoolset.org/documentation/manual/v3/xsd/wix/majorupgrade.html 
in the Schedule
