### ISSUE TITLE
[ManagedUI] feature checkbox can be unchecked when allowChange is false

### ISSUE THREAD

**Issue by JeremyAnsel** [oleg-shilo/wixsharp#108]
Consider the following code:
```csharp
var binaries = new Feature("Binaries", isEnabled: true, allowChange: false);
var manual = new Feature("Manual");

var project = new ManagedProject("MyProduct",
    new Dir(@"%ProgramFiles%\My Company\My Product",
        new File(binaries, @"Files\Bin\MyApp.exe"),
        new File(manual, @"Files\Docs\Manual.txt")));

project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.ManagedUI = ManagedUI.Default;

project.BuildMsi();
```
It results to the follwing features tree:
![wixsharp_managedui_feature_chekbox](https://user-images.githubusercontent.com/9573196/28466173-cadc8028-6e2b-11e7-994e-7434b4f83c90.png)

Originally the checkbox for the binaries is checked. When I double click on it, the checkbox is unchecked (it should not since `allowChange` is false).
The Binaries feature is installed when the checkbox is checked or unchecked.

**Comment by oleg-shilo** [comment]
> the checkbox is unchecked (it should not since allowChange is false).

It is a difficult one. The current solution supposed to prevent checking:
```C#
treeView.BeforeCheck += treeView_BeforeCheck;
...

static void treeView_BeforeCheck(object sender, TreeViewCancelEventArgs e)
{
    if (e.Node.IsReadOnly())
    {
        e.Cancel = true;
    }
}
```

However TreeView control bypasses "checking" events on double-click and changes the state directly. This unfortunate `TreeNode` behavior/flaw makes it difficult to fix. To make things even worth double-clicking checkbox and the check box text triggers double-click events differently. Not sure if a true solution is feasible. Will look at it... 

> The Binaries feature is installed when the checkbox is checked or unchecked.

This is correct behavior as the true (unchangable) state is "checked"

**Comment by oleg-shilo** [comment]
Done. [ReadOnlyTreeNode.cs#L118-L129](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.UI/ManagedUI/Forms/ReadOnlyTreeNode.cs#L118-L129).

It works but... it's not elegant by any count...

**Comment by JeremyAnsel** [comment]
Thanks

An other solution might have been to derive the treeview control and override the message procedure to intercept the double-click event, like shown here:
https://stackoverflow.com/a/6130543

```csharp
public class NoClickTree : TreeView
{
    protected override void WndProc(ref Message m)
    {
        // Suppress WM_LBUTTONDBLCLK
        if (m.Msg == 0x203) { m.Result = IntPtr.Zero; }
        else base.WndProc(ref m);
    }              
};
```

**Comment by oleg-shilo** [comment]
Yes, I've seen this one. It seems to be even more extreme that scheduling ;)
And it also disables the default believer (toggling expanded state). It's all much easier with WPF...

**Comment by nicStrauss** [comment]
Hi Oleg,

We recently changed our mature C++ project's installer to WixSharp managed MSI, after 20 using InstallShield. (..currently using version 1.9.8.0)

One of the features used are:
Feature background = new Feature("Background", true, false);

The feature controls registry entries for multiple instance transforms, so must always run, and may not be deselected.

I see similar behaviour as reported here in that even though allowChange is false, you are still able to deselect it the feature tree, but with a few slight exceptions:
1. It can be deselected with a single click, and cannot be re-selected with single or double click.
2. If unselected it does not run (unlike reports above that it can)

Any suggestions?

Best regards,
Nic

**Comment by oleg-shilo** [comment]
Hi Nic,

I suggest you create your Visual Studio project form the CustomUI template.

![image](https://user-images.githubusercontent.com/16729806/58317098-72d08200-7e58-11e9-932d-4261ae2f5fba.png)

With this project type you will have the full source code of the "Feature Selection" dialog. And there you will be able to customize your enable+checked behavior without any limits.
