### ISSUE TITLE
Question: How to change UI /  Dialogsappearance in Custom UI

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1081]
Morning, i have question, how do i change appearance of forms / dialogs in MSI ? I use custom UI Template from Wixsharp and would like to change or create new appearance of my dialogs.  i found out, after build project to msi , wixsharp add wixsharp.dll as dialogs .  How do i add custom dialogs  ? AFAIK standard dialogs are Winforms project. Exists Interface like in Bootsrapper  as WPF project with IWPFDialog where i can add custom dialogs ?

**Comment by samuel-pl** [comment]
I've been using this https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Custom_UI

**Comment by oleg-shilo** [comment]
This one: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUI.WPF
is arguably a better one

**Comment by oleg-shilo** [comment]
If you are happy with working the winform based dialogs then just create the project form the "... - Custom UI" template and the all dialogs will be in your project with their source code

**Comment by Torchok19081986** [comment]
Morning, thanks for suggestions. I create new CustomUI Project from Custom UI template, BUT i cant add UI assembly from somewhere else.  I just want to improve UI in my Install Dialogsequence with custom UI control and make my installer with my colors and log etc. 
Link from @samuel-pl , isnt it for wix UI not CustomUI?

**Comment by oleg-shilo** [comment]
Then you need to add the dependency assembly (your custom control) to your setup.

TBH WiX is a bit clumsy with that so I would simply add your assembly to the resources and load/return it from the `AppDomain.Current.ResolveAssembly` handler. It's a simple but effective trick for deploying all dependency assemblies but without relying on MSI for that.
