### ISSUE TITLE
ProcessMessage in ProgressDialog 

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1082]
Hi Oleg,
May you can explain/have some documentation to this function? 
I'd like to understand this method.
Is in the class : `public partial class ProgressDialog : ManagedForm, IManagedDialog, IProgressDia
`
Haven't see any uses of this method, can it be removed?

**Comment by oleg-shilo** [comment]
Not sure I understand your intention.
What functionality/behaviour are you trying to achieve? 

As for this method, you can override it if you want to process MSI runtime messages. Otherwise, you can rely on the default implementation. Most likely it is what you want to do.

**Comment by RachelXGanon** [comment]
👍
