### ISSUE TITLE
shortcut inside startup menu inside folder.

### ISSUE THREAD

**Issue by saiprabhur** [oleg-shilo/wixsharp#1083]
Want to create short cut inside startup folder.
e..g %ProgramMenu%\Folder1\Folder\shortcut....

The below code i have used. its create shortcut under %programMenu%... not inside \Folder1\Folder... 
Could you help out how to create shortcut inside folder.

new Dir("INSTALLDIR",
  new Files(Path.Combine(BuildDir, "*.*")),
  new Dir(@"%Desktop%",
    new ExeFileShortcut(AppNameWithVersion, Path.Combine("[INSTALLDIR]", $"{BuildSettings.ApplicationName}.exe"), arguments: "") { WorkingDirectory = "[INSTALLDIR]" }),
  new Dir(@"%ProgramMenu%\Folder\Folder1",
    new ExeFileShortcut(AppNameWithVersion, Path.Combine("[INSTALLDIR]", $"{BuildSettings.ApplicationName}.exe"), arguments: "") { WorkingDirectory = "[INSTALLDIR]" }))

**Comment by snechaev** [comment]
Looks like the [sample](https://github.com/oleg-shilo/wixsharp/blob/40d48900092cec58055f417cdf4b10d3780a4a1e/Source/src/WixSharp.Samples/Wix%23%20Samples/Shortcuts%20(advertised)/setup.cs#L24) describes exactly your case. Did you tried this approach?
