### ISSUE TITLE
WixButton doesn't update despite control condition being true - not repainting screen

### ISSUE THREAD

**Issue by samuel-pl** [oleg-shilo/wixsharp#1084]
Hi,

I'm having an issue with an installation screen not updating it's buttons. I have disabled the next button by default.

These are the conditions I've set

`this.NextButton.Conditions.Add(new WixControlCondition { Action = ConditionAction.disable, Value = "NOT (ActivationCodeValid=\"TRUE\")" });`

`this.NextButton.Conditions.Add(new WixControlCondition { Action = ConditionAction.enable, Value = "ActivationCodeValid=\"TRUE\"" });`

While inside my custom action I have set ActivationCodeValid,

`session["ActivationCodeValid"] = "TRUE";`

If I click on any other text box on the screen and interact with it, the next button updates and I can click it. If I go to the previous screen and return to this installation screen, the next button is enabled.

I have tried calling Refresh and pausing + resuming the layout to no avail. How should I properly make the dialog repaint itself?

Thanks

**Comment by samuel-pl** [comment]
After some googling I think many people have had this exact problem in the past, even before WixSharp.

My solution was to add a condition onto the 'next' button while setting up my custom UI and add another DialogAction that would run if the condition was false, showing a message box.

**Comment by oleg-shilo** [comment]
And of course, if you hit the wall, you can always try managed UI instead. This way you will have complete control over your UI.

**Comment by samuel-pl** [comment]
I did actually try the Managed UI. It was very helpful as the previous UI does not have scope to what is happening on the UI, only the predefined properties which were bound one way from UI -> Property.

Now that I am using the Managed UI I can just access properties of my UI directly.

**Comment by oleg-shilo** [comment]
That was exactly the point of designing _Managed UI_ :)
Glad it helped you to solve the problem
