### ISSUE TITLE
Intermittent error

### ISSUE THREAD

**Issue by malicuss** [oleg-shilo/wixsharp#1087]
Aloha Oleg.

Past few days I was messing around one issue, but unfortunately was not able to solve it. So may be you can help me with it.
My actual problem is  that this code, :
```
            project.AfterInstall += e =>
            {
                if (e.IsUninstalling)
                {
                    CustomActions.CleanUp();
                }
            };
```
some times on some PCs  gives me this:

> SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIC835.tmp-\
> SFXCA: Binding to CLR version v4.0.30319
> Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
> WixSharp aborted the session because of the error:
> System.InvalidOperationException: Последовательность не содержит соответствующий элемент
>   в System.Linq.Enumerable.Single(IEnumerable`1 source, Func`2 predicate)
>   в WixSharp.ManagedProject.InvokeClientHandler(String info, SetupEventArgs eventArgs)
>   в WixSharp.ManagedProject.InvokeClientHandlers(Session session, String eventName, IShellView UIShell)
> CustomAction WixSharp_AfterInstall_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

even if CleanUp() is empty, and nothing happens inside. 

This issue does not depends on windows version or .net installed. It definitely appears more frequently on older versions of windows (like 1607). But also have several cases it appears on latest windows (1904) with .net 5 installed.

I hope you can help me, at least give me idea where to dig. Thanks.

**Comment by oleg-shilo** [comment]
Hi Kosta,

It is really strange problem.
The stack trace indicates that the exception is raised by the `Single()` call in `InvokeClientHandler` method.

However it never invokes any LINQ expression at all:

https://github.com/oleg-shilo/wixsharp/blob/61777afd40936ddcf5114edbea9ceb708a350da1/Source/src/WixSharp/ManagedProject/ManagedProject.cs#L522-L530

Strangely enough ` GetHandler(string info)` (one step deeper) has a few calls to `Single` and in fact there is a nasty typo there that potentially leads to the probing exception at runtime.

I have fixed it. The fix is published on GitHub and Nuget as a pre-release: 
```
Install-Package WixSharp.bin -Version 1.19.1-pre
```

**Comment by oleg-shilo** [comment]
Please let me know if it addressed the problem you are experiencing and I will make a full release

**Comment by malicuss** [comment]
Thanks !
Looks like this issue is fixed now, still another really strange one appears. Please take a look, cause I'm totally confused.

> SFXCA: Extracting embedded UI to temporary directory: C:\Users\38E2~1\AppData\Local\Temp\MSI13928
> SFXCA: Binding to CLR version v4.0.30319
> Cannot attach ManagedUI: System.IO.FileLoadException: Не удалось загрузить файл или сборку "WixSharp.UI, Version=1.19.1.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2" либо одну из их зависимостей. Найденное определение манифеста сборки не соответствует ссылке на сборку. (Исключение из HRESULT: 0x80131040)
> Имя файла: 'WixSharp.UI, Version=1.19.1.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2'
>    в System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    в System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    в System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    в System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
>    в System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
>    в System.Reflection.Assembly.Load(String assemblyString)
>    в WixSharp.ManagedProject.GetDialog(String info)
>    в WixSharp.ManagedProject.<>c.<ReadDialogs>b__36_2(String x)
>    в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    в System.Linq.Enumerable.ToList(IEnumerable`1 source)
>    в WixSharp.ManagedProject.ReadDialogs(String data)
>    в WixSharp.ManagedUI.ReadDialogs(Session session)
>    в WixSharp.ManagedUI.Initialize(Session session, String resourcePath, InstallUIOptions& uiLevel)

**Comment by oleg-shilo** [comment]
This is an assembly loading error that by default is reported by CLR this way. What it means that ManagedUI assembly was not able to load as some ot it's dependencies are missing. The most usual case is that your UI assembly is referencing other assembly (e.g. you added it to the project) that is not added to the msi.

Is it your case?

**Comment by malicuss** [comment]
No, looks like it's not my case. on some machines installation goes fine, on others this error appears. that's really frustrating.

**Comment by oleg-shilo** [comment]
Sorry for the delay. I did not have a good answer for you. Debugging on the target system would be the best approach but most likely you are aware of that.

Though when I though about your problem and looked at the trace stack again I realized that it is a custom dialog that is failing for you. But in this case you can use the usually overlooked feature of WixSharp that allows you to play-back/preview the dialogs without running the msi file.

You can update your project code with this:
```C#
 static public void Main(string[] args)
    {
        if (args.Contains("/test")) //for demo only
        {
            UIShell.Play(ManagedUI.Default.InstallDialogs);
            return;
        }
        . . .
```
You can still build your msi as you did before, but now you can take your project output executable, simply bring it on the misbehaving target system and run with the `/test` argument.
