### ISSUE TITLE
[ManagedUI] backgroup image dimensions

### ISSUE THREAD

**Issue by JeremyAnsel** [oleg-shilo/wixsharp#109]
The exception thrown when the backgroup image ratio is invalid is not helpfull.

`ProjectValidator` suggests a size of 492x312 which throws a `ValidationException`. The exception is thrown when width > height:
https://github.com/oleg-shilo/wixsharp/blob/a248dd643c009cada90ac3832f0ed42c84934f31/Source/src/WixSharp/ProjectValidator.cs#L98-L119

It is suggested to use a size of 156x312 or 164x497:
https://github.com/oleg-shilo/wixsharp/blob/c766ea466fe7cfa62eb7df97b8e1f5d44609ed9c/Source/src/WixSharp.UI/ManagedUI/Forms/WelcomeDialog.scaling.cs#L50-L51

It would be better if the validation exception indicates the size to use.

**Comment by oleg-shilo** [comment]
Done. 

The error message indeed needed the change. Thank you for that. 

Please note that "WelcomeDialog.scaling.cs#L50-L51" reference is not an active code but a non-compilable records of the experiments with MSI UI. 

The actual most accurate ratio is dictated by the runtime size of the PictureBox of the `WelcomeDialog` that can be observed in the WinForm designer.

**Comment by JeremyAnsel** [comment]
Thanks
