### ISSUE TITLE
LaunchCondition Example

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1093]
Hi Oleg,
I was looking at your [sample](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/FeatureConditions/setup.cs) 

`        project.LaunchConditions.Add(new LaunchCondition("PROP1 or Installed", "PROP1 is required"));
`
Can you explain why PROP1 is required? For which of the following project 5 Features it is?
Will I get this PROP1 only in case of the software installed?
Tnx

**Comment by snechaev** [comment]
Here is some explanation

https://github.com/oleg-shilo/wixsharp/blob/9423ad2d4e00fdfa23fd675de0f0fa9a4b447297/Source/src/WixSharp.Samples/Wix%23%20Samples/FeatureConditions/setup.cs#L11-L23

So, "PROP1 is required" is just a human-readable message to show in case if condition is not met.

**Comment by RachelXGanon** [comment]
@snechaev Thanks for your replay!
Can you specify which of the features is it?
btw - I have a condition I have to check only in case if install. Does  `"or Installed"` make the condition occur only at install scenario?
Thanks
