### ISSUE TITLE
How to set installation variables computed inside custom action

### ISSUE THREAD

**Issue by Puchaczov** [oleg-shilo/wixsharp#1094]
I have two custom actions that must compute some values (elevated execution) and use it. I would like to be able to pass those datas to another one custom action.

So basically:

```

  var elevatedDetermineVariables = new ElevatedManagedAction(CustomActions.BeforeFilesInstallation, Return.check,
      When.Before, Step.InstallFiles, Condition.Always)
  {
  };

  var elevatedInstallService = new ElevatedManagedAction(CustomActions.AfterFilesInstalled, Return.check,
      When.After, Step.InstallFiles, Condition.NOT_Installed)
  {
  };
```

and custom actions:

```
    public static class CustomActions
    {
        [CustomAction]
        public static ActionResult BeforeFilesInstallation(Session session){
            //value "test" is taken from "registry" <- local machine so I need to be elevated
            session.CustomActionData["SOME_VARIABLE"] =GetValueFromRegistry();
        }
        [CustomAction]
        public static ActionResult AfterFilesInstalled(Session session){
            session.Property("SOME_VARIABLE")
        }
     }
```

I can't get it how to do it, is there any sample that shows how to achieve it?

**Comment by oleg-shilo** [comment]
You may not like the answer. :)
I would advice not to pass data between custom actions. Have only one action and then you don't need to pass anything.

```C#
project.AfterInstall += args =>
{
    if (!args.IsUninstalling)
    {
        // you are elevated here
    }
};
```

But I understand that sometimes you need to.
So... I am not sure elevated cations push data back to the session. they might be read-only creatures.
Also, a though... I would expect that you do not need to be elevated if you only read the registry

**Comment by xmarshal** [comment]
I suggest using a registry (or something similar e.g. file in temp) for this kind of exchange.
And why you cant read registry from second action?
