### ISSUE TITLE
WixSharp not generate .wxs file

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1095]
Hi, the file: Wix/Installer.g.wxs kepts empty
`<!-- not generated yet -->`
How can I view the page?

**Comment by oleg-shilo** [comment]
I suggest you create your VS project from one of the WixSharp project templates. This will warranty the correct creation of the  wxs file.

**Comment by RachelXGanon** [comment]
I created the project via vs 19. `Managed - Custom UI`
