### ISSUE TITLE
Setting RegistrySearch Id causes infinite loop

### ISSUE THREAD

**Issue by austinw-fineart** [oleg-shilo/wixsharp#1096]
The RegistrySearch Id setter sets itself, thus causing an infinite loop:
https://github.com/oleg-shilo/wixsharp/blob/d809ad85510a84849ee0ab0a249d375077c64ef5/Source/src/WixSharp/RegistrySearch.cs#L61

**Comment by oleg-shilo** [comment]
Yes it is a bug :(
A very nasty typo. 
Thank you for reporting.

Fixed

Until the fix is published please use base class to set the property.

**Comment by austinw-fineart** [comment]
Well I found another one traversing base classes 😅
https://github.com/oleg-shilo/wixsharp/blob/d809ad85510a84849ee0ab0a249d375077c64ef5/Source/src/WixSharp/GenericEntity.cs#L93

**Comment by oleg-shilo** [comment]
Oh my. And Source/src/WixSharp/FileSearch.cs
And some more

**Comment by oleg-shilo** [comment]
Done. Another two:
![image](https://user-images.githubusercontent.com/16729806/144746286-a75a7d4c-6dd0-4d37-9999-57af613dd0e4.png)

May I ask you a favor? Can you please check again. I did a global search but another pair of eyes would not hurt.

Txs

**Comment by austinw-fineart** [comment]
Yes I do believe that's all of the recursive setters I could find 👍
