### ISSUE TITLE
Run upgrade in is cmd not working

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1098]
Hey Oleg,
I implemented the `MajorUpgrade` element,
when I want to run the upgrade via the command  line,
I have to to run the msi of the higher version with `/i `.(e.g msiexec /i <path_to_higher_msi>)
`/u` does nothing. (e.g does show no error/ no message at the event viewer and not install/upgrade)
How can I have it work?
P.S
If I change the version locally(e.g build a project version x and then change the version to y, it works.)
The bug starts as I produces two  releases from the pipeline..

May it a bug with the product code?
I have the dame `GUID` in both.
Tnx.

**Comment by RachelXGanon** [comment]
?

**Comment by RachelXGanon** [comment]
@oleg-shilo

```
 P.S
If I change the version locally(e.g build a project version x and then change the version to y, it works.)
The bug starts as I produces two releases from the pipeline..
```
I also does not work. Created a new project as this [sample](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/MajorUpgrade)
I have two small questions:

- Is the upgrade working only via `/i` parameter?
- Is it a wix issue or WixSharp issue?

Your answer will be highly appreciated!
Tnx.

**Comment by RachelXGanon** [comment]
Ok 
I got my problem:) 
There's a `/update` parameter on *.msp files not on on *.msi files.
Is it possible to WixSharp to create a *.msp files?
Tnx.

**Comment by oleg-shilo** [comment]
No, it's not possible. WixSharp deliberately supports only MajorUpgrade MSI model. Minor updates and patches are by many considered as a deployment anti-pattern (even though supported by MSI) so there is no support for that in WixSharp.

**Comment by RachelXGanon** [comment]
Thanks.
