### ISSUE TITLE
Is there any way to dynamically set the name of shortcut?

### ISSUE THREAD

**Issue by Dimazavrus** [oleg-shilo/wixsharp#1099]
Hello!
Is there any way to dynamically set the name of shortcut?
For example
...
new Dir( @"%Desktop%",
          new ExeFileShortcut( install_app, "[SHORTCUT_NAME]", "[DIRTOINSTALL]app.exe", "" ) { Condition = new Condition( "NEEDINSTALL=\"1\"" ), IconIndex = 0 }

**Comment by oleg-shilo** [comment]
It completely depends if WiX supports dynamic values in the attribute of the corresponding XML element.
Which I simply do not know. But WiX documentation will have the answer.

Check the generate wxs and you will see which element/attribute you are trying to set dynamically
