### ISSUE TITLE
Check for .NET462

### ISSUE THREAD

**Issue by Christobal25** [oleg-shilo/wixsharp#11]
Hey,
when I wan´t to check if .NET462 is installed it is not possible.

`project.SetNetFxPrerequisite("NETFRAMEWORK462='#1'", "Please install .NET 4.6.2 first");`

this throws an Exception 

> error LGHT0094: Unresolved reference to symbol 'Property:NETFRAMEWORK462'

WixToolset v.3.11+ is installed

Thanks Christobal25

**Comment by oleg-shilo** [comment]
I am guessing that this property is not a pat of WiXNetFxExtension. This is the fragment of the Wix# XML documentation:
```
Binds the LaunchCondition to the version condition based on WiXNetFxExtension properties. 
The typical conditions are:
NETFRAMEWORK20='#1'
NETFRAMEWORK40FULL='#1'
NETFRAMEWORK35='#1'
NETFRAMEWORK30_SP_LEVEL and NOT NETFRAMEWORK30_SP_LEVEL='#0'
...
The full list of names and values can be found here http://wixtoolset.org/documentation/manual/v3/customactions/wixnetfxextension.html 
```
If you indeed want to use the property with that name you will need either to create and initialize it by yourself or include the extension that does it for you. 

A very quick look to the link from the doc reviled that `WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED` might be what you need. But you will need to test it...

**Comment by Christobal25** [comment]
Hey,
thanks for the fast answer.

**Comment by mbinic** [comment]
Sorry for replying to a closed question, but just so you're aware: now you can use the new Conditions for this instead, e.g. `Condition.Net462_Installed`.
