### ISSUE TITLE
RunAppAtTheEnd

### ISSUE THREAD

**Issue by Dimazavrus** [oleg-shilo/wixsharp#110]
Hello.
I'm trying to run the application at the end of the installation (like RunAppAtTheEnd example), but at this moment installation folder does not yet exist.
```
Project proj = new Project( ... , new ManagedAction( "RunApp" ) );

public static ActionResult RunApp( Session session )
{
   string path = System.IO.Path.Combine( session["INSTALLDIR"], "MyApp.exe" );

   if( !System.IO.Directory.Exists( session["INSTALLDIR"] ) )
      session.Log( session["INSTALLDIR"] + " not found" );
}
```
Why? How to run app at the end installation?

**Comment by oleg-shilo** [comment]
Most likely your manged custom action is scheduled for "too early" execution. 
Though instead of fixing it I would recommend to use Managed project and hookup for the `AfterInstall` event. Another advantage is that inside of the event handler you will be in the elevated execution context.

```C#
var project = new ManagedProject("ManagedSetup"...
project.AfterInstall += project_AfterInstall;
...
static void project_AfterInstall(SetupEventArgs e)
{
    ...
}
```

**Comment by Dimazavrus** [comment]
Its works, but I need access to session parameters to pass an argument to the application:

```
static void AfterInstall( SetupEventArgs e )
{
  string path = IO.Path.Combine( e.InstallDir, "MyApp.exe" );
  System.Diagnostics.Process.Start( path, "myparam:" + e.Session["MYPARAM"] );
}
```
I start the setup this way: MyAppSetup.msi myparam=xxx
This leads to error: Cannot access session details from a non-immediate custom action.

**Comment by oleg-shilo** [comment]
This is a well known limitation (design flaw actually) of MSI. The deferred actions are the only MSI way to execute anything elevated after the installation. However when a deferred action is invoked the MSI session is already closed. Thus none of it's properties can be accessed. Good reading: https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model.

The only way out is to push the MSI property in question into the `CustomActionData` and access it with the `Property(...)` extension method: 

```C#
project.DefaultDeferredProperties += ",MY_PROP";
...
string my_prop = session.Property("MY_PROP");
```
Though if you are using ManagedProject then you can save ANY data into the global Wix# property bag:
```C#
static void project_Load(SetupEventArgs e)
{
    e.Data["my_prop"] = "<something>";
}

static void project_AfterInstall(SetupEventArgs e)
{
    var my_prop = e.Data["my_prop"];
}
```
Have a look at "Setup Events" sample. It deals with the challenges as yours.

**Comment by Dimazavrus** [comment]
Good solution, thank you very much for your help!

**Comment by oleg-shilo** [comment]
You are welcome :)
I am closing this issue. You can still reopen it if required.
