### ISSUE TITLE
Bug At Uninstall

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1102]
Hey, 
I have a severe bug I tried to debug for hours, any help will be highly appreciated :) 
I have service that writes logs to folder C:\ProgramData\MyCompany\MyProduct
at uninstall I delete this folder, the uninstall  failed.
In the message box it show the right path.
here's my code:
```
        public void OnAfterInstall(SetupEventArgs e)
        {
            if (e.IsUninstalling)
            {
                var programData = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);
                var myFolder =  @"MyComany\MyProduct";
                var logsFolderPath = $"\"{programData}\\{myFolder}\"";
                MessageBox.Show($"logs folder path: {logsFolderPath}");

                DirectoryInfo logsFolder = new DirectoryInfo(logsFolderPath);
               
                MessageBox.Show($"show if exist: {logsFolder?.Exists}");

                if ((bool)(logsFolder?.Exists))
                {
                    logsFolder?.Delete(true);
                }
            }
```

**Comment by Torchok19081986** [comment]
Morning,  which value shows messagebox in logsFolderPath ? try to Path.Combine programData with myfolder to string path. 
I dont know much about new extesion in WixSharp, but you can also try DeleteIfExists Extension Method in WixSharp.

**Comment by RachelXGanon** [comment]
Hey, that's work for me
```
                var programData = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);
                var path = $@"{programData}\My Compant\My Produt";
                DirectoryInfo logsFolder = new DirectoryInfo(path);
```


Thanks, :)

**Comment by RachelXGanon** [comment]
Hi,
Seems like is way more severe that I thought.
While running with verbose logging it shows error:
`System.IO.IOException: The process cannot access the file 'Log.log' because it is being used by another process.`
Is there a way to have schedule the timing so first the service will stop and then it will delete the logs folder?
I'm on this for few days now, so a very big Thank to anyone trying to help!

**Comment by oleg-shilo** [comment]
You can just stop the service from your custom action before deleting it.
Though you might need to be an admin so `AfterInstall` is your friend

**Comment by RachelXGanon** [comment]
Do you what's the order of those things in wixsharp?
like does the mechanism stops the service before the after_install action?

**Comment by oleg-shilo** [comment]
There is no "order of this things" in WixSharp. 

The problem is that MSi is supposed to stop the service on uninstall, not WiX and not WixSharp this should release the log file and you should be able to delete it. Why it is not happening in your case... have no idea. May be there is something that prevents service from being stopped?

**Comment by RachelXGanon** [comment]
_There is no "order of this things" in WixSharp._
I guess my bug starts and ends at this sentence...
I did investigating a lot on the order those things to vain..
_May be there is something that prevents service from being stopped?_
So yeah, I'm going to check this,
Thank you👍
