### ISSUE TITLE
The type or namespace name 'WixSharp' could not be found

### ISSUE THREAD

**Issue by iovispot** [oleg-shilo/wixsharp#1105]
Extending #1076 

By the way, creating a new project from one of the templates does not automatically include the nuget package. That is also visible from the error directive which warns the user to do so first and remove the directive.

The issue is, upon installing the NuGet package, the IDE recognizes and highlights them properly with code highlighting. No errors appear, until I actually run the project. Everywhere WixSharp classes are being referenced from is the same error and I can't get it running no matter what. I've cleaned, rebuilt the project, reinstalled the nuget packages and even restarted my VS2022 and computer.

**Comment by oleg-shilo** [comment]
> templates does not automatically include the nuget package.
Correct, on VS2019 and early I could not get it restored correctly as in this case, it requires importing `targets`. I tried, but after spending long hours I had to opt to the manual add.

> he same error and I can't get it running no matter what.
I think it is due fact that VS2022 effectively abandoned the packages.config approach and insists on adding packages through the project references. This is quite opposite to VS2019. Thus VS2019 will most likely work for you

I will be rebuilding the templates for VS2022 and will see if now it can be properly addressed.


In a meantime you can simply create a console app application and import WixSharp.bin package. Then in the add the post-build event as it is described here: https://github.com/oleg-shilo/wixsharp/wiki/VS2013-%E2%80%93-2015-Templates#msi-authoring-steps

**Comment by oleg-shilo** [comment]
This is an empty project that you can use as your own template template. It can run in VS2022
[WixSharpSetup1.zip](https://github.com/oleg-shilo/wixsharp/files/7797177/WixSharpSetup1.zip)

My very first experiment showed the new VS2022 project/nuget model works really well for restoring packages but automatic update of build targets is still a question as I am not sure it is supported in VS2022. If I am right ant it is not then the only way to build an msi as part of the project build is to execute the exe is to execute it in the post-build event as I described in the prev post and as it is done in the attaahched project

**Comment by silvitin** [comment]
Alright, very nice! Just, please tell me what the post-build event does and what am I supposed to put in there? The "../.." part is an unrecognized command.

**Comment by oleg-shilo** [comment]
The attached "WixSharpSetup1.min.zip" already has post-build event populated for you. You are expected to put VS macro TargetPath.

However, I have also attached "WixSharpSetup1.zip", which even has all packages added as it would do with the VS2022 project templates available. So you can simply make a copy of this project and customize the content for your needs.

Alternatively, you can even export "WixSharpSetup1.zip" as a VS2022 template after opening it in VS2022. This way you don't have to wait till I update and publish templates. Thus you can start using your own template locally right away.

**Comment by silvitin** [comment]
Hi. Sorry for replying so late, had a very busy week. Thanks for the template, much appreciated! So far, the project covers all my needs for an installation application. Very nice work on WixSharp!

**Comment by oleg-shilo** [comment]
The new templates have been released just yesterday.
so you can start using them

**Comment by silvitin** [comment]
Already on it. Looking good. :)

**Comment by alicexudoosan** [comment]
I experience same situation after upgrade the framework to dotnet 6.0. Is wixsharp compatible with dotnet 6.0? Thank you very much :)

**Comment by oleg-shilo** [comment]
No, currently it is compatible with .NET Framework only.

WiX4 seems to support .NET Core family, but cannot find any example. Thus I cannot do much about this until WiX team provides some guidance on that. So far I only found a simple on the BA but not on CA.
