### ISSUE TITLE
How to disable sensitivity to fourth octet of product version

### ISSUE THREAD

**Issue by xmarshal** [oleg-shilo/wixsharp#1106]
I am using immutable UpgradeCode and ProductCode and MajorUpgrade.Default
I want version 1.1.1.2 not to update version 1.1.1.1

**Comment by oleg-shilo** [comment]
As far as I know, it is an MSI limitation. It does not recognize the fourth version component as an upgrade trigger and considers `1.1.1.1` and `1.1.1.2` as the same versions. 

Though it does recognise UpgradeCode and ProductCode derived by WixSharp from the version text as different. But... this does not solve your problem. 

I cannot exclude that there is some exotic MSI/WiX trick that you can use but it is expected not to work out of the box. MSI is a very old technology :(

**Comment by xmarshal** [comment]
Напишу пока по русски)
Возможно я не правильно выразился. 
В моем случае версия с более высоким четвертым октетом обновляет версию, не сморя на то что mai воспринимает их как одну и туже.

**Comment by oleg-shilo** [comment]
Sorry, then I am puzzled :)
Usually, users ask how to achieve that behaviour but not how to avoid it 😄 

Nevertheless, the answer stands. The best chance to customize the upgrading algorithm is via WiX customization. Of course, WixSharp will then need to provision that customization, which is usually not a problem.  But finding the magic XML customisation is out of my depth.
