### ISSUE TITLE
Documentation update request

### ISSUE THREAD

**Issue by seraphire** [oleg-shilo/wixsharp#1107]
I just installed WixSharp (Awesome project btw!) and I noted 2 issues on the [**Building MSI - Step by step tutorial page**](https://github.com/oleg-shilo/wixsharp/wiki/Building-MSI-%E2%80%93-Step-by-step-tutorial) as of 4-Jan-2022

Under Building with Visual Studio:

- This appears to be an update:  When  using a WixSharp template, it already had the project set for .NET Framework 4.0, but it appears that the Framework has been changed to 4.5.1

- Additionally, at least for the Templates, (I'm not sure about a blank project) the source file should not be changed form _Program.cs_ to _Setup.cs_

I hope this helps!

**Comment by oleg-shilo** [comment]
Thank you Ben, 

I am going to rerelease all templates for VS2022 so will update them and the documentation.

**Comment by oleg-shilo** [comment]
Done.

> Program.cs to Setup.cs
I am not sure about this one. Maybe it was the case in the old templates but I just tested it with the latest one and it uses program.cs. I have also updated the sample on wiki.
![image](https://user-images.githubusercontent.com/16729806/149623685-21848f40-e823-4bec-86c8-4f48d6d9136d.png)

**Comment by seraphire** [comment]
Great @oleg-shilo , thank you!
