### ISSUE TITLE
Best way to debug in Visual Studio an Embedded UI

### ISSUE THREAD

**Issue by marcobeninca71** [oleg-shilo/wixsharp#1109]
Hello Oleg
I'm writing a custom UI starting from the example EmbeddedUI_WPF. I'd like to debug my code because it's no trivial (and it throws an exception somewhere) but with no success. I tried to compile in debug and put a

`MessageBox.Show("Stop here");`

Then run the msi package and when the message box appears I tried to attach the debugger to the msiexec.exe process but the debug information are not loaded, so my breakpoint is never hitted.
Do you have any suggestion?
Best regards
Marco

**Comment by oleg-shilo** [comment]
Hi Marco,

You must run your debugger (VS) elevated. Then it will have access to the debug info.

I also prefer to use `Debug.Assert(false);` and then select the elevated debugger from the "select debugger" dialog.

But Assert based debugging sometimes fails to attach.
Try both ways. but it is important that the debugger is elevated

**Comment by marcobeninca71** [comment]
Hi Oleg
thanks for the quick reply. I tried but I faced another issue: the debugger is not able to load the debug symbols for the running assembly. Please see the picture below

![image](https://user-images.githubusercontent.com/25340312/149726067-4bf8f728-58b3-47c1-92d8-013bff89f820.png)

How can I make the debugger to load the correct debug info?
Marco

**Comment by oleg-shilo** [comment]
If you tried to select debugger from the assertion box it may not find symbols. I observed it sometimes.

The only technique that works for me reliably is:
- put the assertion
- start setup
- start VS in elevated mode
- When assertion pops, use VS->Debug->"Attach to process" to attach to the msiexec.exe (there might be a few active).
- Place breakpoint after the assertion and resume running from the assertion dialog.

Yep, that convoluted :(
