### ISSUE TITLE
Display attribute & Reset link doesn't work in FeaturesDialog window

### ISSUE THREAD

**Issue by lord2kim** [oleg-shilo/wixsharp#111]
Hi, Oleg. 
In first thank you very much for this framework. Very simple way for create installer every case for new build. 

Question is follow. 

When I use WixUI_FeatureTree for UI additional attribute Display working ok. The follow C# code create expanded default tree on appropriate window.

```C#
var app = new Feature("Application") { Name = "Application",
                                       Description = "Application",
                                       Attributes = new Dictionary<String, String>() {
						{ "Display", "expand" } 
				       }
				     };
var driver = new Feature("Driver") { Name = "Driver",
                                     Description = "Driver" };
app.Add(driver);

...

project.UI = WUI.WixUI_FeatureTree;
```
As we can see by screen below, default feature tree is expand: 
![Image](http://i93.fastpic.ru/big/2017/0730/af/b23bd7eb0c1edf458e50c97f29d7e1af.png)

But if I will use WixSharp.UI.Forms.FeaturesDialog window this attribute doesn't work and in any case custom tree doesn't expanded on UI by default.

```C#
var app = new Feature("Application") { Name = "Application",
                                       Description = "Application",
                                       Attributes = new Dictionary<String, String>() {
						{ "Display", "expand" } 
				       }
				     };
var driver = new Feature("Driver") { Name = "Driver",
                                     Description = "Driver" };
app.Add(driver);

...

project.ManagedUI = new ManagedUI();
project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                .Add<LicenceDialog>()
                                .Add<InstallDirDialog>()
                                .Add<FeaturesDialog>()
                                .Add<ProgressDialog>()
                                .Add<ExitDialog>();
```

As we can see by screen below, custom feature tree is not expand (collapse): 
![Image](http://i94.fastpic.ru/big/2017/0730/cf/c8544668c46ce61d5fed9f61f4f0c6cf.png)

This "feature" doesn't work in custom FeaturesDialog window ? Or has another way for using it ? 
If this is doesn't work does it possible for fix it ? :)

Also looks like "Reset" link in this FeaturesDialog doesn't work too.

**Comment by oleg-shilo** [comment]
Thank you for reporting the issue.
Currently 'display' attribute is not processed in the FeaturesDialog. I have extended the solution to handle it an in the future releases the feature tree will reflect the 'Display' attribute value.

A dedicated `Feature.Display` member has been added to assist with the syntax:
```C#
var docs = new Feature("Documentation", "Product documentation (manuals and user guides)", true) 
{ 
    Display = FeatureDisplay.expand 
};
```
As for "Reset", I am not sure the I have enough information. It seems to work, at least for the sample from the distro:
![wix _support](https://user-images.githubusercontent.com/16729806/28855499-72962bae-7780-11e7-8838-f65eae893a16.gif)

---

And on completely unrelated topic... Just sharing some tips...

You can add attributeds to the `WixEntity` in a more elegant way:
```C#
var app = new Feature("Application") 
{ 
    Name = "Application",
    Description = "Application",
    AttributesDefinition = "Display=expand; AnotherAttribute=777" 
};
```
You don't need to host your images somewhere else. You can just add them to GitHub wiki by doping the image file directly in the post's text or even pasting it from the clipboard.

**Comment by oleg-shilo** [comment]
The latest NuGet package contains the fix.

**Comment by lord2kim** [comment]
Hi, Oleg.

Thank you very much. Looks like it's working with latest update of WIx#.

Thank you for tips...yes, this is better & elegant.

About "Reset" link...hm, strange, in previous Wix# ver this is doesn't work, but with latest update is is work correctly.

**Comment by oleg-shilo** [comment]
OK then. I'll be closing this issue.
