### ISSUE TITLE
MSI OverwriteOnInstal

### ISSUE THREAD

**Issue by Chani6935** [oleg-shilo/wixsharp#1112]
Hey,
I created two MSI files in different versions
I run the first MSI and then run the second MSI and the files are indeed replaced, but once I try to run the first MSI again the files are no longer replaced
Would appreciate help
Thanks

This is my code:

`                _items = new List<WixEntity>();
                _items.AddRange(new List<WixEntity>(Array.ConvertAll(System.IO.Directory.GetFiles(_rootFolderName), new Converter<string, File>(fileName => new File(fileName)))));
                _items.AddRange(new List<WixEntity>(Array.ConvertAll(System.IO.Directory.GetDirectories(_rootFolderName), new Converter<string, Dir>(folderName => new Dir(folderName)))));

                ManagedProject project = new ManagedProject(msiFileName, // Msi file name                    
                    new Dir(pathFolder, // The path of the folder to which the files will be copied
                      _items.ToArray() // The folders or files we want to copy                  
                      ));                

                project.Version = new Version(projectVersion);

                project.AllFiles.ForEach<File>((f) => f.OverwriteOnInstall = true);

                project.GenerateProductGuids();
                project.Id = Project.CalculateProductId(project.GUID.Value, project.Version).ToString();

                

                project.ManagedUI = new ManagedUI();

                //project.ManagedUI.Icon = @"Images\Logo.jpeg";

                project.ManagedUI.InstallDialogs
                    .Add(Dialogs.Welcome)
                    .Add(Dialogs.InstallDir)
                    .Add(Dialogs.Progress)                    
                    .Add(Dialogs.Exit);

                project.ManagedUI.ModifyDialogs
                    .Add(Dialogs.Welcome)
                    .Add(Dialogs.InstallDir)                    
                    .Add(Dialogs.Progress)                    
                    .Add(Dialogs.Exit);

                string result = Compiler.BuildMsi(project); // Returns: Path to the built MSI file. Returns null if MSI cannot be built.
                if (result == null)
                {
                    MessageBox.Show("MSI cannot be built", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
                else
                {
                    MessageBox.Show("MSI file location : \n" + result, "Information", MessageBoxButton.OK, MessageBoxImage.Information);
                }`

**Comment by oleg-shilo** [comment]
I suggest you carefully check if after installing the second msi you have two entries in the "add/remove programs".

It is an MSI question and it is closely related to the subject of msi identity (covered on wiki).

BTW I also suggest you consider replacing your `project.id` assignment with a definitive product identity assignment via GUID. Something like this:
```c#
project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
```

In this case, you have a warrantee that an msi with a higher version can upgrade the one with a lower version.
