### ISSUE TITLE
How to create a registry key with WixSharp?

### ISSUE THREAD

**Issue by gvsoft3750** [oleg-shilo/wixsharp#1113]
I am brand new to WixSharp.  I've only been using it for a couple of days, so I am definitely a newbie, and almost certainly missing lots of information that comes with experience.  I am using Visual Studio 2019 on Windows 10 Pro.

I am attempting to create a registry key with my WixSharp program.  First, I tried to create it with an elevated custom action (ElevatedManagedAction).  When that didn't work, I tried creating it in an "after install" method (project.AfterInstall += method).  But I get the same error either way.  I can create the registry key using the same code in a test app, but it refuses to work in the MSI.  I suspected permissions, but when it didn't work in the AfterInstall step too, I began to question my theory.

The error is "Registry key name must start with a valid base key name" which doesn't make any sense to me.  Granted, I have never used the Registry functions in C# before, but I am familiar with the Windows API methods and similar functions in VCL (C++Builder).

So, what am I doing wrong?  Here is what I have tried:

```
Registry.LocalMachine.CreateSubKey("SOFTWARE\\MyCompany\\MyProduct\\MyApp", true, RegistryOptions.None);
```

and also:

```
var HKLMSoftware = Registry.LocalMachine.OpenSubKey("SOFTWARE", RegistryKeyPermissionCheck.ReadWriteSubTree, RegistryRights.FullControl);
var key = HKLMSoftware.CreateSubKey("MyCompany\\MyProduct\\MyApp", RegistryKeyPermissionCheck.ReadWriteSubTree, RegistryOptions.None);
```

But I always get the same exception.

Thank you,

Dennis

**Comment by gvsoft3750** [comment]
I have worked out a solution that gives me the final result I was looking for.  Prior to trying the methods that failed, I had attempted to use ```new RegValue```, but I couldn't figure out how to give it the value I wanted.  I have since found an example that helped, and this works:

```
new ManagedProject(
    new RegValue(new Id("INSTALLDIR"),
        RegistryHive.LocalMachine,
        "SOFTWARE\\MyCompany\\MyProduct\\MyApp",
        "InstallPath",
        new Id("INSTALLDIR").Value)
)
```

I would still like to know what I was doing wrong in my other attempts, though, in case anyone has any ideas or suggestions.

Thanks,

Dennis

**Comment by gvsoft3750** [comment]
I solved my problem with RegValue.  I needed to use "[INSTALLDIR]" for the value (not new Id("INSTALLDIR").Value):

```
new ManagedProject(
    new RegValue(new Id("INSTALLDIR"),
        RegistryHive.LocalMachine,
        "SOFTWARE\\MyCompany\\MyProduct\\MyApp",
        "InstallPath",
        "[INSTALLDIR]")
)
```

Dennis

**Comment by oleg-shilo** [comment]
Great. Thank.s for sharing the solution
