### ISSUE TITLE
INSTALLDIR folder is not removed on uninstall

### ISSUE THREAD

**Issue by gvsoft3750** [oleg-shilo/wixsharp#1114]
I seem to have discovered a case where the installation folder will not get removed upon uninstalling.  This case seems to be the result of creating a sub-directory(ies) under the main directory, like this:

```
new ManagedProject("MyProductSetup",
                   new Dir(@"%ProgramFiles%\MyCompany\MyProduct\MyApp",
                           new Dir(@"Logs") // after adding this, the install folder will NOT be removed at uninstall
                   )
);
```

Interestingly, the "Logs" folder is removed, but none of its parent folders are removed.

How do I fix this?

Thanks,

Dennis

**Comment by oleg-shilo** [comment]
I just tested your scenario and even put a test case for it (https://github.com/oleg-shilo/wixsharp/commit/c79c9cd0d392ffa91e3a22ecae77aace85e1e8a4). The whole directory is getting removed on uninstall.

I have attached the msi and wxs (the whole build dir is also there)
[test.zip](https://github.com/oleg-shilo/wixsharp/files/7993919/test.zip)

**Comment by gvsoft3750** [comment]
Thank you for looking into it, Oleg.  There must be something else about my setup that is causing the problem.  I know nothing about MSI or WiX.  Any suggestions for how to identify what causes folders to not get removed?

Dennis

**Comment by oleg-shilo** [comment]
The problem itself is an MSI chellende. WixSharp (and WiX for that matter) plays a little role in it.

WixSharp only ensures that the corresponding `RemoveFolder` element is inserted for the directory you are asking:
![image](https://user-images.githubusercontent.com/16729806/152512803-e4b28571-67b5-4bef-9d94-7d66f2134159.png)

But it is MSI runtame , which is responsible for actual deletion of the folder. And it does it at least in the test I have done and shared with you. 

Did you try to run msi I shared with you?

. . .

Anyway, the usual reasons for the folder not being removed is that it contains files that were not put there by the msi that created the folder. The name of your folder (`logs`) suggests that indeed you are planing your app to create log files there. Big no-no :)

Another reason is another install that creates the folder with the same name. Not sure your case

**Comment by gvsoft3750** [comment]
Well, in my case, it isn't because there are existing files (because I am just testing the install/uninstall process).  I did see the expected behavior when my project was smaller (folders would delete, except when there were existing files).  But somewhere along the line, that behavior changed.  There is no other folder with the same name either.

Here is what my actual wxs looks like:

![image](https://user-images.githubusercontent.com/98843223/152543625-5ab95351-e24c-46f3-9e86-78edf35d6436.png)

I don't think the PermissionEx entry is related, because when I remove the ```DirPermission``` property from my code, the problem still occurs.

I will keep investigating and report anything new I find.

Dennis

**Comment by oleg-shilo** [comment]
Good luck Denis
