### ISSUE TITLE
Running msiexec with /quiet does not install the product

### ISSUE THREAD

**Issue by gvsoft3750** [oleg-shilo/wixsharp#1115]
I have a working MSI that installs/uninstalls my program fine.  I can install it with:

msiexec /i myproduct.msi
and
msiexec /i myproduct.msi /passive

But if I try to install with /quiet, like this:
msiexec /i myproduct.msi /quiet

The product is NOT installed.  I checked the log and it says I didn't have permission.  Okay.  So to solve that, I added the /a switch:

msiexec /a myproduct.msi /quiet

Afterward, there is almost nothing in the log, and yet it says it installed (even though it didn't).  Then I tried:

msiexec /a myproduct.msi /passive

That gave an odd error:

DEBUG: Error 2911:  Could not remove the folder E:\Config.Msi\.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2911. The arguments are: E:\Config.Msi\, , 

How do I correctly configure WixSharp to create an installer that can install quietly, and also give it automatic administrative permission?

Dennis

**Comment by oleg-shilo** [comment]
Not sure what is happening. You are entering the dark forest of MSI land. Many things there are mysterious there. :)

I do not see any connection between the MSI session being (or not) user interactive and the deployment artifacts installed successfully.

Though MSI forums might help. But no warantee

As for administrative permissions, if you are talking about elevating the install session then you need to use windows elevation (e.g. command prompt in admin mode).  `/a` does not do that.
If you are talking about permission of the folder you are installing then you need to use  `DirPermission` (see Permissions sample).

**Comment by gvsoft3750** [comment]
Yes, I have used ```DirPermissions``` in a couple of places.  But I was talking about what happens when I use ```/a```, which I guess I misread.

Thanks, I guess I'll just stick with the basics for now, and if I get requests for a quiet install, I'll research MSI further.

Dennis
