### ISSUE TITLE
Conditional messages to check versions of OS, .NET,  etc

### ISSUE THREAD

**Issue by ronaamishay** [oleg-shilo/wixsharp#1117]
Hello Oleg. I'm quite new in wixsharp, I'm trying to convert my wix installation to wixsharp.
My wix installation includes a conditional message, to check .net version, that I'd like to add also in my wixsharp. Here is how it looks in original wxs file:

		<PropertyRef Id="WIX_IS_NETFRAMEWORK_46_OR_LATER_INSTALLED" />
		<Condition Message="This application requires .NET Framework 4.6, or higher. Please install the .NET Framework then run this installer again.">
			<![CDATA[WIX_IS_NETFRAMEWORK_46_OR_LATER_INSTALLED]]>
		</Condition>

I tried to add these conditions on my wixsharp project (in cs file)

            LaunchCondition dotNetCondition = new LaunchCondition("WIX_IS_NETFRAMEWORK_46_OR_LATER_INSTALLED", "This application requires .NET Framework 4.6, or higher. Please install the .NET Framework then run this installer again.");

            var project = new Project(
                            _productName,
                            dotNetCondition);

The result, however, is not what I meant

    <Condition Message="This application requires .NET Framework 4.6, or higher. Please install the .NET Framework then run this installer again.">WIX_IS_NETFRAMEWORK_46_OR_LATER_INSTALLED</Condition>

where is my mistake? how should this be done?

Thanks in advance!

**Comment by ronaamishay** [comment]
think I found the solution:

            project.SetNetFxPrerequisite("WIX_IS_NETFRAMEWORK_46_OR_LATER_INSTALLED ", "This application requires .NET Framework 4.6, or higher. Please install the .NET Framework then run this installer again.");

**Comment by oleg-shilo** [comment]
Thank you for sharing
