### ISSUE TITLE
Can wixsharp work with wix v3.14 or later?

### ISSUE THREAD

**Issue by ronaamishay** [oleg-shilo/wixsharp#1120]
Hi,
I would like to check that .net version is 4.8 or higher.(as prerequisite to my installation).
wix tag: WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED is available starting in WiX v3.14.

My wixsharp project seems to work with wix 3.11.2
` <PackageReference Include="WixSharp.wix.bin" Version="3.11.2" />
`
can wix sharp work with wix v3.14 or later? how is it done?

**Comment by oleg-shilo** [comment]
These are two very different questions :)

1. You can emit tags that are not available out of box either via WixSharp types (e.g. `Condition`) or via XML injection (e.g. `project.WixSourceGenerated += ...`).
  Even more, if I understand your challenge correctly (you provided very little description) you can:
  
  ![image](https://user-images.githubusercontent.com/16729806/153141891-35b3155d-ea38-4d9e-9bac-775a79acd75f.png)


2. Most likely yes but I never tried. You can install v3.14 and see if it works.

**Comment by Torchok19081986** [comment]
Morning, i found https://github.com/wixtoolset/issues/issues/5977 . I added .net framework 4.7.2 as .wxs extensionfile to installer. It works event with 3.11 Wixtoolset and current Wixhsharp. 
best regards.
