### ISSUE TITLE
Wrong folder created with FirewallException and changed default INSTALLDIR during install

### ISSUE THREAD

**Issue by Dalstroem** [oleg-shilo/wixsharp#1124]
Hi Oleg, I have found a weird bug when creating a `FirewallException` and `INSTALLDIR` is changed to a different root drive during install.

Default install location is `C:\Program Files\MyCompany\MyApp`, but changed to `D:\Program Files\MyCompany\MyApp` during installation.

This code below will create `C:\Program Files\MyCompany` when installed, and the firewall rule is correct (`D:\Program Files\MyCompany\MyApp\MyApp.exe`), and when uninstalled an empty folder `D:\Program Files\MyCompany` remains.

If you comment out the first `FirewallException` and uncomment `FirewallException` on the found "EXE" file, everything works as expected.

```csharp
string productName = "MyApp";
Version productVersion = Version.Parse("1.0.0");

WixObject[] wixObjects = {
    new Dir("%ProgramFiles%\\MyCompany\\MyApp",
        new Files("*.*")),

    // This will create "C:\Program Files\MyCompany" when installed into "D:\Program Files\MyCompany\MyApp".
    // When uninstalled, "D:\Program Files\MyCompany" remains but "D:\Program Files\MyCompany\MyApp" is removed.
    new FirewallException
    {
        Name = productName,
        Program = "[INSTALLDIR]MyApp.exe",
        Scope = FirewallExceptionScope.any
    }
};

try
{
    var project = new Project(productName, wixObjects)
    {
        Platform = Platform.x64,
        Version = productVersion,
        UI = WUI.WixUI_InstallDir,
        UpgradeCode = Guid.Parse("{ADE728A6-7D54-4E3A-ABB7-23CB738BA446}"),
        ProductId = Guid.NewGuid()
    };

    project.ResolveWildCards(ignoreEmptyDirectories: true);

    // This installs and uninstalls correctly.
    //var exeFile = project.AllFiles.Single(o => o.Name.EndsWith(".exe"));

    //exeFile.FirewallExceptions = new[]
    //{
    //    new FirewallException
    //    {
    //        Name = productName,
    //        Scope = FirewallExceptionScope.any
    //    }
    //};

    project.BuildMsi();
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

**Comment by oleg-shilo** [comment]
Thank you.
Does look like a bug. Will have a look at it.

**Comment by oleg-shilo** [comment]
Hm... after some analysis, I am not sure it is a real bug.

You see, the `MyApp` of `%ProgramFiles%\\MyCompany\\MyApp` is interpreted as an INSTALLDIR. Though judging from your description you want `MyCompany` to be the one that is treated as an INSTALLDIR.

Thus you can try to rewrite it as below:
```C#
  new Dir("%ProgramFiles%\\MyCompany",
      new Dir("MyApp",
          new Files("*.*")),
```

Though most likely this would only address part of the problem. 
I suggest you look at the produced wxs. Even without the modification, I suggested your wxs should contain the corresponding `ReomoveFolder` element:

![image](https://user-images.githubusercontent.com/16729806/154951156-7754ab41-6cbf-4ac2-828a-af7c523e066f.png)

If it does then it is an MSI/WiX problem. If it doesn't then it is a WixSharp defect.
Can you please have a look and let me know?

**Comment by Dalstroem** [comment]
Hi Oleg.

I want `%ProgramFiles%\\MyCompany\\MyApp` to be my **INSTALLDIR**. And it is with option 2 when the _FirewallException_ is create on the EXE file it-self. But not when created on the project with `Program = "[INSTALLDIR]MyApp.exe"`.

I don't see why there are a difference when _FirewallException_ is create the 2 different ways. Should't it be the same either way?

Looking at a diff of both _*.wxs_ files, I can see a `ProgramFiles64Folder.MyCompany` component (red ?) outside of **INSTALLDIR** in the "bugged" MSI, but not when the _FirewallException_ is created on the EXE file.

I have removed all GUIDs for better diff :)

![Diff1](https://user-images.githubusercontent.com/1663793/155124624-fe564b6b-d2a9-41e9-93d6-237ea41c537c.png)

![Diff2](https://user-images.githubusercontent.com/1663793/155124641-86ce50ae-f163-40b9-af89-d269a58d4d01.png)

I have uploaded the Visual Studio _MyApp_ project with the 2 _*.wxs_ files, if that helps.

[MyApp.zip](https://github.com/oleg-shilo/wixsharp/files/8116257/MyApp.zip)

**Comment by oleg-shilo** [comment]
> Should't it be the same either way?

Sadly, no, they should not. 
According [WiX documentation](https://wixtoolset.org/documentation/manual/v3/xsd/firewall/firewallexception.html) `FirewallException` element is expected to be a parent of either `File` or `Component`. Thus two different WixSharp definitions lead to these two different WiX (XML) use-cases. 
Thus is is kind of correct, as WiX expects you to do. 

But why one use case leads to the folders not being removed even there is a clear statement `<RemoveFolder...`, I do not know.
![image](https://user-images.githubusercontent.com/16729806/155247524-dbd76645-6869-4a03-a5f2-da4404cb0bcf.png)

Thus unless you are able to find a direct cause/solution, you stick with what you know works. And only improve the setup definition readability with the use of `OnProcess` delegate:
```C#
new Dir("%ProgramFiles%\\MyCompany\\MyApp",
    new Files("*.*")
    {
        OnProcess = file=>
        {
            if (file.Name.EndsWith("MyApp.exe"))
                file.FirewallExceptions = new[] {
                    new FirewallException
                    {
                        Name = productName,
                        Scope = FirewallExceptionScope.any
                    }};
        }
    }),
```
