### ISSUE TITLE
Executing logic once a service has been started

### ISSUE THREAD

**Issue by pikausp** [oleg-shilo/wixsharp#1125]
As a part of our installer, a service is registered on the system, however, the `AfterInstall` callback is executed before the service is registered & started.

```
AFTER_INSTALL
IsInstalling: True; IsUninstalling: False; IsUpgradingInstalledVersion: False
Executing logic for new installation.
Loading secrets from the secure server.
System.InvalidOperationException: Unable to complete the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:55243
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   .........................
MSI (s) (AC:CC) [14:49:32:621]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
MSI (s) (AC:CC) [14:49:32:623]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (AC:CC) [14:49:32:623]: Executing op: ServiceInstall(Name=MyService,DisplayName=MyService,ImagePath="C:\Program Files\MyApp\MyApp.exe",ServiceType=16,StartType=2,ErrorControl=32769,,Dependencies=[~],,StartName=NT AUTHORITY\LocalService,Password=*******,Description=MyService,,)
MSI (s) (AC:CC) [14:49:32:633]: Executing op: ActionStart(Name=RollbackServiceConfig,,)
MSI (s) (AC:CC) [14:49:32:634]: Executing op: CustomActionSchedule(Action=RollbackServiceConfig,ActionType=3329,Source=BinaryData,Target=RollbackServiceConfig,CustomActionData=SchedServiceConfig)
MSI (s) (AC:CC) [14:49:32:634]: Executing op: ActionStart(Name=ExecServiceConfig,,)
MSI (s) (AC:CC) [14:49:32:635]: Executing op: CustomActionSchedule(Action=ExecServiceConfig,ActionType=3073,Source=BinaryData,Target=ExecServiceConfig,CustomActionData=SchedServiceConfigMyService1restartrestartrestart130)
.....
```

What would be the proper way to execute logic once this service has been started?

**Comment by oleg-shilo** [comment]
The `AfterInstall` event handler is scheduled like this:
```xml
<CustomAction 
  Id="WixSharp_AfterInstall_Action" 
  BinaryKey="WixSharp_InitRuntime_Action_File" 
  DllEntry="WixSharp_AfterInstall_Action" 
  Return="check" 
  Impersonate="no" 
  Execute="deferred" />
```

This may, or may not, be the time point you want to execute your custom deployment logic. Cannot comment on that. Though it is very unlikely MSI is failing to execute this deferred action at the correct time. Thus your problem is likely caused by the asynchronous nature of the _service start_ action.

As a side point, I would really question trying to do something as heavy as communication with the service from the service installer. It looks like a deployment antipattern. What will happen if your service fails to start? Can you consider your installation completed?

**Comment by pikausp** [comment]
Yeah, it seems like it's "too early" as the service is not yet registered in the system. It doesn't matter how long I wait, the service will be registered/started in the step following the `AfterInstall` callback.

Basically, it comes down to the wishes of our client.  We will either have to use a custom action, registering it once the service is started, or using a different mechanism to pass the initial data to the service.

I don't think the installation can be considered complete unless the service was started & initialized by the installer. Initialized with data from the installer I mean.

**Comment by oleg-shilo** [comment]
> I don't think the installation can be considered complete unless the service was started & initialized by the installer. Initialized with data from the installer I mean.

Sorry, this can be debated :)
The initialisation is not a part of the deployment but the configuration. Deployment of initialization data is but initialization is not. 

When MS started tightening the rules about Windows deployment for applications certified "Built for Windows" they demanded that on deployment there is no app/service is started. Instead, you start your app or a special initial configuration app. 
In fact, you are supposed to start the same initialization app/process when a new user logs. Thus you do not need to repair/reinstall every time a new user is created on the system.

Anyway, it seems like you are completely aware of the implications of the problem you are facing. So I will leave it to you.
My advice is:
- deploy your initial config data and let the service on startup read it and initialize itself.
- you will also be able to repeat this process any time should the user decide to reset your product configuration to the initial state.

**Comment by pikausp** [comment]
Was referring to how our client sees it :) Thanks again Oleg!
