### ISSUE TITLE
Strange Behaviour of MSI 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1126]
Hallo, i created msi package for my app .  Package was successfully created , but i have strange behaviour after i try to execute it. 
Installer with dialogs not appaers anymore. (Dont know why BIG Question Sign ???? )  In Eventlog of windows i can find  two errors 1602 and 1603 for my installpackage. 
On my customUI project, i set pacakgeplatform to x64, same like my execution file and all dlls in deployfolder. 
Somehow i could identify problem : if i set Platform in Visual Studio to Any, it works, but if i set it to x64, it doesnt work anymore. 
Any idea why or which reasons could be for errors in Installer ?

**Comment by oleg-shilo** [comment]
You can execute your msi with the loging enabled. it may help

**Comment by Torchok19081986** [comment]
morning, oleg. i tested output msi file with normal installtion method and execute it from cmd with line msiexec.  msi cancel installation after uiinitialized event.  I do only check for admin rights in event with folowing code
 ```csharp
Version installedVersion = e.Session.LookupInstalledVersion();
            Version toinstalledversion = e.Session.QueryProductVersion();

            var owner = e.Session.GetMainWindow();

            if (toinstalledversion <= installedVersion)
            {
                MessageBox.Show(owner, "Aktuelle Version von " + e.ProductName + " ist bereits installiert", "Windows Installer - Versioneninfo", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                e.ManagedUI.Shell.ErrorDetected = true;
                e.Result = ActionResult.UserExit;
            }

            var windowsidentity = WindowsIdentity.GetCurrent();

            const WindowsBuiltInRole rolles_admin = WindowsBuiltInRole.Administrator;

            if (!new WindowsPrincipal(windowsidentity).IsInRole(rolles_admin))
            {
               
                MessageBox.Show(owner, "Die Installation muss mit administrativen Rechten starten.\r\nBitte warten.\r\nWindows Installer startet mit administraticen Rechten.", "Info", MessageBoxButtons.OK, MessageBoxIcon.Warning);

                e.Result = ActionResult.Failure;

                var startinfo = new ProcessStartInfo
                {
                    UseShellExecute = true,
                    WorkingDirectory = Environment.CurrentDirectory,
                    FileName = "msiexec.exe",
                    Arguments = "/i \"" + e.MsiFile + "\"",
                    Verb = "runas"
                };
                Process.Start(startinfo);
            }
   ```

**Comment by oleg-shilo** [comment]
Most likely there is an exception in the CA. The next step is to debug

**Comment by Torchok19081986** [comment]
ok, have to. i investigated it to the line e.Session.LookupInstalledVersion(); 
I have to say, first time installation going to be installed. Product is at this time installed on target system. Code returns null. Any possibility to change that?

**Comment by oleg-shilo** [comment]
Sorry, mate. This will have to wait. 

At the moment I have relatives hiding in the bombing shelter in my city Kharkiv of Ukraine. 
While working on this project is a distraction I need, I cannot really be efficient with any even remotely serious support.

**Comment by Torchok19081986** [comment]
oh wait. completly forget, be sage.  The war is always the same: only dead and destruction for normal people, for some rich peoples makes tons of money with weapons.

**Comment by oleg-shilo** [comment]
Sorry, I would not let the whole guilt of a single maniak be shifted on all rich people in the world. 
Though this is probably not the best place for this discussion.
