### ISSUE TITLE
Wix is only uninstall files which are created by himself.

### ISSUE THREAD

**Issue by karimmohammad** [oleg-shilo/wixsharp#1130]
Hi,

I have following problem.
When I install my tool with WIX UI it creates an installation directory.
But when I start my tool this creates also files into this directory.
When I now uninstall my tool again, only files which was installed are deleted.
The files which came later into this folder and the installation folder stay stil there.

Is it possible to delete them to within the uninstall progress? Or to delete the installation directory although there are files in it?

**Comment by Torchok19081986** [comment]
morning, not wix ui do install, msi - windows installer,  install your package on system. msi doesnt touch any external files. means, you have to do it by yourself. if you want to delete all files or all directories at uninstall, you have some options.  Custom Action or do it at event before / after install event.
try get your package will be uninstalled. 
in samples folder is good upgrade sample with messagebox at beforeinstall event.  after you can identify msi want to uninstall package,  comes pure C#. 
not tested, some thing like that 
```csharp
System.IO.DirectoryInfo di = new DirectoryInfo("YourPath");

foreach (FileInfo file in di.GetFiles())
{
    file.Delete(); 
}
foreach (DirectoryInfo dir in di.GetDirectories())
{
    dir.Delete(true); 
}
```

**Comment by oleg-shilo** [comment]
Yes, this is how MSI works.
The ideal solution is not to write anything to the install folder. This is in fact a deployment good practice :)

**Comment by Torchok19081986** [comment]
hiho, Oleg. can we please have extension to delete all files or dirs at uninstall for such a scenario  ?

**Comment by oleg-shilo** [comment]
It already exists:

https://github.com/oleg-shilo/wixsharp/blob/6ead0c5342218e9006f7d7012a115cdba2c7256f/Source/src/WixSharp/Extensions.cs#L1099
