### ISSUE TITLE
Q: display a summary of what is going to happen before clicking Next to begin install

### ISSUE THREAD

**Issue by sanikolov** [oleg-shilo/wixsharp#1131]
First of all, I'd like to express gratitude for this project.
It is amazing, which becomes very obvious when the complexity of the installer increases.

As for my question, what is the best practice to achieve the summary in the attached screenshot from a ManagedUI?

![image](https://user-images.githubusercontent.com/19896827/158212877-9d7dc437-214f-4135-8fa8-1d7baa65a23e.png)

**Comment by Torchok19081986** [comment]
Msi does all by public properties like INSTALLDIR. What if you add some public properties to your MSI like "STARMENU" and after last Dialog and before install show it to user. you can set Values to STARTMENU in curren install Session like session["STARTMENU"]  = "Name or Path" whatever you want and so on. Only dont know how do it if you have Features. Maybe Oleg self, can explain it better for Features. 
Best reagards, Torchok

**Comment by oleg-shilo** [comment]
As @Torchok19081986 correctly explained you can always explore the properties of the and directory structure. 
You will need to do some debugging/exploring. It is actually a MSI challenge, not even WiX or WixSharpi
