### ISSUE TITLE
The setup UI should use the same language as the system language

### ISSUE THREAD

**Issue by twegener-mum** [oleg-shilo/wixsharp#1133]
Hi Oleg,

I use the great WixSharp tool :-) in this way
```
...
var wixProject = new ManagedProject(SetupProductName, wixAddinDirs, wixCommonAppDataDirs);
wixProject.ManagedUI = new ManagedUI { Icon = $@"My.ico" };
...
wixProject.BuildMsi();
```

If I do this, the language in the UI is always in english.
It is possible to have the same language as is the installed windows language?
If so, what have I to do?

thanks in advance thomas

**Comment by Torchok19081986** [comment]
Hi Thomas, in samples folder exists some approaches for languages.  https://github.com/oleg-shilo/wixsharp/wiki/Localization Link for Localisataion.

**Comment by twegener-mum** [comment]
Hi Oleg, I run a German OS, but the resulting .msi /UI appears in English not in German.
Do you have an idea what I'm doing wrong?


I use this approach
```
wixProject.Language = "de-DE,en-US,ru-RU";
wixProject.BuildMultilanguageMsi();
```

If I run the project  I get these lines:

```
...
MSI file has been built: en-US.msi
...
Execute:
"C:\Program Files (x86)\WiX Toolset v3.11\bin\torch.exe" -p -t language "C:\MuM_Git\PubObo\Debug\Setup2019\OBO Construct 3.30.2.0.msi" "C:\MuM_Git\PubObo\Debug\Setup2019\en-US.msi" -out "C:\MuM_Git\PubObo\Debug\Setup2019\en-US.mst"
...
MSI file has been built: ru-RU.msi
...
Execute:
"C:\Program Files (x86)\WiX Toolset v3.11\bin\torch.exe" -p -t language "C:\MuM_Git\PubObo\Debug\Setup2019\OBO Construct 3.30.2.0.msi" "C:\MuM_Git\PubObo\Debug\Setup2019\ru-RU.msi" -out "C:\MuM_Git\PubObo\Debug\Setup2019\ru-RU.mst"
...
> Multi-language setup C:\MuM_Git\PubObo\Debug\Setup2019\OBO Construct 3.30.2.0.msi is completed.
```

**Comment by Torchok19081986** [comment]
morning, english language is always default if you dont add language to msi.  if you want only german language, you can set language to "de-DE" and add  .wxl localisation file from wix toolset it self.  If your wixtoolset iinstalled , you can find in wixui folder .wxl extension. just add ist to msi, thats all. Only one thing: you have to changes intern messages and tags for better readable messages.

**Comment by twegener-mum** [comment]
morning, 
- if I add 
 ` wixProject.LocalizationFile = $@"{Globals.WixToolsetDir}SDK\wixui\WixUI_de-de.wxl";`
I get always german texts
- but I want english text automatically on English, Polish, Non-German OS

**Comment by Torchok19081986** [comment]
can be difficult. you have to add language depend on OS Language. Dont know if language for msi static or not . Try to get OS Language in UIInitialized Event with CA and pure C#.  Maybe you can get it BEFORE msi starts UI. 
CultureInfo ci = CultureInfo.InstalledUICulture ;

**Comment by twegener-mum** [comment]
I thought I create an english .msi and a transform table to  german. so the german texts appears on german OS automatically on all other OS's english?

I loooked at this code on https://github.com/oleg-shilo/wixsharp/wiki/Localization 
- what kind of object is "product"?
- productMsi is a string and has not a method like  EmbedTransform or SetPackageLanguages?
```
product.Language = "en-US"; 
string productMsi = project.BuildMsi(path);
product.Language = "de-DE"; 
string mstFile = project.BuildLanguageTransform(productMsi, "de-DE");
productMsi.EmbedTransform(mstFile);
productMsi.SetPackageLanguages("en-US,de-DE".ToLcidList());
```

**Comment by Torchok19081986** [comment]
AFAIK msi can only have one language at same time.  product is Bootstrapper Project , exe installer with GUI and embeded Msi for install. BA call msi intern and start msi to isntall. BA controls msi. maybe this approach is better. Try it.

**Comment by twegener-mum** [comment]
the following  approach is working, as long I don't use the ManageUI (I missed WixSharp.CommonTasks extension)

```
wixProject.Language = "en-US";
var productMsi = wixProject.BuildMsi();
var mstFile = wixProject.BuildLanguageTransform(productMsi, "de-DE", $@"{Globals.WixToolsetDir}SDK\wixui\WixUI_de-de.wxl");
productMsi.EmbedTransform(mstFile);
productMsi.SetPackageLanguages("en-US,de-DE".ToLcidList());
```

don't using ManageUI, probably `wixProject.BuildMultilanguageMsi(); `would work too, 
Yes, the bootsrapper would be an alternative, maybe another choice would be the CustomUI, which I can localize like I want ...

**Comment by oleg-shilo** [comment]
This example shows how to use German in Managed UI
![image](https://user-images.githubusercontent.com/16729806/160088155-b6e08613-e6c4-4ea3-8926-f838ae393de4.png)
