### ISSUE TITLE
<my-installer>.msi /uninstall gives This patch package could not be opened

### ISSUE THREAD

**Issue by merijndejonge** [oleg-shilo/wixsharp#1136]
Hello,
I've created an installer that correctly installs my software. I can also remove the software from "Add or Remove programs". However, I cannot uninstall from the msi direct.
That is, if I run the command:

```
<my-installer.msi> /uninstall 
```
I get this error message:
![image](https://user-images.githubusercontent.com/1928998/159884440-6393e643-f4e7-4c02-894a-8eeddaea4910.png)

What is going wrong?

**Comment by Torchok19081986** [comment]
morning, try open cmd and runs msiexec.exe <path_to_msi> /u .

**Comment by merijndejonge** [comment]
When runnin
```
msiexec.exe <path_to_msi> /u
```
I get the help screen of msi:
![image](https://user-images.githubusercontent.com/1928998/160077131-caf81b94-fe88-4b82-adca-4596ebf3f03b.png)

When I run 
```
msiexec.exe /u <path_to_msi>
```
Nothing happens.

It turns out I've to use /x
