### ISSUE TITLE
DisallowUpgradeErrorMessage and DowngradeErrorMessage not showing 

### ISSUE THREAD

**Issue by kanhaiyabaranwal** [oleg-shilo/wixsharp#1138]
Hi, I want to prevent downgrade or upgrade of my MSI when another version is already installed. So, if 1.0.2 is installed, installing 1.0.1 or 1.0.3 should be prevented. 

            project.GUID = new Guid("XXX-XXXXX-XXX");                    

            project.UpgradeCode = new Guid("XXX-XXXXX-XXX"); 
            project.ProductId = new Guid("XXX-XXXXX-XXX"); 
            project.Version = new Version("1.0.2");
            project.MajorUpgrade = new MajorUpgrade
            {
                AllowSameVersionUpgrades = false,
                Schedule = UpgradeSchedule.afterInstallValidate,
                Disallow = true,
                DisallowUpgradeErrorMessage = "A lower version of [ProductName] is already installed. Setup will now exit.",
                AllowDowngrades = false,
                DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
            };

Issue# 1:
I followed other issues which says that repair/remove pop-up message will not appear for same version with above changes. 
https://github.com/oleg-shilo/wixsharp/issues/660
https://github.com/oleg-shilo/wixsharp/issues/492

Am I right? Can I have the configuration, where old/new/same versions of the products are not allowed by the installer if one version is already installed. 

Issue# 2: I want my custom message. How can I get it. What changes are required to get custom message?
Currently, the setup exits with standard message "Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel."

**Comment by Torchok19081986** [comment]
morning,  1. is there reason to use majorupgrade instead of majorupgragestrategy? I use majorupgradestrategy and it works. downgrade message and error shows if you try to install same version.
2. custom message : in Sample exists folder for custommesage at installer .  try it, maybe it can help you.

**Comment by kanhaiyabaranwal** [comment]
In https://github.com/oleg-shilo/wixsharp/issues/492, @oleg-shilo has recommended to use MajorUpgrade.

![image](https://user-images.githubusercontent.com/33118071/160749433-dbf3ccf6-1e08-4867-9b47-c2ec71750e8c.png)

**Comment by kanhaiyabaranwal** [comment]
My question is. 
Issue#1) With "AllowSameVersionUpgrades = false", MSI file with same version (first 3 parts) gets reinstalled automatically. This is not an expected behavior. I would expect the warning message that product with same version is already installed. I I would expect repair/remove pop-up message.



Issue#2) When ProductId is changed, Custom message appears and installer exits which is an expected behavior.

There are also other

**Comment by kanhaiyabaranwal** [comment]
Thanks for your response @oleg-shilo , for the time being I shall treat it as MSI feature and check if a desirable option is available with WXS that can help.
