### ISSUE TITLE
Wixsharp Managed Setup Model

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1139]
Hi,
I have a question regarding the [Managed Setup Model](https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model)
I have a manifest file that being produced by the installer to the installation dir.

- After installation, I want to run a command that install the manifest.(as the file is presented, after being produced)
- Before uninstall, I want to to run a command that uninstall the manifest.(as the file is still presented)

For the first action I tried to use `OnAfterInstall` with `if (e.IsInstalled)`
For the second action I tried to use `OnBeforeInstall` with ` if (e.IsUninstalling)`
Both didn't work. Can you please advise?
Thanks a lot.

**Comment by oleg-shilo** [comment]
Both options are the right choice as they are fired at the right point. so you are good.

Thus the only things that can go wrong here are:
- Manifest file is not deployed. I Assume it's not the case as it is easy to check
- Manifest file is not "enabled". i assume you do some programmatic manipulation with it as you are referring to the  C# event handlers. This can be easy checked with the debugger. I suggest you debug your routines.
- Elevation is required but not achieved at runtime. Note `OnAfterInstall ` is elevated but `OnBeforeInstall ` is not. But I am not even sure you need to elevate your process.

**Comment by RachelXGanon** [comment]
Hi, Thank you so much for your quick response!
I'm sorry I wasn't clear, I meant for an  instrumentation manifest, and it's not being "really produced", I just copy paste it to the installation dir.
If `OnBeforeInstall` isn't elevated then what other elevated alternative can I use? Is `OnLoad` elevated?
Thanks a lot.

**Comment by oleg-shilo** [comment]
So you copied/created some file in the install dir after the installation. Basically, it has nothing to do with the setup. OK.
And you are trying to do something with this file in `AfterInstall` and `BeforeInstall`.

Is it an accurate interpretation of your explanation?

**Comment by RachelXGanon** [comment]
No.
As I'm  creating the project like that:
`new ManagedProject("ProjectName", directories)`
as the `directories` obj contains folders and the manifest file.
What I mean is that this is not an application manifest but instrumentation manifest.

**Comment by oleg-shilo** [comment]
Sorry, it is still impossible for me to understand what you are trying to do.
These two statements contradict each other:
- "I just copy paste it to the installation dir."  (implies you only create the file ar install time)
- "as the directories obj contains folders and the manifest file." (implies you have the file at compile time)

**Comment by RachelXGanon** [comment]
I'm sorry for the misunderstood
That's the right one
"as the directories obj contains folders and the manifest file." (implies you have the file at compile time)

**Comment by oleg-shilo** [comment]
OK, then we are on the same page. 👍 

Now, this is what you are trying to do:

1.    After installation, I want to run a command that install the manifest.(as the file is presented, after being produced)
 2.   Before uninstall, I want to to run a command that uninstall the manifest.(as the file is still presented)


You said "Both didn't work.". How?. What exactly did not work?

**Comment by RachelXGanon** [comment]
Well first of all , I found the fix - I had to use "IsInstalling" and not "IsInstalled".
It didn't came to the function if I used the IsInstalled property.

**Comment by oleg-shilo** [comment]
Yep, that's why I provided the samples. If you follow the pattern from these samples then it is a straightforward exercise. :)

**Comment by RachelXGanon** [comment]
👍
