### ISSUE TITLE
Progress dialog shows placeholders instead of file names

### ISSUE THREAD

**Issue by daxpandhi** [oleg-shilo/wixsharp#114]
This is with v1.4.7.0.

The dialog shows `[1]`, etc. instead of the names. Not a big deal, but thought I should report it. Please let me know if you need additional data.

![2017-08-03_16-19-57](https://user-images.githubusercontent.com/6795809/28918647-c9e85584-7867-11e7-8937-51d06c771514.png)

**Comment by oleg-shilo** [comment]
Thank you. Can you tell me if you are using native MSI UI or the managed one (`project.ManagedUI = ...`)?

**Comment by daxpandhi** [comment]
Thanks for the quick response, Oleg! :)

I'm using the MSI UI. Or rather, never specified.

**Comment by oleg-shilo** [comment]
Then it makes my life easier :)

It's not Wix#, It's either WiX or MSI. Wix# is not involved in UI at all unless it is a managed UI. It may be some glitch with the localization or something similar. Hard to tell.

I know, it doesn't help you much :) 

Thank you for the reporting this anyway.

**Comment by daxpandhi** [comment]
No problem - its only a superficial problem. I'll keep an eye on it and see if I can find anything. I wonder if this is a bug in the Windows 10 creators update, which I just had installed. Anyways, if anything relevant comes up, I'll open the bug again.

**Comment by JeremyAnsel** [comment]
Hello,
Have you tried the solution indicated in #87 ?
It consists of adding `<UIRef Id="WixUI_ErrorProgressText" />`.

**Comment by daxpandhi** [comment]
@JeremyAnsel - thank you! 👍
