### ISSUE TITLE
Repair files on uninstall extension (addon, plugin)

### ISSUE THREAD

**Issue by Zerpico** [oleg-shilo/wixsharp#1141]
I want to create an extension installer that adds a file to an already installed application. But it also replaces some files.
Is it possible to restore files during uninstallation?
For example:
- The application with the file **mylibrary.dll** is already installed
- Then I install my app extension which replaces **mylibrary.dll**
- Uninstall the extension and restore the original file **mylibrary.dll**

**Comment by Torchok19081986** [comment]
Morning, i think last point not possible. you overwrite your dll and set it to new one.  Some backup old dll and overwrite it to new , before. Not possible.
 Uninstall Action delete all files which cames from installation and delete all regkeys, nothing more.  
Many CRM or eERP makes plugins with MEF Framework. means, you can use some intern libraries from main programm and after install it works WITH app not standalone. At uninstall your app / programm delete this Connection and originally state be recovered. It has nothing to do with MSI.  This means, you have to add MEF Support to your mainprogramm / app

**Comment by Zerpico** [comment]
> Uninstall Action delete all files which cames from installation and delete all regkeys, nothing more.

Can I do a CustomAction before installation, to copy the original file to some backup directory with the file name **mylibrary.backup.dll**. And the action after uninstallation to return the original file?

**Comment by Zerpico** [comment]
> yes, you can execute CA before installation, BUT...

When i try CA:
```csharp
[CustomAction]
public static ActionResult CreateBackupCvEngine(Session session)
{
    var programDir = Environment.ExpandEnvironmentVariables("%ProgramFiles%");
    var installDir = Path.Combine(programDir, CompanyName, ProductName);
    File.Copy(Path.Combine(installDir, "myLibrary.dll"), Path.Combine(installDir, "myLibrary.dll.backup"), true);

    return ActionResult.Success;
}
```
Info: System.Reflection.TargetInvocationException: The caller threw an exception. ---> System.UnauthorizedAccessException: Access denied along the way "C:\Program Files (x86)\MyCompany\MyProduct\myLibrary.dll.backup".

**Comment by Torchok19081986** [comment]
Morning, this exception you get, if you dont have enough rights to do something iike copy or delete or move in path. You have to do your CA in AfterInstall or BeforeInstall Events. Those callse are elevated.  
in event you can try following code, not tested 

msiproject.BeforeInstall += BeforeInstall /*  or AfterInstall before += */
if(e.Installed && !e.NotBeingUpgraded)
{
   /* do something */
}


best regards.

**Comment by Zerpico** [comment]
Yes. It helped, thanks for the help
