### ISSUE TITLE
How to set Installdir in BA pass to MSI

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1142]
Morning, i create a BA Installer based on sample like Bootstrapper\WixBootstrapper_UI. 
I add new Window to view and would like to set in this window installdir and run msi with Installdir path after user click install. But somehow msi doesnt get it from BA.  I tried with CA, but MSI doesnt execute CA. 
Following Approach doesnt work:
1. Add CA in MSI and set , before created Variables, in BA to Installdir => Path is empty.
2. Set CA on Step InstallUISequece and InstallSequence is suggestion on Stackoverlow, but there is none such steps in WixSharp. 

```csharp
bootstrapper.Variables = new[] 
 { 
       new Variable("BURNINSTALLDIR", "INSTALLDIR") { Overridable = true }
 };
```

CA looks like 

```csharp

 [CustomAction]
 public static ActionResult SetInstallDir(Session session)
 {
     session["BURNINSTALLDIR"] = session["INSTALLDIR"];
       
      return ActionResult.Success;
 }

```

Can someone pls tell me, how do i set Installdir path in BA pass to MSI ?

**Comment by Zerpico** [comment]
@Torchok19081986 how did you solve this problem?

**Comment by oleg-shilo** [comment]
Code sample "WixBootstrapper_UI" shows how to pass user input from BA UI to the MSI property.
I just have updated the sample to include this scenario. previously it was using only registry search as an input for the bootstrapper string variable.
