### ISSUE TITLE
Installer show fail message in the logs but get successful exit dialog 

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1143]
Hi,
As I looked in the installer logs I get the following error:
```
Info: DEBUG: Error 2911:  Could not remove the folder C:\Config.Msi\.
Info: The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2911. 
```
But the installer ended up with successful exit dialog.

Can you please change it, to catch the error and display the corresponding exit dialog?
Thank you!

**Comment by oleg-shilo** [comment]
While this MSI behaviour is not possible to change you will need to contact MS for that as WixSharp as a project has nothing to do with MSI.

As for the exit dialog I am not sure the current behaviour is incorrect. The UI is processing all MSI messages and indicates the failure (if detected) in the exit dialog. Thus the presence of certain messages in the log is not an indication of the failure or success of the setup. Even in your sample, the line indicates that it is an "error message" as well as the "info message". This tells me that it might be a non-critical error. And you kind of confirm it "the installer ended up with a successful exit dialog".

If you still want to do something about the content of the log file at the end of the install. you can do it very easily. Just create your project from the "Custom UI' template and do that magic in the exit dialog.

**Comment by RachelXGanon** [comment]
Got it.
You say` it might be a non-critical error`
Is critical error means for whatever error that throw exception?

**Comment by oleg-shilo** [comment]
Nope, a critical error is an error that fails the installation. Non-critical is the one that was detected but it did not stop the installation.
