### ISSUE TITLE
how to install multiple msi´s in BA

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1144]
Morning, i have to create multiple BA installer for install mainprogramm, myapp and optionally install adobe reader dc as well if user choose install this feature. 
How do i add second package to BA with files or folder requires by second package? I can add feature to msi and change UI to WUI.Featuretree, but i cant add second package to install it.  Optionall Install of Adobe Reader DC contains 5 or 6 Folders and 1 Msi  to install it on Targetsystem. Just dont know how . 
Exists sample of multiinstaller of BA somewhere in Samples folder?

**Comment by oleg-shilo** [comment]
WixBootstrapper sample show that. Even it shows how to deal with adobe.

**Comment by Torchok19081986** [comment]
Morning, thanks for answer, Oleg. I have in Samples 8 Folders in bootstrapper. Which it WixBootstrapper? I dont have Folder with name WixBootstrapper.  I have V1.20 from release link.

**Comment by Torchok19081986** [comment]
Morning, Oleg. I found it, but how do i add window or dialog to BA for choice of Install addtionially packages? I create BA where i start msi after install click.  Like in Example WixBootstrapper_UI. I just dont know where do add dialog : in BA or main MSI pacakage ?

**Comment by oleg-shilo** [comment]
I suggest you add any custom dialogs in BA and collect user input before proceeding to the individual MSI installations. 
Adding dialogs to MSI is an attractive option but I am afraid that because of the long-standing bug WiX Burn still does not support custom UI in MSI. Only native UI.

There is a sample for custom bootstrapper UI
