### ISSUE TITLE
Checkbox to launch application - ManagedProject 

### ISSUE THREAD

**Issue by rishit-epari** [oleg-shilo/wixsharp#1146]
Hi, 

Is there any way we can have a checkbox at the final stage of the installation? It should launch the application if the user selects the option in a managed project.

**Comment by Torchok19081986** [comment]
morning, download samples . Launch at end folder has exmaple , how to start app after install if user want it. 
best regards.

**Comment by rishit-epari** [comment]
@Torchok19081986, thanks for the response. The sample you are referring to will automatically launch the application without user choice. 

My scenario is I need to have a checkbox on the exit dialog if the user selects the checkbox it will launch the application after finishing, and if it's not selected it will just finish the installation.

**Comment by Torchok19081986** [comment]
hm. Ok. msi makes alle by public properties in Uppercase. you can try to add deferedproperty example 'LAUNCHAPPATEND' and get it like in example. But problem is, last window, after finish the installtion succesfully doesnt close at this point atuomatically.

**Comment by rishit-epari** [comment]
@Torchok19081986, thanks again for the response. I will give it a try and test your solution. 

I was also looking into the code and I found **LaunchApplicationFromExitDialog** but when I am trying this approach I am facing issues with the build in the managed project. You aware of it's usage or point me to any example other than the one mentioned in AllInOne sample.
