### ISSUE TITLE
Can't access CLSID registry in desired way

### ISSUE THREAD

**Issue by roman-khazanskii** [oleg-shilo/wixsharp#1149]
I'm trying to write some values in `HKCR\CLSID`, like so:

```csharp
var project = new ManagedProject("Program",
    new RegValue(fullSetup, RegistryHive.ClassesRoot, @"CLSID\{6ED90329-F283-477A-83A3-97ADA22C02F9}\InprocServer32", "CodeBase", "file:///[INSTALLDIR]"),
    new Dir(@"%ProgramFiles%\Manufacturer\Program",
        new Files(@"..\Program\bin\Debug\*.*",
        file => !file.EndsWithAny(true, new string[] { ".pdb", ".obj" }))
        ));
```

however it always gets written to `HKCR\WOW643Node\CLSID`, even if I set `project.Platform = Platform.x86;`.

And looks like there is no method like `ImportRegFile` or `ImportRegValue` in project anymore, so I can't set `RegValue.Win64` to false.

What should I do?

**Comment by Torchok19081986** [comment]
morning, do you try to install on x64 OS Machine ? if so, then, you can try to use following code from example Install on x64

```csharp

static public void BuildWithAttributes()
    {
        //this sample is inly useful for the demonstration of how to work with AttributesDefinition and XML injection

        var project =
            new Project("MyProduct",
                new Dir(@"%ProgramFiles64Folder%\My Company\My Product",
                    new File(@"Files\Bin\MyApp.exe") { AttributesDefinition = "Component:Win64=yes" },
                    new Dir(@"Docs\Manual",
                        new File(@"Files\Docs\Manual.txt") { AttributesDefinition = "Component:Win64=yes" })));

        project.Package.AttributesDefinition = "Platform=x64";
        project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");

        //Alternatively you can set Component Attribute for all files together (do not forget to remove "Component:Win64=yes" from file's AttributesDefinition)

        //either before XML generation
        //foreach (var file in project.AllFiles)
        //    file.Attributes.Add("Component:Win64", "yes");

        //or do it as a post-generation step
        //project.Compiler.WixSourceGenerated += new XDocumentGeneratedDlgt(Compiler_WixSourceGenerated);

        Compiler.BuildMsi(project);
    }

    static void Compiler_WixSourceGenerated(XDocument document)
    {
        document.Descendants("Component")
                .ForEach(comp=>comp.SetAttributeValue("Win64", "yes"));
    }

````

**Comment by oleg-shilo** [comment]
>however it always gets written to HKCR\WOW643Node\CLSID, even if I set project.Platform = Platform.x86;

Correct. By default WiX build Wi32 msi so it installs registry values in WOW643Node hive.


There is a `static public RegValue[] ImportRegFile(string regFile)` but you will probably be more comfortable by simply adding regfiles to the project:

```C#
project.ImportRegFile("MyProduct.reg");
// or 
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File(@"readme.txt")),
        new RegFile("MyProduct.reg"),
```

**Comment by oleg-shilo** [comment]
Be careful if you are registering your x86 server in the hive that is not `WOW643Node` your com server will not be able to start.

**Comment by roman-khazanskii** [comment]
Adding `{ AttributesDefinition = "Component:Win64=no" }` just for RegValue and RegFile didn't change CLSID path.
When I tried to add it to Dir ctor, I get an error:

```
Unhandled Exception: System.ApplicationException: Cannot resolve custom attribute definition:Component:Win64=no
1>Note, some Wix elements may not be contained by 'Component' elements (e.g. 'CloseApplication'). Thus attempt to set parent component attribute will always fail.
```

Using

```
foreach (var file in project.AllFiles)
         file.Attributes.Add("Component:Win64", "no");
```

also didn't change anything :(

And project doesn't seem to have a member named `Compiler`...

**Comment by roman-khazanskii** [comment]
> you have to look in your output .wxs file. before adding attributedefinition and after adding it . some values has to be changed after.

Diff shows no change...

**Comment by oleg-shilo** [comment]
Please have a look at :
![image](https://user-images.githubusercontent.com/16729806/165911708-dea783bb-21dd-45ee-93ce-72a9fe3c0f6a.png)

https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Install%20on%20x64

It is specifically designed to demonstrate how to work with x64 installs.

In straightforward scenarios, the only thing you need is:
```C#
project.Platform = Platform.x64;
```
nothing else. you do not need even to deal with the `Component:Win64`. Though if for whatever reason you prefer to then in the same sample you will find the routine (@Torchok19081986 posted it early)

>And project doesn't seem to have a member named Compiler...

`Compiler` is a static class. Though the same effect can be achieved with the extension methods:
```C#
Compiler.BuildMsi(project);
// or
project.BuildMsi();
```

I know it is what you tried to do but I suggest you use the sample first and see if it works. Then compare produced WXS (yours and from the sample). This may give you a clue.

I noticed you are trying to set `file.Attributes.Add("Component:Win64", "no")` meaning you want the registry to go to `HKCR\WOW643Node`. I am not sure it is what you wants to achieve.

**Comment by Torchok19081986** [comment]
if i understand correctly, he want to register comserver or components as com, with writing regvalues in regpath. InprocServer32 is com componente.

**Comment by oleg-shilo** [comment]
Yeah I understand that.
But I set `project.Platform = Platform.x86` then it is expected that the reg values go to the wi32 registry hive on Win64 system that is `HKCR\WOW643Node\CLSID`. If you set `project.Platform = Platform.x64` then it goes to `HKCR\WOW643Node\CLSID`.

Thus the original post statement is, well..., puzzling:
```
however it always gets written to HKCR\WOW643Node\CLSID, even if I set project.Platform = Platform.x86;.

**Comment by roman-khazanskii** [comment]
Sorry for me not being very clear; I want to write to `HKCR\CLSID`, not to `HKCR\WOW643Node\CLSID`

**Comment by Torchok19081986** [comment]
only question, is it possibly that in reg file included in project to install on targetsystem, exists path to x64 registry ?

**Comment by oleg-shilo** [comment]
> Sorry for me not being very clear; I want to write to HKCR\CLSID, not to HKCR\WOW643Node\CLSID

Then you want to write in the Win64 registry hive. Meaning you need to set your platform to x64.
This is how it works on Win64 systems:
- x86 applications
  - install files go to `C:\Program Files (x86)` 
  - registry values go to `<root>\WOW643Node` hive
- x64 applications
  - install files go to `C:\Program Files` 
  - registry values go to `<root>` hive

**Comment by roman-khazanskii** [comment]
>Then you want to write in the Win64 registry hive. Meaning you need to set your platform to x64.

Looks like it always writes to `WOW6432Node`, regardless of what I'm setting platform to. I was setting `project.Platform = Platform.x64;` from the beginning, and `%ProgramFiles% resolves to `Program Files` but registry writes always go to `WOW6432`

**Comment by roman-khazanskii** [comment]
I tried to use ElevatedManagedActions (as described in #637) and `var softwareKey = RegistryKey.OpenBaseKey(Microsoft.Win32.RegistryHive.ClassesRoot, RegistryView.Registry64);` works as expected, so I can resort to that :) Thanks! 

Still, I'm puzzled why setting Platform.x64 doesn't seem to affect registry redirection.

**Comment by oleg-shilo** [comment]
> Still, I'm puzzled why setting Platform.x64 doesn't seem to affect registry redirection.
It does affect it.

When you set "project.Platform = Platform.x86;" the registry is expected to go to `HKCR\WOW643Node\CLSID`.

**Comment by oleg-shilo** [comment]
Roman, then I can only suggest you test that sample I mentioned. 

If changing `project.Platform` triggers the right behaviour for the sample then there is something in your scenario that is different. comparing WXS can give you a clue.

If changing `project.Platform` does not work even for the sample than... the sample is wrong or there is something in with WixSharp and I will need to have a look at it.

**Comment by roman-khazanskii** [comment]
Results are interesting.
I used sample `WixSharp.1.20.0.0\Samples\Install on x64` and added this line to the project:

`new RegValue(RegistryHive.ClassesRoot, @"CLSID\12345\6578", "CodeBase", "aaaa"),`

and set `project.Platform = Platform.x86;` and `project.Platform = Platform.x64;` - and that did affect the WXS:

In case of x86:

```xml
        <Component Id="Registry.1" Guid="6f330b47-2577-43ad-9095-1861b742561a" KeyPath="yes">
          <RegistryKey Root="HKCR" Key="CLSID\12345\6578">
            <RegistryValue Id="CodeBase" Type="string" KeyPath="no" Value="aaaa" Name="CodeBase" />
          </RegistryKey>
```

and in case of x64 `Win64="no"` is set to "no" (which looks a bit confusing to me but nevermind):

```xml
<Component Id="Registry.1" Guid="6f330b47-2577-43ad-9095-1861b742561a" Win64="no" KeyPath="yes">
          <RegistryKey Root="HKCR" Key="CLSID\12345\6578">
            <RegistryValue Id="CodeBase" Type="string" KeyPath="no" Value="aaaa" Name="CodeBase" />
          </RegistryKey>
```

This results in two different .msi that setup the sample program in `Program Files` and `Program Files (x86)` respectively, however (!) they both will write to the same registry path - `HKCR\WOW6432\CLSID` !

Here's complete sample with both .msi
[Install on x64.zip](https://github.com/oleg-shilo/wixsharp/files/8602280/Install.on.x64.zip)

**Comment by oleg-shilo** [comment]
Thank you Roman,
Then it does look like something that needs to be addressed (or at least verified) in WixSharp. Will check.
Changing the label to defect.

**Comment by oleg-shilo** [comment]
Hi Roman,

My apologies. I have missed the point that only connected the dots when started testing your scenario. 

You see, the `RegValue` does not automatically adhere to the `project.Platform` because the user may need to install registry of both types (x86 and x64). Thus you need to set `RegValue.Win64=true`. See code below:

```C#
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File("readme.txt")),
        new RegValue(RegistryHive.LocalMachine, @"Software\My Company\My Product", "LICENSE_KEY", "01020304")
        {
            Win64 = true,
            AttributesDefinition = "Type=binary"
        });

project.Platform = Platform.x64;
project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.UI = WUI.WixUI_ProgressOnly;

project.BuildMsi();
```

**Comment by roman-khazanskii** [comment]
Thanks!

For those who will stumble in this issue in the future, I'll share my current workaround:

1. I was indeed intending to register my class for COM, and I found out that it's better to use `System.Runtime.InteropServices.RegistrationServices` for this, than writing to registry by hand. So I added this code to my `project.AfterInstall` event:

```csharp
var file = e.Session.Property("INSTALLDIR") + "my_dll.dll";
var asm = System.Reflection.Assembly.LoadFrom(file);

var regAsm = new System.Runtime.InteropServices.RegistrationServices();
var result = regAsm.RegisterAssembly(asm, System.Runtime.InteropServices.AssemblyRegistrationFlags.SetCodeBase);
```

2. And for direct writes to registry (that I still need to do), in the same `AfterInstall` event I use `var softwareKey = RegistryKey.OpenBaseKey(Microsoft.Win32.RegistryHive.ClassesRoot, RegistryView.Registry64);`, second option allows me to control redirection to WOW6432

**Comment by roman-khazanskii** [comment]
>You see, the RegValue does not automatically adhere to the project.Platform because the user may need to install registry of both types (x86 and x64). Thus you need to set RegValue.Win64=true.

Oh. Thanks, I'll check this

**Comment by oleg-shilo** [comment]
And to make the future investigation turn around faster I have updated the documentation:
![image](https://user-images.githubusercontent.com/16729806/166441913-7d4d9e7a-6c44-47f0-8bb2-9cbe9f3bde72.png)

**Comment by oleg-shilo** [comment]
@roman-khazanskii, 

1. ...var regAsm = new System.Runtime.InteropServices.RegistrationServices();... 
   While MSI/WiX consider self-registration as an anti-pattern, I actually like it very much for its convenience. Will add your code to the samples library. 
   
 2. As for writing to the registry from `AfterInstall` you arguably don't need to do it if you use `RegValue.Win64`.
     I will also mention this on Wiki.

**Comment by roman-khazanskii** [comment]
>You see, the RegValue does not automatically adhere to the project.Platform because the user may need to install registry of both types (x86 and x64). Thus you need to set RegValue.Win64=true.

I checked this just now and it does indeed work! 

>As for writing to the registry from AfterInstall you arguably don't need to do it if you use RegValue.Win64.

Sure, using RegValue.Win64 requires less typing and feels more idiomatic than custom action :)
Thanks again!

>While MSI/WiX consider self-registration as an anti-pattern, I actually like it very much for its convenience. Will add your code to the samples library.

Wow, thanks!

The only thing that bothers me in that approach is hard-coded dll name (which is similar to hard-coded paths for installed Files); I'm not very good at C# so I couldn't quickly find any good way to get this info from current solution.
But that's probably a question for another topic?

**Comment by oleg-shilo** [comment]
Yeah, but probably it is something that is OK to hardcode it as long as it is the file name only. This is because there is no wat programmatically determine if the file is a COM server or not. So you will always encode it as `if (file.GetFileName() == "<some mane>"`). So there is nothing really wrong here.

**Comment by oleg-shilo** [comment]
And of course, you can use WiX canonical approach:
![image](https://user-images.githubusercontent.com/16729806/166444805-8d52f0ff-572c-4683-8abd-58b6fca8f4e1.png)

```C#
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File(@"Files\Bin\MyApp.exe",
                        new TypeLib
                        {
                            Id = new Guid("6f330b47-2577-43ad-9095-1861ba25889b"),
                            Language = 33,
                            MajorVersion = 23
                        },
                        new ComRegistration
                        {
                            Id = new Guid("6f330b47-2577-43ad-9095-1861ba25889b"),
                            Description = "MY DESCRIPTION",
                            ThreadingModel = ThreadingModel.apartment,
                            Context = "InprocServer32",
                            ProgIds = new[]
                            {
                                new ProgId
                                {
                                    Id = "PROG.ID.1",
                                    Description ="Version independent ProgID ",
                                    ProgIds = new[]
                                    {
                                        new ProgId
                                        {
                                            Id = "prog.id",
                                            Description="some description"
                                        }
                                    }
                                }
                            }
                        })));
```

But self-registration is definitely simpler :)
Stil... remember the limitations of self-registration approach - it is not transactional as it is based on custom action but not REGISTRY data. So use it at your own risk. :)

**Comment by roman-khazanskii** [comment]
>But self-registration is definitely simpler :)
Stil... remember the limitations of self-registration approach - it is not transactional as it is based on custom action but not REGISTRY data. So use it at your own risk. :)

Sure, thanks!
I suppose I should close this issue now since my question is resolved :)

**Comment by roman-khazanskii** [comment]
Also, a word of warning about dll self-registration. When I tried to add self-**un**registration to the `project.BeforeInstall` event, I was getting exceptions about `System.Security.SecurityException: Requested registry access is not allowed.`

So I had to move unregistration to deferred action `new ElevatedManagedAction(CustomActions.BeforeUninstall, Return.check, When.Before, Step.RemoveFiles, Condition.BeingUninstalledAndNotBeingUpgraded)`

**Comment by oleg-shilo** [comment]
Yep, correct. Registration requires elevation (deferred action). You can Use `ElevatedCustomAction` for that.
and `project.BeforeAfterInstall` is already elevated.

**Comment by roman-khazanskii** [comment]
>and project.BeforeAfterInstall is already elevated.

Hmm.. If it's already elevated, why was I getting an exception?
UAC message was already accepted at that point..

**Comment by roman-khazanskii** [comment]
>Sorry, it was a typo. It meant to be project.AfterAfterInstall
It is the only elevated event

Oh, okay, that explains it :)
Thanks!
