### ISSUE TITLE
Question: Install config file (feature) by condition

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [oleg-shilo/wixsharp#1150]
After looking and reading in the many Samples in WixSharp.Suite I am still not sure how to best accomplish the following:

I am installing:

- `app.exe`
- `app-config.yaml`
- `ServiceInstaller` for windows service using:
  - app.exe as file
  - Arguments: `--config.file {AbsolutePathTo-app-config.yaml}`

There are two possible configurations for `app-config.yaml`: 
- "Config Default"
- or "Config Other"

available under different filenames (`config-default.yaml` and `config-other.yaml`) in the source directory.

I have declared a readonly project `DefaultFeature` (installdir, binary, ...)  and a second optional `Feature` "Other".

- If Feature Other is not enabled, `app-config.yaml` should be installed in the "default" config using `config-default.yaml`
- If the user selects Feature "Other",  `app-config.yaml` should be installed config using `config-other.yaml`

What is the best way to do this?

It is not possible to define "exclusive features" using radio buttons, is it? So a user can only choose one config but not both?

If I try to add the second configfile with the same `TargetFileName` I get an exception (`is installed in ... by two different components`). Also this would be dependent on execution order so the second file overwrites the first, which is risky and hacky.

Instead of "switching" the config file, I could also install both configs, and edit the start arguments of the windows-service, but the problem would stay the same.

I guess [using a FeatureCondition](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/FeatureConditions/setup.cs#L44) sounds about right?

If I define a feature "defaultConfig" I could disable it using (pseudo):
```csharp
defaultConfig.Condition = new FeatureCondition("FEATURE_OTHER = 1", level: 2); // ?
```

However I don't have a `install property` , I want to know if the Feature was selected in the gui.
But I don't know if WIX permits the same filename twice, even when a condition ensures only on of the options is used?

A possible workaround could be to use a Action / Event after installation to "manually" switch the config file to the desired configuration (Default or B) but I am sure there is a better way.

Sorry if I am overlooking the obvious solution.
Thanks in advance!

**Comment by oleg-shilo** [comment]
Hi Mario,

I let other devs, who are more fluent in WiX than I am, answer your very core questions about WiX/MSI.

Though I suggest you look at the "Custom UI" projects templates that allow you to implement ANY complicated feature selection scenario. If you create a project from these templates:
![image](https://user-images.githubusercontent.com/16729806/166107248-7992aad9-c97b-4c32-888f-6be1a76a8657.png)
You will be able to control from your Form/WPF code-behind how the user selects the features and prevent/enforce the specific combinations. 

Though, of course, it will work only with UI, which is most likely acceptable.
