### ISSUE TITLE
Start app after install leading to failed installation

### ISSUE THREAD

**Issue by ejongejans** [oleg-shilo/wixsharp#1155]
hi, 

I'm trying to start our application after installing. Somehow whatever I try it's not working. 
It's reverting the installation and I have no idea why.. 

wixproject = new Project(w.ProductName);
wixproject.AddAction(new ManagedAction(
                CustomActions.StartAppAction,
                Return.check, 
                When.After,
                Step.InstallFinalize, Condition.NOT_Installed));

//the below does give me the question; but it's not being started and the install is being reverted as unsuccesfull.... 

[CustomAction]
public static ActionResult StartAppAction(Session session)
 {
            string exeName = session["INSTALLDIR"] + session.Property("WAssemblyName") + ".exe";
            if (DialogResult.Yes == MessageBox.Show("Would you like to start the program?" + Environment.NewLine + Environment.NewLine + exeName, "Start", MessageBoxButtons.YesNo))
            {
                System.Diagnostics.Process.Start(session["INSTALLDIR"] + exeName);
            }
            return ActionResult.Success;
}

**Comment by oleg-shilo** [comment]
I suggest debugging. If your custom action failed to start the process it also failed your installation.

Most likely you want to start the app but not fail the install in case of failure. I am only guessing.
Thus consider using `AfterInstall` event instead:

```C#
project.AfterInstall += args =>
{
    if (!args.IsUninstalling)
        Process.Start(args.InstallDir.PathJoin("app.exe"));
};
```

**Comment by ejongejans** [comment]
mm thx. I switched it to ManagedProject. But somehow my  args.Session.Property("WAssemblyName") variable is empty in the AfterInstall event. (i'm sure i've assigned it). Is this variable available in this event? I see some other code examples here and there where it's used. But also remember reading something about it not being available after install?

wixproject.AfterInstall += args =>
            {
                if (!args.IsUninstalling)
                {
                    string exeName = args.Session.Property("WAssemblyName") + ".exe";
                    if (DialogResult.Yes == MessageBox.Show("Would you like to start the program?" + Environment.NewLine + Environment.NewLine + exeName, "Start", MessageBoxButtons.YesNo))
                    {
                        System.Diagnostics.Process.Start(args.InstallDir.PathJoin(exeName));
                    }
                }
            };

**Comment by oleg-shilo** [comment]
That is a limitation of the MSI technology. The deferred actions like `AfterInstall` cannot access properties.
WixSharp allows working around this limitation. You can declare upfront which property you want to tunnel to your deferred action. The easiest way to do this is either to mark the property `IsDeferred=true` or indicate the same on te projectlevel:
```C#
project.DefaultDeferredProperties += ",WAssemblyName";
```
Or you can even use WixSharp own global property bag that does not have this limitation:
```c#
static void project_Load(SetupEventArgs e)
{
    e.Data["persisted_data"] = "some text";
    . . . 

static void project_AfterInstall(SetupEventArgs e)
{
    var persisted_data = e.Data["persisted_data"];
```

**Comment by ejongejans** [comment]
Hi Oleg, 

Just to confirm and for others who read this. Works great with the defaultdefferedproperties. 

Elco

**Comment by oleg-shilo** [comment]
Excellent. Thank you for letting me/us know
