### ISSUE TITLE
New versioned dll gets deleted after update

### ISSUE THREAD

**Issue by blutswende** [oleg-shilo/wixsharp#1156]
Hi,

i have a problem with a new versioned DLL by a third party from Version 20.20 to 1.0 .
After updating my software with the setup created with wixsharp, the DLL file is deleted.

In my approach before the version was changed i was using
``` 
new Dir(tesserAct, "TesserAct",
   new Files(tesserAct, @"TesserAct\*.*")),
```

now i tried following approaches because they are the only one (IMHO) which fit my purpose
``` 
var attributes = new Dictionary<string, string> {{"PatchWholeFile", "yes"}};

                    new Dir(nuance, "TesserAct",
                        new Files(tesserAct, @"TesserAct\*.*", a => !a.EndsWith(@"TesserAct\bin64\jp2k_kdu_apps_vnew.dll") && !a.EndsWith(@"TesserAct\bin64\kdu_vnewR.dll")),
                        new Dir(tesserAct, "bin64",
                            new WixSharp.File(tesserAct, @"TesserAct\bin64\jp2k_kdu_apps_vnew.dll") { Attributes = attributes, OverwriteOnInstall = true },
                            new WixSharp.File(tesserAct, @"TesserAct\bin64\kdu_vnewR.dll") {Attributes = attributes, OverwriteOnInstall = true })),
``` 

And **OverwriteOnInstall** by it's own and **attributes** by it's own.

All three approaches are deleting the DLL from the target directory.

What is the right approach for forcing the new DLL (lower version then previous) files to be installed?

regards
Florian

**Comment by StefanKoell** [comment]
I am facing the same issue. In .net 6.0.8 the System.IO.Compression.Native.dll has version 42.42.42.42424 and in .net 7-rc1 the version is 7.0.something. How can I tell MSI to still deploy the "older" version of the file and force install the lower version? Not sure why this has been closed unanswered...

**Comment by oleg-shilo** [comment]
The original question is not related to WixSharp but rather to WiX.
I never reject these questions as sometimes I am able to answer them. And sometimes the other devs/users can help too. In this case no one answered it for 4 months so I closed it. Nothing can be done by changing WixSharp to address the problem as it is about "how to use WiX attributes to force certain MSI behaviour".

Sorry, I still have nothing to offer for that. WiX guys are probably in a better position.

But I am happy to investigate / look at WixSharp if it is doing something wrong.

**Comment by oleg-shilo** [comment]
As a side note, try to look at the generated WXS file. It will give you some clue about what WiX bahavier to expect.

After all both attributes and `OverwriteOnInstall`  are simply trigger generation of the XML elements (e.g. `RemoveFile`)
