### ISSUE TITLE
How to install a shortcut into SendTo folder?

### ISSUE THREAD

**Issue by AchimBursian** [oleg-shilo/wixsharp#1157]
I'm not at all successful in installing a shortcut to the user's SendTo folder.
  new FileShortcut("AnalyzerSuite", @"[SendToFolder]")

I get a weird error:
`error LGHT0204: ICE38: Component Component.SendToFolder.EmptyDirectory installs to user profile. It must use a registry key under HKCU as its KeyPath, not a file.`

Any idea how to achieve this? I tried "[SendToFolder]", "SendToFolder", "%SendToFolder%", nothing works...

**Comment by Torchok19081986** [comment]
morning, SendTo in Windows Contextmenu , probably, RegistryValue . Try to search in Registry for SendTo. I think , you have to create there some regvalues to achive that. 
After some search i found , it shoud be .lnk fiile place to Path "C:\Users\<your username>\AppData\Roaming\Microsoft\Windows\SendTo"
