### ISSUE TITLE
DigitalySign with Keystore

### ISSUE THREAD

**Issue by digitalsigi** [oleg-shilo/wixsharp#116]
Hi Oleg,
I am using this great tool some time now and I am very satisfied.
Now I am forced to you a hardware token for code signing and thus can't use the WixSharp Build in DigitalySign anymore. In CommonTasks I found its using the standard signtool.exe which I great. I suggest to add one more optional parameter telling to use the DN or a part of it as supported by signtool.
Proposal:
```C#
static public int DigitalySign(string fileToSign, string pfxFile, string timeURL, string password, string optionalArguments = null, string wellKnownLocations = null,bool useCertificateStore=false)
        {
            //"C:\Program Files\\Microsoft SDKs\Windows\v6.0A\bin\signtool.exe" sign /f "pfxFile" /p password /v "fileToSign" /t timeURL
            //string args = "sign /v /f \"" + pfxFile + "\" \"" + fileToSign + "\"";
           // or
            //string args = "sign /v /n \"" + pfxFile + "\" \"" + fileToSign + "\"";
           string certPlace = useCertificateStore==true ? "/n" : "/f";
            string args = $"sign /v {certPlace} \"" + pfxFile + "\"";`
```

Thx
Josef

**Comment by oleg-shilo** [comment]
Good suggestion. Txs.

Done as a NuGet pre-release v1.4.7.1 
```
Install-Package WixSharp.bin -Pre
```

**Comment by digitalsigi** [comment]
Appologize the rather late confirmation.
The change works like charm. Thx.
Seasons greetings
Josef

**Comment by oleg-shilo** [comment]
Not a problem. Thank you.
