### ISSUE TITLE
Question on Bundle

### ISSUE THREAD

**Issue by Ishtiy** [oleg-shilo/wixsharp#1160]
Hello Team,
Thank you for this great library.
This is not an issue, asking for guidance.

Can you guide me on the following:
Ive have created a c# project to create a boostrapper bundle and will be moving to Wix#.

 I have a challenge to add additional files which are not part of any msi/exe in the bundle but they need to be copied to specific folder on the user machine. How can I include additional files in a bundle? 

The only way I can see is, create a msi on the fly and make that msi as last in the chain.

Any better options, can anybody suggest.
Thanks in advance.

Regards,
Ishtiy

**Comment by oleg-shilo** [comment]
You can always include any files in the resources of your assembly. Either MSI ManagedProject or Bundle UI.
This way you can copy your files from when your assembly is loaded for the execution.

But, tbh it seems like an antipattern, copying any data on the target machine while this data is not the deployment artifacts neither required for your setup application to function. Unless I misinterpreted you.

**Comment by Ishtiy** [comment]
Thank you so much.
Actually, these are customised xml files per user/customer which our app
uses. I'm creating a bundle authoring for our on field support.

We have serveral msi/exe to be installed and also deploy customised xml
config files for that customer (many locations).

Would you be able to guide me to any sample, I could refer about using
resources in Bundle, wanted to avoid creating another msi on fly for just
these files.

Also was struggling, to add ChainItems in loop, but found some samples in
old codeplex RSS feeds.

Many thanks and much appreciated 🙏

**Comment by oleg-shilo** [comment]
These two projects contain custom UI for but strapped 
![image](https://user-images.githubusercontent.com/16729806/168302030-dbbffd0c-974f-49b6-915d-1b1f4121b806.png)

As for adding and reading resources, I was referring to a trivial .NET application technique when you add a resource file to the application and then include bitmaps, binaries and strings to it:

![image](https://user-images.githubusercontent.com/16729806/168302644-c2c9bce5-dd55-4472-8f04-679ee3302c50.png)

**Comment by Ishtiy** [comment]
Once again, thank you so much 🙏

Regards
Ishtiy
