### ISSUE TITLE
WPF installDir dialog is ignoring selectedfolder

### ISSUE THREAD

**Issue by gasparovicm** [oleg-shilo/wixsharp#1162]
When installation folder is selected by "Choose file" button/dialog, then path is ignored a and text in field is not changed.
When it is typed manually it works.
WinForm version works.

**Comment by oleg-shilo** [comment]
Indeed there is a mistake in the code behind.
It is in fact works as the selected value is passed to the msi session even if the text box is not updated visually. 
But of course, it needs to be fixed.

**Comment by gasparovicm** [comment]
I see .      NotifyOfPropertyChange(() => InstallDirPath); is missing in set of property InstallDirPath in class InstallDirDialogModel. Ok. Temporary I will use my own fixed copy as custom dialog.

**Comment by oleg-shilo** [comment]
Bingo!
You can also use the WPF CustomUI project template so the source code for the dialogs will be in your codebase and put the fix there.

**Comment by oleg-shilo** [comment]
Done.
Will be available in the very next release
