### ISSUE TITLE
Wrong Installdir in BA Installer for Update / Upgrade

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1164]
Hallo, i have trouble in BA Installer. I have successfully created BA installer for Install my app at first time with msi UI set as   productProj.UI = WUI.WixUI_InstallDir.
in msi project i set to path "C:\Apps\My Company\MyApp\Tools" 
For Update i set installer UI for ProgressOnly.
But for update / upgrade msi doesnt noted already installed app in Installdir and install update always to "C:\Apps\My Company\MyApp\Tools"  even if installdir was changed by user to another path.
```csharp

   var productProj =
            new ManagedProject("MyCompany",
                new Dir(@"C:\Apps\MyCompany\MyApp\Tools",
                       new Files(filespath + @"\*.*",
                       f=>!f.EndsWith(".obj") 
                       && !f.EndsWith(".pdb") 
                       && !f.EndsWith(".txt") 
                       && !f.EndsWith(".tdb") 
                       && !f.EndsWith(".ipm")));                
     
 productProj.SetNetFxPrerequisite(Condition.Net48_Installed, "Install NET 4.8 First.");

 productProj.UI = WUI.WixUI_InstallDir;

```

For Update / Upgrade i change `productProj.UI = WUI.ProgressOnly`. 

Can some tell if it something wrong in my project description or its bug in wix toolset ?

**Comment by oleg-shilo** [comment]
I am not sure what you mean:
> For Update i set installer UI for ProgressOnly...... For Update / Upgrade i change productProj.UI = WUI.ProgressOnly

WixSharp, WiX and MSI do not support setting native UI for a specific install action.

**Comment by Torchok19081986** [comment]
morning, ok, i will try explain. if you install your product by *.msi installer als packge. first install with installdir and second install with progressonly, you can update / upgrade your product. Works without problems. 
same behaviour at BA Installer doesnt work. 
string product = productmsi.BuildMSI() 
and later add it to BA Installer.
if i add new files and set beforecreated msi package UI to progressonly, product goint to be uninstalled by msi, BUT not install in same path, doesnt memorize installdir path. Msi after uninstall install always in path like before mean C:\Apps\MyCompany\MyApp\Tools

**Comment by oleg-shilo** [comment]
Then this is something that is controlled by the Bundle upgrade model. Not sure your exact scenario is handled.

As a complete side note, installing to the custom location ("install with installdir") is rather an antipattern that always triggers headaches for the devs while often bringing very limited benefits.

**Comment by oleg-shilo** [comment]
The default bundle use case is to install all items that are not installed. Thus quite possibly Bundle does not support upgrading individual items an easy way.
But.... as I mentioned, this is a WiX/Bundle question not WixSharp. You might be able to find something there. 

As a possible direction y9ou can look at the `DetectPackageComplete` event. It may let you decide if 
you want to uninstall or upgrade (install over) a specific item
Have a look at the Bootstrapper samples
![image](https://user-images.githubusercontent.com/16729806/170996614-983e60bb-95f9-4018-9374-5a044b6b0d81.png)
