### ISSUE TITLE
Question: Calling an web API on success or failure of msi.

### ISSUE THREAD

**Issue by pr4v33nv3rm4** [oleg-shilo/wixsharp#1167]
hi,
I am in need to call an external API on the success or failure of the MSI, so what events I should be looking to know whether MSI is installed or failed?

**Comment by oleg-shilo** [comment]
```C#
var project = new ManagedProject( . . .
. . .
project.AfterInstall += e =>
{
    if (!e.IsUninstalling) // install and repair
    {
        . . .
    }  
};.
```
BTW, the event handler is already eleveted.

**Comment by pr4v33nv3rm4** [comment]
ok, thanks a lot I'll check this.

**Comment by pr4v33nv3rm4** [comment]
Sorry to open this again but need some help.
I have something like

```
project.AfterInstall += e =>
                {
                    if (!e.IsUninstalling) // install and repair
                    {
                        var response =  CallAPI("Success");
                        e.Session.Message(InstallMessage.Info, new Record() { FormatString = string.Format("Info log {0} : \n {1}", DateTime.Now, response) });
                    }
                    else
                    {
                        var response =  CallAPI("Failure");
                        e.Session.Message(InstallMessage.Info, new Record() { FormatString = string.Format("Info log {0} : \n {1}", DateTime.Now, response) });
                    }
                };
```

This works fine for the successful installation but when the installation is failed API is not getting called.
(I am redirecting the standard error from CMD as a process and if it's not empty throwing that as an exception in order to fail the installation.) 

I think "Afterinstall" will not be called on failure I guess?

**Comment by pr4v33nv3rm4** [comment]
Got it, at this moment I think the best option would be is to call the API where I am throwing exceptions in order to fail the installation.
Thanks 👍
