### ISSUE TITLE
creating desktop shortcut with always "Run as administrator" mode on

### ISSUE THREAD

**Issue by kanhaiyabaranwal** [oleg-shilo/wixsharp#1168]
My script wants that it should be run in admin mode. Obviously, it is inconvenient to ask user to always run the shortcut that triggers the script in admin mode. There is already an issue created on this - https://github.com/oleg-shilo/wixsharp/issues/302 where you suggested 

Try and see if the standard code sample (e.g. [InstallFiles](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Install%20Files)) triggers UAC on your system. It supposed to.

I tried with following on my wixsharp project but the shortcut doesn't start in Admin mode.
            project.EnableUninstallFullUI();
            project.EnableResilientPackage();
            project.InstallPrivileges = InstallPrivileges.elevated;

To me, it looks like running in admin mode is a feature of the shortcut and not of the script.

            project.FindFile(f => f.Name.EndsWith("stopApp.bat"))
           .First()
           .Shortcuts = new[]{
                    new FileShortcut("Stop MyApp","%Desktop%"){ AttributesDefinition = @"Icon=app.ico;IconIndex=0"}
                   };

Can you please suggest how to make the shortcut always run as administrator.

**Comment by kanhaiyabaranwal** [comment]
FYI, in below link, Impersonate="no" is suggested to solve this issue. In my .wxs file, it is added, but it still doesn't work.
https://www.add-in-express.com/forum/read.php?FID=5&TID=13992

**Comment by oleg-shilo** [comment]
Correct `InstallPrivileges` is expected to control your setup application (msi) buit, not the application or a shortcut you are installing.
Not sure what attribute of the Shortcut is triggering the elevation. But indeed it is controlled by the shortcut properties:
![image](https://user-images.githubusercontent.com/16729806/170998232-0ea07e36-c60a-4041-8646-7e127f55214a.png)

**Comment by kanhaiyabaranwal** [comment]
Thanks @oleg-shilo for the response. I find an indirect solution by creating a wrapper script that starts the target script in admin mode. For details, check method 4 in 
https://www.top-password.com/blog/make-your-program-always-run-as-administrator/

**Comment by oleg-shilo** [comment]
TBH seems like a too-heavy solution. 
But if you are happy with the approach, why not :)

**Comment by jjxtra** [comment]
Having same issue, just trying to add a desktop shortcut. Msi already runs as admin so bizarre that I can't create a shortcut on user desktop...

**Comment by jjxtra** [comment]
![image](https://user-images.githubusercontent.com/1271832/209711371-ec7bc7d6-8f5a-4073-ad7b-78291cbd5d57.png)

**Comment by jjxtra** [comment]
The solution is to set `project.InstallScope = InstallScope.perMachine;`

**Comment by oleg-shilo** [comment]
Excellent. Thank you for sharing the solution
