### ISSUE TITLE
Multi-Instance Installer

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#117]
I am trying to create an installer which can install multiple instances of a service. It must be able to use msiexec to pass the instance name as a parameter.

Is there any way that WIX# can handle this? Or  is the only way by using a transform file to modify the ProjectCode in the MSI database?

**Comment by oleg-shilo** [comment]
Please have a look at the samples from the distro. For example 'MultipleInstances Install'.
