### ISSUE TITLE
Building MSI error MSB3073 - exited with code 1

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#1172]
Wix Toolset v2.11.2.4516 installed. WixSharp 1.20.1.0 installed. WixSharp templates for Visual Studio installed.
I'm starting Visual Studio 2019 Community and I'm choosing WixSharp Managed Setup - Custom WPF UI template. And I'm doing Clean Solution, and Rebuild Solution. In Output I have:

Rebuild started...
1>------ Rebuild All started: Project: WixSharp_Setup61, Configuration: Debug Any CPU ------
Restored h:\4me\WixSharp\WixSharp_Setup61\WixSharp_Setup61.csproj (in 23 ms).
1>WixSharp_Setup61 -> h:\4me\WixSharp\WixSharp_Setup61\bin\Debug\net451\WixSharp_Setup61.exe
1>Building MSI
1>'c:\tmp\tmpb4e555a154bf44d891ca09c47685c2a1.exec.cmd' is not recognized as an internal or external command,
1>operable program or batch file.
1>D:\Users\slawek\.nuget\packages\wixsharp\1.20.1\build\WixSharp.targets(5,5): error MSB3073: The command ""h:\4me\WixSharp\WixSharp_Setup61\bin\Debug\net451\WixSharp_Setup61.exe" "/MSBUILD:WixSharp_Setup61" "/WIXBIN:" "/Configuration:Debug" "/Platform:AnyCPU"" exited with code 1.
1>Done building project "WixSharp_Setup61.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

But when I'm runing from CMD in folder h:\4me\WixSharp\WixSharp_Setup61 this command:
bin\Debug\net451\WixSharp_Setup61.exe
I've got MSI.

Sorry, I don't know what to ask. So - how to got the MSI calling build in VS?

**Comment by oleg-shilo** [comment]
While it is most likely unrelated, please try to upgrade your WiX toolset to the version that WixSharp was tested with (v3.11.2.0). v2.* may have some surprises.

The error seems to indicate that the project `WixSharp.targets` (part of WixSharp nuget package) is not executed correctly.
So I suggest you either remove it from your project manually or delete `WixSharp` nuget package but leave `WixSharp.bin`. Then you can simply call your `WixSharp_Setup61.exe` from the post-build event.

`*.targets` does exactly that. runs the exe after it is built.

It's hard to say why `*.targets` does not work.  Just in case I have installed the latest templates on my VS2019 and it built msi correctly so I am not sure about the cause of your problem. But that simple workaround will unblock you.

**Comment by sadam2** [comment]
Thanks a lot for the answer. But first I have to apologize. I made mistake writing the version number of Wix Toolset. Proper value is v3.11.2.4516. Sorry.
I did a second installation on a different machine. And it works.
The situation on the first machine is unusual. I have two operating systems there - Windows 7 and Windows 10. And multiboot of course. First drive (with Windows 7) has c: on both systems.  Second (with Windows 10) has d: on both. And maybe that's a problem with the paths.
I can do the tests for you. Maybe the cause can be found. Five years ago I was doing my first installer using Wix#. And I got a lot of help from you. It's time for me to help now. Write down what I can do.

**Comment by oleg-shilo** [comment]
> And I got a lot of help from you. It's time for me to help now. 

My friend, you made my day. 😄 
Karma works in mysterious ways.
Don't get disappointed if we cannot find the cause of that VS Template problem. It happens.
You helped me already. I had a hectic start today. Now I feel better.
