### ISSUE TITLE
Install .Net 4.8 with bundle

### ISSUE THREAD

**Issue by alxcp** [oleg-shilo/wixsharp#1174]
Hello, Oleg!

Thank you for your package, I've been using it for many years and even contributed (DigitalSignature feature).
Now I am migrating from .Net 4.5 to .Net 4.8 and I experiencing a strange issue.

Wix  : 3.14.0.5722
Wix#: 1.20.1

When I'm trying to execute the bundle installer on the PC without .Net 4.8 installed I have next records in the installer log:

```
[081C:0AF4][2022-06-08T01:07:44]w343: Prompt for source of package: NetFx48Web, payload: NetFx48Web, path: C:\Users\Alex\Desktop\redist\ndp48-web.exe
[081C:0AF4][2022-06-08T01:07:44]e054: Failed to resolve source for file: C:\Users\Alex\Desktop\redist\ndp48-web.exe, error: 0x80070002.
[081C:0AF4][2022-06-08T01:07:44]e000: Error 0x80070002: Failed while prompting for source (original path 'C:\Users\Alex\Desktop\redist\ndp48-web.exe').
[081C:0AF4][2022-06-08T01:07:44]e313: Failed to acquire payload: NetFx48Web to working path: C:\Users\Alex\AppData\Local\Temp\{3B5BDCE0-7B13-4F4A-A6B4-BEC31DF60BEE}\NetFx48Web, error: 0x80070002.
[081C:0694][2022-06-08T01:07:44]e000: Error 0x80070002: Failed while caching, aborting execution.
```

I see in the original NetFX48.wxs that folder 'redist' is the root folder to search for the NetFx48Web payload:

`<WixVariable Id="NetFx48WebPackageDirectory" Value="redist\" Overridable="yes" />`

I tried to put the ndp48-web.exe in the 'redist' folder near my installer and the installation was successful.

I have already tried to include the ndp48-web.exe as payload to bundle but the result is the same.

Maybe I'm missing something, but previously I used the same way to install NetFx45Web, and everything worked as expected.
As minimum our QA accepted new installer in 2016 :)

My WixSharp bundle creation code:

  ```
          var bootstrapper =
                new Bundle(RebrandConfiguration.I.RebrandedAppName, 
                    new PackageGroupRef("NetFx48Web"))
                {
                    Version = new Version(RebrandConfiguration.I.ApplicationVersion),
                    UpgradeCode = BundleUpgradeCode,
                    DisableModify = "yes",
                    DisableRemove = true,
                    Application = new ManagedBootstrapperApplication("%this%"),
                    SuppressWixMbaPrereqVars = true,
                    Condition = "VersionNT>=v6.0",
                    Manufacturer = RebrandConfiguration.I.Manufacturer,
                    HelpUrl = RebrandConfiguration.I.ISUrlHelp,
                    AboutUrl = RebrandConfiguration.I.ISUrlAbout,
                    Variables = new[] {new Variable("InstallDir")},
                    Language = language,
                };
```

Here is my resulting bundle wxs:

```
<?xml version="1.0" encoding="windows-1251"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension" xmlns:bal="http://schemas.microsoft.com/wix/BalExtension">
  <Bundle Name="Bundle name" AboutUrl="http://sample.uri" Condition="VersionNT&gt;=v6.0" DisableRemove="yes" DisableModify="yes" HelpUrl="http://sample.uri" Manufacturer="Manufacturer" UpgradeCode="..." Version="7.7.192" >
    <BootstrapperApplicationRef Id="ManagedBootstrapperApplicationHost">
      <Payload SourceFile="Installer.WixSharp.exe" />
      <Payload SourceFile="BootstrapperCore.config" />
      <Payload SourceFile="..\..\Build\Debug\Microsoft.Deployment.WindowsInstaller.dll" />
    </BootstrapperApplicationRef>

    <Variable Name="InstallDir" Persisted="yes" />

    <Chain>
      <PackageGroupRef Id="NetFx48Web" />

      <MsiPackage Id="Package" DisplayInternalUI="yes" Visible="yes" SourceFile="..\..\Build\Setup-7.7.192.msi">
        <MsiProperty Name="INSTALLDIR" Value="[InstallDir]" />
        <MsiProperty Name="COMMANDLINELOCALE" Value="[CommandLineLocale]" />
        <MsiProperty Name="WIXBUNDLEORIGINALSOURCE" Value="[WixBundleOriginalSource]" />
      </MsiPackage>
    </Chain>
  </Bundle>
</Wix>
```

**Comment by oleg-shilo** [comment]
Hi Alexey, 
> ...even contributed (DigitalSignature feature).

I do remember you :)

As for the problem you are experiencing, I do not have the answer. Your wxs seems to be quite OK.

My understanding is that the whole wiring of the payloads/downloadables and path probing is defined in the `NetFx48Web` and there is something that is not right there.

The way out of this problem can be altering the `NetFx48Web` file and building the bundle with it. You started moving in this direction. Probably not the ideal solution but may work. 

Interestingly enough this post is talking about an alternative DIY `NetFx48Web` implementation: https://stackoverflow.com/questions/70202643/wix-burn-bootstrapper-installing-net-framework-as-payload. There is a chance they had the similar problem.

Hope it helps. 

And of course... Слава Українi!

**Comment by alxcp** [comment]
Героям Слава!
I, my wife, and my children are safe if there are safe places in Ukraine at all.
I have read every link on the topic, including this one.
Replacing the file was the first thought that came to my mind, but I haven't found a working way to replace it yet.
I'll try.

By the way, what about Digital Signature.
The next release of Win11 will include a new version of the Smart App Control. If Smart App Control switched to the 'On' state it strictly requires that every single binary in the installer is signed, including the content of the sfxCA.dll (Managed Custom Actions binary), and itself sfxCA as well. Also, ManagedBootstrapperApplication should be signed.
I tried Windows Insider Preview version of the Win11 and found that a lot of the existing installers will be affected. I even can't install the 7zip for example.

For now, I found relatively dirty workaround - I'm allowing wixsharp to do all its job, after that I manually generate sfxca.dll through MakeSfxCA.exe with signed content, than sign sfxca.dll and replace the target file directly in the MSI to the signed one, then re-signing the MSI. Some other payloads also require hacks.

I will prepare a Pull Request with a clean solution for signing the necessary binaries during wixsharp compilation if I find timeslot.

**Comment by alxcp** [comment]
I think I've figured it out.

This functionality in Wix is ​​broken by Microsoft.
I already met such complaints, but I did not think that the problem was still relevant.

Each new build of the framework is posted by Microsoft via the same link.
WixFxNet{version}.wxs describes the current build of the framework (hash, size, etc.), and RemotePayLoad becomes obsolete when an update to the framework is released.
I'm only surprised that there are no RemotePayLoad check errors in the installer log.

I checked the current WixFxNet48.wxs on GitHub and it's already out of date.

The second problem is that my installer is built on CustomSilentBA and doesn't have its own interface. Until the moment when it comes to our MSI, the user does not see anything, and downloading the framework takes a lot of time, during which the installer does not show signs of life. 
And, worse, the installation of the framework requires a reboot, and is better to warn the user about that before starting the installation of the application.

Therefore, I decided to add a form to my Bootstrapper that is shown if the required version of the framework is missing. 
This form will have warnings, explanations, a cancel button and a ProgressBar of the framework installer downloading process.
I know it sounds like a workaround, but we got into this situation so unexpectedly on the eve of the release that we need a quick and working solution.

**Comment by oleg-shilo** [comment]
That's quite disappointing. But, well, I am afraid there is not much that we can do. :(

 As for CustomSilentBA, I agree that while it may seem like a good option having no way to communicate the progress or even startup failures o the user is problematic. Having minimalistic UI is completely warranted. Thus I think your solution is pragmatic enough.
 
 The same applies to the first problem (WixFxNet48.wxs). If you cannot reliably download the framework it is better to recognize and accept the limitation and let the user to deal with it.
 
 Though in this case you kind of don't need a bundle and can simply put a prelaunch condition in your msi where you cjheck the presence of the required .NET distro. Am I right?
 
================

 > I, my wife, and my children are safe if there are safe places in Ukraine at all.
 
My mam and all my relatives are in Kharkiv. So I know the filling. I wish your family a safe ending of this nightmare.

**Comment by alxcp** [comment]
> Though in this case you kind of don't need a bundle and can simply put a prelaunch condition in your msi where you cjheck the presence of the required .NET distro. Am I right?

We are releasing the MSI for some cases (mass deploy through AD), but our main release must be executable - all integrations are built on this, so wee need the bundle, it doesn't matter that we can do an installation without it.
I have almost implemented the progress window in Custom BA and the PO has approved a new type of installer, so this problem can be considered solved.

> ================
> My mam and all my relatives are in Kharkiv. So I know the filling. I wish your family a safe ending of this nightmare.

I have relatives scattered all over the country. Worst of all, my parents and sister with niece - got stuck near Melitopol. Fortunately far enough from the current and supposed future battlefields. 
I believe in the victory of Ukraine.
Good luck and thank you for your support!

**Comment by oleg-shilo** [comment]
> I believe in the victory of Ukraine.
So do I, my friend. With all my guts!
Reach me if you need any help. We are connected on Linkedin.
