### ISSUE TITLE
How to create a component selection step in the installer

### ISSUE THREAD

**Issue by Zerpico** [oleg-shilo/wixsharp#1176]
How do I create an installer where there will be a step to select components to install?

Like this:

[x] Base components
[x] Plugin1
[ ] Plugin2

[Back]  [Next]  [Cancel]

This action should specify which files to unpack into INSTALLDIR.<br>
Or it could be launching other MSI files of selected components.

Is it possible?

**Comment by Torchok19081986** [comment]
Morning, i found following link https://assist-software.net/blog/how-build-custom-installation-package-bundle-using-wpf-prism-mef-and-wix for custom BA Installer. Is pure Wix. You can here add or customize your needs . Just dont know how to do it in Wixsharp. Too much Info at same time.

**Comment by oleg-shilo** [comment]
You have two options. You can install your components as features of the single msi and let users select the required features.

if your components are in fact msi files then you need a bootstrtapper. The example @Torchok19081986 has shared is the bootstrapper custom UI (BA) sample.  

WixSharp supports WiX Bootstrapprer and comes with the sample for the custom BA.
![image](https://user-images.githubusercontent.com/16729806/175315811-bc7a9b77-40b0-43ad-a43d-3d3e8d4f8f59.png)

You will need to build your UI with the component selection dialog and then in the `void OnDetectPackageComplete(object sender, DetectPackageCompleteEventArgs e)` method you will be able to enable/disable specific component based on te user selection.

**Comment by Zerpico** [comment]
I build this project and get default UI

![image](https://user-images.githubusercontent.com/6038354/176924798-bbadcbcd-70c3-48be-939c-6a2dce6f8322.png)

**Comment by Zerpico** [comment]
My fault. I realized what I was doing wrong.
I will try to make a bootstrap with a component selection step

**Comment by Zerpico** [comment]
> You will need to build your UI with the component selection dialog and then in the `void OnDetectPackageComplete(object sender, DetectPackageCompleteEventArgs e)` method you will be able to enable/disable specific component based on te user selection.

I tried to custom boottrap UI, but I don't understand how to enable or disable the component.
And the progress event does not work in BootstrapperApplication
```csharp
this.Bootstrapper.Progress += (_, ea) =>
{
    this.LogEvent("Progress", ea);
    // Update progress
    RunOnUIThread(() =>
    {
        this.LocalProgress = ea.ProgressPercentage;
        this.GlobalProgress = ea.OverallPercentage;
    });
};         
this.Bootstrapper.ExecuteProgress += (_, ea) =>
{
    this.LogEvent("ExecuteProgress", ea);
    // Update progress
    RunOnUIThread(() =>
    {
        this.LocalProgress = ea.ProgressPercentage;
        this.GlobalProgress = ea.OverallPercentage;
    });
};
```
