### ISSUE TITLE
Creating MSI log all the time

### ISSUE THREAD

**Issue by kanhaiyabaranwal** [oleg-shilo/wixsharp#1179]
MSI log file is generated when you click on "view log" after installation completes. If it's not clicked, it is not generated. Is there a way to generate the log all the time in %temp%\Wixsharp directory or any where else.

**Comment by kanhaiyabaranwal** [comment]
Can someone respond on this please

**Comment by oleg-shilo** [comment]
You need to run your msi via `mesiexc.exe` 
It is a standard way of generating logs.
Run `msiexec.exe` and see all the options it supports. One of them is for logging.

**Comment by kanhaiyabaranwal** [comment]
sure. thanks.

**Comment by RachelXGanon** [comment]
_If it's not clicked, it is not generated._
It is, and saved in the temp folder
https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/enable-windows-installer-logging

**Comment by oleg-shilo** [comment]
yes but only if you pass the new path to the process that is running the msi - msiexec.exe
If you do not (e.g. just double-click the msi file) then msiexc runs without custom args so the log goes to the default folder.
Interestingly enough the custom UI provided by WixSharp offers you the ability to intercept the log messages and show them from the exit dialog

**Comment by RachelXGanon** [comment]
Yeah,
but can I like, have the file saved in the installation folder instead of the temp?
Or it's only to run copy command?
