### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#118]
I am trying to do the following in a ManagedForm Dialog to write to an install log:

` MsiRuntime.Session.Log("Test Log Entry");`

when i run the the following:

`msiexec /i "c:\ExampleInstaller.msi" /l*v c:\install.log /qn `

No  log entry shows. 

Is this what the MsiRuntime.Session is for?

**Comment by oleg-shilo** [comment]
Yes you can log with the session object. This is the fragment form `Wix# Samples\DTF (ManagedCA)` sample:

```C#
[CustomAction]
public static ActionResult MyAction(Session session)
{
    MessageBox.Show("Hello World! (CLR: v" + Environment.Version + ")", "Embedded Managed CA (" + (Is64BitProcess ? "x64" : "x86") + ")");
    session.Log("Begin MyAction Hello World");

    return ActionResult.Success;
}
...
msiexec /i CustomActionTest.msi /L setup.log 
```
![image](https://user-images.githubusercontent.com/16729806/29102584-88cefab8-7cfd-11e7-89bb-11dc68902013.png)

The best approach for you would be to clone the source and start exploring the samples.

**Comment by johnferry0** [comment]
Thanks for the quick feedback i will try this out.

**Comment by onefreddy** [comment]
hi, faced the same problem

```
    public partial class InstallWebsitesConfigureDialog : ManagedForm
    {
        ///init class and dialog collapsed

        void next_Click(object sender, System.EventArgs e)
        {

            MsiRuntime.Session.Log("Test1 my log");
            MsiRuntime.MsiSession.Log("Test2 my log");
            Runtime.Session.Log("Test3 my log");

            Shell.GoNext();
        }

    }
```

I have tried three methods and none of them work. The final log file does not contain the lines I am writing. I don't need CustomAction. I have to write from a form.

**Comment by oleg-shilo** [comment]
It's a tricky one.

MSI setup logging is controlled by supplying the corresponding CLI args to the `msiexec`:
```
msiexec /i "path_to_msi" /log "pass_to_log_file.log"
```
If you run your UI setup his way all your log messages will appear in the log file as expected. 

However, if you do not provision logging (via `msiexec`) then effectively logging is disabled and WixSharp UI simply maintains the virtual stack of all log messages intercepted by the handler of the MSI installation messages. And in your case, you log your messages before the installation stated so the log message is not intercepted.

While it is not strictly speaking a mistake, it is definitely inconvenience. 

I am changing this issue into the feature request and will find a way to intercept log messages even if they are sent before the installation starts.

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release.
The VS project templates are also updated to ensure the complete log content

**Comment by onefreddy** [comment]
@oleg-shilo thanks! this is a very useful update
