### ISSUE TITLE
Installer not responding

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1181]
Hi, I'm trying to install the msi, but the msi freezes(see image below), It's specific on one platform, (No clue why)
![image](https://user-images.githubusercontent.com/89771659/174842146-cb30153c-4998-4da1-8613-32fa0b2f4b71.png)
While running on:
- silent mode "msiexec /i setup.msi /qn /quiet"
- silent mode with error handling : "msiexec /i setup.msi /qr " 
 it's not produced,

on the log file it showed it stuck on until I closed the installer by the task manger:
```
MSI (c) (78:64) [14:13:00:259]: Machine policy value 'MsiDisableEmbeddedUI' is 0
MSI (c) (78:64) [14:13:00:259]: EEUI - Running MsiEmbeddedUI code
MSI (c) (78:B8) [14:13:00:305]: Cloaking enabled.
MSI (c) (78:B8) [14:13:00:305]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (78:B8) [14:13:00:305]: Connected to service for CA interface.
SFXCA: Extracting embedded UI to temporary directory: C:\Users\ADMINI~1\AppData\Local\Temp\MSI12721
SFXCA: Binding to CLR version v4.0.30319
MSI (c) (78!84) [14:13:00:828]: PROPERTY CHANGE: Adding WIXSHARP_MANAGED_UI property. Its value is 'WixSharp.UI, Version=1.20.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2'.
MSI (c) (78!84) [14:13:01:015]: PROPERTY CHANGE: Adding WIXSHARP_MANAGED_UI_HANDLE property. Its value is '591654'.
Cannot attach ManagedUI: Microsoft.Deployment.WindowsInstaller.InstallCanceledException: Exception of type 'Microsoft.Deployment.WindowsInstaller.InstallCanceledException' was thrown.
   at WixSharp.ManagedUI.Initialize(Session session, String resourcePath, InstallUIOptions& uiLevel)
SFXCA: Initialization canceled by user.
```
Thank You!

**Comment by RachelXGanon** [comment]
@oleg-shilo that's a critical bug for us, do you an idea what's going on?
Thank You

**Comment by RachelXGanon** [comment]
This issue also produced as I create a default `Managed Setup - Custom UI`

**Comment by RachelXGanon** [comment]
If I create project `Wixsharp Setup ` it works fine.
@oleg-shilo  can you elaborate? 
Thanks a lot!

**Comment by oleg-shilo** [comment]
Hi Rachel, 
The stack trace does not show anything specific. 
I suggest you debug your project and see what causes the problem. I can have a look at it but you will need to provide the test case that can be executed outside of your environment. I am not sure you can do that but it's great if you can. 

I just tested the silent options for the "CustomUI.Sequence" sample project and they work as expected.

Debugging on your environment is arguably the easiest option. Just attach the elevated debugger to the msiexec you are running. You can even put an assertion to your first dialog constructor.

**Comment by RachelXGanon** [comment]
@oleg-shilo  - Thanks for your response!
can you please elaborate what do you mean by _attach the elevated debugger to the msiexec you are running._?
Thank You!

**Comment by RachelXGanon** [comment]
Should I have a specific version of .net to be installed on the system?

**Comment by oleg-shilo** [comment]
Yes .NET needs to be installed, but since it is part of the windows I do not expect that you need to install some other versions. Unless it is what your product being installed requires.

WixSharp is relying on WiX for executing managed CA. Thus you will be able to find on WiX site what is the .NET version required.

Saying that, Managed UI is implemented as WinForm without the use of any exotic stuff. Thus any .NET framework will do. And since you have the top-level form displayed there is no problem starting your MSI

**Comment by RachelXGanon** [comment]
Hi Oleg,
Currently debugging, but interesting note -> 
while compiling the `Managed Setup - Custom UI` on .Net framework 3.5 the issue isn't produced.(e.g msi works fine.)

while compiling on higher version I got `ValidateAssemblyCompatibility` warning.
Does it make sense to you?

**Comment by RachelXGanon** [comment]
The debugger isn't hitting.

**Comment by oleg-shilo** [comment]
You can put the assertion in your code to assist with attaching the debugger

**Comment by RachelXGanon** [comment]
Hi,
I couldn't debug the dialogs because I'm using like that:
```
project.ManagedUI.InstallDialogs
                                      .Add<WixSharp.UI.Forms.WelcomeDialog>()
                                      .Add <WixSharp.UI.Forms.LicenceDialog>()
                                      .Add <WixSharp.UI.Forms.ProgressDialog>()
                                      .Add <WixSharp.UI.Forms.ExitDialog>();
```

I can tell that after few mins and several hysterical enter presses the license dialog has launched. No welcome dialog :(

**Comment by RachelXGanon** [comment]
After some more debugging I've got only 3 lines in my code:
Working version, First dialog is the license:
```
 var installer = new ManagedProject("ProjectName")   { GUID = new Guid("Guid") };
  installer.BuildMsi();
```
         
Not working version:
```
 var installer = new ManagedProject("ProjectName")   { GUID = new Guid("Guid") ,  **ManagedUI = ManagedUI.Default**};
  installer.BuildMsi();
```

**Comment by RachelXGanon** [comment]
@oleg-shilo  - Any idea?
Thank You!

**Comment by oleg-shilo** [comment]
>I couldn't debug the dialogs because I'm using like that:

Not sure why. You said "I create a default Managed Setup - Custom UI", meaning your project has the code for all dialogs.
So you can put the breakpoint in your welcome dialog constructor. Even better put there `Debug.Assert`
When assertion is fired attach the elevated debugger to the running instance of msiexec.exe that is displaying the assertion. Click continue in the asssertion box and it will bring you to your source code.  From that point you are debugging.

That's it. 

One warning. You should not attach the debugger from the assertion box but from VS. It should not make any difference but it does :(
