### ISSUE TITLE
Last Stage returns error code -532462766

### ISSUE THREAD

**Issue by mbarnet** [oleg-shilo/wixsharp#1182]
Don't know if this is a WIX error code or a WixSharp one. It prevents the last stage process from running correctly and throws this return code -532462766.

**Comment by oleg-shilo** [comment]
You can probably answer this question by debugging the setup app at the "LastStage". I am not sure what exactly it is in your case but assume you can assert in "AfterInstall" event and it will break the execution before that return code is produced.
