### ISSUE TITLE
add CA from External Assembly throw Error

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1183]
Hallo , i have a trouble to add CA from external Assembly in ManagedUI . I added just like in sample 
```csharp
new ManagedAction(CustomActions.MyAction)
{
  ActionAssembly = typeof(CustomActions).Assembly.Location,
});
```

Also created defaultdeferedproperties just like

```csharp

 msiproject.DefaultDeferredProperties = ",WINUSER,WINPWD,WINDOMAIN" 
```
and added Assemblies to project in

```csharp
 project.DefaultRefAssemblies.Add(path + "\\mylibrary.dll");
```

But msi Log throw Error 1723. There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run.

Can someone please help me ?

**Comment by oleg-shilo** [comment]
You may want to use the corresponding code sample as a starting point and add the product-specific functionality on top of it. 
![image](https://user-images.githubusercontent.com/16729806/176660670-fa96282f-11ea-41f4-9745-feaca625a74b.png)

**Comment by Torchok19081986** [comment]
many Thanks , Oleg.  I found my problem. After successfully compilied external dlls and some time later msi.  Problem was , msi was reference to old version of dlls, not newest ones.  is there posibility in wix#  , to copy content from  path to current project, like in visual studio build post and prebuild events ?

**Comment by oleg-shilo** [comment]
Of course. It is C#. You can do anything.

```C#
// copy your files here

var project = new ManagedProject(....
```

**Comment by Torchok19081986** [comment]
morning, thanks Oleg , again.  Cant i just copy all files from path to path in WixGenerated Event or it impossible during msi generate ? after that close question, pls.

**Comment by oleg-shilo** [comment]
If you need these files to generate WiX files (and then msi) then you should do it before WiX is generated and `WixGenerated` is too late for that. So you need to do it before. Like in that pseudocode in above
