### ISSUE TITLE
Uninstall the installer in CLI NON-silent mode show windows default UI

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1185]
Hi,
while installing via the CMD(e.g `msiexec /x <path_to_msi>`)
windows default UI is opened instead of the installer UI.

Running with `msiexec /x <path_to_msi> /qf` open the default windows UI as well.
Is there a way to run the uninstall via the CMD and get the installer UI?
Thank You!

**Comment by oleg-shilo** [comment]
No, MSI as a deployment technology does not allow any customisation of uninstall UI. You can only customise installation and repair/modify scsnatios.

**Comment by RachelXGanon** [comment]
Got it :)
Thanks @oleg-shilo !
