### ISSUE TITLE
Use Condition to decide display page

### ISSUE THREAD

**Issue by Dawid128** [oleg-shilo/wixsharp#1186]
Hi, 

What is the best way to display page only if condition are true ? 
What I want achieve is displaying page "Configuration" but only if application is installing first time. In other case page should be skip. 

Now I am using .ManagedUI.InstallDialog, but I not found solution to dynamic decide if customize page should be displayed.. 
The second way what I found is .CustomUI but in this case I have a small problem with create custom page (I prefer WPF)

**Comment by Torchok19081986** [comment]
morning, dont know if this helps. 
first , try to get value of your application in beforeinstall by appseach.  if appsearch doesnt find your application by project.guid or name, you can set your custom public property like example SHOWCUSTOMPAGE to true or false.  
good point for research is, if msi try to set values for features. maybe here you can find some info. if possible somehow. 

if not you can try burninstaller, with BA installer as WPF you can control your installer (not displayinternallUI, cause land standing bug in wix toolset). 

best regards. Torchok
