### ISSUE TITLE
Heat Failure

### ISSUE THREAD

**Issue by JRFoulkes** [oleg-shilo/wixsharp#1187]
Hi,

I am trying to add a VS project output but get the following:

> Unhandled Exception: System.Exception: 'Heat' failure...
> 1>   at WixSharp.Harvester.AddProject(VsProject project)
> 1>   at WixSharp.Harvester.AddProject(String projectPath)
> 1>   at WixSharp.Extensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
> 1>   at WixSharp.HarvesterExtensions.AddVsProjectOutput(Project project, String[] vsProjects)
> 1>   at eQuipInstaller.Program.Main() in C:\Repos\source\IP2\4.0\Solutions\IP2\Installer\Program.cs:line 14
> 1>C:\Users\User\.nuget\packages\wixsharp\1.19.0\build\WixSharp.targets(5,5): error MSB3073: The command ""C:\Repos\e-source\IP2\4.0\Solutions\IP2\Installer\bin\Debug\net48\Installer.exe" "/MSBUILD:Installer" "/WIXBIN:" "/Configuration:Debug" "/Platform:AnyCPU"" exited with code -532462766.
> 

It is a winforms project, .net 4.8.

Any help would be appreciated, thanks.

**Comment by oleg-shilo** [comment]
Sorry, I overlooked this message. 
Now it's probably too late. 
`WixSharp.Harvester` is a later addition to the WixSharp functionality. It use `heat.exe` to aggregates VS project outputs. Most likely some of the parameters that are passed from your code are upsetting `heat.exe`. If you look at the console output you will find `heat.exe` specific (not WixSharp) output with the details of the error.
