### ISSUE TITLE
ModifyDialogs behavior

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#119]
I have created a BackupDialog that is intended for backing up configuration files on uninstalls or upgrades. It allows for a user to select a backup location.

```
project.ManagedUI.ModifyDialogs
                .Add<MaintenanceTypeDialog>()
                .Add<BackupDialog>()
                .Add<ProgressDialog>()
                .Add<ExitDialog>();
```
When the installer is run manually and Remove is chosen, the installer navigates to the BackupDialog and works as expected.

When i try to do the following:
`msiexec.exe BACKUPDIR="d:\backups" /q /x "ExampleInstaller.msi"`
("BACKUPDIR" is a project property)

It uninstalls the product and completely skips the backup process. Is there a way to allow for this Dialog to still work on uninstall in silent mode?

**Comment by oleg-shilo** [comment]
I assume that the "backup process" is something you have implemented in your `BackupDialog`. If it is the case then it's a wrong approach as MSI doesn't execute any of the "UI Sequence" steps on uninstall. This is just how MSI works. This is the reason why one cannot have custom UI for uninstalling.

If you ask me, a backup activity does not belong to the deployment domain at all. It is a part of the  application domain and I would completely remove it from the setup.

**Comment by johnferry0** [comment]
A fair point about the backup activity.

**Comment by oleg-shilo** [comment]
BTW having anything (not only backup) in the UI sequence  is questionable and not only with respect to uninstall action. MSI install may be triggered in a completely silent mode and none of the UI actions will be invoked in this case. Thus if you really have to have some activity integrated with UI then you need to use UI only as a user triggered event to invoke the activity (e.g. CustomAction). And this very activity should be invoked automatically in case of non-UI execution. 

'ManagedEvents' sample deals with this scenario.
