### ISSUE TITLE
ServiceInstallers property initialization can cause null reference

### ISSUE THREAD

**Issue by Bram-Boris** [oleg-shilo/wixsharp#1190]
Hi,

With the 1.18.1 release it became possible to define multiple services for a single file using the new ServiceInstallers property.
The ServiceInstaller property which still works but behaves a little bit differently in regards to initialization.

With the following code the `set` of ServiceInstaller could be called with a `null` value if `SomeCustomVariable` was `null` and this would insert an `null` in the ServiceInstallers collection.
```csharp
file = new File(sourceFilePath)
{
	ServiceInstaller = SomeCustomVariable?.SomeCustomMethodThatCreatesAnServiceInstallerInstance()
};
```
Of course this is preventable with if statements on our part but maybe it is an improvement to verify the value that is inserted beforehand, instead of failing later on when it loops through the ServiceInstallers when processing the files.
If needed/wanted I can submit a PR.
https://github.com/oleg-shilo/wixsharp/blob/998e67e76f4114093cc7a2362413e06f5b74b01b/Source/src/WixSharp/File.cs#L172-L180

https://github.com/oleg-shilo/wixsharp/blob/3fbf34769fced52cb90d3215a16a2b1e80033a09/Source/src/WixSharp/Compiler.cs#L1738

**Comment by oleg-shilo** [comment]
Agree. Your proposal makes sense.
Please fire the PR and I will merge it right away.
Txs for your contribution
