### ISSUE TITLE
Additional msi package doesn't get installed on modify

### ISSUE THREAD

**Issue by AwesomeM4rc** [oleg-shilo/wixsharp#1192]
Hello :)

I have a problem with the installation of a additonal msi package (msiServiceToolPackage). 

`var msiServiceToolPackage = BuildServiceToolPackage(assetRepository.GetAssetPath(ProductInfo.ServiceTool));`
`var bootstrapper = new Bundle(ProductInfo.Name, msiPackage, msiServiceToolPackage);`

This is my code for the msi package:

      private static MsiPackage BuildServiceToolPackage(string assetPath)
      {
         return new MsiPackage(assetPath)
                {
                   Name = Path.GetFileName(assetPath),
                   Permanent = false,
                   ForcePerMachine = false,
                   Vital = false,
                   InstallCondition = Condition.Always & new Condition("INSTALLALLSCANNERPLUGINS=\"True\""),
                   Visible = true,
                   EnableFeatureSelection = false,
                   DisplayInternalUI = false,
                };
      }

The InstallCondition evaluates to **true** when the Feature "INSTALLALLSCANNERPLUGINS" is selected in the Installation proccess. 
This works perfectly fine if the application gets installed for the first time and the feature was selected. -> The ServiceTool msi package gets installed. 

But if the feature "INSTALLALLSCANNERPLUGINS" wasn't selected on the initial installtion (-> The ServiceTool msi package is not installed) and somebody uses the modify option and selects the feature, then the additional msipackage "ServiceTool" dosen't get installed. I expected it to get installed.

In the installer log file the condition evaluates to true, but the package dosen't get planned it stays as absent:

> [41E8:3D00][2022-07-26T13:10:51]i052: Condition '( (1)  AND INSTALLALLSCANNERPLUGINS="True")' evaluates to true.
> [41E8:3D00][2022-07-26T13:10:51]i201: Planned package: ServiceTool.msi, state: Absent, default requested: Absent, ba requested: Absent, execute: None, rollback: None, cache: No, uncache: No, dependency: None

Is this the normal behaviour? Didn't really find any simillar problems with a solution or explanation for it.

**Comment by AwesomeM4rc** [comment]
It seems like that the modify dosen't request the install of packages by default, you have to set it manually during the planning.

I found this on stackoverflow: https://stackoverflow.com/questions/60613712/how-to-add-package-in-modify-mode-via-wix-boostrapper

> During LaunchAction = "Modify", the engine does not install packages by default. You can see that by the default requested: Absent part of the log. If a custom BA wants to install a package during Modify, it needs to change the requested state during Plan (using the pRequestedState parameter of the OnPlanPackageBegin method). Note that changing the default state can lead to unwanted scenarios such as installing packages while the bundle is being uninstalled, so test thoroughly.

So i attached a method (PlanPackageBegin += OnPlanPackageBegin) to the PlanPackageBegin to set the requestet state of the package: 

     private void OnPlanPackageBegin(object sender, PlanPackageBeginEventArgs e)
      {
            if (e.PackageId == "ServiceTool.msi"
                && Engine.StringVariables["INSTALLALLSCANNERPLUGINS"] == "True"
                && _plannedAction == LaunchAction.Modify)
               {e.State = RequestState.Present;}
            return;
       }

Seems to be the solution to this problem.

**Comment by oleg-shilo** [comment]
Thank you for sharing your solution
