### ISSUE TITLE
How not to overwrite a file if it exists in INSTALLDIR

### ISSUE THREAD

**Issue by Zerpico** [oleg-shilo/wixsharp#1193]
How can i not rewrite `file1.txt` if during the update when the msi is installed in the INSTALLDIR directory.

**Comment by oleg-shilo** [comment]
It might be some WiX attribute available for that. Don't really remember. But if this is the case, then you can add the attribute to the `File` instance via the `File.AttributeDefinition` property.

**Comment by Zerpico** [comment]
I found
```
var licFile = new File("file1.txt") { NeverOverwrite = true };
```
