### ISSUE TITLE
Question: How to install Font if it not installed in CustomUI

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1195]
Hallo, i have a trouble to install .ttf File on Targetsystem. In Samples Folder of 1.20 Version exits Description, but if i try to install it , msi doesnt install it at all.  It looks like "%Fonts%" cant be found on Targetsystem.

**Comment by oleg-shilo** [comment]
`%Fonts%` is a WixSharp convention that is translated to WiX folder name for fonts `FontsFolder`. Thus `%Fonts%` the system never tries to find `%Fonts%` on the target system.
If the translation is not happening in your case then it can be the cause of the problem. I have checked the samples and the wxs file is generated correctly:

![image](https://user-images.githubusercontent.com/16729806/183245727-516ad0f3-72b6-48d0-8667-2cd2d8221599.png)

Can you check this on your side?

**Comment by Torchok19081986** [comment]
morning, i have just checked .wxs file in installfolder.  All Items for tts File correct, just like in your descrption. I change some description of install ttf file of targetsystem. From Dir("%Fonts%") new File ("myFont.ttf") to one with AtributeDefinition = "TrueType=yes" and it works. Ttf File was installed correctly on targetsystem.
