### ISSUE TITLE
Question: Multiple Instance install MSI coupled with bootstrapper?

### ISSUE THREAD

**Issue by tblong** [oleg-shilo/wixsharp#1199]
Currently I'm using wixsharp to install a windows service based project just fine.  I have a need to convert this MSI to support multiple install instances and intend on using your example [MultipleInstances Install](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/MultipleInstances%20Install) to get me started.  

As shown in the example above, the user would have to know how to run the MSI with the correct transform identified.  I would instead like to create a bootstrapper with a simple UI in order to make it easier on the user to select the exact settings which would map to a given transform ID.  Then my bootstrapper would be the one calling `msiexec` with the correct parameters.  Am I heading down the correct path with this or is there a better way?

Edit 2022-09-07:
After some additional research looking into creating a custom bootstrapper WPF based UI with the [WixBootstrapper_UI](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/WixBootstrapper_UI) example, what I have not figured out yet is whether I'll have the ability in any of the events or overridable methods in `BootstrapperApplication` to add the `TRANSFORMS=":SomeTransformID"` argument for when it comes time for the bootstrapper code to call `msiexec` on my bundled MSI.  In short, I still need to figure out whether it is possible to customize the bootstrapper side to set the `TRANSFORMS` property at runtime where a given transform ID is prebaked into my MSI at build time.

## Possible solution 1?
What if the following build setup was on the bootstrapper side?

```csharp
var bootstrapper =
  new Bundle("MyProduct",
	  new PackageGroupRef("NetFx40Web"),
	  new RollbackBoundary(),
	  new MsiPackage(productMsi) { MsiProperties = "TRANSFORMS=[TRANSFORMSFROMBOOTSTRAPPER]" });
```

The above generated the following `<chain>` section in the .wxs file for the bootstrapper:
```xml
<Chain>
  <PackageGroupRef Id="NetFx40Web" />

  <RollbackBoundary />

  <MsiPackage SourceFile="wix\MyProduct.msi">
	<MsiProperty Name="TRANSFORMS" Value="[TRANSFORMSFROMBOOTSTRAPPER]" />
	<MsiProperty Name="WIXBUNDLEORIGINALSOURCE" Value="[WixBundleOriginalSource]" />
  </MsiPackage>
</Chain>
```
For the possible solution above, does the above mean that the bootstrapper will set the `MyProduct.msi`'s `TRANSFORMS` property equal to the bootstrappers  `TRANSFORMSFROMBOOTSTRAPPER` property when it comes time for the bootstrapper to call `msiexec` on the MSI during the actual install process?

**Comment by oleg-shilo** [comment]
Sorry, I will need to investigate in next week. 
I am short on free time right now

**Comment by oleg-shilo** [comment]
I had a look at your description and actually, I do feel your very first option was the simplest one. Particularly if you go all the way and opt for your own bootstrapper (without WiX). Something like the external UI sample:
![image](https://user-images.githubusercontent.com/16729806/189319906-cb2664db-74ce-4667-aee8-af1434d3a2d2.png)

Your proposed solution is supposed to work, as far as I understand how the properties are passed through the chain.
Important thing is that any MSI property set from outside must be public (declared uppercase). But it looks like you are aware of it.

**Comment by tblong** [comment]
No rush here and thanks for the quick feedback too.  This task for me is only for discovering the best route possible.  The work you have done here with this framework making wix more approachable has been a tremendous help over the years. 

I did successfully get the bootstrapper setting the `TRANSFORMS` property on the MSI in the bundle and the MSI using the effective transform to adjust the install dir accordingly.  Here is the working setup with one unexpected outcome I'll detail at the bottom:

## The bootstrapper side
```csharp
// the msi for the bootstrapper bundle
string productMsi = BuildMsi();

var bootstrapper =
  new Bundle("MyBootStrapper",
	  new PackageGroupRef("NetFx472Web"),
	  new MsiPackage(productMsi)
	  {
		  MsiProperties = "TRANSFORMS=[TRANSFORMSFROMBOOTSTRAPPER]",
		  Visible = true
	  });

bootstrapper.SuppressWixMbaPrereqVars = true;
bootstrapper.Version = new Version("1.0.0.0");
bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25844b");
bootstrapper.PreserveTempFiles = true;
bootstrapper.OutDir = "wix";
bootstrapper.OutFileName = "MyBootStrapper";
bootstrapper.WxsFiles.Add(@"CustomWxs\NetFx472.wxs".PathGetFullPath());
bootstrapper.Include(WixExtension.NetFx);
bootstrapper.Include(WixExtension.Util);
bootstrapper.Include(WixExtension.Bal);

// hardcoded :SecondInstance just to test here, intend to bake setting this into the bootstrapper UI
bootstrapper.Variables = "TRANSFORMSFROMBOOTSTRAPPER=:SecondInstance".ToStringVariables();

bootstrapper.Build();
```

## The MSI in the bundle with transforms defined
```csharp
static string BuildMsi()
{
	var project = new Project("MyProduct",
					 new Dir("dynamic_installdir",
						 new File("Program.cs")),
					 new Property("INSTANCEID", "Default"), // the prop to modify by the transform
					 new ManagedAction(SetInstallDir, Return.check, When.Before, Step.LaunchConditions, Condition.NOT_BeingRemoved));

	project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
	project.InstallScope = InstallScope.perMachine;
	project.InstallPrivileges = InstallPrivileges.elevated;
	project.WixSourceGenerated += Project_WixSourceGenerated;
	project.PreserveTempFiles = true;

	project.OutDir = "wix";
	project.OutFileName = "MockMultiInstanceInstallProduct";

	return project.BuildMsi();
}

private static void Project_WixSourceGenerated(XDocument wxsDocument)
{
	var instanceTransforms = new XElement("InstanceTransforms", new XAttribute("Property", "INSTANCEID"));

	foreach (string instance in "FirstInstance,SecondInstance,ThirdInstance".Split(','))
	{
		instanceTransforms.Add(
			new XElement("Instance",
				new XAttribute("Id", instance),
				new XAttribute("ProductCode", Guid.NewGuid()),
				new XAttribute("ProductName", "My Product " + instance)));
	}

	wxsDocument.Root.Select("Product").Add(instanceTransforms);
}

[CustomAction]
public static ActionResult SetInstallDir(Session session)
{
	session["INSTALLDIR"] = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),
									 "My Company", "Product_" + session["INSTANCEID"]);

	return ActionResult.Success;
}
```

So the unexpected part was that the bootstrapper itself shows up in add/remove programs.  I was only expecting the MSI in the bundle to show up in add/remove programs; which it does since I have `MsiPackage.Visible=true` in the example above.  I intended the user to be able to run the bootstrapper multiple times, select for example a dropdown with the correct transform, and then post install only the MSI with the effective transform would show up in add/remove programs.  

I did some digging but came up with nothing, so is there a way to make it so the bootstrapper itself does not get installed?  Is this why you suggested this "Particularly if you go all the way and opt for your own bootstrapper (without WiX). Something like the external UI sample" above?

**Comment by oleg-shilo** [comment]
>  Is this why you suggested this "Particularly if you go....

Exactly. 

I found Bootstrapper user experience a little unpredictable when dealing with complicated scenarios like this. There is a good reason for this - designers of Bootstrapper had to make it ultimately versatile. 

But I do feel that a very simple truly custom bootstrapper might be a more pragmatic choice for cases like yours.
The downside is that you have no warranty the .NET is present. While WiX Bootstrapper will install it for you. Thus what I was suggesting is not ideal at all.

But if your target OS is a modern one then you always have .NET installed.

**Comment by tblong** [comment]
Much thanks for the guidance, got all the intel I need at this point and will give this ticket a close.
