### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by Christobal25** [oleg-shilo/wixsharp#12]
Hey, 

I have in my Setup-Project an Folder with my *.wxl Files for all of my Dialogs.
So I have the Question if it´s possible to Build for each Language an Setup at once.

Like:
` project.LocalizationFile = "Language\\Filename_*(for all the Languages).wxl";`
and than
`project.Language = "en-US, fr-fr, de-de (...)";`

Thanks Christobal25

**Comment by oleg-shilo** [comment]
Yes it is. Though not the way you suggested. You can build all msis from the same build script.
```C#
var project = new ManagedProject(...)

project.LocalizationFile = @"Language\en-US.wxl";
project.Language = "en-US";
project.OutFileName = "en.product.msi";
project.BuildMsi();

project.LocalizationFile = @"Language\en-FR.wxl";
project.Language = "fr-FR";
project.OutFileName = "fr.product.msi";
project.BuildMsi();

project.LocalizationFile = @"Language\de-DE.wxl";
project.Language = "de-DE";
project.OutFileName = "de.product.msi";
project.BuildMsi();
```

**Comment by Christobal25** [comment]
Thanks for your Help, but I have another Question...

`private void dialog_Load(object sender, EventArgs e){`
`var box = System.Windows.Forms.MessageBox.Show("[KeyA]", "[KeyB]", (...)  )`
`(...)`
`}`

Is it possible to localize the Key´s for the MessageBox in the CodeBehind from a WinForm?

**Comment by oleg-shilo** [comment]
Typically. WinForm localization is done view dedicated resources *.resx and as such they have nothing to do with MSI. This is the most orthodox approach and it's covered very well by "WinForm Localization".

Alternatively can access the UIText table from the msi being executed and read any key value from it with MSI SQL statement via the session object. It is not trivial but possible and Wix# does for some scenarios.

However If you are using EmbeddedUI (ManagedUI) WiX compiler does not embed wxl file and the UIText table is not created. Wix# fixes this problem and embeds your whole language file as binary resource. You can access it at runtime like this:
```C#
var bytes = Session.TryReadBinary("WixSharp_UIText");
```
Convert it to whatever you want (e.g. XML) and you can read your text from it. Though MsiRuntime class already has the localization routine based on that embedded wxl file:
```C#
void next_Click(object sender, EventArgs e)
{
    string localized = MsiRuntime.Localize("whatever");
```
Or you can even use the more powerful LocalizeWith extension:
```C#
void dialog_Load(object sender, EventArgs e)
{
    next_button.LocalizeWith(MsiRuntime.Localize);
```
This extension reads the `Text` property of the control, localizes it and sets it back to the control.


ait are using maare .
