### ISSUE TITLE
Windows Installer Patch

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#120]
I was wondering if it is possible to use wix# to create .MSP files?

**Comment by oleg-shilo** [comment]
No. Wix# deliberately avoids 'patching' in favor of 'major upgrade'. Have a look at `E:\Galos\Projects\WixSharp\Source\src\WixSharp.Samples\Wix# Samples\MajorUpgrade` samples.

**Comment by lord2kim** [comment]
But this can be good "feature" when need update just 2 files of application ("hot fix") which contains about 200 files.
Don't remove installed application and files created by it & also update version in "Programs & Features".

Does it possible with MajorUpgrade or MajorUpgradeStrategy ?

**Comment by oleg-shilo** [comment]
> But this can be good "feature" when need update just 2 files of application ("hot fix") which contains about 200 files.

Sorry but I have to disagree. The deployment should maintain a simple "X-COPY" style model and any changes to the deployment should be conducted to the whole deployment. And MS seems to agree with me. They completely ditched all over engineered features of MSI (components, patches, msm, upgrades) and replaced MSI technology with ClickOnce.

> Does it possible with MajorUpgrade or MajorUpgradeStrategy ?

It does, on practical level. Your upgrade MSI will automatically uninstall old version. Thus it is a single step. But you upgrade MSI will need to include the all deployment elements anyway.

**Comment by lord2kim** [comment]
OK, thank u.
It's a shame that we can't just update a couple of files using Wix# to generate an update / patch ((

**Comment by oleg-shilo** [comment]
Look, the fact that I disagree with your evaluation of the feature benefits does not mean that there is none. It's just a matter of the effort/benefit ratio that makes it hard for me to justify starting a new development for something that I do not believe in.  

However if you strongly believe that "support for patching" is a good feature then feel free to experiment and provide a solution that can be safely integrated with Wix#. I will definitely give it a chance.

**Comment by lord2kim** [comment]
OK thanks.
Will look what I can do with it.
