### ISSUE TITLE
Taskbar Icon not showing

### ISSUE THREAD

**Issue by Arthur-Neto** [oleg-shilo/wixsharp#1200]
Hi sorry to bother again :)
So I encountered a problem with the latest release, 1.20.2, the taskbar icon isn't showing unless I click in the window for some reason, strange because I tested with version 1.20.0 and it's working fine there, using Custom WPF UI template.

![image](https://user-images.githubusercontent.com/10981004/188706282-a0259f10-dd84-4fde-aaba-ecc23edcfa76.png)

**Comment by oleg-shilo** [comment]
This behaviour is a limitation of the MSI integration with UAC. And it is non-deterministic by nature. Thus it may or may not manifest itself somewhat randomly. IE, if you just proceed to the install step and stop using the keyboard (to avoid changing keyboard focus accidentally) it will in fact activate UAC prompt eventually. It always does. But I do agree that the UX is rather terrible. But this is how MS designed it :(

The last point in the Limitations sessions [here](https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios) describes the problem and even the workaround. Though the workaround is not really reliable so I cannot recomment it as a real solution.

**Comment by ssrakesh** [comment]
I am using using WPF window. but did not see this issue in winforms
in wpf using this code to make it visible in taskbar
```
var formHostParent = this.ManagedFormHost.Parent as System.Windows.Forms.Form; 
SetForegroundWindow(formHostParent .Handle);
```

**Comment by oleg-shilo** [comment]
Both flavours of UI are impacted by this MSI limitation. And that workaround was initially implemented even before WixSharp released WPF support. It's just that the non-deterministic nature of this defect makes it show the symptoms randomly. :(
