### ISSUE TITLE
Does it support .net 5?

### ISSUE THREAD

**Issue by shengxue** [oleg-shilo/wixsharp#1201]
Does wixsharp support .net 5?

**Comment by oleg-shilo** [comment]
No, 
It's not possible. WiX only supports .NET framework but not .NET Core (.NET5 and higher). Thus WixSharp cannot possibly provide the integration to the unsupported .NET runtime

**Comment by shengxue** [comment]
Is this the reason why I got compile error: ```Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral```?

**Comment by shengxue** [comment]
@oleg-shilo  I couldn't find the support for VCRedist in WixSharp examples.   does WixSharp support VCRedist?

**Comment by shengxue** [comment]
Wix can have definition in bundle, and bundled installer will install .net framework 4.7.2 and VC redist
``` xml
      <PackageGroupRef Id="NetFx472"/>
      <PackageGroupRef Id="VC2019X86"/>
```

while, I saw ```NetFx40Web``` in WixSharp examples, and I thought the below codes will trigger .net framework web installer, so I am wondering if WixSharp have similar ```PackageGroupRef``` for VC redist?
``` csharp
new PackageGroupRef("NetFx40Web")
```

**Comment by oleg-shilo** [comment]
I see. You are referring to the predefined external packages that WiX already supports.
Then indeed WixShar supports it too.

if you add the corresponding line to your code:  

```C#
var bootstrapper =
    new Bundle("My Product",
                new PackageGroupRef("VC2019X86"),
```
It will produce the desired 

![image](https://user-images.githubusercontent.com/16729806/189312655-2337a785-a65d-4c66-86e8-c27a1c050b65.png)

**Comment by shengxue** [comment]
The code can be compiled,
``` csharp
var bootstrapper =
    new Bundle("My Product",
                new PackageGroupRef("NetFx40Web"),
```

but the code can not compile
``` csharp
var bootstrapper =
    new Bundle("My Product",
                new PackageGroupRef("VC2019X86"),
```

**Comment by oleg-shilo** [comment]
> You will need to find with WiX documentation which extension contains this package. I just do not know.

**Comment by oleg-shilo** [comment]
It does not compile because you need to add WiX extension that implements this package.

Since you provided the example `   <PackageGroupRef Id="VC2019X86"/>`, you also can find out the name of that extension...
