### ISSUE TITLE
Uninstall from Program Files problem at ManagedUI

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#1202]
I've prepared and attached setup based on one of samples. My main change was to use %Personal% instead of %ProgramFiles%. I then ran build.cmd. And next I ran CMD as admin and the MSI. I chose custom installation, and in it I changed the installation folder to a folder in Program Files (x86). The installation was completed without error. Uninstall.cmd was completed without error too. But the application stayed in Program Files (x86). Wasn't  removed.

[ManagedSetup.zip](https://github.com/oleg-shilo/wixsharp/files/9521877/ManagedSetup.zip)

**Comment by oleg-shilo** [comment]
Sorry, I do not have the bandwidth to troubleshoot your problem. But I suggest you have a look at the generated wxs file to see if there is anything wrong there (even though unlikely).
The fact that the installation succeeded means that it is probably outside of a typical WixSharp scenario and something that is generic to the MSI scenario. 

ManagedUI cannot be a problem. You can testy it by simply switching to the default native UI.

**Comment by sadam2** [comment]
:-) Sorry, I don't know how to get the WXS file from CSCS.EXE running in this BUILD.CMD which is in the attached ManagedSetup.zip file.

**Comment by sadam2** [comment]
I decided not to use %Personal% instead of %ProgramFiles%. Unfortunately, the local user folder as the default installation location does not work well. To get the installation to the local user folder, we can either change the path from the dialog box or call MSIEXEC with the INSTALLDIR parameter. This works.
Maybe someday %Personal% will work, too.
