### ISSUE TITLE
Feature - RegisterCom class to ease the registration of COM files

### ISSUE THREAD

**Issue by yokioda** [oleg-shilo/wixsharp#1204]
Hello,

I've created a custom WixEntity class that adds the appropriate registry entries for a COM file like .dll or .ocx into the generated .wxs file.

The current ways of handling this did not really appeal to me because I wanted to do it "the right way" (no regsvr32.exe or self registration) but without all the hassle of manually extracting the registry entries and adding them to the .wxs.

Inspired by the Harvester #695 I created a class that utilizes heat.exe to extract the registry entries and adds them to the files .wxs entry. I created the corresponding extensions as well making it as simple as:

```csharp
new File(@"Some\File.dll").RegisterCom()
or
new Files(@"SomeFiles\*.*").RegisterCom()
```

to register .dll or .ocx files.
The files including an example project can be found here: [RegisterCom](https://github.com/yokioda/RegisterCom)

I think it would be a great addition to the project and was wondering if you'd like to add it to the codebase.
Paul

**Comment by oleg-shilo** [comment]
Excellent. Thank you.

**Comment by oleg-shilo** [comment]
Thank you for such a comprehensive contribution.
Done.

I integrated it with a few very minor changes though: 
- I renamed `RegisterCom` to `RegisterAsCom` as it may improve the readability
- I changed the inheritance and it now subclasses from `WixEntity` instead of `File`.

**Comment by yokioda** [comment]
Reasonable changes.

I'm just happy to be able to assist in making MSI automation a bit less painful.
