### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#1206]
I am creating an application installer using VS 2019 and WixSharp 1.20.2. There is to be a folder created in the application folder with a file or files available to all. My code snippet looks like this:

), new Dir("lm",
	new DirPermission("Everyone", GenericPermission.All),
	new File(@"Files\Data\lm\special.lm")),
     
and I received such errors in the output window:

6>C:\agent\_work\66\s\src\ext\UtilExtension\wixlib\UtilExtension.wxs(41): error LGHT0102: The localization variable !(loc.msierrSecureObjectsFailedCreateSD) is unknown.  Please ensure the variable is defined.
6>C:\agent\_work\66\s\src\ext\UtilExtension\wixlib\UtilExtension.wxs(42): error LGHT0102: The localization variable !(loc.msierrSecureObjectsFailedSet) is unknown.  Please ensure the variable is defined.
6>C:\agent\_work\66\s\src\ext\UtilExtension\wixlib\UtilExtension.wxs(43): error LGHT0102: The localization variable !(loc.msierrSecureObjectsUnknownType) is unknown.  Please ensure the variable is defined.
6>C:\Users\Pracownik\.nuget\packages\wixsharp\1.20.2\build\WixSharp.targets(5,5): error MSB3073: The command ""C:\4me\Repozytorium\WixSharp Installer\bin\Release\net48\WixSharp Installer.exe" "/MSBUILD:WixSharp Installer" "/WIXBIN:" "/Configuration:Release" "/Platform:AnyCPU"" exited with code -1.
6>Done building project "WixSharp Installer.csproj" -- FAILED.

What must be changed?

**Comment by oleg-shilo** [comment]
Not sure. 
Does the DirPermission sample work in your environment?
