### ISSUE TITLE
Prevent wixsharp installer from copy files if already exist

### ISSUE THREAD

**Issue by TashenDev** [oleg-shilo/wixsharp#1208]
Hi how do I prevent installer from copying of images to C:\inetpub\wwwroot if those images already exist in that folder?

**Comment by TashenDev** [comment]
> ```cs
> new File(@"Files\Docs\Manual.txt") { NeverOverwrite = true })),
> ```

is this for a new Dir? like this...
            var deployDirectory = new Dir(
                destination,
                new IISVirtualDir
                {
                    Name = virtualDirName,
                    AppName = "[ProductName]",
                    WebSite = new WebSite(virtualDirName, " *:80") { InstallWebSite = false, },
                    WebAppPool = new WebAppPool("[ProductName]", AppPoolSettings),
                    AttributesDefinition = "Component:Win64=yes",
                },
                new Files(new Feature { }, path, f => !f.EndsWithAny(true, ".pdb", "Development.json")),

                
                new DirPermission("SYSTEM", GenericPermission.All),
                new DirPermission("Everyone", GenericPermission.None),
                new DirPermission("IIS_IUSRS", GenericPermission.All)
            );

**Comment by oleg-shilo** [comment]
Just a formatting suggestion... I have modified your post above so the code is properly formatted.

**Comment by oleg-shilo** [comment]
The attribute `NeverOverwrite` is for the file.

**Comment by TashenDev** [comment]
> 

is the File object is an instance of System.IO.File?
I'm getting an error cannot create instance of static class 'File'

**Comment by TashenDev** [comment]
I don't have WixSharp.File. I'm using v1.6 and just updated nuGet Package to 1.2

**Comment by TashenDev** [comment]
I fixed it with using statement
using File = WixSharp.File;

**Comment by TashenDev** [comment]
> The attribute `NeverOverwrite` is for the file.
> 
> Like in the sample below:
> 
> ```cs
>         var project =
>             new Project("MyProduct",
>                 new Dir(@"%ProgramFiles%\My Company\My Product",
>                     new File(@"Files\Bin\MyApp.exe"),
>                     new Dir(@"Docs\Manual",
>                         new File(@"Files\Docs\Manual.txt") { NeverOverwrite = true })),
>                 new Binary(new Id("mycert"), @"Files\mycert.cer"),
>                 new Certificate("NameOfCert", StoreLocation.localMachine, StoreName.personal, "mycert"),
>                 new Certificate("NameOfCert2", StoreLocation.currentUser, StoreName.personal, @"Path\to\cert\file", authorityRequest: false));
> ```

Can you have more than one File inside a new Dir?
If so, how would the code look.

**Comment by TashenDev** [comment]
Hi 
for the Dir object...I'm adding the images path which is already part of the new Files object of the installer.
I'm getting errors that the files are installed by two different components and this breaks reference counting.
![af-za](https://user-images.githubusercontent.com/95073544/190582301-c0b41aab-d0e4-481f-ae86-bb383b8e8d64.png)

**Comment by TashenDev** [comment]
I've also tried removing the 2nd Dir and only have one Dir. It then compiles but when installing still overwrites existing files

**Comment by TashenDev** [comment]
Its seems to be copying a copy of files to the root of the installation directory.

**Comment by oleg-shilo** [comment]
> is already part of the new Files object of the installer.

Then you should use filters (param in the Files constructor) to avoid duplication. Or add all the files explicitly

> It then compiles but when installing still overwrites existing files.

I suggest you confirm that WixSharp generates corresponding `<Component NeverOverwrite="yes">`.
If it does then you need to consult WiX documentation and see how the observed behaviour is consistent with the expectations associated with this WiX functionality. Quite possibly there is a discrepancy there.

> Its seems to be copying a copy of files to the root of the installation directory.

Please check if the WixSharp sample for `Files` works for you:
![image](https://user-images.githubusercontent.com/16729806/190893002-4a88dba8-72c2-4653-9117-7c0d9ff26ea5.png)

It can help you to investigate your problem.

**Comment by TashenDev** [comment]
> > is already part of the new Files object of the installer.
> 
> Then you should use filters (param in the Files constructor) to avoid duplication. Or add all the files explicitly
> 
> > It then compiles but when installing still overwrites existing files.
> 
> I suggest you confirm that WixSharp generates corresponding `<Component NeverOverwrite="yes">`. If it does then you need to consult WiX documentation and see how the observed behaviour is consistent with the expectations associated with this WiX functionality. Quite possibly there is a discrepancy there.
> 
> > Its seems to be copying a copy of files to the root of the installation directory.
> 
> Please check if the WixSharp sample for `Files` works for you: ![image](https://user-images.githubusercontent.com/16729806/190893002-4a88dba8-72c2-4653-9117-7c0d9ff26ea5.png)
> 
> It can help you to investigate your problem.

I added files to be excluded in the Files parameter to overcome the duplication and that resolved my issue. Thanks for your help.
