### ISSUE TITLE
Write to registry to a path that doesn't exist

### ISSUE THREAD

**Issue by ronaamishay** [oleg-shilo/wixsharp#1211]
Hi,
I tried to use the following syntax to write to registry 

```
var regkey = new RegKey(null, RegistryHive.LocalMachine, "SOFTWARE\\WOW6432Node\\MyCompanyName\\MyCompanyProduct\\Install\\version", new RegValue("InstallerId", "mypath"));
project.AddRegKey(regkey);
```

it's working only if the whole path (....\\MyCompanyName\\MyCompanyProduct\\Install\\version )  exists in registry. in this way, the key and value ("InstallerId", "mypath") are added. but if the path or part of it doesn't exist (for example, MyCompanyProduct doesn't contain "Install"), nothing happens. How can  add the path to registry if doesn't exist?

**Comment by ronaamishay** [comment]
The solution that I found was to add each node separately with empty value. Than only the last one contains the value:

```
            project.AddRegValue(new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\WOW6432Node\MyCompanyName", string.Empty, string.Empty));

            project.AddRegValue(new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\WOW6432Node\MyCompanyName\MyCompanyProduct\", string.Empty, string.Empty));

            project.AddRegValue(new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\WOW6432Node\MyCompanyName\MyCompanyProduct\Installer", "InstallerId", "mypath"));

```

**Comment by yokioda** [comment]
The registry entries are added to the WOW6432Node by default.


If you explicitly add it as in your original question the key is created in

> SOFTWARE\WOW6432Node\WOW6432Node\MyCompanyName\MyCompanyProduct\Installer

instead.


I don't know what exactly happens when using your solution, but you can just use
```C#
var regkey = new RegKey(null, RegistryHive.LocalMachine, @"SOFTWARE\MyCompanyName\MyCompanyProduct\Installer", new RegValue("InstallerId", "mypath"));
project.AddRegKey(regkey);
```
or
```C#
project.AddRegValue(new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MyCompanyName\MyCompanyProduct\Installer", "InstallerId", "mypath"));
```
to reach the desired result.

If you wanted to create a x64 key you would even need to explicitly declare it and make your installer x64 as well.
```C#
project.Platform = Platform.x64;
new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MyCompany\MyProduct\x64Key", "Name", "Value") { Win64 = true }
```

**Comment by oleg-shilo** [comment]
As @yokioda correctly indicated MSI does not handle well dev experience for x64 scenarios. 
It's simply because it is an old fellow that was created before x64 days
