### ISSUE TITLE
On uninstall services get deleted and restarted, resulting in "Application could not be restarted" error events in Event Viewer

### ISSUE THREAD

**Issue by snoopiedoom** [oleg-shilo/wixsharp#1212]
Title, quite big installer, hit a stump on how to solve this.
Tried to debug using a CustomAction(Before RemoveFiles ) but it launches after the FilesInUse Dialog.

One idea was that this happens because we elevate the whole setup like here: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/RestartElevated(UI)/setup.cs

Other than that, we use a ManagedUI(WinForm), and in the end, the services are installed via a CustomAction (After, InstallExecute, NOT_BeingRemoved) using an AssemblyInstaller.

I apologize in advance for any lack of information, I am completely new to wix/wixsharp, and I am working on an existing codebase.

**Comment by oleg-shilo** [comment]
Only a suggestion...
Try to see if the standard WiX way of installing services solves the problem. 
![image](https://user-images.githubusercontent.com/16729806/192677360-4cb9ab87-612b-41ac-9917-7fe8681bd000.png)
