### ISSUE TITLE
Special deferred custom action not working in WPF External UI

### ISSUE THREAD

**Issue by josejobin45** [oleg-shilo/wixsharp#1213]
Hi,
I am trying to build an installer with external UI using code sample from externalUI->wpf. I need to run a PowerShell script after install and managed to get it working from MSI using special deferred action.

But when trying to run exe build using the MSI the files are getting copied but script is not running after install. Am I missing something? Do I need to add anything else in WPF external UI code. 

Cheers.

**Comment by oleg-shilo** [comment]
I think it might be some confusion about the relationship between external UI and Custom Actions.
To put it simply, there is no connection whatsoever. External UI only takes user input and simply starts the MSI (msiexec.exe) in the background and after that MSI runtime takes fool controls and UI cannot possibly change anything.

Thus there is a possibility that the problem you are experiencing is triggered even without External UI.

This is what I did. I have created the deferred action for the `<wixsharp>\Source\src\WixSharp.Samples\Wix# Samples\External_UI\Msi` sample:

```C#
project.AfterInstall += (e)=>
{
    System.Windows.Forms.MessageBox.Show("project.AfterInstall");
};
```

And then build and executed `<wixsharp>\Source\src\WixSharp.Samples\Wix# Samples\External_UI\WpfSetup`. The CA is fired just fine.

![image](https://user-images.githubusercontent.com/16729806/193561455-b0cc7769-bf3d-4a11-9bc8-66aadc31ccfe.png)

So you may want to try this sample.

**Comment by josejobin45** [comment]
Can you look at my after-install code. This executes from MSI and runs fine.

project.AfterInstall += (e)=>
        {
            if (!e.IsUninstalling)
            {
                string Install = e.InstallDir;
                string cmdd = io.Path.GetFullPath(io.Path.Combine(Install, @"..\My Product\Script\run.cmd"));
                var process = Process.Start(cmdd);
                process.WaitForExit();
            }
But when using wpf UI it isn't working.

**Comment by josejobin45** [comment]
I tried to show a message box like you showed in your example and I can't seem to get it working with external UI. Nothing from project.afterinstall is working from external UI. From MSI it works fine.

**Comment by oleg-shilo** [comment]
I suggest you try to build and run the sample I just created for you. 
Just in case I have attached the sample with the working msi and the UI:
![image](https://user-images.githubusercontent.com/16729806/193830345-1c81ac0f-6e03-4011-b391-82212cfafdfe.png)
[External_UI.zip](https://github.com/oleg-shilo/wixsharp/files/9707204/External_UI.zip)

**Comment by josejobin45** [comment]
Thanks for the reply Oleg. I was able to get the installer to display message box with your example. But even after editing the msi's setup.cs i am not able to get my own message to display,wpf ui display's your messagebox not what i defined but the features getting installed changed to what I defined. I don't understand why this is happening. If the new MSI isn't getting loaded properly how only the features i defined changed.

**Comment by josejobin45** [comment]
Thanks Oleg for the reply. I was able to get the message box to display with your sample. But I am still facing some issues. I think my build is not taking any changes I made to the MSI correctly. It is keeping old MSI's information i believe. Can you tell me how to change the location from which the wpfsetup takes the MSI, Or how to update the MSI information to the new one. Rebuilding the solution doesn't help. Thanks for your help thus far.

**Comment by josejobin45** [comment]
All features are present from my MSI but the afterinstall message "project.afterinstall" is getting generated from somewhere i don't know. I updated your sample with my MSI still it is showing your message. I don't understand what's happening.

**Comment by josejobin45** [comment]
It was a issue where I was loading old MSI's to the WPF setup. Couldn't have found the issue without your help. Oleg you are the best. Thank you. You can close this thread now.

**Comment by oleg-shilo** [comment]
Not a problem. Glad you sorted it out.
