### ISSUE TITLE
Bundle MSI inside another MSI to install before setup.

### ISSUE THREAD

**Issue by josejobin45** [oleg-shilo/wixsharp#1216]
Hi,
I am trying to bundle some MSI's inside an MSI so as to install them one after another. I was hoping to do it with project.beforeinstall. Basically I want to have a single MSI with other MSI inside it. Can you tell me which sample to follow.
PS: I also need External UI feature to be present. Any methods that allow it is preferred.

**Comment by oleg-shilo** [comment]
You cannot use BeforeInstall as at this time MSI already started the setup transaction.
1. You can use On UIload and make a condition the mse has to be used with the UI, even progress only. 
2. You can use Bootstrapper with the custom BA (bootstrapper app). 
3. You can use Simplified Bootstraper (pretty much option 1). 
4. You can use NSIS Bootstrapper (it supports custom UI for bundled MSIs, while WiX does not). The sample is in the repository

**Comment by josejobin45** [comment]
Can NSIS produce an exe file as output. I need the output to be an MSI so that I can load it into WPF External UI setup.

**Comment by oleg-shilo** [comment]
If you want to use "external UI + a primary MSI" model then Simplified Bootstraper sample is what you need.

NSIS is just another bootstrapper. Though arguably more civilized than WiX Burn. Thus it produces an exe that starts msi one after another. But these msi setups can have their custom UIs

**Comment by josejobin45** [comment]
Can I give external UI to NSIS bootstrapper. I want to chain install some msi's in a folder. Is there any method in which I can have both external UI of wpf and  chain installation capability of NSIS together.

**Comment by geghamyan** [comment]
> Can I give external UI to NSIS bootstrapper. I want to chain install some msi's in a folder. Is there any method in which I can have both external UI of wpf and chain installation capability of NSIS together.

Take a look on the suggestion here:
https://github.com/oleg-shilo/wixsharp/issues/1205#issuecomment-1246298732

To embed multiple MSI's in the bootstapper you can use [payloads](https://github.com/oleg-shilo/wixsharp/blob/69bf82e496b715b34f64dd19ecf7d875776e63d7/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L177)

**Comment by josejobin45** [comment]
Thanks for the suggestion geghamyan. For the project i working on I need a custom UI in which can be greatly modified. I don't understand how to provide NSIS bootstrapper with WPF UI or it is even possible. If the output of the bootstrapper was an MSI i could add it to WPF external UI sample to execute it. But because the output is an exe i don't know how to add a WPF UI to the bootstrapper.

**Comment by josejobin45** [comment]
Thanks for the suggestion geghamyan. Due to some constrains i am not able to use the NSIS solution. So I am now trying to bootstrap using WixBootsrapper_UI sample. I was able to create the bootstrapped exe but cannot run it for some reason. It won't display anything after administrator privilege request screen. I am sorry if the question is too basic, i am new at this. Thanks for understanding.

**Comment by josejobin45** [comment]
Thanks for the suggestion geghamyan. It seems i can't use NSIS in my project due to some company policy. I was able to make a simple bootstraper with wixbootstrapper_UI. I think it will be enough. Thanks for the help. You guys are great 😃.
