### ISSUE TITLE
How can i build huge bootstrap

### ISSUE THREAD

**Issue by Zerpico** [oleg-shilo/wixsharp#1217]
I need to build one bootstrap which includes:

-  1st MSI larger then 2.7 GB
-  2nd MSI = 1.1 GB
-  Third party installer = 1.5 GB

But i get error:

```
1>light.exe : error LGHT0306: An error (E_FAIL) was returned while finalizing a CAB file. This most commonly happens when creating a CAB file with more than 65535 files in it. Either reduce the number of files in your installation package or split your installation package's files into more than one CAB file using the Media element.
```

I try in 1st installer set Media:
```
project.Media.Clear();
project.WixSourceGenerated += document =>
{
    document.Select("Wix/Product")
        .AddElement("MediaTemplate", "CabinetTemplate=cab{0}.cab; CompressionLevel=none; EmbedCab=no; ");
 };
```

or try set on Bundle property as Compressed = false.<br>
But everything is not going. I don't understand how I can build one big exe installer. Or an installer with additional archives (as it is in MSI with CAB files)

**Comment by Zerpico** [comment]
Here is what I was able to do.
If you generate a bundle.vcs with the following structure:
```xml
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="MyApp">
    
    <Chain>
      <PackageGroupRef Id="NetFx451Redist" />
      <PackageGroupRef Id="BigMsiSetup" />
    </Chain>

  </Bundle>

  <Fragment>
    <PackageGroup Id="BigMsiSetup">
      <MsiPackage SourceFile="..\BigInstaller.msi" />
    </PackageGroup>

    <Container Id="BigMsiSetup" Name="cab0.cab">
      <PackageGroupRef Id="BigMsiSetup" />
    </Container>
  </Fragment>

```
I added the packgroup as a fragment, and specified the container. It has become an external file.
But to generate something like this in WixSharp, I had to use the following codes:

```csharp

var msiGeneratedFile=BuildMsi();

var bundle = new Bundle(bundleName)
{
   // some property for bundle
};

//change generated wxs
bundle.WixSourceGenerated += document =>
{
    document.Select("Wix/Bundle/Chain")
           .AddElement("PackageGroupRef", "Id=BigMsiSetup");

    document.Select("Wix/Fragment")
           .AddElement("PackageGroup", "Id=BigMsiSetup")
            .AddElement("MsiPackage", $"SourceFile={msiGeneratedFile}");

    document.Select("Wix/Fragment")
           .AddElement("Container", "Id=BigMsiSetup; Name=cab0.cab")
            .AddElement("PackageGroupRef", "Id=BigMsiSetup");
};


```

**Comment by Zerpico** [comment]
Please help me. I still need to create a bundle with cab packages

**Comment by oleg-shilo** [comment]
I am progressing very well on Wix4 support so if this behaviour is addressed in Wix4, you will be able to use it very soon..

**Comment by Zerpico** [comment]
> I am progressing very well on Wix4 support so if this behaviour is addressed in Wix4, you will be able to use it very soon..

Great. I will be waiting very much
Maybe there is another solution.  Don't know how to make msi with one additional cab file?

At the moment, the properties of the project are as follows:
```csharp
project.Media.Clear();
project.WixSourceGenerated += document =>
{
         document.Select("Wix/Product")
          .AddElement("MediaTemplate", "EmbedCab=no; CabinetTemplate=cab{0}.cab; CompressionLevel=medium; MaximumUncompressedMediaSize=2000;");
};
```
I get files like this:

- App.msi    (2,7 MB)
- cab1.cab   (1,04 GB)
- cab2.cab   (1,07 GB)

I want fewer cab files, like this:

- App.msi    (1,05 GB)
- cab1.cab   (1,07 GB)
