### ISSUE TITLE
Dynamic custom UI sequence

### ISSUE THREAD

**Issue by serezlan** [oleg-shilo/wixsharp#1218]
Hi oleg-,

Is there a way to set UI sequence dynamically?
My use case is when user is doing fresh install then custom page is shown requesting additional info.
If user is upgrading then skip custom page.

I'm able to inject custom page but do not know how to do it dynamically.

Thx.

**Comment by oleg-shilo** [comment]
Yes, and it is in fact very easy.
Create, your project from "Custom UI" template (either WinForm or WPF) and then in every dialog you will be able to decide to show or to skip it.
When you create the project investigate the source code of the dialog and it will be obvious how to do it. If not then com back here :)

**Comment by serezlan** [comment]
I've experimenting with sample in Custom_UI folder and could not figure out how to do this.
Could you give me some asistance?

Anyway.. just to be clear when I said upgrading, I meant when we install with newer build version.

Thx

**Comment by Zerpico** [comment]
You can detect if a product is installed via an upgrade code

```csharp
public class MsiHelper
{

private static class MsiWinApi
{
    [DllImport("msi.dll", CharSet = CharSet.Auto, SetLastError = true)]
    internal static extern uint MsiEnumRelatedProducts(string strUpgradeCode, int reserved, int iIndex, StringBuilder sbProductCode);

    [DllImport("msi.dll", ExactSpelling = true)]
    internal static extern IntPtr MsiGetActiveDatabase(IntPtr hInstall);

    [DllImport("msi.dll", CharSet = CharSet.Unicode)]
    internal static extern InstallState MsiGetComponentPath(string szProduct, string szComponent, [Out] StringBuilder lpPathBuf, ref int pcchBuf);

    [DllImport("msi.dll", CharSet = CharSet.Unicode)]
    internal static extern Int32 MsiGetProductInfo(string product, string property, [Out] StringBuilder valueBuf, ref Int32 len);
}

public static bool DetectInstallByUpgradeCode()
{
    try
    {
        string upgradeCode = _session["UpgradeCode"];

        //found related productCode for installation version
        string productCode = GetRelatedProductCode(upgradeCode);
		return !string.IsNullOrEmpty(productCode)
    }
    catch (Exception ex)
    {
        _session.LogMessage(ex.ToString());
    }
    return false;
}

private static string GetRelatedProductCode(string upgradeCode)
{
    StringBuilder productCodeBuffer = new StringBuilder(38);
    uint err = MsiWinApi.MsiEnumRelatedProducts(upgradeCode, 0, 0, productCodeBuffer);
    if (err != ERROR_SUCCESS) throw new ArgumentException($"Can't found related products for UpgradeCode: {upgradeCode}");
    return productCodeBuffer.ToString();
}

}

```

**Comment by serezlan** [comment]
Hi @Zerpico ,

Thx for your reply. 
I'm able to detect if product already installed. The problem is how to adjust page sequence when such event happened.

Here's my use case:

- Fresh install
Welcome Dialog > License Agreement > Custom page > Install Dir > Verify

- Update 
Welcomd Dialog > License Agreement > Verify 

AFAIK, this sequence is set prior to BuildMSI() and I want to know how to change it dynamically.

Thx

**Comment by Zerpico** [comment]
@serezlan 
I don't know how exactly you made the project. But for a similar situation, I made one customDialog:

```csharp
//dialogs for install
project.ManagedUI.InstallDialogs
	.Add(WixSharp.Forms.Dialogs.Welcome)
	.Add(WixSharp.Forms.Dialogs.Licence)
	.Add<CustomDialogs.MyCustomDialog>()
	.Add(WixSharp.Forms.Dialogs.InstallDir)                
	.Add(WixSharp.Forms.Dialogs.Progress)
	.Add(WixSharp.Forms.Dialogs.Exit);

//dialogs for modify and uninstall
project.ManagedUI.ModifyDialogs
	.Add(WixSharp.Forms.Dialogs.MaintenanceType)
	.Add(WixSharp.Forms.Dialogs.Features)
	.Add(WixSharp.Forms.Dialogs.Progress)
	.Add(WixSharp.Forms.Dialogs.Exit);
```

You can create **MyCustomDialog** and when initializing the form, detect if product already installed and display or skip it

```csharp
public partial class MyCustomDialog : ManagedForm, IManagedDialog
{
    public MyCustomDialog()
    {
        InitializeComponent();
	this.Load += new System.EventHandler(this.MyCustomDialog_Load);
    }

    void MyCustomDialog_Load(object sender, EventArgs e)
    {
        banner.Image = Runtime.Session.GetResourceBitmap("WixUI_Bmp_Banner");
        ResetLayout();

        if (IsInstalledProduct())
        {
            Shell.GoNext();
        }        
    }
//...
}
```
But there is one problem with this solution. If you go to the previous step with the *InstallDir* step, you will open *MyCustomDialog* and it can immediately execute *Shell.GoNext()* if it detects that the product is installed

**Comment by oleg-shilo** [comment]
@Zerpico is right, the key algorithm is to detect if you want to skip the dialog in the `OnLoad` event handler. And if you do then just call `Shell.GoNext`.

BTW you already have all information about prv version in the event argument:

```C#

static void project_Load(SetupEventArgs e)
{
    if (e.IsUpgradingInstalledVersion)
    {
         . . . 
    }
```

Or in the dialog 
```C#
static class DialogsHistory
{
    public static Type LastDialog; 
}
... 
public MyCustomDialog()
{
    DialogsHistory.LastDialog = this.GetType(); // should implement it in "License Agreement" and "InstallDir" dialogs too
    InitializeComponent();

    this.Load += new System.EventHandler(this.MyCustomDialog_Load);
}

void MyCustomDialog_Load(object sender, EventArgs e)
{
        banner.Image = Runtime.Session.GetResourceBitmap("WixUI_Bmp_Banner");
        ResetLayout();

        if (this.MsiRuntime.MsiSession.IsUpgradingInstalledVersion())
        {
            if(DialogsHistory.LastDialog = typeof(InstallDir))
                Shell.GoPrev();
            else
                Shell.GoNext();
        }        
    }
```

As for that problem @Zerpico mentioned, it is enough for you to know what is you prev screen was and you can either call `Shell.GoNext()` or `Shell.GoPrev()`

**Comment by serezlan** [comment]
Hi @oleg-shilo ,

After reading your comment, I searched and found one sample with similar code in wixsharp sample and it works great.

Thank you.
