### ISSUE TITLE
Major upgrade results in dangling components in system32

### ISSUE THREAD

**Issue by barnabas90** [oleg-shilo/wixsharp#1221]
Hi,

I’ve ran into an odd issue recently.
I have an msi v1.0 that installs 1 dll also v1.0 into system32.
I have another msi, the same, except for msi and dll versions are 2.0.
If I clean install 1.0, the dll gets copied into system32, and a registry entry under hklm/software/…/shareddll/ appears for my component, a reference counter with a value 1. When I uninstall the msi the file gets removed and the registry entry gets removed as expected. Same goes for 2.0.

But:
When i upgrade from 1.0 to 2.0, the dll gets replaced with the newer version, but the reference counter in the registry is 2. If I uninstall the product, the counter gets decremented, but still 1, and the dll file is not removed.
Seems like on major upgrade the uninstall phase doesn’t decrement the reference counter. If I want to install back 1.0, I can, but the dll doesn’t get replaced because the higher version wins, so I have 1.0 installed but I have a 2.0 dll installed from the previous installation.

I found a way to workaround this, by default on every rebuild wixsharp generates a new guid for each component. if I hardcode a constant component guid for this dll and use it accross msi versions, the issue goes away, on upgrade the counter remains 1.

I haven’t used any special attributes, just a simple file component, default majorupgrade behavior, nothing fancy. I didn’t ask for the registry entry either it got there automatically.

is this expected and my workaround is the way how it should a system32 installed component look like at the first place, or some bug?

**Comment by oleg-shilo** [comment]
Effectively it is the question of how MSI handles upgrades of the overlapping resources. If you look even deeper then you will see the tail of "DLL-hell".

Sorry, I do not have the answer for that. MSI sometimes is quite mysterious.

As for the injection of regkeys, you can disable it via `AutoElements.DisableAutoUserProfileRegistry = true;`. It is required for some of the setups but not for all:

![image](https://user-images.githubusercontent.com/16729806/197457132-9ef36330-0972-487c-854d-192e467a6455.png)

**Comment by barnabas90** [comment]
Thank you, I suspected the same. I've found some forum threads where people say that component guids must be the same for system32 installed files accross versions in order to make majorupgrade work properly, but I haven't found anything in the wix book nor in any official documentation.

**Comment by oleg-shilo** [comment]
btw you can force deterministic component GUIDs assignment

**Comment by barnabas90** [comment]
Thank you, I'll check that.

**Comment by oleg-shilo** [comment]
You can set component id via the property of `WixEntity`:

```c#
new File(@"Files\Docs\Manual.txt")
{
    ComponentId = "6f330b47-2577-43ad-9095-1861ba258892"
}
```
