### ISSUE TITLE
Non LegacyDummyDirAlgorithm creates C:\ProgramFilesFolder empty folder

### ISSUE THREAD

**Issue by 11v1** [oleg-shilo/wixsharp#1223]
Hi,

If I have an installer without files by default C:\ProgramFilesFolder is created. With LegacyDummyDirAlgorithm = true there is no empty folder. It looks like something went wrong with the non-legacy algorithm.

**Comment by oleg-shilo** [comment]
Thank you Grigorii,
Can you please share your simple setup definition that exhibits the problem?

I have checked and `Registry` sample after commenting out the files does create `c:\ProgramFilesFolder`
![image](https://user-images.githubusercontent.com/16729806/197394668-e9bc0885-1102-4b2c-9da9-2ee56f421b4e.png)

Maybe you can check if in your environment this sample behaves the same way as in mine?

**Comment by 11v1** [comment]
Hi Oleg,

With the **Registry** sample, I have the same issue, if I remove the code you highlighted then `C:\ProgramFilesFolder` folder is created during installation. If I write `AutoElements.LegacyDummyDirAlgorithm = true` then msi works as expected and no folder is created.

**Comment by oleg-shilo** [comment]
Hm-m-m, it's not what I observe with that very sample. 
Let me recheck again, in case something went wrong with the test. 

But if you are right then nothing much we can do about it. No support for no-directory scenario is a WiX/MSI limitation and it just means that today only one version of WixSharp workaround works - `AutoElements.LegacyDummyDirAlgorithm = true`. So I will need to hardcode it to true.

I will let you know my findings.

**Comment by oleg-shilo** [comment]
I can confirm that you were right and the new algorithm does leave dummy folder in the drive root (the old algorithm does it in the program files).
But I actually found a workaround that allows avoid ing this problem.

Will let you know when it is ready

**Comment by oleg-shilo** [comment]
Done, will be available in the very next release

**Comment by 11v1** [comment]
I'm happy to hear that. Thank you, Oleg.

**Comment by oleg-shilo** [comment]
Done.
https://github.com/oleg-shilo/wixsharp/releases/tag/v1.20.3.0
