### ISSUE TITLE
Second msiexec still running after installer closed

### ISSUE THREAD

**Issue by nickdollahz** [oleg-shilo/wixsharp#1225]
I noticed even with Sample installer there is a msiexec.exe process that is still running when I close the installer.
I tested a bare bone Wix installer and it doesn't do that. 

It has the command line arg of C:\Windows\system32\msiexec.exe /V

Can you share some light on what is going on there?

On an installer I wrote it actually shows a message of "Installer is no longer responding".
It stays open for quite a while like 20+ mins or so on my installer. 5mins or so for the sample installer.

**Comment by oleg-shilo** [comment]
It is an MSI runtime service that is expected to be running on all OS at all time as an elevated process.

It s the actual service that loads your msi and executes the deployment definition scenario this msi implements.

**Comment by nickdollahz** [comment]
Is there some way to wrap a UI around it so we know when its done? or to otherwise stop it?
I've been end tasking it while testing. Not sure what effect that has on anything? 

It seems it lets me delete the msi but it's still doing stuff in the background.

**Comment by oleg-shilo** [comment]
It is MSI runtime service. You should not interfere with it. If you manage to kill it then most likely service manager will resurrect it.

This service is a fundamental part of the OS so you dos not want to mess with it:

![image](https://user-images.githubusercontent.com/16729806/198827864-8fca7bdc-56f6-422e-9368-54f1dd8efad1.png)
