### ISSUE TITLE
How to add multiple CA´s for BA Installer

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1227]
Morning, i have to add some CA´s in Installer , but my project ist BA from Template WixBootstrapper_UI. Basically searc registry value and add file to path. Here i struggle, how to do it. Is it somehow possible?

**Comment by oleg-shilo** [comment]
CustomAction is a behaviour embedded in the msi, not in the BA.

**Comment by Torchok19081986** [comment]
i found it. Added CA like ManagedAction and it works. 

Only one small troble: if i change ManagedAction to ElevaterManagedAction i got error that Step.Launchconditions couldnt be execute. Also try to change Step to Install or aother Step Enum. Error is same. What are Step need to be, if ElevatedManagedAction ist set? Step is fourth Parameter in Manged Action .
