### ISSUE TITLE
 AppSearch.GetProductVersionFromUpgradeCode return false

### ISSUE THREAD

**Issue by shengxue** [oleg-shilo/wixsharp#1229]
``` csharp
    static void project_BeforeInstall(SetupEventArgs e)
    {
        MessageBox.Show(e.ToString(), "BeforeInstall " + AppSearch.GetProductVersionFromUpgradeCode(e.UpgradeCode));
    }
```

```AppSearch.GetProductVersionFromUpgradeCode(e.UpgradeCode)``` always return false when installing it ever when some other version is already installed, and return true when uninstalling it.

**Comment by oleg-shilo** [comment]
I am not sure what you mean "return false". It returns not `bool` but `Version`.
If it cannot detect the version then I suggest you debug the problem by simply executing a search in a hello-world app without executing your msi.

This is the hint - implementation of `GetProductVersionFromUpgradeCode`:

```C#
static public Version GetProductVersionFromUpgradeCode(string upgradeCode)
{
    try
    {
        var productCode = AppSearch.GetRelatedProducts(upgradeCode).FirstOrDefault();
        if (productCode != null)
            return GetProductVersion(productCode);
    }
    catch { }
    return null;
}
```

**Comment by shengxue** [comment]
@oleg-shilo  I tested this method in ```project_BeforeInstall```, and it returns null. Sorry for the misleading expression in my question!

later on, I tested this method in a custom action, and it returns expected version.   It looks like that related registry is already cleared before ```project_BeforeInstall``` is triggered.

``` csharp
            project.AddAction(new ManagedAction(CustomActions.CheckIfOtherVersionInstalled, Return.ignore, When.After,
                Step.LaunchConditions, Condition.NOT_Installed));
```

**Comment by oleg-shilo** [comment]
if you are upgrading then indeed `project_BeforeInstall` will be fired after the previous version is uninstalled as the result of upgrading. It is how MSI works.

I suggest you try this:
```C#
project.BeforeInstall += args =>
        {
            if (!args.IsUpgradingInstalledVersion
            . . .
```
WixShar captures the installed version for the user before the upgrade.

**Comment by shengxue** [comment]
@oleg-shilo   Thanks a lot for your answers! Really appreciate it!
