### ISSUE TITLE
how can I know if installer runs in '/quiet' mode?

### ISSUE THREAD

**Issue by shengxue** [oleg-shilo/wixsharp#1230]
``` csharp
        static void project_BeforeInstall(SetupEventArgs e)
        {
                MessageBox.Show($"UI level: {e.UILevel}, UISupporesed: {e.IsUISupressed}");
            }
       }
```

The code always shows ``` UI level: 2, UISuppressed: true``` , no matter it runs in '/quiet' mode or not.

how can I know if installer runs in '/quiet' mode?

**Comment by oleg-shilo** [comment]
Note that `UILevel` reflects UI aspects of MSI native UI. Thus, if MSI uses embedded UI (ManagedUI), then MSI runtime always sets this variable to value 2 (silent). Therefore you cannot do much with it.
