### ISSUE TITLE
Invalid product version '2022.11.8'. Product version must have a major version less than 256

### ISSUE THREAD

**Issue by chuongmep** [oleg-shilo/wixsharp#1231]
Hi Developer !  

Can I ask , How we can make version is `Year.Month.Day` ? It mean this is a limit just support for 1.x.x like that ? 

Any respone acpreciated.

**Comment by oleg-shilo** [comment]
This is an MSI limitation thus most likely you will find some answers or workaround on corresponding forums. But there will be nothing that WixSharpo can offer for this as the problem is somewhere in the MSI/WiX layer

**Comment by chuongmep** [comment]
Hi @oleg-shilo,
Can I have any chance to look into open source to add more or require new feature ?

**Comment by oleg-shilo** [comment]
Absolutely. But I suggest you try to investigate the problem first before diving into the solution. A quick googling revealed that it is an MSI problem so it may be difficult to overcome. 

Anyway, I am happy to integrate if you share your solution.

**Comment by chuongmep** [comment]
Thanks @oleg-shilo , I see this is problem is in many year, but I don't know reason why developer don't improve this.

**Comment by CADbloke** [comment]
Perhaps an alternative:

I use vMajor.vMinor.build#.yyddd for reasons...
- MSI upgrades only look at the 1st 3 numbers, if the year+day was 3rd you could only ship once per day. 
- yy is the 2-digit year, 22. By the time that's a problem I will be dead. 
- ddd is the 3-digit day of the year

**Comment by chuongmep** [comment]
@CADbloke that is also a good idea.Thank you.
