### ISSUE TITLE
Apply <SuppressValidation>true</SuppressValidation>

### ISSUE THREAD

**Issue by briangbutterfield** [oleg-shilo/wixsharp#124]
I am experiencing the exact problem identified in [SO](https://stackoverflow.com/questions/38286360/running-wix-on-build-services-in-visual-studio-team-services-was-vs-online-er?rq=1).  However, if I add the following to the WiXSharp csproj is does not have the same effect.

`
<PropertyGroup>
    <SuppressValidation>true</SuppressValidation>
</PropertyGroup>
`

Can anyone help?

**Comment by briangbutterfield** [comment]
It appears this usage works for me.

`project.LightOptions = "-sval";`

**Comment by oleg-shilo** [comment]
Glad you found it. That's exactly what I would suggest to you.
