### ISSUE TITLE
How to change top banner dialog box font color

### ISSUE THREAD

**Issue by sharanraj124** [oleg-shilo/wixsharp#1240]
Hi,

I try to execute MSI build using wixshrp in c# scripts, but I cannot change the font color in showing a dialog box.
The build was successful and the installation also succeeded.

below I added my sample code and screen shot, I am not able to change black color to white

```
var project = new Project(displayName)
{
    InstallerVersion = 500,
    GUID = Uuid5.FromString(Name);,
    Name = "Sample",
    Description = pc.Description,
    OutFileName = Path.Combine(opts.PackageOutDir, opts.PackageName),
    Version = new Version(ap.Version),
    LicenceFile = Path.Combine(
        opts.PackageOutDir,
        Config.Files.PackageLicenseRtf(opts.PackageName)),
    Platform = Platform.x64,
    InstallScope = InstallScope.perMachine,
    UI = WUI.WixUI_Minimal,
    BannerImage = Path.Combine(opts.ResDir, Config.Files.TopBannerBmp),
    BackgroundImage = Path.Combine(opts.ResDir, Config.Files.LeftBannerBmp),
};

Compiler.BuildMsi(project);
```
![Screenshot 2022-11-30 152655](https://user-images.githubusercontent.com/41563058/204765624-cc8f9c6b-6059-4721-8199-29631c914396.png)

**Comment by oleg-shilo** [comment]
I am not sure it is even possible with native WiX UI.

Thus the easiest and most convenient way is to use managed UI.  
I suggest you create your VS project from WixSharp Custom UI template and you will have all dialogs available so you can just change the font colour.

**Comment by sharanraj124** [comment]
Thanks, @oleg-shilo, I will check on my side
