### ISSUE TITLE
Deferred action powershell window incorrect user.

### ISSUE THREAD

**Issue by josejobin45** [oleg-shilo/wixsharp#1242]
Hi,
I am trying to run a command prompt which calls a powershell script from wixsharp using 'project.afterinstall'. I was able to make it run but the user in which it runs is defaulting to workgroup/system. I want the script to be run under the current logged in user. Is it possible?

Thanks.

**Comment by oleg-shilo** [comment]
AfterInstall is running as a deferred action. This is the way MSI allows you to the action elevated.
You can probably easy map it as non-deferred action and then most likely it will impersonate it as current user.

```C#
 var project = 
     new ManagedProject("CustomActionTest",
         new Dir(@"%ProgramFiles%\My Company\My Product",
             new File("script.ps1")),
         new ManagedAction(CustomActions.RunPS, 
                           Return.check, 
                           When.Before, Step.WHATEVER_STEP_YOU_NEED, 
                           Condition.NOT_Installed),
    
    . . .
    
public class CustomActions
{
    [CustomAction]
    public static ActionResult RunPS(Session session)
    {
        var startInfo = new ProcessStartInfo();

        startInfo.UseShellExecute = true;
        startInfo.FileName = "PowerShell.exe"
        startInfo.Arguments = "\"" + session.Property("INSTALLDIR") + "\\script.ps1\"";
        startInfo.Verb = "runas";

        Process.Start(startInfo);

        return ActionResult.Success;
    }
    . . . 
```

**Comment by josejobin45** [comment]
Thanks a lot for the help Oleg. I will check this out.

**Comment by josejobin45** [comment]
It works..Thanks Oleg. I am closing this thread.
