### ISSUE TITLE
Do not build msi during the compilation

### ISSUE THREAD

**Issue by ko-vasilev** [oleg-shilo/wixsharp#1246]
Hello,
Right now when you compile the application, it automatically generates the MSI file (as mentioned in [comment](https://github.com/oleg-shilo/wixsharp/issues/136#issuecomment-325568490))
Is there a way to avoid this behaviour? My MSI builder requires quite a lot of arguments in order for it to be executed correctly, and exits with 1 status code if some of them were omitted (thus the builder compilation fails as it can't build the MSI with the default arguments it supplies)

Thanks!

**Comment by oleg-shilo** [comment]
Yes you can do it by not importing `WixSharp` nuget package (it adds the build step) but `WixShar.bin` instead. It only brings the assemblies and VS will only build the msi builder but not the msi itself.
