### ISSUE TITLE
ManagedBootstrapperApplication how catch error from msi

### ISSUE THREAD

**Issue by Zerpico** [oleg-shilo/wixsharp#1247]
I created ManagedBootstrapperApplication on wpf application.
And MSI package with custom action. If there are errors in custom action, I can't catch it in bootstrap

```csharp
[CustomAction]
public static ActionResult SomeCAction(Session session)
{
    MessageBox.Show("SomeError");
    return ActionResult.Failure;
}
```
I thought I could catch her through:  
```csharp
public BootstrapperSession(BootstrapperApplication bootstrapper)
{
    this.Bootstrapper = bootstrapper;
    this.Bootstrapper.Error += (_, e) => { Cancel();  LogEvent("ERROR", e); };
}
```

but it doesn't work

**Comment by oleg-shilo** [comment]
I don't know the exact mechanism of bobbling MSI errors into the bootstrap application. 
If you find the answer, let me know. I would prefer WixSharp makes it easier to catch these errors if possible.
