### ISSUE TITLE
WixSharp and PackageReference

### ISSUE THREAD

**Issue by bodnarpolina** [oleg-shilo/wixsharp#1249]
Hello! It's more a question than an issue. I'm using _PackageReference_ for my NuGet packages. As I've read here:https://github.com/wixtoolset/issues/issues/6248 _Wix Toool 3_ doesn't support _PackageReference_. I watched the commit to this issue and it was merged to _Wix4_ and they have now release candidate which supports _PackageReference_: https://wixtoolset.org/docs/releasenotes/#v4 As I understand _WixSharp_ uses the installed wix package. So I updated my package from  v311 to release candidate. But for some reason wix is still looking for the packages in a directory: _packages_  rather than in _global packages_: https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders. So, I'm getting an error that 

> The system cannot find the file '..\..\packages\Splunk.Logging.Common.1.7.2\lib\net45\Splunk.Logging.Common.dll' 

So, I don't know maybe it's a still _Wix tool_ issue or maybe it's an integration issue between _WixSharp_ and _Wix tool_. It would be great if you privide any information. Thanx!

**Comment by oleg-shilo** [comment]
Hi Polina,

Indeed location of the packages maybe can be tricky. 

This is how WixSharp does it:
```txt
Gets or sets the location of WiX binaries (compiler/linker/dlls).The default value is the content of environment variable WIXSHARP_WIXDIR. 
If user does not set this property explicitly and WIXSHARP_WIXDIR is not defined [Compiler](https://github.com/oleg-shilo/wixsharp/issues/1249) will try to locate WiX binaries in well known locations in this order: 

<solution_dir>\packages\WixSharp.wix.bin.<max_version>\tools\bin

Program Files\Windows Installer XML v<max_of 3*>\bin
```
```C#
 static public string WixLocation
        {
            get
            {
                if (wixLocation.IsNotEmpty() && !IO.Directory.Exists(wixLocation))
                {
                    Console.Error.WriteLine($"The specified location {wixLocation} was not valid.  Trying other methods to find the Wix assemblies!");
                    wixLocation = null;
                }

                if (wixLocation.IsEmpty()) // Not set from the installer - find it now
                {
                    wixLocation = WixBinLocator.FindWixBinLocation()?.PathGetFullPath();
                    Environment.SetEnvironmentVariable("WixLocation", wixLocation);
                }

                return wixLocation;
            }
            set
            {
                wixLocation = value;

                // prevent interfering with the user defined relative path WixLocation by setting custom CurrentDir 
                if (wixLocation.IsNotEmpty() && !IO.Path.IsPathRooted(wixLocation) && IO.Directory.Exists(wixLocation))
                    wixLocation = wixLocation.PathGetFullPath();

                Environment.SetEnvironmentVariable("WixLocation", wixLocation);
            }
        }
```

I will extend the implementation of `WixBinLocator.FindWixBinLocation()` when WiX v4 becomes reality. It's rather simple.
So please log the feature request when v4 is out. 
Doing it prior WiX4 release is rather expensive. Earlier, I have done two full-scale attempts to provide WiX4 preview integration to discover that it was waste of time due to the volatility of WiX API that was still evolving.

But for now you can simply address this problem by assigning `Compiler.WixLocation` and/or `Compiler.WixSdkLocation`manually. You can even assign it programmatically by implementing your own probing algorithm.
