### ISSUE TITLE
RegParser needs to handle a string value ending with "\n", not only with "\r\n"

### ISSUE THREAD

**Issue by bjlee2000** [oleg-shilo/wixsharp#125]
Hello 

I have a reg file with string values ending with "\n" due to our git configuration. 
Since RegParser and related routines assumes all the line ending with "\r\n", 
string values ending with only "\n" have issues like below.  

1) @= "Windows" ==> "Windows&quot"
2) A following line after a string value makes data type becomes REG_MULTI_SZ insteadf of REG_SZ.

Please could you take a look?

Thanks
BJ

**Comment by oleg-shilo** [comment]
Should be OK now with the [26092e](https://github.com/oleg-shilo/wixsharp/commit/26092e67852a5b4c452dd201068261de22c7ee5d) commit.

You can test the latest binaries from [here](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/WixSharp.dll).
