### ISSUE TITLE
Old version is not uninstalled 

### ISSUE THREAD

**Issue by serezlan** [oleg-shilo/wixsharp#1252]
Hi,

When I installed newer version, I can see in "Add/Remove Program" that the old one is still there. 
Here's my code:

var project = new ManagedProject(GetProductNameWithVersionNumber(),
                         new Dir(string.Format("%ProgramFiles%\\{0}\\{1}", cfg[Util.Config.CompanyNameKey], cfg[Util.Config.ProductNameKey]),
                 new Files(cfg[Config.BaseDirKey] + "*.*")));

            project.GUID = new Guid(cfg[Config.ProductGUIDKey]);
            project.ProductId = Guid.NewGuid();
            project.UpgradeCode = new Guid(cfg[Config.UpgradeCodeKey]);
            project.Version = GetVersionNumber();

            project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
            project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;

Could you help me find out what's wrong?

Thanks

**Comment by Torchok19081986** [comment]
morning, AFAIK ProductId property should be always the same. This is GUID for MSI Installer, which identify over Uninstall GUID in Registry. IF you set it als always new one, MSI could not find it , and install always package as first one. Set ProductId to some your choosed GUID like new Guid(<Your-GUID-Value-Goes-Here>). 

best regargs. 
Torchok

**Comment by oleg-shilo** [comment]
Thank you @Torchok19081986 
Your description of the process is accurate. Though the terminology requires clarification. It is not _ProductId_ that should always be the same but _UpgradeCode._

This topic can be confusing so the best way of achieving "upgradeable" MSIs is not to try to assign those IDs as in the original post, even though it is possible. Instead, you should set only set a single property `project.GUID` to the same GUID value for all setups that you ever build for this product. In this case, the correct combination for _ProductId_ and _UpgradeCode_ will be generated for you.

The details are here: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming

Saying that if for whatever reason it is preferred to set both _ProductId_ and _UpgradeCode_ explicitly then I suggest you play with the MajorUpgrade samples and see how the correct combinations of the _ProductId_ and _UpgradeCode_  are auto-generated and then try to replicate it manually for your product.

**Comment by serezlan** [comment]
Thanks for your prompt reply.

After some additional tests, this problem only occur on different build number.On different major/minor/revision number everything works as expected.

**Comment by oleg-shilo** [comment]
Great. Yes indeed MSI only recognises 3 parts version. :(
