### ISSUE TITLE
Communication between custom action events

### ISSUE THREAD

**Issue by serezlan** [oleg-shilo/wixsharp#1254]
Hi,

I need to create variable in beforeInstall event and use it in AfterInstall event.
If I set property in pre-install event and access it in post install, I get the following error

cannot access session details from non-immediate custom action 
Is there solution for this?

Thanks

**Comment by oleg-shilo** [comment]
Look at the "Setup Events" sample. It does exactly what you need:
![image](https://user-images.githubusercontent.com/16729806/212471718-900d8709-2920-429a-8a5c-60db7f5c8248.png)

**Comment by serezlan** [comment]
perfect!

thanks :)
