### ISSUE TITLE
Create 64 bit bundle

### ISSUE THREAD

**Issue by josejobin45** [oleg-shilo/wixsharp#1256]
Hi,

I created a bundle with 2 msi's and it is working fine. But after I sign it with some certificate it is not working. I believe it is because the bundle is 32 bit. How can I change it to 64 bit.

Thanks.

**Comment by oleg-shilo** [comment]
I am not sure you can control CPU architecture of the bundle executable. But if you do then the answer will be in the WiX Bootstrapper documentation.

Let's say there is a CLI parameter that does the trick. Then you can pass the parameter with WixSharp and do the same. But first, you will need to understand that it such a trick is possible.

**Comment by josejobin45** [comment]
The issue with my signing was because I was not signing the engine with insignia. 32 bit was not the issue. The problem is solved currently but I will be working on how to change the bundle architecture. I will update here if I find a method. Thanks oleg

**Comment by Torchok19081986** [comment]
morning, found link for Wix V4 and future request for enhancement . https://www.joyofsetup.com/2021/06/05/wix-v4-random-fact-no.-4/
