### ISSUE TITLE
Change/Repair installation - key not found in SetupEventArgs.Data in AfterInstall event

### ISSUE THREAD

**Issue by Karol-Zdunek** [oleg-shilo/wixsharp#1257]
Hello. I found possible issue when doing "Change" installation (Managed Setup with custom UI).
(using WixSharp 1.20.3)
In one of the custom UI dialog I am reading "TRAVELDATE_OPTION" data from the user and assigning it to MsiRuntime.Data which is a 
_"Repository of the session properties to be captured and transfered to the deferred CAs."_
my code:
```
void next_Click(object sender, EventArgs e)
{
    MsiRuntime.Data["TRAVELDATE_OPTION"] = radioButton1.Checked ? "FlexDate" : "ExactDate";
    Shell.GoNext();
}
```
Its all works fine for standard installation - I can access this variable/data in "AfterInstall" event:
```
project.AfterInstall += args => {
    if (!args.IsUninstalling)
    {
        args.Data.TryGetValue("TRAVELDATE_OPTION", out var dateOption);
        ...
    }
};
```
**the problem is happening when I run Change installation - simply args.Data does not contain "TRAVELDATE_OPTION" key**...
Is this a bug or I simply need to handle this logic somehow different in case of Change or Repair installation?

**Comment by oleg-shilo** [comment]
Unfortunately, it is not a defect but a limitation.
That session data only exists during the session and MSI does not persist it after the install is finished. Thus you will need to persist it by yourself in some sort of config file that can be read during the modification session.

**Comment by Karol-Zdunek** [comment]
Let me clarify my findings (sorry, maybe I was not accurate enough ).
The problem I am facing is actually at "modification session" (change installation) 
and I have on that session my custom dialog as well 
(to receive TRAVELDATE_OPTION from the user). 
In fact I am reading this setting from config file on custom dialog load event, and later passing on next click to MsiRuntime.Data["TRAVELDATE_OPTION"]

```
project.ManagedUI.ModifyDialogs
    .Add<MaintenanceTypeDialog>()
    .Add<TravelDateOptionDialog>()
    .Add<ProgressDialog>()
    .Add<ExitDialog>();
```
So on modification session I am also taking "TRAVELDATE_OPTION"  from the user (in custom 'TravelDateOptionDialog')  
...and unfortunately 'AfterInstall' event show that "TRAVELDATE_OPTION" is not in args.Data.
'AfterInstall' is triggered also at the end of "Change" installation.

**Comment by oleg-shilo** [comment]
> sorry, maybe I was not accurate enough

I think you explained it well even the first time :)

When you trigger "change install" the  "modification session" starts from scratch. Some of the core properties are persisted by MSI from the previous "install session". IE InstallDir. 

However MSI does not do it for other user defined session properties. Like yours. I just retested it with the  "Setup Events" sample that is designed for that:
![image](https://user-images.githubusercontent.com/16729806/213912029-e4bc6dc7-4354-4906-b091-202c24172abb.png)

Thus for some reliably persistent properties you cannot use session but order data storage solutions. IE, files, registry.

> 'AfterInstall' is triggered also at the end of "Change" installation.

Correct. In the MSI terminology the time point Before/After install referred to the whole session regardless of it's nature (install, repair, modify, uninstall). AfterInstall event after any MSI execution.
