### ISSUE TITLE
Wix catastrophic failure

### ISSUE THREAD

**Issue by paokakis** [oleg-shilo/wixsharp#1260]
I'm not sure if I should post this here but here I go.
I had an installer for a project that I'm building which worked fine 6 months ago. Without any changes in the installer project I tried to build today and got the following error :

`light.exe : error LGHT0001: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
  
Exception Type: System.Runtime.InteropServices.COMException
  
Stack Trace:
at Microsoft.Tools.WindowsInstallerXml.Cab.Interop.NativeMethods.CreateCabFinish(IntPtr contextHandle, IntPtr newCabNamesCallBackAddress)
at Microsoft.Tools.WindowsInstallerXml.Cab.WixCreateCab.Complete(IntPtr newCabNamesCallBackAddress)
at Microsoft.Tools.WindowsInstallerXml.CabinetBuilder.CreateCabinet(CabinetWorkItem cabinetWorkItem)
at Microsoft.Tools.WindowsInstallerXml.CabinetBuilder.ProcessWorkItems()`

I'm not sure if I'm doing something wrong. I tried to change the generation of Cab files to multiple files in case the size of the MSI is too big for the OS. One note since the last time that I built the installer I upgraded my OS to Windows 11, if that matters.

The version of wix is 3.11.2

**Comment by paokakis** [comment]
I found the issue. It was indeed because of file size. I needed to add the following code to split all files to different cab files : 
`            int idx = 0;
            foreach (var file in project.AllFiles)
            {
                file.AttributesDefinition = $"DiskId={(idx % 6) + 1}";
                idx++;
            }`

**Comment by oleg-shilo** [comment]
Great. Thank you for sharing the work around.
