### ISSUE TITLE
Localization bootstrapper

### ISSUE THREAD

**Issue by EfimUserR** [oleg-shilo/wixsharp#1264]
I need to wrap the msi in a wixsharp.bootstrapper. I did it. Now I want to translate all the text in the bootstrapper into Russian and replace some of the displayed messages with others.I did this in msi through the language property and the wxl file. I tried to do the same in the bootstrapper. This doesn't work when I change the language to Russian anyway. If I connect the wxl file in bootstrapper then app stops running and giving error.
Error 0x80070490: Failed to initialize data in bootstrapper application.
Could you tell me what I'm doing wrong, and how I can translate it into Ru?
`string productMsi = BuildMsi();

            var bootstrapper =
              new Bundle(nameProduct,
                  new MsiPackage(productMsi) { Compressed = true })
              {
                  Version = new Version(1, 0, 0, 0),
                  UpgradeCode = new Guid(guid),
              };
            bootstrapper.Application.SuppressOptionsUI = true;
            bootstrapper.Language = "ru-RU";
            bootstrapper.Application.LocalizationFile = @"WixUI_ru-ru.wxl";
            bootstrapper.Application.LogoFile = "favicon.ico";
            bootstrapper.IconFile = "favicon.ico";
            bootstrapper.Build($"{nameProduct}_Setup_{bootstrapper.Version}.exe");`

**Comment by Torchok19081986** [comment]
Morning, there is Sample of BA Installer with MultiLanguage. Get a Copy of latest Wix# Samples. Navigate to Folder Samples\Bootstrapper\MultiLanguageSupport. Sample shows how to make BA Installer Multilanguage. I dont think, you can choose only one Language for BA, cause MSI is mainlanguage en-US and you localize MSI , not BA. Try it. 
Best regards.

**Comment by EfimUserR** [comment]
I tried to change my code as show in the example you were talking about. I get errors when I try to run the project. Looks like I did something wrong. I'm gonna try to run the project later anyway. However I see in the project code that the language is changed for msi, not for bootstrapper. In my case bootstrapper is used to run msi which runs in the background without pop-up windows. User can see only bootstrapper UI and that's why I need to translate its UI into RU. I have no problem to do this for msi. msi is translated into RU well even as the only language. There is still a question with the localization file. How can I change text in bootstrapper to other that I need?

**Comment by Torchok19081986** [comment]
Morning, for msi project in Wix#, you have to add .wxl file as localization. Msi build it with your added wxl localize file. 
As for BA Installer there is Theme Property.  I dont try it, but for Path "C:\Program Files (x86)\WiX Toolset v3.11\SDK\themes\"
, if you have installed Wix Toolset 3.11 .  I think if Ru Language not exists there, you can google it or chage one of them file for your BA Installer and add it to Installer . Try it.

**Comment by EfimUserR** [comment]
Hello, thank you for your reply. You helped me a lot. I used file 1049.wxl by path "C:\Program Files (x86)\WiX Toolset v3.11\SDK\themes" and added it as payload. Everything has been translated. There weren't translatings many elements and I needed to add them by hand but it doesn't matter. By the way, I found a little bug. For some reason if I try to delete app with non-standard way in windows and I use deleting programs from control panel instead then BA user interface won't be translated. However, if I use "change" option insted "delete" option, then everything will be transtaled correctly. It's not important for me but it's interesting. The problem is in windows as I understand it.

P.S.
I would like to say something for people who found the answer to their question in this thread. Probably you will need to add another file as called "theme" to your program because some words is shown incorrecly in terms of styles after translating.
