### ISSUE TITLE
An error (E_FAIL) was returned while finalizing a CAB file

### ISSUE THREAD

**Issue by CarloPoletto** [oleg-shilo/wixsharp#1265]
I need to create an .msi file using WixToolset v.3.11.2 and WixSharp v1.9.2. The .msi file must also contain a folder with many files inside (more than 12000). However, this generates an error: 

```
An error (E_FAIL) was returned while finalizing a CAB file. This most commonly happens when creating a CAB file with more than 65535 files in it. Either reduce the number of files in your installation package or split your installation package's file into more than one CAB file using the Media element.
```

How do I use the Media element to split my installation package into more than one CAB file?

**Comment by Torchok19081986** [comment]
Hallo,

Wix says https://www.joyofsetup.com/2011/06/21/wix-and-cabinetry/

Try WixGeneratedSource event for achive that or maybe Oleg know better solution.

**Comment by oleg-shilo** [comment]
I cannot give you full guidance on how to use `Media` and `MediaTemplate` WiX elements. It is WiX matter.
But WixSharp supports both of them:

```C#
var project = new Project("My Product",
                  new MediaTemplate { CompressionLevel=CompressionLevel.high },
                  new Dir(@"%ProgramFiles%\My Company\My Product",
                  ...
```

```C#
 var project = new Project("My Product",
                   new Dir(@"%ProgramFiles%\My Company\My Product",
        
                   ...
        
project.Media.First().Id = 2;
project.Media.First().CompressionLevel = CompressionLevel.mszip;
```
