### ISSUE TITLE
Question : Wix V4 Long standing Bug for BA Installer with internal UI 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1267]
Morning, aka Wix V4 is now able to create BA Installer with intenal UI. 
Link : 
https://wixtoolset.org/docs/releasenotes/

Section : "Burn, bundles, and bootstrapper applications"

...
    - The new [WixInternalUIBootstrapperApplication](https://wixtoolset.org/docs/reference/schema/bal/wixinternaluibootstrapperapplication/) BA supports showing only the internal or embedded UI of an MSI package.
...

Any idea, when we can use it in Wix# or wait for Stable Wix V4 ? Currently is RC2.

**Comment by oleg-shilo** [comment]
Oh... It is still not released. It is only an RC. I missed your message last line.
We will still need to wait til it is officially out.

**Comment by christophwille** [comment]
https://github.com/wixtoolset/wix4/releases/tag/v4.0.0 seems to be the case now (that it is released)

**Comment by oleg-shilo** [comment]
Great. then the work starts :)

**Comment by Torchok19081986** [comment]
morning @oleg-shilo , where can i get example of wixsharp for WixInternalUIBootstrapperApplication : internal or embeded UI ? 
i have to transfer my BA Installer base on wixtoolset 3.11 to new Wix V4 and newst Wixsharp ? 
Many Thanks

**Comment by oleg-shilo** [comment]
It's the same sample as before: `WixBootstrapper_NoUI`

**Comment by Torchok19081986** [comment]
morning, @oleg-shilo. Many Thanks. I will try it. Last Question:  in old wix toolset 3.11, i couldnt create custom UI for MSI , because of this bug, but in Wix V4 is possible, right? 
I would like add custom UI  to my BA Installer. I have to add sql server choose Dialog, user credentials so on.  Summary 5 external Dialogs in BA.

**Comment by oleg-shilo** [comment]
>but in Wix V4 is possible, right?

yes it is.

Look at this sample:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/96152a27-d500-403a-9205-0973e8fb828b)

It shows "how to"

**Comment by oleg-shilo** [comment]
But use the `wix-v4-master` branch

**Comment by Torchok19081986** [comment]
ok, i need some explanation. I downloaded latest src of WixSharp. But i cant compile it.  do i have to download latest wix-v4 source and somehow add it to wixsharp MultiLanguage Project ? WixToolset.Mba.Core Package is already exists in Project. 
Sry, that i need again your help.
