### ISSUE TITLE
How to change the temporary folder used by WixSharp when building an MSI file?

### ISSUE THREAD

**Issue by CarloPoletto** [oleg-shilo/wixsharp#1268]
I am using WixSharp v1.9.2.0 to build an MSI file, but when I call the `project.BuildMsi()` method, WixSharp creates temporary files in the `%Temp%` folder of Windows. However, my project is quite large, and soon my C drive is full, causing the MSI creation to fail.

Is there a way to change the folder that WixSharp uses for its temporary files? If so, how can I do that?

Thanks

**Comment by snechaev** [comment]
Answer may be found here https://stackoverflow.com/questions/75589381/how-to-change-the-temporary-folder-used-by-wixsharp-when-building-an-msi-file. In short, it overrides `%TEMP%` environment variable for msbuild before executing main wix# targets.

So, looks this issue may be closed, unless Oleg will decide to implement any different / simplier solution for the problem.

**Comment by oleg-shilo** [comment]
Actually WixSharp is very gently to the team dirs and deletes all temp files it creates during the build unless:

- build fails
- or `project.PreserveTempFiles = true;` is set

If you found that the cleanup incomplete, please let me know and I will fix it.

Though any other tools in the MSI build chain (e.g. candle.exe, light.exe) may still create some files in the system temp folder. Then WixSharp has no business removing them. The solution suggested by @snechaev might be what you are looking for in this case.
