### ISSUE TITLE
Set File and Directory permissions in the ProgramDataFolder

### ISSUE THREAD

**Issue by kazachok13** [oleg-shilo/wixsharp#1269]
Hi, have an app that is installed in Program Files folder:

`new Dir("%ProgramFiles64Folder%",
                new Dir(CompanyName,
                    new Dir(new Id(Compiler.AutoGeneration.InstallDirDefaultId), ProductName,
                        new DirPermission("Users", GenericPermission.All),
                        new WixSharp.File(Path.Combine(TargetPath, $"{ProductName}.exe"),
.......
`

I also have a Directory in ProgramData folder:
`new Dir(@"%CommonAppDataFolder%",
                new Dir(CompanyName,
                    new Dir(ProductName,
                        new DirPermission("Everyone", GenericPermission.All),
                        new DirPermission("Users", GenericPermission.Write | GenericPermission.Read) { 
                            Delete = true, 
                            CreateFile = true, 
                            CreateChild = true
                        })))`

Installation goes through fine, Admin user runs the app fine.
The application creates additional subfolders under ProgramData\[ProductName]
`config`  with `appssettings.json` file (there are a few of them), and `logs` as well as database files `MyDB.mdf` and `MyDB_log.ldf`

Database files are created first time when the app starts and db is MSSQL localdb files.

But when I login as a standard user, the app will not launch and the Log Viewer shows that exception is access is denied to that `appsettings.json` file.

How do I set permisssions for all the users for the files that have not been created yet by the applicaiton?
Or is there something I am missing?

Thank you.

Tim

**Comment by Torchok19081986** [comment]
morning, i think you have to crreate Custom Actions in C# and run it at installation of your app. 

MS Code for FilePermission 

```chsarp

public static void AddFileSecurity(string fileName, string account,
            FileSystemRights rights, AccessControlType controlType)
        {

            // Get a FileSecurity object that represents the
            // current security settings.
            FileSecurity fSecurity = File.GetAccessControl(fileName);

            // Add the FileSystemAccessRule to the security settings.
            fSecurity.AddAccessRule(new FileSystemAccessRule(account,
                rights, controlType));

            // Set the new access settings.
            File.SetAccessControl(fileName, fSecurity);
        }
```

Diffuculty is identfy File 

Try follwing : Create own Session Property for MSI like APPSETTIONSJSON. 
then in set Property to Filepath in another CA like session["APPSETTIONSJSON"] = "your path goiing there". After that runs code form beofre also as CA. your filename paramter is your session Property. 
should work. Had also struggle on that. 

best regards, Torchok

**Comment by kazachok13** [comment]
Hi Torchok, thank you for the reply.
I will try it out, but yes, there are a quite a few other config files and log files that will be created as the application runs.
So I think it should be a way to specify root folder permissions for /Write/Create/Create subfolders and files just for the top folder and permissions would propagate down.
Cause I can login as admin and set the permissions for the top folder for standard users and check the  “Replace all child object permission entries with inheritable permission entries from this object” in the Security Settings for that folder and Click Apply.
Curious if anyone was able to do it similarly in the WixSharp/Wix.

Thank you

**Comment by Torchok19081986** [comment]
Hiho, kazachok13. No Problem. I think biggest Difficulty here is ACL for custom Files / Groups. Security for Windows User. 
But...
there is some Light at End of Road. 
You can force MSI start as Admin. WixSharp provides code for this. And then you can try to create your own Install Logic in pure C#. 

Maybe some Pinvoke at lowest Level in Windows . 

i found link : 
https://www.pinvoke.net/default.aspx/Enums/FILE_FS_ATTRIBUTE_INFORMATION.html

This can be invoke at runtiime in MSI, Try some different approaches. Maybe one of them you can use for MSI installation and Permissions of your Files. 

Only Oleg self can provide more info about your Challenge 😉😉😉

Best regards. Torchok.

**Comment by kazachok13** [comment]
I appreciate the feedback and help with this. We use ProgramData/Company/ProductName/ directory to store DB and config files for the application and those need to be shared among all the users, so I was trying to have that location accessible for read/write. I ended up using Torchok's suggestion using custom action and setting permissions for that folder/files.
Thanks
