### ISSUE TITLE
Desktop shortcut gets installed to C:\DesktopFolder

### ISSUE THREAD

**Issue by jimfoye** [oleg-shilo/wixsharp#127]
[Moved from Codeplex]

Originally I was using FileShortcut (see the commented line below) but I want to set a condition, and while FileShortcut has a Condition property, I'm warned not to use it and the build fails if I do. So I'm following some other examples that I have seen, and using ExeFileShortcut instead.

So now here's what I do (this is in F#):

```
let desktopShortcut = ExeFileShortcut(productName, "[INSTALL_DIR]Downhole.LasDoctor.exe", "")
desktopShortcut.Condition <- Condition("INSTALLDESKTOPSHORTCUT=\"yes\"") 

let project = ManagedProject(productName, 
                new Dir(@"%Desktop%", desktopShortcut),
                new Property("INSTALLDESKTOPSHORTCUT", "no"),
                new Property("ENABLESHELLINTEGRATION", "no"),
                new Dir(@"%ProgramFiles%\Downhole Software\LAS Doctor",
                    new File(binDir "Downhole.LasDoctor.exe",
                        new FileShortcut(productName, @"%ProgramMenu%\Downhole Software\LAS Doctor"),
                        //new FileShortcut(productName, "%Desktop%"),
                        new FileAssociation("las")),
                    new File(binDir "Downhole.LasDoctor.exe.config"),
// etc.

```
Before I made this change the shortcut was installed to the desktop. Now it installs it to "C:\DesktopFolder"!

Here's the generated snippet from the .wxs file, maybe this is helpful:

```
<Directory Id="INSTALLDIR" Name="DesktopFolder">

<Component Id="LAS_Doctor_" Guid="f0c6a396-9b2a-4f8d-9f57-5c9b819aa252">
  <Condition>INSTALLDESKTOPSHORTCUT="yes"</Condition>

  <Shortcut Id="INSTALLDIR.LAS_Doctor_" WorkingDirectory="INSTALL_DIR" Target="[INSTALL_DIR]Downhole.LasDoctor.exe" Name="LAS Doctor.lnk" />

  <CreateFolder />

  <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
    <RegistryValue Value="0" Type="string" KeyPath="yes" />
  </RegistryKey>
</Component>

</Directory>

```
Any ideas?

Also, how do I set a condition for a FileAssociation? That does not even have a Condition property. I have the UI working and it correctly sets the property in the current session, I just need to know how to make FileAssociation check the condition. Or maybe I have to manually create the association in a custom action now?

Thanks.

**Comment by oleg-shilo** [comment]
Most likely the problem is caused by the fact that the Desktop dir has been marked with the INSTALLDIR id. 
This is because Wix# is automatically assigning the INSTALLDIR id to the first directory in the dirs declaration. This is the way of integration MSI UI and a specific directory from the setup.

If auto-assignment is not desired for whatever reason then you should set all IDs manually as you would do it in raw WiX. Alternatively you can also manually indicate which directory is an INSTALLDIR by setting `Dir.IsInstallDir` to true.

Though for many practical reasons it's just easier (and more readable) to keep your install dir first and let Wix# do the id auto-assignment. I expect that you would solve your problem by simply placing Desktop dir below the "LAS Doctor" dir:

```F#
let project = ManagedProject(productName, 
                new Property("INSTALLDESKTOPSHORTCUT", "no"),
                new Property("ENABLESHELLINTEGRATION", "no"),
                new Dir(@"%ProgramFiles%\Downhole Software\LAS Doctor",
                    new File(binDir "Downhole.LasDoctor.exe",
                        new FileShortcut(productName, @"%ProgramMenu%\Downhole Software\LAS Doctor"),
                        //new FileShortcut(productName, "%Desktop%"),
                        new FileAssociation("las")),
                    new File(binDir "Downhole.LasDoctor.exe.config"),
                new Dir(@"%Desktop%", desktopShortcut),
```

**Comment by jimfoye** [comment]
Thanks, Oleg. When I shift that down as you suggested it works.

Also, I had to change "INSTALL_DIR" to "INSTALLDIR". I saw the former in your examples, but I realize now that in those examples you're explicitly setting the ID on the installation directory, and I was not. But I assume that not setting the ID and relying on "INSTALLDIR" is safe, as it seems to work.

Thanks again. Wix# is awesome. It is sad to think of how many millions of man-hours have probably been wasted over the decades due to Microsoft's installer technology being the way it is.

**Comment by oleg-shilo** [comment]
>...not setting the ID and relying on "INSTALLDIR" is safe

Yes it is safe. The first dir is always getting Ids assigned automatically for all XML elements (including "INSTALLDIR") automatically unless the developer opted in the explicit Id assigning. And the Id value 'INSTALLDIR' is just a name that became a de-facto naming standard for the setup destination folder.

BTW, the name 'INSTALLDIR' can be changed to anything else by adjusting `AutoGenerationOptions.InstallDirDefaultId` property.

>  It is sad to think of how many millions of man-hours have probably been wasted over the decades due to Microsoft's installer technology being the way it is.

I am with you 100%. It's like it was written for aliens. Just judging from your remark, I think you would find interesting my interview on the same subject for InfoQ (https://www.infoq.com/articles/WixSharp).

**Comment by jimfoye** [comment]
I read that interview when it came out. That's how I learned about WixSharp. 😄
