### ISSUE TITLE
SetupTypeDlg not available with NativeDialogs

### ISSUE THREAD

**Issue by rykr** [oleg-shilo/wixsharp#1272]
I was trying to skip the license page and go straight from Welcome to Setup Type.  I was able to do this with Compiler_WixSourceGenerated but was unable to do this with DialogSequence.  Is this not possible with DialogSequence?

**Comment by oleg-shilo** [comment]
You may want to have a look at `Skip_UIDialog` sample:

```C#
        project.CustomUI = new DialogSequence()
                                   .On(NativeDialogs.WelcomeDlg, Buttons.Next, new ShowDialog(NativeDialogs.InstallDirDlg))
                                   .On(NativeDialogs.InstallDirDlg, Buttons.Back, new ShowDialog(NativeDialogs.WelcomeDlg));
```

Though....
This functionality was implemented a very long time ago to achieve UI customization with Native MSI UI.
The customization developer experience is not great. And troubleshooting is complicated. Basically, it was a dead-end direction.

Thus an alternative approach "Managed UI' was introduced and today it is a recommended UI customization.
