### ISSUE TITLE
Offline Installer

### ISSUE THREAD

**Issue by mtseytli** [oleg-shilo/wixsharp#1273]
Hi, I am trying to create an offline installer for my program, that has many prerequisites that have to be downloaded.
In the online version I used a Bootstrapper with ExePackage and DownloadUrl provided, but seems like the downloaded programs are deleted right after they are installed.
Is there a way to keep the programs on the computer to allow offline installation?

Thank you!
Maria

**Comment by Torchok19081986** [comment]
Hiho Maria, according to Wix itself, you can keep your payload Packages if you set it as Permament , Permanent = "yes" or True. 
Dont know for sure, AFAIK Permanent Packages means, you cant uninstall them. Try in separate Testproject. 
Maybe this can help you ,

best regards, 
Torchok
