### ISSUE TITLE
Action BeforeInstall in ManagedProject don't run in Bootstrap

### ISSUE THREAD

**Issue by Zerpico** [oleg-shilo/wixsharp#1274]
I have created a ManagedProject and some actions on  event ```BeforeInstall```.

```csharp
project.BeforeInstall += (s) =>
{
   //some actions
};
```
 It is executed if I run the MSI file, but it is not executed when I run the **Bundle** inside which my project is

I created a custom ManagedBootstrapperApplication, maybe that's the reason. But shouldn't be

```csharp
var bootstrapper = new Bundle(bundleName)
{
    Language = "ru-ru",
    Version = version,
    UpgradeCode = new Guid("1f390b47-2569-43ad-9095-1861bb25844b"),
    SuppressWixMbaPrereqVars = false,
    Application = new ManagedBootstrapperApplication(Path.Combine(itemsDir, "SetupServerBootsrapGui.dll"))
    {
        Payloads = new string[]
        {
              "BootstrapperCore.config",
              Path.Combine(itemsDir, "Newtonsoft.Json.dll"),
              Path.Combine(itemsDir, "MaterialDesignColors.dll"),
              Path.Combine(itemsDir, "MaterialDesignThemes.Wpf.dll")
        }.Select((string x) => x.ToPayload()).ToArray(),
    }
};

bootstrapper.Chain.Add(new MsiPackage(MyProductMsi));
```

**Comment by oleg-shilo** [comment]
The fact that the isolated msi fires this event indicates that the custom action is scheduled and executed correctly. 

So the problem is in the bootstrapper.
Cannot really help you with that...

**Comment by Zerpico** [comment]
> The fact that the isolated msi fires this event indicates that the custom action is scheduled and executed correctly.
> 
> So the problem is in the bootstrapper. Cannot really help you with that...

Yes indeed, I checked the action starts, but after installing the files
