### ISSUE TITLE
Conditional Installation

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1275]
Hallo, I have BA Installer where i start install MSI from UI. This far runs well, but if i create checkbox at GUI in Installer for example  Checkbox "install additionally as Plugin", it doesnt start. I want start second msi. if Checkbox equals True, then msi should install it as plugin in additonally MSI package at end of installation. I thought start from Example of "Conditionally Installation". 

in Version 1.20.3 of Conditionally Installtion  
```csharp

    static public void Main()
    {
        //Note that if the install condition for the component can be set without interacting with user (e.g. analysing registry)
        //as part InstallExecuteSequence. However if interaction is required (e.g. message box, checkbox) install condition should
        //be set form InstallUISequence.

        string installDir = @"%ProgramFiles%\My Company\My Product";

        Project project =
                new Project("My Product",

                    //Files and Shortcuts
                    new Dir(installDir,
                        new File(@"AppFiles\MyApp.exe",
                            new FileShortcut("MyApp", @"%ProgramMenu%\My Company\My Product")),
                        new ExeFileShortcut("Uninstall MyApp", "[System64Folder]msiexec.exe", "/x [ProductCode]")),

                    new Dir(@"%ProgramMenu%\My Company\My Product",
                        new ExeFileShortcut("Uninstall MyApp", "[System64Folder]msiexec.exe", "/x [ProductCode]")),

                     new Dir(@"%Desktop%",
                        new ExeFileShortcut("MyApp", "[INSTALLDIR]MyApp.exe", "")
                        {
                            Condition = new Condition("INSTALLDESKTOPSHORTCUT=\"yes\"") //property based condition
                        }),

                    //setting property to be used in install condition
                    new Property("INSTALLDESKTOPSHORTCUT", "no"),
                    new ManagedAction(CustomActions.MyAction, Return.ignore, When.Before, Step.LaunchConditions, Condition.NOT_Installed, Sequence.InstallUISequence));

        project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
        project.UI = WUI.WixUI_ProgressOnly;
        project.OutFileName = "setup";
        project.PreserveTempFiles = true;

        Compiler.BuildMsi(project);
    }
}

public class CustomActions
{
    [CustomAction]
    public static ActionResult MyAction(Session session)
    {
         session["INSTALLDESKTOPSHORTCUT"] = "yes";
        return ActionResult.Success;
    }
}

```

How can i do it in BA with multiple MSI packages with Conditon ? If  Property equals "True" or "yes" and delegate it to BA ?

**Comment by Torchok19081986** [comment]
ok, thanks for reply , @oleg. I found in Examples WixBootstrapper with CustomTheme. There ist description of Checkbox for additionally Installation of the second MSI. MSI instlal second package on condition, what i can set it, and install it in same session. No Problem with that. 
I only dont understand, how i can set GUI for Interface of Installer. In Example is Theme als Xml file, but i need it in WPF Window and maybe pure C#.
```csharp

 bundle.Application.ThemeFile = Path.Combine(itemsDir, "Resources", "RtfTheme.xml");

```

How can i create custom UI instead of set ThemeFile ?

**Comment by oleg-shilo** [comment]
You can simply create a custom bootstrapper WPF UI. 
And put the check box there. And then use the value of the check box to decide which msi to engage.

If you still want to use bootstrapper stock UI then you should apply the theme file but the approach will be the same. The checkbox is going to be in the BA not in msi-UI.

I think your idea of using checkbox in bootsrtapper instead of msi-UI is much better and will work.

**Comment by Torchok19081986** [comment]
morning, @oleg. Thanks for answer.  Last questions: how bootstrapper controls multiple msi ? Update or Upgrade for Package newer Version ? Controlinfopanel, shows all Packages, not only bootsrapper Package? Do i have to control it in MSI Project description or in BA self? Ideal, i would like to show all packages in Controlpanelinfo, but if not and it technically not possible, also ok.

**Comment by oleg-shilo** [comment]
WixBootstrapper_NoUI sample can show you the most advanced technique of controlling the detection of the msis and the actions to take:
```C#
DetectPackageComplete += (s, e) =>
{
    //Presence or absence of MyProductPackageId product will be a deciding factor
    //for initializing BA in Install, Uninstall or Modify mode.
    if (e.PackageId == "MyProductPackageId")
    {
        switch (e.State)
        {
            case PackageState.Obsolete:
                this.Engine.Log(LogLevel.Error, string.Format(DowngradeWarningMessage, e.PackageId));
                MessageBox.Show(string.Format(DowngradeWarningMessage, e.PackageId), this.Engine.StringVariables["WixBundleName"], MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                Engine.Quit(0);
                break;

            case PackageState.Absent:
                this.Engine.Plan(LaunchAction.Install);
                break;

            case PackageState.Present:
                this.Engine.Plan(LaunchAction.Uninstall);
                break;
        }
    }
};
```

But in most cases just including multiple MSIs and letting the default detection algorithm take place will be enough. So you don't need to go to so much troubles as in the code above.

As for what to show in the control panel, most likely it is something that you can find in WiX forums.

**Comment by Torchok19081986** [comment]
Many Thanks, @oleg. 👍
