### ISSUE TITLE
Bootstrapping and features

### ISSUE THREAD

**Issue by stannynuytkens** [oleg-shilo/wixsharp#1276]
Hi,

I've built a simple MSI builder project driven by configuration to build basic MSI projects.
This project _(exe)_ will be used at the end of a pipeline to produce redistributable MSI files. Now most of the time
I'd like to bundle the output (all of the MSI files).

The caveat is that I want to enable feature selection (also configuration) to decide which MSI files need to run. Is this possible?

**Comment by oleg-shilo** [comment]
If you want to bundle multiple msi then you need to use MSI Bundle. Have a look at Bootstrapper samples.
Quite possibly you may need to implement custom bootstrapper UI to allow feature selection.

**Comment by Torchok19081986** [comment]
morning, acordning to Stackoverflow , you have to add in BA config file following description : 

<BootstrapperApplicationRef Id="ManagedBootstrapperApplicationHost" >
  <Payload SourceFile="$(var.InstallSourceResources)Bootstrapper\FusionInstallUX.dll"/>
  <Payload Id="FusionInstallUX.config"
           SourceFile="$(var.InstallSourceResources)Bootstrapper\FusionInstallUX.BootstrapperCore.config"
           Name="BootstrapperCore.config" Compressed="yes"/>
</BootstrapperApplicationRef>

and 

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <sectionGroup
            name="wix.bootstrapper"
            type="Microsoft.Tools.WindowsInstallerXml.Bootstrapper.BootstrapperSectionGroup, BootstrapperCore">

            <section
                name="host"
                type="Microsoft.Tools.WindowsInstallerXml.Bootstrapper.HostSection, BootstrapperCore" />
        </sectionGroup>
    </configSections>

    <startup useLegacyV2RuntimeActivationPolicy="true">
        <supportedRuntime version="v4.0" />
    </startup>

    <wix.bootstrapper>
        <host assemblyName="FusionInstallUX">
            <supportedFramework version="v4\Full" />
            <supportedFramework version="v4\Client" />
        </host>
    </wix.bootstrapper>
</configuration>

link : 
https://stackoverflow.com/questions/7840380/custom-wix-burn-bootstrapper-user-interface

best regards, Torchok
