### ISSUE TITLE
Managed Bootstrapper samples failed to create MBA at runtime (after upgrade to WixSharp v1.20.3)

### ISSUE THREAD

**Issue by MariaIslamova** [oleg-shilo/wixsharp#1277]
Samples from https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper (e.g. WixBootstrapper_UI) fail at runtime with error:
```
[4EF4:9430][2023-04-11T17:39:24]e000: Error 0x8013101b: Failed to create the managed bootstrapper application.
[4EF4:9430][2023-04-11T17:39:24]e000: Error 0x8013101b: Failed to create UX.
[4EF4:9430][2023-04-11T17:39:24]e000: Error 0x8013101b: Failed to load UX.
[4EF4:9430][2023-04-11T17:39:24]e000: Error 0x8013101b: Failed while running 
```
Note that I was able to build, launch and install WixBootstrapper_UI sample with WixSharp v1.13.2 + .Net Framework v3.5. With all later WixSharp versions (e.g. WixSharp v1.20.3 + .Net Framework v4.5.1) the error at launch time occurs.

My scenario:
[OLD version]
1. Clone repo and open https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/WixBootstrapper_UI/WixBootstrapper_UI.csproj in Visual Studio 2022.
2. Save auto-created solution
3. Install WixSharp v1.13.2 package, in WixBootstrapper_UI.csproj properties make sure it targets  .Net Framework v3.5
4. Build project
5. Launch created exe file with bootstrapper (my_app.exe) -> OK!

[After upgrade]
...
3. Upgrade to WixSharp v1.20.3 package, in WixBootstrapper_UI.csproj properties target  .Net Framework v4.5.1
   * At this point compiler requires to reference library "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Xaml.dll" which was done successfully
4. Build project (no complains on compatibility!)
5. Launch exe file with created bootstrapper (my_app.exe) -> FAIL! with the error above

If anyone have already built MBA with the latest WixSharp revision I would appreciate any advice on how to make it work. Thanks!

**Comment by Torchok19081986** [comment]
morning, did you try it in another .NET Framework like 4.5.2 and better? i had same issue, but after i set Target Framework to 4.8.1 and recompilied it , my_app_exe runs agains well.

**Comment by MariaIslamova** [comment]
@Torchok19081986 ? thanks for the reply. Yes, I tried 4.6, 4.7, 4.8 and 4.8.1 in particular. The result is the same - failure on loading MBA. What is your exact version of WixSharp? v1.20.3 ?

**Comment by Torchok19081986** [comment]
morning, yes, my version of WixSharp is 1.20.3. Strange things happens. looks like problem of BA in .NET Framework.  Your BA runs in 3.5 , but not in NET Framework 4.5 and better.

**Comment by oleg-shilo** [comment]
Just a small announcement (kinda).
I am progressing very well on Wix4 support so if this behaviour is addressed in Wix4, you will be able to use it very soon.

**Comment by MariaIslamova** [comment]
@oleg-shilo, it sounds great! Looking forward to migrating to Wish# + Wix4!

**Comment by oleg-shilo** [comment]
You can track the progress here: #1281

**Comment by MariaIslamova** [comment]
UPD: For some reasons BootstrapperCore.config generated at build time contained extra tags with earlier .Net Framework versions (maybe b/c they were installed on my machine?..). So I had to include manually edited config.

BootstrapperCore.config for .Net Framework 4.8:
`
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<configSections>
		<sectionGroup name="wix.bootstrapper" type="Microsoft.Tools.WindowsInstallerXml.Bootstrapper.BootstrapperSectionGroup, BootstrapperCore">
			<section name="host" type="Microsoft.Tools.WindowsInstallerXml.Bootstrapper.HostSection, BootstrapperCore" />
		</sectionGroup>
	</configSections>
	<startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
	</startup>
	<wix.bootstrapper>
		<host assemblyName="MyAssemblyName" />
	</wix.bootstrapper>
</configuration>
`

Setup.sc:
`
ManagedBootstrapperApplication.DefaultBootstrapperCoreConfigContent =
                System.IO.File.ReadAllText("BootstrapperCore.config");
 var bootstrapper = new Bundle(...);
`
