### ISSUE TITLE
upgrading multiple products

### ISSUE THREAD

**Issue by TheToughGuy** [oleg-shilo/wixsharp#1278]
Hi,

I have an older product that I want to remove when upgrading my new product, but it has a different upgrade ID from my main product, I see in old school Wix I could add multiple upgrade entries to the upgrade table thus:
```

<!-- Major upgrade - Your New Product Line, using the MajorUpgrade convenience element -->
<MajorUpgrade DowngradeErrorMessage="A later version of [ProductName] is already installed" />

<!-- Older Product Line 1: Upgrade Code -->
<Upgrade Id="{11111111-1111-1111-1111-000000000000}">
   <UpgradeVersion Property="PRODUCTLINE1" IncludeMinimum="yes" Minimum="0.0.0" />
</Upgrade>

<!-- Older Product Line 2: Upgrade Code -->
<Upgrade Id="{22222222-2222-2222-2222-000000000000}">
   <UpgradeVersion Property="PRODUCTLINE2"  IncludeMinimum="yes" Minimum="0.0.0" />
</Upgrade>

<!-- Older Product Line 3: Upgrade Code -->
<Upgrade Id="{33333333-3333-3333-3333-000000000000}">
   <UpgradeVersion Property="PRODUCTLINE3"  IncludeMinimum="yes" Minimum="0.0.0" />
</Upgrade>
```

how do I achieve the same functionality in wixsharp?

I have tried using a custom action that runs the msiExec command, but that runs into the issue of there being another installer (this one!) already running...

**Comment by Torchok19081986** [comment]
morning, msiexec instance is one and only. All another msiexec instances can only be execute if previous instance ends. this is limitaion of msiexec process. I seen custom Burn Application installer where each product came togther in bundle, where you can choose product to install or update. 
for this propose you have to create custom BA installer. this is not trivial task, but it can be done. try to search for WixToolset BA installer for multple products. i prety sure you can find it, 
And all properties and descrption can be done in wixsharp like same. 
Maybe Oleg can give you right path to achieve it that way . 
as Source for Beginning : you can see it in following link
https://assist-software.net/blog/how-build-custom-installation-package-bundle-using-wpf-prism-mef-and-wix
and 
https://www.wrightfully.com/part-1-of-writing-your-own-net-based-installer-with-wix-overview/

Best regads, Torchok

**Comment by TheToughGuy** [comment]
Thanks for that. I think I'll move the uninstall of the aditional product into the application then. 

Regards, ToughGuy
