### ISSUE TITLE
Environment.GetFolderPath with onedrive installed

### ISSUE THREAD

**Issue by fredericoregateiro** [oleg-shilo/wixsharp#1279]
I got a strange bug on windows with onedrive installed.

Running this code
``` csharp
Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)
```
The path returned is something like this: `C:\Users\frede\OneDrive\Documentos` which is the correct one.

If I run this code in the `AfterInstall` event i got this path: `C:\Users\frede\Documents` that was the correct path if the onedrive was not installed.

How can i get the correct path, if onedrive is installed?

**Comment by oleg-shilo** [comment]
It is not exactly a WixSharp question. :)
One point that can help you is the fact that AfterInstall runs elevated.

I am guessing OneDrive mapping is not processed if it is dome from the elevated context.

You can check it easily if you test `Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)` from the elevated hello works test app.

Then you can start searching for the solution...

**Comment by fredericoregateiro** [comment]
Thanks @oleg-shilo 

when i first saw this problem, i never thought this was related to wixsharp, but it's the only place i can see this behavior

I've created a small repo with this problem [here](https://github.com/fredericoregateiro/wixsharp-GetFolderPath).

Maybe you can see what's wrong in my code? i cannot see what to do.

Running from a console app using `<requestedExecutionLevel level="requireAdministrator" uiAccess="true" />`:
![image](https://user-images.githubusercontent.com/6304701/233400624-c9610b96-2ba5-4a60-8d00-14e9d2b9ee86.png)

Running from the `AfterInstall` event:
![image](https://user-images.githubusercontent.com/6304701/233399976-7673deac-eda8-4ed3-a092-e14f30918cfa.png)

**Comment by oleg-shilo** [comment]
I will close it as it is really outside of WixSharp scope.
`AfterInstall` is a deferred elevated action. The only difference (that I am aware) in the execution context is that elevation. But quite possibly MSI runs it somehow differently.

As for your challenge, I suggest you store the path from the `BeforeInstall` in the session property. You will also need to ensure the property is channelled to the deferred actions: ` project.DefaultDeferredProperties += ",MYPROP";`.
