### ISSUE TITLE
[ManagedUI] INSTALLDIR with SourceName attribute

### ISSUE THREAD

**Issue by JeremyAnsel** [oleg-shilo/wixsharp#128]
Hello,

I have added a `SourceName` attribute to the install directory.

With the native msi UI, the `INSTALLDIR` is `C:\Program Files (x86)\My Company\My Product\`.
```csharp
var project = new Project("MyProduct",
    new Dir(@"%ProgramFiles%",
        new Dir(@"My Company",
            new Dir("My Product",
                new File(@"Files\File1.txt")))));

project.Dirs[0].Attributes["SourceName"] = ".";
project.Dirs[0].Dirs[0].Attributes["SourceName"] = ".";
project.Dirs[0].Dirs[0].Dirs[0].Attributes["SourceName"] = ".";

project.Package.Attributes["Compressed"] = "no";
project.Media.ForEach(t => { t.EmbedCab = null; t.Cabinet = null; });

project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.UI = WUI.WixUI_InstallDir;

project.OutDir = "MyMedia";
project.BuildMsi();
```
![wixsharp_installdir_native](https://user-images.githubusercontent.com/9573196/29273495-c2b35f98-8104-11e7-8919-7ca664ff2cae.png)

But with the managed UI, the `INSTALLDIR` is `ProgramFilesFolder:.\My Company:.\My Product:.` instead of `C:\Program Files (x86)\My Company\My Product\`.
```csharp
var project = new ManagedProject("MyProduct",
    new Dir(@"%ProgramFiles%",
        new Dir(@"My Company",
            new Dir("My Product",
                new File(@"Files\File1.txt")))));

project.Dirs[0].Attributes["SourceName"] = ".";
project.Dirs[0].Dirs[0].Attributes["SourceName"] = ".";
project.Dirs[0].Dirs[0].Dirs[0].Attributes["SourceName"] = ".";

project.Package.Attributes["Compressed"] = "no";
project.Media.ForEach(t => { t.EmbedCab = null; t.Cabinet = null; });

project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.ManagedUI = ManagedUI.Default;

project.OutDir = "MyMedia";
project.BuildMsi();
```
![wixsharp_installdir_managed](https://user-images.githubusercontent.com/9573196/29273563-05d033be-8105-11e7-87f0-cfff381f2e8e.png)

**Comment by oleg-shilo** [comment]
Thank you. Done. Will be available in the next release.

I am curious, why would one need to set 'SourceName' attribute? Is it some legacy code you are dealing with?

**Comment by JeremyAnsel** [comment]
Thanks

I'm updating an old msi which uses `SourceName`.

Without setting `SourceName`, `MyMedia` folder contains:
```
│   MyProduct.msi
│
└───ProgramFilesFolder
    └───My Company
        └───My Product
                File1.txt
```

With setting `SourceName`, `MyMedia` folder contains:
```
    File1.txt
    MyProduct.msi
```

**Comment by oleg-shilo** [comment]
Yeah I though it might be the legacy solution you are dealing with. 
If you are eager to try the fix you can just grab the latest binary `WixSharp.dll` for GitHub: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples
