### ISSUE TITLE
uninstall from customer path

### ISSUE THREAD

**Issue by AnastasiaKSG** [oleg-shilo/wixsharp#1283]
Hello,
this topic does not help me:
https://github.com/oleg-shilo/wixsharp/issues/486

So here is my similar problem:
If I choose a custom path, the program is uninstalled from the apps list, but the files remain in the installation folder because the standard installation path is still the standard path. I would like uninstall the program and files from any path. In this code I used examples from WixSharp.Samples# with message boxes. Every uninstalling attempt I made shows the standard installation path in the corresponding MessageBox.

`using System;
using System.Windows.Forms;
using WixSharp;
using WixSharp.Controls;

namespace SetupAntriebsparameterWixSharp
{
    class Program
    {
        static void Main()
        {
            string setupVersion = "1.0.0";
            var version = new Version(setupVersion);
            var productCode = Guid.NewGuid().ToString("B");
            var upgradeCode = new Guid("XXX-XX-XXX-XX-XXX");
            var setupName = "setup";
            var defaultInstallFolderPath = @"%AppData%\MyProduct\";
            var setupContentPath = @".\InstallerContent\*.*";

            var project =
                 new ManagedProject(setupName + " " + setupVersion,
                     new Dir(defaultInstallFolderPath, 
                         new Files(setupContentPath)));

            project.MajorUpgrade = new MajorUpgrade
            {
                AllowDowngrades = false,
                DowngradeErrorMessage = "Eine neuere Version von [ProductName] ist bereits installiert.",
                AllowSameVersionUpgrades = true,
            };

            project.UpgradeCode = upgradeCode;
            project.GUID = new Guid(productCode);
            project.InstallScope = InstallScope.perUser;
            project.Language = "de-De";
            project.Version = version;
            project.ControlPanelInfo.HelpTelephone = "555";
            project.ControlPanelInfo.ProductIcon = @".\CustomImages\Shortcut.ico";
            project.ControlPanelInfo.Manufacturer = "Firma";
            project.ControlPanelInfo.InstallLocation = "[INSTALLDIR]";
            project.BackgroundImage = @".\CustomImages\background.bmp";
            project.BannerImage = @".\CustomImages\banner.bmp";

            project.UI = WUI.WixUI_InstallDir;

            project.BeforeInstall += args =>
            {
                if (args.IsUninstalling)
                { 
		   args.Session["INSTALLDIR"] = @"C:\Users\anast\AppData\Roaming\oooo";
                    MessageBox.Show(args.InstallDir, "Uninstalling from" + args.InstallDir);
                }             
                else
                    MessageBox.Show(args.InstallDir, "Installing in "+ args.InstallDir);
            };
            project.BuildMsi("setup.msi");
        }
    }
}`

I tried using InstallDir instead of Dir as mentioned in the topic with similar problem. But it didn't help.
This line is my wrong test attempt to override INSTALLDIR. But my goal is that the program should be uninstalled from any user-defined path without admin rights.
` args.Session["INSTALLDIR"] = @"C:\Users\anast\AppData\Roaming\oooo";`

I need your help.

**Comment by AnastasiaKSG** [comment]
I have solved the problem... By changing to the Load event.
`            project.Load += args =>
            {
                if (args.IsUninstalling)
                { 
                    args.Session["INSTALLDIR"] = @"C:\Users\anast\AppData\Roaming\oooo";
                    MessageBox.Show(args.InstallDir, "Uninstalling from" + args.InstallDir);
                }
                    
                else
                    MessageBox.Show(args.InstallDir, "Installing in "+ args.InstallDir);
            };`

**Comment by AnastasiaKSG** [comment]
It works only if I remove my App from Windows App List -> Deinstall. 
If starting the MSI Installer -> Remove, the folder with files is still there... 
These are two different deinstall routines.
How I can delete Install folder if deinstalling from customer path with MSI-Installer?

**Comment by oleg-shilo** [comment]
Uninstalling is fully controlled by MSI so it's hard to say how it is managing "deinstall routines".

Though I just have tested [InstallDir_DynamicPath](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/InstallDir_DynamicPath) sample and it uninstalls from right-click msi file. 

I suggest you build and test this sample to verify that it works and then see what is causing the difference in your case.
