### ISSUE TITLE
Problem with FirewallException WIX4

### ISSUE THREAD

**Issue by Anhell06** [oleg-shilo/wixsharp#1287]
FirewallException does not work in Wix4, or I configure it incorrectly
Could you tell me if this is a bug or a usage error?

In code:
```
var firewallException = new FirewallException($"{_projectSettings.Name}")
            {
                RemoteAddress = _projectSettings.FirewallExceptionAddresses,
                Port = _projectSettings.FirewallExceptionPort,
//Without Condition still doesn't work
                ComponentCondition = new Condition(" (ADD_FIREWALL_EXCEPTION=\"True\") AND (NOT (REMOVE=\"ALL\")) ")
            }

var project = new ManagedProject(_projectSettings.Name,
                firewallException, ...
```

In XML:
```
<FirewallException Id="MyApp_" Name="MyApp" Port="8080" xmlns="http://wixtoolset.org/schemas/v4/wxs/firewall">
          <RemoteAddress Value="127.0.0.1" />
          <RemoteAddress Value="127.0.0.2" />
          <RemoteAddress Value="127.0.0.3" />
        </FirewallException>
```

The problem appears for some reason only when ManagedUI is used. I tried using the same with Wix UI and the exception installs fine

_Maybe it's worth describing such problems in a topic on WIX 4.0?_

**Comment by oleg-shilo** [comment]
Interesting.
Can you please chank if the XML is generated the same way with and without ManagedUI. Dependency on ManagedUI seems very strange.

**Comment by oleg-shilo** [comment]
If XML is generated differently then it is a WixSharp defect. If consistent then it might be something that WiX4 is doing something strange. 

It would be a little easier if your sample never works at all. That ManagedUI dependency is completely puzzling

**Comment by Anhell06** [comment]
The problem was solved by itself, the problems were in the system settings on which the test was launched
