### ISSUE TITLE
DigitalSignatureBootstrapper сompletely broken in WIX4

### ISSUE THREAD

**Issue by Anhell06** [oleg-shilo/wixsharp#1289]
```
public static int DigitalySignBootstrapper(string bootstrapperFileToSign, string pfxFile, string timeURL, string password, string optionalArguments = null, string wellKnownLocations = null, bool useCertificateStore = false, SignOutputLevel outputLevel = SignOutputLevel.Verbose, HashAlgorithmType hashAlgorithm = HashAlgorithmType.sha1)
        {
            int num = DigitalySignBootstrapperEngine(bootstrapperFileToSign, pfxFile, timeURL, password, optionalArguments, wellKnownLocations, useCertificateStore, outputLevel, hashAlgorithm);
...
```
DigitalySignBootstrapperEngine always run with _string signToolPath = "<unknown insignia.exe/signtool.exe Path>"_

_externalTool.ExePath = signToolPath;_ in WixSharp.CommonTasks.Tasks.DigitalySignBootstrapper Crashes with path error

**Comment by Anhell06** [comment]
DigitalSignature также не работает свойство HashAlgorithm

**Comment by oleg-shilo** [comment]
Correct :(
`insignia.exe` signing tool is no longer available in WiX SDK so I made it to break.

This is when I need the community support. I need to understand how WiX4 expects to do msi signing. The documentation is silent about that.
