### ISSUE TITLE
How to use WelcomeDialog from "WixSharp Managed Setup - Custom WPF UI" template with a different image?

### ISSUE THREAD

**Issue by TD-peter** [oleg-shilo/wixsharp#1292]
Hi,

The WelcomeDialogModel contains the following line:

public BitmapImage Banner => session?.GetResourceBitmap("WixUI_Bmp_Dialog").ToImageSource();

I see with Orca that the "WixUI_Bmp_Dialog" is included in the MSI in the Binary table as binary data.

I would like to use a different image. How can I add my own image to the Binary table in the creates MSI?
If it is in the Binary table, I assume I can reference it like the code above, but with a different name.

Or is there another way to achieve this?

Thanks,
Peter

**Comment by TD-peter** [comment]
I managed to solve it using 
project.AddBinary(new Binary(new Id("dialog_image"), @"Images\dialog_image.png"));

I would also like to change the MSI icon that is also shown in the top left of the Window.
Is that possible?

**Comment by oleg-shilo** [comment]
Perfect. Thank you for sharing the solution to the problem.
