### ISSUE TITLE
Problems locating add/remove icon in dynamically created installer

### ISSUE THREAD

**Issue by Oudalally** [oleg-shilo/wixsharp#1295]
i'm building a tool which will compile and package several applications, and using wixsharp for the installer part of it.
The tool is configured using JSON config files, and after compiling a VS project and putting the resultant binaries into a directory, it creates the installer using that directory as the source location.

My problem comes in setting the icon for add/remove programs.
The project which is building the installers is made in visual studio, and has a directory in it called Resources, which contains the icon file, and the banner image file, as well as the EULA rtf file.

I can set the banner image fine with `project.BannerImage = Path.Combine(execLocation, "resources\\Banner.png");`, but when I try to set the icon file using the same method, it just doesn't find it.

The line I'm using is as follows - `project.ControlPanelInfo.ProductIcon = "\\resources\\icon.ico";`

Looking at the generated wix project, the path to the banner is an absolute path, but the path to the icon is a relative path, and it contains a lot of back statements (ie, ..\..\..\..\..\..\InstallBuilder\Resources), which is really confusing.

The path it's trying to load the icon from is in fact in my home Dir.

` <Icon Id="app_icon.ico" SourceFile="..\..\..\..\..\..\IDistributionBuilder\BuildDistros\bin\Debug\resources\icon.ico" />`

The install builder tool is executing from bin\debug in the VS project, and the resources folder is in that same location, so I can't fathom why it's generating this long relative path.

Is there any documentation which will help point me in the right direction?
I've been through the examples, but so far I'm just confused.

Should the icon file be in the project which is building the installer, or should it be copied to the location where the binaries I'm packaging live?
Should the icon be set as a resource, or content and copied to the same folder as the exe that is building the installer?

I'm beyond confused now, so any help would be really appreciated.

**Comment by Oudalally** [comment]
Well, I've found why the long relative path was being created.
I'd set the source base dir in a previous change, and forgot to change it back.

The icon path is now being set correctly in the wxs file, however the icon still isn't being loaded.
Even specifying a full path to the icon in the c#, it's not adding it.

**Comment by oleg-shilo** [comment]
I suggest you check the generated WXS file (I assume you are using VS WixSharp project, which generates wxs).
If the icon element is correct then it is MSI/WiX issue. However, if wxs is incorrect then it is WixSharp defect and I will need to look at it.

**Comment by Oudalally** [comment]
The icon item seems to be fine. It was finding it during the build, and adding it to the MSI correctly.
If I change the paths during the msi build, it fails to find it.

The wxs seems to be ok, it just isn't using the icon when it's installed. The installer seems to work fine otherwise though which is a little confusing.

**Comment by oleg-shilo** [comment]
I cannot explain your problem :(
I have built and installed the ProductInfo sample and it shows the icon correctly:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/a4964268-d5cf-4c5d-9151-f65118cbb9ac)
Is it possible that the icon file is not valid?

**Comment by Oudalally** [comment]
It's very possible...
I have used this icon in another installer though, but in that case, I was adding folders manuallay to that one installer.

My current project assembles the installer dynamically, so there is no code which adds a specific directory to the installer in the project. 
I'll play around with it more today and see if I can find out more.

**Comment by Oudalally** [comment]
I've managed to reproduce the issue in a text project.

Using the following test code, the icon is not set in the uninstall entry - 
```
            string execLocation = System.AppDomain.CurrentDomain.BaseDirectory;
            var project = new Project("Test Project",
            new Dir(@"%ProgramFiles%\Test Company\Test App",
                new File(execLocation + @"\Files\TextFile1.txt")
            ));

            project.EnableResilientPackage();
            project.EnableUninstallFullUI();
            project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
            project.ControlPanelInfo.ProductIcon = "ist_icon.ico";
            project.BuildMsi();
```

However, if I comment out `project.EnableUninstallFullUI();`, the icon is set correctly.

Is this explainable behaviour relating to how Wix handles this argument, or indicative of a bug?

**Comment by Oudalally** [comment]
Further to that last test, I've knocked together a test which follows the approach I'm using in my dynamic build tool.
I'm creating the Dir object, setting permissions and adding it to the project seperately (I need to use this approach as the Dirs will vary for each project the tool builds).

The following code sample is the approach I'm using

```
            string execLocation = System.AppDomain.CurrentDomain.BaseDirectory;
            var project = new Project("Test Project");
            Dir rootInstallDir = new Dir(new Id("INSTALLDIR"), @"%ProgramFiles64Folder%\Test Company\Test App",
               new DirPermission("Users", GenericPermission.All), new Files(execLocation + "\\Files\\*.*")
           );

            project.AddDir(rootInstallDir);
            project.EnableResilientPackage();
            //project.EnableUninstallFullUI();
            project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
            project.ControlPanelInfo.ProductIcon = "ist_icon.ico";
            project.BuildMsi();
```

If I uncomment `project.EnableUninstallFullUI();`, again the icon is not set.
However, examining the MSI shows that the icon is added, and it doesn't complain about not being able to locate it during the build.

**Comment by Oudalally** [comment]
As a final test, I have commented the `project.EnableUninstallFullUI();` in my build tool, and it's once again setting the icons.

**Comment by oleg-shilo** [comment]
Great, you found **the** reason :)

Apparently setting up a custom uninstall UI interferes with the default product icon in the ARP dialog.
The solution is to avoid using custom uninstall UI (as you did) by not calling `EnableUninstallFullUI`
Or specifying the product icon explicitly:

```C#
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File("readme.txt"),
            new File("app_icon.ico")));
. . .
project.EnableUninstallFullUI(@"[INSTALLDIR]\app_icon.ico");
```

I have updated the API documentation to reflect this:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/816dcf53-a2b1-4e5a-b32b-354f1e081db6)
