### ISSUE TITLE
Question: arm64

### ISSUE THREAD

**Issue by christophwille** [oleg-shilo/wixsharp#1296]
I saw #1005 

I am working on https://github.com/icsharpcode/ILSpy/commits/christophwille/splitsetup and have added a switch like that 

```
#if ARM64
			project.Platform = Platform.arm64;
#else
			project.Platform = Platform.x64;
#endif
```

(Details see https://github.com/icsharpcode/ILSpy/commit/33973d72526d073697ae49a4ca6a5d31e54ea474). However, if I build with ARM64 set (x64 builds fine like before)

`msbuild ILSpy.Installer.sln /p:Configuration="Release" /p:Platform="Any CPU" /p:DefineConstants="ARM64"`

I get

```
D:\GitWorkspace\ILSpy\ILSpy.Installer\ILSpy.wxs(4): error CNDL0265: The Platform attribute has an invalid value arm64.
 Possible values are x86, x64, or ia64. [D:\GitWorkspace\ILSpy\ILSpy.Installer\ILSpy.Installer.csproj]
  Cannot build D:\GitWorkspace\ILSpy\ILSpy.Installer\ILSpy.wxs
C:\Users\christophw\.nuget\packages\wixsharp\1.20.3\build\WixSharp.targets(5,5): error MSB3073: The command ""D:\GitWor
kspace\ILSpy\ILSpy.Installer\bin\Release\net472\ILSpy.Installer.exe" "/MSBUILD:ILSpy.Installer" "/WIXBIN:" "/Configurat
ion:Release" "/Platform:AnyCPU"" exited with code -1. [D:\GitWorkspace\ILSpy\ILSpy.Installer\ILSpy.Installer.csproj]

```
Obviously it is me doing something wrong / misunderstanding a concept. Could you please kindly point me in the right direction? Thanks.

**Comment by oleg-shilo** [comment]
Hi Chrisoph,
You are not doing anything wrong.

I have  checked and indeed the latest version of WiX 3 does throw this error and complains that only three other values are supported:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/19c68a0d-53d6-45b0-b5be-e3177ee406f6)

And yet [WiX documentation for the same version](https://wixtoolset.org/docs/v3/xsd/wix/package/) states that `Platform` attribute in fact supports 7 values and one of them is `arm64`.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/2edbf575-91b5-4196-8fd0-96543242b8a3)

Unfortunately, it is a clear bug in the WiC compiler.

**Comment by christophwille** [comment]
Current https://wixtoolset.org/docs/releasenotes/ states "Arm64 is supported in the core toolset, extensions, and Burn." (WiX v4.0.0) then means it was never really supported in Wix3 (found SO post https://stackoverflow.com/questions/60368718/arm64-support-in-wix-toolset-for-building-for-surface-pro-x that sort of pointed in that direction).

**Comment by oleg-shilo** [comment]
Oh my...
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/176057e7-5239-49a1-a68e-c9b4acf4637d)

tbh, I cannot say that I am completely surprised.

**Comment by christophwille** [comment]
Side-question that is now sort-of related: how is your Wix4 effor coming along?

**Comment by oleg-shilo** [comment]
A simple answer - "it's done"
A complete answer - "it's not ready to fly" :(

The porting is completed but because WiX4 is rough on the edges, flaky and largely undocumented, some of the fundamental deployment scenarios are still not available in WiX4. 

There are some [critical gaps](https://github.com/oleg-shilo/wixsharp/issues/1282) that need to be closed before I can release. I am hoping for the community to help me with solving these.

The most important one is WiX4 failure to give any working sample for the Cutsom BA bootstrapper.

I have described WiX4 porting effort [here](https://github.com/oleg-shilo/wixsharp/wiki/WixSharp-and-WiX4).

**Comment by oleg-shilo** [comment]
>...  you did bring the problems to their attention in their repos?

Actually no. I feel like WiX4 is still very raw and I am trying to appropriately prioritize my effort in communicating with WiX team. 
It is because in the past communication happened to be a challenge.

Thus at this phase, I am trying to rely on the community to help me first with finding the information WiX indicated exists but then look at (and communicate to WiX) the outstanding defects if any. 

I need to be careful how much I invest in WiX4 it is already my fourth try. All previous were unsuccessful due to te WiX4 still evolving.

I hope you understand my challenge here.

**Comment by christophwille** [comment]
btw, it seems that 3.14 does exist https://wixtoolset.org/docs/v3/releases/v3-14-0-6526/ (interestingly enough I didn't find it on GH releases)

**Comment by oleg-shilo** [comment]
OK, you can download this SDK and use to build your msi with WixSharp:

```c#
project.Platform = Platform.arm64;
Compiler.WixLocation = @"C:\temp\wix314-binaries"; // folder with the content of "wix314-binaries.zip"
```

It does indeed allow arm64 platform. Though it generates relevant warnings that you will need to decide about.

**Comment by christophwille** [comment]
But I could keep https://github.com/icsharpcode/ILSpy/blob/d1e9f8bd77d70a9f132adc1d8fae5f23b58053e6/ILSpy.Installer/ILSpy.Installer.csproj#L11 (or should I entirely remove that?)

**Comment by oleg-shilo** [comment]
>  (or should I entirely remove that?)

You can keep everything as is. But it looks like you have already guessed it.

>Would you consider packaging that version?

WiX tools often produce warnings that are very generic and do not really apply to a specific scenario. Thus I suggest you do build the msi with the warning and test it on the target arm system. there is a fair chance that it will just work. 

As I interpret it, it simply says that you need to ensure you run this msi on the OS with the MSI service version 5.0 and higher.

**Comment by christophwille** [comment]
I meant "Would you consider packaging 3.14 as your .wix.bin NuGet package"

**Comment by christophwille** [comment]
There don't seem to be many differences (in terms of files) between 3.11.2 and 3.14 - what doesn't match up for me at all are Source\src\WixSharp.Samples\Wix_bin\SDK\wixui and Source\src\WixSharp.Samples\Wix_bin\SDK\themes - where do those come from in your repo?

**Comment by oleg-shilo** [comment]
There is a difference in the binaries themselves (in the WiX toolset folders).

The folders you are asking about are copies of the WiX toolset ditributables downloaded from WiX site.

Done. Published https://www.nuget.org/packages/WixSharp.wix.bin/3.14.0
WixSharp itself is not changed so I did not release any new version. Though I had to update a few code samples to make them with WiX v3.14

**Comment by oleg-shilo** [comment]
You can test it now and if works as expected I will close the issue.

**Comment by christophwille** [comment]
Yes, that workaround does the trick (output:  Windows Installer XML Toolset Compiler version 3.14.0.6526) and ILSpy installs arm64:
![image](https://github.com/oleg-shilo/wixsharp/assets/344208/1818bdb1-d385-40b1-8412-c9207eaf8433)
Thanks!

**Comment by oleg-shilo** [comment]
Great. Glad it all worked out.

BTW wanted to thank you and the whole ILSpy team for the great product. 
From the screenshot below you can tell that I am a heavy user of your product 😄 

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/3e86a34f-6358-4cb1-a4b6-a3dd941c963a)
