### ISSUE TITLE
wixsharp:WpfDialog auto scaling based on screen resolution

### ISSUE THREAD

**Issue by Anidil** [oleg-shilo/wixsharp#1297]
My wixsharp:WpfDialog do not scale properly based on the source RDP resolution.

800x600 work on most machines with 150% screen augmentation. However few machines expects 1180x880 for the installer screen to display fully and with 800x600 resolution, those machines display only top-left quarter of the screen and rest of the screen is fully trimmed off 

Here is my AutoScaleMode.Dpi. It's the same behavior when I do not set the the 'SetSize' values

```c#
        private static void Project_UILoaded(SetupEventArgs e)
        {
            var managedUI = e.ManagedUI as Form;

            managedUI.AutoScaleMode = AutoScaleMode.Dpi;
            managedUI.PerformAutoScale();
            managedUI.FormBorderStyle = FormBorderStyle.FixedToolWindow;
            managedUI.StartPosition = FormStartPosition.CenterScreen;

            //managedUI.Size = new Size(1180, 880);
            //e.ManagedUI.SetSize(1180, 880);

            managedUI.Size = new Size(800, 600);
            e.ManagedUI.SetSize(800, 600);

            managedUI.Refresh();
        }
```

**Comment by oleg-shilo** [comment]
Thank you.
Do you consider your solution generic enough to handle all screens/resolutions? So it can be merged with the codebase

**Comment by Anidil** [comment]
Hello Oleg, The solution is generic enough to handle all screens and resolutions. This issue happens when we use WPF with wixsharp. With Forms based screens, I have not faced any resolution issues.

**Comment by oleg-shilo** [comment]
Thank you 
I will integrate your solution and release in a week or so

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release. 

You can set the scaling mode like this:

```C#
project.ManagedUI.AutoScaleMode = AutoScaleMode.Dpi;
```

I left the default as `AutoScaleMode.Font` as it is too risky to change the defaults so dramatically. Particularly because of the standard WinForm.AutoscalingMode also defaults to `Font`.  But changing it is now easy.

Note that even when you use WPF dialogs the top-level window/shell (`e.ManagedUI`) is still a WinForm object.
