### ISSUE TITLE
Bug: DigitalSignatureBootstrapper ignores CertificateStore = StoreType.sha1Hash

### ISSUE THREAD

**Issue by tzehetner** [oleg-shilo/wixsharp#1298]
The DigitalSignatureBootstrapper ignores, in my opinion, the most important way to specify a certificate (via its thumbprint, now that certificates aren't issued as pfx files anymore). If you set `CertificateStore` to `StoreType.sha1Hash` it uses `StoreType.commonName` instead. The reason for this is, that internally in its Apply method it uses the boolean UseCertificateStore property instead of the CertificateStore property.

See https://github.com/oleg-shilo/wixsharp/issues/827 for a workaround.

**Comment by oleg-shilo** [comment]
Sorry Thomas, you will need to walk me through it.

DigitalSignatureBootstrapper was implemented by some of the contributors and my involvement was minimal.
I do not know it well enough to understand the details of the issue.

It is my understanding is that [this](https://github.com/oleg-shilo/wixsharp/issues/827#issuecomment-615157642) is the workaround. But I am not sure how it is applicable to the short description you have provided. 
If it is the case then what is the expectation of the fix ingrating this work around?
 
Can you provide the pseudo-code or the description of the desired end-to-end behaviour?

**Comment by tzehetner** [comment]
Hi Oleg, sorry for the late reply.

I have created a pull request, that should fix this issue. I had to change two method signatures, which is a breaking change. Feel free to add overloads instead, if necessary.

**Comment by oleg-shilo** [comment]
Great, thank you. Will process the PR asap

**Comment by oleg-shilo** [comment]
Thomas, may I ask you to repeat your PR but to the `wix-v4-master` branch please?
