### ISSUE TITLE
InstalledFileAction

### ISSUE THREAD

**Issue by rdt23** [oleg-shilo/wixsharp#13]
how is it possible to acsess to file from the .MSI file folder and not from the install dir

**Comment by oleg-shilo** [comment]
If you are asking about the `InstalledFileAction` (which is just a CustomAction) then you just need to specify the id of the file from that different folder:
```C#
new InstalledFileAction("file_id", "your_arg", 
                         Return.check, 
                         When.Before, 
                         Step.InstallFinalize, 
                         Condition.Installed),
```  
And if you need to assign some files explicit Id then you need to pass it into the file constructor:
```C#
new File(new Id("file_id"),  @"Files\your_app.exe"))
```
