### ISSUE TITLE
ManagedUI does not visually indicate upgrade failure

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/wixsharp#130]
Triggered by #122 

_Note, this is a cosmetic problem about Managed UI not reflecting upgrading outcome. But the upgrading itself works correctly._  

The problem is rather conceptual. MSI/WiX upgrade support (e.g. via MajorUpgrade element) works correctly regardless of the UI technology. However it hooks into UI sequence to show upgrade failure message only with native UI but not with the EmbeddedUI (ManagedUI).

The unfortunate MSI/WiX design aspect is that the upgrading outcome (e.g. failure) is not preserved in any way (e.g. session property). Thus ManagedUI cannot detect it and update itself to reflect the upgrading result. Meaning that most likely ManagedUI will need to do some extra work to predict if the upgrade is possible and immediately navigate to the exit if it's not.

**Comment by oleg-shilo** [comment]
The first implementation (c684512) allows simplified way of scheduling checking for MajorUpgrade compatibility from ManagedUI:

```C#
project.ManagedUI = ManagedUI.Default;
project.ScheduleDowngradeUICheck(
           "Later version of the product is already installed : ${installedVersion}",
            (thisVersion, installedVersion) => thisVersion <= installedVersion);
```

**Comment by gcostanzo** [comment]
Hello,

I've been looking for the feature mentioned here (Aug. 19, 2017 commit) but I noticed it was removed in a subsequent commit (Sept. 10, 2017 commit):
![image](https://user-images.githubusercontent.com/7451073/205398618-03f2938a-dfe5-4b43-b356-e25e30688351.png)

Any reason why? Is there another function available to do this or do we have to go through a `UIInitialized` delegate?

Thank you.

**Comment by oleg-shilo** [comment]
It was removed because it did not fit very well the typical UI install scenario. IE it hdes the complexity of UI localization without providing any controlling mechanizm to the user.

Thus it is much simpler to allow user to do directly what he/she wants to do instead of trying to implement a more complicated API that will fail to satisfy everyone.

Saying that you can achieve the same functionality by simply following the approach described in the `MajorUpgrade` sample:

```C#
 project.UIInitialized += (SetupEventArgs e) =>
        {
            Version installedVersion = e.Session.LookupInstalledVersion();
            Version thisVersion = e.Session.QueryProductVersion();

            if (thisVersion <= installedVersion)
            {
                MessageBox.Show("Later version of the product is already installed : " + installedVersion);

                e.ManagedUI.Shell.ErrorDetected = true;
                e.Result = ActionResult.UserExit;
            }
        };
```
.
