### ISSUE TITLE
Make more elements translateable

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#1301]
The following lines of code use hard-coded translations. This might be an option for improvement to replace them by a label like `[MYLABEL]`:

## CustomDialog, EmptyDialog, MsiSetupForm, etc.

Skipped, is sample.

**ProgressDialog**
```
this.waitPrompt.Text = "Please wait for UAC prompt to appear.\r\n\r\nIf it appears minimized then activate it" +
    " from the taskbar.";
```

**InstallDirDialog**
```
this.copyToolStripMenuItem.Text = "Copy";
```

**InstallScopeDialog**
```
this.copyToolStripMenuItem.Text = "Copy";
```

**LicenseDialog**
```
this.copyToolStripMenuItem.Text = "Copy";
```

**Other**
AutoElements.cs: `UACWarning`

**Comment by oleg-shilo** [comment]
An interesting and very valid problem. I need to think about the way to fix it.
It's hard to design the API for that as in this case there are two incompatible localization models utilized within the same application: WiX and .NET App localization.

Let me think about it.

As for now, you can use this to control `this.waitPrompt.Text`:
```C#
static void Project_UIInitialized(SetupEventArgs e)
{
    if(Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName == "en" )
        e.Session["UAC_WARNING"] = "custom warning";

    if (Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName == "uk" )
        e.Session["UAC_WARNING"] = "спеціальне попередження";
```

**Comment by oleg-shilo** [comment]
Done.
Will be available in the very next release.

I have added the explanation of how to do the custom localization here: https://github.com/oleg-shilo/wixsharp/blob/wix-v3-master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUI.Dialog/setup.cs

I have also updated the "CustomUI.Dialog" code sample to reflect on the technique.

**Comment by monty241** [comment]
Thanks for incorporating these improvement! The wxl is quite complex and expensive when doing many languages.

**Comment by oleg-shilo** [comment]
Totally agree with you. 
The alternative model is quite simple and straightforward. It can be that simple and expressive:

```C#
static void msi_UIInitialized(SetupEventArgs e)
{   
    MsiRuntime runtime = e.ManagedUI.Shell.MsiRuntime();

    if (CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "de")
    {
        var translations = "UserNameDlgTitle=Benutzeranmeldeinformationen;" +
                           "UserNameDlgDescription=Einstellungen für Anwendungsanmeldeinformationen;" +
                           "UserNameDlgNameLabel=Nutzername";

        foreach (var item in translations.ToDictionary())
            runtime.UIText[item.Key] = item.Value;
    }
}
```

**Comment by monty241** [comment]
Thanks for your understanding! Yes, given the tip above this is close to what we have added and are testing now. For most purposes and user communities it is probably an acceptable workaround.
