### ISSUE TITLE
Uninstall registry created under HKLM instead of HKCU

### ISSUE THREAD

**Issue by KiranNiranjan** [oleg-shilo/wixsharp#1302]
I am encountering an issue with Wix# where the uninstall registry for my product is being created under HKLM (HKEY_LOCAL_MACHINE) instead of HKCU (HKEY_CURRENT_USER). However, despite trying various options, the uninstall registry is still being created under HKLM.

I am using WixSharp version `1.20.4` with the **ManagedProject** template and a custom UI to create an MSI for my project.

Options I have tried:

1. Setting InstallScope to perUser.
2. Configuring session properties, including `ALLUSERS = 2 and MSIINSTALLPERUSER = 1`, in different combinations.
3. Using the following options: 
`AutoElements.DisableAutoKeyPath = true; AutoElements.DisableAutoUserProfileRegistry = false;`
4. A workaround described in this issue ->  https://github.com/oleg-shilo/wixsharp/issues/609

Despite these attempts, the uninstall registry continues to be written under HKLM. I would greatly appreciate any guidance or assistance to resolve this issue and ensure that the uninstall registry is created under HKCU as required.

Please let me know if any additional information or code snippets are needed to further investigate this problem. Thank you in advance for your help.

**Comment by oleg-shilo** [comment]
Kiran, this is something that is deeply managed by MSI. 
I think you have a better chance of understanding the triggers for this behaviour by analyzing the generated wxs.
If you can find what is that property/element that needs to be changed I am happy to help you to convert it in the appropriate WixSharp definition.

**Comment by KiranNiranjan** [comment]
Thank you for your quick response and suggestion. I understand that MSI manages this behavior, and I have analyzed the generated `wxs` file. However, my requirement is to completely move all the properties associated with the product, including the uninstall registry, from `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\{ProductCode}` to `HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\{ProductCode}`.

I know that this is a departure from the standard MSI behavior, but it is a specific requirement for our project. We need to ensure that all the product-related uninstall information is stored under `HKCU` for **per-user** installations.

I would appreciate it if you could suggest a way that can be achieved in WixSharp to accomplish the complete migration of properties to `HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\{ProductCode}`.

**Comment by oleg-shilo** [comment]
I am afraid WixSharp is not going to help with this.  
These registry entries are created by MSI runtime during the installation and consumed by MSI runtime (for uninstalling). Thus WixSharp can indeed conveniently modify any registry (delete or move) but this most likely will dramatically impact MSI runtime and potentially make your product impossible to uninstall.  Thus I would rather invest in understanding the required WXS content for achieving HKCU only data. 

The only thing that I suggest you try is changing `AutoElements.DisableAutoUserProfileRegistry` value. Just to ensure that it does not push the runtime behaviour in one or another direction. The chance is very small but testing is very simple.

**Comment by KiranNiranjan** [comment]
Thank you for your prompt response. I already tried changing `AutoElements.DisableAutoUserProfileRegistry` but I don't think it made any difference in the build.

I will keep this thread updated on any progress or further questions that may arise. For now, we can close this issue.🙂

**Comment by oleg-shilo** [comment]
OK. Yes, please. If you find the solution to this interesting problem. Please post it here. So the others can benefit. from it.
