### ISSUE TITLE
Improve usability of `Project.WildCardDedup`

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/wixsharp#1304]
This issue is the result of the comprehensive discussion of Issue #270.

`Project.WildCardDedup` should be implemented according to this definition:

> When `ResolveWildCards` is invoked, it inserts the files discovered from project's `DirFiles` and `Files` definitions. For every `Dir`, which gets new discovered files, the global dedup delegate `Project.WildCardDedup` will be invoked.

**Comment by Lumoryel** [comment]
Hi Oleg, thanks for clearing this up and implementing it!

I tested Version 1.22 and for me it now does what I need and what I would expect.

So just to make sure I understood your definition correctly:

> "In ResolveWildCards(), for every (Target-) Dir that has one or multiple (Source-) DirFiles or Files, the WildcardDedup is called exactly once (to ensure there aren't multiple files with the same name in the same target directory)".

Is this correct?
