### ISSUE TITLE
Error "Could not set file security ..." when starting per-user uninstaller for ordinary user

### ISSUE THREAD

**Issue by Anton-V-K** [oleg-shilo/wixsharp#1307]
I've prepared an installer which installs a product for current user.
The testing code:
```
using System;
using WixSharp;

namespace TestPoductMSISetup
{
    internal class Program
    {
        static void Main()
        {
            var project = new Project("TestProductMSI",
                              new Dir(@"%LocalAppDataFolder%\TestProductMSI",
                                  new File("Program.cs")));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
            project.InstallScope = InstallScope.perUser;
 
            project.BuildMsi();
        }
    }
}
```
However when uninstalling I get the error like this one:
```
Could not set file security for file 'C:\Users\???\AppData\Roaming\Microsoft\Installer\'.
Error: 5. Verify that you have sufficient privileges to modify the security permisions for this file.
```
![image](https://github.com/oleg-shilo/wixsharp/assets/20116984/fb9cb126-3258-42b3-ba28-a12d6b9fc2cf)
The mentioned user doesn't have administrator privileges.
However it has access to the mentioned directory `C:\Users\???\AppData\Roaming\Microsoft\Installer`, which is actually empty.
The NTFS-permissions for the folder are correct, so this is not something like [this python's issue](https://bugs.python.org/issue41961).

OS: Windows 10 64-bit 21H1

Probably something is missed in the script?

When I install and then uninstall as administrator, everything works fine (UAC prompt doesn't pop up in both cases).
The issue also doesn't happen on two other clean Windows 10 systems (inside VMware). They have newer version 21H2 and 22H2, so it may be related to the version of system MSI-component.

See also #1302

**Comment by Anton-V-K** [comment]
After all investigation I tend to conclude the issue is caused by the bug in MSI-component (`msi.dll`? `msiexec.exe`?), which can't handle redirected user profiles.
So if you have moved your user's profile to another drive, and created a symlink (junction) under `C:\Users` to point to the new location, msi-based installers/uninstaller (which work without elevation) will complain about "wrong" permissions for `C:\Users\???\AppData\Roaming\Microsoft\Installer`.

Luckily there is a **workaround**: just remove `C:\Users\???\AppData\Roaming\Microsoft\Installer` (it is usually empty), and installer/uninstaller will re-create. This works one time only, and the next installer/uninstaller will compain with the same error - keep on removing the directory in the hope the bug will get fixed in Windows 13 :)

**Comment by oleg-shilo** [comment]
A very interesting problem. Looks like an MSI design flaw. A significant one :(

Thank you for sharing.

**Comment by Anton-V-K** [comment]
This issue happens for Python installer as well, and there is a good explanation what's going on behind the scenes - https://github.com/python/cpython/issues/86127#issuecomment-1357916414

**Comment by oleg-shilo** [comment]
I think you nailed it.
