### ISSUE TITLE
File system long paths in custom actions

### ISSUE THREAD

**Issue by 11v1** [oleg-shilo/wixsharp#1308]
Hi, I have observed that file operations started from .NET custom actions do not support long paths. If I call `Directory.Delete(@"C:\Test", true)` and C:\Test contains a file whose path exceeds 260 characters, then the operation throws an exception. If I do `Directory.Delete(@"\\?\C:\Test", true)` then I hit "System.ArgumentException: Illegal characters in path.". If I execute the same code from the standalone application, then it works. Any ideas on how to enable the standard .net file system related functions to support long-paths?

**Comment by oleg-shilo** [comment]
Not sure. It is a generic .NET topic (not MSI/WiX) so maybe you can find the answer somewhere. 

Though I have one possible cause to check. 
When you are testing "the standalone application" it is executed under the exact CLR version you built it against.

When a custom action is executed then it is MSI/WiX who is initiating CLR. Thus it is possible that the file system operations are implemented a little differently. You can easily check the version by checking the CLR version from the custom action.

**Comment by oleg-shilo** [comment]
It looks like the 260 limit doesn't apply since .NET Framework 4.6.2. Most likely the MSI runtime is earlier than that.

**Comment by 11v1** [comment]
The RuntimeInformation.FrameworkDescription in custom action returns .NET Framework 4.8.4515.0

**Comment by oleg-shilo** [comment]
Sorry, mate. I have no idea then.
