### ISSUE TITLE
Wix V4 Error build if project include MajorUpgradeStrategy

### ISSUE THREAD

**Issue by Ales999** [oleg-shilo/wixsharp#1309]
Simple code:
```
        private static readonly Guid UpgradeCode = new Guid("7FC5E919-6239-4D66-ADD7-A3F3AA437A3A");

        static void Main(string[] args)
        {
            Version versionApp = new Version(1,0,2,0);
            Guid productId = new Guid("15612BF1-22F4-4931-A129-ED71975B2E3D"); // change guid if upgate version

            var project = new Project(
                "MyWpfTestApp",
                new Dir(@"%ProgramFiles%\MyORg\MyWpfTestApp",
                new File(@"WpfAppTestWiX.exe"))

                )
            {
                SourceBaseDir = sRootDir,
                Version = versionApp,
                GUID = new Guid("0975C956-56E1-424C-BBC0-4B66C8A3A863"),
                ProductId = productId,
                Encoding = Encoding.UTF8,
                OutDir = "..",
                //Description = @"Test",
                OutFileName = @"TestApp_Setup",
                UpgradeCode = UpgradeCode,
                MajorUpgrade = new MajorUpgrade
                {
                    Schedule = UpgradeSchedule.afterInstallValidate,
                    DowngradeErrorMessage =
                            "A later version of [ProductName] is already installed. Setup will now exit."
                },
                MajorUpgradeStrategy = new MajorUpgradeStrategy // <-- Error If add this block
                {
                    RemoveExistingProductAfter = Step.InstallInitialize,
                    UpgradeVersions = VersionRange.OlderThanThis,
                    PreventDowngradingVersions = VersionRange.NewerThanThis,
                    NewerProductInstalledErrorMessage = "."
                },
            };

           Compiler.BuildMsi(project);
    } // end main
   ...
```
Error:
TestApp_Setup.wxs(38) : error WIX0400: The Custom element contains illegal inner text: 'NEWPRODUCTFOUND'.
TestApp_Setup.wxs(44) : error WIX0400: The Custom element contains illegal inner text: 'NEWPRODUCTFOUND'.

[TestApp_Setup.wxs.txt](https://github.com/oleg-shilo/wixsharp/files/11995101/TestApp_Setup.wxs.txt)

**Comment by oleg-shilo** [comment]
Fixed. Will be available in the very next release. I hope to do it within a week.

**Comment by Ales999** [comment]
After upgrade to last release (2.0.1) and enable again thih block:

```
                    MajorUpgradeStrategy = new MajorUpgradeStrategy
                    {
                        RemoveExistingProductAfter = Step.InstallInitialize,
                        UpgradeVersions = VersionRange.OlderThanThis,
                        PreventDowngradingVersions = VersionRange.NewerThanThis,
                        NewerProductInstalledErrorMessage = "."
                    },
```
New error:
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка		Duplicate symbol 'WixAction:InstallExecuteSequence/RemoveExistingProducts' referenced by C:\Users\Alexey\source\repos\SMClock\Install_SMClock.wxs(177). This typically means that an Id is duplicated. Ensure all your identifiers of a given type (File, Component, Feature) are unique or use an access modifier to scope the identfier.	SMClockSetup	C:\Users\Alexey\source\repos\SMClock\Install_SMClock.wxs	174	
[Install_SMClock.wxs.txt](https://github.com/oleg-shilo/wixsharp/files/12450735/Install_SMClock.wxs.txt)

A'm check this file and not found this dublicated string.

**Comment by oleg-shilo** [comment]
WixSharp v2 uses WiX4 to compile wxs. Thus the error is coming form the compiler detecting duplication in the user-defined wxs and some of the WiX libs.

Quite possibly it is the result of the design changes in WiX4. But I do not know for sure.

Note, you are using `MajorUpgradeStrategy` which is using an old `Upgrade` element API that WiX team has deprecated. Thus it is recommended to use the latest `MajorUpgrade` element instead. See Major upgrade example.

```C#
project.MajorUpgrade = new MajorUpgrade
{
    Schedule = UpgradeSchedule.afterInstallInitialize,
    DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
};
```

You can still make your code to compile by removing the MajorUpdate element:
```c#
project.WixSourceGenerated += e => e.FindFirst("MajorUpgrade").Remove();
```
 But there is no warranty that it will work at runtime.

**Comment by Ales999** [comment]
Thanks, closed.
