### ISSUE TITLE
Adding directories to a project

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#131]
I have an existing WIX installer which adds around 40 directories in an install. When creating a new Wix# replacement i am running into trouble with adding so many directories to a project.

The installer works well until i add greater than around 24 directories. It then starts giving the following error message for the generated wix:

_The InstallUISequence table contains an action 'Set_DirAbsolutePath' which cannot have a unique sequence number because it is scheduled before or after action 'AppSearch'.  There is not enough room before or after this action to assign a unique sequence number.  Please schedule one of the actions differently so that it will be in a position with more sequence numbers available.  Please note that sequence numbers must be an integer in the range 1 - 32767 (inclusive)._		

The markup that it is complaining about is:

```
...
    <InstallExecuteSequence>
      <Custom Action="WixSharp_InitRuntime_Action" Before="AppSearch"> (1) </Custom>
      <Custom Action="Set_CancelRequestHandler_Props" After="InstallInitialize" />
      <Custom Action="CancelRequestHandler" Before="InstallFinalize"> (NOT (REMOVE="ALL")) </Custom>
      <Custom Action="PreventDowngrading" After="FindRelatedProducts">NEWPRODUCTFOUND</Custom>

      <RemoveExistingProducts After="InstallFinalize" />

      <Custom Action="Set_DirAbsolutePath" Before="AppSearch">(NOT Installed) AND (UILevel &lt; 5) AND (AccessControl_Bin = ABSOLUTEPATH)</Custom>
      <Custom Action="Set_DirAbsolutePath1" Before="AppSearch">(NOT Installed) AND (UILevel &lt; 5) AND (AccessControl_Config = ABSOLUTEPATH1)</Custom>
  
```
 
The errors are occurring in the custom actions of the InstallExecuteSequence and InstallUISequence tags.

Is there currently a limit on how many directories can be added to a project in Wix#?

**Comment by oleg-shilo** [comment]
I will have a look, but it seems like a MSI/WiX limitation associated with (or triggered by) amount of custom actions being scheduled. In your case it is `Set_DirAbsolutePath`, which is typically should be used only once. Thus you add a single (root) directory via absolute path and the rest is a collection of the normal relative Dir withing the root dir. 

The big problem is that MSI/WiX do not support absolute path at all. Yest it's hard to believe but it is the case. Thus for every single abs_dir a custom action needs to be set up to assign that Dir an absolute path value (property). Wix# simply does it under the hood so the developer does not have to. 

The error message implies that there is a limit on the amount of these custom actions. May be there is come work around. Hard to tell. But the simplest way to approach it is to try to avoid having too many abs dirs.

**Comment by oleg-shilo** [comment]
Just an extra info....

As I suspected, there is no problem with having too many dirs but only to have so many of them being absolute path dirs. The code below compiles 40 dirs without any problem:
```C#
class Script
{
    static void prepare_dirs(string root)
    {
        for (int i = 0; i < 40; i++)
        {
            var dir = root.PathJoin(i.ToString());
            System.IO.Directory.CreateDirectory(dir);
            System.IO.File.WriteAllText(dir.PathJoin($"file_{i}.txt"), i.ToString());
        }
    }

    static public void Main(string[] args)
    {
        prepare_dirs("dirs"); 

        var project = new ManagedProject("MyProduct",
                         new Dir(@"C:\MyCompany\MyProduct",
                             new Files(@"dirs\*.*")));

        project.UI = WUI.WixUI_ProgressOnly;

        Compiler.BuildMsi(project);
    }
    ...
```
