### ISSUE TITLE
Problem during dynamic localization

### ISSUE THREAD

**Issue by sotiredofyours** [oleg-shilo/wixsharp#1310]
Hello, I ran into two bugs(?) during the localization of my application.

1. `TextProgress` messages are defined by `project.Language` but not from wxl.
2. `[ProjectName]` is not recognized in the final dialog.

My code:
```
  public static ManagedProject Localize(this ManagedProject project)
        {
            project.AddBinary(new Binary(new Id("ru_xsl"), "WixUI_ru-RU.wxl"));
            project.AddBinary(new Binary(new Id("es_xsl"), "WixUI_es-es.wxl"));
            project.AddBinary(new Binary(new Id("kz_xsl"), "WixUI_kk-KZ.wxl"));
            
            project.UIInitialized += e =>
            {
                var runtime = e.ManagedUI.Shell.MsiRuntime();

                switch (Localization.DetectLanguage())
                {
                    case SupportedLanguages.Russian:
                        runtime.UIText.InitFromWxl(e.Session.ReadBinary("ru_xsl"));
                        break;
                    ...
                }
            };

            return project;
        }
```
I tried on several `wxl` files, but the problem remained.

Screenshots: 

![image](https://github.com/oleg-shilo/wixsharp/assets/81583669/587f8cf7-657c-44b9-9137-1820ababe800)

![image](https://github.com/oleg-shilo/wixsharp/assets/81583669/4fc75549-29cf-4e3e-9699-0074106b9eed)

Localization file attached.

[WixUI_ru-ru.zip](https://github.com/oleg-shilo/wixsharp/files/11995813/WixUI_ru-ru.zip)

**Comment by oleg-shilo** [comment]
When you call `runtime.UIText.InitFromWxl(...` you replace ALL content of localization with the wxl content. But your file does not have `ProductName` string. In Welcome dialog it is OK as the localization falls back to the session properties and get the `ProductName` from there. But in the exit dialog the session is already cleared and that property does not exist.

Thus you need to add all extra localization that you need after you InitFromWxl.

```C#
runtime.UIText.InitFromWxl(e.Session.ReadBinary("ru_xsl"));
runtime.UIText["ProductName"] = e.Session.Property("ProductName");
```

**Comment by oleg-shilo** [comment]
I have updated the API and the samples to allow merging localizations:
```C#
runtime.UIText.InitFromWxl(e.Session.ReadBinary("uk_xsl"), merge: true);
```
