### ISSUE TITLE
Same .msi to install product for current user and for all users

### ISSUE THREAD

**Issue by Anton-V-K** [oleg-shilo/wixsharp#1311]
I've prepared an installer which installs the product for current user without elevation.
And now I'm evaluating whether it is feasible to somehow implement (in the same installer) the mode in which the product can be installed for all users. This can be done if the installer is started with administrator rights (elevated).
In short:

1. If installer runs without elevation, the product is installed under `%LOCALAPPDATA%` for current user.
2. If the installer runs elevated, the product is installed into `Program Files` for all users.
3. It should be possible to have multiple "instances" of installed product (one per each user + one for all users).

Is it possible with MSI?
Taking into account that registry entry in all cases is created under `HKLM` (there is a dedicated issue #1302 for that), I thought I would have to separate the entries for each user, but apparently MSI can handle it on its own: same registry key is "shared" for every user, and it is kept while at least one product "instance" is installed on PC.

The project I start with looks this way:
```c#
using System;
using System.Diagnostics;
using WixSharp;

namespace TestPoductMSISetup
{
    internal class Program
    {
        static void Main()
        {
            var project = new Project("TestProductMSI",
                              new Dir(@"%LocalAppDataFolder%\TestProductMSI",
                                  new File("Program.cs")));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
            project.InstallPrivileges = InstallPrivileges.limited;
            project.InstallScope = InstallScope.perUser;
            project.OutDir = Process.GetCurrentProcess().MainModule.FileName.PathGetDirName();

            project.BuildMsi();
        }
    }
}
```
It supports side-by-side product installations for every user, though this behavior is confusing a bit: once a user uninstalls its copy, the entry in Apps and Features stays (if any other user has the product installed), and second attempt to uninstall the product ends with the error: `This action is only valid for products that are currently installed`.

Having another GUID for system-wide installer (for all users) is OK.
What is the correct way to check whether the installer runs elevated in `Program.Main()?` Do I need a custom action for that?

AFAIK Roblox can install itself in a similar way, but its installer isn't based on MSI.

PS: It is a kind of question, which I would place under Discussions, but there is no such space in this repo :(

**Comment by oleg-shilo** [comment]
Not sure if MSI supports it natively.

A simple (brute force style) solution would be to bootstrap two MSIs. One for all/elevated and one for current-user/unelevated. And run one or another depending on elevation context.

Detecting elevation is relatively easy. 
```C#
WindowsIdentity.GetCurrent().IsAdmin()
// or
project.BeforeInstall += args =>
{
    if (args.IsElevated)
        . . . 
```

`Program.Main()` is wrong for that. It is only executed during msi build but not during the installation. It is an MSI build script, so you will need to use some other events. Either msi pre-install event or a custom BA of a botstrapper.

**Comment by Anton-V-K** [comment]
Ah, I see the Discussions now. This issue can be moved there then :)
Thanks a lot for the quick reply. It seems I need to reconsider my approach - probably two separate installers wouble be easier to implement in my case.

**Comment by Mywk** [comment]
I've been also trying to figure this out for the last few days, if someone ends up finding out a good approach that doesn't include bootstrapping multiple msi's that would be amazing!

**Comment by oleg-shilo** [comment]
You may fork another elevated `msiexec /i <msi_file> APPCONTEXT=true` process from the beforeInstall (or any other event) and gracefully exit the primary process.
And you can use `APPCONTEXT` property value to bypass all interaction with the user and jump directly to the installation phase. 
Or you can simply start msiexec in progress-only mode.

**Comment by LosWolfos** [comment]
This approach has significant drawbacks though. Burn/ The BA from wix 3 does not support Dual Purpose Packages. MSI itself does without problems and has for 15 years. 
We used this workaround/hack of having a per user and a per machine package with the same program to realise this in burn.
Then selecting through the BA which to use depending on Context, but this will result in your Burn bundle always being installed per user because there is a hard switch on compile time when creating the bundle which will mark it as a "User" Bundle. This will result in the bundle itself only being installed for the executing User. And thus only visible in Apps/Features for that User. Worst Case The Admin if it was run  from a User Account as an Admin.
Wix 4 allegedly solves this though...

**Comment by oleg-shilo** [comment]
The proposal in my prev post is not ultimately elegant but it seems has no drawbacks as it is relying on a single MSI.
Basically first (short-lived msi session) plays the role of a BA and the second one started from the first with the user input collected, does the actual installation.

**Comment by LosWolfos** [comment]
So your not using burn but a second msi as a prerequiste of sorts.
Okay I missunderstood this then.

**Comment by oleg-shilo** [comment]
Yes, but to be more precise it's only one msi but tow sessions. 

Run the first msi and let it collect the environment information and even ask user for the input if required (e.g. select installation type). At this point, only MSI UI will be exercised. Afater that cancel the installation but just before that start itself again (start the msi process) with the user selection captured and passed as properties set from CLI of msiexec process.

This second, session will detect the required properties set and bypass the UI and jump straight to the installation phase.

It was the only way of achieving MSI UI without resorting to the BA in WiX3. Reason: WiX3 has never fixed the bug of failing to display MSI managed UI. 

Fortunatelly WiX4 addressed it.

**Comment by oleg-shilo** [comment]
Fantastic, thank you for sharing

**Comment by oleg-shilo** [comment]
@Mywk, just a pointer to make your solution slightly easier to implement. Specifically your last two points.
If you want any property to be automatically tunnelled through `CustomActionData` and accessed from any stage of your setup, you can just declare this on the project level:

```C#
project.DefaultDeferredProperties += ",WHATEVER";
```
Then you can safely access it with the property method extension `Session.Property("WHATEVER")`. If it detects that it is a deferred custom action and the session object is destroyed then it will automatically get the value from the CustomActionsData.

**Comment by Mywk** [comment]
@oleg-shilo That's great to know, I will keep that in mind!

I tried to make sure that I only do assignment of the properties on the Dialogs before the MSI runs, then setting whatever information I need inside the dialogs themselves as static variables or simply using the utility classes (like AppSearch.IsProductInstalled for the Finished dialog). This way I'm not risking trying to access something that no longer exists due to any MS shenanigans.

**Comment by modz2014** [comment]
> I sucessfully made a single msi for installing for the current user, all users or just extracting the files. ![image](https://user-images.githubusercontent.com/5620014/254286116-ee43c384-45b6-4065-adf6-178db90a0585.png)
> 
> I'll leave some pointers here just in case someone ends up in this issue later looking for something similar:
> 
>     * The local user / current machine can be set by simply setting the property [**ALLUSERS**](https://learn.microsoft.com/en-us/windows/win32/msi/allusers). Important to note is that the default value for InstallScope should be perUser, otherwise you always require administrator.
> 
>     * When installing for all users you will need administrator permissions, this can be achieved in a **CustomAction** using **APPCONTEXT** or by passing your own variables. I simply do a **Process.Start** with **runas** and the parameters I need.
> 
>     * If you want to create shortcuts locally or for all users (using **Environment.SpecialFolder.CommonDesktopDirectory**), you need a **ExeFileShortcut** with **Condition**
> 
>     * You can extract using an "[Administrative Installation](https://learn.microsoft.com/en-us/windows/win32/msi/administrative-installation)", and unlike the name, you do not need admin permissions to do it.
> 
>     * You cannot run a msi while another is running, for extracting I had to delay the execution of my administrative installation command, there may be a better way to achieve this but I'm not aware of it.
> 
>     * You can set properties directly from the custom UI using **Runtime.Session["WHATEVER"]**
> 
>     * If properties aren't working as they should inside your **CustomActions**, make sure that you set **UsesProperties** in your **ManagedAction**
> 
> 
> Hope this helps someone.

do you have an example of this

**Comment by Mywk** [comment]
@modz2014 I posted all the pointers I could regarding this, together with the code samples in this reposotory it should be enough to be able to achieve what you need.
Since the code I created for the setup was written during company time unfortunately I can't share it.

**Comment by modz2014** [comment]
whats it under

**Comment by modz2014** [comment]
do you have a full example of this

**Comment by oleg-shilo** [comment]
You need to look at the examples folder in this repo.
If you search in the wiki for this repo you will find it. It's here: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples.

For @Mywk  code you can look at the AllInOne sample:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/e0dbd1e7-842f-4cf9-845d-6433e0a7a4fa)


For my version (essentially the same as the one @Mywk provided but using a different way of setting up) you can probably use any ManagedSetup sample as starting point:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/526c6321-9bef-4e1d-923b-b75998024d24)

You can take the sample, modify it for your needs and add the routine @Mywk or I provided.

I also suggest you install WixSharp Visual Studio extension so you can create your project from the WixSharp template

**Comment by modz2014** [comment]
but those samples dont show anything like @Mywk i was just wondering not in a rush shut something to learn i guess

**Comment by oleg-shilo** [comment]
Both samples show how to compose WixSharp project. 
@Mywk explained what needs to be done. 
He and I provided the missing code bits. 
You will need to bring it all together.

It's very unlikely that you will find somewhere the code sample addressing your specific problem.

**Comment by modz2014** [comment]
yer will do
