### ISSUE TITLE
Files aren't removed if app is uninstalled from a custom location

### ISSUE THREAD

**Issue by Anton-V-K** [oleg-shilo/wixsharp#1314]
I'm installing an app into a custom location for custom user. The installation goes fine, however after the ~installation~ uninstallation the app's files are not removed.
Here is code snippet (almost the same as in #1311, just extra line `project.UI = WUI.WixUI_InstallDir;` was added):
```
using System;
using System.Diagnostics;
using WixSharp;

namespace TestPoductMSISetup
{
    internal class Program
    {
        static void Main()
        {
            var project = new Project("TestProductMSI",
                              new Dir(@"%LocalAppDataFolder%\TestProductMSI",
                                  new File("Program.cs")));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
            project.InstallPrivileges = InstallPrivileges.limited;
            project.InstallScope = InstallScope.perUser;
            project.OutDir = Process.GetCurrentProcess().MainModule.FileName.PathGetDirName();
            project.UI = WUI.WixUI_InstallDir;

            project.BuildMsi();
        }
    }
}
```
If the app was installed into the default location, everything is cleaned up correctly during uninstallation.
However when the user chooses another dir to install the app, the uninstaller doesn't remove it.
Any special code is needed to handle uninstallation in this case?

**Comment by oleg-shilo** [comment]
No, not in WixSharp. 
Though I am sure there is a magic attribute in WiX that will achieve that. If you find it then you can set this attribute from WixSharp too.
