### ISSUE TITLE
Conditions when installing files

### ISSUE THREAD

**Issue by Anhell06** [oleg-shilo/wixsharp#1315]
Faced a new problem, maybe I'm not somewhere wrong

There is a file that I want to install only during the initial installation, it contains a config and cannot be overwritten when updating the program

But the condition does not work correctly or does not work at all. Maybe I don't understand it correctly. Tell me how to add a file only during the initial installation

```xml
<Component Id="Component.appsettings.json_4134647770" 
           Guid="009b2a12-e2c2-11ed-8fc4-f1980b2c6c59" 
           Condition="(NOT Installed)">
    <File Id="appsettings.json_4134647770" 
          Source="..\GameServerAgent.WebApi\bin\Debug\net6.0\appsettings.json" />
</Component>
```

**Comment by oleg-shilo** [comment]
I am not sure `Installed` is a valid MSI runtime property. So you may not be able to evaluate it at runtime.

While there are tricks to achieve that but all of them are violating deployment "good practices" principle for configuration data. It should not be deployed by the deployment application but by the application itself on the first run.

A simple scenario why you want to do that is the case of the corrupt or lost config file. Running a reinstall is not appropriate here. But deleting a corrupted file and letting the product up recreating it correctly is a good way of solving this.

If you opt for this approach you will also gain by appropriately handling per-user scenarios.

I know, it's not the answer you were looking for but it is something to consider.
