### ISSUE TITLE
The possibility of NOT assembling MSI file

### ISSUE THREAD

**Issue by thunderquack** [oleg-shilo/wixsharp#1316]
Hello. 
Sometimes I need just to create a project file without assembling MSI, but there is WixSharp.targets which prevents me to do so. 

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="MSIAuthoring" AfterTargets="AfterBuild" >
    <Message Importance="high" Text="Building MSI" />
    <Exec Command="&quot;$(TargetPath)&quot; &quot;/MSBUILD:$(ProjectName)&quot; &quot;/WIXBIN:$(WixBinPackage)&quot; &quot;/Configuration:$(Configuration)&quot; &quot;/Platform:$(Platform)&quot;" WorkingDirectory="$(ProjectDir)"/>
  </Target>
</Project>
```

So after project gets built, the command mentoided in `<Exec>` section is being executed, which I don't need. 
Because of the facts that components' .targets files are imported after project file .targets, overriding target with the name `MSIAuthouring` doesn't seem to me possible. 

I have a temporarily solution making something like 
`<Target Name="MSIAuthoring" AfterTargets="AfterBuild" Condition="'$(SkipMSIAuthoring)' != 'true'">` in WixSharp.targets file and then defining SkipMSIAuthoring=true in the project file, but obviously it is not ideal.

Does my problem has an alternative solution, or it's better just to create a PR with my proposals an contribute a bit?

**Comment by oleg-shilo** [comment]
There are a few ways to do that but this one is arguably the simplest one:
- Change `project.BuildMsi()` to `project.BuildWxs()`

**Comment by thunderquack** [comment]
That's about exe files, I am create dll project which has my own custom dialogs (inherited from `WixCLRDialog`), my own conditions and so on, and so forth. So the project produces dll and therefore command `Command="&quot;$(TargetPath)&quot` (where TargetPath is blahblahblah.dll) gets executed with an error 🤷

**Comment by thunderquack** [comment]
Created PR #1321 along with my proposals to the documentation change

**Comment by oleg-shilo** [comment]
OK, sorry, I missed the point that you actually did not want to build anything. including wxs.

Then it may be solved even easier. Instead of importing `WixSharp` package in your class library project import `WixSharp.Bin`.
This p[package contains only the assemblies nothing else.

```txt
WixSharp.Bin = WixSharp_assemblies
WixSharp = WixSharp.Bin + WixSharp.targets
```
