### ISSUE TITLE
Bootstrapper bundle has bugs on wxs files generation.

### ISSUE THREAD

**Issue by andrei-aliashkevich** [oleg-shilo/wixsharp#1317]
When i try to build bootstrapper with russian names i ran into a wxs file generation problem. Bootstrapper compiler uses StringWriterWithEncoding(Encoding.Default) writer when saves XDocument to string. This leads to errors when using russian characters on systems with a non-russian locale (changes xml declaration encoding). The MSI compiler does not have this problems, because it use StringWriterWithEncoding(project.Encoding) writer when saves XDocument to string, and project.Encoding by default uses UTF8.

**Comment by oleg-shilo** [comment]
Please use wix-v3-branch until it is merged back to master and released

**Comment by andrei-aliashkevich** [comment]
I reviewed the fix, and it seems to me that we need to make the same fix a little lower.
