### ISSUE TITLE
Scope perMachine wix4

### ISSUE THREAD

**Issue by Anhell06** [oleg-shilo/wixsharp#1320]
I build the msi project in wix4 and set the property Scope = InstallScope.perMachine but msi does not start with administrator rights. I tried to force ALLUSERS 1, but get error that the variable is a duplicate

**Comment by oleg-shilo** [comment]
The `Install Files` sample in the `wix-v4-master` uses the scope as you ask and it does trigger UAC prompt:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/80301ea1-93b0-4c18-bc6a-8cd3ee44dcff)

Just in case if you expect a prompt to be displayed when UI starts, it's not how MSI works. UAC is engaged at the first step of the actual installation not the UI sequence. See this article: https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#event-driven-custom-actions
