### ISSUE TITLE
How to run BeforeInstall as elevated? 

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1322]
Hi,
How can I make it as the AfterInstall? Thx
<img width="595" alt="image" src="https://github.com/oleg-shilo/wixsharp/assets/89771659/495dedf9-c5f0-498d-b8f7-38ef57851f44">

**Comment by oleg-shilo** [comment]
There is no event for that. But you can use `ElevatedManagedAction` for that:

```C#
var project =
    new ManagedProject("My Product",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File(@"Files\MyApp.exe")),
        new ElevatedManagedAction(CustomActions.OnInstall, Return.check, When.After, Step.InstallFiles, Condition.NOT_Installed)
        {
            UsesProperties = "APP_FILE=[INSTALLDIR]MyApp.exe"
        });
```
But you will need to find an appropriate for your scenario combination of `When.After` and `Step.InstallFiles`

**Comment by RachelXGanon** [comment]
Thx!
