### ISSUE TITLE
Upgrade Version not working

### ISSUE THREAD

**Issue by oury1** [oleg-shilo/wixsharp#1324]
Hi
when i install a version of the product not matter what version i want to update i receive an error 
![image](https://github.com/oleg-shilo/wixsharp/assets/34249540/48c9432e-0c23-4be5-9708-a15a739dc4ba)

`  project.Version = new Version(13, 0, 0,1);
            
           project.MajorUpgrade = new MajorUpgrade
              {
               Disallow = false,
               AllowSameVersionUpgrades = true,
                  Schedule = UpgradeSchedule.afterInstallFinalize,
                  
                  DowngradeErrorMessage =
                              "A later version of [ProductName] is already installed. Setup will now exit."
              };
 `

![image](https://github.com/oleg-shilo/wixsharp/assets/34249540/8ea47294-f23a-4278-9365-9cfb2b944bd4)

![image](https://github.com/oleg-shilo/wixsharp/assets/34249540/a79baefa-4353-4e67-a158-f634d0989499)

**Comment by oleg-shilo** [comment]
If I remember it right, the last element of the version (build number) is not considered in the MSI upgrade scenarios.
Try your test but build change any more meaningful part of the version. IE `13.0.0.0 -> 13.0.1.0`

**Comment by oury1** [comment]
Allready tried but same problem also change the 13 to 14 and have exactly
the same problem

Le mar. 25 juil. 2023, 11:54, Oleg Shilo ***@***.***> a
écrit :

**Comment by oleg-shilo** [comment]
Then I can only suggest you follow the [major upgrade](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/MajorUpgrade/readme.txt) sample and then see how it is different compared to your case.
I just retested the sample and it does the upgrade correctly.
