### ISSUE TITLE
The old version of the product is not detected

### ISSUE THREAD

**Issue by sotiredofyours** [oleg-shilo/wixsharp#1325]
Hi @oleg-shilo, I encountered strange behavior during the installation of products.

```
 project.MajorUpgrade = new MajorUpgrade()
            {
                Schedule = UpgradeSchedule.afterInstallInitialize,
                AllowDowngrades = false,
                AllowSameVersionUpgrades = false,
                DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
            };
```
I have Major Upgrade set up and I have encountered strange behavior:

1. On Windows 7 (x32), when installing the version below, the Downgrade Message appears, but the program is still installed and appears in the control panel appears. That is, I have 2 versions installed in the control panel at the same time, and the files in Program Files will be overwritten by the last installed version.

2. On Windows 10, the installer cannot find the previous version of the product at all (I checked through `e.Session.LookupInstalledVersion()`). Otherwise, the behavior is the same as on WIndows 7

The project has only a GUID value assigned.
Could you tell me what to look at to figure out what's going on.
 
UPD: 
I found out what's wrong. MSI does not look at the fourth digit of the version. This was the problem. Closing issue.

**Comment by oleg-shilo** [comment]
Yep, this is the known limitation of the MSI as technology.
Though some may argue that it is not a limitation but a constraint since MSI complies with the Semantic versioning concept.
