### ISSUE TITLE
Library erased after update

### ISSUE THREAD

**Issue by igorekRnd** [oleg-shilo/wixsharp#1326]
There are 2 directories with files:
```
files-1
├── readme.txt
├── swresample-4.dll
└── swresample-4.txt
```
```
files-2
├── readme.txt
├── swresample-4.dll
└── swresample-4.txt
```
Using the following command, 4 installers are created:
`.wixsharp\cscs.exe Test.cs`

Contents of the Test.cs file:
```
//css_ref wix-314\sdk\Microsoft.Deployment.WindowsInstaller.dll;

using System;
using WixSharp;

class Script
{
    static public Project project(string prefix, string num)
    {
        var instDir = prefix == "p" ? @"%ProgramFiles%\igor" : @"%LocalAppData%\igor";

        return new Project(prefix + "-" + num)
        {
            Dirs = new[] { new Dir(instDir, new Files("files-" + num + @"\*.*")) },
            GUID = new Guid("61D8419B-39FC-40C8-96D2-DD3EC0609D11"),
            UpgradeCode = new Guid("D70DC8AF-53E4-4C0F-A229-078B9ADFFA11"),
            Version = new Version("1.0." + num),
            MajorUpgradeStrategy = new MajorUpgradeStrategy
            {
                UpgradeVersions = VersionRange.ThisAndOlder,
                PreventDowngradingVersions = VersionRange.ThisAndNewer,
            },
        };
    }

    static public void Main(string[] args)
    {
        Compiler.BuildMsi(project("p", "1"));
        Compiler.BuildMsi(project("p", "2"));
        Compiler.BuildMsi(project("u", "1"));
        Compiler.BuildMsi(project("u", "2"));
    }
}
```
The problem is this: when you upgrade project p-1 to p-2 (ProgramFIles), the swresample-4.* files are deleted and only the updated readme.txt remains.
If you update the project u-1 to u-2 (LocalAppData), then all three files are updated correctly.
Tell me why is this happening?

**Comment by igorekRnd** [comment]
files can be downloaded from the cloud: https://yadi.sk/d/c6hTViBos0Kl_g

**Comment by igorekRnd** [comment]
If you install the distribution kit without updating, or if you reinstall it, or if you click restore after an incorrect installation, then all files are restored

**Comment by oleg-shilo** [comment]
> Tell me why is this happening?

I cannot. This is something that is completely controlled by WiX/MSI. WixSharp does not implement any own behaviour regarding upgrading.

I can only suggest that you try to find the answer on WiX forums. You may also want to analyse generated wxs files. Use `PreserveTempFiles = true` to collect them.

Also remember that MajorUpgrade really means **replacement**.  The old version is removed before the new is installed.

**Comment by igorekRnd** [comment]
> Also remember that MajorUpgrade really means **replacement**. The old version is removed before the new is installed.

I tried commenting out the lines
```
/*
            MajorUpgradeStrategy = new MajorUpgradeStrategy
            {
                UpgradeVersions = VersionRange.ThisAndOlder,
                PreventDowngradingVersions = VersionRange.ThisAndNewer,
            },
*/
```
after installing the p-1 distribution and updating to p-2, one file was updated readme.txt, and the remaining 2 files remained from p-1
[p-1.wxs.txt](https://github.com/oleg-shilo/wixsharp/files/12207205/p-1.wxs.txt)
[p-2.wxs.txt](https://github.com/oleg-shilo/wixsharp/files/12207206/p-2.wxs.txt)
[u-1.wxs.txt](https://github.com/oleg-shilo/wixsharp/files/12207207/u-1.wxs.txt)
[u-2.wxs.txt](https://github.com/oleg-shilo/wixsharp/files/12207208/u-2.wxs.txt)

**Comment by igorekRnd** [comment]
> I can only suggest that you try to find the answer on WiX forums. You may also want to analyse generated wxs files. Use `PreserveTempFiles = true` to collect them.

tell me, what command can I build a distribution kit from *.wxs ?

**Comment by oleg-shilo** [comment]
> distribution kit from *.wxs 

I assume you are referring to msi. If I am right then you can use `project.BuildMsiCmd()` to generate the  batch file for building your msi.

BTW, you doe not need to set `project.UpgradeCode` explicitly. I will be assigned from `project.GUID` anyway.

**Comment by igorekRnd** [comment]
Thanks Oleg for your help. Here's what it's come to. Generated *.wxs files and MSI generation scripts: Build_*.cmd. In project files u-1.wxs, u-2.wxs replaced one line
`      <Directory Id="LocalAppDataFolder" Name="LocalAppDataFolder">
`
on
`      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
`
That is, I changed the destination folder in the XML file generated for wixtools. After that, projects u-1, u-2 started working with the ProgramFIles folder instead of LocalAppData and the files stopped being erased. The difference is that u-* projects work with the registry.

**Comment by igorekRnd** [comment]
I didn’t think of anything smarter than how to build a project in * .wxs with the destination folder LocalAppData. Then in bash change its path to ProgramFiles, and then continue to build the project build script using wixtools. If there is an easier way, please help me find it.

**Comment by igorekRnd** [comment]
Oleg, a working option for the ProgramFiles directory would help solve my problem
`AutoElements.DisableAutoUserProfileRegistry = false;`
But it works only in case of AppLocal and only in case of = true;

Issue link: https://github.com/oleg-shilo/wixsharp/issues/98

**Comment by igorekRnd** [comment]
looked at the wix# code and found similar checks before injecting this insert
`&& xDir.InUserProfile()`
maybe there is some way to add this insert from your code?

**Comment by igorekRnd** [comment]
problem solved with XML insertion
```
//css_ref wix-314\sdk\Microsoft.Deployment.WindowsInstaller.dll;
//css_ref wix-314\sdk\System.Xml.dll;


using System;
using System.Xml.Linq;
using WixSharp;

class Script
{
    static public Project project(string prefix, string num)
    {
        var instDir = prefix == "p" ? @"%ProgramFiles%\igor" : @"%LocalAppData%\igor";
        var regValue = new RegValue(RegistryHive.CurrentUser, @"Software\WixSharp\Used", "", "0");

        Project p = new Project(prefix + "-" + num)
        {
            Dirs = new[] { new Dir(instDir,                 
                new File("files-" + num + @"\readme.txt"),
                new File("files-" + num + @"\swresample-4.dll"),
                new File("files-" + num + @"\swresample-4.txt"))
            },            
            GUID = new Guid("61D8419B-39FC-40C8-96D2-DD3EC0609D11"),
            Version = new Version("1.0." + num),
            MajorUpgradeStrategy = new MajorUpgradeStrategy
            {
                UpgradeVersions = VersionRange.ThisAndOlder,
                PreventDowngradingVersions = VersionRange.ThisAndNewer,
            },
            PreserveTempFiles = true,
            
        };

        p.WixSourceGenerated += Compiler_WixSourceGenerated;
        return p;
    }

    private static void Compiler_WixSourceGenerated(XDocument document)
    {
        foreach (XElement el in document.FindAll("Component"))
        {
            el.AddElement(new XElement("RegistryKey",
                           new XAttribute("Root", "HKCU"),
                           new XAttribute("Key", @"Software\WixSharp\Used"),
                           new XElement("RegistryValue",
                               new XAttribute("Value", "0"),
                               new XAttribute("Type", "string"),
                               new XAttribute("KeyPath", "yes"))));
        }
    }

    static public void Main(string[] args)
    {
        AutoElements.DisableAutoUserProfileRegistry = true;

        Compiler.BuildMsi(project("p", "1"));
        Compiler.BuildMsi(project("p", "2"));
        Compiler.BuildMsi(project("u", "1"));
        Compiler.BuildMsi(project("u", "2"));
        //Compiler.BuildMsiCmd(project("u", "2"));
    }
}
```
XML insertion, I spied on the wix# sources. I would like the Author Oleg to add the ability to add this insert using the AutoElements flag.

**Comment by oleg-shilo** [comment]
You have done a great job of investigating it.
Indeed `DisableAutoUserProfileRegistry` would be my suggestion but you have already found it.

The need to touch user-profile registry is a rediculous MSI constrain with little justification.

It looks like you have found yet another reason (that I was not aware of) for updating  user-profile.
Agree, it makes sense to allow doing this with a single property value of a project object or `AutoElements`.

Making it into enhancement

**Comment by oleg-shilo** [comment]
This is what I was afraid of. I wasn't sure if setting the user profile reg value for all components will not have any side effects.

Do you think having it implemented as `AutoElements.ForceUserProfileRegistry` is an overkill? Should we just let users select the component it should be allied to?

**Comment by oleg-shilo** [comment]
BTW, looking at your code, with the component selection can be simplified a little.

```c#

project.WixSourceGenerated += doc =>
{
    doc.FindAll("Component")
       .Where(x => x.HasAttribute("Id", val => val.Contains("Component.cmp.exe_")))
       .ForEach(AutoElements.InsertUserProfileRegValue);
};
```

**Comment by igorekRnd** [comment]
> Though `InsertUserProfileRegValue` will become public only after the release.

Yes, I tried to do this today, before your comment :)

**Comment by igorekRnd** [comment]
> This is what I was afraid of. I wasn't sure if setting the user profile reg value for all components will not have any side effects.
> 
> Do you think having it implemented as `AutoElements.ForceUserProfileRegistry` is an overkill? Should we just let users select the component it should be allied to?

I saw your commit and I think it's a good solution when the distribution doesn't use services. Maybe something else will come out. I don't know how best to do it. It seems to me that it is not necessary to include filtering in the library, it is better to use this example of yours:

```
project.WixSourceGenerated += doc =>
{
    doc.FindAll("Component")
       .Where(x => x.HasAttribute("Id", val => val.Contains("Component.cmp.exe_")))
       .ForEach(AutoElements.InsertUserProfileRegValue);
};
```

**Comment by oleg-shilo** [comment]
OK, then will leave it at least for now.
I have added this sample in the member XML doc.
Txs
