### ISSUE TITLE
Admin right 

### ISSUE THREAD

**Issue by modz2014** [oleg-shilo/wixsharp#1327]
hi I was wondering if there is an option for the user to select admin right or not before installing is this possible

**Comment by modz2014** [comment]
i dont see an example though

**Comment by oleg-shilo** [comment]
@Mywk only described his solution but he did not provide an example. You will need either to develop your solution from his description or ask him to share the code.

**Comment by oleg-shilo** [comment]
You can use the events that are nothing else but wrappers around custom actions. Something like this:

```C#
project.Load += Project_Load;
. . .
private static void Project_Load(SetupEventArgs e)
{
    // Check if this is an administrator installation started as a user and if we re-start as admin
    string isOpenAdmin = e.Session["OPEN_AS_ADMIN"];

    if (isOpenAdmin == "true" && !e.IsElevated)
    {
        string msiFilePath = e.Session["OriginalDatabase"];
        string additionalParameters = ...;

        "msiexec".StartElevated($"/i \"{msiFilePath}\" {additionalParameters}");

        e.Result = ActionResult.SkipRemainingActions;
    }
}
```
The rest is exactly as @Mywk described.

If you prefer you can still implement raw Custom Action. You will find the samples in this repo

**Comment by modz2014** [comment]
i did this project.Actions = new ManagedAction(CustomAction.BeforeInstallInitialize,
				Return.check,
				When.Before,
				Step.InstallInitialize,
				Condition.NOT_Installed); but it cant find my custom action not sure why

**Comment by modz2014** [comment]
does wix have on already built in do I have to create my own

**Comment by oleg-shilo** [comment]
No, MSI has no custom action for restarting msi elevated in the scenario when you ask the user to select the scope of the installation. What you are trying to di is a very user-specific scenario and it is not covered by the framework.

WiX approach would probably be to create a custom bootstrapper BA.  A way more complicated than just 7 lines of code we are sugesting.

**Comment by modz2014** [comment]
yer fair enough

**Comment by sanikolov** [comment]
@Mywk in the sample you provided above there is no process start delay.
What did you mean by 
`You cannot run a msi while another is running, for extracting I had to delay the execution of my administrative installation command, there may be a better way to achieve this but I'm not aware of it.`

**Comment by sanikolov** [comment]
@oleg-shilo I tried your sample above in a ManagedUI project.
The last 2 dialogs are `Progress` and `Exit`.
```
project.ManagedUI.InstallDialogs.Add(Dialogs.Licence)
                                            .Add(Dialogs.InstallDir)
                                            .Add<CustomDialog1>()
                                            .Add<CustomDialog2>() 
                                            .Add(Dialogs.Progress)
                                            .Add(Dialogs.Exit);
```

In CustomDialog1 I invoke the snippet that you've provided.
UAC prompt comes up, then a new installer instance is launched as expected.
Unfortunately the old installer instance remains at the `Finish` dialog, which is the same as `Exit`.
I have to press OK to make it go away and then I can continue installing with the 2nd instance.
I tied
```
e.Result = ActionResult.SkipRemainingActions;
```
as well as `ActionResult.UserExit`, Exit dialog stays just the same.
I tried also `Environment.Exit(0);` as well as a direct low level call to
```
        [DllImport("kernel32.dll", SetLastError = true)]
        static extern void ExitProcess(uint uExitCode);
```
Nothing can make the Exit (a.k.a Finish) dialog go away.
Any ideas?

**Comment by oleg-shilo** [comment]
I see.

> as well as ActionResult.UserExit, Exit dialog stays just the same.

Fair enough. It is how MSI session looks at the end - the Exit dialog is shown.

What you can do is to call `Shell.Cancel();` just after you started another msiexec. This will end the UI session without going through the remaining dialogs. 

There is a chance that the actual msiexec from the first session may remain in the memory.
If it is the case then you can simply try to kill all instances of msiexec:
```C#
Process.GetProcessesByName("msiexec")
    .ForEach(p=>
    {
        try
        {
            p.Kill();
        }
        catch { }
    })
```
It's brutal but it works. After that there should remain only one instance of msiexec - MSI runtime service. You will not be able to kill it. You are fine.

**Comment by oleg-shilo** [comment]
yep, that will work too

**Comment by modz2014** [comment]
but then wahts the point of the it having something seperate is not really ideal

**Comment by Mywk** [comment]
> @Mywk in the sample you provided above there is no process start delay. What did you mean by `You cannot run a msi while another is running, for extracting I had to delay the execution of my administrative installation command, there may be a better way to achieve this but I'm not aware of it.`

This is the way that works best for me, tested on different computers (both very slow and very fast) and on Windows 8, 8.1, 10 and 11:

```c#
var psi = new ProcessStartInfo("cmd.exe", $"/c timeout /t 4 && msiexec /a \"{msiPath}\" {extraParameters}")
{
    UseShellExecute = false,
    CreateNoWindow = true
};

// Start the msiexec process
var process = Process.Start(psi);

// Close self
...
```

**Comment by modz2014** [comment]
thats basically calling cmd to do it

**Comment by Mywk** [comment]
@modz2014 Correct. If you find a better way do let me know.

**Comment by oleg-shilo** [comment]
Just in case...

Don't forget that the event handler will be called **always**. Thus you need to have all your checks `IsInstalling`/`IsUnInstaling/IsModifying/IsAdmin` done in the event handler.

**Comment by oleg-shilo** [comment]
Have a look at the "ManagedEvents" sample it restarts itself from the `Project_UIInitialized` event if it is not run as admin.
Quite possibly it is exactly what you need

**Comment by modz2014** [comment]
hey i am revisting this agian but i cant seem to figure out how to create custom diaglogs ect

**Comment by oleg-shilo** [comment]
Just create the project from the appropriate Visual Studio template:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/502da7b5-e99a-4d5d-bd0f-c23f123d6871)

Or you can even use the template for the complete "Custom UI" with the all dialogs source code included in the project.
