### ISSUE TITLE
Strange focus on the taskbar

### ISSUE THREAD

**Issue by sotiredofyours** [oleg-shilo/wixsharp#1328]
When installing the product, I noticed a strange behavior - the first icon on the taskbar focuses and shows the contents if the program is open. 

![image](https://github.com/oleg-shilo/wixsharp/assets/81583669/a9053339-e842-4c74-8073-831d63a6f511)
![image](https://github.com/oleg-shilo/wixsharp/assets/81583669/275ec516-e8ce-4f10-835a-a7d1576180ab)

Feel free to ask if you need any additional information.

**Comment by oleg-shilo** [comment]
It is WixSharp attempt to provide a workaround for the UAC prompt problem associated with the MSI's embedded UI implementation. Unfortunately, it can have side effects like the one you are describing.

You can disable this behaviour with the code below:

```c#
AutoElements.EnableUACRevealer = false;
```

This is the background:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/98a4827a-3c60-48af-ac4e-3b531ba65aa9)


Just after your report, I decided to disable this work around by default as it's value is debatable. The change will be available in the very next release

**Comment by sotiredofyours** [comment]
@oleg-shilo Thank you again for such a quick response. That helped.
