### ISSUE TITLE
Add subfolders results in two identical id's

### ISSUE THREAD

**Issue by SeanFarrow** [oleg-shilo/wixsharp#133]
Hi,

I've got a case where I'm adding a tree of directories that has subfolders such as:
lib
osx
Linux

where osx and Linux are at the same level in the tree.
I get an error message that the id lib has been defined twice.

What is the best way around this? having looked at the source, I thought there was an internal constructor to Dir (that doesn't appear to be used) that dealt with this when given a path.
Help appreciated as always.
Cheers
Sean.

**Comment by oleg-shilo** [comment]
The easiest way is to specify the dir IDs explicitly in the constructor:
```C#
new Project("MyProduct",
    new Dir(new Id("root_dir"), @"%ProgramFiles%\My Company\My Product",
    // or
    new Dir("root_dir".ToId(), @"%ProgramFiles%\My Company\My Product",
```

**Comment by SeanFarrow** [comment]
How should I then deal with subdirs, should they be part of the containing directory? Or will they be picked up given the target path—an example would be good!
Cheers
Sean.

**Comment by oleg-shilo** [comment]
Example? :) 
~90 of Wix# codebase are samples. Download them from GitHub and you most likely will find what you are looking for.

**Comment by SeanFarrow** [comment]
Ok, maybe I was meaning something else , lets say I have a ffolder structure on the source system, it would be nice to run a utility providing me with wix# code to replicate this on the target system a little bit like what heat can do?

target system

**Comment by oleg-shilo** [comment]
You may want to stop using your email client and post directly on GitHub. Otherwise your email get publicly exposed. See your post above.

As for replicating the dir structure see the "ReleaseFolder" and "WildCard Files" samples.
