### ISSUE TITLE
Can't find related products 

### ISSUE THREAD

**Issue by sotiredofyours** [oleg-shilo/wixsharp#1330]
Now there is an application installed by an old installer. It has a known `UpgradeCode` and `ProductCode` is a constant. I set the same `UpgradeCode` in my project, `ProductCode` is set as `project.GUID`.  

 Under a normal user everything works as it should - the old application is removed during the installation process.
But when I run the new installer under administrator, it doesn't find the related product and installs next to the already installed product.

After some investigation, I found a strange behavior in the installer logs (there is no such behavior when installing from a simple user):
```
FindRelatedProducts: could not read ASSIGNMENTTYPE info for product '{MyProductID}'.  Skipping...
FindRelatedProducts: could not read ASSIGNMENTTYPE info for product '{MyProductID}'.  Skipping...
```

I tried to change the InstallationScope but it didn't help. Maybe you have encountered something like this before and can tell me which way to investigate further.

**Comment by sotiredofyours** [comment]
I found out that the behavior does not depend on user rights, but on what `InstallScope` the previous installer had (its could install either way). If you install in `perUser` and the previous program was installed in `perUser`, everything works as it should. But if the scopes are different, the same error occurs. I need to uninstall the previous product regardless of the scope. Is this possible?

**Comment by sotiredofyours** [comment]
It turns out that there is no way to check both types of the installed product at once? Maybe check in custom  actions somehow?

**Comment by oleg-shilo** [comment]
Have a look at `root\Source\src\WixSharp.Samples\Wix# Samples\InstallScope_Dynamically`
You still have some flexibility even after the msi is compiled. Maybe it can help.

**Comment by sotiredofyours** [comment]
Unfortunately, it didn't help. But thanks for the quick response anyway.
