### ISSUE TITLE
Error when build multilanguage MSI

### ISSUE THREAD

**Issue by oury1** [oleg-shilo/wixsharp#1334]
Hi
I have a error when trying to build msi multilanguage file 
the error is :

 "C:\Users\sango\.nuget\packages\wixsharp.wix.bin\3.14.0\tools\bin\torch.exe" -p -t language ".\kk_module_setup13.0.0.0.msi" "C:\Users\sango\Downloads\kk-master\kkPlugin\WixInstaller\fr-FR.msi" -out "C:\Users\sango\Downloads\kk-master\kkPlugin\WixInstaller\fr-FR.mst"
  Windows Installer XML Toolset Transform Builder version 3.14.0.6526
   Copyright (c) .NET Foundation and contributors. All rights reserved.
   
 C:\Users\sango\Downloads\kkNoah-master\kkPlugin\WixInstaller\torch.exe : error TRCH0001: Internal MSI failure. Win32 error: 1631, MSI error: 2203, detail: C:\Users\sango\Downloads\kkNoah-master\kkPlugin\WixInstaller\fr-FR.mst, -2147287008
   
   Exception Type: Microsoft.Tools.WindowsInstallerXml.Msi.MsiException
   
   Stack Trace:
      at Microsoft.Tools.WindowsInstallerXml.Msi.Database.GenerateTransform(Database referenceDatabase, String transformFile)
      at Microsoft.Tools.WindowsInstallerXml.Binder.BindTransform(Output transform, String transformFile)
      at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
      at Microsoft.Tools.WindowsInstallerXml.Tools.Torch.Run(String[] args)
   Binder temporary directory located at 'C:\Users\sango\AppData\Local\Temp\hf3fuwqg'.
   Unbinder temporary directory located at 'C:\Users\sango\AppData\Local\Temp\hf3fuwqg'.
   Torch temporary directory located at 'C:\Users\sango\AppData\Local\Temp\h3tnpfud'.
   > Multi-language setup .\kk_module_setup13.0.0.0.msi is completed.

But the file is created and work fine 

the code i have used 

` project.Language = "en-US";
 string productMsi = project.BuildMsi();
 project.Language = "fr-FR";
 string mstFile = project.BuildLanguageTransform(productMsi, "fr-FR");
 productMsi.EmbedTransform(mstFile);
 productMsi.SetPackageLanguages("en-US,fr-FR".ToLcidList());
 project.Language = "en-US,fr-FR";
 project.BuildMultilanguageMsi(@".\kk_module_setup"+ project.Version+".msi");`

thanks for the help

**Comment by Torchok19081986** [comment]
Morning, looks like windows error. Do you try to create you multilanguage MSI with admin rights? I had same error , that wixtollset could access wixtoolset exe's. I started visual studio elevated and error disapears. 
Another question, why build msi multilanuage ? Is Burn Installer not more suitable for multilanguage MSI ? In Wix 3.11 works prety well and example for that is from Oleg really good.

**Comment by oury1** [comment]
Hi Thanks for your response
but elevated visual studio not fix the issue same error

I need multilanguage msi because i need autodetected windows language for
the msi


Le jeu. 31 août 2023 à 09:09, Torchok19081986 ***@***.***> a
écrit :

**Comment by Torchok19081986** [comment]
hm.. ok. Then why not build various count of msi with main languages like, en-Us, fr-FR and so on. After that build Burn Installer and add all this MSI's files to Burn Installer Package and on the runtime create CA with windows Language Detection and start right MSI for it ? Example of Burn Installer with embeded MSI could you help with, maybe. Is good Point to start.

**Comment by oleg-shilo** [comment]
Have a look at the multi-lang sample:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/bc767fd1-7bfa-4178-9d17-ba04fc8deb92)

It uses MST transformation file for embedding additional languages in a single msi.

However I also prefer a simple approach with a culture-specific msi. Even though this approach is less elegant than MST approach. But it is more straight forward since MSI does not support runtime-localization natively.

**Comment by oleg-shilo** [comment]
As for your error then indeed it is an unhandled exception in torch.exe, which is part of WiX SDK. Thus it is an external product with respect to WixSharp - "who knows what is happening there".
