### ISSUE TITLE
Detection of .NET 6 or NET 7

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1339]
Morning, does anyone know, how to add Detection of .NET 6 or .NET 7 with WixSharp or pure Wix Toolset v4 ? 
My Programm based on NET 6 and will be upgraded to NET 7 end of this year.  How can i add in Node  
```charp
new PackageGroupRef("NetFx472Web")
```
NET 6 or NET 7 detection ? 

Many Thanks.

**Comment by Torchok19081986** [comment]
i found link for Wix Toolset V4 fot NETFX Extension, but i dont know how to add it to BA Installer. 
https://wixtoolset.org/docs/tools/wixext/dotnet/
I think, i have to add 
<netfx:DotNetCoreSearch
  RuntimeType="aspnet"
  Platform="x64"
  MajorVersion="6"
  Variable="AspNetCoreRuntimeVersion"
  />
Part to my Installer, but here i struggle.

**Comment by oleg-shilo** [comment]
You can add a simple class to your codebase:
```c#
public class DotNetCoreSearch : ChainItem
{
    [Xml] public string RuntimeType = "aspnet";
    [Xml] public string Platform = "x64";
    [Xml] public string MajorVersion = "7";
    [Xml] public string Variable = "AspNetCoreRuntimeVersion";

    public override XContainer[] ToXml()
    {
        var root = new XElement(WixExtension.NetFx.ToXName("DotNetCoreSearch")).AddAttributes(this.Attributes);
        root.Add(this.MapToXmlAttributes());
        return new[] { root };
    }
}
``` 

And then:
```c#
 var bundle = new Bundle("My Product",
                  new MsiPackage(yourMsi),
                  new DotNetCoreSearch());
```

**Comment by Torchok19081986** [comment]
Many Thanks, @oleg-shilo. I will use it later for my bundle. Last Question, after that close Issue. I am right, that Wix V4 has some breaking Changes for Bundle and each Extension like NetFx ? Is there limitation or scenario where i cant use this code for some reasons ? I question that, because Wix V4 is new and not fully documented like v3.11.

**Comment by oleg-shilo** [comment]
WiX4 has renamed all extensions and implemented them in new assemblies. But this is completely handled by WixSharp.

As for the stability of WiX4 implementation.... TBH I am lost here. I found myself very often struggling with the documentation and some behaviour changes that are not documented so I had to reverse engineer them. :o(

And WiX team has no capacity to address it in a timely manner.

**Comment by Torchok19081986** [comment]
then i approach wix v4 bundles and msi´s with care. I can always switch to v3.11 / v3.12 back. 😀😀😀
