### ISSUE TITLE
Exception on new BA Installer with WixBootstrapp V4

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1340]
Morning, 
i tested new BA Installer for DisplayInternal UI with newest WixSharp and WixToolset v4 . Sample is MultiLanuguges Support. 
Code: 
```csharp

public class WixBAFactory : BaseBootstrapperApplicationFactory
{
    protected override IBootstrapperApplication Create(IEngine engine, IBootstrapperCommand command)
    {
        //Debug.Assert(false); <-- Cause Exception at Start. My System or it is Bug ? Dont know. 
        return new BA(engine, command);
    }
}

```

Error at Start of Installation shows like in Picutre. 

![Error on Start](https://github.com/oleg-shilo/wixsharp/assets/25432729/47f52913-31a3-4f95-857a-a9253813df80)

**Comment by oleg-shilo** [comment]
It is an assertion. Please remove it.
It has been left there by accident after debugging.

The code-base has been corrected.
