### ISSUE TITLE
Question : WPF Installer with Custom UI

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1341]
Hallo, i would like to add Avalonia UI to WPF UI and Change Caliburn.Macro to MS MVVM Toolkit for WPF. I got some good points and skills for MVVM Toolkit. 
How do i change WPF Installer UI and use it in Wixsharp ? Shoud i use wix toolset 3.11 or v4 ? WixSharp in latest Version ?

**Comment by oleg-shilo** [comment]
Both v3.11 and v4.0 of WixSharp use CM for the stock WPF dialogs thus migration will not make any difference.

CM is used only for binding but you do not have to use it. You can go with any other MVVM framework (including CM, which is imho by far superior to any other alternative).

Just create the project from "Custom UI" VS project template and then you can use any UI building technique of your choice.

**Comment by Torchok19081986** [comment]
Many thanks, @oleg-shilo. I try it. does MSI matter which .NET Framework UI in ManagedUI execute or not ? Avalonia UI runs only as NET 7 or higher. CustomUI WPF Project is .NET Framework 4.7.1 or hight. Not 100% sure, if i can add .NET 7 compiled Dlls from
Avalonia UI to CustomUI Project. Do i have to use AssemblyResolve Event for Dependecies of UI  ? If so , lot of work. 
Bundle UI cant i set to Custom UI, right ?

**Comment by oleg-shilo** [comment]
Yes it does matter. 
MSI loads **.NET Framework** flavour of CLR not **.NET Core**. Meaning that you cannot use any version of .NET higher than 4.8. Thus you will need to use the .NET Framework Avalonia build, if it exists.

As a side note, if you need to have such a comprehensive deployment UI that you need to use a rich framework as Avaonia, it tells me that you seem to much (e.g. complex product configuration). In such cases having reach UI outside of MSI process is more appropriate. 
Just a suggestion...

**Comment by Torchok19081986** [comment]
Morning. hm.. i thought so. Ok. Thanks for suggestion. I have some special Dialogs with Certificate Import, Sql Server Dialog and Check User for allow Read/Write Rights in SQL Database.  I had created MSI Package for this purpose and it works. Now, i should create better  UI for this Installer with .exe.  In WPF can i create so awesome UI , but i dont know where to start for this purpose. 
Which kind of project to start to create Installer ? In Prinzip i need WPF UI with Functionals from MSI. 
Project in  Examples src\WixSharp.Samples\Wix# Samples\External_UI\WpfSetup is , i think, right choice. BUT It doesnt show any dialogs. It Installs just Product. Here begins my struggle.

**Comment by oleg-shilo** [comment]
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/f7a80fc8-3cfe-4ce5-99b5-d24b66374c54)

**Comment by oleg-shilo** [comment]
src\WixSharp.Samples\Wix# Samples\External_UI\WpfSetup 
will also do

**Comment by Torchok19081986** [comment]
ok, thanks. If i understand right, i have to add UI Wizard to Next / previous Page in WPF and transfer data from UI to MSI. MSI Install example is there with CUSTOM_UI = True. Only one thing i dont understand , what is easier set CheckBox for example "Skip Certificate Import " at first window or Skip it in Wizard itself later ? MSI copy files to destination.

**Comment by oleg-shilo** [comment]
it's the same effort. 
I personally have a slight preference for the  "Install Documentation" approach. Just easier to debug if you need to.
