### ISSUE TITLE
ARP Entries by Bundle Installation

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1343]
Hallo,  i got curious behaviour of Bundle Installer. Standard Bundle Installation create 2 Entries for Bundle and MSI , but if i uninstall Bundle , Routine of Uninstallation doesnt uninstall MSI Product from ARP Entry.  Is still be there . 
How can i also uninstall MSI Product if Bundle going be unsintalled if possible ?
 
In V3.11 of WixToolset i could set hide Property to Bundle, but it doesnt work anymore. I think it has to do with new WixToolset V4 implementation. 

Project was created in Visual Studio 2022 and Template for Bundle Wix V4.

**Comment by Torchok19081986** [comment]
I can give some new Info, after i try and fail on Testsystem. If i set bootstrapper.UpgradeCode same like in MSI Project, then only bundle Installation will be created in ARP Entry. Uninstallation runs well. UI comes and uninstall MSI Producht with Bundle Installation. This Behaviour is new for me, and dont knew it. Was is in 3.11 same or not ? 
😐😐😐

**Comment by oleg-shilo** [comment]
> Was is in 3.11 same or not ?

I expect it to be the same as in 3.11. I doubt WiX team would change the fundamentals.

> i could set hide Property to Bundle,

Not sure I follow. Bundle neither XML element nor class have `hide` property.

You can still control `Visible` attribute of the package. The same way as in 3.11. The produced XML is the same

in 3.11
```xml
<Chain>
    <MsiPackage DisplayInternalUI="yes" Visible="yes" SourceFile="CRT.msi" ...
```
in 4.0
```xml
<Chain>
    <MsiPackage Visible="yes" SourceFile="CRT.msi"  ...
```

**Comment by Torchok19081986** [comment]
Morning, i tested visible  = false / true. Behaviour is same.  But only if i set Visible on Bundle Class to false / true. If not Bundle displays 2 Entries in ARP . Also Registry checked. 2 Entry are exists in Registry, depend on Platfom which was set in Bundle and MSI. 
Still curious. 
😐😐😐
