### ISSUE TITLE
Installation Path to MSI 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1344]
Morning, i created External UI in Wpf based on WPF Setup from Samples. 
```csharp

public void StartInstall()
{
    if (InstallDocumentation)
        base.StartInstall("CUSTOM_UI=true ADDLOCAL=Binaries,Documentation");
    else
        base.StartInstall("CUSTOM_UI=true ADDLOCAL=Binaries");
}

``` 

I added Path to choose for Installation, but MSI doesnt get it. I set standard path to C:\apps\mycompany\mytools. 
do i have add Installdir BEFORE or AFTER ADDLOCAL ? I tried both, but nothing working. MSI is embeded and has also standrdpath . 
If i understood correctly, MSI will be triggered to start from External UI with parameters from before. 

msi creation project looks following : 

```csharp

static public void Main(string[] args)
    {
        var docs = new Feature("Documentation");
        var binaries = new Feature("Binaries");

        var project =
            new Project("MyProduct",

                new LaunchCondition("CUSTOM_UI=\"true\" OR REMOVE=\"ALL\"", "Please run setup.exe instead."),

                new Dir("C:\Apps\My Company\My Product",
                    new File(binaries, @"Files\Bin\MyApp.exe"),
                    new Dir(@"Docs\Manual",
                        new File(docs, @"Files\Docs\Manual.txt"))));

        project.UI = WUI.WixUI_InstallDir;
        project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");

        Compiler.BuildMsi(project);
    }

```

**Comment by oleg-shilo** [comment]
Your setup object has reference to the msiFile location:
```C#
private void Window_Loaded(object sender, RoutedEventArgs e)
{
    App.HideSplashScreen();

    Setup = new MyProductSetup(App.MsiFile);
``` 

And the file itself is created at the application startup:

```C#
public partial class App : Application
{
    static Window splashscreen;

    private void Application_Startup(object sender, StartupEventArgs e)
    {
        splashscreen = new SplashScreen();
        splashscreen.Show();
        App.DoEvents();

        byte[] msiData = WpfSetup.Properties.Resources.MyProduct_msi;
        MsiFile = Path.Combine(Path.GetTempPath(), "MyProduct.msi");

        if (!File.Exists(MsiFile) || new FileInfo(MsiFile).Length != msiData.Length)
            File.WriteAllBytes(MsiFile, msiData);

        AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
    }
```

The code above is from the `External_UI/WpfSetup` sample

**Comment by Torchok19081986** [comment]
thanks, that was my start project. Meanwhile i could create some new items for my needs to install or skip. Works like a charm. 

After some tries, i could set it in Installdir for MSI File by adding INSTALLDIR to TextBox binded Property. 
Only last Question here : I cant use same functionality like it was in Bundle, right? Means, i cant upgrade to newer Version of MSI if MSI file has newer Version as already installed. 
I tried to change MSI Version from 1.0.0.0 to 1.1.0.0 , but after start Setup it show always Product is installed , but update or upgrade is not possible, only repair or unintall.

**Comment by oleg-shilo** [comment]
>  but after start Setup it show always Product is installed

Yes if you are upgrading then you start with the product being installed. 

This is what you can rely on:

```c#
var code = AppSearch.GetProductCode("Windows Live Photo Common");
var name = AppSearch.GetProductName("{1D6432B4-E24D-405E-A4AB-D7E6D088CBC9}");
var version = AppSearch.GetProductVersion("{1D6432B4-E24D-405E-A4AB-D7E6D088CBC9}");
var installed = AppSearch.IsProductInstalled("{1D6432B4-E24D-405E-A4AB-D7E6D088CBC9}");
```

**Comment by Torchok19081986** [comment]
hm.. ok. i have to search for solution. WixSharp.Msi.dll has Class MSI Parser. GenericSetup inherit from MSI Session where it defnied. Has same methods. How do i perform Update to newer Version of MSI if it installed ? Just execute MSI with parameters like ... UpgradeCode = 'GUID-HERE' ? Call of "IsProductInstalled " happens before them and UI Buttons based on true or false.

**Comment by oleg-shilo** [comment]
>  How do i perform Update to newer Version of MSI if it installed ?

You just start your msi as if the product is not installed. And it will install the old version and after that install a new version. You do not need to pass anything. UpgradeCode  is not a parameter that comes to msi from outside but an identity of the MSI

**Comment by Torchok19081986** [comment]
hmmm..  That means currently implmentation of Install button in Xaml with binding and properties i can ignore, right ?
```csharp

<Button
    Click="Install_Click"
    IsEnabled="{Binding CanInstall}"
    Visibility="{Binding InitialCanInstall, Converter={StaticResource BooleanToVisibilityConverter}}">
    Install
</Button>

```

**Comment by Torchok19081986** [comment]
Heureka!! It works. It was cached in %temp% File. If there File already exists it doesnt work. MSI install always this file, and this was mistake. Also need to add MajorUpgradeStrategy to MSI File. Automatic to remove and install newer Version doesnt work without 

project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
project.MajorUpgradeStrategy.PreventDowngradingVersions.OnlyDetect = false;
project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;

Override Generic Setup in derived Class works also. Only Wizard for Wpf with MVVM remain opens. 
😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄😄

**Comment by oleg-shilo** [comment]
Still... the struggle with the buttons you are describing makes me think that you are probably over-engineering it :)

If you detect that 
- the product is not installed then only enable the `install` button 
- the product is installed and it is the same version as you are trying to install then only enable the `uninstall` button
- the product is installed and it is a lower version that you are trying to install then enable the `uninstall` and `install` buttons. But change the text of the `install` button to `upgrade`.

That's it

**Comment by Torchok19081986** [comment]
hm.. Thanks for advice. Ok, i going to try it. but i have now suitable installer for my needs with Extenral UI. 
Just tested. Behaviour of unsinstall, repair/change is rely on IsProductInstalled or not. This far ok.  If Product is installed, buttons for uninstall and repair/change appears in UI , if not is seeable anymore. 
I have  to change as well Install / Upgrade Button in same way.  
I just try to figere out , actionname, installing new product in UI is always English. Codepage for External UI cant be set, is protected. Also change MSI Language doesnt work. But at this poing is OK for me. I can now create some modern UI with behaviour of MSI and use MVVM Framework for it. 
Thats all because DisplayInternalUI in Wix v4 is still not very relyable.

**Comment by Torchok19081986** [comment]
Thanks for help. Dont want to waste your time anymore. 😉😉😉

**Comment by oleg-shilo** [comment]
>  ...DisplayInternalUI in Wix v4...

Not sure what you mean.  `DisplayInternalUI` is a property of the MsiPackage class that is used to build bootstrappers.
You are using ExternalUI, which is the complete opposite of the Bundle approach even though it is dealing with the same problem domain.

**Comment by oleg-shilo** [comment]
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/0fdc1162-8f01-4617-979f-47d4aa9efe56)

**Comment by Torchok19081986** [comment]
hm. i tested it in multilanguage support of this example. DisplayInternalUI Property of MSIPackage doesnt work for me and here cant or could not set any another dialog for my installer with sql database and import certificate. MSI doesnt show my dialog. And because of that i was thinking, i try External UI, which is see more often as bootstrapper Installer.
