### ISSUE TITLE
When selecting different installation directory, subfolders still get installed in default directory

### ISSUE THREAD

**Issue by Bor55** [oleg-shilo/wixsharp#1345]
I am making an installer which uses regex to check a txt file and then based on the list of needed files includes them into the setup program. The source directory has 24 files and then a folder with 5 other subfolders/files. When launching the setup and changing the installation directory, only the first 24 files get installed into the changed path, but the folder and the subfolders which are within the source directory get installed into the default target directory.
I have noticed that the sourceDir doesn't really matter because the txt file contains a fixed location and the files need to be there anyways.
![image](https://github.com/oleg-shilo/wixsharp/assets/84669914/e713e9fb-5661-4dae-8289-4dec7c2a9f0d)

![image](https://github.com/oleg-shilo/wixsharp/assets/84669914/1a62e8ec-d366-4c37-9621-240763502569)

**Comment by Torchok19081986** [comment]
morning, examine your output .wxs file. Why is targetDir Path is absolut?

**Comment by Bor55** [comment]
> morning, examine your output .wxs file. Why is targetDir Path is absolut?

Morning, thanks for your reply. What should I be looking for in the .wxs file?
I'm trying to make it so the targetDir will have the same kind of structure as the original directory (hence combine). I tried making it ("[INSTALLDIR]", currentDirectory)); hoping that would fix my issue, but it didn't.

**Comment by Bor55** [comment]
@Torchok19081986 I am adding about 110 directories/files in total so the second way would be a bit more time consuming. The way I'm doing it is that I have a .txt file which contains the names of each directory and file and then I use regex to extract the names from that txt file and add each file to its given directory with the foreach part. 
As for the .wxs file, I found this:
![image](https://github.com/oleg-shilo/wixsharp/assets/84669914/3e2603e2-be74-4d52-acd0-fc3589fd2d6d)
The files should all be installed at the C:\inetpub\SoapTest\ but instead they're at the TARGETDIR1-5 which is the default path (also the path that is read from the txt file)

**Comment by Torchok19081986** [comment]
makes sense by too much files. 

looks realy curious. Do you try to add file to IIS ? If so there is example from Oleg in Samples. Folder called "IIS".  Download latest example codes and then navigate to Source\src\WixSharp.Samples\Wix# Samples\IIS Folder. Here are samples of how to add webapp to IIS.

**Comment by Bor55** [comment]
That was my next goal, to implement the IIS from the sample I am working on it currently :)

**Comment by Torchok19081986** [comment]
Remember only 2 things as remark : 
1. you can always use Event WixSourceGenerated for custom description of your installer. 
2. Your webapp has to be placed in IIS in Subfolder of mainfolder . Only then iis shows it in Webserver and manager.

**Comment by Bor55** [comment]
Thanks, I'll remmember that.

**Comment by oleg-shilo** [comment]
MSI/WiX deployment specification expects TARGETDIR, which points to one of the well-known locations like "Program Files".

If you want to deploy to an absolute path then you need to take special care about setting this all up as MS/WiX does not support abs paths directly. WixSharp does the heavy lifting:

```c#
        var project = new ManagedProject("MyProduct",
                          new Dir(@"C:\inetpub\SoapTest",
                              new Files(@"d:\dev\SoapTest\publish\*.*")));

        project.UI = WUI.WixUI_ProgressOnly;
        
        project.PreserveTempFiles = true;
        project.BuildMsi(project)
```

As a generic advice, have a look at the samples on this repository and specifically on the InstallDir_AbsolutePath sample.

**Comment by Bor55** [comment]
Thanks for the example and advice, I'll go look at that sample now.
