### ISSUE TITLE
AppSearch.GetProductVersion() doesn't return a revision

### ISSUE THREAD

**Issue by quatrebi** [oleg-shilo/wixsharp#1346]
### Case
I need to compare the versions of the products: current & installed. I use one `.msi` installer with Embedded UI.

### Reproduce
I get the version of the installed product via `AppSearch.GetProductVersionFromUpgradeCode()`. The current version via the `ProductVersion` session property with parsing to the `Version` type.

### Problem
The installed version like as `1.14.1`. It's without revision (the 4th value).
The current version - `1.14.1.0`. It's WITH revision.
So, _CSharp_ thinks that it's different version - **THATS BAD FOR ME**

### My vision
I checked at the code of `AppSearch.GetProductVersion()`, which is used by the method above. And I saw that the `Version `object creates without **revision** (the 4th value)

specs:
* .NET Framework 4.8
* WiX Toolset v.3.14

**Comment by quatrebi** [comment]
#SOLUTION
Based on the information from the [link](https://learn.microsoft.com/en-us/windows/win32/msi/productversion). I came to the conclusion that the problem is in the installer. Which ignores the revision. Therefore, to solve this problem, it is necessary to change the versioning rules for the installer/product.

**Comment by quatrebi** [comment]
# Another solution
Use `MsiGetProductInfo()` method `INSTALLPROPERTY_VERSIONSTRING` and parsing via `Version` class returns all info about product version including revision

**Comment by oleg-shilo** [comment]
Good tip. Thank ou for sharing

**Comment by oleg-shilo** [comment]
I have added `AppSearch.GetProductVersionString` to allow more convenient access to the version information:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/ed8d7b1f-65af-4777-87e4-bf2c1826c004)

It will be available in the very next release.

**Comment by oleg-shilo** [comment]
Note some products are impossible to read with `MsiGetProductInfo`.

Thus Spotify and Zoom are installed in some exotic manner that MSI interop does not detect them via:

```C#
[DllImport("msi")]
static extern int MsiEnumProducts(int iProductIndex, StringBuilder lpProductBuf);
```
