### ISSUE TITLE
WPF External UI Actionname Localization

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1347]
Morning, i try to add Localization to Actionname in External UI Project. Forget to mention, Language is it always "en-US". 
MSI Language ist set to "de-DE", but External UI doesnt show Actions for Install new Product in "de-DE" Language. Codepage cant be set either, it is protected by GenericSetup Class of WixToolset / Wixsharp. 
How do i set or add Localization to External UI ? 

in WPF is following segment 

```csharp
  <StackPanel
      Grid.Row="1"
      Margin="10,0,69,5"
      VerticalAlignment="Bottom">
      <TextBlock Margin="0,5" Text="{Binding CurrentActionName}" />

```

**Comment by Torchok19081986** [comment]
Morning, i was trying to figured out, why my external UI does show actionname in English ? 
my msi description looks like this 

```csharp

static public void Main(string[] args)
{
    var docs = new Feature("Documentation");
    var binaries = new Feature("Binaries");

    var project =
        new Project("VTE Tool",

            new LaunchCondition("CUSTOM_UI=\"true\" OR REMOVE=\"ALL\"", "Please run setup.exe instead."),

            new Dir(@"C:\Apps\My Company\My Product",
                new File(binaries, @"Files\Bin\MyApp.exe"),
                new Dir(@"Docs\Manual",
                    new File(docs, @"Files\Docs\Manual.txt"))));

    project.Version = new Version("1.4.3.1");
    project.Language = "de-DE";
    project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
    project.MajorUpgradeStrategy.PreventDowngradingVersions.OnlyDetect = false;
    project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;

    project.UI = WUI.WixUI_InstallDir;
    project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
    project.UpgradeCode = new Guid("E52630EA-EE81-4F7C-86FF-464825237A5A");
    Compiler.BuildMsi(project);
}

```

do i need add .wxl file to my msi or anything else ?

**Comment by oleg-shilo** [comment]
I am not entirely sure how the localization of progress messages is taking place in MSI. 
You can check if the stock UI (native MSI GUI) is localizing the messages correctly. It can give you a clue.

**Comment by Torchok19081986** [comment]
thanks, @oleg-shilo. I found a mistake in creation of MSI .  I know reason why msi was in english. It happening cause MSI in previous Version was installed in en-US. if you add another language to msi and perform update, a previous version language will be used, not current one. i had in previous version no language , by default en-US, and in current exe Embeded UI , was set to "de-DE". Also i could override Methods in my Class which is inheriting in Generic Setup for example
```csharp

private void RunAsync(Action action)
{
    ThreadPool.QueueUserWorkItem(delegate
    {
        try
        {
            action();
            ErrorStatus = "Erfolgreich";
            UpdateStatus();
        }
        catch
        {
            ErrorStatus = "Failed. See log file for details.";
        }

        IsRunning = false;
    });
}


private void UpdateStatus()
{
    using MsiParser msiParser = new(MsiFile);
    IsCurrentlyInstalled = msiParser.IsInstalled();
    ProductName = msiParser.GetProductName();
    ProductVersion = msiParser.GetProductVersion();
    ProductStatus = string.Format("Software ist {0} INSTALLIERT\n\n", IsCurrentlyInstalled ? "" : "NICHT ");
}

```
after that, i was able to change it to de-DE and update to newer version was successfully shows in de-DE language. It is not 100% correct, by for needs , thats all.
