### ISSUE TITLE
RegistrySearch not reading value

### ISSUE THREAD

**Issue by gw-ubunye** [oleg-shilo/wixsharp#1348]
Hi,

I am trying to read the registry to set properties for use in my launch conditions. I have the following:

```
new Property("WIN_RELEASEID", new RegistrySearch(RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion", "ReleaseId", RegistrySearchType.raw))

new Property("DOTNET_INSTALLED", new RegistrySearch(RegistryHive.LocalMachine, @"SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedhost", "Version", RegistrySearchType.raw))
```

I log both values to see what is returned by the search. WIN_RELEASEID returns the correct value whereas DOTNET_INSTALLED is empty where it should be "7.0.11". I have tried a few other keys to test and some return values, others don't. The installer is running with elevated permissions so that shouldn't be an issue.

I'd appreciate any guidance.

**Comment by oleg-shilo** [comment]
To investigate it you can try to read the values from the `project.BeforeInstall` event:

```C#
project.BeforeInstall += arg =>
{
    arg.Session[WIN_RELEASEID] = <read your registry here>;
    arg.Session[DOTNET_INSTALLED] = <read your registry here>;
};
```

You can even put an assertion in the hander so you can debug it.

**Comment by gw-ubunye** [comment]
The "BeforeInstall" event appears to fire too late. My managed action that logs the values is set to fire after the "LaunchConditions" step and the logged value is null. So, I changed the action to fire before LaunchConditions and I read the registry then as well. This works. I will go with this solution. I don't understand why RegistrySearch doesn't work though.

**Comment by oleg-shilo** [comment]
is it possible that the problem is caused by the RegSearch searching in the WOW registry hive because msi session is a x86 process?

**Comment by gw-ubunye** [comment]
Could well be. I am forcing the 64bit registry in my custom action. Any way to do this with the "RegistrySearch"?

**Comment by oleg-shilo** [comment]
This is MSI/WiX mystery. I personally, would prefer to do any stuff that does not behave well from code (CA).
I can analyse my environment (86 vs 64) I can control what I am doing. I can debug!!! 😄

**Comment by gw-ubunye** [comment]
Sure, but I wouldn't want to reinvent the wheel either. I'd like to use the facilities that are there, if I can. 😉

Ito. debugging, I have never done this with an installer. Is there guidance on how to do this somewhere?

I am struggling with something else now, but I'll first fight it a bit more and if it defeats me, I'll post as a new issue.

Thanks for your help so far.

**Comment by oleg-shilo** [comment]
When dealing with MSI, sometimes reinventing the wheel is a better option :o)
But of course, it all depends.

As for debugging, it's described [here](https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#managed-custom-actions)

**Comment by gw-ubunye** [comment]
Yep, I am starting to agree. Reinventing square wheels would make for a much smoother ride. Custom actions it is then.

Thanks for your help, Oleg.
