### ISSUE TITLE
Perform Uninstall and restart UI

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1349]
Morning, i fight External UI with embed MSI to do uninstall current version and install newer Version.  Uninstall happens depend on MajorUpdateStrategy and in my spefic case after Stepinitialize. Runs well, but i want, if possible, to restart UI AFTER old version uninstalled and newer Version should be installing. I dont know how to do it ?

**Comment by oleg-shilo** [comment]
Detect your conditions (e.g. it is update or fresh install)

On the exit of application just for another process with the same assembly but pass a CLI parameter so you do not do an infinite loop:

```C#
static void Main(string[] args)
{
    App.SupressRestart = args.Contain("-donotrestart");
}
. . .
if(needToRestart && !App.SupressRestart)
{
    Process.Start(this.GetType().Assembly.Location, "-donotrestart");
    Process.CurrentProcess.Kill();
}
```

**Comment by Torchok19081986** [comment]
i could do it , somehow. Logic is same. After some struggles and tries. I make it depend on if AppSearch does find product by Guid or not. If so, then strict forward to perform msi actions. Code from @oleg-shilo works. 👍.
