### ISSUE TITLE
How does one change the color of a TextStyle?

### ISSUE THREAD

**Issue by krippz** [oleg-shilo/wixsharp#135]
Hi I'm trying to build a custom UI, I'm using the BuildHelper method 
```
var customUI = new CustomUI();

SetDefaultTextStyles(customUI);

customUI.On(NativeDialogs.ExitDialog, Buttons.Finish, new CloseDialog() { Order = 9999 });
customUI.On(NativeDialogs.WelcomeDlg, Buttons.Next, new ShowDialog(NativeDialogs.LicenseAgreementDlg));
customUI.On(NativeDialogs.LicenseAgreementDlg, Buttons.Back, new ShowDialog(NativeDialogs.WelcomeDlg));
... 
omitting for clarity
```

I do have a helper method that does this:

```
private static void SetDefaultTextStyles(CustomUI customUI)
{
   customUI.TextStyles.Clear();
   customUI.TextStyles.Add("WixUI_Font_Normal", new System.Drawing.Font("Tahoma", 8));
   customUI.TextStyles.Add("WixUI_Font_Normal_Bold", new System.Drawing.Font("Tahoma", 8, System.Drawing.FontStyle.Bold));
   customUI.TextStyles.Add("WixUI_Font_Bigger", new System.Drawing.Font("Tahoma", 12));
   customUI.TextStyles.Add("WixUI_Font_Title", new System.Drawing.Font("Tahoma", 9, System.Drawing.FontStyle.Bold));            
 }
```

But I'm failing to understand how I can get the following xml in the .wxs file:

```
<TextStyle Id="WixUI_Font_Normal" FaceName="Tahoma" Size="8" Red="255" Green="255" Blue="255"  />
...
omitting for clarity
```

Thank you in advance!

/regads
@krippz

**Comment by oleg-shilo** [comment]
Unfortunately the WiX font attibutes do not match `System.Drawing.Font` properties. And color is one of these cases. I am afraid you have no other choice but to inject XML with `bootstrapper.WixSourceGenerated+=` post processing.

**Comment by krippz** [comment]
Thank you!
It works as  expected, If you don't mind I can perhaps create  a simple sample to demo this for future reference?

**Comment by oleg-shilo** [comment]
Absolutely! Please do the sample and then create a pull-request. If you don't want to deal with git-hub you can just send me the sample and I will add it. 
Take your time, I will be not be available on this project for next ~10 days anyway.
