### ISSUE TITLE
Windows Service app not auto close while uninstall package

### ISSUE THREAD

**Issue by gsvin99** [oleg-shilo/wixsharp#1350]
Hello, 
I'm using task scheduler to install/upgrade packages under the "system" account in order to skip the UAC prompt and automate the installation procedure. When uninstalling a package, the notification "The following application should be closed before continuing the installation" appears every time a Windows service application is installed. This problem occurs only when upgrading a package with "system" user capabilities.  If the same steps are taken and the package is upgraded with administrator privileges, the Windows service programme will shut automatically.

I saw another pattern. If you upgrade a package under the "System" account, a UAC prompt will display before triggering the project.Msi_Load += Load event. If installed with administrative access, UAC confirmation occurs after the Load event has concluded.
If try to stop a Windows service app via the command line or c# code, you will receive an access declined message. A UAC window will also show before this occurs.

Please advise on how to avoid the message "The following application should be closed before continuing with the installation" during the uninstall package.

The line used in uninstall custom action.
session.HandleErrors(() =>
                        { Tasks.InstallService(session.Property("INSTALLDIR") + "TestService.exe", false); });

Thanks in advance.

**Comment by oleg-shilo** [comment]
Hey @gsvin99,
 
 Unfortunately, I'm not able to give you any suggestions to address the problem. 
 It seems to me that the matter is related not to WixSharp or even WiX but to MSI runtime and how it handles elevations.
 
The user code of an MSI session (e.g. custom actions) does not request elevation directly so I see very little opportunity for you to change the MSI behaviour by doing something different in the code.

I am even puzzled about UAC prompt being displayed at all when you do stuff under the system account. You're supposed to be already elevated!!!

You can try to get a little more info by logging `SetupEventArgs.IsElevated` from multiple stages of your install, just to see what is happening.

**Comment by gsvin99** [comment]
Thanks @oleg-shilo .
