### ISSUE TITLE
How to prevent show previous UI in Extenal UI Project

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1351]
Morning, i struggle at moment with if it possible to prevent to appear / shows up , previous UI in Extenal UI Porject.
If i add some new components at my External UI like another Checkbox to for example "Install User Certificate" , after start exe to install newer Version, somehow UI show old version with no checkbox , but after uninstalling it and install newer Version , UI will be refresh and this new Checkbox appears. AFAIK External UI do write msi data from ebeded ressource to temp , so far OK. I tried to delete this file before newer Version appears, somehow it works. I dont fully understand why this behaviour comes. Is there possibility to do it at splashscreen. 
I tried already following code on event Application_Startup :

```csharp

if(File.Exists(Path.Combine(Path.GetTempPath(), "MyTool.msi")))
{
   File.Delete(Path.Combine(Path.GetTempPath(), "MyTool.msi"));
}

Thread.Sleep(1000);

if (!File.Exists(MsiFile) || new FileInfo(MsiFile).Length != msiData.Length)
    File.WriteAllBytes(MsiFile, msiData);

```

but somehow it doesnt work. If not possble, how to clean up all from my setup temporary files after install ?

**Comment by Torchok19081986** [comment]
i have investigated some further. After install / update to newer version files like .log and msi still exists in Temp Folder.  
MSI doesnt clean up these files. I think , it has to do with External UI. Isnt my responsibility to do it ? Fully rely on MSI Installer is not here anymore, if i understand it correctly. 🙄🙄🙄

**Comment by oleg-shilo** [comment]
if it is you who put some files in the temp dir then it is you who need to clean it.
If it MSI rutime then you don't need to do it.

**Comment by Torchok19081986** [comment]
morning, @oleg-shilo. Thanks for the infos. Ok, understood. Does Event for exit_iinstall in External UI exists? I would like to add cleanup data from temp after install / update is successfull or not. I see only event setup_started nothing anymore. 
🤨🤨

**Comment by oleg-shilo** [comment]
This is the way you can explore the events:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/3adededc-dec6-494d-81fb-9b064ded39e3)
