### ISSUE TITLE
LaunchApplicationFromExitDialog exception

### ISSUE THREAD

**Issue by Grandik7** [oleg-shilo/wixsharp#1354]
Hello,

When using LaunchApplicationFromExitDialog feature, I've got following exception: 
![image](https://github.com/oleg-shilo/wixsharp/assets/38108481/c638c862-fdd6-4aa6-9789-c1dcb92b90f3)
In generated XAML there are no UI tags. 

My minimal code looks like this:
![image](https://github.com/oleg-shilo/wixsharp/assets/38108481/13ce2de1-0824-4e8a-a93a-b5f32427ace4)

Do you have any advice for me, please?

Thanks and regards,
Michal

Used:
Console application
targeting net48
nugets WixSharp.bin 1.22.1 & WixSharp.wix.bin 3.14.0

**Comment by oleg-shilo** [comment]
There is something unexpected in the WXS structure. IE element UI is absent.
The easiest way to find out is to put a breakpoint there since you have the source code.
Not sure how this element can be lost. It's always there.

Though...
`LaunchApplicationFromExitDialog` is a feature that allows for overcoming the inflexibility of WiX native UI customization. And as such it is expensive because it relies on the complex exotic UI customization syntax.

WixSharp now offers a more natural approach with ManagedUI (there is a VS project template for that) so you can customize ExitDialog exactly the same way as you would for any other .NET app.

**Comment by Grandik7** [comment]
Exactly as you say: UI element is not there in context.XParent neither in generated *.wxs. Anyway, installer is built properly :) It's strange.

I'll try using ManagedUI.

Thanks

**Comment by Grandik7** [comment]
Anyway, I am not able to achieve equal behavior. 

Using this [solution](https://github.com/oleg-shilo/wixsharp/issues/479#issuecomment-424964739) new app is launched immediately after installation. But desired behavior is to launch new app after click on Finish button on exit dialog. 

Could you please guide me?

**Comment by oleg-shilo** [comment]
But why don't you use the exit button directly, if you are using ManagedUI? In fact, it has been introduced to make situations like this as easy to handle as any other programming task.

 You can simply put your exit button click handler:
 
```C#
void finish_Click(object sender, System.EventArgs e)
{
    Shell.Exit();
    Process.Start(Runtime.Session.Property("INSTALLDIR").PathCombine("my_app.exe"));
}
```  

You will just need to create your project form the WixSharp Custom UI template and the source code for your all dialogs will be available for you. 
Just in case if you are not aware, you can get the WixSharp project templates by installing WixSharp VS extension

**Comment by Grandik7** [comment]
Thank you, it works. I was not sure, what is "clean solution".

But Runtime.Session.Property("INSTALLDIR") was empty in my case. Instead I used Runtime.InstallDir property. Is it allright?

**Comment by oleg-shilo** [comment]
`Runtime.InstallDir` is in fact a preferred method for discovering install dir. It takes care of cases when UI may redefine the actual property holding the installdir value. Or if the US sequence is involved the MSI runtime may handle the session properties completely different way.

Anyway, glad it all worked out for you.  Keep using `InstallDir`. It's fine.

**Comment by Grandik7** [comment]
Thank you for your support!
