### ISSUE TITLE
WixSharp-wix4 can't build

### ISSUE THREAD

**Issue by kev-is-coding-for-adn** [oleg-shilo/wixsharp#1355]
Hi,

We have been using WixSharp (first named) for a while now and now is the time to upgrade our applications to NET 7.
The migration went well for the applications themselves but now we're trying to upgrade our "msi builder" application that was using WixSharp.

Our new "msi builder" now targets "net7.0-windows" and I have referenced WixSharp_wix4.bin like this:
` <PackageReference Include="WixSharp_wix4.bin" Version="2.0.1"/>`

The build of the project went well. 
But when I launch my application with some parameters, when it comes to "project.BuildMsi(outputPath);", it fails at 
`ManagedProject.cs : this.DefaultRefAssemblies.Add(Type.GetType("WixToolset.Mba.Core.Engine").Assembly.Location);`
It seems to not find **WixToolset.Mba.Core.Engine**.

Is there something I'm missing ?
Thanks for your help.
Kevin

**Comment by oleg-shilo** [comment]
Unfortunately, WixSharp-based msi builder must be an assembly targeting .NET Framework. This is a WX architectural constraint. So WixShap is also restricted here.

Theoretically, it is possible to implement the builder in any technology, but because the builder assembly is also utilized as a CA assembly it means it needs to qualify for a managed CA assembly as it is required by WiX. And this means that it is .NET Framework, not .NET Core family

**Comment by kev-is-coding-for-adn** [comment]
Thanks for the explanation !
I managed to keep my msi-builder as a .Net Framework project, and now it can generate a msi for a Net 7 project so that's perfect.

The problem I'm facing now is that, I have a `project.AfterInstall` custom actions which is defined in my msi-builder (NetFramework so). When I launch the msi created, it fails at the end with this error (seen in log file):

`Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
Info: WixSharp aborted the session because of the error:
System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'AdnSetupMaker, Version=1.24.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Tentative de chargement d’un programme de format incorrect.
Nom de fichier : 'AdnSetupMaker, Version=1.24.0.0, Culture=neutral, PublicKeyToken=null'
   à System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   à System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   à System.Reflection.Assembly.Load(String assemblyString)
   à WixSharp.ManagedProject.GetHandler(String info)
   à WixSharp.ManagedProject.InvokeClientHandler(String info, SetupEventArgs eventArgs)
   à WixSharp.ManagedProject.InvokeClientHandlers(Session session, String eventName, IShellView UIShell)`

AdnSetupMaker is the name of my msi-builder under NetFramework.

If I comment the `project.AfterInstall` in the code, the msi will work well.
Any ideas on that ?
Thanks

**Comment by kev-is-coding-for-adn** [comment]
Never mind ! It seems that `project.Platform = Platform.x64;` solve the problem !
