### ISSUE TITLE
How to install exe via the wixsharp installer

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1356]
Hi,
My question is not necessarily on wixsharp but may you know to help. Like, maybe i'm using the wrong project type etc.
Im using `ManagedProject` of wix sharp.
During the my installer I'd like to install _.net sdk_ which actually is an exe file.
I have the file attached to the project, so i just run a process on `AfterInstall` action that install the file.

Now, the exe file behaves like msi installer, double click opens GUI etc. 

The issue is, that It's failed with error code  `1618` which means it can't run multiple programs in parallel.
 a.k.a my installer and the exe file.

Any idea?
Thanks!

**Comment by Torchok19081986** [comment]
morning,  AFAIK in one MSI installer is multiple installs not possible. You have to use BA Installer / Burn Installer for this propose. 
there is sample from Oleg with multiple Installer. Here you can add your secondary package of exe and install it like another part of your installer.  Download sample and navigate to wixsharp-2.0.1.0\wixsharp-2.0.1.0\Source\src\WixSharp.Samples\Wix# Samples\Bootstrapper. Many Samples for BA. 
another good link i found : https://assist-software.net/blog/how-build-custom-installation-package-bundle-using-wpf-prism-mef-and-wix, pure wix toolset. Dont know how to do it in Wix# . 😐😐😐. 

Best regards, Torchok

**Comment by oleg-shilo** [comment]
@Torchok19081986 is right. Installing MSI is atomic and one install can only start after another one.

The canonical approach for that is a bootstrapper. A simple native application that runs one MSI installation after another.
WixSharp supports both WiX bootstrapper and NSIS bootstrapper. Have a look at the samples and you may decide which option is more suitable for you. Note, that while NSIS is not exactly MSI technology it offers an excellent simple alternative to often overcomplicated WiX bootstrapper. 

If you still want to do it the way you described then you will need to ensure that after you start your SDK installer your primary installation finishes and exits. Otherwise MSI runtime will prevent your SDK form installing as it doesit now

**Comment by RachelXGanon** [comment]
Yes, well thank you guys.
I need to fail my installer in case the .net sdk failed to install successfully so I guess my first solution is wrong.
I'll have a look on both examples.
Thx!

**Comment by RachelXGanon** [comment]
Hi,
I played a bit w/ the wix bootstrapper installer example, 
I have the .net 5 sdk executable, which i'd like to install only in case any other .net 5 version is not installed.
Using the `ManagedProject` it was quite i have a custom action that run a power script as follow:
```
  private static bool IsNet5SdkInstalled(Session session)
    {
        var command = @"dotnet --list-sdks";
        var args = $"/C {command}";

       //create a process in C#
        var executionResult = new ProcessRunner().RunHidden(new ExecutionArguments()
        {
            Executable = "Powershell.exe",
            Args = args
        });

        var sdks = executionResult.StdOut.Split();
        var isInstalled = sdks.Any(sdk => sdk.StartsWith("5."));

        return isInstalled;
    }
```

and then I could choose if I want to install this or not:
 ```
 [CustomAction]
    public static ActionResult InstallNetSdk(Session session)
    {
        if (!IsNet5SdkInstalled(session))
        {
            var result = InstallNet5Sdk(session);//fail because cant run multiple programs in parallel 
        }
    }

```

Using bundle it's like this:
```
   static void Main()
        {
            var bootstrapper =
              new Bundle("MyProduct",
                  new ExePackage("netsdk.exe")
                  {
                      Permanent = true
                  },
                  new MsiPackage("tcm.msi"));

            bootstrapper.Version = new Version("1.0.0.0");
            bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25844b");

            bootstrapper.Build("MyProduct.exe");
        }
```
 Is there a way I can implement this in bundle? like, install via custom action etc?
Thx!

**Comment by oleg-shilo** [comment]
Have a look at the WixBootstrapper example.  
It has commented out (for demo purposes) code for running the executable as one of the prerequisites.

**Comment by RachelXGanon** [comment]
Yup, saw this. BTW you have great examples
AFIK  `DetectCondition`  doesn't work for .NET 5

**Comment by oleg-shilo** [comment]
This is yet another sample for this. In this case it shows how to implement your own `DetectCondition` if the one provided by WiX does not work:

```c#
var bootstrapper =
    new Bundle("My Product",
                new ExePackage(@"..\..\Managed Setup\Self-executable_Msi\ManagedSetup.exe")
                {
                    Name = "ManagedSetup",
                    InstallArguments = "/i",
                    UninstallArguments = "/x",
                    RepairArguments = "/fa",
                    DetectCondition = "MyAppInstalled",
                    Compressed = true
                });

bootstrapper.Version = new Version("1.0.0.0");
bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25889a");

// Use file search to detect if MyApp is already present on the target system
// Alternatively you can use UtilRegistrySearch to detect the MyApp by testing registry

bootstrapper.Include(WixExtension.Util);
bootstrapper.AddWixFragment("Wix/Bundle",
                            new UtilFileSearch
                            {
                                Path = @"[ProgramFilesFolder]My Company\My Product\MyApp.exe",
                                Result = SearchResult.exists,
                                Variable = "MyAppInstalled"
                            });

// bootstrapper.PreserveTempFiles = true;
bootstrapper.Build("my_app.exe");

```
