### ISSUE TITLE
Wix binaries

### ISSUE THREAD

**Issue by Grandik7** [oleg-shilo/wixsharp#1359]
Hi, 

I've created VSIX extension using your NuGets (WixSharp.bin & WixSharp.wix.bin) serving installer creation. When I installed it, all works well. Then I passed it to my college and he got following error:
![image](https://github.com/oleg-shilo/wixsharp/assets/38108481/6c8b56a1-0322-4930-840d-ccf6ce35c1bd)

I havent installed any wix toolset - as I understand it, wix binaries are included in WixSharp.wix.bin NuGet. My college haven't yet used this NuGet so it wasn't on his disk. Then he copied my folder C:\Users\{user}\.nuget\packages\wixsharp.wix.bin to his PC and this error didn't repeat.

Instead he got other error:
![image](https://github.com/oleg-shilo/wixsharp/assets/38108481/3d15073c-0bcc-4d56-a0e2-ca55939c2983)

**I have two questions:**
Why are not wix binaries included in my extension as other NuGet libraries?
Do you have any idea what second error means?

Thanks & regards,
Michal

**Comment by oleg-shilo** [comment]
Hi Mihal,

The first error means that WixSharp cannot find WiX toolset compilers.
If you import nuget packages in VS WixSharp knows where to look for
"WixSharp.wix.bin" binaries. But you are doing it all for the extension so
it's not clear to me where the packages have been extracted. Quite possibly
it confuses WixSharp. Though if you do know that location you can simply
set it from the WixSharp project definition by setting Compiler.WixLocation:

[image: image.png]
