### ISSUE TITLE
Create .msi at Run Time, not Compile Time

### ISSUE THREAD

**Issue by silentnightwalk** [oleg-shilo/wixsharp#136]
Thanks in advance!

At the moment, my .msi is being built cat Compile time.

Compiler.BuildMsi(managedProject);

Is it possible to make so that the .msi is created at Run time?

**Comment by krippz** [comment]
Hi 
I'm not sure that I follow, you want to build a msi package from your application?
could you give a simple example of the problem you are trying to solve?

**Comment by silentnightwalk** [comment]
Thanks for your reply.

I would like to run .exe file in order to build the .msi.
Here is a simple WixSharp program:
https://github.com/silentnightwalk/SampleProjectFreelance2/blob/master/SampleWixSharp/Program.cs
And the .msi i being built at compile time here.

I would like everything else to be the same but the .msi to built after running SampleWixSharp.exe

Have a good time!

**Comment by lord2kim** [comment]
Hi, silentnightwalk.

U can just move `Compiler.BuildMsi(project);` line from Main() method to any other and call it by button click or by any other action.

**Comment by silentnightwalk** [comment]
Hi, lord2kim. Thanks for your answer.
But I actually want it to be inside the Main() method. Sorry for repeating, I'd like msi to be created not at compile time but at runtime. I'm sorry for not understanding, but if  Compiler.BuildMsi(project);  is inside Main() then nothing would change and msi would be created at compile time. 
:)

**Comment by lord2kim** [comment]
@silentnightwalk, yes, u right. If `Compiler.BuildMsi(project);` is inside Main() then nothing would change and msi would be created at compile time.

U need the installer to be generated at program startup time. Then u need move this function or full process of creating new installer (project) from Main() method to any other method and call it in Main().

```C#
static void Main(string[] args)
{
      another_method();
}

static void another_method()
{
    ...
    Compiler.BuildMsi(project);
}
```

**Comment by oleg-shilo** [comment]
@silentnightwalk 
Just to clarify the "build process". Your Wix# project is a console application project. If its executable run then it invokes "main" and the msi is generated. The Wix# project template is configured in such a way that the exe is executed after every successful project compilation. This creates an effect of the "Compile build" but technically speaking it is a "Runtime build".

Thus @lord2kim is correct. You can call `project.BuildMsi` from anywhere and anytime and it will build the MSI providing the input files and the environment (e.g. WiX compilers) are in place.

**Comment by silentnightwalk** [comment]
Thank you very much. After the clarification (about "build process") it became clear to me.
