### ISSUE TITLE
Copy installfiles depened of userchoice

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1360]
Hallo, i would like to create .exe Installer burn or External UI depend on which kind of License user choosed in install Dialog.  I know that i can creat public session variable like "FREE" or "PREMIUM" and check if in install session in CA, but after that my knowledge is near end. I would like to install only Files that marked as FREE and if user has Premium License copy these files. Is it possible ? There is no Condition for file and i dont know how to set each file for Condition or Feature, that later will be choosed by user and licensetype.

**Comment by Torchok19081986** [comment]
i create following CA 
code 
```csharp

[CustomAction]
    public static ActionResult DetermineLicenseType(Session session)
    {
        DialogResult result = MessageBox.Show("Do you have a premium license?", "License Type",
            MessageBoxButtons.YesNo, MessageBoxIcon.Question);

        string licenseType = result == DialogResult.Yes ? "Premium" : "Free";

        // Set the property to be used later
        session["LICENSE_TYPE"] = licenseType;

        return ActionResult.Success;
    }

```

and now i need to set files based on type. Unfortunatelly, still dont know. Any idea ?

**Comment by oleg-shilo** [comment]
I think you are on the right path.
Have a public property used as a condition for installing the file(s) in question.
Assign this property a value based on the user input
