### ISSUE TITLE
Use custom action in wix boostrapper

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1361]
Hi,
I'd like to use a custom action like that:
```
 bootstrapper.AddWixFragment("CustomActions",
            new ManagedAction("MyCustomAction", Return.check, When.Before, Step.InstallInitialize, Condition.NOT_BeingRemoved, Sequence.InstallUISequence));
```
But I get error cannot convert type `ManagedAction` to type `XElement`

from this [link](https://stackoverflow.com/questions/26615043/how-can-i-show-information-from-wix-custom-actions-in-burn-managed-bootstrapper), it seems I can use custom action in WIX

**Comment by Torchok19081986** [comment]
Morning, why do you want use CA in bootstrapper ? BA Installer is only UI that tunneling refs to MSI Package. If you have access to creation of MSI File, just Add ManagedAction to it. Thats it .  There you can handle it in session depend on your needs. Pure C# make it more dynamically. 
best regards, Torchok.

**Comment by RachelXGanon** [comment]
Hey Torchok, morning.
I need to install an exe file as  pre requisite to my msi.
The issue is that I'd like to custom this a bit such as run PS command that check which version in installed and log a proper message to the log file. And in case install failed to show a message box with a proper message to the user..

**Comment by Torchok19081986** [comment]
hm. Ok. prerequires and some harder to handle. there is sample of @oleg-shilo in Source for pre-requirements Installation. Maybe this can give you some Info about it. Why PS Command? you can use UtilSearch for Windows Registry if it should check installed version. Also in source of sample for it. Just try it in simple MSI and you have needed Information for it.

**Comment by Torchok19081986** [comment]
AFAIK is MSI throw Error if insallation failed. You can always use event after_install to check if product was installed and show it in Richtextbox at enddialog. Add event msiproject_afterinstall and handle it some like

```csharp

 productProj.AfterInstall += (SetupEventArgs e) =>
{
     MessageBox.Show("MSI session is completed", "My Product");
};

```

you need also Check if it not Upgrading or Unintaling it.

**Comment by RachelXGanon** [comment]
bootstrapper does not not know `AfterInstall` 
Does it mean that Wix cant handle custom prerequires? Maybe im using the wrong project type?

**Comment by Torchok19081986** [comment]
Wix toolset and Wix# can handle it. 
After_Install event exists only in MSI, not in BA Installer.  You add MSI to bootstapper Installer. Handle it in MSI.

**Comment by RachelXGanon** [comment]
Yeah you are right. Thought while I used MSI then I got error 1618( that it can't install multiple programs in parallel)
Actually, that why I moved to use BA installer..

**Comment by Torchok19081986** [comment]
BA Installer not Install anything. ITS ONLY UI to Handle some scenario like yours if you need to create multiple Installer. thats it. MSI / Windows Installer handle all installation. Means, all you need to do is set MSI for your needs.  And for multiple installations i recommend to consult examples from @oleg-shilo in newest Version. Oleg did very good job to provide all standard examples for it. 

Multiple MSI Instlaler in BA can be challenging, but you can try step for step approach. create msi to handle event afterinstall step1 and so on. Create simple BA and add MSI as Package to look what msi throw back to UI. step by step. After some tries, you can have some information for it and handle it in C# in CustomAction in Msi. Nothing more is it.

**Comment by Torchok19081986** [comment]
i forget one thing to mention. Use wix toolset in Version 3.11 or 3.12. In Wix V4 exists breaking changes in BA and here are some new implementation, that needs time to do some doable Installer.
