### ISSUE TITLE
Shortcut to Dir/Folder

### ISSUE THREAD

**Issue by DrGierth** [oleg-shilo/wixsharp#1363]
Hello Oleg

Is it possible to create a shortcut to a Directory/Folder?

Regards

Michael

**Comment by Torchok19081986** [comment]
morning, according to wix toolset https://wixtoolset.org/docs/v3/xsd/wix/shortcut/, looks possible. Try add in project Description new Shortcut to File or Dir.

**Comment by oleg-shilo** [comment]
At the moment it is possible by using [XML injection](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/InjectXML) but I prequalified this issue to the enhancement and will make it more straightforward.

**Comment by oleg-shilo** [comment]
Done. Released 
WiX3 v1.24.1
WiX4:  v2.0.4.0

Ironically the sample `Shortcuts` already demonstrated hos to deply a dir shortcut as the functionality was already supported. But to I have added a dedicated WiX entity `DirectoryShortcut` so it is more obvious for the users.ab=void

**Comment by DrGierth** [comment]
Hallo Oleg,

 

Thank you very much for your support.

 

I wish you a Merry Christmas and a happy and successful New Year.

 

Michael Gierth

 

Von: Oleg Shilo ***@***.***> 
Gesendet: Donnerstag, 14. Dezember 2023 08:29
An: oleg-shilo/wixsharp ***@***.***>
Cc: DrGierth ***@***.***>; Author ***@***.***>
Betreff: Re: [oleg-shilo/wixsharp] Shortcut to Dir/Folder (Issue #1363)

 

Done. Released
WiX3 v1.24.1
WiX4: v2.0.4.0

Ironically the sample Shortcuts already demonstrated hos to deply a dir shortcut as the functionality was already supported. But to I have added a dedicated WiX entity DirectoryShortcut so it is more obvious for the users.ab=void

**Comment by oleg-shilo** [comment]
Thank you Michael,

Merry Christmas to you and your family too.
