### ISSUE TITLE
Version 2.* missing on NuGet.org?

### ISSUE THREAD

**Issue by runlie-symetri** [oleg-shilo/wixsharp#1364]
Is there a reason that the version released 3-ish weeks ago is not available on the regular NuGet.org feed? I don't mind downloading it manually, but I thought I would flag it in case there are some automated actions or similar that have failed.

**Comment by oleg-shilo** [comment]
It's there: https://www.nuget.org/packages/WixSharp_wix4/
Are we talking about the same packages?

**Comment by runlie-symetri** [comment]
I am an idiot... :P Sorry!
I had the package reference for the regular packages, and simply bumped the version to 2.0.2, and didn't realize that the names had changed.

I would argue that since the major version has been bumped, it would be OK to have the same name, even though the public API is somewhat changed, but I'm not in a position to do anything other than fix my package reference and be happy that you made this available. :P 

Thank you!

**Comment by oleg-shilo** [comment]
> I would argue that since the major version has been bumped, it would be OK to have the same name, ...

Fully agree. And it is in the plan. The problem is the maturity of WiX4 that needs to be achieved first. 
POlease see this roadmap page that outlines the plan: https://github.com/oleg-shilo/wixsharp/wiki/WixSharp-and-WiX4
