### ISSUE TITLE
What is the purpose of `StartArguments` in the .targets file (see linked code)

### ISSUE THREAD

**Issue by yurikus** [oleg-shilo/wixsharp#1366]
https://github.com/oleg-shilo/wixsharp/blob/6a60ce1f777c900b757da44b5926e0338d3a26eb/Source/NuGet/WixSharp/build/WixSharp.bin.targets#L4

It interferes with my command line parsing in my debug session

**Comment by oleg-shilo** [comment]
The purpose of this param is to execute the target (your msi builder exe) as part of the build. 
It is described [here](https://github.com/oleg-shilo/wixsharp/wiki/VS2019-%E2%80%93-2022-Templates#msi-authoring-steps).
 
If it is not what you need then you can just delete this line from your project file. But then building your project will not be enough for building the MSI. You will need to execute your freshly built for that. You will also need to ensure all WiX compile tools are found by WixSharp at runtime.

Anyway. You can just go with one of the options:
- remove targets files.
- remove the packages all together but simply reference the required WixSharp dll(s)
- always skip the first attribute `args = args.Where(a=>!x.StartsWith("/MSBUILD:")).ToArray() )`

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/11b0ed5d-99aa-44dd-8b08-1a5917a07781)


In the WiX4 package the same is done purely via post-build events so it's easier to manage.

**Comment by yurikus** [comment]
> The purpose of this param is to execute the target (your msi builder exe) as part of the build.

That I understand, and to avoid that I `PackageReference` only `WixSharp.bin`. Which unfortunately adds `/MSBUID` as a property in a target. 

> If it is not what you need then you can just delete this line from your project file. 

I cannot, as the target is auto-imported on nuget restore and I want a seamless experience without modifying the local targets file, which will be overwritten next time I delete nuget cache

**Comment by oleg-shilo** [comment]
>I can probably do that, looks "dirty" though. I doubt WixSharp.bin needs this property.

This is the old version. The new WiX4 targeting package does not have it. Is migrating to WiX4 an option for you?

**Comment by yurikus** [comment]
I already wrote everything for Wix3, since this was the version available on nuget. I wish the `PropertyGroup` would've been conditioned on some `EnableX` variable, so I could turn it off. `ExcludeRestorePackageImports` turns everything off..

**Comment by oleg-shilo** [comment]
OK. Let me just rebuild the package so you can continue as usual.

**Comment by oleg-shilo** [comment]
Done. Give nuget.org a few minutes to index it. The new package will be WixSharp.bin.v1.2.1.1

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/1e65e5c0-b07a-4f51-97a7-1f186d30d3d1)

**Comment by oleg-shilo** [comment]
Yep, it is ready now

**Comment by yurikus** [comment]
Thank you very much! 
If I may suggest, for the future take note of how Net Core people condition their .props and .targets with a `DisableX` variable.

**Comment by oleg-shilo** [comment]
That's OK, what you were dealing with is an old approach that has been deprecated in the WiX4 templates that do not use any props or targets.

But... are you referring to the condition based on the "target framework" context of the package? Or it is something specific on the nuspec syntax? Or you mean "DisableX variable" as an environment variable?

**Comment by yurikus** [comment]
Here's a sample of what I mean: [GenerateAssemblyInfo](https://github.com/dotnet/sdk/blob/bc686d13672a93e8b2aabf796afdcf74e6802594/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L25) property. Default value is `true` for netcore projects and silently generates bunch of properties. Setting it to `false` allows for an external AssemblyInfo.cs file.

**Comment by oleg-shilo** [comment]
Ah, that one. It's actually an MSBuild property group condition. I thought that it was something specific for .NET Core.  

Anyway, agree, it would be a good alternative for the unconditional targets/properties. 
It's not needed for the current packages any more but it's a good technique for future packages if the need arises. Thank you.
