### ISSUE TITLE
Managed UI add dialog by condition

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1367]
Hi,
If I'm using a not managed UI project, I'm using it:

`theUI.On(NativeDialogs.VerifyReadyDlg, Buttons.Back, new ShowDialog(customDialog, condition));`

If I'm using a managed UI project, I'm using it:
```
   project.ManagedUI.InstallDialogs
                                      .Add<WixSharp.UI.Forms.WelcomeDialog>()
                                      .Add <WixSharp.UI.Forms.LicenceDialog>()
```

How can I add a dialog in managed UI by condition? as in the first example.
Thx.

**Comment by Torchok19081986** [comment]
moring, AFAIK is not possbile inject custom UI Dialog in Managed UI by condition.  You can try Xmlinjection , but i dont think result will be successfull. ManagedUI is static and cant be modified on runtime. Maybe switch to bootstrapper Installer with custom UI External or Internal. Here you has more possibilities, in WPF und pure C#, with Wix# also. 
best regards, Torchok.

**Comment by oleg-shilo** [comment]
>ManagedUI is static and cant be modified on runtime...

Not exactly. You define the dialog sequence at compile time, true, but you have full freedom to modify this sequence at runtime based on the environment conditions. IE skip the doialog and jump right to the next one:

```c#
void dialog_Load(object sender, EventArgs e)
{
    if(shouldSkip)
        Shell.GoNext();
    . . .
```
