### ISSUE TITLE
Error while installing Putty as Prerequisites 

### ISSUE THREAD

**Issue by NishantThakkar** [oleg-shilo/wixsharp#1368]
I am trying to install PuttY as Prerequisites by creating custom action. It's giving error code **1618**

### Code: 

```
var project = new ManagedProject("MyProduct",
                             new Dir(@"%ProgramFiles%\MyProduct",
                                 new File("Program.cs"),                                 
                                 new File(@"Prerequisits\putty-64bit-0.79-installer.msi")
                                 )
                             );

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

 project.Actions = new[]
            {               
                new ManagedAction(CustomActions.InstallPutty, Return.check, When.After, Step.InstallFinalize, Condition.NOT_Installed),
            };

```

```
public class CustomActions
    {
        [CustomAction]
        public static ActionResult InstallPutty(Session session)
        {
            MessageBox.Show("Inside InstallPutty...");
            session.Log("Installing PuTTY silently...");
            var installerPath = session.Property("INSTALLDIR") + @"putty-64bit-0.79-installer.msi";
            MessageBox.Show($"Install putty: {installerPath}");           
             var installCommand = $"/i \"{installerPath}\" /qn";       
           
            var processStartInfo = new ProcessStartInfo
            {
                FileName = "msiexec",               
                Arguments = installCommand,                
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using (var process = Process.Start(processStartInfo))
            {
                process.WaitForExit();

                if (process.ExitCode != 0)
                {
                    MessageBox.Show($"Exit code is {process.ExitCode}");                   
                    return ActionResult.Failure;
                }
            }
            return ActionResult.Success;
        }
    }
```
### Error: 

![MicrosoftTeams-image (2)](https://github.com/oleg-shilo/wixsharp/assets/5793534/d1071efb-8434-4b49-83d9-852d511aae5a)

**Comment by Torchok19081986** [comment]
hiho, according to MS , error 1618 throw if msi instlaler already installing something. https://learn.microsoft.com/de-de/windows/win32/msi/error-codes

Do you want to install Prerequisits in same msi package? That cant be done, unfortunatelly. You have some options here
1. Create Custom BA Installer and handle it there 
2. In Sample of Oleg, still exists NSIS Bootsrapper, here you can have Prerequisits , but UI , dont know.

**Comment by NishantThakkar** [comment]
I have created Bootstrapper  Application and used Bundle. Added PuttY as MsiPackage, which worked for me. Now I have to integrate a custom UI screen, there I have tried 2 approaches. 

### 1.  I have built using windows desktop application, and adding into bundle as ExePackage. 
**Code Snippet:** 
```
 static void Main()
        {
           
            var bootstrapper =
           new Bundle("MyProduct",          
                new ExePackage(@"Prerequisits\DesktopApp\DesktopApp.exe")
                );
            bootstrapper.Name = "MyProduct";            
            bootstrapper.Version = new Version("1.0.0.0");
            bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25844b");  
            bootstrapper.Build("MyProductBoot.exe");
        }

```
**Error:**

> [C058:8B74][2023-11-21T17:56:18]i301: Applying execute package: DesktopApp.exe, action: Install, path: C:\ProgramData\Package Cache\98DE4118FCDA0108636EE8C236B183F458B99737\DesktopApp.exe, arguments: '"C:\ProgramData\Package Cache\98DE4118FCDA0108636EE8C236B183F458B99737\DesktopApp.exe"'
> [C058:8B74][2023-11-21T17:56:18]e000: Error 0x8000809a: Process returned error: 0x8000809a
> [C058:8B74][2023-11-21T17:56:18]e000: Error 0x8000809a: Failed to execute EXE package.
> [7094:0634][2023-11-21T17:56:18]e000: Error 0x8000809a: Failed to configure per-machine EXE package.
> [7094:0634][2023-11-21T17:56:18]i319: Applied execute package: DesktopApp.exe, result: 0x8000809a, restart: None
> [7094:0634][2023-11-21T17:56:18]e000: Error 0x8000809a: Failed to execute EXE package.

### 2. I have built using Custom Dialog template, there msi has been generated and adding into bundle as MsiPackage. There I am not getting any error, but I can not see the UI of my Custom Dialog template.

**Code Snippet:** 
```
 static void Main()
        {
           
            var bootstrapper =
           new Bundle("MyProduct",          
                new MsiPackage(@"Prerequisits\Parameters.msi") { DisplayInternalUI = true }
                );
            bootstrapper.Name = "MyProduct";            
            bootstrapper.Version = new Version("1.0.0.0");
            bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25844b");  
            bootstrapper.Build("MyProductBoot.exe");
        }
```

**Comment by oleg-shilo** [comment]
You have a few problems with your approaches.

1. > I have built using windows desktop application, and adding into bundle as ExePackage.

   That exe file is your desktop UI app, isn't it? If yes, then it meaqns that you are asking the bootstrapper to run "DesktopApp" after installing Putty. But this does not make sense because you did not install your product yet.
   
2. > I have built using Custom Dialog template, there msi has been generated and adding into bundle as MsiPackage.

    If you using WiX3 then it has a bug that prevents showing MSI UI from the bootstrapper.
    
    
Thus your options are:
- Use your approach 2 but change your project type to target WiX4, which has that WiX defect fixed.
- Use your approach 1 but use MsiPackage and simply run your DesktopApp from the AfterInstall event.
  This is the most appropriate approach from the deployment good practices angle.

**Comment by juagicre** [comment]
Instead of MessageBox.Show, I would like to pass this message to the ExitDialogModel, which I see it contains the Shell and it contains the CustsomErrorDescription, but I don't find the ExitDialogModel within the Session class. 
Sorry for being a bit out of topic here, but I saw the example so similiar to my situation...

**Comment by oleg-shilo** [comment]
`ExitDialogModel` is not exactly part of the session but a custom UI provided by the user (in this case WixSharp provided it on your behalf). `Session` only holds MSI runtime properties but not UI.

The normal approach for passing some data between dialogs is saving it to the session object and then reading it from the next dialog. However, it may not work for the ExitDialog as your session can be terminated at that time. You may want to test it.

But the simplest approach is from the .NET not MSI world :)

Create your project from the "Custom UI" VS template and you will have the complete source code for your dialogs. Then you can pass the data between managed objects freely (e.g. as static members).
