### ISSUE TITLE
NativeDialogs.VerifyReadyDlg  displays InstallDirDlg

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1369]
Hi,
I'm using this to display a custom dialog after the license:
`CustomUI theUI = CustomUIBuilder.BuildPostLicenseDialogUI(dialogDefinition);`
Here, on click on the NEXT of the custom dialog: if the property ISAPPINSTALLED is not True I'd like to display customdialog2
else to display VerifyReadyDlg  
this is my code:
```
		theUI.On(dialogDefinition, Buttons.Next,
				new ShowDialog(myDialogDefinition2, new Condition("NOT_Installed AND (ISAPPINSTALLED=\"FALSE\")")));

			theUI.On(dialogDefinition, Buttons.Next,
				new ShowDialog(NativeDialogs.VerifyReadyDlg, new Condition("NOT_Installed AND (ISAPPINSTALLED=\"TRUE\")")));
```

Regardless to what the property is equal to, running the MSI I would except to get the custom dialog  or VerifyReadyDlg but i get InstallDirDlg dialog.

**Comment by oleg-shilo** [comment]
Rachel, is there any chance this issue is related to another one you have closed yesterday?
https://github.com/oleg-shilo/wixsharp/issues/1367

**Comment by RachelXGanon** [comment]
Hi Oleg, 
I have not used ManagedUI by the end, because I have to inject different dialogs, a bit more than GoNext and Prev.
Any way this issue has been fixed as I changed the condition :
`new Condition("NOT_Installed AND (ISAPPINSTALLED=\"FALSE\")") => new Condition("ISAPPINSTALLED=\"FALSE\" ")`
Im not sure why thought.

**Comment by oleg-shilo** [comment]
I do encourage you to use managed UI as it is superior to the injection of custom dialog to the native UI.
And also... with moving to WiX4 support for injecting to native UI sequence  will not be available.
