### ISSUE TITLE
Add custom attribute to Bundle project (Bootstrapper)

### ISSUE THREAD

**Issue by lord2kim** [oleg-shilo/wixsharp#137]
I'am trying to add custom attribute `dep:ProviderKey = 01234567-8901-2345-6789-012345678901` to Bundle tag of bootstrapper .wxs file (I hope this help me hardcode GUID value for bootstrapper installer):

```C#
...

var productMsi = Compiler.BuildMsi(project);

var bootstrapper =
                new Bundle($"Application",
                    new PackageGroupRef("NetFx40Web"),
                    new MsiPackage(productMsi) { Vital = true, Id = "MyProductPackageId", DisplayInternalUI = false })
                { AttributesDefinition = "dep:ProviderKey = 01234567-8901-2345-6789-012345678901" };

bootstrapper.IncludeWixExtension(@"WixDependencyExtension.dll", "dep", "http://schemas.microsoft.com/wix/DependencyExtension");

...
```

I'am tried use and Attributes property and AttributesDefinition property and has the same result:
The Bundle element contains an unexpected attribute 'WixSharpCustomAttributes'.

```XML
WixSharpCustomAttributes="dep:ProviderKey=6f330b47-2577-43ad-9095-1861bb258891"
```

What I do wrong ? How I can add custom attribute to Bundle project ?

**Comment by oleg-shilo** [comment]
You cannot use `AttributesDefinition` for that as the column character is reserved as a separator for a parent element in the attribute name: `"Component:SharedDllRefCount=yes"`.  

Thus, as in any other case of XML ambiguity, you will need to handle the problem an XML way:
```C#
bootstrapper.IncludeWixExtension("WixDependencyExtension.dll", "dep", "http://schemas.microsoft.com/wix/DependencyExtension");
...
bootstrapper.WixSourceGenerated += (doc) =>
{
    var dep = doc.Root.GetNamespaceOfPrefix("dep");
    doc.Root.Select("Bundle").Add(new XAttribute(dep + "ProviderKey", "01234567-8901-2345-6789-012345678901"));
};
```
It's possible to extend the current "add attribute" algorithm to support XML namespeces by introducing an alternative delimiter to indicate the namespace as opposite to the parent element. Though the best candidate "column" is already taken :(

The ideal solution would be:
``` C#
project.AttributesDefinition="Component|SharedDllRefCount=yes";
// and
project.AttributesDefinition="dep:ProviderKey=01234567-8901-2345-6789-012345678901";
```
And because ':' is taken (and already in use for quite some time) a less intuitive second delimiter will need to be introduced. Something like this:   
``` C#
project.AttributesDefinition="Component:SharedDllRefCount=yes";
// and
project.AttributesDefinition="dep'ProviderKey=01234567-8901-2345-6789-012345678901";
// or
project.AttributesDefinition="{dep}ProviderKey=01234567-8901-2345-6789-012345678901";
```
This is what I haven't decided yet and would appreciate the community feedback.

Anyway I am marking this issue as a feature requests so the namespace support comes in one or another way.

**Comment by lord2kim** [comment]
@oleg-shilo, thank you very much. This is working for me.

But looks like this doesn't resolve mine problem. Maybe you can help me with it ?

When I've install my application from bootstrapper installer, I have 2 new installed programms: mine program with ID which is not same as I set for .msi package; and another for bootstrapper installer.

Uninstall shortcut has Target attribute for program (not for bootstrapper installer). Maybe I can get ID value for bootstrapper installer from WPF code ? (for change Uninstall shortcut to shortcut for bootstrapper installer)
Or maybe there is another way for do it ?

For example:
In current time Uninstall.lnk has follow target: <C:\Windows\System32\msiexec.exe /x {GUID_FOR_MSI_PACKAGE}>
I wan set it to follow: <C:\ProgramData\Package Cache\{GUID_FOR_BOOTSTRAPPER_INSTALLER}\Application.exe>

**Comment by oleg-shilo** [comment]
I am not sure if you can extract the GUID from the bootstrapper app. Though you definitely can from MSI. 

Also keep in mind that you have full control over MSI identities (see this [doc section](https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming)). Meaning that you can specify your Product and Upgrade code (that appears in Control Panel) directly in your project definition.

**Comment by lord2kim** [comment]
@oleg-shilo, ok thank you.
In either case, I need a bootstrapper GUID.

I did not think about a more optimal option than parse registry branch for Uninstall programs and search installed bootstrapper application. After that, change the Target property in the Uninstall.lnk file to UninstallString from the registry.

**Comment by oleg-shilo** [comment]
BTW, that bootstrapper GUID that you see in Control Panel is most likely the "bootstrapper.UpgradeCode" that you assigned in the project definition.

**Comment by lord2kim** [comment]
@oleg-shilo, looks like no.
The fact is that I don't see any GUID values in the Unistall registry branch, which I assigned to GUID & UpgradeCode to MSI package and UpgradeCode of bootstrapper.

**Comment by oleg-shilo** [comment]
I expect you to see no `project.GUID` in the registry. Correct. However there should be `project.UpgradeCode`. 

In case of any uncertainty have a look at your MSI in Orca (MSI viewer). It will let you see directly in the MSI tables.
...
Sorry, I will not be able to respond as I will be unavailable for a week or so.

**Comment by lord2kim** [comment]
@oleg-shilo. ok thank you Oleg.
No, I didn't see UpgradeCode value in registry.

I will look. Maybe I'll find something I need :)

**Comment by oleg-shilo** [comment]
Give a try to Orca. Then you will know for sure the all IDs you should be looking for: 

![image](https://user-images.githubusercontent.com/16729806/29807685-5abe5da4-8cd8-11e7-9643-a3f9790e8b74.png)

**Comment by raghuma4** [comment]
Hi,

I am trying to add custom attribute to MsiPackage elementi in Bundle using the wix extensions. After adding the custom attribute to .xsd file and making necessary changes to CompilerExtension.cs and PreprocessorExtension.cs, still candle.exe is throwing an error saying that "The MsiPackage element contains an unexpected attribute error:Custom attribute"

Any idea to resolve this error ? 

Thanks for your help

**Comment by oleg-shilo** [comment]
First of all, a few words about the original problem reported in this thread.

Unfortunately the feature (support for **custom** attributes) has been implemented but only partially. Thus  `Project` and its content got the feature integrated but `Bundle` did not.

The very latest release v1.9.2 addresses the issue and now you can add custom attributes to the `Bundle`:

```C#
bootstrapper.IncludeWixExtension(@"WixDependencyExtension.dll", "dep", "http://schemas.microsoft.com/wix/DependencyExtension");
bootstrapper.AttributesDefinition = "{dep}ProviderKey=01234567-8901-2345-6789-012345678901";
```
This feature is yet to be extended to Packages but non custom attributes are already supported by all entities across the system. 

If you find that you cannot add custom attribute with WixSharp default functionality you can always inject then via xml-injection mechanism (see InjectXML sample).  

----

Now, about your problem.

I am not sure I follow. What are those `CompilerExtension.cs` and `PreprocessorExtension.cs` files?

Anyway, if you add attribute from the custom namespace you typically need to add this namespace via "WixExtension". This is what that `bootstrapper.IncludeWixExtension` call does.

**Comment by raghuma4** [comment]
I am sorry to confuse you. I have created my own extension schema and added custom elements to Bundle element like 
<Bundle>
     <mySchema:Elemen1 attr1="value1"
                                         attr2="value2"/>
-------------
</Bundle>

But I would also like to add custom attribute to existing MsiPackage element in Bundle like
<MsiPackage  Id="p1"
                        mySchema:CustomAttr1="value" />

I have added to custom attribute to my xsd file using <xs:attribute name="CustomAttr1".... />

As per wix documentation on MsiPackage element **Any Attribute (namespace='##other' processContents='lax') Extensibility point in the WiX XML Schema. Schema extensions can register additional attributes at this point in the schema. The extension's CompilerExtension.ParseAttribute() method will be called with the package identifier in contextValues["PackageId"].**
Reference :  http://wixtoolset.org/documentation/manual/v3/xsd/wix/msipackage.html

Unfortunately I am getting error saying that **MsiPackage contains unexpected element  mySchema:CustomAttr1**. The wix schema is not recognizing my custom attribute (CustomAttr1). 
                     

Please provide your suggestions on this ? Thanks in Advance

**Comment by oleg-shilo** [comment]
If compiler says that it cannot recognize **your** namespace extension and the name of the namespace is correct (I assume `mySchema`) then it simply means that the compiler does not know where your namespace is defined.

For example the assembly that defines `DependencyExtension` namespace  ('WixDependencyExtension.dll') is added as below:
```C#
bootstrapper.IncludeWixExtension(@"WixDependencyExtension.dll", "dep", "http://schemas.microsoft.com/wix/DependencyExtension");
```

Something similar needs to be done for your assembly as well.
