### ISSUE TITLE
Run After install as elevated

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1370]
Hi,
In the AfetrInstall action I run a simple function that suppose delete folders.
```
  if (Directory.Exists(path))
            {
                Directory.Delete(path, true);
            }
```
I get the following exception:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path '...dll' is denied.
  `
The folder exists under ProgramFiles.

AFIK AfterInstall is elevated. IS it?

**Comment by oleg-shilo** [comment]
Yes, it is elevated.
But `UnauthorizedAccessException` can be caused by other circumstances too.
