### ISSUE TITLE
[Feature request / Bug] Please make minimum Framework version 4.6.2

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1371]
I understand the "wix 4" versions are 4.7.2 but not all companies have moved to Wix 4 due to licensing and existing systems.

MS Currently have Framework 4.6.2 as their minimum update-able version;
With 4.6 "Still (currently)" in build support for VS 17.8.

Please Either change the build targets binaries to be 4.6.2
And / or make the binaries support 4.8 (As this is now the recommended for all "Updated" installations of windows 10 + 11.

![image](https://github.com/oleg-shilo/wixsharp/assets/2418812/08cd532f-1d3d-45ac-9d24-555941f38b03)

**Comment by oleg-shilo** [comment]
Hi Simon,
I am not sure I fully understand. Which WiX stream are you proposing to target an additional .NET platform? 
Is it WiX4 or WiX3?

Currently, NuGet packages are configured:

- WiX3 -> .NET v4.5.1 (will work on 4.6.2 systems)
- WiX4 -> .NET v4.7.2 (will not work on 4.6.2 systems)

**Comment by oleg-shilo** [comment]
I proceeded with multi-targeting WiX3 packages. Now this is how it is mapped:
```
WiX3 -> .NET v4.6.2 (default codebase target)
        .NET v4.5.1 
    
WiX4 -> .NET v4.7.2
```

Now you can update your packages from nuget.org (e.g.  `https://www.nuget.org/packages/WixSharp.bin/1.23.0`)

**Comment by Smurf-IV** [comment]
Thanks.
Now just need to add in 4.8 to both, and this can then be closed :-)

**Comment by oleg-shilo** [comment]
I am afraid there is some misunderstanding here. You don't need any other targets except the lowest supported. Even 4.6.2 is not needed. You can still create v4.6.2 project and use the v4.5.1 package in it. I only added 4.6.2 to acknowledge the change of the support status for these runtimes.

Thus, sorry, I see no reason to multiply runtimes for no reasonable value.
