### ISSUE TITLE
Creating a FileAssociation with Icon and Advertised = false does not work

### ISSUE THREAD

**Issue by Lumoryel** [oleg-shilo/wixsharp#1372]
Hi there,

I have problems creating FileAssociations:

```
      myExe.AddAssociation(
            new FileAssociation("myext", "application/custom", "open", "\"%1\"")
            {
                Description = "My File Type Description",
                Advertise = false,
                Icon = @"someFolder\SomeIcon.ico"
            }
```

I get the Error CNDL0014:

> The ProgId/@Icon attribute's value, 'someFolder\SomeIcon.ico', is not a legal identifier.  Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every identifier must begin with either a letter or an underscore

When I don't define an Icon, everything works.
When I define an icon and switch Advertise = true, everything works (including the icon)
But I want to have an Icon AND Advertise = false to avoid auto-repair when a double click on my file type is done.

Any Ideas?
Thank you
Lumo

**Comment by oleg-shilo** [comment]
This is the WiX magic that you are dealing with. :)

Just from the error message it looks like WiX is expecting an Id of teh WiX element but it is something else that is passed there.
Have a look at the generated WXS.

If it does not help then please create a hello world test case and I will have a look.

**Comment by Lumoryel** [comment]
Hi Oleg, thank you for having a look into it. Attached you'll find a simple example.

[WIX Test Advertising Problem.zip](https://github.com/oleg-shilo/wixsharp/files/13485812/WIX.Test.Advertising.Problem.zip)

When I turn off advertise on the FileAssociation, there is no error.
The strange thing is, when I use ` Icon = "MyIcon.ico"` , then I get a different error than when I use ` Icon = @".\MyIcon.ico"` .

**Comment by oleg-shilo** [comment]
I found the problem. It's caused by a mistake in the icon handling algorithm in the file association class.

The Icon attribute needs to be set to the exe file ID but not the icon path. While I am working on the fix please use this workaround:

```C#
  p.WixSourceGenerated += doc =>
        {
            var exeId = aAppDir.Files.FirstOrDefault(x => x.Name.EndsWith(".exe")).Id;
            doc.FindFirst("ProgId").SetAttribute("Icon", exeId);
        };
        
// or
  p.WixSourceGenerated += doc =>
        {
            var prog = doc.FindFirst("ProgId");
            var exe = prog.Parent.FindFirst("File");
            prog.SetAttribute("Icon", exe.Attr("Id"));
        };      
```

**Comment by Lumoryel** [comment]
Thank you Oleg.
So in short: it is not possible to use an external image when having a non-advertising file association.
As a workaround, I put all my icons in win32 resource files (.res), compiled it into my executables and set the `IconIndex` in the `FileAssociation`.

**Comment by oleg-shilo** [comment]
Yep, this should work.
