### ISSUE TITLE
[Bug] WixSharp.Lab nuget attempts to pull in incorrect version of System drawing

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1376]
V1.23.0

```
Failed to add reference. The package 'WixSharp.Lab' tried to add a framework reference to 'System.Drawing' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
```

Parent project is .net 4.8.0

**Comment by oleg-shilo** [comment]
`WixSharp.Lab' has no compile time dependency on a specific version of `System.Drawing`. It only enforces the referencing at compile time:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/16b99c28-4c55-464e-bc38-bad7a3fba35f)

Thus the MSI will use the version of `System.Drawing` that is available on the target system.

Note: 'WixSharp.Lab' is no longer supported and available for educational purposes.
