### ISSUE TITLE
[Feature] A way (Or create an example) of how to create a standalone fragment and insert into Projects / chains / etc

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1379]
I want to use an equivalent of a separate wix file that has the self contained variables / conditions / check / elements as a c# object, that can then be inserted into the relevant areas in a project / bundle / chain / etc.

e.g.
given an existing wix bundle  containing
``` xml
<Chain ParallelCache="yes">
    <PackageGroupRef Id="WindowsDesktopNetRuntime"/>
    ......
```
And a separate wxs file that has
``` xml
<Fragment>
    <Variable Name="CheckNETRuntime_RequiredVER" Type="version" Value="8.0.0.33101" />
    <util:RegistrySearch Id="CheckNETRuntime_ID"
                         Variable="CheckNETRuntime_Current"
                         Result="value"
                         Root="HKLM" Key="SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{17316079-d65a-4f25-a9f3-56c32781b15d}"
                         Value="DisplayVersion"
                         Win64="yes"/>

    <PackageGroup Id="WindowsDesktopNetRuntime">
        <ExePackage
            Id="WindowsDesktopNetRuntime"
        ......
```
How to do this via the wixSharp coding experience in separate files?

Because:
I want to reuse these separate fragments in other projects / bundles / etc.

**Comment by oleg-shilo** [comment]
There is a code sample for that: 
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/1ed90014-7826-444c-85c7-44b965676972)

But I added an extension to make it easier to use from files:

```C#
static public WixProject AddWixFragmentFile(this Project project, string placementPath, string wixFile)
```

**Comment by Smurf-IV** [comment]
But that is just injecting XML.
I want to use a Feature C# object and add things into (Like a project) that can then be referenced by the Parent Project / Bundle / other fragment(s)

**Comment by oleg-shilo** [comment]
And you do have this equivalent. `AddWixFragmentFile` works exactly as in WiX.

**Comment by Smurf-IV** [comment]
Is there a working example of this API usage?
And, Is there going to be a way of not using a WixFile, and doing it in code as requested ?

**Comment by oleg-shilo** [comment]
> Is there a working example of this API usage?

Yes it is in `InjectXML`


> And, Is there going to be a way of not using a WixFile, a...

Yes, these methods of adding WixObjects to the `project` are available:
```C#
project.AddActions(...);
project.AddBinaries(...);
project.AddDirs(...);
project.AddProperties(...);
project.AddRegValues(...);
```
