### ISSUE TITLE
ManagedUI, how to do something on uninstall?

### ISSUE THREAD

**Issue by jimfoye** [oleg-shilo/wixsharp#138]
I want to prompt the user for an action on uninstall (ask him if he wants me to delete application settings or leave them in place for a future install).

I have tried two approaches., 1) ManagedAction, and 2) hooking ManagedProject.UILoaded. In both cases, when installing, my code gets called, but when uninstalling, it does not.

I must be missing something!

**Comment by oleg-shilo** [comment]
You cannot do this from UI (neither managed nor native). MSI completely prohibits any customization of uninstall UI sequence and always engages builtin dialog during uninstall. Unless it's started in silent mode, of course.

What you need to do is to add event handler to an event that is not associated with UI in any way. You have  two good candidates: `project.BeforeInstall` and `project.AfterInstall`. A later one is arguably better as it runs elevated. Implement your action there (subject of 'is uninstalling' check):

```C#
static void project_AfterInstall(SetupEventArgs e)
{
    if (e.IsUninstalling)
        ...
```

**Comment by jimfoye** [comment]
Oh right, I had forgotten this! I actually implemented something similar on another project, but I had been away for Wix# for a while and I thought I could (or maybe even should) use the custom action.

You've solved the problem beautifully with these project events, thanks.

**Comment by jimfoye** [comment]
I guess this is related to #369, When I pop a MessageBox, it is "under" the window that is showing the progress of the uninstallation. Using e.Session.GetMainWindow() doesn't help here. Any ideas?

I've tried my code in both BeforeInstall and AfterInstall actions with the same result.

(Aside from this annoyance, my code is working as desired).

**Comment by oleg-shilo** [comment]
`GetMainWindow` is an attempt to find the main window associated with currently executed _msiexec.exe_:
```C#
Tasks.GetMainWindow("msiexec", p => p.MainWindowTitle.Contains(session.Property("ProductName")));
. . .
public static IWin32Window GetMainWindow(string processName, Func<Process, bool> filter)
{
    var processes = Process.GetProcessesByName(processName);
    try
    {
        return new NativeWindow(processes.FirstOrDefault(filter)?.MainWindowHandle);
    }
    finally
    {
        processes.ForEach(x => x.Dispose());
    }
}
```
Bing a reverse engineered work around It is not guaranteed to work 100% as a generic solution. Thus you may try it specifically for your sue-case with the hardcodded windows title.

**Comment by jimfoye** [comment]
The window that says "Please wait while Windows configures..." belongs to Explorer, apparently. I can find it by using EnumWindows(), GetWindowText(), etc. Now I can use it as the parent window to the MessageBox call. However, after the MessageBox closes, Windows Installer cancels the uninstall! This seems very weird, I'm sure, but it is not happening because of anything in my code. In fact, it does the same thing if I use null for the parent. The only way it does not cancel is if I use e.Session.GetMainWindow() (which returns a NativeWindow with handle of 0x0), but of course then my original problem is back.

The only thing I can come up with is that somehow the click on the MessageBox "flows through" back to the progress window and triggers the one button on that window, which is "Cancel", but it's a mystery to me how or why that would happen.

![image](https://user-images.githubusercontent.com/4249676/55841487-f591bd80-5af4-11e9-993b-5240d5e97919.png)


Any ideas or even suggestions for alternative approaches are welcome. What about Session.Message(), it's not clear to me how that works, or if it's intended for this problem.

**Comment by oleg-shilo** [comment]
I think `Session.Message` might be exactly what you need:

https://github.com/oleg-shilo/wixsharp/blob/8cd450cedeb956bd6f06e97796776a9a5f464b4a/Source/src/WixSharp.Samples/Wix%23%20Samples/Reboot/setup.cs

**Comment by jimfoye** [comment]
Sure enough, I found find this quote on an MSDN forum:

> The supported way to interact with Windows Installer isn't with a MessageBox, it's with the MsiProcessMessage Win32 API that knows how to deal with messages and windows in these situations.

I adapted your example to my needs. (For anybody reading in the future, set field 0 to your message text, if you use field 1 it will be formatted with a "1. " in front of it). Sure enough, the question appears and obviously behind the scenes the window with the message is being passed the handle to the other window as its parent, as there is no  pop-under problem, and you can't click on the parent.

However, the uninstaller is again cancelled! So the net result is exactly the same as my own code to go hunting for that window and pop a MessageBox. Of course, this code is better, as I don't need the PInvoke stuff in my code, and it's the recommended way of doing things.

I know it sounds like I must be doing something else in my code to cause the unuinstall to be cancelled, but if I do nothing but remove this prompt (whether done with Session.Message or hand-rolled), the cancel problem goes away. I'm at wit's end. Any ideas?

**Comment by jimfoye** [comment]
Ok, found my problem. I was making a PInvoke call to refresh the desktop at the start of my handler, using SHChangeNotify(). Somehow this mucks with things, perhaps because the progress window (and the parent of any message window) is managed by Explorer. I'll have to go back and figure out why I was doing this, but removing this call fixes the problem.

Thanks for the all the help.

**Comment by oleg-shilo** [comment]
Wow, that's great. I am happy you managed to address this complicated issue.

About `record[0]` vs `record[1]`. I remember testing that very sample I provided and it worked just fine. Thus the question is "was there something in the way you invoke the method or arrange the projectthat it required you to change the record index?"

I am only guessing that you probably did not use ` new Error("9000",... `. Is it right?

**Comment by jimfoye** [comment]
This is a very funky API - even by Windows Installer standards. I think you are supposed to set [1] to a number that is a lookup to an error table, and the code must be looking at it and saying "This is a string, not an int, so I'll just treat this as the error message. Oh, and I'll put a "1. " in front of it".

So I set record[0] to my message, and it doesn't prefix the text with "1. " Field 0 is also the format string, so setting record.FormatString to the text has exactly the same effect. At least, in my universe it does.

Here's all the code, but it's in F#, so it looks a little different from C#. Also, note that Record implements IDisposable, though I don't know if it's doing any real cleanup.

```
use record = new Record()
record.[0] <- "A license file was found. Do you want to ..." // rest omitted
let message = 
    let i = (int InstallMessage.User) ||| (int MessageButtons.YesNo) ||| (int MessageIcon.Question)
    InstallMessage.Parse (typeof<InstallMessage>, string i) |> unbox<InstallMessage>
// call e.Session.Message (message, record) and check result...

```
Now, the epilogue: I was using a MessageBox in a CustomAction called earlier (BeforeInstall) to check to see if Excel is running. Flushed with excitement over my victory here, I tried to replace that call with a call to Session.Message(). (Note that this earlier call did not have the "pop-under" problem, e.ManagedUIHandle works fine there as the parent for the MessageBox). However, no matter what I did, I could not get the call to return MessageResult.Cancel, it always returned MessageResult.OK. Here's the code I tried:
```

use record = new Record()
record.[0] <- "Please close running instances of Microsoft Excel so Setup can continue."
let message = 
    let i = (int InstallMessage.User) ||| (int MessageButtons.OKCancel) ||| (int MessageIcon.Warning)
    InstallMessage.Parse (typeof<InstallMessage>, string i) |> unbox<InstallMessage>
let result = e.Session.Message(message, record)
// check for MessageResult.OK or MessageResult.Cancel, but it's always MessageResult.OK

```
