### ISSUE TITLE
`Package` (all child elements of Chain) need to have the `After` field added

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1382]
When several Chained elements are being "Pulled down / http loaded" in parallel, 
then there needs to be a precedence in how the packages are installed.
This is done via the use of the `After` keyword in Wix.

e.g. an msi checks for the existence of CRT and will not install until CRT is correct
CRT is being pulled down and installed add some random point.

the `After` keyword means that the msi will not be processed until CRT has completed.

**Comment by oleg-shilo** [comment]
Done.
Will be available in the very next release

**Comment by oleg-shilo** [comment]
Done. You can import now v1.24.0.0 packages

**Comment by Smurf-IV** [comment]
Confirmed - Thanks
