### ISSUE TITLE
Package (all child elements of Chain) need to have the `SuppressSignatureVerification` field added

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1383]
This is to allow internally signed packages to not have the verification checked by the bundle, because the bundle is also signed after it has been built.

**Comment by oleg-shilo** [comment]
Done.
Will be available in the very next release

**Comment by oleg-shilo** [comment]
Done. You can import now v1.24.0.0 packages

**Comment by Smurf-IV** [comment]
Confirmed - Thanks
