### ISSUE TITLE
[Bug] When the `bootstrapper.Build` API uses the same name as the project, then misleading compile warnings are issued

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1384]
From https://github.com/oleg-shilo/wixsharp/issues/1373#issuecomment-1829941785

Therefore either 
- state why the compiler warning is issued (In VS output window) and add to documentation
- Or, Fix to allow the same name as the project as per Wix Bundle creation projects

**Comment by oleg-shilo** [comment]
Accepted. 
A warning message is generated for all output path collisions (e.g. msi, msm, bootstrapper).

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/77554103-8105-4dd4-a464-735f2adf71ad)

**Comment by Smurf-IV** [comment]
Seems like I spoke too soon.
This is still a problem.

**Comment by oleg-shilo** [comment]
I will check it. But keep in mind that there is no good way of "fixing" the problem. It is a setup definition mistake. The new release only supposed to state thus as an error in the build output and it is up to the user to either change the name of the assembly or the bootstrepper file. But they cannot be the same.

**Comment by oleg-shilo** [comment]
Does it produce this warning in your environment?
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/dff38980-fe1d-4ec9-b9e1-3e43d17566e4)

**Comment by oleg-shilo** [comment]
OK, yep, then it makes sense. That extra step is the one who fails the build.
