### ISSUE TITLE
[Request] Can you create an Example Bundle that uses Winform(s) UI please

### ISSUE THREAD

**Issue by Smurf-IV** [oleg-shilo/wixsharp#1386]
I cannot seem to get the Winform UI working so that it runs / works for a `ManagedUI` Bundle app.
V 1.23.1
Wix 3.14

I have tried to convert / use the following as an example (As it is an MIT codebase)

https://github.com/SonarQubeCommunity/sonarqube-windows-installer

But there are too many issues to compile out first.

So that I can use the theming (e.g. via https://github.com/Krypton-Suite/Standard-Toolkit dll's) to modify the look'n'feel of the dialogs

**Comment by Smurf-IV** [comment]
> Is it to build WinForm based ManagedUI for msi and the show it from the bundle?

No: A Winform replacement for the Bundle UI, as the msi's will be hidden.

**Comment by oleg-shilo** [comment]
Did you have a look at 
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/228b18ec-562f-4910-9938-4bbcd04a5714)

It is WPF but there is no UI technology coupling. You can easily modify it to be implemented in WinForm.
You only need to re-implement a single dialog MainView.

Let me know if it does not work out for you I will cook up something for you quickly.

**Comment by Smurf-IV** [comment]
Might be best to go and create that example please?
As I will not be able to get back to this until mid next week at the earliest (And that might not happen either :-( )

**Comment by oleg-shilo** [comment]
> As I will not be able to get back to this until mid next week at the earliest (And that might not happen either :-( )

I am in no hurry. I am prepared to help you when you say you need my help. But I do not want to do it "just in case" as so far there were no requests for converting that sample in WinForm version, except from you. 

Please understand, I do have the backlog of other support requests to address so I need to be wise with my time invested in this project.
