### ISSUE TITLE
How to make FileAssociation conditional?

### ISSUE THREAD

**Issue by jimfoye** [oleg-shilo/wixsharp#139]
There's no Condition property, as there is, for example, with ExeFileShortcut.

**Comment by oleg-shilo** [comment]
Correct. There is none. MSI does not support 'condition' associated with the program registration (ProgID element). Note, `FileAssociation` class gets translated into a [WiX ProgId element](http://wixtoolset.org/documentation/manual/v3/xsd/wix/progid.html) during the build. 

Though you can have a condition associated with the parent `File`.

**Comment by jimfoye** [comment]
OK, I can just do this myself, I'm already now reading/writing registry values in event handlers anyway.

Thanks.
