### ISSUE TITLE
Load event not firing in "Managed Setup" sample

### ISSUE THREAD

**Issue by DarkenSral** [oleg-shilo/wixsharp#1390]
Hi! I am trying to get the Load event to run in the "Managed Setup" sample but it doesn't seem to fire. I'm using the wix-v3-master branch, commit 2277af. I have edited the setup.cs file so that it should display a message box and interrupt the installation, but it doesn't. I'm not sure if I am making something stupid or if this is a bug?

**Comment by oleg-shilo** [comment]
I just repeated your test and i seems to work in my conditions:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/8afc191d-b87d-44e6-9ad2-639aef717a99)

Is it possible that you are expecting the msgbox at the start of GUI but not the start of the "install session". If it is the case then you need to let the setup to go through you UI sequence, which is not the true MSI session but a preparation for it and then at the start of the progress dialog.

If it is the case then have a look at this wiki. I might put it in a good perspective.
https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#event-driven-custom-actions

**Comment by oleg-shilo** [comment]
In both actually.

`Project_UIInitialized +=` will handle your condition check just before UI started in the UI session.

`Project_Loaded  +=` will handle your condition check when UI was suppressed by the user.

**Comment by DarkenSral** [comment]
Thanks Smurf-IV, the stackoverflow article did the trick! I am trying to read 64-bit registry in the ManagedUI events, i.e Project_UIInitialized and Load and as far as I understand, I cannot use MSI RegistrySearch or other fancy MSI stuff there as Managed UI handling and events happens "before" those are even processed. The example below works for reading some random test value out of 64-bit registry:

`    static void Project_UIInitialized(SetupEventArgs e)
    {
        try
        {
			if (e == null) throw new Exception("SetupEventArgs == null");
			if (e.Session == null) throw new Exception("Session == null");

            string installDir = null;
            var localKey = RegistryKey.OpenBaseKey(
                Microsoft.Win32.RegistryHive.LocalMachine,
                RegistryView.Registry64);
            localKey = localKey.OpenSubKey("SOFTWARE\\Autodesk\\AutoCAD\\R24.3\\ACAD-7100\\Install");
            
            if (localKey != null)
            {
                installDir = localKey.GetValue("INSTALLDIR").ToString();
                localKey.Close();
            }

            if (installDir == null) throw new Exception("INSTALLDIR == null");

            e.Session["INSTALLDIR"] = installDir.ToString();
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "OUCH! EXCEPTION");
        }

        var message = e.Session["INSTALLDIR"];
        MessageBox.Show(message.IsNotEmpty() ? message : "AutoCAD C3D 2024 needs to be installed!");
        if (message.IsNullOrEmpty()) e.Result = ActionResult.Failure;
    }`

**Comment by oleg-shilo** [comment]
BTW you can set bitness of your registry search directly on the object:

```c#
 new Property("SQL_BROWSER_LOCATION",
    new RegistrySearch(
        RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\services\SQLBrowser", "ImagePath", RegistrySearchType.file)
        {
            Win64 = true
        }
```
I thought you did try it because of "Platform.x64 doesn't seem to help". 
Setting the platform value cascades in the setting `RegistrySearch` bitness of `RegValueProperty` as well.
Though some scenarios may not be supported.  

Thus:
```C#
project.Platform = Platform.x64;
 ...
new RegValueProperty(
    "NETFRAMEWORK20",
    RegistryHive.LocalMachine, 
    @"Software\Microsoft\NET Framework Setup\NDP\v2.0.50727", 
    "Install", 
    "0")
```
produces

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/888d496d-651d-4c2d-bb2f-c415808df85e)

However you might be setting up `RegistrySearch` somehow differently. 

Let me know how you do it and I will extend the bitness cascading to your scenarion too.

**Comment by oleg-shilo** [comment]
I found one of the non supported scenarios that makes sense to cover. 
Changing this issue to defect.

**Comment by oleg-shilo** [comment]
Done. I actually implemented it to cover **all** scenarios now.

**Comment by oleg-shilo** [comment]
Yes it does happen before the actual msi session starts.

It seems to me that your task can be solved in a much easier way than it seems.

Let's recognize that you may have two types if install: with and without UI. User may suppress UI even if you do not anticipate it.

For "With UI" scenario place your C# registry reading routine in your earliest event that is `UIInitialized` event.
For "Without UI" scenario place your C# reading routine in your earliest event that is `Loaded` event. 

If the target system does not meet the prerequisite conditions one of these events will detect it and prevents further installation.

If the target system does meet the prerequisite conditions then both events will do the check and happily pass the execution flow further to the chain.

This is the link to the wiki page that helps understanding how it works: https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#event-driven-custom-actions

**Comment by oleg-shilo** [comment]
I have captured the essence of our discussion on the Tips'n'Trics page: https://github.com/oleg-shilo/wixsharp/wiki/Tips'n'Tricks#checking-prerequisite-conditions-as-soon-as-possible

**Comment by DarkenSral** [comment]
I have a follow-up question on the above, regarding features and feature conditions. Like install conditions they tend to depend on some AppSearch property being set, defining if the feature should be checked/unchecked/visible/invisible. But since AppSearch isn't run before the UI, does this also mean that I have to "roll my own" appsearch in C# code and set the appropriate session properties in UIInitialized and Loaded events?

**Comment by oleg-shilo** [comment]
yep, this it means that. 

For straight forward searches like presense of file you can use fully rely on .NET base classes (`Directory.GetFiles(...)`).

For MSI based searches you can use WixSharp `MsiParser`:

```C#
using (var msi = new MsiParser(MsiFile))
{
    Console.WriteLine(msi.IsInstalled());
    Console.WriteLine(msi.GetProductName();
    Console.WriteLine(msi.GetProductVersion();
    Console.WriteLine($"The product is {(IsCurrentlyInstalled ? "" : "NOT ")}INSTALLED");
}
```
