### ISSUE TITLE
[Request] CLR managed UI is missing "VerifyReadyDlg"

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1391]
Standard WIX UI includes a "VerifyReadyDlg" as the last dialog shown before executing the installer.

The "Next" button is renamed "Install" (with UAC shield, if appropriate) and it prompts the user to being the install or go back to change settings.

Using the managed UI template in Visual Studio, there's no "verify ready" dialog. So we click through the installer "next", "next", "next" and suddenly it's installing without final confirmation. When clicking "Next" the final time, the user is probably expecting another configuration dialog, not for the install to begin.

**Comment by oleg-shilo** [comment]
In this case it is deliberate. 
WixSharp is not just C# binding to WiX, it's an attempt to address an obvious awkwardness of developer and user (UX) experiences.

The removal of VerifyReadyDialog is the result of the analysis of the usual user experience offered by MSI. This dialog was introduced 24 years ago (first Windows Installer release) when disc capacity was limited and it allowed user asses the storage cost of the installation. Today it hardly plays any useful role.

A provocative question? 😄 
"When was the last time when you looked at the VerifyReadyDialog information and it made you go to the previous screen to do something different?"

Saying that, if you really need to provide this dialog, just create the VS project from the Custom UI template. This will give you the source code of all dialogs. Make a copy of one of then, make it look and behave like VerifyReadyDialog and add it to the UI sequence. That's it.

**Comment by thenextman** [comment]
Ok, thanks! I understand it's deliberate although I don't agree with the reasoning.

That said - like you state, it's easy enough to recreate this dialog and that's what I've done.
