### ISSUE TITLE
Is it possible to inherit wxl files using managed UI?

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1392]
I have an existing Wix3 setup that's localized using wxl files. I use one of the WiX default UI flows, customized by adding several additional dialogs.

I add wxl files for the languages I support, containing the custom strings used in my UI and etc. This works well: the default WiX UI is localized using the [Wix3 wxl files](https://github.com/wixtoolset/UI.wixext/blob/master/src/wixlib/WixUI_en-us.wxl), and my custom UI and additions are localized using my own wxl files.

How to achieve the same using the WixSharp managed UI?

The managed UI project template provides a recreation of some of the default WiX dialogs; the localization resource strings and values match what's contained in the Wix3 wxl files - is that what it's using "under the hood"?

I've noticed two things:

- If I create a new managed UI project and simply change `product.Language = "fr-FR"`; I still get an English language MSI which is not what I'd expect.
- More importantly (and this is what I'd like to understand); I'm adding my own dialogs that need their localization. For simplicity, let's assume I'm still producing a single language MSI. I create a wxl and configure things in WixSharp:

```
project.Language = "en-US";
project.LocalizationFile = "MyLocalization_en-US.wxl";
```

I add my custom localizations to the wxl and they show up in my setup UI. _But_, __importantly__, all the "default" localizations are now lost! For example, instead of "Next" I see "WixUINext" in the product.

Of course I can workaround this by taking the default WiX3 localizations and copy-pasting them into my own .wxl file, but this seems like a burden. Is there a way to make this work like WiX3 (where language files are "additive" rather than "replace")?

**Comment by oleg-shilo** [comment]
The current API design is that WixSharp compiler always expects the user to supply wxl file for ManagedUI if the language is custom. 

Though there is no good reason for not utilizing the localization file in the WiX SDK folder (if it can be found).
This feature will be available in the next release.

**Comment by thenextman** [comment]
@oleg-shilo Thanks for fixing this. It works for me. I found a problem using my existing wxl files but I'll open a new issue for that.
