### ISSUE TITLE
manuell imported Regkey strange Behaviour

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1395]
Morning, i faced strange Behaviour with manuell Imported RegKey File. AFAIK if msi has regkey to install it, this will be also updated during upgrade. BUT if i brought my own Regkey File , mykey.reg, to import, after upgrade it disapeard from registry. Is there posiblity add once regkey ? i want to change behaviour of programm based on this regkey, but this should NOT be part of Installation. 

Or how do i import only once Regkey 🤔🤔🤔. 

Best regards, Torchok.

**Comment by oleg-shilo** [comment]
I have checked and importing reg file does not introduce any install condition of any sort. It emmits the same WXS as if youy added regvalue manually (without import).

Have a lookat you generated wxs. Maybe it has a clue.
