### ISSUE TITLE
How to add ExePackage with 3.5 GB TAR file into Bundle?

### ISSUE THREAD

**Issue by Xyroid** [oleg-shilo/wixsharp#1399]
I am creating a WiX installer as a `Bundle` project. The bundle has 5 packages (exe and msi). 4 out of 5 are third party apps and the forth one is a Windows Form app. It takes input from the user and it is passed to PowerShell scripts. Those PowerShell scripts also require a TAR file as an input. The size of TAR file is 3.5 GB. The TAR will be part of WinForm app.

First I tried to add the TAR file into WinForm app and then build the installer project but it resulted into arithmetic overflow. Then removed the TAR file and PS scripts from WinForm app and added the TAR file and PowerShell scripts as `Payloads` to `ExePackage`. It didn't work and got the following error. Tried splitting TAR files into multiple parts, but same error.

> light.exe : error LGHT0306: An error (E_FAIL) was returned while finalizing a CAB file. This most commonly happens when creating a CAB file with more than 65535 files in it. Either reduce the number of files in your installation package or split your installation package's files into more than one CAB file using the Media element.

Then tried to keep TAR file outside of installer but in same directory, where the installer is. This didn't work because none of these built-in variables gave me the path from where the installer was launched, `CURRENTDIR`, `SOURCEFILEDIR`, `OriginalDatabase`, `WixBundleOriginalSourceFolder`, `WixBundleSourceProcessFolder`. I passed these variables as a command argument to WinForm app.

Then I referred [this issue](https://github.com/oleg-shilo/wixsharp/issues/1217). Though it is not related bundle but I tried to replicate it. This is creating a CAB file only if I exclude the TAR file. I am unable to create multiple CAB files which has the TAR files in part.

So basically what I am missing to create an installer which installs few third party apps and then invokes a PS script via a WinForm app, which has a dependency on a huge TAR file? The non-working code is give below.

```csharp
static void Main() 
{
	var bootstrapper = new Bundle("MyBundle",
		new ExePackage(@"Prerequisites\pre1.exe"),
		new ExePackage(@"Prerequisites\pre2.exe"),
		new MsiPackage(@"Prerequisites\pre3.msi"),
		new ExePackage(@"Prerequisites\pre4.exe")
	);

	bootstrapper.WixSourceGenerated += Bootstrapper_WixSourceGenerated;

	bootstrapper.Build("installer.exe");
}

private static void Bootstrapper_WixSourceGenerated(XDocument document)
{
	document.Select("Wix/Bundle/Chain")
			.AddElement("PackageGroupRef", "Id=TarFile");

	var dependencies = new List<string>
	{
		"Assets\\Common\\PV.psm1",
		"Assets\\PV\\PV.ps1",
		"Assets\\PV\\RPV.ps1",
		"Assets\\PV\\HUGE.tar.gz"	// removing this creates a CAB file but I want to include it
	};

	var payloads = new List<Payload>();
	foreach (var dep in dependencies)
	{
		payloads.Add(new Payload { Name = dep, SourceFile = dep });
	}

	var exePackage = new ExePackage(@"Prerequisites\CustomWinForm.App.exe")
	{
		Name = "CustomWinForm.App.exe",
		Payloads = payloads.ToArray()
	};

	var exeXml = exePackage.ToXml();
	
	var res = document.Select("Wix")
			.AddElement("Fragment")
			.AddElement("PackageGroup", "Id=TarFile")
			.AddElement("ExePackage", "SourceFile=Prerequisites\\CustomWinForm.App.exe; Name=CustomWinForm.App.exe; InstallCommand=[OriginalDatabase]");

	foreach (var e in exeXml.Elements().ToList())
	{
		res.AddElement(e);
	}
	
	document.Select("Wix/Fragment")
			.AddElement("Container", "Id=TarFile; Name=cab0.cab")
			.AddElement("PackageGroupRef", "Id=TarFile");
}
```

**Comment by Torchok19081986** [comment]
Hiho, i think that you need Wix V4. there is older Post by Wix Team. https://github.com/wixtoolset/issues/issues/6521
Or you can try webinstaller , where you can download payload during install. 

best regards, Torchok.
