### ISSUE TITLE
How to install a desktop shortcut for all users?

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/wixsharp#140]
I know about the `%Desktop%` location to install an `ExeFileShortcut` into the current user's Desktop folder.

What I simply cannot find out is how to install it to the "All Users Desktop".

**My question:**

Any hint on how/whether this is possible?

**Comment by UweKeim** [comment]
I've just found `InstallScope.perMachine`. Maybe this ins enough to set once per project?

**Comment by oleg-shilo** [comment]
Might be the solution. After all this is the purpose of "All Users Desktop" - to be a "perMachine" scope. Never tried it though.
