### ISSUE TITLE
Can't mark directory as permanent

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1401]
I want to create a directory that exists even after uninstall (I know this approach is debatable, but I read it should be possible in WixSharp by searching similar issues and of course, it's trivial in WiX by just omitting the `RemoveFolder` tag)

However, this:

```
new Dir("%CommonAppDataFolder%")
{ 
    Dirs = new Dir[]
    {
        new Dir("Vendor")
        {
            Dirs = new []
            {
                new Dir("Program").SetComponentPermanent(true)
            }
        }
    }
},
```

Doesn't work. At compile time I get:

>Unhandled Exception: System.ApplicationException: Cannot resolve custom attribute definition:Component:Permanent=yes
> Note, some Wix elements may not be contained by 'Component' elements (e.g. 'CloseApplication'). Thus attempt to set parent ?> component attribute will always fail.

Should this work? Or is my only option to post-process the wsx file and remove the "RemoveFolder" element?

**Comment by oleg-shilo** [comment]
It is really a question of achieving it with WiX.
`SetComponentPermanent` simply adds the attribute `Permanent` to the component element. It works for files but it does not for dirs as they are normally not nested by a component. That's why `SetComponentPermanent` fails.

So what can you do? You can follow your own advice  and remove the "RemoveFolder" element:

```c#
project.WixSourceGenerated += (doc) =>
            doc.FindAll("RemoveFolder")
                .Single(x=>x.HasAttribute("Id", "Program"))
                .Remove();
```

Yep, it's not very elegant, arguably adequate.

technically speaking, you can also try to wrap your dirt in the artificial `Component` element and stamp it with a `Permanent` attribute. But arguably it is even less elegant. TRickier to do and.... I just cannot advise anyone to play with components.

This business is so messy in MSI/WiX that I cannot see it as a safe option.

=====================

Just to illustrate my point...
I found my old comments while looking for the solution to your problem: 

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/2320b558-f555-400f-bd7f-9278a7cbccbb)

This is how messy it is

**Comment by oleg-shilo** [comment]
Just to make users life a little easier I have implemented an extension for that:

```c#
project.SuppressRemovingFolderFor("Program");
```

BTW, you do not have to wait for the next release. If you add the code below to your codebase you can start using this extension before I make the release:

```C#
static public Project SuppressRemovingFolderFor(this Project project, string directoryId)
    => project.WixSourceGenerated += (doc) =>
               doc.FindAll("RemoveFolder")
                  .Single(x => x.HasAttribute("Id", directoryId))
                  .Remove();
```

**Comment by thenextman** [comment]
Thanks for the workaround, but it doesn't seem to work for me (although the issue seems to be the MSI rather than WixSharp itself)

Rather than troubleshoot this, I think it's actually better if I just create the directory using an `ElevatedManagedAction`.

In case you're interested, this is what I get:

```
// Directory setup
new Dir("%CommonAppDataFolder%", new Dir("Vendor", new Dir("Product"))),

// Not shown - post process remove "remove folder" element from Vendor and Product components
```

Generated .wxs:

```
<Directory Id="CommonAppDataFolder" Name="CommonAppDataFolder">
  <Directory Id="Vendor.1" Name="Vendor">
    <Directory Id="Product" Name="Product">

      <Component Id="Component.Product.EmptyDirectory" Guid="db3903d6-c451-4393-bd80-eb9fd9ec0be0" KeyPath="yes" Win64="yes">
        <CreateFolder />
      </Component>

    </Directory>

    <Component Id="Vendor.1" Guid="db3903d6-c451-4393-bd80-eb9f911ab598" KeyPath="yes" Win64="yes">
      <CreateFolder />
    </Component>

  </Directory>
</Directory>
```

But, the folders are removed on uninstall. As shown by the MSI log:

>MSI (s) (00:94) [19:56:28:321]: Executing op: FolderRemove(Folder=C:\ProgramData\Vendor\Product\,Foreign=0)
>MSI (s) (00:94) [19:56:28:321]: Note: 1: 2318 2:  
>MSI (s) (00:94) [19:56:28:323]: Note: 1: 2318 2:  
>MSI (s) (00:94) [19:56:28:324]: Executing op: FolderRemove(Folder=C:\ProgramData\Vendor\,Foreign=0)

For comparison, my working WiX project looks like this:

```
<Directory Id="CommonAppDataFolder">
        <Directory Id="CommonDevolutionsFolder" Name="Vendor">
          <Directory Id="ProgramDataFolder" Name="Product">
          </Directory>
        </Directory>
      </Directory>
    </Directory>
    <DirectoryRef Id="ProgramDataFolder">
      <Component Id="C.CommonAppDataFolder" Guid="dc6b6f37-78d2-4f0a-9464-d1f63ef64fab" Permanent="yes">
        <CreateFolder>
          <PermissionEx Sddl="$(var.ProgramDataSddl)" />
        </CreateFolder>
      </Component>
    </DirectoryRef>
```

Like I said, I'll likely just us a custom action instead. WixSharp makes it so easy :)

**Comment by oleg-shilo** [comment]
Agree
If you move to the CA then the easiest way to do this is from the "AfterInstall" event. It's already elevated and the even arg has the install dir and the setup type (install/uninstall/upgrade)
