### ISSUE TITLE
UtilRegistrySearch has Win64 instead of Bitness

### ISSUE THREAD

**Issue by NJullienSweet** [oleg-shilo/wixsharp#1402]
In the `WixSharp_wix4` package, `WixSharp.Bootstrapper.UtilRegistrySearch` only has the `Win64` boolean member from WiX v3 which writes out `yes` or `no`. In WiX v4, it was replaced with `Bitness` and values `default`, `always64` or `always32`.

![image](https://github.com/oleg-shilo/wixsharp/assets/139108357/d348fa0f-3027-4d97-a336-1e2c6afeb809)

![image](https://github.com/oleg-shilo/wixsharp/assets/139108357/196b65f5-2320-45e7-bb5f-c4d505d5303f)

**Comment by oleg-shilo** [comment]
Thank you. Will update the implementation. 
Until the patch is ready you can use this work around:

```C#
new UtilRegistrySearch
{
    Root = RegistryHive.LocalMachine,
    . . .  
    // Win64 = true,
    AttributesDefinition = "Bitness=always64",
    . . .
},
```

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release.

Please note that the current WixSharp API is not changed. Simply the `Win64` field will trigger correct attribute usage.
