### ISSUE TITLE
Filtering files in wildcard directory does not seem to work

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1403]
I'm installing a PowerShell module; there are several directories and files that I'd like to just include with a wildcard syntax (which, incidentally, is _so_ much easier in WixSharp than Wix - kudos!).

However, the source directory contains a directory I'd like to _exclude_ (in this case, `src`).

So, I wildcard my files like this:

```
Dirs = new Dir[]
{
    new Dir("PowerShell", 
        new Dir("Modules", 
            new Dir("Product", 
                new Files(@"{path-to-directory\*.*",  f => !f.Contains("src")))))
}
```

However, the "src" directory is still added to the wxs.

Even if I modify my code to add an explicit function for the predicate, e.g.

```
f => {
    if (f.Contains("src"))
    {
        return false;
    }

    return true;
}
```

And stop in the debugger, I can see it returning `false` for the files and subdirectories in that path. But they are still present in the .wxs after building.

**Comment by Torchok19081986** [comment]
morning, AFAIK wildcard works with File Extensions, and not by directory. Something like f => !f.Contains("*.exe") and so on, works  perfectly. For exclude Dirs , you can try to use wixsource_generated event and check the output wxs file. That can gives you some info, Only @oleg-shilo  can provide better info.

**Comment by thenextman** [comment]
@Torchok19081986 Thanks for the information

It doesn't make sense, though; because the predicate is called for every file with the (relative) path to the file. So checking if it contains ".exe" is not different to checking if it contains a directory name ("src"). And wildcard syntax surely won't work in the predicate ("*.exe").

It's not really a big deal since I can just add the folders I want separately, but it would be nice if this worked (it seems like it doesn't, or at least - if it does some extra "magic" inside it breaks expectations of how the predicate should work).

**Comment by Torchok19081986** [comment]
maybe. Sry, i didnt has any scneario to craete installer with exclude dirs. There is Sample in ..\Source\src\WixSharp.Samples\Wix# samples\WildCard Files Sample of Wildcard for File. 
Interesting line is 

```csharp

 project.AllFiles
               .Where(file => file.Name.EndsWith(".dll"))
```
,  you can try for AllDirs, if it exists and do same for Dirs. 

Best Regards, Torchok.

**Comment by oleg-shilo** [comment]
You are in full control inside of your predicate. Thus if the path hs `src` fragment then you definitely can detect it and reject the file.

I suspect that you might be receiving the relative path and the `src` subfolder is not there because it is not in the path string. The easiest way to test it is debug your code. Alternatively, you can verify this by if passing the absolute path. I reckon it will address the issue.

I specifically added the test case for your scenario: https://github.com/oleg-shilo/wixsharp/commit/3b01f93ae7263ed6ba80433e96470819447c628e

**Comment by thenextman** [comment]
Aha, ok - indeed I had stepped with the debugger and checked I was returning `false` from the predicate at the right time.

However, after a closer look - the files are indeed _not_ added to the .wxs, only the empty directories are created.

I understand the way this works; since I don't want the empty directories I'll just add individual dirs instead of building a wildcard of the whole tree.

Thanks for the help!
