### ISSUE TITLE
Can't make `LookupInstalledVersion` work

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1405]
I recognize that this is probably an error on my side, but I'm hoping to get some guidance on where I'm going wrong.

I wish to prevent downgrades.

I have my project configured thus:

```
internal static Guid UPGRADE_CODE = new Guid("{my-guid-that-does-not-change");

ManagedProject project = new (Includes.PRODUCT_NAME)
{
    UpgradeCode = UPGRADE_CODE,
    Version = new Version(23, 12, 0),
    //etc
};
project.MajorUpgrade = new ()
{
    AllowDowngrades = false,
    AllowSameVersionUpgrades = true,
    DowngradeErrorMessage = "Another version of this product is already installed.",
    Schedule = UpgradeSchedule.afterInstallInitialize,
};
```

So far, so good: if I install this version (23.12.0) and then try to install 23.10.0 afterwards, the execution prevents the downgrade.

_But_ I would like to check for a downgrade _before_ the user presses "Install". Looking at existing issues, I implemented the following;

```
project.UIInitialized += Project_UIInitialized;
// ...

private static void Project_UIInitialized(SetupEventArgs e)
{
    Version installedVersion = e.Session.LookupInstalledVersion();
    Version thisVersion = e.Session.QueryProductVersion();
    MessageBox.Show($"{installedVersion} {thisVersion}");
}
```

But `e.Session.LookupInstalledVersion` is always `null`.

Where am I going wrong?

**Comment by Torchok19081986** [comment]
morning, i had same trouble in managedProject. You can try AppSearch get Installedversion by your ProductId, which is your GUID and awalys same. MSI get it by Exection. Only one small Problem : i could not cancel Execution of MSI if installedVersion and thisVersion different or same. Somehow MSI always execute it .

**Comment by thenextman** [comment]
Thanks @Torchok19081986. I have figured out what's going on here.

`LookupInstalledVersion` eventually calls `AppSearch.GetRelatedProducts(upgadeCode)` and then takes `FirstOrDefault` from the result.

For some reason, on my machine, `GetRelatedProducts` (which is just calling the native `MsiEnumRelatedProducts`) returns multiple related products - actually three, the first two not having version or name information, and the third is my already installed product. I don't know why my system is this way (perhaps registry corruption) but it seems more reliable to manually call `AppSearch. GetRelatedProducts` and iterate the results to find if you are already installed.

One other trick is that `GetRelatedProducts` expects the upgrade code to be parenthesized; so you need to surround the argument with curly braces (e.g. `AppSearch.GetRelatedProducts("{" + upgradeCode.ToString() + "}"`). Otherwise it won't work.

Happy holidays!

**Comment by thenextman** [comment]
This works for me:

```
Version thisVersion = e.Session.QueryProductVersion(); 
Version installedVersion = 
    AppSearch.GetRelatedProducts("{" + Includes.UPGRADE_CODE + "}")
        .Where(productCode => AppSearch.GetProductName(productCode)?.Equals(Includes.PRODUCT_NAME) ?? false)
        .Select(AppSearch.GetProductVersion)
        .FirstOrDefault();

if (thisVersion <= installedVersion)
{
    MessageBox.Show($"Later version of this product is already installed ({installedVersion})");

    e.ManagedUI.Shell.ErrorDetected = true;
    e.Result = ActionResult.UserExit;
}
```

**Comment by oleg-shilo** [comment]
Hey Richard, this is a very valuable finding.

I am reopening this issue and requalifying it into an enhancement.
I think your improved AppSearch algorithm should to be implemented in the WixSharp core functionality.
