### ISSUE TITLE
Default UI header not transparant

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#141]
We are switching from Wix to Wixsharp. In Wix, the background of text on the header is transparant. In WixSharp ui components it is gray. See picture.

IMHO the visual designer of the header image should ensure that black text on it is readable, so that the text clearly readable. 

I would prefer the background to be transparant as in WiX.

![image](https://user-images.githubusercontent.com/7579444/29818231-a10bc53e-8cbb-11e7-91c8-c5872dd680e4.png)

**Comment by oleg-shilo** [comment]
Done. 
Until the release is available publicly please use "Custom UI Sequence" VS template to modify the label background property.

**Comment by monty241** [comment]
Thank you.
