### ISSUE TITLE
Passing argument to internal exe file being used

### ISSUE THREAD

**Issue by MANGLARAM** [oleg-shilo/wixsharp#1410]
Hi
I'm creating a msi installer. What i want is i use build file of go convert it into exe and and pass it as a file in program.cs main file what i want is when i run this wixsharp installer the exe that i placed in file method should run with the arguments i want . So what i want is how to pass those arguments to the exe that i want to run internally

program.cs part where i add the exe.
           var project = new ManagedProject("BasWizard",
                             new Dir(@"%ProgramFiles%\Aquilai\Bas",
                                 new File(".\\BasExe\\basagent.exe")));
                               
my arguments to the basagent.exe are like - some ip, group, key, id     

==========================================================

secondly there is a issue i am facing with the height and width of installer i specify my props in xaml according to my requirment but when build and run it shortens them , i dunno why??

**Comment by oleg-shilo** [comment]
Fo running the installed exe file you can use `Project.AfterInstall += . . .` even. It runs elevated and you can get the session type (install vs uninstall) from the event args. You can also use even args to get the install directory that was used for the installation.

**Comment by MANGLARAM** [comment]
what i have is a customDialog that i created and i defined installation path in the product.cs main file but those installation path are not getting created when i run the msi

**Comment by oleg-shilo** [comment]
I am not sure what exactly is happening during your msi build as your build process is not clear to me.

I suggest you look at the generated wxs file and see if the installdir gets defined correctly.
