### ISSUE TITLE
How can I set install path for a particular feature in Custom UI dialog and make managed project to take that while installing

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1413]
### Discussed in https://github.com/oleg-shilo/wixsharp/discussions/1412

<div type='discussions-op-text'>

<sup>Originally posted by **abskulkarni** January  1, 2024</sup>
Hi
I am using WixSharp to build msi for our product.
I have a custom UI dialog where I am giving facility to user to change installation directory for a feature. (I am having multiple features those may have different installation directories/paths)
How can I make managed project to take this user defined path while installing that feature?</div>

**Comment by oleg-shilo** [comment]
I am afraid your scenario is not supported by MSI. It does not allow having various install dirs per feature.

It's one install dir for an msi.

**Comment by Torchok19081986** [comment]
Hallo, i come across following link in wix toolset V3. https://wixtoolset.org/docs/v3/xsd/wix/feature/
"... 
ConfigurableDirectory | String | Specify the Id of a Directory that can be configured by the user at installation time. This identifier must be a public property and therefore completely uppercase.
"

**Comment by oleg-shilo** [comment]
This does not tell me that "change installation directory for a feature" is possible. This is my understanding that the ConfigurableDirectory is the directory that is one of your predefined dirs. Though the documentation (that link you provided) is shockingly bad. It does not say what it the purpose of this attribute or when and how to use it.

However, if you feel that it is what you are looking for then you can use it. Just set this attribute to whatever you want. It's available in both WiX3 and WiX4 streams.

**Comment by Torchok19081986** [comment]
morning, @oleg-shilo was right. MSI doesnt allow to change Path of Features. I think only way to achieve that is , build custom BA Installer with custom Feature selection dialog where each feature is own msi File triggert one after another. 
Like install main files, go to feature selection and so on. Never tried it , looks complcated. 😐😐😐
