### ISSUE TITLE
Custom UI- Installer is no longer responding

### ISSUE THREAD

**Issue by NishantThakkar** [oleg-shilo/wixsharp#1414]
I am using Custom UI wix# template which has 2 custom InstallDialogs.
On the 1st dialog am capturing some parameters in 2nd screen have custom code of creating VM on Hyper-V.
Have implemented custom progress bar based on VM creation status, and when my VM gets created, I complete my progress bar.
I have used **BackgroundWorker** and **ProgressBar** together.  

Issue 1# I am keeping 2nd dialog idle for 20 mins, after that   it displays message: "**Installer is no longer responding**"

Issue 2# The installer is also not displaying in **Control Panel.**

**Code snippet:**

> Program.cs

```
project.ManagedUI.InstallDialogs.Add<VMConfigurationDialog>()
                                            .Add<CustomProgressDialog>();
```

**Below is the screenshot of the message:**

![image](https://github.com/oleg-shilo/wixsharp/assets/5793534/788846af-dcf3-45d8-95aa-959cf8f7b1bc)

**Comment by oleg-shilo** [comment]
Your installer hangs. Probably your installation is blocked somehow.

YOu have a better chances to troubleshoot it if you debug your "custom code"

**Comment by NishantThakkar** [comment]
> Your installer hangs. Probably your installation is blocked somehow.
> 
> YOu have a better chances to troubleshoot it if you debug your "custom code"

Installer is not getting hanged, as I can seamlessly move screen, so UI thread is completely free. Even code gets executed properly. But after that I am keeping my screen idle for 20 mins, there I am getting **"Installer is no longer responding"** .

**Comment by NishantThakkar** [comment]
**Please find more logs after executing msi with log file:**

> MSI (c) (70:48) [16:52:37:266]: EEUI - Running MsiEmbeddedUI code
> MSI (c) (70:60) [16:52:37:375]: Cloaking enabled.
> MSI (c) (70:60) [16:52:37:375]: Attempting to enable all disabled privileges before calling Install on Server
> MSI (c) (70:60) [16:52:37:375]: Connected to service for CA interface.
> SFXCA: Extracting embedded UI to temporary directory: C:\Users\admin\AppData\Local\Temp\MSI16331
> SFXCA: Binding to CLR version v4.0.30319
> MSI (c) (70!A0) [16:52:38:344]: PROPERTY CHANGE: Adding WIXSHARP_MANAGED_UI property. Its value is 'WixSharp.UI, Version=1.19.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2'.
> MSI (c) (70!A0) [16:52:45:298]: PROPERTY CHANGE: Adding WIXSHARP_MANAGED_UI_HANDLE property. Its value is '3737070'.
> **MSI (c) (70!A0) [16:52:57:079]: PROPERTY CHANGE: Adding WIXSHARP_RUNTIME_DATA property. Its value is 'WIXSHARP_MANAGED_UI_HANDLE=3737070'.**
> **MSI (c) (70:7C) [17:24:08:245]: RunEngine wait timed out**
> Installer is no longer responding.
> MSI (c) (70:7C) [17:24:08:266]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg
> 
> MSI (c) (70:7C) [17:24:39:532]: fFatalExit=true
> === Verbose logging stopped: 03-01-2024  17:24:39 ===

**Comment by oleg-shilo** [comment]
> Installer is not getting hanged, as I can seamlessly move screen

It does not mean it's msi is responsive. MSI session is run by a system service process `msiexec.exe`. 
UI is run as another external desktop process `msiexec.exe`. So your UI is responsive. But your actual session most likely is not.

That `Installer is no longer responding` message is displayed by that system service process.

As a troubleshooting step, I would disable that "custom code" and see how it changes the behaviour.
