### ISSUE TITLE
Detection Win OS on  Wix V4 in WixSharp for Win 11

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1416]
Morning, i have a trouble to detect win11 on WPF Installer. In Wix3 , until Win10, i could detect Win 10 OS , works great. but since win11 this OS Detection doenst work by Environment Class. My Installer doesnt look like win11 standard with rounded corner. IS there any build-in WixSharp or Wix Toolset V4 to detect OS ? AFAIK i can detect in CA, but currently CA doesnt return Win 11 OS Build number, sadly. 

```csharp

Environment.OSVersion.Version.Build >= 22000;

```
I tried this in WIn11 VM client out, it returns Win 10 or greater , bur not win11. 

update info : i found in stackoverflow https://stackoverflow.com/questions/33817452/wix-toolset-custom-action-command-doesnt-correctly-detect-windows-10-version, how do i set it Wix# ?

**Comment by oleg-shilo** [comment]
The problem you are facing is outside of WixSharp domain. 
Though WixSharp can make it easier to overcome the problem you are facing - "CLR not detecting OS version correctly".

The following method will return you the OS version correctly:

```C#
        public static string GetWinVer()
        {
            var version = "";
            string batchFile = System.IO.Path.GetTempFileName().DeleteIfExists();
            batchFile += ".cmd";
            try
            {
                System.IO.File.WriteAllText(batchFile, "ver");
                var ver = new ExternalTool
                {
                    EchoOn = false,
                    ExePath = batchFile
                }.ConsoleRun(x => version = x); // capture the last line

                // Microsoft Windows [Version 10.0.22621.2861]
                return version.Split(' ').Last().Trim(']');
            }
            finally
            {
                batchFile.DeleteIfExists();
            }
        }
```
