### ISSUE TITLE
How to run rollback at After_Install  at CANCEL 

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1417]
Hi Oleg, hope you are doing well.
Got a  question, I'd like to run a command line at rollback, for example, as user click on CANCEL.
The code I used:
```
 private void OnAfterInstall(SetupEventArgs e)
{
       if (e.Result != 0)
            {
                _rollback?.RunRollback();
            }
}

```
Those line are not being called as I click on CANCEL. (progress bar show it is in state of starting services).
I know that because i'm using logging, and I don't get the log there. seems like, it's not being called at all.
How can I run the code above at rollback?
Thanks!

**Comment by Torchok19081986** [comment]
hiho, AFAIK you dont have to do it manually. Just try set ActionResult to Failure. 
best regards, Torchok.

**Comment by RachelXGanon** [comment]
Hi @Torchok19081986  Thanks for your response. 
I'd like to run a command line at CANCEL. 
Trying to have it in the AFTER_INSTALL didn't help.
I'm not sure I understand your suggestion.
