### ISSUE TITLE
Height and width issue of dialog 

### ISSUE THREAD

**Issue by MANGLARAM** [oleg-shilo/wixsharp#1418]
i have a issue regarding height and width of dialog UI , i am talking about outer box here am i am not able to set them what i wish to, it is rendering at a fixed ratio whatever i input in XAML

**Comment by oleg-shilo** [comment]
This will do what you need:

```c#
project.UIInitialized += (SetupEventArgs e) =>
{
    e.ManagedUI.SetSize(800, 800);
};
```
