### ISSUE TITLE
Custom Action assembly file %this%.CA.dll generated by sample DTF (Managed CA) and others

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#142]
On WixSharp 1.4.7.2, cs-script through choco 3.27.5.0.

Adding custom actions to a project, we had continuing issues.  Striking was that a file %this%.CA.dll was generated. 

Using WIX only and a hand-coded xx.ca.dll, the custom actions run fine.

Tried this sample:
https://github.com/oleg-shilo/wixsharp/blob/c766ea466fe7cfa62eb7df97b8e1f5d44609ed9c/Source/src/WixSharp.Samples/Wix%23%20Samples/DTF%20(ManagedCA)/Different%20Scenarios/Embedded/setup.cs

and added:

        project.PreserveTempFiles = true;

This also results in a DLL in the output with the name: %this%.CA.dll

I've looked in the source code of WixSharp and I think %this% should have been expanded to the assembly name during creation of the wix project. The sample (and my own project) contain this in the temporary wxs file:

`    <Binary Id="Action1_MyAction_File" SourceFile="%this%.CA.dll" />
`
I think the following code should be different:

```
        string ResolvePath(string path)
        {
            if (path == "%this%")
            {
                var callingAssembly = new StackTrace().GetFrames()
                                                      .Select(f => f.GetMethod().DeclaringType.Assembly)
                                                      .First(a => a != this.GetType().Assembly)
                                                      .Location;
                return callingAssembly;
            }
            else
                return path;
        }

```
since a path such as "%path%.ca.dll" is not matching the need. Better would be: replace all occurrences of %this% by the assembly name.

In few other places there are also references to %this% I don't understand. 

Logging contains:

```
1>  Building MSI
1>  "C:\ws\dir\dotnet\solutions\20-Acme Support Assistant\bin\Acme.SupportAssistant.Setup.exe" "/MSBUILD:Acme.SupportAssistant.Setup"
1>  Searching for custom action entry points in Acme.SupportAssistant.Setup.exe
1>      Loaded dependent assembly: C:\Program Files (x86)\WiX Toolset v3.11\sdk\Microsoft.Deployment.WindowsInstaller.dll
1>      MyAction=Acme.SupportAssistant.Setup!CustomActions.MyAction
1>  Searching for an embedded UI class in Acme.SupportAssistant.Setup.exe
1>  Modifying SfxCA.dll stub
1>  Copying file version info from C:\ws\dir\dotnet\Acme\Acme.SupportAssistant.Setup\Acme.SupportAssistant.Setup.exe to C:\ws\dir\dotnet\Acme\Acme.SupportAssistant.Setup\%this%.CA.dll
1>  Packaging files
1>      Acme.SupportAssistant.Setup.exe
1>      CustomAction.config
1>      Acme.SupportAssistant.Setup.pdb
1>      WixSharp.dll
1>      Microsoft.Deployment.WindowsInstaller.dll
1>  MakeSfxCA finished: C:\ws\dir\dotnet\Acme\Acme.SupportAssistant.Setup\%this%.CA.dll
1>  Wix# support for EmptyDirectories is automatically enabled
```

I will switch back to a separate assembly for the custom actions.

**Comment by monty241** [comment]
Using a separate CA assembly it works, but remember to specify path and extension:

```
var m = new ManagedAction(new Id("NOP"), CustomActions.NOPCustomAction, Path.Combine(this.SolutionFolder, "bin", "Acme.Wix.CA.dll")
                                    , Return.check
                                    ,  When.After
                                    ,  Step.InstallInitialize
                                    , Condition.NOT_Installed);

```

**Comment by oleg-shilo** [comment]
I am off and will not be able to look at the problem for the next 1-2 weeks. 

Just from the top of my head the major difference between the current cscs.exe and the one that is distributed with Wix# is that the assemblies are now loaded from memory thus their location at runtime may no longer be discovered.  This improves CS-Script user experience but it may also compromise advanced reflection based scenarios (e.g. Wix#). 

Would you please do a simple experiment. Disable in-memory assembly loading In your build script. You can do this by placing `//css_args -inmem:0` at the top of the script.

**Comment by monty241** [comment]
@oleg-shilo Hello Oleg, thanks for your feedback. Sure, no problem. But at the top of what build script (file name or so)? I am using some C# code that generates with your assembly the wxs and then compiles it.

**Comment by oleg-shilo** [comment]
A build script is the file that cs-script is executing. Thus in all samples it is `setup.cs` file.
