### ISSUE TITLE
Image loading issue and msi top strip naming issue

### ISSUE THREAD

**Issue by MANGLARAM** [oleg-shilo/wixsharp#1422]
I have a image that i moved to installation path on run but that image is not getting reflected on my custom UI . How can i achieve that and how can i set text of my choice on top strip of msi

something like this
var project = new ManagedProject("BAS Agent Installer",
                  new Dir
                  (@"%ProgramFiles%\Bas",                                
                      new File("Exe\\basagent.exe"),
                      new File("InstallLog.txt"),
                      new File("Exe\\logo.png")
                      ));

i have a image tag with source defined in my xaml whose value i am retriving from the xaml.cs file but that is not getting reflected in my msi

**Comment by Torchok19081986** [comment]
morning, ManagedProject has 2 Properties, that needs to be set for custom Image and Text. These are BannerImage and BannerText. Only one thing : Bannerimage has to be png Link: https://wixtoolset.org/docs/v3/wixui/wixui_customizations/
Also if your provided Image too large , at generate msi wixsharp generated warning that image too big. 

Best regards, Torchok.
