### ISSUE TITLE
Optional override of default WiX localization

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1423]
Using a managed Wix3 setup with custom UI, this [issue](https://github.com/oleg-shilo/wixsharp/issues/1392) resolved my problem with layering my own translations on top of the default WiX localization.

However, it's still not perfect. Consider for example the default string:

`<String Id="WelcomeDlgTitle" Overridable="yes"><!-- _locID_text="WelcomeDlgTitle" _locComment="WelcomeDlgTitle" -->{\WixUI_Font_Bigger}Welcome to the [ProductName] Setup Wizard</String>`

In a regular WiX project, I can (in my custom wxl) provide a new value for this string ID, e.g.

`<String Id="WelcomeDlgTitle" Overridable="yes">{\WixUI_Font_Bigger}My custom welcome string</String>`

And the setup will use my custom string in place of the default WiX one.

This is not the case with wixsharp, where the default WiX string will be used.

It's trivial to workaround the issue by using a different string ID, but it increases the workload when porting an existing WiX project.

**Comment by Torchok19081986** [comment]
morning, in Wix Sharp you can add standard Localization to msi project. This file, wxl , you can find in Installfolder of Wix toolset. there is many localizations file in there.  Path  , if you installed wix toolset v3 normal would be C:\Program Files (x86)\WiX Toolset v3.11\SDK\wixui. 
Only one thing , in Wix4 was changes in String Id for Localization . Here you have to manually editing values in wxl Files, cause Wix Team has changed Localization in wxl Files.
Link for Wix 4
https://wixtoolset.org/docs/tools/codepage/

**Comment by thenextman** [comment]
> morning, in Wix Sharp you can add standard Localization to msi project. This file, wxl , you can find it in Installfolder of Wix toolset. there is many localizations file in there. Path , if you installed wix toolset v3 normal would be C:\Program Files (x86)\WiX Toolset v3.11\SDK\wixui. Only one thing , in Wix4 was changes in Schema for Localization . Here you have to manually editing values in wxl Files, cause Wix Team has changed Localization in wxl Files. Link for Wix 4 : https://wixtoolset.org/docs/tools/codepage/ for Wix 4 Localization : https://wixtoolset.org/docs/schema/wxl/string/

Sure, I understand all of this. 

The wxl [string](https://wixtoolset.org/docs/schema/wxl/string/) element has an `overridable` attribute:

> Determines if the localized string may be overridden by a definition in another localization file

For overridable strings we can repeat the string ID in our custom wxl to _override_ the default string.

This does not work with wixsharp, hence my post.

**Comment by oleg-shilo** [comment]
@thenextman, does my comment in #1423 help addressing the problem?

**Comment by thenextman** [comment]
> @thenextman, does my comment in #1423 help addressing the problem?

Hi @oleg-shilo! I think you have a typo in your post, the link is back to this issue?

**Comment by oleg-shilo** [comment]
Yep, you I right. I meant #1424

**Comment by thenextman** [comment]
Ok, thanks.

>@thenextman, does my comment in https://github.com/oleg-shilo/wixsharp/issues/1423 help addressing the problem?

Not really, this appears to be a difference in how wixsharp consumes wxl files versus vanilla WiX

In WiX I can override the default WiX localizations by adding the _same_ string ID to my custom wxl (as long as the resource is marked `overridable`). This doesn't work with wixsharp.

A workaround is just to use a new string and modify the UI.

**Comment by oleg-shilo** [comment]
Hey Richard, are we talking about the same things?

I just tested WiX4 stream `CustomUI.WPF.Sequence` sample (it is in the repository). It seems like I was able just to redefine "Next" button text with a single entry in the custom wxl file.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/e9007af9-3b3f-43fa-b36f-1658127a0d1c)

May be you are referring to some other scenario...

**Comment by thenextman** [comment]
Thanks @oleg-shilo! I'm using Wix3 / WinForms UI...

**Comment by oleg-shilo** [comment]
Hm...
Still the same result:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/f1c1daeb-63ea-4e98-832a-8ea6d066d078)


Can you check this project that it works for you, please? And then we will dive deeper.

**Comment by thenextman** [comment]
@oleg-shilo With the latest nuget, this is indeed not a problem. My mistake - I apologize!
