### ISSUE TITLE
`Localize` function doesn't resolve properties

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1424]
Consider the following WiX3 example:

```
<Dialog Id="DG_InvalidConfig" Width="400" Height="85" Title="!(loc.InvalidConfigurationDlg_Title)">
```

Where the localization looks like this:

```
<String Id="InvalidConfigurationDlg_Title">[ProductName] Setup</String>
```

At runtime, the dialog title will properly be "My Product Setup".

If I attempt the same with wixsharp:

```
MessageBox.Show(
    MsiRuntime.Localize("InvalidConfigurationDlgInfoLabel"), 
    MsiRuntime.Localize("InvalidConfigurationDlg_Title"), 
    MessageBoxButtons.OK, 
    MessageBoxIcon.Warning);
```

The message box title is localized, but the property isn't resolved ("[ProductName] Setup")

For now, I use this workaround but ideally this would work the same as WiX

```
    private string ResolveVariables(string message)
    {
        return Regex.Replace(message, @"\[(.*?)]", (match) =>
        {
            string property = match.Groups[1].Value;
            string value = this.Session()[property];

            return string.IsNullOrEmpty(value) ? property : value;
        });
    }
```

**Comment by oleg-shilo** [comment]
There is a built-in routine that does it in a single step (though maybe in a less elegant way):

```C#
MessageBox.Show(
    "[InvalidConfigurationDlgInfoLabel]".LocalizeWith(MsiRuntime.Localize), 
    "[InvalidConfigurationDlg_Title]".LocalizeWith(MsiRuntime.Localize)), 
    MessageBoxButtons.OK, 
    MessageBoxIcon.Warning);
```
I have updated the method documentation to indicate that there is a better alternative:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/4f150da1-3362-4162-a4a1-e2908661c75e)

**Comment by thenextman** [comment]
@oleg-shilo This is great, thanks! I didn't find it in the API before. Exactly what I need 💯

**Comment by oleg-shilo** [comment]
Yeah, it's a bit buried in the implementation. 
But I hope the updated documentation will help.

**Comment by oleg-shilo** [comment]
I also updated the wiki about the topic:
https://github.com/oleg-shilo/wixsharp/wiki/Localization#custom-content-localization
