### ISSUE TITLE
Managed UI installer architecture

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1427]
My product _only_ targets x64, and I'm successfully installing it as such (`Package` `Platform=x64` and all components marked `Win64`).

I note that when the managed UI is launched, it's an x86 process (as seen in Windows Task Manager). This is a minor inconvenience, but I'd prefer a 64-bit process. I switch the project build to x64 but now the UI fails to run:

>Exception thrown by embedded UI initialization:
>System.BadImageFormatException: Could not load file or assembly 'MyProduct, Version=1.0.0.0, Culture=neutral, >PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Yes; of course an x86 process can't open an x64 DLL. But why is the process 32-bit? Is this a limitation of external UI? Anyway to change this?

That's a minor inconvenience; but more importantly, the msiexec also seems to run as x86. This is more annoying: I want to run custom action code in DLLs that only have a 64-bit version.

My old installer (built with WiX3) targets x64 in the same way, and both the UI and msiexec run as 64 bit processes. Can anyone shed some light or point me to the right documentation?

Thanks!

**Comment by oleg-shilo** [comment]
> I note that when the managed UI is launched, it's an x86 process

Yep, this is the way MSI service is designed. It always starts a fresh x86 process `msiexec.exe` for a msi file being executed. 
We have no control over it. It is how MSI team architectures the whole solution.

When you switch VS project to x64 you effectively make it into a x64 assembly. It is OK you you are only using this assembly to build an msi file. But if you are also using this assembly to implement managed EmbeddedUI(ManegedUI), then x86 CLR will fail to load this x64 assembly. Understandably. As you correctly noted. We have no way to change it.

However, the story with custom actions is slightly different.

You see, MSI is such an archaic creature that it uses a prehistoric routine invocation model. Thus for any custom actions, it forks a new `rundll32.exe` process that hosts your native CA dll, which in turn initializes x86 CLR and loads your CA assembly.

Annoyingly, there is no reason for custom actions to be of the same CPU architecture as the hosting (`msiexec.exe`) process. Your OS has an x64 version of `rundll32.exe`. The only problem is that `msiexec.exe` does not involve it but its x86 equivalent.

If indeed you have a dependency on some x64 managed resources you can achieve it but in a very clumsy (msi inspired way) 😄 

Tuus you can define your CA stump as a normal x86 codebase. But when it comes to the implementation of your CA that requires x64 you can perform it as an external process (kinda like `rundll32.dll`). This would be your `runasm.dll`. Its implementation would take really a few lines of code only:

```C#
AppDomain.CurrentAppDomain.ExecuteAssembly("path to your x64 CA assembly", args);
```

You compile your `runasm.dll` for x64, pack it in MSI, and ensure that your x64 CA assembly speats out an easy-to-read result. IE prints in StdOut a JSON with the result data. 

Thus in your stump CA you will:
- extract  `runasm.dll`
- extract x64 CA assembly
- fork an external x64 process (runasm.dll my.x64.CA.dll)
- read stdout 
- make your business logic action in the CA stump


I am even willing to provide a working sample for that but I need to focus on the next release first.

**Comment by thenextman** [comment]
@oleg-shilo Thanks 1,000,000 for the detailed technical summary. I understand this well now. I was frustrated that I couldn't find this documented anywhere for Windows Installer.

For now, I'm skipping the dependency that's x64 only (it's nice to have but not crucial). But I will keep this solution in my pocket.

Thanks once again 👍

**Comment by oleg-shilo** [comment]
I only made a consistent typo in my post

> `runasm.dll`

It should be `runasm.exe`.

I corrected it now.
