### ISSUE TITLE
[Question] SetNetPrerequirements to NET 7 or better

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1428]
Morning, is someone successfully added Net Requirements for application over Net Framework 4.8.1 ? 
I had update my app to net 7 and now i need update also my installer. I think i have to going after wix V4 . Only https://wixtoolset.org/docs/tools/wixext/dotnet/ link was there. Like always not documented well. 😄😄😄.

Is there support to NET 7 or better ? Another way maybe create custom wxs file for net Framework 7 over internal tools like harvest etc and add this outgoing wxs to installer. Just dont know which way is better.   🙄🙄🙄. 
I would like to going with wixstandardbootstrapper installer and WPF where i have most posibilities to achive that.

**Comment by oleg-shilo** [comment]
You can create your WixSharp as normal and then add `<netfx:DotNetCompatibilityCheck Property="DotNetCheckResult" RuntimeType="desktop" Version="7.0.0" RollForward="minor" Platform="x64" />` to the generated wxs file as in your post.

**Comment by oleg-shilo** [comment]
Interestingly enough WiX team marks this feature as still "work in progress"
https://wixtoolset.org/docs/development/wips/add-dotnet-runtime-compatibility-check/

**Comment by oleg-shilo** [comment]
This code will do the job:

```C#
    static public Project SetNetPrerequisite(this WixSharp.Project project, string version, string runtimeType, string rollForward, string platform, string errorMessage = null)
    {
        var condition = Condition.Create("Installed OR DotNetCheckResult = 0");
        string message = errorMessage ?? $"Please install .NET version {version} first.";

        project.LaunchConditions.Add(new LaunchCondition(condition, message));

        project.WixSourceGenerated += doc =>
            doc.FindFirst("Package").AddElement(
                WixExtension.NetFx.ToXName("DotNetCompatibilityCheck"),
                $"Property=DotNetCheckResult; RuntimeType={runtimeType}; Version={version}; RollForward={rollForward}; Platform={platform}");

        project.Include(WixExtension.NetFx);

        return project;
    }
```

**Comment by Torchok19081986** [comment]
moring @oleg-shilo . Many thanks. I just tried your code in wix v4 msi package. It works like it should be. Output msi produced same message on PC with installed and not installed .NET 7 Framework. 😄😄😄😄

**Comment by oleg-shilo** [comment]
Great. Txs for confirming. 
I am also putting this new `SetNetPrerequisite` implementation to the codebase so it will be available out of the box.

**Comment by oleg-shilo** [comment]
Available now as a prerelease `WixSharp_wix4.bin.2.0.6-pre`

**Comment by michal-paukert-tfs** [comment]
Is is possible to SetNetPrerequisite and also include prerequisite into msi and install if needed?
