### ISSUE TITLE
Transparent Background for ManagedUI.WPF Dialog-Banner TextBlock Controls

### ISSUE THREAD

**Issue by MichaelRobl** [oleg-shilo/wixsharp#1429]
Please change the background of the TextBlock.Controls  of the UI.WPF.Dialogs from White to Transparent.

Reason:
If I replace the standard banner bitmap with my own and this bitmap does not have the color white at the locations of the TextBlock elements, it looks very unprofessional.

**Comment by oleg-shilo** [comment]
Done, the fix will be available with the very next release. The update of the VS project templates will follow.

Until the fix is available, you can use VS "WPF Custom UI" template with source code for all dialogs, where you can remove the background attributes.

**Comment by MichaelRobl** [comment]
Hi Oleg,

great the removal of the background attribute works fine. 

Thank you for your great work!
