### ISSUE TITLE
Missing NuGet Package Dependencies for ManagedProject Template

### ISSUE THREAD

**Issue by MichaelRobl** [oleg-shilo/wixsharp#1434]
If an WixSharp Managed Setup (Wix4) Project ist created  and the project is restored, 4 NuGet Packages will be restored (wixsharp_wix4, wixsharp_wix4.bin, wixtoolset.dtf.windowsinstaller, wixtoolset.mba.core). During the build of the project additional nuget packages will be restored from the generated wix.tools.csproj file:

wix.tools.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="WixToolset.Dtf.CustomAction" Version="*" />
	<PackageReference Include="WixToolset.Dtf.WindowsInstaller" Version="*" />
	<PackageReference Include="WixToolset.Heat" Version="*" />
  </ItemGroup>
</Project>
```

It exists non direct or transitional dependencies of the wixsharp_wix4 NuGet package for the two additionals NuGet packages:
- WixToolset.Dtf.CustomAction
- WixToolset.Heat

Problem:
On our Build-Server we have only one productive nuget feed which contains all productive nuget packages which does not contains these two packages (no dependency exists). So our build on the build server failed with the following error message:

1>C:\Users\roblmich\.wix\.wixsharp\wix.tools\wix.tools.csproj : error NU1101: Unable to find package WixToolset.Dtf.CustomAction. No packages exist with this id in source(s): _[deleted sources for this Issue]_
1>C:\Users\roblmich\.wix\.wixsharp\wix.tools\wix.tools.csproj : error NU1101: Unable to find package WixToolset.Heat. No packages exist with this id in source(s): _[deleted sources for this Issue]_
1>  Failed to restore C:\Users\roblmich\.wix\.wixsharp\wix.tools\wix.tools.csproj (in 996 ms).

Please add to the wixsharp_wix4.bin packages dependencies for the two nuget packages. 
This package has already dependencies to the WixToolset.Dtf.WindowsInstaller nuget package.

**Comment by MichaelRobl** [comment]
One more additional NuGet Package dependency should be included for the wixsharp_wix4.bin package, because during build this package will be downloaded from internal code:
- WixToolset.UI.wixext

**Comment by MichaelRobl** [comment]
Hi Oleg, 

I'm in consense with you to analyse deep-dependency resolution of nuget packages. The only problem I will see is that the 
mentioned nuget packages will not be determined by a deep dependency resolution of the WixSharp_Wix4 package.

These packages will be restored only in code executed by the compiled MSI-Builder Application.
The only way to resolve these dependencies is to compare the NuGet packages folder before and after the execution of the MSI-Builder Application.

If the MSI should successfully build all nuget packages must be "restoreable".

**Comment by oleg-shilo** [comment]
> The only way to resolve these dependencies is to compare the NuGet packages folder before and after the execution of the MSI-Builder Application.

Yep. This is how you explore dependencies when preparing your product build spec for your CI.

BTW, it's not different to any other package-based build process. If you are to build a Node.js product (e.g. react app) on your CI, you would have the same problem. 
You cannot discover all your dependencies by analysing package.json. You will need to build your app (or do `npn install`) to collect ALL the packages in the `node_modules` folder.
