### ISSUE TITLE
NuGet config variable "globalPackagesFolder" is ignored

### ISSUE THREAD

**Issue by MichaelRobl** [oleg-shilo/wixsharp#1436]
On our Build-Server we have a nuget config file witch re-define the global nuget package folder from default (%userprofile%\.nuget\packages) to another location e.g. D:\NugetCache\%username%.

No we have build errors at the moment an call to WixSharp.CommonTasks.Wixtools.PackageDir is executed with result with an DirectoryNotFoundException. After Inspect the class I have seen that the Property NuGetDir in the WixTools class  points to %userprofile%\.nuget\packages.

here an example of the corresponding nuget config file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="globalPackagesFolder" value="D:\NuGetCache\%username%\" />    
  </config>
  <packageSources>
    <clear />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

The reason for change the global packages folder is to switch from the system partition C:\ to another partition D:\ 
so that nuget packages are not backed up in a system backup (only C:\ will be backup).

**Comment by oleg-shilo** [comment]
In this case, you need to instruct WixSharp as well, about the host OS using a custom packages location. You can do it by setting the `"NUGET_PACKAGES"` environment variable.

Unfortunately, it was a mistake when porting WiX3 in WiX4 codebase and the envar evaluation was not ported to the `WixTools` class. I have corrected the problem and published the prerelease (`WixSharp_wix4.bin.2.0.6-pre`):

```
public static class WixTools
{
    static internal string NuGetDir => Environment.GetEnvironmentVariable("NUGET_PACKAGES") ?? 
                                       @"%userprofile%\.nuget\packages".ExpandEnvVars();
    . . . 
```


Available now as a prerelease `WixSharp_wix4.bin.2.0.6-pre`
