### ISSUE TITLE
Set install path from registry entry

### ISSUE THREAD

**Issue by Lindsay-Mathieson** [oleg-shilo/wixsharp#1439]
Have been struggling with this one all day and just can't seem to figure it from the docs or examples.

As per the title, am trying to set the install path from a pre-existing registry entry (installing a component DLL for a third party application).

Have tried all the options from:

https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/SetupEvents/setup.cs

but none of them seem to work. Using a Id("NAME") for the Dir path just returns the ID Name, not its value.

Using WixManaged 4 Template.

**Comment by oleg-shilo** [comment]
You will need to read the path from registry and then set it to `INSTALLDIR` property. This is a predefined ID of your install dir.

You should do it as early as possible. See that SetupEvents sample to identify the earliest event for this

**Comment by oleg-shilo** [comment]
There is also a dedicated sample for that:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/3bf8b573-b0a6-474e-86f2-f73d0352238d)

**Comment by Lindsay-Mathieson** [comment]
Thanks, that did the trick, I did look at it earlier but made a couple of mistakes:
* Used Dialogs.InstallDir to track the install path, but it doesn't show there
* Was just using new Dir(new Id("CUSTOM_PATH+")), which just has the destPath parameter, I guess the Id() gets converted to a string of the name.
