### ISSUE TITLE
Close window can't exit?

### ISSUE THREAD

**Issue by Coloryr** [oleg-shilo/wixsharp#1440]
I create a wpf ui on start.
and just click close.
![image](https://github.com/oleg-shilo/wixsharp/assets/26276037/36585c26-e82a-4f3b-8197-0b154eddc9b6)
than delete the msi file, it can't be remove
![image](https://github.com/oleg-shilo/wixsharp/assets/26276037/7a27af61-286f-4fd3-b775-055496414b50)
the msi program has not been closed.
![image](https://github.com/oleg-shilo/wixsharp/assets/26276037/c0b6cff3-e690-407c-bade-e83c07352d93)
I't i missing some part of the code?
[project](https://github.com/Coloryr/ColorMC/tree/build_test/src/ColorMC.Setup.Wix)

**Comment by oleg-shilo** [comment]
I am not sure why your screenshot is showing InstallDirDialog while your project does not define it.

Anyway, I am guessing that msiexec is holding your setup because something did not go according the eplan during your installation.

Your project definition seems OK.
Though... don't you need to set `project.Platform = Platform.arm64;` for your arm distro?

You can also use this to simplify your code:

```C# 
new Dir(@"%ProgramFiles%\My Company\My Product",
    new Files(@"@"..\build_out\win-x64-aot\*.*")
. . .
```

**Comment by Coloryr** [comment]
I have noticed that the program will not end immediately after closing, and it will take some time for the program to close.

**Comment by Coloryr** [comment]
> I am not sure why your screenshot is showing InstallDirDialog while your project does not define it.
> 
> Anyway, I am guessing that msiexec is holding your setup because something did not go according the eplan during your installation.
> 
> Your project definition seems OK. Though... don't you need to set `project.Platform = Platform.arm64;` for your arm distro?
> 
> You can also use this to simplify your code:
> 
> ```cs
> new Dir(@"%ProgramFiles%\My Company\My Product",
>     new Files(@"@"..\build_out\win-x64-aot\*.*")
> . . .
> ```

No, there will be many unnecessary things in the output folder that I need to filter out.
arm64看起来需要单独设置

**Comment by Coloryr** [comment]
> I am not sure why your screenshot is showing InstallDirDialog while your project does not define it.
> 
> Anyway, I am guessing that msiexec is holding your setup because something did not go according the eplan during your installation.
> 
> Your project definition seems OK. Though... don't you need to set `project.Platform = Platform.arm64;` for your arm distro?
> 
> You can also use this to simplify your code:
> 
> ```cs
> new Dir(@"%ProgramFiles%\My Company\My Product",
>     new Files(@"@"..\build_out\win-x64-aot\*.*")
> . . .
> ```

set arm64 build fail
https://github.com/Coloryr/ColorMC/actions/runs/7664028297/job/20887748814
![image](https://github.com/oleg-shilo/wixsharp/assets/26276037/eeea26a3-552a-4f87-bd84-d10a70a6fb25)

**Comment by oleg-shilo** [comment]
Then it means that it is a WiX question as it seems like WiX no longer accepts arm platform attributes. 
t

**Comment by Coloryr** [comment]
> Then it means that it is a WiX question as it seems like WiX no longer accepts arm platform attributes. t

ok
