### ISSUE TITLE
[question] How to configure RemoveFiles Suppress=yes

### ISSUE THREAD

**Issue by ax-jrobb** [oleg-shilo/wixsharp#1441]
I want WixSharp to do the equivalent of this:

```xml
<Wix>
  <Product>
    <InstallExecuteSequence>
      <RemoveFiles Suppress="yes" />
    </InstallExecuteSequence>
  </Product>
</Wix>
```

I have yet to figure out a way to configure this. Is it possible?

**Comment by oleg-shilo** [comment]
You can do this:
```C#
project.WixSourceGenerated +=
            doc => doc.FindFirst("InstallExecuteSequence")
                      .AddElement("RemoveFiles", "Suppress=yes");
```

**Comment by ax-jrobb** [comment]
Thanks! Didn't have the outcome I wanted (removefiles is still being executed -- not a WixSharp thing, probably user error), but it did generate the desired Wix XML.
