### ISSUE TITLE
Wix4: CustomUI background image not showing

### ISSUE THREAD

**Issue by jozseffa** [oleg-shilo/wixsharp#1443]
Switching from Wix3 to Wix4 and WixSharp_wix4.bin the custom BackgroundImage and BannerImage bmp are not showing.

I converted the old v3 .wxs file manually by 'wix.exe convert' and checked for differences.
There was a new entry inserted by the converter:

`    <UIRef Id="WixUI_Common" />
`
After inserting that UIRef by code in WixSourceGenerated event for Wix4, the images are showing as expected.

Here is my code for others with the same issue:

```
private void Project_WixSourceGenerated(XDocument xml)
{
	var elemPackage = WixSharp.Extensions.Select(xml.Root, "Package");
	var elemUIRef1 = WixSharp.Extensions.Select(elemPackage, "UIRef");
	if (elemUIRef1?.GetAttribute("Id") != nameof(WUI.WixUI_Common))
	{
		var elem = WixSharp.Extensions.AddElement(elemPackage, "UIRef", $"Id={nameof(WUI.WixUI_Common)}");
		if (elemUIRef1 != null)
		{
			elem.Remove();
			elemUIRef1.AddBeforeSelf(elem);
		}
	}
}
```

I found no documentation why this is missing for Wix4...,
Maybe, you can find it out in witch cases WinSharp4 should insert the UIRef.

**Comment by oleg-shilo** [comment]
Hi Josef, thank you for sharing your findings.

Indeed WiX4 has changed the rules without any reflection in the documentation.
In WiX3 I was able to embed the image as `WixUI_Bmp_Dialog` and initialize a custom UI dialog as below:

```C#
image.Image = Runtime.Session.GetResourceBitmap("WixUI_Bmp_Dialog");
```

In WiX4 compiler started complaining about this code saying that there is collision with another `WixUI_Bmp_Dialog` id. Probably just introduced in WiX4. 

To overcome this problem WixSharp.4 embedds the image with a new id `WixSharpUI_Bmp_Dialog`:
```C#
image.Image = Runtime.Session.GetResourceBitmap("WixSharpUI_Bmp_Dialog");
```

Thus you would need to change it in your dialog code. If you are creating the project from a VS template then this change will be done automatically.

As for the `WixUI_Common`, if it does the trick then you probably can use it (I modified it a little):

```C#
project.WixSourceGenerated +=
    doc =>
    {
        if (!doc.FindAll("UIRef").Any())
            doc.FindFirst("Package")
                .AddElement("UIRef", $"Id={nameof(WUI.WixUI_Common)}");
    };
``` 

But I would recommend a more direct approach - accessing the background images with the new IDs:

```C#
public BitmapImage Banner => session?.GetResourceBitmap("WixSharpUI_Bmp_Banner").ToImageSource();
public BitmapImage Banner => session?.GetResourceBitmap("WixSharpUI_Bmp_Dialog").ToImageSource();
```

**Comment by jozseffa** [comment]
Thank you for clarifying and suggestions.

Regarding modified UIRef insertion:
don't forget, there is already an UIRef to WixUI_ErrorProgressText.
My final wxs look like this:

```
<UIRef Id="WixUI_Common" />
<UIRef Id="WixUI_ErrorProgressText" />
```

**Comment by oleg-shilo** [comment]
Ah.. Fair enough. Then:

```C#
roject.WixSourceGenerated +=
    doc =>
    {
        if (!doc.FindAll("UIRef").Any(x=>x.HasAttribute("Id", "WixUI_Common")))
            doc.FindFirst("Package")
                .AddElement("UIRef", $"Id={nameof(WUI.WixUI_Common)}");
    };
```

**Comment by oleg-shilo** [comment]
I just extended the `None` extension signature and in the next release you will be able to use:
```c#
if (doc.FindAll("UIRef").None(x => x.HasAttribute("Id", "WixUI_Common")))
```

Still, I do recommend using ` session?.GetResourceBitmap(correct_id)` instead. 😄
