### ISSUE TITLE
wix-setup.exe being flagged by protection systems

### ISSUE THREAD

**Issue by sdiaz-pdq** [oleg-shilo/wixsharp#1445]
We are installing a win service that automatically upgrades itself running a new version of its msi. Everything works as expected, but some systems are firing alerts due to the use of `wix-setup.exe`. I'm aware wixsharp uses this exe in its regular execution flow for some managed setup.

Is there a way I can bundle that functionality into my app instead of being a separate exe? or even a way to sign `setup.exe` with my cert so antivirus and alike wont flag it as unknown?

I've been testing and it seems like projects without ManagedUI elements don't reference `setup.exe` in the wxs but if I inspect the final msi I still can see it there

**Comment by oleg-shilo** [comment]
Hi Sergio,

WixSharp does not use `wix-setup.exe`. I am guessing that this executable is an assembly (that VS builds and runs) when you build your you WixSharp project. (see [this for details](https://github.com/oleg-shilo/wixsharp/wiki/VS2019-%E2%80%93-2022-Templates#msi-authoring-steps))

Lately, many antivirus vendors started using so-called "AI algorithms" to detect danger. In result, they detect and delete useful legit executables (compilers, a binary that you just built). Thus VirusTotal flags (at least it did a year ago) as "infected" an executable that you just built from the default VS template for WPF app without adding a single line of code. Yep, it is that stupid.

It is a major problem and in my company, we only managed to deal with it by whitelisting the folder where all our projects are. 

Quite possibly you can sign your executable (your very WixSharp project) if you have the certificate, and it might solve the problem too.

Note that at runtime your executable with your CAs is extracted by MSI and executed with `msiexe` -> `rundll32.exe (yourCA.dll +your_setup.exe)` but it never actually executes your setup*.exe. Instead, it executes rundll32 and the exe is loaded in the same native process as an assembly.

Signing msi may also convince your antivirus. But who knows...

**Comment by oleg-shilo** [comment]
You can bundle your custom actions as a separate assembly (dll/exe) but you will still need to deal with the AV.

**Comment by sdiaz-pdq** [comment]
Wow! Thanks for the super quick response Oleg

I was completely misunderstanding the process, thank you for the insights.
We are already signing the msi and that doesn't seem to do the trick. I'm gonna try to sign the generated exe or otherwise I guess we will need to whitelist as well as you mentioned. 

Have a nice day!
