### ISSUE TITLE
Catch all exceptions in managed WinForms UI

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1446]
In a traditional WinForms application, I can trap all unhandled exceptions by doing something like this:

```
public static void Main(string[] args)
{
    Application.ThreadException += new     
  ThreadExceptionEventHandler(ErrorHandlerForm.Form1_UIThreadException);
  Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);
  AppDomain.CurrentDomain.UnhandledException += new       
  UnhandledExceptionEventHandler(CurrentDomain_UnhandledException);
}
```

Is there any way to do something similar in the managed WinForms UI? Catch any unhandled exceptions from my interface in a top-level exception handler?

**Comment by thenextman** [comment]
> Actually, it is possible. Good suggestion. Made it into an `enhancement` ticket. It's easy. Will doit in a very next release.

Thank you @oleg-shilo!

**Comment by oleg-shilo** [comment]
Done.

```C#
project.UnhandledException += Project_UnhandledException;
. . .
void Project_UnhandledException(ExceptionEventArgs e)
{
    MessageBox.Show("Project_UnhandledException");
    Debug.Assert(false);
}
```

**Comment by thenextman** [comment]
I appreciate your work on this @oleg-shilo 

Is it possible the change wasn't pulled for the 1.25 release? I can't see the new event on `ManagedProject`...

<img width="1359" alt="Screenshot 2024-02-15 at 20 36 48" src="https://github.com/oleg-shilo/wixsharp/assets/2573400/d45678a3-bf60-4b1c-8d6b-532dbac87150">

**Comment by oleg-shilo** [comment]
Will check. 
I provisioned the fix in both streams but of course, it might be a human packaging mistake.

**Comment by oleg-shilo** [comment]
Indeed it was a mistake. This proves I am a human 😄 
Will fix it asap

**Comment by thenextman** [comment]
> This proves I am a human

Hard to believe - with speed of bug fixes and new features, I thought surely you must be a machine ;)

Thanks for the quick attention, I appreciate it as always

**Comment by oleg-shilo** [comment]
It should be OK in a few mins:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/3275b9e6-4f36-4c5d-890b-9ebcfee2e333)

**Comment by oleg-shilo** [comment]
I added the version validation now to the CI script. Should not happen again

**Comment by oleg-shilo** [comment]
Don't forget to update the package from the default template:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/b98a7db9-7d05-4fc3-8c30-0c65606eb9b3)

**Comment by thenextman** [comment]
It's working great, thank you. A nice improvement.

**Comment by oleg-shilo** [comment]
It was a great suggestion. Txs.
It also let me discover a logical problem with dialog exceptions being swallowed without impact on the execution flow.
