### ISSUE TITLE
Suggestion to add extra pre-defined Condition to be triggered when uninstalling.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#145]
In our installers with WIX, we often have a custom action triggered when the product is fully de-installed. This custom action is not triggered when the product is upgraded.

For instance with VSTO add-ins, you need to unregister the add-in with the respective Office product.

You can not use Condition.Removing, since that one is triggered also during upgrades.

Suggestion is to add this pre-defined Condition (for now we have it in our own code, but others might be helped by  adding this pre-defined condition):

```
        /// <summary>
        /// Software is being removed and no newer version is being installed.
        /// </summary>
        public static readonly Condition UninstallCondition = new Condition("(NOT UPGRADINGPRODUCTCODE) AND (REMOVE=\"ALL\")");

```

**Comment by oleg-shilo** [comment]
I have no problem with defining another condition. Will be done in the next release. But... please have a look at _Managed Events_. The are by far superior to the raw custom actions (even if they are just wrappers around the most important custom actions:
```C#
project.AfterInstall += project_AfterInstall;
...
static void project_AfterInstall(SetupEventArgs e)    
{
    if (e.IsUninstalling && !e.IsUpgrading)
        ...
```  
`IsUninstalling` and `IsUpgrading` are already encapsulating your property analysis.

Another important point is that `AfterInstall` runs elevated.

**Comment by monty241** [comment]
Hi Oleg, thanks for pointing it out. I saw it in some blogs passing by, but was unsure whether it was a new feature or obsoleted feature, so tried to stick to mimicking the functionality of WIX we had used. When I understand correctly, these are there new-and-improved replacements, so we will use them in the future.

**Comment by oleg-shilo** [comment]
Managed Setup model is an infrastructure that combines MSI/WiX and Wix#/ManagedEvents/ManagedUI.  This is the currently recommended authoring model that addresses the most of the shortcomings of the raw MSI/WiX toolset. 

Developers should consider it as a default approach unless their specific requirements directly prohibit MSI hosting CLR runtime during the installation.

**Comment by monty241** [comment]
Thanks for elaboration!
