### ISSUE TITLE
How to pass a session value to a deferred action

### ISSUE THREAD

**Issue by isaachaz** [oleg-shilo/wixsharp#1450]
In our setup we are creating a project of type Project (not ManagedProject)

I am trying to change a file in Program Files based on session property.
When working with an immediate action it fails on access denied.

When working with a deferred action it theoretically succeed but i can't access a session property from a deferred action(only immediate)
In other terms doing "var myvalue = session["product_selected" throws an exception.

Is there a code sample for setting a property from an immediate action that would then be used later by a deferred action?

**Comment by oleg-shilo** [comment]
Sorry, I have to ask.
Why are you resisting the use of `ManagedProject`? It is just an extended version of `Project`. It's a more convenient way of firing CA with minimal plumbing and with many deployment scenarios being already directly supported.

Your scenario in this case is also supported. There is a sample for that: 

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/e36c819e-1083-4d7a-ae7d-5371a24efbea)

The sample shows how to read in the elevated `AfterInstall` event a value (`persisted_data`) from the session object that was set at the early stage of the setup.

So you have an option. You can add to your project the prefix `Managed` 😄 and use this functionality or you can try to convert the sample in raw CA equivalent.

**Comment by isaachaz** [comment]
How do i access the sample?

**Comment by oleg-shilo** [comment]
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/a2a62c21-8c5f-4c5b-9b14-bf1b98998421)
