### ISSUE TITLE
MSI installer file name missing in taskbar.

### ISSUE THREAD

**Issue by bh-ubunye** [oleg-shilo/wixsharp#1453]
We were using embedded UI to create the MSI installer, but the installer file name does not show in taskbar.

![image](https://github.com/oleg-shilo/wixsharp/assets/110579042/5e4b1a40-8ac7-4376-bbfd-16c2b4b532bc)

If there was anything lacking during setup, could you please let us know?

**Comment by oleg-shilo** [comment]
I do not think you are missing anything in your code. I just built and run [Custom UI sample](https://github.com/oleg-shilo/wixsharp/tree/wix-v4-master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUI.Sequence) and it does show the taskbar thumbnail image. You can try it by yourself.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/3663ca43-e5c2-4a43-b7f9-dce99d7d3b77)

 Actually, you cannot influence the behaviour of the taskbar during the installation. It's all done by MSI and Windows.
  
 Most likely it is something fishy with the icon you supplied or just a Windows glitch.

**Comment by bh-ubunye** [comment]
We able to see the icon but the name of installer not display as the image I shared.

**Comment by oleg-shilo** [comment]
Did you roll over the mouse?
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/2ebade20-bc72-4faf-95c0-4d8b1b78ba66)

**Comment by bh-ubunye** [comment]
![image](https://github.com/oleg-shilo/wixsharp/assets/110579042/6855c571-b5d9-48ca-87b1-a2c78a2e7ea5)

ya, the name was missing

**Comment by oleg-shilo** [comment]
I do not know. 
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/c450514e-d5c1-4ba5-a09a-ae2c69eddb09)

If it works on your machine it means there is something different in our setup definition. Then you can explore and fix it.
If it does not work it means that somehow your environment is laying up with the MSI,
