### ISSUE TITLE
Project in WixSharp 2.1.0.0

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1454]
Hallo there, 
i was looking for new change in wixsharp and i downloaded latest examples of wix#. 
I opened Project WixBootstrapper_MsiEmbeddedUI and got Error.
```csharp

   var bootstrapper =
       new Bundle("My Product",
                  new ExePackage(@"..\..\Managed Setup\Self-executable_Msi\ManagedSetup.exe")
                  {
                      Name = "ManagedSetup",
                      InstallCommand = "/i",
                      UninstallCommand = "/x",
                      RepairCommand = "/fa",
                      DetectCondition = "MyAppInstalled",
                      Compressed = true
                  });

```
for first opening project there was InstallArgs, UninstallArgs, RepairArgs  and not Command. Wixsharp doesnt recognized Args, but only Command exists in ExePackage. Do i have to install some wixsharp dependency or it just typo ?

Another question : WiX4-Spike Project . New and it comes from Wixtoolset team ?
many Thanks for explanation.

**Comment by oleg-shilo** [comment]
> I opened Project WixBootstrapper_MsiEmbeddedUI and got Error.

You need to open the solution, not the project. Quite possibly you are missing some dependencies.
The easiest way is to create the project from the VS template. It will do all the required plumbing (e.g. packages).

> Another question : WiX4-Spike Project . New and it comes from Wixtoolset team ?

Yes it is from their repo.

**Comment by Torchok19081986** [comment]
morning, oleg. Ähm... .sln File was not there. I had to open .csproj File after that i could save Project as sln File. This Behaviour is in many another Projects of Wix#. Sln Files not exists in Examples.

**Comment by oleg-shilo** [comment]
You need to open the root solution file. Samples are part of the primary codebase.
