### ISSUE TITLE
An example of how to install an ocx file

### ISSUE THREAD

**Issue by ColinMaclean** [oleg-shilo/wixsharp#146]
I have an old legacy application which require me to install an ocx file. I looked at the examples but couldn't find an example of this.

**Comment by ColinMaclean** [comment]
Answered my own question. Not sure if its the best way 
 var publishAction = new PathFileAction("regsvr32.exe", @"/s legacy.ocx", "INSTALLDIR", Return.ignore, When.Before, Step.InstallFinalize, Condition.NOT_Installed)
                          {
                            Attributes = new Dictionary<string, string>()
                                         {
                                           {"Execute", "deferred"},
                                           {"Impersonate", "no"}
                                         }
                          };

   var unpublishAction = new PathFileAction("regsvr32.exe", "/u /s legacy.ocx", "INSTALLDIR", Return.ignore, When.Before, Step.InstallFinalize, Condition.Installed)
                            {
                              Attributes = new Dictionary<string, string>
                                           {
                                             {"Execute", "deferred"},
                                             {"Impersonate", "no"}
                                           }
                            };

...
                      Actions = new Action[]
                                {
                                  publishAction,
                                  unpublishAction
                                },
...

**Comment by oleg-shilo** [comment]
Yes this is the way you can do it. Or even like this:
```C#
var project = new ManagedProject(...
project.AfterInstall += project_AfterInstall;
...
static void project_AfterInstall(SetupEventArgs e)
{
    var command = $"/s \"{ Path.Combine(e.InstallDir, "legacy.ocx") }\"";
    if (e.IsUninstalling)
    {
        Preocess.Start("regsvr32.exe", "/u " + command);
    }
    else
    {
        Preocess.Start("regsvr32.exe", command);
    }
```
However WiX's current recommended approach is to use heat.exe to generate registry data that is the OCX registration and add this data at runtime to the target system registry. Though as for me, it is rather reflection of the current fashion than a technical necessity.  And I would actually keep your solution.
