### ISSUE TITLE
Add -sw1026 to default Wix4 argument options?

### ISSUE THREAD

**Issue by klokkenman1** [oleg-shilo/wixsharp#1460]
Hey,

Because users of WixSharp don't really have influence over the name that gets generated for the components I suggest adding the -sw1026 argument to [compiler.cs](https://github.com/oleg-shilo/wixsharp/blob/e8ce6a8eea04b05b917d86da552c8788b1c1e593/Source/src/WixSharp/Compiler.cs#L307]) because candleoptions seem to be no longer used.

I also receive the following error "WIX1149: ServiceConfig functionality is documented in the Windows Installer SDK to "not [work] as expected." Consider replacing ServiceConfig with the WixUtilExtension ServiceConfig element." but this might be because of something we configured.

I could create a PR for this if you like its only a small change.

Im not sure if the LightOptions should also be added?

**Comment by klokkenman1** [comment]
Should we not suppress warning 1149 aswell then?

**Comment by oleg-shilo** [comment]
Not sure about this one. In this case, WiX is saying, "We have messed up a little. Consider using an alternative" I cannot take responsibility for WiX's decisions and say "Just ignore it". Specifically, because I do not understand the depth of implications of ignoring the warning.

I only put the impression in defaults when I am reasonably confident in the outcome and the warning is triggered by a fundamentally silly reason. At least I was trying to follow this approach :)

**Comment by klokkenman1** [comment]
My viewpoint is more that if I as user of wixsharp can not influence if the generated Wix file uses ServiceConfig instead of WixUtilExtension ServiceConfig than why should I deal with this warning?

Or do I have influence over this?

Ofcourse its not a problem to suppress it via the WixOptions, its also fine if its suppressed by default.

Thanks!

**Comment by oleg-shilo** [comment]
OK, the short answer is "Yes you can influence it"

But the complete answer does need a little explanation.

Historically WiX was encoding service deployment via plain `ServiceConfig` element. WixSharp adhered to that by channelling `ServiceInstaller` properties to the element attributes.

Later WiX introduced a new version of this element - "WixUtilExtension ServiceConfig element". So WixSharp redirected the props to a new element. 

However, WiX team has failed to transfer all attributes from the old ServiceConfig to a new one. Three of them are only present in the old element. Quite possibly they had a good reason for that but they did not reveal it. They also did not obsolete the old element. Thus I could not just drop the use of the old element (WiX still recognizes it as valid). 

This means that WixSharp had no choice but to simply emit the old ServiceConfig if the user specified those three specific attributes that are only  available in the old ServiceConfogn element:

```C#
class ServiceInstaller
{ . . .
  public void Process(ProcessingContext context)
  {
      if (RequiresConfig())
      {
          Config = new ServiceConfig
          {
              DelayedAutoStart = DelayedAutoStart,
              PreShutdownDelay = PreShutdownDelay,
              ServiceSid = ServiceSid,
              ConfigureServiceTrigger = ConfigureServiceTrigger,
            };
        }

        if (RequiresConfigUtil())
        {
            ConfigUtil = new ServiceConfigUtil
            {
                FirstFailureActionType = FirstFailureActionType,
                SecondFailureActionType = SecondFailureActionType,
                ThirdFailureActionType = ThirdFailureActionType,
                . . .
```

Now you probably see that you indeed have "influence over this" but only by means of using or not using these specific three properties: DelayedAutoStart, PreShutdownDelay, ServiceSid. Thus if you do not use them then no ServiceConfig is emitted and no warning is generated.

To make it more transparent I added WixSharp warning:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/401e1aba-59b0-4bfa-9bbd-7da094bc518b)
