### ISSUE TITLE
ManagedUI Custom Dialog Size

### ISSUE THREAD

**Issue by johnferry0** [oleg-shilo/wixsharp#147]
When trying to increase the size of a custom dialog (via the design view), it does not change in the installer.

Is there any way to do this other than embedding a custom UI?

**Comment by oleg-shilo** [comment]
No, changing the dialog size doesn't affect the size of the shell dialog, which is a container window that changes the dialogs one by one as pages in the browser. Thus you need to change the "browser size".

Have a look at "CustomUIDialog" sample. It shows how to changes the shell window size (though the code is commented out for demo purpose.

**Comment by SiyataDishmaya** [comment]
Are you referring to the following example:\
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUIDialog/UserNameDialog.cs

If so, I was not able to get it to change the dialog size. Any advice would be greatly appreciated.

**Comment by oleg-shilo** [comment]
No I was talking about _setup.cs_ file:
https://github.com/oleg-shilo/wixsharp/blob/74e319e9a16c6d5b00e48befa5068ddb27383701/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUIDialog/setup.cs#L65-L76

**Comment by SiyataDishmaya** [comment]
Now that the dialog box is resized, it is no longer centered on the screen. I don't see that there is access to change the screen position. Any ideas would be greatly appreciated. 
Thanks

**Comment by oleg-shilo** [comment]
You do have access to the dialog:
```C#
var dialog = (e.ManagedUIShell.CurrentDialog as Form);
```

You do have access to its containing parent as well (`dialog.Parent`). In fact you have direct access to the top level window:  

```C#
var window = (e.ManagedUIShell as Form);
```
Use the debugger to analyze the runtime properties of `e.ManagedUIShell`.

By having all this at your disposal you can fully control size and position of your dialogs. And controlling them is a trivial .NET task, which does not really belong to the WixSharp domain.

I hope it helps.

**Comment by SiyataDishmaya** [comment]
Thank you! Centering the dialog box, while taking multi-monitor systems into account, is not so trivial. You are right in saying that is it not specific to WixSharp.

**Comment by oleg-shilo** [comment]
Sorry, I did not mean to trivialize your challenge. Even though it came out this way.

Interestingly enough the current implementation of `e.ManagedUIShell` on WixSharp side is indeed trivial:

```C#
void InitializeComponent()
{
    this.SuspendLayout();
    this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
    this.TopMost = true;
    . . .
``` 

Is it something that you can just reinforce at runtime?

**Comment by NickeManarin** [comment]
Is there any way to set the size while already running the setup?

**Comment by oleg-shilo** [comment]
You can always access the main dialog of your setup form `ManagedForm` via `this.Parent`, which is a top level Window (`Form`).

**Comment by NickeManarin** [comment]
@oleg-shilo It does not work. I've tried to use this during loading of `WelcomeDialog` managed UI:

```
            Width = 480;
            Height = 300;
            Parent.Width = 480;
            Parent.Height = 300;
```

But the Form window still has the same size, just the Window content was smaller. Btw, is there any way to debug the code?

**Comment by oleg-shilo** [comment]
Sorry, I've been a bit busy. Will try to send you a working sample today.

**Comment by NickeManarin** [comment]
Oh, there's no need. It's working. I forgot to say that in my edit. Thanks. 😄

**Comment by oleg-shilo** [comment]
Not a problem.

Just remember `Parent` is just a winform, nothing else.


```C#
class ShellView : Form, IShellView
{
    public void SetSize(int width, int height)
    {
        this.MaximumSize =
        this.MinimumSize =
        this.Size = new Size(width, height);
    }
. . .
```

**Comment by kipamgs** [comment]
Hi,
I have a similar problem. I'm using the ManagedUI WPF template. I only want to change the size of 1 dialog.
Is this possible?
I tried this but it's not working.

```
    public partial class SQLConnectionDialog : WpfDialog, IWpfDialog
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SQLConnectionDialog" /> class.
        /// </summary>
        public SQLConnectionDialog()
        {
            InitializeComponent();
        }
        public void Init()
        {
            this.ManagedFormHost.Parent.Width = 800;
            this.ManagedFormHost.Parent.Height = 800;

            ViewModelBinder.Bind(new SQLConnectionDialogModel { Host = ManagedFormHost, }, this, null);

        }
}
```

**Comment by oleg-shilo** [comment]
Hmm, something is wrong. Somehow, accessing the top-level WinForm from the hosted WPF dialog is not working.

I will need to investigate.

In a meantime please use this method from MSI event:

```c#
project.UILoaded += e => e.ManagedUI.SetSize(800, 800);
```

**Comment by oleg-shilo** [comment]
OK, I found the cause.

Fires, you need to update the MaxMin size as well; otherwise, the form will not respond to your new setting. 

```c#
this.ManagedFormHost.Parent.MaximumSize = new System.Drawing.Size(800, 800);
this.ManagedFormHost.Parent.MinimumSize = new System.Drawing.Size(800, 800);
this.ManagedFormHost.Parent.Width = 800;
this.ManagedFormHost.Parent.Height = 800;
```

The second problem is trickier - timing. The dialog's `void Init()` is called on dialog installation but before the whole visual tree is built. So the new size you are setting is overwritten when the top-level window is displayed. Thus you need to call your routine later (e.g. OnVisibleChanged).

But.... `project.UILoaded += e => e.ManagedUI.SetSize(800, 800);` is actually simpler and a more direct approach. So I suggest you use it instead.

**Comment by kipamgs** [comment]
This works great. Thank you.

**Comment by oleg-shilo** [comment]
Great. Glad we solved it.
