### ISSUE TITLE
When I include my app exe file in it's own File line it does not uninstall...

### ISSUE THREAD

**Issue by kplatter** [oleg-shilo/wixsharp#1472]
I have found that when MyApp.exe is placed in its own new File... section MyApp.exe does not uninstall

``` C#
            ManagedProject project = new ManagedProject()
            {
                Dirs = new WixSharp.Dir[]
                {
                    new Dir(@"%ProgramFiles%\\MyApp",
                        new Files(appFeature, $".\\SourceDir\\*.*", f =>
                            !f.EndsWith(".svn")
                            && !f.Contains("\\Reports\\")
                            && !f.Contains("\\V_")
                            && !f.Contains("LIB")
                        ),

                        new Files(appFeature, $".\\SourceDir\\V_{VERSION.Major}.{VERSION.Minor}\\*.*", f =>
                             !f.EndsWith("MyApp.exe")
                        ),

                        new WixSharp.File(new Id("MyApp.exe"), $".\\SourceDir\\V_{VERSION.Major}.{VERSION.Minor}\\MyApp.exe"),
                        ...
```

Only if I allow the MyApp.exe file to be pulled in using the new Files *.* does it uninstall during the uninstall process...

**Comment by oleg-shilo** [comment]
I am not sure that the problem is caused by your code definition.
This is the fresh VS project that tests your assumption and it seems like the problem is caused by something else:

```C#
using System;
using WixSharp;

namespace WixSharp_Setup12
{
    internal class Program
    {
        static void Main()
        {
            var project = new Project("MyProduct",
                              new Dir(@"%ProgramFiles%\My Company\My Product",
                                  new Files(@".\bin\Debug\net462\*.exe"),
                                  new File("Program.cs")));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

            //project.PreserveTempFiles = true;
            project.BuildMsi();
        }
    }
}
```
I have attached the sample. I suggest you test it and see if it shows the same symptoms as you describe:
[WixSharp Setup12.zip](https://github.com/oleg-shilo/wixsharp/files/14548945/WixSharp.Setup12.zip)

**Comment by oleg-shilo** [comment]
MSI does not remove an installed artifact if it was modified or replaced after the installation (e.g. text file). 
Or the file is also installed by another setup. In this case, MSI will store refcount in the registry and delete the file only after the last product setup is uninstalled.
  
You may want to check for that.

**Comment by kplatter** [comment]
I think this was due to other Dirs and Files code, after some clean up I am no longer having this issue...
