### ISSUE TITLE
Simply complex error project.AddVsProjectOutput

### ISSUE THREAD

**Issue by kPlusPlus** [oleg-shilo/wixsharp#1475]
I must to have made/make few serial setups.
project.AddVsProjectOutput to .net8.0 desktop app projects

System return 
Severity	Code	Description	Project	File	Line	Suppression State
Error	HEAT5317	MSBuildBinPath required for ToolsVersion '(none)'	Setup WinSystemManagment	C:\Temp\Setup WinSystemManagment\heat.exe	1	

*** cant add
ToolsVersion="Current" 
MSBuildBinPath required for ToolsVersion 'Current'
The "MSBuildBinPath" property is reserved, and cannot be modified.  !!!!!

**Comment by kPlusPlus** [comment]
> kPlusPlus, I am having a hard time understanding/following your Issue... Are you saying that you need to make multiple setups and are trying to use AddVsProjectOutput and getting HEAT5317 error?

Sorry for my bad speech.
--- AddVsProjectOutput for .net8 project dont work !!!

**Comment by kplatter** [comment]
Well I am going to have to let oleg address that, I am not sure if there are any issues between .NET 8 and AddVsProjectOutput

**Comment by oleg-shilo** [comment]
@kPlusPlus , can you explain what are you doing in your solution so I can try to reproduce your scenario? Right now your original post is a little short on details.
