### ISSUE TITLE
Installer UI scale is not right on 4K screen

### ISSUE THREAD

**Issue by John-Steelcad** [oleg-shilo/wixsharp#1477]
Hi,
My installer does not scale well on 2k and 4k screens. It looks fine on FHD though. I'm using a ManagedProject and ManagedUI.
<img width="372" alt="image" src="https://github.com/oleg-shilo/wixsharp/assets/109443661/c27fd8ab-9abd-480e-9bb7-92d3eb4bd630">

Let me know if you need any other information.

**Comment by Torchok19081986** [comment]
morning, i found following link on Wix toolset Site. https://wixtoolset.org/docs/schema/wxs/bootstrapperapplicationdll/. Looks like it possible in V4, but in Bootstrapper Application Installer.   Never tried on 2K and 4K Screenresolution. 
Best regards, Torchok.

**Comment by kplatter** [comment]
John are you using WPF Dialogs?

**Comment by John-Steelcad** [comment]
> John are you using WPF Dialogs?

No I'm not:

`project.ManagedUI = new ManagedUI();
            project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                            .Add(Dialogs.Licence)
                                            .Add(Dialogs.Progress)
                                            .Add(Dialogs.Exit);`

`project.ManagedUI.ModifyDialogs.Add(Dialogs.MaintenanceType)
                                           .Add(Dialogs.Features)
                                           .Add(Dialogs.Progress)
                                           .Add(Dialogs.Exit);`

**Comment by oleg-shilo** [comment]
John, try WPF dialogs instead. 
WPF is designed to deal with issues like that. 
Of course, you can get the whole custom UI project template and deal with this manually but I would mess with WnForms if I was in your shoes. 

If you still kin to get it sorted out for WinForms then create your project from `WixSharp CustomUI` VS template and every dialog will have a skeleton code (`ResetLayout`) for dealing scaling. You can just modify it as you need:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/a7cef264-fcd9-4636-93c4-138d81b87137)

**Comment by John-Steelcad** [comment]
I must be missing something in the code regarding using WPF dialogs instead of WinForms. How do I use them instead without create a whole custom UI? I'm not overly keen to spend time on that at the moment so hoping you have default ones.

**Comment by oleg-shilo** [comment]
You do not need to create a custom WPF UI by yourself. You just create your project from the WPF template and the UI (with all dialogs) will be created for you. You don't need to change a line of code unless you want to:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/075ab3a8-fa75-4bcb-ae9e-2b01a3ce40d9)

**Comment by oleg-shilo** [comment]
And if you don't even need the access to the dialogs code then it takes just one line:
```C#
 project.ManagedUI = ManagedUI.DefaultWpf; // all stock UI dialogs
 ```

**Comment by John-Steelcad** [comment]
Thanks. I have just worked that out. I now see 2 issues with overlapping.

Welcome and Exit title too long for dialog:
<img width="367" alt="image" src="https://github.com/oleg-shilo/wixsharp/assets/109443661/e65c2cd5-4717-4e10-bacf-57fa53476efd">

and banner image seems to have white text box overlapping:
<img width="369" alt="image" src="https://github.com/oleg-shilo/wixsharp/assets/109443661/b8f29311-d6e8-4caa-9b2c-b6b1c430a12c">

**Comment by oleg-shilo** [comment]
Then I suggest you use the first approach I proposed and then adjust the dialog layout to your needs.
Also, have a look at this sample. It gives you an overview of all WPF opportunities:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/2dd35731-dd26-42a4-87ec-9266f3d70710)

**Comment by John-Steelcad** [comment]
No worries. I'll see what I can do. Thanks for the help.

**Comment by John-Steelcad** [comment]
I've just been using a new Custom WPF UI  - I decided if I'm making a new project I'll try wix4 but I cannot get it to build. I've worked my way through a couple of pathing errors but now stuck on this error. What should I look for to get this to build?
`Error: Invalid argument: No CA or UI entry points found in module: C:\Project\WixSharp4_Setup\bin\Debug\net472\win-x86\WixSharp4_Setup.exe
Exception thrown: 'System.ApplicationException' in WixSharp.dll
Cannot package ManagedCA assembly(C:\Project\SDOperations\bin\Release\%this%)`

**Comment by John-Steelcad** [comment]
Seems I had to manually add the correct version:
`dotnet tool install --global wix`
`wix extension add -g WixToolset.UI.wixext/4.0.4`

I also changed my custom action to:
`project.AfterInstall += Msi_AfterInstall;`
`project.DefaultDeferredProperties += ",INSTALLDIR";`

```
        static void Msi_AfterInstall(SetupEventArgs e)
        {
            try
            {
                var installDirectory = e.Session.Property("INSTALLDIR");

                Process process = new Process();
                process.StartInfo.FileName = string.Format("{0}\\SD Operations.exe", installDirectory);
                process.StartInfo.WindowStyle = ProcessWindowStyle.Normal;
                process.Start();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message + ex.StackTrace);
            }

            //if (!e.IsUISupressed && !e.IsUninstalling)
            //    MessageBox.Show(e.ToString(), "AfterExecute");
        }
```

**Comment by oleg-shilo** [comment]
>Maybe related? https://github.com/orgs/wixtoolset/discussions/6516

Yes, it is related to that WiX problem. 
You can also have a look at this discussion: https://github.com/oleg-shilo/wixsharp/issues/1473
Quite possibly you already did. 

WiX team has marked the bug as fixed [yesterday](https://github.com/wixtoolset/issues/issues/6536) so possibly they will release the fix soon. But until it's done you will have to have this explicit step `wix extension add -g WixToolset.UI.wixext/4.0.4` and delete that bloody `5.0.0-rc1`.

A few further comments...

>project.DefaultDeferredProperties += ",INSTALLDIR";

`INSTALLDIR` is already there: 
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/87bb1b43-5bbe-441c-a7b2-b0e88861d5ac)

> I can't right click on the project and build release?

I cannot tell you what is different in your environment, but I have attached the WixSharp (wix3) project that was created from the "Custom WPF UI" template and builds for Release.
[WixSharp_Setup65.zip](https://github.com/oleg-shilo/wixsharp/files/14717392/WixSharp_Setup65.zip)

Have a look, maybe it will help.

**Comment by John-Steelcad** [comment]
Thanks for that info Oleg. I downloaded the zip you attached and it's fine. My old wix3 project also lets me build it. I am using the wix4 "Custom WPF UI" template which is basically the same... still won't build. Although VS says "Build succeeded" there is no msi created.

**Comment by oleg-shilo** [comment]
Let me check, maybe wix4 is broken

**Comment by oleg-shilo** [comment]
OK, it builds
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/6b47a543-129b-4d24-8ac7-44690be536dd)
try this attachment
[WixSharp Setup1.zip](https://github.com/oleg-shilo/wixsharp/files/14717511/WixSharp.Setup1.zip)

**Comment by John-Steelcad** [comment]
Yours works. You have a wix folder with a wxs file. Mine doesn't for some reason. How do I make one? I'm wondering if that is the issue.

**Comment by oleg-shilo** [comment]
It's created during the build

If you delete it and run the build again the folder will be recreated.
Check if you have the same build-event statement in your proj file.
Good thing is that you have something working and now you only need to find that small thing that makes the difference

**Comment by John-Steelcad** [comment]
I found you have this in post built event
```
cd .\
set ide=true
"$(TargetPath)"
```
When I add that I get an error:
```
Error	MSB3073	The command "cd .\
set ide=true
"C:\Project\SDOperations\WixSharp4_Setup\bin\Release\net472\win-x86\SDOperations.WixSharp.Setup.exe"" exited with code -532462766.	SDOperations.WixSharp.Setup	C:\Project\SDOperations\WixSharp4_Setup\SDOperations.WixSharp.Setup.csproj
```

**Comment by oleg-shilo** [comment]
That event is from the project template.

The problem seems to come from your exe that behaves differently in Release build. Have a look at the output window, it can give you a clue. 

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/4b9aeda5-61e7-4923-902f-351db7f7857f)

You may also increase verbosity with `Compiler.VerboseOutput = true;` 

You can easily debug your build process but... you have a rel;ease build... :)

**Comment by oleg-shilo** [comment]
then there is a chance your config manager is screwed:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/a0812cd4-46a0-4926-bcf5-97e83704ce5d)

Go with the benchmark you have. Or even kill your solution and see if you can build a new single project solution

**Comment by John-Steelcad** [comment]
My config manager shows the same as you. So strange! The only way I can get it to build is starting it without debugging.

**Comment by oleg-shilo** [comment]
you can always take my solution/project and add your files one by one and see which one breaks the config manager...

If you hit the wall, you can remove your sensitive date from the code and send your proj to me nd I can have a look

**Comment by John-Steelcad** [comment]
[like]  John Norbury reacted to your message:
________________________________

**Comment by John-Steelcad** [comment]
So I copied in your project and managed to get it to build properly. It turns out I basically had to rewrite much of my logic - mainly paths to things.

Earlier I wrote that I changed my custom action to Msi_AfterInstall but now when the app starts it does not have the same permissions for some reason? Eg. even to access a network drive. Any ideas why? I'm thinking I need to change this back to a custom action.

> Seems I had to manually add the correct version: `dotnet tool install --global wix` `wix extension add -g WixToolset.UI.wixext/4.0.4`
> 
> I also changed my custom action to: `project.AfterInstall += Msi_AfterInstall;` `project.DefaultDeferredProperties += ",INSTALLDIR";`
> 
> ```
>         static void Msi_AfterInstall(SetupEventArgs e)
>         {
>             try
>             {
>                 if (!e.IsUISupressed && !e.IsUninstalling)
>                 {
>                     var installDirectory = e.Session.Property("INSTALLDIR");
> 
>                     Process process = new Process();
>                     process.StartInfo.FileName = string.Format("{0}\\SD Operations.exe", installDirectory);
>                     process.StartInfo.WindowStyle = ProcessWindowStyle.Normal;
>                     process.Start();
>                 }
>             }
>             catch (Exception ex)
>             {
>                 MessageBox.Show(ex.Message + ex.StackTrace);
>             }
>         }
> ```
> 
> This builds now if I set to debug and run it. For some reason, I can't right click on the project and build release?

**Comment by oleg-shilo** [comment]
> Earlier I wrote that I changed my custom action to Msi_AfterInstall but now when the app starts it does not have the same permissions for some reason? Eg. even to access a network drive. Any ideas why? I'm thinking I need to change this back to a custom action.

I do not expect that starting the app can be influenced by the way you install it. Unless you specifically set the app permissions during the installation. But I do not think you did.

Don't get confused about CA and events. Event is a custom action. Always. Have a look at the generated WXS file and you will see it. The only difference is with one specific event `AfterInstall` is that it is also elevated. If for whatever reason elevation is undesirable, you can unelevate it by calling `project.UnelevateAfterInstallEvent();` before the build.

**Comment by John-Steelcad** [comment]
I tried project.UnelevateAfterInstallEvent(); and it worked except that this event is fired before the installer had finished. I changed back to my custom event and it's all working well now.
