### ISSUE TITLE
Question : How to add all dependencies for MSI / Bootstrapp Installer

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1480]
Morning, i have Problem to add Libraries for MSI if all Dlls have Versionsnumber in Name. 
I create view Dlls with output like this MyDependency.1.0.21.2024.dll and so on, but if i try to add it to MSI i got Error that dlls cant be found. Strangewise if i delete Versionsnumber of dlls , all dlls will be added to msi and create msi output without any error. 
I was some curios why. 
I created all dlls from link : 

https://stackoverflow.com/questions/72549821/how-to-append-version-to-assembly-output-file-name-in-net-standard-2-0-library

and use 
```xml
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="AssemblyIdentity"/>
    </GetAssemblyIdentity>
    <Exec Command='COPY "$(TargetPath)" "$(TargetDir)$(TargetName)%(AssemblyIdentity.Version)$(TargetExt)" /Y' />
  </Target>
```
in post-build event in visual studio 2022.

do someone had issues and resolve it successfully or how can add my new created dlls with Versionsnumber to msi output without getting error ?

**Comment by Torchok19081986** [comment]
i tried to add this dlls in another ways into msi installer. one way with by name and antother way with new Files [] if files doesnt contains .obj, .sln and so on extension. This results in 1. way in error and in 2. way with success. Does wix sharp exe get files name extension with dot separator ? something like string mydll = appdomain.currentdomain.basedirectory + "MyDependency.1.0.21.2024.dl" doesnt work, but in another way with array of Files works. Somehow i still curious.

**Comment by oleg-shilo** [comment]
Sorry, you will need to describe your scenario so advice can be provided. 
At the moment it's not clear to me what you are trying to do,

**Comment by Torchok19081986** [comment]
hm. ok. i will try to describe my problem better.
i want to  add many dlls to msi . 
Problem is, that 

```csharp

   var project = new ManagedProject("MyProduct",
                    new Dir(@"%ProgramFiles%\My Company\My Product",
                        new File("Program.cs")));

   project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

```
where file is 

```csharp
string mydll = appdomain.Current.BaseDirectory + @"\Mydll.1.0.21.2024.dll";

```
(MSI Description here form before) new File(mydll)

if i try to add it to files , i got error that file cant be found.

**Comment by oleg-shilo** [comment]
Make sure your dll is indeed in the directory you think it is.

The version string in the file name is irrelevant. Likely there is a problem with your currentdir/sourcedire.

This simple test builds msi just fine.

```C#

namespace WixSharp_Setup2
{
    internal class Program
    {
        static void Main()
        {
            string wixSharpDll = AppDomain.CurrentDomain.BaseDirectory.PathCombine("WixSharp.dll");
            string mydll = wixSharpDll.PathChangeFileName("Mydll.1.0.21.2024.dll");
            System.IO.File.Copy(wixSharpDll, mydll, true);

            Console.WriteLine(mydll);

            var project = new Project("MyProduct",
                              new Dir(@"%ProgramFiles%\My Company\My Product",
                                  new File("Program.cs"),
                                  new File(mydll)));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

            project.BuildMsi();
        }
    }
}
[WixSharp Setup2.zip](https://github.com/oleg-shilo/wixsharp/files/14740702/WixSharp.Setup2.zip)

```

I have attached the sample project for you:

**Comment by Torchok19081986** [comment]
Many thanks, @oleg-shilo  for quick response. I will try it and after test, i give feedback.

**Comment by Torchok19081986** [comment]
Now i tested your solution. Its work perfectly. 
Probably that my DLL, somehow,  is not prepared at the time of building MS. Dont know why, but thats error is disapears. Only last question : is there better way to deal with multiple dlls in this scenario ? Or i have to add all dlls to Collection or array and do part of code with Copy in loop ? My Idea : add to IEnumerable<string> and after add it to Files Array in project.Files.

**Comment by oleg-shilo** [comment]
> Dont know why, but that's error is disappears. 

Now I am convinced that the problem is caused by the raise conditions between two post-build events. One - building msi, another one renaming your DLL. The problem is gone because you have your DLL built from the previous build. You are in fact every time embedding in your msi the older build.

As the ugliest workaround you can put `Thread.Sleep(2000)` and it will fix your old solution.  The renaming in the msi build script seems like a more controllable approach if you ask me. 

Remember, the VS project is nothing else but a dotnet assembly that builds your msi when it is executed in the post-build event.

Read more here: https://github.com/oleg-shilo/wixsharp/wiki/VS2019-%E2%80%93-2022-Templates#msi-authoring-steps

**Comment by Torchok19081986** [comment]
ok, many thanks. I will remember your suggestion if i got any another error in build msi project. 🫡🫡🫡.
