### ISSUE TITLE
How to enable "browse" button in Features dialog while using WUI.WixUI_FeatureTree?

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1481]
Hi

I am using project.UI = WUI.WixUI_FeatureTree; option to have features screen as shown below. But I get "Browse" button disabled.

1. How can I set it to enabled so that user can browse and select his own install directory? OR if WixUI_FeatureTree is not correct choice, what is correct way of obtaining desired output? (Browse button enabled in features screen)

![FeatureBrowseDisabled](https://github.com/oleg-shilo/wixsharp/assets/23351437/9b10a5fc-34c8-4ac4-bdfa-48cba6a0c3bd)

2. Is Wix toolkit 4 version supported by WixSharp? If yes, what is Wix# version compatible with Wix 4 toolkit?

**Comment by oleg-shilo** [comment]
Yes Wix4 toolset is supported by WixSharp.

The best way to use it is to create the VS project from the corresponding WixSharp project template. You will need to install WixSharp VS  extension.

You can use any of the templates but arguably the most beneficial template is the Custom UI template, which comes ith the source code for the all dialogs (either WinForms or WPF).

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/168365cb-abf8-44da-8934-f3fb0fd71029)

**Comment by abskulkarni** [comment]
Thanks oleg-shilo for prompt help.
Can you please also guide me in my first query? I have set ConfigurableDir argument of Feature constructor to a non-empty string. I got Browse button enabled, but now I want it to set to %programfiles%\My Company\My Product" by default.

How do I do that?

**Comment by abskulkarni** [comment]
Thanks oleg-shilo for prompt help.
Can you please also guide me in my first query? I have set ConfigurableDir argument of Feature constructor to a non-empty string. I got Browse button enabled, but now I want it to set to %ProgramFiles%\Insurance_Data_Repository\IDR Command Line" by default.

I have tried below things, but it does not compile at first place.

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/bdd91581-fd67-4095-8d86-2463c0d8eb27)


How do I do that? Where & what am I doing wrong?

**Comment by abskulkarni** [comment]
Issue resolved. msi was already running so not getting compiled. Now it is working.

**Comment by oleg-shilo** [comment]
Keep in mind that you can control the type of UI by setting specific properties of your project object. 
It is has to be one of these options:

```C#
project.ManagedUI = ManagedUI.Default;    // WixSharp own WinForms custom UI
project.ManagedUI = ManagedUI.DefaultWpf; // WixSharp own WPF custom UI
project.UI = WUI.WixUI_<ui_type>;         // MSI own native UI
````
