### ISSUE TITLE
WiX Toolset security releases (2024-03-22)

### ISSUE THREAD

**Issue by juvo64** [oleg-shilo/wixsharp#1482]
There were security releases for the WIX Toolset: https://wixtoolset.org/news/2024/03/22/wix-security-releases-available/

**Comment by oleg-shilo** [comment]
Thank you @juvo64.

WixSharp does not need to be is updated as WiX toolset is distributed independently through its own distribution channels.

There is only one optional package that `WixSharp.wix.bin.3.14.0.1.nupkg`.
Though, I cannot understand which version WiX team recommends use. 
The link you shared has a sublink to v3.14.0.8606
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/6d669db7-40e0-4c36-880b-524e951d6cd0)

However, it is not the latest release. The Releases page nominates another release as the latest.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/41f1febc-2448-4f03-9bf1-1c67aba3b6ab)

Did you have some specific release in mind?

Don't forget this WixSHarp package is optional. You can install WiX tools set the way WiX teams recommend (e.g. release download)

**Comment by oleg-shilo** [comment]
OK. Thank you. 
I still prefer to update WiX binaries even though it's not mandatory. But still, it's better to play nice.

I just updated this package and it is now available from NuGet.org. I decided to go with the latest v3.14.1 release.

And WiX4 stream is fully independent - no need to change anything.

Thank you and please let me know if you see that WixSharp is behind again...  

I decided to
