### ISSUE TITLE
ManagedUI not displaying localized language from wxl file.

### ISSUE THREAD

**Issue by gsvin99** [oleg-shilo/wixsharp#1492]
I am using the ManagedUI project to build a multi-language UI similar to https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/MultiLanguageUI. I uploaded many wxl files while building the package, and then during UI initialization, I packed the system default locale code and selected the wxl file. However, my installation progress page shows localized language 50% and English 50%.  

Note: 
My machine has two languages (Chinese simplified and English), and I set Chinese as the default language.

currentActionLabel.The text is localized while the form is loaded. However, ProcessMessage (Microsoft.Deployment.WindowsInstaller.IEmbeddedUI.ProcessMessage) selected English rather than English.
                                CurrentAction.Text: "{0} {1}".Format(currentActionLabel.Text, message);

public override MessageResult ProcessMessage(InstallMessage messageType, Record messageRecord, MessageButtons buttons, MessageIcon icon, MessageDefaultButton defaultButton)
        {
            switch (messageType)
            {
                case InstallMessage.InstallStart:
                case InstallMessage.InstallEnd:
                    {
                        showWaitPromptTimer.Stop();
                        waitPrompt.Visible = false;
                    }
                    break;
                case InstallMessage.ActionStart:
                    {
                        try
                        {
                            string message = null;
                            if (messageRecord.FieldCount >= 3)
                            {
                                message = messageRecord[2].ToString();
                            }
                            ////else
                            ////{
                            ////    message = messageRecord.FormatString;
                            ////    if (message.IsNotEmpty())
                            ////    {
                            ////        for (int i = 1; i < messageRecord.FieldCount; i++)
                            ////        {
                            ////            message = message.Replace("[" + i + "]", messageRecord[i].ToString());
                            ////        }
                            ////    }
                            ////    else
                            ////    {
                            ////        message = messageRecord[messageRecord.FieldCount - 1].ToString();
                            ////    }
                            ////}
                            if (message.IsNotEmpty())
                                currentAction.Text = "{0} {1}".FormatWith(currentActionLabel.Text, message);
                        }
                        catch
                        {
                            //Catch all, we don't want the installer to crash in an
                            //attempt to process message.
                        }
                    }
                    break;
            }
            return MessageResult.OK;
        }

sample:
![image](https://github.com/oleg-shilo/wixsharp/assets/67852635/cf99d776-cff1-4ca6-be5f-8db7117e1eb0)

Thank you in advance. Please help me resolve this problem.

**Comment by Torchok19081986** [comment]
morning, questions over questions. Which version of WixToolset and WixSharp do you use ? AFAIK if localalization file doesnt have entry for Translated string it switch automatically to english as default. You can look into your .wxl files if all string for localization are correct translated.

**Comment by gsvin99** [comment]
I'm using the version shown below for my project.  
Wixsharp Version : 1.20.2
WixToolset : v3.11

        private static void Localize(this ManagedProject project, string currentPath)
        {
            project.AddBinary(new Binary(new Id("ar_sa_wsl"), Path.Combine(currentPath, @"AppInfo\Localize\WixUI_ar_SA.wxl")))
                   .AddBinary(new Binary(new Id("cs_cz_wsl"), Path.Combine(currentPath, @"AppInfo\Localize\WixUI_cs_CZ.wxl")))
                   .AddBinary(new Binary(new Id("da_dk_wsl"), Path.Combine(currentPath, @"AppInfo\Localize\WixUI_da_DK.wxl")))
		   ...........
                   .AddBinary(new Binary(new Id("zh_cn_wsl"), Path.Combine(currentPath, @"AppInfo\Localize\WixUI_zh_CN.wxl")))
                   .AddBinary(new Binary(new Id("zh_tw_wsl"), Path.Combine(currentPath, @"AppInfo\Localize\WixUI_zh_TW.wxl")))
                   .AddBinary(new Binary(new Id("en_us_wsl"), Path.Combine(currentPath, @"AppInfo\Localize\WixUI_en_us.wxl")));
        }

private static void LoadUiText(SetupEventArgs e, MsiRuntime runtime)
{
            string cultureInfo = CultureInfo.CurrentCulture.ToString().ToLower(CultureInfo.InvariantCulture);
            if (TranslateText.IsSupportedLanguage(cultureInfo))
            {
                runtime.UIText.InitFromWxl(e.Session.ReadBinary(cultureInfo.Replace("-", "_") + "_wsl"));
            }
            else
            {
                runtime.UIText.InitFromWxl(e.Session.ReadBinary("en_us_wsl"));
            }
}

private static void UIInitialized(SetupEventArgs e)
{
	MsiRuntime runtime = e.ManagedUI.Shell.MsiRuntime();
        LoadUiText(e, runtime);
}

Sample wxl file for English.
<String Id="ProgressTextMigrateFeatureStates" Overridable="yes">Migrating feature states from related applications</String>
    <String Id="ProgressTextMigrateFeatureStatesTemplate" Overridable="yes">Application: [1]</String>

wxl file for Chinses 
<String Id="ProgressTextMigrateFeatureStates" Overridable="yes">正在从相关应用程序迁移功能状态</String>
    <String Id="ProgressTextMigrateFeatureStatesTemplate" Overridable="yes">应用程序: [1]</String>

Only progressbar message is showing English instead of system languages. Please let me know, if need any other information.

**Comment by Torchok19081986** [comment]
morning, there is sample of multiple languages in example folder of wixsharp. if i understand your code aboe correct, you add all languages to installer . What happens if you not add en-us.wxl ?

**Comment by gsvin99** [comment]
Thanks @Torchok19081986. If the en-us.wxl file is not injected, then the package cannot be installed. If you remove the logic for adding all language wxl files, it will default to English rather than the system language.

**Comment by Torchok19081986** [comment]
hm..i think , some part of your description is not correct. 
```csharp

using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows;
using WixSharp;
using WixSharp.Bootstrapper;
using WixSharp.CommonTasks;

using io = System.IO;

public static class Script
{
    [STAThread]
    static void Main()
    {
        if (appFileName == "setup.exe")
            RunAsBA();          // msi-running session
        else
            RunAsMsiBuilder();  // msi-building session
    }

    static string appFileName => System.Reflection.Assembly.GetExecutingAssembly().Location.PathGetFileName();

    static void RunAsMsiBuilder()
    {
        // A custom BA with the language selection will be prepared
        BuildMsiWithLanguageSelectionBootstrapper();

        // a custom msi launcher with the language selection will be prepared
        // It is an alternative technique for building a simplistic managed bootstrapper that is nothing else but simple
        // .NET executable.
        {
            // var msiFile = BuildMultilanguageMsi();

            // aggregate deployment files
            // var appFile = System.Reflection.Assembly.GetExecutingAssembly().Location;
            // io.File.Copy(msiFile, msiFile.PathGetDirName().PathCombine("bin", msiFile.PathGetFileName()), true);
            // io.File.Copy(appFile, msiFile.PathGetDirName().PathCombine("bin", "setup.exe"), true);
            // io.File.Copy(appFile.PathChangeFileName("WixSharp.dll"), msiFile.PathGetDirName().PathCombine("bin", "WixSharp.dll"), true);
            // io.File.Copy(appFile.PathChangeFileName("WixSharp.Msi.dll"), msiFile.PathGetDirName().PathCombine("bin", "WixSharp.Msi.dll"), true);
            // io.File.Copy(appFile.PathChangeFileName("WixToolset.Mba.Core.dll"), msiFile.PathGetDirName().PathCombine("bin", "WixToolset.Mba.Core.dll"), true);

            // Console.WriteLine("=========================");
            // Console.WriteLine($" The setup files are aggregated in {msiFile.PathGetDirName().PathCombine("bin")}.");
            // Console.WriteLine("=========================");
        }
    }

    static void RunAsBA()
    {
        // Debug.Assert(false);
        // A poor-man BA. Provided only as an example for showing how to let user select the language and run the corresponding localized msi.
        // BuildMsiWithLanguageSelectionBootstrapper with a true BA is a better choice but currently WiX4 has a defect preventing
        // showing msi internal UI from teh custom BA.
        ConsoleHelper.HideConsoleWindow();

        var msiFile = io.Path.GetFullPath("MyProduct.msi");
        try
        {
            var installed = AppSearch.IsProductInstalled("{6fe30b47-2577-43ad-9095-1861ca25889c}");
            if (installed)
            {
                Process.Start("msiexec", $"/x \"{msiFile}\"");
            }
            else
            {
                var view = new MainView();
                if (view.ShowDialog() == true)
                {
                    if (view.SupportedLanguages.FirstOrDefault().LCID == view.SelectedLanguage.LCID) // default language
                        Process.Start("msiexec", $"/i \"{msiFile}\"");
                    else
                        Process.Start("msiexec", $"/i \"{msiFile}\" TRANSFORMS=:{view.SelectedLanguage.LCID}");
                }
            }
        }
        catch (Exception e)
        {
            MessageBox.Show(e.Message);
        }
    }

    /// <summary>
    /// This method is provided for demo purposes only
    /// </summary>
    /// <returns></returns>
    static string BuildMultilanguageMsi()
    {
        var project = new ManagedProject("MyProduct",
                          new Dir(@"%ProgramFiles%\My Company\My Product",
                              new File("setup.cs")));

        project.ManagedUI = ManagedUI.Default;

        project.ProductId = new Guid("6fe30b47-2577-43ad-9095-1861ca25889c");
        project.UpgradeCode = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

        var msiFile = project.BuildMultilanguageMsiFor(MainView.Languages);

        // The code below shows how to embed language resources manually instead of calling `BuildMultilanguageMsiFor`
        // project.Language = "en-US";
        // string productMsi = project.BuildMsi();

        // project.Language = "uk-UA";
        // string mstFile = project.BuildLanguageTransform(productMsi, project.Language);

        // productMsi.EmbedTransform(mstFile);
        // productMsi.SetPackageLanguages("en-US,uk-UA".ToLcidList());

        return msiFile;
    }

    static public void BuildMsiWithLanguageSelectionBootstrapper()
    {
        // Compiler.PreserveTempFiles = true;

        var product =
            new ManagedProject("My Product",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File("readme.txt")));

        product.ManagedUI = ManagedUI.Default;

        product.Version = new Version("1.0.0.0");
        product.GUID = new Guid("6f330b47-2577-43ad-9095-1861bb258771");
        product.OutFileName = $"{product.Name}.ml.v{product.Version}";
        var msiFile = product.BuildMultilanguageMsiFor(MainView.Languages);

        var bootstrapper =
                new Bundle("My Product Bundle",
                    new PackageGroupRef("NetFx462Web"),
                    new MsiPackage(msiFile)
                    {
                        Id = BA.MainPackageId,
                        DisplayInternalUI = true,
                        Visible = true,
                        MsiProperties = "TRANSFORMS=[TRANSFORMS]"
                    });

        bootstrapper.SetVersionFromFile(msiFile);

        bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25889b");
        bootstrapper.Application = new ManagedBootstrapperApplication("%this%");

        bootstrapper.Application.AddPayload(typeof(WixSharp.Extensions).Assembly.Location);

        // bootstrapper.PreserveTempFiles = true;

        bootstrapper.Build(msiFile.PathChangeExtension(".exe"));
    }
}

class ConsoleHelper
{
    [DllImport("kernel32.dll")]
    static extern IntPtr GetConsoleWindow();

    [DllImport("user32.dll")]
    static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

    public static void HideConsoleWindow() => ShowWindow(GetConsoleWindow(), 0);
}

```

code from Samples\Bootstrapper\MultiLanguageSupport. MSI will be transform at runtime. It can, probably helps. 
Test it , only then you get your info, why.  Another additional stuff, you have to search self.
