### ISSUE TITLE
Question : Make Wix# Wix Toolset v5 compatible

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1493]
Morning, according to Wix Team, in April should new Wix Toolset v5 released. Will Wix# also support it in later ? 
Link : https://wixtoolset.org/docs/fivefour/

**Comment by Torchok19081986** [comment]
many thanks, @oleg-shilo. Somehow i dont fully understand description of "naked" Filesi n Wix V5.  Group of Files and how to do subdirectory for it ? What is purpose of Subdirectory, if i dont have ine ? 🤔🤔🤔

**Comment by oleg-shilo** [comment]
There is no description but I guess it is somewhat similar to:

```C#
new Dir("My Folder",
    new Dir("bin",
        new File("foo.exe"),
        new File("bar.dll"),
        new File("baz.db")))
```
