### ISSUE TITLE
PerUser to PerMachin

### ISSUE THREAD

**Issue by grizoood** [oleg-shilo/wixsharp#1494]
Hello, I installed my application with "perUser", but the problem is that I cannot switch it to perMachin. However, I have the same UpgradeCode between the 2.

Is there a simple way to Upgrade a WiX installation from per-user to per-machine.

THANKS

**Comment by Torchok19081986** [comment]
morning, AFAIK there is property for Scope Installation perUser or perMachine. You can just test it and probaly find info. Just create one msi for perUser and change Versionnummer and set another  msi package  perMachine. If msi comes for update / upgrade old ones will be unisntalled, but new one will be installed. After that you can search in Registry if it was installed perMachine. Uninstalling feature of msi comes here for own good. 

best regards, Torchok.

**Comment by grizoood** [comment]
I already have an application that is installed as PerUser but when I switch to PerMachin, I have both applications installed, it does not uninstall the PerUser application (both have the same UpgradeCode). So I have two applications installed in "Programs and features"

**Comment by Torchok19081986** [comment]
hm. Then what you set for majorUpdateStrategy ?  I alway set it   project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
  project.MajorUpgradeStrategy.PreventDowngradingVersions.OnlyDetect = false;
  project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;
and in project description you have to use same GUID and give project.Version another Version

**Comment by grizoood** [comment]
If I leave it in PerUser by changing the UpgradeCode, it works but if I change the scope to PerMachin, it installs two versions. I think it's not possible to do this but I'm trying to find a way to do it via a CustomActions or something like that.

https://stackoverflow.com/questions/678002/how-do-i-fix-the-upgrade-logic-of-a-wix-setup-after-changing-installscope-to-pe

**Comment by Torchok19081986** [comment]
I think, you need to create CA that uninstall your product at start as always if it find related product. In BA Installer works, i can also share code here. BUT this will be way too complicated to do. Not rely on MSI Uninstall Routine. Harder , than you think it will be. 😐😐😐

**Comment by grizoood** [comment]
Then I do it using events (Load, BeforeInstall, AfterInstall) and not a CustomAction.

```c#
   project.Load += Msi_Load;
   project.BeforeInstall += Msi_BeforeInstall;
   project.AfterInstall += Msi_AfterInstall;
```

Also I don't understand this sentence:
```c#
 session.DoAction("AppSearch"); // Replace "AppSearch" with your actual action name
```

**Comment by grizoood** [comment]
@oleg-shilo, Could you provide me with an example please.

Let's imagine if the installation fails or the user cancels the installation, if I use the UIInitialized and UILoaded events, will the uninstallation of existing products be canceled?

**Comment by grizoood** [comment]
I'm sorry, I'm a beginner, could you give me an example with the use of the bootstrapper via wixsharp using the event: void OnDetectPackageComplete(object sender, DetectPackageCompleteEventArgs e)

**Comment by Torchok19081986** [comment]
morning, i used example of Wix# Bootstrapp Application. In Folder Examples search for WixBootstrapper_UI. THis example has all that you need to start. i dont remember anymore if event was from example or i added it later self. 

in class MainViewModel.cs an ctor

```csharp

 public MainViewModel(BootstrapperApplication bootstrapper)
 {
     this.IsBusy = false;

     this.Bootstrapper = bootstrapper;
     this.Bootstrapper.Error += this.OnError;
     this.Bootstrapper.ApplyComplete += this.OnApplyComplete;
     this.Bootstrapper.DetectPackageComplete += this.OnDetectPackageComplete;
     this.Bootstrapper.PlanComplete += this.OnPlanComplete;
     this.Bootstrapper.Shutdown += Bootstrapper_Shutdown;
     this.Bootstrapper.ExecuteComplete += Bootstrapper_ExecuteComplete;
     this.Bootstrapper.ExecutePackageComplete += Bootstrapper_ExecutePackageComplete;
     this.Bootstrapper.Engine.Detect();
 }

```
then handle event just like i post befeore. All another stuff you will be need self customized for your own BA Installer. But this is idea.

**Comment by grizoood** [comment]
Thanks, I'll close the topic for now.
