### ISSUE TITLE
WixSharp Setup - Bootstrapper Custom BA (Some assembly references are missing) in Designer

### ISSUE THREAD

**Issue by grizoood** [oleg-shilo/wixsharp#1495]
Hi,

I'm having a problem, I'm using a Visual Studio template: "WixSharp Setup - Bootstrapper Custom BA (WiX4)" for a bootstrapper application. But the Visual Studio Designer displays this:

Version of Visual studio :
Microsoft Visual Studio Community 2022 (2) (64 bits)
Version 17.9.5

I have no errors during compilation and when I run it, it displays the interface correctly.

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/2de7474d-8925-4735-ae0e-31ad84e543d1)

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/830ad61a-1234-4fa9-b678-4eff7b579437)

Do you have a solution?

**Comment by Torchok19081986** [comment]
welcome aboard. WPF Designer from MS is still kindof buggy, unforturenatallly. just close solution. delete .vs and all stuf inside .bin folder. Now open same solution, wait some time and build. should work. Somehow is wpf designer doesnt load immediatly data and remain onload. we cant do also nothung about it. Alternative , use Avalonia WPF Template for UI. Here works WPF Deisgner like it should . BA UI is wpf, and you can style it from any library what you want. 
https://github.com/AvaloniaUI/Avalonia.Samples

**Comment by grizoood** [comment]
@Torchok19081986, Great thank you very much, it works :)
