### ISSUE TITLE
MSI language

### ISSUE THREAD

**Issue by grizoood** [oleg-shilo/wixsharp#1497]
Hi,

Need help with MSI language !

In Wix, it is possible to define languages:

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/25421756-bc6e-4ab1-8d1d-63764b9beaa3)

And then we can create different language files :

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/5243721f-103f-430d-aa64-8b4494d17ebd)

fr-FR.wxl file : 

```xml
<?xml version="1.0" encoding="utf-8"?>
<WixLocalization Culture="fr-FR" xmlns="http://schemas.microsoft.com/wix/2006/localization">
  <String Id="Language">1036</String>
  <!-- Supported language and codepage codes can be found here: http://www.tramontana.co.hu/wix/lesson2.php#2.4 -->
  <String Id="Name">Nom de l'application</String>
  <String Id="ApplicationName">Nom du produit - !(loc.Name)</String>
</WixLocalization>
```

en-US.wxl file : 

```xml
<?xml version="1.0" encoding="utf-8"?>
<WixLocalization Culture="en-us" Codepage="1252" xmlns="http://schemas.microsoft.com/wix/2006/localization">
  <String Id="Language">1033</String>
  <!-- Supported language and codepage codes can be found here: http://www.tramontana.co.hu/wix/lesson2.php#2.4 -->
  <String Id="Name">Application name</String>
  <String Id="ApplicationName">Product name - !(loc.Name)</String>
</WixLocalization>
```

Product.wxs file :
```xml
<Product Id="*"
		Name="!(loc.ApplicationName)"
                Language="!(loc.Language)">
```

And this generates 2 msi output.

How can I do the same thing with wixsharp?

**Comment by grizoood** [comment]
I'm trying to do this:

```c#
project.Name = "!(loc.ApplicationName)";
```
But I get errors:

```
Cannot find the Binary file 'Product name - Application name.wxl'. The following paths were checked: Product name - Application name.wxl
Cannot find the Binary file 'Product name - Application name.licence.rtf'. The following paths were checked: Product name - Application name.licence.rtf
Cannot find the Binary file 'Nom du produit - Nom de l'application.wxl'. The following paths were checked: Nom du produit - Nom de l'application.wxl	
Cannot find the Binary file 'Nom du produit - Nom de l'application.licence.rtf'. The following paths were checked: Nom du produit - Nom de l'application.licence.rtf
```

**Comment by oleg-shilo** [comment]
> project.Name = "!(loc.ApplicationName)";

It's not how WixSharp works but you can achieve the desired outcome by simply reading the app name with C# from the wxl file:

```C#
project.Name = XDocument.Load(project.LocalizationFile)
    .FindAll("String")
    .First(x => x.HasAttribute("Id", "ApplicationName"))
    .Attr("Value");
```

And I just added a new more convenient extension method that embeds the code above. Thus from the next release you will be able to do it even as simple as below:

```C#
project.Name = project.LocalizationFile.GetLocalizedString("ApplicationName");
```

**Comment by grizoood** [comment]
One last question which is somewhat related.

How can we retrieve the ApplicationName variable to display the correct translation in the interface.

I want to replace "MESSAGE fr-FR or en-US" with "ApplicationName" variable which comes from the wxl file

```c#
   static void Msi_UIInitialized(SetupEventArgs e)
   {
       //MessageBox.Show(e.ToString(), "UIInitialized");

       e.ManagedUI.Shell.CustomErrorDescription = "MESSAGE fr-FR or en-US";
       e.ManagedUI.Shell.ErrorDetected = true;
       e.Result = ActionResult.UserExit;
   }
```

**Comment by grizoood** [comment]
It's good I found.

```c#
        static void Msi_UIInitialized(SetupEventArgs e)
        {
            //MessageBox.Show(e.ToString(), "UIInitialized");

            MsiRuntime runtime = e.ManagedUI.Shell.MsiRuntime();

            e.ManagedUI.Shell.CustomErrorDescription = runtime.UIText["ApplicationName"];
            e.ManagedUI.Shell.ErrorDetected = true;
            e.Result = ActionResult.UserExit;
        }
```

**Comment by oleg-shilo** [comment]
```C#
static void Msi_UIInitialized(SetupEventArgs e)
{
    MsiRuntime runtime = e.ManagedUI.Shell.MsiRuntime();
    // at this point `runtime` is initialized with the appropriate wxl so you do not need to decide  
    // as in "<String Id="CustomError" Overridable="yes" Value="MyCustom Error"></String>"
    e.ManagedUI.Shell.CustomErrorDescription = runtime.Localize("CustomError");
    e.ManagedUI.Shell.ErrorDetected = true;
    e.Result = ActionResult.UserExit;
}
```

**Comment by oleg-shilo** [comment]
Yep, the same thing :)

**Comment by grizoood** [comment]
Is it possible to chain the variables like this:

```xml
<WixLocalization Culture="en-US" Codepage="1252" xmlns="http://wixtoolset.org/schemas/v4/wxl">
	<String Id="Name" Value="Application test"></String>
	<String Id="ApplicationName" Value="MyProduct - !(loc.Name)"></String>
</WixLocalization>
```
ApplicationName => "MyProduct - Application test"

Or should I do this:

```xml
<WixLocalization Culture="en-US" Codepage="1252" xmlns="http://wixtoolset.org/schemas/v4/wxl">
	<String Id="Name" Value="Application test"></String>
	<String Id="ApplicationName" Value="MyProduct - Application test"></String>
</WixLocalization>
```

I know that in Wix it is possible but in WixSharp, I don't know.

**Comment by oleg-shilo** [comment]
There are two use-cases for that:

Formatted localization with the dynamic template (C# string):
```C#
var msg = "[ProductName] Setup".LocalizeWith(runtime.Localize);
MessageBox.Show(msg, "1");
```
With the product name being either MSI property or a string from the language file. And "[ProductName] Setup" is your template. BTW `!(loc.Name)` is a WiX proprietary syntax that they integrated with MSBuild process but it has no direct support outside of WiX VS project.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/fd3c7471-d30d-4129-9694-f688739a24d7)

Another use-case is the template in the language file. Every entry there can reference another entry from the same language file by enclosing the entry Id  in the square brackets:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/04ef781d-7819-4474-ab9c-4158dae60c0a)

And now you can use it like this:
```C#
msg = "[CustomError]".LocalizeWith(runtime.Localize);
MessageBox.Show(msg, "2");
```

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/0eeb830b-ad01-45f4-ae17-12d89a0a8934)

**Comment by grizoood** [comment]
Great, thank you @oleg-shilo

**Comment by grizoood** [comment]
I encounter another problem, I want to have 2 identical products with the same guid, but when I do this:

```c#
static void Main()
{
    var project = new ManagedProject("MyProduct",
                  new Dir(@"%AppData%\My Company\My Product",
                      new File("Program.cs")));

    project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

    project.ManagedUI = ManagedUI.DefaultWpf; 

    project.Language = "fr-FR";
    project.LocalizationFile = $@".\languages\custom_{project.Language}.wxl";
    project.Name = "Test-fr-FR";
    project.BuildMsi($"{project.Name} V{VERSION} {YEARS} {project.Language}.msi");

    project.Language = "en-US";
    project.LocalizationFile = $@".\languages\custom_{project.Language}.wxl";
    project.Name = "Test-en-US";
    project.BuildMsi($"{project.Name} V{VERSION} {YEARS} {project.Language}.msi");
}
```

It doesn't compile and tells me this:

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/5059091f-8605-459b-aaf4-3c29d58aef8c)

I think it doesn't save the :
- Test-fr-FR.licence.rtf
- Test-fr-FR.dialog_bmp.png
- Test-fr-FR.dialog_banner.png

Because project name is redefined in : ```Test-en-US```

So I tried to create two ManagedProject :

```c#
static void Main()
{
    Generate("en-US");
    Generate("fr-FR");
}

static void Generate(string language)
{
    var project = new ManagedProject("MyProduct",
                  new Dir(@"%AppData%\My Company\My Product",
                      new File("Program.cs")));

    project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

    project.ManagedUI = ManagedUI.DefaultWpf;

    project.Language = language;
    project.LocalizationFile = $@".\languages\custom_{project.Language}.wxl";
    project.Name = $"Test-{language}";
    project.BuildMsi($"{project.Name}.msi");
}
```

This works, it generates the two msi outputs :
```
Test-en-US.msi
Test-fr-FR.msi
```

The problem is found when executing the msi. For example I launch the msi: "en-US", everything is fine it installs it but subsequently if I launch the msi "fr-FR", I would like it to open the maintenance interface because it is the same product. Currently it shows me this:

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/c310f54f-18d8-4cbe-a7e6-6713a52deab9)

**Comment by Torchok19081986** [comment]
hallo, i had same issue with my standard language en-US msi. It happens, because you dont have set MajorUpdateStrategy. Just set it default . Should work after recreate msi new with newer version.

**Comment by oleg-shilo** [comment]
Did you have a look at this sample? Maybe it is what you are looking for?
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/46e7def1-5157-4903-86f4-2b09a319c6fb)

**Comment by Torchok19081986** [comment]
import is codeline in sample : 
```csharp 

static void RunAsBA()
    {
        // Debug.Assert(false);
        // A poor-man BA. Provided only as an example for showing how to let user select the language and run the corresponding localized msi.
        // BuildMsiWithLanguageSelectionBootstrapper with a true BA is a better choice but currently WiX4 has a defect preventing
        // showing msi internal UI from teh custom BA.
        ConsoleHelper.HideConsoleWindow();

        var msiFile = io.Path.GetFullPath("MyProduct.msi");
        try
        {
            var installed = AppSearch.IsProductInstalled("{6fe30b47-2577-43ad-9095-1861ca25889c}");
            if (installed)
            {
                Process.Start("msiexec", $"/x \"{msiFile}\"");
            }
            else
            {
                var view = new MainView();
                if (view.ShowDialog() == true)
                {
                    if (view.SupportedLanguages.FirstOrDefault().LCID == view.SelectedLanguage.LCID) // default language
                        Process.Start("msiexec", $"/i \"{msiFile}\"");
                    else
                        Process.Start("msiexec", $"/i \"{msiFile}\" TRANSFORMS=:{view.SelectedLanguage.LCID}");
                }
            }
        }
        catch (Exception e)
        {
            MessageBox.Show(e.Message);
        }
    }

```

**Comment by grizoood** [comment]
Weird, i have 2.1.5 version but merge is red underline

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/3facc7b9-7e3d-4d77-92a1-4577b6790399)

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/926667d6-9e37-4294-b7fa-21074c3d9688)

**Comment by Torchok19081986** [comment]
merge is paramter, just do remove it, second parameter is boolean, which is true. You dont need merge as variable.

**Comment by grizoood** [comment]
![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/4bb13fbe-7036-4319-b80b-18d17ae18954)

When I do "Go to Definition" in visual studio :

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/cb6b6842-da4a-4195-8ec8-be0f8a3c80fc)

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/96eb3ebe-daad-4f2c-ab01-cb086240fdc5)

**Comment by oleg-shilo** [comment]
Let me check the package in case it was a packaging problem.

**Comment by oleg-shilo** [comment]
Ah... all good. The change to the new signature was done for WiX3 stream and has not yet propagated to WiX4 stream of work.
So you can just drop that last arg in the method call.

**Comment by grizoood** [comment]
Ok I'll delete that :)

I took your example exactly with wix4 :/

```
error WIX0103: Cannot find the Binary file 'WixUI_de-DE.wxl'. The following paths were checked: WixUI_de-DE.wxl
error WIX0103: Cannot find the Binary file 'WixUI_el-GR.wxl'. The following paths were checked: WixUI_el-GR.wxl
```

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/18b48712-621e-4912-978f-a424faf7de72)

**Comment by grizoood** [comment]
No work :
```c#
project.AddBinary(new Binary(new Id("de_xsl"), @"WixUI_de-DE.wxl"))
       .AddBinary(new Binary(new Id("gr_xsl"), @"WixUI_el-GR.wxl"));
```

Work :
```c#
project.AddBinary(new Binary(new Id("de_xsl"), @"CycleScroller\WixSharp Setup1 WPF UI\WixUI_de-DE.wxl"))
       .AddBinary(new Binary(new Id("gr_xsl"), @"CycleScroller\WixSharp Setup1 WPF UI\WixUI_el-GR.wxl"));
```

**Comment by grizoood** [comment]
I had to add the full path, I don't know why

```
 CycleScroller\WixSharp Setup1 WPF UI\{FILE_NAME}wxl"
```

**Comment by oleg-shilo** [comment]
The file path is relative to the "working dir". If you used VS template then it is where the project file is. 
If you create your project other way then it is what your project settings say.

You an always check it by putting in the script file:

```C#
Console.WriteLine(Environment.CurrentDirectory);
```
