### ISSUE TITLE
Mainteance dialog (Change enabled button)

### ISSUE THREAD

**Issue by grizoood** [oleg-shilo/wixsharp#1501]
I work with the template: "Wix Sharp Setup WPF UI", I try to get as close as possible to what was done in Wix.

I don't create a feature, so everything is in "Complete".

In my old Wix msi I had the Maintenance window which grayed out the "Change" button because there were no selectable features and also replace the text by MaintenanceTypeDlgChangeDisabledText.

- How can I do the same thing with WPF UI?
- I don't know what exactly determines the change activated or deactivated on the 3 modes (Change, Repair, Remove), could you help me?

Wix interface :

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/1394951c-1789-4142-af02-ce9c81b0fbce)

WixSharp interface :

![image](https://github.com/oleg-shilo/wixsharp/assets/25281140/bda324b1-e367-4587-8149-ce1449103cfd)

**Comment by oleg-shilo** [comment]
TBH I am not sure the button should be disabled. It is rather a questionable UX.

I prefer the button to be enabled and if you click it it should go to the features dialog and show the current state of the features so user can decide if the change is really required. This is the current behaviour.

Though, if you want to make this decision on user behalf you can analyse the full state of every feature programmatically. It's not a problem.

I suggest you use "Custom WPF UI" template as it comes with the source code for the Features dialog where the "explore feature state" technique is used. You can just reuse the code. Most likely it will cover your needs.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/7c2d7f3a-18c5-4d3c-9b71-518c995424bd)

**Comment by grizoood** [comment]
I used this : 

```c#
    /// <summary>
    /// Updates the buttons of the dialog depending on ARPNOMODIFY, ARPNOREPAIR, ARPNOREMOVE.
    /// </summary>
    /// <param name="session">The session.</param>
    public void UpdateButtons(ISession session)
    {
        if (session["ARPNOMODIFY"] == "1")
        {
            ChangeLabel.Text = "[MaintenanceTypeDlgChangeDisabledText]";
            Change.IsEnabled = false;
        }
        else
        {
            ChangeLabel.Text = "[MaintenanceTypeDlgChangeText]";
            Change.IsEnabled = true;
        }

        if (session["ARPNOREPAIR"] == "1")
        {
            RepairLabel.Text = "[MaintenanceTypeDlgRepairDisabledText]";
            Repair.IsEnabled = false;
        }
        else
        {
            RepairLabel.Text = "[MaintenanceTypeDlgRepairText]";
            Repair.IsEnabled = true;
        }

        if (session["ARPNOREMOVE"] == "1")
        {
            RemoveLabel.Text = "[MaintenanceTypeDlgRemoveDisabledText]";
            Remove.IsEnabled = false;
        }
        else
        {
            RemoveLabel.Text = "[MaintenanceTypeDlgRemoveText]";
            Remove.IsEnabled = true;
        }

        // `Localize` resolves [...] text into the localized strings stored in MSI resources tables
        this.Localize();
    }
```
