### ISSUE TITLE
Transfer wix v3 Localization to V4 Loc in Wix#

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1502]
Morning, i have trouble to tranlate / convert v3 Localizationfile to v4. In V4 are breaking changes in Localization. I figured out, i can create command for cmd and convert it from v3 to v4, with some custom programming. 

in v3 Localization File looks 
```xml

<WixLocalization xmlns="http://schemas.microsoft.com/wix/2006/localization" Culture="de-DE" Codepage="1252">
  <String Id="WixUIBack" Overridable="yes">&amp;Zurück</String>
</WixLocalization>

```

and in v4

```xml

<WixLocalization xmlns="http://wixtoolset.org/schemas/v4/wxl" Culture="de-DE" Codepage="1252">
  <String Id="WixUIBack" Text="&amp;Zurück"/>
</WixLocalization>

```

```csharp
       
      public enum LanguageCode
      {
          English_US = 1252,
          German_DE = 1033,
     
      }

 
  XmlDocument xmlDoc = new();
  xmlDoc.Load(inputFilePath);

  XmlElement? rootElement = xmlDoc.DocumentElement;

  // Create a namespace manager and add the default namespace
  XmlNamespaceManager nsManager = new(xmlDoc.NameTable);
  nsManager.AddNamespace("ns", "http://schemas.microsoft.com/wix/2006/localization");

  //Change the namespace to WiX v4 format
  rootElement?.SetAttribute("xmlns", "http://wixtoolset.org/schemas/v4/wxl");

  // Select all String elements
  XmlNodeList? stringNodes = xmlDoc.SelectNodes("//ns:String", nsManager);

  foreach (XmlNode node in stringNodes)
  {
      XmlElement stringElement = (XmlElement)node;
      // Get the inner text content
      string value = stringElement.InnerText.Trim();
      // Remove the old Overridable attribute
      stringElement.RemoveAttribute("Overridable");
      stringElement.SetAttribute("Value", value);
     stringElement.InnerText = "";
  }

    xmlDoc.Save(outputFilePath);
```
this code procude output 

```xml
  <String Id="WixUIBack" Value="&amp;Zurück"> ??? whitepsaces here
  </String>

```

almost works, only whitespace need to be removed in innerText, there is some another little difference to fullfill v4 Localozation File. I have questons here in thema : 
1. how do i get version of template in wix# if it was created in v3 and not v4 ? Only then triggered this code. 
2.  there is no officially locs for each languages in v4, right? Only in v3 in installfolder of wixtoolset v3.14 ?

i dont want to manuallly always edit v3 in v4 localization. Need too much time.

**Comment by oleg-shilo** [comment]
This is what I used in WiX4 stream:

```c#
/// <summary>
/// Convert WXL file of WiX3 format to WiX4 format.
/// </summary>
/// <param name="source">The source file.</param>
/// <param name="destination">The destination file.</param>
static public void Wxl3_to_Wxl4(this string source, string destination)
{
    var doc = XDocument.Parse(IO.File.ReadAllText(source));
    doc.Descendants()
       .Where(x => x.Name.LocalName == "String")
       .ForEach(x =>
       {
           x.SetAttribute("Value", x.Value);
           x.Attribute("Overridable")?.Remove();
           x.Value = "";
       });

       IO.File.WriteAllText(
           destination,
           doc.ToString().Replace("xmlns=\"http://schemas.microsoft.com/wix/2006/localization\"",
                                  "xmlns=\"http://wixtoolset.org/schemas/v4/wxl\""),
           Encoding.UTF8);
}
```

The XDocument makes things much simpler :)

I only just added the removal of "Overridable". I assume you found that it is ignored I WiX4. Am I right?

**Comment by oleg-shilo** [comment]
> how do i get version of template in wix# if it was created in v3 and not v4 ? Only then triggered this code.

```
WixSharp.dll 2.* => WiX4
WixSharp.dll 1.* => WiX3
```

> there is no officially locs for each languages in v4, right? Only in v3 in installfolder of wixtoolset v3.14 ?

Correct.
I remember it was such a disappointment to discover that the files were no longer available. Quite possibly you can find them in the WiX4 repo. So I gave up. It does not impact WixSharp directly but only the users (sorry to say that). But it lest it was not blocking WixSharp 2 release

**Comment by Torchok19081986** [comment]
absolut fantastic to share you part of code. Many, many thanks , @oleg-shilo. Am i correct if loc files also affected BA wxl Files ? If so, i need somehow also convert it to v4, but for this purpose solution need.

**Comment by oleg-shilo** [comment]
> Am i correct if loc files also affected BA wxl Files?

It does:

```C#
bootstrapper.Application.LocalizationFile ="my_lng.wlx"; `
```

And for the conversion you can use that `Wxl3_to_Wxl4` two posts above.

**Comment by Torchok19081986** [comment]
i tried your solution code with XDocument. Works perfectly like expected, but you forget .ToList() before .ForEach. 😄.

**Comment by oleg-shilo** [comment]
No I did not. 😄.
In the context of WixSharp you have an extension method `ForEach` that is always available for 

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/d0f42364-6788-429a-bcb9-ba18335085ed)

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/547a2915-28c3-4965-bf1b-f4db73967faf)

But you are right if the sample is used outside of `WixSharp` namespace the `.ToList()` conversion is required.

**Comment by Torchok19081986** [comment]
last question here, after that, close pls this question. There is no changes in Localization in Wix V5, right? I dont find anything for loc Files in Wix V5.

**Comment by oleg-shilo** [comment]
This makes me think that it is still the same protocol as in WiX4.

As far as I understand WiX5 is an incremental progression and while some API areas are changed it still follows WiX4 development paradigm. Thus XML namespace did not change, while it did for WiX3->WiX4 transition.
