### ISSUE TITLE
Change installation content based on user inputs

### ISSUE THREAD

**Issue by artemishenkov** [oleg-shilo/wixsharp#1508]
Hi, I am trying to create my first installer using WixSharp with WPF. Visual Studio has created a default template with different dialogs. InstallDirDialog has a nice example of how to change the install directory based on user input using ISession from ManagedForm but for my installer, I need to change the content inside the installation directory. So if the user chooses option B I have to install one additional folder in the installation directory and run a Windows service from that folder. I would appreciate any guidance on how I can manage installation content based on user inputs. 
Thank you.

**Comment by Torchok19081986** [comment]
morning, AFAIK is msi content to install , is static, and cant be changed at runtime. Maybe webinstaller as BA Installer, can achive that. Never tried. You can try following options : 
Option 1 :  - FeatureTree Dialog. If you choose feature to install, handle it to install it, if not will not be installed.  
Option 2 :  - Conditional Installation. There is example inside of Wix#. "Conditional Installation". These based on Question if user want to install Desktop Shortcut at runtime. if yes, it will be installed, if not then no shortcut will be installed by msi. Idea of your installer is same. I would advice , you practice BA Installer. There is also Template form Oleg for WPF. With this template you have most posibility to create, change and use MSI Installer with own logic for it. 

best regards, Torchok.

**Comment by artemishenkov** [comment]
Thank you for your response I will try your suggestions and give feedback later.

**Comment by artemishenkov** [comment]
Thank you a lot. Works just fine!
