### ISSUE TITLE
Recurisive Add all Files and Subfolders

### ISSUE THREAD

**Issue by Diddlik** [oleg-shilo/wixsharp#1511]
Is there a way to automatically recursively add all files and subdirectories from the folder? And keep the folder structure?
I have in my release folder about 20-30 files and some sub folders which include some other files. I want to add all of them to Installer preserving folder structure.

**Comment by oleg-shilo** [comment]
Yes there is:

```C#
var project = new Project("MyProduct",
                  new Dir(@"%ProgramFiles%\My Company\My Product",
                      new Files(@"..\Release Folder\*.*")));
. . .
```

See `Release_Folder` sample for the details:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/cbf5f410-8a1c-4317-9291-4f60bf4de75b)

But also... keep in mind that with WixSharp you are no longer bound by the pure domain-specific scope of WiX API a pure declarative nature of XML. You have the full power of C# which has one of the most powerful generic-purpose APIs and can be used as a declarative, imperative or functional language. You are in full control.

Even if WixShar did not have the required functionality out of the box you could achieve the objective with very little effort:

```C#
. . .
var rootDir = project.FindDir(@"%ProgramFiles%\My Company\My Product");
foreach(var filePath in System.IO.Directory.GetFiles(@".\bin\Release", "*"))
    rootDir.AddFile(new File(filePath));
. . .
```

And if you want to preserve the folder structure you would need to alter the algorithm above a little.

But you are in luck. WixSharp happens to do exactly what you need.

**Comment by Diddlik** [comment]
Thank you Oleg, my understanding about "Dir" and "DirFiles" was not correct, now it works pretty well!

**Comment by oleg-shilo** [comment]
Great. I am happy you worked it all out.
