### ISSUE TITLE
BA Installer with multiple MSI's Trouble

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1514]
Morning, i have BA Installer with 2 msi`s packages. Somehow i cant get error or description if installer is complete. I would like to show by end of installation if one of msi package is successfully installed or not. I can currently only get firstpackage exitcode, but not from second package. for example if second package needs admin rights to install and failed to install, shows user that second package is failed becaused not enough right to install. If possible not cancel installation. 
MSI Package are created just straight forward. Stadandardescription for msi with files and installdir as WixUI.Installdir. 
I use wix toolset 4.0.5 and wix# 2.12.5. 
Many thanks for answer.

**Comment by Torchok19081986** [comment]
i thnik , im on right way. I added dictionary<string, int> and after installation in event 
```csharp 
 private void Bootstrapper_ExecuteComplete(object sender, ExecuteCompleteEventArgs e)
```
add packageid and status. Sofar ok, but now need info, how can i proceed to installation further if one of packages is failed to install ? currently if one of packages failed to install, burn cancel installation. Any idea ??

**Comment by Torchok19081986** [comment]
thnks for Tipp, @oleg-shilo .  
i got it work, dicitonary is created in mainviewmodel and added new key and value to it , was no big deal. Now im struggling with feature window in BA. I created already window as usercontrol and add 2 checkboxes to it and i thought i can add some logic to it if checkbox is checked, install msi and if not, nothing installed. BUT although my  efforts, BA always install both packages. Now i need to find out on which step BA set packages to install if it contains more than 1 MSI . Start, Cached or Begin ? All event looks same, but not much info. Propbably need to tested it all out. Last question here : do OnPlanComplete happens before or after start events ? if i had idea to create another viewmodel for new window and checked it . Bounding to CheckBox is not hard and add another viewmodel to mainviewmodel is also no nightmare anymore. 😉😉😉😉

**Comment by oleg-shilo** [comment]
>  do OnPlanComplete happens before or after start events ?

TBH I do not know. I would expect it to be before the installation start. 
You will need to put the message boxes there and test.

This is the problem with WiX - more often than not you need to reverse-engineer it to make it work. :(
