### ISSUE TITLE
Wix# build blocks parallel build in VS solution

### ISSUE THREAD

**Issue by greha** [oleg-shilo/wixsharp#152]
Hi,

I am optimizing our rather large solution (339 projects) when I noticed that as soon as the Wix# setup project is built, VS halts exactly at this project and waits till it finishes before continuing with the other projects.
Only 1 core gets used at that time and we loose about 40 seconds of build time.
Is there a setting which I might have forgotten to enable parallel builds while wix# is building or is this by design due to Wix / Msi tooling?

**Comment by oleg-shilo** [comment]
I am not sure about internals of the VS _parallel build_ implementation so it's hard to comment this problem. I actually expected Wix# to have the same treatment as any other VS project. Though understanding the Wix# building model can help you to handle the problem.

Wix# VS project is nothing else but a C# console app project. The main C# file is a "build script" that defines your MSI in the app entry point (_static main_). When the application is built the produced exe can be executed and the outcome of this execution is the desired msi file.

1. When you use project created from the Wix# VS project templates the project always have an extra step post-build that is defined in the project file as a reference to `WixSharp.targets` file. Thus every time you compile your project the exe is also executed.

2. Another way if creating the VS project for Wix# is to have just an ordinary console app project with `WixSharp.bin` NuGet package (this package does not include `WixSharp.targets`). And just have the call to execute the target exe in the post-build project event.

3. MSI can also be built with CS-Script C# script engine. This way it is a matter of a simple exe execution (synchronous and asynchronous): 
`cscs.exe setup.cs`. All Wix# samples are distributed with corresponding _build.cmd_ batch files that shows how to do the build with CS-Script.

If parallel build fails to do async building with one model you can try it with the other two. May be it will work.
