### ISSUE TITLE
Application folder is not removed after uninstallation

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1522]
Hi @oleg-shilo ,
I have created Wix4 project and able to install 2 features properly with below code in Main method.
**My question is,** if I uninstall product from control panel, installDir is not removed from Program Files folder. Those folders remain empty. **How to fix this?**

static void Main()
{
    var productName = System.Configuration.ConfigurationManager.AppSettings["ProductName"];
    var installDir = System.Configuration.ConfigurationManager.AppSettings["DefaultInstallDir"];
    var sourceDir = System.Configuration.ConfigurationManager.AppSettings["SourceDirectory"];

    Feature idrCmdFeature = new Feature("IDRCMD", "IDR Command Line Component");
    Feature idrPcFeature = new Feature("IDRPC", "IDR Polling Consumer Component");

    var project = new ManagedProject(productName,
                     new Dir(installDir,
                        new Dir("IDR Command Line",
                            new Files(idrCmdFeature,@"IDR Command Line\*.exe"),
                            new Files(idrCmdFeature, @"IDR Command Line\*.dll"),
                            new Files(idrCmdFeature, @"IDR Command Line\*.config"),
                            new Files(idrCmdFeature, @"IDR Command Line\*.xml")),
                        new Dir("IDRPC",
                            new Files(idrPcFeature, @"IDRPC\*.exe"),
                            new Files(idrPcFeature, @"IDRPC\*.dll"),
                            new Files(idrPcFeature, @"IDRPC\*.config"),
                            new Files(idrPcFeature, @"IDRPC\*.xml"))));
    project.SourceBaseDir = sourceDir;
    project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

    //project.ManagedUI = ManagedUI.Empty;    //no standard UI dialogs
    //project.ManagedUI = ManagedUI.Default;  //all standard UI dialogs
    
    //custom set of standard UI dialogs
    project.ManagedUI = new ManagedUI();

    project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                    .Add(Dialogs.Licence)
                                    .Add<CustomDialog>()
                                    .Add(Dialogs.Progress)
                                    .Add(Dialogs.Exit);

    project.ManagedUI.ModifyDialogs.Add(Dialogs.MaintenanceType)
                                   .Add(Dialogs.Features)
                                   .Add(Dialogs.Progress)
                                   .Add(Dialogs.Exit);

    project.Load += Msi_Load;
    project.BeforeInstall += Msi_BeforeInstall;
    project.AfterInstall += Msi_AfterInstall;

    //project.SourceBaseDir = "<input dir path>";
    //project.OutDir = "<output dir path>";

    ValidateAssemblyCompatibility();

    project.BuildMsi();
}

**Comment by Torchok19081986** [comment]
Hiho, first of all, what happens if you set installdir to another path, for example C.\My Company\My Product ? Any Changes ? If change Path has different output, all Folders are remove at uninstall, here you got your evidence. If not, try AfterInstall Event. 
something like following code 

```csharp

project.AfterInstall => (SetupEvents ea) 
{
  if(ea.Session.IsInstalled && ea.Session.IsUninstalling)
  {
     Directory.Delete(ea.Session["INSTALLDIR"]+ "\\YourDirectory")
  }
}

```
Normally, what windows installer install on system, will be also delete at uninstallation. no matter, if from control panel or not.

**Comment by Torchok19081986** [comment]
Normally you dont need do something at AfterInstall Event. 
But, you need do test it, step by step, out.  Probably ProgrammFiles somehow interpret it differently as another Path. Also at Installation user windows rights can play role here. There is sample for Admins Check to install msi. Try it . It not much code. Shows if msi at start shows message, that user has not enought right to install it.  Only BeforeInstall and AfterInstall Events are elevated and you will see UAC . All another events doesnt elevated at all. ProgrammFiles Folder and all Top Folder of Window are set as NTFS and if user doesnt have enough privilages to remove or install it it, you got error. this can be your case. You can also try different versions of template in v3 and in v4. Is there any difference ? If not, maybe your project has "wrong" output wxs file. Verify it with "standard" msi description , if you put it in v3 wix# project template and v4 wix# project template. 
Only then you can get info, why.

**Comment by abskulkarni** [comment]
I am using Wix4.0. 
And AfterInstall event to delete install directory is NOT working. e.Session.IsInstalled() && e.Session.IsUninstalling() is evaluated as false while uninstalling application.

**Comment by oleg-shilo** [comment]
The term "install" refers to the execution of msi setup either for installing, modifying, upgrading, preparing or uninstalling the product.

Thus AfterInstall is the last event of the session. Thus if you do something at this point during the uninstalling it means that your product is already uninstalled. Thus quite possibly it is the reason why `e.Session.IsInstalled()` is evaluated as `false`. 

So you can check the file system to understand if you actually uninstalling. Or simply evaluate `isUninstalling()`. This condition is rather sufficient for your case.

If I was you I would still look at the causes for the folder not being removed by uninstall. Usually, it is caused by the presence of the files created by other apps. And only when you are ready to give up :) then remove some folders manually.

**Comment by abskulkarni** [comment]
e.IsInstalled && e.IsUninstalling does not work either. Uninstallation rolls back somehow.
There are no files present in installed folders by the way. I just install MSI and tries to uninstall immediately.

**Comment by oleg-shilo** [comment]
The `Managed Setup/SetupEvent` sample shows how these session extension properties work. This sample is working and you can use it as a benchmark.

The `IsUninstalling` does not do much but simply checks the session properties:

```C#
        /// <summary>
        /// Determines whether the MSI is running in "uninstalling" mode.
        /// <para>
        /// This method will fail to retrieve the correct value if called from the deferred custom
        /// action and the session properties that it depends on are not preserved with
        /// 'UsesProperties' or 'DefaultUsesProperties'.
        /// </para>
        /// </summary>
        /// <param name="session">The session.</param>
        /// <returns></returns>
        static public bool IsUninstalling(this Session session)
        {
            return session.Property("REMOVE").SameAs("All", true);
        }
```

Thus if for whatever reason "REMOVE" property value is wrong then the extension method will return wrong result too.

As for `IsInstalled` it's value assigned based on the MSI Interop:

```c#
        /// <summary>
        /// Determines whether the specified product code is installed.
        /// </summary>
        /// <param name="productCode">The product code.</param>
        /// <returns>Returns <c>true</c> if the product is installed. Otherwise returns <c>false</c>.</returns>
        public static bool IsInstalled(string productCode)
        {
            StringBuilder sb = new StringBuilder(2048);
            uint size = 2048;
            MsiError err = MsiInterop.MsiGetProductInfo(productCode, "InstallDate", sb, ref size);

            if (err == MsiError.UnknownProduct)
                return false;
            else if (err == MsiError.NoError)
                return true;
            else
                throw new Exception(err.ToString());
        }
```

These are just bits and pieces of information for you to help to understand what is going on.

But... again, I would use the benchmark project and look for the change in your solution that triggers the outcome of IsInstalled and IsInstalling. As the last resort, I would consider your own implementation of the IsInstalled in one of the setup events. The code is above.

**Comment by abskulkarni** [comment]
Hi
I just observed that, if my feature folder has sub-folders, then its parent install folder is not deleted. 
How to fix this?

**Comment by oleg-shilo** [comment]
It's not the behaviour I can investigate remotely. 
I would look at the generated wxs file and see if the folders/sub-folders you are deploying are associated with the correct features.  

It works well for ProgFiles installdir but maybe in your case it somehow breaks the associations.
