### ISSUE TITLE
Write Filename with Path on InstallDialog

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1524]
Morning, i have to show Installfile with Path on InstallDialog. Currently if Product will be installed or upgrade ,  Text in Progressbar write Actionname. How can i write File with Path that will be installed / copied to targetsystem ? I tried to change currentActionname with custom Property and add all files to this property, but nothing happens. I also found out , i need to change Record of MSI . How can i do that during install ? 
i try to use following code
```csharp

 public class CustomActions
    {
        [CustomAction]
        public static ActionResult UpdateProgressBarText(Session session)
        {
            try
            {
            
                string fileList = session["CURRENTINSTALLFILELIST"];
                
          
                string[] files = fileList.Split(';');

           
                foreach (string file in files)
                {
                    session.Message(InstallMessage.ActionStart, new Record(new object[] { "Installing file: " + Path.GetFileName(file) }));

                }
            }
            catch (Exception ex)
            {
                session.Log("Custom action failed: " + ex.Message);
                return ActionResult.Failure;
            }

            return ActionResult.Success;
        }
    }

```

unfortunatly, msi still write Actioname on top, not current file name with path.

**Comment by oleg-shilo** [comment]
Progress message formatting is a mess. See this discussion: https://github.com/oleg-shilo/wixsharp/discussions/1504

If you want to have full control over the progress messages then you have better chances by implementing your own progress label in the custom ProgressDialog.

**Comment by Torchok19081986** [comment]
many thanks. I just tested it. it really a mess. I didnt knew that i was such a ... to handle it. I will try another approach. Maybe it can do better. Why not try extract all files from msi / BA Installer to temp/myproduct after Initialize. Then write all file name to json and then just write it to progressbar Text for output like "File MyProduct.exe will be copied to <Path>" something like that. Custom CA should be possbile. There only one thing to know, how to schedule multiple CA one after another. 
Just idea.

**Comment by Torchok19081986** [comment]
just writen 2 CA´s 
```csharp 

using Microsoft.Deployment.WindowsInstaller;
using Newtonsoft.Json;
using System;
using System.IO;

public class CustomActions
{
    [CustomAction]
    public static ActionResult GenerateJson(Session session)
    {
        try
        {
            // Get list of files in temp folder
            string[] files = Directory.GetFiles(session["TEMPFOLDER"]);

            // Generate JSON string
            string json = JsonConvert.SerializeObject(files);

            // Write JSON to file
            string jsonFilePath = Path.Combine(session["TEMPFOLDER"], "files.json");
            File.WriteAllText(jsonFilePath, json);

            session["FILES_JSON_PATH"] = jsonFilePath; // Store file path in property for later use

            return ActionResult.Success;
        }
        catch (Exception ex)
        {
            session.Log($"Error generating JSON file: {ex.Message}");
            return ActionResult.Failure;
        }
    }

    [CustomAction]
    public static ActionResult UpdateProgressBarText(Session session)
    {
        try
        {
            // Read the JSON file path stored in property
            string jsonFilePath = session["FILES_JSON_PATH"];

            // Read JSON content
            string json = File.ReadAllText(jsonFilePath);

            // Deserialize JSON to array of file paths
            string[] files = JsonConvert.DeserializeObject<string[]>(json);

            // Iterate through the files and update the progress bar text
            foreach (string file in files)
            {
                // Get filename
                string filename = Path.GetFileName(file);
                
                // Construct installation path
                string installPath = Path.Combine(session["INSTALLDIR"], filename);

                // Update label text
                session.Message(InstallMessage.ActionStart, new Record(new object[] { "Installing file: " + installPath }));

                // Perform installation of the file...
            }
        }
        catch (Exception ex)
        {
            session.Log("Custom action failed: " + ex.Message);
            return ActionResult.Failure;
        }

        return ActionResult.Success;
    }
}


```

**Comment by oleg-shilo** [comment]
Great. Unorthodox but great. 😄

**Comment by Torchok19081986** [comment]
i will test it and give feedback by end of this week. 2 more questions here : 
 1.  - why is this messagerecord is such a mess ? WTF? No better implementation by MS or Wix Toolset Team ? 
 2.  - I can add CustomActions to msi project, but somehow i need make sure that both CA execute one after another. second one rely on previous CA. Only then i can do something. Am i right to set Execution Point of both CA belongs to InstallSequence or it should be earlier ?

**Comment by oleg-shilo** [comment]
I have no answer for `#1`
For the `#2` I would go with a single CA at the appropriate time. Project events are specifically implemented for that.
If you go with CAs and want to ensure that the InstallSequence schedules then the only reliable way to ensure the order is implemented right is to test. The usual stuff. MessageBox in the CA body...

**Comment by Torchok19081986** [comment]
ok, thanks again. I got some feedback already. I got it to work. tempfolder set - successfull in beforeinstall event. Also successfull added external assembly NewtonSoft.Json for Serialize and Deselize file. Now to struggle with bring it to Progressbar Dialog. 
I need to use Microsoft.Deployment.WindowsInstaller Assembly , but it doesnt work. Somehow Windows.Dtf.Isntaller Package from Wix toolset works agains it. No Solution for that. 🤔🤔🤔

**Comment by oleg-shilo** [comment]
Windows.Dtf.Isntaller vs Microsoft.Deployment.WindowsInstaller
WiX4 vs WiX3

You need to build your WPF with the right version of the paclage

**Comment by Torchok19081986** [comment]
thought so. That means , i dont need installer dll from MS , only from Wixtoolset, right ? There is only one question , just for understanding. CurrentActionname that shows on InstallDialog, doesnt has some Mapping to Files, which MSI should deploy to targetsystem ?

**Comment by oleg-shilo** [comment]
>.... , only from Wixtoolset, right ?

Yes

>... CurrentActionname that shows on InstallDialog, doesnt has some Mapping to Files, 

I assume you are asking abut `ProgressDialog`. Not every action has a file name associated with. So the simple answer is - "n it does not have such a map". 

But some actions may have such mapping but how to extract it at runtime is a mystery. You saw that discussion link I gave in my prev post...

**Comment by Torchok19081986** [comment]
i got almost. I create 3 Files readme.txt, and 2 pdfs as Binary. Added it as Ressources to Installer, MSI Project. Extract to Path happens over own public Property. This Property assign value beforestart event and code to extract it 
```csharp

 public static void WriteResourceToFile(string path, byte[] fileName)
 {
     File.WriteAllBytes(path, fileName);
 }

```
where Path is your custom property.  Json Serialize and Deseliaze no needed, so is simpler to use and test. how do i now set Record ? all my efforts doesnt do anything. 
code in progressbar dialog
```csharp
 foreach (var file in filesToInstall)
 {
     string installPath = Path.Combine(session["TEMPFOLDER"], file.Value);
  
     CurrentAction = string.Format("{0}-{1}", installPath, file.Value);
     
     Thread.Sleep(1000*10);
 } 

```
doesnt work.

**Comment by oleg-shilo** [comment]
This may help:
https://github.com/oleg-shilo/wixsharp/blob/a01cca3de29fe6d6aa20827d3a1e5ac4589521ef/Source/src/WixSharp.Samples/Wix%23%20Samples/DTF%20(ManagedCA)/setup.cs#L70

**Comment by Torchok19081986** [comment]
morning, this work. Message appers on Record like it should. 
```csharp
  record[2] = string.Format("File: [" + installPath + "],  Directory: [" + file.Value + "],  Size: [6]");

```
Only thing i struggle now is, set currentAction to it. Create new Property and set it addionally or just binding from ViewModel doesnt work. String doesnt appear on ProgressBar  CurrentAction string.

**Comment by Torchok19081986** [comment]
After countless tries, i would ask for one thing. Do i have to somehow change record Table self? Via sql query and then read it ?
Actionname msi writes on Template in Progressbar, but no addionall string. Whatever i put it on additionally. 
Can i setrecord in MSI on filed 2 or 3 to my string and then read it ? just like https://www.pinvoke.net/default.aspx/msi.MsiRecordSetString.

**Comment by oleg-shilo** [comment]
Not sure about the table but you can always set a property. And then read this property when you format your message

**Comment by Torchok19081986** [comment]
Morning, some feedback on this. In before Install Event appears message with custom property . File : readme.txt , Directory : mypath. But in ProgressbarDialog not.
```csharp
string description = string.Format("File: [{0}], Directory: [{1}]", System.IO.Path.GetFileName(file.Value), System.IO.Path.GetFullPath(installPath));

session["CUSTOMRECORDMESSAGE"]  =  description ;
```
or
```csharp
session.Property("CUSTOMRECORDMESSAGE")  =  description ;
```
doesnt show anything. 
I use Method 
```csharp
 public MessageResult ProcessMessage(InstallMessage messageType, Record messageRecord, string currentStatus)
```

**Comment by oleg-shilo** [comment]
>  In before Install Event appears message with custom property .

I am not sure I understand that. `Project.BeforeInstall` is an event that has no messages. It has an event argument `SetupEventArg`. That's it.

But for the differences in the session context between project events (custom actions) and UI sequence (dialogs) see this [wiki section](https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#event-driven-custom-actions):

![image](https://private-user-images.githubusercontent.com/16729806/288575163-efbb4bbc-eacb-4de9-8f3f-d9b81677fbf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODcyMTYsIm5iZiI6MTcxNTU4NjkxNiwicGF0aCI6Ii8xNjcyOTgwNi8yODg1NzUxNjMtZWZiYjRiYmMtZWFjYi00ZGU5LThmM2YtZDliODE2NzdmYmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA3NTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMTI0ZDFmZGIwNjllNzE3MmJhMWMzZDU3NWY3Y2Y0YWZjMjQ1MWZmMDgyZGJjOGU4MDZjNmU2ZGU0YzdiYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.77Mfugn2a-32Uae2VZLYvKi-pt4w2PnnYVAA5TyJyN0)

**Comment by Torchok19081986** [comment]
thanks, again. I format record on before_install event and add it to custom property. Sofar OK. Now i want to bring it to progressdialog. BUT..... Regardless all my efforts it doesnt show it on any circumstances. 

![Screenshot 2 2024-05-13 101534](https://github.com/oleg-shilo/wixsharp/assets/25432729/6527a70d-2c95-450f-8583-329104e43b06)

I also satisfied if i can write it to listbox or any control. I just want to show it to user, thats it.

**Comment by oleg-shilo** [comment]
I see.

Have a look at the diagram I shared. You will see that the UI dialog is popped before the installation starts. Thus the session does not know what files you are installing. Yes, it collected the user selection (e.g. features) but at the start of the progress dialog, the user selection is not processed yet.

This is what you can do. 
- if your setup is straightforward and the user selection does not impact the files being installed but only the directories then you can simply read the file names that are going to be installed from the msi table.
- Alternatively, you can just use any IPC mechanism to notify the dialog about the file names from the BeforeInstall event handler. Remember, MSI hosts dialogs and CAs in different processes.

**Comment by Torchok19081986** [comment]
thought so. My Installpackage is straightforward. I would like to read msi property for files. How do i open database and query all files from current msi ? session.Database doesnt exists on progressabarDialog. Method GetProperty of MSI Database doenst found either.

**Comment by oleg-shilo** [comment]
I checked,  you are right. The DB is not prepared at that stage. You are back to square one. Then you have only one option - IPC. Sadly

**Comment by Torchok19081986** [comment]
ok, i write custom CA, that should do it, but i got error, also if syntax for msi db correct.

```csharp

 public static ActionResult ReadFilesTable(Session session)
 {
     try
     {
         // Open the MSI database
         using (var database = new Database(session["OriginalDatabase"], DatabaseOpenMode.ReadOnly))
         {
             // Query the Files table
             var filesView = database.OpenView("SELECT `FileName` FROM `Files`");
             filesView.Execute(null);

             // Read the properties of each record in the Files table
             Record record;
             while ((record = filesView.Fetch()) != null)
             {
                 for (int i = 0; i < 3; i++)
                 {
                     string fileName = record.GetString(i); // Assuming FileName is in column 1
                     session.Log($"File Name: {fileName}");
                 }
            
             }
         }

         return ActionResult.Success;
     }
     catch (Exception ex)
     {
         session.Log($"Error reading Files table: {ex.Message}");
         return ActionResult.Failure;
     }
 }

```

writes in Log 1603 
Info: Calling custom action SetupFileNames!SetupFileNames.CustomActions.ReadFilesTable
Info: Error reading Files table: Die SQL-Abfragesyntax ist ungültig oder wird nicht unterstützt.
Info: CustomAction ReadFilesTable returned actual error code 1603 but will be translated to success due to continue marking

**Comment by Torchok19081986** [comment]
it works on originaldatabase in CA. :-), juhu.

```csharp

[CustomAction]
public static ActionResult ReadFileTable(Session session)
{
    try
    {
        // Open the MSI database
        using (var database = new Database(session["OriginalDatabase"], DatabaseOpenMode.ReadOnly))
        {
            // Query the File table
            using (var view = database.OpenView("SELECT * FROM `File`"))
            {
                view.Execute();

                // Read the properties of each record
                Record record;
                while ((record = view.Fetch()) != null)
                {
                    string fileName = record.GetString("FileName"); // Get the FileName column
                    //string filePath = record.GetString("Directory_") + "\\" + fileName; // Get the Directory_ column and combine with FileName
                    session.Log($"File Path: {fileName}");
                }
            }
        }

        return ActionResult.Success;
    }
    catch (Exception ex)
    {
        session.Log($"Error reading File table: {ex.Message}");
        return ActionResult.Failure;
    }
}
```

**Comment by Torchok19081986** [comment]
because i couldnt change record to my needs, i did it in another way. Code is same like CA, but with some changes and it runs on Init() Call. 
![Screenshot 3 2024-05-13 135716](https://github.com/oleg-shilo/wixsharp/assets/25432729/b0ff9448-c5f4-4754-9b8b-e114f0040ea3)
output shows all files that embeded. This type of installfiles i see in many another installers.
