### ISSUE TITLE
SetVersionFromFileId not working for relative path in Managed Project Dir

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1525]
Hi
I am using Wix 4.0. I am trying to set version from file id as shown in below figure. Variables "installDir", "productName" & "sourceDir" possess valid path and values. However, until I set absolute path in second argument of new WixSharp.File constructor,
I keep getting error depicted in screenshot below.

Please help me in identifying what and where I am doing wrong?

(By the way, if I uncomment line no 39 for gg as new Id with sourceDir and subsequent path and give its id to SetVersionFromFileId(gg.Id), it still doesn't work and gives same error.)

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/bf8a439e-38eb-486e-bd82-2150d2427f24)

**Comment by oleg-shilo** [comment]
You can put in your build script `Console.WriteLine(Environemnt.CurrentDirectory)" to understand what is your currentdir during the msi build. Then you can understand how to adjust your `SourceBaseDir`. Most likely it is somehow not what you expect.

Also keep in mind that you can use an alternative syntax for setting the project ID:

```C#
project.Version = CommonTasks.Tasks.GetVersionFromFile("<path to your dll>");

```

**Comment by abskulkarni** [comment]
Hi @oleg-shilo ,
I am sorry I did not understand your comment above.
1. What is build script? Is it C# code ? Which place in code should I write Console.WriteLine?
2. I am not sure from where I should refer CommonTasks.Tasks? I am getting obvious compile error if I directly put your project.Version line in my code.

**Comment by oleg-shilo** [comment]
> What is build script? Is it C# code ?

Yes it is C# code that builds msi. Read more here https://github.com/oleg-shilo/wixsharp/wiki/VS2019-%E2%80%93-2022-Templates#msi-authoring-steps

> Which place in code should I write Console.WriteLine?

Any place. IE first action in the static main. You only want to understand when is the current dir when your script is executed by VS and why your paths do not work. 

> I am not sure from where I should refer CommonTasks.Tasks?

Common tasks are implemented in the `WixSharp.dll` assembly which you are getting with WixSharp package.
