### ISSUE TITLE
Azure pipeline build

### ISSUE THREAD

**Issue by chpo69** [oleg-shilo/wixsharp#1526]
When I build my wixsharp project in azurePipeline I get this error
`EXEC : error : `wix.exe` cannot be found. Ensure you installed it with `dotnet tool install --global wix``

How can I do to resolve this problem?
Thanks in advance

**Comment by oleg-shilo** [comment]
By installing the tool (wix.exe) with the `dotnet tool install --global wix`.

You just need to have this step in your YAML build script

**Comment by chpo69** [comment]
It works with the step below before the build
`
- task: DotNetCoreCLI@2
  displayName: 'Install wix as a dotnet tool -- dotnet tool install --global wix'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global wix'
`

THANKS

**Comment by chpo69** [comment]
Fixed

**Comment by oleg-shilo** [comment]
Great, 
Glad it's all sorted out.
And I also shared your solution in the Tips'n'Tricks section: https://github.com/oleg-shilo/wixsharp/wiki/Tips'n'Tricks#azure-pipeline-build
