### ISSUE TITLE
Install directory path changes when MSI is run second time through msexec command ADDLOCAL parameter

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1529]
Hi 
I have features in my MSI. I want to install them as per wish, like one feature at a time and I am using MSEXEC command with ADDLOCAL .
In my WixSharp project, I am taking install directory from config file and it is local path. Below is pictures.

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/84df2390-d21b-4cd2-b06b-5069bc4acc53)

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/5eafdedc-0924-4f37-9fa6-1ee01597669f)

Now I am using command like below to install features:

1) msiexec /i "F:\Abhijit\Misc\ConsoleApp1\IDRWix\Applications\IDRApplications.msi" /quiet ADDLOCAL=IDRCMD

2) msiexec /i "F:\Abhijit\Misc\ConsoleApp1\IDRWix\Applications\IDRApplications.msi" /quiet ADDLOCAL=IDRSERVICE

My problem is, for 1st msiexec command, it installs in expected directory i.e. in config file (F:\IDRInstall\IDRWithWix4.0)
But 2nd msiexec command somehow assigns "C:\ABSOLUTEPATH" as install directory and install IDRSERVICE feature under C:\ABSOLUTEPATH

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/807f5f8f-6bc4-4a24-b658-27682e9831b7)

Why is this behavior? Is there any wrong in Wix code?

**Comment by oleg-shilo** [comment]
Ah, I see.

The absolute path as installdir is not supported by WiX directly. Instead, the value of the installdir needs to be set as a custom action ar runtime.

WixSharp addresses this by allowing sepcifuing either a standard dir (e.g. progfiles) or an absolute dir in the `nerw Dir(...)` constructor and depending on the supplied value it schedules that required customer action. Though I am not entirely sure how this scheduling works in the multifeature scenario.

See this example:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/bcf089ba-945b-4bfa-8a5c-4a5516504fea)

Thus it is possible the somehow in your case the CA ` <CustomAction Id="Set_DirAbsolutePath" ` was not called or called correctly.

I suggest you look at the generated wxs and most likely it will have a clue.
