### ISSUE TITLE
Check box in Exit Dialog 

### ISSUE THREAD

**Issue by Dimazavrus** [oleg-shilo/wixsharp#153]
Hello!

Is any way in Wix# to add check box in Exit Dialog for WUI.WixUI_InstallDir, without using ManagedUI?

Something like this
http://wixtoolset.org/documentation/manual/v3/howtos/ui_and_localization/run_program_after_install.html

**Comment by oleg-shilo** [comment]
You can either add the required 'publish' XML from the `WixGeneratedEvent` or you can use `project.CustomUI` (have a look at "Skip_UIDialog" sample). 

But nothing can compare to the simplicity of the ManagedUI though. :)

**Comment by vmathtime** [comment]
Also you can use "WIXUI_EXITDIALOGOPTIONALCHECKBOX" property, which automatically add a checkbox at exit dialog (and "WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" to set text). You should only add properties to Project
