### ISSUE TITLE
Dialog Data transfer problem

### ISSUE THREAD

**Issue by JusterWork** [oleg-shilo/wixsharp#1531]
I want to do two things:
1. After the installation is complete, users can choose whether to start the installed program on the InstallExitDialog interface.
2. How to pass parameters in several dialog of the default template provided by wixsharp? A lot of things I tried didn't work.
For example: I set A value A on WelcomeDialog and then take the value of A in InstallExitDialog

I am using wixsharp-wix.WPF2.1.2, and the problem occurs in the dialog provided by the project template.

**Comment by oleg-shilo** [comment]
You can pass any data between dialogs the same way as between any objects in the .NET applications.

All dialogs belong to the same process so it's a usual .NET task.
If you do not want to pollute the dialogs with this data then you can have a global data repository:

```C#
static class RuntimeContext
{
    public static string Data1;
    public static string Data2;
    . . .
}
```

However, the majority of the usual context data that you might require (e.g. `base.Runtime.Session["PASSWORD"];`) is already embedded in the msi session object that is available in every dialog.

There are a few ways access ing your msi session from the dialog: 
```C#
Session session = this.MsiRuntime().MsiSession;
Session session = this.Runtime.Session.SesssionContext();
```

Many users prefer to have access to the `SetupEventArgs` object even though its normally available in the MSI project events but not in dialogs. But it can be easily constructed on-fly:

```C#
SetupEventArgs args = this.MsiRuntime().MsiSession.ToEventArgs();
```

**Comment by JusterWork** [comment]
oleg, thank you
