### ISSUE TITLE
Add Ignore Errors  a driver installer to Bundle

### ISSUE THREAD

**Issue by DanTaliaL** [oleg-shilo/wixsharp#1532]
Hi Oleg,

I have some .exe installers and my MSI installer in a bundle. However, if the user has a newer driver in the system, the driver in the bundle is not installed, and it returns error code 1, causing the bundle installation to stop with error code 1. How can I add a mechanism to ignore installer errors in the bundle?

**Comment by Torchok19081986** [comment]
morning, Had same problem. Try to add Vital Property and set it to false. Should work. This property seem to autoset to true if dont specific in msi package in Bundle.
