### ISSUE TITLE
Allow specifying the Group name when adding a FirewallException

### ISSUE THREAD

**Issue by Germs2004** [oleg-shilo/wixsharp#1533]
Please add a feature to WixSharp that allows us to specify the "Group" name when adding a new FirewallException rule.  It appears that WixToolkit has a [property named "Grouping"](https://wixtoolset.org/docs/schema/firewall/firewallexception/) for this, though I haven't tested it.

I suggest adding a new "Group" property that works like this:
```
FirewallException fwAllowRule1 = new()
{
    Feature = featureFirewallRules,
    Scope = FirewallExceptionScope.any,
    Name = "Contoso Web Server",
    Description = "This is my new rule to allow Contoso Web Server to connect.",
    Group = "Contoso"
};
FirewallException fwAllowRule2 = new()
{
    Feature = featureFirewallRules,
    Scope = FirewallExceptionScope.any,
    Name = "Contoso Data Server",
    Description = "This is my new rule to allow Contoso Data Server to connect.",
    Group = "Contoso"
};
```

screenshot of the Windows Firewall table showing the Group column that I'd like to be able to edit:
![image](https://github.com/oleg-shilo/wixsharp/assets/5519340/5e7d49ea-99ec-4573-a4c8-ea8f770be978)

As a workaround, I think the only way to do this currently is to not use the FirewallException object, but call a Powershell script instead, which supports specifying the Group.  Here is a Powershell command for that:
`New-NetFirewallRule -DisplayName "Contoso Web Server" -Direction Inbound -Program "C:\Contoso\webserver.exe" -Action Allow -Group "Contoso"`

**Comment by oleg-shilo** [comment]
WixSharp actually supports specifying WiX attributes that are not directly mapped to the WixSharp entities properties. Thus you can easily achieve the desired result by using a generic property `AtributesDefinition`:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/21572e3f-09f6-430f-82bd-a90d55258ff7)
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/3e68ade4-0242-43a3-95f5-7adbd842f230)

Note, this attribute is only available in WiX5 (not WiX4) so if you do not have it installed globally you might need to do it from the code for your specific project:

```C#

WixTools.SetWixVersion(Environment.CurrentDirectory, "5.0.0");

var project = new Project("MyProduct", . . . 
```
But I added the dedicated property so it will be available in the very next release.
