### ISSUE TITLE
Execute CA which needed Powershell in Version 5.1

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1535]
Hallo, i write currently Bundle that needs to execute CA where i have to check if any Powershell Version installed and if yes, get version of it. 
CA is relativ simple. Get Envriroment.GetEnvironmentVariable("WINDIR")\powershell.exe works fine, but how do i get output of this 
version send back my bundle ? 
I can get output from powershell by set in process args to $PSVersionTable , but cant get add or show it to bundle installer during runtime. 
Any idea i would appreaciate.

**Comment by Torchok19081986** [comment]
i created test wpf project in NET 8.0 and want to show if somehow possible. Is harder as i thought. 
![Screenshot 2024-05-15 152703](https://github.com/oleg-shilo/wixsharp/assets/25432729/7c15e014-53ee-4ee8-a4b4-b3de583184b0)
need all packages from nuget to execute following code

```csharp

using PowerShell ps = PowerShell.Create();
ps.AddScript("$PSVersionTable.PSVersion");
try
{
    var result = ps.Invoke();
    if (ps.HadErrors)
    {
        // Handle errors
        MessageBox.Show("Error executing PowerShell command");
        return;
    }

    if (result.Count > 0)
    {
        var psVersion = result[0].Properties["Major"].Value.ToString() + "." +
        result[0].Properties["Minor"].Value.ToString();

        MessageBox.Show("PowerShell version: " + psVersion);

        //Bootstrapper.Engine.StringVariables["POWERSHELLVERSION"] = psVersion;
    }
    else
    {
        MessageBox.Show("Result is 0");
    }
}
catch (Exception ex)
{
  
    MessageBox.Show("PowerShell is not installed or cannot be accessed: " + ex.Message);
}

```
most annoying fact, all packages shoudl have same version major and minor installed on targetsystem, and if not it cant find powershell.exe 
😵‍💫😵‍💫😵‍💫.

**Comment by oleg-shilo** [comment]
Great, txs for sharing.

And if someone wants only a simple command execution then this can be done even like this:

```C#

RunPowerShellScript("Get-Desktop 1 | Switch-Desktop");
. . .

static void RunPowerShellScript(string command)
{
    var startInfo = new ProcessStartInfo
    {
        FileName = "powershell.exe",
        Arguments = $"-NoProfile -ExecutionPolicy unrestricted -Command \"{command}\"",
        UseShellExecute = false,
        CreateNoWindow = true
    };
    Process.Start(startInfo);
}
```

**Comment by Torchok19081986** [comment]
thanks again, @oleg-shilo . One thing, works until powershell version 5.1. In Version later than 5.1 powershell.exe was named pwsh.exe .  MS has  added NET Framework >=5.0 into powershell, for better using .

**Comment by oleg-shilo** [comment]
Noted
