### ISSUE TITLE
Unable to set property value from Session Object in a Custom WPF Dialog

### ISSUE THREAD

**Issue by Aaswin1996** [oleg-shilo/wixsharp#1539]
Adding my Project too
[Uploading ScoutInstaller.zip…]()
I want to set the MODE property based on the radio button selected but as soon as the RADIO button selected property is HIT my installer abruptly vanishes 

ModeDialog.xaml.cs Code : 
`
    namespace WixSharp.UI.WPF
    {
        public partial class ModeDialogView : WpfDialog, IWpfDialog
        {
            ManagedForm host;
            ISession session => Host?.Runtime.Session;
            public ModeDialogView()
            {
                InitializeComponent();
            }
    
            public void Init()
            {
                ViewModelBinder.Bind(new ModeDialogModel { Host = ManagedFormHost }, this, null);
            }
    
            public ManagedForm Host
            {
                get => host;
                set => host = value;
            }
            private void GoPrev_Click(object sender, System.Windows.RoutedEventArgs e)
            {
                
            }
    
            private void GoNext_Click(object sender, System.Windows.RoutedEventArgs e)
            {
                MessageBox.Show("Clicked on Go next");
                try
                {
                    MessageBox.Show("Setting Property");
    
                    session["MODE"] = "CRC";
                    
                }
                catch(Exception ex) {
                    MessageBox.Show(ex.Message);
                    MessageBox.Show(ex.StackTrace);
                }
                
                Host?.Shell.GoNext();
            }
    
            private void Cancel_Click(object sender, System.Windows.RoutedEventArgs e)
            {
                
            }
    
            private void EnterpriseButtonChecked_Checked(object sender, System.Windows.RoutedEventArgs e)
            {
               
                MessageBox.Show("Enterprise Clicked");
                session["MODE"] = "ENTERPRISE";
                
            }
    
            private void CRCButtonChecked_Checked(object sender, System.Windows.RoutedEventArgs e)
            {
                MessageBox.Show("CRC Clicked");
                session["MODE"] = "CRC";
            }
        }
    
        public class ModeDialogModel : Caliburn.Micro.Screen
        {
            public ManagedForm Host { get; set; }
    
            public BitmapImage Banner => Host?.Runtime.Session.GetResourceBitmap("WixUI_Bmp_Banner").ToImageSource();
    
            public void GoPrev()
                => Host?.Shell.GoPrev();
    
            public void GoNext()
                => Host?.Shell.GoNext();
    
            public void Cancel()
                => Host?.Shell.Cancel();
        }
    }
`
ModeDialog.Xaml Code : 
`<wixsharp:WpfDialog
    x:Class="WixSharp.UI.WPF.ModeDialogView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:wixsharp="clr-namespace:WixSharp.UI.WPF;assembly=WixSharp.UI.WPF"
    d:DesignHeight="200"
    d:DesignWidth="500"
    DialogTitle="[ProductName] Setup"
    mc:Ignorable="d">
    <Grid x:Name="Root">
        <Grid.RowDefinitions>
            <RowDefinition Height="60" />
            <RowDefinition Height="*" />
            <RowDefinition Height="53" />
        </Grid.RowDefinitions>
        <Border
            Margin="-1,-1,-1,0"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Stretch"
            Background="White"
            BorderBrush="Gray"
            BorderThickness="1">
            <Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="80" />
                </Grid.ColumnDefinitions>
                <Image
                    x:Name="Banner"
                    Grid.ColumnSpan="2"
                    HorizontalAlignment="Stretch"
                    VerticalAlignment="Stretch" />
                <StackPanel Margin="9">
                    <TextBlock
                        Grid.Column="0"
                        Background="White"
                        FontSize="12"
                        FontWeight="Bold">
                        [CustomDlgTitle]
                    </TextBlock>
                    <TextBlock
                        x:Name="DialogDescription"
                        Margin="17,5"
                        VerticalAlignment="Stretch"
                        Background="White"
                        TextWrapping="WrapWithOverflow">
                        [CustomDlgTitleDescription]
                    </TextBlock>
                </StackPanel>
            </Grid>
        </Border>
        

        <Border
            Grid.Row="2"
            Margin="-1,0,-1,-1"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Stretch"
            BorderBrush="Gray"
            BorderThickness="1">

        </Border>

        <RadioButton x:Name="CRCButtonChecked" 
            Content="CRC" HorizontalAlignment="Left" Margin="21,52,0,0" Grid.Row="1" VerticalAlignment="Top" Checked="CRCButtonChecked_Checked"/>
        <RadioButton x:Name="EnterpriseButtonChecked"
            Content="Enterprise" HorizontalAlignment="Left" Margin="21,72,0,0" Grid.Row="1" VerticalAlignment="Top" Width="94" Checked="EnterpriseButtonChecked_Checked"/>
        <Border
    Grid.Row="2"
    Margin="-1,0,-1,-1"
    HorizontalAlignment="Stretch"
    VerticalAlignment="Stretch"
    BorderBrush="Gray"
    BorderThickness="1">
            <StackPanel
        HorizontalAlignment="Right"
        VerticalAlignment="Center"
        Orientation="Horizontal">
                <Separator Width="10" Opacity="0" />
                <Button
            x:Name="GoPrev"
            Height="23"
            MinWidth="73" Click="GoPrev_Click">
                    [WixUIBack]
                </Button>
                <Separator Width="10" Opacity="0" />
                <Button
            x:Name="GoNext"
            Height="23"
            MinWidth="73" Click="GoNext_Click">
                    [WixUINext]
                </Button>
                <Separator Width="20" Opacity="0" />
                <Button
            x:Name="Cancel"
            Height="23"
            MinWidth="73" Click="Cancel_Click">
                    [WixUICancel]
                </Button>
                <Separator Width="10" Opacity="0" />
            </StackPanel>
        </Border>
        <TextBlock HorizontalAlignment="Left" Margin="21,24,0,0" Grid.Row="1" TextWrapping="Wrap" Text="Select Mode Of Installation" VerticalAlignment="Top" Width="229"/>
    </Grid>
</wixsharp:WpfDialog>`

**Comment by Torchok19081986** [comment]
hiho, i had same issue. AFAIK you have to add your public property to MSI in Installer.  If you use simple ManagedProject 
add it like project.AddProperty(new Property("MODE","Empty")), should work. But for BA Installer you have to add it as  well for MsiPackage. Unlikwise, MSI want always all properties denified before, only then you can assign value to it at runtime.

**Comment by Aaswin1996** [comment]
> hiho, i had same issue. AFAIK you have to add your public property to MSI in Installer. If you use simple ManagedProject add it like project.AddProperty(new Property("MODE","Empty")), should work. But for BA Installer you have to add it as well for MsiPackage. Unlikwise, MSI want always all properties denified before, only then you can assign value to it at runtime.

I am already doing that : 
![image](https://github.com/oleg-shilo/wixsharp/assets/33788096/1198e87b-7f5b-46b7-ae18-4a51000b30ce)

**Comment by Aaswin1996** [comment]
@oleg-shilo  @Torchok19081986  Can someone point me in the right direction ?

**Comment by Torchok19081986** [comment]
morning, hm, strange. You can try , just  for example, in CA and add it in session["MODE"] = "Whatever". See ouput in beforeinstall event - first option.
second option - Create ManagedAction CA , when.before, check.ignore, Condition.NotInstalled, Step.InstallSequence. Add also MessageBox with session["MODE"] in CA. If messagebox comes with your assign value, something wrong in your Installer.
