### ISSUE TITLE
Asking for reboot after unistalling

### ISSUE THREAD

**Issue by artemishenkov** [oleg-shilo/wixsharp#1540]
Hi,  I have written an installer that installs a Windows Service and when I uninstall it I get this reboot message 
![image](https://github.com/oleg-shilo/wixsharp/assets/53975397/598139f8-b4b2-4f26-8fa5-384ccc21ca66)
But Windows Service and other folders are uninstalled successfully without any reboot is there any chance I can suppress this message? 
I would appreciate any help. Thank you.

**Comment by oleg-shilo** [comment]
Yes indeed. The uninstalling services only become complete after reboot. Between uninstalling and rebooting the service is kinda in the "marked for deletion state" (kinda undead).
You cannot start it and you cannot delete it from the registry. Only reboot transfers it to the final "deleted" state.

Thus while suspending the message box is theoretically possible, it does not really brings significant value.
