### ISSUE TITLE
Digital Signature with relative certificate path not working

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1541]
Hi @oleg-shilo 
Please refer below screen shot. I am trying to sign MSI with a certificate located in path shown in screenshot below.
As you can see, Path.GetFullPath returns exact same and correct path to p12 certificate file. But Digital Signature is failing with error seen in error list.
However, if I give absolute path in DigitalSignature's pfxFilePath property (which is exactly same what Path.GetGullPath returns), it is succeeded.

1. Can you please help in resolving this where I can give a relative path to certificate?
2. I want to use same relative path approach for licence file. Will this work for it also?

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/bc2a5a25-835d-4052-b4a4-f439658fa66a)

**Comment by oleg-shilo** [comment]
I think the problem is caused by the SourceBaseDir being set to some location. 
All relative paths are resolved against `project.SourceBasedDir`, which by default is a currentdir of the current process.

Thus you will need to find a way to adjust your relative path against your `Constants.SOURCEDIR`

**Comment by abskulkarni** [comment]
> I think the problem is caused by the SourceBaseDir being set to some location. All relative paths are resolved against `project.SourceBasedDir`, which by default is a currentdir of the current process.
> 
> Thus you will need to find a way to adjust your relative path against your `Constants.SOURCEDIR`

Hi @oleg-shilo 
But Path.GetFullPath resolves to absolute path already (which is also proved working if I give whole absolute path in pfxPath.
So it is confusing me.
1. Do you mean to say Path.GetFullPath gets resolved relative to SourceDir when MSI is being run?
2. If yes to 1, is there a way I can use a public property for certificate path & set property at some event so that MSI can resolve digital signature?

**Comment by abskulkarni** [comment]
> > I think the problem is caused by the SourceBaseDir being set to some location. All relative paths are resolved against `project.SourceBasedDir`, which by default is a currentdir of the current process.
> > Thus you will need to find a way to adjust your relative path against your `Constants.SOURCEDIR`
> 
> Hi @oleg-shilo But Path.GetFullPath resolves to absolute path already (which is also proved working if I give whole absolute path in pfxPath. So it is confusing me.
> 
> 1. Do you mean to say Path.GetFullPath gets resolved relative to SourceDir when MSI is being run?
> 2. If yes to 1, is there a way I can use a public property for certificate path & set property at some event so that MSI can resolve digital signature?

Hi @oleg-shilo
I somehow resolved it by doing below steps, but I am still unclear about concept of relative path being used in WixSharp.

1. I pasted licence.rtf & certificate file on the path where MSI gets generated.
2. In the script, I took Path.GetFullPath of those files, like, Path.GetFullPath("licence.rtf") & Path.GetFullPath("certificate.p12") in respective variables licencePath & certificatePath.
3. I used these variables in project.LicenceFile & DigitalSigntaure respectively.
4. MSI got compiled and it got signed as well.

Please refer below screen shot for code changes.

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/89dd4728-ce4a-42e0-b430-df8f20606db0)

Please refer below screen shot where I pasted files

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/09309b78-696c-4399-b2e7-d0c548c77efb)

Question : Can you please explain this concept of relative path as I am still confused why and how it worked?

**Comment by oleg-shilo** [comment]
You managed to solve it because you switched to an absolute path. Your process's current directory has no impact on absolute paths. Life is good. :)

However when you were using relative paths then they are always relative to the process current dir.

```
absolute_path = curr_dir + relative_path
```

When you set `SourceBaseDir` you are saying to to WixSharp compiler "during the build, do not use currentdir but SourceBaseDir for all MSI input files relative paths"

```
absolute_path = SourceBaseDir + relative_path
```
This will be happening during the execution of WiX compilers (`project.BuildMsi()` call) but not when you are calling your `Path.GetFullPath(...)`
