### ISSUE TITLE
How to show all installing Files in control , for example userconrol or listbox, in Bundle WPF C#

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1544]
Morning, i would like to show alle files from MSI in Bundle. I seen Installer from DevExpress . For Example screenshotfoto 
![Screenshot 2024-05-24 084147](https://github.com/oleg-shilo/wixsharp/assets/25432729/81ee5d79-2c0b-498c-b3b4-64418af23124)

Any Idea how to get all files in MSI in Bundle ? 
Many thanks for advices and i would like to get step-by-step guidance.

**Comment by oleg-shilo** [comment]
This can only be achieved by analyzing the msi file `File` table.

```C#
MsiInterop.MsiOpenDatabase(msiFile, MsiDbPersistMode.ReadOnly, out db));
. . .
```
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/b44c6ca2-d4e6-424a-9020-78f2d915c098)

**Comment by oleg-shilo** [comment]
You can. 
I assumed you wante dto access this information a runtime, not at compile time. The dialog on our screenshot is a runtime progress dialog. 

But yes you can just use `project.AllFiles`. The result may be somewhat inaccurate though if you allow user not to install some files aggregated in the `Fearure`. But it will be as inaccurate as analyzing msi anyway.
