### ISSUE TITLE
Explicitly assign component Id in WXS through C# script

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1547]
Hi @oleg-shilo 
I am building WXS through script and build WXS using wix.exe to get final MSI.
However, My components get automatically assigned a very long Id due to long names of components involved. Unfortunately, I cannot reduce component names.
So is there facility to control or explicitly assign component ID?

**Comment by abskulkarni** [comment]
Doesn't help. My component names are exceeding 72 characters. So my custom logic cannot have file name, dir hash etc.

What logic I want is, just take associated feature name and post fix with auto incremented counter. E.g. if feature name is MainFeature then its component ids will be "Component.MainFeature.**1**", "Component.MainFeature.**2**" & so on..

**Comment by oleg-shilo** [comment]
You can assign the comp Id directly from code if you have to:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/b2cfd5a9-d339-4768-bd4d-58e42afe98b7)

**Comment by abskulkarni** [comment]
Hi @oleg-shilo 
I am not adding individual file in a feature directory. As I showed earlier, I am using Files objects with various file extensions as shown below. So in directory, I want to copy all exe, dll, config & xml files from source path. 
How can I set custom component id for each these files?

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/1db25a09-b971-47fc-b835-29d2f4585489)

**Comment by oleg-shilo** [comment]
You can always specify some extra steps when processing the file:

```C#
new Files(@"..\Release Folder\test\*.exe", x => x.PathGetFileName() != "app-I-do-not-like.exe")
                    {
                        OnProcess = file =>
                        {
                            file.ComponentId = "whatever",
                            file.OverwriteOnInstall = true;
                        }
                    },
```

Though, do not forget, that you do not have to rely on WixSharp algorithms only. You have the all power of .NET/C#. 

```C#
var destDir = project.Dirs.FirstOrDefault();
foreach (var filePath in System.IO.Directory.GetFiles(@"..\Release Folder\test", "*.dll"))
    destDir.AddFile(new File(filePath)
    {
        ComponentId = "whatever"+Guid.NewGuid().ToString("N"),
    });
```

**Comment by abskulkarni** [comment]
> Owner

Thanks @oleg-shilo . That should resolve my problem.

**Comment by oleg-shilo** [comment]
Don't forget that you need to use your specific criteria to find the directory you want to add:
 
 ```C#
 var destDir = project.Dirs.FirstOrDefault(x=>x....your condition here);
 ```
