### ISSUE TITLE
Change MSI properties to be viewed on "Windows Properties" screen

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1549]
Hi @oleg-shilo 

I want to merge setup.exe properties in below screen shot to be seen in MSI properties. This I need to do through Wixsharp C# script.

1. Like MSI properties should show File Description, Product version, File Version, copyright etc
2. Title property of MSI file is stuck to "Installer Database". How to change that?

![image](https://github.com/oleg-shilo/wixsharp/assets/23351437/d9ecb23c-e334-402b-9ac1-9c07232b185a)

**Comment by oleg-shilo** [comment]
WixSharp facilitates the compilation of the setup definition (wxs) into msi file with WiX compiler (candle/light or wix). But WixSharp is not involved in setting up the msi file properties.

But if you find that somehow it can be controlled with WiX jusrt share it here and I will guide you with triggering the desired behaviour through WixSHarp.

TBH, I am not sure that what you are asking is possible.
