### ISSUE TITLE
Conditional uninstallation - Uninstall only if registry value is zero

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1562]
Hi @oleg-shilo 
I want to uninstall my product based on one registry value to be zero or not. So while uninstalling, this registry value should be checked. If it is zero, only then uninstallation should continue else exit without uninstalling.

1. Is it possible?
2. If it is to be done with any custom action, can you please share any sample code?

**Comment by oleg-shilo** [comment]
Yes it is 
Have a look at this sample:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/5635f630-8c4c-4cb3-be70-839172e853e5)

The event handler `project.Load += project_Load;` is invoked on both install and uninstall. You can check the registry from there:

```c#
static void project_Load(SetupEventArgs e)
{
    if (e.IsUninstalling)
    {
        var registryValue = 0; // read the value from the registry
            
        if(registryValue == 0)
            e.Result = ActionResult.UserExit;
    }
```
