### ISSUE TITLE
Some questions about registry

### ISSUE THREAD

**Issue by Dimazavrus** [oleg-shilo/wixsharp#157]
Hello, Oleg.

I have such a situation:
Installer write into registry some keys with values. My application write some new keys and change values inserted by installer.

1. Is any solution to remove key from registry on uninstall if this key was added by application?

2. is NeverOverwrite attribute works for RegValue? 
I'm trying to use 
NeverOverwrite = true, AttributesDefinition = "Component:Permanent=yes"
but Installer rewrite value on application upgrade.

Thanks.

**Comment by oleg-shilo** [comment]
1. If it is an applicator created key then MSI doesn't know about it. Probably a custom action or _InstallComplete_ event is the best option you have.

2. This question is really about WiX/MSI support for RegValue. I am not sure how exactly it protects the registry key from writing. But... just in case verify that the attributes successfully created in the .wxs file. I want to eliminate Wix# generation problem.
