### ISSUE TITLE
set Wix Toolset version for WixSharp

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1570]
Hallo, i have trouble to add or set v4 version to current project. I create bootstrapper project and would like do some tests, but it always compiles with v3.12, not v4. My Visual Studio says, wix v4.0.5+b9b2f1b4 is installed. Any possibility to add v4 instead of v3 compiles? For some reasons, i have to  keep both version. I cant unisntall v3.12, unfortunatelly. I am very thankfull for any advice or code line for wix sharp latest version.

**Comment by oleg-shilo** [comment]
Is it possible that you accidently used WixSharp (WiX3) template?

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/af572155-301e-4085-8890-5e2edca37496)

**Comment by Torchok19081986** [comment]
hallo, i have to say, "No". i used template for v4, but wxs file comes out with schema of v3. Dont know why. I would as well check again my template and output wxs file.

**Comment by oleg-shilo** [comment]
> Example is in wix toolset v3. Now i wanted to create same output in wixsharp. 

Then you need to use WiX3 WixSharp based template.
Look at the WixBootstrapper_UI sample. It shows how to set external BA (e.g. your WixWpfWizardBA):

```C#
bundle.Application = new ManagedBootstrapperApplication(@"Samples\Bootstrapper\WiX4-Spike\Bundle1\WixToolset.WixBA\bin\Debug\net472\win-x86\WixToolset.WixBA.dll");

```

**Comment by Torchok19081986** [comment]
many thanks. Last question here : can i use also Template for v4 or there a reasons agains it ?
