### ISSUE TITLE
Duplicate component IDs are added when shortcuts are added 

### ISSUE THREAD

**Issue by Aaswin1996** [oleg-shilo/wixsharp#1571]
![image](https://github.com/oleg-shilo/wixsharp/assets/33788096/e66604a1-16df-4452-9ab1-b27aff483a4d)
![image](https://github.com/oleg-shilo/wixsharp/assets/33788096/0e7b0a9e-0fee-49b9-acd8-7c1f0bbeb5dd)

Adding shortcuts lead to duplicate folder ids .The compnents for these shortcuts are added with similar ids .

**Comment by oleg-shilo** [comment]
Thank you for reporting. I will investigate.

**Comment by Aaswin1996** [comment]
> Thank you for reporting. I will investigate.

Any workaround in the meantime @oleg-shilo  ?

**Comment by oleg-shilo** [comment]
You can directly fix the IDs in the wxs.

See InjectXML sample.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/01e47a8c-f3d1-4231-baec-910678e47503)

**Comment by oleg-shilo** [comment]
Can you please share a "HelloWorld" style sample that demonstrates the problem?
And in general, please share the code rather than an image. It makes it easier for me to replicate the problem.

Just adding the `FileShortcut`s alone does not trigger the problem.
