### ISSUE TITLE
Fonts are not installed for all users

### ISSUE THREAD

**Issue by kotsopoulosd** [oleg-shilo/wixsharp#1572]
Hi,

I currently new to the WixSharp and I am trying to install an msi that uses some fonts. Below is a sample of the code I use.
![image](https://github.com/oleg-shilo/wixsharp/assets/16580384/90e94fd0-6d05-4aee-b8ae-534eb3a8b13f)

I set also the install scope "PerMachine" and during installation I clicked "Run as Administrator" but again after installation the fonts were missing for other users and had to install them manually
I came across to this article :
https://blog.flowpoint.ai/post/v2/solved-installscopepermachine-in-wix-makes-no-difference/

Am I missing something ? 

Thanks in advance

**Comment by Torchok19081986** [comment]
hiho, there is example of wixsharp , how to install it. I had same issue. solved by adding codeline 
```csharp
new File("FreeSansBold.ttf") { AttributesDefinition="TrueType=yes"}));
```
works for me.

**Comment by kotsopoulosd** [comment]
The constructor of the FontFile does exactly the same thing if you check the source code.

![image](https://github.com/oleg-shilo/wixsharp/assets/16580384/748054eb-9f58-4fb5-a063-24a9f67110ec)

The installScope = PerMachine, thought sets this value.

I will try your way to see if this solves the issue but inside the sample there are two ways to set the fonts. 
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Install%20Font/setup.cs

**Comment by Torchok19081986** [comment]
hm. May be. I solved my issue with second way. At First it doesnt work. After i set AttributeDef , it works.

**Comment by kotsopoulosd** [comment]
FYI 
@Torchok19081986, both cases are working actually fine actually. I noticed that the font installation fails per machine only if the license of the windows machine is outdated/expired and/or if there are any restrictions for this machine that do not allow such actions.
