### ISSUE TITLE
Tags are wrong in git

### ISSUE THREAD

**Issue by smaudet** [oleg-shilo/wixsharp#1577]
I think your automated pipeline is broken.

Your tags are broken in git, all the latest (2.1.7.0, 2.2.0.0) all point at master instead of their respective branches.

I have been having some issues with the compiler e.g. and been unable to follow along in the source code. Recommend you fix so the tags actually point at the correct commits.

**Comment by oleg-shilo** [comment]
Definitely. Thank you for letting me know.

**Comment by oleg-shilo** [comment]
Done
