### ISSUE TITLE
Change Registrykeys on Uninstall

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#158]
Hi Oleg,
i have some Problems and hope that you can give me some help. My Problem is that i need change Registrykeys in Windows during uninstalling. 
I tried to start regedit.exe to change key and also Tasks.ImportRegFile, but both are not working. 
Execution is in Project.AfterInstall event like :  if (e.IsUninstalling) ... Is there limitation to do that during uninstall myproduct or how can i do this. I really need help here.

**Comment by oleg-shilo** [comment]
_regedit.exe_ may fail if you are not elevated. 
_Tasks.ImportRegFile_ does not create registry keys but a RegValue objects at Wix# compile time.
'Project.AfterInstall event like : if (e.IsUninstalling)' is a good approach. I see no real limitations. It also runs already elevated.

**Comment by Torchok19081986** [comment]
Ok. Thanks for answer. user is "One and only Administrator" where UAC - User Account Control - deactivated. Im going to try regvalue objects.

**Comment by Torchok19081986** [comment]
Hi Oleg, i tried you suggestion with RegValue objects in Wix#, but it doenst work also.  I thought , im going to try customaction during uninstall. I dont know what kind of CustomAction: ManagedAction or PathExeFileAction or something else. I going to try all of them und give some feedback.

**Comment by oleg-shilo** [comment]
> ...i tried you suggestion with RegValue objects in Wix#... 

Sorry, I did not suggest that :)
In fact I said that creation of RegValue will not help you with the creation of the of the registry keys. Most likely `PathExeFileAction` will follow the same fate.

My suggestion was to use  `Project.AfterInstal` routine to add reg key manually (e.g. C# code). 

Sorry if I didn't explained it properly.

**Comment by Torchok19081986** [comment]
i tried add regkey manually, but PathExeFileAction doesnt work. I have .reg File and i should import this in registry. Current i dont know solve for my problem. I going to search.

**Comment by oleg-shilo** [comment]
`PathExeFileAction` is typically involved in other use-cases. This is what I meant "manually":
```C#
project.AfterInstall += project_AfterInstall;
...
static void project_AfterInstall(SetupEventArgs e)
{
    if (e.IsUninstalling)
    {
        using (var key = Registry.CurrentUser.CreateSubKey("Names");  
        {
            key.SetValue("Name", "Isabella");  
        }
        // or
        string reg_file = <location of your reg file>;
        Process.Start("regedit.exe", $"\"{reg_file}\"");
    }
}
```

**Comment by Torchok19081986** [comment]
Thanks for example anyway. I would try it in next few hours and give feedback.

**Comment by Torchok19081986** [comment]
Hi Oleg. Here is my feedback for your example. After try it in uninstall and looks like your solution would be work, but there is always question from regedit.exe if i would like to import this .reg file and after click "OK" nothing happen. I also tried regedit.exe with "/s " parameter, but its no use. curiously /e for export works fine. Any Idea ?

**Comment by oleg-shilo** [comment]
Is it possible that it goes to the "roaming" sub-key on x64? 

Regedit is reliable and tested by millions. It's unlikely it is failing. May be the input is not what it supposed to be?

**Comment by Torchok19081986** [comment]
this works with cmd.exe like regedit.exe /s myregfile.reg, but it doesnt work in uninstall. my import Regfile looks like 
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Update\Policy]
"EnableJavaUpdate"=dword:00000001
"NotifyDownload"=dword:00000001
"NotifyInstall"=dword:00000000
"Frequency"=dword:01030000
"UpdateSchedule"=dword:00000014

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Update\Policy\jucheck]
"UpdateSchedule"=dword:00000013
"Frequency"=dword:01160000
"UpdateMin"=dword:00000037

**Comment by oleg-shilo** [comment]
I am not sure about accuracy of your test. I just did a quick one and everything seems to work as expected.

[test.zip](https://github.com/oleg-shilo/wixsharp/files/1310598/test.zip)

 The attached test eliminates mistakes with the location of reg file and roaming. Use it as a starting point.

**Comment by Torchok19081986** [comment]
Hi Oleg. Thanks for answer. i tested it already. works with some changes. looks like 
string reg_file = @"pathtoreg\test.reg";
            Process.Start("regedit.exe","-s " + reg_file + ""); 
with this work. Before was not complied "There is $ sign cannot be compiled."

**Comment by silentnightwalk** [comment]
Isabella is a very good name choice.
