### ISSUE TITLE
Shortcut "Target" produces unexpected results for many supported WiX environment constants

### ISSUE THREAD

**Issue by S1r0hub** [oleg-shilo/wixsharp#1580]
When creating a shortcut (e.g. ExeFileShortcut), adding constants to the target path like this: "[WindowsFolder]AnyApp.exe" does not work properly.
I found that the normalization function "NormalizeWixString" (from Extensions.cs) only works as expected for the constants explicitly mentioned in it (e.g. SystemFolder), as those are replaced in prior to the following line and restored afterwards:
```c#
.Replace($"[{key.Trim('%')}]", Compiler.EnvironmentConstantsMapping[key])
```

The line that seems to cause these issues was added with commit https://github.com/oleg-shilo/wixsharp/commit/fa97638c3ae639436b5351613a7e14218be87213 in June 2019.
It replaces known constants like "[WindowsFolder]" with the string from the mapping, which is just "WindowsFolder", and therefore, square brackets are removed.
As a result, for a target path like `[WindowsFolder]AnyApp.exe`, the generated .wxs file will contain the invalid shortcut path `WindowsFolderAnyApp.exe`.

Based on comments like "Protect ..." and "restore ..." in the normalization function, I wonder if this is really the desired behavior.
Thanks :)

**Comment by oleg-shilo** [comment]
Thank you for such a detailed report. I will investigate.

**Comment by oleg-shilo** [comment]
You were right. The original fix was incomplete.
Thank you for doing the research. Appreciate it.
Fixed now. It will be available in the very next release.

**Comment by S1r0hub** [comment]
Great to hear!
Thanks for the quick fix.

**Comment by S1r0hub** [comment]
Tested it. Thanks again for fixing.
Closing this issue now :)
