### ISSUE TITLE
> since I know now root cause of my issue, how can I include sub folders in my new Files constructor or somewhere in Files

### ISSUE THREAD

**Issue by abskulkarni** [oleg-shilo/wixsharp#1584]
> since I know now root cause of my issue, how can I include sub folders in my new Files constructor or somewhere in Files 

Not sure I know what you mean, but `Files` will automatically pick all subfolders found.
However if you are asking about `new Files( new Dir(...` then no. `new Dir` can only be inside of te parent dir. Exactly as in the file system.

_Originally posted by @oleg-shilo in https://github.com/oleg-shilo/wixsharp/issues/1578#issuecomment-2219957171_
            

Hi @oleg-shilo 
**Here the issue is as below:** (It will be descriptive explanation about source directory structure. So sorry in advance)

**Source Dir structure :** I have source directory say named "Database". It has got three sub-folders say "SQL", "MYSQL" & "UPGRADE". 
Now these sub-folders may have further unlimited number of sub-folders depending on upgrades happening or DB technology being introduced. But in all these sub-folders (level unpredictable) will have .sql files, .dacpac files. Please note, parent/base "Database" folder itself does not have any .sql or .dappac file.

**Problem I face :** Now through WixSharp MSI, I want to create exact folder structure as that of source directory structure above. There I face difficulty. I have a feature named "Database" in Wix# code which is supposed to install "Database" folder with exact structure as that of source dir. But MSI creates empty folder named "Database" when run, **if "Database" feature is not selected.**

**Workaround I apply is:** Place an empty test.sql file in "Database" source base folder itself & compile MSI project. This way I get around empty folder situation. Means, it does not create empty "Database" folder when feature is not selected during installation. **But when selected**, it also copies this extra test.sql which is not needed,

**Comment by abskulkarni** [comment]
Hi @oleg-shilo 
Can you please guide me if there is any solution to my issue above?

**Comment by oleg-shilo** [comment]
As @smaudet  suggested, manually recursing through the folders is the most powerful option you have. But it's costly. You have to do recursion heavy lifting:

```C#
// pseudo code
foreach(var file in Directory.GetFiles("<your root dir>", "*", SearchOptions.AllFiles))
{
      string instalDir = file.GetDirName().MakeRelativeTo(project.SourceDir);
      Dir wDir = project.FindOrCreateDir(installDir);
     
      wDir.AddFile(new File("<whatever feature you want>", file));
}
project.Build.Msi();
```

However, ... dId you try the suggestion I posted in the original thread?  

```C#
AutoElements.SupportEmptyDirectories = CompilerSupportState.Disabled;
Compiler.AutoGeneration.IgnoreWildCardEmptyDirectories = true;
```
