### ISSUE TITLE
Cannot use: "CommonAppDataFolder".AsWixVarToPath() when installing wixsharp nuget package

### ISSUE THREAD

**Issue by jonreis** [oleg-shilo/wixsharp#159]
The compiler error that is reported is:

 error CS0121: The call is ambiguous between the following methods or properties: 'WixSharp.Extensions.AsWixVarToPath(string)' and 'WixSharp.Extensions.AsWixVarToPath(string)'

This is due to the way the SharedExtensions.cs file is shared between Wixsharp and Wixsharp.bin projects.

Steps to reproduce:

1) Add a reference to the nuget package: Wixsharp
2) attempt to use AsWixVarToPath()

**Comment by jonreis** [comment]
I am wondering if AsWixVarToPath is even implemented properly. 

CommonAppDataFolder is evaluated on the machine that the installer is being run on. However; in Wixsharp this is being evaluated on the computer the msi is being compiled on. If these Environmental variables change between versions of the OS, then the installer will no longer function.

Am I missing something here?

**Comment by jonreis** [comment]
Ah, I see  the error of my ways. I should be using: %CommonAppDataFolder% not  "CommonAppDataFolder".AsWixVarToPath() 

I am guessing the AsWixVarToPath() is meant for internal use? Maybe it should be set to internal, instead of public to avoid others making the same mistake.

BTW, after spending a day working with this Wix#, I have to say I am very impressed. It is a fantastic solution to developing with Wix, especially considering the new version of DLL hell Microsoft has introduced with .NET Standard. 

Thank you very much for the great work done on creating this library!

**Comment by oleg-shilo** [comment]
Thank you,

I am glad you solved your problem. 

As for `AsWixVarToPath` purpose, it is actually for an external (not internal) use by the custom UI on the target system. Wix# simply comes with some internal custom UI modules that use it but it can also be a  user-defined UI.

**Comment by jonreis** [comment]
Hello Oleg, do you have a PayPal account? I would like to send some money to you.

**Comment by oleg-shilo** [comment]
Thank you. 
You will find the "donate" link at the top of the [readme.md](https://github.com/oleg-shilo/wixsharp). Alternatively you can go straight to the donations page: http://www.csscript.net/Donation.html.

Your support greatly appreciated.
