### ISSUE TITLE
Info: SFXCA: Failed to create temp directory. Error code 5

### ISSUE THREAD

**Issue by masonwu21** [oleg-shilo/wixsharp#1590]
when i install WixSharp Managed Setup

Info: === Logging started: 2024/7/12  13:43:54 ===
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: MyProduct
ActionStart: Action 13:43:54: INSTALL. 
Info: Action start 13:43:54: INSTALL.
CommonData: 1: 0 2: 1033 3: 1252 
CommonData: 1: 0 2: 1033 3: 1252 
CommonData: 1: MyProduct
Info: === Logging started: 2024/7/12  13:43:58 ===
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: MyProduct
ActionStart: Action 13:43:58: INSTALL. 
Info: Action start 13:43:58: INSTALL.
InstallStart: 1: MyProduct 2: {6FE30B47-2577-43AD-9095-1861CA25889C} 
ActionStart: Action 13:43:58: WixSharp_InitRuntime_Action. 
Info: Action start 13:43:58: WixSharp_InitRuntime_Action.
**Info: SFXCA: Failed to create temp directory. Error code 5**
Info: CustomAction WixSharp_InitRuntime_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Info: Action ended 13:43:59: WixSharp_InitRuntime_Action. Return value 3.
Info: Action ended 13:43:59: INSTALL. Return value 3.
InstallEnd: 1: MyProduct 2: {6FE30B47-2577-43AD-9095-1861CA25889C} 3: 3 
CommonData: 1: 2 2: 0 
CommonData: 1: 2 2: 1 
Info: Action ended 13:43:59: INSTALL. Return value 3.

**Comment by oleg-shilo** [comment]
SFXCA log entry is created by the managed Custom Action.
When WiX runtime prepares the assemblies for execution it extracts them from the msi database and copies them in the temporary folder. I am guessing that in your environment it fails to do so.

Maybe something is tricky with the permissions. 
You can try to execute msi elevated to verify that.

**Comment by nefarius** [comment]
I successfully built a setup on Jul 19 from the latest nuget packages, now on a fresh install with nothing else changed I get the same error and can't get rid of it, *something* has changed :thinking:

**Comment by ByronMayne** [comment]
Yeah same goes for me, project has been built locally on the same PC with no issues. Today it no longer builds.

**Comment by nefarius** [comment]
See #1593
