### ISSUE TITLE
Wix Woolkit 3.14.1 not working "SFXCA: Failed to create temp directory. Error code 5"

### ISSUE THREAD

**Issue by Lumoryel** [oleg-shilo/wixsharp#1593]
When I build and install the template, it ends with 
![image](https://github.com/user-attachments/assets/f87b2313-5476-49a9-8108-f5eb9d9e7517)

Log File:

> Info: === Logging started: 16.07.2024  15:10:07 ===
> CommonData: Message type: 0, Argument: 1033
> CommonData: Message type: 1, Argument: MyProduct
> ActionStart: Action 15:10:07: INSTALL. 
> Info: Action start 15:10:07: INSTALL.
> CommonData: 1: 0 2: 1033 3: 1252 
> CommonData: 1: 0 2: 1033 3: 1252 
> CommonData: 1: MyProduct
> Info: === Logging started: 16.07.2024  15:10:08 ===
> CommonData: Message type: 0, Argument: 1033
> CommonData: Message type: 1, Argument: MyProduct
> ActionStart: Action 15:10:08: INSTALL. 
> Info: Action start 15:10:08: INSTALL.
> InstallStart: 1: MyProduct 2: {6FE30B47-2577-43AD-9095-1861CA25889C} 
> ActionStart: Action 15:10:08: WixSharp_InitRuntime_Action. 
> Info: Action start 15:10:08: WixSharp_InitRuntime_Action.
> Info: SFXCA: Failed to create temp directory. Error code 5
> Info: CustomAction WixSharp_InitRuntime_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Info: Action ended 15:10:08: WixSharp_InitRuntime_Action. Return value 3.
> Info: Action ended 15:10:08: INSTALL. Return value 3.
> InstallEnd: 1: MyProduct 2: {6FE30B47-2577-43AD-9095-1861CA25889C} 3: 3 
> CommonData: 1: 2 2: 0 
> CommonData: 1: 2 2: 1 
> Info: Action ended 15:10:08: INSTALL. Return value 3.

After that also my other existing wixsharp projects did not work anymore.
I had to delete the nuget cache, somehow it did not help to just downgrade to an older nuget.
Best
Lumo

**Comment by oleg-shilo** [comment]
Thank you for letting me know

**Comment by nefarius** [comment]
I am facing the same issue, simply have re-built an unmodified setup, only thing that changed is on a fresh build node so something behind the scenes must have happened.

**Comment by nefarius** [comment]
I downgraded `WixSharp.wix.bin` to 3.14.0, same error. Relevant snippet from log:

```
MSI (s) (D0:A8) [18:39:56:851]: Doing action: WixSharp_InitRuntime_Action
Action 18:39:56: WixSharp_InitRuntime_Action. 
Action start 18:39:56: WixSharp_InitRuntime_Action.
MSI (s) (D0:8C) [18:39:56:858]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIA37D.tmp, Entrypoint: WixSharp_InitRuntime_Action
MSI (s) (D0:60) [18:39:56:858]: Generating random cookie.
MSI (s) (D0:60) [18:39:56:862]: Created Custom Action Server with PID 9160 (0x23C8).
MSI (s) (D0:A4) [18:39:56:882]: Running as a service.
MSI (s) (D0:A4) [18:39:56:885]: Hello, I'm your 64bit Impersonated custom action server.
SFXCA: Failed to create temp directory. Error code 5
CustomAction WixSharp_InitRuntime_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 18:39:57: WixSharp_InitRuntime_Action. Return value 3.
Action ended 18:39:57: INSTALL. Return value 3.
```

**Comment by nefarius** [comment]
Alright, I downgraded to
```xml
    <PackageReference Include="WixSharp.wix.bin" Version="3.14.0" />
```
and manually deleted all `WixSharp.wix.bin` instanced under `%USERPROFILE\.nuget`, rebuilt and it works again.

**Comment by nefarius** [comment]
@gerrit-amagno could you be affected [by this](https://github.com/actions/runner-images/issues/9667)?

**Comment by gerrit-amagno** [comment]
@nefarius yes, I've added a similar fix 2 days ago. thanks for your help! https://github.com/amagno-io/AmagnoVirtualPrinter/commit/2c96e5cff19cd4ec3cb366bab87d2b27b833fdf6

**Comment by nefarius** [comment]
Found it; they [broke it upstream](https://github.com/wixtoolset/issues/issues/8687) and the "solution" suggested is to just upgrade to v4 or higher. Wow. I have no words. Shame.

**Comment by nefarius** [comment]
> @nefarius yes, I've added a similar fix 2 days ago. thanks for your help! [amagno-io/AmagnoVirtualPrinter@2c96e5c](https://github.com/amagno-io/AmagnoVirtualPrinter/commit/2c96e5cff19cd4ec3cb366bab87d2b27b833fdf6)

This may or may not affect you but downgrading [adds surface for a vulnerability](https://github.com/wixtoolset/issues/security/advisories/GHSA-jx4p-m4wm-vvjg).

**Comment by AbuTharHatem95** [comment]
Info: === Logging started: 9/14/2025  0:22:35 === CommonData: Message type: 0, Argument: 1033 CommonData: Message type: 1, Argument: AnalysisTool ActionStart: Action 0:22:35: INSTALL. Info: Action start 0:22:35: INSTALL. CommonData: 1: 0 2: 1033 3: 1252 CommonData: 1: 0 2: 1033 3: 1252 CommonData: 1: AnalysisTool Info: === Logging started: 9/14/2025  0:22:47 === CommonData: Message type: 0, Argument: 1033 CommonData: Message type: 1, Argument: AnalysisTool ActionStart: Action 0:22:47: INSTALL. Info: Action start 0:22:47: INSTALL. InstallStart: 1: AnalysisTool 2: {79BA601D-2FA8-491D-8340-17285189B57F} ActionStart: Action 0:22:47: WixSharp_InitRuntime_Action. Info: Action start 0:22:47: WixSharp_InitRuntime_Action. Info: SFXCA: Failed to create temp directory. Error code 5 Info: CustomAction WixSharp_InitRuntime_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Info: Action ended 0:22:48: WixSharp_InitRuntime_Action. Return value 3. Info: Action ended 0:22:48: INSTALL. Return value 3. InstallEnd: 1: AnalysisTool 2: {79BA601D-2FA8-491D-8340-17285189B57F} 3: 3 CommonData: 1: 2 2: 0 CommonData: 1: 2 2: 1 Info: Action ended 0:22:48: INSTALL. Return value 3

----
I'm still having the same problems, is there a solution?

**Comment by nefarius** [comment]
Read the issue history. Either downgrade or move to v4/v5/v6 etc.
