### ISSUE TITLE
Sign Wixsharp dlls

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1608]
Hi @oleg-shilo , 
I'm using `WixSharp` and ` WixSharp.bin` nuget packages version `1.24.2`
and I see that the following dlls are not digitally signed
```
WixSharp.UI.dll
WixSharp.UI.CA.dll
WixSharp.dll
```

For example:

<img width="270" alt="image" src="https://github.com/user-attachments/assets/d22d77cb-7d4b-4a56-a055-ada7eae48193">

Can you please provide the dlls signed?  

Thx,
Rachel

**Comment by oleg-shilo** [comment]
They are (WixSharp*.dll) signed already:

![image](https://github.com/user-attachments/assets/a388fb85-8c03-4d58-b9ef-736b31db6aa5)

However, any files generated during the build or included by you can be signed as an explicit post-build step by setting `project.SignAllFiles = true`.
Read about it here: https://github.com/oleg-shilo/wixsharp/wiki/Tips'n'Tricks#how-to-sign-all-wixsharp-dlls

**Comment by RachelXGanon** [comment]
Hi, I tried to set` project.SignAllFiles = true.` but it throw error it is not supported for `Managed` type project.

**Comment by RachelXGanon** [comment]
Also, is it allowed to sign the wixsharp dlls with custom tool? usually it is not allowed to sign 3trd party dlls unless they specified it's allowed.

**Comment by RachelXGanon** [comment]
Hi, here's an example to a signed dll
<img width="299" alt="image" src="https://github.com/user-attachments/assets/7e35d0ef-b4da-41d1-abd7-8aebc6edac60">

as you can see in yellow, there's a tab Digital Signature on the dll, entering this will provide more details on the sigature etc.
But I don't have this in Wixsharp.

**Comment by RachelXGanon** [comment]
Hi, thanks for your response Oleg.
Sign dll with a strong name is not same as sign dll with digital sigature.

Sign the installer with a strong name ensures the uniqueness of the assembly by associating it with a public/private key pair. This enables version control and ensures that the correct version of an assembly is loaded in .NET applications.

Sign dll with a digital signature adds a layer of security by certifying the origin of the assembly (the DLL) using a digital certificate. It prevent user from dll hijack, so user can't load dll code and change it.

There are few tools to sign the common is SignTool.exe

**Comment by oleg-shilo** [comment]
OK, then we are talking about two different concepts. I indeed was referring to the "Strong Name Signing" while you are talking about "Digital Signing (Authenticode)". 

So let's rewind the conversation to the start. 

- WixSharp assemblies are all signed with _strong name_.
- None of WixSharp assemblies are _digitally signed_.

If you are interested in digitally signing WixSharp assembly then you will need to purchase a trusted certificate from CA and use it for signing.

You can follow the "Signing" sample and sign all binary files of your msi including all assemblies.

**Comment by RachelXGanon** [comment]
Yeah, right. For the installer *.msi I obviously do it.
But the wixsharp dll is a third party dll, it's a bit problem from a legal concept that I'd sign it.

In the example above there's a Microsoft dll which I get after install the nuget package, is signed with digital sigature.
Is there a way to add support for this, so installing the wixsharp nuget will provide dll signed with digital sigature?

Thanks!

**Comment by oleg-shilo** [comment]
Unfortunately no.
WixSharp is an Open-Source initiative and it does not have a trusted certificate available for digitally signing its assemblies. Signing with Self-Signed Certificate is possible but it would not do you any good as it will not be trusted after you distribute it anyway.
