### ISSUE TITLE
Hidden child features in FeaturesDialog.UserSelectedItems

### ISSUE THREAD

**Issue by Trigve** [oleg-shilo/wixsharp#1613]
I don't know if it is a bug, but I have for example 2 features:
`Feat1` - Just simple feature
`Feat2` - has 2 hidden child features `Feat2Child1`, `Feat2Child2`

When I enable the `Feat1` only in the feature dialog, then in the `FeaturesDialog.UserSelectedItems` there are also `Feat2Child1` and `Feat2Child2`. The children features shouldn't be there.

**Comment by oleg-shilo** [comment]
Sorry, I am a little short on time. So will look at it before the end of this week.

**Comment by oleg-shilo** [comment]
Is it WinForms or WPF UI.

I think it is WPF.  I see the child nodes there seem to be broken so most likely you are just experiencing the side-effects. 
Marking this a s defect.

**Comment by Trigve** [comment]
It's a WinForm UI.

**Comment by oleg-shilo** [comment]
Hm... I checked your scenario and with WinForms it seems to work as expected.

![image](https://github.com/user-attachments/assets/89a6ceb1-609c-4fb6-b17c-cf3b0e27f0c1)


This is my definition of the features:
```C#
var feature1 = new Feature("Feat1", "Feat1", true);
var feature2 = new Feature("Feat2", "Feat2", true);

```C#
Feature features21 = new Feature("Feat2Child1", "Feat2Child1", true) { Display = FeatureDisplay.expand };
Feature features22 = new Feature("Feat2Child2", "Feat2Child2", true) { Display = FeatureDisplay.expand };
feature2.Add(features21, features22);

var project = new ManagedProject("ManagedSetup",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File(feature1, "readme.md"),
                    new File(feature2, "setup.cs"),
                    new File(features21, "exta_fr-fr.wxl"),
                    new File(features22, "app.config")));
```

**Comment by oleg-shilo** [comment]
The WPF FeaturesDialog is fixed now so the fix will be available with the very next release

**Comment by Trigve** [comment]
The `Feat2Child1` and `Feat2Child1` should have `Display` property set as `FeatureDisplay.hidden`.

**Comment by oleg-shilo** [comment]
Well, `hidden` plays no role in this. `UserSelectedItems` is a collection of the features that user has checked.
And since you created these child items as already checked they are included in the `UserSelectedItems`.
But because they are hidden then you cannot uncheck them.

So what is the problem that you are trying to solve?

**Comment by Trigve** [comment]
I want to have a feature, which have children but they shouldn't be visible and should be installed only if the parent feature is installed.
So when `Feat2` is checked, `Feat2Child1` and `Feat2Child2` should be also added as selected features. When I uncheck `Feat2`,   `Feat2Child1` and `Feat2Child2` shouldn't be in selected features. At least that sounds to me logical.

**Comment by oleg-shilo** [comment]
Then you need to to customize your feature tree selection algorithm.

Create your project from the "WixSharp CustomUI" template and it will bring you the source code dialogs.
Then in the FeaturesDialog modify the `Next_Click` event handler to ensure child features clicked state:

![image](https://github.com/user-attachments/assets/92fe7c8b-7482-4ab6-95d1-d6a2574f6b79)

**Comment by Trigve** [comment]
Ok, thanks.

So this is by design, right?

**Comment by oleg-shilo** [comment]
Yes, this is the same design/behavior as with the MSI stock UI.
