### ISSUE TITLE
Parallel publish into shared folder.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#162]
This is an enhancement request. When you run multiple wix# jobs in parallel, you can run into the error shown below since the parallel jobs share some file names.

It would be efficient for our process when the file names would be unique per solution or build project, which would allow running multiple builds in parallel into one shared folder.

![image](https://user-images.githubusercontent.com/7579444/30477866-0af91c3e-9a0f-11e7-81b1-d318876eca9d.png)

**Comment by oleg-shilo** [comment]
The name of the native CA dll is supposed to be `<asm_name>.CA.dll` thus changing it would break the tractability between the CA dll and the assembly it embeds.

You will need either synchronize your access to the shared location or build each msi in it's own folder:
```C#
...
project.OutDir = <your_solution_dir>;
var msi = project.BuildMsi();        
File.Copy(msi, msi.PathChangeDirectory(<your_release_dir>));
```

**Comment by monty241** [comment]
Hi Oleg, thank you. Would it be possible to keep `<asm_name>.CA.dll` at that name, but only have WIX# publish the resulting msi somewhere else than the location of `<asm_name>.CA.dll`?

**Comment by oleg-shilo** [comment]
The code in my prev post does exactly that. Though you can simplify it even further:
```C#
project.OutDir = <your_solution_temp_dir>;
project.BuildMsi(@"<your_release_dir>\setup.msi");
```

**Comment by monty241** [comment]
Hi Oleg, sorry, feeling terribly stupid. In my mail I could see only the initial text till 'own folder:' and I did not read well here. I will go for your solution. Thank you!

**Comment by oleg-shilo** [comment]
:)

**Comment by monty241** [comment]
Works line a charm!
