### ISSUE TITLE
[Question] How to access location of actual msi during installation

### ISSUE THREAD

**Issue by ssrakesh** [oleg-shilo/wixsharp#1625]
Problem:
We have created a msi using wix#.
msi is available in the portal, but while downloading we have to embed uniq info to msi and same will be used during installation and during app launch.
So we are creating a zip file along with configuration file + msi in the portal for user to download.
But during installation I am not able to access the msi location

I tried to use following ppt to get msi location, in ElevatedManagedAction(When.Before, Step.InstallFiles, Condition.NOT_BeingRemoved)
```
session.Property("CURRENTDIRECTORY"),
session.Property("SourceDir"),
session.Property("SOURCEDIR"),
session.Property("OriginalDatabase")
```
But these are set to empty during action execution, 

how to get this property with proper values? or is there any other way to embed info into msi?

**Comment by Torchok19081986** [comment]
morning, https://learn.microsoft.com/en-us/windows/win32/msi/originaldatabase?redirectedfrom=MSDN 
According to MS - Property of Original Database should be right way.  Maybe Step is not set it correctly. Does MSI cached MSI Files into Windows Temp Folder ? if so you can try get tempfilename from installer self. Wix Toolset has dll WindowsInstaller and Class Installer. Maybe it helps. Another way debug step by step. If you use Wix# Tempalte and Temaplte for Cusotm UI, you can debug msi BeforeInstall Event with MessageBox. Here Windows Installer shows all properties which it want to set before Installation begins. You can try it. 
best regards, Torchok.

**Comment by oleg-shilo** [comment]
MWixSharp added the extension method to the session object: `e.Session.MsiFile();`.
It simply accesses the `OriginalDatabase` property.

**Comment by ssrakesh** [comment]
> MWixSharp added the extension method to the session object: `e.Session.MsiFile();`. It simply accesses the `OriginalDatabase` property.

Thats gre8. I will check

**Comment by oleg-shilo** [comment]
Object `e.Session` is the argument of any WixSharp installation event. Alternatively, you can access session object from a raw managed CustomAction. It is the only argument of the CA method: `public static ActionResult MyAction(Session session)`.

As for managed events (e.g. AfterInstall). You need to use `ManagedProject` instead of `Project`.

**Comment by ssrakesh** [comment]
Thanks, I am accessing session from ElevatedManagedAction itself. but in log those parameters are empty.
ManagedProject is so good, just that bz o the UAC issue others in my team will not accept.

**Comment by ssrakesh** [comment]
I think best approach would be to use Wixsharp - bootstrapper with BA

**Comment by ssrakesh** [comment]
I tried to send param to msi,
But this param is empty during execution of ElevatedManagedAction.
But at the end when it dumps all the values I can see proper values.
So how to get param value in ElevatedManagedAction ?

**Comment by ssrakesh** [comment]
I just used `ElevatedManagedAction.UsesProperties = "OriginalDatabase"`
then values started appearing.

**Comment by oleg-shilo** [comment]
> `ElevatedManagedAction.UsesProperties = "OriginalDatabase"`

Please note that it is already set if you are using ManagedProject and project events (e.g. Load, BeforeInstall) instead of raw Custom Actions.
