### ISSUE TITLE
IsManagedUISession = 1 when running silent installation

### ISSUE THREAD

**Issue by anv1l** [oleg-shilo/wixsharp#1636]
I execute the installer with /quiet mode, however SetupEventArgs.IsManagedUISession returns 1? 
The code is running in project.AfterInstall event handler, eg:

 private static void OnAfterInstall(SetupEventArgs setupArgs) {
     setupArgs.Session.Log($"Managed UI session = {setupArgs.IsManagedUISession}");
....

According to https://github.com/oleg-shilo/wixsharp/issues/766 I am using correct way to detect silent mode when using managedui?

**Comment by anv1l** [comment]
Right, IsManagedUISession reports it incorrectly, but checking ManagedUIHandle works.

Also see: https://github.com/oleg-shilo/wixsharp/issues/17

**Comment by oleg-shilo** [comment]
> IsManagedUISession reports it incorrectly, but checking ManagedUIHandle works.

Hm-m-m. Strange. both calls are checking the same code:

![image](https://github.com/user-attachments/assets/95ae4677-fd4b-4d4f-ad1a-b444bd1eaefa)

I would expect them both either fail or work. But not only one of them.

Do you still see the managed UI when you execute it with /quiet?

**Comment by anv1l** [comment]
The managed ui is not visible. The log entry from the code in my sample is: "Managed UI session = 1"

**Comment by oleg-shilo** [comment]
Not sure I follow. your log shows `1` for a **boolean** value. I would expect `True` or `False`. String formatting is controlled by CLR, not by WiX or WixSharp.

And, can you elaborate on "checking ManagedUIHandle works". What does it return?

**Comment by anv1l** [comment]
Sorry for confusion, I was writing previous comment using my phone and not having code in front of me. 

I tested this a bit using following code:
            setupArgs.Session.Log($"Managed UI sessionhandle == Zero {setupArgs.ManagedUIHandle == IntPtr.Zero}");
            setupArgs.Session.Log($"Managed UI session = {setupArgs.IsManagedUISession}");

running msi with /quiet /lv log.txt
Managed UI sessionhandle == Zero True
Managed UI session = True

running msi without /quiet switch
Managed UI sessionhandle == Zero False
Managed UI session = True

So it indeed seems, that IsManagedUISession returns true even when running in quiet mode.
