### ISSUE TITLE
Opening .exe from AfterInstall event behaves different in combination with registry than starting .exe as normal. 

### ISSUE THREAD

**Issue by ejongejans** [oleg-shilo/wixsharp#1640]
Hi, 

I'm trying to open our installed .exe, after installing it. With the code below. 
That works fine. 

But somehow I get a dialog from our licensing library (integrated in .exe), saying it's in evaluation mode of our software. 
There is a valid license installed in in the local user registry. 

But somehow, when the process is started from the installer it can't access that registry key and looks somewhere else. Where i'm not sure at the moment.  
How to prevent that? Or what exactly is different when a .exe is started from the .msi like this?  

I've tried to set the InstallPrivileges to limited, but that doesnt' seem to make a difference. 

Of course, when I start the installed .exe as normal; it doesn't happen and it finds the installed license correctly.

OS: windows 10, up to date. 

Thanks for any help

kind regards
Elco

```
wixproject.DefaultDeferredProperties += ",WAssemblyName";
**wixproject.InstallPrivileges = InstallPrivileges.limited;**
wixproject.AfterInstall += args =>
{
    if (args.IsInstalling)
    {
        try
        {
            string exeName = args.Session.Property("WAssemblyName") + ".exe";
            string exePath = args.InstallDir.PathCombine(exeName);
            if (DialogResult.Yes == MessageBox.Show("Would you like to start the program after finishing the install?" + Environment.NewLine + Environment.NewLine + exePath, "Start software?", MessageBoxButtons.YesNo, MessageBoxIcon.Question))
            {
                System.Diagnostics.Process.Start(exePath);
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show("Could not start the software: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }
};
```

**Comment by Torchok19081986** [comment]
Hallo, somehow it looks like your exe search in wrong registry TreeView. There is x86 and x64 Registry TreeView. There is example from oleg, for x64-Registry Treeview or x64-Bit Process. Just search in Release source code and try it. MSI is always x86 and your process, maybe compiled for x64.

**Comment by oleg-shilo** [comment]
> MSI is always x86 and your process, maybe compiled for x64.

Correct. MSI session is always x86 since it is x86 Windows service. This is the limitation of MSI technology.

**Comment by ejongejans** [comment]
Hi, 

I don't have direct access to the registry location code. (bought component :S ) 
There is in that case nothing to do about it correct? 

But what I don't understand is why does my 64bit app startup as 32bit? 
There is just 1 .exe installed in the program files, and this is a .NET8 app, compiled for 64bit. 

Is the MSI forcing that as a 32bit process somehow? 

And chaining something with a new launcher.exe in the middle that starts the final .exe wouldn't help either I guess.. ? 

thx
Elco

**Comment by ejongejans** [comment]
Ok thanks! 
Then it will be a future todo when we rebuild the licensing library. 

kind regards
Elco
