### ISSUE TITLE
Unable to use Third party dll in custom actions.

### ISSUE THREAD

**Issue by swapnilpachkude** [oleg-shilo/wixsharp#1648]
I have created wixsharp application that creates the config.json file after installation is completed. I have used the Newtonsoft.json package in application.
After installation it's not creating a json file.

**Comment by Torchok19081986** [comment]
morning, first of all, which version of wixsharp do you use for msi creation ? Second: there is sample from oleg, where it shows how to call Assemblies / dll´s , in CA. Download latest release Folder. In Folder navigate to ... Source\src\WixSharp.Samples\Wix# Samples\DTF (ManagedCA)\Different Scenarios. Here is explanation, how to use third party assemblies in CA. AFAIK this works, only for wixtoolset 3.X, for 4.X you have to looks for latest description of CA and Assemblies.

**Comment by oleg-shilo** [comment]
Thank you @Torchok19081986, yep that is the folder containing all asm dependency scenarios samples.

@swapnilpachkude, most likely you forgot to add Newtonsoft assembly to your project.

you can do it either explicitly with the `project.DefaultRefAssemblies.Add("<assembly>dll");` or even ask WixSharp compiler to add them automatically.

```c#
project.AddCustomActionRefAssembliesOf(typeof(Script)); // Script is the build script class that defines your MSI 
```
The technique works in all editions/versions of WixSharp.

**Comment by swapnilpachkude** [comment]
Hi @oleg-shilo @Torchok19081986, Thank you so much for the quick response and guidance. It's working now.

**Comment by oleg-shilo** [comment]
@Torchok19081986, yep the sample you quoted is the correct one.
