### ISSUE TITLE
Old version uninstall, new version install chain failure

### ISSUE THREAD

**Issue by julajus** [oleg-shilo/wixsharp#1658]
Hello, need some consultation, what I am doing wrong. Working with custom WPF installer.
My task is to fully uninstall product, showing progress bar, then fully install new one, also showing progress bar.
Using separate views for uninstall and install.
Code part of UninstallProgressViewModel:

```c#
public void StartExecute()
{
    _session["REMOVE"] = "ALL";
    _session["MODIFY_ACTION"] = "Remove";

    _shell?.StartExecute();
}

public void OnExecuteComplete()
{
    try
    {
        _session["REMOVE"] = "";
        _session["MODIFY_ACTION"] = "";

         //go to installing progress view
        _shell?.GoNext();
    }
    catch (System.Exception ex)
    {
        SessionError = ex.Message;
        SessionTrace = ex.StackTrace;
    }
}
``` 

Uninstall process finishes successfully, but Installer is crashing on setting session values back to default.
Try Catch block shows this:

```
The handle is invalid.
   at WixToolset.Dtf.WindowsInstaller.Session.set_Item(String property, String value)
   at WixSharp.MsiSessionAdapter.set_Item(String name, String value)
   at MySetup.ViewModels.UninstallProgressViewModel.OnExecuteComplete()'
``` 

Also checked for nullability, _session is not null, it is set in constructor:
```c#
protected ViewModelBase(ManagedForm host)
{
    _host = host;
    _session = host?.Runtime.Session;
    _shell = host?.Shell;
}
``` 

Could You please check and help me understand the problem?

**Comment by oleg-shilo** [comment]
I am not sure what exactly you are doing in your UI session. It's designed to handle a single MSI session (install/restore/uninstall) and I do not know how you are going " fully uninstall product, showing progress bar, then fully install new one,". 

But the error itself tells us that your session object handler is no longer valid (the session is already closed)

**Comment by julajus** [comment]
Thank You, will redesign my project a little bit to handle only one session per run.
Main answer was: It's designed to handle a single MSI session (install/restore/uninstall)
