### ISSUE TITLE
Could not load file or assembly after update from 2.3.2 to 2.4.1

### ISSUE THREAD

**Issue by julajus** [oleg-shilo/wixsharp#1659]
Hello, 
I am developing custom UI setup project with WPF on 4.7.2 .net
I am using Caliburn.Micro (4.0.212) and WixSharp_wix.bin (2.3.2) nugets.
When updating WixSharp_wix.bin to 2.4.1, msi file builds, but running it throws error (could not load Caliburn.Micro):

<img width="144" alt="Setup_error" src="https://github.com/user-attachments/assets/613f08f6-aeb9-49ed-9154-422ed4795c95">

**Comment by Torchok19081986** [comment]
morning, First , Calibun.Micro is not maintanence anymore. Support was ended. Oleg dropped or want to drop this MVVM in WPF for suche problems. You can use any MVVM Framework that you want. For example : if you want that your installer moder and nice looking, you can use Avalonia WPF C#. there also supoort for .NET Framework, not only NET 6+. For mainly use MVVM in your WPF Template, you can use community toolkit from MS (in past was name MS Toolkit).
https://learn.microsoft.com/de-de/dotnet/communitytoolkit/mvvm/observableobject - for Community toolkit.
https://docs.avaloniaui.net/docs/concepts/the-mvvm-pattern/avalonia-ui-and-mvvm - for avalonia UI and MVVM. 
You choice and basically ,  i effort, that you want do for installer. 
best regards, Torchok.

**Comment by julajus** [comment]
I want to use Prism, but having same issue, same error, when added this nuget. So tried with Caliburn, to properly reproduce problem.

**Comment by Torchok19081986** [comment]
AFAIK , prism use own mvvm framwork, Brian Lagunas did very good job with prism. You can try to create test project and remove all caliburn.micro refences from wixsharp. After this you got all error , where you have to add new mvvm framework. This approach need some time, but with this way you can achieve all what you want. I did same for get rid of caliburn.micro mmvm framework and added community toolkit.

**Comment by julajus** [comment]
Already did it, error is the same (when running msi after successfull build):
<img width="147" alt="Setup_error" src="https://github.com/user-attachments/assets/20e36ba3-4646-4f9b-a19c-f58ffd14248c">

My project looks like that:
<img width="113" alt="Project" src="https://github.com/user-attachments/assets/625abdf4-0ead-4ee4-90f4-101e6847fd1c">

**Comment by julajus** [comment]
At last, after searching to similar issues, found solution in:
https://github.com/oleg-shilo/wixsharp/issues/1128#issuecomment-1062821120

In my case this made the trick:
```c#
project.DefaultRefAssemblies.Add(typeof(Prism.Mvvm.BindableBase).Assembly.Location);
```

**Comment by Torchok19081986** [comment]
good , if this works, but cant clsoe ticket. 😄😄😄.
