### ISSUE TITLE
Unable to skip dialog

### ISSUE THREAD

**Issue by jojonv** [oleg-shilo/wixsharp#1666]
Hello,

I'd like to skip a dialog based on some dynamic condition, ie. if a component the application which is being installed depends on is already present on the system the dialog should be skipped.

What I did is I tried to follow [this issue](https://github.com/oleg-shilo/wixsharp/issues/1218) and hooked up on `Load` event (of the dialog), validated the condition and then called `Shell.GoNext`. Unfortunately calling `Shell.GoNext` in `Load` results in a weird situation where all remaining dialogs are skipped.

I also tried to follow [CustomUI.Sequence Sample](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUI.Sequence/setup.cs) and call `e.ManagedUIShell.CurrentDialog.Shell.Dialogs.Insert` or `Remove` in `UILoaded` event but it did nothing - I mean the the removed dialog was still shown and the inserted not.

WixToolset 3.14 version is used and WixSharp 1.26.0.

**Comment by oleg-shilo** [comment]
Apologies. The [CustomUI.Sequence Sample](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUI.Sequence/setup.cs) was messier than it should be. I just updated and tested it.

Please one of the possible techniques - "modifying dialog sequence" or "jumping out of the dialogue":
```c#
    static void Project_UILoaded(SetupEventArgs e)
    {
        MessageBox.Show("Project_UILoaded");
        var msiFile = e.Session.Database.FilePath;

        // Simulate analyzing the runtime conditions with the message box.
        // Make a decision to show (or not) Licence dialog.

        // There are two options for skipping dialogs:
        // - by modifying dialog sequence (next two commented lines)

        // if (MessageBox.Show("Do you want to remove 'Licence Dialog'?", "Wix#", MessageBoxButtons.YesNo) == DialogResult.Yes)
        //     e.ManagedUI.CurrentDialog.Shell.Dialogs.Remove(Dialogs.Licence);


        // - by handling OnCurrentDialogChanged event
        e.ManagedUI.OnCurrentDialogChanged += ManagedUIShell_OnCurrentDialogChanged;
    }

    static void ManagedUIShell_OnCurrentDialogChanged(IManagedDialog obj)
    {
        if (obj.GetType() == Dialogs.Licence)
        {
            // Simulate analyzing the runtime conditions with the message box.
            // Make a decision to jump over the dialog in the sequence
            if (MessageBox.Show("Do you want to skip 'Licence Dialog'?", "Wix#", MessageBoxButtons.YesNo) == DialogResult.Yes)
            {
                obj.Shell.GoNext();
            }
        }
    }
```

Please note that `Load` method is no good for any manipulations with the dialog sequence. The technique above should help.

Also you will need to replace `e.ManagedUIShell.CurrentDialog.Shell.Dialogs` with `e.ManagedUI.CurrentDialog.Shell.Dialogs` as this API has changed since the example was created.

**Comment by jojonv** [comment]
Hi @oleg-shilo, 

thank you for taking the time to help me out. Both ways you mentioned work. 

I'll likely go with the second one, ie. `e.ManagedUI.CurrentDialog.Shell.Dialogs` as I noticed that calling `GoNext` in `OnCurrentDialogChanged` causes the skipped dialog to be visible for a second.

I'm going to close the issue since it was resolved.
