### ISSUE TITLE
Error on using  template "WixSharp Managed Setup - Custom Dialog (Wix 3)"

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/wixsharp#1676]
**Original report:** https://marketplace.visualstudio.com/items?itemName=OlegShilo.WixSharpProjectTemplates&ssr=false#qna
_On behalf of Tushar Bhagat_ 

	
I can see error while creating project from template "WixSharp Managed Setup - Custom Dialog (Wix 3)"

"The project file could not be loaded. '<', hexadecimal value 0x3C, is an invalid attribute character. Line 22, position 3.  C:\Backup\WixSharp Setup1\WixSharp Setup1.csproj"

Visual Studio version is VS 2022 - 17.12.0

**Comment by bhagatus** [comment]
Thank you for raising ticket for the issue.
Meanwhile issue gets resolved I was searching for the option to create custom dialog without template.
Please let me know your suggestion if any.

**Comment by oleg-shilo** [comment]
I have just published the VS extension with the fix for the template. Update the extension and you will get the template working. If for whatever reason it does not then take the attached freshly created project. But it should work. I have created this project from the new template.
[WixSharp Setup26.zip](https://github.com/user-attachments/files/17992203/WixSharp.Setup26.zip)

**Comment by bhagatus** [comment]
Thanks a lot for your quick action. I am able to create custom dialog project using new template.
