### ISSUE TITLE
no framework found after upgrading to dot net 8 core

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#1679]
My wix sharp installer worked well in dot net 5 , I have now upgraded to dot net 8. The app windows service works well in debug, and the installer is created as expected it is a bootstrap bundle. 

Windows 11 does have dot net framework 4.8 so all should be fine but the servie can't be started the error in the event viewer :

Description: A .NET application failed.
Application: PlcData.LoggingService.exe
Path: C:\Program Files (x86)\ACL\Apps\PlcData.LoggingService\PlcData.LoggingService.exe
Message: You must install or update .NET to run this application.

App: C:\Program Files (x86)\ACL\Apps\PlcData.LoggingService\PlcData.LoggingService.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: C:\Program Files (x86)\ACL\Apps\PlcData.LoggingService\

No frameworks were found.

**Comment by oleg-shilo** [comment]
Thank you for sharing the outcome
