### ISSUE TITLE
Approach (may be special one) to windows services designed with Topshelf.

### ISSUE THREAD

**Issue by silentnightwalk** [oleg-shilo/wixsharp#169]
Thanks a lot!

The requirement I have is to create an installer which would install/uninstall a product and a Topshelf windows service as a part of this product.

What is Topshelf: "Topshelf is a framework for hosting services written using the .NET framework. The creation of services is simplified, allowing developers to create a simple console application that can be installed as a service using Topshelf." 
https://topshelf.readthedocs.io/en/latest/#

It would be useful for me to know how to combine Topshelf and WixSharp. Here is my code, which only installs. **But I would like to also get the service uninstalled with the installer.** The problem is that I did not find a way to uninstall Topshelf with one command line call. Unfortunatelly they did not do "stop uninstall" with one step like "install start". Also, MSI  shows me a dialog asking whether to close open applications before uninstall or not. In both ways, the service does not get uninstalled properly.

Full source of my experiment is here on github:
https://github.com/silentnightwalk/TopshelfWixSharp

One more thing, may be a hint for new tasks. Actually, it would be better for me to have some answer quickly. But for the future, it would be possibly good to have special `Tasks`, for example:

```
Tasks.InstallTopshelfService();
Tasks.InstallStartTopshelfService();
Tasks.UninstallTopshelfService();
Tasks.StopUninstallTopshelfService();
```

Or if this is too difficult, just a **Sample** for working with Topshelf would do a great thing.

Ok, back to the issue, here's the code:

```
    // here is my code which fails to uninstall the service 

    class Setup
    {
        static void Main(string[] args)
        {
            Compiler.WixLocation = @"..\packages\WixSharp.wix.bin.3.11.0\tools\bin";
            var project = new ManagedProject("TopshelfWixSharp"
                , new Dir(
                    $@"{Environment.ExpandEnvironmentVariables("%programfiles(x86)%")}\TopshelfWixSharp"
                    , new File($@"..\TopshelfWixSharp\bin\Debug\TopshelfWixSharp.exe")
                    , new File($@"..\TopshelfWixSharp\bin\Debug\Topshelf.dll")
                    )
                );
            project.BeforeInstall += Project_BeforeInstall;
            project.AfterInstall += Project_AfterInstall;
            Compiler.BuildMsi(project);
        }

        private static void Project_BeforeInstall(SetupEventArgs e)
        {
            if (e.IsUninstalling)
            {
                Tasks.StopService("TopshelfWixSharp");

                Process proc = new Process();
                proc.StartInfo.FileName = $@"{Environment.ExpandEnvironmentVariables("%programfiles(x86)%")}\TopshelfWixSharp\TopshelfWixSharp.exe";
                proc.StartInfo.Arguments = "uninstall";
                proc.StartInfo.Verb = "runas";
                proc.Start();
            }
        }

        private static void Project_AfterInstall(SetupEventArgs e)
        {
            if (e.IsInstalling)
            {
                Process proc = new Process();
                proc.StartInfo.FileName = $@"{Environment.ExpandEnvironmentVariables("%programfiles(x86)%")}\TopshelfWixSharp\TopshelfWixSharp.exe";
                proc.StartInfo.Arguments = "install start";
                proc.StartInfo.Verb = "runas";
                proc.Start();
            }
        }
    }
```

**Comment by oleg-shilo** [comment]
Thank you for your proposal. I had a look at _Topshelf_ and your GitHub project and indeed it looks interesting. Though, having _Topshelf_ specific functionality in Wix# codebase does not seat well with me. Any external-product specific functionality needs to come in Wix# domain as an extension not the modification of Wix#. 

Your idea is great but it needs to be delivered as an Wix# extension library. You can wrap your `Task.Install*TopshelfService(this Project project,...)` routines in a nice clean assembly and simply reference it from your Wix# project. What would be even better approach is to publish your assembly as a NuGet package (e.g. "WixSharp.Tposhelf"). This way you will make it much easier to share with other developers.  

----

I noticed a small but tricky mistake in your code:
```C#
new Dir($@"{Environment.ExpandEnvironmentVariables("%programfiles(x86)%")}\TopshelfWixSharp"...
```
The environment variable is will evaluated at compile time and converted into an absolute path `C:\Program Files (x86)\TopshelfWixSharp`. Probably it's not what you want as the target system may not be Winx64 or it mey not even have 'C' drive.

When you fix **this** problem you will still have a potential crash in your event handlers:
```C#
proc.StartInfo.FileName = $@"{Environment.ExpandEnvironmentVariables("%programfiles(x86)%")}\TopshelfWixSharp\TopshelfWixSharp.exe";
```
The code above will be evaluated at install time and it may also fail to acquire the correct path. 
A much simple and more reliable solution would be:

```C#
new Dir(@"%ProgramFiles%\TopshelfWixSharp", 
    , new File(@"..\TopshelfWixSharp\bin\Debug\TopshelfWixSharp.exe"...
...
proc.StartInfo.FileName = e.InstallDir.PathJoin("TopshelfWixSharp.exe");
```

**Comment by Eagle3386** [comment]
@silentnightwalk Since I'm using Topshelf for my service, too, I'd love to see a modified (read: extended) Wix# as a NuGet package that supports Topshelf just out of the box.

To date, Topshelf is the only developer-friendly project I know of that helps debugging code and after building it, run as a normal service (accompanied by an included install, just run `service.exe install` from command line) at the same time.

**Comment by silentnightwalk** [comment]
Unfortunatelly, I'm not good at expressing my thoughts.
This published issue was actually a question.
The problem is that I haven't yet managed to settle things with Topshelf.
The published code doesn't work well. It only installs, but does not do uninstalling.
I don't promise but i probably could try to add a new nuget package. 
But first i defenately need to know what it should do.
Could you please help me with any solution on Topshelf!
I would love to take some part in this project, but i can not promise because life is crazy (work, family, many other things). I warn you that if i take some little part, then i would probably be asking many questions.
Again, please first help me!...

**Comment by oleg-shilo** [comment]
:) 
The adjustments I suggested most likely will help. The code in the form as it was would probably work but only on the very same system where msi is compiled.

**Comment by Eagle3386** [comment]
Here's some snippet from my project regarding (un)installing a service that is developed by using Topshelf.

The `CustomAction`'s code:
```csharp
public static ActionResult ManageService(Session session)
{
  return session.HandleErrors(() =>
    {
      if (bool.Parse(session.Property("ISINSTALLING")))
      {
        Process.Start(Path.Combine(session.Property("INSTALLDIR"), $"MyApp.exe"), "install");
        Tasks.StartService("MyApp");
      }
      else
      {
        Tasks.StopService("MyApp");
        Process.Start(Path.Combine(session.Property("INSTALLDIR"), $"MyApp.exe"), "uninstall");
      }
    });
}
```

The simplified `Project` code for building the MSI:
```csharp
var project = new Project(
    projectName,
    new Dir(
      $@"%ProgramFiles%\MyCompand\MyApp",
      new DirFiles($@"{serviceOutputDirectory}\*.*", fileName => !new[] { ".pdb", ".xml" }.Any(fileName.EndsWith))),
    (...)
    new ElevatedManagedAction(CustomActions.ManageService, Return.check, When.After, Step.InstallFiles, Condition.BeingRemoved)
    {
      UsesProperties = "INSTALLDIR,ISINSTALLING=False"
    },
    new ElevatedManagedAction(CustomActions.ManageService, Return.check, When.After, Step.InstallFiles, Condition.NOT_Installed)
    {
      UsesProperties = "INSTALLDIR,ISINSTALLING=True"
    })
  {
    (...)
  };
project.BuildMsi();
```

The result is that if you're installing, t

**Comment by silentnightwalk** [comment]
Thank you very much!

**Comment by silentnightwalk** [comment]
unfortunately, @Eagle3386 's solution did not work for me.
The service does not get uninstalled.

**Comment by oleg-shilo** [comment]
Then you may want to debug your CA.

Place an ASEERT there. When assertion dialog pops up do not use its "_start new instance_" action but instead attach **already elevated** instance of your VS to the process that hosts the assertion dialog. 
Then you will be able to see what is the problem (e.g. wrong path, not elevated, ...).

**Comment by silentnightwalk** [comment]
Finally, i did a walkaround.
I moved the Service functionality to separate assembly, and created two wrapper projects. One of them is Topshelf (for debugging) and the other is usual windows service (for installing).
This is not very important for me any more, but Topshelf compatibility would defenatelly be great and useful for somebody.
The problem in my case was probably the fact that it took long time the service to stop. However, i'm not sure, i hadn't got to use Asserts.
On the other hand, i suspect, this code (causing uninstall problem):
```
new ElevatedManagedAction(
    CustomActions.ManageService, 
    Return.check, 
    When.After, 
    Step.InstallFiles, 
    Condition.BeingRemoved
) 
{
    UsesProperties = "INSTALLDIR,ISINSTALLING=False"
}
```
because it looks different in Samples:
```
new ElevatedManagedAction(
    CustomActions.UnInstallService, 
    Return.check, 
    When.Before, 
    Step.RemoveFiles, 
    Condition.BeingRemoved
)
```
Thanks a lot!

**Comment by rsmilek** [comment]
This my solution of install/uninstall Topshelf service, working properly for me. It is based on service installer example from WixSharp. What it is important compare previous solution is that unistall by Process.Start only fails because service's files are removed before they are uninstalled, this is what is fixed here.

```csharp
using System;
using System.Diagnostics;
using System.Linq;
using System.IO;
using System.Security.Principal;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Deployment.WindowsInstaller;
using WixSharp;
using WixSharp.CommonTasks;

internal static class Script
{
    static public void Main(string[] args)
    {
...
	try
        {
            var project =
                new Project(ProductFullName,
					new Dir(@"%ProgramFiles%\" + ProductFolderName, new Files(redistributionDir + @"\*.*")),
                    new ElevatedManagedAction(CustomActions.InstallService, Return.check, When.After, Step.InstallFiles, Condition.NOT_Installed),
                    new ElevatedManagedAction(CustomActions.UnInstallService, Return.check, When.Before, Step.RemoveFiles, Condition.BeingUninstalled));

...
            project.BuildMsi();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
    }
}

public class CustomActions
{
	// Service
	const string ServiceName = "Your service name";
	const string ServiceFileName = "Your service filename";

	private static int ExecProcessAndWaitForExit(string fileName, string arguments)
	{
		Process process = new Process();
		process.StartInfo.FileName = fileName;
		process.StartInfo.Arguments = arguments;
		process.StartInfo.WindowStyle = ProcessWindowStyle.Normal;
		process.Start();
		process.WaitForExit();
		return process.ExitCode;
	}

    [CustomAction]
    public static ActionResult InstallService(Session session)
    {
        return session.HandleErrors(() =>
        {
		ExecProcessAndWaitForExit(Path.Combine(session.Property("INSTALLDIR"), ServiceFileName), "install start");
        });
    }

    [CustomAction]
    public static ActionResult UnInstallService(Session session)
    {
        return session.HandleErrors(() =>
        {
		ExecProcessAndWaitForExit(Path.Combine(session.Property("INSTALLDIR"), ServiceFileName), "stop uninstall");
        });
    }
}
```
