### ISSUE TITLE
WixUI pathing issue

### ISSUE THREAD

**Issue by Ceran0r** [oleg-shilo/wixsharp#1696]
Hi, I'm back with another strange issue. I'm trying to use WixSharp in a GitLab CI Windows environment to build a setup executable.
Up to a point, everything works flawlessly and the WXS project file builds. However, when the WIX compiler is called, I run into a crash with the following error:

```
  Windows Installer XML Toolset Compiler version 3.14.1.8722
  Copyright (c) .NET Foundation and contributors. All rights reserved.
  
  MyProject.wxs
  Windows Installer XML Toolset Linker version 3.14.1.8722
  Copyright (c) .NET Foundation and contributors. All rights reserved.
  
C:\GitLab-Runner\builds\xxxxxxxxx\rd\software\myproject\MyProject\bin\Release\net8.0-windows\win-x64\Setup\MyProject.wxs(3025): error LGHT0103: The system cannot find the file '..\..\..\..\..\..\..\..\..\..\..\..\Users\gitlab_runner\.nuget\packages\wixsharp.wix.bin\3.14.1\tools\sdk\wixui\WixUI_en-US.wxl'. [C:\GitLab-Runner\builds\xxxxxxxxx\rd\software\myproject\MyProject\MyProject.csproj]
```

I'm unsure what to do about this, as I'm running a dotnet restore beforehand - this file should be available by default as a part of the wixsharp.wix.bin NuGet package, no? Note that this process works on my local dev machine and a setup executable is produced. Any help, please?

**Comment by Ceran0r** [comment]
Update: Resolved the issue by migrating to Wix 4, which brought its own host of issues, but those seem more manageable to me.

**Comment by oleg-shilo** [comment]
Yep. This is a better strategy.
Don't get me wrong, WiX4 is not ideal but at least there is a chance that something will be fixed there if it's broken. WiX3 is unlikely to be maintained with the same attention as WQiX4
