### ISSUE TITLE
Question regarding temp files on build/debug in project root folder

### ISSUE THREAD

**Issue by Eagle3386** [oleg-shilo/wixsharp#171]
While running a build/debug, I noticed that either Wix and/or Wix# create temporary files within both, my setup project's root folder (i. e. where `Setup.csproj` and `App.config` reside) and within `bin/[Debug or Release]` folder.

I'd like to know
a) why Wix(#) doesn't use the corresponding bin-subfolder only
and
b) if there's some switch or setting to enforce a). This would help with e. g. running build/debug on a RAM disk instead of on HDD/SSD.

Thanks in advance. 😄

**Comment by oleg-shilo** [comment]
This is because Wix# by default builds in the current directory (same as root), which is also a source directory for all Wix# `Project` items. Though VS uses `obj/{configuration}` subfolders. Thus these two tools are using slightly different project layout model. 

If it is not what you want then set Wix# build and source directory explicitly:

```C#
project.OutDir = @"%LATEST_RELEASE%\MSI";
project.SourceBaseDir = "%LATEST_RELEASE%";
```

**Comment by oleg-shilo** [comment]
> Of course, that results in the MSI being placed into bin\{configuration}\bin\{configuration}.

And for this one you should use `project.BuildMsi(<final msi path>)`.

If you want to get rid of temp files just keep `project.PreserveTemporaryFiles = false`  (default).

**Comment by Eagle3386** [comment]
> And for this one you should use `project.BuildMsi(<final msi path>)`.

Tried that (even hardcoded `project.BuildMsi(@"C:\Test\test.msi");`, but still throws `DirectoryNotFoundException`, stating "Could not find a part of the path 'C:\WS\MyApp\MyApp.Setup\bin\Debug\bin\Debug\MyApp.Setup.exe'."

`project.PreserveTemporaryFiles = false` was never set by my code, hence it should have its default of false.

**Comment by oleg-shilo** [comment]
If  you never touched `project.PreserveTemporaryFiles` then all temp files should be cleared on successful build. Is it not happening?

As for `project.BuildMsi(@"C:\Test\test.msi");`, will have a look at it.

**Comment by Eagle3386** [comment]
> If you never touched `project.PreserveTemporaryFiles` then all temp files should be cleared on successful build. Is it not happening?
Sure it's happening. I'm after having them rather created on the RAM disk than on HDD/SSD.

> As for `project.BuildMsi(@"C:\Test\test.msi");`, will have a look at it
FWIW, it works when `OutDir` and `SourceBaseDir` are unset. If I set all three, the exception mentioned above occurs.

**Comment by Eagle3386** [comment]
Addition note:

Setting neither `OutDir` nor `SourceBaseDir`, but setting `OutFileName` and using `BuildMsi()` instead, I get the exact same MSI package placed within setup project's root folder and within its `bin\{configuration}` subfolder.

**Comment by oleg-shilo** [comment]
> Sure it's happening. I'm after having them rather created on the RAM disk than on HDD/SSD

:) I understood your objective. I just wanted to ensure that clearing temp files isn't broken.

-------------

Now, I have checked the 'WixSharp Setup - Custom CLR Dialog' project and I don't see any temporary files in the root during the build when the default project is modified with this:
```C#
project.OutDir = "build";
project.PreserveTempFiles = true;

project.BuildMsi();
```

I have checked the build output and none of the WiX compilers used the root folder for anything. 

Though I observed only one exception:  a tiny 1K _CustomAction.config_ ` file is created by Wix#. The file is small and written in a single hit so I doubt getting rid of it will make any difference. Though if you wish you can place it in the SSD location and add to your project from there. 

I have attached the project and the build output log. 

[WixSharp Setup - Custom CLR Dialog1.zip](https://github.com/oleg-shilo/wixsharp/files/1346303/WixSharp.Setup.-.Custom.CLR.Dialog1.zip)
