### ISSUE TITLE
Request for IsSilent() extension method

### ISSUE THREAD

**Issue by Eagle3386** [oleg-shilo/wixsharp#172]
Since there are extension methods like `IsInstalling` and `IsUninstalling`, I'd like to ask for one that determines if the MSI is running in silent mode. This helps doing something like
```csharp
if (session.IsSilent)
  // (...)
else
  // (...)
```

**Comment by oleg-shilo** [comment]
Done. 
In a mean time you can use `SetupEventArgs.IsUISupressed`.

**Comment by Eagle3386** [comment]
Thanks a lot, @oleg-shilo! 😄
