### ISSUE TITLE
Different background colors for text and background.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#174]
See picture.
(1) has color #d3cfcb.
(2) has color #d4d0c8.

Is especially visible when running on terminal server with RDP.

Suggestion is to make the text render on a transparant background. Or to use #d4d0c8 also for labels.

![image](https://user-images.githubusercontent.com/7579444/31069254-f75f1f8e-a75b-11e7-86d0-6fd1319c8bc1.png)

**Comment by oleg-shilo** [comment]
If it is ManagedUI then all text background colors are already set to `Transparent`. Though WinForns can be tricky with transparency.

If the problem only appears with RDP then I wouldn't pay much attention to this issue at all. RDP has it's own approach to managing performance by degrading colors. 

Also, I don't see any label next to the (2) marker on your image.
