### ISSUE TITLE
More user-friendly status label.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#175]
The status label is now for instance "InstallInitialize" or "RollbackFiles" etc.

This is not English and probably a reflection of the inner workings.

Suggested change to use text comprehensible for non-techies, such as:

- Initialize Installation
- Rollback Files

Etc.

![image](https://user-images.githubusercontent.com/7579444/31069302-328e0ffc-a75c-11e7-8a4e-c7e64f3bf551.png)

**Comment by oleg-shilo** [comment]
The information about the progress status is passed to the message handler with the `Record` object. The object itself implements localization and formatting. The class encapsulates formatting template `record.FormatString` and collection of fields to be used as formatting arguments. Triggering formatting can be as simple as calling `record.ToString`.

Thus template `Action 0:25:01: [1]. [2]` after formatting can become `Action 0:25:01: CostInitialize. Computing space requirements`

The field 2 (`record[2] == "Computing space requirements"`) seems to be a perfect candidate for dialog the label text. However some fields come in a cryptic form that is not fulli compatible with UI scenarios. For example the value of `record[2]` for InstallFiles action is `Copying new files File: [1],  Directory: [9],  Size: [6]`. Any further resolving formatting handlers is problematic. That is why I decided to show only a raw name of the action which, is the field with index 1 (record[1]).

 However if the full message is preferred (even if it is not fully resolved) then it can be achieved by using custom ProgressDialog with the flag `simple` set to false: 

```C#
public override MessageResult ProcessMessage(InstallMessage messageType, Record messageRecord...
{
    ...
    switch (messageType)
    {
        case InstallMessage.ActionStart:
        {
            try
            {
                bool simple = true;                            {
               ...
```
