### ISSUE TITLE
setdirectory missing

### ISSUE THREAD

**Issue by digitalsigi** [oleg-shilo/wixsharp#176]
Hi,
I need to create a new directory on C Drive root folder e.g. C:\MyNewDir if it doesn't exist. In plain WIX I would do it with Directory and SetDirectory, like here: [https://stackoverflow.com/questions/15921078/wix-toolset-create-directory-in-root-disk-system-disk-or-c-and-copy-files-i](url).
How to do that with WixSharp? Do I have to implement a Custom action for that?

Josef

**Comment by oleg-shilo** [comment]
Have a look at InstallDir_AbsolutePath sample

**Comment by digitalsigi** [comment]
Oh my goodness, Its a shame, it is so simple, and I did not figure it out. Blame on me.
Thx for careing.
Josef

**Comment by oleg-shilo** [comment]
:)
