### ISSUE TITLE
SetupEventArgs - e.IsUninstalling is false when using maintenance dialog - remove

### ISSUE THREAD

**Issue by martinbu** [oleg-shilo/wixsharp#177]
Hi,

I have the problem that the IsUninstalling property of the SetupEventArgs in the project AfterInstall event is false if the program is removed via the maintenance dialog (Execute the msi file again and choose remove).

Everthing works correctly if I uninstall the program in the system control or via an uninstall shortcut.

Is this an intended behaviour?

```
public static void Main(string[] args)
{
  var project = new ManagedProject("IsUninstallTest",
                  new Dir(@"%ProgramFiles%\UninstallTest\",
                    new File("readme.txt")));

  project.AfterInstall += Project_AfterInstall;

  project.BuildMsi();
}

private static void Project_AfterInstall(SetupEventArgs e)
{
  System.Windows.Forms.MessageBox.Show("Is Uninstalling: " + e.IsUninstalling);
  if (e.IsUninstalling)
  {
    // e.IsUninstalling is always false if the uninstall is triggered via executing the msi again
    // and click remove in the maintenance dialog
  }
}
```

Regards,
Martin

**Comment by martinbu** [comment]
The behavior is also correct when using a ManagedUi. But that is not the case at the moment.

```
project.ManagedUI = new ManagedUI();
project.ManagedUI.ModifyDialogs.Add(Dialogs.MaintenanceType)
                               .Add(Dialogs.Features)
                               .Add(Dialogs.Progress)
                               .Add(Dialogs.Exit);
```

**Comment by oleg-shilo** [comment]
Believe it or not but it is actually correct behavior. :)
From MSI point of view it is not an uninstall but a product modification, even if you are removing all components. If msi was not started with an "uninstall" argument then it is not an "uninstall".

Technically it is correct but practically... well, ridiculous. In ModifyDialog of ManagedUI I forcefully set `REMOVE=ALL` so it helps the users. But if you are using native UI then you are on mercy of the MSI interface designers.

I suggest you evaluate all available session properties and see if you can use them to detect "uninstalling". You can do this by placing `MessageBox.Show(e.ToString());` in AfterInstall handler. I have captured one for you:
 
![image](https://user-images.githubusercontent.com/16729806/31132647-1687ebe0-a8a9-11e7-9747-d5fdef623bab.png)

If this does not help then you will need to use something else. I.E. test the pretense of some file.

**Comment by martinbu** [comment]
Hi Oleg,

thank you for your fast response. I could manage the problem by setting the REMOVE property manually.

```
customUI.On(NativeDialogs.MaintenanceTypeDlg, Buttons.Remove, new SetProperty("REMOVE", "ALL"), new ShowDialog(NativeDialogs.VerifyReadyDlg));
```

Now everything works as expected.

**Comment by oleg-shilo** [comment]
👍
