### ISSUE TITLE
How to do a FILESEARCH in WixSharp

### ISSUE THREAD

**Issue by digitalsigi** [oleg-shilo/wixsharp#179]
For several reasons I am in the process of migrating a WIX based installer to WixSharp. In WIX I have following snippet to determine the installed Version of Word an use it in an condition:
```XML
<Property Id="WORDEXEVERSION" Secure="yes">
      <RegistrySearch Id="RegSearch_WORDEXE" Root="HKLM" Key="SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\Winword.exe" Type="file">
        <FileSearch Name="WINWORD.EXE" MinVersion="14.0.0.0" />
      </RegistrySearch>
    </Property>
    <Condition Message="Word 2010 or newer is required"><![CDATA[Installed OR WORDEXEVERSION]]></Condition>
```

I found a bootstrap sample with utilsearch, but this is not a bootstrapper.
How to to do this in WixSharp?
Josef

**Comment by oleg-shilo** [comment]
You can have a look at ["RegistrySearch"](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples) sample. "LaunchConditions" sample handles the use-case very similar to yours.

Though you can also go with the ManagedSetup and have it as simple as below:
```C#
var project = new ManagedProject("ManagedSetup", 
...
project.BeforeInstall += project_BeforeInstall;
...
static void project_BeforeInstall(SetupEventArgs e)
{
    var word_exe = (string)Registry.GetValue(<key_name>, <value_name>, <default_value>);
    if (!File.Exists(word_exe))
    {
        MessageBox.Show("Word 2010 or newer is required"), e.ProductName);
        e.Result = ActionResult.Failure;
     }
}

```

**Comment by digitalsigi** [comment]
Hi Oleg,
Had a strange experience with managedproject with backgroundimage WxH, so I did not follow this path and did not consider that as a real issue.
Have now implemented following solution:
```C#
            project.AddWixFragment("Wix/Product", XElement.Parse(@"
                 <Property Id=""ADOBEEXEVERSION"" Secure=""yes"">
      <RegistrySearch Id = ""RegSearch_WORDEXE"" Root = ""HKLM"" Key = ""SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\AcroRd32.exe"" Type = ""file"">
        <FileSearch Name = ""AcroRd32.exe"" MinVersion = ""10.0.0.0""/>
      </RegistrySearch >
    </Property >

            "));
            project.LaunchConditions.Add(new LaunchCondition("Installed OR ADOBEEXEVERSION", "Für diese Anwendung muss Adobe Reader Ver 10 oder neuer installiert sein."));

```
which works fine.

**Comment by oleg-shilo** [comment]
Yep. Good work around.

But the problems you experienced were related to the ManagedUI not ManagedProject. ManagedUI is a WinForm solution thus it inheritably affected by all WinForms limitations. You just simply need to use NativeUI with managed project and you'll be OK: 

```C#
// project.ManagedUI = ManagedUI.Default;
project.UI = WUI.WixUI_Mondo;
```
Even more, should you ever in the future decide to go C# path, you don't have to use ManagedProject. You can keep your `Project` as you do now. The only difference is that you cannot use event any handlers and need to add [ManagedCustomActions](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/DTF%20(ManagedCA)/setup.cs) manually instead:
```C#
static public void Main(string[] args)
{
    var project = new ManagedProject("CustomActionTest",
            new Dir(@"%ProgramFiles%\My Company\My Product",
                new File("setup.cs")),
            new ManagedAction(CustomActions.MyAction, Return.check, When.Before, Step.LaunchConditions, Condition.NOT_Installed));

    project.BuildMsi();
}

public class CustomActions
{
    [CustomAction]
    public static ActionResult MyAction(Session session)
    {
        var word_exe = (string)Registry.GetValue(<key_name>, <value_name>, <default_value>);
        if (!File.Exists(word_exe))
        {
            MessageBox.Show("Word 2010 or newer is required"), session.Propert("ProductName"));
            return ActionResult.Failure;
         }
         else 
             return ActionResult.Success;
    }
}
```
