### ISSUE TITLE
WixCLRDialog error

### ISSUE THREAD

**Issue by yfnfif** [oleg-shilo/wixsharp#18]
Hello!
I've added an dialog inherited from WixCLRDialog. 
Depending on the input data I want to inject my dialog using project.InjectClrDialog or not inject.

```C#
project.UI = WUI.WixUI_InstallDir;
if (args[0] == "InjectClrDialog")
{
    project.InjectClrDialog("ShowCustomDialog", NativeDialogs.InstallDirDlg,
                        NativeDialogs.VerifyReadyDlg);
}
project.RemoveDialogsBetween(NativeDialogs.WelcomeDlg, NativeDialogs.InstallDirDlg);
```
If project.InjectClrDialog is called, it's OK.

If project.InjectClrDialog isn't called, I've got the errors:
```
The command "cd "C:\Work\app-installer\AppInstaller\" "C:\Work\app-installer\AppInstaller\bin\Debug\Setup.exe" 111" exited with code 1.
Dependent assembly not supplied: WixSharp.UI, Version=1.3.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2
System.IO.FileLoadException: Cannot resolve dependency to assembly 'WixSharp.UI, Version=1.3.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
```

**Comment by oleg-shilo** [comment]
It looks like in your setup there is somewhere dependence on `WixShar.UI` assembly and it is not packed if you do not call InjectClrDialog. There are various ways to pack the referenced assemblies but arguably the simplest one is an unconditional approach via DefaultRefAssemblies:
```C#
// pack WixShar.UI.dll
project.DefaultRefAssemblies.Add(typeof(WixCLRDialog).Assembly.Location);
```

The chances are that it will help. Othervise you may need to do custom assembly loading/probing.
___

As a side note, I cannot recommend CLR dialog injection as a default approach. It is still a valid technique that sometimes is a  saver, but _Managed UI_ is by far a more manageable approach. As a simple generic rule "Use ManagedUI if you can and InjectCLRDialog if you have to".
