### ISSUE TITLE
Question: Is it possible to do this with Wixsharp

### ISSUE THREAD

**Issue by sherry-ummen** [oleg-shilo/wixsharp#181]
Hi,

I want to create an installer which, downloads an msi install that and then install itself.

When user uninstalls this app then it should also uninstall the other msi (which was downloaded and installed) and then uninstall itself.

Is it possible to do with WixSharp? If yes then could you please provide me with an example?

Sherry

**Comment by Dalstroem** [comment]
In my experience with MSI and Windows, it's not possible to run multiple MSI installers at the same time.

**Comment by sherry-ummen** [comment]
Hmm I have the same feeling as well, but then there some Bootstrapper in Wix which could be used somehow to achieve this. I am not sure, I have not read their documentation as it just goes beyond my head.

**Comment by sherry-ummen** [comment]
One way could be that the main installer is an exe and that installs the downloaded msi? Hmm I dont know whether thats even possible or makes any sense.

**Comment by Dalstroem** [comment]
Sure, you can run EXE and MSI at the same time, but you have to finish MSI no. 1 before starting no. 2. Otherwise it will return an error.

**Comment by sherry-ummen** [comment]
Hmm could you elaborate a bit more.

I am currently doing is
I have a custom .exe wpf app, which downloads the required .msi and then installs it. For uninstallation I have to use the same .exe as I did not find a way to register the app to be shown in the Programs and Features.

**Comment by oleg-shilo** [comment]
> One way could be that the main installer is an exe and that installs the downloaded msi?

You are talking bootstrapper now. 

Any bootstrapper (either stock or custom) is a native application that is hosted by OS itself but not MSI runtime. Thus bootstrapper process does not interfere with the MSI installation at all. 

Browse bootstrapper samples and you may find what you are looking for: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples

**Comment by sherry-ummen** [comment]
thanks, before I delve into it . Could you confirm it possible that if I do the bootstrapper way then
* It is possible for the installer to download an msi and installer it 
* The main installer and the downloaed installer will be seen in the Programs and features 
* On uninstalling the main installer its possible to uninstall the downloaded msi as well

**Comment by oleg-shilo** [comment]
When I was describing bootstrapper I was referring to Burn (part of WiX suite). Wix# provides the API integration for Burn. See bootstrapper samples. Thus please be aware that it is not Wix# but rather Burn who controls the butstrapper behavior. 

* _It is possible for the installer to download an msi and installer it_
The `MsiPackage` class has `DownloadUrl` property:

```C#
        var msiOnlinePackage = new MsiPackage(crtMsi) //demo for downloadable msi package
        {
            Vital = true,
            Compressed = false,
            DisplayInternalUI = true,
            DownloadUrl = @"https://dl.dropboxusercontent.com/....../CRT.msi"
        };
```
* _The main installer and the download installer will be seen in the Programs and features_
Let's use accurate terminology. "installer" is always an msi file.  "main installer" is not an installer but an installer launcher. Native application that manages installer(s). 

Depending on the boostrapper and MSI package properties you an make either name of a boostrapper or embedded packages appear in the control panel. Consult Burn documentation.
   
* _On uninstalling the main installer its possible to uninstall the downloaded msi as well_
Yes. This behavior can be achieved. For details look at Wix# bootstrapper samples and consult WiX bootstrapper (Burn) documentation.
