### ISSUE TITLE
Certificate - SetComponentPermanent(true) does not make component permanent

### ISSUE THREAD

**Issue by jonreis** [oleg-shilo/wixsharp#184]
I am setting my certificates as permanent:
   project.Certificates.ForEach(c => c.SetComponentPermanent(true));

yet, when I look at the generated wix code I see:

          <Component Id="Certificate2" Guid="2cb16dd1-db19-4d3b-8644-695e9f6da0a2" KeyPath="yes">
            <Certificate Id="_...DO_RSA_Certification_Authority" BinaryKey="comodorsaaddtrustca.crt" Name="COMODO RSA Certification Authority" Overwrite="no" StoreLocation="localMachine" StoreName="ca" xmlns="http://schemas.microsoft.com/wix/IIsExtension" />

            <CreateFolder />
          </Component>

Should there be a Permanent = "yes" attribute?

**Comment by jonreis** [comment]
`        public XContainer[] ToXml()
        {
            var element = new XElement(WixExtension.IIs.ToXNamespace() + "Certificate");

            element.SetAttribute("Id", Id)
                   .SetAttribute("BinaryKey", BinaryKey)
                   .SetAttribute("CertificatePath", CertificatePath)
                   .SetAttribute("Name", Name)
                   .SetAttribute("Overwrite", Overwrite)
                   .SetAttribute("PFXPassword", PFXPassword)
                   .SetAttribute("Request", Request)
                   .SetAttribute("StoreLocation", Enum.GetName(typeof(StoreLocation), StoreLocation))
                   .SetAttribute("StoreName", Enum.GetName(typeof(StoreName), StoreName))
                   .AddAttributes(this.Attributes); // add this?

            return new[] { element };
        }`

Maybe need to add: .AddAttributes(this.Attributes); ?

**Comment by oleg-shilo** [comment]
Yep. Will do.
Thank you.

**Comment by oleg-shilo** [comment]
Excellent pick. Found some other cases of `ToXml()` that needed fixing. 
Done. Will be available  in the next release.
