### ISSUE TITLE
Dynamic features

### ISSUE THREAD

**Issue by F1nZeR** [oleg-shilo/wixsharp#186]
Is it possible to create dynamic features during the installation process?
I want to automatically detect installed software on target user pc and to provide list of possible extensions (via features list) for every software.

p.s. also now I'm using ManagedUI with UIInitialized event where I'm looking for installed software via registry lookup, but it gives different results on my machine: during the msi build and during the installer launch. Which .net is used during the installation process? (proj has been built with .net 3.5)

**Comment by oleg-shilo** [comment]
A good option is to fave all features defined in your MSI and only make them available depending on the target environment characteristics.

> but it gives different results on my machine: during the msi build and during the installer launch.

It supposed to. These are two different systems.

> Which .net is used during the installation process?

The one that is present on the target system. Your build system has nothing to do with the installation itself.

DTF (WiX subsystem responsible for loading CLR) loads the framework, which is available on the target system and suits the best the assembly you have embedded in MSI. User can specify custom `Project.CAConfigFile` at to assist with the CLR loading (e.g. EmbeddedUI sample).

The simplest way to avoid problems is to keep your managed UI assembly target version as low as practical.
