### ISSUE TITLE
How to Use "RemoveExistingProducts"

### ISSUE THREAD

**Issue by WarriorBlue** [oleg-shilo/wixsharp#187]
Thank you in advance for creating so wonderful tool of Wix.

I have a problem here. How to use RemoveExistingProducts in Wixsharp.

Thank you again.

**Comment by oleg-shilo** [comment]
You typically don't use this element directly. Though if you do, please provide the WiX use-case so it's possible to assess what the porting path is.

But the simplest (though not the most elegant) way to handle this is to inject XML fragment before compilation.
