### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by sherry-ummen** [oleg-shilo/wixsharp#189]
hi,

I am in a weird situation. I am trying to create a upgrade for the existing installer which I created using Wix#. But in the uninstall phase I created a bug, because of which uninstall did not happen and msi crashed.

Now I fixed the issue, but whenever I uninstall the msi I still get the crash meaning my new changes are not reflected in the uninstall phase. I do not understand why its not taking my changes.

The main() looks like this
```csharp
  public static void Main() {
            try {
                Compiler.WixLocation = @"..\packages\WixSharp.Binaries.1.0.35.0\lib\bin"; // TODO: Adding "WIXSHARP_WIXDIR=" to the csproj does not work. Find a better way?
                var project =
                    new Project(Constants.NAME,
                        new Dir(Constants.INSTALLER_DEFAULT_INSTALL_PATH),
                        new ElevatedManagedAction(CustomActions.InstallService, Return.check, When.After,
                            Step.InstallFiles, Condition.NOT_Installed),
                        new ElevatedManagedAction(CustomActions.UnInstallService, Return.check, When.Before,
                            Step.RemoveFiles, Condition.BeingRemoved));

                project.ProductId = Guid.NewGuid();
                project.GUID = new Guid("E3C6F2FF-CA9E-4391-B69F-19108CC08F85");
                project.OutFileName = Constants.SETUP_FILE_NAME;
                project.Version = new Version(Constants.INSTALLER_VERSION);
                project.Platform = Platform.x64;
                project.OutDir = @"..\ServerDBInstaller\bin";
                AddHelpInformation(project);
                project.MajorUpgrade = new MajorUpgrade {
                    Schedule = UpgradeSchedule.afterInstallInitialize,
                    AllowSameVersionUpgrades = false,
                    DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
                };
                project.BuildMsi();
            } catch (Exception ex) {
                Console.WriteLine(ex.Message);
            }
        }
```

**Comment by oleg-shilo** [comment]
Wix# is kind of irrelevant here. You have an exception during uninstall and it obviously prevents uninstall completion. MSI does not give you any mechanism for recovering.  

During my testing it happens from time to time. I usually remove install information from registry manually. Though I cannot recommend it as a generic technique. Your best chances are with _Revo Uninstaller_ (Chocolaty: https://chocolatey.org/packages/Revo.Uninstaller/1.9.4.1). Or other similar product.

It automatically clears registry from the products that failed to do so on uninstall.

**Comment by sherry-ummen** [comment]
Ohh ok. Thanks for the info.
