### ISSUE TITLE
iis:Certificate

### ISSUE THREAD

**Issue by TerribleDev** [oleg-shilo/wixsharp#19]
I'm trying to figure out how I can install an SSL cert into an iis website akin to wix's iis:Certificate xml node

**Comment by oleg-shilo** [comment]
Can you send a WiX fragment that shows the usage. 

Wix# comes with the `Certificates` sample but it relies on `Certificate` element. Thus `iis:Certificate` has no direct element-based support but most likely can be easily added via attributes or xml injection.

**Comment by TerribleDev** [comment]
Honestly, I think I figured it out myself....I'll include a fragment here shortly that i believe will work...

**Comment by oleg-shilo** [comment]
Yep, this is the way to go. 

The idea was that for anything that is not immediately available devs can use _XML injection_, which covers support for fragments, includes and direct manipulation of the xml tree, If any of these use-cases deserve to be ported into (directly supported by) Wix# compiler then I expected that the developer(s)  would send me their solution and I would do the porting.

Thus if you wish, you can share your work around and I will see if making it the core functionality makes sense.

**Comment by TerribleDev** [comment]
ok good to know. I've been using wix sharp for some time, and it has been great! So thanks for maintaining it

**Comment by oleg-shilo** [comment]
Glad you like it :)
Closing the issue...
