### ISSUE TITLE
Question: How to check if feature was installed during setup

### ISSUE THREAD

**Issue by paiden** [oleg-shilo/wixsharp#190]
Our managed UI install sequence contains the standard feature selection dialog and a custom exit dialog.

Depending on the feature selection the user made during the install, the behavior of the exit dialog should change. 

```csharp
// Global feature definitions
Features.FeatureA = new Feature("A", "Description")

// Exit Dialog On Load etc.
if(WasFeatureInstalled(Features.FeatureA)) {
  this.labelExitMessage.Text = "yes";
}
else {
  this.labelExitMessage.Text = "no";
}
```

I was not able to find a example that does something like this. Is there a way to do this with WixSharp?

**Comment by oleg-shilo** [comment]
Please see this code fragment: https://github.com/oleg-shilo/wixsharp/blob/504737ae68fd69587efd63db1f4dc2f9b93dec0f/Source/src/WixSharp.UI/ManagedUI/Forms/FeatureItem.cs#L136

**Comment by paiden** [comment]
Thanks that helped me to get it to work. Just for reference and to help others, this is the helper method I'm currently using in the dialog:

```csharp
        private InstallState GetFeatureState(string name)
        {
            var installedPackage = new ProductInstallation(this.MsiRuntime.ProductCode);

            if (installedPackage.IsInstalled)
            {
                return installedPackage.Features
                    .First(x => x.FeatureName == name)
                    .State;
            }
            else
            {
                return InstallState.Absent;
            }
        }
```
