### ISSUE TITLE
Minor upgrade/patch workaround?

### ISSUE THREAD

**Issue by QuentinSuckling** [oleg-shilo/wixsharp#192]
Hi Oleg,

I know there's no minor upgrade/patching in WixSharp but I was wondering if there is workaround or hack using MajorUpgrade to allow me to push just a subset of files out?

I'll describe my situation so you get a better idea -
It's a rich-client WPF app that is about 300MB but it's fairly new so I'm pushing out updates every few days/1 week or so.
The thing is that most of the 300MB is images/resources and 3rd party libraries that will only change a few times a year. The updated files I need to push out are only about 10mb or so.
If the users were in an office then I wouldn't have an issue giving them a full build each time, but they are out on the road usually and connecting with limited mobile 4G.
Having them download the full install each time isn't an option.

I thought I might be able to work around it with Features.
I specified features for all the other files/shortcuts and had the update binaries separated into their own feature.
Then in the upgrade installer I only included the update binaries and set the MajorUpgrade.RemoveFeatures = string.Empty. (full definition below)
The description says that this means no features will be removed.
But when I ran the upgrade installer it still removed all the other features and just reinstalled the updated binaries.
Am I misunderstanding how that process works?

Anyway, what are your thoughts on the best way to handle this?

Thanks,
Quentin

            project.MajorUpgrade = new MajorUpgrade
            {
                Schedule = UpgradeSchedule.afterInstallInitialize,
                MigrateFeatures = true,
                RemoveFeatures = string.Empty,
                IgnoreRemoveFailure = true,
                DowngradeErrorMessage = Resources.DowngradeErrorMessage
            };

**Comment by oleg-shilo** [comment]
Yes, the scenario you are describing is more consistent with Minor not Major update.  Though I am not entirely convinced MSI offers the best solution for the application resources update mechanizm. 

You have only two choices:
* You can implement MinorUpgrade with XML injection during WixSharp build.
* You can rework application architecture to allow dynamic resource update (WPF is already ready for this). Thus you can download a "resource update" package, unpack it and load on app restart.  It makes a good sense from design point of view but it may be quite effort consuming to implement.

**Comment by QuentinSuckling** [comment]
Ok, thanks Oleg.

I'll investigate those options and let you know if I've got any more questions.

Cheers,
Quentin
