### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#193]
Hi Oleg.
I looked at your localization example (Wix # Samples \ Localization \ Full Localization (Czech))
I have an easier way to use localization resources:

```
string lang = "cs-CZ";
Thread.CurrentThread.CurrentUICulture = new CultureInfo(lang);
project.Language = lang;
```

Now you can use resources without problems
`project.MajorUpgrade.DowngradeErrorMessage = Resource.NewerVersionDetected;`
_________________________________
Sorry for my Google Translate :)

**Comment by oleg-shilo** [comment]
Not exactly :)
What you have done is setting the UI culture during build time at the machine you used to build your msi.

This has nothing to do with the believer of your custom UI on the target PC because that building routine will never be executed during the installation.

If you want ti init CurrentUICulture for custom UI you need to do it at runtime from the corresponding event handler:
```C#
project.Language = "de-de";
     
project.UIInitialized += e =>
        {
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(project.Language);
        };
```

**Comment by oleg-shilo** [comment]
After some further consideration I decided to do the CurrentUICulture automatically for all ManagedUI sequences (in WixSharp.UIShellShoeModal). 
```C#
try
{
    int cilture = msiRuntime.Session.Property("ProductLanguage").ToInt();
    if (cilture != 0)
        Thread.CurrentThread.CurrentUICulture = new CultureInfo(cilture);
}
catch { }
```
Marking this issue and "Enhancement"

**Comment by Xaddan** [comment]
It is not much not what I was talking about.
I don't use ManagedUI in their installers. I use Bootstrapper as the installation interface, but some text I use the msi installers. This is the text associated with the Feature, the text from CA.
When you build the installer with a culture different from the culture of Windows I get the error:
> LGHT0311 error : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database''s code page, or update the database''s code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.

Will tell you how it went.
The culture of my Windows is Russian.
I created an installer with 2 localizations-English and Russian.
When creating installer, I created 2 resource file: Resource.resx and Resource.EN-us.resx
In The Resource.resx files are English localization strings in the Resource.EN-us.resx Russian respectively.

When assembling I change only project.Language
```
project.Language = “en-US”;
project.Language = “ru-RU”;
```
During Assembly of the Russian installer no problem, I did not receive. Installer to build and work as expected, everything was localized.
When creating the English I was getting the above described error, looking wixsharp generated wxs file I saw there is Russian localization strings.
It turns out that wixsharp used the culture of Windows and the Assembly took localization strings ...\ru-ru\ ProjectName.resources.dll
_________________________________
Sorry for my Google Translate :)

**Comment by oleg-shilo** [comment]
Don't worry about "Google Translate". You English is fine. :)

According your description you do indeed have compile time problem. I really need to get to the bottom of it. Can you please provide more details on "It turns out that wixsharp used the Windows culture". 

Did you find something in the code/XML that triggered using that specific culture? If so what was it exactly?

Thank you.

**Comment by Xaddan** [comment]
I was a bit inaccurate when I said that it was wixsharp. This is the behavior of all applications written in C#. [Thread.CurrentUICulture](https://msdn.microsoft.com/ru-ru/library/system.threading.thread.currentuiculture(v=vs.110).aspx) is exposed depending on the culture of the operating system.
> The UI culture specifies the resources an application needs to support user input and output, and by default is the same as the operating system culture.

This causes the program to look for resources that match the Windows culture.
To solve the problem, I used what I described in the first post.

I made a small project for clarity: [CultureTest.zip](https://github.com/oleg-shilo/wixsharp/files/1464042/CultureTest.zip)

**Comment by oleg-shilo** [comment]
Yep, this is what I thought. 

And this is exactly what was that enhancement for CustomUI. Before popping the first dialog Wix# **runtime** sets current culture to the language of the Wix# project.

Though I don't see how the change to the "build script" (WixSharp project) at **compile** time can affect anything.  

I took your test project and was able to build it as is:
```C#
string lang = "ru-RU";
//lang = "en-US";

//Thread.CurrentThread.CurrentUICulture = new CultureInfo(lang);
```
And after that I built it for en-US:
```C#
string lang = "ru-RU";
lang = "en-US";

//Thread.CurrentThread.CurrentUICulture = new CultureInfo(lang);
```
So I kind of see no problems here. So what exactly uncommenting `CurrentUICulture = ...` does achieve?

**Comment by Xaddan** [comment]
Probably because of the fact that you, most likely, the English culture of Windows is not manifested. Try to swap resources in places. Resource.resx was mined Russian text in English, and Resource.en-US.resx rename Resource.ru-RU.resx and replace English text with Russian.

**Comment by oleg-shilo** [comment]
OK, I see. I missed the point that you are pushing the MSI builder application resources into the WiX definition via `DowngradeErrorMessage = Resource.NewerVersionDetected,`.

I was afraid that somewhere Bootstrapper does not initializes itself at runtime correctly. But it is in fact a pure compile time challenge associated with the way you push your string content into the MSI to be built. Thus clearly there is nothing wrong with WixSharp itself nor the way it triggers underlying compilers: burn and candle.

Anyway, it all means that your post is in fact a useful technique that can be useful for others but it does not directly belongs to the WixSharp domain. However, I wouldn't mind to put some measures to assist developers in the situation like yours. Thus I have changed the implementation of the `Project.Language` to synch CurrentCulture with the language specified by the developer:
```C#
public string Language
{
    get { return language; }
    set
    {
        language = value.DeflateWhitespaces();
        try
        {
            if (language.IsNotEmpty())
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);
        }
        catch { }
    }
}
```
It will certainly solve your problem but.... only if you assign language before accessing the resources:
```C#
// will work
var project = new Project("ProjectName");
project.InstallScope = InstallScope.perMachine;
project.Language = "en-US";
project.MajorUpgrade = new MajorUpgrade
{
    ...
    DowngradeErrorMessage = Resource.NewerVersionDetected,
};

// will not work
var project = new Project("ProjectName");
project.MajorUpgrade = new MajorUpgrade
{
    ...
    DowngradeErrorMessage = Resource.NewerVersionDetected,
};
project.InstallScope = InstallScope.perMachine;
project.Language = "en-US";
``` 

Thank you for sharing the test project. It was crucial for understanding the nature of the problem.

**Comment by Xaddan** [comment]
Not at all. I'm glad that I helped to improve the project.
