### ISSUE TITLE
Get temp folder

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#194]
The method used to get the path to the temp folder looks a bit wrong (Source\src\WixSharp\SharedExtensions.cs):
```
case "TempFolder": return Path.Combine(Path.GetDirectoryName(Environment.GetFolderPath(Environment.SpecialFolder.Desktop)), @"Local Settings\Temp");
```
Starting with Windows 7 the temp is located in: ..\AppData\Local\Temp
It seems to me that this will be better:
```
case "TempFolder": return Path.GetTempPath();
```
_________________________________
Sorry for my Google Translate :)

**Comment by oleg-shilo** [comment]
Agree. Thank you for reporting.
Fixed.
Will be available in the next release.
