### ISSUE TITLE
Unable to change registry value while installing.

### ISSUE THREAD

**Issue by pr4v33nv3rm4** [oleg-shilo/wixsharp#195]
hi,
I am trying to enable "developer mode" in windows 10 using my installer.
as [Microsoft site](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development)  suggest's it can be done using below powershell command.

`reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"`

This works completely fine if i execute this via command prompt as admin.

Now to achieve the same with my installer i tried two approaches.
1. Executing the same command from a bat file as process on custom action with

`Execute.deferred,
Impersonate = false`

above while executing says  "The operation completed successfully." in console but the registry value is not getting changed.

2.Using the WixSharp inbuilt RegValue() property:

`new RegValue(fullSetup, RegistryHive.LocalMachine, @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock", "AllowDevelopmentWithoutDevLicense", "#1"), 
`

This gives me warning related to access permission: 

> Verify that you have sufficient access to that key,or contact your support personnel.

Are there any options to provide additional privileges? 
Any help will be appreciated.

**Comment by oleg-shilo** [comment]
There can be quite a few reasons. 

Your 1 may put the data to the roming hive. Writ esomething distinctive as a value (e.g. `$$$$$$$tets$$$$$`). Then search registry for this value. You will see where it end up.

Your 2 may be running at runtime without elevation. 'SinglePackageAuthoring' sample shows how to elevate scope. But being C# developer I always prefer programming for that:
```C#
project.AfterInstall += project_AfterInstall;
static void project_AfterInstall(SetupEventArgs e)
{
    try
    {
        // Set your registry from here
    }
    catch { }
}
```

**Comment by pr4v33nv3rm4** [comment]
hi oleg,

Thanks for replying back.
I tried below approach.

```
project.AfterInstall += project_AfterInstall;
static void project_AfterInstall(SetupEventArgs e)
{
    try
    {
        // Set your registry from here
        // Note, you are already elevated
         RegistryKey key = Registry.LocalMachine.OpenSubKey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock", true);
                if (key != null)
                {
                    key.SetValue("AllowDevelopmentWithoutDevLicense", "91642220", RegistryValueKind.DWord);
                    MessageBox.Show(key.GetValue("AllowDevelopmentWithoutDevLicense").ToString());
                    key.Close();
                }
    }
    catch { }
}

```

The installer finished successfully without exception the message box shows the registry value as "91642220" ,but when i tried searching the registry for value "91642220" it's no where to be found.
Could you suggest what should i try next.

**Comment by pr4v33nv3rm4** [comment]
Ok got it,
I am on 64 bit machine so i should specify that in code.

`RegistryKey key = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64).OpenSubKey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock", true);`

above worked. :)

**Comment by oleg-shilo** [comment]
Great.

This is what I meant by "our 1 may put the data to the roaming hive." Though I would still expect you to be able to find this value in the `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node` branch.
