### ISSUE TITLE
ID Generation is weak

### ISSUE THREAD

**Issue by emmoemminghaus** [oleg-shilo/wixsharp#196]
Situation:
The Project has one File called ~/Views/BBB/Index.cshtml in previous setup.
A new file ~/Views/AAA/Index.cshtml is added.
After i run the Update the file ~/Views/BBB/Index.cshtml is removed.

Result:
The ID for ~/Views/BBB/Index.cshtml changes from "Component.Index.cshtml" to "Component.Index.cshtml.1" 
~/Views/AAA/Index.cshtml gets "Component.Index.cshtml"
(AAA is scanned first then BBB, order is important to retrace this)

The Problem:
When you do a update installation and remove the existing Product after the installation, then a file that has a changed ID is removed (regardless of the ID exists on another file).

Conclusion:
The ID MUST not change at all costs, otherwise you loose files on upgrade.
Doing the Removal before Install is no solution, e.g. when you don't want to reinstall services (Just because you don't want to ask for the username and password). Also "Removal after install" is mentioned as the most efficient Method in [RemoveExistingProducts Action](https://msdn.microsoft.com/library/aa371197.aspx)

Proposal:
Add a selectable id generation scheme that generates a Hash of lowered relative installation path for files.
(Selectable because giving all files a new ID will remove them on next update)

**Comment by oleg-shilo** [comment]
The algorithm for ID auto-assignment is indeed has certain limits. Thus, historically the implementation approach was influenced by two major objectives. One, to reliably avoid ID duplication. And another one, to make IDs as human readable as possible. 

The second one was objective was rather "childish". As far as WixSharp concerned, the ID could be anything (even GUID) and its readability is truly irrelevant. The readability goal was dictated by the WiX traditionalists who insisted on WixSharp emitting WiX XML in its most orthodox form. 

In the result  the ID auto-assignment may not fit certain scenarios (e.g. yours). 
For those cases when the ID must be 100% deterministic you can always assign the ID directly to the critical entities:
```C#
var project = new Project("MyProduct",
                    new Dir(@"%ProgramFiles%\MyProduct",
                        new File(new Id("index_a"), @"files\aaa\Index.cshtml"),
                        new File(new Id("index_b"), @"files\bbb\Index.cshtml")));
```    
The code above produces the following XML:
```xml
<Component Id="Component.index_a" Guid="e4b5dae1-f2ca-4570-a721-44ef3500debd">
    <File Id="index_a" Source="files\aaa\Index.cshtml" />
</Component>

<Component Id="Component.index_b" Guid="e4b5dae1-f2ca-4570-a721-44ef3500deba">
    <File Id="index_b" Source="files\bbb\Index.cshtml" />
</Component>
```

Saying that, I really don't mind giving the user more power in influencing the ID generation, not only taking over completely. Thus I have implemented (committed but not released yet) mechanism for specifying the custom algorithm for the ID generation:
```C#
WixEntity.CustomIdAlgorithm =
    entity =>
    {
        if (entity is File file)
        {
            var target_path = project.GetTargetPathOf(file);
            var hash = target_path.GetHashCode32();

            // WiX does not allow '-' char in ID. So need to use `Math.Abs`
            return $"{target_path.PathGetFileName()}_{Math.Abs(hash)}";
        }
        return null;  // pass to default ID generator
    };
``` 
Thus you can still auto_IDs. The produced XML is:

```xml
<Component Id="Component.Index.cshtml_1630848081" Guid="5495a725-b52b-4e09-96f6-14d3079908f6">
    <File Id="Index.cshtml_1630848081" Source="files\aaa\Index.cshtml" />
</Component>

<Component Id="Component.Index.cshtml_1471362266" Guid="5495a725-b52b-4e09-96f6-14d306cc55b8">
    <File Id="Index.cshtml_1471362266" Source="files\bbb\Index.cshtml" />
</Component>
```

**Comment by emmoemminghaus** [comment]
This CustomIdAlgorithm is exactly what i mention.  Great. 🥇 
When do you plan to release this? (yesterday is a good idea :) )

Writing the ID "manually" is possible for my current project because there are only 3 Files missing.
But i doubt that in the near future this will be more and more, because we currently standardize filenames.

**Comment by oleg-shilo** [comment]
When do you plan to release this? (yesterday is a good idea :) )

Just because you asked... :)
Done. Grab the new release from NuGet

**Comment by emmoemminghaus** [comment]
Great, thank you.
