### ISSUE TITLE
How can I get wixpdb?

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#197]
Hi.
To create patches in WIX, I used this Pyro and wixpdb ([Using Purely WiX](http://wixtoolset.org/documentation/manual/v3/patching/wix_patching.html)).
I did not notice that wixsharp kept wixpdb, and did not find the settings responsible for this.
How can I get wixpdb using wixsharp?
_________________________________
Sorry for my Google Translate :)

**Comment by oleg-shilo** [comment]
This is what you need:
```C#
project.PreserveTempFiles = true;
```
This will preserve all temporary files including *.wixpdb.

**Comment by Xaddan** [comment]
Yes, I used this setting, but it does not save *.wixpdb, only *.wxs and *.wixobj.

**Comment by oleg-shilo** [comment]
You are right that flag only controls *.wxs. My mistake.

I have extended the functionality with the new flag that specifically controls DBG artifacts:
```C#
project.PreserveBdgFiles = true;
```
