### ISSUE TITLE
Files.AddRange not work

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#198]
Hi, Oleg.
I can not add files to the directory via Files.AddRange

Steps of action
1) create a directory:
```
private Dir _directxDir = new Dir(new Id("DIRECTX_INSTALL_LOCATION"), "DirectX9.0c");
```
2) create a list of files:
```
private File[] _directx_x32 =
		{
			new File(_directxFeature, "dxsetup.exe"),
			new File(_directxFeature, "dxupdate.cab"),
			new File(_directxFeature, "dxdllreg_x86.cab"),
			new File(_directxFeature, "dsetup32.dll"),
			new File(_directxFeature, "dsetup.dll"),
			new File(_directxFeature, "Apr2006_d3dx9_30_x86.cab"),
			new File(_directxFeature, "DEC2006_d3dx9_32_x86.cab"),
			new File(_directxFeature, "Nov2008_d3dx9_40_x86.cab"),
			new File(_directxFeature, "Aug2009_d3dx9_42_x86.cab"),
			new File(_directxFeature, "Aug2009_d3dx11_42_x86.cab"),
			new File(_directxFeature, "Jun2010_d3dx11_43_x86.cab"),
			new File(_directxFeature, "Aug2009_D3DCompiler_42_x86.cab"),
		};

```
3) add files to the directory:
```
_directxDir.Files.AddRange(_directx_x32);
```
But nothing happens, the list of files in the directory is empty.

What am I doing wrong?

Test project: [AddRangeTest.zip](https://github.com/oleg-shilo/wixsharp/files/1469889/AddRangeTest.zip)
_________________________________
Sorry for my Google Translate :)

**Comment by oleg-shilo** [comment]
As you can see from the signature the extension method is invoked against `IEnumerable<T>`, which does not allow the original collection to be modified: 

![image](https://user-images.githubusercontent.com/16729806/32804279-98dcfaca-c9da-11e7-8be7-3e5a97705581.png)

The solution is:
```C#
_directxDir.Files= _directxDir.Files.AddRange(_directx_x32);
```
The better name would be `_directxDir.Files.Combine(_directx_x32)` but it's already taken by LINQ. If you found it confusing you can just go with raw LONQ:
```C#
_directxDir.Files= _directxDir.Files.Combine(_directx_x32).ToArray();
```

**Comment by Xaddan** [comment]
How stupid it turned out, i was inattentive.
Thank you.

**Comment by oleg-shilo** [comment]
To be honest I expected it to be potentially confusing. I just took the risk when named the method this way.

If we find more developers making the same mistake, then ... I will need to rework the API :)

I, just got an idea. Will 'Merge' be a better, more intuitive name?
```C#
_directxDir.Files = _directxDir.Files.Merge(_directx_x32);
```

**Comment by Xaddan** [comment]
Yes "Add" means adding new elements to the current collection, it really confused and I did not pay attention to the syntax.
Yes, "Merge" will be more understandable.

**Comment by oleg-shilo** [comment]
Great, will mark AddRange as obsolete.

**Comment by oleg-shilo** [comment]
I was actually wrong. `Combine` is available. LINQ uses `Concat`.
Fixed.
 Now it is 
```C#
_directxDir.Files = _directxDir.Files.Combine(_directx_x32);
```

**Comment by jonreis** [comment]
Hi Oleg,
I have run into this a number of times myself. Is there a reason why arrays are exposed rather than List<T>?

From an interface standpoint it would be nicer to add files directly to the collection without having to merge to arrays together.

Just my 2 cents,

Jonathan
