### ISSUE TITLE
ProgressText

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#199]
How can I set the [ProgressText](http://wixtoolset.org/documentation/manual/v3/xsd/wix/progresstext.html) for my CA?

**Comment by oleg-shilo** [comment]
`ProgressText` element is a part of the WiX native UI support. WixSharp does not bring anything new in teh native UI. If you have to use it you should use it WiX way. 

While you can have a look at `CustomMSIDialog` project, which shows how to deal with native UI, WixSharp encourages the use of managed UI and deal with problems like yours in a traditional C# way.

If you choose this option then you will need to create your project from the  "Custom UI" project template, where you will heave the full access to the ProgressDialog: 
![image](https://user-images.githubusercontent.com/16729806/32805367-4a54df5a-c9dd-11e7-9ff7-410e4777ff72.png)

**Comment by Xaddan** [comment]
I do not need to change the ProgressDialog itself.
I need to add text that will show up over the progress bar, and inform about the execution of my CustomActions.
On Wix it looks like this:
```
<CustomAction Id="InstallDirectX" FileKey="File_DXSETUPEXE" ExeCommand="/silent" Execute="deferred" Impersonate="no" Return="check"/>

<InstallExecuteSequence>
      <Custom Action="InstallDirectX" After="InstallFiles">(!DirectX = 2) AND (&DirectX = 3)</Custom>
</InstallExecuteSequence>

<UI>
    <ProgressText Action="InstallDirectX">!(loc.InstallDirectXProgressText )</ProgressText>
</UI>
```
It is expected that something like that:
```
InstalledFileAction InstallDirectX = new InstalledFileAction("File_DXSETUPEXE", "/silent")
{
   Step = Step.InstallFiles,
   When = When.After,
   Return = Return.check,
   Execute = Execute.deferred,
   Impersonate = false,
   Condition = new Condition("(!DirectX = 2) AND (&DirectX = 3)"),
   ProgressText = Resource.InstallDirectXProgressText ,
};
```

**Comment by nathanbedford** [comment]
@oleg-shilo is there no plans to support the "ProgressText" feature (tied to a CA) as @Xaddan suggested?
