### ISSUE TITLE
File.Attributes (on parent Component) after setting File.NeverOverwrite will not work

### ISSUE THREAD

**Issue by pbalassone** [oleg-shilo/wixsharp#20]
Hello,

I'm adding a **File** instance to a project. I need the file (it is a database file) to be both permanent and to be never overwritten on upgrade/reinstallation.
I saw that the **Attributes** property of the **File** class is supporting a way to specify an attribute of the parent component element of the file, but if I set the **File.NeverOverwrite** property to true before setting the **File.Attributes** property with a new dictionary containing the value `{ "Component:Permanent", "yes" }` then the resulting auto-generated .wxs file contains the desired component with only the **NeverOverwrite** attribute set.
If I don't set the **File.NeverOverwrite** property, but I add also the value `{"Component:NeverOverwrite", "yes" }` to the **File.Attributes** dictionary, the resulting component has both the **NeverOverwrite** and **Permanent** attributes correctly set.

Case #1 (not working)

Code:
```
File databaseFile = new File(fileFullPath)
          {
            NeverOverwrite = true,
            Attributes = new Dictionary<string, string> { { "Component:Permanent", "yes" } }
          };
```

The code above generates the following xml elements in the auto-generated .wxs file:

```
<Component Id="Component.db.sqlite" Guid="123cb6bc-2fd4-4d54-a496-90ea76d1f866" NeverOverwrite="yes">
    <File Id="db.sqlite" Source="Database\db.sqlite" />
    <RemoveFolder Id="INSTALLDIR.Database" On="uninstall" />
    <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
        <RegistryValue Value="0" Type="string" KeyPath="yes" />
    </RegistryKey>
</Component>
```

Case #2 (properly working)

Code:
```
File databaseFile = new File(fileFullPath)
          {
            Attributes = new Dictionary<string, string> { { "Component:Permanent", "yes" }, { "Component:NeverOverwrite", "yes" } }
          };
```

The code above generates the following xml elements in the auto-generated .wxs file:

```
<Component Id="Component.db.sqlite" Guid="d96a16ee-d566-4745-9a90-0c72b953ae00" Permanent="yes" NeverOverwrite="yes">
    <File Id="db.sqlite" Source="Database\db.sqlite" />
    <RemoveFolder Id="INSTALLDIR.Database" On="uninstall" />
    <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
        <RegistryValue Value="0" Type="string" KeyPath="yes" />
    </RegistryKey>
</Component>
```

I hope I was clear enough, I really appreciate your work.

Thanks

**Comment by oleg-shilo** [comment]
Yes it's all clear. Thank you. 
Indeed this is a defect. I'll look into it. 

Until i's fixed please use your work around. 
BTW you can go with a slightly lighter flavour:
```C#
File databaseFile = new File(fileFullPath)
{
    AttributesDefinition = "Component:Permanent=yes; Component:NeverOverwrite=yes"
}
```

**Comment by oleg-shilo** [comment]
You can also use an alternative work around:
```C#
new File(@"Files\Docs\Manual.txt")
     { NeverOverwrite = true }
    .SetComponentPermanent(true)
```
