### ISSUE TITLE
WixStandardBootstrapperApplication ShowVersion

### ISSUE THREAD

**Issue by sanjuleo** [oleg-shilo/wixsharp#201]
Hi
There is ShowVersion property to show product version on the bootstrapper. 
http://wixtoolset.org/documentation/manual/v3/xsd/bal/wixstandardbootstrapperapplication.html

I am not able to find this implementation in WixSharp.

Am I missing something?

Thanks.

**Comment by oleg-shilo** [comment]
WixSharp by default covers only the **mandatory** and the most critical **optional** properties of the WiX objects. Thus it is expected that some of the properties may not be available out of box. In such cases you can easily add these properties on-fly:  
```C#
bootstrapper.Application.AttributesDefinition = "ShowVersion=yes; ShowFilesInUse=yes";
```
Nevertheless I have updated the WixSharp class with the extra properties. Thus in the next release you will be able to set these properties directly:
```C#
bootstrapper.Application.ShowVersion=true;
```

**Comment by sanjuleo** [comment]
Thanks so much. Below did update the wxs - 
bootstrapper.Application.AttributesDefinition = "ShowVersion=yes; ShowFilesInUse=yes";

But unfortunately version is still not visible on the bootstrapper UI. Even if I create a Wix (not sharp) project and try ShowVersion, it doesn't work.

**Comment by oleg-shilo** [comment]
Yeah, WixSharp can only prepare the WiX source for the compilation with Burn but it has no control over the outcome of the Burn compilation.  

I has verified that WixSharp produces the correct output but the rest is up to WiX. This is what I used for the verification:

http://wixtoolset.org/documentation/manual/v3/bundle/wixstdba/
```xml
    <?xml version="1.0"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
            xmlns:bal="http://schemas.microsoft.com/wix/BalExtension">
      <Bundle>
        <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense">
          <bal:WixStandardBootstrapperApplication
            LicenseFile="path\to\license.rtf"
            ShowVersion="yes"
            />
        </BootstrapperApplicationRef>
        <Chain>
        </Chain>
      </Bundle>
    </Wix>
```
May be you can find something on WiX forums.

**Comment by chenho125** [comment]
The issue still exists in 3.11.2.  
WixStandardBootstrapperApplication ShowVersion still not functioning.

**Comment by oleg-shilo** [comment]
Can you please confirm if the emitted WXS contains `ShowVersion="yes"` as it should?

**Comment by chenho125** [comment]
Hi Oleg,
I finally figured out why it was not working.  After read carefully on section: Working with WiX Standard Boostrapper Application (WiX toolset), I found out that the ShowVersion only works with WixStandardBootstrapperApplication.RtfLargeLicense and WixStandardBootstrapperApplication.HyperlinkLargeLicense.  The sample in that section is not a valid sample while it uses: WixStandardBootstrapperApplication.RtfLicense.  This limitation is not mentioned in document for BootstrapperApplicationRef either.  Thanks for the follow up.
Chen

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
WiX toolset

Working with WiX Standard Bootstrapper Application
 |

 |

 |




    On Sunday, January 16, 2022, 07:05:51 AM EST, Oleg Shilo ***@***.***> wrote:  
 
 


Can you please confirm if the emitted WXS contains ShowVersion="yes" as it should?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oleg-shilo** [comment]
Thank you Chen. 

It's a difficult one to handle as I am not sure it is a limitation. It seems to be a bug in WiX. 
You see, [WiX documentation](https://wixtoolset.org/documentation/manual/v3/xsd/bal/wixstandardbootstrapperapplication.html) does not mention any limitations.
![image](https://user-images.githubusercontent.com/16729806/150122889-8910abdd-a909-43f8-aede-7691c00ea9b2.png)

Nevertheless, I would update the sample. Can you please indicate which sample needs the update?

**Comment by chenho125** [comment]
See following from (WiX toolset):


Working with WiX Standard Bootstrapper Application
......
   
   - WixStandardBootstrapperApplication.RtfLicense - the first variant displays the license in the welcome dialog similar to the WixUI Advanced.
   - WixStandardBootstrapperApplication.HyperlinkLicense - the second variant provides an optional hyperlink to the license agreement on the welcome dialog, providing a more modern and streamlined look.
   - WixStandardBootstrapperApplication.HyperlinkSidebarLicense - the third variant is based on HyperlinkLicense but provides a larger dialog and larger image on the initial page.
   - WixStandardBootstrapperApplication.RtfLargeLicense - this variant is similar to RtfLicense but is a larger dialog and supports the option of displaying the version number.
   - WixStandardBootstrapperApplication.HyperlinkLargeLicense - this variant is similar to HyperlinkLicense but is a larger dialog and supports the option of displaying the version number.
See the text in red.
The sample code is following, which does not use either of supported Themes see text in red:


HyperlinkLargeTheme, HyperlinkSidebarTheme, and RtfLargeTheme can optionally display the bundle version on the welcome page:
    <?xml version="1.0"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
            xmlns:bal="http://schemas.microsoft.com/wix/BalExtension">
      <Bundle>
        <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense">
          <bal:WixStandardBootstrapperApplication
            LicenseFile="path\to\license.rtf"
            ShowVersion="yes"
            />
        </BootstrapperApplicationRef>
        <Chain>
        </Chain>
      </Bundle>
    </Wix>    On Wednesday, January 19, 2022, 06:40:54 AM EST, Oleg Shilo ***@***.***> wrote:  
 
 


Thank you Chen.

It's a difficult one to handle as I am not sure it is a limitation. It seems to be a bug in WiX.
You see, WiX documentation does not mention any limitations.


Nevertheless, I would update the sample. Can you please indicate which sample needs the update?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oleg-shilo** [comment]
Not sure I follow. What you provided is not content from this project. 
Is there a chance that you are referring to the WiX samples hosted by WiX project (not WixSharp project)?
