### ISSUE TITLE
multiple languages

### ISSUE THREAD

**Issue by wayne-lu** [oleg-shilo/wixsharp#202]
wixsharp support a msi file integration in multiple languages ? and automatically according to the system language display.

**Comment by oleg-shilo** [comment]
Well, MSI attitude towards localisation is to build an individual package per language. So nothing you can do about that.

Though if you are using WixSharp managed UI you have a bit more opportunities. Managed I is just an ordinary managed application at runtime thus it supports all localization techniques of .NE as any other managed application. But of course it requires more effort to support multiple languages.
