### ISSUE TITLE
UrlReservation

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#207]
Can you add support for the [UrlReservation](http://wixtoolset.org/documentation/manual/v3/xsd/http/urlreservation.html) element?
```
<Component Id="UrlReservation" Guid="*" KeyPath="yes" Win64="yes">
   <http:UrlReservation Url="http://+:9999/***/device_service/">
      <http:UrlAce SecurityPrincipal="*S-1-1-0" Rights="register" />
   </http:UrlReservation>
</Component>
```

**Comment by oleg-shilo** [comment]
Sorry, I don't have immediate plans for extending API to this direction. Though you can extend it by yourself.  It is in fact very simple. Have a look at "[EventSource](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp/EventSource.cs)" element support. It is an excellent example of extending WixSharp with the support for new WiX elements.

When you are done and if you feel that others can benefit from your work you can share it (in any convenient way) and I will add it to the codebase.

This wiki article can also be useful: https://github.com/oleg-shilo/wixsharp/wiki/Code-Contributions-Guideline

**Comment by Xaddan** [comment]
Hi Oleg.
I have implemented this functionality, you can see here:
https://github.com/Xaddan/wixsharp/commit/083cb5bbe2eb976e2d71f8f361b5bdcfc027a473

**Comment by oleg-shilo** [comment]
Excellent. Can you please create a pull request so I can evaluate it.
Thank you.
