### ISSUE TITLE
Unable to sign msi file

### ISSUE THREAD

**Issue by Sollex-21412** [oleg-shilo/wixsharp#208]
It is not possible to sign msi file with certificate from Windows Certificate Store.

```csharp
            var project = new ManagedProject("MyProduct",
                             new Dir(@"%ProgramFiles%\My Company\My Product",
                                 new File("Program.cs")))
            {
                DigitalSignature = new DigitalSignature
                {
                    UseCertificateStore = true,
                    TimeUrl = new Uri("http://timestamp.verisign.com/scripts/timstamp.dll"),
                    PfxFilePath = "Cert_Name", // Certificate name from Cert Store
                    OptionalArguments = "/fd SHA256",
                    WellKnownLocations = @"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin"
                }
            };
```

Stack trace:
```
1>   Auto-generated InstallDir ID:
1>     INSTALLDIR=%ProgramFiles%\My Company\My Product
1>  
1>  Unhandled Exception: System.ArgumentNullException: Value cannot be null.
1>  Parameter name: s
1>     at System.Runtime.InteropServices.Marshal.SecureStringToBSTR(SecureString s)
1>     at WixSharp.XmlMapping.ToInsecureString(SecureString input)
1>     at WixSharp.DigitalSignature.Apply(String fileToSign)
1>     at WixSharp.Compiler.Build(Project project, String path, OutputType type)
1>     at WixSharp.Compiler.Build(Project project, OutputType type)
```

In case when Password is not null, I got:
```
EXEC : SignTool error : The /p option requires the /f option.
```

**Comment by oleg-shilo** [comment]
The problem with empty password is fixed (`Value cannot be null`). The fix will be available in the very next release i a day or two.

Though keep in mind that problems with signing itself is outside of the WixSharp scope. When you build the MSI check what signing command is produced.

This is what the output is in my environment for your sample:

```txt
 Auto-generated InstallDir ID:
   INSTALLDIR=%ProgramFiles%\My Company\My Product
Execute:
"signtool.exe" sign /v /n "Cert_Name" /t "http://timestamp.verisign.com/scripts/timstamp.dll" /fd SHA256 "...\WixSharp\Source\src\WixSharp.Samples\Wix# Samples\Signing\MyProduct.msi"
SignTool Error: No certificates were found that met all the given criteria.
```

If the  "signtool.exe" command is incorrect then let me know and I will have a look. But otherwise I am afraid it is a "signtool.exe" issue.

**Comment by Sollex-21412** [comment]
I tried to sign via cmd. Everything works as expected. The problem was only in the null password attribute.

Thanks!

P.S.
I've used "Cert_Name" as sample. Actually there is another certificate name =).

**Comment by oleg-shilo** [comment]
OK. Great. Then the issue is sorted out. 
The patch will be ready early next week.

**Comment by Sollex-21412** [comment]
Verified with 1.5.0.0.
Thanks.

**Comment by AmosOtis** [comment]
Are there examples showing how to sign the MSI using the DigitalSignature construct?  I've got it working but I have to put the password in my c# code.  I'd prefer to reference a trusted root certificate installed on my computer and force all other developers of my project to install a certificate with the same name.  But maybe that isn't how this is supposed to work.  Basically, why I think some examples would be helpful showing various use cases.
