### ISSUE TITLE
Add InstallPrivileges property to project

### ISSUE THREAD

**Issue by Sollex-21412** [oleg-shilo/wixsharp#214]
Please add possibility to set "InstallPrivileges" to "limited" as it done for "InstallScope"

For now, I have to use a workaround:
```csharp
project.WixSourceGenerated += document =>
{
    document.Root.Select("Product/Package").SetAttributeValue("InstallPrivileges", "limited");
};
```
But I think, it would be great to have such feature.

**Comment by oleg-shilo** [comment]
Makes sense. 
Done. 
Will be available in the next release.

**Comment by Sollex-21412** [comment]
Verified with 1.5.0.0.
It works! 
Thanks.
