### ISSUE TITLE
.NET 2 support

### ISSUE THREAD

**Issue by fredericoregateiro** [oleg-shilo/wixsharp#215]
Hello,
I need to create a installer to use with .net 2 app, 
so is there any wixsharp version that support this framework?

Thanks

**Comment by oleg-shilo** [comment]
> create a installer to use with .net 2 app,

Can you please elaborate?

WixSharp is just a builder (like compiler). It's version is irrelevant except just a few cases. 
- If your setup is a native MSI then you are just fine. 
- If you are using managed CustomAction then just make sure their assembly is .NET2 compatible that's 
it. 
- If you are using ManagedSetup you will need to test the result  of compilation. It may or may not work on .NET2.

I have only tested the setups for .NET3.5, which has, as yopu may know, the same CLR version as .NET2.

**Comment by fredericoregateiro** [comment]
I've just add a reference, from the nuget, and when i build the solution i get these warnings:

![wixsharp](https://user-images.githubusercontent.com/6304701/33495523-a72ec112-d6be-11e7-85bc-8a9eb6f2095a.png)

These are the references missing from the .net 2:
- System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
- System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

For me a normal native MSI will do just fine.

**Comment by oleg-shilo** [comment]
Then you can just use .NET 3.5+ VS project and you 'll be fine.

**Comment by fredericoregateiro** [comment]
I have to use the .NET 2.
Is there any old version that i can use?

**Comment by oleg-shilo** [comment]
> I have to use the .NET 2.

I argue you don't. 

Judging from your screenshot you are using VS2017 (or at least VS2015). You can have a WixShrp project targeting even .NET4 and this will not affect anything. This project, when building is triggered, produces the .NET4 assembly (exe), which is nothing else but an MSI builder. At the end of the build VS runs that exe and the MSI is produced. After that that .NET4 exe is discarded. 

Thus I just do not see how you "have to use .NET 2".

**Comment by fredericoregateiro** [comment]
The msi is to install a application on old machines (Windows XP), and these app target .net 2.

I will try do change the .net target on the msi project and test the installer on a cliente.

Thanks,

**Comment by oleg-shilo** [comment]
> ...and these app target .net 2.

Yes, I understand that but this has nothing to doe with the version of the runtime that your MSI building tool (WixSharp) is using. 

It could have implications if your MSI includes WixSharp .net4 assemblies. And they are to be executed on target system during  deployment. However you have indicated that it is not the case as your msi is a pure native MSI. 

Your situation is no different to the building a .net2 executable with VS2017, which is itself a .net4 IDE.
