### ISSUE TITLE
Failed to load assembly Microsoft.Deployment.WindowsInstaller

### ISSUE THREAD

**Issue by Fujiwaranosai** [oleg-shilo/wixsharp#217]
Hi,

I use `ManagedUI`. If I run the msi without administrator, it opens and quits quickly. The install log contains this line:

`SFXCA: Failed to load assembly Microsoft.Deployment.WindowsInstaller. Error code 0x80070005`

If I run with administrator, it works fine.

I also checked if it was caused by `ManagedUI` or not by not using `project.managedUI = new ManagedUI()` (commenting it out) but still use `ManagedProject` (`var project = new ManagedProject`). So I'm sure including `ManagedUI` caused this problem.

Is it intended that the msi only works for elevated user or did I forget something to make it work?

One more important thing is: it doesn't only require elevated user but a system admin. Even if I enable UAC and accept the prompt, it doesn't run. It only works if I run with administrator. And that also caused a problem when uninstalling the app (from Settings/Apps of Windows 10): uninstalling doesn't work. I have to run the msi again with administrator (and uninstall option) to uninstall it.

Thanks for help.

**Comment by oleg-shilo** [comment]
To be honest I have never sen this error even though during my tests I always run unelevated. I suggest you try to build and run one of the ManagedUI samples.

You may also check if `Microsoft.Deployment.WindowsInstaller` can be loaded on the target system. May be it's just a CLR incompatibility.

**Comment by Fujiwaranosai** [comment]
Hi Oleg,

I think you're right. Last week I updated windows to the latest fall creator version and the issue went away. Probably the previous windows has some problem with it.

**Comment by oleg-shilo** [comment]
I am really happy to hear that :)
The problem sounded unresolvable, to be honest :)
