### ISSUE TITLE
Common Question to MSI

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#219]
Hi Oleg,
how can i change name of output msi ? Msiname is equal namespace. I tried to set name in project.BuidlMsi() with parameter, but nothing happend. Could you please help me here ? 
Thanks for answer.

**Comment by Xaddan** [comment]
`project.OutFileName = "setup";`

**Comment by Torchok19081986** [comment]
Thats work fine! Thanks a lot.
