### ISSUE TITLE
WixSharp hint appreciated. Service deletion exception on service installation.

### ISSUE THREAD

**Issue by silentnightwalk** [oleg-shilo/wixsharp#220]
Thanks a lot in advance!

Any hint would be very helpful!

I'm getting exception releted to service deletion, even though, installation phase. 
System.ComponentModel.Win32Exception:
The specified service has been marked for deletion

or the same in Russian: Указанная служба была отмечена для удаления

Some aspects to mention (chronologically): 
- A couple of days ago our product was installed to "Program Files (x86)" successfully
- After that it was uninstalled successfully
- After that the same msi was launched again. Desktop installation dir whas chosen: C:\Users\Katerina\Desktop\работа\MasterSCAFARTBETA
- exception was thrown at insallation phase. To be more exact, on custom action, which is being fired after files coppied to install dir.
- The istallation attempt was repeated with "Program Files (x86)" folder specified. Exception reoccured. 

I'm not sure if it's possible to attach a part of the log. May be i'll post it as well.

Thanks!

**Comment by silentnightwalk** [comment]
Just in case, here is a part of the log. 
Sorry. 
It was first strange symbols then put through http://www.online-decoder.com/ru (before decoder we had jokes like ўЄЁ at the end means усё).
After decoder it is still strange symbols. 
But if you know Russian then small effort may shed some light on the situation. 
Sorry for posting what is not clear for most of the readers. Also, sorry for asking you to make efforts.

------------------------------------------------

ActionData: 1: zlib.js 2: 3: 4: 5: 6: 467 7: 8: 9: C:\Users\Katerina\Desktop\ЁрсюЄр\MasterSCAFARTBETA\nodejs\node_modules\tiny-inflate\

ActionData: 1: zstream.js 2: 3: 4: 5: 6: 851 7: 8: 9: C:\Users\Katerina\Desktop\ЁрсюЄр\MasterSCAFARTBETA\nodejs\node_modules\pako\lib\zlib\

ActionStart: ─хщёЄтшх 14:27:34: Action8_OnInstall.

Info: SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSI9FA.tmp-\

Info: SFXCA: Binding to CLR version v4.0.30319

Info: Calling custom action WixSetupLibrary!WixSetupLibrary.WixSetupRT.BuildExeSetupRT+CustomActions.OnInstall

Info: System.Exception: Microsoft (R) .NET Framework Installation utility, версия 4.7.2046.0

c Корпор ция М йкрософт (Microsoft Corporation). Все пр в з щищены.

Выполняется группов я опер ция уст новки.

Н чин ется эт п уст новки процедуры уст новки.

См. ф йл журн л выполнения опер ция для сборки C:\Users\Katerina\Desktop\р бот \MasterSCAFARTBETA\MS4DService.WinService.exe.

Д нный ф йл н ходится в C:\Users\Katerina\Desktop\р бот \MasterSCAFARTBETA\MS4DService.WinService.InstallLog.

Выполняется уст новк сборки 'C:\Users\Katerina\Desktop\р бот \MasterSCAFARTBETA\MS4DService.WinService.exe'.

З тронуты следующие п р метры:

logtoconsole =

logfile = C:\Users\Katerina\Desktop\р бот \MasterSCAFARTBETA\MS4DService.WinService.InstallLog

assemblypath = C:\Users\Katerina\Desktop\р бот \MasterSCAFARTBETA\MS4DService.WinService.exe

Уст н влив ется служб MS4DService_Beta...

Созд ется исходный EventLog MS4DService_Beta в журн ле Application...

Н эт пе уст новки возникло исключение.

System.ComponentModel.Win32Exception: Ук з нн я служб был отмечен для уд ления

Н чин ется эт п отк т процедуры уст новки. 

------------------------------------------------------

**Comment by Xaddan** [comment]
Можешь описать как у тебя происходит установка и удаление службы?
Подозреваю что через sc.exe, не рекомендую использовать его для этих целей, при его использование винда не всегда удал службу, а только помечает на удаление, лучше всего использовать виксовый [ServiceInstall](http://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceinstall.html), с ним никогда нету проблем.

 workaround: перезагрузи комп, служба удалится и ты сможешь произвести установку.
__________
Лучше используй этот декодер https://www.artlebedev.ru/decoder/ он лучше декодирует (не реклама :))

**Comment by silentnightwalk** [comment]
Установка и удаление происходят так:
Install and uninstall are implemented like following:

```
                , new ElevatedManagedAction(CustomActions.OnInstall, Return.check, When.After, Step.InstallFiles, Condition.NOT_Installed)   
                , new ElevatedManagedAction(CustomActions.OnUninstall, Return.check, When.Before, Step.RemoveFiles, Condition.BeingRemoved) 
```

```
        public class CustomActions
        {
            [CustomAction]
            public static ActionResult OnInstall(Session session)
            {
                return session.HandleErrors(() =>
                {
                    //.........

                    Tasks.InstallService(session.Property("INSTALLDIR") + "MS4DService.WinService.exe", true);
                    Tasks.StartService(serviceName, false);

                    //run monitor 
                    System.Diagnostics.Process.Start(session.Property("INSTALLDIR") + "MS4DMonitor.exe");
                });
            }

            [CustomAction]
            public static ActionResult OnUninstall(Session session)
            {
                return session.HandleErrors(() =>
                {
                    //..........

                    //uninstall MS4DService
                    Tasks.InstallService(session.Property("INSTALLDIR") + "MS4DService.WinService.exe", false);

                    //close monitor
                    //............
                });
            }
        }
```

**Comment by silentnightwalk** [comment]
@Xaddan , спасибо
попробую 
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/WinService/With_WiX/setup.cs
буду рад если будут другие подсказки.

Thanks, i'll try this link. Happy to receive other hints.

**Comment by Xaddan** [comment]
Да, попутал `sc.exe` не умеет устанавливает службы, только удалять, `InstallUtil.exe` устанавливает их, `Tasks.InstallService` как раз и реализует установку через `InstallUtil.exe`. Переделывай на `ServiceInstall` и будут все работать )
