### ISSUE TITLE
Sql script execution during install

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#221]
Hall Oleg,
i have some problems with install / execute embeded .sql during installation of my product. Hope that you can help me. 
In Examples SqlDatabases in setup.cs there is line 
new SqlDatabase("MyDatabase0", ".\\SqlExpress", SqlDbOption.CreateOnInstall));
 //new SqlString("alter login Bryce with password = 'Password1'", ExecuteSql.OnInstall)))
If i unterstand correcty, will MyDatabase0 install on local instance with SqlExpress during install, but i dont see any creadentials for Sql Server .  
I use ManagedProject with custom Dialogs where i can search sql server instance and set values for user and password. 
I tried to set Property directry in Custom Action (ManagedAction), but failed. It looks like session["SQLUSER"] and session["SQLPASSWORD"] etc.  I got Info from https://www.firegiant.com/wix/tutorial/sql/creating-a-database/ .  
Do you have Example how i can set credentials for SQL Server, User and password ?

**Comment by Xaddan** [comment]
For SqlString, you must specify a User:
```
new User(new Id("SqlUser"), "[SQLUSER]") { Password = "[SQLPASSWORD]"},
new SqlDatabase("MyDatabase0", ".\\SqlExpress", SqlDbOption.CreateOnInstall),
    new SqlString("alter login Bryce with password = 'Password1'", ExecuteSql.OnInstall))
	{
		User = "SqlUser"
	});
```

**Comment by Torchok19081986** [comment]
Thanks for answer. Only I dont know where i can set properties for current session. In tried in custom action, but nothing happend. I need some sample how i can set choosed value for Server, user, password and execute it during install after my dialog set.

**Comment by Xaddan** [comment]
Look at this [project](https://www.codeproject.com/Articles/331368/WIXDataBase).

**Comment by oleg-shilo** [comment]
You can set property from custom action or `Project` event handler:
```C#
session["prop_name"] = "prop_value";
```
'CustomUIDialog' sample shows how to collect user name and password and pass it to other custom actions.

**Comment by Torchok19081986** [comment]
Thanks. Do i understand correctly, that i need create properties with new Property () and set value for mypropertyname with session["mypropertyname"] = "value" in Customaction where value is userchoosed sqlserver, sqluser and sqlpassword ?

**Comment by oleg-shilo** [comment]
Having a property created with `new Property()` isn't mandatory for some scenarios and for others is. Though it is good idea to have it. This way you can have a simple control over the default value for this property. 

Another good practice is to have the property name in all upper case. This way MSI recognizes it as a _public_ property and lets you set it from the command line (for starting msi file).

Setting the property value can be done either from any custom action (including project event handlers) or from the UI dialog:
```C#
void next_Click(object sender, EventArgs e)
{
    MsiRuntime.Session["PASSWORD"] = password.Text;
    MsiRuntime.Session["DOMAIN"] = domain.Text;
    MsiRuntime.Data["test"] = "test value";
    Shell.GoNext();
}
```
You should really have a look at the sample I recommended: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUIDialog

It has everything you need, explicit and implicit properties, properties defaults, setting property value from a custom action and a dialog, accessing property from deferred and non deferred action, use of install events. 

The sample had come traces of test code but I just cleaned it for you.

**Comment by Torchok19081986** [comment]
Thanks for quick answer Oleg. That it. My mistake was set values not from MsiRuntime.Session[""]. Thanks for example. I give it try. Only one question: can i run embeded .sql script after set credentials for sql server, user and password or i need to extract file then read this file and run it in sql connection ?

**Comment by oleg-shilo** [comment]
It depends. 
WixSharp does not have any dedicated functionality for SQL execution thus, unless WiX has something you will need to have a custom action where you execute your SQL. 

I don't particularly like this approach. Most likely is is a config task that you are trying to do and deployment is not the best place for this. Though I can be wrong about the nature of your sql.

You can extract the sql from the assembly resources or for the MSI:
```C#
project.AddBinary(new Binary(new Id("sql_file"), "your file path"));
...
var sql = session.GetEmbeddedString("sql_file");
```    
Then... you know what to do.

**Comment by Torchok19081986** [comment]
Then i can try it. i have now some clear ideas how. Thanks. This was very helpfull.
