### ISSUE TITLE
ServiceInstaller should not be bound to a file.

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#225]
I need to configure the Windows service:
```xml
<Component Id="W32Time" Guid="***" KeyPath="yes" Win64="$(var.Win64)">
   <ServiceInstall Id="ServiceDisabled" Name="W32Time" Start="disabled" Type="ownProcess" ErrorControl="ignore"/>
   <ServiceControl Id="ServiceControl" Name="W32Time" Stop="both"/>
</Component>
```
When I added the ServiceInstaller to the project:
```C#
public static readonly Project Project = new Project ("",
    new ServiceInstaller("W32Time"){ StartType = SvcStartType.disabled, StopOn = SvcEvent.InstallUninstall, ErrorControl = SvcErrorControl.ignore });
```
I received an exception:
```
System.TypeInitializationException: Инициализатор типа "WSInstaller.Package.Common" выдал исключение. ---> System.Exception: Unexpected object type is among Project constructor arguments: ServiceInstaller
```

**Comment by oleg-shilo** [comment]
> ServiceInstaller should not be bound to a file

Actually it should. WiX requires the `ServiceInstall` (and its `Component`)  to be bound to the directory either directly or through the file. It is one of the many anti-patterns MSI/WiX exhibits. 

Even the name of the element `ServiceInstall` has very strict semantics - "you are installing the service". And service can only be installed with the service file.

What you are trying to do is not to install but to to **configure** a third party service. And this type of action does not belong to the deployment but to the application domain. 

_According to "Windows Certified Application" requirements (since Vista) all configuration tasks must be performed by the application at startup but not during deployment. It just makes sense. And the fact that MSI lets you do the config tasks does not man you should. Yes, MS is contradicting itself in this case._

Anyway it is entirely up to you to follow (or not) certain deployment strategies so by no means I am dictating you what to do. However I don't want WixSharp to promote controversial deployment practices and that's why `ServiceInstaller` will have to stay as it is.

Now, how to address your problem? 

If you still want to configure a third party service with `ServiceInstall` you can easily do it by subclassing the `ServiceInstaller` class:
```C#
class ServiceUpdater : ServiceInstaller, IGenericEntity
{
    public void Process(ProcessingContext context)
    {
        var component = context.XParent.AddElement("Component", 
                                                 $@"Id={this.Id};
                                                    Guid={WixGuid.NewGuid(this.Id)}");
        var elements = this.ToXml(context.Project).Cast<XElement>();
        elements.ForEach(component.Add);
    }
}
```
The class above uses `ServiceInstaller` o produce the required XML, injects it into the parent entity and by being `IGenericEntity` lets user to pass itself into any constructor:
```C#
var project =
    new Project("My Product",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new ServiceUpdater
            {
                Name = "W32Time",
                StartType = SvcStartType.disabled,
                StopOn = SvcEvent.InstallUninstall,
                ErrorControl = SvcErrorControl.ignore
            }));
```
There is only one problem with the code above: `ServiceInstaller.ToXml` is not public. I am going to change it to public but right now you will need to use reflection as a temporary work around:
```C#
public static T Call<T>(this object obj, string name, params object[] args)
{
    var method = this.GetType().GetMethod(name, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.InvokeMethod);
    return (T)method.Invoke(this, args);
}
...
var elements = this.Call<object[]>("ToXml", context.Project).Cast<XElement>();
```

And as a compromise I will consider including `ServiceUpdater` into WixSharp API.

**Comment by oleg-shilo** [comment]
Though there is one thing that I am not entirely sure the produced XML in the solution is the best WiX way to update the service.

**Comment by Xaddan** [comment]
Thanks for the quick work.
I need to completely disable the Windows time service.
My piece of code on Wix works as it should, the service stops and its type of start is disabled.
```
<Component Id="W32Time" Guid="{E3DD263D-0685-4045-A074-**}" KeyPath="yes" Win64="$(var.Win64)">
   <ServiceInstall Id="ServiceDisabled" Name="W32Time" Start="disabled" Type="ownProcess" ErrorControl="ignore"/>
   <ServiceControl Id="ServiceControl" Name="W32Time" Stop="both"/>
</Component>
```
When using such a  `ServiceUpdater`:
```
new ServiceUpdater
{
   Name = "W32Time",
   StartType = SvcStartType.disabled,
   StartOn = null,
   StopOn = SvcEvent.InstallUninstall_Wait,
   RemoveOn = null,
   ErrorControl = SvcErrorControl.ignore,
}
```
This piece of code is generated:
```
<Component Id="W32Time" Guid="7ac06edf-d365-40c0-ae50-**" Win64="yes" KeyPath="yes">
   <ServiceInstall Id="W32Time" Name="W32Time" DisplayName="W32Time" Description="W32Time" Type="ownProcess" Start="disabled" ErrorControl="ignore" />

   <ServiceControl Id="StopW32Time" Name="W32Time" Stop="both" Wait="yes" />
   <RemoveFolder Id="INSTALL_LOCATION" On="uninstall" />
</Component>
```
But it does not work as expected, the service stops but its startup type remains Auto.

I thought this might be affected by DisplayName and Description. I removed them but nothing has changed.

**Comment by oleg-shilo** [comment]
Well, it only confirms my feeling that this is not a good approach and probably you are better off either with a fresh IGenericEntity implementation or even with a simple XML injection.

But for the sake of experiment you can do this:
```C#
class ServiceUpdater : ServiceInstaller, IGenericEntity
{
    public void Process(ProcessingContext context)
    {
        var component = this.CreateParentComponent();
        this.ToXml(context.Project)
                            .Cast<XElement>()
                            .Where(x => x.Name == "ServiceInstall" || x.HasAttribute("Stop"))
                            .ForEach(component.Add);

        context.XParent.AddElement(component);
    }
}
...
var project =
    new Project("My Product",
        new Dir(@"%ProgramFiles%\My Company\My Product",
        new ServiceUpdater
        {
            Name = "W32Time",
            StartType = SvcStartType.disabled,
            Type = SvcType.ownProcess,
            StopOn = SvcEvent.InstallUninstall_Wait,
            ErrorControl = SvcErrorControl.ignore
        },
        service = new File(@"..\SimpleService\MyApp.exe")));
```

It produces the required XML:
```xml
<Component Id="W32Time" Guid="6fe30b47-2577-43ad-9195-186107d87cf0" KeyPath="yes">
  <ServiceInstall Id="W32Time" Name="W32Time" DisplayName="W32Time" Description="W32Time" Type="ownProcess" Start="disabled" ErrorControl="ignore" />

  <ServiceControl Id="StopW32Time" Name="W32Time" Stop="both" Wait="yes" />
  <RemoveFolder Id="INSTALLDIR" On="uninstall" />
</Component>
```

**Comment by Xaddan** [comment]
At me it turns out here such code:
```
<Component Id="W32Time" Guid="7ac06edf-d365-40c0-ae50-31da1291691e" Win64="yes" KeyPath="yes">
   <ServiceInstall Id="W32Time" Name="W32Time" Type="ownProcess" Start="disabled" ErrorControl="ignore" />

   <ServiceControl Id="StopW32Time" Name="W32Time" Stop="both" />
</Component>
```
But it still does not work, the type of service startup is still Auto. I do not understand why this happens. I looked at 2 installers through Orca, they have the same tuned ServiceInstall and ServiceControl, but one works as nada, and the second one does not work.

**Comment by Xaddan** [comment]
Not yet exhibited Feature, the component is placed in the Complete Feature, not the one I indicated.

**Comment by Xaddan** [comment]
I created a small installer on WIX and moved my component there. He stopped working. What's going on, I need to think. ))

**Comment by oleg-shilo** [comment]
Good luck :)

**Comment by Xaddan** [comment]
This is mysticism :) I tried everything, but it does not work. I'll have to change the startup type via sc.exe. But I think it would be useful to have a certain function to stop and start services.
Something like:
```
new ServiceStart ("ServiceName", SvcEvent);
new ServiceStop ("ServiceName", SvcEvent);
```

Thank you for your time.

**Comment by oleg-shilo** [comment]
You already have it. Not exactly the same but similar:
```C#
public class CustomActions
{
    [CustomAction]
    public static ActionResult InstallAction(Session session)
    {
        return session.HandleErrors(() =>
        {
            Tasks.StartService("WixSharp.SimpleService", throwOnError:false);
        });
    }
```

**Comment by oleg-shilo** [comment]
Or even better:
```C#
project.BeforeInstall += session =>
{
    if (!session.IsUninstalling)
        Tasks.StopService("some_service", throwOnError: false);
};

project.AfterInstall += session =>
{
    if (!session.IsUninstalling)
        Tasks.StartService("some_service", throwOnError:false);
};
```

**Comment by Xaddan** [comment]
`project.BeforeInstall` and `project.AfterInstall` will work, if run the installer without UI?

**Comment by oleg-shilo** [comment]
Yes it will, the events are of the "ManagedProject" class not "ManagedUI".
 Note that `AfterInstall` ensures that you are elevated.

**Comment by Xaddan** [comment]
And how can I make a binding to the Feature? )

**Comment by oleg-shilo** [comment]
You can access the selected features in the session object:
```C#
string[] names = session.Features.Select(x => x.Name).ToArray();
```

Have a look at `FeaturesDialog.cs` it uses the same technique.

Though keep in mind that MSI kills the session in all deferred actions (e.g. project.AfterInstall). If it is your case then you need to tunnel your feature at startup:
``` C#
project.BeforeInstall += session =>
{
    if (session.Features.Any(x => x.Name == "my_feature")
         e.Data["update_service"] = "yes"; // now this value is available for deferred actions

    if (!session.IsUninstalling && e.Data["update_service"] == "yes")
        Tasks.StopService("some_service", throwOnError: false);
};

project.AfterInstall += session =>
{
    if (!session.IsUninstalling && e.Data["update_service"] == "yes")
        Tasks.StartService("some_service", throwOnError:false);
};
```

**Comment by Xaddan** [comment]
As it is difficult. Better I in the old manner. ))
```
new WixQuietExecAction("sc.exe", "start some_service")
{
   Id = "Start_some_service",
   Step = Step.StartServices,
   When = When.Before,
   Return = Return.check,
   Execute = Execute.deferred,
   Impersonate = false,
   Condition = Feature.Install(),
};
```

**Comment by oleg-shilo** [comment]
Yep, not bad after all.

----

Can you please load the feature  request to add feature "Session.IsFeatureSelected(string name)"?
