### ISSUE TITLE
Project.HashedTargetPathIdAlgorithm generates invalid ids

### ISSUE THREAD

**Issue by staylr** [oleg-shilo/wixsharp#226]
With WiX# 1.5.0, using Project.HashedTargetPathIdAlgorithm results in invalid ids for file names containing spaces, special characters or starting with digits. I've had to do something like below. Otherwise the new feature seems to work well, solves a problem I was having. Thanks!

```
        private static string MangleGeneratedId(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return null;
            }

            id = id.Replace('@', '_').Replace(' ', '_').Replace('-', '_');
            if (Char.IsDigit(id[0]))
            {
                id = "_" + id;
            }

            return id;
        }
```

**Comment by oleg-shilo** [comment]
Thank you. 
The defect is corrected. 
The fix will be available in the next release. 

If you don't want to wait you can grab the binaries from [AppVeyer](https://ci.appveyor.com/project/oleg-shilo/wixsharp/build/1.5.0.19/artifacts).

Or adjust the custom algorithm:
```C#
project.CustomIdAlgorithm = 
    entity => project.HashedTargetPathIdAlgorithm(entity).Expand();
```

You can also simplify your work around:
```C#
private static string MangleGeneratedId(string id) => id.Expand();
```
