### ISSUE TITLE
IIS permission to run installer service

### ISSUE THREAD

**Issue by sanjuleo** [oleg-shilo/wixsharp#228]
Hi
My web application needs to create dynamic installers which I am doing with wixSharp. My wixsharp installer creation project works well when used from a windows form but when used from the ASP.net MVC project, it throws -
"light.exe : error LGHT0217 : Error executing ICE action 'ICE07'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0216 : An unexpected Win32 exception with error code 0x643 occurred: Action - 'ICE09' Fatal error during installation
Exception thrown: 'System.Exception' in WixSharp.dll"

Looks like the process being run through IIS does not have access to "Windows Installer Service". Have you encountered such error?

Please advise.

**Comment by oleg-shilo** [comment]
It looks like Windows restricts access to the "Windows Installer Service" for non desktop applications.
I guess the only option you have is to run your "MSI building services" (based on WixSharp) on your desktop and talk to them via some simple communication channel (NamedPipes, socket).

**Comment by sanjuleo** [comment]
Thanks for the prompt response.

It was a different issue rather. After more googling, following solution worked -
project.LightOptions = "-sval";
