### ISSUE TITLE
Add the ability to determine whether the feature was selected for installation.

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#229]
Hey.
Can you add a new function that would determine whether the feature was selected for installation?
Something like:
`Session.IsFeatureSelected (string name)`

**Comment by oleg-shilo** [comment]
Sorry for asking to open this issue. My bad. It's already implemented:

![image](https://user-images.githubusercontent.com/16729806/33746845-c3f8520e-dc13-11e7-87eb-426011659981.png)
