### ISSUE TITLE
Many instance from one msi

### ISSUE THREAD

**Issue by Halkidik** [oleg-shilo/wixsharp#231]
Hello, can you describe me how to install new instance of application by each run of msi?

**Comment by Halkidik** [comment]
i know that we can select productid like "*" in xml, but how can i do it using wixsharp @oleg-shilo

**Comment by Halkidik** [comment]
as i understood we should prepare something like this in wxs:
![image](https://user-images.githubusercontent.com/20342105/33942908-1a447952-e020-11e7-9c0e-43602ed53f9a.png)

**Comment by oleg-shilo** [comment]
There is a sample project that can be useful for you: "MultipleInstances Install".
Have a look. May be it is even exactly what you are looking for. Though your original description of the problem "_...install new instance of application by each run of msi?_" completely puzzled me. I doubt that exactly that is even possible.

**Comment by Halkidik** [comment]
As I understood when we install the app like msiexec / i "My Product.msi" MSINEWINSTANCE = 1 TRANSFORMS = ": SecondInstance" we can't install many instances of one app just install one of the instances or i do something wrong? because in my case when i'm trying to install instance, installer just reinstall previous instance

**Comment by oleg-shilo** [comment]
Sorry. Cannot help you. This question it truly outside of WixSharp scope. You will need to looks for the answer in the MSI/WiX domain. But if you find the answer and have difficulties applying it to WixSharp solution then this thread can be more helpful for you.

**Comment by Halkidik** [comment]
@oleg-shilo thank you, i decided to use .exe file what run msi with instance transform
