### ISSUE TITLE
Feature Installation

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#232]
Hi Oleg, 
i have  question.
 Is there something possibility to check if user has rights to install feature like windows firewall exception  or current user have rights to install feature ? 
In Sample i found function IsAdmin(), but this checks only if current user is Administrator.  How do i check if user have some administrator rights ?
if user have rights to install feature set to enabled  and if not disable.

**Comment by oleg-shilo** [comment]
This is an OS API task  and neither MSI, WiX nor WixSharp can answer your need directly.

I don't know the answer. You will need to find how to solve this problem outside of setup and then bring it into your msi as a Custom Action, Install Event or GUI C# routine.
