### ISSUE TITLE
wixsharp DLL not compiled for 4.0v

### ISSUE THREAD

**Issue by ECJana** [oleg-shilo/wixsharp#24]
Just wanted know if the WixSharp , Wixsharp.ui and Wixsharp.msi DLLs would be moving to the 4.X framework?

I wanted to use a few other libs for my msi and cannot due to the version of these dlls being v2.0.

**Comment by oleg-shilo** [comment]
There is a good reason to keep Wix# assemblies compiled for lowest possible runtime version. This way you can host them on any CLR version.

Yep, you don't need Wix# assemblies being compiled for .NET 4 to be hosted by .NET 4 target platform. You can use them them as they are. Just target your VS project to v4 and you are done. 

I have attached the solution that builds the msi, which invokes .NET 4 assembly at runtime.
[WixSharp Setup1.zip](https://github.com/oleg-shilo/wixsharp/files/793096/WixSharp.Setup1.zip)
