### ISSUE TITLE
Dependent assembly not supplied

### ISSUE THREAD

**Issue by inventgroep** [oleg-shilo/wixsharp#241]
Dear Oleg,

I'm trying to build some of the sample projects, but get this error using the CustomCLRDialog sample project:

1>EXEC : error : Dependent assembly not supplied: **WixSharp.UI**, Version=1.5.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2
1>EXEC : error : System.IO.FileLoadException: Cannot resolve dependency to assembly 'WixSharp.UI, Version=1.5.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

While trying to build CustomMSIDialog, I receive these errors:

1>EXEC : error : Dependent assembly not supplied: **WixSharp.Lab**, Version=1.0.39.1, Culture=neutral, PublicKeyToken=3775edd25acc43c2
1>EXEC : error : System.IO.FileLoadException: Cannot resolve dependency to assembly 'WixSharp.Lab, Version=1.0.39.1, Culture=neutral, PublicKeyToken=3775edd25acc43c2' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

I'm using Windows 10 Ent. & VS2017 version 15.4.5.

Can you help me a little with this?

Regards,

Wietse
The Netherlands

**Comment by oleg-shilo** [comment]
Sorry missed this one completely.
You will need the "WixSharp.Lab" NuGet package

**Comment by sylvesp** [comment]
Hi Oleg,

I am also getting this "Dependent Assembly not supplied" Error :(

1>  Building MSI
1>  Searching for custom action entry points in WixSharp Setup.exe
1>EXEC : error : Dependent assembly not supplied: WixSharp.UI, Version=1.14.2.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2

I did reference the WixSharp AND WixSharp.Lab Nuget packages.
Any idea what may I be doing wrong?

Thanx,
Peter

**Comment by oleg-shilo** [comment]
Is it possible that even when you brought the right packages in the project the assemblies are not referenced by your CA?

If it is the case then it can be easily fixed by nominating them explicitly:

```C#
project.DefaultRefAssemblies.Add(typeof(UIShell).Assembly.Location); // WixSharp.UI assembly
```
