### ISSUE TITLE
Q: ManagedUI, events and Rollback?

### ISSUE THREAD

**Issue by dviry** [oleg-shilo/wixsharp#246]
When using the preferred ManagedUI events (i.e. .BeforeInstall and .AfterInstall), I basically do not need any "custom actions" (ManagedCustomAction) since I can call my code directly...

But how do I manage a Rollback initiated by the Installer automatically (say when one of the actions failed)?

Thanks in advance

**Comment by Xaddan** [comment]
I did not use `.BeforeInstall` and `.AfterInstall`, and I can not say 100%. 
But as I understand these events are performed in the context of `immediate` actions, and according to the rules in such actions there should not be anything that changes the state of the computer and hence for them there is no need to rollback.

**Comment by dviry** [comment]
Actually in the Documentation it is stated that .AfterInstall is a deferred action, so would that "golden rule" still apply?

Either way, I moved all back to ElevatedCustomActions since I really need the Rollback functionality...

Thanks

**Comment by oleg-shilo** [comment]
Yes `AfterInstall` handler is hosted by a deferred action. The reason for this is to allow automatic elevation so the developer has full freedom of choice for what to do. I rally dislike obscenely fragmented business logic enforced on developers by MSI via bunch of custom actions. The "events" is an attempt to collapse them all into just a few most important MSI events for the most important deployment stages.

Thus if one want to do something in case of RollBack you can still do it in AfterInstall but you need just to detect the rollback. 

If you believe RollBack deserves to be promoted into event then just log a feature request and I may consider extending the current event model with a new event.

**Comment by dviry** [comment]
I liked the idea of the events, but had to switch back to using ElevatedCustomActions, so I guess you can close this.

Thanks

**Comment by oleg-shilo** [comment]
Not a prob.
