### ISSUE TITLE
command line arguments

### ISSUE THREAD

**Issue by Andruha-008** [oleg-shilo/wixsharp#25]
Can I get command line arguments for the processing of the script
MyProduct.msi arg1="abc" arg2="bcd"?

**Comment by oleg-shilo** [comment]
You cannot access the arguments directly. Typically the arguments, as in your case, are propagated into the session properties:
```C#
msiexec.exe /i "C:\Example.msi" MY_PROP="myValue"
```
However, this mechanism works only for public properties - properties with fully capitalized names.

If it is what you are referring to then you access these properties just as any other msi properties.
 ```C#
var value = session["MY_PROP"] ;
```

**Comment by Andruha-008** [comment]
Thanks
