### ISSUE TITLE
Registry values are  not removed while uninstalling

### ISSUE THREAD

**Issue by soundarpandiyan** [oleg-shilo/wixsharp#255]
Hi oleg, first of all i would like to thanks such a great library provided. it would be great helpful if you help on this issue

the below code i'm using also i have tried with different options like  ForceDeleteOnUninstall = true, AttributesDefinition = "Component:Permanent=no"}

```C#
 var LMOInterfaceServiceProjectSetup =
                    new Project(ProductName,     
new RegValue(RegistryHive.LocalMachine, @"Software\[Manufacturer]\Systems\IDP", "Name", "[ProductName]") { RegistryKeyAction = WixSharp.RegistryKeyAction.createAndRemoveOnUninstall},
 new RegValue(RegistryHive.LocalMachine, @"Software\[Manufacturer]\Systems\IDP", "Path", "[INSTALLDIR]") { RegistryKeyAction = WixSharp.RegistryKeyAction.createAndRemoveOnUninstall },
 new RegValue(RegistryHive.LocalMachine, @"Software\[Manufacturer]\Systems\IDP", "Version", "[AppVersion]") { RegistryKeyAction = WixSharp.RegistryKeyAction.createAndRemoveOnUninstall},
  new Dir(MainDirectory,
                              new DirFiles(MainDirectoryFiles,
                               f => !ExcludedFiles.Any(Extensions => f.EndsWith(Extensions, true))),
                            new Dir(SubDirectory,
                                new DirFiles(SubDirectoryFiles))));  
```

**Comment by soundarpandiyan** [comment]
Thanks Oleg, i have sorted out the issue. 
Sorry another question, i have command line parameters which is working with msi file but not in the boostrapper exe. i have only one msipackage.

**Comment by oleg-shilo** [comment]
The bootstraper's exe has it's oven command line args policy. 
If I am not mistaken WiX does not allow direct tunneling the exe's arguments. Instead they are translated into the msiexec args on-fly. Though quite possibly Burn has some customization mechanism that I am just not aware of.
