### ISSUE TITLE
How should installer behave when NoRepair is true?

### ISSUE THREAD

**Issue by jimfoye** [oleg-shilo/wixsharp#257]
My understanding is that when an installer is run and the version is the same, Windows installer automatically goes into "repair mode", so to speak. But what if repair has been disabled? I set project.ControlPanelInfo.NoRepair to true, so in this case, how exactly should the MSI behave when run a second time?

When I try it, it does not give any error or informational message. The "Preparing to install" dialog briefly opens and closes, and then a window frame (i.e., a window with no content) flashes briefly in the upper left-hand corner of the desktop. This definitely looks odd! 

After that, presumably the MSI exits, and I don't see any changes to the system.

Obviously I'd like to figure out what that phantom window is, and give a meaningful message to the user.

**Comment by oleg-shilo** [comment]
If you are using native UI then it is completely out of user control. Nothing you can do unless there is a special MSI mechanism for custom handing of this specific scenario.

Though if you are using ManagedUI you can try catch the condition and do something more user friendly. Just a guess. 

You can use ManagedEvents sample to see what events are fired if `NoRepair` is _true_. Then you can popup the message box to the user if the appropriate event exist. Actually this approach can also be used with native UI as well.

**Comment by jimfoye** [comment]
I'm using ManagedUI. I will take a look at the ManagedEvents sample. Thanks.
