### ISSUE TITLE
Set Installdir as Shared

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#263]
Hi Oleg,
i tried to set my installdirectory as 'Shared'. In Examples version 1.5.0 i found example for Permissions. Looks like this.
...
 new Dir(@"Docs2", new DirPermission("Everyone", GenericPermission.All)). This set all Rights for User "Everyone" and it works. How do i set my installdir as Networkpath like \\Domain\Foldername and marked installdir as 'Shared' ?
Do i need to call cacls.exe after Install or something like that ?

**Comment by oleg-shilo** [comment]
To be honest i don't know what is the MISI/WiX strategy towards installing on network drive.

You can try `InstallDir_AbsolutePath` and see what wxs and msi is generated (if any).

**Comment by Torchok19081986** [comment]
Ok. I try it. I als tried run, start Process after successfully installation in Msi_AfterInstall Event, cmd.exe with parameters net share name=PathToInstalldir /USERS:Everyone, FULL, /CACHE:None, but this works only as Admnistrator or user with special rights, but this doenst work, via cmd.exe and give it same paramters it works. Only afterinstall doesnt work. How do i start another process after install ? Is there some example in Examples  ?

**Comment by oleg-shilo** [comment]
When you execute anything from `Msi_AfterInstall` you need to be aware that you are in the elevated mode and your current dir is win32 (this is what MSI sets).

Execution itself is no different to any other cases. You can find the example in "src\WixSharp.Samples\Wix# Samples\Managed Setup"

**Comment by Torchok19081986** [comment]
Hallo Oleg, after set InstallDir_AbsoluPath or set it to e.Installdir in msi_afterinstall event i got window with Temp Folder. Path is C:\Windows\Temp\M<Nr>.tmp. Looks like msi doesnt set my installdir path for shared and of course, i can no set "net share mydir=<Path>" for myshared Dir. Any Ideas ?

**Comment by oleg-shilo** [comment]
Not sure what is happening in your case. I just slightly changed the `InstallDir_AbsolutePath` sample and this is what I've got:

```C#
project.AfterInstall += Project_AfterInstall;

static void Project_AfterInstall(SetupEventArgs e)
{
    MessageBox.Show("\ne.InstallDir -> " + e.InstallDir + "\n" +
                    "\nEnvVar('INSTALLDIR') -> " + Environment.GetEnvironmentVariable("INSTALLDIR"),
                    "AfterInstall");
}
```

![image](https://user-images.githubusercontent.com/16729806/35272094-2ed4b3a4-0088-11e8-900d-a976e498446b.png)

**Comment by Torchok19081986** [comment]
Ok. i need to check all my settings. I started after myproduct is installed in event msi_afterinstall process like
process p = new process(); with paramters, filename etc. 
cmd.exe with parameters /c net share nameofshared="e.Installdir" /Users:Everyone, FULL, /Cache:no. 
but, after successfully Installation start cmd.exe and it doesnt get e.installdir and ask me for Path.
Something is wrong, but dont know what.  Is it Different between events project_afterinstall or msi_afterinstall ? Because i set it after msi not in Project.

**Comment by oleg-shilo** [comment]
There are a few problems:
>  Is it Different between events project_afterinstall or msi_afterinstall ? 

They are just names. You can name them as you wish. The important thing is that the event handler supposed to subscribe to `project.AfterInstall +=`

First of all, verify that you can obtain correc t value for INSTALLDIR in your event handler. Use MessageBox for that: ` MessageBox.Show("ne.InstallDir);`.

If you can, then verify what is wrong with your `process.start`. I see at least one potential problem. Your InstallDir is not enclosed in quotation chars and it has high chance to have spaces:

```C#
p.StartInfo.Arguments = " /c net share myproduct=" + e.InstallDir + "";
// probably needs to be something like this
p.StartInfo.Arguments = " /c net share myproduct=\"" + e.InstallDir + "\"";

```

**Comment by Torchok19081986** [comment]
ok. Thanks. i try it in this way and give feedback.
