### ISSUE TITLE
Project.SetVersionFrom() and Project.Version

### ISSUE THREAD

**Issue by dviry** [oleg-shilo/wixsharp#264]
I am using the SetVersionFrom() extension to be able to set a high (unsupported) Version number (2017.*) read from a file, and I've been running into issues with upgrades ("Another version of this product is already installed").
It seems that when setting Project.GUID and using Project.SetVersionFrom() the Project.Version is not set and WixSharp is ALWAYS using the same ProductID (even with different Project.Version).

Now [in the remarks](https://github.com/oleg-shilo/wixsharp/blob/a84d369910833023ba21c27644059183966fa908/Source/src/WixSharp/CommonTasks.cs#L904) you write:
"If SetVersionFrom is used then Wix# is no longer responsible for setting the product version.
This task is delegated to WiX so the whole value `project.Version` becomes completely irrelevant."

Not sure what I am doing wrong, but I had to set Project.Version to get a new ProductID to get my upgrades to work... Could it be related to the high version number that WiX wont support?

Thanks

**Comment by dviry** [comment]
That's exactly what I thought, but when using .SetVersionFromFile() it does not work since I am using an "invalid" version (so I am guessing it is passing the .Version to the WiX instead of the "!(bind.FileVersion.MyApp_file"...)

```
.wxs(3,0): Error CNDL0242: Invalid product version '2017.0.0.0'. Product version must have a major version less than 256, a minor version less than 256, and a build version less than 65536.
```

Cheers

**Comment by dviry** [comment]
... in fact, it seems 1.6.1 "broke" something for me since now I am getting the following error (which worked fine before):
```
.wxs(3,0): Error LGHT0298: Unresolved bind-time variable !(bind.FileVersion.xxxxx.exe).
```

**Comment by dviry** [comment]
OK, got it to work (with the old .SetVersionFrom()). Here is my snippet of code that now works:
```c#
var files = FindFile(f => f.Name.EndsWith(versionFromAssembly, StringComparison.InvariantCultureIgnoreCase));
if (files.Length != 1)
{
    throw new ArgumentException($"Cannot find {versionFromAssembly} to retrieve Version info!");
}
var file = files.First();

var info = FileVersionInfo.GetVersionInfo(files[0].Name);
OutFileName = $"{name}_{info.ProductVersion}";

// set version from one of the contained files
SetVersionFrom(file.Id);
Version = new Version(info.ProductVersion);
```

... but if I change to `SetVersionFromFile(file.Name)` and remove the Version I get an error (invalid version number).

Cheers

**Comment by oleg-shilo** [comment]
As for me it is an obvious WiX bug:

> It is OK if the version with too high element is set indirectly via _binding_.
   It is not OK if the version with too high element is set directly to _Product_ element.

Though I may consider calling `Version = new Version(info.ProductVersion);` automatically from inside of 
`SetVersionFrom(file.Id);`

**Comment by oleg-shilo** [comment]
> I wrote: "Though I may consider calling Version = new Version(info.ProductVersion); automatically from inside of SetVersionFrom(file.Id);"

Done. 7ac06751c73e3d420f1a0988da5ba5864165c725

```C#
static public Project SetVersionFrom(this Project project, string fileId, bool setProjectVersionAsWell = true)
{
    project.SetVersionFromIdValue = fileId;
    project.WixSourceGenerated += document =>
        document.FindSingle("Product")
                .AddAttributes("Version=!(bind.FileVersion." + fileId + ")");

    if (setProjectVersionAsWell)
    {
        var file = project.AllFiles.FirstOrDefault(x => x.Id == fileId);
        if (file != null)
        {
            var file_path = Utils.PathCombine(project.SourceBaseDir, file.Name);
            if (IO.File.Exists(file_path))
                project.Version = new Version(FileVersionInfo.GetVersionInfo(file_path).FileVersion);
        }
        else
            Console.WriteLine("Warning: ");
    }
    return project;
}
```
