### ISSUE TITLE
Exception using RegFile class with REGEDIT4 version reg file

### ISSUE THREAD

**Issue by RSchwoerer** [oleg-shilo/wixsharp#265]
I am getting an exception trying to use the ``RegFile`` class.
It happens when importing a reg file with a ``REGEDIT4`` version string at the top of the reg file.

Here's the full callstack from the exception...
`System.ArgumentException: 'ANSI' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at WixSharp.RegParser.Parse(String content)
   at WixSharp.RegFileImporter.ImportFrom(String regFile)
   at WixSharp.Project..ctor(String name, WixObject[] items)
   at Script.Main(String[] args)`

It is being caused by this method...
https://github.com/oleg-shilo/wixsharp/blob/26092e67852a5b4c452dd201068261de22c7ee5d/Source/src/WixSharp/RegFileImporter.cs#L302

I'm not sure the reasoning behind returning the ``ANSI`` value. It looks like according to [this MSDN page](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netframework-4.6.1#Remarks) ``ANSI`` is not even a valid encoding string (maybe it was at one time).

## Steps to Reproduce
If you change the first line of [this sample reg file](https://github.com/oleg-shilo/wixsharp/blob/6c6cc4ef7800e5d2b9772f0f858deb94dd1ba077/Source/src/WixSharp.Samples/Wix%23%20Samples/Registry/MyProduct.reg#L1) to ``REGEDIT4`` and run the build you will get the same exception.

## Workaround
Change the first line of any reg file to ``Windows Registry Editor Version 5.00``.
This should probably be there anyway (since XP anyway) but some older files may still have the old version string.

**Comment by oleg-shilo** [comment]
Thank you. Corrected in 97259adba49a95fc7fce48838aa4e3d58a1fa938
Will be available in the next release.
