### ISSUE TITLE
Set ARPINSTALLLOCATION custom action in wrong place

### ISSUE THREAD

**Issue by aleksandr-grechko** [oleg-shilo/wixsharp#267]
Hi,

I use this notation:

        project.ControlPanelInfo.InstallLocation = "[INSTALLDIR]";  

to set up ARPINSTALLLOCATION property.
It should create action to set this property and schedule it after CostFinalize action ([link](http://robmensching.com/blog/posts/2011/1/14/arpinstalllocation-and-how-to-set-it-with-the-wix-toolset/)).
But Wix# adds this action right after my latest custom action in InstallExecuteSequence.

 
> 
    <CustomAction Id="CA_CompareVersionsOnUpgrade" BinaryKey="Action4_CompareVersionsOnUpgrade_File" DllEntry="CompareVersionsOnUpgrade" Return="check" Execute="firstSequence" />
    <CustomAction Id="Set_ARPINSTALLLOCATION" Property="ARPINSTALLLOCATION" Value="[INSTALLDIR]" Return="check" Execute="immediate" />
    <CustomAction Id="Set_ARPNOMODIFY" Property="ARPNOMODIFY" Value="True" Return="check" Execute="immediate" />
    <CustomAction Id="Set_DirAbsolutePath" Property="INSTALLDIR" Value="C:\SPASandbox\" />

    <InstallExecuteSequence>
      <Custom Action="CA_CompareVersionsOnUpgrade" Before="LaunchConditions">WIX_UPGRADE_DETECTED</Custom>
      <Custom Action="Set_ARPINSTALLLOCATION" After="CA_CompareVersionsOnUpgrade"> (NOT Installed) </Custom>
      <Custom Action="Set_ARPNOMODIFY" After="Set_ARPINSTALLLOCATION"> (NOT Installed) </Custom>
      <Custom Action="Set_DirAbsolutePath" Before="AppSearch">(NOT Installed) AND (UILevel &lt; 5) AND (INSTALLDIR = ABSOLUTEPATH)</Custom>
    </InstallExecuteSequence>

> 
    <CustomAction Id="CA_CompareVersionsOnUpgrade" BinaryKey="Action5_CompareVersionsOnUpgrade_File" DllEntry="CompareVersionsOnUpgrade" Return="check" Execute="firstSequence" />
    <CustomAction Id="CA_PostInstallSteps" BinaryKey="Action5_CompareVersionsOnUpgrade_File" DllEntry="PostInstallSteps" Return="check" Execute="immediate" />
    <CustomAction Id="Set_ARPINSTALLLOCATION" Property="ARPINSTALLLOCATION" Value="[INSTALLDIR]" Return="check" Execute="immediate" />
    <CustomAction Id="Set_ARPNOMODIFY" Property="ARPNOMODIFY" Value="True" Return="check" Execute="immediate" />
    <CustomAction Id="Set_DirAbsolutePath" Property="INSTALLDIR" Value="C:\SPASandbox\" />

    <InstallExecuteSequence>
      <Custom Action="CA_CompareVersionsOnUpgrade" Before="LaunchConditions">WIX_UPGRADE_DETECTED</Custom>
      <Custom Action="CA_PostInstallSteps" After="InstallFinalize"> (NOT Installed) </Custom>
      <Custom Action="Set_ARPINSTALLLOCATION" After="CA_PostInstallSteps"> (NOT Installed) </Custom>
      <Custom Action="Set_ARPNOMODIFY" After="Set_ARPINSTALLLOCATION"> (NOT Installed) </Custom>
      <Custom Action="Set_DirAbsolutePath" Before="AppSearch">(NOT Installed) AND (UILevel &lt; 5) AND (INSTALLDIR = ABSOLUTEPATH)</Custom>
    </InstallExecuteSequence>

**Comment by oleg-shilo** [comment]
Thank you.

Fixed in 0722b11e8f15d9d7d45980b04b3a5f8944e122d0. Will be available in the next release

**Comment by TI-asilva** [comment]
Hello,

I am using the code from above:

`project.ControlPanelInfo.InstallLocation = "[INSTALLDIR]";`

which generates the 2 xml blocks in the .wxs file:

`<CustomAction Id="Set_ARPINSTALLLOCATION" Property="ARPINSTALLLOCATION" Value="[INSTALLDIR]" Return="check" Execute="immediate" />`
`<InstallExecuteSequence>
  <Custom Action="Set_ARPINSTALLLOCATION" After="CostFinalize"> (NOT Installed) </Custom>
</InstallExecuteSequence>`

These are the only such blocks I have (i.e. there are no other custom actions). However, this does NOT lead to the setting of the InstallLocation key in the registry and I'm not sure why. One thing of note is that this msi is part of a bootstrapper bundle that contains another installer that is a prerequisite for the msi's app. The rest of the installer is fairly vanilla Program.cs (project was generated by WixSharp Project Templates). I am using the default/minimal UI and it makes no difference whether I specify a custom directory or not. For what it's worth, my Directory tags look like this:

`    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFiles64Folder" Name="ProgramFiles64Folder">
        <Directory Id="INSTALLDIR" Name="appname">
           .
           .
           .
        </Directory>
      </Directory>
    </Directory>`

Any idea what I could be missing? 

Also, a side question - is there documentation explaining that line of code anywhere? I have the same goal of setting the InstallLocation registry key, but were it not for this related bug post, I would not have known to do that.

Thank you
