### ISSUE TITLE
File.AddShortcut Extension has strange side effects

### ISSUE THREAD

**Issue by RSchwoerer** [oleg-shilo/wixsharp#269]
I am trying to create some shortcuts and using the ``AddShortcut`` extension has some weird side effects. It seems to be affecting wxs file output much more than just adding the single line to add a Shortcut.

I tried to isolate this using one of the samples, my actual application is much larger and there are other components that are being changed when adding a line similar to below.
Also, I am using the ``Files`` method (like [release folder](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Release%20Folder/setup.cs)) so going back and finding the files and attaching the shortcuts is only way to do it (as far as I know).

## Steps to reproduce
Using the [setup](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Shortcuts/setup.cs) sample, add the below code...........

```C#
project.ResolveWildCards(ignoreEmptyDirectories: true)
  .FindFile(f => f.Name.EndsWith("MyApp.exe", StringComparison.OrdinalIgnoreCase))
  .First()
  .AddShortcut(
    new FileShortcut("MyApp", @"%ProgramMenu%\My Company\My Product")
    { IconFile = @"AppFiles\Icon.ico", WorkingDirectory = "%Temp%", Arguments = "777" }
  );
```
When this additional ``AddShortcut`` is added the shortcut "Uninstall MyApp" is no longer in the output. And there are some warnings about duplicate directories.

> error LGHT0091 : Duplicate symbol 'Directory:ProgramMenuFolder.My_Company' found. This typically means that an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
error LGHT0092 : Location of symbol related to previous error.

**Comment by oleg-shilo** [comment]
Sorry for the delay. Working on it...

**Comment by oleg-shilo** [comment]
The problem is in you definition of the `FileShortcut` object. 

The second argument in the constructor supposed to be the ID of the directory where the shoulrcut should be created. You have specified multi elements path. This path was automatically broken into pieces and converted into a new directory tree, which then has been placed in the already defined dir structure:

```C#
// @"%ProgramMenu%\My Company\My Product" =>

new Dir("%ProgramMenu%",
    new Dir("My Company",
        new Dir("My Product")))
```

The fixed version of your code looks like this: 
```C#
project.ResolveWildCards(ignoreEmptyDirectories: true)
        .FindFile(f => f.Name.EndsWith("MyApp.exe", StringComparison.OrdinalIgnoreCase))
        .First()
        .AddShortcut(
            new FileShortcut("MyApp_AnotherOnle", "INSTALLDIR")
            {
                IconFile = @"AppFiles\Icon.ico",
                WorkingDirectory = "%Temp%",
                Arguments = "777"
            });
```

Please note that I have also updated the method XML doc so it makes the point that the second argument is not a path but a dir ID:

![image](https://user-images.githubusercontent.com/16729806/35315426-6e263922-0120-11e8-8dac-ffc5a94ec326.png)

**Comment by RSchwoerer** [comment]
Thanks, that makes sense.

The 'shortcuts' sample I linked conveniently had a 'Dir' for "%ProgramMenu%\My Company\My Product" already. I was trying to add all the shortcuts at the end, using the [release folder example](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Release%20Folder/setup.cs) style.

How do I find the Id of an existing 'Dir'?
If I have this...

> new Dir(@"%ProgramMenu%\My Company\My Product",
                    new ExeFileShortcut("Uninstall", "[System64Folder]msiexec.exe", "/x [ProductCode]"),

(I am actually adding a few other 'ExeFileShortcut's here also, not just the one "uninstall")

This does not seem to work...

> var programMenuId = project.FindDir(@"%ProgramMenu%\Veeco Instruments").Id;

I get...

> error LGHT0094: Unresolved reference to symbol 'Directory:My_Product' in section 'Product:{GUID}'.

**Comment by oleg-shilo** [comment]
There a few techniques.

One is raw LINQ:
```C#
var id = project.Dirs
                .Where(x => x.Name == "%ProgramMenu%").SelectMany(x => x.Dirs)
                .Where(x => x.Name == "My Company").SelectMany(x => x.Dirs)
                .Where(x => x.Name == "My Product")
                .FirstOrDefault()
                .Id;
```
Alternatively you can just call `project.FindDir` as you did. Though it's not clear how you add the shortcut so I cannot comment on the _light_ error.
