### ISSUE TITLE
Custom folders doesn't remove during uninstall

### ISSUE THREAD

**Issue by Sollex-21412** [oleg-shilo/wixsharp#271]
Hi all.
Custom start menu folders doesn't remove during uninstall. 
Should I add something else?
Here is the code:
```c#
new Dir(new Id("STARTMENUSHORTCUTPATH"), "startMenu,
    new ExeFileShortcut(Constants.ProductName, string.Format("[INSTALLDIR]{0}", Constants.ExeName), "")
    {
        Condition = new Condition("INSTALLSTARTMENUSHORTCUT=\"yes\"")
    },
    new ExeFileShortcut(string.Format("Uninstall {0}", Constants.ProductName), "[System64Folder]msiexec.exe", "/x [ProductCode]")
    {
        Condition = new Condition("INSTALLSTARTMENUSHORTCUT=\"yes\"")
    }),

**Comment by oleg-shilo** [comment]
I have checked and the `Shortcuts` sample removes start menu entries properly.

The only difference is comparing to your code is that second parameter in the `Dir` constructor and the use of `Conditions`. https://github.com/oleg-shilo/wixsharp/blob/96666dac4dc458dc7950100e798eb18a05caf2dc/Source/src/WixSharp.Samples/Wix%23%20Samples/Shortcuts/setup.cs#L38-L40

**Comment by Sollex-21412** [comment]
Sorry for the delay, somehow I've missed notification.

My goal is to make dynamic path for the start menu shortcuts. That's why I use "STARTMENUSHORTCUTPATH".

```c#
"STARTMENUSHORTCUTPATH=" + "\"" + Environment.GetFolderPath(Environment.SpecialFolder.StartMenu) + "\\Programs\\" + startMenuPath + "\""
```
The problem is the installer won't to remove this dynamic folder during uninstall.

Part of the my "SetupMSI.g.wxs":
```xml
      <Directory Id="STARTMENUSHORTCUTPATH" Name="startMenu">

        <Component Id="App.1" Guid="b0fe9c09-057d-42c8-b0ef-297e99297ef2">
          <Condition>INSTALLSTARTMENUSHORTCUT="yes"</Condition>

          <Shortcut Id="STARTMENUSHORTCUTPATH.App.1" WorkingDirectory="INSTALLDIR" Target="[INSTALLDIR]App.exe" Name="App.lnk" />
          <RemoveFolder Id="STARTMENUSHORTCUTPATH" On="uninstall" />

          <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
            <RegistryValue Value="0" Type="string" KeyPath="yes" />
          </RegistryKey>
        </Component>

        <Component Id="Uninstall_App" Guid="b0fe9c09-057d-42c8-b0ef-297e1f7e3cbc">
          <Condition>INSTALLSTARTMENUSHORTCUT="yes"</Condition>

          <Shortcut Id="STARTMENUSHORTCUTPATH.Uninstall_App" WorkingDirectory="System64Folder" Target="[System64Folder]msiexec.exe" Arguments="/x [ProductCode]" Name="Uninstall App.lnk" />

          <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
            <RegistryValue Value="0" Type="string" KeyPath="yes" />
          </RegistryKey>
        </Component>

      </Directory>
    </Directory>
```

**Comment by oleg-shilo** [comment]
Then may by the fact that this path is dynamically composed is responsible for MSI not removing the folder.

If it is the case then it is simply how MSI works. Meaning that you may need to remove this folder also dynamically (e.g. from _AfterInstall_ event).

Though I would verify first that your test environment does not exhibit this behavior for non-custom folders.  Just test and see if the sample from WixSharp distro works correctly.

**Comment by Sollex-21412** [comment]
Well, OK. In this case, I'll remove this in AfterInstall event.
Thank you for the advice.
