### ISSUE TITLE
Issues with the native bootstrapper

### ISSUE THREAD

**Issue by geghamyan** [oleg-shilo/wixsharp#273]
Hi all,

There are some issues I fixed related to the native boostrapper:

The logic related to "WixSharp.NativeBootstrapper.PrerequisiteRegKeyValue" handling doesn't work, because of an issue in nbs.exe native app. I fixed it and updated the NbsBuilder.Src.7z archive in the source tree.
The logic for NativeBootstrapper.DoNotPostVerifyPrerequisite boolean flag is swapped. Fixed it.
I've rebuilt nbsbuilder.exe with vs2017 (xp support) and added to the WixSharp.bin nuget package.

Pull request is created:
https://github.com/oleg-shilo/wixsharp/pull/272

Regards,
Tigran

**Comment by oleg-shilo** [comment]
Thank you, Tigran,

I am a bit drowning in other GitHub projects to I really appreciate you fully taking care about this issue.

Cheers,
Oleg

**Comment by geghamyan** [comment]
My pleasure. Thank you for the Wix# project.

**Comment by geghamyan** [comment]
Oleg, what do you think about an ability to configure built-in resources of the resulting nbs.exe application. It can be done through additional command line parameters to nbsbuilder.exe. In particular I am referring to:
* version information: description, copyright, product version etc
* application icon
* manifest (UAC admin rights)

Currently, after building the native bootstapper, I am using the Vestris.ResourceLib nuget package to patch the above-mentioned resources, which feels like more like a workaround.

Regards,
Tigran

**Comment by oleg-shilo** [comment]
Yes this is a limitation of the current solution. I do see the ability of programmatically patching (e.g. with Vestris.ResourceLib) the executable as a valuable feature. However I am not sure that the level of demand for 'native bootstrapper' justifies the effort. After all we do have WiX bootstrapper (Burn). It's not ideal but this is what everyone is using.

I would still give it a go but I simply have absolutely no time for that now. The amount of active tickets/issues are slowly going up. Isn't it always :)

If you ever find time for this I will gladly merge any PR for that.

**Comment by geghamyan** [comment]
Oh yes, I was implying that I am going to write the code :) 
Just wanted to run it through you first, before spending time on it.

For me, the biggest difference between the Wix Bootstapper and the native one is that the Burn is not "fire-and-forget", it installs itself in the system and requires careful reasoning regarding uninstallation/update/maintenance procedures.

**Comment by oleg-shilo** [comment]
Then go for it. :)
Another problem is that Burn does not show MSI internal UI if it is an _EmbeddedUI_. Rediculous bug that was reported ~2 years ago and still not fixed.

----

As for `Vestris.ResourceLib` I am very interested to see if it can patch interop-exported assemblies. I didn't know about this library and resorted to use ResourceHacker.exe in command line mode to patch CS-Script plugin for Notepad++ I wrote. To my surprise everything else dramatically fails to do so unless it is a raw simple dll/exe.

**Comment by oleg-shilo** [comment]
Uupdate on Vestris.ResourceLib...

Unfortunately it also fails..
