### ISSUE TITLE
ManagedUI does not handle different DPI settings

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#274]
I've been trying to work out the best way to handle our requirements for a custom dialog, and although I've read all the docs, and the various statements that ManagedUI is the easiest and most flexible approach for customisation, it appears to have a very significant problem.  It doesn't appear to handle high dpi scenarios at all really?

![image](https://user-images.githubusercontent.com/2234967/35195836-e44c5e48-fed1-11e7-9b12-1c32dc333206.png)
![image](https://user-images.githubusercontent.com/2234967/35195839-f405911a-fed1-11e7-8e16-f348be8a0867.png)

Is this a known issue?

**Comment by oleg-shilo** [comment]
Nasty. The UI is WinForm based. While indeed it is easy to work with, it is bound by the technology limitations. This technology is not good with scaling at all. It's not WPF.

I did custom scaling at least for some critical UI elements (e.g. features tree). But apparently it wasn't enough in your case.

I suggest that you do not use compiled stock dialogs but rather use them as code. Create the project from "Custom UI" template.

![image](https://user-images.githubusercontent.com/16729806/35273106-7e94df56-008b-11e8-9811-e35a1b94d45d.png)
  
Now, you have all dialogs completely open for modifications/adjustments. You can implement any custom scaling techniques as you want. If you happen to find and implement a good scaling algorithm please share it and I can update the stock dialogs so everyone can benefit.

**Comment by apawsey** [comment]
Looking at the source, I have considered some ways to better handle the UI, but for now we've decided on an external UI... at least I think we have :)

I am desperately trying to find time to tackle some of these as pull requests... so we'll see.
