### ISSUE TITLE
Add Win64 parameter to RegistrySearch

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#278]
According to http://wixtoolset.org/documentation/manual/v3/xsd/wix/registrysearch.html, WIX supports the following parameters:
- Id
- Key
- Name
- Root
- Type
- Win64
- plus children.

In last version of RegistrySearch.cs of Wixsharp the parameter `Win64` is not available.

Of course you can workaround this limitation by determining whether the installer is running on 32- or 64-bit windows and then rewriting the registry path when necessary.

But it would be easier for end users when Win64 would be supported too.

**Comment by oleg-shilo** [comment]
I argue that this attribute is not as useful as it seems at the first site. This is what the documentation says.

> ...The default value is based on the platform set by the -arch switch to candle.exe or the InstallerPlatform property in a .wixproj MSBuild project: For x86 and ARM, the default value is 'no'. For x64 and IA64, the default value is 'yes'. 

Meaning that when running x86 setup the reg-values will be created in the Win32 hive. And if it happens to be a x64 setup then the Win64 hive will be the target.

The objective of the WiX `Win64` attribute is to allow one to work with the registry hive, which is inconsistent with the setup target architecture. And because of this I would rather hide it from user to avoid unnecessary confusion.  

Though supporting this attribute is already implemented: https://github.com/oleg-shilo/wixsharp/blob/96666dac4dc458dc7950100e798eb18a05caf2dc/Source/src/WixSharp/RegistrySearch.cs#L100

**Comment by monty241** [comment]
Yes, for several scenarios it can be confusing. When I looked it up, I needed a registry search specifically into the 32-bit hive for both 64-bit and 32-bit installers.

Reason: Visual Studio Tools for Office Runtime only registers its presence in the 32-bit section on 64-bit Windows for both the 32- and 64-bit installations of Visual Studio Tools for Office Runtime.

What would be good approach to avoid the confusion of the default and still allow such a scenario?

**Comment by oleg-shilo** [comment]
As for me I would (as early as possible) check the required registry with C#:
```C#
new ManagedAction(CustomActions.CheckRegistry, Return.check, When.Before, Step.AppSearch, Condition.NOT_Installed)
...
public class CustomActions
{
    [CustomAction]
    public static ActionResult CheckRegistry(Session session)
    {
        // do your OS architecture checking and reg search
        string reg_value = ...
        e.Session["MY_ALWAYS_x86_REG"] = reg_value; 
        ...

// or

project.Load += CheckRegistry;
...
static void CheckRegistry(SetupEventArgs e)
{
    // do your OS architecture checking and reg search
    string reg_value = ...
    e.Session["MY_ALWAYS_x86_REG"] = reg_value; 
    ...
``` 

And only if managed CA/event is not suitable then use that `RegistrySearch.Win64`.

**Comment by monty241** [comment]
Thank you. Do I understand it correctly that the invocation of ManagedAction does not incur a large performance penalty? We are still trying to use as few as possible custom actions. But when the performance is not hampered, it would save even more time.

**Comment by oleg-shilo** [comment]
> ...ManagedAction does not incur a large performance penalty?

Yes, it is correct. 

Though, honestly, it is the first time ever I hear anyone even considering performance of the CA. :)

It is a setup application. It is an activity that is performed in many cases only once per product deployment life. The activity itself is highly disruptive so it is expected to be performance non-critical. The activity itself includes steps with sometimes enormous delays. For example triggering elevation prompt can take anything between 3-15 seconds.

Thus, one may have various reasons for not using ManagedActions but "performance" is not among them.

**Comment by monty241** [comment]
Ok, good to know. We have never tested performance very deeply on what is causing the installs to vary widely in runtime, but your experience is very well welcome.
