### ISSUE TITLE
A Shortcut's generated ID is different from what it is explicitly set to

### ISSUE THREAD

**Issue by BobVul** [oleg-shilo/wixsharp#280]
When setting a `FileShortcut`'s `Id`, e.g.:

```cs
file.Shortcuts = new []
{
    new FileShortcut(new Id("MyShortcutId"), "MyShortcut", "INSTALLDIR")
};
```

the generated shortcut is not `MyShortcutId` but rather `Shortcut.FileId.MyShortcutId`.

I'm not sure if this was an oversight or if it's intentional. It does make it more difficult to find the shortcut to inject XML into it.

There's a similar issue with directory-owned shortcuts. For an `ExeFileShortcut` the id becomes the `Component` element's id, not the `Shortcut` element's id.

https://github.com/oleg-shilo/wixsharp/blob/96666dac4dc458dc7950100e798eb18a05caf2dc/Source/src/WixSharp/Compiler.cs#L1859

**Comment by BobVul** [comment]
I guess, even if it isn't intentional, changing this behaviour would break some existing scripts too...

**Comment by oleg-shilo** [comment]
Thank you. Valid point. Fixed.

**Comment by BobVul** [comment]
Thanks!
