### ISSUE TITLE
DirPermission never set

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#284]
Hi,

This may be a underlying Wix issue, I'm not sure, but I'm guessing you'll know better than me.

I'm setting the permissions for a folder that is created during the install...
```
new Dir(@"%CommonAppDataFolder%\TaxPacc",
                    new DirPermission("[SERVICEACCOUNTUSERNAME]", "[SERVICEACCOUNTDOMAIN]", GenericPermission.All),
                    new Dir("Server",
                        new WixSharp.File(serverFeature,...),
```
However, the permissions are never set.

I've checked the wxs output and it looks like this...
```
 <Directory Id="CommonAppDataFolder" Name="CommonAppDataFolder">
        <Directory Id="CommonAppDataFolder.TaxPacc" Name="TaxPacc">

          <Component Id="ComponentDirPermission" Guid="8ff4eac9-03a9-44fa-b146-3b9e5e062900" KeyPath="yes">
            <CreateFolder>
              <PermissionEx User="[SERVICEACCOUNTUSERNAME]" Domain="[SERVICEACCOUNTDOMAIN]" GenericAll="yes" xmlns="http://schemas.microsoft.com/wix/UtilExtension" />
            </CreateFolder>
            <RemoveFolder Id="CommonAppDataFolder.TaxPacc" On="uninstall" />
          </Component>

          <Directory Id="CommonAppDataFolder.TaxPacc.Server" Name="Server">

            ...

          </Directory>
        </Directory>
      </Directory>
```
Which with my reasonable knowledge of WIX, looks fine.  Obviously nothing complains during the build.

However, as I said, the permissions are never set.  I ran the msi with complete logging, and dug into the WIX source, and discovered that the PermissionsEx is handled in two stages.  A SchedSecureObjects action is run to find the items that need to have permissions set, and then later an ExecSecureObjects action should run to actually set the permissions.  However in my logging, the ExeSecureObjects action is never run (or at least I can find no trace of it in the log).  SchedSecureObjects is though, with no error messages I can see.

Looking at the source for SchedSecureObjects, the only way I could see that it would run the schedule action, and not the exec action, is a check for the 64-bit flag on the component, matching the 64-bit nature of the CA dll.  That's the only way I can see that it can run that action and not produce any errors, but also not do anything, because in that situation it silently skips the component.  I've tried manually setting that flag in the MSI (after building it with WixSharp), and it didn't seem to make a difference, although I can't honestly say I set the flag correctly etc.

I am now completely at a loss as to why it never runs the execute portion.

I tried using the permissions sample, and that runs the ExecSecureObjects fine... and I'm trying to see any differences between my project and that sample, but I can't find much.  The biggest is obviously that my project is built via MSBuild and the wixsharp targets, and the sample is built via the cscs stuff.

Any ideas at all???

**Comment by oleg-shilo** [comment]
Hi Adam, indeed it may be some WiX underlying problem though it's hard to say for sure at this stage. 

Your findings about SchedSecureObjects/ExecSecureObjects are quite remarkable. As for me, they deserve to be logged as WiX issue. Silently skipping user anticipated actions is no way a reasonable approach.

To be honest judging from your description you already have more knowledge about the issue than I do.  :)

I would expect x64 attribute to be already set for all components simply because your project would have the platform property set to x64. 
```C#
project.Platform = Platform.x64;
```
Thus it may indeed be some problem with that attribute if for whatever reason it's not set correctly.

> I've tried manually setting that flag in the MSI (after building it with WixSharp), and it didn't seem to make a difference, although I can't honestly say I set the flag correctly etc.

There is a much better way of verifying the solution. I suggest you use `project.BuildMsiCmd` instead of `project.BuildMsi`. This way WixSharp produces WiX file and the batch file to build an msi from it. 

This gives you the ability to change any element of wxs file and compile it without WixSharp being involved neither with the need to patch MSI manually. This gives you a complete freedom of experimenting without guessing.

**Comment by apawsey** [comment]
I totally agree that the fact that it can potentially skip setting permissions and log nothing about it, is a bit crazy.

The only reason I think this might _somehow_ be related to wixsharp is the fact that the sample works.

My logic is as follows...
Two projects built on the same machine, tested on the same virtual machine.
Both projects have near identical wixsharp source (regarding the permissions part).
Both projects have near identical wix xml output (again regarding the permissions part).
The most obvious difference is one is built like all the other samples, by executing the script.  The other is built by compiling the msi, and then executing, all through the msbuild process.

All I could think is that something is different in what is being generated and passed to wix, and/or possibly in how the wix tools are being executed.  I did notice for example that when the sample executes the wix light tool, there is a couple of -"ext" parameters being passed, whereas when light is executed as during the msbuild process, I don't see any -ext parameters being passed.

Don't misunderstand, I'm certainly not on some kind of witch-hunt to place this issue at WixSharp's feet... unfortunately it's just one of those problem solving exercises where I'm desperately trying to find any difference as I have very little other evidence to go on 😞

**Comment by oleg-shilo** [comment]
Don't worry, you in no danger of being accused in witch-hunting. :)

The fact that you have one solution that works and another one that doesn't already indicates that it's fixable (well I hope).  

Can you please send me these samples so I can have a closer look?

**Comment by oleg-shilo** [comment]
> ... light tool, there is a couple of -"ext" parameters being passed, whereas when light is executed as during the msbuild process, I don't see any -ext parameters being passed.

BTW if you are using BuildMsiCmd you can exteriment by removing not needed -ext params from candle and light.
