### ISSUE TITLE
Session.Database.FilePath is empty in managed custom action

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#285]
Hi,

In a custom action we need to copy the msi file to a folder within the install, because it also contains the install for the client software and is distributed via a built in update service.

However when I try and access session.Database.FilePath to get the original msi location (inside a managed custom action) the value is empty (it may be null I'm not sure, but point is, it's not there).  Any idea as to why?

Thanks.

**Comment by apawsey** [comment]
Worked around this using Session["OriginalDatabase"] but still wondering why it would be empty?

**Comment by oleg-shilo** [comment]
Yeah, I also noticed that. Unfortunately WixSharp has no control over the content of the session object. It's instantiated and populated by WiX/MSI runtime. 

Though WixSharp proactively helps the user with this problem and in the ManagedProject events (managed CA) you can retrieve the msi file path. Even in deferred CA which have completely empty session object:

```C#
project.AfterInstall += project_AfterInstall;

static void project_AfterInstall(SetupEventArgs e)
{
    MessageBox.Show(e.MsiFile);
    ...
```
And ths solution is based on the very same work around: Session["OriginalDatabase"]

**Comment by apawsey** [comment]
Oh well... msi and it's peculiarities 🤦‍♂️ 😆

**Comment by oleg-shilo** [comment]
Yeah, not only MSI but session as well.... When I was only starting WixSharo I was shocked when I learned that in Deferred Actions the session object is already disposed and one can get an absolute zero information about the installation being in progress.

Fortunately there is a work around for almost anything... :o)
