### ISSUE TITLE
NativeImage for wildcards

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#286]
Hi,

Is there any good way to add the native image functionality for files added by wildcard?

Thanks.

P.S. I'd like to have a discussion with you regarding the wixsharp msi functionality.  Is there a way I can contact you?

**Comment by oleg-shilo** [comment]
You can do something like this:
```C#
project.ResolveWildCards();
project.AllFiles
       .Where(file => file.Name.EndsWith(".dll"))
       .ForEach(file => file.Add(new NativeImage { Platform = NativeImagePlatform.x86 }));
```
> Is there a way I can contact you?

Sure. Contact my via LinkedIn and we will exchange emails.

**Comment by apawsey** [comment]
Yeah that's exactly what I did, sorry it wasn't really an 'issue', I was just checking to see if I'd missed something.

As I said before, the wildcards was one of the main reasons we adopted wixsharp, and in general this is all pretty awesome.  That said, I think there's some really powerful things that could be done with the wildcards functionality... predicates for applying certain attributes, child items, etc.  As usual, when the world around me has stopped apparently ending (ie: current versions are out the door), I'm going to make some real effort to submit some PR's here.  Thanks again!

**Comment by oleg-shilo** [comment]
Yes wild cards do have some not yet explored opportunities. When you declare wild card entity you already have the ability to pass predicates: 
```
public DirFiles(string sourcePath, Predicate<string> filter)
```

However the larger potential is not in the filtering but mapping delegates. 

They can do much more then just passing (or not) the file into the setup definition (project).  They can deeply modify/decorate the entity before letting it into the project def. They can even emit new entities either vertically (e.g. exe file automatically gates its shortcut inserted) or horizontally (e.g. every dll is inserted with its xml doc file). Similar to the LINQ where we have two paradigms `Select()` vs. `SelectMany()`.    

This would require very carefully crafted API. Just extra signatures of `DirFiles` and `Files` would not do it.
An immediate candidate would be something like this:
```c#
project.ResolveWildCards(forEachFile: file=>{...},
                         forEachDir: dir=>{...},                              
                         forSomethingElse: context=>{...},
                         ...
                         onCompletion: project=>{...});
```
