### ISSUE TITLE
Feature Suggestion: Prerequisites

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#288]
Hi,

Have you thought about handling prerequisites with wixsharp?  I'm currently having to add the VSTO runtime to our installer, and I've whipped up a really quick prerequisite downloader class that we use before the project code runs... but like I say, it's a real rush job, but I think done properly, there's a lot of value in it.  WixSharp gives a really nice environment for handling tasks like this before a build/package operation.

Just a thought.

**Comment by oleg-shilo** [comment]
It's an interesting idea. Is there any overlap with Burn? By definition it does exactly that (URL based package) but at run (not compile) time.

OK "overlap" is not a very accurate term in. In both cases the objective is the same. To bring the dependency package to the target PC. Though in one case the dependency is downloaded at compile time and embedded into the main package (presumably built with Burn). In another one the main package (built with Burn) contains the dependency download instructions.

Not rejecting... Just also thinking :)   Prompting for further discussion...
