### ISSUE TITLE
Q: FilesInUse Dialog in ManagedUI?

### ISSUE THREAD

**Issue by dviry** [oleg-shilo/wixsharp#289]
According to [this article](https://msdn.microsoft.com/en-us/library/aa369546(v=vs.85).aspx), if there are any filesInUse MSI searches for a Dialog named "FilesInUse" to show to the user.
When using the ManagedUI there is no such dialog in the created .MSI, so nothing is shown to the user (only at the end a reboot recommendation dialog shows, probably directly from .MSI), which silently fails (basically choosing Ignore).

Are there any plans to include such a feature? What is your suggested way of handling such cases?

Thanks in advance

**Comment by oleg-shilo** [comment]
Yes it is a missing feature.
May I ask you to help my with this one? I am the overseas business trip so I don't have much time to dig. Can you please provide a working WiX/WixSharp code snippet that can be used to trigger the FileInUse condition. It will dramatically streamline the developing the new dialog.

Thank you.

**Comment by dviry** [comment]
I've created a Sample to reproduce this - included in the WixSamples folder - I can send you a PR if you wish.
I was trying to analyse this myself, by adding a ManagedAction to run .After the .InstallValidate step and was hoping to use session.Database.Export() or .ExportAll() to see the MSI tables but I always get an "Invalid Handle". What am I missing?

Thanks,
Leon

**Comment by oleg-shilo** [comment]
Hi Leon,

You can just attache the sample to the this thread message and I can have a look at it. 
The problem you have is due to the fact that MSI destroys the session object for all deferred actions. And After install is a deferred elevated CA.

I though initially that WixSharp runtime will need to filter MSI messages and when FileIn use is called to pop the UI dialog "files in use".

Though now I realized that it may not be so easy. Will see.

**Comment by oleg-shilo** [comment]
But the first step is to have the MSI that triggers messages associated with the FileInUse condition.

**Comment by dviry** [comment]
I've literally just created a sample:

```c#
static public void Main(string[] args)
    {
        var project =
            new ManagedProject("FilesInUse",
                new Dir(@"%ProgramFiles%\FilesInUse",
                    new Files(@"Files\MyApp.exe"))
                );

        //project.UI = WUI.WixUI_Common;
        //project.ManagedUI = ManagedUI.Default;

        Compiler.BuildMsi(project);
    }
```

MyApp.cs:
```c#
using System;
using System.Windows.Forms;

class Script
{
	[STAThread]
	static public void Main(string[] args)
	{
		MessageBox.Show("Hello World!");
	}
}
```

Build, install msi, then execute the installed %programFiles%\FilesInUse\MyApp.exe (leave it open) and run the msi again to uninstall. The default Wix FilesInUse Dialog will popup (albeit empty).

If you uncomment the two lines (to enable the ManagedUI) and follow again the steps - there will be no FilesInUse Dialog and the app will be killed and the install successfull (no questions asked ;)

Thanks

**Comment by oleg-shilo** [comment]
Thank you. 

I had my hopes that the error was happening during the installation and ManagedUI simply misses the _FileInUse_ condition. But..., it's during uninstall. Meaning, that not only WixSharp but even WiX cannot control the UI. 

 _During uninstallation MSI uses a built-in UI dialogs with no possibility for any customization._ 

An empty "FilesInUse Dialog" is really wired. It seems to be a pure native MSI UI problem.
In fact I have found some other MSI clients reporting the same behavior: https://www.advancedinstaller.com/forums/viewtopic.php?f=2&t=11857. Though in this case it was during **install** with native UI.

----

Strangely enough in my test I have consistent behavior (empty FilesInUse Dialog) regardless if native or managed UI is used. The dialog is always displayed.

From _InstallFiles_ sample:
```C#
var project =
    new ManagedProject("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
                new File(new Id("MyApp_file"), @"Files\Bin\MyApp.exe"),
            new Dir(@"Docs\Manual",
                new File(@"Files\Docs\Manual.txt")
                {
                    NeverOverwrite = true
                })),
            new Property("PropName", "<your value>"));

project.SetVersionFrom("MyApp_file");
project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");

// project.UI = WUI.WixUI_Common;
project.ManagedUI = ManagedUI.Default;

project.Language = "en-US";

project.BuildMsi();
``` 



Not really sure what can be done about it.
