### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by Andruha-008** [oleg-shilo/wixsharp#29]
Hello! I use WixSharp in visual studio 2015. When I execute "Install-Package WixSharp", automatically creates "packages" folder. I have many WixSharp projects, and all of them contain "packages" folder. This is bad for me, because the projects are stored and built on buildserver.

I'm trying to create a project without a command "Install-Package WixSharp", and manually add WixSharp.dll, WixSharp.Msi.dll, WixSharp.UI.dll into the References. When I build project, it create WixSharpSetup.exe file, but I need msi file. What I have to do to create msi file after building project without executing "Install-Package WixSharp"?
p.s.: sorry for my English

**Comment by dguder** [comment]
Hi, creating a packages folder is the base concept behind [nuget](http://www.nuget.org) and they will be created by each project/solution where nuget packages are referenced. The resulting folders size is round about 2.5 MB (without WixSharp.wix.bin). IMHO this is not too much to worry about. 

If you really want to avoid this, then you need to run the resulting exe with something like following parameter (substitute `<ProjectName>`) and a proper working directory:
`WixSharpSetup.exe "/MSBUILD:<ProjectName>"`
This is what is defined in `WixSharp.targets` file in the nuget package `WixSharp` which is installed by `Install-Package WixSharp`

The larger package is the afore mentioned `WixSharp.wix.bin` (ca. 21 MB). For this you can create an environment variable named `WIXSHARP_WIXDIR` or `WIX` to point to the folder either with `WixSharp.wix.bin` binaries or the latest official (corresponding) binaries from [wixtoolset](http://wixtoolset.org/releases/)

**Comment by Andruha-008** [comment]
thanks
