### ISSUE TITLE
Windows Service not installed after successful installation

### ISSUE THREAD

**Issue by asuricode** [oleg-shilo/wixsharp#291]
Please see this question and see if someone can help...

https://stackoverflow.com/questions/48777617/wixsharp-service-not-getting-installed

**Comment by oleg-shilo** [comment]
You will need to do some investigating work. So far the only information about the problem you have provided is "Service is not installed".

I can only suggest that you clone WixSharp repo and start with using unmodified WinService sample form the WixSharp samples: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/WinService/With_WiX.

Verify that it works in your environment. Note that the sample includes the service executable that was tested and confirmed to work.

After that start modifying the sample with your business logic. See which steps breaks the installation. Check what is created in the registry. And so on...
