### ISSUE TITLE
Failed to add a reference to "nbsbuilder"

### ISSUE THREAD

**Issue by DarthSidius** [oleg-shilo/wixsharp#297]
Visual Studio Community 2017 version 15.5.5, .Net 4.7.02556
NuGet pakage WinSharp.bin 1.6.2

Failed install pakage:
"Failed to add a reference to "nbsbuilder".
   Make sure that the file is available, and is a valid assembly or COM component."

**Comment by oleg-shilo** [comment]
Hm... Why is it trying to add the reference? `nbsbuilder` is not an assembly.
Will have a look.

**Comment by oleg-shilo** [comment]
Yes it was a mistake. The nbsbuilder executable was put in the package (upon) user request but in the wrong folder so it's treated as an assembly. The new package v1.6.2.1 with nbsbuilder in the _tools_ folder has been published. It will take ~10 mins for NuGet to index it.

**Comment by geghamyan** [comment]
Oleg, what will be a correct way to get access to "nbsbuilder.exe" in "tools" folder ?
I am using "[PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)" format, so the binaries reside in Nuget cache folder C:\Users\<username>\.nuget\packages\WixSharp.bin\1.6.2.1\tools.

**Comment by geghamyan** [comment]
How about using "content" folder for the Nuget package ? It can be placed to "content/tools" and will be copied to the "application_root"/tools folder according to the documentation:

------
content | Arbitrary files | Contents are copied to the project root. Think of the content folder as the root of the target application that ultimately consumes the package. To have the package add an image in the application's /images folder, place it in the package's content/images folder.

**Comment by oleg-shilo** [comment]
Tigran, I see your point.

"PackageReference" format hides the tool completely away. 

I also perfectly understand where you are coming from by trying to elevate the builder to the _content_ 
type so it is copied to the project folder. Though I am afraid it will unconditionally insert this file and it's folder into the project and it will be seen in the solution explorer in  this case. But I am not entirely sure.

Have you ever tried that?

**Comment by geghamyan** [comment]
No, I haven't tried it. Let me experiment and research other alternatives.

**Comment by geghamyan** [comment]
I researched different approaches and made a change, similar to what proposed as an answer here
https://stackoverflow.com/questions/10198428/nuget-where-to-place-dlls-for-unmanaged-libraries/36289251

`
<references> section is added to register only managed dlls
WixSharp.bin.targets file is added to copy unmanaged dll to the output folder
`
Oleg, please check the pull-request

**Comment by oleg-shilo** [comment]
Thank you. The PR https://github.com/oleg-shilo/wixsharp/pull/306 has been merged.
