### ISSUE TITLE
How to get your sample 'Conditional Installation' to work as a ManagedProject ?

### ISSUE THREAD

**Issue by JamesWHurst** [oleg-shilo/wixsharp#3]
Hi, I want to make my installer put a program shortcut onto the user's desktop optionally, and I see that you already provided a sample "Conditional Installation" that does this. However, my installer, built following your advice -- is a ManagedProject, not a Project. 

I copied your code from the sample:

                var project = new ManagedProject( "DesignForge Throttle",
                                                  new Dir( @"%ProgramFiles%\DesignForge\Throttle",
                                                      new Files( @"Files\Bin\*.*", f => !f.EndsWith( ".xml" ) && !f.EndsWith( ".pdb" ) ) ),
                                                  new Property( "INSTALLDESKTOPSHORTCUT", "no" ),
                                                  new ManagedAction( CustomActions.MyAction, Return.ignore, When.Before, Step.LaunchConditions, Condition.NOT_Installed, Sequence.InstallUISequence )
                                               );
...
                project.ManagedUI = new ManagedUI();

                project.ManagedUI.InstallDialogs.Add( Dialogs.Welcome )
                                                .Add( Dialogs.Licence )
                                                //.Add( Dialogs.SetupType )
                                                //.Add( Dialogs.Features )
                                                .Add( Dialogs.InstallDir )
                                                .Add( Dialogs.Progress )
                                                .Add( Dialogs.Exit );
...
and then added this ManagedAction after class Script:

    public class CustomActions
    {
        [CustomAction]
        public static ActionResult MyAction( Session session )
        {
            if (DialogResult.Yes == MessageBox.Show( "Do you want to install desktop shortcut", "Installation", MessageBoxButtons.YesNo ))
                session["INSTALLDESKTOPSHORTCUT"] = "yes";

            return ActionResult.Success;
        }
    }

But no message-box appears to ask me whether I want to install the desktop shortcut.

While on the topic of message-boxes, I also could not get your other method for launching them to work. Within this ManagedProject, I added these 3 methods:

        static void Msi_Load( SetupEventArgs e )
        {
            if (!e.IsUISupressed && !e.IsUninstalling)
                MessageBox.Show( e.ToString(), "Load" );
        }

        static void Msi_BeforeInstall( SetupEventArgs e )
        {
            if (!e.IsUISupressed && !e.IsUninstalling)
                MessageBox.Show( e.ToString(), "BeforeInstall" );
        }

        static void Msi_AfterInstall( SetupEventArgs e )
        {
            if (!e.IsUISupressed && !e.IsUninstalling)
                MessageBox.Show( e.ToString(), "AfterExecute" );
        }

and hooked them to the project events thusly:

                project.Load += Msi_Load;
                project.BeforeInstall += Msi_BeforeInstall;
                project.AfterInstall += Msi_AfterInstall;

However, again -- nothing seemed to appear. It seems that within each of those event-handlers, e.IsUISupressed is true, so the example does not work.  Is there another way to tell when this installer is being run as a silent process with no user-interaction?

Thank you oleg

James Hurst
[Setup.txt](https://github.com/oleg-shilo/wixsharp/files/644195/Setup.txt)

**Comment by oleg-shilo** [comment]
It's good you attached setup.txt. I will have a look at it. 

MyAction is not called because it is scheduled for InstallUIAction and this sequence is no longer invoked as you are using an EmbeddedUI. But it is actually goo because you can simply place a check box in the appropriate dialog and this would be even a better user experience than message box "Do you want to ...." 

`Msi_BeforeInstall` is a valid alternative to the `MyAction` if you still want to popup the message box. It should work. I will go through your sample tomorrow.

**Comment by oleg-shilo** [comment]
There are a few things that were done a wrong way in your test. One of them is relying on `IsUISupressed`. This property simply returns `UILevel <= 4`. MSI does not treat EmbeddedUI as "true UI" and reports its as "suppressed UI".

Another one was trying to install shortcut to Desktop with `FileShortcut`. While it may work such a shortcut cannot be a subject to a condition. Thus it has to be a ExeFileShortcut. And you also need to "install" the Desktop folder so the shortcut can be associated with it in the wxs definition. I know it's plain ugly. But... this is the MSI architecture for you. :(

Another thing is that when you use MSI support for EmbeddedUI (ManagedUI) suppresses UI sequence and some of the events will be jammed (e.g. `Load`). That' is why if you use ManagedUI you need to hook to `UILoaded` event.

Anyway, I have attached the adjusted version of your setup.txt that works as intended.


 


[setup.cs.txt](https://github.com/oleg-shilo/wixsharp/files/647913/setup.cs.txt)
