### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by Andruha-008** [oleg-shilo/wixsharp#30]
hello!
How can I set feature state to enabled (or disabled) from Msi_Load (or Msi_BeforeInstall) function?

**Comment by manytwo** [comment]
Just use the standard Msi property [ADDLOCAL ](https://msdn.microsoft.com/fr-fr/library/windows/desktop/aa367536(v=vs.85).aspx).

You must set it during project.Load event, project.BeforeInstall step is too late.

```CS
static void project_Load(SetupEventArgs e)
{
    e.Session["ADDLOCAL"] = "Feature1,Feature3";
}
```
During install you just need to set added properties and other are disabled .
During Modify , you can use REMOVE property on same way.

**Comment by Andruha-008** [comment]
thanks
