### ISSUE TITLE
Embedded UI is always run as x86

### ISSUE THREAD

**Issue by dhilgarth** [oleg-shilo/wixsharp#300]
My installer is configured for x64 via `project.Platform = Platform.x64`.  
I have created the installed project from the "WixSharp Managed Setup - Custom UI" project template.
The code that runs in my custom form is being executed in a x86 process. This is problematic because I am accessing the registry to check if certain keys exist. My check now accesses the x86 view of the registry while the actual installation will access the x64 view.

**Comment by oleg-shilo** [comment]
MSI/WiX do not offer any mechanism for controlling hosting CPU type. [`EmbeddedUI`](http://wixtoolset.org/documentation/manual/v3/xsd/wix/embeddeduiresource.html) WiX element only has SourceFile attribute and that's it. Thus MSI runtime decided what CLR to use.

Setting `project.Platform = Platform.x64` has nothing to do with EmbededdUI. It only controls destination folders and CA runtime CPU type.

Thus your best chance is to use ManagedSetup events or ManagedCustomActions. They are executed in the expected CPU context.

**Comment by dhilgarth** [comment]
That's a pity. I have now solved it by explicitly specifying the registry view to use (based on https://stackoverflow.com/questions/26217199/what-are-some-alternatives-to-registrykey-openbasekey-in-net-3-5/28866237)
