### ISSUE TITLE
Privileges for simple msi

### ISSUE THREAD

**Issue by nisbus** [oleg-shilo/wixsharp#302]
Hello,

I've created a simple msi builder using Wix# but my users are unable to install because they get an error stating that they don't have sufficient privileges and need to run as administrator.
The program is installed into Program Files (x86) but even as local administrators they get this prompt.

If they open a cmd as admin they can run the installer but that is rather lame for an msi.

What settings am I missing?

Here is the script:

`
public static class Script
    {
        static string baseDir = "..\\..\\..\\{PRODUCT}\\Bin\\Release\\";
        static string _ExeName = "{PRODUCT}.exe";
        static public void Main(string[] args)
        {
            if (args.Length == 1)
                baseDir = args[0];
            var allFiles = baseDir + "*.*";
            var installDir = new Dir(@"%ProgramFiles%\\{Company}\\{PRODUCT}\\",
                 new DirFiles(baseDir + "*.*"),
                 new Dir(@"locales",
                 new DirFiles(baseDir + @"locales\\*.pak")),
                 new Dir("x86",
                 new DirFiles(baseDir + @"x86\\*.dll"))); 

            var exePath = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
            var combined = Path.Combine(new string[] { exePath, baseDir });

            var project = new Project("{PRODUCT}", installDir)
            {
                Version = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version,
                GUID = new Guid(),
                Description = "{PRODUCT}",
                InstallScope = InstallScope.perUser,
                UpgradeCode = new Guid("{GUID}")
            };
            project.UI = WUI.WixUI_ProgressOnly;            

            project.ResolveWildCards();
            project.Version = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version;
            project.ControlPanelInfo = new ProductInfo
            {
                Manufacturer = "{COMPANY}",
                ProductIcon = "..\\..\\..\\{PRODUCT}\\Images\\{PRODUCT}.ico",
                InstallLocation = @"%ProgramFiles%\\{COMPANY}\\{PRODUCT}\\"                
            };
            var exeFile = project.AllFiles.FirstOrDefault(f => f.Name.EndsWith(_ExeName));
            if (exeFile != null)
            {
                exeFile.Shortcuts = new[]
                {
                    new FileShortcut("{PRODUCT}", @"%Desktop%"),

                    new FileShortcut("{PRODUCT}", "%ProgramMenu%\\{COMPANY}")
                };
            }
            Compiler.BuildMsi(project);
        }
    }
`

**Comment by oleg-shilo** [comment]
Nothing obviously wrong...
Try and see if the standard code sample (e.g. [InstallFiles](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Install%20Files)) triggers UAC on your system. It supposed to.

**Comment by CADbloke** [comment]
The problem is `InstallScope = InstallScope.perUser,` - the MSI does not run as elevated. You cannot force it to with `project.InstallPrivileges = InstallPrivileges.elevated;`

> The Package/@InstallScope attribute's value, 'perUser', is not compatible with attribute @InstallPrivileges's value, 'elevated'. It is recommended that only the InstallScope attribute be used.
