### ISSUE TITLE
Windows Firewall Exception for Port and executable

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#309]
Hi Oleg, 
i have some question. In Sample of Windows Firewall Exception is very good sample for create firewall exception. Works fine. 
But i have some difficulty to check if exception already exists for port.
Background: i have multiple programms which are use same sql server with ports 1433 TCP and 1434 UDP and if i install my application an set those ports during installation , i have problem with uninstall my application. 
MSI uninstall my application and remove all those port for sql server.  How can i do not touch those ports, but still uninstall my application ? Is there some posibility to control this behavior ?

**Comment by oleg-shilo** [comment]
> But i have some difficulty to check if exception already exists for port.

You may be able to do that with `Conditions`. Though I am not sure if any of WiX utilities have predefined action to do the port checking. A possible solution would be to check the firewall/registry and set the `Condition` from a managed action or even handler.

> How can i do not touch those ports, but still uninstall my application?

You can do this by adding with RefValues and Files by setting `Permanent` attribute of their component:
```C#
new RegValue(...)
{ AttributesDefinition = "Component:Permanent=yes" }
```
You will need to try the same approach for `FirewallException`.

**Comment by oleg-shilo** [comment]
You can also set the attribute this way:
```C#
new RegValue(...).SetComponentPermanent(true)
```

**Comment by Torchok19081986** [comment]
Thanks Oleg. I will try you suggestion and give feedback.

**Comment by oleg-shilo** [comment]
👍
