### ISSUE TITLE
Create Taskscheduler Task 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#310]
Hi, is there posibility to crate a Task in Taskscheduler during installation ? Username, password, Tasktime etc are exists. But i cant add new task in Taskscheduler.
I already tried schetasks.exe with paramters and taskservice from Microsoft.Win32.TaskScheduler.dll. 
It appears always UAC. How do i set my Project with InstallPriviliges = 'elevated' or something like this ? 
I create my msi with this requirement at first time. I really need some help here or answer this cant be create during installation in msi.
Thanks for Help anyway.

**Comment by oleg-shilo** [comment]
You can use `ElevatedCustomAction`. It seems to be a good candidate. 

```c#
var project =
    new Project("My Product",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File(@"..\SimpleService\MyApp.exe")),
        new ElevatedManagedAction(CustomActions.InstallService, Return.check, When.After, Step.InstallFiles, Condition.NOT_Installed),
        new ElevatedManagedAction(CustomActions.UnInstallService, Return.check, When.Before, Step.RemoveFiles, Condition.BeingRemoved));
...
public class CustomActions
{
    [CustomAction]
    public static ActionResult InstallService(Session session)
    {
        return session.HandleErrors(() =>
        {
            // do your stuff 
        });
    }
}

```

Though my favorite is AfterInstallEevnt, which is always elevated:

**Comment by Torchok19081986** [comment]
Ok, thanks again. I will try it, but im prety sure, your suggestion works fine.
