### ISSUE TITLE
To add VC++ dependency in Bundle.

### ISSUE THREAD

**Issue by JunaidAK** [oleg-shilo/wixsharp#311]
How to detect if client has VC++ installed or not and install it accordingly from a url.

**Comment by Lechl** [comment]
Not directly the answer, but maybe this can help solve the problem if you need the VC++ only for your application.

Just add the VC++ library files (i think those are three dll files) to your project and let wix copy it to the application startup path. 
So you always have the VC++ files in your project - you dont need to check for install then.

**Comment by JunaidAK** [comment]
Thanks. But I want it to be installed in the system, the same way .net framework is installed (using PackageRef).

**Comment by oleg-shilo** [comment]
You can use Bundle (see https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/WixBootstrapper/setup.cs).

You don't even need to have a condition, just install it always. If it is already present boostratpper will just skip the CRT-install step.

**Comment by oleg-shilo** [comment]
> for bundling .net framework, not VC Redis

Not exactly. The example shows how to build and bundle the main product msi and its dependency CRT. 
![image](https://user-images.githubusercontent.com/16729806/189133023-9c56ad01-1cc5-48e6-9ef5-1f2eaaa16cb8.png)

In the user sample code there is nothing specific about the distribution of .NET.

Though the sample is just an example and it is expected that the users will replace the main product and its dependency with their real binaries.
