### ISSUE TITLE
How to localize controls text in WPF embedded UI

### ISSUE THREAD

**Issue by marcobeninca71** [oleg-shilo/wixsharp#314]
Hi all
I'm developing a installation package starting from the EmbeddedUI_WPF. I'd like to localize the strings showed inside the controls of the wpf window (like the text of a button). Usually in Wpf you can use the resources file specific for the language and then write something like the follow:

string text = Properties.Resources.someNameOfAStringIntoTheResources;

The specific resource file is inside a folder (for example for French)

.\<application_folder>\fr-FR\<application_name>.resources.dll

But I think this file is not available at run time. I had a look inside the temporary installation folder and it's not included.

How can I access the localized resources during the run time?

thanks

**Comment by oleg-shilo** [comment]
You will need to include your resource the setup as a binary asset:
```C#
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
        ...
            new Binary(new Id("my_res"), @"fr-FR\<app_name>.resources.dll"),
```
Then you would need to access the file at your GUI startup (see #313). After that you can just dynamically load the resource from the file (or byte array) and read the required resource item one by one.

Just having the files present in the specific WPF-friendly locations may not be enough. Though I have never tried.
