### ISSUE TITLE
Binding UI Element to Propery in Project

### ISSUE THREAD

**Issue by billybobpersonal** [oleg-shilo/wixsharp#317]
Good day

I have been using Wix# and I'm very impressed, thanks for all the hard work getting it where it is.

I have been trying to achieve something and have looked at all the examples but without success.

I am trying to create a custom dialog via the Visual Studio Template. On the Custom Dialog I have a Lookup and 2 text box fields. I am trying to get the ManagedProject to use the values selected but for some reason it always just uses the Default Values assigned to it. 
I created session variables and then assign the values input from the dialog to them but when I try to access the Session variables in the Project then the values are just the default values that were assigned to them when the project initialized. 

I am certain that I am missing something(that is probably simple) and have tried quite a few possible ways to do it using the samples, without success.

Your help will be greatly appreciated.

P.S I have attached the visual studio project for you to look at.

[EquipsmeWebsite.zip](https://github.com/oleg-shilo/wixsharp/files/1818964/EquipsmeWebsite.zip)

**Comment by oleg-shilo** [comment]
I had a look at your project and could not see anything obviously wrong. At least for the first look.

I just modified the 'CustomUIDialog' [sample](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUIDialog) to display the user input (password) from the `BeforeInstall` event. 

```C#
static void msi_BeforeInstall(SetupEventArgs e)
{
    MessageBox.Show(e.Session.Property("PASSWORD"), "msi_BeforeInstall");
    ...
```
This is similar to what you have in in your project. In this case it all seems to work. If you compare these two solutions most likely you will find the cause of that problem.
