### ISSUE TITLE
Add Remove icon

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#319]
I can set the add remove icon in Wix Installer. How do I do it using Wix sharp?

**Comment by oleg-shilo** [comment]
Can you elaborate? What exactly do you mean by "set the add remove icon"?

The most common deployment scenarios can be found in the samples folder of the distro. [AllInOne](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/AllInOne) sample is a good starting point.

**Comment by ltemimi** [comment]
Hi Oleg
Many thanks for getting back to me when I used to use Wix I could point it to an icon to use for add-remove. This icon then appears in control panel instead of the normal windows icon. I think it was something like <Id ="ADDREMOVE.ICO Path> This icon is different from the one I am able to set using project.ManagedUI.ico = "path to bmp"
There is no property in wix # to set the add-remove icon that would appear in control panel.
By the way I believe wix# is awsome. how do you configure it to check for a version of dot net framework and download it if not installed in the user machine.
I will be great to have a book written about wix #
Thanks
Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Sunday, 18 March 2018, 11:09, Oleg Shilo <notifications@github.com> wrote:
 

 Can you elaborate? What exactly do you mean by "set the add remove icon"?The most common deployment scenarios can be found in the samples folder of the distro. AllInOne sample is a good starting point.—

**Comment by oleg-shilo** [comment]
Hi Laz,

OK, I understand now. :)

You will need to use `ControlPanelInfo` object for that. Have a look at "ProductInfo" sample:
```C#
project.ControlPanelInfo.ProductIcon = "app_icon.ico";
```


>  how do you configure it to check for a version of dot net framework and download it if not installed in the user machine.

You may want to use bootstrapper for that. See "Samples\Bootstrapper" folder for the samples. 

The task of installing a dependency package from the MSI setup is impossible because of the MSI installation atomic nature. Thus it has to be done from an external application that chains multiple packages together - Bootstrapper. WixSharp provides the interface to WiX Bundle bootstrapper solution.   

You can find the Wiki article on the matter here: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#burn-bootstrapper

**Comment by ltemimi** [comment]
Thanks very much Oleg I really appreciate the help
Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Sunday, 18 March 2018, 12:03, Oleg Shilo <notifications@github.com> wrote:
 

 Hi Laz,OK, I understand now. :)You will need to use ControlPanelInfo object for that. Have a look at "ProductInfo" sample:project.ControlPanelInfo.ProductIcon = "app_icon.ico";
how do you configure it to check for a version of dot net framework and download it if not installed in the user machine.
You may want to use bootstrapper for that. See "Samples\Bootstrapper" folder for the samples.The task of installing a dependency package from the MSI setup is impossible because of the MSI installation atomic nature. Thus it has to be done from an external application that chains multiple packages together - Bootstrapper. WixSharp provides the interface to WiX Bundle bootstrapper solution.You can find the Wiki article on the matter here: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#burn-bootstrapper—

**Comment by ltemimi** [comment]
Hi Oleg
I have a project that has worked perfectly well and now when I build


Any idea?
I appreciate your time
Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Sunday, 18 March 2018, 12:03, Oleg Shilo <notifications@github.com> wrote:
 

 Hi Laz,OK, I understand now. :)You will need to use ControlPanelInfo object for that. Have a look at "ProductInfo" sample:project.ControlPanelInfo.ProductIcon = "app_icon.ico";
how do you configure it to check for a version of dot net framework and download it if not installed in the user machine.
You may want to use bootstrapper for that. See "Samples\Bootstrapper" folder for the samples.The task of installing a dependency package from the MSI setup is impossible because of the MSI installation atomic nature. Thus it has to be done from an external application that chains multiple packages together - Bootstrapper. WixSharp provides the interface to WiX Bundle bootstrapper solution.You can find the Wiki article on the matter here: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#burn-bootstrapper—
