### ISSUE TITLE
How do I make a Wissharp MSI always remove a previous version?

### ISSUE THREAD

**Issue by skroche** [oleg-shilo/wixsharp#32]
I am looking for a solution where the MSI always uninstalls the previous version and installs a new one, irrespective a of an upgrade.(without showing the dialogue which says -- "Another version of this product is already installed. Installation of this version cannot continue. 
To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel. ") I found the link to solve this using Wix (http://stackoverflow.com/questions/11732290/how-do-i-make-a-wix-msi-always-remove-a-previous-version).

I am looking for doing the same using Wix#. I am not sure how to generate a new GUID each time the program is built and MSi is generated. Is there a way that this could be done? please help me with this.

**Comment by oleg-shilo** [comment]
I cannot comment on the quality of that work around. If it works for you, then go for it,

Bu as for the GUID generation you can do this as below:
```C#
project.ProductId = Guid.NewGuid();
project.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
```
