### ISSUE TITLE
Bootstrap update not always replacing existing install

### ISSUE THREAD

**Issue by steronydh** [oleg-shilo/wixsharp#321]
When I update a bootstrap install with a new version number, I usually (but not always) get a second entry in the "apps and features" list in Windows 10. I expect to see a single entry with the new version.

If I watch the installer, the new version appears in the list before the old one disappears, as though the new installer upgrades each of the embedded MSI installs one at a time before updating the entry in "apps and features". The older version doesn't always disappear, leaving me with an orphaned entry that is a problem to get rid of.

Is there a recommended way to set up a bootstrapper project in order to get it to upgrade reliably?

**Comment by Lechl** [comment]
Looks like a missing (or always autogenerated) UpgradeCode, which must be the same for every version.

**Comment by steronydh** [comment]
@Lechl According to the comments on UpgradeCode, if UpgradeCode isn't specified then the GUID is used instead, so it should be constant.

I've decided to combine all of my sub-projects into a single MSI install and am not using a bootstrapper any more so this is no longer a problem.

**Comment by oleg-shilo** [comment]
You can always verify the upgrade code either during the build. It's printed in the compiler output:

![image](https://user-images.githubusercontent.com/16729806/37704111-062fe018-2d4c-11e8-95b3-316184fd4aef.png)


Or by opening MSI in Orca:

![image](https://user-images.githubusercontent.com/16729806/37704068-da8384e2-2d4b-11e8-9934-bf88d3321aaa.png)

**Comment by steronydh** [comment]
I'm seeing an Upgrade code in the output that is different from the GUID, but I'm also seeing this popup which says that the GUID will be used if the UpgradeCode isn't specified:

![image](https://user-images.githubusercontent.com/4245329/37705077-b8c9d67a-2cf2-11e8-8dd9-5ba4a5360b13.png)

**Comment by oleg-shilo** [comment]
> that is different from the GUID

It's supposed to be different. GUID is a seed for generating the actual UpgradeCode . What must be the same is the UpgradeCode in both MSIs (the original and the upgrade one)

**Comment by steronydh** [comment]
I see, thanks for the clarification.

**Comment by oleg-shilo** [comment]
But of course if you want to avoid any ambiguity You can just set the UpgradeCode  explicitly.
