### ISSUE TITLE
Service tried to start before config file is updated

### ISSUE THREAD

**Issue by RTyrer** [oleg-shilo/wixsharp#325]
Hi I'm trying to install a service.  It is reliant on a value in a config file.
Here is the code for the service:

            ServiceInstaller si = new ServiceInstaller();
            si.Type = SvcType.ownProcess;
            si.Vital = true;
            si.Name = "MyService";
            si.DisplayName = "My Company Service";
            si.Description = "Custom service to control the world";
            si.StartType = SvcStartType.auto;
            si.Account = "LocalSystem";
            si.ErrorControl = SvcErrorControl.ignore;
            si.Interactive = false;
            si.StartOn = SvcEvent.Install;
            si.StopOn = SvcEvent.InstallUninstall_Wait;
            si.RemoveOn = SvcEvent.Uninstall_Wait;

            file.ServiceInstaller = si;  //file variable is MyService.exe

I can successfully update the configuration values through the following customer action:

               ManagedAction action = new ManagedAction(CustomActions.ApplyConfigurationServiceSettings);
                action.Return = Return.check;
                action.When = When.After;
                action.Step = Step.InstallFinalize;
                action.Condition = Condition.NOT_BeingRemoved;

But this only works until I add the Service Installer.  Problem is the Service Installer is attempting to Start the service before the Apply Configuration Service Settings is ran.

What would be the best way to have the custom action execute before the Service Installer attempts to start the service?

I've tried to get around this by adding a util:XmlFile to the config file instead of a custom action.  Here is the output:

<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" 
	 xmlns:iis="http://schemas.microsoft.com/wix/IIsExtension" 
     xmlns:sql="http://schemas.microsoft.com/wix/SqlExtension" 
     xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Product Id="removed" Name="Company.Division.Product.Service" Language="1033" Codepage="Windows-1252" Version="18.1.0.263" UpgradeCode="removed" Manufacturer="superman">
    <Package InstallerVersion="200" Compressed="yes" SummaryCodepage="Windows-1252" Languages="1033" />
    <Media Id="1" Cabinet="_...any.Division.Product.Service.cab" EmbedCab="yes" />

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
        <Directory Id="ProgramFilesFolder._1_A_Company" Name="1 A Company">
          <Directory Id="ProgramFilesFolder._1_A_Company.CUSTOM" Name="CUSTOM">
            <Directory Id="INSTALLDIR" Name="Product">

              <Component Id="Component.Microsoft.Practices.EnterpriseLibrary.Common.dll_766019613" Guid="1052dc2d-038c-40a9-9768-90f5bfb22ba3">
                <File Id="Microsoft.Practices.EnterpriseLibrary.Common.dll_766019613" Source="..\..\..\CUSTOM\Product\Company.Division.Product.Service\bin\Debug\Microsoft.Practices.EnterpriseLibrary.Common.dll" />
              </Component>

              <Component Id="Component.Microsoft.Practices.EnterpriseLibrary.Data.dll_935643614" Guid="1052dc2d-038c-40a9-9768-90f52e4cc20f">
                <File Id="Microsoft.Practices.EnterpriseLibrary.Data.dll_935643614" Source="..\..\..\CUSTOM\Product\Company.Division.Product.Service\bin\Debug\Microsoft.Practices.EnterpriseLibrary.Data.dll" />
              </Component>

              <Component Id="Component.Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.dll_1215679349" Guid="1052dc2d-038c-40a9-9768-90f5ff7d8d88">
                <File Id="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.dll_1215679349" Source="..\..\..\CUSTOM\Product\Company.Division.Product.Service\bin\Debug\Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.dll" />
              </Component>

              <Component Id="Component.Company.Division.Product.Service.exe_532574124" Guid="1052dc2d-038c-40a9-9768-90f5b4cf34db">
                <File Id="Company.Division.Product.Service.exe_532574124" Source="..\..\..\Custom\Product\Company.Division.Product.Service\bin\Debug\Company.Division.Product.Service.exe" />
              </Component>
			  
              <Component Id="Component.Company.Division.Product.Service.exe.config_308516668" Guid="1052dc2d-038c-40a9-9768-90f5ca355fcf">
                <File Id="Company.Division.Product.Service.exe.config_308516668" Source="..\..\..\CUSTOM\Product\Company.Division.Product.Service\bin\Debug\Company.Division.Product.Service.exe.config">
                  <util:XmlFile Id="XmlFile" Action="setValue" ElementPath="//configuration/appSettings/add[\[]@key='VALUE1'[\]]/@value" Value="[VALUE1]" File="[#Company.Division.Product.Service.exe.config_308516668]" />
                  <util:XmlFile Id="XmlFile.1" Action="setValue" ElementPath="//configuration/appSettings/add[\[]@key='VALUE2'[\]]/@value" Value="[VALUE2]" File="[#Company.Division.Product.Service.exe.config_308516668]" />
                  <util:XmlFile Id="XmlFile.2" Action="setValue" ElementPath="//configuration/appSettings/add[\[]@key='VALUE3'[\]]/@value" Value="[VALUE3]" File="[#Company.Division.Product.Service.exe.config_308516668]" />
                </File>
              </Component>

              <Component Id="Component.Newtonsoft.Json.dll_820300908" Guid="1052dc2d-038c-40a9-9768-90f5935d5da8">
                <File Id="Newtonsoft.Json.dll_820300908" Source="..\..\..\CUSTOM\Product\Company.Division.Product.Service\bin\Debug\Newtonsoft.Json.dll" />
              </Component>

              <Component Id="Component.System.Net.Http.Formatting.dll_785127317" Guid="1052dc2d-038c-40a9-9768-90f59877113f">
                <File Id="System.Net.Http.Formatting.dll_785127317" Source="..\..\..\CUSTOM\Product\Company.Division.Product.Service\bin\Debug\System.Net.Http.Formatting.dll" />
              </Component>

            </Directory>
          </Directory>
        </Directory>
      </Directory>
    </Directory>

    <UI />

    <Upgrade Id="1052dc2d-038c-40a9-9768-90f5d6cd1627">
      <UpgradeVersion Minimum="0.0.0.0" Maximum="18.1.0.263" IncludeMinimum="yes" IncludeMaximum="no" Property="UPGRADEFOUND" />
      <UpgradeVersion Minimum="18.1.0.263" IncludeMinimum="no" OnlyDetect="no" Property="NEWPRODUCTFOUND" />
    </Upgrade>

    <CustomAction Id="_...etConfigurationServiceSettings" BinaryKey="GetConfigurationServiceSettings_File" DllEntry="GetConfigurationServiceSettings" Return="check" Execute="immediate" />
    <CustomAction Id="PreventDowngrading" Error="Newer version already installed" />

    <Binary Id="GetConfigurationServiceSettings_File" SourceFile="..\..\..\Install\%this%.CA.dll" />

    <UIRef Id="WixUI_Minimal" />
    <UIRef Id="WixUI_ErrorProgressText" />

    <Feature Id="Complete" Title="Complete" Absent="allow" Level="1">
      <ComponentRef Id="Component.Microsoft.Practices.EnterpriseLibrary.Common.dll_766019613" />
      <ComponentRef Id="Component.Microsoft.Practices.EnterpriseLibrary.Data.dll_935643614" />
      <ComponentRef Id="Component.Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.dll_1215679349" />
      <ComponentRef Id="Component.Company.Division.Product.Service.exe_532574124" />
      <ComponentRef Id="Component.Company.Division.Product.Service.exe.config_308516668" />
      <ComponentRef Id="Component.Newtonsoft.Json.dll_820300908" />
      <ComponentRef Id="Component.System.Net.Http.Formatting.dll_785127317" />
    </Feature>

    <InstallExecuteSequence>
      <Custom Action="_...etConfigurationServiceSettings" Before="InstallFiles"> (NOT (REMOVE="ALL")) </Custom>
      <Custom Action="PreventDowngrading" After="FindRelatedProducts">NEWPRODUCTFOUND</Custom>

      <RemoveExistingProducts After="InstallFinalize" />
    </InstallExecuteSequence>

    <InstallUISequence>
      <Custom Action="PreventDowngrading" After="FindRelatedProducts">NEWPRODUCTFOUND</Custom>
    </InstallUISequence>

  </Product>
</Wix>

Unfortunately, this generates error CNDL0005 : The File element contains an unexpected child element 'util:XmlFile'.

Any advise on how to resolve the issue would be appreciated.

Thanks,

Scott

**Comment by Xaddan** [comment]
ManagedAction action = new ManagedAction(CustomActions.ApplyConfigurationServiceSettings);
  action.Return = Return.check;
  action.When = When.Before;
  action.Step = Step.StartServices;
 action.Condition = Condition.NOT_BeingRemoved;
