### ISSUE TITLE
Error 1406 in Update

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#326]
Hallo Oleg, i need some info or help. I got always Error 1406 after update. Update should write Regvalue with new values. Msi Installer says: "... Verify that you have sufficient acess to that key...". I excute msi package with update as Adminstrator. How do i set Regvalue Permissions for my regvalue keys ? In my application this looks like ... new Regvalue (RegistryHive.LocalMachine, @"SOFTWARE\mycomapnay\myproduct\Updates", "Needupdate", "0"). Thanks for Help .

**Comment by oleg-shilo** [comment]
You can try and see if the registry key in question can be accessed from the elevated custom action (or _after install_ event). This will give you a clue about the nature of the access problem.
 
Of course writing to registry is the best done with `RegValue` class and I am only suggesting the custom action as a troubleshooting step.

**Comment by Torchok19081986** [comment]
I going to try your suggestion. Am i right, if i would say i should be new ElevatedManagemntAction ? 
Thanks.

**Comment by oleg-shilo** [comment]
Yes you are right. You can also use `project.AfterInstall += ...` event, which is also elevated.

**Comment by Torchok19081986** [comment]
Thanks. If i do understand right, that i need something like custom or elevatedcustomaction in after install. But if set ManagedAction in Step.Afterfinalize , i always get error, that custom action should be between install and finalize. Which Step are correct for this kind of CustomAction ? Thanks for Help.

**Comment by oleg-shilo** [comment]
`project.AfterInstall += ...` is the best candidate. It is an elevated  deferred custom action. Though you don't need to specify step or any other custom attributes for it. It's all already done for you. You only need to supply your routine (the event handler).
