### ISSUE TITLE
installation in different folders

### ISSUE THREAD

**Issue by Andruha-008** [oleg-shilo/wixsharp#33]
Hello!
I try to install exe-files in "c:\MyPrograms", and ini-files in "d:\MyData".
I do it like this:
            string productName = "MyProduct";            
            string installDir = @"c:\MyPrograms\" + productName;  
            string installDataDir = @"d:\MyData\" + productName;
            var project = new ManagedProject(productName, 
                             new Dir(new Id("program"), installDir, 
                                 new Dir(set1, "Set1", new Files(set1, filesToInstall_set1)),
                                 new Dir(set2, "Set2", new Files(set2, filesToInstall_set2))),    
                             new Dir(new Id("data"), installDataDir, new Files(dataFilesToInstall))
                                 );

but there is a compilation error:
 error LGHT0091: Duplicate symbol 'CustomAction:Set_INSTALLDIR_AbsolutePath' found. This typically means that an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.

How can I install files on 2 different drives?

**Comment by oleg-shilo** [comment]
The "good setup" practices discourage deployment to non "well-known" locations (e.g. absolute path). And Wix# is following the same approach. It is build mainly for the use-cases when you install in "ProgramFiles". Saying that Wix# allows installing to an absolute path destination - `InstallDir_AbsolutePath` sample. 

However installing to multiple absolute dirs from a single setup amy not be  directly supported. I have never tried. For such an exotic you will need to understand how to do it in raw WiX. Analysing intermediate *.g.wxs of `InstallDir_AbsolutePath` would be one of the possible investigation technique.

When you understand how to do this then you can either:
* Find the way to do it with Wix# only
* Use Wix# and manipulate XML in the `XmlGenerated` 
* Use Wix# and import WXS `fragment`.

However the best solution would be to review your deployment strategy and avoid using absolute path destinations.

**Comment by Andruha-008** [comment]
Thanks
