### ISSUE TITLE
Best way to run vcredist in Wix# with embedded UI

### ISSUE THREAD

**Issue by marcobeninca71** [oleg-shilo/wixsharp#331]
Dear Oleg
I developed an installer based on the Embedded_UI example.
Everything runs well but now I need to integrate the vcredist installation into mine.
I tried to add a custom action on AfterInstall event of the ManagedProject class to run manually the vcredist.exe package which is part of my installation. But I got the error from vcredist package that another installation is in progress.
Which is the best way to integrate the vcredist installation into a Wix# project?
Thanks

**Comment by marcobeninca71** [comment]
Dear Oleg
thanks for your reply... I've changed my mind and decided to use the msm packages from Microsoft to merge them with my installation module. I think it should be possible using the **_Merge_** class in WixSharp.

**Comment by oleg-shilo** [comment]
Fair enough. 

Juts keep in mind that Merge Modules are even more conservative approach than MSI itself. Even MS completely ditch them in all MS current products. E.G. Visual Studio and Office are using bootstrappers only to manage packages installations.

Saying that, it does not mean that msm may not work just fine on the case by case base.

**Comment by CADbloke** [comment]
VS2019 has no MSM modules for VCredist things. See https://github.com/MicrosoftDocs/cpp-docs/issues/2248

**Comment by shengxue** [comment]
@CADbloke   I tried this solution, but I got error message "Another Installation is already in Progress. Complete that installation before preceding with this installation" 

![image](https://user-images.githubusercontent.com/6092790/189114045-6c732211-a5db-4098-aa99-481c0df86985.png)

**Comment by shengxue** [comment]
@CADbloke  is it possible to know from ```SetupEventArgs ``` that if the setup.msi is running in silent mode?

``` csharp
project.AfterInstall += Project_AfterInstall;
...
private static void Project_AfterInstall(SetupEventArgs e)
{
    if (e.IsInstalling)
        Process.Start(e.InstallDir.PathCombine("crt_launcher.exe"));
    ...
```

**Comment by CADbloke** [comment]
@shengxue Dunno. Maybe @oleg-shilo knows?

**Comment by oleg-shilo** [comment]
Yes it is possible:
```C#
if (args.UILevel ....
```

**Comment by CADbloke** [comment]
Because the ONLY place I could find it is https://community.chocolatey.org/packages/vcredist140#versionhistory - the minimum version for VS2022 (VC17) is "14.30".  I'll post it here so I can find it later.
