### ISSUE TITLE
SaveBinary crashes

### ISSUE THREAD

**Issue by Savvkin** [oleg-shilo/wixsharp#332]
Hello. I'm using 1.6.3.3 version from NuGet.

I've noticed that my custom ManagedUI form didn't work correctly if it is loaded more than one time (For example, user clicked prev, then next again). It crashes at MsiRuntime.Session.SaveBinary that is called during the form load.

Then I just tried to call SaveBinary two times in the row with the same arguments and confirmed, that first time it works and the second time it crashes.

**Comment by oleg-shilo** [comment]
OK, this one is indeed an interesting one.

Apparently WiX has a bug as it fails to retrieve a stream from the view of the 'Binary' table more than once. 

This is what SaveBinary does:
```C#
using (var sql = session.Database.OpenView("select Data from Binary where Name = '" + binary + "'"))
{
    sql.Execute();

    System.IO.Stream stream = sql.Fetch().GetStream(1);

    using (var fs = new System.IO.FileStream(file, System.IO.FileMode.Create))
    {
        int Length = 256;
        var buffer = new Byte[Length];
        int bytesRead = stream.Read(buffer, 0, Length);
        while (bytesRead > 0)
        {
            fs.Write(buffer, 0, bytesRead);
            bytesRead = stream.Read(buffer, 0, Length);
        }
    }
}
```
As you can see there is no a single WixSharp stuff there. Thus I suggest you cache the stream object (e.g. in static var of the dialog) as a work around. Not an elegant one but it will work. The alternative is to wait for WiX to fix it.

------------

I did intensive experimenting and it seems that the bug affects only `Binary` table but no others.

The following simple test case always have `stream1` object properly initialized and `stream2` object is always `null`:
```C#
using (View sql = session.Database.OpenView("select Data from Binary"))
{
    sql.Execute();
    var record = sql.Fetch();
    var stream1 = record.GetStream(1);
}

using (View sql = session.Database.OpenView("select Data from Binary"))
{
    sql.Execute();
    var record = sql.Fetch();
    var stream2 = record.GetStream(1);
}
```
Not disposing the views makes no difference . Unfortunately.
 
You can try to log this bug with the test-case on WiX GitHub but I have little no hope for a prompt response. There is one issue that is a real show stopper - wixtoolset/issues#4921. And... it's pending for 3 years... :o(

But still, letting them know probably a good idea.
