### ISSUE TITLE
FeaturesDialog drawing issues

### ISSUE THREAD

**Issue by Savvkin** [oleg-shilo/wixsharp#333]
Hello. I'm on 1.6.3.3 version from NuGet and has some issues with FeaturesDialog form:

1. Long node names with spaces are cut (wrapped to the 2nd line) when run on the Windows 7 without visual styles. Solved by using same approach in the treeView_DrawNodeText as in treeeView_DrawNode (MeasureString().Width+2 and drawFormat instead of bounds.Width+5)

2. When I add multiple expanded features with children, scroll position is not at the top of the tree. Solved by adding featuresTree.Nodes[0].EnsureVisible() to the end of ResetLayout() method of FeaturesDialog form.

**Comment by oleg-shilo** [comment]
Done. Can you please review the changes (https://github.com/oleg-shilo/wixsharp/commit/04ecfc75402f10b2bece5813a6e0664416202d86) to verify that your description is processed correctly.

Thank you,
Oleg
