### ISSUE TITLE
Condition for ServiceInstaller.

### ISSUE THREAD

**Issue by jakubpietka** [oleg-shilo/wixsharp#335]
Hi, i'm building MSI and I'm settings ServiceInstaller property for my exe File. The problem is that I want to not install these services if they are already installed while upgrading application. I want to install services only if application installing for the first time, when upgrading, only stop this service and start after app installed. How can I achieve this?

Thanks.

**Comment by oleg-shilo** [comment]
You can make an installation a subject of a condition based on custom property. You can set this property from one of the project Events. Have a look at "Setup Events" sample.
```C#
static void project_Load(SetupEventArgs e)
{
    if (e.IsInstalling && !e.IsUpgrading)
        e.Session["install_service"] = "true";  
    ...
```
Also have a look at `MajorUpgrade` sample for the use-case of the more complicated "calculated" conditions.
