### ISSUE TITLE
DLL required for ElevatedManagedAction

### ISSUE THREAD

**Issue by steronydh** [oleg-shilo/wixsharp#336]
I have a working WixSharp project. If I add an empty ElevatedManagedAction to it, when I run the installer it fails with the error message "There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor."

If I remove the ElevatedManagedAction item, the error message goes away. The ElevatedManagedAction function is in a class in the same file as the project definition.

If I look at the Log I see the same message. The name of the DLL doesn't appear anywhere.

What DLL do I need to add to the project for ElevatedManagedActions? Or have I missed some other configuration somewhere?

**Comment by oleg-shilo** [comment]
Most likely your routine in this CA requires some assembly that is not packaged with the CA. If it is the case you will need to add to your CA all referenced extra assemblies. Have a look at `DTF_ExternalAssembly` sample:
```C#
new ManagedAction("CustomAction")
{
    ActionAssembly = "CustomAction.dll",
    RefAssemblies = new []{"DispalyMessage.dll"}
}
```

**Comment by steronydh** [comment]
Thanks @oleg-shilo This is my entire CA (comments removed):

```
        public static ActionResult ManageServiceTrs(Session session)
        {
            return session.HandleErrors(() =>
            {

            });
        }
```

**Comment by oleg-shilo** [comment]
But I don't see it being marked as CA with the ` [CustomAction]` attribute. Did you miss it:
```C#
public class CustomActions
{
    [CustomAction]
    public static ActionResult ManageServiceTrs(Session session)
    ...
```

As for me I prefer events. No attributes. No special names. So much better! :) 
``` C#
project.BeforeInstall += session =>
{
    if (!session.IsUninstalling)
        Tasks.StopService("some_service", throwOnError: false);
};
project.AfterInstall += session =>
{
    if (!session.IsUninstalling)
        Tasks.StartService("some_service", throwOnError: false);
};
```

**Comment by steronydh** [comment]
It's nearly working with events :) - the (C# Topshelf) service installs with no errors but doesn't appear in the list of Services:

```
       private static void AfterInstall(SetupEventArgs e)
        {
            if (!e.Session.IsUninstalling())
            {
                try
                {
                    e.Session.Log("Installing TRS service");
                    Tasks.InstallService(Path.Combine(e.Session.Property("INSTALLDIR"), "TRS.exe"), true);
                    e.Session.Log("TRS service installed");
                }
                catch (Exception ex)
                {
                    e.Session.Log("Error AfterInstall: " + ex.Message);
                }
            }
        }
```

**Comment by steronydh** [comment]
This solution to Topshelf services mixed with your event handler seems to be working: https://github.com/oleg-shilo/wixsharp/issues/169#issuecomment-331866366

Thanks, @oleg-shilo
