### ISSUE TITLE
Image background for WixUI in Managed Project stretched or invalid

### ISSUE THREAD

**Issue by General-Fault** [oleg-shilo/wixsharp#339]
This appears to be the result of Issue #109, 
If using a ManagedProject, the custom background image size is expected to be 156x312.  However if using the standard WixUI dialogs, the image will be stretched to 493x312. If provided with an image of the appropriate size, the ProjectValidator throws an error if the width is greater than the height.

> "Project.BackgroundImage has incompatible (with ManagedUI default dialogs) aspect ratio. The expected ratio is close to W(156)/H(312). The background image (left side banner) in ManagedUI dialogs is left-docked at runtime and if it's too wide it can push away (to right) the all other UI elements.  You can suppress image validation by setting Project.ValidateBackgroundImage to 'false'."

Workaround:
set Project.ValidateBackgroundImage = false;

**Comment by oleg-shilo** [comment]
Do you think WixSharp needs to do any extra effort to explain the issue to the user or that message suggesting the very same work around is good enough?

**Comment by exedor** [comment]
I am seeing this again. I can either use ManagedProject and deal with this problem or Project and lose CustomActions.

**Comment by oleg-shilo** [comment]
Since this thread was closed there were quite a few changes in this area.
I suggest you verify that the latest WixSharp and the latest VS Templates work in your scenarios. I expect that they do.
Then you can see what needs to be done to update your projects.

Mind you that implementing a reliable resizing mechanism on monitors with custom scaling is not a trivial task. Particularly in the WinForms environment.

That's why you WixSharp offers templates with the complete source code for the all dialogs (WinForms or WPF) so users can have full freedom of implementing any handling of custom-scaling.

**Comment by exedor** [comment]
They do not. This was discovered as a result of updating my project used templates from only a few months ago. I'm running Wix 5.0.1+2f00cbe6 with the latest Wix4 templates. I've implemented image scaling and resizing before. Modern image processing libraries do make a lot easier than it was 20 years ago!

I do get what you're saying about winforms. I've had to do it here as well.

It looks to be more of confusion around the difference between providing an image for the left dock space vs providing an image for the whole background. When I provide one that is the exact size requested in the error for the left dock, it gets stretched to fit the whole background. When I supply an image the size of the whole background, it complains.

What I'm trying to describe is very different behavior between Project and ManagedProject. The old template and code was using Project. This showed up as soon as I switched to ManagedProject. I guess that's what I'm saying. There's an odd difference in behavior between Project and ManagedProject. As soon as I switched to ManagedProject which I thought was the newer of the two, this issue showed up. The workaround worked, but should it have been necessary?

It is behaving like ManagedProject is a copy of older code and Project has received updates and fixes that have not been implemented in ManagedProject.

**Comment by oleg-shilo** [comment]
The image sizing problems are coming from the way the default images are prepared for the setup you build. Thus they are extracted form the WiX framework files but not distributed with WixSharp.

This way you have the warranty to work with the latest images from WiX team. But it also means that if they change sizes or anything else then the default WixSharp sizing algorithm will be impacted. There were already cases like that.

If you want to use custom images I suggest you build your setup with complete custom UI. This way you will have access to the dialog code and you can completely replace the default image UIElements/controls and take full advantage of controlling the layout by yourself.

> Project and ManagedProject.

`Project` used MSI own UI. It is a native (unmanaged) Windows UI that fits very nicely all desktop scaling modes. Though you have no control over UI customization except archaic XML-based MSI specific application markup language. Bloody ugly if you ask me.

`ManagedProject` allows you to define managed UI (WinForm or WPF). The disadvantage is that I could not provide a truly generic reliable scaling solution that would satisfy all possible desktop scaling settings.

**Comment by exedor** [comment]
I'm not doing scaling on multiple desktops. That's just it. I'm doing anything weird. It really seems like it's just treating the left dock image versus the image for the whole background very differently. Like why would it complain about not having a specific resolution needed for left dock only, and then when given that specific resolution, it stretches it across the entire background? That's what I'm seeing that does not make sense.
