### ISSUE TITLE
Show dialog with option (remove or cancel) if another version of product already installed

### ISSUE THREAD

**Issue by KryuchkovAlexandr** [oleg-shilo/wixsharp#34]
Hello! 
How to make folowing case?
1. When installator started (double clicked on .msi), search another version of product (older or newer). If another version already installed, show dialog with message "Another version of this product is already installed. Remove current version of product to continue".
2. Dialog has 2 buttons: "yes" - for removing current version, and "no" - for cancel installation

In wix sharp sources, i find example "AppSearch.IsProductInstalled". In my case, method returns false, but product installed. Maybe it's a bug?
And, how to start removing of other version application?

**Comment by oleg-shilo** [comment]
> Remove current version of product to continue... 

The behavior you describe is already part of MSI. You'll need to have a look at MajorUpgrade sample from the downloadables.

 > ...i find example "AppSearch.IsProductInstalled".

No, `AppSearch.IsProductInstalled` works. But it tests the product code, which is different for every version of the product. Read this section describing the matter: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming

If you need to test if **any** version of the product is installed then you need to use new API (`AppSearch.GetProductVersionFromUpgradeCode`) discussed here: https://github.com/oleg-shilo/wixsharp/issues/31

**Comment by KryuchkovAlexandr** [comment]
Thank you for your help!
