### ISSUE TITLE
Additional / Extend Installation

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#340]
Hallo Oleg, i have a few questions and hope that you can give some answers and clarity. 

* Q1:  Is there posibility to extend already installed application with new features / new functions ? Something like if my product installed, and only then, install additional msi in same path. Registrykey for installdir and installedversion are exists already. I can access them. 
* Q2: Is it posible to show Main Window if product already installed ? If i double klick at my msi file, then windows show message, that product already installed or show modify Window  with unisntall, repair etc.
What i try to achieve is, 2 buttons on first Window  one for main application installation and another for additional features, something like that. Do i need bootstrapper for that or it posible to make msi behavior like that ? Thanks for Help.

**Comment by oleg-shilo** [comment]
Yes it's kind of possible but the whole thing is a bit unorthodox (doesn't mean it's wrong). 

Q1: seems like a separated product deployment that targets the same destination path as another product.
Accessing install_dir and installed_version can be done via raw MSI registry or MSI API available with WixSharp. And of course your primary product can also store this information in some "well known" location shared by both products.

Q2: It does sound as a good fit for Custom UI (ManagedUI). In one of the pre-installation dialogs you can do the target system analysis and implement the user experience you have described.
