### ISSUE TITLE
UAC Text is not localized

### ISSUE THREAD

**Issue by dviry** [oleg-shilo/wixsharp#341]
Hi Oleg,

after getting 1.6.4 the ProgressDialog [received an extra UAC "warning" text](https://github.com/oleg-shilo/wixsharp/issues/301):
- as a LinkLabel - yet the links points nowhere
- [hard-coded text in English](https://github.com/oleg-shilo/wixsharp/blob/039c3edbc39b2186a88345156c5636637e8a2bbd/Source/src/WixSharp.UI/ManagedUI/Forms/ProgressDialog.Designer.cs#L225)

There is no possibility to totally hide this nor to localize it... So yes, for now I'll have to temporarly implement my own but I think the default ManagedUI should provide an easier way to customize this.

Cheers

**Comment by oleg-shilo** [comment]
Done. 

```C#
// custom (localized) message
AutoElements.UACWarning = "Wait for UAC prompt to appear on the taskbar.";
```
![image](https://user-images.githubusercontent.com/16729806/38736289-e57682ca-3f6e-11e8-8ed8-78860239f180.png)


```C#
// hidden message
AutoElements.UACWarning = null;
```
![image](https://user-images.githubusercontent.com/16729806/38736445-65169614-3f6f-11e8-8e8e-d0a081688d9e.png)

**Comment by alexpwnz** [comment]
> Yeah, this is the annoying one.
> 
> You probably know what triggered this new feature, which is an attempt to communicate to the user that MSI/UAC have problems. There were complains from the users assuming that WixSharp is somehow responsible for that error. Some even suggested that if WixSharp cannot fix (OS problem!) it then it is completely useless.
> 
> I am annoyed by the fact that WixSharp has to take this offense simply because it "at the wrong place at the wrong time".
> 
> But I agree that:
> 
> * localization is overlooked in this case and needs to be implemented in some way
> * there should be a good way to control the visibility of the warning.
> * "link appearance" should be matched with the link behavior.
> 
> In a mean time please use this work around to hide the warning message:
> 
> ```cs
> project.UILoaded += Project_UILoaded;
> ...
> static void Project_UILoaded(SetupEventArgs e)
> {
>     e.ManagedUI.OnCurrentDialogChanged += dialog =>
>     {
>         if (dialog.GetType() == Dialogs.Progress)
>             foreach (Control c in (dialog as Form).Controls)
>                 if (c is LinkLabel)
>                 {
>                     c.Visible = false;
>                     break;
>                 }
>     };
> }
> ```

  static void Project_UILoaded(SetupEventArgs e)
        {
            e.ManagedUI.OnCurrentDialogChanged += dialog =>
            {
                if (dialog.GetType() == Dialogs.Progress)
                    foreach (Control c in (dialog as Form).Controls)
                        if (c.Name.StartsWith("waitPrompt", StringComparison.InvariantCultureIgnoreCase))
                        {
                            c.Text = "Пожалуйста, подождите, пока появится приглашение UAC.\r\n\r\nЕсли он свернут, активируйте его на панели задач";
                            c.ForeColor = Color.Red;
                            break;
                        }
            };
        }
