### ISSUE TITLE
Duplicate symbol 'Directory:ProgramFilesFolder' found

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#344]
Hi Oleg.
I have a small problem.
I need to make several entries in the 32-bit registry branch in 64 bit windows.
I do this:
```C#
new RegValue(Feature, RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION", "WebBrowserContainer", 11000) { Win64 = false },
new RegValue(Feature, RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_96DPI_PIXEL", "WebBrowserContainer", 1) { Win64 = false  },
```

At the time of the build, this error occurs:
> error LGHT0091: Duplicate symbol 'Directory:ProgramFilesFolder' found. This typically means that an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.

And the following code is generated:
```xml
<Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
  <Component Id="Registry1" Guid="*" Win64="no">
    <RegistryKey Root="HKLM" Key="SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION">
      <RegistryValue Id="WebBrowserContainer" Type="integer" KeyPath="yes" Value="11000" Name="WebBrowserContainer" />
    </RegistryKey>
  </Component>
</Directory>

<Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
  <Component Id="Registry2" Guid="*" Win64="no">
    <RegistryKey Root="HKLM" Key="SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_96DPI_PIXEL">
      <RegistryValue Id="WebBrowserContainer1" Type="integer" KeyPath="yes" Value="1" Name="WebBrowserContainer" />
    </RegistryKey>
  </Component>
</Directory>
```

Version:1.6.4.1

Before that was the version 1.6.3.2, there were no problems.

**Comment by oleg-shilo** [comment]
Yes the pre-release v1.6.4.1 delivers an updated algorithm for handling mixed (x64+x86) deployments. And it looks like a side effect of it. 

Will provide the fix asap.

Cheers

**Comment by oleg-shilo** [comment]
Done. The fix is available as a prerelease or athe laest NuGet package.
