### ISSUE TITLE
How to set User for Win Services

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#346]
Hi Oleg, i need some help. In Samples under WinService ->With_WiX i found how to install WinService . Works fine. How do i set User like Local Administrator or Domain Amdinistrator for UserAccount ? Wix installed always my exe as LocalSystem. Can you please help me with this question ?

**Comment by oleg-shilo** [comment]
I would expect that setting `ServiceInstaller.Account` property would do the trick.

**Comment by Torchok19081986** [comment]
Thanks. I going to try it.

**Comment by oleg-shilo** [comment]
As far as I remember the all samples do trigger elevation on starting the actual installation. 
Don't confuse it with starting the UI. I am talking about the actual installation. You will need to see what makes your setup different. 

You can also try `project.InstallScope = InstallScope.perMachine`.

If you want to elevate UI stage then it's also possible but i don't remember from the top of my head how. If it is what you want you will need google WiX for that.

**Comment by Torchok19081986** [comment]
I found a suggestion on MSDN, dont know how to use it. I need something like manifest config, where i can set requiredAdministrator. if i understand that correct, this will verify from windows before UI initialized and show some info, that app cant be installed with current user. 
Is there some posilibity to implement manifest file with required user rights in msi ?

**Comment by oleg-shilo** [comment]
Manifest file embedded in the executable is the only (official) way to make Windows application elevated at startup. It is a general technique of building any executable (exe file) on Windows.

Though this has nothing to do with MSI as technology. The MSDN suggestion you found is accurate and 100% correct but it has nothing to do with your challenge.  When you execute msi you are not executing any application. Instead you are interacting with already running background service - MSI runtime. 

Anyway, I have offered you two relevant directions to explore. This is my impression that you have decided not try them. I am not sure why. :)

But... it is ultimately your choice...

**Comment by oleg-shilo** [comment]
OK, then you did test it. Great. 
Please understand that without your feedback on the early suggestions it is close to impossible to understand your current troubleshooting status/stage.

Anyway, I am still puzzled that your installation does not get elevated by default. Is this what happening?
Or may be it does elevate but requires that special admin user. Can you elaborate on this specific point?
  
In any case you may be able to find some info on WiX forums. But embedding the manifest is a wrong direction. Your msi is not an executable but a database binary file. Thus you have no way to force MSI runtime to process any manifest but you also cannot even embed it as your msi is not of a PE (Portable Executable) format.

On a practical side of this matter you can always put a pre-condition (e.g. in `project.Load` event) where you can check if the current process user context belongs to the Admin user. And if it's not fail the setup with the user prompt to restart as admin. This way you will be OK even if you are not able to solve that elevation challenge.

**Comment by Torchok19081986** [comment]
i guess here is the clue. I am logged as Admin User , but not as Domain Adminstrator. And my process belongs to current user with admin rights and it already elevated.  Looks like there is not enough rights for this user. 
I going to try your suggestion on load and give some feedback. Question: my Enviroment has nothing to do with that ? windows Terminal Server 2016 as Hyper-V in network with 10 Client and 1 real Server right?

**Comment by oleg-shilo** [comment]
Yes I think it is a clue. 

To put it simple, you are required to start the setup as a user with some specific rights (e.g. domain admin). Meaning that being elevated is not going to solve anything. Still... may be there are some MSI/WiX tricks that I just don't know.

But I think the best course of actions would be not to force (very challenging) but to ask the user (very simple) to run as a domain admin. The only challenge is to find C# way for detecting domain admin. Though it should be much simpler than to do any MSI tricks. But it looks like you are aleady considering this.   

Though there is another thing to check. I just remembered...

Have a look at "AdminInstall" sample. It uses different sequences `Sequence`  to detect so called "admin installation". The chances are small but the test is very simple. Build the sample and execute it as just admin and then as domain admin. If these two tests invoke different custom actions then you have your "domain admin detection" algorithm.

**Comment by Torchok19081986** [comment]
Hallo Oleg, i found solution to solve my problem. With PrincipalContext i can verify if user are Domain Admin and same time check password. PrincipalContext.ValidateCredentials can validate credentials against current domain. I think that i am on right way. Another things are only implementation in msi during install. thats all.

**Comment by oleg-shilo** [comment]
Cool. 
That is exactly the direction I thought we would end up with. And the fact that you can use `PrincipalContext.ValidateCredentials` makes it even better than just a work around.

Another `Tips/Hints` :)
