### ISSUE TITLE
Replace references from codeplex to github

### ISSUE THREAD

**Issue by icnocop** [oleg-shilo/wixsharp#347]
Hi.

Thank you for WixSharp.

Since the project has moved to github, I expected links to be updated accordingly.

For example, in [WixSharp.bin.nuspec](https://github.com/oleg-shilo/wixsharp/blob/master/Source/NuGet/WixSharp/WixSharp.bin.nuspec):

```
<licenseUrl>https://wixsharp.codeplex.com/license</licenseUrl>
<projectUrl>https://wixsharp.codeplex.com/</projectUrl>
<iconUrl>https://download-codeplex.sec.s-msft.com/Download?ProjectName=wixsharp&amp;DownloadId=872632&amp;Build=20941</iconUrl>
```

References to codeplex also exist in other places.

Thank you.

**Comment by oleg-shilo** [comment]
Thank you. 
Done.
