### ISSUE TITLE
Bootstrapper with Custom UI for PackageGroupRef

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#348]
Sorry for my bad English.
I have PackageGroupRef("NetFx40Web") in my bootstrapper. Declared before my two msi, which I want to install. I made custom UI for bootsrapper based on WixBootstrapper_UI sample.
Net Framework installs properly. It have proper localization. But I want to change it - fonts have too big size and texts are cutted. Is possible to change that UI? Maybe even to WPF?

**Comment by oleg-shilo** [comment]
Hi there,

Yes you can change the appearance of the bootstrapper app. The sampe you have mantioned comes with the full source code so you can change any part of the UI:

![image](https://user-images.githubusercontent.com/16729806/39105714-caed4dc4-46fa-11e8-89e4-c69ba68e0c02.png)

**Comment by sadam2** [comment]
Hi,
It is honour for me to talk with You.
Seems we have misunderstanding.
We can see that screen after calling MainView(this).ShowDialog().
 Butin setup.cs we have:
![obraz](https://user-images.githubusercontent.com/27967943/39119958-7bcb95a0-46ed-11e8-9209-e568818faae4.png)
and when I am testing (with my name of product of course) on Windows XP I have such screen:
![obraz](https://user-images.githubusercontent.com/27967943/39120225-263bd644-46ee-11e8-98e0-4a35340abb1a.png)
before that screen about which You are writing.

**Comment by sadam2** [comment]
Hi,
sorry, Ive made a mistake - not that fragment of your code. I was thinking about:
![obraz](https://user-images.githubusercontent.com/27967943/39120538-0324bb3e-46ef-11e8-9865-6ace9ee9bd92.png)
where PackageGroupRef("NetFx40Web") generates screen which we can see before.

**Comment by oleg-shilo** [comment]
Yes it seems to be misunderstanding. :)
You said the example you referred to had only a single dialog defined, which is that BA WPF window. Your screenshot makes me thing that it is a UI of one of the Bootstrapper's packages. If it is the case then any modifications of this package UI are to be done outside of bootstrapper (see UI customization on Wiki). 

However if the dialog you revering to is the UI that Burn shows during downloading .NET then you are out of luck. WiX provided no customization path (as far as I know).

In any case reading these notes: https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-(Burn)-integration-notes may give you a better understanding of the challenge you are facing.

**Comment by sadam2** [comment]
Thank you very much for the third page. I saw your bootstrapers samples. They show what we can. And they don't (near) show, what we can't. Your new, third page in documentation is very usefull.

God bless you :smiley: . You are realy hard working man.

**Comment by oleg-shilo** [comment]
Amen to that 😄

**Comment by sadam2** [comment]
From @oleg-shilo:

> However if the dialog you revering to is the UI that Burn shows during downloading .NET then you are out of luck. WiX provided no customization path (as far as I know).

Yes, it is that UI. And seems I am out of luck. Is any way to delete the screen from ManagedBA? I'm thinking about installing .NET using own winform UI.

**Comment by oleg-shilo** [comment]
> Is any way to delete the screen from ManagedBA?

No there is no way to change it. Please make no mistake, this screen (dialog) is not part of your ManagedBA. This iis something that WiX team has developed to entertain the user during downloading .NET and they provided no way for customization. And the actual ManagedBA is initialized and displayed only after .NET is downloaded and installed. Thus it's not only WixShar but even raw WiX cannot help you.

Saying that, if you do find the way around then please share it here. There can be apossibility to integrate it in WixSharp.

**Comment by sadam2** [comment]
> This is something that WiX team has developed


Yes. I understood that before. Now I'm thinking about simple installer which installs .NET (if is needed) and after that calls ManagedBA. 
I was asking yesterday because I have lesson from my father: Always is somebody, who opens closed doors.
