### ISSUE TITLE
Deploying a scheduled task

### ISSUE THREAD

**Issue by pr4v33nv3rm4** [oleg-shilo/wixsharp#349]
hi,

Does wix# has inbuilt classes for task scheduler also similar to "public ServiceInstaller ServiceInstaller;"?
If not what is the recommended approach to configure scheduled task via MSI.

I am thinking of to invoke a command using custom action to achieve this.

thanks

**Comment by pr4v33nv3rm4** [comment]
hi oleg,
I don't think Wix also has anything inbuilt as all the examples i have seen they are using custom action to invoke command.
example:
```
<CustomAction Id="CreateScheduledTaskId"
               Property="CreateScheduledTask"
              Return="check"
              Execute="immediate"
               Value="&quot;[SystemFolder]SCHTASKS.EXE&quot; /CREATE /SC DAILY /MO 1 /ST 10:00 /TN &quot;CcsReturnProcess&quot; /TR &quot;&quot;[INSTALLFOLDER]CcsReturnProcess.exe&quot;&quot; /RU &quot;[Service.User]&quot; /RP &quot;[Service.Password]&quot; /RL HIGHEST" />

```

So i am gonna follow the same approach. Thanks.

**Comment by oleg-shilo** [comment]
Then probably it is the easiest to go with `AfterInstallevent`:
```C#
project.AfterInstall += session =>
{
    if (!session.IsUninstalling)
    {
        Process.Start($"{Environment.GetFolderPath(Environment.SpecialFolder.System)}\\SCHTASKS.EXE", 
                       "/CREATE /SC DAILY /MO 1 /ST 10:00 /TN \"CcsReturnProcess\" /TR \"\"{session.InstallDir}\\CcsReturnProcess.exe\"\" /RU \"{session.Property("Service_User")}\" /RP \"{session.Property("Service_Password")}\" /RL HIGHEST");
   };
```

Just ensure you properly tunnel `Service_User` and `Service_Password` properties.

**Comment by pr4v33nv3rm4** [comment]
sure,i'll give it a try and let you know.

**Comment by Torchok19081986** [comment]
Hallo Oleg, i tried it also create taskscheduler during install with SCHTASKS.EXE. It doesnt work for me, but with TaskService Class works fine.

**Comment by oleg-shilo** [comment]
If SCHTASKS.EXE is failing for you then you need to debug the SCHTASKS.EXE execution. 
Ensure that in the `AfterInstallevent` you are executing the very same command as you do from the command prompt (during your test).

Most likely there will be some difference (e.g. `session.Property("Service_User")` returns empty string).

**Comment by Torchok19081986** [comment]
Hi Oleg, You was right, there is some difference between SCHTASKS.EXE and Class. Only on user and password. for my test, it looks like exe doesnt recognize user and password for task creatation. 
I found something interesting on github. I used example by link for task creation.
https://github.com/dahall/TaskScheduler/wiki/Examples. Works great with that.

**Comment by oleg-shilo** [comment]
Looks interesting. 
I marked this thread as "Tips/Hints" so others can easy find it.
