### ISSUE TITLE
Show Msi UI at the uninstall

### ISSUE THREAD

**Issue by aleksandrkolesnikov** [oleg-shilo/wixsharp#350]
Hello Oleg!

The `Package.DisplayInternalUI` works only at the install. But is it possible to show Msi UI at the uninstall?

Thanks.

**Comment by oleg-shilo** [comment]
No. It is the MSI technology constrain. Custom UI is only possible for install and modify/repair. 
During uninstall the stock MSI UI is displayed. 
Nothing can be done about that.

Though you can have a custom BA (bootstrapper UI application) which changes its appearance in case of uninstall.

**Comment by oleg-shilo** [comment]
Hm... It is an interesting technique :)

Obviously you are no longer uninstalling. You are modifying, and during the modification you are removing all the components. Yes the final result is the same but from MSI runtime point of view you are completely avoiding uninstall sequence.

I have to say that while the technique has a lot of limitations it does achieve the result.

Can you please do a few tests for so I can understand how generic this technique is?

- Can you test and see what `msiexec /uninstall <your msi>` does?
- What exactly the user prompt when you try to remove the uninstallable product from ControlPanel?

Thank you.

**Comment by Torchok19081986** [comment]
Hi Oleg, what do you mean with "what msiexec /uninstall <your msi> does? 
In controlpanel is no uninstall. Only change and repair. if i click to change then it appears modifying window with uninstall, repair etc. you choose just remove and your msi will be uninstalled, but with your gui or algorithm. Looks like with project.ControlPanelInfo.NoRemove = true, you change uninstall startpoint for that and right here you can set your changes for uninstall.
Is it  that you wanted to know ?

**Comment by oleg-shilo** [comment]
Thank you. This does answer my second question.

As for "what msiexec /uninstall does?" I meant "what happens?" when you execute `msiexec /uninstall <your msi>`?

**Comment by Torchok19081986** [comment]
just tested. msi unisntall my product by guid /x silently.

**Comment by oleg-shilo** [comment]
Do you mean "msiexec /uninstall <your msi>" uninstalls the product without showing the GUI?

**Comment by Torchok19081986** [comment]
not exactly. it shows only uninstall gui like always. I found some interest info about gui in msiexec with /x or /uninstall. if i goodled it for change ui with msi i found almost always there are all set noremove to true or arpnoremove to 1 and show full UI in installui sequence.  advance installed make it like this
https://www.advancedinstaller.com/user-guide/qa-uninstall-change-button.html
and what i know is, that adobe air msiinstaller does have a guid for unisntall. another question ? is it possible to set .exe for uninstall ? something like if i want to unisntall i jump to exe with gui ?

**Comment by Torchok19081986** [comment]
after long research i found some info about it. If i understand correctly , that we need to override internal interface of msiexec. Then we can create own interface and use if. in pinvoke site i found link: 
https://www.pinvoke.net/default.aspx/msi/MsiSetInternalUI.html 
after trying it  i got my new managedform dialog, but i dont know how to use it .

**Comment by oleg-shilo** [comment]
> if i goodled it for change ui with msi i found almost always there are all set noremove to true or arpnoremove to 1 and show full UI in installui sequence. advance installed make it like this.

Yes it confirms that the technique is used to avoid limited user experience of MSI uninstall UI and rerout the user to the 'modify' UI instead.

And this can be achieved in WixSharp with `project.ControlPanelInfo.NoRemove = true`.

> s it possible to set .exe for uninstall ? something like if i want to unisntall i jump to exe with gui ?

This second question is more complex. MSI file is not an executable but a database file. When user double-clicks it OS starts `msiexec.exe` with the clicked msi file as an argument. Thus msiesec is the executable in this scenario and it triggers the installation of the msi by sending it to the running MSI service. The UI displayed to the user is the UI that is assembled at runtime by the MSI service from the UI definition inside of the msi file being executed. That definition is a set of the records that describes how UI controls are to be placed in dialogs during Install/Modify. For Uninstall MSI is using a built-in definition of the UI and it cannot be changed. 

Thus when it is vital to have a custom uninstall user experience you can disable Uninstall  (`project.ControlPanelInfo.NoRemove = true`) and simply implement "remove all" scenario in the Install/Modify UI. 

And for the customizing the Install/Modify UI you can use either WiX XML or WixSharp managed UI. 

> after long research i found some info about it. If i understand correctly , that we need to override internal interface of msiexec. 

Yes indeed `MsiSetInternalUI` is used to override the standard UI, but it has to be used by the host executable not by the custom action.  This scenario is called "External UI"

Thus you can write your own equivalent of `msiexec.exe` which would strat the msi file execution and call `MsiSetInternalUI` at start of the execution. In this case you are indeed in full control of the UI for all cases: install, modify and uninstall. 

However you don't have to invent the wheel hare. You can grab one of the WixSharp samples ('External_UI') that implement exactly that scenario:

![image](https://user-images.githubusercontent.com/16729806/39798038-379b7212-53a2-11e8-8846-6f8e884dbba6.png)

Read this: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#complete-custom-external-ui
And this: https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#managed-ui

---------------

Though I am sensing from your post that you are leaning towards customizing standard UI. If it is the case then you will be better off with the https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#managed-standard-ui and `project.ControlPanelInfo.NoRemove = true`..
