### ISSUE TITLE
Validate installation dir

### ISSUE THREAD

**Issue by mferraricloudsurfers** [oleg-shilo/wixsharp#352]
Hi,
i'm using the InstallDirDialog during my setup. Is it possible to validate the user's selected path and proceed with the rest of the installation process only if the path match with a specific pattern?

**Comment by oleg-shilo** [comment]
Hi there,

You have two options: 
- You can use `ManaagedUI` (Custom UI Sequence VS project template) and have you validation in the InstallDirDialog as just an ordinary C# routine.
- Alternatively you can verify the InstallDir value in the `project.BeforeInstall` event and fail the setup if the value is not withing the exepectations.

**Comment by mferraricloudsurfers** [comment]
Thank you Oleg. And is it possible in `BeforeInstall` event to modify the `InstallDir`? What I need to do, is to append to the seleted dir a suffix. 
Example: user select c:\Program Files\InstallDir path and what I want is to append a dynamic folder to the selected path. So c:\Program Files\InstallDir\A , c:\Program Files\InstallDir\B, c:\Program Files\InstallDir\C .... and so on. Is it possible? Because i tried to alter the InstallDir property in BeforeInstall event, but my change has been ignored.

**Comment by oleg-shilo** [comment]
I actually expect it to work. There is a sample for that: [InstallDir_DynamicPath](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/InstallDir_DynamicPath/setup.cs).
Though it is using different event: `project.Load`
Meaning that most likely `project.BeforeInstall` is too late.

**Comment by mferraricloudsurfers** [comment]
I used `ManagedUI` to solve my problem. I used your InstallDirDialog.cs source file and I reimplemented it with my own dynamic path logic. 

Thank you.
