### ISSUE TITLE
Change "ProductName" during installation

### ISSUE THREAD

**Issue by mferraricloudsurfers** [oleg-shilo/wixsharp#357]
If i build an msi file with a project name (i.e. "MySoftware"), is it possible to alter the `ProductName` to something like "MySoftware (Beta)" during the installation process? So, in programs and features window i want to see "MySoftware (Beta)" title.

**Comment by oleg-shilo** [comment]
Please see "ProductInfo"sample. I don't think product name can be changed but you can definitely change the other fields content.

**Comment by mferraricloudsurfers** [comment]
Hi Oleg, the example show how modify ControlPanelInfo of a project, but those parameters are editable during installation? And how? Because i haven't a project reference in my `ManagedForm`
