### ISSUE TITLE
MsiLogFileLocation in bootstrapper

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#358]
Is possible to get MsiLogFileLocation in bootstrapper?

**Comment by Xaddan** [comment]
WixBundleLog - Bootstrapper log file
WixBundleLog_MsiPackage_Id - Msi log file

**Comment by sadam2** [comment]
Thank you very much for answer.

I had another situation. Now I'm running two installers. Both are waiting because I had Debbuger.Launch() in code. And I had Two log files. I had previous too:

![obraz](https://user-images.githubusercontent.com/27967943/39566830-2a4f61ac-4ebd-11e8-9e89-b7a2ece1b03e.png)

Which one belongs to which installer?

**Comment by Xaddan** [comment]
-rodowisko_uruchomienowe_-_wersja_1.0.0.35_20180502214439.log - this is the bootstrapper's log

 -rodowisko_uruchomienowe_-_wersja_1.0.0.35_20180502214439_000_ExecutionEnvironmrntId64.log - this is the installer's log

In order to get the log file from bootstrapper:
```C#
var bootstrapperLog = Engine.StringVariables["WixBundleLog"];
var installerLog = Engine.StringVariables["WixBundleLog_ExecutionEnvironmrntId64"];
```

**Comment by sadam2** [comment]
Thank you very much again. Your first answer suggest me to look for WixBundleLog in Google. And I found (and I check it) at wix_users discussion group. Answer from Farrukhw 3 years ago. When I saw your second answer, I checked the second line too. It works. Thank you.

**Comment by Xaddan** [comment]
To get the name of the variable by which you can get the log file, you can parse the BootstrapperApplicationData file. The WixPackageProperties element contains the LogPathVariable attribute, which stores the variable name.
