### ISSUE TITLE
Reinstall of currently installed MSI

### ISSUE THREAD

**Issue by BasiK** [oleg-shilo/wixsharp#359]
Hello Oleg,

My current msi has MajorUpgrade.AllowDowngrades = true and a fixed UpgradeCode. Both upgrades and downgrades of msi's are handled as expected. However, if I want to reinstall the exact same msi file, with identical version (but for example with other command line msi properties defined), the installer starts and finishes immediately without an error code and without actually reinstalling the software.
How can I force an uninstall/reinstall when executing the identical msi? I tried explicitely setting AllowSameVersionUpgrades instead of AllowDowngrades, but also with no luck.

Cheers.

**Comment by oleg-shilo** [comment]
I would think that `AllowSameVersionUpgrades` should do the trick. Abut apparently it does not. :(

You may find a bit more luck in pure WiX resources. 

Please let me know if you find the solution (or a trick). It may be worth if incorporating it in WixSharp.

**Comment by BasiK** [comment]
Hey Oleg,

I got preoccupied with a lot of other things, but recently came across the solution it seems.
I see there is support for my case through the msiexec paramters / switches REINSTALL and REINSTALLMODE.
I now have it working with wixsharp, using REINSTALL=all and REINSTALLMODE=a when performing the msiexec command on the idential msi file and specifying the condition for my custom action (ElevatedManagedAction) as 'NOT_BeingRemoved' instead of my former 'NOT_Installed' condition. 

Cheers.

**Comment by oleg-shilo** [comment]
Great, thank you for sharing.
Marking the post as "Tips/Hints" tag.
