### ISSUE TITLE
Prevent install my software on Windows any Server 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#36]
Hallo Oleg, i have one question. 
How do i check in Wix# before install target is windows server and show some message ? 
Could you please help me with my problem ? 

Thanks for your help a lot.

**Comment by oleg-shilo** [comment]
You can use MSI launch condition.
But personally, I would just have a C# routine in `BeforeInstall` event.

**Comment by Torchok19081986** [comment]
ok, thanks for answer. i would try it.

**Comment by Torchok19081986** [comment]
i tried it with c# code. I got OS Version with WMI and validate it on my conditions.
