### ISSUE TITLE
how to create own shortcut in windows controlpanel

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#361]
Hi Oleg, i need some help with my question. How do i create/install own shortcut in windows control panel ? 
I found the solution with .reg File

Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\CLSID\{959E11F4-0A48-49cf-8416-FF9BC49D9656}]
@="User Accounts: Advanced"
"InfoTip"="Configure advanced user account settings and passwords."
[HKEY_CLASSES_ROOT\CLSID\{959E11F4-0A48-49cf-8416-FF9BC49D9656}\DefaultIcon]
@="C:\\Windows\\System32\\netplwiz.dll,6"
[HKEY_CLASSES_ROOT\CLSID\{959E11F4-0A48-49cf-8416-FF9BC49D9656}\Shell\Open\Command]
@="Control userpasswords2"
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\NameSpace\{959E11F4-0A48-49cf-8416-FF9BC49D9656}]

works really good. I only dont know, how to import or create this reg entry in CLSID and copie dll with my gui to strat in System32 Folder in install package.  Am i right if  i say i need some special rights to do this ?

**Comment by oleg-shilo** [comment]
I am leaving along the question if it is good or not to copy dll(s) into the System32 folder. Usually you simply add the location of your dll to the system "PATH" envar instead of polluting the system folders.

You'll decide....

But fro the permissions you can run an elevated custom actions and do it from there.
You can also use `AfterInstall` event that is already elevated. Just check there if you are installing or uninstalling and do your stuff (edit reg key, move files....).

There are also WixSharp samples of importing reg files.

**Comment by Torchok19081986** [comment]
Hallo Oleg. I tried to use afterinstall action. I got installterexception with description: "could not access non-immediate custom action". All i set in afterinstall event is
 string installdir = e.Session["INSTALLDIR"];
 string windir = Environment.GetFolderPath(Environment.SpecialFolder.Windows);
if (!e.IsUninstalling)
{
             var regttask = Tasks.ImportRegFile(e.Session["INSTALLDIR"] + @"\Config\vtesu2amwts.reg");

               MessageBox.Show("Import Registry Entry is successfully done", "Import Regfiles", MessageBoxButtons.OK, MessageBoxIcon.Information);
              Thread.Sleep(2000);
if (System.IO.File.Exists(installdir + "\\TSCP.dll") == true && System.IO.File.Exists(installdir + "\\TSCP.exe") == true && System.IO.File.Exists(installdir + "\\TSCP.exe.config") == true)
              {
                   System.IO.File.Copy(installdir + "\\TSCP.dll", windir + "\\System32\\TSCP.dll", true);
                   System.IO.File.Copy(installdir + "\\TSCP.exe", windir + "\\System32\\TSCP.exe", true);
                   System.IO.File.Copy(installdir + "\\TSCP.exe.config", windir + "\\System32\\TSCP.exe.config", true);                 
            }
            else
            {
              MessageBox.Show("Files not found. No Copied from  " + installdir + " to " + windir + @"\System32\" + " was executed.", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
             }

there is something wrong with that, but i could not figure out what.  Coult you please help me wit that ?
also same custom action in Step.InstallFinalize was not executed. In Custom Action im not sure which Condition i should use. Not_Installed or Installed ?

**Comment by oleg-shilo** [comment]
This is the MSI limitration. It does not allow session data to be accessed from the deferred Custom Actions (elevated actions in your case). Have a look at the Deferred Actions sample.

But to put it simple, you can access all properties you need from the event arg - `e.InstallDir`. 

Have a loo at 'Setup Events' sample.

**Comment by oleg-shilo** [comment]
Unrelated...
BTW you can improve code samples formatting in the posts if you enclose your code in the proper quotes ` - region:

![image](https://user-images.githubusercontent.com/16729806/40038344-ffd11366-5854-11e8-8310-faae5af6c7cf.png)

**Comment by Torchok19081986** [comment]
thanks for help. i figured out, how to access to INSTALLDIR. with e.CustomActionData["INSTALLDIR"] works. 
Only Task.Importregrile doesnt recognize value with C:\Windows\System32\netplwiz.dll,6. 
With mouse click works and .reg file can correct import. How to import regfile ?

**Comment by oleg-shilo** [comment]
> e.CustomActionData["INSTALLDIR"] works.

I encourage you to use e.InstallDir for INSTALLDIR and `e.Session.Property("PROP_NAME")` for everything else. `e.CustomActionData` only works for the tunneled properties but `e.Session.Property(..)` for all.

> Task.Importregrile doesnt recognize value with C:\Windows\System32\netplwiz.dll,6. I got error "escape sequence doesnt recognze \W".

You can easily debug it in a simple console app to see what is wrong with it.

**Comment by Torchok19081986** [comment]
Yes. i tried e.Session.Property and that doesnt work for me. e.CustomActionData work because is will be trigged by my own customaction where i need current installdir. i found some description for that .
my reg file was wrong. i had to set 2 backslashes not 1. should be C:\\ not C:\.  
Import with Tasks.ImportRegFile doesnt work, but process.start("regedit.exe ", $"-s \"+{regfile}+"\") works great, dont know why. i created my regvalues always with Regvalue, but now i needed to import reg file. 
Found solution with regedit.exe with parameter -s as args and execute it as ElevatedManangedAction. 
0% error in 10 Tests.

**Comment by oleg-shilo** [comment]
> Yes. i tried e.Session.Property and that doesnt work for me. e.CustomActionData work because...

I don't see how this can be the case. `Property` extension method redirects your code straight to the "CustomActionData":

```C#
public static string Property(this Session session, string name)
{
    if (session.IsActive())
        return session[name];
    else
        return (session.CustomActionData.ContainsKey(name) ? session.CustomActionData[name] : "");
}
```

And for the INSTALLDIR value you have the dedicated member - `e.installDir`
But... it is ultimately up to you...

**Comment by Torchok19081986** [comment]
Ok. i dont see anything what can be wrong with that, but if i dont use e.customactiondata["INSTALLDIR"] then i got always installerexception with error "could not access session details for non-imediate action data". 
after i googled it i found that i need to use customactiondata and it works. i thought always that i get INSTALLDIR via session["INSTALLDIR"] or e,Installdir. In another Installerproject i used same functions/methods  here works fine. i have no lowest idea, what wrong.
