### ISSUE TITLE
Wrong File Id if file name start from dot

### ISSUE THREAD

**Issue by Satran87** [oleg-shilo/wixsharp#367]
[test.zip](https://github.com/oleg-shilo/wixsharp/files/2004437/test.zip)
Good day.
You can try using files from attached zip
I know, if using "File", i can use my own id, but for "Files" i can't
```
            var project = new ManagedProject("test1",
                new Dir(new Id("INSTALLDIR"), @"%ProgramFiles%\My Company\My Product",
                    new Files(@"C:\test\*.*")));
            project.GUID = new Guid("6fe30b47-2577-43ad-9195-1861ba25889b");
            project.OutFileName = "setup_1";
            project.BuildMsi();
```
In wxs file i get
            <Component Id="Component..jshintignore_1749687543" Guid="6fe30b47-2577-43ad-9195-18619e22ba77">
              **<File Id=".jshintignore_1749687543"** Source="..\\..\\..\\..\\..\\..\\..\\..\\..\\test\\.jshintignore" />
            </Component>

And error
error CNDL0014 : The File/@Id attribute's value, '.jshintignore_1749687543', is not a legal identifier.  Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every identifier must begin with either a letter or an underscore.

**Comment by oleg-shilo** [comment]
Yes it is a defect.

Please use this work around until the fix is available:

```C#
project.WixSourceGenerated += 
      doc => doc.Descendants()
                .Where(x => x.HasAttribute("Id", value => value.StartsWith(".")))
                .ForEach(x => x.SetAttribute("Id", "_" + x.Attribute("Id").Value));
```
