### ISSUE TITLE
How to change custom UI Dialog Color 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#368]
Hi Oleg, is there posibility to change Color in new Dialog (BackgroudColor) from Grey or Lightgrey to another color like Lightblue or something like that ?.

**Comment by oleg-shilo** [comment]
Yes it is. It is just a WinForm dialog so you can change anything. 
```C#
this.BackColor = System.Drawing.SystemColors.CrazyPink; 
```

**Comment by oleg-shilo** [comment]
No, `ManagedForm` is the base class of all dialogs and it is up to derived classes to customize the final appearance. 
If you are not happy with the appearance of the **stock** WixSharp dialogs then you are better off with the "Custom UI" project template. In this case you will have access to all dialogs source code and you can alter their appearance without any limitations. 

![image](https://user-images.githubusercontent.com/16729806/40161977-bd1d5a78-59f5-11e8-97f6-0f5375d53a30.png)
