### ISSUE TITLE
In version 1.6.4.3 Empty directories are not created

### ISSUE THREAD

**Issue by DarthSidius** [oleg-shilo/wixsharp#370]
Sample "Epmty Directories" in version 1.6.3.0 was still working

**Comment by oleg-shilo** [comment]
I am still investigating it but it seams like a typo in the code (wrong config value) caused accidental disabling of the empty directory support.

Until it is fixed you can restore the original functionality by setting another config property to true before the `Build` call:
```C#
AutoElements.LegacyDummyDirAlgorithm = true;
```
