### ISSUE TITLE
Force the install to "C:\Program Files\" on 64 bit OS

### ISSUE THREAD

**Issue by SiyataDishmaya** [oleg-shilo/wixsharp#371]
I would like to force  the install to "C:\Program Files\" on 64 bit OS instead of C:\Program Files (x86)\. Using the following code snippet does not achieve it. Any ideas on solving this will be greatly appreciated. Thanks

        var project =
                new Project(productName,
                    new Dir(@"C:\Program Files\" + programFilesFolder,

**Comment by oleg-shilo** [comment]
Please have a look at "Install on x64" sample

**Comment by sadam2** [comment]
Does it mean that we must declare environment variable before installing?

**Comment by oleg-shilo** [comment]
Hi there,

1. Building msi for x64
I cannot comment on what is happening on your system bu the "Install on x64" sample modified as below produces the expected result with the application installed in the **Program Files**. I just tested it:

```C#
static public void Build()
{
    //note %ProgramFiles% will be mapped into %ProgramFiles64Folder% as the result of project.Platform = Platform.x64;
    var project =
        new Project("MyProduct",
            new Dir(@"%ProgramFiles%\My Company\My Product",
                new File(@"Files\Bin\MyApp.exe"),
                new Dir(@"Docs\Manual",
                    new File(@"Files\Docs\Manual.txt"))),
            new RegValue(RegistryHive.LocalMachine, @"Software\My Company\My Product", "Message", "Hello"));

    project.PreserveTempFiles = true;
    // if (Environment.GetEnvironmentVariable("buid_as_64") != null)
        project.Platform = Platform.x64;

    project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");

    project.BuildMsi();
}
```

When you build your msi verify that the output has the install dir correctly:

![image](https://user-images.githubusercontent.com/16729806/40262022-b7d5f86a-5b47-11e8-8106-1e7f869726c1.png)

2. x86 vs x64 at runtime.
Your bootstrapper approach is correct. 
> But sample "Install on x64" suggests simplest solution and I don't understood that.

Not exactly. The sample shows how to **build** x64 or x86 msi from the same source code depending on envar. It is about building not installing. The idea is that the developer who needs to build two identical msis targeting different CPU type will run the build script twice. Once with `buid_as_64` set and once with unset.

3. Localization
> How to localize user in FilePermission?

I am not sure what exactly you mean. 

But for a typical localization you may have a look at "CustomUIDialog" sample.

**Comment by sadam2** [comment]
I'm very sorry. I made an mistake. I tried to repeat what I made yesterday with no success. You are right. Setting  `project.Platform = Platform.x64;` is enough to have installed in Program Files.. I'm very sorry.

With the localization we can open new project choosing in WixSharp Setup in Visual C#, add wixsharp from NuGet and little modify the project file getting:

class Program
    {
        static void Main()
        {
            //DON'T FORGET to add NuGet package "WixSharp".

            var project = new Project("MyProduct",
                              new Dir(@"%ProgramFiles%\My Company\My Product",
                                  new File("Program.cs",
                                    new FilePermission("Everyone", GenericPermission.All)
                                  )));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
            //project.SourceBaseDir = "<input dir path>";
            //project.OutDir = "<output dir path>";
            
            //project.Language = "pl-PL";
            //project.Codepage = "1250";

            project.BuildMsi();
        }
    }
we can compile that. No errors. And after uncommenting the settings for Language and Codepage I have such output:
1>------ Rebuild All started: Project: LocalizedPermissions, Configuration: Debug Any CPU ------
1>  LocalizedPermissions -> C:\NEUCA\LocalizedPermissions\bin\Debug\WixSharp Setup.exe
1>  Building MSI
1>  Wix# support for EmptyDirectories is automatically disabled
1>  
1>  ----------------------------------------------------------
1>  
1>  Wix project file has been built: C:\NEUCA\LocalizedPermissions\MyProduct.wxs
1>  
1>  Windows Installer XML Toolset Compiler version 3.11.0.1701
1>  Copyright (c) .NET Foundation and contributors. All rights reserved.
1>  
1>  MyProduct.wxs
1>  Windows Installer XML Toolset Linker version 3.11.0.1701
1>  Copyright (c) .NET Foundation and contributors. All rights reserved.
1>  
1>C:\build\work\eca3d12b\wix3\src\ext\UtilExtension\wixlib\UtilExtension.wxs(41): error LGHT0102: The localization variable !(loc.msierrSecureObjectsFailedCreateSD) is unknown.  Please ensure the variable is defined.
1>C:\build\work\eca3d12b\wix3\src\ext\UtilExtension\wixlib\UtilExtension.wxs(42): error LGHT0102: The localization variable !(loc.msierrSecureObjectsFailedSet) is unknown.  Please ensure the variable is defined.
1>C:\build\work\eca3d12b\wix3\src\ext\UtilExtension\wixlib\UtilExtension.wxs(43): error LGHT0102: The localization variable !(loc.msierrSecureObjectsUnknownType) is unknown.  Please ensure the variable is defined.
1>C:\NEUCA\LocalizedPermissions\packages\WixSharp.1.6.4.0\build\WixSharp.targets(6,5): error MSB3073: The command ""C:\NEUCA\LocalizedPermissions\bin\Debug\WixSharp Setup.exe" "/MSBUILD:LocalizedPermissions"" exited with code -1.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
I was googling and I found some advices. I even compiled something. No success - using MsiRuntime in Custom Action in a such way:

        string bytes;
        MsiRuntime msiRuntime = new MsiRuntime(session);
        bytes = "Everyone".LocalizeWith(msiRuntime.Localize);
        io.File.WriteAllText("c:\\neuca\\Everyone.txt", bytes);

ends with application crash.

**Comment by oleg-shilo** [comment]
> I'm very sorry. I made an mistake.

Don't worry much about that. We have all been there. :)

> ...ends with application crash.

Let's be accurate with interpreting the behave. It is important as it lets you to pinpoint the location of the problem.

There is no any crash. There is  a WiX linker (light.exe) error `error LGHT0102`.
 I suggest that you use the sample I mentioned to verify that you can compile msi in your environment. Juts to verify your tools. 

After that investigate carefully what that sample does for German localization. You'll see that it not only sets language but also localization file. One obvious error candidate it the absence of the Polish WiX localization on your system. 

In my environment I see the same behavior and it is expected - I don't have Polish localization.
Anyway, it is a WiX not WixSharp problem.
Thus my advise - do exactly the same localization steps as for German localization sample.

> I even compiled something. No success - using MsiRuntime in Custom Action in a such way:...

I am not sure why you are trying to do something in custom action, which is invoked at runtoime. You clearly have a **compile time error**. I recon if you just get the appropriate `WixUI_pl-ple.wxl` file he problem will go away. At list this is what i would try.

Cheers

**Comment by SiyataDishmaya** [comment]
Is there any way to get part of the installer to use  project.Platform = Platform.x64 and another part to use project.Platform = Platform.x86? In other words, some of the files need to installed on "C:\Program Files\" and others on "C:\Program Files (x86)\" ?

**Comment by oleg-shilo** [comment]
It should be possible.  `project.Platform = Platform.x86` simply converts 
```C#
new Dir(@"%ProgramFiles%\My Company\My Product",...
```
into 
```C#
new Dir(@"%ProgramFiles64Folder%\My Company\My Product",...
```

But you can use the dedicated target dir names and component attributes (and their mixtures). Have a look at the `BuildWithAttributes` method i the same sample:
```C#
static public void BuildWithAttributes()
    {
       
        var project =
            new Project("MyProduct",
                new Dir(@"%ProgramFiles64Folder%\My Company\My Product",
                    new File(@"Files\Bin\MyApp.exe") { AttributesDefinition = "Component:Win64=yes" },
                    new Dir(@"Docs\Manual",
                        new File(@"Files\Docs\Manual.txt") { AttributesDefinition = "Component:Win64=yes" })));
. . .
```

**Comment by SiyataDishmaya** [comment]
Thank you for your reply. Your example shows assigning attributes to the files and not the directories. These do not change which "Program Files" directory to use. I have tried to apply the same attributes to the directories but it gives me an error "Cannot resolve custom attribute definition:Component:Win64=yes" I want to set "project.Platform = Platform.x86" for some of the project and "project.Platform = Platform.x64" for the other part. Any suggestions would be appreciated.

**Comment by oleg-shilo** [comment]
The first half of my response covered working with directories and the second illustrated matching x64 non-directory elements.  Have a look at the sample. I mentioned. Investigate the generated Wxs code with and without `project.Platform` being assigned. This will give you an idea.

This is what I meant by "mixtures":

```C#
new Project("MyProduct",
                new Dir(@"%ProgramFiles64Folder%\My Company\My Product",
                    new File(@"Files\Bin\MyApp.exe") { AttributesDefinition = "Component:Win64=yes" }),
                new Dir(@"%ProgramFilesFolder%\My Company\My Product",
                    new File(@"Files\Bin\MyApp2.exe") 
```

Though the pseudo-code above most likely requires some tweaking. I have never tried this approach.

One thing that needs to be clear here is that the difficulties that you are experiencing are due to the MSI/WiX not being designed for this sort of deployment.  And for a good reason. One has no business to install the same product in both x86b and x64 System locations. From the moment you decided to go this way you open yourself for troubles (or at least chellenges).
