### ISSUE TITLE
MsiFile location

### ISSUE THREAD

**Issue by mihazelenov** [oleg-shilo/wixsharp#372]
Hi! How can i find MsiFile location in UIInitialized event?

**Comment by DarthSidius** [comment]
`SetupEventArgs.MsiFile`

Read manual

**Comment by mihazelenov** [comment]
Could you please show me manual that contains information about what i have to do if it property is empty?

**Comment by oleg-shilo** [comment]
You indeed can find it in the `WixSharp.Reference.chm` in the distro package. 

![image](https://user-images.githubusercontent.com/16729806/40537501-673b0f34-6052-11e8-9a83-35464a878ef3.png)


But to be honest I perfectly understand your difficulties. This doc is an interface description and it works the best when you know the type member and want to see what it is.

For the challenges like yours I always prefer to use Intrellisense (F12) see what is available in the event argument. 

And I also created a special sample that demonstrates what is available in any event handler: "Setup Events".

![image](https://user-images.githubusercontent.com/16729806/40537337-ff3e1a84-6051-11e8-9c36-db40c0f054c3.png)

**Comment by mihazelenov** [comment]
As can i see this example works when Load event is raised. I, in turn, ask how can i get this value in UIInitialized event, because I need to use this value before installation is started.

**Comment by oleg-shilo** [comment]
You do it the same way. It's just a different event but with the same signature. 

However if it just happens that at that point `MsiFile` is not available then you can just access it directly via the session object:

``` C#
e.Session.property("OriginalDatabase")
```

**Comment by mihazelenov** [comment]
It's finally works! Thank you

**Comment by oleg-shilo** [comment]
I have tested and indeed it is too early and indeed the MSiFile value is not ready at this stage yet. 

Thus you will have to use `e.Session.property("OriginalDatabase")`.

**Comment by mihazelenov** [comment]
I talked abot it. Thanks
