### ISSUE TITLE
Bootstrapper.DigitalSignature.Apply hide console output

### ISSUE THREAD

**Issue by Lechl** [oleg-shilo/wixsharp#373]
Hello Oleg,

i'm using AppVeyor for automated builds. I have a bootstrapper which i sign with a pfx certificate. Works perfect!

But in the AppVeyor build i see the console output of the signtool. This is bad for me because I have no option to suppress the log showing the password of the certificate.

Few enhancement options are: Replace the password always with something like '*****', or add an parameter hiddenLog with default value to the Sign function. Or maybe add a ApplySilent function.

What do you think?

**Comment by oleg-shilo** [comment]
The easiest way for you is to override `DidgitalSignature.Apply` and do your silent signing.

As a starting point you can use the current implementation:

```C#
public virtual int Apply(string fileToSign)
{
    var retValue = CommonTasks.Tasks.DigitalySign(fileToSign, 
                                                  PfxFilePath, 
                                                  TimeUrl?.AbsoluteUri, 
                                                  Password,
                                                  PrepareOptionalArguments(), 
                                                  WellKnownLocations, 
                                                 UseCertificateStore);

    Console.WriteLine(retValue != 0
        ? $"Could not sign the {fileToSign} file."
        : $"The file {fileToSign} was signed successfully.");

    return retValue;
}
```
Where, https://github.com/oleg-shilo/wixsharp/blob/a2c1a72cb0c92da5408c8c355ab8da1e923ae4c2/Source/src/WixSharp/CommonTasks.cs#L182

However in the next release you will have the possibility to modify (or even clear) the output content before it is displayed in the console:

```C#
ExternalTool.ConsoleOut = (line) => Console.WriteLine(line.Replace("secret", "******"))
```

**Comment by Lechl** [comment]
Thank you Oleg!

**Comment by oleg-shilo** [comment]
👍

**Comment by dguder** [comment]
I also want to have the password hidden. But I don't understand your proposal. 
From my point of view the line [L1612](https://github.com/oleg-shilo/wixsharp/blob/a2c1a72cb0c92da5408c8c355ab8da1e923ae4c2/Source/src/WixSharp/CommonTasks.cs#L1612) in `CommonTasks.ExternalTool()` is the point where the password will be written to log/output. And this is not handled by the new log handler. BTW: The `signtool.exe` log doesn't display any passwords.
So for the moment a "simple" override doesn't help. IMHO `ExternalTool()` and `DigitalySign(...)` must be changed.

**Comment by oleg-shilo** [comment]
Don't I look silly now? I have just released half-done re-implementation of already existing feature. 
There was no need for that release. The feature was already available all along.

_@Lechl  this message is also important for you._
 
You are absolutely right. This is the line you are referring to:
```C#
Compiler.OutputWriteLine("Execute:\n\"" + this.ExePath + "\" " + this.Arguments);
```
And the default value of `Compiler.OutputWriteLine` is
```C#
class Compiler
{
    public static Action<string> OutputWriteLine = Console.WriteLine;
    . . . 
```  
Thus if you use it as is it will just print the output (e.g. signtool.exe) without any changes. However you can assign it to a new handler that can process the output or even completely "swallow" it.  

```C#
Compiler.OutputWriteLine = (line)=>{};
```

I will try to re-release and revoke the change later this week.

Thank you.

**Comment by Lechl** [comment]
Oh god, we all overlooked this. Thank's @oleg-shilo! Can be closed.

**Comment by oleg-shilo** [comment]
After further considerations I decided to keep that additional output filtering as it allows output massaging per `ExternalTool` instance. This in turn let me mask the password specifically in the signing routine. 
```C#
var tool = new ExternalTool
{
    WellKnownLocations = wellKnownLocations ?? @"C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin;" +
    ...
    ExePath = "signtool.exe",
    Arguments = sha1,
    ConsoleOut = (line) => Compiler.OutputWriteLine(line.Replace(password, "***"))
}
``` 

Meaning that from the next release you may remove `Compiler.OutputWriteLine = (line)=>{};` as the password will be masked automatically.

**Comment by dguder** [comment]
Thx @oleg-shilo. I'm sorry, I did not look into `Compiler.OutputWriteLine()` so I overlooked this too. 
And +1 for the default masking of the password.

**Comment by oleg-shilo** [comment]
To: @Lechl 

Hi Dominic, can you please give me some details on your use of AppVeyor. I am evaluating it for the commercial product CI and want to avoid problems that you have described.

My question are:
- Do you use AppVeyor free or commercial account?
- If it is a commercial account, does it mean that the log/output details can be still viewed publicly?

Thank you
Oleg

**Comment by Lechl** [comment]
@oleg-shilo 

- I'm using commercial account.
- No, them are not desposed publicly. But in our case not everyone who has access to the account should have access to the private key.

The default masking is very good, so no one has the chance to get the password via changing the code (eg. remove the `Compiler.OutputWriteLine = (line)=>{};`)

**Comment by oleg-shilo** [comment]
Great, thank you.
