### ISSUE TITLE
Msi file does not get created

### ISSUE THREAD

**Issue by davetek007** [oleg-shilo/wixsharp#374]
I am creating a project and adding 1 file containing a shortcut. When I call BuildMsi, it fails to create the MSI, 

A wixobj and a wsx file are created, and no errors are returned.

If i then run light.exe referencing the wixobj, the error is LGHT0094, with an unresolved reference to the folder containing the shortcut. 

I am able to reproduce the error and can provide code as necessary.

Thanks

**Comment by davetek007** [comment]
I should also point out that I'm using the latest version of WixSharp

**Comment by davetek007** [comment]
` public static void CreateMsi()
        {
            const string inDir = @"C:\temp\wixIn\";
            const string outDir = @"C:\temp\wixOut\";

            const string file = @"C:\temp\wixIn\MyApp.exe";

            var project = new Project("TestMsi")
            {
                GUID = Guid.NewGuid(),
                PreserveTempFiles = true,
                OutDir = outDir,
                UI = WUI.WixUI_ProgressOnly,
                Dirs = new[]
                {
                    new Dir(@"temp", new Dir(@"wixIn", new WixSharp.File(file, new FileShortcut("MyShortcut", inDir))))
                }
            };

            Compiler.BuildMsi(project);
        }`

**Comment by davetek007** [comment]
`
 public static void CreateMsi()
        {
            const string inDir = @"C:\temp\wixIn\";
            const string outDir = @"C:\temp\wixOut\";

            const string file = @"C:\temp\wixIn\MyApp.exe";

            var project = new Project("TestMsi")
            {
                GUID = Guid.NewGuid(),
                PreserveTempFiles = true,
                OutDir = outDir,
                UI = WUI.WixUI_ProgressOnly,
                Dirs = new[]
                {
                    new Dir(@"temp", new Dir(@"wixIn", new WixSharp.File(file, new FileShortcut("MyShortcut", inDir))))
                }
            };

            Compiler.BuildMsi(project);
        }
`

**Comment by davetek007** [comment]
`        public static void CreateMsi()
        {
            const string inDir = @"C:\temp\wixIn\";
            const string outDir = @"C:\temp\wixOut\";
            const string file = @"C:\temp\wixIn\MyApp.exe";
            var project = new Project("TestMsi")
            {
                GUID = Guid.NewGuid(),
                PreserveTempFiles = true,
                OutDir = outDir,
                UI = WUI.WixUI_ProgressOnly,
                Dirs = new[]
                {
                    new Dir(@"temp", new Dir(@"wixIn", new WixSharp.File(file, new FileShortcut("MyShortcut", inDir))))
                }
            };
            Compiler.BuildMsi(project);
        }`

**Comment by davetek007** [comment]
`
        public static void CreateMsi()
        {
            const string inDir = @"C:\temp\wixIn\";
            const string outDir = @"C:\temp\wixOut\";
            const string file = @"C:\temp\wixIn\MyApp.exe";
            var project = new Project("TestMsi")
            {
                GUID = Guid.NewGuid(),
                PreserveTempFiles = true,
                OutDir = outDir,
                UI = WUI.WixUI_ProgressOnly,
                Dirs = new[]
                {
                    new Dir(@"temp", new Dir(@"wixIn", new WixSharp.File(file, new FileShortcut("MyShortcut", inDir))))
                }
            };
            Compiler.BuildMsi(project);
        }
`

**Comment by oleg-shilo** [comment]
The test-case you have provided does produce the error output with the clear indication of the failure:
![image](https://user-images.githubusercontent.com/16729806/40574737-f0de15c4-611a-11e8-80f7-be876df5c13d.png)

However, I wouldn't even spend time trying to understand the cause of the problem. Instead I advice you to take any of the samples in this repository or the distro and modify them according your needs.

Using Visual Studio templates is another good way to start. The project created from the template contains a correct definition that can be successfully compiled into msi file.

Below is the fragment from the "Shortcuts" sample:
```C#
var project =
    new Project("My Product",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new InternetShortcut
            {
                Name = "Wix# project page",
                Target = "https://github.com/oleg-shilo/wixsharp"
            },
            new Dir("Samples",
                new File(@"AppFiles\MyApp.cs")),

            new File(@"AppFiles\MyApp.exe",
                new FileShortcut("MyApp", "INSTALLDIR"), //INSTALLDIR is the ID of "%ProgramFiles%\My Company\My Product"
                new FileShortcut("MyApp", @"%Desktop%") { IconFile = @"AppFiles\Icon.ico", WorkingDirectory = "%Temp%", Arguments = "777" }),

            new ExeFileShortcut("Uninstall MyApp", "[System64Folder]msiexec.exe", "/x [ProductCode]")
            {
                WorkingDirectory = "%Temp%"
            })
. . . 
```

**Comment by sadam2** [comment]
@davetek007 
Sorry for my bad english.
I don't uderstand what you expect from your code. But maybe such solution helps you:


        public static void CreateMsi()
        {
            const string outDir = @"C:\Temp\wixOut";
            const string file = @"C:\Temp\wixIn\MyApp.exe";
            
            var project = new Project("TestMsi")               
            {
                GUID = Guid.NewGuid(),
                PreserveTempFiles = true,
                OutDir = outDir,
                UI = WUI.WixUI_ProgressOnly,
                Dirs = new[]
                {
                 new Dir(outDir,
                    new WixSharp.File(file,
                        new FileShortcut("MyShortcut", outDir.ToDirID())))
             }
            };
            
            Compiler.BuildMsi(project);
        }

**Comment by oleg-shilo** [comment]
Have a look at "Shortcuts" sample. It deals with the scenario exactly like yours.

**Comment by davetek007** [comment]
Thanks. Where can I find that please?

**Comment by oleg-shilo** [comment]
Clone the repository (or download it as zip) and you will find ~90 samples.

Your sample (online):
https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Shortcuts

**Comment by oleg-shilo** [comment]
As a side note, you may want to use GitHub to respond on messages instead of email client. 
Otherwise it inserts plenty of noise. See your post above - 34 lines and only 2 are related to your actual message.

**Comment by davetek007** [comment]
Thanks.. The information you've provided has been very helpful, so all good to close this issue.

Thanks again :)
