### ISSUE TITLE
How I can first uninstall previous and after that install new?

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#375]
I'm installing two executables, four libraries and three configuration files. One of that executables is a kind of manager which manages our processes (works as windows service) and the second is user interface. During install I must ask user to have from him configuration params. After that I'm preparing configuration files and I'm starting the manager and his UI, I'm doing that in custom action after install files. In uninstalling I must properly stop that manager. Using rules for his version. In custom action before remove files. So I want in upgrade process first uninstall previous version. How to do that? I was trying some solutions but the uninstall prosess is called after installig new version. At that time is to late to stop my manager.

**Comment by oleg-shilo** [comment]
I always strongly advice against making configuration a part of the installation. It needs to be a part of the app first startup. But  you have already implemented it and it is up to you if you ever want to address it.

As for stopping services, it seems like stopping then at setup startup unconditionally would do the trick. 
And you can always start the services at the end of setup but only if it is not an uninstall session.

**Comment by sadam2** [comment]
For clarity:
I have one installer with version number 1.1. It knows how to uninstall. It uses code number 1 for it . And it is not simple uninstalling an service.
And I have installer version number 1.2. It uses code number 2 to uninstall. But I must have in it code number 1 too if I found installed previous version.
And in installer number 1.99 I must have codes: number 1, number 2, number 3, ... number 99.
