### ISSUE TITLE
How can i set WebSite Id dynamically

### ISSUE THREAD

**Issue by NikitaEgorov** [oleg-shilo/wixsharp#376]
I want install WebApp to exists WebSite
I create Dialog for choose exists WebSite.
How can i set WebSite Id after user choose it

**Comment by oleg-shilo** [comment]
The Ids if the WiX entities are allocated (automatically or manually) at compile time . Idon't really see hw it can be controlled at runtime. Please have a look at `IIS_ASP_NETApp` and `IIS_XMLInjection` samples.

[Samples folder](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples)
