### ISSUE TITLE
How to copy files to  a existent directory installed by another installer?

### ISSUE THREAD

**Issue by Saulotv** [oleg-shilo/wixsharp#379]
How to copy files to  a existent folder?

I am implementing a installer. I need install/copy some files (components) to a existent folder installed by another installer. The problem is when I need uninstall this component, the installer remove the entire folder and not only the component.

**Comment by oleg-shilo** [comment]
By default MSI dos not remove the folder if it is empty. This seems like a reasonable and acceptable behavior.

**Comment by oleg-shilo** [comment]
@sadam2 
I re-read my first answer and found a nasty typo there. A very dramatic one. 
It's supposed to be "By default MSI dos not remove the folder if it is **NOT** empty."  Olny such a behavior can be classified "reasonable and acceptable".

As for dealing with unknown files in the installation directory, you cannot do much with the installer itself. If these are not its files then it has no business removing them. Of course one can have an _on-uninstall_ custom action and forcefully rip off the files:

```C#
project.AfterInstall += args =>
{
    if (args.IsUninstalling)
        foreach(var file in IO.Directory.GetFiles(args.InstallDir))
            IO.File.Delete(file);
};
```  
However I strongly question your application deployment model that leads to the installation folder being polluted by any files that were not installed by your installer. But... this is really up to you.

@Saulotv 
Yo may have a look at WiX Directory element and if it has "Permanent" attribute it may just solve your problem.

**Comment by sadam2** [comment]
As I understood @Saulotv , he has installer "A", which installs files, say fileA1 and fileA2 to ProgramFiles\MyProduct. And he has installer "B", which installs files, say fileB1 and fileB2 to ProgramFiles\MyProduct. And he installs "A" and after that he installs "B". And now, when he uninstalls "B" files fileA1 and fileA2 are uninstalled too without any additional code. It is very interesting, how he made it.

**Comment by oleg-shilo** [comment]
> It is very interesting, how he made it.

I perfectly understand your interest. :o)
If you ask me until now I thought this scenario is just impossible.
