### ISSUE TITLE
Conditionally running my installer

### ISSUE THREAD

**Issue by SiyataDishmaya** [oleg-shilo/wixsharp#380]
I want to create an installer to make sure that a dll exists in a certain location and that there are valid registry values. These could have been installed by some other installer - not ours. If these are missing, I want my installer to install them. I also want my install to run silently . What is the best way to check these conditions and just exit if they are already installed else install  them silently?

**Comment by oleg-shilo** [comment]
A canonical WiX way is to use `FileSearch` and `RegistrySearch` elements. They are pseudo-actions that are executed by MSI runtime and their result (path/regvalue) are tunneled to the property, which in turn can be used as an install condition. WixSharp fully support them and you can find the corresponding samples.

Though I personally prefer the traditional programmers way:

```C#
var project = new ManagedProject("ManagedSetup", ...

project.BeforeInstall += project_BeforeInstall;

static void project_BeforeInstall(SetupEventArgs e)
{
    e.Session["SHOULD_INSTALL_MY_DLL"] = System.IO.Path.File.Exists("<your path>").ToString();
```

**Comment by SiyataDishmaya** [comment]
Where and how would I use  e.Session["SHOULD_INSTALL_MY_DLL"] to exit the installation if the file exists? Thanks

**Comment by oleg-shilo** [comment]
You use it (property) in the deployment entity install condition. WiX implements this technique via `Condition` attribute of the element (e.g. `File`). And WixSharp facilitates setting this attribute via the `Condition` member of the WixSharp entity:
```C#
var project =
    new ManagedProject("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File("my.dll")
            {
                Condition = new Condition("SHOULD_INSTALL_MY_DLL=\"yes\"")
            })
            . . . 
project.BeforeInstall += project_BeforeInstall;

. . .

static void project_BeforeInstall(SetupEventArgs e)
{
    // you will need to handle x86 vs x64
    var expectedLocation = Environment.ExpandEnvironmentVariables(@"%ProgramFiles%\My Company\My Product\my.dll");

    if(!System.IO.Path.File.Exists(expectedLocation))
        e.Session["SHOULD_INSTALL_MY_DLL"] = "yes";
}
```

**Comment by SiyataDishmaya** [comment]
The way I understand this, is that you can make a conditional install on specific elements - in this example a file. It seems that if the file exists, it will skip that part of the install but the rest of the installation will continue. So you would be left with a install entry in the control panel without any files associated with it. Is there a way to exit the whole installation without installing anything at all? Thanks.

**Comment by oleg-shilo** [comment]
Your understanding of my answer is 100% accurate. 

Sorry your question was kind of open for interpretation so I though you only want to skip installing a certain file (component) but not aborting the whole install.

Anyway have a look at the [samples](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples) library that contains ~90 complete samples covering almost all possible deployment scenarios.

The most orthodox approach would be a LaunchConditions and RegistrySearch samples.

However if I continue managed approach your

```C#
var project =
    new ManagedProject("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File("my.dll")
            . . . 
project.BeforeInstall += OnStart;
project.UIInitialized += OnStart; // not executed if UI is supressed

. . .

static void OnStart(SetupEventArgs e)
{
    // you will need to handle x86 vs x64
    var expectedLocation = Environment.ExpandEnvironmentVariables(@"%ProgramFiles%\My Company\My Product\my.dll");

    if(!System.IO.Path.File.Exists(expectedLocation))
    {
        e.Result = ActionResult.Failure;
        if (!e.IsUISupressed)
            MessageBox.Show(e.Session.GetMainWindow(), "Setup has been aborted because...");
    }
}
```
