### ISSUE TITLE
Certificate password can be null

### ISSUE THREAD

**Issue by biasso** [oleg-shilo/wixsharp#387]
Hi Oleg,
with commit 281567b38eb9b7176a8cb0fe7e15aeeb19943b83 an `ArgumentNullException` is thrown using the following code:

```cs
project.DigitalSignature = new DigitalSignature()
{
    UseCertificateStore = true,
    PfxFilePath = "My certificate name",
    OptionalArguments = "/a /s MY /fd sha256 /tr \"http://sha256timestamp.ws.symantec.com/sha256/timestamp\"",
    Description = "My description"
};
```

The `password` variable can be `null`.
https://github.com/oleg-shilo/wixsharp/blob/90111a5fce95fc76649f1ae473ea50eeb21ca6a8/Source/src/WixSharp/CommonTasks.cs#L215

**Comment by dviry** [comment]
I am hitting the same issue, tried to solve it with password=string.Empty but for some reason it does not work.
So yes, I personally would appreciate a HotFix NuGet....

Thanks

**Comment by biasso** [comment]
I can wait for the normal release.
For now I downgraded to version 1.6.5.0 where the digital signature works correctly.

**Comment by oleg-shilo** [comment]
Done: 
```
Install-Package WixSharp -Version 1.6.5.2-HotFix 
```

**Comment by dviry** [comment]
PM> Install-Package WixSharp -Version 1.6.5.2-HotFix 


Attempting to gather dependency information for package 'WixSharp.1.6.5.2-HotFix' with respect to project 'inPoint.Setup.SDK', targeting '.NETFramework,Version=v4.7'
Gathering dependency information took 951,9 ms
Attempting to resolve dependencies for package 'WixSharp.1.6.5.2-HotFix' with DependencyBehavior 'Lowest'
_Install-Package : Unable to find a version of 'WixSharp.bin' that is compatible with 'WixSharp 1.6.5.2-HotFix constraint: WixSharp.bin (>= 1.6.5.2)'._
At line:1 char:1
+ Install-Package WixSharp -Version 1.6.5.2-HotFix
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by oleg-shilo** [comment]
Give it another try. May be NuGet was not ready yet. The package is there: https://www.nuget.org/packages/WixSharp/1.6.5.2-HotFix

![image](https://user-images.githubusercontent.com/16729806/41036525-aa82f038-69d3-11e8-8ee1-b3944c14e7a3.png)

**Comment by dviry** [comment]
yes but shouldn't the dependency in WixSharp.nuspec also point to 1.6.5.2-HotFix instead of this?

        <dependencies>
            <dependency id="WixSharp.bin" version="1.6.5.2" />
        </dependencies>

**Comment by oleg-shilo** [comment]
:( Yes . My mistake. 
Incrementing the version now...

**Comment by oleg-shilo** [comment]
Should be OK now
```
Install-Package WixSharp -Version 1.6.5.3-HotFix 
```
