### ISSUE TITLE
Remove default text from UI when using background or banner images

### ISSUE THREAD

**Issue by spoved1** [oleg-shilo/wixsharp#39]
I set a project to WixUI_Minimal and then set background and banner images.  However, I notice that the default text (for example [ProgressDlgTitleInstalling]) is still visible on top of the banner.  How do I either set the text to an empty string or make the banner image be the top most control?  Thanks.

**Comment by oleg-shilo** [comment]
I don't thing it is a simple task to control UI elements with native MSI/WiX UI. You can do it very easy with Wix# ManagedUI but not with the native UI that you are using.

if you really want to customize the appearance of the MSI UI you need to redefine the XML definition of potentially every UI dialog. Not a pretty prospective.

Though you may try to set the title to the empty string. Find what exactly is the default text definition (e.g.  [ProgressDlgTitleInstalling]) and in any "before UI" events set this property to an empty string:

```C#
void OnLoad(SetupEventArgs e)
{
     e.Session["ProgressDlgTitleInstalling"] = "";
}
``` 
It may be the trick that you are looking for.

And of course you can switch to managed UI where you have full freedom to do with the UI dialogs anything you want.

**Comment by spoved1** [comment]
Thanks for the suggestions Oleg.  

First, can you explain how to do a "before UI" event?  

I also tried switching to ManagedUI to get more control but I'm having a few issues still though.

            wixp.ManagedUI = new ManagedUI()
            wixp.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
            wixp.ManagedUI.InstallDialogs.Add(Dialogs.Licence)
            wixp.ManagedUI.InstallDialogs.Add(Dialogs.InstallDir)
            wixp.ManagedUI.InstallDialogs.Add(Dialogs.Progress)
            wixp.ManagedUI.InstallDialogs.Add(Dialogs.Exit)

The first problem is, if I add a handler for the UI initialized event

             AddHandler wixp.UIInitialized, AddressOf CustomActions.UiInitEvent

then the MSI automatically fails with an Event Log entry of 1602 (which means user canceled).  If I add a handler for the UI load event, that never gets called.

             AddHandler wixp.UILoaded, AddressOf CustomActions.UiLoadEvent

I'm following the examples pretty close to a T but I'm obviously overlooking something.  Any pointers would be appreciated.

**Comment by oleg-shilo** [comment]
>First, can you explain how to do a "before UI" event?
I meant one of those (see "Managed Events" sample):
```C#
project.UILoaded += project_UIInit;
project.Load += project_Load;
project.BeforeInstall += project_BeforeInstall;
project.AfterInstall += project_AfterInstall;
```
Tough don't bother I tested it and the approach doesn't work. MSI at runtime ignores the property value and uses it's own algorithm for assigning the dialog title.

If you are using the _ManagedUI_ the you have two customization options:

* Change form title of the UI shell without modifying the UI sequence;
```C#
project.UILoaded += Project_UILoaded;

static void Project_UILoaded(SetupEventArgs e)
{
    var shellDialog = (Form)e.ManagedUIShell;
    shellDialog.Text = "New Title";
    e.ManagedUIShell.OnCurrentDialogChanged += ManagedUIShell_OnCurrentDialogChanged;
}

static void ManagedUIShell_OnCurrentDialogChanged(IManagedDialog obj)
{
    var dialog = (Form)obj;
    var shellDialog = (Form)dialog.Parent;
    shellDialog.Text = "New Title";
}
```
* Alternatively you can just create the project from the "WixSharp Managed Setup - Custom UI" template an change the actual dialog titles from the form designer.

**Comment by spoved1** [comment]
Thanks again Oleg.  I went a slightly easier route.  I ended up just specifying my own localization file with the specific text definitions empty.  Seems to work fine.  Still seems strange though that MSI lets you easily set images but makes it difficult to deal with the overlaying text.

**Comment by oleg-shilo** [comment]
>Still seems strange though that MSI lets you easily set images but makes it difficult to deal with the overlaying text.

That's MSI I know. :)
