### ISSUE TITLE
Setting registry at run time based on if it is 32 or 64 bit machine

### ISSUE THREAD

**Issue by SiyataDishmaya** [oleg-shilo/wixsharp#390]
In my install, I need to set a registry key based on whether  the install is running on a 32 bit or 64 bit machine  - either C:\Program Files\ or C:\Program Files (x86)\ respectively . I have a C# function IsOS64Bit() which checks if it is running on 32 bit or 64 bit. I have tried using Environment.ExpandEnvironmentVariables(@"%ProgramFiles%\") to get the Program Files path at run time but it gives back  C:\Program Files\  on 64 bit instead of  C:\Program Files (x86)\. I have also tried to use a managed action to set a session variable but I have not succeed in getting it called at the right time to have an effect on the setting of the registry. I cannot find any samples that seem to address this issue. Any help getting this done will really be appreciated.

**Comment by oleg-shilo** [comment]
It is a bit tricky. The output of the code below depends on the CPU context of the hosting process but not the OS type: 
```C#
var prog_files = Environment.ExpandEnvironmentVariables("%ProgramFiles%");
Console.WriteLine(prog_files);
```
Thus it is:
- x86 process on x64 OS: `C:\Program Files (x86)` 
- x64 process on x64 OS: `C:\Program Files` 
- x86 process on x86 OS: `C:\Program Files`
- x64 process on x86 OS: _impossible to run_
