### ISSUE TITLE
Add Combine overloads which take a single element

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/wixsharp#391]
So...you changed Add to Combine, which reads much more nicely, but you got rid of the overload taking a single element, which makes adding a single item more tedius.

**Comment by oleg-shilo** [comment]
Could you please elaborate. Without the context it's very hard to understand what API you are referring to.

**Comment by oleg-shilo** [comment]
I am only guessing that you may refer to `public static T1[] WixSharp.Extensions.Combine<T1, T2>(this T1[] obj, params T2[] items)`. But it uses `params` so you can pass a single item without any problems:

![image](https://user-images.githubusercontent.com/16729806/41288338-50822530-6e89-11e8-9623-737412d33b64.png)

**Comment by rconde01** [comment]
Doh...sorry about that :(

**Comment by oleg-shilo** [comment]
Been there... :)
