### ISSUE TITLE
Override strings from default wxl

### ISSUE THREAD

**Issue by cloudlucky** [oleg-shilo/wixsharp#392]
Is there a way to override just a few strings from the default wxl?
In a way, to inherits from the default wxl and change a few strings.

For example, a way to inherits from the WixUI_en-us.wxl and change a few strings in a custom one:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<WixLocalization Culture="en-US" Codepage="1252" xmlns="http://schemas.microsoft.com/wix/2006/localization">
  <String Id="InstallScopeDlgPerUserDescription">Just Me (recommended)</String>
  <String Id="InstallScopeDlgPerMachineDescription">All Users (requires administrator privileges)</String>
</WixLocalization>
```

Or I need to copy the WixUI_en-us.wxl in my project and change the strings that I need?

**Comment by oleg-shilo** [comment]
This is actually a WiX question that I don't know the answer for. 

WixSharp allows you to change any string in the _ManagedUI_ but performing the substitution for the native UI is out of WixSharp control.

Let me know if you find the pure WiX trick and I will incorporate it to the WixSharp work flow.
