### ISSUE TITLE
Auto run Bootstrapper with/without custom WPF UI

### ISSUE THREAD

**Issue by nadjibnet** [oleg-shilo/wixsharp#394]
Hi,

I noticed and confirmed in WiX Community that when we use the custom WPF/WinForm UI. The client PC should have at least the dotNet 4 installed (Not present in Windows 7).

Are they a way to automatic switches between **custom/default UI**. If **dotNet 4.x** is **present/missing** respectively.

Else, I suggest that as a feature.

Thanks,

**Comment by oleg-shilo** [comment]
No there is no way for automatic switching custom/default UI at runtime. This is the constrain of MSI but not of WixSharp.

Meaning that in such a cases one will need to use a bootstrapper. You can use either WiX Burn (`Wix# Samples\Bootstrapper\WixBootstrapper*` samples) or you can use the "hot from the oven", to be  released NSIS bootstrapper integration (courtesy of @geghamyan). 

Though keep in mind that Burn has a long standing bug - it cannot display internal UI of the bootstrapped msi if it is a custom UI (embedded managed UI). 

NSIS bootstrapper immune to this problem : https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/DotNETBootstrapper.cs.

The NSIS integration release is to be released within a day or two.

**Comment by nadjibnet** [comment]
Thanks Good Luck

**Comment by oleg-shilo** [comment]
Done please have a look at release v1.7.0
