### ISSUE TITLE
NSISBootstrapper sample doesn't work on Windows XP

### ISSUE THREAD

**Issue by sadam2** [oleg-shilo/wixsharp#396]
On my test machine - Windows XP Service Pack 3 (Oracle VirtualBox) without any NetFramework setup.exe installs Prerequisite as the main product.
On my second test machine - Windows 7 (Oracle VirtualBox too) everything is OK.

And one trick. Use:

![obraz](https://user-images.githubusercontent.com/27967943/41549153-37bd8094-7325-11e8-9ceb-ab8d69f656e7.png)

to have the message at the top :-).

Best Regards

**Comment by geghamyan** [comment]
The primary MSI of the _NsisBootstrapper_ sample uses  the _ManagedAction_ to show a message box. It implies dependency to the Microsoft Framework, thus on a machine without the framework the primary MSI won't be able to execute the managed code. 
It's just an example how to install a prerequisite before the main installer. Please refer to _DotNETBootstrapper.cs_ as an example how to install the Framework.

**Comment by geghamyan** [comment]
The last supported .net framework version for the XP is 4.0, so the framework installation code will along the lines of:

```
            var bootstrapper = new NsisBootstrapper`
            {
                DoNotPostVerifyPrerequisite = false,
                PrerequisiteFile = "dotNetFx40_Full_setup.exe",
                PrimaryFile = msiFile,
                OutputFile = "MyProduct.exe",
                PrerequisiteRegKeyValue = @"HKLM:SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework,Version=v4.0:"
            };

            bootstrapper.Build();
```

**Comment by oleg-shilo** [comment]
Thank you Tigran.

**Comment by sadam2** [comment]
A litlle misunderstanding. On XP, after install, we have the **Prerequisite** product on **Add / remove programs** list. And, of course, we can uninstall it from there.
By the way - where is the log file of the NsisBootstrapper?

**Comment by sadam2** [comment]
Sorry, I made a mistake. I didn't saw the **Prerequisite** on the **Programs an functions** list. Seems i was tired.
