### ISSUE TITLE
Compiler.WixLocation - Error using relative path

### ISSUE THREAD

**Issue by gsferreira** [oleg-shilo/wixsharp#4]
Hi,

I've been trying to compile a project in a machine without the Wix Toolset, using the package WixSharp.wix.bin.

I can compile it using the fullpath

` Compiler.WixLocation = @"c:\tfs\dev\packages\WixSharp.wix.bin.3.10.1\tools\bin"; `

But if I set the Compiler.WixLocation to the relative path to the package, I got the following error:

`Compiler.WixSdkLocation = @"..\..\..\packages\WixSharp.wix.bin.3.10.1\tools\SDK";`

```
5>  Wix project file has been built: C:\TFS\DEV\Service\Service.Installer\Service.WixSharp\Installer\MSI\MyMIS Service.wxs
5>  
5>  
5>  Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
5>     at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
5>     at System.Diagnostics.Process.Start()
5>     at WixSharp.Compiler.Run(String file, String args)
5>     at WixSharp.Compiler.Build(Project project, String path, OutputType type)
5>     at WixSharp.Compiler.Build(Project project, OutputType type)
5>     at WixSharp.Compiler.BuildMsi(Project project)
5>     at WixSharp.Project.BuildMsi(String path)
5>     at WixSharpSetup.Program.Main(String[] args) in C:\TFS\DEV\Service\Service.Installer\Service.WixSharp\Program.cs:line 101
5>C:\TFS\DEV\packages\WixSharp.1.2.0.0\build\WixSharp.targets(6,5): error MSB3073: The command ""C:\TFS\DEV\Service\Service.Installer\Service.WixSharp\bin\Debug\WixSharpSetup.exe" "/MSBUILD:Service.WixSharp"" exited with code -532459699.
========== Build: 11 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Am I doing something wrong?

**Comment by oleg-shilo** [comment]
>But if I set the Compiler.WixLocation to the relative path to the package...
`Compiler.WixSdkLocation = @"..\..\..\packages\WixSharp.wix.bin.3.10.1\tools\SDK";`

Actually your code snippet indicates that you didn't. You set `WixSdkLocation`, which you should't touch unless your SDK is not in the typical location with respect to `WixLocation`. Also I don't think your path points to the right location. You can check it with `Console.Writeline(System.IO.Path.GetFullPath(Compiler.WixSdkLocation))`

I suggest you completely remove any `Compiler.Wix*Location` assignment. The latest release has the ability to do the probing for WiX compilers/tools in the NuGet WixSharp.wix.bin package. You only need to set this variable(s) if the tools are not in the well-known locations, which are:

- Environment variable `WIXSHARP_WIXDIR`
- WiX full installation in %ProgramFiles%
- VS solution NuGet package WixSharp.wix.bin

I just tested a fresh VS project and these are the code configurations that work:
* Bin will be found in the expected package location and Sdk will be discovered based on actual `WixLocation`
```C#
//Compiler.WixLocation = @"..\packages\WixSharp.wix.bin.3.10.1\tools\bin";
//Compiler.WixSdkLocation = @"..\packages\WixSharp.wix.bin.3.10.1\tools\sdk";
```
* Sdk will be discovered based on used defined `WixLocation`
```C#
Compiler.WixLocation = @"..\packages\WixSharp.wix.bin.3.10.1\tools\bin";
//Compiler.WixSdkLocation = @"..\packages\WixSharp.wix.bin.3.10.1\tools\sdk";
```
* Both bin and sdk are usedr defined
```C#
Compiler.WixLocation = @"..\packages\WixSharp.wix.bin.3.10.1\tools\bin";
Compiler.WixSdkLocation = @"..\packages\WixSharp.wix.bin.3.10.1\tools\sdk";
```

**Comment by gsferreira** [comment]
Hi @oleg-shilo 

I've checked the Compiler.WixLocation and the PATH it's ok.
I also removed the WixSdkLocation.

I'm still getting the same error.
The exit code is "-532459699". 

Do you have any other advice?

**Comment by oleg-shilo** [comment]
Not really. The test I described in my prv post was conducted on the clean Win10 with VS2015. The project was a raw Wix# template with `WixSharp` and `WixSharp.wix.bin` packages. It cannot be any more standard environment than this. And it worked as expected. Did you do the same test in your environment?

Though there arte some ambiguities that I cannot comment on. You tested configuration #2 and it didn't work for you. But my primary advice was "using latest release with no Compiler.WixLocation set ". Did you have an opportunity to do that?

Another one is the most important 'unknown'. I have no idea what project you use. 
Was it based on Wix# template? What is the actual current dir at runtime? How did you verify that "_the PATH it's ok_"?  

You said "_I can compile it using the fullpath_" meaning that the relative path at runtime does not point to the same location as the absolute one. So it cannot be really OK. Try to print out `Path.GetFullPath(Cmpiler.WixLocation)` just before Project.BuildMsi call. Most likely it points to the wrong location.

**Comment by gsferreira** [comment]
To overcome this, I set the value of Compiler.WixLocation with the full path.

`Compiler.WixLocation = Path.GetFullPath(@"..\..\..\packages\WixSharp.wix.bin.3.10.1\tools\bin");`

Probably the issue was that when compiling, the current directory is based on other location.
