### ISSUE TITLE
EmbeddedUI

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#406]
Hi Oleg.

I decided to study EmbeddedUI. I made myself a test project based on your example EmbeddedUI_WPF. When I wanted to see data about features, I get such exceptions.
![image](https://user-images.githubusercontent.com/14925308/41986430-25753ea8-7a47-11e8-86c5-426a5a21ea6a.png)
Do not you know the reason?

**Comment by oleg-shilo** [comment]
The session object and its initialization is outside of WixSharp codebase. It is fully managed by WiX API. I also found that in many cases WiX managed instances do not have all members initialized. 

The only way out is to read/set MSI session properties with the routines based on the name of the feature taken from the `session.Features` item(s).

Have a look at "FeaturesDialog.cs", soecifically `BuildFeaturesHierarchy` method.

**Comment by Xaddan** [comment]
Yes, I also had thoughts of getting information from the database. But I wanted to get your advice.))
Can you tell the difference between ManagedUI and EmbeddedUI?
Can I use WPF in ManagedUI?

**Comment by oleg-shilo** [comment]
> Can you tell the difference between ManagedUI and EmbeddedUI?

The same. EmbeddedUI is an MSI UI hosting technique/model, which allows implementing UI as a managed assembly.

WixSharp comes with a two major components implementing this model. 

First is the set of samples named "EmbeddedUI*". These samples are nothing more than two MS code samples for implementing UI as WPF and WinForms.

Second is the built-in WinForm implementation of UI - top level shell form with child dialogs replicating the standard MSI dialogs look and feel. It is called ManagedUI. 

Thus "ManagedUI" is a particular implementation of the EmbeddedUI MSI model.
   
> Can I use WPF in ManagedUI?

It's problematic. ManagedUI dialogs are WinForm dialogs. You can extend these dialogs with yourr custom WinForm dialogs but not with WPF as the shell dialog (parent) is a winform window and it cannot contain child WPF UI elements.

However you probably can create another winform dialog and host WPF usercontrol in it. I think it is possible with `ElementHost`.

**Comment by Xaddan** [comment]
Thanks!

**Comment by geghamyan** [comment]
@oleg-shilo sometime I was experimenting with separating the ManagedUI functionality as a more standalone component, so it can be used as UI shell for the ExternalUI and the managed bootstrapper UI. You had concerns that it's probably shouldn't be the main way how to customize the the bootstrapper. I agree that it might not be the main way, but it can be certainly an useful option in the arsenal. 
What do you think , how about to give it a second chance ?

**Comment by oleg-shilo** [comment]
> @oleg-shilo sometime ago I was experimenting... What do you think , how about to give it a second chance?

Hi Tigran, yes I do remember our discussion. I had two major consideration points at that time:
1. Practical value of the merged (EmbeddedUI and Bootstrapper) UI shell. I considered it to be one of those "high effort low value" features.
2. Integration challenges as the existing EmbeddedUI/Bootstrapper model needs to stay as is. And if the feature is implemented it has to be as an option, not the default only needs to be an option.

Today, after quite a few conceptual failures of the WiX bootstrapper I no longer consider point \# 1 to be accurate. Any alternative UI models can only improve dev experience. The good example of that is the recent feature NSISBootstrapper.  

As for point # 2, it seems that we are already in agreement.

Tigran, if you are still keen tho give it a go please do so. As long as we can integrate it without affecting existing EmbeddedUI/BootstrapperUI model I have no problems with the approach. If required we can even agree on some additional UI hosting interface or non-breaking changes of the existing interface.

As for code base, you can do it as a PR but please also consider possibility of the "WixSharp Extension Model". Depending on your architectural choices you may find it beneficial to provide your UI infrastructure as an external assembly. This way you will have a complete freedom of the implementation, other developers may also want to try to implement something similar. And for WixSharp it will be the first cut of the Extensibility Model. Though feel no pressure. PR is also fine.r

**Comment by geghamyan** [comment]
Hi Oleg, thank you for the reply. Do you already have a vision how "WixSharp Extension Model" should look like ? For example any specific architectural choices you want to do.
I will try to come up with some proposal first and we can do it as several iterations.

**Comment by oleg-shilo** [comment]
Not a problem, I'll come up with some pointers over weekend. Let's take it offline. Contact me at 
![image](https://user-images.githubusercontent.com/16729806/42870431-30eedf3a-8abb-11e8-83b7-b93e02c5319a.png)
Or on LinkedIn. I believe we are already connected.
Let me know when you copied my email so I remove it from this message.
