### ISSUE TITLE
Localization Features

### ISSUE THREAD

**Issue by note-do** [oleg-shilo/wixsharp#407]
Hi, Oleg.
I have a really close issue to #193.
So, I have a VS project with two ManagedProject - one for the language. Just like you advised in #12. I use resource files Resources.resx and Resources.ru-ru.resx for define localization strings for:
`project.ControlPanelInfo.Manufacturer`
`project.LicenceFile`
`feature.Name` and `feature.Description`

The issue is only on applying localization to feature parameters. All other cases go well. But because this issue I cannot build en-US localized msi with an error
`A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.`

[Build.zip](https://github.com/oleg-shilo/wixsharp/files/2149747/Build.zip)

**Comment by oleg-shilo** [comment]
Unfortunately I do not have the answer. Though WiX forums may have something on that topic.
And I assume you have already tried setting `project.Codepage`. Did you?

**Comment by note-do** [comment]
I have figured out the issue. I created features with localization string at first and only after that apply the localization via `project.Language`.
It was my fault. I'm sorry.
