### ISSUE TITLE
Check for already installed components

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#41]
Hallo, is there some possibility to check if components  from third Software like .dll file alredy exists ? 
Thanks for answer.

**Comment by Torchok19081986** [comment]
i already figured out, how can i do this. CustomAction is key. Only one Question here, how can execute CustomAction before msi started to install. This info needed before i can install myproduct.

**Comment by oleg-shilo** [comment]
Have a look at `Setup Events` sample and experiment with it. Most likely some of the evens listed below is suitable for the task:
```C#
        project.UILoaded += project_UIInit;
        project.Load += project_Load;
        project.BeforeInstall += project_BeforeInstall;
```
Note that you have no warranty that the `Load` and `UILoad` events will be fired as user may deside to do silent installation. You will also need to take care about elevation as all these events are no elevated.
