### ISSUE TITLE
Forceing update of NON-versioned Files

### ISSUE THREAD

**Issue by emmoemminghaus** [oleg-shilo/wixsharp#411]
Hello,

I am facing a problem with NON-versioned files. 
Under certain circumstances such files are not replaced by an update (or on an installation).

A few reasons:
- modification date is set by some system software (Dont ask). 
- the files are copied the files over for some reason
- …

According to this link (https://docs.microsoft.com/de-de/windows/desktop/Msi/file-versioning-rules) literally every change of the modification date to a date after the creation date of a file is responsible.

**How can i force the reliable overwrite of such a file from a setup that is generated with WIXSharp.**

I can accept that .config files are not overwritten, but not for e. g. content files of a web (like .cshtml)

Emmo

**Comment by oleg-shilo** [comment]
The default behavior of MSI is that the files are not replaced if they already exist. 

In order to do this you need to insert extra XML element RemoveFile (MSI brilliance). With WixSharp you can achieve this with `File.OverwriteOnInstall`

**Comment by emmoemminghaus** [comment]
Thanks for your fast Answer. 

I set OverwriteOnInstall for all files in project.AllFiles after calling ResolveWildCards() now "unversioned" Files are replaced.

Then i tryed downgrading my installation and redo my update... even if OverwriteOnInstall is set, **versioned** files are not replaced when the version is higher. 
It looks like <RemoveFile> is ignored on versioned Files at all.

**Comment by oleg-shilo** [comment]
This is what I have no answer for. I am not aware about side effects of `OverwriteOnInstall` on downgrading. 
The answer can only be found in MSI/WiX documentation. 

Sorry, I never had the need to implement downgrading with `OverwriteOnInstall` . Though now I wonder if upgrading isn't affected by this as well.

**Comment by emmoemminghaus** [comment]
Anyway, i try to use a Version forward Strategy… just a headshaking as always.

Thanks for your support.

Emmo
