### ISSUE TITLE
The package Wixsharp.wix.bin should be auto-discoverable.

### ISSUE THREAD

**Issue by mslagle** [oleg-shilo/wixsharp#418]
The package Wixsharp.wix.bin should be auto-discoverable.  I should not have to set a path in code or in an environment variable to find this package.  Also - this package should win over any installed version of Wix that I have on my system.

**Comment by mslagle** [comment]
So after digging into the code, I figured out what happened.

1. I installed WIX
2. Un-installed WIX
3. Added the nuget package WixSharp.wix.bin package to the project.

Because I installed wix, the environment variable was already set, ignoring the search for a package.  Because the directory didnt exist anymore, I kept on getting errors that both the wix install and wixsharp.wix.bin package couldnt be found.

I have a few ideas on how to change the WixSharp.wix.bin package to make it more discoverable.  Here is what I would like to change.

- The current algorithm for package searching only finds and uses the latest package found.  We should instead use the package referenced.
- Adding the package should trump any found wix install.  The added package should be the system of record for what we build against. 
- I noticed that when running a debug build without automatic building, the command line arguments were not set and package searching didnt work at all (due to project path not being set).  This should be fixed to not require command line arguments to be set.

**Comment by oleg-shilo** [comment]
After further consideration I am no longer sure in this enhancement.

The real challenge comes with the new nuget packages caching location in VS2017, which is now is a system wide and not project specific as it was. Meaing that if WixSharp extends the probing algorithm and picks `WixSharp.wix.bin` from the global location it will not be possible to make a decision which WiX to use when WiX is installed on the system.

 > package searching only finds and uses the latest package found.

Yes this is the intention. If alternative location is preferred then it should be set from the code explicitly.  

I am afraid any changes to the existing probing algorithm will bring very little benefit for the required effort.

**Comment by mslagle** [comment]
#426
