### ISSUE TITLE
Refer CA assembly from another solution

### ISSUE THREAD

**Issue by Naveen84n** [oleg-shilo/wixsharp#422]
Hi , 
I have CA assembly file from another project .
How i can refer the CA Assembly to my WIX sharp project and build MSI

string assemblyCAFile = new FileInfo(Strings.CustomActionDLLPath).FullName;
 var ValidatePackages = new ManagedAction("Test",assemblyCAFile)
                {
                    Return = Return.check,
                    Execute = Execute.deferred,
                    When = When.Before,
                    Step = Step.InstallFiles,
                    Sequence = Sequence.InstallExecuteSequence,
                    MethodName = "Test",
                    
                };
				
				project = new Project(projectName,
                        mediaTemplate,
                        //CertificateActions,
                        CertificatePackage,
                        packageNames,
                        directory
                        );
						
		Am getting following error :+1: 
Cannot package ManagedCA assembly(%this%)

Kindly help me in this case

**Comment by oleg-shilo** [comment]
Check 'DTF_ExternalAssembly' sample.

Your code snippet probably is inaccurate or incomplete. Your project does not even use your `CustomAction`.

As a side note:
```C#
// replace 
string assemblyCAFile = new FileInfo(Strings.CustomActionDLLPath).FullName;

// with
string assemblyCAFile = Path.GetFullPath(Strings.CustomActionDLLPath);

// or even this
string assemblyCAFile = Strings.CustomActionDLLPath.PathGetFullPath();

```

**Comment by Naveen84n** [comment]
Thank you very much for your valuable answer.
