### ISSUE TITLE
How to mark a .NET assembly to be NGen'd during install

### ISSUE THREAD

**Issue by jhudler** [oleg-shilo/wixsharp#43]
In Wix XML it is possible to add the NetFxExtension which enables the <netfx:NativeImage> sub-element to be added under the <File> element.

Wix# apparently have a predefined set of sub-elements that are allowed to put inside <File>, so this approach seems to not be possible.

What is the usual / recommended way to NGen assemblies during install via Wix#? Any examples?

**Comment by oleg-shilo** [comment]
Sorry I somehow missed your post.
Have a look at InjectXML sample. It demonstrates how to extend Wix# with a new element by implementing `IGenericEntity`.

Note, currently, Wix# allows generic Entities to be added to directories only. I am marking this post as `enhancement` and will make the change for the next release to allow generic Entities to be added to files as well. But for now you will need to find the file element in your `Process` method: 

You will need something similar to thie:

```c#
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles64Folder%\My Company\My Product",
            new NativeImage { Platform = "32bit" },
            new File(@"Files\Bin\MyApp.exe"),
...

public class NativeImage : WixEntity, IGenericEntity
{
    [WixSharp.Xml]
    new public string Id
    {
        get { return base.Id; }
        set { Id = value; }
    }

    [WixSharp.Xml]
    public string Platform;

    [WixSharp.Xml]
    public int Priority = 0;

    [WixSharp.Xml]
    public string AppBaseDirectory;

  ....

    public void Process(ProcessingContext context)
    {
        var util = WixExtension.NetFx;

        context.Project.IncludeWixExtension(util);

        //serialize itself and add to the parent component
        context.XParent
               .FindAll("File")
               .First(e => e.HasAttribute("Source", value=>value.EndsWith("MyApp.exe")))
               .Add(this.ToXElement(util, "NativeImage"));
    }
}
```

**Comment by jhudler** [comment]
Hi Oleg,

No worries.
Thanks for the response & snippet. I'll be assuming this approach by now then. 
I'm glad you considered as an enhancement. Thank you again.

**Comment by oleg-shilo** [comment]
Done in https://github.com/oleg-shilo/wixsharp/commit/61ed80eec669e58de1da3edcd97acf69e0e2d3bd
Ready and waiting for release.

```C#
new Project("MyProduct",
     new Dir(@"%ProgramFiles%\MyCompany\MyProduct",
         new Files(@"Release\Bin\logger.dll",
             new NativeImage { Platform = NativeImagePlatform.x86}),
```

**Comment by jhudler** [comment]
Great News Oleg!

I see you modified the `Files` class to allow an `IGenericEntity` as child - this will bring great flexibility from now on.

Thanks!
