### ISSUE TITLE
Question: Start external process after Finish button is pressed

### ISSUE THREAD

**Issue by avpirogov** [oleg-shilo/wixsharp#432]
Hello @oleg-shilo,
We need to run an external exe file after user presses Finish button on Exit dialog with the folowing code:

```
...
var project = new ManagedProject(ProductName,
                                        new Dir(appTargetPath,exes));
...
project.ManagedUI = new ManagedUI();

project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                            .Add(Dialogs.Features)
                                            .Add(Dialogs.InstallDir)
                                            .Add(Dialogs.Progress)
                                            .Add(Dialogs.Exit);
...

```
Could you please give us any ideas on this.

**Comment by oleg-shilo** [comment]
If you doen't want to use `AfterInstall` event then the easiest way to hook up to your Exit button is to have a custom ExitDialog and attach the event handler to your button.

Create the VS project form the "WixSharp - CustomUI" template and you will have the access to the ExitDialog code.
