### ISSUE TITLE
Help: Remove \ at the end of Env Variable

### ISSUE THREAD

**Issue by ssijbabu** [oleg-shilo/wixsharp#437]
Hi all,

`new EnvironmentVariable("JBOSS_HOME","[INSTALLDIR]") { System = true },`

When i create an environment variable using the above code, the created env var value has \ at the end. How can i create env var without having \ at the end?

Regards
Sujay

**Comment by oleg-shilo** [comment]
The value of the MSI session property `INSTALLDIR` is controlled by the MSI runtime and you cannot and should not change it.

Though you can have another custom variable that can be used isntead:

```C#
new EnvironmentVariable("JBOSS_HOME","[INSTALLDIR_EX]") { System = true }
. . .
project.BeforeInstall += (e)=>
{
    e.Session["INSTALLDIR_EX"] = e.Session["INSTALLDIR"].Trim('\\');
};
```
