### ISSUE TITLE
Uninstall failing with no reason

### ISSUE THREAD

**Issue by hespi** [oleg-shilo/wixsharp#44]
I have successfully written a WiX# program that generates a MSI installer that works like a charm. The problem comes when I try to uninstall the application... installer is always failing. The worst is that no error log can be found neither in Windows Events, nor even provided by the installer itself.

After searching for some hours, I've discovered that Wix Toolset recommends to use UPPERCASE guids for compatibility reasons. The problem is that Wix# is generating lowercase guids in the WXS file so this may be causing the error. Besides, some other developers in Stackoverflow recommend to programmatically convert them to uppercase before generating the MSI.

- http://stackoverflow.com/questions/7532863/wix-not-removing-files-on-uninstall
- http://wixtoolset.org/documentation/manual/v3/howtos/general/generate_guids.html

**Is there anyway in which I can configure a WixManagedProject to generate uppercase GUIDS?.**

Any help will be appreciated. Thanks.

**Comment by oleg-shilo** [comment]
Wow! I could not even imagine that character case of GUID can  matter. Will update the implementation to refelct that.

In a mean time you can use post-build event to fix GUIDS:
```C#
Compiler.WixSourceGenerated += document =>
{
    document.FindAll("Component")
            .ForEach(e => e.SetAttributeValue("Guid", e.Attribute("Guid").Value.ToUpper()));
};
```

**Comment by hespi** [comment]
Hi Oleg,

Many thanks for your quick response. After generating some debug logs on Uninstall process, I've realized that the problem was on a custom code I placed on the _AfterInstall_ event, that was also executed after uninstall, so a check of e.IsUninstalling has solved the issue.

In any case, I've placed your code to generate upper case GUIDs and now everything works as expected.
