### ISSUE TITLE
Question: Wixsharp update from 1.0.35.3 to 1.8.0 - 2

### ISSUE THREAD

**Issue by csaba6os** [oleg-shilo/wixsharp#440]
Hi Oleg,

We have a wix project where we updated to the latest version of wix and wixsharp.
_Old packages:_ 
```
 <package id="WiX" version="3.11.0.906-pre" targetFramework="net35" />
 <package id="WixSharp.bin" version="1.0.35.3" targetFramework="net35" />
```
_New Packages:_
```
 <package id="WiX" version="4.0.0.5512-pre" targetFramework="net35" />
 <package id="WixSharp.bin" version="1.8.0" targetFramework="net35" />

```  
After upgrading we had some build errors, which we could solve successfully with your help, thanks for that!
https://github.com/oleg-shilo/wixsharp/issues/436

But now we are stuck again, after fixing the previous issue.

**Output:**
```
18>EXEC : error : Invalid argument: WixToolset.Dtf.WindowsInstaller.dll must be included in the list of support files. If using the MSBuild targets, make sure the assembly reference has the Private (Copy Local) flag set.
18>D:\projects\xxxxxx\Standalone\StandaloneSetup\SetupAgent.cs : error : System.ApplicationException: Cannot package ManagedCA assembly(D:\projects\xxxxxx\SetupTemp\WixSharp.dll)
18>     at WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String configFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
18>     at WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
18>     at WixSharp.Compiler.GenerateWixProj(Project project)
18>     at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
18>     at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
18>     at WixSharp.Compiler.Build(Project project, String path, OutputType type)
18>     at WixSharp.Compiler.Build(Project project, OutputType type)
18>     at InstallerCommonParts.AgentInstall.AgentInstaller.BuildLauncherMsi(SetupInfo setupInfo) in D:\projects\xxxxxx\InstallerCommonParts\AgentInstall\AgentInstaller.cs:line 316
18>     at InstallerCommonParts.AgentInstall.AgentInstaller.GetValidLauncherExe(AgentInstallMode installMode) in D:\projects\xxxxxx\InstallerCommonParts\AgentInstall\AgentInstaller.cs:line 58
18>     at InstallerCommonParts.AgentInstall.AgentInstaller.Build(AgentInstallMode installMode) in D:\projects\xxxxxx\InstallerCommonParts\AgentInstall\AgentInstaller.cs:line 42
18>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5143,5): error MSB3073: The command ""D:\projects\xxxxxx\SetupTemp\StandaloneSetup.exe" "D:\projects\xxxxxx\3rdParty\WiX.4.0.0.5512-pre\tools"" exited with code 1.
```

The Copy local  flag is set on the csproj file:
```
<Reference Include="WixToolset.Dtf.WindowsInstaller">
   <HintPath>..\..\..\..\..\3rdParty\WiX.4.0.0.5512-pre\tools\WixToolset.Dtf.WindowsInstaller.dll</HintPath>
   <Private>True</Private>
</Reference>

```
Could you give me any hint why it's giving me this message?
				
Thank you for your help again!
Regards,
Csaba

**Comment by oleg-shilo** [comment]
Sorry, without the project it's impossible to tell why the assembly is not found. I suggest you simplify your project to the level of HelloWorld all and share it here.

**Comment by csaba6os** [comment]
Hi Oleg, 

I've attached an example project. Please unzip it under D:\projects (it's hardcoded in the solution) and when you start the solution restore the nuget packages.

Thanks for your help ;)
Best regards,
Csaba

[wix_error.zip](https://github.com/oleg-shilo/wixsharp/files/2269926/wix_error.zip)

**Comment by oleg-shilo** [comment]
Hi Csaba,

Sorry for the delay. I have checked the project you Shared. The problem is caused by the fact that WiX team decided to change `*.WindowsInstaller.dll` assembly dramatically. It's not only a new version of the assembly but also a change in the namespaces. Meaning that what WiX 4 is officially out WixSharp will need to be recompiled against that assembly (_WixToolset.Dtf.WindowsInstaller.dll_). This also means tat once WixSharp supports WiX4 it will stop supporting WiX3.

Anyway, while WiX4 is still in the beta you will need to use WiX3 toolset instead.

**Comment by oleg-shilo** [comment]
Changing the issue to the 'Enhancement'.

**Comment by oleg-shilo** [comment]
Duplication of #446
