### ISSUE TITLE
Run update.msi for my product

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#441]
Hallo Oleg, i have one bigger problem and hope you can help me with. Before i founed wisharp and wixtoolset my application was created by another developer. Application was not installed - only copied to target and updates was done by copied only new files. Since wixhsharp and wixtoolset i can create updateXYZ Version for products and just execute it. this works absolutely great.  Now i have requst to create updates packages. If product are not installed, you cant execute update, because no upgradecode present right ? I have to update my product with new features and new executables. I'm now completly clueless how i can do that. Maybe registry export and import or i can set in update.msi path to copied application ?

**Comment by sadam2** [comment]
Maybe You need to have bootstrapper with two msi. One updating msi (your updateZYZ) and next one doing full install (say installXYZ). And decide in bootstrapper which one of them will be used.

**Comment by oleg-shilo** [comment]
You can achieve this by using normal update MSI (see "upgrade" sample). 

But you will need to extend it with the launch condition to prevent starting if e.g. some file/registry is not present and there is MSI version of your product is also not found. As for me, `project.Load` is a good candidate for that. Though traditional `LauchCondition` with MSI RegestrySearch and FileSearch based properties is also fine. 

If manually installed product is found then use its location as InstallDIr (see InstallDir sample). This will be the fresh install. 

If MSI installed then you don't need to worry about anything. MSI will pick the previous InstallDir automatically.

**Comment by Torchok19081986** [comment]
Thanks for help. I didnt knew that is posible.  I would try it on my VM and give some Feedback. 
 LaunchConditions could be more than one right ?

**Comment by oleg-shilo** [comment]
I think it you can have only a single condition but the condition expression can include multiple properties, which in turn can be initialized at startup.

Also check out "Managed Setup" sample. It does runtime checking and preventing the setup from installing the product if the target PC name is not what is expected.

**Comment by Torchok19081986** [comment]
I tried your suggestion like in Managed Setup. It works. One problem, after update successfully installed, msi doesnt copy new files to new installdir. I guess it happend because one error for extend db and make rollback. Is that right ?

**Comment by oleg-shilo** [comment]
Cannot comment on this one. I don't know what are the specific details of your solution.

One possibility is that your db file is locked.

Another good candidate is that your files need to have `File.OverwriteOnInstall` set to true. It's not obvious but by default MSI does not overwrite the files during the installation/upgrade if they are already exist:
- User created files during the first installation.
- Installed files that are remains present after the uninstall during upgrade. Note, upgrading first uninstalls the existing product and only after that tries to install a new one. 
Also keep in mind that MSI never removes the installed files during uninstall if the the files have been modified since the installation.

**Comment by Torchok19081986** [comment]
Greatest thanks Oleg. 
I going to try it with OverwriteOnInstall. I think Rollback was executed after one of erros are appears during update. i will track each one step were my errors appear do some correction. 
All my 7 executables are only modified by developer, but i keep it in mind. That means my product can be only get new Versions of programm by Update not just copy files? This is exactly what i need to achieve.

**Comment by oleg-shilo** [comment]
> That means my product can be only get new Versions of programm by Update not just copy files?

No really, copying files is always a possibility. From the prospective of copying the business is as usual.  For example you can go into "program files -> MS Word" and modify some or bring new files there. The same applies to your application.

**Comment by Torchok19081986** [comment]
Hallo Oleg. I tried OverwriteonInstall . It works, also if file are newer as files in *.msi. Msi does overwrite all files by same name. Is there posibility to check which are .exe are newer or does msi self check which files are newer and copy it to installdir ?

**Comment by oleg-shilo** [comment]
Not really. MSI approach is straight forward - either never overwrite the existing file or overwrite always.
For anything else you will need to have a custom deployment solution. For example have your exe as 'binary' in your setup. Meaning that i will not by part of th einstallation but will be present in the package. Then in the BeforeInstall (or AfterInstall) event check the destination for th presense of the local exe file and dec ide if you want to overwrite it. Do the "opposite" algorithm on uninstalling.
