### ISSUE TITLE
How can I make an installer window resizable using native UI?

### ISSUE THREAD

**Issue by milkin-vl** [oleg-shilo/wixsharp#445]
Hi, is there a way to make an installer window resizable without using native UI? Now maximize button is disabled.

Thanks for your help.

**Comment by oleg-shilo** [comment]
It's hard to understand your use-case as you provided no context.

You can build your own UI (EmbeddedUI) without an limitations or you can use External UI with the same outcome.

If you are using ManagedUI it is nothing else but a stock implementation of the EmbeddedUI that repeats native UI user experience. And as such it disables maximizing. Even though I don't see why you would want to resize the stock ui you can still adjust any of the window properties from the UILoaded event handler.  After all it is just a WinForm object.

Have  a look "CustomUIDialog" sample.

**Comment by milkin-vl** [comment]
Oleg, now I realized my mistake. Thanks again.
