### ISSUE TITLE
Cant create msi with new project of WixSharp

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#446]
Hallo Oleg,
i need again your help. I started new Wix sharp project in  VS 2017 as Managed Setup -  Custom UI.
Method project.BudilMsi() give me Error with Info: "Cant compile ManagedCA.dll in project." and something about Windows.Deployment.WindowsInstaller.dll. Installerdll is exists and will be copy local into my project. After running BuildMsi() method it create only *.exe and *.wxs and .*wixobj but not msi.
In older project with Version 1.6.2 after Update to 1.8.0 of Wix Sharp here works great. Description of msi Dirs, Files, Contorlpanelnfo, Dialogs and etc. is the same.

**Comment by oleg-shilo** [comment]
You need to ensure you have WiX installed on your OS.
Alternatively you can bring WixSharp.wix.bin with 'WixSharp.wix.bin' nuget package.

**Comment by Torchok19081986** [comment]
Wix Toolset is in Version 3.11 installed. WixSharp.wix.bin are also installed from nuget, but thats brought no improvment. There is no error during compile to msi. Thats not work only in new projects of WixSharp. In all of them. if i open older project, here works all correctly.

**Comment by oleg-shilo** [comment]
I cannot comment on your systems specifics. But, when I have just created a new project with the following packages:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="WixSharp" version="1.8.0" targetFramework="net35" />
  <package id="WixSharp.bin" version="1.8.0" targetFramework="net35" />
  <package id="WixSharp.wix.bin" version="3.11.0" targetFramework="net35" />
</packages>
```
I worked straight away. And it picked the WiX compilers from the NuGet packages:

![image](https://user-images.githubusercontent.com/16729806/43387469-dbd08670-9429-11e8-9841-8262e18275da.png)

**Comment by Torchok19081986** [comment]
Now my new Project looks like in your picture. 
I founded "error". if you change .NET Framework in Project from 3.5 to 4.5 and better, msi cant be created. Dont know why, but in my main project in could change .NET Framework to 4.6.2 and it works without problems. May be some wix toolset issue ? there is already Wix 4.0. can be installed and use it. I tried it with 4.0 and here works fine.

**Comment by oleg-shilo** [comment]
I have created a feature request for that: https://github.com/oleg-shilo/wixsharp/issues/450
