### ISSUE TITLE
Change Product Code during install

### ISSUE THREAD

**Issue by RTyrer** [oleg-shilo/wixsharp#447]
We are installing the same web site multiple times on the same server.  These sites have been created by hand for many years.  

The code is installed in 'C:\inetpub\{prod}.{cust}'.  
The website and virtual path are also '{prod}.{cust}'.
The app pool is '{prod}.{cust}.AppPool'.

I've created an installer that will install the website as described above, based on the msi package name.
For example Prod.Cust.msi

It successfully installs and uninstalls the website once.  After that I get the option of Change, Repair Remove, because it detects the product is already installed.  To get around this, I'd like to change the Product Code before the Install is started.  I can generate a unique GUID based on the msi package name.

I assumed I could change the Product Code in a Custom Action, but haven't been able to get it to work.
How can this be accomplished?  Generating the install for each customer is not an option, according to my employer.  I am open to better/simpilar options.

Thanks,

Scott

**Comment by RTyrer** [comment]
More information:

The following code is in the Custom Action:
        session["ProductCode"] = newProductCode;

Querying the WMIC shows the application was installed with the original GUID.  So, I don't believe the 'ProduceCode' is being updated.   The Custom Action is being called Before the AppSearch.  Perhaps it is read only?  

I'm also attempting to update the 'UpdateCode'.
     session["UpgradeCode"] = newProductCode;

Uninstalling appears to have no effect after more than one instance has been installed.  The files and IIS settings remain, though the feature no longer shows in ADD/REMOVE programs.

**Comment by oleg-shilo** [comment]
This is something that is deeply buried in the MSI runtime design/implementation. But I would expect that when loading msi file for the execution it reads its ProductCode and UpgradeCode before it executes any CA and after that never reads these properties again.

**Comment by RTyrer** [comment]
Thank you for you response.  I am assuming the same thing.  I appreciate all your effort in creating and supporting an excellent piece of software.
