### ISSUE TITLE
The UI of 64-Bit (Managed UI) setups is running as 32-Bit process

### ISSUE THREAD

**Issue by DanielEgbers** [oleg-shilo/wixsharp#448]
### Description
This is about setup projects that should generate a 64-Bit MSI-Setup (WixProject.Platform = WixSharp.Platform.x64).

The UI itself and the UI events (UIInitialized and UIInitialized) are running as 32-Bit process. The installation itself, related events (Load, BeforeInstall and AfterInstall) and custom actions are running as 64-Bit process.

I have only tested it with Managed UI setups, so it could also occur in other setup project types

### Expected behavior
The UI itself and the UI events of a 64-Bit setup are running as 64-Bit process

### Actual behavior
The UI itself and the UI events of a 64-Bit setup are running as 32-Bit process

### Steps to reproduce
1. Clone my reproduction of this issue: https://github.com/DanielEgbers/WixSharpX64BitIssue
2. Build and run the MSI (It shows a message-box on all mentioned events, that tell if it is a 64-Bit process or not)

or

1. Create a new Managed UI Setup (using the templates: https://github.com/oleg-shilo/wixsharp/tree/master/Source/Templates/ProjectTemplates)
2. Set the the property "Platform" of "project" to WixSharp.Platform.x64
3. Add any of the mentioned events to "project"
4. Build the MSI and debug it
5. Check what platform the events are actually running in by evaluating "IntPtr.Size == 8" (true = 64-Bit and false = 32-Bit)

### Notes
This has already been reported by @Strohhalm but was closed without any change (see #283 )

**Comment by oleg-shilo** [comment]
Indeed #283 was closed without any comment. Most likely by accident during the release cleanup. It's corrected now.

WixSharp (nor WiX) has no control over how the assembly, which implements EmbeddedUI is hosted. The choice of the CRL CPU architecture is entirely up to MSI runtime.

I cannot exclude that there is some magic MSI config value to trigger the desired behavior but I am afraid there is nothing you can do from WixSharp about it..

**Comment by oleg-shilo** [comment]
BTW, I absolutely appreciate the quality of your issue report and amount of the details you have provided. I only wish I could help...

**Comment by DanielEgbers** [comment]
Well, the whole MSI-System is so messed up, I guess I expected this answer.
I really hope Microsoft gets MSIX right.
Anyway, thanks for looking into it.

**Comment by oleg-shilo** [comment]
It's OK. As I mentioned, it is 27 years old tech :)
You can't know everything.
You will have no problem running any exe from your installer. CPU architecture has no impact on this.

When you run exe you are simply requesting your OS to start the exe from the given path. And the requesting app can have any supported architecture because it is the OS, not your app who is going to create the process from that exe.
