### ISSUE TITLE
How to activate already exists windows Firewall rule

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#449]
Hi Oleg, how do i activate windows firewall rule if rule are exists or set it to active  ? In example is only for create it. I need to activate Files and Shares in network and also RPC Server with WMI. Rules are exists, but not always activated.

**Comment by oleg-shilo** [comment]
I don't know the exact answer but most likely there will be a way described in the documentation for FirewallException Element (Firewall Extension). When/if you find it porting it in WixSharp will be a relative simple exercise.

**Comment by Torchok19081986** [comment]
I done some google research. It looks like in Windows Firewall exists property for Enabled or Enable. But i dont find nothing like that in FirewallException element.

**Comment by Torchok19081986** [comment]
For new Rules it can be activatedif windows firewallrule going to be created. Installer set it as activated. 
I tried also if rules exists overwrite it by same name. Doesnt work for me. 
i fought it can be activated through installer, but it looks like for exists rules was that not implement to windows firewall. May be some security thoughts of MS.
