### ISSUE TITLE
Building a MSI for a VS Project?!

### ISSUE THREAD

**Issue by schmitch** [oleg-shilo/wixsharp#451]
Hello,
currently I'm not sure if it is worth an issue, but feel free to close it, if it doesn't suite an issue.

At the moment I'm looking into Installers and looked at WixSharp.
What I want to accomplish is the following:
1. Have a VS Project with a SLN file which contains at least the following projects:
   - WPF like Application (Xamarin.Forms) Project (csproj)
   - Installer Project (also csproj)
2. Make the Installer Project call a Release Build for the WPF like Application & Build the Installer

However I have no idea if that is even possible that easily with WixSharp.
Currently what works is that I can build a Release Target with msbuild and then invoke the WixSharp installer afterwards (somehow hardcoding the paths), but I think it should be possible more easily to actually let WixSharp reference another Project.

i.e. at the moment I do something like that:
```
 var projectBaseFolder = System.IO.Directory.GetParent(Environment.CurrentDirectory).FullName;
            var path = System.IO.Path.Combine(projectBaseFolder, @"MyProject\bin\Release");

            var files = System.IO.Directory.GetFiles(path).Select(File => new File(File)).ToArray();
```

However this has two assumptions, first I need to build it from the command line (msbuild).
`Environment.CurrentDirectory` needs to be one path above the root (I guess in VSStudio the path might be different).
It would at least help if there was a way to detect the `Root Folder`/Where the SLN files is.

**Comment by oleg-shilo** [comment]
I actually think that referencing project inside of the WixSharp project is a healthy idea. I am not sure yet that it can be done elegantly but I will give it a try.

Until this feature is available please use the following approach:
- Have WixSharp project added to your solution
- Point the base dir of the `Project` instance to the WPF solution dir.
- Have the following setup definition:

  ```C#
  var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new Files(@"WPF_Project\bin\Release\*.*"),
            new ExeFileShortcut("Uninstall My Product", "[System64Folder]msiexec.exe", "/x [ProductCode]")));

  project.SourceBaseDir = "<solution dir>";
  // project.SourceBaseDir = @"..\";
  project.GUID = new Guid("6f330b47-2577-43ad-9095-1561ba25889b");

  project.BuildMsi();
  ```

**Comment by oleg-shilo** [comment]
I have started some pre-work for supporting auto setting up `project.SourceBaseDir` from VS project dependencies. But I quickly realized that the approach cannot be implemented without affecting other use-cases.  

For example if you have a solution with three projects as below:
1. Product application project
2. Custom WixSharp dialog project
3. WixSharp setup project

In the case like this it's not possible to tell which project binaries WixSharp needs to include the files . The only solution is to specify it explicitly fro the code. But then it becomes exactly the same solution as it is now. 

```C#
project.SourceBaseDir = "<custom dir>";
```
