### ISSUE TITLE
Component Id generation for RegValue does not take RegValue.Id into account

### ISSUE THREAD

**Issue by meareindel** [oleg-shilo/wixsharp#452]
WixSharp's current implementation of RegValue Component Id generation uses simple algorithm, based on constant "Registry" string and index of RegValue:

https://github.com/oleg-shilo/wixsharp/blob/0a26ba87121653bc915ebc33a1102bdef7e13d1f/Source/src/WixSharp/Compiler.cs#L2231-L2250

In other words next code

```csharp
            var project = new ManagedProject(awpExecutableName,
                    new RegValue(new Id($"MyRegValueId"), RegistryHive.CurrentUser, 
                "someKey", "someName", "someValue"),
                    new RegValue(new Id($"MyRegValueId2"), RegistryHive.CurrentUser, 
                 "someKey2", "someName2", "someValue2"),
                )
```

produces this:

```xml
        <Component Id="Registry1" Guid="<determined by component id>" KeyPath="yes">
          <RegistryKey Root="HKCU" Key="someKey">
            <RegistryValue Id="MyRegValueId" Type="string" KeyPath="no" Value="someValue" 
            Name="someName" />
          </RegistryKey>

          <CreateFolder />
          <RemoveFolder Id="ProgramFilesFolder" On="uninstall" />
        </Component>

        <Component Id="Registry2" Guid="<determined by component Id>" KeyPath="yes">
          <RegistryKey Root="HKCU" Key="someKey2">
            <RegistryValue Id="MyRegValueId2" Type="string" KeyPath="no" Value="someValue2"
            Name="someName2" />
          </RegistryKey>

          <CreateFolder />
          <RemoveFolder Id="ProgramFilesFolder" On="uninstall" />
        </Component>
```

Now consider a situation when two products with one RegValue each other both got installed so theirs RegValue both has the same guid therefore registry record of only one product will be removed on uninstall (specifically the first installed product).

The only workaround I've found is to inject manually generated RegValue xml snippets with different guids.

It's similar to #203 / #196 and I think component id generation for RegValues could be just the same as for File now.

**Comment by oleg-shilo** [comment]
> Now consider a situation when two products with one RegValue each other both got installed so theirs RegValue both has the same guid therefore registry record of only one product will be removed on uninstall (specifically the first installed product).

Actually I expect the registry value to stay. The component GUID comes the product ID (GUID), which  will be different for your two MSIs. Thus MSI runtime will only delete the reg value with the very last product uninstalled.

**Comment by meareindel** [comment]
Just to make it more clear - imagine that you have two installers with one RegValue with same GUID each. Install both of them, now uninstall - only registry key of first installed product will be removed, not both.

> The component GUID comes the product ID (GUID), which will be different for your two MSIs.
Yes, I've found this logic, it seems to be ok but only when you first setup and build one msi then second, not when you first setup both and then build both. I mean, making two instances of ManagedProject and then making two calls to BuildMsi() leads to using GUID of second project for other GUID generation, and this is a situation when duplicate component GUIDs could be generated for both msis. It was my situation, actually.

It's not a really issue thought considering that GUID generation feature but it would be helpful to have at least some documentation notes about that.

**Comment by oleg-shilo** [comment]
> Just to make it more clear - imagine that you have two installers with one RegValue with same GUID each. Install both of them, now uninstall - only registry key of first installed product will be removed, not both.

Correct. And this is exactly the default behavior behavior you would want. If you want the value to be deleted even if the second product is still installed you will need to set `ForceDeleteOnUninstall`. 

Note that this behavior is an MSI feature but not a WixSharp one. And this paradigm has nothing to do with the component id  allocation.

> ... it would be helpful to have at least some documentation notes about that.

Absolutely. I have dedicated the whole Wiki section for that: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming

**Comment by meareindel** [comment]
I mean if you install two products and then uninstall both of them, one of the registry value will still stay in registry - specifically the registry value of product installed second. Just because component GUID of that two registry values are identical. And reason why they are identical is WixSharp implementation of this: https://github.com/oleg-shilo/wixsharp/blob/0a26ba87121653bc915ebc33a1102bdef7e13d1f/Source/src/WixSharp/Project.cs#L310-L318

WixGuid.ConsistentGenerationStartValue is changing by the project.GUID set but not by build of that project. So when I do something like this

```csharp
var project1 = new ManagedProject(...) {GUID = <some_guid>};
var project2 = new ManagedProject(...) {GUID = <some_other_guid>};
```
and then do
```csharp
project1.BuildMsi();
project2.BuildMsi();
```

then all GUIDs for both projects are generating using <some_other_guid>. Therefore all RegValues of that projects with same index would have identical GUIDs. Of course if I using default GUID generator.

So I could just call project1.BuildMsi() before project2 instantiation to resolve the issue, but it not seems like intuitive behavior. The closest phrase in documentation I've found is "The auto-Ids are generated on the first access" and this also doesn't describe such behavior.

**Comment by oleg-shilo** [comment]
My apologies. You were right all along.

My logic was based on the assumption that any given component Id is unique within a product. But it happens to be unique globally.

To be honest I am shocked. Why on earth you would try to manage components globally instead of withing their parents (products). It's the same MSM pain all over again. 

It only confirms the my initial design decision to completely remove components from the picture by automatically assigning them. I only underestimated their nasty nature and failed to hide them globally.

Re-qualifying this issue into a defect.

Thank you for reporting it.

**Comment by meareindel** [comment]
> Why on earth you would try to manage components globally instead of withing their parents (products)

As far as I understand from the https://docs.microsoft.com/en-us/windows/desktop/msi/windows-installer-components, it is a windows installer feature by design that components could be shared between applications. The registry record from my example above should then be removed only when both products had uninstalled, not just the first one, if I correctly understood answers here - http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/Windows-Installer-Service-and-reference-counting-td702967.html - but in my case it has removed when I uninstall just the first one product if I remember correctly. I'll take some tests later to check this.

**Comment by oleg-shilo** [comment]
It was a rhetorical question. :) 

I know, they wanted us to manage components outside of their logical boundaries. That's why they have introduced Minor Upgrade, MSM and components. All these features are astonishing examples of over-engineering. And every single one of this features has been later discouraged to use (e.g. "Designed For Vista" app certification requirements). And in the latest deployment framework from MS ClickOnce they were completely removed. 

Interestingly enough for files the ability to stay after uninstall in case if the have been altered is implemented without the use of components. It's understandable, files have timestamps,  and the registry keys don't.        

All this is rather unpleasant surprise. The fix is simple though it may affect many WixSharp users. I will need to release it very carefully.

**Comment by meareindel** [comment]
Thanks, it works now. But it looks strange in result wxs files in case where two projects are set up one by one first and then built one by one second so the seed of second project is using for guid generation of components:

```xml
<Component Id="Component._...______________________________.1.53b75a360a85484e8fc531984bca09d5" Guid="520101f6-e7aa-4d4e-bf3d-0b89fd883748">
<Component Id="Registry.1.53b75a360a85484e8fc531984bca09d5" Guid="520101f6-e7aa-4d4e-bf3d-0b89d701294b">
        <Component Id="Registry.1.520101f6e7aa4d4ebf3d0b89c579bb9e" Guid="520101f6-e7aa-4d4e-bf3d-0b89dcbb2281">
        <Component Id="Component.___________________________.520101f6e7aa4d4ebf3d0b89c579bb9e" Guid="520101f6-e7aa-4d4e-bf3d-0b892f82bc63">

```

See, the first two components from above are belong to one project, and second two are belongs to second project. Guids of all four seems like from the same seed, but ids of first two contains guid substring from their project. It's not something critical though but maybe it would be better to move guid generator seed setting to the compile stage instead of project instantiation?

**Comment by oleg-shilo** [comment]
I am not sure I follow your. This is the test I did trying to replicate the problem you described:

```C#
var project1 =
    new Project("MyProduct",
        new RegValue(RegistryHive.LocalMachine, 
                    @"Software\My Company\My Product", "LICENSE_KEY", "01020304"));

project1.PreserveTempFiles = true;
project1.OutFileName = "project1";
project1.GUID = new Guid("af330b47-2577-43ad-9095-1861ba25889b");

var project2 =
    new Project("MyProduct",
        new RegValue(RegistryHive.LocalMachine, 
                    @"Software\My Company\My Product", "LICENSE_KEY", "01020304"));

project2.PreserveTempFiles = true;
project2.OutFileName = "project2";
project2.GUID = new Guid("bf330b47-2577-43ad-9095-1861ba25889b");

project1.BuildMsi();
project2.BuildMsi();
```
It generates the expected WXS.

**Comment by meareindel** [comment]
I mean all the component guids in both wxs will looks like "bf330b47-2577-43ad-9095-xxxxxxxxxxxx" meaning they are using GUID seed of second project you instantiated - not built. Though they are different, It would be more logical if component guids of first project use seed of their project.

**Comment by oleg-shilo** [comment]
It's not what I am experiencing. 

Can you please execute the very code below:
```C#
var project1 =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product", new File("readme.txt")), 
        new RegValue(RegistryHive.LocalMachine,
                @"Software\My Company\My Product", "LICENSE_KEY", "01020304"));

project1.PreserveTempFiles = true;
project1.OutFileName = "project1";
project1.GUID = new Guid("af330b47-2577-43ad-9095-1861ba25889b");

var project2 =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product", new File("readme.txt")),
        new RegValue(RegistryHive.LocalMachine,
                    @"Software\My Company\My Product", "LICENSE_KEY", "01020304"));

project2.PreserveTempFiles = true;
project2.OutFileName = "project2";
project2.GUID = new Guid("bf330b47-2577-43ad-9095-1861ba25889b");

project1.BuildWxs();
project2.BuildWxs();
```
It produces the components' ids as expected:
![image](https://user-images.githubusercontent.com/16729806/44849233-d3050f80-ac9c-11e8-9ec0-6556a0e296fe.png)

Though your experiment uncovered some peculiar behavior about empty folders but it is a different story.

**Comment by oleg-shilo** [comment]
OK found the explanation for the "empty folders" thing. But it may also address many other problems (like yours).

Call `ResetIdGenerator`:
```C#
project1.BuildMsi();
WixEntity.ResetIdGenerator();
project2.BuildMsi();
``` 

There is even setting for doing it automatically:
```C#
WixEntity.DoNotResetIdGenerator = false; // by default it's true
```

I have implemented this mechanism a long time ago but was not confident enough to enable it by default. Now  I think I should enable it...

**Comment by meareindel** [comment]
>It produces the components' ids as expected

Ids - yes, but not the guids. Take a look at your picture, left part of it, at ```<Component Id="Registry...">```. There is small starting piece of Guid - and that starts with "b", not "a".

**Comment by oleg-shilo** [comment]
Correct. It starts with "a" for project1 and with "b" for project2. This is exactly what is expected. That extra suffix in the `component.id` is the value of the parent `product.id`. Which is "af33..." for project1 and "bf33" for project2.

**Comment by meareindel** [comment]
Yes, if you talking about component "Id" property. But I mean component "Guid" property. It starts with "b" for project1 but logically should starts with "a".

**Comment by oleg-shilo** [comment]
I see. Great. 
Fixed. 

Now `WixGuid.ConsistentGenerationStartValue` is called by the compiler in every `BuildWxs`.

The fix will be available in the very next release.

**Comment by meareindel** [comment]
Thanks! By the way, there is no need to merge project guid to component ID now. At least for component guid distinguish purpose.

**Comment by oleg-shilo** [comment]
Of course. In the latest commit I have removed the merging for ids. Instead, now WixSharp starts/seeds the GUID generation with the project id (also GUID). This way the all guds are deterministic (they are all sequential) and yest globally unique - they start with initial value of the `project.Id`, which is unique by definition, just an ordinary guid.
