### ISSUE TITLE
There is no way to set virtual HKMU registry hive supported by WiX for RegValue

### ISSUE THREAD

**Issue by meareindel** [oleg-shilo/wixsharp#453]
Constructors of RegValue takes the RegistryHive enum as parameter but there is no such member.

**Comment by oleg-shilo** [comment]
![image](https://user-images.githubusercontent.com/16729806/43673506-9bd468ca-9807-11e8-87d4-e36002e3768d.png)

**Comment by oleg-shilo** [comment]
OK, I see. With the introduction of HKMU value the `RegistryKey` element can no longer be mapped with `Microsoft.Win32.RegistryHive`.

I have marked this issue as a feature request.  

Until the feature is implemented please use Xml injection to achieve the desired result.

**Comment by meareindel** [comment]
Ok, thanks!

**Comment by meareindel** [comment]
All right here, new enum contains necessary member, thanks!
