### ISSUE TITLE
How to set biggest version of Installer

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#454]
Hi Oleg, i have small problem and hope you can help me with. In my project i have 7 executables, not exeinstallers. Each exe have own version build and how do i set version of msiistaller for biggest version from one of them ?

**Comment by oleg-shilo** [comment]
It's just an ordinary C#. Do it programmatically.
```C#
// pseudo-code
project.Version = Directory.GetFiules("<whatever>", "*.exe")
                           .Select(f => f.GetVersion())
                           .Max()
```

**Comment by Torchok19081986** [comment]
Thanks. Something like that. I didnt knew if it possible.
