### ISSUE TITLE
Overwrite files

### ISSUE THREAD

**Issue by mihazelenov** [oleg-shilo/wixsharp#459]
Hi! I trying to modify my project, but after installing .config file do not replaced to new version. Why it happened?

**Comment by oleg-shilo** [comment]
By default MSI does not overwrite the existing files. Use `File.OverwriteOnInstall` if overwriting is required.

**Comment by mihazelenov** [comment]
Could you please give me a sample?

**Comment by oleg-shilo** [comment]
Something like that:
```C#
new Dir(@"Docs\Manual",
    new File(@"Files\Docs\Manual.txt")
    {
        OverwriteOnInstall = true
    }
```

**Comment by candeveci13** [comment]
Hi,

I came across a similar situation with Files class instead of File. I couldn't find OverwriteOnInstall attribute in Files. How can we solve it?

**Comment by oleg-shilo** [comment]
`Files` is a utility class for aggregating the items form a given folder. It simply creates bunch of `File` classes and it is up to you to adjust the items properties. Have a look at `ReleaseFolder` sample.

You will need something as simple as this:

```C#
new Files(@"..\Release Folder\Release\*.*")
{
    AttributesDefinition = "OverwriteOnInstall=yes"
}
```  

Though the next release will have:
```C#
new Files(@"..\Release Folder\test\*.exe")
{
    OnProcess = file =>
    {
        file.OverwriteOnInstall = true;
    }
}
```

**Comment by chancezheng** [comment]
how to set in product.wxs and bundle.wxs?

**Comment by chancezheng** [comment]
> how to overwrite when repair or modify, and how to set in product.wxs and bundle.wxs?

add RemoveFile label or set File lable's DefaultVersion= "65535.65535.65535.65535", I resolve it by myself.

**Comment by oleg-shilo** [comment]
Please use VS templates for WixSharp. They have the answers you are looking for.
