### ISSUE TITLE
Including a 3rd party exe installer

### ISSUE THREAD

**Issue by pkzOR** [oleg-shilo/wixsharp#46]
Previously, using WixSharp 1.0, we had an 3rd party exe (an installer) that was included in our source files. A custom action started the exe at the end of our install. 

Now, having upgraded to the latest via NuGet, the same project gets an error:

System.BadImageFormatException: Could not load file or assembly 'file:///C:\3rdparty.exe' or one of its dependencies. The module was expected to contain an assembly manifest.

Server stack trace: 
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String 
codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, 
StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean 
throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName 
assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, 
StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean 
throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, 
Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm 
hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, 
StackCrawlMark& stackMark)
at System.Reflection.Assembly.ReflectionOnlyLoadFrom(String assemblyFile)
at WixSharp.AsmReflector.OriginalAssemblyFile(String file)
at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage
(IntPtr md, Object[] args, Object server, Object[]& outArgs)
at 
System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage 
msg)
Exception rethrown at [0]: 
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage 
reqMsg, IMessage retMsg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& 
msgData, Int32 type)
at WixSharp.AsmReflector.OriginalAssemblyFile(String file)
at 
WixSharp.Utils.<>c__DisplayClass4_0.<OriginalAssemblyFile>b__0(AsmReflector 
asm)
at WixSharp.Utils.ExecuteInTempDomain[T](Func2 action)
at WixSharp.Utils.OriginalAssemblyFile(String file)
at WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, 
String[] refAssemblies, String outDir, String configFilePath, Nullable1 
platform, Boolean embeddedUI, String batchFile)
at WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement 
product)
at WixSharp.Compiler.GenerateWixProj(Project project)
at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
at WixSharp.Compiler.Build(Project project, String path, OutputType type)
at WixSharp.Compiler.Build(Project project, OutputType type)
at MsiBuilder.MsiBuilder.Build() ...

=> var msi = Compiler.BuildMsi(project);

Note that the 3rd party exe is listed in the project.DefaultRefAssemblies.
Ideas?

Pete

**Comment by oleg-shilo** [comment]
The error means that the assembly that has been compiled for x64 is being loaded on the x86 CLR or vise versa. Ideally you want your assembly to be compiled against "AnyCPU" this way it will adhere to the CLR CPU  type of the host/target system. 

Note, MSI runtime is always x86 even when it is running on x64 OS.

**Comment by pkzOR** [comment]
Thanks for the reply. I had looked at exactly that, but all the projects were set to AnyCPU (with Prefer 32 bit   un-check). I'll look again.

**Comment by oleg-shilo** [comment]
But what is the target CPU of that third party assembly? May be it is what is causing the discrepancy? You can check the asm CPU type with ILSpy/Reflectpor. And you can also run a hello world  msi with Wix# custom action to check what is the actual CLR type during the installation. I recon this is where the problem is.

**Comment by pkzOR** [comment]
it is an x86 exe. At which version of WixSharp did this get enforced? We were on version 1.0.16.

**Comment by oleg-shilo** [comment]
> At which version of WixSharp did this get enforced?

Wix# does not enforce anything. Actually it never did. If you are talking about "MSI runtime is always x86" then it is enforced by the MSI itself. 

The fact that your `3rdparty.exe` is x86 already indicates that it will have a conflict when loaded on x64. 

Yes I expect that MSI runtime to be always x86 but only nased on my experiments not the "promise" from MS. And I cannot exclude that under certain circumstances it can be x64 (e.g. next version of MS Installer). That is why I Wix# is compiled with neutral "AnyCPU" so it fits any OT type.

Anyway, the next step would be to verify the actual runtime on your target system is. This is how you can do it:

Create a hello world project similar to this one:
```C#
 var project =
            new Project("MyProduct",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File(...
...
project.Load += project_Load;
...
static void project_Load(SetupEventArgs e)
{
    MessageBox.Show("Hello World! (CLR: v" + Environment.Version + ")", 
                    "Embedded Managed CA (" + (Is64BitProcess ? "x64" : "x86") + ")");
}

static bool Is64BitProcess
{
    get { return IntPtr.Size == 8; }
}
```
 Run the produced MSI on your target system and you will see if it is in conflict with your `3rdparty.exe` CPU type.

**Comment by pkzOR** [comment]
Results:
Hello World! (CLR: v4.0.30319.42000) Embedded Managed CA (x86)

I think I've found the problem we're running into though:

I'm trying to include an unmanaged exe that's used by a custom action.
In the past (v1.0.16), wixSharp would build the msi, and include the 3rd party exe just fine.
In the newer versions, in ProjectValidator.cs, AsmReflector.OriginalAssemblyFile makes a call to System.Reflection.Assembly.ReflectionOnlyLoadFrom(...), in order to get the full filename.
This call doesn't work on unmanaged exes.
The commit where this changed is c46e2abba9c6b42375a9467f51a79242a1b45c1f .

How would someone go about including an unmanaged utility (like say 7zip.exe) in an install to be used by a custom action?

-----------------------------------------------
Just a note in case someone else tries this:
The project needs to be a ManagedProject and since I wasn't using a UI,  project_load was changed to:
static void project_Load(SetupEventArgs e)
		{
			e.Session.Log("Hello World! (CLR: v" + Environment.Version + ") Embedded Managed CA (" + (IntPtr.Size == 8 ? "x64" : "x86") + ")");
		}


Thanks for being so responsive!

**Comment by oleg-shilo** [comment]
Great. Of course. It all makes sense now.
You mentioned `project.DefaultRefAssemblies` meaning that you are adding assembly. This property is for the assemblies but not for unmanaged binaries.

You will need to use `Binary` or even `BinaryAction:
```C#
var project = 
    new Project("My Product",
        new Binary(new Id("EchoBin"), @"Files\Echo.exe"), 
        new Dir(@"%ProgramFiles%\My Company\My Product",
        
            new File(binaries, @"AppFiles\MyApp.exe",
                new WixSharp.Shortcut("MyApp", @"%ProgramMenu%\My Company\My Product"),
                new WixSharp.Shortcut("MyApp", @"%Desktop%")),
            
        new BinaryFileAction("EchoBin", "/i", 
                                Return.check, 
                                When.After, 
                                Step.InstallFinalize, 
                                Condition.NOT_Installed),
                                
        BinaryFileAction("EchoBin", "/u", 
                                Return.check, 
                                When.Before, 
                                Step.InstallFinalize, 
                                Condition.Installed), 
    ...
        
Compiler.BuildMsi(project);
```

**Comment by pkzOR** [comment]
Perfect! I had seen the Binary, but not the BinaryAction. 
Thanks again.
