### ISSUE TITLE
File not embeded in msi installer

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#462]
Hallo Oleg, i have some problem with my installer, since last update . 
if i dont change my file, copy and overwrite it in path, look like installer ignored file.
i use managed project and want to install or modify .xml file in path, but currently my file not going to be added to msi. 
string path  = "<path to dir with files for msi>";
... 
 new Dir("Test", 
  new File(path + "\\settings.xml"))
...
works only if i delete file and copy a newer one to path. doesnt work for just copy it and overwrite it after windows ask you for action.
How do i use something like wildcard ? Maybe  *.xml or *.exe for choosed folderstructer for my installer.
I tried it with *.xml or *.exe, but i always got error "File not found exception". 
Can you help me with this ?

**Comment by Xaddan** [comment]
Use Files instead of File
```C#
new Dir("Test",
  new Files($"{path }\*.xml"))
```

**Comment by oleg-shilo** [comment]
"_WildCard Files_" and "_ReleaseFolder_" samples are covering the cases like yours.
