### ISSUE TITLE
Strange repair package behavior with EmitConsistentPackageId=true

### ISSUE THREAD

**Issue by meareindel** [oleg-shilo/wixsharp#463]
Dear Oleg,

Consider this small code:
```csharp
class Program
    {
        static void Main(string[] args)
        {
            MakeSimpleProject();
        }

        public static void MakeSimpleProject()
        {
            var project = new ManagedProject("test", new Dir("test", new File("test.txt")))
            {
                Name = "Test",
                Version = new Version(1, 0, 0),
                GUID = new Guid("ba14b053-df9d-4054-802a-5beb30298945"),
                UpgradeCode = new Guid("71f6b809-df94-445d-9901-f28b97f3054b"),
                Platform = Platform.x86,
                InstallScope = InstallScope.perUser,
                EmitConsistentPackageId = true,
            };

            project.BuildMsi();
        }
    }
```

Here "test.txt" is permanent file with some content and it is not being modified or something through the whole issue reproduction.

And here is the repro itself:
1) Run the program above (you have to have the "test.txt" as a content file of ms vs project or do something similar).
2) Install the resulting msi - it's ok
3) Run the program again.
4) Open the resulting msi and try to repair it - you'll get the UAC prompt with red header.

Now if you close the UAC prompt, you'll see this in msi log:

```
MSI (s) (A0:50) [19:58:09:409]: SECREPAIR: Hash Database: C:\WINDOWS\Installer\SourceHash{BA14B053-DF9D-4054-802A-5BEB40299945}
MSI (s) (A0:50) [19:58:09:414]: SECREPAIR: filename: test.msi Stored Hash Value:AruGD6dzI3Aet7a3ddUtTGM7yHHK7KcpELt8O9Ywg3w= Current Hash:gLl5Aen6H6xqFeOK95rq2TZTjrPS2fRvJHsbXMz7Pxg=
MSI (s) (A0:50) [19:58:09:414]: Machine policy value 'AlwaysInstallElevated' is 0
MSI (s) (A0:50) [19:58:09:414]: User policy value 'AlwaysInstallElevated' is 0
MSI (s) (A0:50) [19:58:12:840]: MSI_LUA: Credential Request return = 0x800704C7
MSI (s) (A0:50) [19:58:12:840]: Note: 1: 3 
MSI (s) (A0:50) [19:58:12:840]: SECUREREPAIR: SecureRepair Failed. Error code: 3C44E5F0
```

And even if you click "Yes" in the UAC prompt, msi'll say that installation was successful but running repair next time will show UAC prompt again and again. Furthermore, package won't be repaired in silent mode as the UAC prompts disabled in that case.

I suppose that this is not the WixSharp issue though but there is no clue in google about how to disable this SecureRepair or something. So maybe you can shed some light on this.

**Comment by oleg-shilo** [comment]
Something that immediately comes to my mind is that you can run your repair as elevated process. Then you will not be prompted tor elevation and your UAC prompt will not interfere with your MSI UI (silent in this case).

A simple use-case to test is to have an **elevated** shortcut to `msiexec.exe` with the "repair args" (don't remember exactly what they are). When you run such a shortcut the elevation will be triggered before msi session starts. Meaning that it will not require another elevation. I expect this to work. But...  let me know...

**Comment by oleg-shilo** [comment]
BTW, I don't think `EmitConsistentPackageId=true` has anything to do with the problem you are trying to solve. This setting simply ensures that if you build your MSI twice without any changes between the builds the two msi files produced by your builds are binary identical.

**Comment by meareindel** [comment]
> you can run your repair as elevated process

Yes, but it would be strange for per-user installation.

> the two msi files produced by your builds are binary identical

It seems they are not, considering messages from repair log - at least they has different hashes.

Looks like I need to post my question to wix mailing list but I doubt they could help me considering warning in candle with ```EmitConsistentPackageId=true``` :)

Anyway, thanks for answers.

**Comment by oleg-shilo** [comment]
> It seems they are not, considering messages from repair log - at least they has different hashes.

Interesting... 

I just did the test. I have build two msis from the same codebase with `EmitConsistentPackageId=true`. They are the same from install/uninstall point of view. I can install product by executing msi-1 and then right-click msi-2 and uninstall this very same product. This operation would trigger the error if `EmitConsistentPackageId=true` is not set.

However both msis are not identical from upgrade point of view. I haven't try but this is what you discovered. And.... when I checked the msis with KDif3 it found them different as well. It looks like WiX/msi compilers still inject something during the build.

I found this MSi/WiX behavior fundamentally flawed. Imagine this, you built an msi and released it to the public. Now you need to rebuild it to troubleshoot the user reported defect - build 100% identical msi. Nah! Impossible. MSI team knows better... Frankly this patronizing attitude is annoying, at least.
