### ISSUE TITLE
Alternate install directory during setup

### ISSUE THREAD

**Issue by SamoilovVV** [oleg-shilo/wixsharp#468]
Hello, Oleg!
I'm making plugin for a CAD system and wish to make installer based on wix#.
It's works great, but I would like to add choises for different CAD versions and AllUsers/CurrentUser setup option. Install path for each option will be different.
I can't find example for such scenario and I'm stucked with it. How can I alternate install path during setup depending on user choice?

**Comment by oleg-shilo** [comment]
Have a look at "InstallDir_DynamicPath". It shows how to set the dir(s) dynamically.

```C#
static public void Main()
{
    var project =
        new ManagedProject("MyProduct",
            new Dir(new Id("DIR1"), "root1", new File("setup.cs")),
            new Dir(new Id("DIR2"), "root2", new Files(@"files\*.*")));

    project.UI = WUI.WixUI_ProgressOnly;
    project.Load += Project_Load;

    project.BuildMsi();
}

static void Project_Load(SetupEventArgs e)
{
    e.Session["DIR1"] = @"C:\My Company1";
    e.Session["DIR2"] = @"C:\My Company2";
}
```
If you want o give your user the choice of customizing both of them then you will need to customize the install dir selection dialog with an extra install dir text box.

As for AllUsers/CurrentUser you can use stock dialog InstallScopeDialog.  It already has the required radio-buttons wired.

Thu just create a new project form WixSharp project template:

![image](https://user-images.githubusercontent.com/16729806/45088406-3afba000-b14c-11e8-91a8-fd516bd96358.png)

And after that just modify 'InstallScopeDialog' as required

**Comment by SamoilovVV** [comment]
Thanks a lot, I modify stock InstallScopeDialog and it works like a charm.
But if plugin installed for AllUsers - uninstalling not working.
It seems that uninstall happens from a path for CurrentUser, specified on project creation:
new ManagedProject(@"MyPlugin",
                             new Dir(new Id("DIR_DEPLOY"), @"%AppData%\ApplicationPlugins\MyPlugin\", 
                             new DirFiles(@"..\..\MyPlugin\bin\Release\*.*", IsFileToInclude)));
