### ISSUE TITLE
Execute .batch from RessourceManager

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#47]
Hallo Oleg, i need some help with execute a batch file from Ressourcesmanger in my ManagedProject.
Situation: i have dll in my project and i have to register mydll as com-object. I tried heat.exe  file mydll.dll -out mydll.wxs, but after installation dll is not registered as com.
My workaround was with write batch which run regasm,exe and register mydll as com. Here i need some help. 
How can i execute .batch during installation ? CustomAction maybe ? What should i do in Return, Step and Condition ? Some codeexample would be good. Thanks for your help.

**Comment by oleg-shilo** [comment]
Is this a duplicated post? I am sure we have already discussed this topic. May be on CodePlex?

**Comment by Torchok19081986** [comment]
i hope not. I had only one Question on Codeplex for Wix#.    -.-
My Problem is that i myAddins are COM Assembly and should be registred with RegAsm.exe . 
There is no possibility reg my assembly as com during install. May be i shoult start RegAsm.exe from Target and register my assembly After the Installation. 
Only one Question, can i start another Process after installation like Regasm.exe in CustomAction ? 
CustomAction would seen like Process.Start (<Path to regasm.exe>, "myassembly.dll" )  maybe ?

**Comment by oleg-shilo** [comment]
OK may be it was someone else contacting me directly.

Anyway, I suggest you do it in post install event. It is nothing else but a more convenient deferred CA. You will be already elevated. You will know the the install dir location....
Have a look at  ["setup events" sample](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/SetupEvents/setup.cs).

**Comment by oleg-shilo** [comment]
Finding regasm.exe location will be something like this:
```C#
string dot_net_dir = Path.GetDirectoryName("".GetType().Assembly.Location);
string regasm_exe = Path.Combine(dot_net_dir, "regasm.exe");

```

**Comment by Torchok19081986** [comment]
thanks for info. I will try it so.
