### ISSUE TITLE
Upgrades Installing Side-By-Side

### ISSUE THREAD

**Issue by OptrixAU** [oleg-shilo/wixsharp#471]
This may be a better question for the Wix project itself, but I'm having an issue with upgrading.

When I update my version number and build an installer, it installs _along-side_ the earlier version. It's treating it as if my UpgradeCode had changed between builds, instead of just my ProductCode.

So instead of uninstalling the old version and installing the new, I end up with _two_ copies in my "Add and Remove Programs" screen. Then three, then four etc.

Do you have any idea what could be causing this? I've double-checked and the UpgradeCode appears to be the same between all installers, it's simply the Product ID and Version that changes. 

The first WXS...
```xml
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="<GUID INTRO>-a2e7bd2da12d" Name="ARDI VE" Language="1033" Codepage="Windows-1252" Version="0.9.9.2991" UpgradeCode="<GUID INTRO>-a2e7bd9d067d" Manufacturer="Me">
```

The second WXS...
```xml
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="<GUID INTRO>-a2e7bd2da51d" Name="ARDI VE" Language="1033" Codepage="Windows-1252" Version="0.9.9.3999" UpgradeCode="<GUID INTRO>-a2e7bd9d067d" Manufacturer="Me">
```

Code...

```c#
            project.GUID = new Guid("<GUID INTRO>-a2e7bd9d067d");
            project.Version = new Version("0.9.9.3999");
            project.Platform = Platform.x64;
            
            project.MajorUpgradeStrategy = new MajorUpgradeStrategy
            {
                UpgradeVersions = VersionRange.OlderThanThis,
                PreventDowngradingVersions = VersionRange.NewerThanThis,
                NewerProductInstalledErrorMessage = "A newer version of this product is already installed.",
                RemoveExistingProductAfter = Step.InstallInitialize
            };          
```

Does anyone have an idea what on earth is going on and why it doesn't attempt an upgrade?

**Comment by OptrixAU** [comment]
Found a previous, similar issue. Changed the code setting the update strategy to the below...

```c#     
            project.MajorUpgrade = new MajorUpgrade
            {
                Schedule = UpgradeSchedule.afterInstallInitialize,                
                AllowDowngrades = true,
                IgnoreRemoveFailure = true,
                AllowSameVersionUpgrades = false
            };
```

...and the issue seemed to go away - it uninstalled all of the (many) previous versions.

**Comment by oleg-shilo** [comment]
Good. You found it. Read more here: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#product-upgrades

> MajorUpgradeStrategy yields WiX UpgradeVersion element, which is arguably the most comprehensive upgrade definition. However in the later versions of WiX a simplified upgrade definition has been introduced. It relies on MajorUpgrade WiX element. For most of the upgrade scenarios you will find MajorUpgrade allows achieve the same result with much less effort. Wix# supports MajorUpgrade element via MajorUpgrade member.
