### ISSUE TITLE
WPF Bootstapper

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#472]
Hi Oleg, this may be not issue, but i really have to understand bootstapper of Wix#.
I found WPF Bootstrapper in Samples and this works fine. Endproduct is .exe, great. 
In Code msi going to be create and embeded in exe and execute after extract to temp. Is correct ?
Q1: Can msi be added from path ? 
There ist Checkbox for Installdocumentation.
Q2: Is there some posiblity to add install .net framewrok Version XYZ and may be database? 
Q3: Each Checkbox will be proved to install feature, am i right ? How install bootstapper checked feature , one after another  ? 

10.09.18: I tried bootstapper in windows forms and wpf. in Windows forms exe after double click, start msi and i see what msi going to do like normal installation. May be it has to do with DisplayinternalUI = true. In WPF exists this also. 
In WPF installation perform silently or not show to user? How do i in WPF same like in win forms ?

**Comment by oleg-shilo** [comment]
Missed this one...

> Q1: Can msi be added from path?

Yes
```C#
string productMsi = productProj.BuildMsi();
...
var bootstrapper = new Bundle("My Product",
                       new PackageGroupRef("NetFx40Web"),
                           new MsiPackage(productMsi)
```

> Q2: Is there some posiblity to add install .net framewrok Version XYZ and may be database?

``C#
new PackageGroupRef("NetFx40Web"),
```
Though the name (e.g. `NetFx40Web`) is always a predefined WiX Burn constant.  Alternatively you can ass a package with the URL pointing to the .NET installer to download and execute.


> Q3: Each Checkbox will be proved to install feature, am i right ? How install bootstapper checked feature , one after another?

Bootstapper does not understand the feature concept. It works with products. The responsibility to manage the features is still on individual MSIs. You can let your MSY to show it's GUI and this will pop the FeatureSelection dialog. Otherwise provide the checkboxes in tyour custom BA and tunnel all user selected features to the msi.

Mind you WiX has a bug that prevents showing the msi UI unless it is a native stock UI. They plan to fix it in WiX 4.0.

And... yes you control msi UI with 'DisplayinternalUI = true'

**Comment by Torchok19081986** [comment]
Thanks Oleg for answers. I know now how to create wished bootstapper. Last Question here: how do i create not SilentBootstapper like Bootstrapper, because myproduct install always silent. I create a sample like your WPF Bootstapper und here is silent. Work fine, but i cannot choose new installdir like in "normal" Bootstapper.

**Comment by oleg-shilo** [comment]
Sorry, I may be misinterpreting you question. I understand that you want to create a bootstrapper that has UI and you want your embedded msi to receive some user input collected with the bootstrapper own UI.

If it is the case then have a look at Bootstrapper_UI sample here on GitHub.

I just have updated the Bootstrapper_UI sample to show how to pass user input from BA to MSI package.

**Comment by Torchok19081986** [comment]
Many thanks Oleg. I going to try it.

**Comment by Torchok19081986** [comment]
I solve my proble mit Bootstapper. Error comes only if you use 3.11.X and 4.0 Wix Toolset Binaries at same time. WixToolset.Dtf.WindowsInstaller.dll is part of Wix toolset V 4.0. In 3.11 is dll not exists. Unfortenally only completly uninstall both of wix toolset in V 3.11 and 4.0 can help. Wix sharp doesnt recognize after uninstalling wix toolset V4 binaries for compile msi.

**Comment by hvandrie** [comment]
![image](https://user-images.githubusercontent.com/13115360/127357664-e997ee3a-a2c8-429f-839e-e831c41db08e.png)

Ran into same issue, and you can have both WiX 3.x and 4 installed at the same time. However, it is needed to change the environment variable WIX to point to the WiX 3.x path:

setx /M WIX "C:\Program Files (x86)\WiX Toolset v3.11\"
![image](https://user-images.githubusercontent.com/13115360/127357949-c223d948-85d2-4f05-8925-fc83398b044e.png)


Restart VS, and you're good to go to build.

**Comment by oleg-shilo** [comment]
Or you can also set global envar `WixLocation` This one is specific for WixSharp so setting it will not interfere with anything else
