### ISSUE TITLE
Value of Custom Property is not updated when using in ElevatedManagedAction

### ISSUE THREAD

**Issue by sven-weber** [oleg-shilo/wixsharp#473]
Hi, 

I currently have a problem with the values of own Properties during the execution of a ElevatedManagedAction. 

Via the ManagedProject I defined a Property named APIPORT: 

```csharp
Project.Properties = new Property[]
{
       new Property
       {
              Name = "APIPORT",
              Value = "8080"
       }  
}
```

This Property is then updated in a custom UI and later used in a ElevatedManagedAction: 

```csharp
 void next_Click(object sender, EventArgs e)
 { 
      MsiRuntime.Session["APIPORT"] = NumericPort.Value.ToString();
      Shell.GoNext();
 }
```

```csharp
 new ElevatedManagedAction(AdjustApplicationPortInConfig, Return.check, When.After, Step.InstallFiles, Condition.NOT_Installed)
 {
     UsesProperties =  "CONFIG_FILE=[INSTALLDIR]\\Web.config, BINDING=http://localhost:[APIPORT]"
 }, 
```

As you can see I also use the pre defined Property INSTALLDIR in that action. 

When changing the INSTALLDIR Property value via the InstallDir Dialog, the value is also changed during the execution of the custom action. Unfortunately the custom Property is not updated. When using it in the custom action it remains on its default value 8080. 

I already let the custom UI prompt the new value of the property after it was changed and the correct value was prompted. 

I also tried to first execute the custom Dialog and than the InstallDir Dialog as it may be a issues of dialog order but that also did not change the behavior. 

The third thing I did was to take a look at the InstallDir Implementation to see if any Method is called in order to update the Propertys value in deferred actions but that does not seem to be the case. 

If any more Information is needed I'm happy to provide it. 

Maybe someone has an idea where the Problem could be located.

**Comment by oleg-shilo** [comment]
It doesn't look right. Might be a defect. Will investigate it....

**Comment by oleg-shilo** [comment]
After some thinking...

Try to use events. `Project.AfterInstall` is elevated. Have a look at "Setup Events" sample it show a few ways of tunneling the custom property value into the elevated action (e.g. `project_AfterInstall` handler).

**Comment by sven-weber** [comment]
Hi Oleg, 

thanks for the reply! 
I tried using the Project.AfterInstall event and specifying the Properties via DefaultDeferredProperties 

```csharp

setup.Project.DefaultDeferredProperties += ", APIPort, INSTALLDIR"; 

´´´´

Unfortunately the result is the same. No Property update.. 
Maybe there is something wrong in my way of setting the property in the custom UI? 

Or is there something I can trigger to remap the Deferred Properties?

**Comment by sven-weber** [comment]
Hi Oleg, 

thanks for the response. 

Your response seems to be working out for me. 

I will close the issue. Thanks again!

**Comment by shengxue** [comment]
@oleg-shilo 

My codes are like below.  I set ```Host.Shell.MsiRuntime().MsiSession[Constants.SET_AS_STARTUP_PROGRAM] ``` in custom UI, but  neither ```CustomAction``` nor ```project_BeforeInstall``` can read it.   any idea on it?

``` csharp
          var project = new ManagedProject("My product" )
            {
                 ManagedUI = new ManagedUI(),
                Properties = new Property[]
                {
                    new Property
                    {
                        Name = "SetAsStartupProgram",
                        Value = "false",
                        IsDeferred = true 
                    }  
                },
            };

 
         project.BeforeInstall += project_BeforeInstall;
        project.AddAction(new ManagedAction(CustomActions.RegisterAsStartupProgram, Return.ignore, When.After,
                Step.InstallFinalize, Condition.NOT_Installed));
         }

         static void project_BeforeInstall(SetupEventArgs e)
        {
            if (!e.IsInstalling)
                return;

            MessageBox.Show( $"project_BeforeInstall: {e.Session.Property(Constants.SET_AS_STARTUP_PROGRAM)}");
        }
```
``` csharp
   public class CustomDialogModel : Caliburn.Micro.Screen
    {
        public ManagedForm Host { get; set; }

        private bool _setAsStartupProgram;

        public bool SetAsStartupProgram
        {
            get => _setAsStartupProgram;
            set
            {
                MessageBox.Show($"SetAsStartupProgram: {value}");
                _setAsStartupProgram = value;
                Host.Shell.MsiRuntime().MsiSession[Constants.SET_AS_STARTUP_PROGRAM] = _setAsStartupProgram ? "true" : "false";
            }
        }

        public void GoPrev()
            => Host?.Shell.GoPrev();

        public void GoNext()
            => Host?.Shell.GoNext();

        public void Cancel()
            => Host?.Shell.Cancel();
    }
```
``` csharp
        [CustomAction]
        public static ActionResult RegisterAsStartupProgram(Session session)
        {
            session.Log($"Begin {nameof(RegisterAsStartupProgram)}");

            MessageBox.Show( $"RegisterAsStartupProgram {session.Property(Constants.SET_AS_STARTUP_PROGRAM)}");
            
            return ActionResult.Success;
        }
```

**Comment by oleg-shilo** [comment]
Great. happy it all worked out
