### ISSUE TITLE
Custom Logic for SilentBootstrapperApplication

### ISSUE THREAD

**Issue by zeburrehman** [oleg-shilo/wixsharp#475]
Hi,

I want to create a bootstrapper for my application. I've used SilentBootstrapperApplication for Build calss Application property.  Following is the code.

`bootstrapper.Application = new SilentBootstrapperApplication();`

where as bootstrapper is Bundle class object, and this works fine. But...

**What I Want?**
I would like to have a hook where i could write my code (custom logic). This hook (event) should be called (raised) at the start of bootstrap execution. I would like to have some custom logic over there.

**What I Did So Far**
After looking at the code samples and searching a bit on internet i have implemented following solution. I wrote my own implementation of _ManagedBootstrapperApplication, IWixSharpManagedBootstrapperApplication_ which accept the my implementation of _BootstrapperApplication_ in constructor. In my custom BootstrapperApplication i can hook startup event in Run method. For implementaton i've picked up the same implementation as on WixSharp repository (fro file SilentBA). I updated my above line as follwing

`bootstrapper.Application = new MySilentBootstrapperApplication();`

But now i'm getting following error in my log file when i run the bootstarp exe.

> [3F50:1338][2018-09-17T21:58:51]e000: Error 0x80131018: Failed to create the managed bootstrapper application.
> [3F50:1338][2018-09-17T21:58:51]e000: Error 0x80131018: Failed to create UX.
> [3F50:1338][2018-09-17T21:58:51]e000: Error 0x80131018: Failed to load UX.

Kindly can someone guide me, where am i going wrong? Or is there any way i can override my implmentation of BootstrapperApplication in SilentBootstrapperApplication (which is passed in constructor).

**Comment by zeburrehman** [comment]
Hello,

I was able to fix this issue. In order to make it easy for future usability purpose, I will share my solution here. 
It was more Wix oriented issue instead of WixSharp. In order to implement your custom BootstrapperApplication implemtation, you have to add an assembly attribute 

> [assembly:  BootstrapperApplication(typeof(MySilentManagedBA))]

You might have to face one other issue after implementing that. 

> Bootstrapper Error 0x8013101b: Failed to create the managed bootstrapper application.

and this is cuased due to entry in default _BootstrapperCore.config_ file. You have to place your own _BootstrapperCore.config_ file and need to remove following entries

```
<supportedRuntime version="v2.0.50727" / >
<supportedFramework version="v3.5" runtimeVersion="v2.0.50727" />
```
For more details about issue you can have a look at this  [link](http://devdare.blogspot.com/2014/05/bootstrapper-error-0x8013101b-failed-to.html)

One more thing you can do instead of writing all code is to pick up the implmentation of SilentBA.cs and create pass on you custom config file in constructor of SilentBootstrapperApplication just like following

```
 public MyCustomSilentBootstrapperApplication(string primaryPackageId)
            : base(typeof(SilentManagedBA).Assembly.Location, "BootstrapperCore.config")
        {
            PrimaryPackageId = primaryPackageId;
        }

public MyCustomSilentBootstrapperApplication()
            : base(typeof(SilentManagedBA).Assembly.Location, "BootstrapperCore.config")
        {
        }
```

And then change following line in your bootstrapper.

`bootstrapper.Application =  new MyCustomSilentBootstrapperApplication(),`

Hope this will help you.

Thanks

Zeb ur Rehman

**Comment by oleg-shilo** [comment]
Great,

I have updated the code 'WixBootstrapper_UI' sample with your settings:

```xml
<wix.bootstrapper>
    <host assemblyName="WixBootstrapper_UI">
        <supportedFramework version="v4\Full" />
        <supportedFramework version="v4\Client" />

  <!--You may consider alternative settings.
      See these discussions: 
        - https://github.com/oleg-shilo/wixsharp/issues/416 
        - https://github.com/oleg-shilo/wixsharp/issues/389-->
            
    <!--<supportedFramework version="v3.5" runtimeVersion="v2.0.50727" />
        <supportedRuntime version="v2.0.50727" />-->
    </host>
</wix.bootstrapper>
```

Please also be aware that you can replace the the content of the "*.config" even without specifying a custom file for that. You can use 'ManagedBootstrapper.DefaultBootstrapperCoreConfigContent', which also have the links to the same solution that you shared: 
![image](https://user-images.githubusercontent.com/16729806/45748640-b7ae7400-bc4c-11e8-905d-6155871fbe44.png)
