### ISSUE TITLE
Set WebAppPool attributes using Properties

### ISSUE THREAD

**Issue by bks11** [oleg-shilo/wixsharp#477]
Hi, Oleg.
I had a problem using the properties to pass the values to WebAppPool.Attributes
Why I can`t use the following construction            

```
new User(new Id("USER_SYSTEM_SITE"), user, "cup.tea", "DOMAIN")
new Property("AUTH_TYPE", "other")   //ApplicationPoolIdentity
WebAppPool = new WebAppPool
(
  "LyncPresenceWebMvc",
   "Identity=[AUTH_TYPE]; User=USER_SYSTEM_SITE"
)
```

In this case I have the following error:
_Error		The iis:WebAppPool/@Identity attribute's value, '[AUTH_TYPE]', 
is not one of the legal options: 'networkService', 'localService', 'localSystem', 'other', or 'applicationPoolIdentity'.	
MvcAdminPackageInstaller	..\Workdesk.wxs	48_	

The same code  with WebSite  work without problem
```
 new IISVirtualDir
            {
                Name = "LWebMvc",
                AppName = "LWebMvc",
                WebSite = new WebSite("[IIS_SITE_NAME]", "[IIS_SITE_ADDRESS]:[IIS_SITE_PORT]") { InstallWebSite = true },
                WebAppPool = new WebAppPool("LyncPresenceWebMvc", "Identity=other; User=USER_SYSTEM_SITE")
            }
```

Could you please give us any ideas on this.

Thank you.

**Comment by oleg-shilo** [comment]
I am not really sure as some WiX XML elements/attributes allow referencing properties while others don't. I suggest you analyse your generated WXS and see which element-attribute combination upsets the compiler.

Then verify with WiX doco if that attribute allows referencing props.

**Comment by bks11** [comment]
Thank you very much for the response and the link.
I missed this information in mind.
Maybe you can advise how to dynamically change the value of  "Identity", depending on the choice of conditions in the dialog box. 

In CustomDialog I set property
```
void next_Click(object sender, EventArgs e)
{
	MsiRuntime.Session["AUTH_TYPE"] = "other";// applicationPoolIdentity
	Shell.GoNext();
}
```
Depending of value of this Property["AUTH_TYPE"] during the events Load and (or) BeforeInstall I try set values. 
But value not update

```
Dictionary<string, String> appPoolAttr = new Dictionary<string, string>();            
appPoolAttr["Identity"] = "applicationPoolIdentity";
clientAppPool.Attributes = appPoolAttr;
```
Same code i try in CustomAction

```
new ManagedAction(
  CustomActions.ModifyIdentity,
  Return.check,
  When.Before,
  Step.InstallFiles,
  Condition.Always )
```

**Comment by oleg-shilo** [comment]
Unfortunately you cannot do it truly dynamically as MSI/WiX simply requires you to make this decision at compile time.

The only two possible works around are:
- In `AfterInstall` even handler programmatically change the app_pool identity (e.g. registry/config file modification, ) 
- Define two nearly identical `IISVirtualDir` with two different 'identity' settings. Associate each `IISVirtualDir` with a dedicated `Feature` enable only one of them depending on the runtime condition (e.g. User CheckBox). Or let the User Experience follow the normal feature selection case in the stock UI.

**Comment by bks11** [comment]
Thank you for the advice. I will try to implement this solution.
