### ISSUE TITLE
Automatic merge modules finding with right visual studio version

### ISSUE THREAD

**Issue by marcobeninca71** [oleg-shilo/wixsharp#478]
Dear Oleg
This is a question (or a request?). In my WixSharp code I use the Merge class to include in my installation a VC redist package. The merge modules are inside the directory

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Redist\MSVC\<version>\MergeModules

Till now everything is fine. Today I installed the new update of Visual Studio 2017 and the above directory changed and the old one no longer exists. So I need to point to a new directory to find the merge module.

Is there a way to find the actual version of Visual Studio and dynamically build (in code) the above path to always point to an existing location?

Best regards
Marco

**Comment by oleg-shilo** [comment]
Of course. The major point of WixSharp - you have the power of C# at your disposal.

Probe a few expected VSCode locations (it looks like you already know them). And based on the probing outcome build your merge module path:

```C#

string MergeModulesLocation
{
   get
   {
       // probe a few dirs
       return "whateverdir";
   }
}
. . .
var project =
        new Project("MyMergeModuleSetup",
            new MediaTemplate { CompressionLevel = CompressionLevel.none, EmbedCab = false },
            new Dir(@"%ProgramFiles%\My Company",
                new Merge(featureB, MergeModulesLocation.PathCombine("MyMergeModule.msm")),
                . . .
```

**Comment by marcobeninca71** [comment]
Great Oleg
I was not sure about that because WixSharp code is not executed but interpreted during compile time.
Thanks again
Marco
