### ISSUE TITLE
Too long names on including files using new Files()

### ISSUE THREAD

**Issue by smth-mn** [oleg-shilo/wixsharp#481]
Hi
At the moment I'm trying to create installer for small portable app. So, i have to put in it some pieces of used soft. Trying to avoid manual addition i used 
`new Dir(
         new Id("arango_database"),
         new Files(@"..\..\arango_database") { IncludeMask = "*" }
)`
expecting that this would simply include all the files form `..\..\arango_database` into the msi.

Unfortunately, this code breaks all the installer throwing 
`System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`
By the way, adding files manually works well.

So, the only thing i try to comprehend is how WixSharp creates filenames files added in such style.

**Comment by oleg-shilo** [comment]
Th error means that the some files with too long names are picked by the `Directory.GetFiles(@"..\..\arango_database", "*", SearchOption.AllDirectories)`, which is in essence the algorithm behind `ResolveWildCards`.

You can solve this problem by filtering out the files that you don't need:
```C#
new Files(@"..\..\arango_database\*", x => x.Length < 260) 
```

BTW you need to include the mask in the path:
![image](https://user-images.githubusercontent.com/16729806/46078026-43d51400-c1d6-11e8-9511-9e48c8f62a37.png)

**Comment by Xaddan** [comment]
Try this:
```C#
Project.SourceBaseDir = @"..\..\"
...
new Dir(new Id("arango_database"),
 new Files(@"arango_database\*")
```

**Comment by smth-mn** [comment]
Wow, now it works fine!

By the way, seems like I've found (elegant?) way to deal with too long filenames in portable apps.
The solution is to pack all necessary files into some kind of archive (.zip or smth like thas) and then put it into created .msi with binaries of any extracting tool. On installation the only thing you'll have to do is to run script that extracts data from archive.

Still can't comprehend, how it works, but it does.
I believe the answer lies somewhere on the low-level of operation system work, where filenames restrictions are not so strict.

**Comment by Xaddan** [comment]
All the matter in the formation of the path to the files.
For example, you have such a project structure:
Project: `D:\project\arango\arango.sln`
Bin files: `D:\project\arango\bin\Release\arango.exe`
Database files: `D:\project\arango\arango_database\`

When you specify `new Files (@"..\..\arango_database\* ")`, the following path is created: `D:\project\arango\bin\Release\..\..\arango_database\* `

But if you specified `Project.SourceBaseDir = @"..\..\"` then the path is preformatted to `D:\project\arango`, and as a result it will be as follows: `D:\project\arango\arango_database\*`

**Comment by oleg-shilo** [comment]
@Xaddan is correct.
There are two points in your code that you may want to address:
1. The path expression that you pssto the `Files` constructor. It must include your wild-card mask. 
2. Regard;less what is the real set of files you are trying to include you may get too-long file names. The best. If it is the case you need to come up with the strategy hoe to deal with them. This task is outside of WixSharp/WiX/MSI. If you approach is just to exclude these files then you need to use filters like this one:
    ```
    new Files(@"..\..\arango_database\*", x => x.Length < 260) 
    ```

The chances are that if you address point 1 you will no longer experience too-long names. But only test will tell.

**Comment by smth-mn** [comment]
Got it all.

The issue I struggled with was not the one that @Xaddan described. There were trully huge names in disgusting style. Something like 

> ...\node-server\node-v9.4.0-win-x64\node_modules\npm\node_modules\npm-registry-client\node_modules\concat-stream\node_modules\typedarray\test\server\...

By the way, found it in portable version of nodejs.

So there were no way to add such files to .msi
Moving the structure to the root folder was not the proper solution. It even spoiled the situation more cause in that case installer failed not on the step of creation, but on the remote pc on installation stage. 

The only way I found to deal with that situation was to encapsulate such files into an archive and unwrap all the stuff during installation, as I've told before.  Any better ideas?)

**Comment by oleg-shilo** [comment]
Ah... Node.js. Yes it's an ugly beast to deploy. 

This is truly off topic and you need to follow the Node.js app deployment guideline. 

Normally you do not deploy `node_modules` but only your app modules. all dependency modules (including node.js core modules) are to be installed either with node.js itself or with `node install` command, which does pull all dependency packages (modules) found in your app `package.json` file.
