### ISSUE TITLE
Files Replace or OverwriteOnInstall

### ISSUE THREAD

**Issue by SFC-Sarge** [oleg-shilo/wixsharp#482]
How to doe this but with Files?

new Dir(@"Docs\Manual",
    new File(@"Files\Docs\Manual.txt")
    {
        OverwriteOnInstall = true
    }

i.e. new Files(@"..\WksUpdateRSSUsbBootDrive\bin\x64\Release\*.*", f => !f.EndsWith(".exe")

**Comment by SFC-Sarge** [comment]
Is this what you have to do?

            project.AllFiles.ForEach<File>((f) => f.OverwriteOnInstall = true);
            project.ResolveWildCards();

**Comment by SFC-Sarge** [comment]
Yes it works.

**Comment by oleg-shilo** [comment]
This post is ultimately self-sufficient :o)
Thank you for sharing
