### ISSUE TITLE
Error 1603 during install

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#483]
Hallo Oleg, i have problem in my new installer. i got some new dlls for my new setup, which are reloved in load event. i use 
AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(CurrentDomain_AssemblyResolve) 
event and here in event i load my dll into memory like : Assembly.Load(mynewassemblyasdll.dll). After i try execute code for validation which comes from dll msi crashed without some errors or messages. Only in Eventlog are error of my product with 1603. Is this possible to do it like this or do i need custom BA aka Burn for this ? Only question: how do i use it in BA? Some Samples ?

**Comment by Torchok19081986** [comment]
Problem exists only if i tried to load my new Assembly and execute some code from this Assembly. 
All tries and some research says that i need to use event ResolveEventHandler, but here doesnt work it. 
I give up on this, looks like as it not possibly execute some  code from third party dll during installtion in msi. MSI doesnt recognize this dll for code. Always Exception: Assembly XYZ or some dependecies was not found. Bootstrapepr, not tried.

**Comment by oleg-shilo** [comment]
Have a look at "DTF_ExternalAssembly" sample. 
It is about your use-case.

**Comment by RachelXGanon** [comment]
DTF_ExternalAssembly - have a link?
