### ISSUE TITLE
No way to correctly determine installation directory in created project dirs collection

### ISSUE THREAD

**Issue by meareindel** [oleg-shilo/wixsharp#488]
Dear Oleg,

I have a situation when I need to make project dirs hierarchy first and then slightly extend it (add file shortcuts, file associations, some other directories) basing on some external conditions. To do this I need to know what directory is installation directory. It's also noteable that I'm using the ```public Dir(Id id, string targetPath, params WixEntity[] items)```overload to make root directory of project, and the ```targetPath``` usually looks like "%ProgramFiles%\some\other\folders\hierarchy".

Here are what I've tried to achieve my needs:
1) First of all I've tried to find the right dir among all project dirs by it's id which explicitly set to "[INSTALLDIR]". It works but WiX# compiler output then contains warning about pregenerated ids because first access to Id property of dir invokes generation of that Id.
2) Secondly I've noticed the ```IsInstallDir``` property but unfortunately it turned out that it's getter is internal. Then I've tried changed ```Dir``` class to ```InstallDir``` in creation of root directory and then tried to find the right dir by check if it is of ```InstallDir``` type. But it was not the right dir suddenly because I've used composite targetPath as I described above so it parsed to several ```Dir``` instances and the InstallDir instance I've found contained the right dir in its ```lastDir``` protected field. And even if the ```IsInstallDir``` property getter was public it would gave me nothing because my real installation dir is not the leaf dir in dirs hierarchy at that moment so there is no way to correctly determine it.

Of course I could use reflection but it's not the right way also. So the only solution I see is to manually split ```targetPath``` to individual folders and add them sequentially to the hierarchy. But isn't there some simpler way to achieve this?

**Comment by oleg-shilo** [comment]
Because you have used explicit id in your `Dir` constructor the property name "INSTALLDIR" has no longer any meaning in your project anymore. Thus you need to your "id" instead. 

You can find some useful info here: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#installation-directory.

`IsInstallDir` has no getter for a reason. The `Dir` object that you are looking for is not always the one that you have created with `IsInstallDir = true`.
