### ISSUE TITLE
Same product different Upgrade code

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#489]
Hallo Oleg, you are master in msi and i hope you can give me some info about it. 
Scenario: same product but co-worker used different upgrade code for each installtion of software. 
do msi ovewrite upgradecode if i manually install product in same path or not ? upgradecode have to be same , that msi can found it and make update, but what to do if i have different  upgradecode for same software? Means i have to uninstall it and install all installions with new upgradecode and there is not another way like get Upgradecode in Registry and use it in msi for update or may be force msi to change upgradecode for software by name something like this ? Thanks for info Oleg.

**Comment by Torchok19081986** [comment]
After some investigation i founded that uninstall by productcode and "update" or upgrade by upgradecode. if i tried to install msi for same product and different upgradecode, it looks like msi search for product by productcode and appears message that product already installed use add/remove programm to uninstall it. 

Question: is it possible to search product by product code then uninstall it and install new Version ? 
I tried it in CustomAction , but in event msi_load not posible. Message appears from before always.

**Comment by oleg-shilo** [comment]
If your two msis have incompatible ProductUpgradeCode (read more [here](https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming) ). 
Though nothing prevents you from unisntalling any product from the target system. The best candidate for that is the earliest CustomAction. Try `project.UILoaded`. If the msi still pops up the error message then nothing you can do from your MSI and you may need to consider using a custom bootstrapper that would always uninstall the old product if it is found on the target system.

**Comment by Torchok19081986** [comment]
Many thanks Oleg. Only one question, do bootstapper search product by name for uninstall or by some Guid, project.guid or upgradecode ? Wich part of my product should be always same ?

**Comment by oleg-shilo** [comment]
>... name for uninstall or by some Guid, project.guid or upgradecode ?

The direct answer is "I don't know".

Though it's kind of irrelevant. If you are adding **MSI** packages to your bootstrapper you don't need to worry how bootstrapper decides if the product is installed or not. I am sure it does according the MSI identity model. 

And when you build your MSI the easiest way to ensure that every build of the product MSI is upgredable and assigned correctl IDs is to ensure that all msis of a product are built with the same `project.GUID`.
