### ISSUE TITLE
How to use DialogSequence().On() ?

### ISSUE THREAD

**Issue by mchudinov** [oleg-shilo/wixsharp#49]
This code from tutorial
https://wixsharp.codeplex.com/wikipage?title=Deployment%20scenarios#_skip_dialog
does not work.
DialogSequence().On() needs strings parameters, while Dialogs. members are System.Type
```
project.CustomUI = 
        new DialogSequence()
           .On(Dialogs.WelcomeDlg, Buttons.Next, 
               new ShowDialog(Dialogs.InstallDirDlg))
           .On(Dialogs.InstallDirDlg, Buttons.Back, 
               new ShowDialog(Dialogs.WelcomeDlg));
```
How to use DialogSequence().On() ?

**Comment by oleg-shilo** [comment]
You need to use `NativeDialogs` not `Dialogs`. They are two very different creatures:
![image](https://cloud.githubusercontent.com/assets/16729806/24828503/02bdb920-1ca2-11e7-8558-6aa06e25f657.png)
My advice, don't go _native dialogs_ and go with _ManagedUI_ instead.  _Native dialogs_ was an experimental effort and I do not support it anymore after releasing _ManagedUI_.

If you still want to use _native dialogs_ have a look at samples:

_native dialogs_: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Skip_UIDialog/setup.cs
_ManagedUI_:  
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUISequence/setup.cs
