### ISSUE TITLE
Bootstrapper.SearchFormat.compatible not returning value with prefix '#'

### ISSUE THREAD

**Issue by Lechl** [oleg-shilo/wixsharp#491]
Hello @oleg-shilo,

i was using `SearchFormat.compatible` in a custom `UtilRegistrySearch` to check which .NET Framework (>4.5) is installed.

```
var DetectionVariable = "SOMEVARIABLE";

var search = new UtilRegistrySearch() {
            Root = RegistryHive.LocalMachine,
            Key = @"SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full",
            Value = "Release",
            Variable = DetectionVariable,
            Format = SearchFormat.compatible
}
```
The REG_DWORD value is eg. `1234`. 

I was expecting the `DetectionVariable` to get a value like `#1234`. But this was not the case - it always holds just `1234`.

For now I'm fine with using `SearchFormat.raw`. I just want to know, is this a bug or am I doing something wrong?

**Comment by oleg-shilo** [comment]
Sorry, I do not know the answer. This is actually a WiX question not a WixSharp one.

This is what the produced XML looks like:
```xml
<Fragment >
    <util:RegistrySearch Key="SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full" 
                         Value="Version" 
                         Variable="Netfx4FullVersion" 
                         Format="compatible" 
                         Root="HKLM" 
                         Id="RegistrySearch1" />
```

And the value of `Format` is exactly as it is described in the doco: http://wixtoolset.org/documentation/manual/v3/xsd/util/registrysearch.html
Thus, if you can find the solution then it would be on the WiX forums.

**Comment by Lechl** [comment]
Alright, thank u nevertheless.
