### ISSUE TITLE
Duplicates in Windows's installed apps list even with RemoveExistingProduct.

### ISSUE THREAD

**Issue by Alex55040** [oleg-shilo/wixsharp#492]
Saw a little bit similar issue https://github.com/oleg-shilo/wixsharp/issues/342 - but this is not exactly my case.

At each installation the files in destination installation directory are replaced with newer ones (that is OK). But I get duplicates in Windows 10 "Apps & Features" list with installed applications after each install of my app. Though versions of each newer app is bigger, the duplicates continue to appear. Tried: 1) change only fourth version number, 2) manually change the second version number (commented code for project.Version below) with the number guaranteed greater (гарантированно бОльшим) than the previous one. All lead to the same result with duplicates.

Tried both MajorUpgrade and MajorUpgradeStrategy at the same time, but got the error "Duplicate symbol 'WixAction:InstallExecuteSequence/RemoveExistingProducts' found.". Tried to comment MajorUpgrade and leave MajorUpgradeStrategy. Then tried to comment MajorUpgradeStrategy related code and leave the MajorUpgrade one. The duplicates continue to appear in all cases.

And in any case (MajorUpgradeStrategy or MajorUpgrade with my settings below in code) the installer allows to install the same version many times without any restrictions. I got a heap of the same versions in app list trying to install the same MSI many times.

The installer's log shows the following:
ActionStart: Action 09:19:46: RemoveExistingProducts. Removing applications
Info: Action start 09:19:46: RemoveExistingProducts.
Info: Action ended 09:19:46: RemoveExistingProducts. Return value 1.
…
So I thought all is OK - the previous versions seems like are removed.

So the files in destination folder are replaced with newer ones - that is OK. But my clients wonder why so many objects appear in app list and they have to remove them manually after each installation/upgrade my product.

Part of my code.
```
var project = new ManagedProject($"{productName}",...

project.GUID = Guid.NewGuid();

var exeFile = project.ResolveWildCards()
   .FindFile(f => f.Name.EndsWith(productExeName))
   .First();

var fileVersionInfo = FileVersionInfo.GetVersionInfo(exeFile.Name);
project.Version = new Version(fileVersionInfo.ProductVersion);
//project.Version = new Version("1.2.0.0");

//project.MajorUpgrade = new MajorUpgrade()
//{
//    AllowSameVersionUpgrades = true,
//    Schedule = UpgradeSchedule.afterInstallInitialize,
//    DowngradeErrorMessage = $"A later version of {productName} is already blah-blah...."
//};

project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;
```

PS. I have tried even the following variant (with the highest version ever installed set manually):

```
project.MajorUpgrade = new MajorUpgrade()
{
    Disallow = true,
    DisallowUpgradeErrorMessage = "disallow blah blah",
    DowngradeErrorMessage = "downgrade blah blah",
    Schedule = UpgradeSchedule.afterInstallInitialize
};
```
Result: nothing to stop me from installing, no "blah blah" messages, nothing. Only newer files in destinations folder and another one duplicate in apps list.

**Comment by Xaddan** [comment]
`GUID` is `UpgradeCode` and it should not change!

`Project.ProductId = Guid.NewGuid();`

**Comment by oleg-shilo** [comment]
Correct. @Xaddan  is right.

The problem is caused by you setting the new `project.GUID` in the upgrade definition. All the versions of the same product must have the same `project.GUID`.
Have a look at the "Major Upgrade" sample for the working example.
Reading this section will be extremely beneficial: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming.

Note, you can omit `Project.ProductId = Guid.NewGuid();` completely.

**Comment by Alex55040** [comment]
@Xaddan and @oleg-shilo, thank you. But is there a way to generate Project.GUID automatically within Wix# project? I mean without do it external and copy-paste to the Wix# project's code.

**Comment by oleg-shilo** [comment]
Yes there is. Just don't specify it and a random GUID will be generated automatically. 
But... it's not what you want. As every MSI build will have a random GUID you will end up with the same problem that you dedicated this post to.

**Comment by Alex55040** [comment]
>           Yes there is. Just don't specify it and a random GUID will be generated automatically.
> But... it's not what you want. As every MSI build will have a random GUID you will end up with the same problem that you dedicated this post to.

Can't get what do you mean. I tried what I said - use GUID and upgrade strategy like
```
Project.GUID = new Guid("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX");
project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;
```
and the product updates fine, if at least the third part of the version of the product is greater than the current installed one. If only the fourth part is greater, then the product is installed second time: it replaces the files in the installation directory (that is what I want), but the duplicate appears in the installed apps list. in Windows.

The fourth part of the product version changes every build (I know that it depends of the number of second from the last midnight) but is not taken into account at upgrading. My template for assembly version is "1.1.*". So it requires from me to change at least the second part manually or just wait next day to the third part increments automatically. Or I can use a custom version system with using T4 or something.

**Comment by oleg-shilo** [comment]
> If only the fourth part is greater...

This is where the problem is originated. MSI does not recognize the first component of the version - _revision_. Thus you must increment at least the third component of the version. 

This constraint has nothing to do with neither WixSharp not WiX and it is a pure MSI limitation. 

To meke it more clear, I have created the _MajorUpgrade_ sample, which contains has all required elements: multiple msis, 'MajorUpgrade' vs 'MajorUpgradeStrategy'.

Note, the recommented approech is to use simplified `MajorUpgrade`, which WiX introduced to replace `MajorUpgradeStrategy` for trivial use-cases.

**Comment by Alex55040** [comment]
> This is where the problem is originated. MSI does not recognize the first component of the version - _revision_. Thus you must increment at least the third component of the version.
> This constraint has nothing to do with neither WixSharp not WiX and it is a pure MSI limitation.

But why duplicates appear in the app list? This is also the default behavior of MSI, or I just made something wrong with settings in WiX#?

**Comment by oleg-shilo** [comment]
> MSI does not recognize the first component of the version

Very annoying auto-correction mistake. It is "the forth", not "the first" component.  _Revision_ is the last component of the version.

> But why duplicates appear in the app list? This is also the default behavior of MSI

No it's not. Though I cannot comment on this one as I have no context of your test case. 

Anyway, I have just tested the "MajorUpgrade" sample and it works as expected. Please folow it and update your solution accordingly.

This is what I did:
- Updated the sample with `project.Version = new Version("1.02");`
- Built it into `setup.a.msi` 
- Update the sample with `project.Version = new Version("1.0.3");`
- Built it into `setup.b.msi` 
- Executed and completed `setup.a.msi`
- Observed v1.0.2 in AddRemovePrograms 
- Executed `setup.a.msi` again and observed "change,repair,remove" dialog. Terminated setup without completion. 
- Executed and completed `setup.b.msi`
- Observed v1.0.3 in AddRemovePrograms

**Comment by Torchok19081986** [comment]
same issue for my project too. My Product listed 2 times in add/remove panel. Msi founded already installed product with version 2.5.8.0 for me and newer msi package has new version 2.5.9.0, sofar ok. it doesnt uninstall previous version. I set it like in sample, with majorupgrade, but doesnt work. 
Need help. Guid is always same.

**Comment by oleg-shilo** [comment]
Have you tried the solution I described in my previous post?

**Comment by Torchok19081986** [comment]
Yes. It didnt work. my description of project looks exat like in sample with some difference. But it didnt work anyway for me. 
in event Project_UIInitialized(SetupEventArgs e) msi shows me current version and newer version, all sofar ok. if i dont specify guid for project, curent version cant be founded, msi shows current verison 0 and newer version <whatever>.  my project description lookw like:
                project = new ManagedProject("MySoft",               
                #region Project Declaration 
                    new Dir(@"C:\Apps\" + Application.CompanyName + @"\SU",
                        new Dir(@"bin",
                        new File(pfadToVTESU2vorlage + @"\bin\7z.dll"),
                        new File(pfadToVTESU2vorlage + @"\bin\7z.exe")),
                        new Dir(@"Install"),
                        new Dir(@"logs"),
                        new Dir(@"Temp"),
                        new Dir(@"Config",
                        new File(pfadToVTESU2vorlage + @"\clean.xml")),
                        new File(pfadToVTESU2vorlage + @"\ClientRollUp.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\mms.cfg"),
                        new File(pfadToVTESU2vorlage + @"\MySql.Data.dll"),
                        new File(pfadToVTESU2vorlage + @"\Microsoft.Deployment.WindowsInstaller.dll"),
                        new File(pfadToVTESU2vorlage + @"\Newtonsoft.Json.dll"),
                        new File(pfadToVTESU2vorlage + @"\Newtonsoft.Json.xml"),
                        new File(pfadToVTESU2vorlage + @"\ftplinks.xml") {  OverwriteOnInstall = true},
                        new File(pfadToVTESU2vorlage + @"\Specialsdistributes.dll") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\parameter.xml") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\UpdateVersionen.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\Viewer.aapp"),
                        new File(pfadToVTESU2vorlage + @"\Auswertung.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\Clientsettings.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\ClientUpdater.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\NotifyIcon.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\Optionen.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\ServerUpdater.exe") { OverwriteOnInstall = true },
                        new File(pfadToVTESU2vorlage + @"\VTESU2.sql"),
                        new Dir(@"%ProgramMenu%\MySoft\SU",
                                  new ExeFileShortcut("Optionen", @"[INSTALLDIR]\Optionen.exe", ""),
                                  new ExeFileShortcut("Auswertung", @"[INSTALLDIR]\Auswertung.exe", ""),
                                  new ExeFileShortcut("Client Einstellungen", @"[INSTALLDIR]\Clientsettings.exe", ""),
                                  new ExeFileShortcut("Uninstall SU", @"[System64Folder]msiexec.exe", "/x [ProductCode]"))),
                #region Sql Database Installation                     
                        new ManagedAction(CustomActions.CreateSQLDatabase, Return.check, When.After, Step.InstallFinalize, Condition.NOT_Installed),
                #endregion
                #endregion
                #region Registry Values Declaration 

                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MySoft\SU", "InstallDir", "[INSTALLDIR]"),
                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MySoft\SU", "Installdate", DateTime.Now.ToShortDateString()),
                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MySoft\SU", "Installed", "1"),
                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MySoft\SU", "Dbversion", "1.2"),
                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MySoft\SU", "Dbname", "VTESU2"),
                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MySoft\SU", "Version", v.ToString()));

                #endregion
                project.Properties = new[]
                {
                  new Property("SQLSERVER","empty"),
                     new Property("SQLUSER","empty"),
                      new Property("SQLPASSWORD","empty"),
                       new Property("SQLDATABASE","empty"),
                };

                project.ManagedUI = new ManagedUI();

                project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                               //.Add<LicenceDialog>()
                                               //.Add<InstallDirDialog>()
                                               .Add<VTESU2SqlDatabase>()
                                               .Add<ProgressDialog>()
                                               .Add<ExitDialog>();
                project.Include(WixExtension.Sql);
                project.Include(WixExtension.Util);
                project.ControlPanelInfo.NoRepair = true;
                project.ControlPanelInfo.NoModify = true;
                project.ValidateBackgroundImage = false;
                project.PreserveTempFiles = true;
                project.LocalizationFile = @"localization\Localization-de-DE.wxl";
                project.BackgroundImage = @"Banner\Willkomensdialog.bmp";
                project.BannerImage = @"Banner\installer-top-vte.bmp";
                project.LicenceFile = @"Licensevereibarung\Lizenzvereinbarung.rtf"; 
                //project.Platform = Platform.x86;
                project.InstallerVersion = 450;
                project.InstallScope = InstallScope.perMachine;
                project.GUID = new Guid("ad8de065-9c1b-428b-b5c8-5aaf93f0f632");            
                project.Version = new Version("2.6.0.0");
                project.ControlPanelInfo.HelpLink = @"";
                project.ControlPanelInfo.HelpTelephone = "";
                project.ControlPanelInfo.Manufacturer = "My GmbH";
                project.ControlPanelInfo.ProductIcon = @"Images\my.ico";
                project.ControlPanelInfo.InstallLocation = "[INSTALLDIR]";
                project.ControlPanelInfo.Name = "My Software Updater ";
             
                project.MajorUpgrade = new MajorUpgrade
                {
                    Schedule = UpgradeSchedule.afterInstallInitialize,
                    DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
                };
                project.Include(WixExtension.Sql);
                project.Include(WixExtension.Util);
                project.Load += Project_Load;
                project.BeforeInstall += Project_BeforeInstall;                                     
                project.AfterInstall += Project_AfterInstall;
                project.WixSourceGenerated += Project_WixSourceGenerated;
                project.UIInitialized += Project_UIInitialized;
                project.AbortSetupOnUnhandledExceptions = true;
                project.PreserveDbgFiles = true;
                project.PreserveTempFiles = true;
                project.OutFileName = "UpdateTo" + v;      
                project.BuildMsi(Application.StartupPath + @"\Updates\" + project.OutFileName + ".msi");
that all. in verison 1.6.5 it works. i update project to newer version 1.9.2 of wixsharp and thought, i check after update.. Appears some problem.
in registry 2 value with guid {AD8DE065-9C1B-428B-B5C8-5AAFB3407697} and {AD8DE065-9C1B-428B-B5C8-5AAF93F0F632}. guid  "ad8de065-9c1b-428b-b5c8-5aaf93f0f632" and {AD8DE065-9C1B-428B-B5C8-5AAF93F0F632} are same. i

**Comment by oleg-shilo** [comment]
> Yes. It didnt work. my description of project looks exat like in sample with some difference. But it didnt work anyway for me.

Sorry, I do not have capacity to troubleshoot your solution. Though I have packed mine. Please investigate the attached content. there are two MSI files and their WXS files. You can see exactly what makes the solution to work. Use it as a benchmark and start slowly add yours stuff. This way you will be able to see what part of your code breaks the the upgrade functionality. As you can see from the screenshot below all works as expected:

![image](https://user-images.githubusercontent.com/16729806/46733731-d7c9d400-ccdc-11e8-98ae-ef4a7d70b892.png)

[MajorUpgrade.zip](https://github.com/oleg-shilo/wixsharp/files/2464468/MajorUpgrade.zip)

**Comment by Torchok19081986** [comment]
many thanks Oleg. I going to step by step build solution and see where it looks not ok.

**Comment by oleg-shilo** [comment]
> How do i set package id same as project.guid ?

You don't. You don't need to set `package.id`. This id is set to random GUID by WiX compilers. In fact MS discourages setting `package.id` and reports it as a warning. 

_In MS defense, setting `package.id` is not needed as it is not involved in any of the of the deployment scenarios and is rather an identification of the specific msi binary._  

 Though I personally do not like the idea that simple rebuild without any code change generates non binary identical msi files. Thus WixSharp offers the mechanism for using consistent  `package.id`.

  
```C#
// use
project.EmitConsistentPackageId = true;

// it will lead to this
if (project.EmitConsistentPackageId)
    package.CopyAttributeFrom(product, "Id");
...
```

**Comment by Torchok19081986** [comment]
i tried your solution. It works . Now i can update my product to newer version with another msi package. 
Many thanks, oleg. Is there posibility to get info in exitdialog, if product was updated or not ?

**Comment by oleg-shilo** [comment]
You can still rely on the standard/default error handling mechanism:
```C#
void ExitDialog_Load(object sender, System.EventArgs e)
{
    image.Image = Runtime.Session.GetResourceBitmap("WixUI_Bmp_Dialog");
    if (Shell.UserInterrupted || Shell.Log.Contains("User cancelled installation."))
    {
        title.Text = "[UserExitTitle]";
        description.Text = "[UserExitDescription1]";
        this.Localize();
    }
    else if (Shell.ErrorDetected)
    {
        title.Text = "[FatalErrorTitle]";
        description.Text = Shell.CustomErrorDescription ?? "[FatalErrorDescription1]";
        this.Localize();
    }
   ...
```
If it is not enough you can always use `AppSearch`:
```C#
var installed = AppSearch.IsProductInstalled("{1D6432B4-E24D-405E-A4AB-D7E6D088CBC9}");
var version = AppSearch.GetProductVersion("{1D6432B4-E24D-405E-A4AB-D7E6D088CBC9}");
...
```

**Comment by Alex55040** [comment]
> Anyway, I have just tested the "MajorUpgrade" sample and it works as expected. Please folow it and update your solution accordingly.
This is what I did:

> Updated the sample with project.Version = new Version("1.02");
Built it into setup.a.msi
Update the sample with project.Version = new Version("1.0.3");
Built it into setup.b.msi
Executed and completed setup.a.msi
Observed v1.0.2 in AddRemovePrograms
Executed setup.a.msi again and observed "change,repair,remove" dialog. Terminated setup without completion.
Executed and completed setup.b.msi
Observed v1.0.3 in AddRemovePrograms


Have tested this with settings from your tutorials (the simplest variant):
```
project.MajorUpgrade = new MajorUpgrade
{
    Schedule = UpgradeSchedule.afterInstallInitialize,
    DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
};
```

It is all OK. But if I do it with only the fourth component of app version has been changed, it installs the duplicate.

You can reproduce it by repeating your instructions in the quote but with versions
```
project.Version = new Version("1.0.2.1"); // for the first setup file
project.Version = new Version("1.0.2.2"); // for the second one
```

So this two products (v.1.0.2.1 and v.1.0.2.2) are considered as two different products. Is this MSI bug?

**Comment by oleg-shilo** [comment]
As I mentioned in my perv post (29 days ago). You supposed to change the first, second or the third component of the version. Changing the forth one does not comply with the MSI versioning paradigm.

**Comment by Alex55040** [comment]
Does it mean that the programmers are restricted to make only one MSI per day if they rely on the build-in Visual Studio versioning system, and they have to choose another versioning system (custom or external) if they want to break this limitation?

Is it for the purpose or just inconsistencies in development of VS team and MSI team? I ask just because of curiosity.

**Comment by Alex55040** [comment]
So, as I understand, the reasons of duplications was:
1) new Project.GUID for every version of my app;
2) MSI doesn't recognize the difference of the fourth component of the version as another version, but does recognize it as another product at all, and thus does allow to install it as another product, not a version of the same product.

**Comment by oleg-shilo** [comment]
> Does it mean that the programmers are restricted to make only one MSI per day 

I am afraid it is a wrong place to ask this question. :)

I am, for one, strong critic of MSI versioning policy. For me v1.0.0.0 and v1.0.0.1 represent two completely different product versions. For MSI it is the same. This policy was established (1999) way before VS started offering developers version auto-increment (~3 years before first VS+.NET). I guess it is the primary reason for the discrepancy.

> So, as I understand, the reasons of duplications was:...

"Yes" to both questions.
