### ISSUE TITLE
Question: Using COM Components in C# Code

### ISSUE THREAD

**Issue by OptrixAU** [oleg-shilo/wixsharp#493]
I've got a reference to a COM component (the Task Scheduler library, so that I can set up a new scheduled task as part of installing) in my installation project. I'd prefer not to use the command-line method, if at all possible.

When I try to actually use the component, it can't seem to find it - I get **Could not load file or assembly 'Interop.TaskScheduler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.**

Note that this occurs regardless of if I'm setting platform to x86 or x64, and it works fine when the same code is made into a .NET console app. 

I don't believe I can use https://github.com/dahall/TaskScheduler, as it's now evolved to use new language standards (primarily the *default* keyword) and all of the NuGet packages to do this particular job don't support .NET 3.5 anymore. 

Is there a trick for finding the COM component?

**Comment by Xaddan** [comment]
Just WixSharp does not pack third-party libraries in the CA archive.
Oleg, it would be good to add this capability.

**Comment by oleg-shilo** [comment]
WixSharp supports packing the referenced assemblies via `RefAssemblies` property. Have a look at "DTF_ExternalAssembly" sample.

```C#
new ManagedAction("CustomAction")
{
    ActionAssembly = "CustomAction.dll",
    RefAssemblies = new []{"DispalyMessage.dll"}
}
``` 

Alternatively you can define referenced assemblies on project level with `project.DefaultRefAssemblies`.

**Comment by Xaddan** [comment]
I did not know about this opportunity.
