### ISSUE TITLE
Publishing .NET Core application that uses WixSharp

### ISSUE THREAD

**Issue by meareindel** [oleg-shilo/wixsharp#496]
Dear Oleg,

In continue to #484, I've just published my application as self-contained exe and there is some complicated situation. 

Some background first - I've planned to run asp.net core service which provides restful api for some installers building. Say, I have several options there, such as which installer to build, where to take needed files from, include some parts or not, and so on.

Now if I don't make any additional nuget-package references, then when service starts to build the msi package, it eventually proceeds to wxs generation, and specifically at ```public static XDocument Compiler.GenerateWixProj(Project project)``` it throws an exception saying ```Could not load assembly 'System.Drawing.Common...```, the assembly the .NET Core runtime redirected ```System.Drawing``` assembly used in Wix# to. 

I've added 'System.Drawing.Common' nuget-package reference to my service, and everything seemed ok until I published the service as self-contained exe. Now when I trying to run that exe, msi generation fails at custom actions all-in-one assembly generation, and strictly speaking it's not the Wix# issue. And that's what is happening: I use some Wix# properties such as ```Project.ControlPanelInfo.InstallLocation``` and some other, for which internal Wix# custom actions are used, and I don't use any other custom actions. So when ```MakeSfxCA.exe``` from wix toolset process the ```WixSharp.dll``` it tries to resolve the assembly dependencies, specifically the ```System.Drawing```. And according to it's source, it first tries to load the assembly file from the same folder as input dll. But there is ```System.Drawing.dll``` from .NET Core runtime, that one from nuget-package I've referenced above, so it could not resolve dependency correctly and fails with exception. Then the Wix# itself fails because the custom actions assembly has not been generated. Notable fact, that if ```MakeSfxCA.exe``` can't find the assembly in input folder, it tries to load it from GAC, and in that very case it would be more relevant. But that case could be used to mentally generate several other different cases when there is no simple unified solution for all of them. So the problem solution, as I see it, would be to provide more flexible assembly resolve algorithm of ```MakeSfxCA.exe``` and that should be addressed to the Wix toolset team.

But I've done some further investigations and found, that ProjectValidator.Validate uses the the only ```Bitmap``` class from ```System.Drawing``` and for only ```project.BackgroundImage``` validation. 'But my project has no background image' I thought, and tried to move that part of code to a separate method. And it seemed to work like a charm, it did not try to load the ```System.Drawing``` assembly now and I could remove the nuget-package reference to it, and under debugging everything seemd to be ok now. But when I published my service, it published the ```System.Drawing.Common``` and all of it dependencies again, as a transient dependency it seems, so I've returned to the start. 

Could you please provide some comment on all that? Now I see the only two ways - to move to .Net Framework from .Net Core or to make some console app wrapper targeting .Net Framework, and communicate with it to build msi installers.

**Comment by meareindel** [comment]
Just another thoughts about that - WiX# is already copies custom action assemblies to temp folder if some conditions are fired. So it could be some switch in ```Compiler``` that would make to copy custom action assemblies to temp folder unconditionally. It's of course some kind of hack though.

**Comment by oleg-shilo** [comment]
I would rather make an option for disabling image validation. The same way as it was done for CA validation.

**Comment by oleg-shilo** [comment]
Yes this is exactly sort of the problems I was referring to in #484.

Unfortunately, it's not much one can do to solve this problem. Unless in the future . Unless MakeSfxCA makes it possible to exclude certain assemblies it will always try to pack .NETCore libraries that the target system CLR will not be able to run.

The The potential wok around solutions are:
- Not to use managed CA
- Have all managed CAs implemented in external (netstandard2) assembly
- Use external .NET process to build the msi.

The last one is something that is not particularly elegant but reliable and allowing the all set of WixSharp functionality. BTW WixSharp is distributed with CS-Script executable (cscs.exe). It already builds msis from the WixSharp file outside of the VS. You can just reuse it. Have a look at any _build.cmd_ file in the distro:
```
..\..\cscs.exe setup.cs
pause
```
