### ISSUE TITLE
NET Framework Prerequirements

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#499]
Hallo Oleg, i have problem with project.SetNetFxPrerequisites.
I set it like in sample with project.SetNetFxPrerequisite(Condition.Net461_Installed, "Please install .NET 4.6.1. first."). MSI says during install .NET Framework is not uninstalled and here apperars message from before. 
But problem is .NET Framenwork 4.7.1 installed on target system. Enviroment is Wíndows Server 2012 R2 with RDP Services. I tested same package on normal Server and here works absolutely correct. .NET Framework on another Server can be founded and here can msi install something. Do i need set project.SetNetFxPrerequisite like (new LaunchConditions(Condition.Net461), "Please install .NET 4.6.1. first.") may be ?

**Comment by oleg-shilo** [comment]
No, you are doing it right. The implementation of `SetNetFxPrerequisite` already includes `new LaunchConditions`:
```C#
static public Project SetNetFxPrerequisite(this WixSharp.Project project, string versionCondition, string errorMessage = null)
{
    var condition = Condition.Create(versionCondition);
    string message = errorMessage ?? "Please install the appropriate .NET version first.";

    project.LaunchConditions.Add(new LaunchCondition(condition, message));

    foreach (var prop in condition.GetDistinctProperties())
        project.AddProperty(new PropertyRef(prop));

    project.Include(WixExtension.NetFx);

    return project;
}
```

The problem you are describing indicates that the implementation of the ".NET 4.7.1 presence test" does not work correctly on Wíndows Server 2012 R2. Nothing we can do about it as it is implemented in external extension assembly (NetFx.dll).

You can try to find the solution on WiX forums. May be there is a magic condition value that works on your target system.

If you cannot find the answer then you may need to implement an additional manual launch condition that would check the special registry key present on your server. See "LaunchConditions" sample.

**Comment by Torchok19081986** [comment]
Thanks Oleg. i founded something on github for wixtoolset. Looks like its depend on some windows updates on Target Machine. AND Windows Server 2012 R2 have same issue. 
https://github.com/wixtoolset/issues/issues/5575
I going to set it to .NET 4.5 or better. May be this got some improvements. My functions and methods are for 4.5.1. And if not, i disable it for check.

**Comment by Torchok19081986** [comment]
Looks like with 4.5.1 and 4.5.2 can be set to SetNetFxPrerequisites(Condition.Net452_installed). Works. Any better Versions are not correctly founded by Wix toolset.
