### ISSUE TITLE
Running same .msi twice

### ISSUE THREAD

**Issue by F1nZeR** [oleg-shilo/wixsharp#500]
Hi Oleg,

I'm using default upgrade strategy.
The problem I have is that after installation (first msi run) you can run msi one more time and my expectation was to get an error message box (product is already installed), but nothing happens, at all.
You can then rebuild msi with the same version and run it, and message box appears now.

Any ideas?

**Comment by oleg-shilo** [comment]
Not without the details... :)
Though one point I want to comment immediately. Switch to simplified `MajorUpdate`. WiX introduced it specifically to avoid complexity of `MajorUpdateStrategy`

Please also read my post to #452 post starting with `This is where the problem is originated.`

**Comment by F1nZeR** [comment]
@oleg-shilo 
Simple example that can reproduce my problem:
```csharp
var project = new ManagedProject("test")
{
    Version = new Version(1, 0),
    MajorUpgrade = MajorUpgrade.Default,
    GUID = new Guid("EF158FDF-AADB-49FC-8027-1922E6AA8780")
};

project.ManagedUI = new ManagedUI();
project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome);
project.ManagedUI.InstallDialogs.Add(Dialogs.Progress);
project.ManagedUI.InstallDialogs.Add(Dialogs.Exit);

Compiler.BuildMsi(project);
```

Repro steps:
1) Build msi
2) Run msi and finish installation
3) Run msi one more time
Expected: error (Another version of this product is already installed)
Fact: nothing happens (no install dialog, no error).

You can go further:
4) Rebuild msi (without changes)
5) Run msi
Now error appears.

**Comment by oleg-shilo** [comment]
> Run msi one more time
Expected: error (Another version of this product is already installed)

Agree. According [WiX doco](http://wixtoolset.org/documentation/manual/v3/xsd/wix/majorupgrade.html) `AllowSameVersionUpgrades` is _false_ thus the second run should fail. However if you do the same experiment with native UI or ManagedUI (but with all dialogs) you will see that your setup is in fact successfully executed. Though in the repair mode.

Yes it is not what I would expect but I cannot see any problem with the setup definition, only the unexpected behavior. Inspecting WXS also confirmed that `AllowSameVersionUpgrades` was not set to _true_ by accident. Even setting it to _false/no_ explicitly does not help. MSI runtime still allows executing the same msi file twice:

![image](https://user-images.githubusercontent.com/16729806/46538126-7f6a8f00-c8f6-11e8-9bb6-86ce502bc629.png)

I can only attribute it to the WiX/MSI internal defect/undocumented behavior.

> 4) Rebuild msi (without changes)

This is one of the biggest WiX gotchas. Every time you built msi without any code change it builds a different msi. It always internally embeds a new `PackageId`. MS forced this policy of you but you can change it to allow deterministic building of identical msi binaries when rebuilding without any code change:
 ```C#
project.EmitConsistentPackageId = true;
```

**Comment by F1nZeR** [comment]
> Yes it is not what I would expect but I cannot see any problem with the setup definition, only the unexpected behavior.

Anyway what can I do in order to overcome limitations? I don't need all dialogs, so I'm using managed setup.

Is it ok to use `AllowSameVersionUpgrades = true` then? In that case I think we can check versions manually and force exit if versions are equal.

**Comment by oleg-shilo** [comment]
> Anyway what can I do in order to overcome limitations? 

Sadly, not much to truly fix this behavior. You can try to find the solution on WiX forums but that's it.

>  In that case I think we can check versions manually...

Yes this is the work around that you can implement instead. Have a look at "MajorUpgrade" sample. The use-case "ManagedUICustomCheckAproach" demonstrates the exact solution that you are looking for.

**Comment by F1nZeR** [comment]
Ok, thanks.
