### ISSUE TITLE
Execute Sql script in CustomAction

### ISSUE THREAD

**Issue by bks11** [oleg-shilo/wixsharp#501]
Hello.
Please advice or help how can I use the SqlDatabase and SqlScript class in Custom Action?  
I want to execute script generated during Installation process without using class SqlConnection

```
new ManagedProject("MyProduct",
    new Property("SCRIPT_PATH", @"SqlScriptsConfig.xml"),
       	new Property("DB_NAME", "W"),
              	new Dir(@"c:\Temp\My Product",
                            new File(@"program.cs"),
                            new File(new Id("SCRIPT_CONFIG"), @"SqlScriptsConfig.xml")),
                            new Binary(new Id("script"), "script.sql"),
                //define users
                new User(new Id("localuser"), "test.k") { CreateUser = false },
                    new SqlDatabase()
                    {
                        Id = new Id("TST_DB"),
                        Server = "sp-db",
                        Database = "[DB_NAME]"
                    },
                
                //This command I want execute when user fill all data in Dialogs and I change script 
                new SqlScript("TST_DB", featureA, "script", ExecuteSql.OnInstall),

                new ManagedAction(
                    CustomActions.ExecuteScripts,
                    Return.check,
                    When.After,
                    Step.InstallFinalize,
                    Condition.Always
                )
              );

```
Custom Action (not working)

```
[CustomAction]
public static ActionResult ExecuteScript(Session session)
{
//Modify script
new SqlScript("TST_DB", featureA, "script", ExecuteSql.OnInstall);
return ActionResult.Success;
}
```

**Comment by oleg-shilo** [comment]
I am not sure SqlScript is intended to be used form CA. This class/element encapsulates compile time script file and has it's own scheduling - `ExecuteSql.OnInstall`. Thus using CA kind of defeats the purpose.

If your script is generated during runtime then it cannot be used with SqlScript and indeed CA is required. So running the script will be as simple as running _osql.exe_ against your script file:


```C#
project.AfterInstall += args =>
{
    if (!args.IsUninstalling)
    {
        var osql = new ExternalTool 
        { 
            ExePath = "osql.exe", 
            Arguments = args.InstallDir.PathJoin("script.sql") 
        };
        var output = osql.GetConsoleRunOutput();
        // analyse output and act accordingly
    }
};
```

**Comment by oleg-shilo** [comment]
MSI implementations has a nasty usability bug when it comes to the session properties. All elevated (deferred) CA cannot access session properties. MS created a work around (`CustomActionData`) that is equally ugly but does the job. 
This work around is encapsulated by WixSharp and one needs to declare upfront all the properties that are to be used from deferred actions:
```C#
project.DefaultDeferredProperties += ",SQLSERVER,SQLUSER,SQLPASSWORD,SQLDATABASE";
```
Alternatively you can use WixSharp data dictionary that is already tunneled to the deferred actions:
```C#
// in your dialog
Runtime.Data["SQLSERVER"] = ...;

// in your CA/event
project.AfterInstall += e =>
{
    if (!e.IsUninstalling)
    {
        . . .
       string server = e.Data[SQLSERVER]; 
        . . .
    }
};
```

**Comment by Torchok19081986** [comment]
Many Thanks Oleg. I tried your solution. Works really great. Only one thought, with MsiRuntime.Data["SQLSERVER"] = <value> comes always empty value , but with  MsiRuntime.MsiSession["SQLSERVER"] = <value> ist userinput value. Looks like there some difference between data and msissession.

**Comment by bks11** [comment]
Thank you Oleg.

**Comment by oleg-shilo** [comment]
If you haven't call `Runtime.Data["SQLSERVER"] = ...;` then it is always empty.

**Comment by Torchok19081986** [comment]
hmmm. I cant call Runtime.Data["Property"]. Runtime doesnt exists. I use 1.9.2 and project was created with template of custom UI in V. 1.6.5. After update to newest Version i got some errors with Session. Do i need to recreate my managedproject or how do i get Runtime.Data in my project ? Dependecies are Wixsharp.UI, Wixsharp.Msi and Wixsharp after update only there.
