### ISSUE TITLE
windows service remain in services after uninstall

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#505]
Hallo Oleg, i have difficulty with windows service. i create it and install with wixsharp like in sample, sofar all looks ok, but after i uninstalled it, it stayed in windows services ? do i need to restart pc or may be log out user ? after logout or restart it still remained in windows services. Is some specific about windows services and msi ? windows service, wich i programmed, run as user with some special rights and not as network service, system or another one. Is that mistake ?

**Comment by Xaddan** [comment]
Show the service installation code.

**Comment by Torchok19081986** [comment]
Hallo. Code looks like : 
            ManagedProject project;
            try
            {
                File serivice;

                project = new ManagedProject("WTS",
                                 new Dir(@"%ProgramFiles%\" + Application.CompanyName + @"\" + Application.ProductName + "",
                                     serivice = new File(serviceexe_path + @"\WTS.exe"),
                                 new Dir("Config",
                                     new File(exepath + @"\WTS.exe"),
                                     new File(@"C:\Service\timetorun.xml"))),
                                 new ManagedAction(CustomActions.CheckOS, Return.check, When.Before, Step.CostInitialize, Condition.NOT_Installed),
                                 new ManagedAction(CustomActions.CheckRole, Return.check, When.Before, Step.CostInitialize, Condition.NOT_Installed))
                {
                    GUID = Guid.NewGuid(),

                    ManagedUI = new ManagedUI()
                };

                serivice.ServiceInstaller = new ServiceInstaller
                {
                    Name = "WTS",
                    DisplayName = "TS",
                    Description = "Terminal Server Services",
                    StartOn =  SvcEvent.Install,
                    StopOn = SvcEvent.InstallUninstall_Wait,
                    RemoveOn = SvcEvent.Uninstall_Wait,
                    DelayedAutoStart = true,
                    ServiceSid = ServiceSid.unrestricted,
                    FirstFailureActionType = FailureActionType.restart,
                    SecondFailureActionType = FailureActionType.restart,
                    ThirdFailureActionType = FailureActionType.restart,
                    RestartServiceDelayInSeconds = 30,
                    ResetPeriodInDays = 1,
                    PreShutdownDelay = 1000 * 60 * 3,
                    RebootMessage = "Failure actions do not specify reboot",            
                };
                project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                                .Add<LicenceDialog>()
                                                .Add<ProgressDialog>()
                                                .Add<ExitDialog>();
                project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
                project.Platform = Platform.x64;
                project.InstallerVersion = 450;
                project.ControlPanelInfo.Manufacturer = "Myproduct GmbH";
                project.OutFileName = "WTS-Installer";
                project.OutDir = Application.StartupPath;
                project.BeforeInstall += Project_BeforeInstall; 
                project.UIInitialized += Project_UIInitialized;
                project.AfterInstall += Project_AfterInstall; 

                project.SetNetFxPrerequisite(Condition.Net462_Installed, "Installieren Sie zuerst .NET Framework 4.6.2 oder besser und versuchen Sie erneut.");
                project.IncludeWixExtension(WixExtension.NetFx);
               
                project.AbortSetupOnUnhandledExceptions = true;
               
                project.BuildMsi();

**Comment by oleg-shilo** [comment]
Windows service install/uninstall operations are non-deterministic. he first step of uninstalling (always) is stopping the running service. If stopping fails for whatever reason service manager simply marks the service "for deletion" instead of actually deleting it. And on reboot the service information will be actually deleted from the registry.

This is the way Windows Service Manager handles "naughty" services.

You may want to check, may be it is your case...

**Comment by Torchok19081986** [comment]
Thanks oleg. all my install and uninstall tests looks like that.  i am right if i would say i need CA for uninstall which are show MessageBox "for completely uninstall system need to be rebootet. Do you want reboot now ?" if yes shutdown.exe with parameters ?

**Comment by Xaddan** [comment]
The service code looks right.
If the installer could not stop it, there would be an error stopping the service:
![ffquy](https://user-images.githubusercontent.com/14925308/47497911-a7ea0700-d86c-11e8-8647-ec0146425b1a.png)

**Comment by Xaddan** [comment]
Can I still see the generated code?

**Comment by Xaddan** [comment]
Look at the windows event log, maybe there are errors that would help.

**Comment by Torchok19081986** [comment]
Many thanks. I going to try it. after i uninstall windows service it still remain in windows services. Eventlog says same error 1921. After i reboot system manually it was uninstalled completly. I think i need to program reboot after uninstall in my msi package.

**Comment by Xaddan** [comment]
You need to find the cause of the 1921 error. After the problem is solved, the service will be correctly removed. Look at the service code, maybe there are errors. You can also try to stop services via sc.exe

**Comment by RachelXGanon** [comment]
How can I remove stopped service then? Because trying to stop a '_stopped_' service throw exception so it will fail to remove the service.
(It is interesting thought the installation process marks as success)
