### ISSUE TITLE
How to be if I need to elevate execution context for event "BeforeInstall"?

### ISSUE THREAD

**Issue by danilkalintsev** [oleg-shilo/wixsharp#506]
Hello Oleg,
Thank you. WixSharp is good tool!
I has problem with a privileges of event "BeforeInstall". In the note is include follow rule:      
> // Сводка:
>         //     Occurs before InstallFiles standard action.
>         public event SetupEventHandler BeforeInstall;
>         //
>         // Сводка:
>         //     Occurs after InstallFiles standard action. The event is fired from the elevated
>         //     execution context.
>         public event SetupEventHandler AfterInstall; 

How to be if I need to elevate execution context for event "BeforeInstall"?

Best regards,
Danil

**Comment by oleg-shilo** [comment]
Hi Danil,
`BeforeInstall` is not elevated as it is serving the usual scenario of environment validation before the actual installation. Thus the CA behind BefoerInstall is not deferred (elevated).

If you indeed need the elevation at that step you need to use `ElevateCustomAction`.
See "DeferredActions" sample.

**Comment by danilkalintsev** [comment]
Thank you!
