### ISSUE TITLE
Problem with versions > 1.7.0

### ISSUE THREAD

**Issue by inside686** [oleg-shilo/wixsharp#507]
Hi Oleg,

I have a problem with versions of Wix# that are above 1.7.0 (WixSharp.bin): The installer is created with no apparent issues but when I run it (to install the software) it just closes imediately.
Here is the link to the installer code:

[CytoMine.Installer](https://www.dropbox.com/s/it4e3mr1x6xwqxf/CytoMine.Installer.zip?dl=0)

Let me know if you spot something wrong in it. Note, that it is not urgent as 1.7.0 is working as expected although it would be great to be able to update.

Thanks.

**Comment by oleg-shilo** [comment]
Can you please run it with logging. It may identify the cause of the problem. Let me know your findings.
Thank you.

**Comment by inside686** [comment]
Hi Oleg, it's definitely a bootstrapper failure because the MSI works as intended.
I will try to identify what is causing it.

Thanks.

**Comment by inside686** [comment]
Looking at the generated WXS, the only notable differences are in <InstallExecuteSequence>:
In v1.7:
  ```
  <InstallExecuteSequence>
      <Custom Action="WixSharp_InitRuntime_Action" Before="AppSearch"> (1) </Custom>
      <Custom Action="Set_CancelRequestHandler_Props" After="InstallInitialize" />
      <Custom Action="CancelRequestHandler" Before="InstallFinalize"> (NOT (REMOVE="ALL")</Custom>
      <Custom Action="WixSharp_BeforeInstall_Action" Before="InstallFiles">1</Custom>
    </InstallExecuteSequence>

```
In last version:

```
    <InstallExecuteSequence>
      <Custom Action="WixSharp_InitRuntime_Action" Before="AppSearch"> (1) </Custom>
      <Custom Action="Set_CancelRequestHandler_Props" Before="InstallFinalize" />
      <Custom Action="CancelRequestHandler" After="Set_CancelRequestHandler_Props"> (NOT (REMOVE="ALL")) </Custom>
      <Custom Action="WixSharp_BeforeInstall_Action" Before="InstallFiles">1</Custom>
    </InstallExecuteSequence>
```

**Comment by oleg-shilo** [comment]
Interesting.... The diff/change in your prev post is from the WXS for your **msi** file not the bootstrapper. Your msi works fine and the change is indeed something that was introduced after v1.7. 

What would be more interesting is to compare WXS for the bundle (bootstrapper) of v1.7 vs v1.7+. Since it is a bootstrapper who is playing up.

Can you please to have a look that?

**Comment by inside686** [comment]
The WXS for the bundle are exactely the same:

```
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension" xmlns:bal="http://schemas.microsoft.com/wix/BalExtension" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Bundle Name="Cyto-Mine® Studio Suite v.2.0.19" AboutUrl="https:/www.spherefluidics.com" IconSourceFile=".\Resources\Images\LogoSoftware.ico" Manufacturer="Sphere Fluidics Limited" UpgradeCode="811383c2-75b4-414a-b8b6-95174851ce06" Version="2.0.19" >
    <BootstrapperApplicationRef Id="ManagedBootstrapperApplicationHost">
      <Payload SourceFile="CytoMine.Installer.exe" />
      <Payload SourceFile="BootstrapperCore.config" />
      <Payload SourceFile="Microsoft.Deployment.WindowsInstaller.dll" />
    </BootstrapperApplicationRef>

    <Variable Name="Title" Value="Cyto-Mine® Studio Suite v.2.0.19" Persisted="yes" />
    <Variable Name="ProductName" Value="Cyto-Mine® Studio Suite" Persisted="yes" />
    <Variable Name="Logo" Value="LogoSoftware" Persisted="yes" />

    <Chain>
      <PackageGroupRef Id="NetFx40Web" />

      <MsiPackage Id="MSIPackage" SourceFile="Cyto-Mine® Studio Suite.msi">
        <MsiProperty Name="WIXBUNDLEORIGINALSOURCE" Value="[WixBundleOriginalSource]" />
      </MsiPackage>

      <ExePackage Name="Microsoft .NET Framework 4.6.1" Id="DotNetPackage" InstallCommand="/passive /norestart" DetectCondition="Netfx4FullVersion&gt;=394271" Permanent="yes" SourceFile="Resources\Packages\.NET Framework.exe" Compressed="yes" Vital="yes" />
      <ExePackage Name="Microsoft Visual C++ 2015 Redistribuable" Id="VCPackage" InstallCommand="/install /quiet /norestart" Permanent="yes" SourceFile="Resources\Packages\vc_redist.x64.exe" Compressed="yes" Vital="no" />
    </Chain>

    <util:RegistrySearchRef Id="RegistrySearch1" />
    <util:RegistrySearchRef Id="RegistrySearch2" />
  </Bundle>

  <Fragment >
    <util:RegistrySearch Key="SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full" Value="Release" Variable="Netfx4FullVersion" Root="HKLM" Id="RegistrySearch1" />
    <util:RegistrySearch Key="SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64" Value="Installed" Variable="MSVCRedistInstalled" Root="HKLM" Id="RegistrySearch2" />
  </Fragment>
</Wix>
```

**Comment by inside686** [comment]
Both the WXS for the bootstapper are identical, note that the Intallater (.exe) generated for both are just slightly different in size: new is 178,251,684 bytes, 1.7 is 178,241,938 bytes.

```
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension" xmlns:bal="http://schemas.microsoft.com/wix/BalExtension" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Bundle Name="Cyto-Mine® Studio Suite v.2.0.19" AboutUrl="https:/www.spherefluidics.com" IconSourceFile=".\Resources\Images\LogoSoftware.ico" Manufacturer="Sphere Fluidics Limited" UpgradeCode="811383c2-75b4-414a-b8b6-95174851ce06" Version="2.0.19" >
    <BootstrapperApplicationRef Id="ManagedBootstrapperApplicationHost">
      <Payload SourceFile="CytoMine.Installer.exe" />
      <Payload SourceFile="BootstrapperCore.config" />
      <Payload SourceFile="Microsoft.Deployment.WindowsInstaller.dll" />
    </BootstrapperApplicationRef>

    <Variable Name="Title" Value="Cyto-Mine® Studio Suite v.2.0.19" Persisted="yes" />
    <Variable Name="ProductName" Value="Cyto-Mine® Studio Suite" Persisted="yes" />
    <Variable Name="Logo" Value="LogoSoftware" Persisted="yes" />

    <Chain>
      <PackageGroupRef Id="NetFx40Web" />

      <MsiPackage Id="MSIPackage" SourceFile="Cyto-Mine® Studio Suite.msi">
        <MsiProperty Name="WIXBUNDLEORIGINALSOURCE" Value="[WixBundleOriginalSource]" />
      </MsiPackage>

      <ExePackage Name="Microsoft .NET Framework 4.6.1" Id="DotNetPackage" InstallCommand="/passive /norestart" DetectCondition="Netfx4FullVersion&gt;=394271" Permanent="yes" SourceFile="Resources\Packages\.NET Framework.exe" Compressed="yes" Vital="yes" />
      <ExePackage Name="Microsoft Visual C++ 2015 Redistribuable" Id="VCPackage" InstallCommand="/install /quiet /norestart" Permanent="yes" SourceFile="Resources\Packages\vc_redist.x64.exe" Compressed="yes" Vital="no" />
    </Chain>

    <util:RegistrySearchRef Id="RegistrySearch1" />
    <util:RegistrySearchRef Id="RegistrySearch2" />
  </Bundle>

  <Fragment >
    <util:RegistrySearch Key="SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full" Value="Release" Variable="Netfx4FullVersion" Root="HKLM" Id="RegistrySearch1" />
    <util:RegistrySearch Key="SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64" Value="Installed" Variable="MSVCRedistInstalled" Root="HKLM" Id="RegistrySearch2" />
  </Fragment>
</Wix>
```

**Comment by oleg-shilo** [comment]
OK then, we have the identical bootstrapper wxs files, then the difference in the msi wsx files. it makes sense to compare them.

> Hi Oleg, it's definitely a bootstrapper failure because the MSI works as intended.

Thus the statement above is probably not entirely accurate. The identical bootstrapper wxs files will yield identical binaries.

Of course you vcan also try to build v1.7+ bootstrapper with v1.7 msi and vice versa. But it does look like MSI difference after all.

**Comment by inside686** [comment]
Yes, still both the MSIs work when ran outside the bootstrapper, the conclusion is that there would be some sort of incompatibility between the generated new MSI and the bootstrapper.

**Comment by oleg-shilo** [comment]
The fact that both msis run OK outside of bootstrapper does not necessarily means that they are identical.

Have you compared the MSI generated WXS for v1.7 and 1.7+? Only this will tell you if the msis are different or not

**Comment by inside686** [comment]
Yes, they are slightly different, here are all the wxs for both versions:

[Installer WXS](https://www.dropbox.com/s/ask2y8jtq8md8fa/Installer%20WXS.zip?dl=0)

**Comment by oleg-shilo** [comment]
Great. txs.
Yep the difference is insignificant. I am puzzled. You see, WixSharp is only responsible for the generation of WXS files. The rest is done by WiX compilers. If a valid WXS produces invalid binary, tere is not much can be done by playing with WixSharp. Though I am not 100% confident in the findings yet.  
 
The only last suggestion I can make is to try build:
-  v1.9.2 bootstrapper + v1.7 msi
-  v1.7 bootstrapper + v1.9.2 msi

See which one will fail at runtime

**Comment by inside686** [comment]
Yes it is quite strange indeed, still something changed because the generated installers are not the same in size.
Not really sure how I could mix the versions.

**Comment by oleg-shilo** [comment]
in your bootstrapper definition simply hardcod the location of the msi file from the different version codebase
