### ISSUE TITLE
.config files overwritten on upgrade

### ISSUE THREAD

**Issue by jaslend** [oleg-shilo/wixsharp#508]
I am having an issue with my application's .config files being overwritten during an upgrade and losing any changes that the user may have made while using the previous version.

I have done some research on this subject but after reading [https://github.com/oleg-shilo/wixsharp/issues/459](https://github.com/oleg-shilo/wixsharp/issues/459) it appears that the .config file should not get automatically overwritten.

Do I need to set a parameter to stop the .config files from getting overwritten during the upgrade?

I have tried using:

`new File(@"Files\MyApp.config")
    {
        OverwriteOnInstall = false
    }`

**Comment by Xaddan** [comment]
```C#
new File(@"Files\MyApp.config") { OverwriteOnInstall = true}.SetComponentPermanent(true)
```

**Comment by jaslend** [comment]
I manage to achieve what I required with:

`new File(@"Files\MyApp.config") { NeverOverwrite = true }.SetComponentPermanent(true)`

This stopped an upgrade overwriting the file and kept the config file after an uninstall.

**Comment by pbiradar0** [comment]
Hi,
I am also going through same issue but in my case I want to update the existing config file with some child tag and create the new config file if it not exists.

Any help would be greatly appreciated!
