### ISSUE TITLE
WixSharp.targets build execution and script arguments

### ISSUE THREAD

**Issue by mchudinov** [oleg-shilo/wixsharp#51]
I want to pass arguments to my Wix# script while building in Visual Studio.
It would be pretty easy with Post-Build events in VS.
But!
Wix# build is being executed from WixSharp.targets file. Hardcoded. 
I can modify targets file, but this is bad practice. These changes will be lost with package update. Package is not in source control.
I vote for remove hardcoded build execution from the Wix# package target file. 
Build process should be started explicitly by developer and the build process should be customizable.

**Comment by oleg-shilo** [comment]
Wix# already has NuGet package that doesn't use *.targets. It is called `WixSharp.bin` (https://www.nuget.org/packages/WixSharp.bin/)

Add it to your ConsoleApp project and modify your post-build event as you need.

In fact `WixSharp` package includes (depends on) `WixSharp.bin`. And the only extra that it introduces is that `WixSharp.target`.

**Comment by mchudinov** [comment]
Thank you for so fast answer! 
It works.
