### ISSUE TITLE
Enabling DeskBand after installation

### ISSUE THREAD

**Issue by HavenDV** [oleg-shilo/wixsharp#514]
I want to know if your library supports such specific tasks as enabling the [DeskBand](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144099(v=vs.85).aspx) after installation?
If not, then you can reconcile the interface for this, and I implement it as soon as I learn how to do it (I'm not sure that this is work with the registry, these are extensions of explorer.exe, you may need to work with it directly)

Manual activation is shown below:
![image](https://user-images.githubusercontent.com/3002068/47264376-59c9c080-d559-11e8-842a-5da3d0351f8c.png)

**Comment by oleg-shilo** [comment]
Well, creating specific UI gadgets is out of WixSharp scope. This is true for any tasksof this nature, not only DeskBand.

The most logical path this sort of functionality to be integrated with WixSharp setup is to find a solution that creates/removes _Desk Band_ and simply call it from the managed CA.

**Comment by HavenDV** [comment]
Thanks for the quick response

I mean not the creation, but the registration and the enabling of the already created dll.

Registration is the usual call to regasm library.dll /tlb /codebase, this is easily done by means of this library.
Enabling - I do not know how it is implemented - for this, the question was asked here to find out whether such functionality is implemented here. I mean only a turning on, I have already seen installers who somehow implement this functionality

**Comment by Xaddan** [comment]
Что то типа такого:
```C#
            var project = new Project("MyProduct",
                new InstallDir(@"%ProgramFiles%\My Company\My Product",
                    new File(new Id("LibraryId"), "library.dll")),
                new InstalledFileAction("LibraryId", "/tlb /codebase")
                {
                    Id = "Registry_Library",
                    Step = Step.InstallFiles,
                    When = When.After,
                    Return = Return.check,
                    Execute = Execute.deferred,
                    Impersonate = false,
                });
```
