### ISSUE TITLE
MSI Package leaves log files the application while uninstall

### ISSUE THREAD

**Issue by PrasadGandham** [oleg-shilo/wixsharp#515]
Hi,
Am trying to run simple msi package to install my application with service and upgrade or uninstall according to need. everything worked fine until Iam logging my application status. log files are left behind while uninstalling the msi. everything needs to be done on command line so couldn't edit .wxs file. tried lots of samples but couldn't fine proper solution.here is the code I used.

                    class Script
                     {
                        static public void Main()
                     {	File service;         
		         var project = new Project("smart",
                        new Dir(@"%ProgramFiles%\test\smart",
							new File(@"SMART\app.properties"),
												
						service = new File(@"SMART\app.exe")));
						service.ServiceInstaller = new ServiceInstaller
						{
							Name = "app",
							StartOn = SvcEvent.Install,
							StopOn = SvcEvent.InstallUninstall_Wait,
							RemoveOn = SvcEvent.Uninstall_Wait,
						};
						
		project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
		project.UI = WUI.WixUI_ProgressOnly;
		project.OutFileName = "smart";
		project.Version = new Version("1.0.0.0");
		project.MajorUpgrade = new MajorUpgrade
            {
                Schedule = UpgradeSchedule.afterInstallInitialize,                
                AllowDowngrades = true,
                IgnoreRemoveFailure = true,
                AllowSameVersionUpgrades = false
            };
		project.OutDir = @"../";
		project.BuildMsi(); 
	}

**Comment by oleg-shilo** [comment]
The MSI installation model implies that if you install a set of files then they are removed when you uninstall the application. This does not include any artifacts created by the application (e.g. log files).

Normally you applications create log files in the locations that doe not require removal on uninstall (e.g. temp folders). If you still want to delete the log files then you need to do it manually on uninstall.

**Comment by PrasadGandham** [comment]
yes, I have tried to understand how wixsharp works, is there a possibility of doing the deleting those files, in fact this code leaves behind the folder structure as well since there are files in the folder. is there a way we can write a custom action which would delete the folder including all the files within during uninstall. iam a fan of wixsharp, it takes away most of the burden. can this task of removing excess files  be added into this code..??? i have tried to look for this a lot but couldn't find anywhere.

**Comment by oleg-shilo** [comment]
You can definitely do it with WixSharp. But it will need to be a custom task as it's impossible to implement a generic solution of this sort. 

You can do something like this:
```C#
project.AfterInstall += project_AfterInstall;
...
static void project_AfterInstall(SetupEventArgs e)
{
    if (!e.IsInstalling && !e.IsUpgrading)
            e.InstallDir.Join("LogFolder").Delete();   
```

**Comment by PrasadGandham** [comment]
Sorry for the delay reply, I have tried the code you suggested for removing my logfolder. but iam getting the error 
 _error CS1061: 'WixSharp.Project' does not contain a definition for 'AfterInstall' and no extension method 'AfterInstall' accepting a first argument of type 'WixSharp.Project' could be found (are you missing a using directive or an assembly reference?)_
I tried including all the relevant binaries and .dll , is there somthing Iam missing..

**Comment by oleg-shilo** [comment]
Do you have `using WixSharp` in your code?

The safest way to build a WixSharp project is to bring the WixSharp project templates to your VisualStudio via WixSharp extension and then create the project from one of the templates.

**Comment by oleg-shilo** [comment]
For the `'WixSharp.Project' does not contain a definition for 'AfterInstall'` ensure you have your project as `ManagedProject` not just `Project`.

Have a look at "Managed Setup/Setup Events" sample.

**Comment by PrasadGandham** [comment]
Hi Oleg, I have added the managed project and PathJoin to my project,  Currently iam getting this 

error CS1061: 'string' does not contain a definition for 'Delete' and no extension method 'Delete' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)
I tried every other reference samples in wixsharp couldn't find any reference.

**Comment by oleg-shilo** [comment]
Sorry, the code I provided is a pseudo code that shows the technique. I hoped that you would just convert it into the code that deletes the folder as you wanted.

**Comment by PrasadGandham** [comment]
` static public void Main()
    {
     var project = new Project(.....

                    new ElevatedManagedAction(CustomActions.UnInstallService, Return.check, When.After, step.RemoveFiles, Condition.BeingRemoved));
.
.
.
}
public class CustomActions
{	 
	[CustomAction]
    public static ActionResult UnInstallService(Session session)
    {
	string CleanFolder = @"Path_to_Folder";
	System.Threading.Thread.Sleep(1500);
	System.Diagnostics.Process.Start("cmd.exe", CleanFolder);
	return ActionResult.Success;
    }	
}`


This worked out for me, thanks for the help Olge, need to include proper libraries to work..
