### ISSUE TITLE
Question: Minor upgrade

### ISSUE THREAD

**Issue by tb2johm** [oleg-shilo/wixsharp#517]
This is not os much an issue but more of a question.

I have a desktop project, about 30MB, and we don't release to often.
Now the thing is that when I update a version revision (x.x.x.revision), I get two versions installed. Is there anyway to force a Major upgrade on minor versions as well (e.g. 1.0.0.0 -> 1.0.0.1)?

The important thing here is that I don't see two version of the program in my _Programs and Features_. How it's solved, Major upgrade, of any other solution is of less importance.

**Comment by oleg-shilo** [comment]
Unfortunately MSI does not use revision version component. It is is by design limitation. Thus you will need to increment the third component instead: 1.0.0.0 -> 1.0.0.1

**Comment by tb2johm** [comment]
Sorry I think you made a misprint here? did you mean 1.0.0.1 -> 1.0.1.0?

**Comment by kot-pilot** [comment]
maybe there are some new way to make msi use revision number? Cause i'd need to integrate installer to CI (which uses commit number as revision) and to run it for update servers (so 3rd number won't always be different, but 4th will cause it changes on every commit)

**Comment by oleg-shilo** [comment]
I am afraid it is the limitation of MSI that cannot be overcame. Though I cannot completely exclude that there is some exotic WiX work around that I just don't know.

**Comment by kot-pilot** [comment]
Thank you
