### ISSUE TITLE
Uninstall existing InstallShield

### ISSUE THREAD

**Issue by nadjibnet** [oleg-shilo/wixsharp#518]
Hi,

I moved from my product from InstallShield to WixSharp,
I need to add an AUTO REMOVE/Unistall of the Existing InstallShield
by GUID's

How can add this as custom action, or some thing like that.

Thanks

**Comment by geghamyan** [comment]
Hi,

The way we did it, when we upgraded from InstallShield Express to the Wixsharp was we used dark.exe to generate wix files. Then we used the same InstallShields _Product Id_ as WixSharp _project.GUID_ and UpgradeCode as WixSharp's project.UpgradeCode. That way with the next major version upgrade we have replaced the InstallShield with the Wixsharp generated MSI.

References:
Generating Wix file (*.wxs) from an MSI
https://blogs.msdn.microsoft.com/amolgote/2008/07/18/generating-wix-file-wxs-from-an-msi/

**Comment by nadjibnet** [comment]
Hi, 
Thanks

The problem, is that I had some problems with InstallShield.
I was obliged to deploy with another GUID (when I was using InstallShield) **"I HATE IT"**.

So, Now I  have to InstallShield installations of my Production with 2 the diffrence GUID.

I must uninstall them, or one of them.

Yesterday, I found a solution by my self:

So, I created a C# dedicated App for doing that (The Clean),

using:
//My Clean App should run as Admin.
ManagementObjectSearcher("SELECT * FROM Win32_Product");
ManagementObject mo;
mo.InvokeMethod("Uninstall", null);


Finally I have added this app to a Bootstrapper before my new **LOVELY WIXSHARP INSTALLER**

What do you think about my Solution ?
