### ISSUE TITLE
How to deploy web sites with Wix#?

### ISSUE THREAD

**Issue by mchudinov** [oleg-shilo/wixsharp#52]
Is it possible to deploy web sites with wix#?
I can not find any documentation about it. Are there any code examples available?

**Comment by oleg-shilo** [comment]
All samples: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples

ASP.NET website: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/IIS/ASP.NETApp/setup.cs

**Comment by mchudinov** [comment]
Thank you! This helps a lot.
