### ISSUE TITLE
How to install all files from other project's output?

### ISSUE THREAD

**Issue by eparizzi** [oleg-shilo/wixsharp#520]
I have a project which output type is set to "Windows Application". This is a console project that needs to be installed as a Windows Service.

Currently we're using InstallShield LE for VS2015, but we're trying to migrate to WixSharp.

So, basically, our installer needs to put all the output files from the mentioned project output folder into `%PROGRAMFILES%\MyCompany\MyWinService` and register the main executable as a Windows Service.

I've created a WixSharp Managed Setup project from the templates and so I need to know how to do the following:

1. Copy all the files from another project's output (executable and DLLs) into Program Files.
2. Register the main executable as a Windows Service.

**Comment by oleg-shilo** [comment]
Q-1  
Have a look at "ReleaseFolder". This sample shows how to pick all the files from the arbitrary directory and include them into an msi setup.

Q-2
Have a look at "WinService_WiX" and "WinService_InstallUtil" samples.

**Comment by eparizzi** [comment]
I have looked at those and I'm still trying to figure it out.

How can I debug the setup? It seems to automatically run on build and so I cannot debug it if there's a runtime error.

**Comment by eparizzi** [comment]
Also, it seems the "current directory" used in the Files constructor is different when running it with the postbuild event and when debugging, right?

When the postbuild event executes, the current dir. is the project base dir right? Not the output (inside /bin), is this correct?
But when debugging in VS, the current dir is indeed the output folder as with any other project.

**Comment by eparizzi** [comment]
```csharp
Compiler.WixLocation = @"E:\Work\Client\Repos\Dev\Analytics\packages\WixSharp.wix.bin.3.11.0\tools\bin";

ManagedProject project =
    new ManagedProject("Upload Service",
        new Dir(@"%ProgramFiles%\Client\Upload Service Wix",
            new Files(@"bin\BuildFiles\*.*",
                f => f.EndsWith(".exe") ||
                      f.EndsWith(".config") ||
                      f.EndsWith(".dll"))))
    {
        Platform = Platform.x64
    };

Console.WriteLine("Listing project files...");

foreach(WixSharp.File f in project.AllFiles)
{
    Console.WriteLine(f.ToString());
}

WixSharp.File service = project.FindFile(f => f.Name.EndsWith("UploadService.exe")).Single();

service.ServiceInstaller = new ServiceInstaller
{
    Name = "Upload Service",
    StartOn = null,
    StopOn = SvcEvent.InstallUninstall_Wait,
    RemoveOn = SvcEvent.Uninstall_Wait,
    DelayedAutoStart = true,
    ServiceSid = ServiceSid.none,
    FirstFailureActionType = FailureActionType.restart,
    SecondFailureActionType = FailureActionType.restart,
    ThirdFailureActionType = FailureActionType.restart,
    RestartServiceDelayInSeconds = 30,
    ResetPeriodInDays = 1,
    PreShutdownDelay = 1000 * 60 * 3
};

project.GUID = new Guid("cd2a4338-7ec9-4c8c-9393-9a863df5e5f4");
project.SetNetFxPrerequisite("NETFRAMEWORK45 >= '#378389'", "This software needs .NET Framwork 4.5.");
project.ManagedUI = ManagedUI.Empty;
project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                .Add(Dialogs.Progress)
                                .Add(Dialogs.Exit);

project.OutFileName = "setup";
project.BuildMsi();
```
So this is what I have currently. This throws the following exception:
```
2>  Building MSI
2>  Listing project files...
2>  
2>  Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
2>     at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
2>     at UploadServiceInstaller.Setup.Main() in E:\Work\Client\Repos\Dev\Analytics\UploadServiceInstaller\Setup.cs:line 42
```
It cannot find the exe.
Also, it seems that after constructing the project, there are no files in the object. The weird thing is that they do end up being copied into the install dir after running the MSI. But for some reason, they are not in the project object and so I cannot get the .exe to setup the service...

**Comment by oleg-shilo** [comment]
Sorry, did not have time to respond promptly.

> Also, it seems the "current directory" used in the Files constructor is different when running...

Yes it is different. The curr dir during the build is the project directory. If you want t run it under debugger, you will need to set the "wrking drectory" in the project->properties->debug to `..\..\`.

You can always check the current directory by placing `Console.WriteLine(Environment.CurrentDirectory)`. Then you can compare the output during the build and during debugging.

You can also set `project.SourceBaseDir` to the path of your choice to ensure absolutely deterministic path resolution. 

```C#
project.SourceBaseDir = @"%DEV_ROOT%\MyProjects\Project_A";
```

**Comment by eparizzi** [comment]
I got it working by doing:
```csharp
project.SourceBaseDir = AppDomain.CurrentDomain.BaseDirectory;
```
Which points to the ouput folder in both debug and build scenarios.

**Comment by emersonbottero** [comment]
I couldn't make it work.

Even if you get the EmbeddedUI_WPF example and change the file readme.txt to *.txt or *.* visual studio works ok but when you click the exe file to create the msi nothing happens.
the only way I got it working was to create a file line for each file wich in my example is a lot.

**Comment by ErikParso** [comment]
Yeah I have a same problem. I cannot acces specific file using FindFile method when files are specified using pattern *.*

**Comment by oleg-shilo** [comment]
@emersonbottero 
When the exe is executed from VS (during run or debug) the currdir is `..\..`. Meaning it is your project folder.

Thus if you want to execute it manually (e.g. from bin/release) then you will to ensure the correct currdir:
```
cd ..
cd ..
bin/release/setup.exe
```
----
The best way to ensure deterministic `SourceBaseDir` is to set it based on the location of the executable: 
```C#
project.SourceBaseDir = Path.Combine(
   System.Reflection.Assembly.GetExecutingAssembly().Location.GetDirName(),
  "<whatever relative path you want>");
```

**Comment by CarlWessels** [comment]
I'm encountering a very similar issue to this, but with some more details to add. 

My problem isn't related to the pathing of the project, but when I debug my project, and I put a breakpoint on my project.BuildMsi(), I do a "project.AllFiles.ToList().Count" in my immediate, it yields 0 results. When I step over the buildMsi(), and do the project.AllFiles.ToList().Count again, I get a count > 0.

**Comment by oleg-shilo** [comment]
`project.AllFiles` is populated either immediatelly when you add the files in the constructor or after `project.ResolveWildCards` which is called internally by `project.BuildMsi`. This may explain the difference.

Thus if you are debugging a wildcard scsnario then you may want to call `ResolveWild...` by yourself. This way you can inspect your runtime object before invoking `BuildMsi`:

```C#
project.ResolveWildCards();
project.BuildMsi();
```

**Comment by CarlWessels** [comment]
> `project.AllFiles` is populated either immediatelly when you add the files in the constructor or after `project.ResolveWildCards` which is called internally by `project.BuildMsi`. This may explain the difference.
> 
> Thus if you are debugging a wildcard scsnario then you may want to call `ResolveWild...` by yourself. This way you can inspect your runtime object before invoking `BuildMsi`:
> 
> ```cs
> project.ResolveWildCards();
> project.BuildMsi();
> ```

project.ResolveWildCards(); did the magic for me. Makes sense, Tyvm.
