### ISSUE TITLE
Installdir

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#525]
Hi Oleg, i have question about installdir property. 
i tried to set it like in https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/SetupEvents/setup.cs , but in my msi property "WixSharp_UI_INSTALLDIR" wich are comes from installdir dialog overwrite my installdir from registry.
Begin of my managed Project description :  new Dir(@"C:\Apps\" + Application.CompanyName + @"\myproduct) .... 
And here msi going to be installed if i dont set from managedaction, otherwise if i set it from CA like in link i got always asbolutepath like at begin in installer. 
Regvalue read i make in CA like this : 
            session["INSTALLDIR"] = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\WoW6432Node\mycompany\myproduct").GetValue("Installdir").ToString();
Path read and set correct, but msi doesnt install in it.   
In silent mode doesnt work.
In msi i got always 2 values for installdir (show with orca ): 
WixSharp_UI_INSTALLDIR and INSTALLDIR_ABSOLUTEPATH.  Which path are Targetdir for endpoint / installdir ?

**Comment by Torchok19081986** [comment]
i tried completly new project with link from before and i can install my files into read path. for some few files are work really great. 
Although, i need to create in same path and one subdir in my installdir, but it always install in C:\myproduct. I found example with dynamic_path, but set it like in example doesnt work.
i have to create in session["INSTALLDIR"], which comes from CA: e.Session["INSTALLDIR"] = Registry.CurrentUser.OpenSubKey(@"SOFTWARE\7-Zip")  .GetValue("Path") .ToString(), one subdir with files.  if i understand correctly, 
i have to combine CA with session["INSTALLDIR"] and dynamic_Path. Only I dont know, how.

**Comment by oleg-shilo** [comment]
In your case you are installing to the absolute path. Then probably you can get some idea from _"InstallDir_AbsolutePath"_ sample. Have a look at the generated WiX. It will give you the idea which operty/Dir_ID you need to set at runtime.
