### ISSUE TITLE
registering a com component

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#527]
How to register a COM component with rollback?
 I have the .exe that does the registering
thanks

**Comment by oleg-shilo** [comment]
Probably you can do the registration from one of the Custom Actions (e.g. project events). Though as far as I know WiX strongly encourages registering COM via registry manipulation.

**Comment by ltemimi** [comment]
I am using one custom action and it does not seem to work do I need higher privileges do I set them up to admin

 var project = new ManagedProject(productName,
                new Dir($@"%ProgramFiles%\ACL\{solutionName}\{productName}",
                    new Files(filesPath), new File(msoPath), new File(rtdPath),
                    new File(new Id("registrator_exe"), regPath))
            )
            {
                GUID = installerGuid,
                ManagedUI = new ManagedUI(),
                Actions = new Action[]
                {
                    // execute installed application
                    new InstalledFileAction("registrator_exe", "/u", Return.check, When.Before, Step.InstallFinalize,
                        Condition.Installed),
                    new InstalledFileAction("registrator_exe", "", Return.check, When.After, Step.InstallFinalize,
                        Condition.NOT_Installed)
                }
            };

**Comment by oleg-shilo** [comment]
If you want to register the COM server this way you may need to start it with elevation. The easiest way to do that is form the elevated custom action (see the samples) or from normal action (e.g.  ):
 
```C#
static void run(string app, string args)
{
    var startInfo = new ProcessStartInfo();
    startInfo.UseShellExecute = true;
    startInfo.WorkingDirectory = Environment.CurrentDirectory;
    startInfo.FileName = "msiexec.exe";
    startInfo.Arguments = "/i \"" + session.Property("OriginalDatabase") + "\"";
    startInfo.Verb = "runas";
     Process.Start(startInfo);
}
. . .
project.BeforeInstall += args =>
        {
            if (!args.IsUninstalling)
                run(args.InstallDir.PathJoin("registrator_exe"), "/u");
            else
                run(args.InstallDir.PathJoin("registrator_exe"), "");
        }; 
```

**Comment by ltemimi** [comment]
I know how to do it in Wix how to translate in wixSharp please


    <CustomAction Id="_C495AF79_353F_4BE1_815D_90421684C9FD" BinaryKey="adxregistrator_exe" Execute="deferred" ExeCommand="/install=&quot;[TARGETDIR]$(var.ExcelLogix.AdxComAddIn.TargetFileName)&quot; /privileges=admin" Impersonate="yes" />
    
    <CustomAction Id="_6B5D6FD3_2F32_4DE3_B0D3_D975DB988A20" BinaryKey="adxregistrator_exe" Execute="rollback" ExeCommand="/uninstall=&quot;[TARGETDIR]$(var.ExcelLogix.AdxComAddIn.TargetFileName)&quot; /privileges=admin /generateLogFile=false" Impersonate="yes" />
    
    <CustomAction Id="_DB5E9B2E_6B3D_439C_A025_2413C5D5D893" BinaryKey="adxregistrator_exe" Execute="deferred" ExeCommand="/uninstall=&quot;[TARGETDIR]$(var.ExcelLogix.AdxComAddIn.TargetFileName)&quot; /privileges=admin" Impersonate="yes" />

**Comment by oleg-shilo** [comment]
I am not sure we are on the same page. In my previous email I shared the sample how you register a com component from events (simplified custom actions). This is arguably the simplest way to do it. Did you try it?

If you want the exact equivalent of your WiX sample then your code probably very close to it. You'll just need to ensure your actions are deferred and you are using the exact file IDs. Have a look at "DeferredActions" sample. 

```
new WixSharp.Action(Return.check, When.Before, Step.InstallFinalize, Condition.NOT_Installed)
{    
    Impersonate = true,
    Execute=Execute.deferred,
    AttributesDefinition = "BinaryKey=adxregistrator_exe;"+
                           "ExeCommand=/install=&quot;[INSTALLDIR]adxregistrator.exe&quot"
}
```
Another hint - look at the generated WiX file. It will give you exact idea what you are missing.

**Comment by ltemimi** [comment]
1) I have tried the first suggestion and there are c# syntax errors:
       a)  startInfo.Arguments = "/i \"" + session.Property("OriginalDatabase") + "\""; session is not recognised
       b) run(args.InstallDir.PathJoin("registrator_exe"), "/u"); again PathJoin I  get c# syntax errors
      c)  run is not recognised but it probably is up to me to define it.

Thanks for the last suggestion I will have a go 
new WixSharp.Action(Return.check, When.Before, Step.InstallFinalize, Condition.NOT_Installed)
{    
    Impersonate = true,
    Execute=Execute.deferred,
    AttributesDefinition = "BinaryKey=adxregistrator_exe;"+
                           "ExeCommand=/install=&quot;[INSTALLDIR]adxregistrator.exe&quot"
}

bear in mind WixSharp.Action is a protected class and cannot be instantiated directlly .

I am sorry for the time I have used wixsharp and it has served me well. I feel there may be breaking changes in the last version.
regards laz

**Comment by oleg-shilo** [comment]
BT, I have checked and found that `WixSharp.Action` is actually public and the constructors are simple made protected by mistake. 

It is fixed now. The fix will be available in the very next release.

**Comment by Xaddan** [comment]
Maybe better to use `BinaryFileAction`?
```C#
new BinaryFileAction("adxregistrator_exe", "/install=\"[INSTALLDIR]adxregistrator.exe\"", Return.check, When.Before, Step.InstallFinalize, Condition.NOT_Installed)
 {
                Impersonate = true,
                Execute = Execute.deferred,
  });
```

**Comment by ltemimi** [comment]
Hi Oleg


many thanks for your help. Excellent solution my favourite in fact. the installation partially works but registration is not happening I believe somehow I need elevated privileges, the impersonate may not be sufficient. Any idea?
Thanks Laz

**Comment by ltemimi** [comment]
project.BeforeInstall += args => Run(args.InstallDir.PathJoin("registrator_exe"), !args.IsUninstalling ? "/u" : "");
**I got an error saying ambiguous invocation. and "registrator_exe" underlined**

 private static void Run(string app, string args)
        {
            var startInfo = new ProcessStartInfo
            {
                UseShellExecute = true,
                WorkingDirectory = Environment.CurrentDirectory,
                FileName = "msiexec.exe",
                Arguments = "/i \"" + session.Property("OriginalDatabase") + "\"",
                Verb = "runas"
            };

            Process.Start(startInfo);
        }

**I got an error "The name session does not exist in this context"**

Regards Thanks

**Comment by oleg-shilo** [comment]
The sample I gave you was a pseudo-code that needed adjustments to reflect your specific deployment scenario. The implementation of the `Run` was also taken from WixSharp codebase and contained invalid (for your scenario) bits.

Assuming:
- your com executable can do self registration via `-install` 
- your com executable can do self un-registration via `-uninstall` 
- your com executable file has name "_myComServer.exe_"
- your com executable file is deployed in the root of your install dir.

You will need to adjust your code like this.

```C#
static void run(string app, string args)
{
    var startInfo = new ProcessStartInfo();
    startInfo.UseShellExecute = true;
    startInfo.WorkingDirectory = Environment.CurrentDirectory;
    startInfo.FileName = app;
    startInfo.Arguments = args;
    startInfo.Verb = "runas";
     Process.Start(startInfo);
}
. . .
project.BeforeInstall += args =>
        {
            if (!args.IsUninstalling)
                run(args.InstallDir.PathJoin("myComServer.exe"), "-uninstall");
            else
                run(args.InstallDir.PathJoin("myComServer.exe"), "-install");
        }; 
```

If your com server is a dll (myComServer.dll), then it is like below:

```C#
. . .
if (!args.IsUninstalling)
    run("regsvr32.exe", "\"" + args.InstallDir.PathJoin("myComServer.dll") + "\" /u");
else
    run("regsvr32.exe", "\"" + args.InstallDir.PathJoin("myComServer.dll") + "\" /i");
```

**Comment by oleg-shilo** [comment]
you may want to run your msi with logging and have a look at the log file. if msi is indicating that "no product is installed" then probably it was an error.

**Comment by ltemimi** [comment]
Hi

Yes there an error
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_BeforeInstall_Action
Info: WixSharp aborted the session because of the error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Core.Installer.AclInstaller.Run(String app, String args)
   at Core.Installer.AclInstaller.<>c.<CompileMsi>b__2_0(SetupEventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   at WixSharp.ManagedProject.InvokeClientHandler(String info, SetupEventArgs eventArgs)
   at WixSharp.ManagedProject.InvokeClientHandlers(Session session, String eventName, IShellView UIShell)
Info: CustomAction WixSharp_BeforeInstall_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Info: Action ended 19:52:30: WixSharp_BeforeInstall_Action. Return value 3.
CommonData: Message type: 2, Argument: 0
CommonData: Message type: 2, Argument: 1
Info: Action ended 19:52:30: INSTALL. Return value 3.
InstallEnd: 1: ExcelLogix 2: {11C8C916-1DA7-4DCB-8956-5A5B41CC171B} 3: 3 
CommonData: 1: 2 2: 0 
CommonData: 1: 2 2: 1 
Info: Action ended 19:52:30: INSTALL. Return value 3.
--------------------------
  private static void Run([NotNull] string app, [NotNull] string args)
        {
            var startInfo = new ProcessStartInfo
            {
                UseShellExecute = true,
                WorkingDirectory = Environment.CurrentDirectory,
                FileName = app,
                Arguments = args,
                Verb = "runas"
            };

            Process.Start(startInfo);
        }

I will have to use my project logger to log more info and find out why

Thanks for your help

**Comment by oleg-shilo** [comment]
Of curse! Silly mistake.
Simply the app file is not installed at that time.

You will need to execute uninstall from `Project.BeforeInstall` and install from `Project.AfterInstall`.

**Comment by ltemimi** [comment]
Hi Oleg
I spotted that yesterday and was not sure. will do. Thanks very much
Laz
===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Friday, 7 December 2018, 07:33:50 GMT, Oleg Shilo <notifications@github.com> wrote:  
 
 
Of curse! Silly mistake.
Simply the app file is not installed at that time.

You will need to execute uninstall from Project.BeforeInstall and install from Project.AfterInstall.

**Comment by ltemimi** [comment]
Hi Oleg

I attempted as suggested by using Project.AfterInstall, several issues arose,

1 -  UseShellExecute = false, : To use the Environment.CurrentDirectory this property needed to be set to false.

2 - The installation ran through OK then I attempted to uninstall and I could not uninstall the App, is there a project.BeforeUninstall? I tried to uninstall to no avail what happens the un-installation runs then rolls back. I believe it is the same error where it cannot find the file...

3 - I now have an additional issue when I build the wixsharp project I get:
---------------------------------------------------------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error		ICE30: The target file '5ptluasg.exe|adxregistrator.exe' is installed in '[ProgramFilesFolder]\ACL\Products\ExcelLogix\' by two different components on an LFN system: 'Component.adxregistrator.exe_977180341' and 'Component.adxregistrator.exe_818375905'. This breaks component reference counting.	Core.Installer	C:\Dev\src\Products\Core.Installer\ExcelLogix.wxs	24
--------------------------------------------------------------------------------------------------------------------

4 - When I took a look at the Wix folder two files with the exact name have been generated and appeared to have the same content. I deleted the wix folder rebuilt but still the same error and two "Core.Installer.g.wxs" files are generated in the wix folder. (Core.Installer is my project name)

I am sorry if this has been dragging on a bit , I am a wixsharp fan. 

regards Laz

**Comment by ltemimi** [comment]
Hi Oleg

I have now tried the binaryFileAction suggestion with impersonate set to false and it works very well and my com object registers and the entire installed app works as expected.

Thanks for your help and unless you would like me to pursue the event method I am happy to close the issue.

kind regards Laz

**Comment by oleg-shilo** [comment]
I am glad you found the solution.

Though just to address some confusion:

> 1 - UseShellExecute = false, : To use the Environment.CurrentDirectory this property needed to be set to false.

The point is that you don't want to use `Environment.CurrentDirectory` so you need to set `UseShellExecute = true` in order to for the elevation to happen.


> ...is there a project.BeforeUninstall? 

Yes there is. This is what you want to do foe the event driven approach:

```C#
project.BeforeInstall += args =>
        {
            if (args.IsUninstalling)
                run(args.InstallDir.PathJoin("myComServer.exe"), "-uninstall");
        }; 

project.AfterInstall += args =>
        {
            if (!args.IsUninstalling)
                run(args.InstallDir.PathJoin("myComServer.exe"), "-install");
        }; 

```
> 3 - I now have an additional issue when I build the ...

This cannot be diagnosed without knowing what is installed and how. 

> ...4 - When I took a look at the Wix folder two files with the exact name have been generated and appeared to have the same content. 

If you can, please send me your project file as it might be some problem with it. Please remove from it all sensitive content before sending

**Comment by ltemimi** [comment]
Hi Oleg
Please get my project from https://1drv.ms/u/s!Ai1jsiYR5baCjOhahvepRIb0xWjxKQ.
 I had some breaking changes in the dialogs after updating wixsharp again you helped with the solution.
I am also having issue with building the project in release mode I get :
Severity Code Description Project File Line Suppression StateError The command ""C:\Dev\src\Products\Core.Installer\bin\Release\Core.Installer.exe" "/MSBUILD:Core.Installer" "/WIXBIN:"" exited with code -532462766. Core.Installer C:\Dev\src\Products\packages\WixSharp.1.9.2\build\WixSharp.targets 6 
no issue building in debug mode
regards Laz


===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Sunday, 9 December 2018, 07:56:59 GMT, Oleg Shilo <notifications@github.com> wrote:  
 
 
I am glad you found the solution.

Though just to address some confusion:


1 - UseShellExecute = false, : To use the Environment.CurrentDirectory this property needed to be set to false.


The point is that you don't want to use Environment.CurrentDirectory so you need to set UseShellExecute = true in order to for the elevation to happen.


...is there a project.BeforeUninstall?


Yes there is. This is what you want to do foe the event driven approach:
project.BeforeInstall += args =>
        {
            if (args.IsUninstalling)
                run(args.InstallDir.PathJoin("myComServer.exe"), "-uninstall");
        }; 

project.AfterInstall += args =>
        {
            if (!args.IsUninstalling)
                run(args.InstallDir.PathJoin("myComServer.exe"), "-install");
        }; 


3 - I now have an additional issue when I build the ...


This cannot be diagnosed without knowing what is installed and how.


...4 - When I took a look at the Wix folder two files with the exact name have been generated and appeared to have the same content.


If you can, please send me your project file as it might be some problem with it. Please remove from it all sensitive content before sending

**Comment by oleg-shilo** [comment]
Thank you Laz,

Unfortunately your project cannot be built. There missing dependencies and it also fails to restore the packages. Though it did dive me idea about the content of the Wix sub-folder. It does actually not contain two `*.g.wxs` files as I was afraid if. Simply the project file contains two entries with the same _effective_ name but pointing to the same `*.g.wsx` file.

```xml
 <None Include="wix\Core.Installer.g.wxs" />
 <None Include="wix\$(ProjectName).g.wxs" />
```
It is most likely a result of the updating WixShapr package to the latest version in that project. 

It is a side effect of the latest change in the NuGet package structure and it has no effect on the outcome of building the msi.

As for the VS project, you can get read of that extra item by removing the `<None Include="wix\Core.Installer.g.wxs" />` item from the project file manually. Or by deleting the item from the solution explorer.

**Comment by ltemimi** [comment]
Hi Oleg
Many thanks again for the assistance. In any case the project builds OK and the installer works well when in debug. Any idea as to why I can't build it in Release mode? The error seems to be in this xml file
<?xml version="1.0" encoding="utf-8"?><Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">  <Target Name="MSIAuthoring" AfterTargets="AfterBuild">    <Message Importance="high" Text="Building MSI" />          <Exec Command="&quot;$(TargetPath)&quot; &quot;/MSBUILD:$(ProjectName)&quot; &quot;/WIXBIN:$(WixBinPackage)&quot;" WorkingDirectory="$(ProjectDir)"/>  </Target></Project>
Regards Laz
===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Monday, 10 December 2018, 12:41:11 GMT, Oleg Shilo <notifications@github.com> wrote:  
 
 
Thank you Laz,

Unfortunately your project cannot be built. There missing dependencies and it also fails to restore the packages. Though it did dive me idea about the content of the Wix sub-folder. It does actually not contain two *.g.wxs files as I was afraid if. Simply the project file contains two entries with the same effective name but pointing to the same *.g.wsx file.
 <None Include="wix\Core.Installer.g.wxs" />
 <None Include="wix\$(ProjectName).g.wxs" />
It is most likely a result of the updating WixShapr package to the latest version in that project.

It is a side effect of the latest change in the NuGet package structure and it has no effect on the outcome of building the msi.

As for the VS project, you can get read of that extra item by removing the <None Include="wix\Core.Installer.g.wxs" /> item from the project file manually. Or by deleting the item from the solution explorer.

**Comment by ltemimi** [comment]
Hi Oleg
I have updated to WixSharp 1.9.3. my project builds fine in debug. but when I add a custom action and build I get the error in debug mode, any idea as to why adding a custom action would do that?
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Dev\src\Products\Core.Installer\bin\Debug\Core.Installer.exe" "/MSBUILD:Core.Installer" "/WIXBIN:"" exited with code -532462766.	Core.Installer	C:\Dev\src\Products\packages\WixSharp.1.9.3\build\WixSharp.targets	6	

 var project = new ManagedProject(productName,
                new Dir($@"%ProgramFiles%\ACL\{solutionName}\{productName}",
                    new Files(projectFilesPath),
                    new File(msoPath),
                    new File(rtdPath),
                    new ElevatedManagedAction(CustomActions.DeleteEventLog,
                        Return.check,
                        When.After,
                        Step.InstallFiles,
                        Condition.NOT_Installed)
                ))
            {..........

**Comment by ltemimi** [comment]
Hi Oleg
Thanks very much for your help all is now solved the error when building in release mode was due to a syntax error somehow the debug did not mind it for some reason.

I am now finally closing the case thanks again for persisting with the help I was eager to continue using WixSharp as I have all my dialogs customised to my company pictures and logs.

regards Laz
