### ISSUE TITLE
Question: Access built in feature tree dialog

### ISSUE THREAD

**Issue by Chrissyoung1223** [oleg-shilo/wixsharp#528]
I am trying to access the built in feature tree dialog within my managed UI.  I want to use the default so my features can have configurable directories.  This is the dialog I am trying to place in my managed UI sequence:  `       project.UI = WUI.WixUI_FeatureTree;`
          
 ```
 project.ManagedUI = new ManagedUI();
            project.ManagedUI.InstallDialogs
                                     
                           .Add<WelcomeDialog>()
                           // this is the wixsharp default feature dialog
                           .Add(WixSharp.Forms.Dialogs.Features)
                           .Add<ProgressDialog>()
                           .Add<ExitDialog>();
```

**Comment by oleg-shilo** [comment]
It is either `project.UI` or `project.ManagedUI` but not both.

**Comment by Xaddan** [comment]
In order to be able to customize the installation path of the `feature`, it is necessary to specify the directory `ID` in the `ConfigurableDirectory` attribute.

**Comment by oleg-shilo** [comment]
The easiest way to investigate it is to create the "WixSharp - Custom UI" VS project and have a look in the generated InstallDirDialog. It has both initialization and change of the INSTALLDIR implemented.

**Comment by Xaddan** [comment]
By analogy, you can make a change to `ConfigurableDirectory`.
