### ISSUE TITLE
UtilRegistrySearch not working ?

### ISSUE THREAD

**Issue by jfquarto** [oleg-shilo/wixsharp#53]
```C#
bootstrapper.AddWixFragment("Wix/Bundle",
           new UtilRegistrySearch()
           {
               Root = Microsoft.Win32.RegistryHive.LocalMachine,
               Key = @"SOFTWARE\Microsoft\VisualStudio\12.0\VC\Runtimes\x86\Installed",
               Value = "1",
               Result = SearchResult.exists,
               Variable = "Vcredist2013Installed",
           });`
```
Results in "Registry key not found" in the install log.
Checked with regedit; the key syntax is correct and it exists.
All UtilRegistrySearch in my project fail the same way.

Wix#  1.4.2
VS 2015
Windows 10

**Comment by oleg-shilo** [comment]
It is really a WiX question. Wix# doesn't introduce any new logic for ReqistrySearch.

My very quick superficial test reviled that the `key` should not include the name of the `value` ("Installed" in your case). Also the result value `exist` means that the registry value `HKLM-> SOFTWARE\Microsoft\VisualStudio\12.0\VC\Runtimes\x86->Installed` exist but not that it returns `1`. Again, you'll need to read utils.RegistrySearch documentation.

Thus it should be something like this:
```C#
new UtilRegistrySearch()
{
    Root = Microsoft.Win32.RegistryHive.LocalMachine,
    Key = @"SOFTWARE\Microsoft\VisualStudio\12.0\VC\Runtimes\x86",
    Value = "Installed"               
    Variable = "Vcredist2013Installed"
}
```
And after that you can use `Vcredist2013Installed` in your bundle/msi conditions.

**Comment by jfquarto** [comment]
Thanx, solved now.
