### ISSUE TITLE
updrade only 2 or 3 version as minversion

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#530]
How to set minversion and maxversion like include minversion 2.5.0.0 and max 2.6.0.0 ? if i create update.msi for majaor upgrade i get always includeminversion = 0.0.0.0 and maxversion  = updateversion. ?

**Comment by Torchok19081986** [comment]
I  trid to search for updaterange from v. X to v.Y, but i found nothing. Is it posible or can wix toolset doesnt set updaterversion ranger ?

**Comment by oleg-shilo** [comment]
`MajorUpgrade` element may not support version range. Though older `Upgrade` element does.
Have a look at `project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;` in Samples/MajorUpgrade/setup.1.cs.
