### ISSUE TITLE
Question: custom action and Embedded UI

### ISSUE THREAD

**Issue by otg-agennady** [oleg-shilo/wixsharp#531]
I'm very new in WixSharp, but already charming by this.

Is it possible to call custom action from button click, for example, and choose behaviour based on changed session property?

**Comment by oleg-shilo** [comment]
Yes it is possible. Have a look at CustomUIDialog sample.

**Comment by otg-agennady** [comment]
It realy works, thank you! 

I've run the example and found I cannot change default Icon. Is it true it has no way to change Icon?

**Comment by oleg-shilo** [comment]
I assume you are talking about the banner and background images. If it is the case then yes it is possible.

You can set it as below:
```C#
project.BannerImage = @"..\..\banner.png";
project.BackgroundImage = @"..\..\background.png";
```

Though the most advanced control over your custom UI comes with the "Custom UI" VS project template:

![image](https://user-images.githubusercontent.com/16729806/48342195-2515d880-e6c3-11e8-9a3b-1dda13710643.png)

**Comment by otg-agennady** [comment]
No, I am about Application Icon:

![appicon](https://user-images.githubusercontent.com/797950/48343867-93877600-e684-11e8-8925-2f0fb1dcbb3d.png)

**Comment by otg-agennady** [comment]
It does not show UI when it chained.

I added it to chain
`<MsiPackage
        Name="CustomUIDialog"
        SourceFile="$(var.CustomUIDialog.TargetDir)/ManagedSetup.msi" DisplayInternalUI='yes'/>
`
and it returns error instead of UI.


![image](https://user-images.githubusercontent.com/797950/48475578-315a7c80-e80e-11e8-9945-ae1d88be72b8.png)

![image](https://user-images.githubusercontent.com/797950/48475697-68309280-e80e-11e8-9118-6221f3e86ec5.png)

![image](https://user-images.githubusercontent.com/797950/48475767-8dbd9c00-e80e-11e8-91e0-8e03e9837ba3.png)

![image](https://user-images.githubusercontent.com/797950/48475778-9910c780-e80e-11e8-9845-330096833089.png)
