### ISSUE TITLE
Error while trying to run ExePackage from Bootstrapper chain

### ISSUE THREAD

**Issue by otg-agennady** [oleg-shilo/wixsharp#534]
After packaging WinFormsSetup.exe I've tried to add it to the Bootsrapper chain and run installer

` <ExePackage
        Name="WinFormSetup.exe"
        SourceFile="$(var.WinFormsSetup.TargetPath)"/>`

WIxSharp.Msi.dll loaded from resourses  in the same maner as in example 

`AppDomain.CurrentDomain.AssemblyResolve +=
            (sender, arguments) => Assembly.Load(WixSharp.UI.Properties.Resources.WixSharp_Msi_dll);` 

When I run setup I have error of installation. So I enabled Fusion Log and see log inside:

> LOG: Attempting download of new URL file:///C:/ProgramData/Package Cache/A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31/WixSharp.Msi.DLL.
LOG: Attempting download of new URL file:///C:/ProgramData/Package Cache/A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31/WixSharp.Msi/WixSharp.Msi.DLL.
LOG: Attempting download of new URL file:///C:/ProgramData/Package Cache/A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31/WixSharp.Msi.EXE.
LOG: Attempting download of new URL file:///C:/ProgramData/Package Cache/A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31/WixSharp.Msi/WixSharp.Msi.EXE.
LOG: All probing URLs attempted and failed.

and from proccess monitor:

> 6:02:03.2696860 PM	WinFormSetup.exe	3532	CreateFile	C:\WINDOWS\Microsoft.Net\assembly\GAC_64\WixSharp.Msi\v4.0_1.6.4.3__3775edd25acc43c2\WixSharp.Msi.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2699532 PM	WinFormSetup.exe	3532	CreateFile	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WixSharp.Msi\v4.0_1.6.4.3__3775edd25acc43c2\WixSharp.Msi.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2701415 PM	WinFormSetup.exe	3532	CreateFile	C:\WINDOWS\Microsoft.Net\assembly\GAC\WixSharp.Msi\v4.0_1.6.4.3__3775edd25acc43c2\WixSharp.Msi.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2703311 PM	WinFormSetup.exe	3532	CreateFile	C:\WINDOWS\assembly\GAC_64\WixSharp.Msi\1.6.4.3__3775edd25acc43c2\WixSharp.Msi.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2704832 PM	WinFormSetup.exe	3532	CreateFile	C:\WINDOWS\assembly\GAC_MSIL\WixSharp.Msi\1.6.4.3__3775edd25acc43c2\WixSharp.Msi.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2706025 PM	WinFormSetup.exe	3532	CreateFile	C:\WINDOWS\assembly\GAC\WixSharp.Msi\1.6.4.3__3775edd25acc43c2\WixSharp.Msi.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2710157 PM	WinFormSetup.exe	3532	CreateFile	C:\ProgramData\Package Cache\A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31\WixSharp.Msi.dll	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2711549 PM	WinFormSetup.exe	3532	CreateFile	C:\ProgramData\Package Cache\A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31\WixSharp.Msi\WixSharp.Msi.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2713689 PM	WinFormSetup.exe	3532	CreateFile	C:\ProgramData\Package Cache\A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31\WixSharp.Msi.exe	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
6:02:03.2714927 PM	WinFormSetup.exe	3532	CreateFile	C:\ProgramData\Package Cache\A3673BDAA33BF6E109F1536C60DF3BDEFC2D8B31\WixSharp.Msi\WixSharp.Msi.exe	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

How can I load dll in this situation or it needs to be placed somewhere?

**Comment by oleg-shilo** [comment]
It seems to be a correct way of doing it.

I suggest you have a breakpoint in one of your WinForm setup and try to load the assembly under debugger.

Do two separate experiments. Try to load from the absolute path on the target system.
If it works try to verify what's wrong with the same file being loaded from the resources. 

BTW, it's really not bad to have your dependencies in the setup assembly resources. It's a bit unorthodox but extremely convenient.

**Comment by otg-agennady** [comment]
No breakpoints at all!

>Do two separate experiments. Try to load from the absolute path on the target system.
Yes, I've changed  Assembly.Load to  Assembly.LoadFrom and set  the absolute path on the my local  system. It does not work. What is the second experiment?:)

Note It does not work only if it chained. If I run WinFormsSetup.exe in standalone mode it works perfectly and load assembly.

**Comment by otg-agennady** [comment]
Oleg, thank you very much!

It seems I found solution:

`<ExePackage
        Name="WinFormSetup.exe"
        SourceFile="$(var.WinFormsSetup.TargetPath)">
        <Payload SourceFile="WixSharp.Msi.dll" />
      </ExePackage>`

The solution is adding of Payload ("WixSharp.Msi.dll") for WinFormSetup.exe package.

**Comment by oleg-shilo** [comment]
two experiments were "load from absolute path" and "load from resources" but both under debugger.

When you included the dll as a payload you don't longer need to do custom assembly loading. so you solved it the canonical way.

Though `Assembly.LoadFrom and set the absolute path on the my local system. It does not work.` is rather puzzling. That can only indicate that some other dependency is missing or the assembly is incompatible with your target runtime.

Anyway, you solved it. This is what counts... :o)

**Comment by otg-agennady** [comment]
It does not try to load WixSharp.Msi.dll from the path.

I can suppose that assembly has reference to WixSharp.Msi.dll and trying check it and load from default places  at start before Assembly.Load in Program.cs,  but cannot find it.

I'm very new in C# too, so I'm not sure it has common sense or no?

**Comment by oleg-shilo** [comment]
> ... I can suppose that assembly has reference to WixSharp.Msi.dll and trying check it and load from default places...

Yes it is something logical to assume but... .NET runtime (CLR) does not work this way. It only tries to load the assemblies what their methods/classes are about to be accessed.

Though don't worry much about that. As I said you have a;ready solved it in the most appropriate way.
