### ISSUE TITLE
Uninstall after upgrade

### ISSUE THREAD

**Issue by corina10** [oleg-shilo/wixsharp#535]
Hi, 

I am performing a major app upgrade and it looks like the uninstall is performed after installing. Is this how it is supposed to work? 
Uninstalling fails after application is upgraded due to some RegSever operations that are messed up because UnregServer (at uninstall) gets called after RegServer (at install).

For MajorUpgradeStrategy.RemoveExistingProductAfter I tried: InstallInitialize, InstallValidate and InstallFinalize. It's all the same.

I added some logs of the custom events with timestamps as proof:

Thank you!

abc_20181120022956_003_MTE.msi

***Msi_BeforeInstall 2:30:05 AM
before e.IsInstalling: True
before e.IsUninstalling: False
before e.IsUpgrading: False

***Msi_AfterInstall 2:30:06 AM
after e.IsInstalling: True
after e.IsUninstalling: False
after e.IsUpgrading: False

abc_20181120023012_000_MTE.msi

***Msi_BeforeInstall 2:30:13 AM
before e.IsInstalling: False
before e.IsUninstalling: True
before e.IsUpgrading: False

***Msi_AfterInstall 2:30:19 AM
after e.IsInstalling: False
after e.IsUninstalling: True
after e.IsUpgrading: False

**Comment by Xaddan** [comment]
What is this RegServer action?
Show his code.
