### ISSUE TITLE
External_UI/WinFormsSetup how to get properties

### ISSUE THREAD

**Issue by otg-agennady** [oleg-shilo/wixsharp#536]
Hello Oleg,
the question is how to get properties from Session object in External_UI/WinFormsSetup example? 
I mean if I have some property in Product.wxs and create file.msi and use it in example, I cannot get value of the named  property. I think there is simple way to get collection properties with values but it is not obviosly for me.

**Comment by oleg-shilo** [comment]
`External_UI` session is very different to the session that you have in with WiX custom actions. External UI is nothing else but an external process that commands MSI service to execute MSI file and listens to the service messages during that execution. Thus the process cannot have access to the runtime properties of the MSI file being executed as it is hosted by a separate process (MSI service).

Though typically you don't need to. Usually External_UI is written for a specific MSI so the knowledge about the MSI internals (e.g. properties) is encoded in the UI application directly.

Saying that you can still discover the property of the msi file being executed. Though you will need to do it by analyzing the msi file directly. WixSharp does not provide the direct API for it but you can still reuse some WixSharp infrastructure. Have a look at `MsiParser` class. You can extend it to retreive the properties:

```C#
var msi = new MsiParser(msiFile);
var prop_value = msi.GetProperty("prop_name");
. . .
class MsiParser 
{
    ...
    public string GetProperty(string name)
    {
        return GetStringValue($"SELECT `Value` FROM `Property` WHERE `Property` = '{name}'");
    }
}
```

The next release will have a ready to go `GetProperty`.

**Comment by otg-agennady** [comment]
Thanks a lot, Oleg! 

It makes sense and describes good practice for installator developing, but in my case custom actions already exist and they change some runtime properties and check, for example,  license key.

What do you think about parsing of log file to obtain actual property values on SetupComplete? Is it so ugly as I think?:)

**Comment by oleg-shilo** [comment]
The approach I have described is only suitable for parsing msi file. Meaning that you will get the property default value (before the execution) but not the value that has been modified by the custom action at runtime. 

I do not see any good solution for tunneling the runtime/session context (e.g. property) back to the host process (custom UI). An yes, using log for that seems a bit unorthodox :o )

But.... ultimately it's your call and to be honest MSI as a technology has so many faults of its own that I don't think parsing the log file is that extraordinary. Just make sure your parsing algorithm is immune to the localization.

**Comment by note-do** [comment]
I've tried to use MsiParser in ManagedProject event handlers (Load, UILoaded, UIInitialized, BeforeInstall, AfterInstall). As result, I got an error 

`System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "WixSharp.Msi, Version=1.9.3.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2" либо одну из их зависимостей. Не удается найти указанный файл.`

What should I do to fix it?

**Comment by oleg-shilo** [comment]
Most likely you haven't added the `WixSharp.Msi.dll`. You will need something similar to this:
```C#
project.DefaultRefAssemblies.Add("WixSharp.Msi.dll");
```

**Comment by note-do** [comment]
Thank you! Now it works!

But while I'm testing I found various behavior of the unhandled errors depends on the step of installation
1. UIInitialized - fails the installation without any UI and log.
2. UILoaded - installation skips the error without any log messages about it, 
3. Load and later - normal detection of an error in installation - UI Exit Dialog + message in log.
Why it happens so complicated way?

**Comment by note-do** [comment]
So, actually you are right - all errors are in the log. To create the log file I have to use command line - the template of the bat file is follows.

```
@ECHO OFF
SET MSI="D:\Public\C sharp\WindowsFormsApplication1\WixSharp Setup1\MyProduct.msi"
SET LOG="D:\Public\C sharp\WindowsFormsApplication1\WixSharp Setup1\MyProduct.log"
msiexec /i %MSI% /L*V %LOG%
```
I've done small test based on your sample. You can comment methods' bodies to view different behavior.

```
    class Program
    {
        static void Main()
        {
           
            var project = new ManagedProject("MyProduct",
                             new Dir(@"%ProgramFiles%\My Company\My Product",
                                 new File("Program.cs")));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
            
            project.ManagedUI = ManagedUI.Default;
            

            project.UIInitialized += Project_UIInitialized;
            project.UILoaded += Project_UILoaded;
            project.Load += Project_Load;
            project.BuildMsi();
        }

        private static void Project_UIInitialized(SetupEventArgs e)
        {
            TestMSIParser(e.MsiFile, "UIInitialized");
        }

        private static void Project_UILoaded(SetupEventArgs e)
        {
            TestMSIParser(e.MsiFile, "UILoaded");
        }

        private static void Project_Load(SetupEventArgs e)
        {
            TestMSIParser(e.MsiFile, "Load");
        }

        private static void TestMSIParser(string msi, string eventName)
        {
            MessageBox.Show(msi, eventName);
            var parser = new MsiParser(msi);
            MessageBox.Show(parser.GetProperty("WixSharp_UI_INSTALLDIR"), "WixSharp_UI_INSTALLDIR");
        }
    }
```
