### ISSUE TITLE
impossible rename file during installation

### ISSUE THREAD

**Issue by kain64** [oleg-shilo/wixsharp#538]
https://stackoverflow.com/questions/14475166/changing-file-name-while-installing
current implementation is:
 public File(string sourcePath, params WixEntity[] items)
    {
      this.Name = sourcePath;

probably need to split name and source path

**Comment by kain64** [comment]
can you please review it and approve or reject.

**Comment by oleg-shilo** [comment]
@Xaddan is right. The default use case is the deployment of the file with the same name as the source file.

Everything else needs to be done by specifying custom attributes directly as in the example above.

Though in the very next release you will be able to set it via dedicated property `TargetFileName`:  
```C#
new File("A.txt")
{
    TargetFileName = "B.txt"
}
```

**Comment by kain64** [comment]
@Xaddan, @oleg-shilo  thank you very much ) {AttributesDefinition = "Name=B.txt"} is working
