### ISSUE TITLE
Installing 2 Services in the same installer results in both services using the last ServiceControl definition

### ISSUE THREAD

**Issue by jonreis** [oleg-shilo/wixsharp#541]
I have the following code which creates 2 Windows Services

```
      // Create the Service element for Connexion.Gateway service
      var service = installDir.Files.FirstOrDefault(f => string.Compare(f.Id, "Connexion.Gateway.exe", StringComparison.OrdinalIgnoreCase) == 0);
      if (service == null)
        throw new Exception("Could not locate Connexion.Gateway.exe");
      var serviceInstaller = CreateService("Connexion.Gateway", "Connexion Gateway Service");
      serviceInstaller.StartOn.Start = null; //set it to null if you don't want service to start as during deployment
      service.ServiceInstaller = serviceInstaller;

      // Create Alerting Service
      var alertingService = installDir.Files.FirstOrDefault(f => string.Compare(f.Id, "Connexion.Gateway.Alerting.exe", StringComparison.OrdinalIgnoreCase) == 0);
      if (alertingService == null)
        throw new Exception("Could not locate Connexion.Gateway.Alerting.exe");
      var alertingServiceInstaller = CreateService("Connexion.Gateway.Alerting", "Connexion Gateway Alerting Service");
      alertingServiceInstaller.StartOn.Start = null; //set it to null if you don't want service to start as during deployment
      alertingService.ServiceInstaller = alertingServiceInstaller;

```

This results in the both services end up with the same ServiceControl. It appears that WixSharp is using the last set ServiceControl for both Services. This is new to the latest version of WixSharp (v1.9.3)

            <ServiceControl Id="StopConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Stop="both" Wait="yes" />
            <ServiceControl Id="StartConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Wait="no" />
            <ServiceControl Id="RemoveConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Remove="uninstall" Wait="yes" />

          <Component Id="Component.Connexion.Gateway.exe" Guid="42a9532c-f568-4b73-9469-8a03898769e1">
            <File Id="Connexion.Gateway.exe" Source="Connexion.Gateway\bin\Debug\Connexion.Gateway.exe">
              <NativeImage Id="NativeImage" Platform="64bit" Priority="3" AssemblyApplication="[INSTALLDIR]\Connexion.Gateway.exe" xmlns="http://schemas.microsoft.com/wix/NetFxExtension" />
            </File>

            <ServiceInstall Id="Connexion.Gateway" Name="Connexion.Gateway" DisplayName="Connexion.Gateway" Description="Connexion Gateway Service" Type="ownProcess" Start="auto" ErrorControl="normal" Account="[WIX_ACCOUNT_LOCALSERVICE]" Interactive="no">
              <ServiceConfig DelayedAutoStart="yes" PreShutdownDelay="60000" ServiceSid="none" OnInstall="yes" OnReinstall="no" OnUninstall="no" />

              <util:ServiceConfig FirstFailureActionType="restart" SecondFailureActionType="restart" ThirdFailureActionType="restart" RebootMessage="Failure actions do not specify reboot" ResetPeriodInDays="1" RestartServiceDelayInSeconds="30" />
            </ServiceInstall>

            <ServiceControl Id="StopConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Stop="both" Wait="yes" />
            <ServiceControl Id="StartConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Wait="no" />
            <ServiceControl Id="RemoveConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Remove="uninstall" Wait="yes" />
          </Component>

          <Component Id="Component.Connexion.Gateway.Alerting.exe" Guid="42a9532c-f568-4b73-9469-8a03ce702d83">
            <File Id="Connexion.Gateway.Alerting.exe" Source="Connexion.Gateway.Alerting\bin\Debug\Connexion.Gateway.Alerting.exe">
              <NativeImage Id="NativeImage.2" Platform="64bit" Priority="3" AssemblyApplication="[INSTALLDIR]\Connexion.Gateway.exe" xmlns="http://schemas.microsoft.com/wix/NetFxExtension" />
            </File>

            <ServiceInstall Id="Connexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" DisplayName="Connexion.Gateway.Alerting" Description="Connexion Gateway Alerting Service" Type="ownProcess" Start="auto" ErrorControl="normal" Account="[WIX_ACCOUNT_LOCALSERVICE]" Interactive="no">
              <ServiceConfig DelayedAutoStart="yes" PreShutdownDelay="60000" ServiceSid="none" OnInstall="yes" OnReinstall="no" OnUninstall="no" />

              <util:ServiceConfig FirstFailureActionType="restart" SecondFailureActionType="restart" ThirdFailureActionType="restart" RebootMessage="Failure actions do not specify reboot" ResetPeriodInDays="1" RestartServiceDelayInSeconds="30" />
            </ServiceInstall>

            <ServiceControl Id="StopConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Stop="both" Wait="yes" />
            <ServiceControl Id="StartConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Wait="no" />
            <ServiceControl Id="RemoveConnexion.Gateway.Alerting" Name="Connexion.Gateway.Alerting" Remove="uninstall" Wait="yes" />
          </Component>

**Comment by oleg-shilo** [comment]
Fixed.
The fix will be available in the next release.
