### ISSUE TITLE
ServiceInstaller.StartOn/StopOn/RemoveOn - Documentation bug

### ISSUE THREAD

**Issue by jonreis** [oleg-shilo/wixsharp#542]
The documentation states: 
		/// Set this member to <c>null</c> if you don't want to remove the service at any stage of the installation.

However; if you do set the SvcEvent to null, you get an NRE because of the setter code.

```
			set
			{
				value.Id = "Start" + Id;
				value.Name = Name;
				value.Start = value.Type;
				startOn = value;
			}
```

**Comment by Xaddan** [comment]
To solve this problem and #541
```C#
set
{
  if (value != null)
  {
    _startOn = new ServiceControl
    {
      Id = "Start" + Id,
      Name = Name,
      Start = value.Type,
      Wait = value.Wait,
    };
  }
}
```

**Comment by oleg-shilo** [comment]
Fixed.
The fix will be available in the next release.

**Comment by oleg-shilo** [comment]
Done. Give it up to ~1 hour and it will be indexed and available from NuGet
