### ISSUE TITLE
Unistall issue

### ISSUE THREAD

**Issue by Aloisius64** [oleg-shilo/wixsharp#543]
Hi Oleg,

I'm using Wix#. I experienced some issue about the Unistall feature.

I added an ExePackage to a Bundle. To this ExePackage I specified the attributes "RepairCommand" and "UnistallCommand".

After I have installed the package I proceeded with the Unistall to test. But I will note that the exe that I installed is still present on the window installed program.

In this case I have installed a version of Visual Studio. I show you a code example:

```c#
 var vs2013ShellIntegratedPackage = new ExePackage(vsShellIntegratedSetup) {
    InstallCommand = "/Passive",
    RepairCommand = "/Repair",
    UninstallCommand = "/Uninstall",
    Vital = true,
    PerMachine = false,
    Permanent = false
};
Bundle.Chain.Add(vs2013ShellIntegratedPackage);
```
To completely remove Visual studio I have to go the installed program and start the uninstallation process.

**Comment by Xaddan** [comment]
It seems necessary that was `DetectCondition`.

**Comment by Aloisius64** [comment]
So I have to add a detect condition?

**Comment by Xaddan** [comment]
Bootstrapper will not remove the package until it is sure that it is installed. This requires `DetectCondition`.

**Comment by Aloisius64** [comment]
Thanks. It works.
