### ISSUE TITLE
Question: external assembly managed UI

### ISSUE THREAD

**Issue by alberthoekstra** [oleg-shilo/wixsharp#545]
Hello,

I have a .net 3.5 console application in Visual studio which is used to create an MSI from files from another project in the same solution.

I'm currently stuck with a ManagedUI issue.
I've created a custom dialog that is supposed to use external assemblies to retrieve some data from an SDK.
Whenever I invoke code from the external assembly I get the file not found exception.

I found out that whenever I launch the generated MSI file, it creates a folder in the temp directory, this folder doesn't contain my external assemblies. When I manually put the missing assemblies inside the folder, the error disappear and the code will run.

What should I do to make this work the way it should?

**Comment by oleg-shilo** [comment]
> I found out that whenever I launch the generated MSI file, it creates a folder in the temp directory, this folder doesn't contain my external assemblies...

Correct. This is how MSI is invoking Managed CA. If your custom action (e.g. project event handler) require external assemblies at runtime you will need to add them to the prohject:
```C#
project.DefaultRefAssemblies.Add("your assembly path"); 
```

**Comment by alberthoekstra** [comment]
Thank you for responding to my question.
Weird enough I already tested it with the code you suggested.
It didn't work the first time and now it works.

I don't remember what I've done different but okay.
