### ISSUE TITLE
Question: CustomBA own design

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#546]
Hallo Oleg, i have some questions and hope you can give me some answers. 
1. Is it posible to set own design in BA? WPF Application with example MahApps.Metro.dll , MetroFramework. dll - something like that ?
I found link: 
https://archive.codeplex.com/?p=wixbootstrapper
For me are important are featuretree, what can be installed or user want to install.

2. Is size of embeded files in BA important ? I want to add package >=1 GB like SqlServer, Redistributables etc. Am i right, if i have to extract embeded files to temp or destation folder and start it from there ? 
Do you have some examples of  scenarion like that ?

Thanks already for Info.

**Comment by Xaddan** [comment]
There is an example:
`wixsharp\Source\src\WixSharp.Samples\Wix# Samples\Bootstrapper\WixBootstrapper_UI`

**Comment by Torchok19081986** [comment]
Thanks for info. I examine sample closer. And what about appearance and featuretree ?
I use ManagedUI with Custom dialog. Is it possible ?

**Comment by Xaddan** [comment]
You either use the bootstrapper UI or the ManagedUI installer.
If you select ManagedUI then the featuretree is already implemented.
If the UI bootstrapper, then you have to implement it yourself.

**Comment by Xaddan** [comment]
To be implemented in the boot block, first of all you need to install the installer `MsiPackage`, specify `EnableFeatureSelection`.
```C#
new MsiPackage(name)
{
  ....
   EnableFeatureSelection = true,
},
```
After this, the installer features will be imported into `BootstrapperApplicationData.xml`, which you will have to parse and form a featuretree.

**Comment by Xaddan** [comment]
You can download the [Wix](https://github.com/wixtoolset/wix3) source and see the WixBA project (burn.sln)

**Comment by oleg-shilo** [comment]
Showing ManagedUI from Bootstrapper is problematic. WiX/Burn have a long standing but that prevents BA showing any embeddedUI (not only WixSharp). The but is scheduled to be fixed in WiX v4.0

Though only WiX team can know for sure.

**Comment by oleg-shilo** [comment]
No WiX 4.0 is not available!

Unfortunately found it a hard way. Wasted the whole weekend trying to integrate Wix4 and at the end found that it has a show-stopper bug (https://github.com/wixtoolset/issues/issues/5169) that is not fixed yet.

Chased it further and found that WiX4 binaries I was working with are in fact unreleased builds. As per today (9 Dec 2018) WiX only recommends WiX3.11:

![image](https://user-images.githubusercontent.com/16729806/49693041-2bfa1300-fbbd-11e8-8ea6-c2413ea46c51.png)

**Comment by Torchok19081986** [comment]
Thanks for Info Oleg. i found only  http://wixtoolset.org/releases/v4-0-0-5205/.

**Comment by oleg-shilo** [comment]
Yep, that's the one that I was working with. 

Nothing indicates that it is not the recommended release. Right?!

But the page just one level up says that v3.11.1 is the "Recommended Build": http://wixtoolset.org/releases/

**Comment by Torchok19081986** [comment]
Ok. Only one thing, can you please give me a link for Tutorial of CustomBA. Not wix itself. Maybe some completly begginers guid.
It little bit difficult to know all Info for BA, so that i can create own BA with feature i need.
Then you can close the issue / question.
