### ISSUE TITLE
Can not able to create .msi after publish  Web form Project but its working on windows form.

### ISSUE THREAD

**Issue by renukasaradharao** [oleg-shilo/wixsharp#548]
Hi,

Can anyone please assist me to solve this issue?
   I can not able to create .msi file after publish  Web form Project but its creating successfully in debug mode.
   i installed WiX Toolset v3.11. Is there any issue with my IIS ? i cannot able to figure it out exact error also because its not throwing any exception.

Thanks and Regards,
renuka

**Comment by renukasaradharao** [comment]
I have tight timeline to deliver this portal,  Can anyone please help on above query?

**Comment by renukasaradharao** [comment]
Hi Oleg,
          Could you please assist me on this. i can not able to resolve this issue. .wixpdb file is generating from webform which is hosted in iis but .msi not creating.

**Comment by oleg-shilo** [comment]
I am sorry, but the amount of information you provided is insufficient for understanding the problem. 
The best way to approach it is to create (and post here) a simple hello-world project that illustrates the problem.

You may also find samples collection in this repository. These ~100 samples can be very useful.

**Comment by renukasaradharao** [comment]
hi Oleg,
thank you so much for your reply, here my sample code in webform
public static void Executeexe()
        {
            Process p = new Process();
            p.StartInfo.WindowStyle = ProcessWindowStyle.Normal;
            p.StartInfo.FileName = "cmd.exe";
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardInput = true;
            p.Start();
            p.StandardInput.WriteLine(@"cd C:\\Users\\username\\Documents\\Visual Studio 2015\\Projects\\ConsoleApplication1\\ConsoleApplication1\\bin\\Debug");
            p.StandardInput.WriteLine("ConsoleApplication1.exe abc");
            p.WaitForExit(30000);
        }

**Here msi code  in my consoleApplication**

static void Main(string[] args)
        {
            var project = new Project("MyProduct", new WixSharp.Dir(@"%ProgramFiles%\My Company\My Product", new WixSharp.File("C:\\Files\\Docs\\readme.txt") { AttributesDefinition = "Component:Id=Component.myapp_exe" }, new WixSharp.File("C:\\Files\\Docs\\MyApp.exe", new FileShortcut("MyApp", @"%ProgramMenu%\My Company\My Product"), new FileShortcut("MyApp", @"%Desktop%"))), new WixSharp.Property("ALLUSERS", "1"));
            project.RegValues = WixSharp.CommonTasks.Tasks.ImportRegFile(@"C:\temp\test.reg");
            project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
            WixSharp.Compiler.BuildMsi(project, "c:\\temp\\test14.msi");
        }

iam testing this method "Executeexe"after publish my project to iis , there its failing to create .msi file, where as its creating .msi from visualstudio debug mode.

please help me on this.

**Comment by oleg-shilo** [comment]
This is my understanding that you are trying to build MSI from the Web application backend.

While my immediate reaction is "yes it should be possible" but of course while you are inside of a different runtime there can be plenty of reasons for failure (e.g. execute permissions). 

I suggest you change your `Executeexe` to allow collecting the console output.

```C#
static void Executeexe()
{
    var proc = new Process();
    proc.StartInfo.FileName = "<full path to ConsoleApplication1.exe>";
    proc.StartInfo.Arguments = "abc";
    proc.StartInfo.UseShellExecute = false;
    proc.StartInfo.RedirectStandardOutput = true;
    proc.StartInfo.CreateNoWindow = true;
    proc.Start();
    
    string line = null;
    while (null != (line = proc.StandardOutput.ReadLine()))
    {
        IO.File.AppendText(<your log file>, line+"\r\n");
    }
    proc.WaitForExit();
}

```

**Comment by renukasaradharao** [comment]
Hi Oleg,

i made changes according to your suggestions still iam getting same issue from webapplication which is running through iis. Can you please check below code and correct me if i did wrong.
Here my changes,
 Process proc = new Process();
            proc.StartInfo.FileName = "C:\\Users\\username\\Documents\\Visual Studio 2015\\Projects\\ConsoleApplication1\\ConsoleApplication1\\bin\\Debug\\ConsoleApplication1.exe";
            proc.StartInfo.Arguments = "abc";
            proc.StartInfo.UseShellExecute = false;
            proc.StartInfo.RedirectStandardOutput = true;
            proc.StartInfo.CreateNoWindow = true;
            proc.Start();
            sbLog.Append("Process Started" + Environment.NewLine);
            string line = null;
            while (null != (line = proc.StandardOutput.ReadLine()))
            {
                sbLog.Append(line + "\r\n");
            }
            CreateLogs(path, sbLog);
            proc.WaitForExit();
}

**Comment by oleg-shilo** [comment]
The permission point it was only my speculation. You just need to unsure that you can execute from your web app context and permissions associated with that context may be insufficient. 

What `sbLog` contains?

The code looks OK but you will need to wrap the routine into try catch and catch the exceptions. Just in case if you cannot run the executable at all.

But the best way to diagnose it is to have a break-point in your `Executeexe` and see under debugger what is going on there.

**Comment by oleg-shilo** [comment]
Just a hint...

When posting your code include it into the markdown decoration so it is readable:

\`\`\`C#
\<code\>
\`\`\`

Your posts are readable now because i have fixed them :)
```

**Comment by renukasaradharao** [comment]
ok sure oleg :)
 thank you so much for your help ..
i tried to give network permissions which is worked  but still need to do some more testing.
let you know after successfully created .msi in all scenarios. :)
