### ISSUE TITLE
Maintenance mode with ManagedUI

### ISSUE THREAD

**Issue by Masterkatze** [oleg-shilo/wixsharp#549]
Hello! Is it possible to have a MaintenanceWelcomeDlg in managed UI? Or disable maintenance mode completely when running same .msi again?

**Comment by oleg-shilo** [comment]
You have full freedom of dialog choice:

```C#
project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                .Add<...
                                .Add<ProgressDialog>()
                                .Add<ExitDialog>();

//it effectively becomes a 'Repair' sequence
project.ManagedUI.ModifyDialogs.Add<ProgressDialog>()
                               .Add<ExitDialog>(); 
```

Create your project from the "WixSharp -Custom UI" VS template and you will be able to modify it as much as you need.

**Comment by Masterkatze** [comment]
Cool, thanks! But i can't find out how to implement selection of installation type (repair, modify, uninstall)?

**Comment by oleg-shilo** [comment]
No, you cannot. These are important points to remember:
- `repair/modify` is the same mode. 
- Then the product is installed and the msi file is invoked and it automatically detects the pretense of the product on the system and opens the UI in the  `repair/modify` mode.
