### ISSUE TITLE
Msi want always uninstall product after successfull installation at installfinalize

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#550]
Hallo Oleg, i have one big problem. if i run ms for install, at end of installation i got always mesagebox: "Older Vesion of <Productname> cannot be uninstalled. Please contact your Package Creator."
Log look like 
Log was created by msi : 
Info: === Logging started: 07.12.2018  09:04:18 ===
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: WTSVTESU2
ActionStart: Action 09:04:18: INSTALL. 
Info: Action start 09:04:18: INSTALL.
CommonData: 1: 0 2: 1033 3: 1252 
CommonData: 1: 0 2: 1033 3: 1252 
Info: === Logging started: 07.12.2018  09:04:18 ===
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: WTSVTESU2
ActionStart: Action 09:04:18: INSTALL. 
Info: Action start 09:04:18: INSTALL.
InstallStart: 1: WTSVTESU2 2: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 
ActionStart: Action 09:04:18: FindRelatedProducts. Searching for related applications
Info: Action start 09:04:18: FindRelatedProducts.
ActionData: Found application: {B6C033F0-7026-4173-A837-D0F2E8CC0CF5}
ActionData: Found application: {C68AA3B0-2DEE-4DC1-8133-3C7A247926B0}
Info: Action ended 09:04:18: FindRelatedProducts. Return value 1.
ActionStart: Action 09:04:18: WixSharp_InitRuntime_Action. 
Info: Action start 09:04:18: WixSharp_InitRuntime_Action.
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI3705.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_InitRuntime_Action
Info: Action ended 09:04:19: WixSharp_InitRuntime_Action. Return value 1.
ActionStart: Action 09:04:19: AppSearch. Searching for installed applications
Info: Action start 09:04:19: AppSearch.
Info: Action ended 09:04:19: AppSearch. Return value 0.
ActionStart: Action 09:04:19: ValidateProductID. 
Info: Action start 09:04:19: ValidateProductID.
Info: Action ended 09:04:19: ValidateProductID. Return value 1.
ActionStart: Action 09:04:19: CheckOS. 
Info: Action start 09:04:19: CheckOS.
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI38EB.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WTSVTESU2!TestOS.CustomActions.CheckOS
Info: Action ended 09:04:19: CheckOS. Return value 1.
ActionStart: Action 09:04:19: CheckRole. 
Info: Action start 09:04:19: CheckRole.
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI3949.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WTSVTESU2!TestOS.CustomActions.CheckRole
Info: Action ended 09:04:19: CheckRole. Return value 1.
ActionStart: Action 09:04:19: CostInitialize. Computing space requirements
Info: Action start 09:04:19: CostInitialize.
Info: Action ended 09:04:19: CostInitialize. Return value 1.
ActionStart: Action 09:04:19: FileCost. Computing space requirements
Info: Action start 09:04:19: FileCost.
Info: Action ended 09:04:19: FileCost. Return value 1.
ActionStart: Action 09:04:19: CostFinalize. Computing space requirements
Info: Action start 09:04:19: CostFinalize.
Info: Action ended 09:04:19: CostFinalize. Return value 1.
ActionStart: Action 09:04:19: Set_ARPINSTALLLOCATION. 
Info: Action start 09:04:19: Set_ARPINSTALLLOCATION.
Info: Action ended 09:04:19: Set_ARPINSTALLLOCATION. Return value 1.
ActionStart: Action 09:04:19: Set_ARPNOMODIFY. 
Info: Action start 09:04:19: Set_ARPNOMODIFY.
Info: Action ended 09:04:19: Set_ARPNOMODIFY. Return value 1.
ActionStart: Action 09:04:19: InstallValidate. Validating install
Info: Action start 09:04:19: InstallValidate.
Info: Action ended 09:04:19: InstallValidate. Return value 1.
ActionStart: Action 09:04:19: InstallInitialize. 
Info: Action start 09:04:19: InstallInitialize.
Info: Action ended 09:04:19: InstallInitialize. Return value 1.
ActionStart: Action 09:04:19: Set_CancelRequestHandler_Props. 
Info: Action start 09:04:19: Set_CancelRequestHandler_Props.
Info: Action ended 09:04:19: Set_CancelRequestHandler_Props. Return value 1.
ActionStart: Action 09:04:19: Set_CopyFileForCP_Props. 
Info: Action start 09:04:19: Set_CopyFileForCP_Props.
Info: Action ended 09:04:19: Set_CopyFileForCP_Props. Return value 1.
ActionStart: Action 09:04:19: Set_CreateRegs_Props. 
Info: Action start 09:04:19: Set_CreateRegs_Props.
Info: Action ended 09:04:19: Set_CreateRegs_Props. Return value 1.
ActionStart: Action 09:04:19: Set_OnUninstall_Props. 
Info: Action start 09:04:19: Set_OnUninstall_Props.
Info: Action ended 09:04:19: Set_OnUninstall_Props. Return value 1.
ActionStart: Action 09:04:19: ProcessComponents. Updating component registration
Info: Action start 09:04:19: ProcessComponents.
ActionStart: Action 09:04:19: GenerateScript. Generating script operations for action:
ActionData: Updating component registration
Info: Action ended 09:04:19: ProcessComponents. Return value 1.
ActionStart: Action 09:04:19: UnpublishFeatures. Unpublishing Product Features
Info: Action start 09:04:19: UnpublishFeatures.
Info: Action ended 09:04:19: UnpublishFeatures. Return value 1.
ActionStart: Action 09:04:19: StopServices. Stopping services
Info: Action start 09:04:19: StopServices.
ActionData: Service: Stopping services
Info: Action ended 09:04:19: StopServices. Return value 1.
ActionStart: Action 09:04:19: DeleteServices. Deleting services
Info: Action start 09:04:19: DeleteServices.
Info: Action ended 09:04:19: DeleteServices. Return value 1.
ActionStart: Action 09:04:19: RemoveFiles. Removing files
Info: Action start 09:04:19: RemoveFiles.
Info: Action ended 09:04:19: RemoveFiles. Return value 0.
ActionStart: Action 09:04:19: ExtendDb. 
Info: Action start 09:04:19: ExtendDb.
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI3AD2.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WTSVTESU2!TestOS.CustomActions.ExtendDb
Info: Db VTESU2 wurde erweitert.
Info: Action ended 09:04:33: ExtendDb. Return value 1.
ActionStart: Action 09:04:33: WixSharp_BeforeInstall_Action. 
Info: Action start 09:04:33: WixSharp_BeforeInstall_Action.
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI6F51.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_BeforeInstall_Action
Info: Action ended 09:04:33: WixSharp_BeforeInstall_Action. Return value 1.
ActionStart: Action 09:04:33: InstallFiles. Copying new files
Info: Action start 09:04:33: InstallFiles.
ActionData: File: Copying new files,  Directory: ,  Size: 
Info: Action ended 09:04:33: InstallFiles. Return value 1.
ActionStart: Action 09:04:33: Set_WixSharp_AfterInstall_Action_Props. 
Info: Action start 09:04:33: Set_WixSharp_AfterInstall_Action_Props.
Info: Action ended 09:04:33: Set_WixSharp_AfterInstall_Action_Props. Return value 1.
ActionStart: Action 09:04:33: WixSharp_AfterInstall_Action. 
Info: Action start 09:04:33: WixSharp_AfterInstall_Action.
ActionData: 
Info: Action ended 09:04:33: WixSharp_AfterInstall_Action. Return value 1.
ActionStart: Action 09:04:33: InstallServices. Installing new services
Info: Action start 09:04:33: InstallServices.
ActionData: Service: 
Info: Action ended 09:04:33: InstallServices. Return value 1.
ActionStart: Action 09:04:33: SchedServiceConfig. 
Info: Action start 09:04:33: SchedServiceConfig.
ActionStart: Action 09:04:33: RollbackServiceConfig. 
Info: Action start 09:04:33: RollbackServiceConfig.
ActionData: 
Info: Action ended 09:04:33: RollbackServiceConfig. Return value 1.
ActionStart: Action 09:04:33: ExecServiceConfig. 
Info: Action start 09:04:33: ExecServiceConfig.
ActionData: 
Info: Action ended 09:04:33: ExecServiceConfig. Return value 1.
Info: Action ended 09:04:33: SchedServiceConfig. Return value 1.
ActionStart: Action 09:04:33: MsiConfigureServices. 
Info: Action start 09:04:33: MsiConfigureServices.
ActionData: 
Info: Action ended 09:04:33: MsiConfigureServices. Return value 1.
ActionStart: Action 09:04:33: StartServices. Starting services
Info: Action start 09:04:33: StartServices.
Info: Action ended 09:04:33: StartServices. Return value 1.
ActionStart: Action 09:04:33: RegisterUser. Registering user
Info: Action start 09:04:33: RegisterUser.
Info: Action ended 09:04:33: RegisterUser. Return value 1.
ActionStart: Action 09:04:33: RegisterProduct. Registering product
Info: Action start 09:04:33: RegisterProduct.
ActionData: Registering product
Info: Action ended 09:04:33: RegisterProduct. Return value 1.
ActionStart: Action 09:04:33: PublishFeatures. Publishing Product Features
Info: Action start 09:04:33: PublishFeatures.
ActionData: Feature: Publishing Product Features
Info: Action ended 09:04:33: PublishFeatures. Return value 1.
ActionStart: Action 09:04:33: PublishProduct. Publishing product information
Info: Action start 09:04:33: PublishProduct.
ActionData: 1: Publishing product information 
Info: Action ended 09:04:33: PublishProduct. Return value 1.
ActionStart: Action 09:04:33: CancelRequestHandler. 
Info: Action start 09:04:33: CancelRequestHandler.
ActionData: 
Info: Action ended 09:04:33: CancelRequestHandler. Return value 1.
ActionStart: Action 09:04:33: CopyFileForCP. 
Info: Action start 09:04:33: CopyFileForCP.
ActionData: 
Info: Action ended 09:04:33: CopyFileForCP. Return value 1.
ActionStart: Action 09:04:33: CreateRegs. 
Info: Action start 09:04:33: CreateRegs.
ActionData: 
Info: Action ended 09:04:33: CreateRegs. Return value 1.
ActionStart: Action 09:04:33: InstallFinalize. 
Info: Action start 09:04:33: InstallFinalize.
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: WTSVTESU2
ActionStart: Action 09:04:33: ProcessComponents. Updating component registration
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9ACBDCD4E30} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\WTSVTESU2.exe 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9AC884E6209} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\TSCP.exe 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9AC51C42A7B} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\TSCP.exe.config 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9AC49CF8C25} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\timetorun.xml 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9AC93AC3FD5} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\ExtendDb.sql 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9AC38D64AF8} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\ExtendDb2.sql 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9ACCF3C7C56} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\VTESU2WTS.ini 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 2: {B560A7F8-EB89-4C6A-B652-F9AC20309411} 3: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\vtesu2amwts.reg 
ActionStart: Action 09:04:33: StopServices. Stopping services
ActionStart: Action 09:04:33: InstallFiles. Copying new files
ActionData: File: ExtendDb.sql,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\,  Size: 680
ActionData: File: ExtendDb2.sql,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\,  Size: 532
ActionData: File: timetorun.xml,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\,  Size: 164
ActionData: File: TSCP.exe.config,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\,  Size: 163
ActionData: File: TSCP.exe,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\,  Size: 61440
ActionData: File: vtesu2amwts.reg,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\,  Size: 566
ActionData: File: VTESU2WTS.ini,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\Config\,  Size: 20
ActionData: File: WTSVTESU2.exe,  Directory: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\,  Size: 58880
ActionStart: Action 09:04:33: WixSharp_AfterInstall_Action. 
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI702E.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
ActionStart: Action 09:04:33: InstallServices. Installing new services
ActionData: Service: 
ActionStart: Action 09:04:33: RollbackServiceConfig. 
ActionStart: Action 09:04:33: ExecServiceConfig. 
ActionStart: Action 09:04:33: MsiConfigureServices. 
ActionStart: Action 09:04:33: RegisterProduct. Registering product
ActionData: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB}
ActionStart: Action 09:04:33: PublishFeatures. Publishing Product Features
ActionData: Feature: Complete
ActionStart: Action 09:04:33: PublishProduct. Publishing product information
ActionData: 1: app_icon.ico 
ActionData: 1: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 
ActionStart: Action 09:04:33: CancelRequestHandler. 
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI70FB.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.CancelRequestHandler
ActionStart: Action 09:04:33: CopyFileForCP. 
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI713B.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WTSVTESU2!TestOS.CustomActions.CopyFileForCP
Info: Paths:
installdir: C:\Program Files\VTE Teichmann GmbH\VTESU2WTS\,
windir: C:\Windows
ActionStart: Action 09:04:33: CreateRegs. 
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI719A.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WTSVTESU2!TestOS.CustomActions.CreateRegs
CommonData: Message type: 2, Argument: 0
ActionStart: Action 09:04:34: RollbackCleanup. Removing backup files
ActionData: File: C:\Config.Msi\4fe36ea.rbf
CommonData: Message type: 2, Argument: 1
Info: Action ended 09:04:34: InstallFinalize. Return value 1.
ActionStart: Action 09:04:34: RemoveExistingProducts. Removing applications
Info: Action start 09:04:34: RemoveExistingProducts.
ActionData: Application: {B6C033F0-7026-4173-A837-D0F2E8CC0CF5}, Command line: UPGRADINGPRODUCTCODE={B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} CLIENTPROCESSID=1000 CLIENTUILEVEL=3 MSICLIENTUSESEMBEDDEDUI=1 REMOVE=ALL
CommonData: 1: 0 2: 1033 3: 1252 
ResolveSource: 1: 0 2: WTS-Installer.msi 3: {B6C033F0-7026-4173-A837-D0F2E8CC0CF5} 4: {B6C033F0-7026-4173-A837-D0F2E8CC0CF5}; 5: 0 6: 1 7: 1 8: 0 
Info: CustomAction  returned actual error code 1612 (note this may not be 100% accurate if translation happened inside sandbox)
Error: The older version of WTS cannot be removed. Contact your technical support group. 
ActionData: Application: {C68AA3B0-2DEE-4DC1-8133-3C7A247926B0}, Command line: UPGRADINGPRODUCTCODE={B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} CLIENTPROCESSID=1000 CLIENTUILEVEL=3 MSICLIENTUSESEMBEDDEDUI=1 REMOVE=ALL
CommonData: 1: 0 2: 1033 3: 1252 
ResolveSource: 1: 0 2: VTESU2-WTS-Installer.msi 3: {C68AA3B0-2DEE-4DC1-8133-3C7A247926B0} 4: {C68AA3B0-2DEE-4DC1-8133-3C7A247926B0}; 5: 0 6: 1 7: 1 8: 0 
Info: CustomAction  returned actual error code 1612 (note this may not be 100% accurate if translation happened inside sandbox)
Error: The older version of WTSVTESU2 cannot be removed. Contact your technical support group. 
Info: Action ended 09:04:36: RemoveExistingProducts. Return value 3.
Info: Action ended 09:04:36: INSTALL. Return value 3.
InstallEnd: 1: WTSVTESU2 2: {B560A7F8-EB89-4C6A-B652-F9AC1CED64FB} 3: 3 
CommonData: 1: 2 2: 0 
CommonData: 1: 2 2: 1 
Info: Action ended 09:04:36: INSTALL. Return value 3.

This product is at moment not installed. No regkeys or anyone parts of it in registry to find.
Why msi want to uninstall my product if it not installed .

I start in event UIInitialized only elevated routine for check if user are administrator and if he ist admin, then check for some installed components via CA. 
code: 

            if (!new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator))
            {
                MessageBox.Show("You must start the msi file as admin for ", e.ProductName + ".\r\nApplication will be restarted elevated as Administrator. Please Wait...", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            e.Result = ActionResult.Failure;

                var startInfo = new ProcessStartInfo
                {
                    UseShellExecute = true,
                    WorkingDirectory = Environment.CurrentDirectory,
                    FileName = "msiexec.exe",
                    Arguments = "/i \"" + e.MsiFile + "\"",
                    Verb = "runas"
                };

                Process.Start(startInfo);
            }
            else
            {
                if (Funktions.IsWindowsServer() == true)
                {
                    if (Funktions.HasServerFetureById(18) == false) //ID 18 ist die RDP Rolle für WTS.
                    {
                        e.ManagedUI.Shell.ErrorDetected = true;

                        e.Result = ActionResult.Failure;
                    }
                }
                else
                {
                    MessageBox.Show("Aktuelle Betriebssystem ist nicht Windows Server oder ist unter Windows Server 2008 R2.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);

                    e.ManagedUI.Shell.ErrorDetected = true;
                    e.Result = ActionResult.UserExit;
                }
            }  
        } 
thats all.

**Comment by Xaddan** [comment]
Why launch a new instance of the installer with elevated privileges? The installer himself will do it if necessary!

**Comment by Torchok19081986** [comment]
i have to , because windows service need to be installed elevated, if not, service couldnt be installed.
if i remove elevated code , i cant install windows service. With elevated start , works fine.

**Comment by Xaddan** [comment]
This will force the installer to elevate the privileges.
`Project.InstallScope = InstallScope.perMachine;`

**Comment by Torchok19081986** [comment]
thanks for info. going to try it and give some feedback.

**Comment by Torchok19081986** [comment]
is there some diffrence in MajorStrategy.Default and new MajorUpgradeStrategy { ... } ? I didnt knew it.

**Comment by oleg-shilo** [comment]
Yes there is a difference: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#product-upgrades
