### ISSUE TITLE
Cannot include extra .wxs as part of a bundle

### ISSUE THREAD

**Issue by jonreis** [oleg-shilo/wixsharp#551]
Hello Oleg as always, thank you very much for providing such a fantastic tool. I am not sure if this is an issue, or a question on how to correctly include external wxs files as part of the build process.

WixSharp version: v1.9.3
Issue: I am attempting to add a dependency on .NET 4.7.2 (see attached wxs file)

I have created a bundle, and tried to add a wxs file as follows:

      var net472Path = Path.Combine(SolutionDir, "Connexion.Setup.WixBA", "WixNet4.7.2.wxs");
      bundle.WxsFiles.Add(net472Path);

When I try and build the bundle, I get the following error:

2>E:\connexion\Connexion.Setup.WixBA\candle.exe : error CNDL0001: Cannot specify more than one source file with single output file.  Either specify an output directory for the -out argument by ending the argument with a '\' or remove the -out argument to have the source files compiled to the current directory.
2>  Parameter name: -out

It seems that the error is in the code that generates the Candle command line.

                    string wxsFiles = "";
                    foreach (string file in project.WxsFiles.Distinct())
                        wxsFiles += " \"" + file + "\"";

                    var candleOptions = CandleOptions + " " + project.CandleOptions;
                    string command = (candleOptions + " " + extensionDlls + " \"" + wxsFile + "\" " + wxsFiles + " -out \"" + objFile + "\"").ExpandEnvVars();

from the error message it seems that -out should point to a directory, not a specific file. If I build a previous version of our product that did not use WixSharp and look at the output, I see the following being set for -out:

-out obj\Release\

Also, the Light command line should include a list of wixobj files.

The full command-lines for Candle and Light on our previous product without WixSharp are included as an attachment in case they provide any help.

[WixNet4.7.2.zip](https://github.com/oleg-shilo/wixsharp/files/2665825/WixNet4.7.2.zip)
[CommandLines.txt](https://github.com/oleg-shilo/wixsharp/files/2665928/CommandLines.txt)

**Comment by oleg-shilo** [comment]
Yep, you are absolutely right.   
This is how it's done for msi compilation:
```C#
if (wxsFiles.IsNotEmpty())
{
    candleCmdLineParams.Append(wxsFiles);

    // if multiple files are specified candle expect a path for the -out switch
    // or no path at all (use current directory)
    // note the '\' character must be escaped twice: as a C# string and as a CMD char
    if (outDir.IsNotEmpty())
        candleCmdLineParams.AppendFormat(" -out \"{0}\\\\\"", outDir);
}
else
    candleCmdLineParams.AppendFormat(" -out \"{0}\"", objFile);
```

This approach will need to be repeated for Bandle.

Thank you for reporting it.

**Comment by mgkeeley** [comment]
I tried to add a wxs file to a Bundle using 1.9.4 - it seems the extra .wxs files are now passed to candle.exe correctly; but the corresponding .wixobj files are not passed to light.exe

**Comment by oleg-shilo** [comment]
Will have a look...

**Comment by oleg-shilo** [comment]
After having a look at the current implementation I am no longer sure it is inadequate. 

Your assumption is that if two wxs files (a.wxs and b.wxs) are passed to the candle.exe the compiler will produce two wixobj files (a.wixobj and b.wixobj).

However I see no evidence that this assumption is accurate. Thus candle.exe allows specifying only a sinlge output `wixobj` file. So my assumption was that of that candle.exe always produces a single wixobj file. 

I could not find any sample of multi wxs input so I cannot test neither of these mutually exclusive assumptions so I cannot really proceed with any fix.

Can you please share a simple example that I can use for testing?

Another point, you can easily temporary fix problems like that by building a _build batch file_ instead: 
```C#
project.BuildMsiCmd();
``` 
The code below will create a batch file where you can add any input parameters (e.g. extra wxs and wixobj files).

**Comment by mgkeeley** [comment]
When specifying multiple .wxs files, you must specify a (single) output directory to candle, not an output file. The .wixobj files are placed in this directory.
I don't have a simple example ready, but you can look at the existing code in Compiler.GenerateLightCommand() - this performs the multi-wixobj linking already for msi files. The same just needs to be replicated for the bootstrapper compiler.
I can provide an example a bit later if you still require it - please let me know.

**Comment by mgkeeley** [comment]
[MultiWxsBundle.zip](https://github.com/oleg-shilo/wixsharp/files/2970881/MultiWxsBundle.zip)
I attached an example for you.

**Comment by oleg-shilo** [comment]
OK I see. Txs. Will have a look right away.

**Comment by oleg-shilo** [comment]
Done. Also tested with your sample. Thank you for helping with the investigation.

The fix will be available in the very next release.

**Comment by mgkeeley** [comment]
Thanks for your prompt attention to these issues!  Do you have an idea of when the next release will be?

**Comment by oleg-shilo** [comment]
Yeah, this Monday or so.
