### ISSUE TITLE
Question: Install 2 windows services in same installer

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#552]
Hallo, how to you ServiceInstaller for install 2 different windows services or use installutil.exe twice ?
Is there some posibility ?

**Comment by Xaddan** [comment]
```C#
new File("Svr1.exe",
  new ServiceInstaller
  {
    Name = "Svr1",
    DisplayName = "Svr1",
    Description = "Svr1",
    StartOn = SvcEvent.Install_Wait,
    DependsOn = ServicesNameTimeAdjust,
    StopOn = SvcEvent.InstallUninstall_Wait,
    RemoveOn = SvcEvent.Uninstall_Wait,
    DelayedAutoStart = true,
    StartType = SvcStartType.auto,
    FirstFailureActionType = FailureActionType.restart,
    SecondFailureActionType = FailureActionType.restart,
    ThirdFailureActionType = FailureActionType.restart,
    RestartServiceDelayInSeconds = 10,
    ResetPeriodInDays = 1,
    RebootMessage = "Failure actions do not specify reboot",
  }),
new File("Svr2.exe",
  new ServiceInstaller
  {
    Name = "Svr2",
    DisplayName = "Svr2",
    Description = "Svr2",
    StartOn = SvcEvent.Install_Wait,
    DependsOn = ServicesNameTimeAdjust,
    StopOn = SvcEvent.InstallUninstall_Wait,
    RemoveOn = SvcEvent.Uninstall_Wait,
    DelayedAutoStart = true,
    StartType = SvcStartType.auto,
    FirstFailureActionType = FailureActionType.restart,
    SecondFailureActionType = FailureActionType.restart,
    ThirdFailureActionType = FailureActionType.restart,
    RestartServiceDelayInSeconds = 10,
    ResetPeriodInDays = 1,
    RebootMessage = "Failure actions do not specify reboot",
  }),
```

**Comment by grahamcarson** [comment]
This doesn't work. You end up with the Component element for both services having a ServiceControl element with an Id of StartSvr2. This generates an error when Wix tries to interpret the wxs file and no msi is created.

There are 2 factors to this:
SvcEvent.Install_Wait is a static instance so all  ServiceInstallers have a reference to the same instance.
The setter for the StartOn property modifies the Name and Id of the passed in SvcEvent. This means that the SvcEvent that all ServiceInstallers share ends up with the Name and Id of the last service it was passed to.

The same thing happens with StopOn and RemoveOn.

The solution I have used is to create new instances of SvcEvent for each ServiceInstaller. As SvcEvent has a private constructor and one of the properties that needs setting is protected this requires some rather nasty reflection.

I don't think that the setter of OnStart should be modifying the object passed into it.

**Comment by oleg-shilo** [comment]
Promoting it to 'Enhancement'

**Comment by Xaddan** [comment]
Oleg, you are not flooded commits 556bc4ea9596c9b32eee38ee5ed9d345e97d7671 and 6007f95ec3391969563da4ed4163ce5430cde814 of branches wix-3.11 to the master branch.

**Comment by oleg-shilo** [comment]
It is a very interesting one.

> SvcEvent.Install_Wait is a static instance so all ServiceInstallers have a reference to the same instance.

Actually it is not the same instance. These are the static properties the return a fresh new instance of the class on every access:

![image](https://user-images.githubusercontent.com/16729806/51380862-cbb8a280-1b66-11e9-892a-f33673b270d2.png)
 
I still don't see a good reason for keeping constructor private but it is a different story.

Please share your Reflection based solution so I can see what can be done to solve this problem.

**Comment by oleg-shilo** [comment]
Yep 556bc4e was not merged. Now fixed.
But 6007f95 was in. That's the test screenshot above shows `theSame` as false.

Anyway 556bc4e is a vital one. Will aim for a release over weekend.

**Comment by grahamcarson** [comment]
I am using v1.9.3.0 of WxisSharp. In this version SvcEvent.InstallUninstall_Wait is a public field rather than a public property. This means that all the ServiceInstallers will have the same instance.
v1.9.3.0 is the latest available on nuget, do I need a later version ?

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release
