### ISSUE TITLE
Caught InvalidOperationException

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#553]
We have a first chance exception handler attached often, and I seeing this in the logging therefore.

The exception seems to be caught and have no negative consequences, but maybe it can be improved by explicitly checking whether there are any elements:

```
2018-12-28 15:15:31: First chance exception handling of type 'InvalidOperationException':
2018-12-28 15:15:31: Sequence contains no elements
2018-12-28 15:15:31: Stack trace:
2018-12-28 15:15:31:    ...
   at Invantive.Deploy.Error.CurrentDomain_FirstChanceException(Object sender, FirstChanceExceptionEventArgs e)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at WixSharp.Compiler.EnsureVSIntegration() <<<<<< Here a check could be done.
   at WixSharp.Compiler..cctor()
   at WixSharp.Compiler.get_AutoGeneration()
   at WixSharp.Project..ctor(String name, WixObject[] items)
   at (String , WixObject[] )
   at SIDY.BT.S(String , WixObject[] )
   at EXTERNAL CODE

```
Occurs on v1.9.3.

**Comment by monty241** [comment]
It seems that something is wrong with my Wix# definitions, but to analyze the issue dove a little deeper into error (there are more subsequent caught exceptions).

It seems that the following code triggers the error in EnsureVSIntegration:
````
var itemGroup = doc.Root.Descendants().Where(e => e.Name.LocalName == "Compile").First().Parent;
````
and that all exceptions are suppressed (do not know why):
````
catch { }
````
Maybe the 'catch' can go and a check can be added that there is a First() one and when not an appropriate error is raised?

**Comment by oleg-shilo** [comment]
The catch statement is deliberately empty in this case.

The whole `EnsureVSIntegration` method is responsible for adding to your VS project a **non-compilable** "*.g.wxs". Meaning that:
- The whole purpose of `EnsureVSIntegration` is pure cosmetic - just to let user to access "*.g.wsx" file from Visual Studio.
- There is a high chance of failure as the method depends on the project file undocumented structure, which is subject to change by the third party (MS).
- A complete failure of `EnsureVSIntegration` does not affect the MSI authoring outcome.  
- Any failure of `EnsureVSIntegration` is not recoverable.

Thus I am not sure if this really affects your compilation or there is some other reason for the failure.

**Comment by monty241** [comment]
Thanks for the elaboration. Clear. It was indeed just something I came across when I had the first chance exception handler attached.

Just as a suggestion: I always like to read some comment elaborating why all exceptions are ignored and if possible try to finetune the types being ignored instead of ignoring all exception types.

Having a great transition into 2019!

**Comment by oleg-shilo** [comment]
>  I always like to read some comment elaborating why all exceptions are ignored

Fair enough. Addressed. If you pull the latest master the comments will be there.

Happy New Year to you too :)
