### ISSUE TITLE
Copying VS project and item templates to current user's documents Visual Studio sub folders

### ISSUE THREAD

**Issue by jmothershead** [oleg-shilo/wixsharp#556]

**Comment by jmothershead** [comment]
I have created Visual Studio project and item templates specific to the application I am creating.  I want them to be accessible within VS when adding a project type  or item type.  According to MSDN, the files need to be placed under the appropriate VS version subfolder (e.g., "C:\Users\<username>\Documents\\Visual Studio 2017\Templates\ItemTemplates".  Any suggests or pointers as to how to accomplish this?  Thanks!

-Jim

**Comment by oleg-shilo** [comment]
Sorry, but you will have more chances to find your answer on some generic MSDN/VS forums. 
This place is for discussing WixSharp topics.

**Comment by oleg-shilo** [comment]
OK, I see.
Agree. VS extension hoste on VS Market Place is the best way of distributing VS project templates.
