### ISSUE TITLE
Windows service Msi not generated on build

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#557]
I have a console project to generate an Msi  for a windows service using wix sharp. Normally the msi is generated when I build the project. This not the case now. However , if I start the project from visual studio the msi is generated.

Please help as I need the msi to be generated when I build as I am using Team services to deploy my msi files

Thanks Laz

**Comment by oleg-shilo** [comment]
If you add the WixSharp package from NuGet it will automatically adjust the project _build steps_.

Though if you are doing it from a simple console app project then you can just trigger the build from post-build event as `${TargetPath}`

Read more here: https://github.com/oleg-shilo/wixsharp/wiki/VS2013-%E2%80%93-2015-Templates#msi-authoring-steps

**Comment by ltemimi** [comment]
I have updated the post build event  with "$TargetPath)" and I got an error. Then I updated Wix# to 1.9.3 and it all worked great.
Thanks for the help
