### ISSUE TITLE
Orca ICE57 warning: Component '...' has both per-user and per-machine data with an HKCU Registry KeyPath.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#559]
As documentation for reference and for Google Search on ICE57 warning from Orca.

When you run ORCA Validate on a default generated MSI from WixSharp, you will receive:

Orca ICE57 warning: Component '...' has both per-user and per-machine data with an HKCU Registry KeyPath.

Microsoft documentation on ICE57: https://docs.microsoft.com/en-us/windows/desktop/msi/ice57

From #378 , it seems that the method `InsertUserProfileRegValue` adds entries to the registry under HKCU on the key 'Software\WixSharp\Used' for a component. It is enabled/disabled by  the boolean DisableAutoUserProfileRegistry in AutoElements.cs. The boolean is false by default.

It seems from the issue that this logic is better enabled by default for a better out-of-the-box experience and that the warning ICE57 can safely be ignored.

If not correct, please react. Otherwise question can be closed.

**Comment by oleg-shilo** [comment]
> ...this logic is better enabled by default for a better out-of-the-box experience ...

Absolutely, However, unfortunately it's not that simple. 

Disabling AutoUserProfileRegistry indeed triggers ICE57 warning that user can indeed choose to ignore. But is also triggers **errors** that are show stoppers quite a few WixSharp code samples (AllInOne, ConditionalInstallation, CustomAttributes, ReleaseFolder, Shortcuts, Shortcuts (advertised), Shortcuts-2, WildCardFiles):

![image](https://user-images.githubusercontent.com/16729806/50965090-17df6380-1525-11e9-88b8-4089ec21a4c0.png)

Thus I have no choice but to keep it the work around enabled by default.

But I agree with you principle, ideally the warning should be emitted by default.

**Comment by monty241** [comment]
Thanks for your feedback. We have to live with it :-)
