### ISSUE TITLE
Allow specification of WXS location outside of current location with BuildMsi.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#563]
For archival purposes, we would like to put the generated WXS file in a deviating location. Currently, in Compiler.Build, the BuildWxs method is used without value for WXS file path.

Would be helpful when the location could be specified through BuildMsi, saving one call to BuildWxs to create an archive file.

**Comment by oleg-shilo** [comment]
It is not that simple. The location of the WXS file is not random. It is carefully chosen so the internal references to the input files (relative paths) can be resolved by the compilers.

A better option for your case can be to disable deletion of the WXS at the end of compilation:
```C#
project.PreserveTempFiles = true;
project.BuildMsi();
``` 
After that you can just copy the WXS file to any location of your choice.

**Comment by monty241** [comment]
Yes, that would be an option. However, it would require duplicating the way the wxs path is calculated from wixsharp in our code. That is the reason why the (slower) buildwxs was used.

Would it be possible to store the name of the last WXS file generated in Project object? And then use that one after build? Dito for batch file.

**Comment by oleg-shilo** [comment]
While I agree with your proposal in principle I do not want to modify API unless it does not satisfy some real life scenarios. Particularly in this case as the set of the files that are produced by WixSharp is context specific (bat, wxs, msm, msi, dll) and can also include non-deterministic file collection produced by the WiX compilers.

> ...it would require duplicating the way the wxs path is calculated from wixsharp in our code...

May be there are still some options you can consider. Like this one:
```c#
project.PreserveTempFiles = true;
string wxsFile = project.BuildMsi().PathChangeExtension(".wxs");
```
