### ISSUE TITLE
Correct variable name of SequentialGuid initialization.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#564]
In WixGuid.cs it reads:

            /// <summary>
            /// Initializes a new instance of the <see cref="SequentialGuid"/> class.
            /// </summary>
            /// <param name="previousGuid">The previous GUID.</param>
            public SequentialGuid(Guid previousGuid)
            {
                CurrentGuid = previousGuid;
            }

I think this it meant:

            /// <summary>
            /// Initializes a new instance of the <see cref="SequentialGuid"/> class.
            /// </summary>
            /// <param name="initialGuid">The initial GUID value.</param>
            public SequentialGuid(Guid initialGuid)
            {
                CurrentGuid = initialGuid;
            }

**Comment by oleg-shilo** [comment]
Agree. Done.
