### ISSUE TITLE
Question: How to set property in dialog

### ISSUE THREAD

**Issue by achikhv** [oleg-shilo/wixsharp#565]
I'm trying to write property to registry. Property should be set in custom dialog.

Im my custom dialog I call 
Runtime.Session["MyProperyName"] = propertyValue;

In RegValue element I want to write this property to registry:
new RegValue(feature, RegistryHive.LocalMachine, registryKeyPath, "Owner", 
"[MyPropertyName]");

After installation is complete empty value is written to registry. I tried to register properties in project using AddProperty method, still no effect.

Could you please tell me what am I missing? 

UPD:
If I register property via project.AddProperty I get default value written in registry. So the final question is: how to change property value in custom dialog? Runtime.Session["name"] = value does not work.

**Comment by achikhv** [comment]
Figured it out. I need to use [public](http://msdn.microsoft.com/en-us/library/aa370912%28VS.85%29.aspx) properties with all uppercase name.

**Comment by oleg-shilo** [comment]
Ha ha, I was just testing the solution and noticed your post.
And, yes uppercasing was my first candidate that I was testing.
