### ISSUE TITLE
Cant create new project from Template Wix Sharp

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#577]
Hallo Oleg, i updated my VS 2017 and since update i cant create new project from Template. Error appears , that package.config could be founded on <path>. Tested on 3 various developer pcs, always same issue. strangely project can be created in default path, but visual stduio say error and project doesnt appear. 
reset of settings broutght no improvement. what should i do ? another projects with package.config as reference can be created - successfully.

**Comment by oleg-shilo** [comment]
Looking in to it.

**Comment by Torchok19081986** [comment]
maybe it help a little. a found older developer machine, where VS 2017 Update 15.9.5 are not installed. Here is 15.9.2 installed. Create new Wixsharp Project from template can be done sucessfully and error doesnt appears.

**Comment by Torchok19081986** [comment]
Many thanks Oleg for quick answer.

**Comment by oleg-shilo** [comment]
Did the fix work?

**Comment by oleg-shilo** [comment]
Great.
