### ISSUE TITLE
Projects with CustomActions failing to build

### ISSUE THREAD

**Issue by AvramM** [oleg-shilo/wixsharp#578]
Any project including a CustomAction seems to fail. My own project looks like this:

```
using System;
using System.IO;
using System.Windows.Forms;
using Microsoft.Deployment.WindowsInstaller;
using WixSharp;

namespace Installer
{
    class Program
    {
        static void Main()
        {
            var project = new Project("Test",
                new Dir(@"%ProgramFiles%\Test",
                    new DirFiles(@"C:\Test\*.*")),
                new Dir(@"%ProgramMenu%",
                    new ExeFileShortcut("Test", Path.Combine("[INSTALLDIR]", "Launcher.exe"),
                            arguments: "")
                        { WorkingDirectory = "[INSTALLDIR]" }),
                new ManagedAction(CustomActions.MyAction));

            project.GUID = new Guid("93fefff9-91b2-4c44-8b13-9aad00c8f6a3");
            project.Platform = Platform.x64;
            project.Version = new Version(2, 0, 0, 0);
            project.UI = WUI.WixUI_ProgressOnly;
            project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;

            project.BuildMsi();
        }
    }

    public static class CustomActions
    {
        [CustomAction]
        public static ActionResult MyAction(Session session)
        {
            MessageBox.Show("Test", "Test");//Environment.GetCommandLineArgs().ConcatItems(" "));
            session.Log("Begin MyAction Hello World");

            return ActionResult.Success;
        }
    }
}
```

Also, I tried building the AdminInstall sample in Visual Studio, which also fails to build. Still a problem with the VS integration?

**Comment by oleg-shilo** [comment]
Can you confirm that it is still failing for you with yesterday VS Project template update?

**Comment by AvramM** [comment]
Confirmed. Still fails.

**Comment by Torchok19081986** [comment]
i had same error. Try add to your CA, values like Return.check, When.before, Step.INSTALL, Condition.NOT_Installed. After added this parameters my error appear not anymore.

**Comment by oleg-shilo** [comment]
Just to rule out the environment as a suspect, tr to open and build the attached sample. It includes the NuGet package so you do not depend on you environment ability to download the packages.
[WixSharp Setup3.zip](https://github.com/oleg-shilo/wixsharp/files/2791290/WixSharp.Setup3.zip)

**Comment by AvramM** [comment]
Confirmed - doesn't build.

**Comment by oleg-shilo** [comment]
The it means that your and my environments are different. The only WixSharp dependency that does not come from WixSharp package is WiX itself.
Any chance you have  version 4? or even both v3.11 and v4?

**Comment by AvramM** [comment]
My `WIXSHARP_WIXDIR` is set to `C:\bin\WixSharp.1.9.3.0\Wix_bin\bin`

No version 4 installed. It's very puzzling. I'll try it at home tonight with a completely different system.

**Comment by oleg-shilo** [comment]
Yes, that's odd.

My advice, minimize the amount of "variables in this equation". Replace `project.Build(...)` with `project.BuildCmd(...)`. This wil prepare the WiX source files (*.wsx) and a batch file that can invoke WiX compilers directly and build the msi. 

Effectively from that moment WixSharp is no longer in the picture. If one cannot build msi then it is either because there is a mistake in the produced wxs or there is a problem with the WiX compilers.

This would be the easiest way to minvestigate it.

**Comment by AvramM** [comment]
It can't build it with BuildMsiCmd either.

**Comment by oleg-shilo** [comment]
Good. :)
The we have one suspect less. 

What is the error output?

**Comment by AvramM** [comment]
1>------ Build started: Project: WixSharp Setup3, Configuration: Debug Any CPU ------
1>  WixSharp Setup3 -> C:\Downloads\WixSharp.Setup3\WixSharp Setup3\bin\Debug\WixSharpSetup.exe
1>  Building MSI
1>  <- Packing managed CA:
1>  C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\MakeSfxCA.exe "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\%this%.CA.dll" "C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\x86\sfxca.dll" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\WixSharpSetup.exe" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\CustomAction.config" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\WixSharpSetup.pdb" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\bin\Debug\WixSharp.dll"  "C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\Microsoft.Deployment.WindowsInstaller.dll"
1>  ->
1>EXEC : error : C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\x86\sfxca.dll
1>  
1>  Unhandled Exception: System.ApplicationException: Cannot package ManagedCA assembly(%this%)
1>     at WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String configFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
1>     at WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
1>     at WixSharp.Compiler.GenerateWixProj(Project project)
1>     at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
1>     at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
1>     at WixSharp.Compiler.BuildCmd(Project project, String path, OutputType type)
1>     at WixSharp.Compiler.BuildMsiCmd(Project project, String path)
1>     at WixSharp.Compiler.BuildMsiCmd(Project project)
1>     at WixSharp.Project.BuildMsiCmd(String path)
1>     at WixSharp_Setup3.Program.Main() in C:\Downloads\WixSharp.Setup3\WixSharp Setup3\Program.cs:line 25
1>C:\Downloads\WixSharp.Setup3\packages\WixSharp.1.9.4\build\WixSharp.targets(6,5): error MSB3073: The command ""C:\Downloads\WixSharp.Setup3\WixSharp Setup3\bin\Debug\WixSharpSetup.exe" "/MSBUILD:WixSharp Setup3" "/WIXBIN:"" exited with code -532459699.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by oleg-shilo** [comment]
What is the target CLR in the project props?

**Comment by AvramM** [comment]
.Net Framework 3.5

**Comment by oleg-shilo** [comment]
OK.

Try to define the assembly name explicitly, just in case it's not resolved correctly:

```c#
new ManagedAction(CustomActions.MyAction)
{
    ActionAssembly = typeof(CustomActions).Assembly.Location
}
```

If this does not help see if you can build ManagedProject with events. It defines managed assembly slightly differently.

![image](https://user-images.githubusercontent.com/16729806/51974623-74a2be00-24d4-11e9-9c74-50bf0d142cf2.png)

**Comment by oleg-shilo** [comment]
One thing is for sure we are failing to pack the managed CA.

**Comment by AvramM** [comment]
The managed setup also fails to build.

**Comment by oleg-shilo** [comment]
That's normal. We are failing before it is generated.

We are failing to generate the WiX assembly package. 

Collect the exact CLI command and try to execute it command prompt.
It will be something like that:
```ps
C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\MakeSfxCA.exe "C:\Downloads\WixSharp.Setup3\WixSharp Setup3%this%.CA.dll" "C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\x86\sfxca.dll" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\WixSharpSetup.exe" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\CustomAction.config" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\WixSharpSetup.pdb" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\bin\Debug\WixSharp.dll" "C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\Microsoft.Deployment.WindowsInstaller.dll"
```
For some reason MakeSfxCA.exe (one of WiX compilers) is failing. 

See if it produces any extra error output that WixSharp may be missing.

**Comment by AvramM** [comment]
Progress!!

OK, the exact command line is:

`C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\MakeSfxCA.exe "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\WixSharpSetup.CA.dll" "C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\x86\sfxca.dll" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\bin\Debug\WixSharpSetup.exe" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\CustomAction.config" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\bin\Debug\WixSharpSetup.pdb" "C:\Downloads\WixSharp.Setup3\WixSharp Setup3\bin\Debug\WixSharp.dll"  "C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\Microsoft.Deployment.WindowsInstaller.dll"`

It still fails, with the error:

`Error: C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\x86\sfxca.dll`

Went to have a look at that file, and the `C:\bin\WixSharp.1.9.3.0\Wix_bin\sdk\x86\` directory is empty. So is the x64 directory, so is the wixui directory.

**Comment by AvramM** [comment]
I downloaded a fresh copy of 1.9.4, installed it, and it's now building.

So somehow, the installation in my C:\bin folder had been partially missing. I'm not sure how that happened. But all seems fine now. Thanks for your help getting to the bottom of it!

**Comment by oleg-shilo** [comment]
Great. 
I am glad we sorted it out

**Comment by glitchwizard** [comment]
This has been happening to me, I've got the latest version of WixSharp, and I'm trying to build it with .NET 4.6.1 

Do I need to revert my .NET setup back to 4.0? 

This is the error I'm getting specifically:
```Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\<Source location>\bin\Debug\WixSharpSetup.exe"
exit" exited with code -532462766.	```

**Comment by oleg-shilo** [comment]
It's hard to give a pressie recommendation but situation can be described like this. 

MakeSfxCA.exe does not like the assembly you are supplying (WixSharpSetup.exe). You can only try to downgrade .NET version of your assembly or to try to see of the latest WiX can support your assembly.

WixSharp in this case plays a role of a simple launcher for `MakeSfxCA.exe ... WixSharpSetup.exe ...`
