### ISSUE TITLE
Signtool could not be found on Win10

### ISSUE THREAD

**Issue by dguder** [oleg-shilo/wixsharp#58]
I set up a new machine with Win10 and VS2015. Up to now I it was not necessary to install Windows SDK 7.1A. Thus the signtool could not be found. I have SDK 8.0, 8.1 and 10 installed but all in their new location C:\Program Files (x86)\Windows Kits.

For `DigitalySign` the default `WellKnownLocations` maybe should be extended with one or more of following paths:

- C:\Program Files (x86)\Windows Kits\8.0\bin\x86
- C:\Program Files (x86)\Windows Kits\8.1\bin\x86
- C:\Program Files (x86)\Windows Kits\10\bin\x86
- C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86

(or the corresponding x64 folders)

Regards 
Dominik

**Comment by oleg-shilo** [comment]
Done. Thx.
The fix will be available with the next release. In a mean time you can always pass the desired location as an extra argument:
```C#
Tasks.DigitalySign(msi,
                   "wixsharp.pfx",
                   "http://timestamp.verisign.com/scripts/timstamp.dll",
                   "my_password", 
                   optionalArguments:null, 
                   wellKnownLocations: @"C:\Program Files (x86)\Windows Kits\8.0\bin\x86");
```
