### ISSUE TITLE
Wrong path to the AdminToolsFolder

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#580]
In `AsWixVarToPath` `AdminToolsFolder` is registered as follows:
```C#
case "AdminToolsFolder": return Environment.SpecialFolder.CommonApplicationData.ToPath().PathJoin(@"Start Menu\Programs\Administrative Tools");
```
What corresponds to:
```
C:\ProgramData\Start Menu\Programs\Administrative Tools
```
[KNOWNFOLDERID](https://docs.microsoft.com/en-us/windows/desktop/shell/knownfolderid)
![image](https://user-images.githubusercontent.com/14925308/51587948-e5a60c80-1efb-11e9-93bc-38704b76faec.png)
The correct is:
```C#
case "AdminToolsFolder": return Environment.SpecialFolder.StartMenu.ToPath().PathJoin(@"Programs\Administrative Tools");
```

**Comment by oleg-shilo** [comment]
Txs. Done. Will be available in the next release
