### ISSUE TITLE
Question: How to set Version of product 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#582]
Hallo Oleg, is it possible to set Version of installed product like sample 1.b2.300-v.2901 as string ? Thanks for answer anyway.

**Comment by oleg-shilo** [comment]
I know it is possible but tricky. Not sure what is exactly involved. You will need to dig into WiX documentation.

**Comment by takato1314** [comment]
Just to give a good conclusion after some investigation. It seems that fundamentally wix also enforces this same rule to only allow integers in the versioning for the SemVer compliance standard.

![image](https://user-images.githubusercontent.com/10910968/63412011-63e27700-c429-11e9-80a1-9c5e19649049.png)

So, the following conditions are not allowed:
- Any non-integer strings in the <Product Version="x.x.x.x"> tag.
- More than 4 version numbers (eg. x.x.x.x**.x**)
