### ISSUE TITLE
Question: Preserve Windows service configuration on upgrade/repair

### ISSUE THREAD

**Issue by vassilvk** [oleg-shilo/wixsharp#583]
Hello,

Is there any way to preserve the configuration of a Windows service on upgrades/repairs?

For example, if the installation delivers a service and sets it up to run with the credentials of `LocalSystem` account, and then the user modifies the service configuration to run as a domain account, running a repair or an upgrade to a newer version of the service rewires the service to run as `LocalSystem` account effectively overwriting the user configuration.

Essentially, I am trying to do what [this StackOverflow post](https://stackoverflow.com/questions/2228855/wix-major-upgrade-how-do-i-prevent-windows-service-reinstallation) is discussing, but I am failing to see how to do that with WixSharp.

Here's the bit where I am setting up the service installer:
```csharp
serviceHandle.ServiceInstaller = new ServiceInstaller
{
  Name = productName,
  StartOn = SvcEvent.Install_Wait,
  StopOn = SvcEvent.InstallUninstall_Wait,
  RemoveOn = null,
  DelayedAutoStart = false,
  ServiceSid = ServiceSid.none,
  Account = "LocalSystem",

  ErrorControl = SvcErrorControl.normal,
  Start = SvcStartType.auto,
  Type = SvcType.ownProcess,
  Vital = true,
  DisplayName = productName,
  ConfigureServiceTrigger = ConfigureServiceTrigger.Install
};
```

Note the part where I am setting `RemoveOn = null`.
This is my unsuccessful attempt to accomplish what they describe in that StackOverflow post.

Regardless of the value of `RemoveOn`, the installation overwrites the service account settings on repair.

I am using `WixSharp 1.9.4`, but I have tried with `1.6.1` with the same results.

**Comment by oleg-shilo** [comment]
You can inject the XML expression from that post with the XML-Injection:

_pseudo-code_
```C#
project.WixSourceGenerated += document =>
            {
                document.Root.Select("what ever")
                             .AddElement("DeleteServices", "NOT UPGRADINGPRODUCTCODE");
```

**Comment by vassilvk** [comment]
Thank you, @oleg-shilo!

**Comment by chrisbbe** [comment]
Did you make this actually work @vassilvk ? I'm trying now myself, with no success. Besides adding the <DeleteServices> element as described, did you have to adjust any of the WixSharp properties of `ServiceInstaller` to make it work?

**Comment by oleg-shilo** [comment]
Christion, I have only showed @vassilvk  to implement the workaround he suggested. But I actually do not know if the work around itself was successful.

I hope @vassilvk will answer.

You still fond some extra clue in the original work around post: https://stackoverflow.com/questions/2228855/wix-major-upgrade-how-do-i-prevent-windows-service-reinstallation

**Comment by chrisbbe** [comment]
Yeah, thanks. I found another solution working on the first attempt, more or less dirty: [https://stackoverflow.com/a/54779680/265767](https://stackoverflow.com/a/54779680/265767)
