### ISSUE TITLE
Question: Preventing build of Wix# project building the MSI

### ISSUE THREAD

**Issue by PerMalmberg** [oleg-shilo/wixsharp#584]
Perhaps this is obvious, but how do I prevent the MSI being built when the Wix# project is built?

The Wix# project is created from the templates provided in the Wix# template nuget. I expected there to be a post-build action that ran the resulting binary, but they are empty.

WixSharp 1.9.4
WicxSharp.bin 1.9.4
Wix Toolset 3.11.1

**Comment by oleg-shilo** [comment]
There is a post build action but it is implemented as MSBuild 'WixSharp.targets' not as a post build event.

If you prefer not to have this integration you should remove WixSharp NuGet package before your attempt to build the project:
- Create project from the appropriate VS template 
- Delete "WixSharp" package from the packages.config file
- Restore/Download the NuGet packages
You are ready to build now.

**Comment by PerMalmberg** [comment]
Ah, thank you.
