### ISSUE TITLE
Question: Warning about auto-generated IDs

### ISSUE THREAD

**Issue by PerMalmberg** [oleg-shilo/wixsharp#585]
What exactly does this mean and what have I done wrong to trigger the warning?

>   msi -> C:\code\Phoenix\installer\windows\bin\Debug\WixSharp Setup.exe
1>  Building MSI
1>  ----------------------------
1>EXEC : warning : Wix# compiler detected that some IDs has been auto-generated before the build started. This can lead to the WiX ID duplications. To prevent this from happening either:
1>     - Avoid evaluating the auto-generated IDs values before the call to Build*
1>     - Set the IDs (to be evaluated) explicitly
1>     - Prevent resetting auto-ID generator by setting WixEntity.DoNotResetIdGenerator to true

This is my code:

        public bool Build()
        {
            var res = true;

            try
            {
                var launcher = new File(source / "launcher.exe");

                var project = new Project(productName,
                                  new Dir(installPath,
                                      launcher,
                                      new File(source / "launcher.cfg")))
                {
                    Version = version,
                    GUID = platform == Platform.x86 ? productCode32 : productCode64,
                    UpgradeCode = platform == Platform.x86 ? upgradeCode32 : upgradeCode64,
                    Platform = platform
                };
                
                launcher.ServiceInstaller = new ServiceInstaller
                {
                    Name = "launcher",
                    StartOn = SvcEvent.Install_Wait,
                    StopOn = SvcEvent.InstallUninstall_Wait,
                    RemoveOn = SvcEvent.Uninstall_Wait,
                    ServiceSid = ServiceSid.none,
                    FirstFailureActionType = FailureActionType.restart,
                    SecondFailureActionType = FailureActionType.restart,
                    ThirdFailureActionType = FailureActionType.none,
                    Arguments = "-d -c \"" + (installPath / "launcher.cfg") + "\" -w \"" + installPath + "\"",
                    RestartServiceDelayInSeconds = 30,
                    ResetPeriodInDays = 3
                };

                project.SourceBaseDir = source;
                project.OutFileName = "launcher";
                //project.OutDir = "<output dir path>";

                project.BuildMsi();
            }
            catch(Exception ex)
            {
                System.Console.WriteLine(ex.Message);
                res = false;
            }

            return res;
        }

**Comment by oleg-shilo** [comment]
The major usability idea of WixSharp that user does not have to specify the Ids that can be generated automatically.They just need to be unique. That's all.

WixSharp compiler generates these IDs at runtime on accessing the id members as in this pseudo-code

```  
static internal int id = 1;
public Id
{
    get => id++;
}
```
Every time the id is retrieved it is also incremented. 

It's is obvious that if you use debugger (or any other way) to evaluate `id` it will also be incremented. While normally it will not create any problems I decided to communicate this message to the user. 

The message means "if you ever have any problems with IDs ensure you do not trigger their generation accidentally.". 
That's it.

Though in your case I thing the "accident" is happening inside of the WixSharp implementation. 
I have elevated this post to the 'Enhancement' and will investigate the issue. But for you it means "if it generated MSI successfully then you can just ignore the warning"

**Comment by PerMalmberg** [comment]
Thank you for the quick reply and explanation, @oleg-shilo . And, thanks for making Wix#, it's  great tool.
