### ISSUE TITLE
[Question] How to add bal:overridable for Variable with wix#

### ISSUE THREAD

**Issue by maratoss** [oleg-shilo/wixsharp#586]
Hi, i am using wix# 1.9.3
i run bundle.exe from command line
and want to pass variable to my Bundle.exe bundle like this
and seems Variable should have Overridable attribute:
`cmd> Bundle.exe SITECONFIGURATION=blabla`

i added variable for my bundle:
`new Variable("SITECONFIGURATION")
{
	AttributesDefinition = "bal:Overridable=yes"
},`

but get the compilation error:
` Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Cannot resolve custom attribute definition:bal:Overridable=yes
3>     at WixSharp.AutoElements.ExpandCustomAttributes(XDocument doc, WixProject project)
3>     at WixSharp.Compiler.BuildWxs(Bundle project)
3>     at WixSharp.Compiler.Build(Bundle project, String path)
3>     at WixSharp.Bootstrapper.Bundle.Build(String path)`

Could you help me with it?
Thanks!

**Comment by maratoss** [comment]
this works but anyway want to do it without that xml injection :)

code:
```
bundle.WixSourceGenerated += document =>
{
	var variable = document
		.Descendants()
		.FirstOrDefault(x => x.Name == "Variable" && x.HasAttribute("Name", "SITECONFIGURATION"));

	if (variable != null)
	{
		variable.Add(new XAttribute("{http://schemas.microsoft.com/wix/BalExtension}Overridable", "yes"));
		Console.WriteLine(variable);
	}
};
```

cmd:
`bundle.exe /i SITECONFIGURATION=ALALALALALALALALLAA -log log.txt `

logs:
`[4AF0:6C58][2019-02-02T19:59:00]i000: Setting string variable 'SITECONFIGURATION' to value 'ALALALALALALALALLAA'`

**Comment by oleg-shilo** [comment]
Scheduled for the next release. Txs

**Comment by oleg-shilo** [comment]
The next release will also have the fix for a minor bug in `AttributesDefinition` support that will enable the following syntax for the cases when the additional (unsupported) attributes require the use of XML namespaces:

```C#
bootstrapper.Variables = new[]
{
    new Variable("BundleVariable", "333")
    {
        AttributesDefinition = "{http://schemas.microsoft.com/wix/BalExtension}Overridable=yes"
    }
};
```
