### ISSUE TITLE
Question: How to add Current User

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#587]
Hallo Oleg, i have a question and hope you can help me with. 
Is it possibly to add current user to Installation ? Sample like SQL Server Installation, where you can search and add current user to Installation and Sql server create windows service as sql instance for choosed user oder users.
idea is, for later,  add user to sql server for login, during silent installation of sql server in BA in complete Installation.

**Comment by oleg-shilo** [comment]
This is the conceptual solution. 
You will need to use public property as a user name and this property will need to be resolved at runtime in the custom action.

**Comment by Torchok19081986** [comment]
Many thanks, Oleg. i think, i know how to resolve public property. 
Something like this :  session["USERNAMETOADD"] = "myvalue", session["MYPASS"] = "mypwdvalue" in CA, i am right ? 
Only one thing: for silent installation, sql server create .ini where are settings for installtion like username, password, name of instance, version etc. 
how do i read or parse this .ini from BA at runtime ? Maybe some example ?

**Comment by Xaddan** [comment]
look at parameter [/ADDCURRENTUSERASSQLADMIN](https://docs.microsoft.com/ru-ru/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017)

**Comment by oleg-shilo** [comment]
@Xaddan is right. If there is a dedicated solution then go with it. 

But if for whatever reason you prefer to set/use properties explicitly (your ini file use case) then you can read your ini file from the same CA where you are going to assign the MSI properties.

**Comment by Xaddan** [comment]
instead of ini, I would use the command line with the /ADDCURRENTUSERASSQLADMIN or /SQLSYSADMINACCOUNTS option
