### ISSUE TITLE
new version/upgrade remove files

### ISSUE THREAD

**Issue by mdissel** [oleg-shilo/wixsharp#59]
Is there a way to remove files when an existing installation is found?
Basically I want to execute the following actions if an existing installation is found:
- remove some obsolete files
- update some files
- add new files
- execute a custom action (only when  version X.X.Y is found)

It that possible? Thanks

**Comment by oleg-shilo** [comment]
First three items are covered by MSI MajorUpgrade approach. See the corresponding Wix# samples.

Forth one is controversial. An MSI setup is not truly started/executed until the previous version is removed thus your custom action will  be executed only when the old version is removed. Thus "when version X.X.Y is found" cannot happen. 

From my personal experience, you are most likely is trying to do from custom action some sort of configuration/initialization. If it is the case then you will be much better of by removing this functionality from MSI domain (custom action) and performing it from the application domain (config utility, product application startup etc.).
