### ISSUE TITLE
Code signing timestamping fails if old Windows SDK is installed

### ISSUE THREAD

**Issue by Mark-Dunning** [oleg-shilo/wixsharp#591]
Hi,

We've found that code signing with timestamping fails on a couple of machines that have an old Windows SDK installed. This seems to be because Wix# tries to use the SignTool from the old SDK which doesn't support timestamping. These machines do have a newer SDK installed as well but Wix# seems to prefer the SignTool from the old one.

Would it be possible to reverse the order of the locations searched so that Wix# prefers the newest SignTool installed rather than the oldest one?

i.e. change this:

    WellKnownLocations = wellKnownLocations ??
        @"C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin;" +
        @"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin;" +
        @"C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool;" +
        @"C:\Program Files (x86)\Windows Kits\8.0\bin\x86;" +
        @"C:\Program Files (x86)\Windows Kits\8.1\bin\x86;" +
        @"C:\Program Files (x86)\Windows Kits\10\bin\x86;" +
        @"C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86",

to this:

    WellKnownLocations = wellKnownLocations ??
        @"C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86;" +
        @"C:\Program Files (x86)\Windows Kits\10\bin\x86;" +
        @"C:\Program Files (x86)\Windows Kits\8.1\bin\x86;" +
        @"C:\Program Files (x86)\Windows Kits\8.0\bin\x86;" +
        @"C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool;" +
        @"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin;" +
        @"C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin";

Thanks.

**Comment by oleg-shilo** [comment]
Done, though it's not a proper solution. It will fail as soon as a new SDK is installed.

A more reliable solution for you will be to set `WellKnownLocations` to the location you want:

```C#
CommonTasks.ExternalTool.ExternalTool = @"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin";
```

**Comment by Mark-Dunning** [comment]
Thanks very much.

You're right that it won't be reliable but it is still convenient to have a few common locations built in to Wix#.

I'll look at trying to do something more reliable but it is a bit awkward in general as the install path for many of these SDKs is configurable (e.g. you might install to D:\). Maybe using an environment variable or a private version of signtool.exe would be better.

Thanks again.

**Comment by oleg-shilo** [comment]
Yep, I thought about envars but decided not to go this way as it is not obvious to the users and opted to API. I think it can be intuitive enough:

```C#
CommonTasks.ExternalTool.WellKnownLocations = 
    @"C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86;" +
    @"C:\Program Files (x86)\Windows Kits\10\bin\x86;" +
    @"C:\Program Files (x86)\Windows Kits\8.1\bin\x86;" +
    @"C:\Program Files (x86)\Windows Kits\8.0\bin\x86;" +
    @"C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool;" +
    @"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin;" +
    @"C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin";
```

**Comment by CADbloke** [comment]
I found the most recent `signtool.exe` in `C:\Program Files (x86)\Windows Kits\10\App Certification Kit`

**Comment by oleg-shilo** [comment]
Thank you. 
Incorporated.
