### ISSUE TITLE
Downgrade WixSharp

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#592]
Oleg, it looks like your commit 437fcdaae2d4bf33606031f5538ee10b902aeab5 rolled back all the changes from 1.9.4.0 to version 1.9.3.0

**Comment by oleg-shilo** [comment]
Yeah, I was using a different PC while being on holidays and it looks like I have made an unfortunate git mistake. 

Though [437fcda](https://github.com/oleg-shilo/wixsharp/commit/437fcdaae2d4bf33606031f5538ee10b902aeab5) is 1.9.4.0.

What are the key changes that you used it identify the problem?

**Comment by oleg-shilo** [comment]
Never mind. I see the problem now. Yes it was that two days ago commit.

**Comment by oleg-shilo** [comment]
Should be OK now with 55aedd997f44e3c05cbba2b4c3a949778162b5a7

**Comment by Xaddan** [comment]
Yes, now it seems that everything is in order.

**Comment by oleg-shilo** [comment]
Thank you, for promptly letting me know about the problem. It was relatively easy to fix - only two commits. But it could be a different story if it was detected in a month or so. 👍
