### ISSUE TITLE
Switch between Silent and UI

### ISSUE THREAD

**Issue by Naicos** [oleg-shilo/wixsharp#594]
We are using the NSIS Bootstrapper and want to build it that you could start it 
with clicking on it and there should be displayed the UI (Which we're trying to realize
through Chrome), but if started over command line it should be silent and take a config file
for the needed Values (like Database logins etc) so for example that we add the path to
the config file (NOT inside the MSI, should be next to the .exe) and it runs in silent mode.
how can we give the parameters from command line to the MSIs?
In normal bootstrapper there was MsiProperty but not in NSIS as far as we saw.

**Comment by geghamyan** [comment]
By default parameters passed through the command file to the exe file will be relayed to the MSI. 
So for example the following call 
`MyProduct.exe /qn PARAM1=VALUE1 PARAM2=VALUE2`
will be internally executed as:
`msiexec.exe /I "primary.msi" /qn PARAM1=VALUE1 PARAM2=VALUE2`

**Comment by oleg-shilo** [comment]
Thank you Tigran. I hoped you would step in :)

**Comment by shengxue** [comment]
@oleg-shilo   ```myProduct.exe /quiet``` passes ```quiet``` to ```primary.msi```.  However, it does not pass ```quiet``` to Prerequisite file?    are there any solution to pass ```quiet``` to Prerequisite file?

**Comment by oleg-shilo** [comment]
I am not sure how but quite possible there is something about it in the NSIS documentation.

**Comment by shengxue** [comment]
I tried ```NsisBootstrapper``` to install .net 6.   If I specify ```Arguments = "/install /passive /norestart /quiet"``` in Prerequisite,  .net 6 is always installed silently even when I double clicked 'install.exe';  while if I don't specify ```Arguments``` in Prerequisite, .net installation dialog always shows even when I run ```installer.exe /quiet``` in command line.

``` csharp
        public static void BundleDotNet6(string msiFile, Version versionToInstall)
        {
            var bootstrapper = new NsisBootstrapper
            {
                Prerequisite =
                {
                    FileName = "prerequisites\windowsdesktop-runtime-6.0.10-win-x64.exe",
                    PostVerify = false,
                    RegKeyValue = @"HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{3EC7701F-54F2-491D-AFD1-0395F465BC5A}:DisplayName",
                    CreateNoWindow = false,
                    Arguments = "/install /passive /norestart /quiet"
                },

                Primary = { FileName = msiFile },

                OutputFile = "installer.exe",
            };

            bootstrapper.Build();
        }
```

**Comment by shengxue** [comment]
@oleg-shilo 
> I am not sure how but quite possible there is something about it in the NSIS documentation.
**If it was Burn then you can definitely channel the switch at runtime through the custom BA.**

do we have such an example in https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples ?

**Comment by geghamyan** [comment]
Take a look on this example:
[    // Arguments passing examples:](https://github.com/oleg-shilo/wixsharp/blob/5f8508a27c670bab10432ec8bb01141b5f1d0557/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L159)

You can achieve this by configuring it through OptionName parameter:
`OptionName = "/prerequisite:",`

**Comment by geghamyan** [comment]
It's going to be `my_product.exe /prerequisite:"/quiet"`
https://github.com/oleg-shilo/wixsharp/blob/5f8508a27c670bab10432ec8bb01141b5f1d0557/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NsisBootstrapper/setup.cs#L160

**Comment by shengxue** [comment]
@geghamyan   the command line ```my_product.exe /prerequisite:"/quiet"``` installs prerequisite silently. However, the internal smi does not install at all, and shows dialog:


![image](https://user-images.githubusercontent.com/6092790/200934000-3a2acb25-1438-4869-b05f-fc89a8d29d7b.png)

**Comment by oleg-shilo** [comment]
That dialog is displayed when msiexec.exe did not receive the correct input parameters.
So it is either in this case user params are misformatted (a bit more probably) or not passed through (). But the dialog is clear indication that msiexec is not happy

**Comment by shengxue** [comment]
@geghamyan  @oleg-shilo  sorry that I overlooked this info in @geghamyan is comment.   With ```/primary:"/qn"```, internal msi works also well!

![image](https://user-images.githubusercontent.com/6092790/201032946-d3817ed9-9120-4a72-bb05-c9ac8ccd1794.png)

**Comment by oleg-shilo** [comment]
Thank you Tigran.
