### ISSUE TITLE
How to get Install folder from bootstrapper

### ISSUE THREAD

**Issue by rolikoff** [oleg-shilo/wixsharp#595]
I have a bootstrapper that has 3 chain items

```C#
var bootstrapper =
    new Bundle(APP_NAME,
        NetFramework472Package("NetFx472Web"),
        new MsiPackage(BuildMSI(Platform.x64, "myapp64"))
        {
            InstallCondition = "VersionNT64",
            Id = "MainPackage64",
        },
        new MsiPackage(BuildMSI(Platform.x86, "myapp"))
        {
            InstallCondition = "NOT VersionNT64",
            Id = "MainPackage",
        });

bootstrapper.LightOptions = "-dWixMbaPrereqPackageId=NetFx472Web -dWixMbaPrereqLicenseUrl=http://referencesource.microsoft.com/license.html";

bootstrapper.Application = new ManagedBootstrapperApplication("%this%", "BootstrapperCore.config");

bootstrapper.SuppressWixMbaPrereqVars = true;

bootstrapper.Build($"myapp_{version.Major}.{version.Minor}.{version.Build}.{version.Revision}.exe");
```

where `BuildMSI()` builds an MSI file for x86 or x64 platform, `NetFramework472Package()` returns `ExePackage` - i use it for .net framework prerequisites. 

As you can see, it's a managed BA with WPF assembly bundled. So my problem right now is that I want to start the app once I get `OnApplyComplete` event and I don't know how to determine the install folder to where one of the MSI's was installed. Is there a way to read INSTALLDIR from the MSI packages somehow?

**Comment by Xaddan** [comment]
Я так понимаю MSI у тебя уже стоит и тебе надо получить его путь установки?
Если нет то посмотри соседнюю тему, я там расписал #596

**Comment by rolikoff** [comment]
Thank you, #596 was helpful.
