### ISSUE TITLE
Question: WixBA UI Sample

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#596]
Hallo Oleg, i have a question. 
i looked for WixBootstrapper_UI Sample. after i compiled it again, i wanted to test it for userinput for Installfolder. After i set it to another installdir , i thought i would be install app in it, but strangely enough its not. App is alway install it in %ProgramFiles%\My Company\My Product as destationation installdir.
In installdir exists and messagebox show me correctly folder.  Do i missing something ?

Question Nr. 2 : how do i use sample with Userinput for installdir in WPF installer etc. ?

**Comment by oleg-shilo** [comment]
This is how you pass MSI properties to your msi from the bundle:
```C#
var bootstrapper =
    new Bundle("My Product",
                new PackageGroupRef("NetFx40Web"),
                new MsiPackage(productMsi)
                {
                    Id = "MyProductPackageId",
                    DisplayInternalUI = true,
                    MsiProperties = "INSTALLDIR=[ACTUAL_INSTALLDIR]"
                });
bootstrapper.Variables = new[] { new Variable("ACTUAL_INSTALLDIR", "<none>"), };
```

**Comment by Torchok19081986** [comment]
Thanks Oleg. Just tested my fullinstaller with bundle. Unfortunately bundle doesnt install my app in choosed path. in sample exists variable "USERINPUT=Userinput" after i do some changes like in your sample i tested it again. no improvements. Installdir ist always %ProgramFiles%\My Company\My Product.
i going to try give some messagebox before and after installtion. I have to do  some research with it.

**Comment by Torchok19081986** [comment]
some feedback on newst test. Messagebox before shows %ProgramFiles%\My Company\My Product as Installdir. After change it to another path, values was not change. i think problem is in line 

  public void InstallExecute() 
    {
        IsBusy = true;

        Bootstrapper.Engine.StringVariables["UserInput"] = UserInput;
        Bootstrapper.Engine.Plan(LaunchAction.Install);
    }
i dont change it in code. This code comes from sample. Any idea ?

**Comment by Xaddan** [comment]
I want to offer my use case.
In `Bootstrapper`, create a variable, for example, `INSTALL_LOCATION`:
```C#
new Variable ("INSTALL_LOCATION", "[ProgramFiles6432Folder]\My Company\My Product")
```
In the `Model`, create a property, for example, `InstallLocation`:
```C#
public string InstallLocation
{
    get
    {
        var path = VariableStore.GetString("INSTALL_LOCATION");
        return path.IsNullOrWhiteSpace() ? String.Empty : VariableStore.FormatString(path);
    }
    set
    {
       VariableStore.SetString("INSTALL_LOCATION", value);
    }
}
```
Pass the variable to the msi package:
```C#
MsiProperties = "INSTALLDIR=[INSTALL_LOCATION]"
```

Now you can use the property to display or change the installation path.
for example
```C#
MessageBox.Show(InstallLocation);
```
Or in `ViewModel`:
```C#
public string InstallLocation
{
    get
    {
        Return Model.InstallLocation;
    }
    set
    {
        if (Model.InstallLocation! = value)
        {
            Model.InstallLocation = value;
            OnPropertyChanged (GetPropertyName (() => InstallLocation));
        }
    }
}
```

**Comment by Torchok19081986** [comment]
Many thanks Xadan. I going to try it. unfoftunaly, my notebook with samples was ram broken. i going to try it some later.
