### ISSUE TITLE
Files creating empty folders on Destination

### ISSUE THREAD

**Issue by WayneHiller** [oleg-shilo/wixsharp#599]
Files( feature, "..\\SomeFolder\\*.ext") is creating empty folders on the Destination that match all folders under ../SomeFolder even though no files where copied (included) in those folders.

**Comment by oleg-shilo** [comment]
Thank you. Will be addressed in the next release.

**Comment by oleg-shilo** [comment]
It turns out that the feature is there except it is not so obvious how to use:

```C#
project.GUID = new Guid("6f330b47-2577-43ad-9095-1561ba25889b");
project.ResolveWildCards(ignoreEmptyDirectories: true);

project.BuildMsi();
```

Though I have update the implementation and with the next release the users will be able to do it in a more intuitive way:
```C#
Compiler.AutoGeneration.IgnoreWildCardEmptyDirectories = false;
. . .
project.GUID = new Guid("6f330b47-2577-43ad-9095-1561ba25889b");

project.BuildMsi();
```

**Comment by Xaddan** [comment]
What if I collect files from two folders, from one I need to collect empty subfolders, and from the other not?

**Comment by oleg-shilo** [comment]
Then you will need to implement your custom wild card equivalent.

Do your magic by collecting the Dirs and Files and then simply add them to the project. The built-in support for covers straight forward use-case. For anything exotic users will need to implement their own algorithms.

**Comment by Xaddan** [comment]
Maybe it is better to add a parameter to the `Files`?

**Comment by oleg-shilo** [comment]
Not really. WixSharp compiler resolves ALL wild card definitions in a single hit. Thus there is no intended support for individual Files/Dirs resolving. If you want to have a mix "_collect empty subfolders, and from the other not_" then it is exactly that edge exotic case that I mentioned in my prev post and it will need to be handled by the user defined algorithm.

**Comment by WayneHiller** [comment]
It seems like having "unknown" empty folders would be pretty rare.  In my case when scanning for files there are a lot of cases like ASP.NET MVC where you need to pull cshtml, js, css from Areas etc so you don't want to copy all the folders, just the folders that actually have files that need to be installed.

**Comment by WayneHiller** [comment]
I added project.ResolveWildCards( ignoreEmptyDirectories: true );

I am still getting empty folders added to the wxs.

`
  <Directory Id="WEBSITEDIR.Areas.Admin.Models" Name="Models">
  <Component Id="Component.WEBSITEDIR.Areas.Admin.Models.EmptyDirectory" Guid="6fe30b47-2577-43ad-9095-1861aee7cbdf" KeyPath="yes" Win64="yes">
  <CreateFolder />
  <RemoveFolder Id="WEBSITEDIR.Areas.Admin.Models" On="uninstall" />
</Component>
</Directory>
`

The source folders are not empty but they do not include any files specified in the wildcard.

**Comment by oleg-shilo** [comment]
I have rechecked and indeed there is a flaw in the "remove empty dirs" algorithm. Currently it removes only the last leaf node in the tree.  

The error has been corrected and the next release will have it fixed. 

Though I think we are over complicating this whole issue. For example one wants to have a custom empty dir handling (e.g. you want to address the flaw in the current implementation). Then it is quite easy to accomplish:

```C#
project.GUID = new Guid("6f330b47-2577-43ad-9095-1561ba25889b");
project.ResolveWildCards();

IEnumerable<Dir> getEmptyDirs() => AllDirs.Where(d => !d.Files.Any() && !d.Dirs.Any());

IEnumerable<Dir> emptyDirs;

while ((emptyDirs = getEmptyDirs()).Any())
{
    emptyDirs.ForEach(emptyDir => AllDirs.ForEach(d =>
                                    {
                                        if (d.Dirs.Contains(emptyDir))
                                            d.Dirs = d.Dirs.Where(x => x != emptyDir).ToArray();
                                    }));
}

project.BuildMsi();
```

After all it is exactly what `ResolveWildCards(ignoreEmptyDirectories: true)` now does.

**Comment by WayneHiller** [comment]
I am struggling to understand why anyone would want empty folders created on the destination for folders that do not contain any files from the wildcard search. It seems like the default should be to exclude them.

When I do Files(".\\projectFolder\\*.js) for example I would expect to only include folders that contain .js files.

**Comment by WayneHiller** [comment]
This code seems incomplete. It only removes top level empty folders.

```
IEnumerable<Dir> getEmptyDirs() => AllDirs.Where(d => !d.Files.Any() && !d.Dirs.Any());

IEnumerable<Dir> emptyDirs;

while ((emptyDirs = getEmptyDirs()).Any())
{
    emptyDirs.ForEach(emptyDir => AllDirs.ForEach(d =>
                                    {
                                        if (d.Dirs.Contains(emptyDir))
                                            d.Dirs = d.Dirs.Where(x => x != emptyDir).ToArray();
                                    }));
}
```
Maybe it should be like this helper I created, so that it starts at leaf folders first.

```
public static void RemoveEmptyFolders( Dir dir ) {
            var dirs = new List<Dir>();

            foreach( var d in dir.Dirs ) {
                if( d.Dirs.Any() ) {
                    RemoveEmptyFolders( d );
                }

                if( d.Dirs.Any() || d.Files.Any() ) {
                    dirs.Add( d );
                }
            }

            dir.Dirs = dirs.ToArray();
        }
```

**Comment by oleg-shilo** [comment]
> It only removes top level empty folders

Not exactly. In the code snippet I provided a single loop removes top level empty folders. An the next loop does it again until all levels are processed. 

I just retested it again. It removes all level dirs. What was your test outcome?

> I am struggling to understand why anyone would want empty folders created on the destination for folders that do not contain any files from the wildcard search. 

I actually agree with you. Empty folders is a deployment nonsense. However support for empty folders was specifically requested by users who wanted to create empty folders for application run time activities (e.g. loging).

**Comment by WayneHiller** [comment]
> I just retested it again. It removes all level dirs. What was your test outcome?

Oh yes you are correct, it works, What I was looking for was a way to remove empty folders from a specific folder tree.

Maybe we could add a method to the Common.Tasks to do that.

>I actually agree with you. Empty folders is a deployment nonsense. However support for empty folders was specifically requested by users who wanted to create empty folders for application run time activities (e.g. logging).

I do add a few needed empty folders for exporting etc but those are created with Dir, Does not make sense to me to include any folders that do not contain any files from the wildcard search.

App
  F1
  F2
  F3
   C1
    CC1

If I use Files("App", "*.JS) and only F1 has any JS files all the other folders will be included and created on the destination. That seems very strange.

Maybe we could update the Comments on "Files" to explain that this will happen and how to remove empty folders if they are not wanted.

**Comment by oleg-shilo** [comment]
Agree. Extra comments have been added to the `Files` all constructors.
![image](https://user-images.githubusercontent.com/16729806/54616719-36795200-4ab4-11e9-95bd-2a1526c0b500.png)

> I do add a few needed empty folders...

I do question this approach. If your app is exporting something then it should be responsible for preparing the export destination. It's not a deployment but a runtime task. This is in fact a quite common deployment anti-pattern that I see all the time. :o)

Imagine if you want to add a new functionality to allow user to choose an alternative export destination. If you create folders during exporting then you are fine. But if you do during deployment then your user will need.... to reinstall the app in order to and choose a different export dir. Doesn't make much sense, does it?

Anyway I encourage you to give your deployment strategy another though.

**Comment by WayneHiller** [comment]
>I do question this approach. If your app is exporting something then it should be responsible for preparing the export destination. It's not a deployment but a runtime task. This is in fact a quite common deployment anti-pattern that I see all the time. :o)

>Imagine if you want to add a new functionality to allow user to choose an alternative export destination. If you create folders during exporting then you are fine. But if you do during deployment then your user will need.... to reinstall the app in order to and choose a different export dir. Doesn't make much sense, does it?

>Anyway I encourage you to give your deployment strategy another though.

Agreed, really the "app" should be responsible for itself. If it needs a folder it should just create it if it does not exist.
