### ISSUE TITLE
.NET 4.0 support

### ISSUE THREAD

**Issue by xplicit** [oleg-shilo/wixsharp#60]
Is it possible to make a build of Wix# project with .NET 4.0? When I target platform to .NET 4.0, I've got an warning and exception:

```
Warning: assembly 'WixSharpTest' is compiled for v4.0.30319 runtime, which may not be compatible with the CLR version hosted by ComputerName. The incompatibility is particularly possible for the EmbeddedUI scenarios. T
he safest way to solve the problem is to compile the assembly for v3.5 Target Framework.

Необработанное исключение: System.ApplicationException: Cannot package ManagedCA assembly(%this%)
   в WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String configFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
   в WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
   в WixSharp.Compiler.GenerateWixProj(Project project)
   в WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   в WixSharp.Compiler.BuildWxs(Project project, OutputType type)
   в WixSharp.Compiler.BuildCmd(Project project, String path, OutputType type)
   в WixSharp.Compiler.BuildMsiCmd(Project project, String path)
   в WixSharp.Compiler.BuildMsiCmd(Project project)
```

**Comment by oleg-shilo** [comment]
Yes it is possible. Though Ideally it should be avoided as you want to target the lowest version of .NET as possible. Though if it is what you want then you can use target as .NET 4.0.

However.... the latest Wix# fully supports .NET 4 and that warning has been removed. Meaning that you are using the old version of Wix# and probably the old version of WiX. Thus your WiX assembly packager `MakeSfxCA.exe` may not like .NET 4. 

I suggest you update both frameworks and see if it solves the problem.

**Comment by oleg-shilo** [comment]
And you can always troubleshoot your `MakeSfxCA.exe`:
```C#
class Script
{
    static public void Main(string[] args)
    {
        var project = new Project()
        {
            UI = WUI.WixUI_ProgressOnly,
            Name = "CustomActionTest",

            Actions = new[]
            {
                new ManagedAction(CustomActions.MyAction, "%this%")
            }
        };

        var asm = typeof(Script).Assembly.Location;
        Compiler.ClientAssembly = asm;
        Compiler.BuildPackageAsmCmd(asm,
                                    asm.PathChangeFileName("my_dll_CA.dll"),
                                    new string[0],
                                    asm.PathGetDirName(),
                                    null);
        //project.BuildMsi();
```
The code above will generate batch file `Build_CA_DLL.cmd` that you can use to investigate `MakeSfxCA.exe` problems without Wix# being involved at all.

**Comment by xplicit** [comment]
I have these packages added in my packages.config. They are latest version, which I can found on nuget. Should I recompile WixSharp from sources to avoid this warning?

```xml
  <package id="WixSharp" version="1.4.3.0" targetFramework="net452" />
  <package id="WixSharp.bin" version="1.4.3.0" targetFramework="net452" />
  <package id="WixSharp.wix.bin" version="3.10.3" targetFramework="net452" />
```

**Comment by oleg-shilo** [comment]
No you shouldn't need to recompile. Let me check again. May be my conclusion about this validation/warning being removed was wrong.

**Comment by xplicit** [comment]
I've got little more descriptive error:

```
Wix binaries cannot be found. Expected location is C:\WINDOWS\system32\Wix_bin\bin

Необработанное исключение: System.ApplicationException: Wix compiler/linker cannot be found
   в WixSharp.Compiler.BuildCmd(Project project, String path, OutputType type)
   в WixSharp.Compiler.BuildMsiCmd(Project project, String path)
   в WixSharp.Compiler.BuildMsiCmd(Project project)
   в WixSharp.Project.BuildMsiCmd(String path)
```

this is dir of `C:\WINDOWS\System32\Wix_bin\bin`. Both `light.exe` and `candle.exe` are located here


```
 Содержимое папки C:\WINDOWS\System32\Wix_bin\bin

27.04.2017  10:16    <DIR>          .
27.04.2017  10:16    <DIR>          ..
08.06.2016  00:10            28 672 candle.exe
05.05.2016  01:36               528 candle.exe.config
27.02.2016  06:56           694 784 darice.cub
08.06.2016  00:10            28 672 dark.exe
05.05.2016  01:36               826 dark.exe.config
08.06.2016  00:11           293 705 difxapp_x64.wixlib
08.06.2016  00:11           203 950 difxapp_x86.wixlib
08.06.2016  00:10            28 672 heat.exe
05.05.2016  01:36               656 heat.exe.config
25.01.2017  09:11            98 571 IncludeFile.ico
08.06.2016  00:10            24 576 insignia.exe
05.05.2016  01:36               448 insignia.exe.config
08.06.2016  00:10            32 768 light.exe
05.05.2016  01:36               528 light.exe.config
08.06.2016  00:10            28 672 lit.exe
05.05.2016  01:36               528 lit.exe.config
25.01.2017  09:11           105 449 LocalizationFile.ico
08.06.2016  00:11            32 768 lux.exe
05.05.2016  01:36               629 lux.exe.config
```

**Comment by oleg-shilo** [comment]
OK, I have created a fresh project and got WixSharp package from NuGet. It compiles for .NET 4 without any warning. Thus somehow your project is using old binaries. You may want to check the actual binaries, not just `packages.config`.

The only place where this warning is triggered (`ProjectValidator.ValidateAssemblyCompatibility`) is completely commented out:

![image](https://cloud.githubusercontent.com/assets/16729806/25517276/faa7e1da-2c31-11e7-998b-0ec225208947.png)

`C:\WINDOWS\System32` ??!!
Why on Earth is it there? :)

I am truly uncomfortably assisting anyone with tweaking his/her system directories.  

Please remove them. Install WiX or get it from NuGet:
```
Install-Package WixSharp.wix.bin
``` 
All your problems may be caused by that inappropriate location.

**Comment by xplicit** [comment]
I have no idea why is WixSharp looking in `C:\Windows\System32` when I have `WixSharp.Wix.bin` package installed and when Wix toolset 3.10.3 is installed in `C:\Program Files (x86)\WiX Toolset v3.10\` . I see that I have these environment variables set: 

```
WIX=C:\Program Files (x86)\WiX Toolset v3.10\
WIXSHARP_DIR=C:\WINDOWS\system32
WIXSHARP_WIXDIR=C:\WINDOWS\system32\Wix_bin\bin
```

I examined these two vars pointed to `System32` and this directory contains v3.9 of WixToolset. OK, I changed WIXSHARP_WIXDIR to `C:\Program Files (x86)\WiX Toolset v3.10\` and exception that libraries cannot be found has gone. But why WixSharp is looking for old installation when new is available? Or why it does not get wix toolset libraries from nuget package.

Warning is still here, but I hope I can ignore it.

**Comment by xplicit** [comment]
If this warning can be safely ignored I'll close the issue.

**Comment by oleg-shilo** [comment]
Sergey, my slight shock was not caused by Wix# expecting WiX binaries to be in the system folders but by the fact that they were actually there. :)

Anyway, I think we are on the right track to fix it. 

> But why WixSharp is looking for old installation when new is available?

Because this is how probing algorithm for WiX tools works:
![image](https://cloud.githubusercontent.com/assets/16729806/25519746/7244750a-2c3c-11e7-91be-11d0e30bf191.png)

BTW, you can use `WiXLocation` to  overwrite the probing directory with any of the available WiX locations:
```C#
Compiler.WixLocation = @"..\packages\WixSharp.wix.bin.3.10.1\tools\bin";

var project = new ManagedProject("DesignForge Throttle",
                  new Dir(@"%ProgramFiles%\DesignForge\Throttle",
...
```

> Or why it does not get wix toolset libraries from nuget package.

WiX toolset is a large library and having it unconditionally downloaded from NuGet would not be suitable for many users that's why you need to add `WixSharp.wix.bin` explicitly if it's preferred to use WiX tools from the Wix# tested package.

> I have no idea why is WixSharp looking in C:\Windows\System32 when I have WixSharp.Wix.bin  

I actually have an idea :)
Most likely you had some old installation of Wix# and you installed/activated it by running `install.cmd`. The tricky part is that it needs to be elevated. However if one doesn't use command prompt and executes `install.cmd` from the correct directory the OS by default sets current directory of the elevated process to the system dir.

I suggest that you completely remove all these environment variables and let Wix# runtime to locate WiX in `Program Files` or set it explicitly from code.

> Warning is still here, but I hope I can ignore it.

That's really worrying. You can ignore it, it's just a warning but I am afraid that you may still be using the old Wix# compilers. 
Can you please check the actual dll in your bin\<Debug|Release> folder. As I mentioned the fresh clean test 30 mins ago emitted no warning.

**Comment by oleg-shilo** [comment]
Just a bit more on the warning. 

The versions that trigger the warning indeed incompatible with .NET 4. You might be in luck and at runtime your routine would survive. Though without any warranty. 

The later versions (at latest the latest one) are fully compatible with .NET 4 that's why warning has been removed. The only appropriate cause of actions is to verify  the actual dll in your bin<Debug|Release> folder.

But if you want to take some risk then you indeed can just ignore the warning. The choice is yours :)

**Comment by xplicit** [comment]
I close the issue, because this was configuration issue of the project I tried to compile. Removing environment variables which pointed to wix toolset 3.9 location allowed me to compile and build installer. The installer is executed and I don't see the issues which could be caused by .NET2.0 -> .NET4.0 retargeting.

**Comment by mbinic** [comment]
Hi @oleg-shilo ,

My project is also on the latest WiX and WixSharp versions, built on a freshly installed Win10 laptop with VS2015, and though there's no exception, I'm still getting the warning.

There are no wix-related environment variables and WiX was never installed, only v3.11 binaries unzipped to solution dir. `MakeSfxCA.exe` is version 3.11.0.1701.

Anything I'm missing?

---

Details:

**packages.config:**
```
<package id="WixSharp" version="1.4.7.2" targetFramework="net462" />
<package id="WixSharp.bin" version="1.4.7.2" targetFramework="net462" />
```

**app.config:**
```
<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
```

**Build output:**
```
1>  Test.Project1.Setup -> C:\Projects\test1\bin\Debug\Test.Project1.Setup.exe
1>  Building MSI using WiX tools in C:\Projects\test1\build\tools\WiX\bin
1>EXEC : warning : assembly 'Test.Project1.Setup' is compiled for v4.0.30319 runtime, which may not be compatible with the CLR version hosted by MSI. The incompatibility is particularly possible for the EmbeddedUI scenarios. The safest way to solve the problem is to compile the assembly for v3.5 Target Framework.
1>  Searching for custom action entry points in Test.Project1.Setup.exe
1>      Loaded dependent assembly: C:\Projects\test1\bin\Debug\WixSharp.UI.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>      Loaded dependent assembly: C:\Projects\test1\bin\Debug\WixSharp.dll
1>      Loaded dependent assembly: C:\Projects\test1\build\tools\WiX\sdk\Microsoft.Deployment.WindowsInstaller.dll
1>      ReadConfig=Test.Project1.Setup!Test.Project1.Setup.CustomActions.ReadConfig
1>      CreateConfig=Test.Project1.Setup!Test.Project1.Setup.CustomActions.CreateConfig
1>  Searching for an embedded UI class in Test.Project1.Setup.exe
1>  Modifying SfxCA.dll stub
1>  Copying file version info from C:\Projects\test1\bin\Debug\Test.Project1.Setup.exe to C:\Projects\test1\bin\Debug\%this%.CA.dll
1>  Packaging files
1>      Test.Project1.Setup.exe
1>      CustomAction.config
1>      Test.Project1.Setup.pdb
1>      WixSharp.dll
1>      WixSharp.UI.dll
1>      Microsoft.Deployment.WindowsInstaller.dll
1>  MakeSfxCA finished: C:\Projects\test1\bin\Debug\%this%.CA.dll
1>  Searching for custom action entry points in WixSharp.dll
1>      Loaded dependent assembly: C:\Projects\test1\build\tools\WiX\sdk\Microsoft.Deployment.WindowsInstaller.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll
1>      WixSharp_InitRuntime_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_InitRuntime_Action
1>      WixSharp_Load_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_Load_Action
1>      WixSharp_BeforeInstall_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_BeforeInstall_Action
1>      WixSharp_AfterInstall_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
1>      CancelRequestHandler=WixSharp!WixSharp.ManagedProjectActions.CancelRequestHandler
1>  Searching for an embedded UI class in WixSharp.dll
1>  Modifying SfxCA.dll stub
1>  Copying file version info from C:\Projects\test1\bin\Debug\WixSharp.dll to C:\Projects\test1\bin\Debug\WixSharp.CA.dll
1>  Packaging files
1>      WixSharp.dll
1>      CustomAction.config
1>      Test.Project1.Setup.exe
1>      WixSharp.UI.dll
1>      Microsoft.Deployment.WindowsInstaller.dll
1>  MakeSfxCA finished: C:\Projects\test1\bin\Debug\WixSharp.CA.dll
1>  Searching for custom action entry points in WixSharp.UI.dll
1>      Loaded dependent assembly: C:\Projects\test1\bin\Debug\WixSharp.dll
1>      Loaded dependent assembly: C:\Projects\test1\bin\Debug\Microsoft.Deployment.WindowsInstaller.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>      Loaded dependent assembly: C:\Projects\test1\bin\Debug\BootstrapperCore.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll
1>  Searching for an embedded UI class in WixSharp.UI.dll
1>  Modifying SfxCA.dll stub
1>  Copying file version info from C:\Projects\test1\bin\Debug\WixSharp.UI.dll to C:\Projects\test1\bin\Debug\WixSharp.UI.CA.dll
1>  Packaging files
1>      WixSharp.UI.dll
1>      EmbeddedUI.config
1>      Microsoft.Deployment.WindowsInstaller.dll
1>      Test.Project1.Setup.exe
1>      WixSharp.dll
1>      BootstrapperCore.dll
1>  MakeSfxCA finished: C:\Projects\test1\bin\Debug\WixSharp.UI.CA.dll
1>  Wix# support for EmptyDirectories is automatically enabled
1>  
1>  ----------------------------------------------------------
1>  
1>  Wix project file has been built: C:\Projects\test1\bin\Debug\Test Project1-201.0.0.0-win64.wxs
1>  
1>  Windows Installer XML Toolset Compiler version 3.11.0.1701
1>  Copyright (c) .NET Foundation and contributors. All rights reserved.
1>  
1>  Test Project1-201.0.0.0-win64.wxs
1>  Windows Installer XML Toolset Linker version 3.11.0.1701
1>  Copyright (c) .NET Foundation and contributors. All rights reserved.
1>  
1>  
1>  ----------------------------------------------------------
1>  
1>  MSI file has been built: C:\Projects\test1\bin\Debug\Test Project1-201.0.0.0-win64.msi
1>  
1>   ProductName: Test Project1 1.0.0.0
1>   Version    : 1.0.0.0
1>   ProductId  : {724c0005-a164-4416-b565-f2070afe7fc6}
1>   UpgradeCode: {102e71ec-cbcd-46f8-b29b-09b8631ec488}
1>  
1>   Auto-generated InstallDir ID:
1>     INSTALLDIR=%ProgramFiles64%\Test Project1 1.0.0.0
```

**Comment by oleg-shilo** [comment]
Not sure how it is possible. The only place where this warning is produced is already commented out in the code for quite some time. The only possible explanation is that the nuget brought you the older version of WixSharp.dll. Can you please collect it from the Debug/Release folder and share it hare. I want to verify that the binary is the correct one. 

Txs

**Comment by miloraddomanovic** [comment]
As @mbinic listed in his post we are extracted WiX version 3.11.0.1701. Packages folder cleaned, only present folders WixSharp.1.4.7.2, WixSharp.bin.1.4.7.2 and double checked that WixSharp.dll version is 1.4.7.2 in packages & bin/debug folders but still same warning.

**Comment by oleg-shilo** [comment]
Abut the warning... We have entered the recursion mode :)

I am saying that the code in question is disabled in the v1.4.7.2 and you guys are sayng that it is still happening. We cannot be all right. Either I am wrong and the nuget package got the wrong binary or in your environment the wrong package is exercised at compile time. 

I can only investigate it if I can reproduce the problem or have some data to investigate. Why don't some one who experience the problem share with me either complete test case that exhibits the problem (e.g. zipped project folder) or at least the content of the Debug/Release folder, as I asked in my previous email?

**Comment by miloraddomanovic** [comment]
@oleg-shilo sorry for wasting your time - I found in our project check for assembly runtime version which produced a warning. 

Thank you again for your help.

**Comment by oleg-shilo** [comment]
Cool. It all makes sense now. :)
