### ISSUE TITLE
Question: how to add installdir to PATH

### ISSUE THREAD

**Issue by aloopkin** [oleg-shilo/wixsharp#601]
Hello,
I'd like to add permanently the product INSTALLDIR to the PATH, so that after installing the product's MSI, echo %PATH% contains the installation directory of the product.
I tried adding `new EnvironmentVariable("PATH", "[INSTALLDIR]")` to the new Project(...) in the Script.cs, but this doesn't seem to work.
How to proceed ?

**Comment by Xaddan** [comment]
Try this
```C#
new EnvironmentVariable("Path", @"[INSTALLDIR]")
{
    Id = "Path_INSTALLDIR",
    Action = EnvVarAction.set,
    Part = EnvVarPart.last,
    Permanent = false,
    System = true,
}
```

**Comment by aloopkin** [comment]
Thanks a lot, this solved the issue
