### ISSUE TITLE
Question: windows service - InstallUtil arguments

### ISSUE THREAD

**Issue by talapoin** [oleg-shilo/wixsharp#602]
Hello, 
I am trying to install windows service using wixsharp. Does anybody know how to pass arguments to installutil.exe using wixsharp SErviceInstaller class?

I need to be able to run something like this installutil.exe /arg1=value1 service.exe

```
            File service;
            var featureDir = new Dir(feature, @"some service",
                service = new File("service.exe"),
                new DirFiles($@"bin\{configuration}\*.dll"),
                new DirFiles($@"bin\{configuration}\*.config"),
                new DirFiles($@"bin\{configuration}\*.xml"),
                new DirFiles($@"bin\{configuration}\*.txt"));
            
            service.ServiceInstaller = new ServiceInstaller
            {
                Name = "service",
                StartOn = null,
                RemoveOn = SvcEvent.Uninstall_Wait,
                Start = SvcStartType.auto,
                DelayedAutoStart = true
            };
```
this code will install windows service but will not pass any argument to installutil.exe

**Comment by Xaddan** [comment]
```C#
service.ServiceInstaller = new ServiceInstaller
{
    Name = "service",
    StartOn = null,
    RemoveOn = SvcEvent.Uninstall_Wait,
    Start = SvcStartType.auto,
    DelayedAutoStart = true
    Arguments = "/arg1=value1"
};
```

**Comment by talapoin** [comment]
@Xaddan this is not a correct solution. Arguments passed to ServiceInstaller "Arguments" property ends writen in registry as a startup argument of the installed service. This is not what I need. I just need an option to run instalUtil.exe /arg1=val1 service.exe....
I don't need an option to pass argument to the service everytime it is started but an option to pass arguments to the service while it is installed.

**Comment by Xaddan** [comment]
`ServiceInstaller` installs a service not through `InstallUtil`
ServiceInstaller installs a service not through InstallUtil

To install via `InstallUtil`, you must write a `Custom Action` and use `Tasks.InstallService()`;
```C#
Tasks.InstallService (session.Property ("INSTALLDIR") + "MyApp.exe", true, /arg1=value1);
Tasks.StartService ("WixSharp.SimpleService", false);
```
See an example of `WinService_InstallUtil`

**Comment by talapoin** [comment]
thanks! will try that.
