### ISSUE TITLE
ManagedUI disable progress messages

### ISSUE THREAD

**Issue by SiyataDishmaya** [oleg-shilo/wixsharp#605]
When using ManagedUI, what is best way to disable the progress messages (not the progress bar) of the ProgressDialog? 
Thanks

**Comment by oleg-shilo** [comment]
The simplest way to do that is to create the project from the full UI sequence project templete:

![image](https://user-images.githubusercontent.com/16729806/54275440-b4ce8380-45de-11e9-9d56-6d947c9cb818.png)

And then simply remove the progress message label from the dialog, which will be available in your project as a source code.

**Comment by SiyataDishmaya** [comment]
Thank you!
