### ISSUE TITLE
Question: How to set property value

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#607]
Hallo Oleg, 
in my project in need to set property value which comes from search in network. 
create new property new Property("MYPROPERTY", "empty"). 

in Custom Action - session["MYPROPERTY"] = value -  is way, but i need to use dllimport from win32 api. How can i use dllimport in wix# ? Is it like third party dlls or i have to add required dlls from win32api in another way ?

**Comment by oleg-shilo** [comment]
Well, you use it the same way as with any C# application. 

If it is a _well-known_ dll then you just add `[DllImport("<your dll>")]` and invoke it at runtime.

If it is the dll that you need distribute then the usage is the same except you will also need to embed the dll into your msi or CA assembly (as resource). And at runtime, before invoking the dll, you will need to copy it somewhere (e.g. temp folder) and add that folder to your process environment variable `PATH`. That's it.

**Comment by Torchok19081986** [comment]
Many thanks, @oleg-shilo. I tested it with dllimport at runtime in CA. works fine. Dll that i used to win32 dll. Works fine. I just added in CA an execute it at runtime. 👍 
Last question, after this you can close this "Question issue".
how do i set Property for registrykey in client-server network ? i need to create regkey on client with servername. i can search for it in network, but i got access issue ? is there some posibility to start CA elevated or do i need to start msi elevated. Both are , i think, doable.

**Comment by oleg-shilo** [comment]
Yes, you can use `ElevatedCustomAction`
