### ISSUE TITLE
Create Shortcut on Desktop to dotnet.exe

### ISSUE THREAD

**Issue by WayneHiller** [oleg-shilo/wixsharp#608]
I am trying to create a Shortcut on the Desktop to dotnet.exe to run my app.dll.

My code is:
```
new Dir( "%Desktop%",
        new ExeFileShortcut( setupFeature, "AIS Setup", @"%ProgramFiles%\dotnet\dotnet.exe", @"[SETUPDIR]\AIS Manager Setup.dll" )
)
```

The wxs generated is:
```
<Directory Id="DesktopFolder" Name="DesktopFolder">
        <Component Id="Component.AIS_Setup" Guid="e535c39d-5fe8-4c19-802d-8033db35b3b2" Win64="yes">
          <Shortcut Id="DesktopFolder.AIS_Setup" WorkingDirectory="DesktopFolder.AIS_Setup.WorkDir" Target="%ProgramFiles%\dotnet\dotnet.exe" Arguments="[SETUPDIR]\AIS Manager Setup.dll" Name="AIS Setup.lnk" />
          <CreateFolder />
          <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
            <RegistryValue Value="0" Type="string" KeyPath="yes" />
          </RegistryKey>
        </Component>
      </Directory>
```

The shortcut does not get created and I don't see any error in the install log.
Am I doing something wrong?

**Comment by oleg-shilo** [comment]
I will need to test this scenario specifically. 
There are some competing priorities with this and the other projects from CS-Script family so it can take a week or two. Sorry.

**Comment by WayneHiller** [comment]
No problem @oleg-shilo I know you are busy, I will do more digging into the WIX docs to see if I can figure out why the shortcut does not get created.

**Comment by Xaddan** [comment]
```C#
new Dir(new Id("SETUPDIR"), "Name",    
    new ExeFileShortcut(setupFeature, @"%ProgramFiles%\dotnet\dotnet.exe", @"[SETUPDIR]\AIS Manager Setup.dll") { AttributesDefinition = "Directory=DesktopFolder" }
```

**Comment by WayneHiller** [comment]
The only way I could get it to work was like this.

```
new Dir( "%Desktop%",
  new ExeFileShortcut( setupFeature, "AIS Setup", @"[ProgramFiles64Folder]dotnet\dotnet.exe", 
                                   "\"[SETUPDIR]AIS Manager Setup.dll\"" ) {
    WorkingDirectory = "SETUPDIR"
  }
)
```

Using %ProgramFiles% in the Target did not work for me. Also the WorkingDirectory component created by wixsharp did not resolve to the correct path, I had to specify the SETUPDIR property name directly.

**Comment by oleg-shilo** [comment]
I have tested and the only working path that I found is this one:
```C#
new ExeFileShortcut("Test DOTNET", 
                    "[ProgramFiles]dotnet.exe", 
                   @"C:\ProgramData\chocolatey\lib\cs-script.core\tools\cscs.dll -wait")
```
I is strange I expected it to be `[ProgramFiles64Folder]dotnet\dotnet.exe` exactly as in your sample.

But... `"[ProgramFiles]dotnet.exe"` just works.

**Comment by WayneHiller** [comment]
@oleg-shilo that is strange, I would not expect that path to work. I could not get %ProgramFiles% to work at all, had to be [...]. Also I had to set the WorkingDirectory to the Name of a Directory, if I let wixsharp generate it then it did not work. Strange.

**Comment by oleg-shilo** [comment]
`%ProgramFiles%` vs `[ProgramFiles]`

Yes that is correct. `%ProgramFiles%` is a WixSharp notation (similar to envars) that is converted to `[ProgramFiles]` when it is used as a `Dir` name. I thought in shortcuts it is `[. . .]` as in native WiX. 

I have checked and it seems that all shortcut samples are using the correct notation:

![image](https://user-images.githubusercontent.com/16729806/54562215-a3d8a480-4a1a-11e9-82b0-763e3d0aabba.png)

And you cannot use any absolute path in the WorkingDir and ExeName. Only properties/names. This is rather an inflexible side of WiX.

**Comment by WayneHiller** [comment]
Sorry @oleg-shilo I  don't know where I got %...% from. Maybe just because it can be used in Dir.  After I dug through some wix docs I figured out about the properties/names no absolute path issue in shortcuts.

Thank you very much for all the help. I have built 3 installations with Wixsharp and everything is working great now. Always a bit of a learning curve with new tools but I absolutely love using Wixsharp.

**Comment by oleg-shilo** [comment]
Great. 
I am not completely surprised you got the impression that `%...%` is supported in shortcuts target. Intuitively we expect both `Dir.Name` and `Shortcut.Target` to represent path. But sadly in WiX/MSI reality they are different creatures.

Anyway I have extended handling `Shortcut.Target` values to support `%...%` as well. 

_WixSharp source_
```C#
new ExeFileShortcut("Uninstall MyApp", @"%ProgramFiles%\msiexec.exe", "/x [ProductCode]")
```
_Produced WiX code_
```xml
<Shortcut Id="INSTALLDIR.Uninstall_MyApp" 
          WorkingDirectory="INSTALLDIR.Uninstall_MyApp.WorkDir" 
          Target="[ProgramFilesFolder]msiexec.exe" 
          Arguments="/x [ProductCode]" 
          Name="Uninstall MyApp.lnk" />
```

The feature will be available in the very next release.

**Comment by WayneHiller** [comment]
Excellent, It is always good to be consistent where we can. Thank you.

**Comment by WayneHiller** [comment]
I have changed my Shortcut to:
```
new ExeFileShortcut( setupFeature, "AIS Setup", @"%ProgramFiles%\dotnet\dotnet.exe", 
                                 "\"[SETUPDIR]AIS Manager Setup.dll\"" ) {
   WorkingDirectory = "SETUPDIR"
 }
```

But the wix looks like:  Note the [ProgramFilesFolder64FolderFolder]

```
<Shortcut Id="DesktopFolder.AIS_Setup" WorkingDirectory="SETUPDIR" Target="[ProgramFilesFolder64FolderFolder]dotnet\dotnet.exe" Arguments="&quot;[SETUPDIR]AIS Manager Setup.dll&quot;" Name="AIS Setup.lnk" />
```

**Comment by oleg-shilo** [comment]
Thank you. 
Indeed the problem was solved only partially as the fix has a side effect on the directory shortcuts (e.g. desktop or programfiles folders).  

The commit https://github.com/oleg-shilo/wixsharp/commit/187a368b0f5db6b92f55eae4a35ceb7fc3fc6c56 addresses the issue and the fix will be available in the very next release.

**Comment by WayneHiller** [comment]
Excellent.

Note I had the same issue using [ProgramFilesFolder].

```
new Dir( "%Desktop%",
     new ExeFileShortcut( setupFeature, "ABS Setup", "[ProgramFilesFolder]dotnet\\dotnet.exe",
                                                                   "\"[SETUPDIR]ABS Setup.dll\"" ) {
         WorkingDirectory = "SETUPDIR"
      }
)
```

Wix

```
          <Shortcut Id="DesktopFolder.ABS_Setup" WorkingDirectory="SETUPDIR" Target="[ProgramFilesFolderFolder]dotnet\dotnet.exe" Arguments="&quot;[SETUPDIR]ABS Setup.dll&quot;" Name="ABS Setup.lnk" />
```

**Comment by oleg-shilo** [comment]
Yes the folders that are affected are:
- `ProgramFilesFolder` 
- `ProgramFiles64Folder` 
- `SystemFolder` 
- `System64Folder`
