### ISSUE TITLE
Build in Windows 10

### ISSUE THREAD

**Issue by GameHackerPM** [oleg-shilo/wixsharp#61]
Generally, I can't build or debug in Windows 10. I needed to create VMware with Windows 7 or Windows 8 and setup .Netframework 3.5 to be able to debug, and when i try to use the built MSI file on Windows 10, It works and extract fine, but for some codes like "Cmd, Rewrite files System.IO .. etc" Some of does strange stuff (I think they are crashing) and then it skip methods for that.
All what I want to ask how can i use it well on Windows 10? 
I get this error when MakesFxCA.exe tries to open:
```
System.ApplicationException: Cannot package ManagedCA assembly(%this%)
   в WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String configFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
   в WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
   в WixSharp.Compiler.GenerateWixProj(Project project)
   в WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   в WixSharp.Compiler.BuildWxs(Project project, OutputType type)
   в WixSharp.Compiler.BuildCmd(Project project, String path, OutputType type)
   в WixSharp.Compiler.BuildMsiCmd(Project project, String path)
   в WixSharp.Compiler.BuildMsiCmd(Project project)
```

Also If I changed the project from .NET 4.0 to .NET 3.5.
It works for MakesFxCA.exe and gets the same error for candle.exe exactly the same error.

Also the GUI for WinForms (Dialogs in WixSharpSetup Project) If i changed locations of controls, some of them gets changed when I try on each windows version (windows 10 Changed , Windows 7 and 8 alike).

Thanks.

**Comment by oleg-shilo** [comment]
I am not sure what is happening in your environment. Windows 10 isn't the direct cause of the problem. I in fact use exclusively Win10 + VS2017.

The error itself indicates that `MakeSfxCA.exe` fails to package the assembly. It's hard to say why but you can at least try to eliminate a "path mistake". Use the code below:
```C#
using System;
using System.Windows.Forms;
using Microsoft.Deployment.WindowsInstaller;
using WixSharp;

class Script
{
    static public void Main(string[] args)
    {
        var project = new Project()
        {
            UI = WUI.WixUI_ProgressOnly,
            Name = "CustomActionTest",

            Actions = new[]
            {
                new ManagedAction(CustomActions.MyAction, typeof(Script).Assembly.Location)
            }
        };

        project.BuildMsi();
    }
}

public class CustomActions
{
    [CustomAction]
    public static ActionResult MyAction(Session session)
    {
#if DEBUG
        System.Diagnostics.Debugger.Launch();
#endif
        session.Log("Begin CustomAction2 Hello World");

        return ActionResult.Success;
    }
}
```

With this code you will ensure that the location of the assembly to be packed is correct. 

Also it will give you a nice assertion prompt and you will see if you are attaching to the correct process. 

Mind you that on Win 10 (at least) your debugger must be elevated. And also you may need to avoid selecting the debugger from the assertion prompt but rater attach your VS2017 to the running process (msiaexec.exe) while the assertion dialog is visible. 

After that you can OK the assertion. This will load the correct source code and bring the breakpoint into the view.

**Comment by oleg-shilo** [comment]
Please have a look at https://github.com/oleg-shilo/wixsharp/issues/60
I provided there instructions on how to troubleshoot `MakeSfxCA.exe`.

**Comment by GameHackerPM** [comment]
Yeah, Thank you. I had a look in #60  and worked after updating the Bin Files from Wix, Still having error for debugging, but at least I can build the MSI file.

**Comment by oleg-shilo** [comment]
When experiencing debugging problems the usual suspects are always the same and they are:
- Debugger and debuggee having different elevation level
- Debugger and debuggee having different CLR version
- Debuggee having the binaries that do not exactly correspond available source code
- Debuggee not having debug symbols available
- User incorrectly identifying the process to debug. Assertion or even message box usually helps.
- Assertion having problems of locating, launching  and attaching the correct debugger. That's why manual attaching gives you a bit more control.
