### ISSUE TITLE
Warning when building two bundles in one setup

### ISSUE THREAD

**Issue by mgkeeley** [oleg-shilo/wixsharp#610]
If during a setup project, a bundle is built and then some other project is built afterwards (eg. another bundle) the following warning is emitted:
> Wix# compiler detected that some IDs has been auto-generated before the build started. This can lead to the WiX ID duplications. (...)

This is because the bootstrapper compiler does not reset the WixEntity AutoId generation at the end of each build in BuildWxs() (like the MSI Compiler does):
`project.ResetAutoIdGeneration(supressWarning: true);`
Example setup:
```
var project = new Project("MyProduct",
    new Dir(@"%ProgramFilesFolder%\My Company\My Product", new File(@"readme.txt"))
);
project.InstallScope = InstallScope.perMachine;
var msi = project.BuildMsi();

var bundle1 = new Bundle("MyBundle", new MsiPackage(msi)) {
    OutFileName = "MyBundle1",
    Version = new Version("1.0")
};
bundle1.Build();

var bundle2 = new Bundle("MyBundle", new MsiPackage(msi)) {
    OutFileName = "MyBundle2",
    Version = new Version("2.0")
};
bundle2.Build();
```

**Comment by oleg-shilo** [comment]
Very accurate problem description and cause analysis. :)
Thanks.
Fixed. Will be available in the next release.
