### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by SiyataDishmaya** [oleg-shilo/wixsharp#613]
We are trying to include a msi driver install within our main install. We use
   project.AddBinary(new Binary("Someinstall.msi"));
to include it in the msi. 

In a managed dialog, we run
   string CRTMsiFile = System.IO.Path.ChangeExtension(System.IO.Path.GetTempFileName(), ".msi");
                string CRTMsiId = "Someinstall.msi".Expand();//Expand() is needed to normalize file name into file ID
                Shell.MsiRuntime().MsiSession.SaveBinary(CRTMsiId, CRTMsiFile);
                int iResult = RunProcessAsAdmin(CRTMsiFile, "/quiet");
The SaveBinary command causes the "Access is denied" error.

This statement causes an "access is denied" error from the UAC. Is there any way to bypass this error? 
Thanks

**Comment by oleg-shilo** [comment]
The only way to bypass UAC is to run elevated. I am not sure what is your `RunProcessAsAdmin` implementation but the code below should work:

```C#
var startInfo = new ProcessStartInfo();
startInfo.FileName = "<exe>";
startInfo.Arguments = "<args>";
startInfo.UseShellExecute = true;
startInfo.Verb = "runas";

Process.Start(startInfo);
```

**Comment by SiyataDishmaya** [comment]
It turns out that the install was  calling some Windows functions which needed more privileges to run. We found a workaround for them. Thanks.
