### ISSUE TITLE
Previous installed product not removed

### ISSUE THREAD

**Issue by digitalsigi** [oleg-shilo/wixsharp#614]
Hi Oleg,
I am in the process of transforming an old WIX XML into Wix#. One of the reasons is that WIX provided an update from V3 to V4, I upgraded from VS2015 to VS2017, so things do not fit together anymore without some additional work.
When I authored the WIX XML I had very little experience with installers, but after some time I got it to work. So far I could transform almost all the items to Wix#, what is left is removing the old product.
In this old XML file the Upgrade section looks like this:
```XML
    <MajorUpgrade Schedule="afterInstallInitialize" AllowDowngrades="no" DowngradeErrorMessage="Diese oder eine neuere Version von [ProductName] ist bereits installiert." />
    <Upgrade Id="$(var.UpgradeCode)">
      <UpgradeVersion Property="SELFFOUND" OnlyDetect="yes" IncludeMinimum="yes" Minimum="5.0.0" IncludeMaximum="yes" Maximum="5.0.0" />
      <UpgradeVersion Minimum="5.0.0" IncludeMinimum="no" OnlyDetect="yes" Language="1031" Property="NEWERFOUND" />
    </Upgrade>
....
      <Custom Action="AlreadyUpdated" After="FindRelatedProducts">SELFFOUND</Custom>
      <Custom Action="NoDowngrade" After="FindRelatedProducts">NEWERFOUND</Custom>
```
in Wix# I have
```CS
            project.MajorUpgradeStrategy = new MajorUpgradeStrategy()
            {
                NewerProductInstalledErrorMessage = "Diese oder eine neuere Version von [ProductName] ist bereits installiert.",
                PreventDowngradingVersions = new VersionRange()
                {
                    OnlyDetect = true,
                    IncludeMinimum = true,
                    Minimum = upgradeVersion,
                    Maximum = upgradeVersion,
                    IncludeMaximum = true

                },
                UpgradeVersions = new VersionRange()
                {
                    Minimum = upgradeVersion,
                    IncludeMinimum = false,
                    IncludeMaximum = true,
                    OnlyDetect = true

                },
                RemoveExistingProductAfter = Step.InstallInitialize
            };
```
If I combine it with MajorUpgrade I get compile errors from light.
Even worse, in the past I did put all files into one Component, while WIX# puts each file is in its own component.
Is there a way to uninstall a previous version in such a scenario?
Thx for any help.

**Comment by oleg-shilo** [comment]
`MajorUpgrade` and `MajorUpgradeStrategy` are two competing WiX technologies and you should use one or another one. I don't expect them to work together.

`MajorUpgradeStrategy` is an older technology and in most of the cases you will be better off with the newer `MajorUpgrade`. But of course if you want to replicate your old solution then you should chose whatever works better for you.

Keep in mind that when you cannot find the map WiX to WixSharp 100% you can always manipulate  or even inject raw XML into the WiX content just before the compilation: https://github.com/oleg-shilo/wixsharp/blob/67c57624b5bc3db389f35ee6dd540da33070409d/Source/src/WixSharp.Samples/Wix%23%20Samples/InjectXML/setup.cs

**Comment by digitalsigi** [comment]
Thx for looking into it. Ah, WixSourceGenerated may be the secret. I am already familiar with AddWixFragment. Actually you are pointing me in direction to manipulate the generated WIX wxs. OK I'll give it a try.
One more thing: My old WIX asks for installerversion="400" whilest Wix# generated uses "200". 
Is there any notable difference?

**Comment by oleg-shilo** [comment]
> you are pointing me in direction to manipulate the generated WIX wxs

Yes but only for the cases when you cannot solve your problem directly. XML injection is a bit intrusive by nature. So you should use it only when you ave to.

> Is there any notable difference?

To be honest I don't know. I simply set this value long time ago when "400" was not available. I would assume that having it as "200" makes the msi more backwards compatible.

**Comment by digitalsigi** [comment]
> To be honest I don't know. I simply set this value long time ago when "400" was not available. I would assume that having it as "200" makes the msi more backwards compatible.

This is what I found: https://docs.microsoft.com/en-us/windows/desktop/msi/released-versions-of-windows-installer, at the bottom of the page are links to more details.
I think "400" came into the game when I was experimenting with WIX. I am not aware whether the existing WIX or CustomActions make use of one of the features. But I'ts quite possible, because I am authoring a VSTO installer based on some samples from internet. Unfortunately they seem to be down the river.

Thx for the great work.
