### ISSUE TITLE
Question: How to create windows restore point

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#616]
Hallo Oleg, i have a question. How do i create windows restore point in Wix# ?  I have to change  some important components in windows and would like to create restore point. Is it possible ?

**Comment by oleg-shilo** [comment]
I am not sure if WiX has direct support for this. Quite possibly it does but you kind of don't need it. It is a part of MSI workflow. Windows always creates restore point before any MSI installation.

**Comment by Torchok19081986** [comment]
many thanks, @oleg-shilo. i didnt knew , it was part of msi workflow.
