### ISSUE TITLE
Guid components

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#617]
Hi Oleg.
After upgrading WixSharp from 1.9.1 to 1.9.5, the Guid components have become changed with each build.
![image](https://user-images.githubusercontent.com/14925308/55224726-93020d00-522a-11e9-9d05-332b59822729.png)

Now for their generators, Product/Id is used, and before that, Product/UpgradeCode was used.
![image](https://user-images.githubusercontent.com/14925308/55224797-af05ae80-522a-11e9-9dd5-6822b7e271e2.png)

Did I miss something?

**Comment by oleg-shilo** [comment]
> ... the Guid components have become changed with each build...

That was scary. I am glad it's not the case. :)

Checked. The components guids are the same regardless how many times you rebuild the project. Even if you change the project/product version.  If indeed in your case rebuilds triggers the change of the component id then please provide the test case so I can investigate.  In my test I was using "InstalFiles" sample.

> Now for their generators, Product/Id is used, and before that, Product/UpgradeCode was used.

Correct but not exactly. 
The the UpgradeCode change was introduced in the later releases I think [v1.9.2.0](https://github.com/oleg-shilo/wixsharp/releases/tag/v1.9.2.0). It was triggered by this issue https://github.com/oleg-shilo/wixsharp/issues/452#issuecomment-411001633. Though the final change was only delivered to the codebase with the commit 25b9d35385e07524b182d29a41db9deab66c30a2

The change was required to accommodate really peculiar MSI requirement for component GUIDs to be not product unique but globally unique. Thus WixSharp was not meeting that requirement at the time. 

Though I am not sure component.id was ever seeded with UpgradeCode by default. This is the current implementation:

```C#
public class WixEntity
{
    . . .
    internal new string ComponentId(string seed)
    {
        // Component id must be globally unique. Otherwise other products can
        // accidentally trigger MSI ref-counting by installing more than one product
        // with the same component id.
        // The problem is caused by the mind bending MSi concept that a identity does
        // not logically belong to the product but to the target system. Thus if two
        // different products happens too have the component with the same id MSI will
        // treat the components as the same component.
        // Using GUID seems to be a good technique to overcome this limitation but the
        // the wast majority of the samples (e.g. WiX) use human readable ids, which are
        // of course not unique.
        // The excellent reading on the topic can be found here:
        // http://geekswithblogs.net/akraus1/archive/2011/06/17/145898.aspx
        // Ideally we would want to keep readability and uniqueness. Thus the solution
        // is to merge "human readable" id with the project guid.

        if (Compiler.AutoGeneration.ForceComponentIdUniqueness)
            return $"{seed}.{this.UpgradeCode.ToString().Replace("-", "")}";
        else
            return seed;
    }
    . . .
```
By default (`Compiler.AutoGeneration.ForceComponentIdUniqueness = false`) so the return value is raw `seed`, which is normally `project.ComponentId($"Component.{wixentity.Id}{suffix}")`:

![image](https://user-images.githubusercontent.com/16729806/55273489-4ef13400-5320-11e9-962c-ac34bdd712a0.png)

If you want to switch to UpgradeCode unconditionally then just `Compiler.AutoGeneration.ForceComponentIdUniqueness` to true.

**Comment by Xaddan** [comment]
I took the `InstalFiles` sample and made the following changes to it:
```C#
project.ProductId = Guid.NewGuid();
project.Version = new Version(1, 0, 0, 0);
//project.SetVersionFrom("MyApp_file");
```
Here's what I got:
![image](https://user-images.githubusercontent.com/14925308/55274779-b2b23780-52f5-11e9-849e-3f73593ec556.png)

**Comment by oleg-shilo** [comment]
I see.

The problem with your code is caused by this code line:
```C#
project.ProductId = Guid.NewGuid();
```
It results in a new _ProductId_ being assigned every time you build. If you are rebuilding the same product you need to maintain the same _ProductId_. And if you don't then effectively you are building a different product installation every time you execute the build. Thus these builds must have different set of component IDs.

You normally would preserve product identity as this:

```c#
project.ProductId = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
```
or even better:

```c#
project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
```

**Comment by Xaddan** [comment]
Take a closer look at the screenshot. I am changing the version.
When changing the version, the ProductId should change, so I use `project.ProductId = Guid.NewGuid ();`
In WixSharp 1.9.1, changing the ProductId did not affect the GUID of the components.

**Comment by Xaddan** [comment]
Well, I realized that installing the ProductId is redundant.

**Comment by oleg-shilo** [comment]
I was in the middle of the message explaining that :)

This is the intended handling of the product version increment:

_Product version 1.0.0.0_
```C#
project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.Version = new Version("1.0.0.0");
```
_Product version 1.1.0.0_
```C#
project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.Version = new Version("1.1.0.0");
```
