### ISSUE TITLE
Question: How to copy files in hidden Folder

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#618]
Hallo Oleg, i tried to copy Files from installer to Folder, which can be browsed by user / Administrator . InstallDir_DynamicPath was reference, but i got always execpetion, that my choosed directory was not found.
in CA i set it like that:
            systempath = session["SYSTEMDIR"];
            session["DIR2"] = systempath;  
            string installdir = session["INSTALLDIR"];
            if (io.File.Exists(cobrasystempath + @"\System.adl") || io.File.Exists(cobrasystempath + @"\System.ini"))
            {
                io.File.Copy(installdir + @"Vorlagen\cobra20190301.fma", session["DIR2"] + @"\cobra20190301.fma");
                session.Log("File copied to " + session["DIR2"]);          
            }
if i set it in Custom Dialog to right path i got exeception, and if not, files are not copied to DIR2 Id. I think its permissions, but i execute it as Domain Admin and its doesnt work also.

**Comment by Torchok19081986** [comment]
I figured out where was my problem and provide some solution here. 
Problem is in CA in Parameter When. if i set my CA for copy from install path to choosed path when paramete to before, it crashes and say it cant find part of path string for file, also if path was valid. 
 if i set when parameter to after and condition to always in CA , it works. 
Only one problem ... new File("Programm.cs" ) { overwriteoninstall = true} doesnt work, installer doenst replace already exists file in path. i got error in log, File in <Path> already exists.

**Comment by oleg-shilo** [comment]
Check your generated wxs file. Verify that it contains `<RemoveFile Id="..." On ="both" Name="..."/>`in the right folder.

**Comment by Torchok19081986** [comment]
Yes, it contains for each file that i marked with overwriteoninstall = true.  I tested it, it seems that i have a problem in my CA where i copy files from install path folder with settings to target path for product. 
It was workaound, i added in file.copy in third parameter overwrite: true, it works.
was my mistake.
