### ISSUE TITLE
Update WixSharp.Lab NuGet package

### ISSUE THREAD

**Issue by nebffa** [oleg-shilo/wixsharp#62]
The WixSharp.Lab NuGet package has issues, in that when you reference it via NuGet it does not bundle the correct version of WixSharp. This leads to an error in the WinForms designer as the correct version of WixSharp cannot be found, meaning that you can't edit to the form at all unless you reference the exact version of the WixSharp dll. The only way to do this seems to be to grab the exact release from GitHub that bundles everything together so that all the versions will be the same, but this is clunky as it avoids using NuGet.

Ideally, the versions of all the NuGet packages should probably be tied to the release so that you can always get the right versions of assemblies.

**Comment by oleg-shilo** [comment]
Not a problem. I just wasn't sure if `WixSharp.Lab` was actually in use.
Fixed now. The package has been published and the build script updated to refresh `WixSharp.Lab` with every release.

Thank you for reporting.

**Comment by nebffa** [comment]
Holy shit dude, that was such a fast response time! Thankyou so much for fixing this. At my workplace, we are big fans of Wix.Sharp - thanks for maintaining it.

**Comment by oleg-shilo** [comment]
:) :)

It was easy. All actions are performed by scripts. I just added the "WixSharp.Lab" to the rest of packages and started the script. That is it.

Enjoy
