### ISSUE TITLE
How to use installation directory in RegistryValue.

### ISSUE THREAD

**Issue by jakubpietka** [oleg-shilo/wixsharp#623]
Hi,
I am creating registry values and my problem is that value should points to installation directory and one of a files but installation path can be changed during installation process.
For example after default installation when user clicks only Next we have c:\test\test.exe and I can create registry value like this: new RegValue(RegistryHive.ClassesRoot, "MyApplication", "ExePath", "c:\test\test.exe");

When user will change installation directory this registry entry will be false. 
How can I create RegistryValue object so it would make sure 'value' parameter will use installation directory and not hardcoded one?

**Comment by Torchok19081986** [comment]
Hi, in my application i use Property of INSTALLDIR. Are you tried it with [INSTALLDIR] for path and for exe itself ? 
if user change path, INSTALLDIR are also valid and use correctly path. Oleg can say more than i.
