### ISSUE TITLE
Question: Conditional Installation

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#625]
Hi Oleg, is it possible to set value in destation file or copy some files after question "should XYZ set to {value}" and if yes then set it ? Its like conditional installation for shortcut, but it doesnt work like expected. if not possible then how do i trigger CA after question ?

**Comment by oleg-shilo** [comment]
You can create an MSI property that is a part of your file condition. And at runt time you can set this property from your CA with the question "should XYZ...".
