### ISSUE TITLE
Creating an msi to deploy an asp.net core 2.1 with angular 6

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#626]
Hi 

Is it possible to create an msi to deploy an asp.net core 2.1 web api with angular 6 front end using the magic of wixsharp?

Thanks laz

**Comment by vermeulen1992** [comment]
Hey laz,

Yes, you can create an installer for almost everything (On windows ofc).
Just define where you want to deploy your files and you are good to go.
Look at the example projects for getting started ;)

Gr, Leon

**Comment by ltemimi** [comment]
Hi Leon

Many thanks for your help, I have dot net core 2.1 to install as a windows service , All my file are installed in the install directory but my custom action fails;
 public static ActionResult InstallService(Session session)
        {
            return session.HandleErrors(() =>
                                        {
                                            Tasks.InstallService(session.Property("INSTALLDIR")
                                                                 + "ConnectedOfficeApp.API.exe",
                                                                 true);

                                            Tasks.StartService("WixSharp.ConnectedOfficeApp.API", false);
                                        });
        }
fails to install the service as the "exe"  is in a dot net core format. I get the error

System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Program Files (x86)\OALConnected\OAL\ConnectedOfficeApp\publish\ConnectedOfficeApp.API.exe' or one of its dependencies. The system cannot find the file specified..

------------------------------
I know the file is there but because the installer project is a dot net framework project it thinks the "exe" file is not there or it cannot load it

Please help
regards Laz

**Comment by oleg-shilo** [comment]
Hi Laz,

Have a look at `Tasks.StartService` implementation and implement your custom approach when you will call `run("dotnet", "app, <args>")` instead of the current `run("app", "<args>")`

Then simply call your  alternative `Tasks.StartService` from the custom action.

**Comment by ltemimi** [comment]
Hi Oleg

Many thanks for your response I have an Install.bat and Uninstall.bat to create, install and uninstall the service would you have an example on how to use them in my custom action.
Thanks Laz

**Comment by oleg-shilo** [comment]
You can do it with `Process.Start("path to batch file")` in your custom action. If you want to hide console window you will need `process.StartInfo.UseShellExecute = false;` and hide window

**Comment by ltemimi** [comment]
Hi Oleg

Many thanks for your response you mean

 public static ActionResult InstallService(Session session)
        {
            var installDir = session.Property("INSTALLDIR");
            var installPath = Path.Combine(installDir, @"\Publish\install.bat");
            Process.Start(installPath);

            return ActionResult.Success;
        }

I am getting a file not found exception ; my install.bat file is in  Publish folder.

Any idea?

Thanks

**Comment by oleg-shilo** [comment]
Yes it is what I meant.

The debugging technique is described here: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#managed-custom-actions

> Thanks to the fact that ManagedAction is implemented in a plain .NET assembly it can be debugged as easy as any other managed code. The most practical way of debugging is to put an assert statement and to attach the debugger when prompted:
``` 
[CustomAction]
public static ActionResult MyAction(Session session)
{
    Debug.Assert(false);
    ...
```

Just keep in mind that your debugger must be elevated.

=================
Just a side note. I have fixed you prev post code formatting. YOu may want to enclose 
your code in pair of \`\`\` for a good formatting view:

\`\`\`c#
Debug.Assert(false);
\`\`\`  

will be displayed as:

```C#
Debug.Assert(false);
```

**Comment by ltemimi** [comment]
Thanks Oleg, your suggestions work well it the path.combine that was the issue ; it returns the second path rather  than the combined path.

Thanks for your time
Laz

**Comment by oleg-shilo** [comment]
Yeah, I have also discovered that non intuitive behavior of `Path.Combine`. Nasty
