### ISSUE TITLE
Question: Getting install directory from bootstrapper options

### ISSUE THREAD

**Issue by Platforms1234** [oleg-shilo/wixsharp#627]
Hi,

I am having an issue getting the install directory that you set in the options button on the bootstrapper, such as in the picture below
![1](https://user-images.githubusercontent.com/49688138/56220581-971e8f00-6060-11e9-8705-b09668f85352.PNG)

I have set up my bootstrapper with the following variable 
`bootstrapper.Variables = new[] { new Variable("INSTALLDIR", "[ProgramFilesFolder]installer") };`

And the variable is passed to the MSI as below

`new MsiPackage(APIPath)
{
    Name = "API installer",
    MsiProperties = "INSTALLDIR=[INSTALLDIR]" + @"\API"
}`

Of course currently, the path the bootstrapper installs to is "[ProgramFilesFolder]installer", I would like to know how to get the new install directory from the image above, and use it in the bootstrapper variable.

Thanks

**Comment by Tum4ik** [comment]
I am using EmbeddedUI_WPF and I'm also interested how to change the installation directory from my custom dialog during installation.

**Comment by Tum4ik** [comment]
hm... It seems it is possible to do with [ManagedProject example](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/InstallDir_DynamicPath/setup.cs)

Am I right?

**Comment by Xaddan** [comment]
I here described how to change the installation directory: #596

**Comment by Tum4ik** [comment]
@Xaddan thanks, it is the answer for @Platforms1234. But do you know the solution without bootstrapper?

**Comment by Platforms1234** [comment]
@Xaddan I did see that post, however I am struggling with where to create the InstallLocation string, I have no model in my code, so cannot create the string

**Comment by Xaddan** [comment]
@Platforms1234 unfortunately, I did not use Standard Bootstrapper, and I can’t answer your question, you have to wait for Oleg.

**Comment by Platforms1234** [comment]
@Xaddan Ok, thanks anyway for the help.

**Comment by Xaddan** [comment]
@Platforms1234 try this:
```C#
bootstrapper.Variables = new[] { new Variable("InstallFolder", "[ProgramFilesFolder]installer") };
...
new MsiPackage(APIPath) { Name = "API installer", MsiProperties = @"INSTALLDIR=[InstallFolder]\API" }
```

**Comment by Platforms1234** [comment]
@Xaddan Perfect! That worked. Thanks so much for the help!
