### ISSUE TITLE
If signing of the bundle, or msi fails, wix does not error

### ISSUE THREAD

**Issue by jonreis** [oleg-shilo/wixsharp#628]
I have wixsharp signing my installers for me which is great. However; it the signing fails, the build still succeeds because wixsharp does not report the error. I think users would want their build to fail under these circumstances.

Here is what gets reported in the build output:

Could not sign the D:\agent\_work\1\s\Connexion.Setup.WixBA\bin\Release\Connexion.15.0.17070.msi file.

There is no other information about why it failed event with OutputLevel = SignOutputLevel.Debug (this is signtool's problem). 

But, regardless of why it failed, I think wixsharp should throw an error.

**Comment by oleg-shilo** [comment]
Can you please provide the test case as I cannot reproduce it:
 
![image](https://user-images.githubusercontent.com/16729806/56367581-e0293b80-6238-11e9-807c-536648253ce4.png)

**Comment by jonreis** [comment]
Sorry Oleg, I have tried but once I got the offending machine working, I cannot reproduce the issue. My only guess is that the PATH settings cause some old version of SignTool.exe being picked up. Once I removed all old versions of the Windows SDK, the problem resolved itself.
