### ISSUE TITLE
3rd-party libraries for custom installer

### ISSUE THREAD

**Issue by Tum4ik** [oleg-shilo/wixsharp#631]
Hi, is not it possible to include some third-party libraries?
For example I want to use [Markdig-WPF](https://github.com/Kryptos-FR/markdig.wpf) to render my License.md file and show it during installation process. But I get an exception when trying to use Markdig functionality.

![image](https://user-images.githubusercontent.com/21317790/56348006-3745f680-61ce-11e9-85be-ed94daed9b06.png)

**Comment by Xaddan** [comment]
Look here: #545

**Comment by Tum4ik** [comment]
Yes, nice, thanks!
