### ISSUE TITLE
Change install directory from the Embedded UI

### ISSUE THREAD

**Issue by Tum4ik** [oleg-shilo/wixsharp#633]
Hi, I am using EmbeddedUI_WPF for my installer.
```csharp
  public class Setup
  {
    public static void Main()
    {
      var project =
        new Project("RemoteControlServer",
          new Dir($"{Environment.GetEnvironmentVariable("ProgramFiles")}\\MyProg",
            new Files(binariesFolderPath),
            new wix.File("License.md")))
        {
          GUID = Guid.Parse("real-guid"),
          EmbeddedUI = new EmbeddedAssembly(sys.Assembly.GetExecutingAssembly().Location)
        };

      project.BuildMsi();
    }
  }
```

I also use this class for my custom dialog to prompt user about installation path.
```csharp
  /// <summary>
  /// Interaction logic for InstallPathDialog.xaml
  /// </summary>
  public partial class InstallPathDialog
  {
    public static event Action Selected;

    public InstallPathDialog()
    {
      InitializeComponent();
    }

    private void InstallPathDialog_OnLoaded(object sender, RoutedEventArgs e)
    {
      Selected?.Invoke();
    }

    private void BrowseButton_OnClick(object sender, RoutedEventArgs e)
    {
      var dialog = new VistaFolderBrowserDialog();
      if (dialog.ShowDialog() == true)
      {
        // TODO: apply installation path from dialog result
      }
    }
  }
```

But I have no idea how I can change the install path.
Could you help me pls?

**Comment by oleg-shilo** [comment]
You need to pass the session object to your dialog:

```C#
class class SampleEmbeddedUI : IEmbeddedUI
{
    public bool Initialize(Session session, string resourcePath, ref InstallUIOptions internalUILevel)
    {
        this.session = session;
        this.appThread = new Thread(this.Run);
        this.appThread.Start();
        . . .

    void Run()
    {
        this.UIDialog= new InstallPathDialog(this.session);
        . . .

class InstallPathDialog
{
    void installButton_Click(object sender, RoutedEventArgs e)
    {
        session["INSTALLDIR"] = this.SelectedDirectory;
        . . .
```

**Comment by Tum4ik** [comment]
Yeah! Finally, thanks. I tried the same, but I tried to set `session["my_own_dir_ID"]`.

**Comment by oleg-shilo** [comment]
It needs to be the name/property of the id of the directory element, which defines where you install your product as it is in the WXS file. WixSharp by default gives it `INSTALLDIR` id.

**Comment by Xaddan** [comment]
Oleg, how to get the original path?
This code produces an empty string:
``` C#
this.SelectedDirectory = session[ "INSTALLDIR" ];
```

**Comment by Tum4ik** [comment]
... the same question ))

**Comment by Xaddan** [comment]
As far as I understand, the Embedded UI is initialized before variables with paths are created, and it will not work to get them in the usual way.

**Comment by Tum4ik** [comment]
so, the way is to keep the original path in some constant? And read the constant during Project building and in the GUI.

**Comment by Xaddan** [comment]
Когда инсталлятор инициализируется, на определенном этапе (вроде бы CostFinalize ), создаются вспомогательные переменные, в том числе и INSTALLDIR, в которую записывается путь установки. Embedded UI инициализируется раньше этапа CostFinalize, поэтому из UI ты не можешь получить данные из переменной INSTALLDIR т.к. её еще не существует.

**Comment by Tum4ik** [comment]
Это понятно, что не могу) Вопрос в том, как смочь?)

**Comment by Tum4ik** [comment]
Константа будет работать, но может есть болле элегантный путь...

**Comment by Xaddan** [comment]
Я Embedded UI не использовал в проектах, и не могу подсказать хорошего решения, но на сколько знаю без костылей не обойтись.
По пробуй использовать константу, хотя я не понял про что ты)
Можно распарсить табличку Directory и собрать путь самому.
![image](https://user-images.githubusercontent.com/14925308/56579379-1112c300-65e1-11e9-909c-ca24bceac6f3.png)

**Comment by Tum4ik** [comment]
Вот константа
```csharp
  public class Setup
  {
    public const string InstallDir = @"c:\install dir";

    public static void Main()
    {
      var serverExeFilePath = sys.Assembly.GetAssembly(typeof(Program)).Location;
      var binariesFolderPath = Path.GetDirectoryName(serverExeFilePath);

      var project =
        new Project("RemoteControlServer",
          new InstallDir(InstallDir,
...
```

там, где нужно получить папку установки:
```csharp
this.SelectedDirectory = Setup.InstallDir;
```

**Comment by Xaddan** [comment]
Тогда уж лучше сделать виксовую переменную
``` C#
var project =
        new Project("RemoteControlServer",
        new Property("DEFAUILT_INSTALLDIR ", @"c:\install dir"));
```
К ней будет доступ из UI
``` C#
this.SelectedDirectory = session[ "DEFAUILT_INSTALLDIR " ];
```

**Comment by Tum4ik** [comment]
Ну вот, уже элегантней ))

**Comment by Xaddan** [comment]
Ну это все равно костыль)
Думаю должен быть способ и получше, но я его не знаю.

**Comment by oleg-shilo** [comment]
since you want to use absolute path then have a look at "absolute path" sample. It solves this problem by exactly creating an additional variable. 

Yes it is ugly as hell. But hey... this is the world of MSI for you. This is not the limitation of neither Wix nor WixSharp nut pure MSI "beauty".

I suggest you create the project from "CustomUI" template:

![image](https://user-images.githubusercontent.com/16729806/56580836-ee030600-6616-11e9-890e-da71833005da.png)

Then have a look at the source files in your project. It will help. "CustomUI" template is nothing else but a WinForm implementation of the Embedded_UI.

**Comment by Tum4ik** [comment]
Буду тогда делать так:
```csharp
  public class Setup
  {
    public const string InstallDirId = "install_dir";

    public static void Main()
    {
      var installDirValue = $"{Environment.GetEnvironmentVariable("ProgramFiles")}\\Tum4ik\\RemoteControl\\Server";

      var project =
        new Project("RemoteControlServer",
          new Property(InstallDirId, installDirValue),
          new InstallDir(new Id(InstallDirId), installDirValue,
...
```
и потом
```csharp
installPathDialog.InstallPathTextBox.Text = _session[Setup.InstallDirId];
```

**Comment by oleg-shilo** [comment]
No, will not work.

You will resolve `ProgramFiles` variable on your build machine but not on the target system. Your `Main` is only executed when you build your msi.

To be honest I am not entirely sure why you are trying to do it in such a convoluted way. 

Your task is quite simple:

```C#
 var project =
                new ManagedProject("My Product",
                    new Dir(@"%ProgramFiles%\My Product",
                        new WixSharp.File(@"myapp.exe",
. . .
// in your dialog

installDirTextBox.Text = Environment.ExpandEnvironmentVariables(@"%ProgramFiles%\My Product");
```

Just make sure you handle x32 vs x64 host target OS

**Comment by Tum4ik** [comment]
oh... thanks, I didn't think about it.

**Comment by oleg-shilo** [comment]
When WixSharp provides generic UI framework (_Embedded_UI_) then I have no other choice but to extract the default installation path from the MSI tables. It is in fact a tricky thing to do. I have to do this because this generic GUI supposed to work with ANY msi supplied by a developer.

Though in your case when you are building your own MSI and own GUI you have this luxury just knowing upfront what is your default install dir.
