### ISSUE TITLE
Implement REINSTALLMODE feature

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/wixsharp#638]
Based on #636  discussion WixSharp will need to implement REINSTALLMODE.
Requrements: https://docs.microsoft.com/en-us/windows/desktop/Msi/reinstallmode

**Comment by Xaddan** [comment]
How are you going to implement it?

**Comment by Xaddan** [comment]
I think `amus` is a good default.

**Comment by oleg-shilo** [comment]
> How are you going to implement it?

As `project.ReinstallMode = "amus";`
