### ISSUE TITLE
Question: How to add FileAssociation for my Programm

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#639]
Hallo Oleg, i want to know, if there are possibility to set File Extension like *.dbl for my Programm during installation ?  Many thanks for answer anyway.

**Comment by Xaddan** [comment]
You won't believe:
```C#
new File("Program.exe",
             new FileAssociation("dbl"))
```

**Comment by Torchok19081986** [comment]
Thansk for answer, @Xaddan. Just tested, works good in MSI. And how about bootstrapper exe ? is it same declaration or ihave to set it in another way ?

**Comment by Xaddan** [comment]
The bootstrapper should not make changes on the user's computer, it should only run the installers (prerequisites and your msi).

**Comment by Torchok19081986** [comment]
thanks again, @Xaddan. installer goinb to set fileassociation for endpoint.  i havnt tested it yet, but what happens on update ? does my file associations are gone after update. AFAIK is update uninstall old version and install newer one . Do i need set *.(extension) in update too ?

**Comment by Xaddan** [comment]
Are you using MajorUpgrade?

**Comment by Torchok19081986** [comment]
Yes. Same guid for project and update.

**Comment by Xaddan** [comment]
When using MajorUpgrade, you should only change what actually needs to be changed in the new version (adding new files, deleting unnecessary files, new entries in the registry, etc.) everything else should not change.

**Comment by Xaddan** [comment]
Since the new version can not only update the old installed version, but also install the product from scratch, you need to plan the installation based on this.
If the new version, when installing from scratch, must register the extension of your program, then you must add this element to the new version.

**Comment by Torchok19081986** [comment]
many thanks, @Xaddan , again 👍 .  if i understand correctly, i need to use it in msi and if i use exe to install my product i have to add it to my output msi file. for update i have to verify what i need and create update exe  / plan executable bootstapper for this. 
Means, i have to tested it in msi / exe installer for firstinstallation and update . 
Close the question.

**Comment by Xaddan** [comment]
First understand that all the changes with the computer are made by the MSI installer! Bootstrapper should not make any changes with the computer!
Make the first version of the installer. Check that it works as it should. (installs files, registry entries, creates shortcuts to files, etc.)

Make a second version of the installer. As a rule, this is the first copy as amended. (Added new files, deleted old files, added new entries to the registry, deleted old entries to the registry, etc.)
Check that it is installed from scratch. Check that it updates the first version.

If your program requires third-party programs, such as the Sql server, .net framework, then you need to use a bootstrapper. He will prepare the computer to install your system.

Make the first version of the bootstrapper. Add to it all the necessary prerequisites and your first version installer.
Check that it works as it should. (Prerequisites are installed, your installer is installed)

Make a second version of the bootstrapper. Add to it all the necessary prerequisites and your second version installer.
Check that it is installed from scratch. Check that it updates the first version.

**Comment by oleg-shilo** [comment]
An excellent summary @Xaddan . 

For all intensive purposes every msi built needs to be considered as a complete self sufficient setup. It needs to be able to install all required arteiacts on a clean target system.

Though you can "mark" your msi as an "upgradable" msi. Every msi you build. This will simply ensyre ther any previous installation of your product will be uninstalled if found during the installation.

That's it. Nothing more, nothing else.
