### ISSUE TITLE
Question: Is it possible to create WebAppPool with freshly created user?

### ISSUE THREAD

**Issue by PubEne** [oleg-shilo/wixsharp#642]
I have a problem that I can not deal with. I create the installer, which is to create a new account in the system (the user provides the name of the new account and password during the installation). This part is working correctly, I have User Name in property 

> e.Session.Property("NAME")

How can I swap it with TestAccount? 

```
WebAppPool = new WebAppPool("AppPool",
	"ManagedRuntimeVersion=v4.0;" +
	"ManagedPipelineMode=Integrated; " +
	"Identity=other;" +
	"User=TestAccount")
```
	
I've also saw this thread:
https://github.com/oleg-shilo/wixsharp/issues/477
When I try to change identity in AfterInstall (via bat file) webAppPool Seems not to be created at this momemnt. Please for any idea to solve this.

**Comment by oleg-shilo** [comment]
I am not sure what exactly you are doing, but should you be trying to set the user via the property:
```C#
WebAppPool = new WebAppPool("AppPool",
	"ManagedRuntimeVersion=v4.0;" +
	"ManagedPipelineMode=Integrated; " +
	"Identity=other;" +
	"User=[NAME]")
```
Though from the WiX doco it's not clear if the properties are getting extended: https://wixtoolset.org/documentation/manual/v3/xsd/iis/webapppool.html
