### ISSUE TITLE
Installation rollback after error

### ISSUE THREAD

**Issue by Lyakhova** [oleg-shilo/wixsharp#643]
Please tell me how to localize the buttons in this dialog?
![ErrorDialog](https://user-images.githubusercontent.com/25749844/57773322-6cd3f600-7720-11e9-8524-af38d74f8e1d.jpg)
When you click on any of the buttons, the installation of the application rolls back, should it be?
Why do three different buttons perform the same function?
Tell me if I can fix it myself? If so, how to do it? Or do I have to wait for future versions of WixSharp?

P.S. Sorry for my English. I translated with google.)

**Comment by oleg-shilo** [comment]
Can you please provide some context. 

- What GUI are you using? Is it native MSI or managed WixSharp UI?
- What triggers the error?

**Comment by Lyakhova** [comment]
1. I am using a managed WixSharp UI.
2. The error has already been fixed, it appeared during the creation of the Windows service. I want to fix this dialog so that users of the application have no questions in the future.

**Comment by oleg-shilo** [comment]
Then I suggest you create a test project from the _Custom UI_ template:

![image](https://user-images.githubusercontent.com/16729806/57846908-953f1b80-7818-11e9-8c2c-c5a75aabc1b9.png)

This will create a project with all dialogs as a source code so you can change any buttons' text. Now you can fix your dialog and bring it to your project. 

If it happens that the message box is not one of those that is part of MSI runtime and not available in the C# source code, then you will need either localize your whole project too. Have a look at "CustomUIDialog" for that.

**Comment by Lyakhova** [comment]
I already created the my project from the Custom UI template. I enabled the following dialogs:
``` 
project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                              .Add<LicenceDialog>()
                              .Add<InstallDirDialog>()
                              .Add<ProgressDialog>()
                              .Add<ExitDialog>();
project.ManagedUI.ModifyDialogs.Add<MaintenanceTypeDialog>()
                              .Add<ProgressDialog>()
                              .Add<ExitDialog>();
```
There is no this dialog:
![image](https://user-images.githubusercontent.com/25749844/57852485-fbfa1000-77eb-11e9-8f86-8136826db3a8.png). 
But this dialog appeared on top of ProgressDialog during an error when starting the service.  The rest of the dialogs are localized except for this. I use localization files from the wix toolset SDK in my project (as in CustomUIDialog)
And you gave advice on localization, but not on the functionality of the buttons. 
> When you click on any of the buttons, the installation of the application rolls back, should it be?
> Why do three different buttons perform the same function?

Sorry, but I still do not understand, this problem (localization, dialog buttons) can be corrected with the help of WixSharp?

**Comment by Xaddan** [comment]
Язык кнопок зависит от культуры винды, насколько я знаю их нельзя локализовать.

**Comment by oleg-shilo** [comment]
It depends. If the message box that you see is an interop (WIN32) message box then indeed not much you can do.

If however it is a message box that MSI constructs and displays at runtime then you most likely can localize it by specifying localization mapping as it is done in "CustomUIDialog" example where the all UI labels are localized in German.

**Comment by Lyakhova** [comment]
Thank you. I understood about the localization of the dialog.  But my problem is that the functionality of the buttons in this dialog does not work (see the screenshot of the dialog above).  
I tried to add a standard UI: `project.UI = WUI.WixUI_Minimal;`.
Then I reproduced the error and this dialog appeared:
![image](https://user-images.githubusercontent.com/25749844/60081703-fbce2800-973a-11e9-9763-bb3ed3cffcdd.png).
When I clicked on the "Repeat" ("Повторить") button, the service launch action started again.  It turns out this is an error in wix sharp, not windows installer. Tell me please, can this be fixed? Why these buttons if they do not work? I want to use ManagedUI in our MSI, but it gets in the way.

**Comment by oleg-shilo** [comment]
```
project.UI = WUI.WixUI_Minimal;
```
The code above means that you are using MSI UI not WixSharp UI. For WixSharp UI you will need to declare it as:

```
project.ManagedUI = . . .
```

> Why these buttons if they do not work?

I am reasonably confident that the message box is a native MSI dialog so you will not be able to do anything about about them. The fact that you have the same message box regardless if you are using MSI or WixSharp UI only confirms this. 

You will need to understand what install action is causing the error. "_It turns out this is an error in wix sharp, not windows installer._" does not tell much... Thus I suggest you investigate the log file. Use _msiexec.exe_ args to enable logging. Most likely there will be an error log message that will tell you what action is raising the error. 

If it happens to the custom action you implemented with WixSharp then you can debug. 

This is how I would approach this problem.
