### ISSUE TITLE
Components shared between multiple applications

### ISSUE THREAD

**Issue by noctis0430** [oleg-shilo/wixsharp#644]
I'm experimenting with WixSharp (1.9.7) to install 2 applications which share the same assembly. With Wix toolset (3.11), I've figured out that we can do so by defining a component and give it a Guid, then have both applications reference to the same component. How do we do the same with WixSharp?

I've been playing around with [this](https://github.com/oleg-shilo/wixsharp/files/3186782/Github.zip)  test solution, and my finding so far is that ones need to set `WixGuid.ConsistentGenerationStartValue` to some fixed Guid in order to have reproducible Guids. In WixSharp, `WixGuid.ConsistentGenerationStartValue` is set to `ProductId` or `GUID` property of `Project`, whichever is available first. If both are not available, a new Guid is used. 

```csharp
internal void ResetWixGuidStartValue()
{
    WixGuid.ConsistentGenerationStartValue = this.ProductId ?? this.GUID ?? Guid.NewGuid();
}
```

This make the mission impossible to achieve since both applications must have different product ID.

Instead, by setting `GUID` property of both projects to the **same** Guid and updating the codes above to the following, I manage to achieve what I want.

```csharp
internal void ResetWixGuidStartValue()
{
    WixGuid.ConsistentGenerationStartValue = this.GUID ?? this.ProductId ?? Guid.NewGuid();
}
```
However, I'm not sure whether it is a right thing to do.

Any thoughts?

**Comment by oleg-shilo** [comment]
You don't need to alter you product identities. you just need to set you component ID to the desired value. You can do this by altering XML `WixSourceGenerated`. Alternatively you can set it directly as file property: 
```C#
new File("my_asm.dll")
{
    ComponentId = "<whatever id you want>"
}
```

**Comment by noctis0430** [comment]
> ```cs
> new File("my_asm.dll")
> {
>     ComponentId = "<whatever id you want>"
> }
> ```

I've tried the above and checked the generated .wxs file. It produce the component with the specified Id, but but the Guid is still not identical. Installing both application with generated .msi file and remove one of them cause the shared library to get removed as well, which is not suppose to happen. A shared component is identified by their Guid instead of Id, no?

**Comment by oleg-shilo** [comment]
> A shared component is identified by their Guid instead of Id, no?

I don't really know. Possibly. The whole idea of shared components was implemented in MSI before .NET was introduced and sharing resources between deployments became anti-pattern. Of course this is not applicable to GAC assemblies.

Anyway, setting the `ComponentId` to the same value in two independent setup projects will trigger generation of the same GUID. This is because GUID is derived from that very same component id:

```C#
XElement comp = dirItem.AddElement(
    new XElement("Component",
        new XAttribute("Id", compId),
        new XAttribute("Guid", WixGuid.NewGuid(compId))));

```

**Comment by noctis0430** [comment]
> ```cs
> XElement comp = dirItem.AddElement(
>     new XElement("Component",
>         new XAttribute("Id", compId),
>         new XAttribute("Guid", WixGuid.NewGuid(compId))));
> ```
From the codes above,I trace the code all the way back to the following:
```cs
public static Guid Default(object seed)
{
    return WixGuid.HashGuidByInteger(WixGuid.ConsistentGenerationStartValue.CurrentGuid, seed.ToString().GetHashCode32());
}
```
which point me back to `WixGuid.ConsistentGenerationStartValue` where it uses the `ProductId` which both of my setup projects have different value. It seems like having the same `ComponentId` alone is not sufficient to generate reproducible Guid for the component. Any thoughts?

**Comment by oleg-shilo** [comment]
Yeah, you are right. I only tested it within the same project so it produced the same GUID.

Of course you may try to override the default implementation of the `Genarotor` 
```C#
WixGuid.Generator = (object seed) =>
            WixGuid.HashGuidByInteger(Guid.NewGuid("the same start guid in both projects"), seed.ToString().GetHashCode32());
```
But this may lead to unexpected behavior so arguably the most practical solution is to use XML injection:

```C#
new File("my_asm.dll")
{
    ComponentId = "my_asm"
}
. . .
project.WixSourceGenerated +=
    doc => doc.FindAll("Component")
              .Single(x => x.HasAttribute("Id", "my_asm"))
              .SetAttribute("Guid", "6f330b47-2577-43ad-9095-1861ba25889b");

```

**Comment by noctis0430** [comment]
Thanks for the proposed solution. But I think I will take the adventurous path and use the following

```cs
internal void ResetWixGuidStartValue()
{
    WixGuid.ConsistentGenerationStartValue = this.GUID ?? this.ProductId ?? Guid.NewGuid();
}
```
Not sure whether it will impact the upgrade process, but we shall see soon 😁

**Comment by oleg-shilo** [comment]
That's not a problem at all.
You can completely shield your solution from any GUID ambiguity by setting the vital ones explicitly:
```C#
project.UpgradeCode = . . .
project.ProductId = . . .
```
