### ISSUE TITLE
Interrupt CA execution

### ISSUE THREAD

**Issue by Xaddan** [oleg-shilo/wixsharp#647]
Hi Oleg.
You do not know how to interrupt the execution of CA, if the user clicked "Cancel" during the installation?
I use bootstrapper.

**Comment by oleg-shilo** [comment]
If you are asking how to detect from the inside of the CA that user clicked _Cancel_ then I don't have the answer. 

I wouldn't be surprised if WiX sets some special property. If it is the case then you can simply check this property and decide if you want to interrupt the CA execution. If you find the answer then share it and I will add `session.IsCanceled` for convenience.    

 Though if you are asking how to cancel the installation from CA to achieve the same effect as when pressing the _Cancel_ button then it is as below:

```C#
[CustomAction]
public static ActionResult MyAction(Session session)
{
    . . .
    return ActionResult.UserExit;
}
```

**Comment by Xaddan** [comment]
I'm talking about your first guess.

**Comment by oleg-shilo** [comment]
OK then.

Of course if you are using managed UI then you can add setting that special property by yourself. However since you are using bootstrapper it is problematic. WiX Burn has a long standing defect that prevents any non-stock UI from being displayed from a bootstrapped session. It is scheduled to be fixed for WiX v4.0 but who knows...

Though if user cancels the install after the the CA has started then relying on property most likely will not work anyway. Why? Because every CA starts as a separate process and the session properties are pushed to the CA at start and retreived back at the end. I am not sure one can pull a fresh set of properties from the middle of CA execution.

**Comment by Xaddan** [comment]
[This is](https://blogs.msdn.microsoft.com/windows_installer_team/2005/09/12/any-tips-on-getting-the-cancel-button-working-for-a-deferred-custom-action/) all that I have found. But I can not make out. Can you help me?

**Comment by Xaddan** [comment]
There is progress, I managed to get an exception when canceling the installation.

![image](https://user-images.githubusercontent.com/14925308/58243557-e5ab0180-7d61-11e9-9661-711f15081948.png)

**Comment by Xaddan** [comment]
Judging by the `Message` method, we won’t get anything except an `InstallCanceledException`.
```C#
public MessageResult Message(InstallMessage messageType, Record record)
{
    if (record == null)
    {
        throw new ArgumentNullException("record");
    }

    int ret = RemotableNativeMethods.MsiProcessMessage((int) this.Handle, (uint) messageType, (int) record.Handle);
    if (ret < 0)
    {
        throw new InstallerException();
    }
    else if (ret == (int) MessageResult.Cancel)
    {
        throw new InstallCanceledException();
    }
    return (MessageResult) ret;
}
```

**Comment by Xaddan** [comment]
Something like this.
```C#
public static class CustomActions
{
    [CustomAction]
    public static ActionResult MyAction(Session session)
    {
        while (true)
        {
            if (session.IsCancelled())
            {
                return ActionResult.UserExit;
            }
        }
    }

    public static bool IsCancelled(this Session session)
    {
        try
        {
            session.Message(InstallMessage.ActionData, new Record());
            return false;
        }
        catch
        {
            return true;
        }
    }
}
```

**Comment by Xaddan** [comment]
Only in this way an exception is written in the logs, which is not good.
```
Exception thrown by custom action:
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> Microsoft.Deployment.WindowsInstaller.InstallCanceledException: Выдано исключение типа "Microsoft.Deployment.WindowsInstaller.InstallCanceledException".
   в Microsoft.Deployment.WindowsInstaller.Session.Message(InstallMessage messageType, Record record)
   в CustomActions.MyAction(Session session) в C:\Users\mtimofeev\Documents\GitHub\wixsharp\Source\src\WixSharp.Samples\Wix# Samples\DTF (ManagedCA)\setup.cs:строка 57
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   в Microsoft.Deployment.WindowsInstaller.CustomActionProxy.InvokeCustomAction(Int32 sessionHandle, String entryPoint, IntPtr remotingDelegatePtr)
CustomAction MyAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 14:04:35: MyAction. Return value 3.
```

**Comment by oleg-shilo** [comment]
Sounds great. 
I don't see any problem with log having a `InstallCanceledException` message when user... well indeed canceled the installation :)

However if you prefer a clean exceptionless approach you can use an alternative extension method:

```C#
public static bool IsCancelledRaw(this Session session)
{
    // does not throw but will become broken if WiX team changes the implementation
    long ActionData = 0x09000000;
    var RemotableNativeMethods = typeof(Session).Assembly
                                        .GetTypes()
                                        .FirstOrDefault(x => x.Name == "RemotableNativeMethods");

    var MsiProcessMessage = RemotableNativeMethods.GetMethods(BindingFlags.Static | BindingFlags.NonPublic)
                                                  .FirstOrDefault(x => x.Name == "MsiProcessMessage");

    var ret = (int)MsiProcessMessage.Invoke(null, new object[]
                                            {
                                                (int)session.Handle,
                                                (uint)ActionData,
                                                (int)new Record().Handle
                                            });

    return (ret == (int)MessageResult.Cancel);
}
```

**Comment by oleg-shilo** [comment]
The next release will have both `Session.IsCanceled` and `Session.IsCanceledRaw` available
