### ISSUE TITLE
Feature checkbox can still be un-checked with allowChange=false

### ISSUE THREAD

**Issue by nicStrauss** [oleg-shilo/wixsharp#648]
Hi Oleg,

We recently changed our mature C++ project's installer to WixSharp managed MSI, after 20 using InstallShield. (..currently using version 1.9.8.0)

One of the features used are:
Feature background = new Feature("Background", true, false);

The feature controls registry entries for multiple instance transforms, so must always run, and may not be deselected.

I see similar behaviour as reported here [https://github.com/oleg-shilo/wixsharp/issues/108#ref-commit-d660e17](url) in that even though allowChange is false, you are still able to deselect it the feature tree, but with a few slight exceptions:
1. It can be deselected with a single click, and cannot be re-selected with single or double click.
2. If unselected it does not run (unlike reports above that it can)

Any suggestions?

Best regards,
Nic

**Comment by oleg-shilo** [comment]
Hi Nic,

I suggest you create your Visual Studio project form the CustomUI template.

![image](https://user-images.githubusercontent.com/16729806/58317098-72d08200-7e58-11e9-932d-4261ae2f5fba.png)

With this project type you will have the full source code of the "Feature Selection" dialog. And there you will be able to customize your enable+checked behavior without any limits.

**Comment by nicStrauss** [comment]
Thanks for the prompt reply, Oleg!

Will do that.
