### ISSUE TITLE
Question: How to add permisisons to regkey 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#649]
Hallo Oleg, i have currently problem with Permission in my msi installer.
There ist FilePermissions and also Dirpermissions, but i found nothing for regkey permission. 
I have to set permissions on some keys in HKLM to everyone, cause sometimes msi doesnt create regkeys or for majorupdate doesnt delete it.

my regkeys in managedproject from CustomUI Template looks following.
```C#
 new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\MyCompany\MyProduct", "InstallDir", "[INSTALLDIR]"),
                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\Mycompany\MyProduct", "Installdate", DateTime.Now.ToShortDateString()),
                new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\VMycompany\MyProduct", "Version", versionToInstalled.ToString());
```
How do i set Permissions on these regkeys ?

**Comment by Torchok19081986** [comment]
Hallo Oleg, i found following link from Wix itself. https://wixtoolset.org/documentation/manual/v3/xsd/wix/registrykey.html
How do i create something like that in Wix# ?

**Comment by oleg-shilo** [comment]
I changed this issue to "feature request" and will implement in the next release.

If you want to use it now you will need to use XML injection:
```C#
 project.WixSourceGenerated += document =>
        {
            document.Root.Select("Product/Package/<whatever your element path>")
                         .AddElement("Permission", "Read=yes; Write=no");
        };
```

**Comment by Torchok19081986** [comment]
many thanks, Oleg. I will wait for next release. 👍

**Comment by oleg-shilo** [comment]
I am reopening it. It is a feature request that is not fixed yet :)
