### ISSUE TITLE
Escaping "minus" `-` character in folder names

### ISSUE THREAD

**Issue by xplicit** [oleg-shilo/wixsharp#65]
I have folowing definition in `Setup.cs` file:

```csharp
Dirs = new[]
{
    new Dir(installPath, new Files(@"installer_files\*.*"))
},
```

installer_files contains directory with name `platform-tools`. When *.wxs is created I see, that this directory has another name: 

```xml
<Directory Id="INSTALLDIR.sdk.platform_tools" Name="platform_tools">
```

`-` char was replaced with `_` char. But I need that folder in install directory with its original name `platform-tools`. Is it possible to not change this char and place directory into install folder as is?

**Comment by oleg-shilo** [comment]
Please ensure that you are using the latest release. This issue has been addressed already: Release v1.4.3.0. Let me know if it is not in your case.

**Comment by xplicit** [comment]
I have package.config with "WixSharp" version="1.4.3.0"

In bin/Debug folder I see `WixSharp.dll` 
```
Date: 2017-04-23, 
Size: 303616, 
Assembly Name = WixSharp, version: 1.4.3.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2
```

**Comment by xplicit** [comment]
Just a note: files with `-` in filename are installed correctly

**Comment by oleg-shilo** [comment]
Can you please provide a simple "hello-world" style test case so I can have a look. My initial test by changing dirname to include dash reviled no problems. 
Thank you

**Comment by xplicit** [comment]
Sure, it's available here https://github.com/xplicit/WixDir

when it generates `setup.wxs` file it creates such xml:

```xml
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
        <Directory Id="ProgramFilesFolder.WixDirSample" Name="WixDirSample">
          <Directory Id="ProgramFilesFolder.WixDirSample.sdk" Name="sdk">
            <Directory Id="INSTALLDIR" Name="with_minus">

              <Component Id="Component.hello.txt" Guid="b0bcb9ab-9bf6-4b03-9179-35dc3056a674">
                <File Id="hello.txt" Source="install_files\sdk\with-minus\hello.txt" />
              </Component>

            </Directory>
          </Directory>
        </Directory>
      </Directory>
    </Directory>
``` 

```xml
         <Directory Id="INSTALLDIR" Name="with_minus">
```

**Comment by oleg-shilo** [comment]
Excellent. Txs. Will look at it first thing tomorrow.

**Comment by oleg-shilo** [comment]
OK. Thanks to your test project I found where the problem was. 

The latest codebase indeed does not suffer from this problem.  The code change for that functionality was committed 8 days ago. But I mistakenly thought that the change went to the latest release v1.4.3.0. My mistake. 

I have made a new release (v1.4.4.0) and now you can update your NuGet package ind it should work.

**Comment by xplicit** [comment]
Thanks, I checked and it's working now.
