### ISSUE TITLE
How to install several Msi at once

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#651]
Hi 

I have several wix# installer projects each producing an msi for the associated projects.
What is the best way to create another project that will run all the Msis one after the other.

Thanks

**Comment by oleg-shilo** [comment]
You need a bootstrapper. You can use either Burn or NSIS bootstrapper. The bootstrapper folder contains some samples that you may want to see. 

And of course there are generic non-MSI solutions:
- Choco
- Custom exe with the msi files embedded as resources
- Zip file with MSIs and a run batch
- . . .

**Comment by ltemimi** [comment]
Hi Oleg

Many thanks for your help while I was waiting for your answer I tried
```
 var bootstrapper =
                new Bundle("LogLogix",
                    new PackageGroupRef("NetFx40Web"),
                    new MsiPackage(windowsServiceInstaller) { DisplayInternalUI = true},
                    new MsiPackage(licenseWizardInstaller) { DisplayInternalUI = true })
                {
                    Version = new Version(version),
                    UpgradeCode = new Guid("{C7278B04-2933-4429-8858-3F9A382FF88E}")
                };
```
And it worked very well giving me most of what I need,
1 - The Msis are installed without prompting users to accept the license agreement
2 - I could not uninstall from control panel. The only way to uninstall is to click on the exe, run as admin then I could uninstall. 
3 - Is there a way of replacing the CD banner on the UI with my company artifact

would the NSIS bootstrapper solve my problems? how to I declare several msi packages at once using it?

I am using wisxsharp 1.9.3 is there any breaking changes on the updates?
Thanks

**Comment by oleg-shilo** [comment]
Yes you can customize UI. Both ManagedUI and Native:
```C#
project.BannerImage;            {
project.BackgroundImage;
```

And you have full control over any UI element of any dialog of ManagedUI. It's just a winform UI. Though ManagedUI will not be displayed from the bootstrapper due to the long standing WiX bug. NSIS does not exhibit this problem.

When it comes to the WiX bootstrapper itself I am not sure you can easily customize it. You will need to consult the documentation. But you can easily overwrite the whole UI. It is a very simple WPF application. Have a look at WixBootstrapper_UI sample.

**Comment by ltemimi** [comment]
Hi Oleg

Thanks for the help I have managed to customise my projects. but the bootstrapper customisation is limited. I will have a go at your other suggestions.

**Comment by oleg-shilo** [comment]
np. but keep in mind that even with the Wix/Burn bootstrapper, which indeed is not very customizable, you can still  do a fair bit of customization. Particularly when it comes for GUI. WixSharp samples contain the "Booststrapper_UI" sample that does just that.
