### ISSUE TITLE
Cannot use the 1.9.8 packages from NuGet

### ISSUE THREAD

**Issue by fschlaef** [oleg-shilo/wixsharp#654]
I installed version 1.9.8 of WixSharp on my machine, but I cannot upgrade the NuGet packages from 1.9.7 to 1.9.8 (`1.9.8-pre` on NuGet)

`Unable to resolve dependencies. 'WixSharp.bin 1.9.8-pre' is not compatible with 'WixSharp 1.9.8-pre constraint: WixSharp.bin (>= 1.9.8)'.`

I'm using Visual Studio 2019 on Windows 10

**Comment by oleg-shilo** [comment]
There is been a packaging problem with that pre-release. You should stick to the 1.9.7 until the problem is fixed.

**Comment by oleg-shilo** [comment]
Fixed starting from prerelease 1.9.8.1-pre
