### ISSUE TITLE
Question: How to make exe Autostart after windows login

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#655]
Hallo Oleg, i have a question an hope, you can help me with. I tried to add in registrykey one key for autostart. In Run or RunOnce , unfortunatlly, doesnt work for me. In autostart folder works. 
How to i install Shortcut or exe itself in shell:StartUp ?

**Comment by oleg-shilo** [comment]
You may try to install your shortcut in "_C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp_"

**Comment by Torchok19081986** [comment]
Many thanks, @oleg. I will try it . I dont know , but i think ProgrammData are only current user , i am correct ? I have to install it for all user on Machine. In Registry exists Key - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run, means for all users. How do i install exe shortcut for all users ?

**Comment by oleg-shilo** [comment]
No it is for all users.
CurrentUser: _C:\Users\<user_name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup_
AllUsers: _C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp_

**Comment by Xaddan** [comment]
What are the problems with adding a key to RunOnce? Show your code.
The key name can be arbitrary, the value must have the full path to the file being run, and may also contain the arguments to start the application.
For example:
```C#
new RegValue(Feature, RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce", "MyApp", @"C:\Program Files\My Company\My Product\MyApp.exe"),
```

**Comment by Torchok19081986** [comment]
Hallo @Xaddan. Thanks for sharing. I tried add it in registry for a sample, nothing was installed, but i think here i did some mistake. I set fullpath for .exe , but not added arguments for start and here is my problem. In startup copied shortcut of exe . Works really well. This bebahiour i dont understand. Do windows need installed programm for start exe from registrykey ? If yes, here is another mistake from me. in going to create some msi installer and check it.

**Comment by Xaddan** [comment]
Arguments are an optional parameter, you specify them only if you need them, I gave them as an example.

If you do not register anything along the path `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce`, then see if the entry goes to the 32-bit registry branch `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\RunOnce`

If this is the case, then set the parameter `Win64 = true`
``` C#
new RegValue (Feature, RegistryHive.LocalMachine, @ "SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce", "MyApp", @ "C:\Program Files\My Company\My Product\MyApp.exe \silent") { Win64 = true },
```

The full path for the .exe is of course not allowed.

You can specify the path to the file like this:
``` C#
[INSTALLDIR]\MyApp.exe
``` 
Or use the file Id to get the full path:
``` C#
private Id MyAppId = new Id ("File_MyApp_exe");
...
new File (MyAppId, feature, @ "AppFiles\MyApp.exe"),
...
new RegValue (Feature, RegistryHive.LocalMachine, @ "SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce", "MyApp", $@"[#{MyAppId}] \silent") { Win64 = true },
```
