### ISSUE TITLE
ExeFileShortcut changing folder name

### ISSUE THREAD

**Issue by fschlaef** [oleg-shilo/wixsharp#656]
Hello,

I am having an issue with `ExeFileShortcut` 

This code

```csharp
project.AddDir(new Dir(@"%ProgramMenu%\My Company",
      new ExeFileShortcut("My Product", "[INSTALL_DIR]\\MySystem\\MyProduct.exe", arguments: "")));
```

Generates this 

```xml
<Shortcut Id="ProgramMenuFolder.My_Company.My_Product" WorkingDirectory="ProgramMenuFolder.My_Company.My_Product.WorkDir" Target="[INSTALL_DIR]\MySystemFolder\MyProduct.exe" Name="My Product.lnk" />
```

`System` got renamed to `SystemFolder` and the link doesn't work.
I tried with `SystZem` and it works, but I cannot rename the actual folder.

I assume it has something to do with wix variables but I didn't enclose them in `%` so I'm at loss here.

I have no workaround

**Comment by oleg-shilo** [comment]
Thank you for reporting this problem. Unfortunately it is a defect and it will be fixed in the next release. For now please use this work around:
```C#
new Dir(@"%ProgramMenu%\My Company\My Product",
    new ExeFileShortcut("My Product", @"[INSTALL_DIR]\MySystem\MyProduct.exe", arguments: ""),
. . .                    
project.WixSourceFormated += Project_WixSourceFormated;
project.BuildMsi();

. . .

static void Project_WixSourceFormated(ref string content)
{
    content = content.Replace("MySystemFolder", "MySystem");
}
```

**Comment by fschlaef** [comment]
Confirmed working 👍
