### ISSUE TITLE
How to add external assembly to msi installer

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#659]
Hallo, i have one little problem to add external assembly to msi-installer and hoping someone has done it already or know solution.
i try to add "Microsoft.Win32.TaskScheduler.dll" for CA. This dll is third party dll and after search for wix sharp solution, i added follwing code in project description. 
 ```C#
 new ManagedAction("CreateTask")
                        {
                            ActionAssembly = "TaskSchedulerActions.dll",
                            RefAssemblies = new[]
                            {
                               "TaskSchedulerMethods.dll",
                               "Microsoft.Win32.TaskScheduler.dll"
                            }, 
                        }.
 ```
Both dll`s "TaskSchedulerActions.dll" and   "TaskSchedulerMethods.dll" could succesfully added to my project . Unfortunally, msi says in installation, FileLoadException  "Microsoft.Win32.TaskScheduler.dll" file or dependecies couldnt be found or in another try, for this installer requirement dll could be found. Please contact your installer distibutor.
in "TaskSchedulerActions.dll" i create 
 ```C#
[CustomAction]
 public static ActionResult CreateTask(Session session)
        {
            try
            {
                Methods.CreateTask(session["INSTALLDIR"] + "\\ServerUpdater.exe", "-silent", session["INSTALLDIR"].ToString());
                return ActionResult.Success;
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.ToString(), "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);

                return ActionResult.Failure;
            }
        }
```
and in   "TaskSchedulerMethods.dll" is method for create Task in Windows TaskScheduler. Library for this comes from github itself and could be seen in https://github.com/dahall/TaskScheduler/wiki/Examples

Can someone help me with or just say is it possible or not ?

**Comment by Torchok19081986** [comment]
After some research i found, that TaskScheduler.dll is present im TEMP, but msi seen doesnt do anything with dll. Do i need maybe dll resolve or something ? I tried like in WpfSetup - Example. But it doesnt seen to work. Added dll as Ressource and copy it in temp, until now works fine, but CA treid to create Task in Windows TaskScheduler, it comes to FileNotFoundException. Here i stuck.

**Comment by oleg-shilo** [comment]
You may want to resolve assembly by yourself via `AppDomain.Current.ResolveAssembly +=...`

In the event handler when CLR is asking you to resolve `TaskScheduler` assembly return it as follows:

```C#
return Assembly.Load(Resources.TaskScheduler_dll); // Resources.TaskScheduler_dll is a byte array 

```

**Comment by Torchok19081986** [comment]
Hi, @oleg-shilo. Thanks for info . That was my first approach. After many, many Tests, i resolve it with CA and stranger thing is happens, it works only if i start CA with data and paramter with execute.immediate. 
Dlls for external assembly seem in right way like in example loaded. Defered or in another way , doesnt work anytime. Currently works CA without any troubles.

**Comment by Xaddan** [comment]
This option works perfectly for me:
```C#
Project.DefaultRefAssemblies.Add("Microsoft.Win32.TaskScheduler.dll");
```
