### ISSUE TITLE
AllowSameVersionUpgrades not behaving as expected

### ISSUE THREAD

**Issue by fschlaef** [oleg-shilo/wixsharp#660]
Hello,

I am having an issue with `AllowSameVersionUpgrades` creating duplicates in Windows Installed Programs and ignoring existing products.

My `project.GUID` and `project.UpgradeCode` are fixed and never change between versions, but are set to different values.
I do not specify `project.ProductId`, I believe this generates a new one each time I create my installer.

The problem I have is the following :

- Generate an installer with version 1.0.0.1
- Install the product
- Re-generate the installer with the same version
- Launch the new installer

What I expect : the installation is prevented since the product is already installed.
What happens : the installation proceeds and a duplicate product is found in Windows.

I have found issues such as https://github.com/oleg-shilo/wixsharp/issues/492 but in those cases the `project.GUID` was being changed : this is not the case here. 

Both `AllowSameVersionUpgrades` and `AllowDowngrades` are set to `false`
I even tried `MajorUpgrade.Disallow = true` without success.

Am I missing something ? How do I prevent being able to reinstall the same version ?

Using Visual Studio 2019 and WixSharp 1.10.0

**Comment by fschlaef** [comment]
Point of interest : doing the same procedure but with version 1.0.0.0 produces an error message when running the 2nd installer, as expected.

I know that MSI doesn't take the 4th digit into account, but it doesn't matter here : I **want** to block install from say 1.0.0.2 to 1.0.0.3, but it seems there is something wrong somewhere.

So : 

1st installer -> 2nd installer (same GUID / UpgradeCode but different ProductId)
1.0.0.0 -> 1.0.0.0 : Error message (expected)
1.0.0.0 -> 1.0.0.1 : Nothing (bug)
1.0.0.1 -> 1.0.0.1 : Nothing (bug)

**Comment by fschlaef** [comment]
@oleg-shilo I assume this means we can't fix this ? 😢

**Comment by oleg-shilo** [comment]
Unfortunate yes, it cannot be fixed. The reason is that it is actually not a bug but a behavior by MSI design. Even though I really dislike this design. And it's not even WiX design but MSI only :(

**Comment by fschlaef** [comment]
@oleg-shilo Alright, no problem. I already warned the customer about this anyway 😃
