### ISSUE TITLE
Cant create new project from Template

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#665]
Hallo Oleg, i have problem to creaet new project from wixsharp template for Version 1.10.0.
I start visual studio 2019 and create new project with wix sharp managedui. 
After i got error "This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\WixSharp.bin.1.9.5.1\build\WixSharp.bin.targets" there is not 1.9.5.1. I n packge.config are references to
package id="WixSharp" version="1.10.0" targetFramework="net462" 
 package id="WixSharp.bin" version="1.10.0" targetFramework="net462" 
How do i solve this Problem ?

**Comment by Torchok19081986** [comment]
i found problem and solution for this problem. In new Template exists WixSharp.1.9.5.1.targets in  Metafiles. 
Dont know why, but after unload project and search for string from above and delete it. After load can new project start and compile without output error. Only Oleg can say why or how to avoid it.

**Comment by oleg-shilo** [comment]
To be honest the provided description (even though detailed) did not let me understand the problem.

And I have just tested it and had no problems with managedui template. 

Let's keep an eye on it...

**Comment by Torchok19081986** [comment]
Hallo Oleg, ok, i descripte my problem in another way. I create new probject in visual stduio 2019 from Managed Setup - Custom UI template. Works. After i try to create msi, just create new msi without anything change. I got error. 
I didnt manually add wixSharp to project, github extension say, it would be restore. after this i got always error in package.

**Comment by oleg-shilo** [comment]
This is what I did in my test:
1. New project from "Managed Setup - Custom UI template
2. Right-click solution item in the solution explorer and selected "Restore packages"
3. Accept license....
4. Build project. 
5. All OK

It looks to me like the restore operation did not work in your case.

**Comment by Torchok19081986** [comment]
hm. Ok. looks really github restore operation not works well. Need some investigation . Many thanks , Oleg, anyway.
