### ISSUE TITLE
Enable Verbose Logging

### ISSUE THREAD

**Issue by meister-d** [oleg-shilo/wixsharp#667]
I am trying to  enable Verbose Logging in my Project. 
As I use the MsiSession EnableLog Method I am missing the ability to set MsiInstallLogMode.Verbose.

On Pinvoke there seems to be an Implementation for Verbose Logging:

```C#
public enum INSTALLLOGMODE  // bit flags for use with MsiEnableLog and MsiSetExternalUI
        {
            INSTALLLOGMODE_FATALEXIT = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_FATALEXIT >> 24)),
            INSTALLLOGMODE_ERROR = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_ERROR >> 24)),
            INSTALLLOGMODE_WARNING = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_WARNING >> 24)),
            INSTALLLOGMODE_USER = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_USER >> 24)),
            INSTALLLOGMODE_INFO = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_INFO >> 24)),
            INSTALLLOGMODE_RESOLVESOURCE = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_RESOLVESOURCE >> 24)),
            INSTALLLOGMODE_OUTOFDISKSPACE = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_OUTOFDISKSPACE >> 24)),
            INSTALLLOGMODE_ACTIONSTART = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_ACTIONSTART >> 24)),
            INSTALLLOGMODE_ACTIONDATA = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_ACTIONDATA >> 24)),
            INSTALLLOGMODE_COMMONDATA = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_COMMONDATA >> 24)),
            INSTALLLOGMODE_PROPERTYDUMP = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_PROGRESS >> 24)), // log only
            INSTALLLOGMODE_VERBOSE = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_INITIALIZE >> 24)), // log only
            INSTALLLOGMODE_EXTRADEBUG = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_TERMINATE >> 24)), // log only
            INSTALLLOGMODE_LOGONLYONERROR = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_SHOWDIALOG >> 24)), // log only    
            INSTALLLOGMODE_PROGRESS = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_PROGRESS >> 24)), // external handler only
            INSTALLLOGMODE_INITIALIZE = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_INITIALIZE >> 24)), // external handler only
            INSTALLLOGMODE_TERMINATE = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_TERMINATE >> 24)), // external handler only
            INSTALLLOGMODE_SHOWDIALOG = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_SHOWDIALOG >> 24)), // external handler only
            INSTALLLOGMODE_FILESINUSE = (1 << (INSTALLMESSAGE.INSTALLMESSAGE_FILESINUSE >> 24)), // external handler only
        }
```

https://www.pinvoke.net/default.aspx/msi/MsiEnableLog.html

Would it be possible to Add this to your lib too? Or ist there anoter way to achive this type of logging?

Regards meister-d

**Comment by Xaddan** [comment]
```C#
new Property("MsiLogging", "vocewarmup")
```

**Comment by meister-d** [comment]
Hi Xaddan, thanx for the quick reply. If I see this correctly, the Property is set as WIX Property when building the msi. I want to be able to use the GenericSetup Class and install an already existing msi Package, which is  not authored by us. 

Regards meister-d

**Comment by oleg-shilo** [comment]
Yes @Xaddan was referring to the WiX property of the setup project that is built with WixSharp. If you want to control the logging of another msi being install you will need t do it via CLI args for the `msiexec /i the_other.msi`

**Comment by meister-d** [comment]
Hi Oleg, thax for the reply.  I used your WpfSetup Example as Ispiration for my own Wpf Application. 

There you Initialize the Setup to be installed like this:

`public MyProductSetup(string msiFile, bool enableLoging = true)
            : base(msiFile, enableLoging)
        {
            InitialCanInstall = CanInstall;
            InitialCanUnInstall = CanUnInstall;
            InitialCanRepair = CanRepair;

            SetupStarted += MyProductSetup_SetupStarted;

            //Uncomment if you want to see current action name changes. Otherwise it is too quick.
            //ProgressStepDelay = 50;
        }`

In my Application I trigger the Start Install like this:

`public void StartInstall(bool update = false)
        {
            var msiCMDLine = GetCommandLineArguments(update);
            var msiLogFile = MsiUtil.GetMsiLogFile(App.LogsDir, update, SetupType.Backend);

            EnableLog(LogFile = msiLogFile, MsiInstallLogMode.ExternalUI);
            StartInstall(msiCMDLine);
        }`

If i start an msi by commandline, I can enable logging by setting the /lv* flags.
In my oppinion It would be nice to have the opportunity to set something like :

`EnableLog(LogFile = msiLogFile, MsiInstallLogMode.Verbose);`

Perhaps it could be added in this way:

` public enum MsiInstallLogModeVerbose: Int32
    {
        None = 0,
        FatalExit = (1 << (Int32)(MsiInstallMessage.FatalExit >> 24)),
        Error = (1 << (Int32)(MsiInstallMessage.Error >> 24)),
        .....
        ShowDialog = (1 << (Int32)(MsiInstallMessage.ShowDialog >> 24)),
        Verbose = (1 << (Int32)(MsiInstallMessage.Initialize >> 24)), 
        ExtraDebug = (1 << (Int32)(MsiInstallMessage.Terminate >> 24)), 
        Initialize = (1 << (Int32)(MsiInstallMessage.Initialize >> 24)), 
        Terminate = (1 << (Int32)(MsiInstallMessage.Terminate >> 24)), 
        FilesInUser = (1 << (Int32)(MsiInstallMessage.FilesInUse >> 24)), 
        ExternalUI = FatalExit | Error | Warning | User | ActionStart | ActionData | CommonData | Progress | ShowDialog
    }`

Regards meister-d

**Comment by oleg-shilo** [comment]
OK, I see. 
Implementing extra constants is not a problem at all. 

It's not entirely clear to me hos logging mode logically connected to the names of the predefined constants. For example why  `ExtraDebug` and `Terminate` have the same value and yet their names suggest no relation. 

However I am happy to update the code with extra constants if you provide the full list of the values you want to define.
