### ISSUE TITLE
Question: project.AddDir

### ISSUE THREAD

**Issue by AwesomeM4rc** [oleg-shilo/wixsharp#668]
Hello,

I have a Problem with project.AddDir as you can see in the following example Code:

    class Program
    {
        static void Main()
        {
            var project = new Project()
            {
                Name = "my Product",

                Actions = new WixSharp.Action[]
                {
                    new ManagedAction(CustomActions.UpdateProperties, Return.check, When.Before, Step.InstallInitialize, Condition.Always),
                }
            };
            //This dosen't work as expected (A1)
            //project.AddDir(new Dir(new Id("TEST"), @"NOT_SET", new Dir("Test2"))); 
            
            //This works as expected (A2)
            //project.AddDir(new Dir(new Id("TEST"), @"NOT_SET")); 

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

            project.BuildMsi();
        }
    }

    public class CustomActions
    {
        [CustomAction]
        public static ActionResult UpdateProperties(Session session)
        {

            session["TEST"] = @"C:\Test";

            return ActionResult.Success;
        }
    }

The project.AddDir A1 creates a Folder named "NOT_SET" and a SubFolder "Test2". 

The project.AddDir A2 creates a Folder "Test" like it was defined in the Custom Action.

Can somebody tell me why A1 dosen't create a Folder named "Test" with a Subfolder "Test2"?

**Comment by Torchok19081986** [comment]
Hallo, i think it can be restriction of msi, because msi can craete at once only one folder on path at same time. Try to separate Test2 Dir from A1 und make it in CA. Had same issue. Solved it with CA and  propertie.

**Comment by AwesomeM4rc** [comment]
I tried it with a CA and it works for the installation but the uninstall doesn't delete the Test Folder anymore. 
Do you know a way to get this work automatically or do I have to write a new CA to remove the Folder when I uninstall the Program?

Also I need to add Files to the "Test" Folder and I guess I have to add them also with a CA? 

I found this Solution on Stackoverflow: https://stackoverflow.com/questions/38927190/i-would-like-to-set-a-features-directory-path-dynamically-using-wix 

I tried to do it like above just with the following code: 

`project.AddDir(new Dir(new Id("TEST"), @"NOT_SET", new WixSharp.File("example.txt")));`

But the Result is the same as before in A1.

**Comment by Torchok19081986** [comment]
In the samples of Wix Sharp in V. 1.10 exists sample with Installdir Dynamically Path.
There ist lines of code . Works for me. I had to set my path for installdir and files dynamically. On Uninstall works also correct.
´´´c#
 var project =
            new ManagedProject("MyProduct",
                new Dir(new Id("DIR1"), "root1", new File("setup.cs")),
                new Dir(new Id("DIR2"), "root2", new Files(@"files\*.*")));
    project.UI = WUI.WixUI_ProgressOnly;
        project.Load += Project_Load;

        project.BuildMsi();
    }

    static void Project_Load(SetupEventArgs e)
    {
        e.Session["DIR1"] = @"C:\My Company1";
        e.Session["DIR2"] = @"C:\My Company2";
    }
´´´

**Comment by AwesomeM4rc** [comment]
This actually solves my issue.

Thanks for the help!
