### ISSUE TITLE
Unable to uninstall a product installed using the generated Wixsharp MSI

### ISSUE THREAD

**Issue by ruhullahshah** [oleg-shilo/wixsharp#669]
## Problem:

While trying to uninstall a program, installed by a generated MSI, using Programs & Features, I only see Change and Repair as the available options. However, I can uninstall by right-clicking the generated MSI and clicking Uninstall.

How can I enable Uninstall in Programs and Features selection as well?

**Comment by oleg-shilo** [comment]
I just tested "Features"sample. Seems to not exhibit the problem you described:
![image](https://user-images.githubusercontent.com/16729806/61462174-8cec9380-a9b5-11e9-8a0e-c00b8f3bd6c6.png)

**Comment by ruhullahshah** [comment]
Hi Oleg

Thanks for confirming. It was a problem on my end. I do not have the exact root cause to share, but I cleaned up my registry and it seems to work. Also it maybe because of the way I was assigning the `ProductId`
