### ISSUE TITLE
Nuget Wix# (WixSharp) - Experimental features is out of date

### ISSUE THREAD

**Issue by dguder** [oleg-shilo/wixsharp#67]
The nuget package WixSharp.Lab 1.4.4. requires WixSharp.bin 1.4.4. But it contains still the WixSharp.Lab.dll 1.3.0 which holds a reference to WixSharp.dll 1.3.0. So using this fails when one want to open the WixForm within the designer. 
Since the nuget package was updated to 1.4.4 it looks like that the WixSharp.Lab.dll wasn't rebuilt after 1.3.0.

Since I couldn't find any build script system like [Cake build](http://cakebuild.net/) I can't provide a pull request. 
So far
Dominik

**Comment by oleg-shilo** [comment]
Txs, fixed now. 
NuGet has been updated and I also added to sources msbuild-based `build.cmd` 

Pull request wouldn't help much as the new binaries needed to be pushed to NuGet and GitHub releases but not to source. 

And I will have a look at Cake. Txs

**Comment by dguder** [comment]
Thx. BTW: Experimantal should be "Experimental" :) Sorry I saw this just now.

**Comment by oleg-shilo** [comment]
All done :)

**Comment by dguder** [comment]
Did you change this in nuget package as well?

**Comment by oleg-shilo** [comment]
Yes I have released the NuGet package as well. It is v1.4.4.1 
https://www.nuget.org/packages/WixSharp/

**Comment by dguder** [comment]
I mean the title of the Experimental nuget package?
["Wix# (WixSharp) - Experimantal features 1.4.4.1"](https://www.nuget.org/packages/WixSharp.Lab/) :)

**Comment by oleg-shilo** [comment]
Don't worry, the title from this issue is not there. :)

**Comment by oleg-shilo** [comment]
Oh, silly me. Yes there is nothing in the release notes but the title... :)
Fixed. Txs. Though the fix it's currently pending...
