### ISSUE TITLE
msi is always creating root folder, even if feature is disabled

### ISSUE THREAD

**Issue by kot-pilot** [oleg-shilo/wixsharp#670]
I have a project with code like:
```
var project = new ManagedProject(Constants.ProductName,
                 new Dir(new Id(Constants.WebSitePhysicalPathProperty), webSiteFeature, @"some_path_here",
                     new Files(webSiteFeature,@"someFilesPathHere\*.*"),
...
```
and everything works ok, but if i uncheck that 'webSiteFeature' it still creates empty root installation folder at 'some_path_here' .  But i need it not to create any folders if that feature is disabled. Can you pls advice me something.

**Comment by Torchok19081986** [comment]
Hallo, how do you set Feature checked in Featuretree ? In examples of wixsharp exists full project description how do it  in right way. AFAIK , you need to set it programatically after feature being enable or desabled. Only in that way, else try to check msi with orca or superorca for features and give messagebox at installationtime. 
Do some investigage work in examples of Oleg Wix#. Still exists folder with name "FeatureConditions".

**Comment by kot-pilot** [comment]
i use managed setup - custom dialog project template, and haven't changed featuresDialog in any ways, features parameter works ok for nested dirs, files and even sqlDatabase (i mean it doesn't create db is databaseFeature was unchecked and etc), but i still don't understand why it creates empty root folder

**Comment by Torchok19081986** [comment]
in featuredialog some lines of code : 
´´´csharp
 string itemsToInstall = features.Where(x => x.IsViewChecked())
                                        .Select(x => x.Name)
                                        .Join(",");
´´´
What is result of string ?

**Comment by kot-pilot** [comment]
if i don't check that feature it's not in string, if i check it it's in that string

**Comment by Torchok19081986** [comment]
it could be another restriction of msi. Features are optional, but dirs and files on top of project or installer would be always created on Target. I don know if it possible to avoid it. Sorry, i cant help you with . Only Oleg or Xadan .

**Comment by kot-pilot** [comment]
thx fo trying :)

**Comment by oleg-shilo** [comment]
This may help...

The code below works as expected. The `Docs` folder is not created if the corresponding feature is disabled:
```C#
var binaries = new Feature("MyApp Binaries", "Application binaries");
var docs = new Feature("MyApp Documentation");
binaries.Add(docs);

var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new File(binaries, @"Files\Bin\MyApp.exe"),
            new Dir(docs, "Docs",
                new File(docs, @"Files\Docs\Manual.txt"))));

project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
project.UI = WUI.WixUI_FeatureTree;

project.DefaultFeature = binaries; //this line is optional

project.PreserveTempFiles = true;

project.BuildMsi();
```

However if I change the code this way `Docs` will always be created:
```C#
. . .
new Dir(docs, @"Docs\Manuals",
. . .
``` 

This is because of the limitation of the WixSharp dir unfolding algorithm. I will see how this limitation can be addressed but until the fix is available you can address the problem by unfolding the dirs  manually:
```C#
. . .
new Dir(docs, "Docs", new Dir(docs, "Manuals",
. . .
```
