### ISSUE TITLE
Question: How to set custom errordiscription from CA

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#671]
Hallo Oleg, i have one problem and i dont know if it possible to solve. 

I create CA where i get some value from registry and value from session property belongs to new public property. works well and i would like to set custom errordiscription in CA.
Following code executed in CA
 ```csharp

 public static ActionResult GetExeVersion(Session session)
        {
           int compare;
           Version v = new Version(19,3,3,4300);         
           session["PROGRAMMDIR"] = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\WOW6432Node\app").GetValue("ProgramDir").ToString();
           var exepath = session["PROGRAMMDIR"] + "\\app.exe";
            FileVersionInfo info = FileVersionInfo.GetVersionInfo(exepath);                
            compare = info.FileVersion.CompareTo(v.ToString());
            if(compare == 0)
            {
                return ActionResult.Success;
            }

            else
            {
//Here i need to set Setupeventargs e or session for .Shell.ErrorDetected = true; 
// Add customdescription like "Software was not found or versions of installer are icompatible "
                return ActionResult.Failure;
            }
           
        }
  ```
Idea is if CA doesnt foudn value or value of exe not same cancel installation with custom description in Exitdialog.
Can you pls help me with or my problem is not solveable in msi ?

**Comment by oleg-shilo** [comment]
As far as I know you cannot customize stock ExitDialog. WiX/MSI is not customizable at that level.

However if you are using ManagedUI of WixSharp then you can do it this the same way way as in "MajorUpgrade" sample:
```C#
e.ManagedUI.Shell.CustomErrorDescription = "Setup was aborted, because Later version of the product is already installed.";
```

**Comment by Torchok19081986** [comment]
Hallo Oleg, i tried you suggestion and in after_install  event. Not working, I got each time error depend of what i set in CA for actionresult. If i would set to failure in exitdialog , i get error 1603 in log and in exitdialog in descriptionbox and so on for userexit etc.  I also tried it in project_afterinstall 
if not installed and shell.errors.any() e.ManagedUI.Shell.CustomErrorDescription = "my description".
unfortunatally  seems actionresult overwrite customdescrioption. Is any parameter i should set for created msi like overwrite error = true or something like that ?

**Comment by Torchok19081986** [comment]
Morning, Oleg. It seems threre is no way to set customdesc in exitdialogfrom CA. I tried to set in event before_install . In CA i gave always success return result. In before install i try to compare installed version of software (values comes from CA and registry save in Properties)
I got System.Reflection.TargetInvocationException with NullReferenceException. 
My CA´s return values and i tried to compare it with FileVersion class and custom version with values for major, minor, build, revisionsnummer. 
Compare result return -1 and here i stuck. Installer cancel setup with error. 
It looks like 
 ```csharp

int compare;
                int major = 19;      //major
                int minor = 4;       //minor
                int build = 0;       //build
                int revision = 4300; //revision
                Version v = new Version(major, minor, build, revision);

                if (!e.IsRepairing && !e.IsUninstalling)
                {                 
                    //string cobraexepfad = e.Session["EXEVERSION"];

                    FileVersionInfo info = FileVersionInfo.GetVersionInfo(e.Session["EXEVERSION"]);

                    compare = info.FileVersion.CompareTo(e.Session["COMPAREVERSION"]);

                    if (compare != 0)
                    {
                        e.ManagedUI.Shell.ErrorDetected = true;

                        e.ManagedUI.Shell.CustomErrorDescription = "Installation was canceled, because...
                            " ";
                        e.Result = ActionResult.UserExit;
                    }
                }
```
Can you help me with  or is compare for 2 versions are not possible in this way?

**Comment by oleg-shilo** [comment]
You better off doing opposite:

```C#
Version currentVesrion = new Version(FileVersionInfo.GetVersionInfo(e.Session["EXEVERSION"]).FileVersion);
Version expectedVersion = new Version("1.2.3.4");

if (currentVersion >= expectedVersion) 
{
    . . .
}
```

**Comment by Torchok19081986** [comment]
Many thanks, @oleg-shilo. Already tried it, without success.  What should i do if return true ? i tried allread all values in exitdialog appears error 1603. Localized to German File. Nothing anymore.

**Comment by Torchok19081986** [comment]
Morning Oleg, i found out where my problem appears. Seems like WixSharp.ManagedProject.UILoaded Eventhandler. this doesnt fire event on beforeinstall and it says "  This member is only populated when it is handled by the WixSharp.ManagedProject.UILoaded
 event handler. It has the default null value for all other events.". NullReferenceExeception. Would be explain my error and problem. How do i set setupeventargs e e.ManagedUI.Shell.ErrorDetected = true in before_install ?

**Comment by oleg-shilo** [comment]
Hi there, I cannot comment the error you are experiencing as the description provides no context. If you have problems with `WixSharp.ManagedProject.UILoaded` then I suggest you try it with the sample "ManagedSetup\Setup Events". See how it works and you will be able to to find the cause of your problem.

**Comment by Torchok19081986** [comment]
Ok, thanks Oleg again . Im going to try your suggestion. In my project it looks like Msi doesnt set or get reference to ManagedUI and here return Null. I also tried ManagedUICustomApproach. Seems also doesnt work.

**Comment by oleg-shilo** [comment]
You must use ManagedUI. Native UI does not invoke the handler:

![image](https://user-images.githubusercontent.com/16729806/61794068-c3b62400-ae63-11e9-866d-03b25b64c23a.png)

**Comment by Torchok19081986** [comment]
Ok,  Where i should set it in my project description ?

**Comment by Torchok19081986** [comment]
Morning Oleg, i tried your suggestion today with Setupevents Sample. Doesnt work also. As soon as i compare two versions: installed version against another version in before_install event and try to cancel it, error appears always. Whatever sample or projecttype i tried. Cancel of installation is not possible. Only if it error appears in msi. 
however I see it, whatever i tried , it looks like something impossible to do. maybe it not covered by wix toolset or wix# currently. Close issue , it is pointless do another big research. I gave up on this.
