### ISSUE TITLE
outdir and BuildMsiCmd fails because the outdir is not created

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#672]
I feel like I must be doing something stupid because this seems like an issue that surely other people would have already commented on...

Basically just create a new setup project with the visual studio templates, add a line for `project.outdir = "msi"` for example, and change the last line to `project.BuildMsiCmd()` instead of `project.BuildMsi()`.

You get an error that it can't find the generated wxs file, but it turns out it's because it silently failed to write the msi file, because the output path doesn't exist. (The silent failure is on line 1004 of compiler.cs).

Have a missed a line of documentation somewhere that this is expected?

Thanks as always for such an amazing tool.

**Comment by oleg-shilo** [comment]
Not sure what happens in your case. I tried it with `InstallFiles` sample and it builds OK:

![image](https://user-images.githubusercontent.com/16729806/61592310-f0c0c780-ac14-11e9-921b-a008d6328f9c.png)

**Comment by apawsey** [comment]
Sorry, I may not have been exactly clear... This only occurs if you use `project.BuildMsiCmd()`.  `project.BuildMsi()' works fine.

**Comment by oleg-shilo** [comment]
Sorry, you were actually were clear. :)
I just missed it...
Will check.

**Comment by oleg-shilo** [comment]
Indeed it was a problem. 
Fixed.
Will be available in the very next release.
