### ISSUE TITLE
Project.AllFiles is empty when specifiing files using *.* pattern.

### ISSUE THREAD

**Issue by ErikParso** [oleg-shilo/wixsharp#674]
I want to copy complete output with all nested files into program files. Following code works just fine.
```
var project = new Project("MyProduct",
    new Dir(@"%ProgramFiles%\My Company\My Product",
        new Files(@"Content\*.*")));
```
Now I want to register service. How do i access Content/Service/MyService File object ? Project.AllFiles is empty and Project.FindFile method does not work either.

**Comment by ErikParso** [comment]
I want to copy complete output with all nested files into program files. Following code works just fine.

```
var project = new Project("MyProduct",
    new Dir(@"%ProgramFiles%\My Company\My Product",
        new Files(@"Content\*.*")));
```

Now I want to register service. How do i access Content/Service/MyService File object ? Project.AllFiles is empty and Project.FindFile method does not work either.

**Comment by oleg-shilo** [comment]
Have a look at "WildCard Files" sample. It does exactly what you need. Most likely you haven't call `project.ResolveWildCards()` :

```c#
. . .
project.GUID = new Guid("{AC19C6E4-9724-4e90-8AC7-6E69B4AB7562}");

project.ResolveWildCards();

project.AllFiles
       .Where(file => file.Name.EndsWith(".dll"))
       .ForEach(file => file.Add(new NativeImage { Platform = NativeImagePlatform.x86 }));

var exeFile = project.AllFiles.Single(f => f.Name.EndsWith("some.exe"));
```

**Comment by ErikParso** [comment]
Project.ResolveWildCards was it. Thank you !
