### ISSUE TITLE
Question: Is there a way to change the size of the program in Add/Remove Programs?

### ISSUE THREAD

**Issue by AwesomeM4rc** [oleg-shilo/wixsharp#675]
Hello,

so I just saw that the size of my installed program has the wrong size in Add/Remove Programs. I guess this is because I extract some zip archives in the "Msi_AfterInstall" method that i added to the project before.

So my question is if there is a way to change the size in the Add/Remove Programs. I first thought I could do it with a Code like that: 

`project.ControlPanelInfo.EstimatedSize`

But actually there are only other useful options available like Manufacturer and so on. 

Any suggestions?

**Comment by GilesBathgate** [comment]
Looks like it should be possible if you add an ARPSIZE property:
https://docs.microsoft.com/en-us/windows/win32/msi/arpsize

project.AddProperty(new Property(new Id("ARPSIZE") ...`?

**Comment by AwesomeM4rc** [comment]
Thanks for the answer. 

I just tried it and unfortunately it dosen't seem to work like it should be. 

The value that I pass to the ARPSIZE property gets written into the Registry Key "Size" but not into the "EstimatedSize" Key. 

![grafik](https://user-images.githubusercontent.com/52924639/62865000-9398cd00-bd0d-11e9-93b8-6442214f7843.png)

I already did somehting to solve my Problem, it isn't a very nice solution but it works for me. 

I just added a File with the "missing" size that I needed and removed it inside the "AfterInstall" method. 

I used the command inside the link to create the file: https://stackoverflow.com/questions/982659/quickly-create-large-file-on-a-windows-system (if someone needs it).

**Comment by AwesomeM4rc** [comment]
I discovered some strange behavior while testing if I could get it work with other solutions.

I added the following code to the Msi_AfterInstall Method:

                var regKey =
                    Registry.LocalMachine.CreateSubKey($@"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{e.Session.Property("ProductCode")}");
                regKey?.SetValue("EstimatedSize", 100000);
                regKey?.Close();

And here is what I found out -> It looks like you can just add or deduct something from the "EstimatedSize" Value. (I guess the Windows Installer just adds his own value to the one that was created before)

For example if my "EstimatedSize" would normally be around like 300MB you can just do

                regKey?.SetValue("EstimatedSize", 100000);

to add 100 MB (Value would then be 400MB) or you can just do

                regKey?.SetValue("EstimatedSize", -100000);

to deduct 100MB (Value would then be 200MB) from the "EstimatedSize" Value

Maybe it helps somebody because it is a way to change the Size in both ways (increase and decrease).

But I don't think that both ways that I discovered are so called "good practices" but it seems like they are working.
