### ISSUE TITLE
Run application on startup.

### ISSUE THREAD

**Issue by ErikParso** [oleg-shilo/wixsharp#676]
Is there a way to register application to run on startup within installation process ?

**Comment by Torchok19081986** [comment]
Hallo , AFAIK there exists 2 methods. First one, create Registrykey in Run key in  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run or RunOnce, second create a shortcut in shell:startup Path. Place a shortcut for your exe. Only i attention, only for current windows user. 
for more info try : https://github.com/oleg-shilo/wixsharp/issues/655
best regards

**Comment by ErikParso** [comment]
Thank you, I used RegValue to register installed application as startup app. But there is problem with uninstalation. Content is not removed from installation folder.. I created a separated thread for this issue here https://github.com/oleg-shilo/wixsharp/issues/680.

**Comment by oleg-shilo** [comment]
This can be a side affect of the application running (and being locked) during the uninstallation.
