### ISSUE TITLE
Is it possible to associate files to installed program ?

### ISSUE THREAD

**Issue by ErikParso** [oleg-shilo/wixsharp#678]
Hello, I want to know.. Is it possible to associate files with specific extension to installed program within installation ? When user opens .xyz file, it opens application with path to this file in arguments. Something like "Open in program" setting.

**Comment by Torchok19081986** [comment]
Hallo, try https://github.com/oleg-shilo/wixsharp/issues/639. Open in Programm hast to be register by windows . Maybe you will need  to set some registry values.

**Comment by ErikParso** [comment]
Thanks i fount it. Following code works for me

    var client = project.FindFirstFile("Client.exe");
    client.Associations = new[] { new FileAssociation("xyz") };

**Comment by CADbloke** [comment]
I had to run `project.ResolveWildCards(ignoreEmptyDirectories: true);` before the above or I got a null refererence error.

Thanks!
