### ISSUE TITLE
Feature Order

### ISSUE THREAD

**Issue by Christobal25** [oleg-shilo/wixsharp#68]
Hey,

I would change the Order of the Features in the Setup, like its generated A-B-D-C, but I would have A-B-C-D.
So it´s possible to change the Order and when it is. How could I do this.

Thanks for your Help.

**Comment by oleg-shilo** [comment]
I actually couldn't find in MSI/WiX documentation any reference to ordering features in the features tree (if it is what you are referring to).  

Thus I can only suggest using ManagedUI (_Custom UI_ VS project template) and order the items in the Features dialog by yourself. Currently the feature tree is populated form the session Features collection in the same order as the the items are stored there.

**Comment by GilesBathgate** [comment]
@oleg-shilo It seems to be related to the order that the <Feature> xml elements appear in the file.

I've put an event handler on `Project.WixSourceSaved` and modified the file so for example:

```xml
<Product>
<Feature Name="B" />
<Feature Name="A" />
<Feature Name="C" />
</Product>
```
Will Yeild a different result to:
```xml
<Product>
<Feature Name="A" />
<Feature Name="B" />
<Feature Name="C" />
</Product>
```

**Comment by GilesBathgate** [comment]
The following hack fixes the issue:

```c#
static void Main()
{
     var feature1 = new Feature(...) { AttributesDefinition = "SortKey=A"};
     var feature2 = new Feature(...) { AttributesDefinition = "SortKey=B"};
     var feature2 = new Feature(...) { AttributesDefinition = "SortKey=B"};

    var project = new ManagedProject(...);
   project.WixSourceGenerated += FixFeatureOrder;
}

private static void FixFeatureOrder(XDocument document)
        {
            var order = new SortedDictionary<string, XElement>();

            var ns = XNamespace.Get("http://schemas.microsoft.com/wix/2006/wi");
            var features = document.Descendants(ns + "Feature");
            foreach (var feature in features)
            {
                var sortKey = feature.Attribute("SortKey");
                if (sortKey == null) continue;

                order.Add(sortKey.Value, feature);
                sortKey.Remove();
            }

            var product = document.Descendants(ns + "Product").First();
            foreach(var feature in order.Values)
            {
                feature.Remove();
                product.AddElement(feature);
            }

        }```
