### ISSUE TITLE
Folder not removed after uninstall.

### ISSUE THREAD

**Issue by ErikParso** [oleg-shilo/wixsharp#680]
Hello. I have a problem after unistalling, content is not removed from ProgramFiles. I found thread https://github.com/oleg-shilo/wixsharp/issues/123

Is it released already ? I see this thread is 2 years old and i have a same problem now. Here is my project definition.

    var project = new Project("MyProduct",
                      new Dir(@"%ProgramFiles%\My Company\My Product",
                        new Dir("Client", 
                            new Files(System.IO.Path.Combine(clientFiles, "*.*"))),
                        new Dir("Service",
                            new Files(System.IO.Path.Combine(serviceFiles, "*.*")))),
                      new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Run",
                        "AspWinServiceClient", @"[INSTALLDIR]Client\AspWinServiceClient.exe")
                      {
                          Win64 = true
                      })
    {
        Platform = Platform.x64,
        GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b"),
        Version = new Version("1.0.0.0"),                                                              
        MajorUpgradeStrategy = MajorUpgradeStrategy.Default,
    };

**Comment by oleg-shilo** [comment]
Can you try and see if `AutoElements.DisableAutoKeyPath = true;` helps.

**Comment by ErikParso** [comment]
No its not working

**Comment by oleg-shilo** [comment]
This can be a side affect of the application running (and being locked) during the uninstallation.

**Comment by oleg-shilo** [comment]
You will need to ensure the app is closed before the uninstall. MSI does not do it automatically. User has to do that

**Comment by oleg-shilo** [comment]
> Can you try and see if AutoElements.DisableAutoKeyPath = true...
>>No its not working

Good, it means that the fix is doing the required trick. It supposed to handle AutoKeyPath automatically...

**Comment by ErikParso** [comment]
I am sorry, I stopped and deleted service, closed client wpf application, but after uninstalation the files are still present in my Programfiles folder.

**Comment by ErikParso** [comment]
Here is complete project definition. I cannot find what is causing this problem.

var project = new Project("MyProduct",
                              new Dir(@"%ProgramFiles%\My Company\My Product",
                                new Dir("Client", 
                                    new Files(System.IO.Path.Combine(clientFiles, "*.*"))),
                                new Dir("Service",
                                    new Files(System.IO.Path.Combine(serviceFiles, "*.*")))),
                              new RegValue(RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Run",
                                "AspWinServiceClient", @"[INSTALLDIR]Client\AspWinServiceClient.exe")
                              {
                                  Win64 = true
                              })
            {
                Platform = Platform.x64,
                GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b"),
                Version = new Version("1.0.0.0"),                                                              
                MajorUpgradeStrategy = MajorUpgradeStrategy.Default,
            };

            project.RebootSupressing = RebootSupressing.ReallySuppress;
            project.ResolveWildCards();

            var service = project.FindFirstFile("AspWinService.exe");
            service.ServiceInstaller = new ServiceInstaller
            {
                Name = "AspWinService",
                StartOn = SvcEvent.Install_Wait,
                StopOn = SvcEvent.InstallUninstall_Wait,
                RemoveOn = SvcEvent.Uninstall_Wait,
                DelayedAutoStart = true,
                ServiceSid = ServiceSid.none,
                FirstFailureActionType = FailureActionType.restart,
                SecondFailureActionType = FailureActionType.restart,
                ThirdFailureActionType = FailureActionType.restart,
                RestartServiceDelayInSeconds = 30,
                ResetPeriodInDays = 1,
                PreShutdownDelay = 1000 * 60 * 3
            };

            var client = project.FindFirstFile("AspWinServiceClient.exe");
            client.Associations = new[] { new FileAssociation("heg") };

            project.BuildMsi();

**Comment by ErikParso** [comment]
I changed project name, guid and installation dir name and it seems to start workig as excepted. Installer removes files, stopps and deletes service, removes registry key even asks me if i want to close client application if running. I guess there is something messed in my system.

**Comment by oleg-shilo** [comment]
Then indeed the problem is not WixSharp related.

I suggest you have a look at the generated wxs. It's not necessarily easy but it may give you a clue. See if there is anything abnormal in the "upgrade" definition there.
