### ISSUE TITLE
Where is good documentation or tutorials? Question

### ISSUE THREAD

**Issue by Obaran** [oleg-shilo/wixsharp#681]
Hello

I am new with WixSharp, I don't know WixTools (only it is exist). I looked on WixSharp documentation and I am able to do very simple installer. But when I want to do something complicated, like External UI and implement "choose directory" I am lost.

I checked CustomUI\External_UI\Wpf sample and EmbeddedUI (both use Wpf if I am correct) and all are very different. In documentation is written "Embedded UI is nothing else but an external UI embedded into MSI so there is no need to distribute separately." that means, can I follow External_UI sample and then EmbeddedUI sample? I am confused, because both are different in code.

Whole documentation is written as for someone who master WixToolset. There is lot of text, but I didn't find some exampes or tutorials how to create own advanced installer. Are there any? Unfortunately, everything what I found is not more (nothing new), then documentation for WixSharp on this git-hub page.

**Comment by oleg-shilo** [comment]
Hi there, WixSharp documentation is indeed hosted on this GitHub project wiki.

You are right, it is unfortunate but WiX tool-chain is extremely and unnecessary complected. WixSharp is an attempt to change it and provide something that is more straightforward and works just out of box.

However the samples that you have chosen "ExternalUI" are not intended to provide a ready to go scaffolding for advanced EmbeddedUI. They are simply a few samples of implementing your own EmbeddedUI if you don't want to use the one provided by WixSharp. 

Saying that, if you are happy to go with WixShar all the way then you can use the whole implementation of EmbeddedUI for WinForms. It's called ManagedUI and is fully ready for you to be used either as is or be customized practically without any limits. 

The samples are: 
![image](https://user-images.githubusercontent.com/16729806/62025285-13f20500-b21b-11e9-9dc0-5868a74b3990.png)

But... despite the samples being available the recommended standard work is to use WixSharp Visual Studio project templates instead:

![image](https://user-images.githubusercontent.com/16729806/62025408-6fbc8e00-b21b-11e9-8dc7-a467e64aa67e.png)

This way you will have the all UI dialogs available in a source code just after the project creation so you can modify them any way you want:
![image](https://user-images.githubusercontent.com/16729806/62025504-b01c0c00-b21b-11e9-937b-efa5a58f0e6b.png)

**Comment by Obaran** [comment]
I apologize for late reply,
Thanks for answer, I tried some other Tools to compare SharpWix, for example IsWix, AdvancedInstaller (Free edition) and Windows Installer Projects Extension.
For now and simplicity I choode Windows Installer Projects Ext. It does everything what Wix or AdvandcedInstaller free and paid editions can do, except custom GUI. It is simple, just click and edit properties.
IsWix have zero documentation, therefore I don't waste much time with it, only tried his simple tutorial.
Unfortunately I don't have time to fully understand how WixSharp work therefore I go with W.I.Projects Extenstion and later I'll go back to WixSharp.
Btw. you can look at Advanced Installer documentation, it is not best but it is good reference how good documentation should looks.
