### ISSUE TITLE
Sending progress updates from Custom Action

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#682]
Hi,

I have a WPF based setup (managed UI around an msi file) which is basically working perfectly.  However I'm doing some manual database fiddling in one of our custom actions, and I wanted the UI to show some progress details.  So I had a look at some of the code behind the MsiSession object, which I saw can handle incoming messages, so I tried to work out how to send those messages in the correct format... and from some references and some very old examples, I got this...

```
        public static void SetupProgress(this Session session, string actionName, string actionDescription, int numTicksExpected)
        {
            //set the UI Status ACTIONSTART
            Record statusRecordObj = new Record(3);
            statusRecordObj.SetString(1, actionName);
            statusRecordObj.SetString(2, actionDescription);
            //below line defines a template for display on each message tick
            statusRecordObj.SetString(3, "[1]");
            session.Message(InstallMessage.ActionStart, statusRecordObj);

            //resets the progress bar.
            Record progressRecordObj = new Record(4);
            progressRecordObj.SetInteger(1, 0); //0 = reset bar
            progressRecordObj.SetInteger(2, numTicksExpected + 1);
            progressRecordObj.SetInteger(3, 0); //0 = left-to-right, 1= R-to-L
            progressRecordObj.SetInteger(4, 0); //0 = calc time remaining
            session.Message(InstallMessage.Progress, progressRecordObj);

            //tell the progress bar to increment for each ActionData message
            progressRecordObj.SetInteger(1, 1); //Action Info
            progressRecordObj.SetInteger(2, 1); //numTicks each ActionData
            progressRecordObj.SetInteger(3, 1); //increment bar for each ActionData
            session.Message(InstallMessage.Progress, progressRecordObj);
        }

        public static void TickProgress(this Session session, string message)
        {
            //The ActionData record follows the template defined in the msiMessageTypeActionStart
            //item #3. Refer to the MSI documentation related to templates. If you add more fields
            //to the template, make sure to add the additional fields here as well.
            Record progressObject = new Record(1);
            progressObject.SetString(1, message);
            session.Message(InstallMessage.ActionData, progressObject);
        }
```

However, I don't appear to be getting anything received in the UI... any thought or better examples?

This isn't exactly a big problem, so consider this low priority :)

**Comment by oleg-shilo** [comment]
Hi Adam,

Some advanced MSI messaging happening there :)

Sorry I don't have an answer. In case of WixSharp I only consume progress info, but do not set it up:
https://github.com/oleg-shilo/wixsharp/blob/6007f95ec3391969563da4ed4163ce5430cde814/Source/src/WixSharp.Samples/Wix%23%20Samples/Custom_UI/EmbeddedUI_WPF/InstallProgressCounter.cs#L85-L163

However what I noticed that you report a progress increment with `ActionInfo:1` message but it needs to be `ProgressReport:2`. You will find the matching case in the code above.
