### ISSUE TITLE
Slightly odd behaviour of User element

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#685]
Hi,

I'm trying to replicate similar behaviour to this post... [https://stackoverflow.com/questions/20583698/wix-conditionally-grant-log-on-as-a-service-right](WiX: Conditionally grant log on as a service right)

Following your user sample, I place the user object in the project root... but attached it to the server feature (I have a server and client feature), as this only matters when the server is installing.

How the output in the wxs file is a little odd... or at least it is from my understanding (which lets face it, when it comes to wix and msi, I'm basically in a constant state of confusion).

It puts the component under the client install directory, but references it from the server feature...
```
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
        <Directory Id="INSTALLDIR" Name="Product">
          <Directory Id="INSTALLDIR.Client" Name="Client">
          ...
            <Component Id="_ServiceAccountUsername_" Guid="5f9293d8-d2e2-42d6-b805-9096a86cae28" Condition="ServiceAccountUsername ~&lt;&gt; &quot;LocalSystem&quot; AND ServiceAccountUsername ~&lt;&gt; &quot;SYSTEM&quot; AND ServiceAccountUsername ~&lt;&gt; &quot;Network Service&quot;" KeyPath="yes">
              <util:User Id="_ServiceAccountUsername_" Name="[ServiceAccountUsername]" CreateUser="no" LogonAsService="yes" UpdateIfExists="yes" />

              <CreateFolder />
              <RemoveFolder Id="INSTALLDIR.Client" On="uninstall" />
            </Component>

         ... (close directory tags, bunch of other stuff)

      <Feature Id="Server" Title="Server" Absent="allow" Level="2" Description="The Server." Display="expand">
       <ComponentRef Id="_ServiceAccountUsername_" />
```

As I said, I assume to not have the correct understanding here, but this feels wonky.  Also I'm not sure why it has the CreateFolder/RemoveFolder tags there as well.

I'm assuming there's a better place to add it to the project tree to avoid this issue?

**Comment by apawsey** [comment]
Sorry, I hadn't realised, but this also generates an error as the condition is (I believe) supposed to be an element under the component, and not an attribute?

**Comment by oleg-shilo** [comment]
> CreateFolder/RemoveFolder...

It is done for supporting empty directories. This is one of the drastic measures thata I had to take to overcome an unbelievebly stubborn nature of MSI/WiX. Nature.

The solution is an extremely inelegant but ... I could only express my feelings about is belo: 

```C#
//'EMPTY DIRECTORY' support processing section
foreach (XElement item in componentsWithNoFiles)
{
    // Ridiculous MSI constraints:
    //  * you cannot install empty folders
    //    - workaround is to insert empty component with CreateFolder element
    //  * if Component+CreateFolder element is inserted the folder will not be removed on uninstall
    //    - workaround is to insert RemoveFolder element in to empty component as well
    //  * if Component+CreateFolder+RemoveFolder elements are placed in a dummy component to handle an empty folder
    //    any parent folder with no files/components will not be removed on uninstall.
    //    - workaround is to insert Component+Create+RemoveFolder elements in any parent folder with no files.
    //
    // OMG!!!! If it is not over-engineering I don't know what is.

```

Now you know how, I feel the same way as you do...

As for the error, what is your source code that generates the error?

**Comment by apawsey** [comment]
I can see why you have the "fun" logic above, but I'm still not understanding why it adds the user as an element under the Client directory, but links the component to the server feature?  Wouldn't that mean that if I install the server only, it would end up creating an empty client folder, which isn't really the end of the world, but just doesn't seem like it should be the case.

As for the source, the abbreviated part of the code regarding the user is as follows:

```
Project project = new Project("Product",
    new Dir(...,
       new DirFiles(...,
       (etc)
       )
    ),
    new User(serverFeature, $"[{Constants.ServiceAccountUsernameProperty}]")
        {
            CreateUser = false,
            UpdateIfExists = true,
            LogonAsService = true,
            ComponentCondition = $"{Constants.ServiceAccountUsernameProperty} ~<> \"LocalSystem\" AND {Constants.ServiceAccountUsernameProperty} ~<> \"SYSTEM\" AND {Constants.ServiceAccountUsernameProperty} ~<> \"Network Service\""
       }
    );
```

I'm not sure if that's enough code for you to decipher the issue.

That generates the wxs above, where the condition is added as an attribute on the component element.  However the error I get from Candle (while compiling) is...
`error CNDL0004 : The Component element contains an unexpected attribute 'Condition'.`

**Comment by oleg-shilo** [comment]
Will try. Txs

**Comment by oleg-shilo** [comment]
> I'm still not understanding why it adds the user as an element under the Client directory, but links the component to the server feature?

This is the very question that I was asking when I saw WiX implementation of user element support for the first time.  One must have it under a directory element. :rage2:

While the documentation states that `Component` is allowed under a [`Product` element](https://wixtoolset.org/documentation/manual/v3/xsd/wix/component.html) any attempt to compile such WiX code throws the error requiring to put the component under the directory element:
`: error CNDL0010 : The Component/@Directory attribute was not found; it is required.`

In your case since the user was placed in the `Project` WixSharp simply moves it int the first top-level directory. 

If you want to completely control placement directory selection you need to put the user directly in the desired parent:

```C#
var project = new Project("Product",
     new Dir(clientFeature, 
         new DirFiles(...)),
     new Dir(serverFeature, 
         new DirFiles(...),
         new User(serverFeature,...))
    . . .
    
```

**Comment by cocowalla** [comment]
@apawsey did you ever figure out how to add a condition to the `User`? I have the same requirement, where I want to conditionally grant the login as a service right, but am seeing the same error if I set a `ComponentCondition` on the `User`.
