### ISSUE TITLE
rollback actions sequencing problem

### ISSUE THREAD

**Issue by kot-pilot** [oleg-shilo/wixsharp#686]
i had  several ElevatedManagedAction which were created and run like that
action 'A' (when.after,step.installFiles)
action 'B' (when.after,step.previousAction)
action 'C' (when.after,step.previousAction)
and everything worked ok.
then i've added a rollback action for action 'B', and made it to fail everytime just to check that everything works as expected. And here i met a problem of wrong actions sequencing.
I expected it will work like : A -> B (it's returning fail) -> B_rollback  -> ...
how it works : A -> B_rollback -> C -> B ...
So looks like it sequences B_rollback action wrong and run's it like usual install action

**Comment by oleg-shilo** [comment]
Action sequencing is an architectural weak spot of MSI as a technology. MS had no other choice but to to make it the way it is was required by the fundamental concept of MSI: everything is declarative and there is no support for defining the complex algorithmic behavior.

WixSharp is an attempt to break away from these constrains and allow devs freely define the desired behavior in the high level language. Thus there is no need to have all those traditional Action1...ActionN chains. Instead yuo can have a single Action/event handler.

```C#
project.OnInstall += ...
```
And now your rollback will happen exactly as the action executed.

Hope it helps.

**Comment by kot-pilot** [comment]
I have Managed project and unfortunately  there  are no OnInstall event (or i can't find it).
Also i've seen that article about wix https://medium.com/@thehenrytsai/uninstall-vs-rollback-custom-action-in-wix-beed702d45c1 and that made me think that wix supports rollback for any count of custom actions (despite of it looks a little bit fuzzy)

**Comment by oleg-shilo** [comment]
Sorry, my bad. I wrote `OnInstall` from the memory. It is actually `BeforeInstall`. The all possible evans are listed below:

```C#
        project.UILoaded += project_UILoaded;
        project.UIInitialized += Project_UIInitialized;
        project.Load += project_Load;
        project.BeforeInstall += project_BeforeInstall;
        project.AfterInstall += project_AfterInstall;
```


> ...that made me think that wix supports rollback for any count of custom actions...

Probably it does. It's just not clear how to achieve that

**Comment by kot-pilot** [comment]
looks like i've figured out how to make it work. 
I had an ElevatedManagedAction and passed rollback action to constructor of that action and it hadn't worked like it supposed. Now i've created ElevatedManagedAction  for rollback action, made it run before actual action (like it was told it that wix article) and set Execute=Execute.rollback for rollback action via object initialization.

`  new ElevatedManagedAction(CustomActions.RollbackInstallWebSite, Return.check, When.After, Step.PreviousAction, Condition.NOT_Installed)
                   {                     
                       Execute=Execute.rollback
                   },
                 new ElevatedManagedAction(CustomActions.InstallWebSite, Return.check, When.After, Step.PreviousAction, Condition.NOT_Installed)`
