### ISSUE TITLE
Updating progress bar via CA 'deferred' Session.Message()

### ISSUE THREAD

**Issue by GameHackerPM** [oleg-shilo/wixsharp#69]
Hi. I have problem while trying to post a message to ProgressDialog Managed UI, sending is from an event which is created in CA (process output received event), which fires every time process receive new line.
Code: 
```
                ProcessStartInfo startInfo = new ProcessStartInfo();
                startInfo.FileName = @"Path of CMD";

                startInfo.UseShellExecute = false;
                startInfo.CreateNoWindow = true;
                startInfo.WindowStyle = ProcessWindowStyle.Hidden;
                Process proc = new Process();
                proc.StartInfo = startInfo;
                proc.StartInfo.RedirectStandardOutput = true;
                proc.OutputDataReceived += delegate (object sender, DataReceivedEventArgs e)
                {
                    if (count >= 250)
                    {
                        session.Message(InstallMessage.Progress, new Record
                        {
                            FormatString = "Progress:100"
                        });
                        return;
                    }
                    count++;
                    session.Message(InstallMessage.Progress, new Record
                    {
                        FormatString = "Progress:" + ((int)((count / Total) * 100)).ToString()
                    });
                };
                proc.Start();
                proc.BeginOutputReadLine();
                proc.WaitForExit();
```

Notice that: I tried to send it with InstallMessage.Progress / Warning / User / AppData, None of them received it. 
I already add the codes to check for any message that starts with "Progress:" in ManagedUI (ProcessMessage), but received nothing.
I'm trying to extract .zip file after installing.

If this is a wrong way to update progress bar with custom proposes, then how could it be done? 
P.S : 
`new ElevatedManagedAction(CustomActions.Extract, Return.ignore, When.Before, Step.InstallFinalize, Condition.NOT_BeingRemoved, Sequence.InstallExecuteSequence)`

Thanks.

**Comment by oleg-shilo** [comment]
You are using deferred CAs and they are running in a very different runtime context. Thus session object is completely disconnected from the actual installation. You may still call methods of the session object but without any warranty of the success. 

BTW you cannot even access ANY property of the session object from a deferred action. If you try you will get "Cannot access session details from a non-immediate custom action" exception.

Neither Wix# nor WiX cannot help you to overcome the "brilliance" of this architecture. Though Wix# helps you to access many vital session properties (e.g. INSTALLDIR) by preserving them in `CustomActionData` so one can access them via the extension method `Property`:
```C#
[CustomAction]
public static ActionResult InstallService(Session session)
{
    return session.HandleErrors(() =>
    {
        Tasks.InstallService(session.Property("INSTALLDIR") + "MyApp.exe", true);
    });
}
```
Thus you may need to use an alternative notification mechanism or may be make your action 'immediate' (if possible).
