### ISSUE TITLE
skip dialogs when upgrade 

### ISSUE THREAD

**Issue by kot-pilot** [oleg-shilo/wixsharp#691]
hi, can i somehow skip dialogs (like installprops) when upgrading, looks like i can't use session.IsUpgrading() is forms' code. Or maybe there is another approach for skipping InstallDialogs  when upgrade. Thx in advance.

**Comment by oleg-shilo** [comment]
> ... i can't use session.IsUpgrading() is forms' code ...

Not sure I follow this one. But you definitely can use complete "Custom UI" VS project template and modify the dialogs as you wish.
