### ISSUE TITLE
Minor upgrade question

### ISSUE THREAD

**Issue by kot-pilot** [oleg-shilo/wixsharp#693]
https://github.com/oleg-shilo/wixsharp/issues/517
maybe there are some new way to make msi use revision number to force upgrade? Cause i'd need to integrate installer to CI (which uses commit number as revision) and to run it for update servers (so 3rd number won't always be different, but 4th will cause it changes on every commit)

**Comment by oleg-shilo** [comment]
I am afraid it is the limitation of MSI that cannot be overcame. Though I cannot completely exclude that there is some exotic WiX work around that I just don't know.

**Comment by kot-pilot** [comment]
looks like i found the solution
https://stackoverflow.com/questions/500703/how-to-get-wix-to-update-a-previously-installed-version-of-a-program

> Add the MajorUpgrade element (from Wix 3.5.1315.0). To circumnavigate the catch that the MajorUpgrade will disregard changes in the revision number of the product version, add the AllowSameVersionUpgrades (or if you prefer AllowDowngrades) attribute. This way, you will be able to upgrade from e.g. 1.0.0.7 to 1.0.0.8. and not just from 1.0.7.0 to 1.0.8.0

**Comment by oleg-shilo** [comment]
But I assumed you have already tried the work around that your link describes. Have you?

This is how you do in in WixSharp:
```C#
project.MajorUpgrade = new MajorUpgrade
{
    AllowSameVersionUpgrades = true,
    AllowDowngrades = true,
    Schedule = UpgradeSchedule.afterInstallInitialize,
    DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
};
```

**Comment by kot-pilot** [comment]
yup, but looks like it didn't helped

**Comment by oleg-shilo** [comment]
Have a look at the emitted WXS. Does i have the required elements/attributes?

**Comment by kot-pilot** [comment]
looks like i've figured it out,   AllowSameVersionUpgrades = true, works, also my problem was that major update runs uninstall->install , and i were need some of those custom actions not to happen while update. I used this thread to achieve that https://stackoverflow.com/questions/34743856/how-to-prevent-database-drop-during-wix-major-upgrade

> If the issue is based on custom actions that run when the older product is being uninstalled, then you can use a custom action condition such as REMOVE="ALL" and not UPGRADINGPRODUCTCODE. UPGRADINGPRODUCTCODE is set in the older product as it is being uninstalled, not in the incoming upgrade.

> If there is something you need to do in the upgrading install that's custom action based, then WIX_UPGRADE_DETECTED will tell you that you are upgrading an installed product.
so i've got the new Condition("REMOVE=\"ALL\" and not UPGRADINGPRODUCTCODE") for uninstall actions which i don't wanna happen while update and new Condition("NOT Installed AND NOT WIX_UPGRADE_DETECTED") for install actions which i don't wanna happen while update

**Comment by oleg-shilo** [comment]
Great. And if you prefer you can evaluate the condition inside of the custom action. In fact I think it is a more readable than WiX _condition_:

```C#
void MyCustomAction(...)
{
    if (session.IsInstalling() && !session.IsUpgrading())
    {
        . . .
    }
}
```

**Comment by kot-pilot** [comment]
thank you :) also i there a way i can evaluate these in win forms code using Runtime.Session object?

**Comment by oleg-shilo** [comment]
Of course:
```C#
    if (Runtime.IsInstalling() && !Runtime.IsUpgrading())
    {
        . . .
    }
```

**Comment by kot-pilot** [comment]
thank you :)

**Comment by kot-pilot** [comment]
> if (this.MsiRuntime.Session.IsInstalling() && !this.MsiRuntime.Session.IsUpgrading())
> {
>     . . .
> }
> ```

unfortunately visual studio says  "ISession doesn't contain a definition for IsUpgrading"

**Comment by oleg-shilo** [comment]
Sorry, my bad. It needs to use `MsiSession`:
```C#
if (this.MsiRuntime.MsiSession.IsInstalling() && !this.MsiRuntime.MsiSession.IsUpgrading())
{
}
```

**Comment by kot-pilot** [comment]
Looks like using this.MsiRuntime.MsiSession.IsUpgrading() is getting wrong value, because upgrading code is set after uninstall phase, and looks like AppSearch.GetProductVersionFromUpgradeCode is the answer :)  (it was said in annotation to  IsUpgrading method)

**Comment by oleg-shilo** [comment]
:) Checked the XML doc comments and indeed the info is all there:

> Gets a value indicating whether the product is being upgraded. 
This method will fail to retrieve the correct value if called from the deferred custom action and the session propertiesthat it depends on are not preserved with 'UsesProperties' or 'DefaultUsesProperties'. 
This method relies on "UPGRADINGPRODUCTCODE" property, which is not set by MSI until previous version is uninstalled. Thus it may not be themost practical way of detecting upgrades. Use AppSearch.GetProductVersionFromUpgradeCode as a more reliable alternative.

**Comment by mihailovdumitru** [comment]
@oleg-shilo , so what what will be the solution to see if we are installing or uninstalling in this case?

**Comment by oleg-shilo** [comment]
It is `AppSearch.GetProductVersionFromUpgradeCode`. Exactly as the method XML doc suggests :)
