### ISSUE TITLE
Question: What is your release schedule.

### ISSUE THREAD

**Issue by GilesBathgate** [oleg-shilo/wixsharp#700]
@oleg-shilo Hi, just wondering how frequently you make releases of Wix#. It would be really good to get a release with some of the recent fixes/patches we need. We could take the source code version, but its easier to integrate into our build system if its on nuget. Thanks, Giles.

**Comment by oleg-shilo** [comment]
> It would be really good to get a release with some of the recent fixes/patches we need. 

Of course. I normally aim for a monthly release cycle during active development and even more frequent "hot fix" releases to deliver some urgent changes. 

To put it simple... I release as soon as I have something to deliver to Wix# users.

And... I am making the release right now.
