### ISSUE TITLE
Question: How to delete custom created Items

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#703]
Hallo Oleg, i have some problem with CA created items. Those Items was created as from third party dll in CA. In example DTF(Managed CA)--> Diffirent Scenaris --> External Assembyly, how to add 3. party dll to installer. Works really well. Now i have to delete all those items if my programm being removed, not upgraded/updated. Unfortunally, for uninstall it doesnt remove beforecreated items. Do i need to create own CA for those or how do i make msiinstaller delete items, which comes from third party dlls`s,  if my programm being uninstalled ? Code for CreateTask looks following:
```csharp
 new ElevatedManagedAction("CreateTask")
                        {
                            ActionAssembly = Application.StartupPath + "\\TaskSchedulerActions.dll",
                            RefAssemblies = new[] { Application.StartupPath + "\\TaskSchedulerMethods.dll", Application.StartupPath + "\\Microsoft.Win32.TaskScheduler.dll"},
                            Execute = Execute.immediate
                        },
```

**Comment by oleg-shilo** [comment]
you can create a managed CA that is executed on both install and uninstall an then simply check inside of the CA  is `session.IsUninstalling`  or `!session.IsUninstalling`. And teh either add or remove your custom items.

**Comment by Torchok19081986** [comment]
Hallo Oleg, many thanks for answer. And how do i make a CA, if CA depend on third party dlls ? Some sample or it works like in your sample of thrid party dll in msi installer ?

**Comment by oleg-shilo** [comment]
> ...thrid party dll ..

Exactly. It is the sample I would refer you to.

**Comment by Torchok19081986** [comment]
Ok, many thanks Oleg again. close the question.
