### ISSUE TITLE
Question: Localized progress action messages.

### ISSUE THREAD

**Issue by GilesBathgate** [oleg-shilo/wixsharp#704]
In the legacy wix based installer we used the following in our .wxl file:

```xml
  <String Id="ProgressTextInstallValidate" Overridable="yes">Validating install</String>
  <String Id="ProgressTextInstallFiles" Overridable="yes">Copying new files</String>
  <String Id="ProgressTextInstallFilesTemplate" Overridable="yes">File: [1],  Directory: [9],  Size: [6]</String>
...
```

Despite adding this to the wixsharp project, the action messages don't seem to be translated. `project.LocalizationFile = "en-us.wxl";`

 Is it still possible to use this mechanisim?

**Comment by GilesBathgate** [comment]
We just had to update ProgressDialog.ProcessMessage to do:
```c#
 //messageRecord[0] - is reserved for FormatString value
 var message = messageRecord[2].ToString();

if (message.IsNotEmpty())
    CurrentAction.Text = message;
```

**Comment by GilesBathgate** [comment]
Resolved using the above.

**Comment by GilesBathgate** [comment]
It would appear that:
 
- messageRecord[0] - is reserved for FormatString value
- messageRecord[1] - contains the untranslated id
- messageRecord[2] - contains the message as translated in the wxl file.

**Comment by oleg-shilo** [comment]
Wow, very unusual convention.

Interesting how it handles the case when there are two formatting args:

    messageRecord[0] - is reserved for FormatString value
    messageRecord[1] - raw text arg1
    messageRecord[2] - translated text arg1
    messageRecord[3] - raw text arg2
    messageRecord[4] - translated text arg2

or 

    messageRecord[0] - is reserved for FormatString value
    messageRecord[1] - raw text arg1
    messageRecord[2] - raw text arg2
    messageRecord[3] - translated text arg1
    messageRecord[4] - translated text arg2

**Comment by oleg-shilo** [comment]
It's really strange but it seems like `messageRecird[2]` unconditionally contains the string to display

```
messageRecord[0]    "Action 23:14:50: [1]. [2]" 
messageRecord[1]    "InstallFiles"  
messageRecord[2]    "Copying new files" 
messageRecord[3]    "File: [1],  Directory: [9],  Size: [6]"    
or 
messageRecord[0]    "Action 23:15:21: [1]. [2]" 
messageRecord[1]    "RegisterUser"  
messageRecord[2]    "Registering user"  
messageRecord[3]    "[1]"   
```

Meaning that your work around is exactly the fix that is needed.

Reopening this issue...

**Comment by GilesBathgate** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textboxbase.appendtext

**Comment by oleg-shilo** [comment]
Can you elaborate?

**Comment by GilesBathgate** [comment]
Please ignore. For some reason, I thought the default UI had a textbox where you print out messages like a console.

**Comment by GilesBathgate** [comment]
Is it the case that the values in the format strings are the indexes of the records to replace them with e.g:

```
messageRecord[0]    "Action 23:15:21: [1]. [2]" 
messageRecord[1]    "RegisterUser"  
messageRecord[2]    "Registering user"  
messageRecord[3]    "[1]" 
```

becomes:
```
messageRecord[0]  =>  "Action 23:15:21: RegisterUser. Registering use" 
messageRecord[3]   =>  "RegisterUser"
```

**Comment by oleg-shilo** [comment]
I also thought about that:
https://github.com/oleg-shilo/wixsharp/blob/9b752b76cd8d77ad0934a394e0f836b1781a9c86/Source/src/WixSharp.UI/ManagedUI/Forms/ProgressDialog.cs#L126-L133

But it was a bit weird to display formatted rec[0] in on the dialog. So I opted to rec[2].

**Comment by GilesBathgate** [comment]
Yes I was thinking rather for the description message in the new MessageDialog feature #692
