### ISSUE TITLE
Question: Accessing properties from within ManagedUI

### ISSUE THREAD

**Issue by GilesBathgate** [oleg-shilo/wixsharp#707]
Suppose I start the msi using the following:
```cmd
msiexec /i MyProduct.msi myproperty=true
```
I have a property in the project:
```c#
project.AddProperty(
    new Property("myproperty","false"));
```
From the managed UI i cannot read this property:
```c#
var value = Runtime.Session["myproperty"];
```

**Comment by oleg-shilo** [comment]
You should be able to do that.
The problem may be different. All properties that are to be passed from outside must be declared as _public_. In MSI world it means the property name must be a  in capital case.

**Comment by GilesBathgate** [comment]
Thanks this worked.

**Comment by oleg-shilo** [comment]
I know, it's hard to believe but yes this is the sophisticated technique MSI team opted to use to manage the visibility of the runtime model. 

![image](https://user-images.githubusercontent.com/16729806/63210180-76f5fe00-c12e-11e9-8f8f-14dae330444a.png)

**Comment by GilesBathgate** [comment]
I've proposed an additional class to help clear up this confusion in future: #709

**Comment by GilesBathgate** [comment]
@oleg-shilo Can you think of any reason why the value wouldn't be accessible when the MaintanceTypeDialog is shown?

**Comment by GilesBathgate** [comment]
The problem seems to be resolved by specifying the property with "Secure"

```c#
project.AddProperty(
    new Property("MYPROPERTY","false") { Secure = true } );
```
