### ISSUE TITLE
Can`t build Wix# Samples\Shortcuts

### ISSUE THREAD

**Issue by spurd0** [oleg-shilo/wixsharp#71]
Hi, i can\`t build code that uses shortcuts. I got latest version of wix# and ran [Build.cmd](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Shortcuts/Build.cmd) and got 

```
C# Script execution engine. Version 3.12.2.0.
Copyright (C) 2004-2016 Oleg Shilo.

Sequence contains more than one matching element
```

**Comment by oleg-shilo** [comment]
Sorry, didn't realize I did not post the response. It's fixed two weeks ago and now waiting for the release.
