### ISSUE TITLE
Question: how to skip RegValue error during installation?

### ISSUE THREAD

**Issue by xplicit** [oleg-shilo/wixsharp#710]
I have project description
```
            var project = new ManagedProject
            {
               ......,
                RegValues = new[]
                {
                    new RegValue (RegistryHive.ClassesRoot, @"myproject\mykey", "", "myvalue")
                }
           }
```

When resulting MSI is installing on some user machines the error can be raised. 

```
Error 1406. Could not write value to key \Software\Classes\... . System error . Verify that you have sufficient access to that key, or contact your support personnel. 
```
I want to make that install of MSI will be always successful even if key is not added to registry.  
Is it possible to skip registry error during installation with such project definition? Or I should write custom action manually which adds registry keys?

**Comment by oleg-shilo** [comment]
It looks like you are out of luck:
![image](https://user-images.githubusercontent.com/16729806/63392104-9758dd80-c3f8-11e9-8177-6a6671455098.png)

**Comment by xplicit** [comment]
Thanks for the answer, I put a link to original SO question here.

https://stackoverflow.com/questions/48258343/wix-tools-ignore-regitry-fail-and-continue
