### ISSUE TITLE
Major Upgrade Product Code doesn't change

### ISSUE THREAD

**Issue by DrGierth** [oleg-shilo/wixsharp#711]
Hello Oleg,

I'm wondering that the ProductCode viewed with Orca is not changing in my installer which I have done according to the MajorUpgrade Samples. As I understood it from your MajorUpgrade Samples I only change the product version ( in my case f.i 7.0.15.0 to 7.0.16.0 ) and the files. As far as I know MSI needs to have different ProductCode and differend ProductVersion for a major upgrade. In my installers ProductCode and UpgradeCode stay the same for every new version. What is my lack of understanding?

Thanks in advance for your effort.

Regards

Michael

**Comment by oleg-shilo** [comment]
I just have tested `MajorUpgrade1` sample. 

Build it once and then build again with incremented the version.  Seems to produce the expected output. The same upgrade code and different product code. 

Though I have to admit that it is quite difficult to spot the difference:

```
 ProductId  : {6f330b47-2577-43ad-9095-1861ca31-d-fd4}
 ProductId  : {6f330b47-2577-43ad-9095-1861ca31-e-fd4}
```

![image](https://user-images.githubusercontent.com/16729806/63438756-35d45580-c470-11e9-81f3-6512ad88a5f2.png)

![image](https://user-images.githubusercontent.com/16729806/63438771-3d93fa00-c470-11e9-91af-9b5d3ed70dd1.png)

**Comment by DrGierth** [comment]
Hi Oleg,

your absolutely right. I didn't recognise that the change was only in the 4th digit, sorry.

Again thanks für your efforts 

Michael
