### ISSUE TITLE
Incorrect fonts when building on Windows Server Core

### ISSUE THREAD

**Issue by Mark-Dunning** [oleg-shilo/wixsharp#714]
We've recently switched some build servers to Windows Server Core and this has switched all of the fonts used in 'CustomUI' installers to 'Lucida Console' (which doesn't look particularly good). Note that we aren't using any custom fonts - just the default of "Tahoma".

![image](https://user-images.githubusercontent.com/25913212/63988346-e5c05780-cb2f-11e9-8426-f76cc2e0c59a.png)

What seems to be happening is that Wix# replaces the configured font with an installed font if the configured font is not available at build time. As Server Core only has Lucida Console installed, that is what it always ends up using.

As a temporary workaround we're using the 'WixSourceGenerated' event to patch the generated XML to reset the font to 'Tahoma'.

**Comment by oleg-shilo** [comment]
Thank you for reporting this. Can you please share your WixSourceGenerated' event to patching solution so I can investigate it?

**Comment by Mark-Dunning** [comment]
Sure, this is what I have at the moment:

    project.WixSourceGenerated += document =>
    {
        if (project.CustomUI == null)
            return;

        var textStyleName = XName.Get("TextStyle", "http://schemas.microsoft.com/wix/2006/wi");
        foreach (var textStyle in document.Descendants(textStyleName))
        {
            var textStyleId = textStyle.Attribute("Id").Value;
            if (project.CustomUI.TextStyles.TryGetValue(textStyleId, out var font))
                textStyle.SetAttribute("FaceName", font.OriginalFontName);
        }
    };

The general idea is to use the 'OriginalFontName' of the System.Drawing.Font rather than the translated font name.

**Comment by oleg-shilo** [comment]
Thank you for the code snippet. 
It's an excellent pick, which is very difficult to spot/predict. 

Fixed. Will be available in the next release.

A small improvement to your work around... You can use `FindAll` extension method so you don't need to deal with namespaces:

```C#
if (project.CustomUI == null)
    return;

foreach (var textStyle in document.FindAll("TextStyle"))
{
    . . . 
```

**Comment by Mark-Dunning** [comment]
Thanks very much. And for the tip about `FindAll`.
