### ISSUE TITLE
question about component ids generating

### ISSUE THREAD

**Issue by kot-pilot** [oleg-shilo/wixsharp#715]
As i understand wixsharp is using UpgradeCode + version info to generate productId and all components ids. Is there any method in wix sharp, which i can use to recalculate all these ids programmatically. Like if i have a ready to use wix source and using some method which takes upgradeCode and boom it recalculates all ids stuff. Thx in advance.

**Comment by oleg-shilo** [comment]
Sorry I did no respond in time. 
No direct method for that but you probably can make some use of:

```
internal void ResetWixGuidStartValue()
{
    WixGuid.ConsistentGenerationStartValue = this.ProductId ?? this.GUID ?? Guid.NewGuid();
}
public static Guid CalculateProductId(Guid productGuid, Version version)
{
    return WixGuid.HashGuidByInteger(productGuid, version.GetHashCode() + 1);
}

public void GenerateProductGuids()
{
    if (!GUID.HasValue)
        GUID = Guid.NewGuid();

    if (!UpgradeCode.HasValue)
        UpgradeCode = GUID;

    if (!ProductId.HasValue)
        ProductId = CalculateProductId(guid.Value, Version);
}
```

**Comment by kot-pilot** [comment]
thank you, could you maybe also show me method where are the component guids generated

**Comment by oleg-shilo** [comment]
Component IDs are not generated but derived from the child id (e.g. File, Directory):
```C#
        internal string GenerateComponentId(Project project, string suffix = "")
        {
            return this.GetExplicitComponentId() ??
                   project.ComponentId($"Component.{this.Id}{suffix}");
        }

        internal string GetExplicitComponentId()
        {
            var attrs = this.AttributesDefinition.ToDictionary();
            if (attrs.ContainsKey("Component:Id"))
                return attrs["Component:Id"];
            else
                return null;
        }
```
And the child element id is generated with the default built-in algorithm unless user-defined algorithm is available with `Compiler.AutoGeneration.CustomIdAlgorithm`:
```C#
// WixEntity class
public string Id
{
    get
    {
        if (id.IsEmpty())
        {
            id = Compiler.AutoGeneration.CustomIdAlgorithm?.Invoke(this) ?? IncrementalIdFor(this);
        }
        return id;
    }
    . . .
```

Have a look at _Custom_IDs_ sample.

----------

And if you want to control CompId 100% precisely you can always supply it directly from the setup definition:
```C#
new File("myAssembly.dll") { ComponentId = "asmComp" })
```
