### ISSUE TITLE
error CNDL0052 : The 'Dialog' dialog element does not have a valid tabbable control

### ISSUE THREAD

**Issue by LatteAno** [oleg-shilo/wixsharp#717]
I'm trying to accomplish something that's almost identical to this:

![image](https://user-images.githubusercontent.com/23175357/64921717-41950c80-d7cf-11e9-957f-32362764ea23.png)

From [this article](https://www.codeproject.com/Articles/804584/Wixsharp-WixSharp-UI-Extensions).

Need to allow users to select the product they want to install, using radio buttons, and install accordingly (no need for the license/activation part at the moment).

I'm getting the following error:
`error CNDL0052 : The 'Dialog' dialog element does not have a valid tabbable control. You must either have a tabbable control that is not marked TabSkip='yes', or you must mark a control TabSkip='no'. If you have a page with no tabbable controls (a progress page, for example), you might want to set the first Text control to be TabSkip='no'.`

I tried adding all kind of controls and also, adding `this.WixAttributes = "TabSkip=no";`, with no success...

Here is the form's code:

```
using WixSharp.Controls;

namespace Installer.Forms
{
	public class ModesWixForm : WixForm
	{

		private void InitializeComponent()
		{
			this.SuspendLayout();
			// 
			// ModesWixForm
			// 
			this.ClientSize = new System.Drawing.Size(284, 261);
			this.Name = "ModesWixForm";
			this.Text = "Test...";
			this.ResumeLayout(false);

		}
	}
}
```

This is how this dialog is used:
```
		private static CustomUI CreateWixFormUI()
		{
			var modesDialog = new ModesWixForm();
			
			Dialog dialogDefinition = modesDialog.ToWDialog();
			dialogDefinition.Title = "Zzz"; // why is this necessary? can't it take it from 
			CustomUI theUI = CustomUIBuilder.BuildPostLicenseDialogUI(dialogDefinition);
			
			return theUI;
		}
```

**Comment by oleg-shilo** [comment]
The article may be describing sample applicable to the older version of WixSharp. 
I suggest you take a look at the current WixSharp version sample [CustomMSIDialog](https://github.com/oleg-shilo/wixsharp/tree/67c57624b5bc3db389f35ee6dd540da33070409d/Source/src/WixSharp.Samples/Wix%23%20Samples/Custom_UI/CustomMSIDialog). I just tested it and it does build the requiered MSI.

Don't forget to add "WixSharp.Lab" nuget package. 

=============

Though if you as me I will always prefer to build UI with the language/framework that is actually suitable for the UI development (e.g. C# and WinForms).  Sorry but IMHO WiX is not :)

And while WixSharp eases the pain of dealing with MSI native UI it does fully eliminates it. But is on the other hand it does great job by integrating managed UI into MSI UI sequence by using MSI external UI technique called "Embedded UI".  

If you create a project based on any of the highlighted VS project templates you will be able to do UI development traditional .NET way:

![image](https://user-images.githubusercontent.com/16729806/64923694-babc5000-d81f-11e9-9276-1ea6bde8e060.png)

**Comment by LatteAno** [comment]
Thanks @oleg-shilo ! as expected, the samples you provided build and run nicely. I'm trying to incorporate these capabilities in our project now.

`WixSharp.Lab` is installed.

I don't have these templates that you showed - this is what I have (which extension do I need to install to have your templates?):

![image](https://user-images.githubusercontent.com/23175357/64943299-0d275c00-d874-11e9-8cad-bde10de53b27.png)

**Comment by LatteAno** [comment]
One more questions, if I may -

I wan't able to find any relevant material to learn this domain of custom UI in MSI, and learning it by trial & error (as I'm currently doing) is very slow.

For instance the whole topic of dialog navigation, the topic of setting conditionals (installing this or that feature, according to user's selection), debugging the UI and so on.

Are there any recommended tutorials/materials to learn custom UI in MSI with WixSharp?

**Comment by LatteAno** [comment]
Thanks to your guidance, @oleg-shilo , it's now working (well, almost... I opened another issue...)

**Comment by oleg-shilo** [comment]
And for anyone who reads this thread.

The VS project templates I was referring to are not WiX templates but WixSharp templates. Thus they need to be installed (VS extension) from the marketplace: https://marketplace.visualstudio.com/items?itemName=OlegShilo.WixSharpProjectTemplates.
