### ISSUE TITLE
Install and Start service conditionally

### ISSUE THREAD

**Issue by BambiShi** [oleg-shilo/wixsharp#718]
Hi,

I have a service that is bundled with a specific feature.
This feature has a specific condition which is a property I added to my installer - for the user to chose at run-time.
Since this is set at run-time of the .msi I don't know how to use the ServiceInstaller in this case.
In other words, I want to have the behavior of ServiceInstaller conditionally - only if the user is running in that's specific feature.

I also don't want to deploy this service if not running in that feature.

Is there a way to do so?

**Comment by oleg-shilo** [comment]
I am not sure about the native capabilities of WiX `ServiceInstall`. It may or may not have capabilities for evaluating conditions. 

You may find the answer in WiX forums. Though me personally, I would use elevated custom action (e.g. `project.AfterInstall +=`) and simply use C# to run the service:

```C#
if (session.Property("your_prop") == "expected_value")
{
    Tasks.StartService("your_service_name", false);
}
```

**Comment by rachelleP** [comment]
When using the above code I get a exception in run-time that there is a dll missing, any idea?

**Comment by oleg-shilo** [comment]
Hard to say, most likely you have a dependency on some assembly/dll that is not included in the msi. You can always start with the services sample 'WinService_InstallUtil'. It has no dependency problems so you can test how `Tasks.StartService` works. 

And `StartService` method is not that mysterious. This is basically what it is:

```C#
var util = new ExternalTool { ExePath = "sc.exe", Arguments = $"start  \"{service}\"" };

var buf = new StringBuilder();
int retval = util.ConsoleRun(line => buf.AppendLine(line));

if (retval != 0 && throwOnError)
    throw new Exception(buf.ToString());
return buf.ToString();
```

And as for missing dll, the most reliable way to find it is to hook to `AppDomain.CurrentDomain.AssemblyResolve +=` before any invoke is done by your assembly. Then you can debug and see in the event what dll exactly is missing.
