### ISSUE TITLE
Start the installed program after installation

### ISSUE THREAD

**Issue by gr001** [oleg-shilo/wixsharp#72]
Hi,

I am using Wix# to create an installer with an external WPF UI. I would like to add a button that will start the installed program after installation. Actually I do not know how to do that. Any suggestions?

Thanks.

Jiri

**Comment by oleg-shilo** [comment]
If you are not changeling the installdir during the installation then you can just read the default installdir from the MSI and then start the app.

However if you do change the installdir by interacting with the user then you need to remember the user input and start the app using the location based on that new dir.

**Comment by bigworld12** [comment]
I faced a similar problem recently and I solved it by reading the registry key for my application, and getting the InstallDir key

**Comment by oleg-shilo** [comment]
Just letting you guys know that exploring path at runtime is not that complicated:
```C#
void Window_Loaded(object sender, RoutedEventArgs e)
{
    ...     
    string path = new MsiParser(App.MsiFile).GetDirectoryPath("INSTALLDIR");
    ...
}
```

**Comment by gr001** [comment]
This is exactly I need and it works. Thanks.
