### ISSUE TITLE
Property seems to change per user's selection, but conditioned files are not being deployed

### ISSUE THREAD

**Issue by LatteAno** [oleg-shilo/wixsharp#721]
In our installer, we want to deploy one of two files, according to a decision that the user should make **during the installation**.

I am able to change the property during run-time, via a `WixForm` using radio buttons, and even to confirm that the bound property indeed changes (using a `CustomAction` that shows a `MessageBox`, checking the expressions `session.EvaluateCondition($"TYPE_OF_PKG=\"ABC\"")` and `session.EvaluateCondition($"TYPE_OF_PKG=\"XYZ\"")`).

However, it doesn't seem to affect the conditioned files - they are simply not deployed (unless I explicitly set the `"TYPE_OF_PKG"` `Property`'s value to e.g. `"ABC"` instead of `"NONE"`).

These are the two feature, `abcFeature` and `xyzFeature`:

	var abcFeature = new Feature("ABC_PKG") {
		Condition = new FeatureCondition($"TYPE_OF_PKG=\"ABC\"", 1),
		Attributes = {["AllowAdvertise"] = "no"},
		AllowChange = true,
		IsEnabled = false,
	};

	var xyzFeature = new Feature("XYZ_PKG") {
		Condition = new FeatureCondition($"TYPE_OF_PKG=\"XYZ\"", 1)
		Attributes = {["AllowAdvertise"] = "no"},
		AllowChange = true,
		IsEnabled = false,
	};

And that's the project definition:

	var files = new WixObject[] { new File(abcFeature, "abc.exe"), new File(xyzFeature, "xyz.exe") };

	new Project(myPorjectName, files)
	{
		Properties = new[] { new Property("TYPE_OF_PKG", "NONE") { AttributesDefinition = @"Secure = yes" }
		Features = new[] { abcFeature, xyzFeature },
		CustomUI = CustomUIBuilder.BuildPostLicenseDialogUI
		(
			dialogDefinition,
			new DialogAction[] { new ShowDialog(NativeDialogs.InstallDirDlg) }
		),
	}

Where in `dialogDefinition` (inherited from `WixForm`), we have two radio-buttons, **bound to the `TYPE_OF_PKG` property**, to display the option to the user (and change its value per the user's decision):

	this.RadioButtonsGroup.BoundProperty = "TYPE_OF_PKG";
	this.RadioButtonsGroup.ControlType = WixSharp.Controls.ControlType.RadioButtonGroup;
	this.RadioButtonsGroup.EmbeddedXML = @"
	<RadioButtonGroup Property=""TYPE_OF_PKG"">
		<RadioButton Value=""ABC"" X=""0"" Y=""0"" Width=""400"" Height=""20"" Text=""ABC"" />
		<RadioButton Value=""XYZ"" X=""0"" Y=""20"" Width=""400"" Height=""20"" Text=""XYZ"" />
	</RadioButtonGroup>";
	this.RadioButtonsGroup.Hidden = false;
	this.RadioButtonsGroup.Id = "RadioButtonsGroup";
	this.RadioButtonsGroup.Location = new System.Drawing.Point(12, 69);
	this.RadioButtonsGroup.Name = "RadioButtonsGroup";
	this.RadioButtonsGroup.Size = new System.Drawing.Size(466, 125);
	this.RadioButtonsGroup.Text = "What to install .wixText?";
	this.RadioButtonsGroup.Tooltip = null;
	this.RadioButtonsGroup.WixAttributes = null;
	this.RadioButtonsGroup.WixText = "What to install .wixText?";

Any idea how to make the selected file deployed?

**Comment by LatteAno** [comment]
I finally managed to work this out.

@oleg-shilo - either I don't understand how it is designed, or `Condition`s on `Feature`s just don't work.

Only when I completely removed the `Feature`s and moved to rely solely on simple object condition (e.g. `new File(...) { Condition = new Condition ("TYPE_OF_PKG", "ABC") }`) it started to work.

**Comment by oleg-shilo** [comment]
That's great.

If you still want to sort out the _FeatureCondition_ problem, I would encourage you to have a look at [FeatureConditions](https://github.com/oleg-shilo/wixsharp/blob/6007f95ec3391969563da4ed4163ce5430cde814/Source/src/WixSharp.Samples/Wix%23%20Samples/FeatureConditions/setup.cs) sample. 

It is a working sample. At least it was :) 

It also has some code explanations that might help.

**Comment by LatteAno** [comment]
Thanks @oleg-shilo, I saw that sample - this is where I learned all of it :smile:

And it's working flawlessly, until you pour to the mix a custom dialog that needs to select the feature to install (e.g. via some radio buttons) **in run-time**.

It's working with `WixUI_FeatureTree`, but not with custom dialog (at least not for me... would be grateful to learn how to fix it, in case I'm doing somethign wrong).

**Comment by oleg-shilo** [comment]
Ah... then you need to see how to read/write the feature state from the session. 

Create a project from the "Custom UI" project template.

![image](https://user-images.githubusercontent.com/16729806/65312067-1ba7a780-dbd5-11e9-9d8c-7ba49b6512d0.png)

Then analyze the "Feature Selection" dialog code. Most likely you will find your answer there.
