### ISSUE TITLE
Stop Services Present Reboot Popup

### ISSUE THREAD

**Issue by BambiShi** [oleg-shilo/wixsharp#723]
Hi,

I'm using the ServiceInstaller like this:
``` C#
    serviceExecutableFile.ServiceInstaller = new ServiceInstaller
				{
					Name = ConfigurationManager.AppSettings["ServiceName"],
					DisplayName = ConfigurationManager.AppSettings["ServiceDisplayName"],
					ErrorControl = SvcErrorControl.normal,
					Type = SvcType.ownProcess,
					DelayedAutoStart = false,
					StartOn = null,
					StopOn = SvcEvent.Uninstall_Wait,
					RemoveOn = SvcEvent.Uninstall_Wait
				};
```
I have an issue that when running uninstall i get the following popup:
![image](https://user-images.githubusercontent.com/29270394/65386291-7874a080-dd42-11e9-81dd-decca5bbe6f2.png)

in fact there is no reboot required and everything is uninstalled perfectly.

Any idea how can I get rid of that popup?

**Comment by oleg-shilo** [comment]
I am not sure you can. If I understand it correctly this dialog is popped up by the WiX `ServiceInstaller` implementation. The message itself is just a precaution and not necessarily needed. If it is the case then you may disable the message box if `ServiceInstaller` allows that. But... if it does not then nothing WixSharp can do about that.

**Comment by rachelleP** [comment]
How can I check whether the ServiceInstaller allows disabling the message box or not?

**Comment by oleg-shilo** [comment]
You will need to dig into WiX ServiceInstaller documentation.
