### ISSUE TITLE
Nothing shows up on executing *.msi 

### ISSUE THREAD

**Issue by kriactivedesigns** [oleg-shilo/wixsharp#724]
project.ManagedUI = new ManagedUI();
            project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                            .Add<LicenceDialog>()
                                            .Add<SetupTypeDialog>()
                                            .Add<FeaturesDialog>()
                                            .Add<InstallDirDialog>()
                                            .Add<ProgressDialog>()
                                            .Add<ExitDialog>();

            project.ManagedUI.ModifyDialogs.Add<MaintenanceTypeDialog>()
                                           .Add<FeaturesDialog>()
                                           .Add<ProgressDialog>()
                                           .Add<ExitDialog>();

I tried to use the above code in my wixsharp project, I get the MSI built successfullly, but when I execute it doesnt shows up anything after Preparing to Install dialogue. What I noticed after building is two processes of MSIBUILD.exe is running in the task manager

**Comment by oleg-shilo** [comment]
No sure what is the rest of your code but... did you try to build the project created from the "Custom UT" VS project template? It should work right out of box:

![image](https://user-images.githubusercontent.com/16729806/65599220-aecf4b80-dfe0-11e9-8928-e29ef3fb3bfa.png)

**Comment by kriactivedesigns** [comment]
The problem was I was building the project in x64.

**Comment by kriactivedesigns** [comment]
There is another issue I am facing. I am using Cutom Managed UI Dialogs. I want a borderless Windows form. I managed to create a borderless windows form, but when the dialog is displayed in the Installer there is a thin White bar over the top which is about 15 px thick and also I dont want Resize handles, but when the mouse pointer reaches the edges of the form resize handle shows up, but as wanted the window cannot be resized. How to solve the issue

**Comment by oleg-shilo** [comment]
Managed UI is a winform UI with a single top level window (ManagedUIShell) that simply host a managed UI dialog as the only child element and substitutes it with the next one every time user presses "next" button.

If you to control that top level window you can access it on `UILoaded` event and modify it or/and subscribe for events. After all this window is just a WinForm object.

```C#
static void msi_UILoaded(SetupEventArgs e)
{
    //If required you can
    // - set the size of the shell view window
    // - scale the whole shell window and its content
    // - reposition controls on the current dialog
    // - subscribe to the current dialog changed event

    //e.ManagedUIShell.SetSize(700, 500);
    //e.ManagedUIShell.OnCurrentDialogChanged += ManagedUIShell_OnCurrentDialogChanged;
    //(e.ManagedUIShell.CurrentDialog as Form).Controls....
}
```
