### ISSUE TITLE
shortcut icon

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#725]
Hi
I have VSTO Excel application with a shortcut. I have put my company logo in the application but was not picked up by wixsharp (as in normal exe project) Please help on how to add an icon to the shortcut.

Thanks

```
  project.ResolveWildCards()
                .FindFile(f =>
                    f.Name.EndsWith("ExcelSql.Data.xlsx", StringComparison.Ordinal)).First()
                .Shortcuts = new[]
            {
                new FileShortcut
                    ("ExcelSql", "%Desktop%")
            };
```

**Comment by oleg-shilo** [comment]
It's a difficult one. `FileShortcut` triggers the insertion of the `Shortcut` WiX element (https://wixtoolset.org/documentation/manual/v3/xsd/wix/shortcut.html). 

From the description of this element I do not see how to set the custom icon. If you do then you can use XML injection to the the "magic" attribute(s).

**Comment by Xaddan** [comment]
Shortcut Element may contain a child [Icon](https://wixtoolset.org/documentation/manual/v3/xsd/wix/icon.html)

**Comment by ltemimi** [comment]
Thanks very much for the help I will have a go at the XML injection.
