### ISSUE TITLE
Create a very bootstrapper

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#727]
We would like a minimalist bootstrapper which should only check for an installed .NET Framework. If not meet we like to show only a message and redirect to the download page (Microsoft).
So no bundled framework nor an automated download. Any idea how this could be done ?

best

Carsten

**Comment by oleg-shilo** [comment]
I am afraid it's tricky. WiX Burn bootstrapper is a .NET application so it bootstraps .NET installation before it starts. 

If it's not what you want then you cannot use it.

Then you can only use a bootstrapper that is a native app. WiX does not have support for that. 

WixSharp experimental feature "Native Botstrapper" (root\WixSharp\Source\src\WixSharp.Samples\Wix# Samples\Bootstrapper\NativeBootstrapper) builds exactly native app but goes beyond simple message box and installs whatever prerequisite is embedded. So again, it's not what you need. Though you may modify the source code and have your own bootstrapper (root\WixSharp\Source\src\NbsBuilder).

**Comment by hcarsten** [comment]
Oleg !
right, sounds interesting. Anyway just seeing the chicken & egg problem already. 
If I look at /Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/NativeBootstrapper/DotNETBootstrapper.cs and here at 

`var setup = new NativeBootstrapper();`
`setup.PrerequisiteFile = @"C:\Users\Admin\Downloads\dotnetfx.exe";`
`setup.PrimaryFile = "MainProduct.msi";`
`...`

Does the line with "C:\Users\Admin\Downloads\dotnetfx.exe" mean that this local file is embbedded into the resulting bootstrapper ?
So if we build a simple windows-programm in c with just your out MessageBox and a ShellExecute we are just fine. 
Just one point might be missing: So how to stop the installer once the bootstrapper returns. If I understand Source/src/NbsBuilder/NbsBuilder.Src/nbs/nbs.cpp correctly I would assume that the process breaks anyway if the sub-process did NOT install the .NET Framework (thus did not created the registry-value). Correct ?

Anyway happy to share our final solution, once we are done.

best 

Carsten

**Comment by geghamyan** [comment]
Hi,
You can try the following solution:
```
            var bootstrapper = new NsisBootstrapper
            {
                DoNotPostVerifyPrerequisite = false,
                PrerequisiteFile = "actions.vbs",
                PrimaryFile = msiFile,
                OutputFile = "MyProduct.exe",
                PrerequisiteRegKeyValue = @"HKLM:SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework,Version=v4.0:"
            };

            bootstrapper.NsiSourceGenerated += (System.Text.StringBuilder obj) =>
            {
                var exec = "ExecShell \"open\" \"$PLUGINSDIR\\actions.vbs\"";
                var str = obj.ToString();
                int ix = str.IndexOf(exec);
                obj.Insert(ix + exec.Length, "\r\nSleep 3000");
            };

            bootstrapper.Build();
```

Where actions.vbs is:
```
MsgBox(".Net Framework is not installed!")
WScript.CreateObject("WScript.Shell").Run "https://dotnet.microsoft.com/download/dotnet-framework"
```

Or as an alternative write a small native executable and use it instead of the vbs script.

**Comment by hcarsten** [comment]
nice solution :) VBS is installed by default (as part of the windows installation) nor not ? we need to target down to Windows 7 ...

best 
Carsten

**Comment by oleg-shilo** [comment]
Thank you Tigran,

I wanted to suggest NsisBootstrapper but though your solution works only by embedding the prerequisite setup. Did not know one could execute vbs too.  

Glad you stepped in :o)

**Comment by geghamyan** [comment]
VBS is a part of the Windows OS starting from Win95, but I personally think it's unreliable solution. VBS scripts might be blocked by admin policies for security considerations or vbs extension might be not associated with the scripting engine.
I'd recommend writing a small native executable which shows a message box and open a weblink and use it along with NsisBootstrapper. 
NsisBootstrapper is more resilient to privilege escalation attacks on earlier versions of Windows than NativeBootstrapper.

Cheers,
Tigran
