### ISSUE TITLE
Borderless Non resizable Custom UI

### ISSUE THREAD

**Issue by kriactivedesigns** [oleg-shilo/wixsharp#728]
There is another issue I am facing. I am using Cutom Managed UI Dialogs. I want a borderless Windows form. I managed to create a borderless windows form, but when the dialog is displayed in the Installer there is a thin White bar over the top which is about 15 px thick and also I dont want Resize handles, but when the mouse pointer reaches the edges of the form resize handle shows up, but as wanted the window cannot be resized. How to solve the issue

**Comment by oleg-shilo** [comment]
Managed UI is a winform UI with a single top level window (ManagedUIShell) that simply host a managed UI dialog as the only child element and substitutes it with the next one every time user presses "next" button.

If you to control that top level window you can access it on `UILoaded` event and modify it or/and subscribe for events. After all this window is just a WinForm object.

```C#
static void msi_UILoaded(SetupEventArgs e)
{
    //If required you can
    // - set the size of the shell view window
    // - scale the whole shell window and its content
    // - reposition controls on the current dialog
    // - subscribe to the current dialog changed event

    //e.ManagedUIShell.SetSize(700, 500);
    //e.ManagedUIShell.OnCurrentDialogChanged += ManagedUIShell_OnCurrentDialogChanged;
    //(e.ManagedUIShell.CurrentDialog as Form).Controls....
}
```

**Comment by kriactivedesigns** [comment]
I set window.FormGripStyle to Hide, and StartLocation to CenterScreen but still the resize grip is showing and also the window is not exactly at the center of the screen

**Comment by oleg-shilo** [comment]
Can you elaborate about the "window"? Is it `ManagedUIShell` or your _step dialog_ window?

**Comment by kriactivedesigns** [comment]
i tried above said things ( FormGripStyle and StartLocation ) in both my CustomForm and ManagedUIShell, but didnt work.

**Comment by oleg-shilo** [comment]
OK, then it may only mean that the form you have updated on `UILoaded` is changing its properties when it is actually displayed. Or... somehow you are not changing vthe properties of the right window/form.

I suggest a simple experiment:
```C#
static void msi_UILoaded(SetupEventArgs e)
{
    var topWindow = (e.ManagedUIShell.CurrentDialog as Form);
    e.ManagedUIShell.OnCurrentDialogChanged += (x, y)=>
    {
        topWindow.Text = "<this is my custom title>";
    };
``` 

This will deterministically tell you if you are working with the right window and can in fact change the properties

**Comment by kriactivedesigns** [comment]
I solved my issues with the following code

           var managedUI = e.ManagedUI as Form;
            managedUI.AutoScaleMode = AutoScaleMode.Dpi;
            managedUI.FormBorderStyle = FormBorderStyle.FixedToolWindow;
            managedUI.StartPosition = FormStartPosition.CenterScreen;
    e.ManagedUI.SetSize(CustomManagedUI.Constants.WindowSize.Width,CustomManagedUI.Constants.WindowSize.Height);


but the issue that the window is not starting at the center of the screen is not fixed

![image](https://user-images.githubusercontent.com/42262332/66125422-81982400-e604-11e9-958b-bbde5921a1b8.png)

see the screenshot, the window has a slight offset to the right.

**Comment by oleg-shilo** [comment]
Below is the initialization code of the top window and its `OnLoad` event handler:

```C#
class ShellView : Form, IShellView
{
    . . .
    void InitializeComponent()
    {
        this.SuspendLayout();
        this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(494, 361);
        this.MinimumSize = new System.Drawing.Size(510, 400);
        this.MaximumSize = new System.Drawing.Size(510, 400);
        this.MaximizeBox = false;
        this.Name = "UIShell";
        this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        this.TopMost = true;
        this.Icon = ".msi".GetAssiciatedIcon();
        this.ResumeLayout(false);
    }
. . .

ShellView.Load += (s, e) =>
    {
        . . .
        result = runtime.InvokeClientHandlers("UILoaded", (IShellView)shellView);
```

As you can see in your `UILoaded` event handler you can do with the window anything you want. You can even subscribe for other events like `VisibileChanged`. YOu have full power of WinForm to customize it as required.

YOu will need to do these extra custom steps because it looks like in your case something is messing with the display settings. Maybe scaling... Maybe something else....

**Comment by kriactivedesigns** [comment]
Thank you for your most valuable help and effort. Everything works almost fine. The startup location issue is still there, but there another major problem i am facing.

> MSI (c) (D4!6C) [22:22:50:442]: Creating MSIHANDLE (26) of type 790531 for thread 6508
> Cannot attach ManagedUI: Microsoft.Deployment.WindowsInstaller.InstallCanceledException: Exception of type 'Microsoft.Deployment.WindowsInstaller.InstallCanceledException' was thrown.
>    at WixSharp.ManagedUI.Initialize(Session session, String resourcePath, InstallUIOptions& uiLevel)

this is the Exception I get. this happens when i click Change, Repair or remove button in the custom modified dialog. What happens is when i click the button the installer crashes

The Complete log file is attaached with this.

[modifylog5.txt](https://github.com/oleg-shilo/wixsharp/files/3698872/modifylog5.txt)

**Comment by hxhgxy** [comment]
How to remove the dialog title bar and border for WPF UI template?

**Comment by oleg-shilo** [comment]
You will need to update the dialog code in your first custom dialog. Something like this: 
```C#
public partial class WelcomeDialog : WpfDialog, IWpfDialog
{
    public WelcomeDialog()
    {
        InitializeComponent();
    }

    public void Init()
    {
        var topWindow = this.ManagedFormHost.Parent as System.Windows.Forms.Form;
        topWindow.text = "Your custom title";

        ViewModelBinder.Bind(new CustomDialogModel { Host = ManagedFormHost }, this, null);
    }
```

**Comment by hxhgxy** [comment]
`public void Init()
		{
			var topWindow = this.ManagedFormHost.Parent as System.Windows.Forms.Form;
			topWindow.Text = "HUEING R&D Management";
			topWindow.Width = 1200;
			topWindow.Height = 700;

			ViewModelBinder.Bind(new WelcomeDialogModel { Host = ManagedFormHost }, this, null);
		}`

I put it like this, but the window title and border is still there. And the window width / height setting didn't work too.

**Comment by hxhgxy** [comment]
![wixsharp1](https://github.com/oleg-shilo/wixsharp/assets/37101628/3199462c-0cdb-4e41-98d8-412d4bf25660)

here is the screen - I actually put an image on the center of window and it shows in design mode. But it is not visible in running time. I will figure it out later. the title bar and border is more important to me. 

Many thanks!

**Comment by hxhgxy** [comment]
topWindow.FormBorderStyle=System.Windows.Forms.FormBorderStyle.None;

it works with this property.
