### ISSUE TITLE
How to change small icon in banner

### ISSUE THREAD

**Issue by apurvabhansali** [oleg-shilo/wixsharp#730]
Hi, was wondering how to change the red default icon in the upper right of the banner of the installer pages.

![image](https://user-images.githubusercontent.com/16947238/66344630-f4124800-e913-11e9-83f5-2c73a9efd33f.png)

I tried ManagedProject.BannerImage by giving a png that is 133x102, but that results in a a stretched and messed up dialog like below:

![image](https://user-images.githubusercontent.com/16947238/66344723-26bc4080-e914-11e9-8540-755cf20d9d29.png)

Thanks!

**Comment by apurvabhansali** [comment]
Any update on this?

**Comment by oleg-shilo** [comment]
Sorry, haven' rich your post yet...
