### ISSUE TITLE
Consider building WixSharp.wix.bin with Wix v3.14

### ISSUE THREAD

**Issue by ygel** [oleg-shilo/wixsharp#732]
WixSharp.wix.bin was updated two years ago, what are your thoughts on updating v3.11 to the latest stable and pushing a pre-release v3.14 to nuget?

**Comment by oleg-shilo** [comment]
that's not a problem. will do with the very next release.

**Comment by oleg-shilo** [comment]
Checked. It is still v3.11 on their site:
![image](https://user-images.githubusercontent.com/16729806/66562940-6ef39100-eba8-11e9-8882-e3701b6b8d87.png)

But of course you can install any, even unstable version and simply

**Comment by ygel** [comment]
@oleg-shilo While it does say v3.11.2 build was last updated 22 days ago (not to mention numerous updates in between). 

> Checked. It is still v3.11 on their site:
> But of course you can install any, even unstable version and simply use it with WixSharp

My use case is  CI, hence trying to automate everything possible. Would much prefer v3.14 from nuget than installing manually.

**Comment by oleg-shilo** [comment]
That's OK, but I cannot get 3.14 binaries as they are not available from their web site.

**Comment by ygel** [comment]
> That's OK, but I cannot get 3.14 binaries as they are not available from their web site.

They're available here: https://wixtoolset.org/releases/v3-14-0-2812/, via this page https://wixtoolset.org/releases/development/

Thanks for looking into it!

**Comment by oleg-shilo** [comment]
The release you are referring is not an officially recommended by WiX. So I am a bit reluctant to use it. It's not really WixSharp place to overrule WiX recommendations.

Though I have just published the nuget package with the latest official WiX binaries v3.11.2. This probably addresses your immediate needs
