### ISSUE TITLE
Installer localization

### ISSUE THREAD

**Issue by bdrachinsky** [oleg-shilo/wixsharp#733]
Hi Oleg, 

Currently I build 1 msi installer per language and it's hard to manage them all.
I want to achieve something like dropdown with list of language and by selecting one of the them the installer should change his installation language. Is there a way to achieve that? As I understood -- I need to use [CustomUI](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/CustomUIDialog/setup.cs) but I don't quite get how to proceed with multiple .wxl

**Comment by oleg-shilo** [comment]
Normally I would advice to have a look at multi-language support by WiX/MSI. If it exists then you can do it in WixSharp. Well, it is a valid advice but... if it's not possible then you can also consider building a custom localizable  _External UI_ see WpfSetup/WinForm setup for it.

![image](https://user-images.githubusercontent.com/16729806/66565141-79fcf000-ebad-11e9-9c78-69dddaf85835.png)

This way our UI is just an ordinary UI application so you can use any standard localization technique.

**Comment by bdrachinsky** [comment]
@oleg-shilo  I've checked your examples but that's not quite what I need. What I need is more like injecting my own page before the Welcome page where I will have dropdown. When item was selected and button was pressed we will proceed to the Welcome page with language that we selected on the previous step

**Comment by bdrachinsky** [comment]
Is there a way to change .wxl file in runtime and show correct UI installer or it should be achieved by getting system language before installation and inject correct wxl?

**Comment by oleg-shilo** [comment]
The approach I described to you is applicable for your requirements. You create an app where you can substitute the content (pages) every time as you proceed to the next step. 

> way to change .wxl file in runtime

Unfortunately MSI/WiX does not allow that. At least i am not aware about such a functionality

**Comment by bdrachinsky** [comment]
I've done multi language support for my application. MSI after the installation show me selected language but I still have issue with changing MSI dialogs language. I've thoughts that I need to place all of the localizations in one .wxl file so it will be like

```
<WixLocalization Culture="en-US" Codepage="1252" xmlns="http://schemas.microsoft.com/wix/2006/localization">
...
</WixLocalization>
<WixLocalization Culture="uk-ua" Codepage="1251" xmlns="http://schemas.microsoft.com/wix/2006/localization">
...
</WixLocalization>
<WixLocalization Culture="ru-ru" Codepage="1251" xmlns="http://schemas.microsoft.com/wix/2006/localization">
...
</WixLocalization>
```

So I can switch them in the "BeforeInstall" event or even in "project.UIInitialized" I'm not sure how to do it or what is the best approach to check user's system Language and pass the right localization. That's my first time working with msi installer so I'm trying to understand the big picture of how it should work. It would be very helpfull if you provide me some samples, thank you

**Comment by oleg-shilo** [comment]
Have a look at ManagedSetup\CustomUIDialog.csproj. It shows how to add a dialog to a German UI.
However it is all about static localization. 

Since you need to change the language dynamically and you are using ManagedUI your UI localization approach is a normal .NET localization. Not the WiXLocalization. 

Saying that you can still use custom localization. Even  if it comes from your WiX resources.

You can, in every dialog call `LocalizeWith` 

```C#
dialog.LocalizeWith(<localize>);
```
Where:
```C#
public static sys.Control LocalizeWith(this sys.Control control, Func<string, string> localize)
``` 

Thus you can create at runtime a localizer that maps an English keyword in Ukrainian. Something like that:
```c#
var map = new Dictionary<string, string>
{
    { "Exit", "Вихiд" },
    {....}
};
Func<string, string> localizer_ua = raw => map[raw];

welcomeDialog.LocalizeWith(localizer_ua);
```

These are just ideas...

**Comment by bdrachinsky** [comment]
This helped me a lot. I've faced another problem. When I started to use customUI dialogs after the installation it keep showing me Messagebox 
![image](https://user-images.githubusercontent.com/13419649/66772207-da996f00-eec4-11e9-9b13-d3b3830cfb9d.png)

Also I'm not able to uninstall, installer just reverts uninstall on the last seconds. Do I need to override some events?

**Comment by oleg-shilo** [comment]
The message box means that somewhere in your code you have my sample event handler. Just find and delete it.

As for aborted uninstall, keep in mind that any error during the install operation aborts this operation. Thus one can find himself in the situation when the product is installed but during uninstalling teh install operation cannot be accomplished.

Unfortunately there is no good way to solve it. One possibility is to have `Debug.Assert` (or `Debugger.Break`) in all your event handlers so you can attach an elevated debugger, find what is causing the error and skip over the offending code line. Though it's too late and you don't have these asserts :)

Then you can only fix your system by manually deleting the install information of your very product from the registry. I do it always when I hit the wall but I cannot recommend it as you eed to know what exactly you are doing. You can use RevoUninstaller for that. It does wonderfull job on removing broken uninstalls.

When you done uninstalling, ensure that in all your event handlers you never throw or return error code during uninstalling. Just log the error instead. THis way you will ensure you can always remove the product.
