### ISSUE TITLE
Hidden property for PublicProperty

### ISSUE THREAD

**Issue by cocowalla** [oleg-shilo/wixsharp#734]
When using WiX, you can declare a public property like this (by "public", I mean it is exposed on the `msiexec` commandline and can be overridden:

```xml
<Property Id="PASSWORD" Hidden="yes" />
```

Note the `Hidden="yes"` - this prevents Windows Installer from logging the value of this property, and is documented [here](https://wixtoolset.org/documentation/manual/v3/xsd/wix/property.html).

Is there any way currently in WixSharp to prevent a public property value from being logged, or is this something that might be added? If the latter, I'd be happy to submit a PR if I could get a few pointers from you 😄

**Comment by oleg-shilo** [comment]
Currently you can add it as an additional attribute:
```C#
new Property("TITLE", "Properties Test")
{
    AttributesDefinition = "Hidden=yes"
},
```
But it's a simple feature I have just added it.

Will be available in the very next release (in a few days)
