### ISSUE TITLE
Use properties with ServiceInstaller

### ISSUE THREAD

**Issue by cocowalla** [oleg-shilo/wixsharp#735]
I'm using `ServiceInstaller` to install a Windows service, and it works as expected.

I'd like to allow configuring the service account using a Property - is there any way to configure `ServiceInstaller.Account` to use a property value?

I realise another way is to use a custom action, such as in [this example](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/WinService/With_InstrallUtil/setup.cs), but I like the simplicity of `ServiceInstaller`, so would prefer to keep it if possible.

**Comment by oleg-shilo** [comment]
I have checked the [documentation](https://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceinstall.html) and it does not specify if `Account` value can expand WiX properties. Meaning that you can only test and see if it works.

It will be something like this:

```C#
service.ServiceInstaller = new ServiceInstaller
{
   Name = "WixSharp.TestSvc",
   StartOn = SvcEvent.Install, //set it to null if you don't want service to start as during deployment
   StopOn = SvcEvent.InstallUninstall_Wait,
   RemoveOn = SvcEvent.Uninstall_Wait,
   DelayedAutoStart = true,
   Account = "[USER_SPECIFIED_SVC_ACCOUNT]",
   . . .
```

**Comment by cocowalla** [comment]
Ah, I wasn't aware of this "expansion" syntax - pleased to report that it works, thanks!

**Comment by oleg-shilo** [comment]
This is an MSI functionality that is available for some WiX elements' attributes. Arguably even for majority but not for all of them .
