### ISSUE TITLE
How to add file into install subdir?

### ISSUE THREAD

**Issue by ladserg** [oleg-shilo/wixsharp#74]
There are files:

- Addon\a\2\a22.txt
- Addon\a\2
- Addon\a
- Files\main.txt
- Files\a\1\a11.txt
- Files\a\1\a12.txt
- Files\a\1
- Files\a\2\a21.txt
- Files\a\2
- Files\a
- Files\b\b1.txt
- Files\b\b2.txt
- Files\b
- build.bat
- main.cs

main.cs is:
```
using System;
using WixSharp;

class Script
{
    static public void Main(string[] args)
    {
        Project project =
            new Project("DistName",
                new Dir(@"%ProgramFiles%\DistName",
                    new Files(@"Files\*.*")
                    ,new Dir("a"
                        ,new Dir("2"
                            ,new File(@"Addon\a\2\a22.txt")
                        )
                    )
                )
            );

        project.GUID = new Guid("ff330b47-2577-43ad-9095-201705231808");

        Compiler.BuildMsi(project);
    }
}

```
Compiler output:

> Copyright (C) 2004-2016 Oleg Shilo.
> 
> Wix# support for EmptyDirectories is automatically disabled
> 
> ----------------------------------------------------------
> 
> Wix project file has been built: D:\test\DistName.wxs
> 
> Windows Installer XML Toolset Compiler version 3.10.3.3007
> Copyright (c) .NET Foundation and contributors. All rights reserved.
> 
> DistName.wxs
> Windows Installer XML Toolset Linker version 3.10.3.3007
> Copyright (c) .NET Foundation and contributors. All rights reserved.
> 
> D:\test\DistName.wxs(18) : error LGHT0091 : Duplicate symbol 'Component:Component.a22.txt' found. This typically means hat an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
> D:\test\DistName.wxs(38) : error LGHT0092 : Location of symbol related to previous error.
> D:\test\DistName.wxs(16) : error LGHT0091 : Duplicate symbol 'Directory:INSTALLDIR.a.2' found. This typically means that an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
> D:\test\DistName.wxs(36) : error LGHT0092 : Location of symbol related to previous error.
> D:\test\DistName.wxs(19) : error LGHT0091 : Duplicate symbol 'File:a22.txt' found. This typically means that an Id is deplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
> D:\test\DistName.wxs(39) : error LGHT0092 : Location of symbol related to previous error.

How to add **Addon\a\2\a22.txt** into **[INSTALLDIR]\a\2\\** ?

**UPD**: In 1.4.2.0 version work this code:
```
using System;
using WixSharp;

class Script
{
    static public void Main(string[] args)
    {
        Project project =
            new Project("DistName",
                new Dir(@"%ProgramFiles%\DistName",
                    new Files(@"Files\*.*")
                    ,new Dir(new Id("Addon"), "a"
                        ,new Dir("2"
                            ,new File(@"Addon\a\2\a22.txt")
                        )
                    )
                )
            );

        project.GUID = new Guid("ff330b47-2577-43ad-9095-201705231808");

        Compiler.BuildMsi(project);
    }
}
```

In version 1.4.3.0 and later, this code don't work.

**Comment by oleg-shilo** [comment]
In your code you are mixing recursive wild cards and explicit file definitions. There is nothing truly wrong with it but when I introduced wild cared I had in mind scenario when they are the only members of the setup definitions (not a mixture). Mixtures should still work but not in the case when there is a duplication caused by the merging source directories.

Saying that I thing Wix# would only benefit if some sort of duplication auto-removal is implemented. That is why I marked the issue as an enhancement.  I will try to implement it for the next release.

As a temporary work around you can switch to non recursive wiled cards:
```C#
using System;
using WixSharp;

class Script
{
    static public void Main(string[] args)
    {
        var project =
            new Project("DistName",
                new Dir(@"%ProgramFiles%\DistName",
                    new DirFiles(@"Files\*.*"),
                    new Dir("b",
                        new DirFiles(@"Files\b\*.*")),
                    new Dir("a",
                        new Dir("1",
                            new DirFiles(@"Files\a\1\*.*")),
                        new Dir("2",
                            new DirFiles(@"Files\a\2\*.*"),
                            new File(@"Addon\a\a22.txt")))));

        project.GUID = new Guid("ff330b47-2577-43ad-9095-201705231808");
        Compiler.PreserveTempFiles = true;

        Compiler.BuildMsi(project);
    }
}
```

**Comment by ladserg** [comment]
Thanks for the response. There are a lot of directories in the real project, their structure is changing. Options files are added to the directories if the user selects the desired item during installation.

In version 1.4.2.0 it works, I will use it for now. And I will wait for the realization or the return of the opportunity I need.

Thank you.

**Comment by oleg-shilo** [comment]
It is actually a bug. Has been introduced with the recent pull request. Ironically it has a duplication prevention routine and just a small bug prevented it from producing desired effect.

Fixed. Will be available with the next release

**Comment by ladserg** [comment]
Everything is working. Thank you.

**Comment by CADbloke** [comment]
see also https://stackoverflow.com/a/57555935/492
