### ISSUE TITLE
Dynamic install directory not working

### ISSUE THREAD

**Issue by cocowalla** [oleg-shilo/wixsharp#742]
I'm having some trouble with a dynamic installation directory. I've looked at the `InstallDir_DynamicPath` sample and a couple of issues (e.g. #468), but I just can't get it working.

I'm using managed UI, and project definition is a bit like:

```c#
var appDir = new InstallDir(@"%ProgramFiles%\Acme\Widget",
    new Files("ProgramFiles\*.*"));

var dataDir = new Dir(new Id("PROFILE_DIR"), "set at runtime",
    new Files("AppData\*.*"));

var project = new ManagedProject("Acme Widget", appDir, dataDir);
```

The basic idea is that I want to install config files into a folder set by the `PROFILE_DIR` property. I set `PROFILE_DIR` in a custom action, and I've tried setting it using the `Load`, `BeforeInstall` and `AfterInstall` events using `e.Data["PROFILE_DIR"] = myPath`, but the files are always installed to `D:\set at runtime`.

Looking at the MSI logs, I can see that the property is being set in the custom actions:

```
MSI (s) (94!2C) [22:40:22:636]: PROPERTY CHANGE: Adding PROFILE_DIR property. Its value is 'C:\MyPath'.
```

Any idea where I'm going wrong here?

**Comment by Torchok19081986** [comment]
Hallo, i had same problems. After Olegs helps me with, i set it from ManagedAction. Looks following:
  new ManagedAction(CustomActions.SetToolDir, Return.check, When.Before, Step.LaunchConditions, Condition.NOT_Installed),
  new Dir(new Id("DIR2"), "root2", <here coms description of followoinf files with new File etc.>
Try set your ID in ManangedAction like following. With session["YOUR_DIR_ID"] = "Path". 
Works really good in my msi-installer.

**Comment by cocowalla** [comment]
@Torchok19081986 as above, that's what I'm already doing, but using the managed UI events to run custom actions instead of `project.Actions` - I've tried it at various steps, including `Load`, `BeforeInstall` and `AfterInstall` 😢

**Comment by cocowalla** [comment]
@Torchok19081986 Hmm, so, I just tried using a `ManagedAction` like in your example, and it does work!

```c#
project.Actions = new WixSharp.Action[]
{
    new ManagedAction(CustomActions.SetProfilePath, Return.check, When.Before, Step.LaunchConditions, Condition.NOT_Installed)
};
```

Looking back at what I was doing with the Managed UI handlers, I was setting the path using `e.Data["PROFILE_DIR"]`, not `e.Session["PROFILE_DIR"] - if I do the latter, it does actually work with the Managed UI handlers too.

@oleg-shilo my understanding was that `e.Data` is a copy of `e.Session`, and elsewhere when I've set properties using `e.Data` the values are available in other custom actions as expected - is there any reason why setting a value using `e.Data` would not make it available as a directory ID, but `e.Session` would?

**Comment by Torchok19081986** [comment]
I interested as well for this question. Maybe @oleg-shilo can explain it better. AFAIK is normal ui msi is diffent from managed ui. Maybe here is solution. This would explain why works with e.Session and not with e.Data.

**Comment by oleg-shilo** [comment]
OK, the questions one by one.

1. Setting installdir dynamically
    do this:
    ```C#
    static void msi_Load(SetupEventArgs e)
    {
        if (e.IsInstalling)
        {
            e.Session["INSTALLDIR"] = @"D:\test";
            . . .  
    ```
    I just tested it. It works. Let me know if it does for you. 

2. `e.Data[...]` vs `e.Session[...]` 
    Both of them are just dictionaries. But... one holds MSI properties and another one holds user defined properties (key-value pairs).

To avoid further confusions I have extended (yet to be published) the XML documentation to reflect the difference: 

![image](https://user-images.githubusercontent.com/16729806/67088842-e2715000-f1f1-11e9-9cb4-ac9c3de6824e.png)

**Comment by cocowalla** [comment]
Yes, setting the value using `e.Session` instead of `e.Data` does work.

I was confused about `e.Session` vs `e.Data`, and had thought `e.Data` was basically a total and better replacement for properties from `e.Session`, but from your new docs I'm now understanding it as:

- Use `e.Data` for custom action data, so properties are available in both deferred and non-deferred actions (which was a real PITA in WiX!)

- Use `e.Session` for MSI session properties

Is this understanding in general correct?

**Comment by oleg-shilo** [comment]
Bingo! That exactly what the difference is.

I do accept that despite being accurate the original documentation did not make enough emphasis on the difference between these two.

Thus after your very last message I have extended the doc content with your bullet points:

![image](https://user-images.githubusercontent.com/16729806/67153899-7439a400-f33d-11e9-9af2-8767627829bd.png)

**Comment by oleg-shilo** [comment]
It's hard to comment on your problem. In your sample, The `FileTreeBuilder` is a complete mystery.

I suggest you follow the sample that shows how to set installdir to an absolute path. I assume it is the problem you are trying to solve.

**Comment by RachelXGanon** [comment]
My bug solved after  uninstall `wixsharp` libraries and reinstall them. 
Thanks.

**Comment by oleg-shilo** [comment]
I am just curious. What actions do you refer to as "uninstall wixsharp libraries"?

**Comment by oleg-shilo** [comment]
OK, so you meant add/remove NuGet packages.
txs
