### ISSUE TITLE
custom UI template throws error

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#743]
Hallo, i have a problem with create new project from Template. I choosed CutomUI template, after that visual studio shows me following error. 
The missing file is ..\packages\WixSharp.bin.1.9.5.1\build\WixSharp.bin.targets.	Installer	C:\Users\Me\source\repos\Installer\Installer.csproj.
Unlikewise Target was set automatic to .NET Framework 4. Restore and reinstall or update to newest Version 1.13 brought no improvement. 
Set .NET Framework to 4.7.2 also not work. Can someone help me with ?

**Comment by oleg-shilo** [comment]
I also have noticed the change in behavior a few days ago. I am leaning towards explaining it by the changes brought by the recent VS updates. PowerShell script from the template stopped correctly modifying the project file on updating/restoring package.

I am working on it right now. The template updates will be available in a day or so.

In a mean time open the project file in notepad and remove all references to the WixSharp files, packages.config file and package imports:

![image](https://user-images.githubusercontent.com/16729806/67095314-55ce8e00-f201-11e9-81df-fdc1b7e117a6.png)

![image](https://user-images.githubusercontent.com/16729806/67095282-42bbbe00-f201-11e9-8454-8e7416e42ab2.png)


![image](https://user-images.githubusercontent.com/16729806/67095235-2b7cd080-f201-11e9-92d0-72083dd81d31.png)

**Comment by oleg-shilo** [comment]
Done. Update your WixSharp project templates VS extension to v1.9.0

**Comment by Torchok19081986** [comment]
Many Thanks, @oleg-shilo .
