### ISSUE TITLE
ManagedForm not getting elevated privileges

### ISSUE THREAD

**Issue by tekbird** [oleg-shilo/wixsharp#744]
I have a managedform at the end of the install steps In that form, I have three checkboxes to create shortcuts on desktop, on start menu and to launch the program. however, it fails with E_ACCESSDENIED exception. how to mitigate this issue?

**Comment by tekbird** [comment]
> I have a managedform at the end of the install steps In that form, I have three checkboxes to create shortcuts on desktop, on start menu and to launch the program. however, it fails with E_ACCESSDENIED exception. how to mitigate this issue?

**Comment by oleg-shilo** [comment]
If you need to be elevated then you have to use `AfterInstall` event. It is a deferred action and it is already elevated so you don't need to do anything special. Pass any require date from your form to the event handler via session properties. MSI does not allow passing data directly. 

Though in your case it will be a deferred action so you have to use deferred property for that.
