### ISSUE TITLE
Missing parameter values when using SetupEventArgs handlers

### ISSUE THREAD

**Issue by vokounjan** [oleg-shilo/wixsharp#745]
Hello!

I've found your awesome project about a week ago and I've been playing with it since then. However last 2 days I've been stuck with this pretty weird behaviour:

I'd like to make a NuGet package (based on WixSharp.bin) which would contain some basic pre-install and after-install steps that could be used to compose a customizable installer for some of our intranet applications. It could look like this:

```csharp
namespace CompanyProject
{
    public class CompanySetupProject : ManagedProject
    {
        public CompanySetupProject(string name)
        {
            Name = name;
            InstallScope = WixSharp.InstallScope.perMachine;
            InstallPrivileges = WixSharp.InstallPrivileges.elevated;
            ManagedUI = WixSharp.ManagedUI.Empty;
            Platform = WixSharp.Platform.x86;
            OutDir = $@"C:\MSI\{Name}";
            PreserveTempFiles = true;
            DefaultRefAssemblies = new List<string> { "bin/Debug/CompanyProject.dll", }; // link to this project's built DLL
        }

        public void SayGoodbyeAfterInstall(string appName)
        {
            AfterInstall += (e) => SayGoodbyeAfterInstallStep.Handle(e, appName);
        }
    }
}
```
with install steps that would look like this:

```csharp
namespace CompanyProject
{
    public static class SayGoodbyeAfterInstallStep
    {
        public static void Handle(SetupEventArgs e, string appName)
        {
            if (e.IsInstalling)
            {
                e.Session.Log("----------------------------------------------------");
                e.Session.Log($"App {appName} has been installed...");
                e.Session.Log("----------------------------------------------------");
            }
        }
    }
}
```

Then if I created an install project (with WixSharp and CompanySetupProject NuGets), I could use it this way (and it would be working):

```csharp
namespace CompanyApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var project = new CompanySetupProject("CompanyApp1");

            project.AfterInstall += (e) => SayGoodbyeAfterInstallStep.Handle(e, "Company App 1");

            project.BuildMsi();
        }
    }
}
```

However if I try to use the method `SayGoodbyeAfterInstall (string appName)`, the value of parameter `appName` gets lost:

```csharp
namespace CompanyApp2
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var project = new CompanySetupProject("CompanyApp2");

            project.SayGoodbyeAfterInstall("Company App 2");

            project.BuildMsi();
        }
    }
}
```
I noticed that there's a difference in temp .wxs files.
For CompanyApp1:
```
<Property Id="WixSharp_AfterInstall_Handlers" Value="CompanyApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|CompanyApp1.Program+&lt;&gt;c|&lt;Main&gt;b__0_0" />
```
For CompanyApp2:
```
<Property Id="WixSharp_AfterInstall_Handlers" Value="CompanyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|CompanyProject.CompanySetupProject+&lt;&gt;c__DisplayClass1_0|&lt;SayGoodbyeAfterInstall&gt;b__0" />
```

Is this behaviour expected? Is there any way to make it work?

I'm installing those projects with 

```
msiexec.exe /i setup.msi /L*V install.log
```
and the difference is around line 500.

```
MSI (s) (30:78) [17:38:17:695]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIE2AB.tmp, Entrypoint: WixSharp_AfterInstall_Action
MSI (s) (30:6C) [17:38:17:695]: Generating random cookie.
MSI (s) (30:6C) [17:38:17:702]: Created Custom Action Server with PID 29380 (0x72C4).
MSI (s) (30:98) [17:38:17:779]: Running as a service.
MSI (s) (30:98) [17:38:17:783]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSIE2AB.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
----------------------------------------------------
App Company App 1 has been installed...
----------------------------------------------------
```

```
MSI (s) (30:28) [17:38:12:108]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSICCDA.tmp, Entrypoint: WixSharp_AfterInstall_Action
MSI (s) (30:30) [17:38:12:108]: Generating random cookie.
MSI (s) (30:30) [17:38:12:113]: Created Custom Action Server with PID 11888 (0x2E70).
MSI (s) (30:D0) [17:38:12:204]: Running as a service.
MSI (s) (30:98) [17:38:12:208]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSICCDA.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
----------------------------------------------------
App  has been installed...
----------------------------------------------------
```

Thanks a lot!

**Comment by oleg-shilo** [comment]
It is a very interesting problem that has very "strong" technical cause laying in the depth of Reflection.

**Differences in WXS**
The `<Property Id="WixSharp_AfterInstall_Handlers"...` differences are valid. They are capturing the fact that in one case your event handler is defined in the assembly that is the very same assembly as the entry assembly so it its name is encoded as `null`. And in another case it is an external assembly so it is defined by its name.

**Differences in behavior**
The event handler of any `ManagedProject` event is a static method or a lambda (which is a static method of an anonymous class).

Being static it can only rely on static data: constants, string literals or other static members. When these static members are not initialized at runtime but at MSI build time their values are `null` like in your case "Company App 2".

However when when you provide your lambda directly CLR compiler captures any literals and stores them in the hard-codded static members of the anonymous class. That's why your "Company App 1" worked.

It's a difficult problem to spot but easy to fix. You need to preserve your build time "literal" into the MSI property so it can be retrieved at runtime:

```C#
public static void SayGoodbyeAfterInstall(ManagedProject project, string appName)
{
    project.AddProperty(new Property("APP_NAME", appName) { IsDeferred = true });
    project.AfterInstall += (e) =>
    {
        MessageBox.Show(e.Session.Property("APP_NAME"), "appName");
    };
}
```
But of course the most logical way for your problem is just to read the product name from already existing property:

```C#
public static void SayGoodbyeAfterInstall(ManagedProject project
{
    project.AfterInstall += (e) =>
    {
        MessageBox.Show(e.Session.Property("ProductName"), "appName");
    };
}
```

**Comment by vokounjan** [comment]
Thank you so much for your explanation! My headache is gone but your solution still doesn't really solve my problem (which is a bit more difficult than the example provided in my previous post).

It works perfectly for passing ```String``` type arguments but my goal is to actually pass more complicated objects (such as ```Dictionary<string, string>``` (static) or even ```Dictionary<string, Dictionary<string, string>>``` for example). I know that I can deserialize/serialize them manually or create some kind of converter (from my object to Property) but isn't there any better way to achieve what I'd like to?

**Comment by oleg-shilo** [comment]
I say serialize them to JSON. This way it is a standard technique and fast and robust enough.

An unpleasant truth is that MSI properties are strings so there is no way you can put there a runtime object without serialization.

**Comment by vokounjan** [comment]
That's a great idea, thank you.
