### ISSUE TITLE
How can i create empty file

### ISSUE THREAD

**Issue by MVKozlov** [oleg-shilo/wixsharp#746]
I need to create empty file while setup process (and fill it in `Project_AfterInstall`)
and it should be removed when application uninstalled

How I can achieve this ?

If I include it as File() from release folder it filled with developer's content which should not be in MSI because can contain sensitive info

**Comment by oleg-shilo** [comment]
Inside of `Project_AfterInstall` handler you can always check if you are installing or uninstalling. Something like:
```C#
if (e.IsUninstalling)
{
    File.Delete("<file _path>"); 
}
else if(e.IsInstalling && !e.IsUpgrading && !e.IsRepairing)
{
    File.WriteAllText("<file _path>", "");
}
```

**Comment by MVKozlov** [comment]
thanks, useful idea.
but now I just remove file content before `Compiler.BuildMsi(project);`
