### ISSUE TITLE
Confirmation on Cancel Click with custom UI

### ISSUE THREAD

**Issue by BambiShi** [oleg-shilo/wixsharp#747]
Hi,

I'm looking for a way that my cancel button on the dialog I created will present the usual confirmation message box:

![image](https://user-images.githubusercontent.com/29270394/67281854-06c27a80-f4d9-11e9-8d74-73229734e4d7.png)

How can I access this general message box and use it on my cancel button?

**Comment by oleg-shilo** [comment]
Create your project from the "Custom UI" template and insert the confirmation message box in the Cancel button on-click handler.

Though, I really dislike "usual confirmation message box" user experience. 
You probably noticed that became a usual subject of numerous programming jokes :)

**Comment by rachelleP** [comment]
Do I need to create the confirmation message box me self? 
Isn't there a way to use the one that is part of the msi installer?

**Comment by oleg-shilo** [comment]
It might be, but I just don't know. Though. You are already using your own UI instead of MSI dialogs. I see no particular harm in using your own message-box instead of the one provided by MSI. Don't  you agree?

**Comment by BambiShi** [comment]
I just added one custom dialog, and all others I use MSI dialogs, thats why I want to use the standard confirmation window - so it should be the same behavior in all  dialogs

**Comment by oleg-shilo** [comment]
Fair enough.
Then try to find the answer in WiX knowledge base. There can be a fuilt-in standard action. Then you can simply invoke that action from your dialog.

**Comment by BambiShi** [comment]
Ok. I'll try to search for that.
Thanks for your help.
