### ISSUE TITLE
Passing data via SetupEventArgs.Data to AfterInstall handler

### ISSUE THREAD

**Issue by juvo64** [oleg-shilo/wixsharp#75]
Hi, 

I'm using a ManagedProject and try to pass information from the BeforeInstall event handler (by e. g. e.Data["Msi_BeforeInstall"] = "some value") to the AfterInstall event handler.
But in my AfterInstall handler there seems to be no e.Data["Msi_BeforeInstall"]. 
Data set in the Load event handler is available at AfterInstall.
Do I misunderstand the usage of SetupEventArgs.Data during the different phases?
How can I easily pass values from BeforeInstall to AfterInstall?

Thanks for your work and help.

**Comment by oleg-shilo** [comment]
It looks likes like tunneling data is broken.
Can you please do a simple test? 
- Set some data to the session properties from `BeforeInstall` event: 
    ```
    e.Session["Msi_BeforeInstall"] = "some value";
    ```
- Then push it from `Load` event: 
    ```
    e.Data["Msi_BeforeInstall"] = e.Session["Msi_BeforeInstall"];
    ```
- See if `Msi_BeforeInstall` data is available in `AfterInstall`

**Comment by juvo64** [comment]
I thought that the Load event occurs before the BeforeInstall event: in this case there won't be a e.Session["Msi_BeforeInstall"] when handling the Load event. 
Am I wrong with this?

**Comment by juvo64** [comment]
I've tested the following:
```
		static void Msi_Load(SetupEventArgs e)
		{
			e.Data["Msi_Load"] = "Done";
			e.Data["Test"] = "Msi_Load";
		}

		static void Msi_BeforeInstall(SetupEventArgs e)
		{
			e.Data["Msi_BeforeInstall"] = "Done";
			e.Data["Test"] = "Msi_BeforeInstall";
		}

		static void Msi_AfterInstall(SetupEventArgs e)
		{
			MessageBox.Show(e.Data.ToString(), "Data");
		}

```
In Msi_AfterInstall I only get:
...
Msi_Load=Done
Test=Msi_Load

**Comment by oleg-shilo** [comment]
My bad. You are right. Then this is just a defect.
Will be looking at it.

**Comment by oleg-shilo** [comment]
Fixed. Waiting for release.

**Comment by juvo64** [comment]
Done with v1.4.5. Many thanks.
