### ISSUE TITLE
Fix Extensions.Combine(this List<>, List<>)

### ISSUE THREAD

**Issue by xmarshal** [oleg-shilo/wixsharp#756]
Current implementation ignores first parameter.
https://github.com/oleg-shilo/wixsharp/blob/aab65d33ec036f21745617ebbdcc8abc88c0642e/Source/src/WixSharp/Extensions.cs#L2194-L2203

**Comment by oleg-shilo** [comment]
Done. Txs
```C#
public static List<T> Combine<T>(this List<T> obj, List<T> items)
{
    if (items != null)
        obj.AddRange(items);
    return obj;
}
```
