### ISSUE TITLE
How to store a value from a ElevatedManagedAction?

### ISSUE THREAD

**Issue by cocowalla** [oleg-shilo/wixsharp#760]
I'm using Managed UI, but on uninstall I need to perform some actions using a `ElevatedManagedAction` (I can't use `AfterInstall`, because I need to access the installed files, and they have already been removed with `AfterInstall` runs).

I'm defining the action using something like:
```c#
new ElevatedManagedAction(CustomActions.MyAction, Return.check, When.Before, Step.RemoveFiles, Condition.BeingUninstalled) { UsesProperties = "MY_PROPERTY" }
```

I need to set `MY_PROPERTY` in the action, so the value can be read in a *later* action.

Because this is a deferred action, I can't access the MSI session, so I tried using `session.CustomActionData["MY_PROPERTY"] = "MY_VALUE"` - however, when I try to read this property in a later action the value is always empty (the later action does also use `UsesProperties` as above).

Is there some way I'm missing that will allow storing and retrieving state across deferred actions?

**Comment by oleg-shilo** [comment]
Did you try 
```C#
project.DefaultDeferredProperties += ",MY_PROPERTY";
```
It may still not work as it is actually close equivalent of "UsesProperties".

Though I have checked and
`new ElevatedManagedAction(CustomActions.OnRemove, Return.check, When.Before, Step.RemoveFiles, Condition.BeingUninstalled)` can definitely access `INSTALLDIR` property without any problems:

```C#
public class CustomActions
{
    [CustomAction]
    public static ActionResult OnRemove(Session session)
    {
        session.Log("------------- " + session.Property("INSTALLDIR"));
        return session.HandleErrors(() =>
        {
            MessageBox.Show(session.Property("INSTALLDIR"));
        });
    }
}
```

**Comment by cocowalla** [comment]
I've also got no issues accessing `INSTALLDIR` - the action can access any session properties that were previously set using `session["MYERGEN"] = "WHATEVER"` in managed UI handlers - the problem is with `ElevatedManagedAction`, where values set using `CustomActionData` are not being persisted (or at least I can't access them in later actions).

I tried adding my property to `project.DefaultDeferredProperties`, but it made no difference.

**Comment by oleg-shilo** [comment]
Yes, it's an interesting problem.
I don't have the solution but I found a few interesting things about it.

The attached solution shows how to access deferred property value from both install and uninstall sequence. 

During install everything works as expected. The message box shows the user entered data for `PASSWORD` property. However.... on uninstall the very same property is displayed with its default value, not the one that the user entered.

I think the attached solution is a good playground for further investigations.

[WixSharp Setup12.zip](https://github.com/oleg-shilo/wixsharp/files/3783513/WixSharp.Setup12.zip)

**Comment by cocowalla** [comment]
Gah, I'm so tired of the restrictions and limitations of MSI!

So, I gave up. Well, kind of :smile:

Rather than work within the miserable constraints of session properties, I decided to work outside of them:

1. I have a POCO that represents the data I want during the install sequence

2. Early in the sequence (the managed `Load` handler), I create a temp file and serialise the POCO to it as JSON, as well as setting a session variable with the name of the temp file

3. Now in *all* further managed handlers or custom actions (immediate or deferred), I can read and write from/to the POCO without limitation (I have extension methods that make this super-simple)

This works beautifully!

**Comment by oleg-shilo** [comment]
That's exactly the direction where I would go too. 

"Don't climb the mountain, just go around".

MSI is such a stubborn and strong creature that it would withstand any creative troubleshooting or brainstorming an sadly.... continue misbehaving.
