### ISSUE TITLE
Execute embedded Binary from ManagedProject

### ISSUE THREAD

**Issue by MVKozlov** [oleg-shilo/wixsharp#761]
I want to execute embedded by `Binary()` exe file like in `Simplified Bootstrapper` sample

but from `ManagedProject()` custom UI

the sample use `session.SaveBinary()`

Is there any way to use it from `Runtime.Session` or some equivalent method ?

**Comment by oleg-shilo** [comment]
Yes, `session.SaveBinary()` and `Runtime.Session` are both referring almost to the same session object. This is what you need to do:

```C#
var msiSession = (Session)Runtime.Session.SessionContext;
msiSession.SaveBinary("WixUI_Bmp_Banner", "background.bmp");
```

**Comment by MVKozlov** [comment]
I try to do it but meet strange problem:
```
msiSession.SaveBinary("WixUI_Bmp_Banner", "background1.bmp");
msiSession.SaveBinary("WixUI_Bmp_Banner", "background2.bmp");
```
The second call fail with null reference.

Why ? How can I "rewind" this binary to save it multiple times ?

**Comment by MVKozlov** [comment]
I found it

`Fetch()` method returning `Record` object use the same object every time and requires the record to be freed (https://docs.microsoft.com/ru-ru/windows/win32/msi/view-fetch)
so `SaveBinary()` extension method should be rewritten like this
``` c#
    // parametrized version for safety (is it need ?)
    using (var sql = msiSession.Database.OpenView("select Data from Binary where Name = ?"))
    {
        using (var r = new Record(new string[] { binary }))
        {
            sql.Execute(r);
        }
        using (var record = sql.Fetch())
        {
            record.GetStream(1, file);
        }
    }
```
or with manual stream manipulation (why?)

**Comment by oleg-shilo** [comment]
Working with MSI database is tricky. This is what `SaveBinary` does:

https://github.com/oleg-shilo/wixsharp/blob/02d1ffc960b71855088be334832d3db15ebea0f3/Source/src/WixSharp/Extensions.cs#L2585-L2621 

I suspect that disposing `System.IO.Stream stream = sql.Fetch().GetStream(1);` has a chance of solving the problem but... kinda should not. Since every consecutive `SaveBinary` call fetches a new stream abandoning it without disposing should not be a problem. But who knows.

Let me know

**Comment by oleg-shilo** [comment]
Oh :)
We are looking at this problem at the same time.  

Did you test it with disposing?

**Comment by oleg-shilo** [comment]
Can you please test this complete version of the extension method:

```C#
public static void SaveBinary(this Session session, string binary, string file)
{
    using (var sql = session.Database.OpenView("select Data from Binary where Name = '" + binary + "'"))
    {
        sql.Execute();

        using (var record = sql.Fetch())
        using (System.IO.Stream stream = record.GetStream(1))
        using (var fs = new System.IO.FileStream(file, System.IO.FileMode.Create))
        {
            var Length = 256;
            var buffer = new Byte[Length];
            int bytesRead = stream.Read(buffer, 0, Length);
            while (bytesRead > 0)
            {
                fs.Write(buffer, 0, bytesRead);
                bytesRead = stream.Read(buffer, 0, Length);
            }
        }
    }
}

```

**Comment by MVKozlov** [comment]
Yes, I test it (as my own method) - it works
But why you do not want to use `record.GetStream(1, file);` ?

**Comment by oleg-shilo** [comment]
The reason is simple. Your code snippet came after I have updated the current implementation. Saying that your suggested alternative API makes sense. This is the current implementation:

```C#
public static void SaveBinary(this Session session, string binary, string file)
{
    using (var sql = session.Database.OpenView("select Data from Binary where Name = '" + binary + "'"))
    {
        sql.Execute();

        using (var record = sql.Fetch())
        {
            record.GetStream(1, file);
        }
    }
}
```
