### ISSUE TITLE
Handling resume from reboot in a custom ManagedUI

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#762]
From what I understand, bootstrappers are passed a `COMMAND` structure from WiX, which contains a way to tell if the installer is staging after a restart, as well as which package caused the reboot. Is it possible to access this data or something equivalent in Wix#? Rebooting during a package installation chain is something we expect to do relatively often.

As an aside, is there also a way to know which package is being installed and execute an action beforehand? Specifically, we are installing .NET 4.7.2 on a machine with no internet, so a Microsoft certificate must be installed into the root certificate store before setup will succeed, and I wanted to have a custom action of sorts do that right before .NET installation.

**Comment by oleg-shilo** [comment]
I suggest you have a look at _WixBootstrapper_NoUI_ or _WixBootstrapper_UI_ samples. They demonstrate how to implement `BootstrapperApplication` class. 

The events of this class (e.g. `DetectPackageComplete`) will be able to tell you when we resume and what package we are up to.

**Comment by sonicbhoc** [comment]
OH! I feel dumb now... I was following the tutorial for managed UI, but that is for MSIs and not bundles. Thanks for steering me in the right direction!
