### ISSUE TITLE
Starting application after MSI window closes

### ISSUE THREAD

**Issue by Jean-Marc1** [oleg-shilo/wixsharp#763]
I have the following managed action which starts an executable after installation but before the MSI installer window closes.  Is it possible to change this so that the executable is started after the user closes the MSI window?

ManagedAction restartAppAction = new ManagedAction(CustomActions.RestartApp, Return.check, When.After, Step.InstallExecute, Condition.NOT_Installed);
wixProject.AddAction(restartAppAction);

Thanks

**Comment by Jean-Marc1** [comment]
Regarding the above query, this was for a regular wix "Project".
I also tried a "ManagedProject" with a hook to the .AfterInstall event, but for this new attempt, I am facing the issue where the session properties are no longer available (the idea is that the executable path to run would be soft coded in a session variable).
So Method 1 ("Project" with custom action) is not ideal because the MSI window is still open when the executable is launched, and Method 2 ("ManagedProject") does not seem to allow for launching a soft coded executable path because the session variables are no longer available when the MSI window is closed...
Any ideas or workaround?  Thanks.

**Comment by oleg-shilo** [comment]
`AfterInstall` is a deferred action so the properties are not directly available. Thus you should use extension method (e.g. `session.Property("<property_name>")`. Or you can access the most important session properties directly in the event argument (e.g. `e.InstallDir`).

Though in your case (at least as you described it) you want your UI to be a trigger. Then you need to use "Custom UI" project VS template. Then you can simply hook up to the `Form.OnClose` and do your stuff.

**Comment by Jean-Marc1** [comment]
Tried the "Custom UI" project VS template, then...
1) added the WixSharp Nuget packages (including WixSharp.wix.bin)
2) added project.ControlPanelInfo.Manufacturer = "MyCompany" (to resolve "ICE39: Bad Type in Summary Information Stream for PID_AUTHOR")
3) Added before project.BuildMsi():
Compiler.WixLocation = @"C:\MyPath\WixSharp Setup2\packages\WixSharp.wix.bin.3.11.2\tools\bin"
On compiling / running, the error in #2 still shows up.  Upon debugging, assigning project.ControlPanelInfo.Manufacturer appears to have no effect.  The Manufacturer field is still set to my %Username% as if the line never executed...

**Comment by oleg-shilo** [comment]
The very last (~12h old) release had a nasty mistake that led to the problem with all `project.ControlPanelInfo` members. 

The fixed release has just been published. Let NuGet to index it and update your packages to v1.13.2.0.  

That should help.

**Comment by Jean-Marc1** [comment]
Upgrading to v1.13.2.0 resolved the issue.

Now trying to figure out:
1) how to have an install that does not create multiple entries in control panel for each version (I have wixProject.MajorUpgradeStrategy = MajorUpgradeStrategy.Default).  Basically for a simple install that add/update files in one directory.

2) how to customize the prompts/labels in my ManagedProject (I have labels in square brackets but could not find where the text is coming from)... with the future goal of being able to use localization.

If you have any pointers... thanks!

**Comment by Jean-Marc1** [comment]
Aside from this, I could be mistaken but it seems that the exit form that is derived from ManagedForm does not trigger the FormClosed or FormClosing event.
This is an issue because even though I can launch an application when the Finish button is clicked, it won't work if the MSI exit screen is closed via the 'X' button or Alt-F4...

**Comment by oleg-shilo** [comment]
MSI is does not make it easy.

**Problem 1** 
The simplest way to solve your problem is to capture the required property in the `OnLoad` event handler:
```C#
string installDir;
void ExitDialog_Load(object sender, System.EventArgs e)
{
    installDir = Runtime.Session.Property("INSTALLDIR");
    image.Image = Runtime.Session.GetResourceBitmap("WixUI_Bmp_Dialog");
    . . . 
```

And of course there is another pure programming possibility :)

You don't even need to use the session object. Your whole UI is in your codebase. Have a class (e.g. `MyRuntime`) with the static variable, which is assigned in the InstallDir dialog ad then use this variable in the ExitDialog. That's it.

**Comment by oleg-shilo** [comment]
**Problem 2**
The labels with `[<WIX localization Id>]` content are automatically resoled/substituted by the WixSharp runtime with the values of that Id from the WiX/MSI localization file embedded in the MSI. I can guide you how to get the localization right but if you are only targeting one language then simply use that language in your labels without square brackets. Then it will be rendered as is.

**Comment by oleg-shilo** [comment]
**Problem 3**

My bad, indeed your dialog is not a top level form but a child of the main window "Shell". Thus you need to intercept it's closing event.

I don't remember but probably you can access the top form by traversing up with `form.Parent`. If not then you can subscribe for any UI event and access Shell form directly:

```C#
static void msi_UILoaded(SetupEventArgs e)
{
    (e.ManagedUIShell as Form).Closed += . . .    
```

**Comment by Jean-Marc1** [comment]
Thanks, I'll try the above proposed solutions.
I'll take any guide/advice regarding localization :)  We'll do need two languages...
Thanks!

**Comment by oleg-shilo** [comment]
Then have a look at `<wixsharp>\Source\src\WixSharp.Samples\Wix# Samples\Managed Setup\CustomUIDialog` sample which injects a dialog into German culture msi solution.

The sample shows how to use `[...]` labels in the custom dialog and how to embed custom localization file (_WixUI_de-de.wxl_)

**Comment by Jean-Marc1** [comment]
Regarding "Problem 3", I do not see any Parent property for the form.
I also tried:
```
wixProject.UILoaded += WixProject_UILoaded;

private void WixProject_UILoaded(SetupEventArgs e)
{
       (e.ManagedUIShell as Form).Closed += WixMSI_Closed;   //shows as "deprecated"
       //(e.ManagedUI as Form).Closed += WixMSI_Closed;
}

private void WixMSI_Closed(object sender, EventArgs e)
{
       MessageBox.Show("WixMSI_Closed");
}

```

But WixMSI_Closed() never gets hit.

**Comment by Jean-Marc1** [comment]
Regarding "Problem 1", I have:

```
Property exeToRunProperty = new Property("RUNAFTERINSTALL", @"C:\MyExeToRun.exe");
wixProject.AddProperty(exeToRunProperty);
```
As you mentionned, I am able to see the property from the WelcomeDialog and the ProgressDialog, but **not** on the ExitDialog:

```
void ExitDialog_Load(object sender, System.EventArgs e)
{
         MessageBox.Show("ExitDialog_Load");   //this works
         string RUNAFTERINSTALL = Runtime.Session.Property("RUNAFTERINSTALL");
         MessageBox.Show("ExitDialog_Load / RUNAFTERINSTALL=" + RUNAFTERINSTALL);   //this does not show indicating the previous line crashed accessing the session variable (unlike the other screens)
         ...
```
So it appears the session variables may no longer be available on the exit screen after the installation (?).

As for assigning a static variable, it would not work in my case because I would like the RUNAFTERINSTALL value to be assigned dynamically (soft coded) when the MSI is built.
The best workaround I found so far for Problem 1 was to save that value to the registry and get it back when the MSI completes the installation, so I can run my executable.

**Comment by Jean-Marc1** [comment]
Regarding Problem 3, it seems to work provided WixProject_UILoaded() is made static!
Thanks.

**Comment by oleg-shilo** [comment]
_Problem 3_
Yes, it needs t be either static or lambda, which is a static method of a hidden dynamically generated class. There is no other way. That's why all the samples are using it this way. 

_Problem 1_
This is what I meant "You don't even need to use the session object. Your whole UI is in your codebase. Have a class...". 

MSI can retire the session object at any time. This is the design problem with MSI architecture. It's rather an embarrassing blander from MS side. Thus NONE of the deferred actions can access even a single session property. That's why WiX has provided the session object that contains no property and throws if you try to access it.

In case of deferred actions there is a convoluted work around - `CustomActionData`. WixSharp makes it easier to use but I cannot recommend it as in your case the session can be truly disposed.

You will need to have some global data where you store your property:

```C#
class Globals
{
    public static string AfterInstallProp;
}

. . .

project.Load += (SetupEventArgs e)=>
{
    Globals.AfterInstallProp = e.Session.Property("RUNAFTERINSTALL");
};

. . . 

void ExitDialog_Load(object sender, System.EventArgs e)
{
     MessageBox.Show("ExitDialog_Load / RUNAFTERINSTALL=" + Globals.AfterInstallProp);
     
```

**Comment by oleg-shilo** [comment]
Forgot to mention.

In order to ensure your `Global` is loaded in the right assembly context it's arguebly better to set the variable in the same UI context as where you retentive that variable:
```C#
void ProgressDialog_Load(object sender, System.EventArgs e)
{
    Globals.AfterInstallProp = Runtime.Session.Property("RUNAFTERINSTALL");
};
```

**Comment by Jean-Marc1** [comment]
Thanks, that helped!
