### ISSUE TITLE
User pressed No on UAC Dialog

### ISSUE THREAD

**Issue by MVKozlov** [oleg-shilo/wixsharp#764]
I have issue Like in #363 

But because I try to make localized installation (I think) `Shell.Log.Contains("User cancelled installation.")` doesn't work for me. Log contains localized message (but error level still `2`)

Any workarounds ?

**Comment by oleg-shilo** [comment]
Yeah, detecting user cancellation is a challenge. 
And , yes you found it right, the default implementation relies on the message in English, which is of course will not work for other languages:

https://github.com/oleg-shilo/wixsharp/blob/25b9d35385e07524b182d29a41db9deab66c30a2/Source/src/WixSharp.UI/ManagedUI/Forms/ExitDialog.cs#L22-L46

Of course you can re-implement the ExitDialog for Russsian. Even though it's not an elegant solution it will work.
