### ISSUE TITLE
Session properties in Repair mode

### ISSUE THREAD

**Issue by Jean-Marc1** [oleg-shilo/wixsharp#767]
I have a custom action which executes when the MSI is launched:
`ManagedAction setRegistrySettingsAction = new ManagedAction(CustomActions.SetRegistrySettings, Return.check, When.Before, Step.CostInitialize, Condition.NOT_BeingRemoved);`

When the install runs, I can interrogate a command line property and it returns a value:
`session.Property("DISABLEAUTOUPDATES")`

In repair mode, that same session property on the command line does not return any value.
`MsiExec.exe /fvamus "{XXXXXXXX …. XXX}" /quiet /norestart /l*vx ".\repair.log" DISABLEAUTOUPDATES=1`

Is it by design?
Thanks!

**Comment by oleg-shilo** [comment]
I am afraid so :)

But make no mistake, by **MSI** design. WixSharp cannot change MSI behavior in this case. If the property is not available even though it is supplied as the command line param, I am afraid there is nothing that can be done about it. Unless of course there is some MSI trick that you can potentially find on MSI forums.
