### ISSUE TITLE
DeferredProperties with semicolon

### ISSUE THREAD

**Issue by juvo64** [oleg-shilo/wixsharp#77]
Hi,

if I have a property with a value containing a semicolon (e. g. a connection string), the value gets truncated in the AfterInstall event:
```
var project = new ManagedProject("MyProduct",
...
	,new Property("TEST", "a;b"));

project.DefaultDeferredProperties += ",TEST";

...

static void Msi_AfterInstall(SetupEventArgs e)
{
	MessageBox.Show(e.Session.Property("TEST"));
}

```
Here the dialog shows "a" instead of "a;b".

Thanks for your help

**Comment by oleg-shilo** [comment]
MSI uses `session.CustomActionData` to store the properties for the deferred action. `session.CustomActionData` uses `;` as a values delimiter. Thus it needs to be be escaped:  

![image](https://cloud.githubusercontent.com/assets/16729806/26477870/e80ea2e4-420b-11e7-8eaa-59f77879dff4.png)

When WixSharp assigns values to its own properties to be tunneled to the deferred action AfterInstall event (e.g. session.Data) it always escapes them and unescapes when they are delivered.

In your case it is the user who assigns the value so WixSharp doesn't risk altering/escaping the user property automatically as it may contradict with the user expectations. 

A good solution would be to perform on-fly escaping/unescaping when the data is pushed to and read from CustomActionData structure. However it is in WiX codebase and there is nothing WiXSharp can do about it. Actually it is a good WiX enhancement proposal.

Thus you need to modify your code:
```C#
new Property("TEST", "a;b".EscapeKeyValue()));
...

static void Msi_AfterInstall(SetupEventArgs e)
{
	MessageBox.Show(e.Session.Property("TEST").UnescapeKeyValue());
}
```

**Comment by juvo64** [comment]
Hi Oleg,

thank you very much for WixSharp and your fast support :-)  
Great job!

**Comment by oleg-shilo** [comment]
You are very welcome :)
