### ISSUE TITLE
default REINSTALLMODE

### ISSUE THREAD

**Issue by TheToughGuy** [oleg-shilo/wixsharp#771]
Hi,

The MSI documentation states that the default for REINSTALLMODE is "omus", however when we did not set this explicitly in our Wix sharp project then the generated wxs was 
    `<Property Id="REINSTALLMODE" Value="amus" />`

This causes the installfinalize stage to generate `info 1603` notices and take considerably longer to install as a result when merging things into system etc.

The workaround is fine for us now we know but wanted to make you aware

**Comment by jzabroski** [comment]
@TheToughGuy Where is that documentation located?  Thanks.

**Comment by TheToughGuy** [comment]
https://docs.microsoft.com/en-us/windows/win32/msi/reinstallmode

**Comment by oleg-shilo** [comment]
Makes sense. The current default value is set as the result of the WixSharp user suggestion being taken to account (https://github.com/oleg-shilo/wixsharp/issues/638). But I agree MSI doc is arguably a better  spec.
