### ISSUE TITLE
Extensions.DeleteIfExists does not delete folders

### ISSUE THREAD

**Issue by xmarshal** [oleg-shilo/wixsharp#772]
https://github.com/oleg-shilo/wixsharp/blob/3bc38329e2933266ec96b220cb5dc6a3d922e974/Source/src/WixSharp/Extensions.cs#L971

According xml doc this method should delete existing files and directories.
System.IO.File.Exists returns false for directories.
Should it support recursive directories deletions?

**Comment by oleg-shilo** [comment]
It is a mistake in the documentation. This extension method is ever used only for deleting the files.
However since it is public it's only logical to extend it to handle directories too.

Done (https://github.com/oleg-shilo/wixsharp/commit/a8424fed4affd575f5883f38279dfe81bfd7ef79)
