### ISSUE TITLE
CustomUI, "second" license dialog

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#773]
on the way porting an existing msi based setup to Wixsharp I am stucked at a point. The old system had 2 license dialogs; actually one for the real software license whereas the second one is actually the data policy. 
Anyway both dialogs only differs in the file been shown but both will need the confirmation been checked before going ahead. The system just uses two SdLicense2 calls. As WixSharp brings the lic-file to the project-level I have no idea how to have the same functionality here.

Any help appreciated.

best Carsten

**Comment by oleg-shilo** [comment]
Adding another file it's not a problem. You can always add it as `binary`.
The actual question is how this second dialog was implemented and the licence/policy content injected into it.

Of course if you use ManagedUI it's very easy but if you are using the native dialog you will need to analyse the original wxs and see what is missing in the wxs generated by WixSharp. This will give you the clue.

**Comment by hcarsten** [comment]
Thanks for the answer. The "original" setup is actually an InstallShield solution (and about 15years old :) ). And yes we are going with the native MSI solution as we currently still having trouble to make a translation to German running. Works fine in the MSI but not in the ManagedUI.
Anyway first is just to a  1:1 replacement for the current setup.
Is there any sample of how "duplicate" a nativeUI dialog in WixSharp ?

best Carsten

**Comment by oleg-shilo** [comment]
Yes, you just create a VS project from the "WixSharp...- Custpm UI" template and it will be obvious from the how to add an extra dialog in whatever place in the UI sequence you want.

And for the localization, see CustomUIDialog sample. It inserts an extra dialog to the German setup with ManegedUI.

**Comment by hcarsten** [comment]
ok, got both things done, so can inject the second dialog and have the UI in German. Last thing missing is how to load the second rtf and show it in the dialog ?

best

Carsten

**Comment by oleg-shilo** [comment]
> ... how to load the second rtf and show it in the dialog? 

You just add your file a s`Binary`:
```C#
var project = new Project("MyProduct",
                  . . .
                  new Binary(new Id("myRtf"), @".\files\manual.rtf")
                  . . .

// and then in the runtime handler/action
session.SaveBinary("myRtf" , <temp file>);
```
