### ISSUE TITLE
Getting reboot request which is not skippable

### ISSUE THREAD

**Issue by marcobeninca71** [oleg-shilo/wixsharp#775]
Hello Oleg
I'm using WixSharp for my installation package for a while and lately sometime (not at each installation) I get a dialog window (coming from windows installer system I think) which prompt the user to reboot. The strange think is that if the user click on cancel to skip rebooting the system reboot itself anyway. This of course can generate loose of unsaved data.
The strange thing is that my installation doesn't touch any system file and all my files are installed into a specific folder inside "Program Files".
Any suggestion on how to avoid this situation?
Marco

**Comment by Torchok19081986** [comment]
Hallo, same problem. I found out , that if windows currently , in 2 or 3 days ago, windows updates are installed on targetsystem. It appers after installation in MSI not skippable reboot request. SQL Server Installation do this always. I do know if you can do something against it . Try to detect if system need reboot. I thinlk Windows Regsearch can be done before installation of your product starts. Somewhere in Registry exitst value. Create a CA and Custom Property like [REBOOT] and return a value from it, can be done. Do someting with value, resume the Installation or prompt Messagebox etc.

**Comment by oleg-shilo** [comment]
Hi Marco, I don't have a specific answer but I do know that MSI can decide to reboot even though the installation did not do any request for that and there is nothing obvious reason for that.
