### ISSUE TITLE
External UI and upgrades

### ISSUE THREAD

**Issue by BillHenning** [oleg-shilo/wixsharp#778]
Hello, I'm using a WPF-based external UI.  I'm running into a scenario where I want a newer build (e.g. v4.0.101) to be able to "upgrade" an older build (e.g. v4.0.100) of the same major.minor version if it's installed.

I have the same Project.GUID set (which will never change) and the same Project.ProductId set since they are the same v4.0.  Note that I would change ProductId for a v5.0.

The problem is that when I run my external UI, it's detecting that the product code is already installed and gives me CanInstall = false and CanUninstall = true via WixSharp.Msi.  Because of that, I switch my external UI into "Remove" mode.  If the user clicks the button to remove, then it does a StartUninstall call, but here I get MSI error 1638 saying another product version is already installed and a failure message is shown.

What I'd prefer to do is have the WixSharp.Msi somehow tell me that here's a scenario where an upgrade is possible so I could add an "Upgrade" mode to my external UI.  Then somehow kick off an upgrade on the MSI, uninstalling build 100 and installing build 101.  

Do you have any tips for how I can improve this user experience?  Ideally I could have the installer for the newer build in "Upgrade" mode in this scenario.  But if that's not possible, I'd like it to be able to at least remove the older build without error 1638.

Thanks!

**Comment by Xaddan** [comment]
Are you using `AllowSameVersionUpgrades`?
```C#
project.MajorUpgrade = new MajorUpgrade
{
    AllowSameVersionUpgrades = true,
    Schedule = UpgradeSchedule.afterInstallInitialize,
    DowngradeErrorMessage = "A later version of [ProductName] is already installed. Setup will now exit."
};
```

**Comment by BillHenning** [comment]
Hello, thanks for the reply, but my question is more related to the API in the WixSharp.Msi assembly.  That is the assembly that external UIs (such as our WPF-based one) can use to get some initial MSI information and kick off a MSI install/uninstall.  We need something there to help us determine if we are in an upgrade scenario and then if so, have some kind of StartUpgrade method.  Nothing seems to currently be available in that area though.

The Project.MajorUpgrade you mentioned is more about creation of the actual MSI, which would definitely be important if we get past the external UI issue.

**Comment by oleg-shilo** [comment]
You will need to analyze both `UpgradeCode` and `Version`. _WixSharp.Msi.dll_ does have API for retrieving this data.  
The same `UpgradeCode`  and different `Versions` means the product can be upgraded.

**Comment by BillHenning** [comment]
Hi Oleg,

If I can somehow detect when there is an old version installed already, how would I use WixSharp.Msi.dll to start an "upgrade" procedure as opposed to pure StartIinstall() and StartUninstall()?

**Comment by oleg-shilo** [comment]
Ah, that is relatively easy. From msi starting point of view you can only install and uninstall. Upgrading is an install-scenario. Simply the new msi triggers automatic uninstall of the old product and installing a new one.

Though in this case your msi must be carefully build so it supports upgrading scenarios. see @Xaddan post up here.

**Comment by BillHenning** [comment]
Thank you, I think I have it sorted out now.
