### ISSUE TITLE
Assembly loading

### ISSUE THREAD

**Issue by jfiuza** [oleg-shilo/wixsharp#782]
Hello, 
I'm using wixsharp and i have the current security problem:

When running the exe installer. A lot of assemblies are loaded from where the exe is installed(ex. igdgmm32.dll, aurora.dll, etc.) and sometimes it would even search dll on all PATH directories. I noticed that msi version loads much less. 
From what i've seen they are mostly drivers and UI related so they might change from pc to pc. 

This would lead to a security issue due to DLL hijacking.

I wanted to know if there is some way to avoid this dll loading or at least before loading the dll we could copy it to a new temp directory.

Many thanks,
Joao

**Comment by oleg-shilo** [comment]
WixSharp does implement custom assembly probing but only during compile time and only for a specific assembly. And also it loads the assembly from its own resources. Inelegant but very reliable safe way:

```C#
Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
{
    return Assembly.Load(WpfSetup.Properties.Resources.WixSharp_Msi_dll);
}
```
Thus if you can see unexpected dlls being loaded at runtime then the answer is likely in the MSI runtime implementation and the PC auto-load policies.

Thus if you have this problem with managed UI then likely these assemblies are loaded by the "EmbeddedUI" hosing provided by WiX hosting. If it is when you do native UI then it's likely to be an MSI thing.

But to be honest it's difficult to make any judgement in this case until you know the managed and non managed libs that are loaded are loaded for the **wrong** reason.  

For example if you install a clever app that places a special button on a title bar of all windows the all UI processes will load this app assembly/dll.
