### ISSUE TITLE
Temporary Files Not Deleted After Successful Build

### ISSUE THREAD

**Issue by rkyoto** [oleg-shilo/wixsharp#783]
With latest release, temporary files are not deleted after a successful build.

It seems that the cleanup function was [recently modified](https://github.com/oleg-shilo/wixsharp/commit/a8424fed4affd575f5883f38279dfe81bfd7ef79?diff=split)

```
            if (path.IsDirectory())
            {
                IO.Directory.GetFiles(path, "*", IO.SearchOption.AllDirectories)
                            .ForEach(deleteFile);

                IO.Directory.GetDirectories(path, "*", IO.SearchOption.AllDirectories)
                            .OrderByDescending(x => x)
                            .ForEach(deleteDir);

                deleteDir(path);
            }
            else
            {
                deleteDir(path);
            }
```

Looks like the last deleteDir() should actually be deleteFile()

**Comment by oleg-shilo** [comment]
You are absolutely right. It is a defect.
Corrected. Will be available in the very next release.

Let me know if this problem affects you and I will make a HotFix release

**Comment by rkyoto** [comment]
Thanks for the reply. We are currently fine with 1.13 version.
