### ISSUE TITLE
EmbeddedUI does not work together with custom actions

### ISSUE THREAD

**Issue by martinsXXX** [oleg-shilo/wixsharp#788]
It seems that a project that uses custom actions AND EmbeddedUI does not compile to msi. This error appears:
{"Cannot package ManagedCA assembly(<...omitted..>\\EmbeddedUI_WPF\\bin\\Debug\\EmbeddedUI_WPF.exe)"}
MSI generation succeeds, when I comment out the line with the EmbeddedUI = or the static class CustomActions.

See zip file for problem demonstration:
[EmbeddedUI_WPF_Upload2.zip](https://github.com/oleg-shilo/wixsharp/files/3974485/EmbeddedUI_WPF_Upload2.zip)

Question1: Is this a limitation of embedded UI? 

We need to build a setup with custom UI (WPF), we derived it from your CustomUI-WPF example. And we need to run one of the installed files with admin-elevation, and with parameters that depend on the user input in the WPF setup wizard. We thought we should do this via CustomAction or ElevatedCustomAction.

Question2: What is the best way to achieve this in a project with embeddedUI?

**Comment by oleg-shilo** [comment]
Can you please test it with `Compiler.ClientAssembly = System.Reflection.Assembly.GetExecutingAssembly().GetLocation();` work around. I suspect `FindClientAssemblyInCallStack` failure derails the whole build.

**Comment by martinsXXX** [comment]
Thank you.
I have done that (see attached new version of project) but the error message still persists.


Mit freundlichen Grüßen, 
i.A. Martin Schöllhammer
Digitale Diagnostik Software
Dürr Dental SE
Tel.-175, Fax -4000175
mailto: schoellhammer.m@duerr.de 



----------------------------------------------------------------
DÜRR DENTAL SE
Höpfigheimer Str. 17
74321 Bietigheim-Bissingen
Deutschland / Germany
Tel. + 49 (0) 7142 / 705-0
Fax + 49 (0) 7142 / 705-500
http://www.duerrdental.com
Join us on Facebook http://www.facebook.com/DuerrDental

Firmensitz / Registered Office:
Höpfigheimer Str. 17, 74321 Bietigheim-Bissingen
Handelsregister / Register of Commerce: Amtsgericht Stuttgart HRB 763587

Vorstand / Executive Board: Martin Dürrstein (Vorsitzender / CEO), Joachim Eppinger, Stefan Pfanzelt, Christian Schorndorfer
Vorsitzender des Aufsichtsrates / Chairman of the Supervisory Board: Bernhard Oberschmidt

>>> Oleg Shilo <notifications@github.com> 18.12.19 13:29 >>>
Can you please test it with Compiler.ClientAssembly = System.Reflection.Assembly.GetExecutingAssembly().GetLocation(); work around. I suspect FindClientAssemblyInCallStack failure derails the whole build.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
( https://github.com/oleg-shilo/wixsharp/issues/788?email_source=notifications&email_token=ALGYQVXSEWUNA5EVYO2SLFTQZIJRHA5CNFSM4J36ZCP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHF6UPY#issuecomment-567011903) , or unsubscribe

**Comment by oleg-shilo** [comment]
The actual error is shockingly direct:
```
Searching for an embedded UI class in EmbeddedUI_WPF.exe
Error: System.NotSupportedException: CA and UI entry points cannot be in the same assembly:
```
It is yet another case of WiX compilers being over restrictive. I see no reason whatsoever for preventing  CA and UI entry points being implemented in the same assembly. 

Yet, interestingly enough, when build  EmbeddedUI_WPF sample from WixSharp source it works just fine.

As a starting point you may want to try and see if the unchanged EmbeddedUI_WPF sample works on your system.

**Comment by oleg-shilo** [comment]
Ah... of course! Instead of raw custom action I used events:
```C#
static void Main()
    {
        var project =
            new ManagedProject("EmbeddedUI_Setup",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File("readme.txt")));

        project.EmbeddedUI = new EmbeddedAssembly(sys.Assembly.GetExecutingAssembly().Location);

        project.CAConfigFile = "CustomAction.config"; // optional step just for demo
        project.PreserveTempFiles = true;
        project.BeforeInstall += Project_BeforeInstall;
        project.BuildMsi();
    }

    private static void Project_BeforeInstall(SetupEventArgs e)
    {
    }
```

Events are just super-charged CAs but since they are invoked from WixSharp runtime it allows bypassing this silly WiX restriction.

I suggest you do the same. Otherwise you need to implement your CS in adifferent assembly just to keep WiX compiler happy.

**Comment by martinsXXX** [comment]
OK thank you very much, this helps!

From my original post,  I apologize to have this further question: 
What's the best way to run one of the installed files with parameters that come from the user input made in the wizard dialog? Should I put that directly in the AfterInstall? Does this still run with administrative privileges (I need that)?

My idea was to define an InstalledFileAction that uses as params the value of a property, then set that property in the ProjectOnBeforeInstall with the  value from the user. Then I excpected the Action would use this userinput as param, but it doesn't.
I have implemented that in the example attached. The Session property "USERINPUT" is changed ( messageboxes prove that), but the action, afterwards, runs with the default value. 
Seems I have some wrong understanding of the way Wix / properties work, 


Mit freundlichen Grüßen, 
i.A. Martin Schöllhammer
Digitale Diagnostik Software
Dürr Dental SE
Tel.-175, Fax -4000175
mailto: schoellhammer.m@duerr.de 



----------------------------------------------------------------
DÜRR DENTAL SE
Höpfigheimer Str. 17
74321 Bietigheim-Bissingen
Deutschland / Germany
Tel. + 49 (0) 7142 / 705-0
Fax + 49 (0) 7142 / 705-500
http://www.duerrdental.com
Join us on Facebook http://www.facebook.com/DuerrDental

Firmensitz / Registered Office:
Höpfigheimer Str. 17, 74321 Bietigheim-Bissingen
Handelsregister / Register of Commerce: Amtsgericht Stuttgart HRB 763587

Vorstand / Executive Board: Martin Dürrstein (Vorsitzender / CEO), Joachim Eppinger, Stefan Pfanzelt, Christian Schorndorfer
Vorsitzender des Aufsichtsrates / Chairman of the Supervisory Board: Bernhard Oberschmidt

>>> Oleg Shilo <notifications@github.com> 18.12.19 14:05 >>>
Ah... of course! Instead of raw custom action I used events:
static void Main() { var project = new ManagedProject("EmbeddedUI_Setup", new Dir(@"%ProgramFiles%\My Company\My Product", new File("readme.txt"))); project.EmbeddedUI = new EmbeddedAssembly(sys.Assembly.GetExecutingAssembly().Location); project.CAConfigFile = "CustomAction.config"; // optional step just for demo project.PreserveTempFiles = true; project.BeforeInstall += Project_BeforeInstall; project.BuildMsi(); } private static void Project_BeforeInstall(SetupEventArgs e) { }
Events are just super-charged CAs but since they are invoked from WixSharp runtime it allows bypassing this silly WiX restriction.
I suggest you do the same. Otherwise you need to implement your CS in adifferent assembly just to keep WiX compiler happy.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
( https://github.com/oleg-shilo/wixsharp/issues/788?email_source=notifications&email_token=ALGYQVVT65FUK67CZAFAHLTQZIN3LA5CNFSM4J36ZCP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHGBM2Q#issuecomment-567023210) , or unsubscribe

**Comment by oleg-shilo** [comment]
Yes `AfterInstall` runs always elevated so it is an ideal spot for running any installed executable.

Be aware that due to the MSI (not WiX) limitation all MSI properties are inaccessible from elevated/deferred CAs. Thus they need to be tunneled there in a special way. 

You will need to nominate these properties:
```C#
project.DefaultDeferredProperties += ",USERINPUT";
``` 

An then you can access them:
```C#
static void Project_AfterInstall(SetupEventArgs e)
{
    var userInput = e.Session.Property("USERINPUT")
    ...
```

See "DeferredActions" sample for more details

**Comment by martinsXXX** [comment]
Thank you very much, finally it works. It took some time, till I realized that I have to use 
var v = e.Session.Property("USERINPUT");
from the deferred- example, instead of 
var v = e.Session["USERINPUT"]; 
to make it work .

**Comment by oleg-shilo** [comment]
That's why I used in my last post `var userInput = e.Session.Property("USERINPUT")` :o)

This is the only reliable way to access the session variables. I had to introduce this extension method as using that ridiculous indexer-based WiX model is truly asking for troubles.
