### ISSUE TITLE
How to set the visible attribute of MsiPackages in a bootstrapper bundle

### ISSUE THREAD

**Issue by juvo64** [oleg-shilo/wixsharp#79]
I want to use a bootstrapper to install prerequisites for my application.
By default the installed packages (e. g. sqlncli.msi) don't appear in "programs and features".
I think the "visible attribute of WIX-MsiPackage" is the solution. 
There seems to be no direct access by Wix#.
Do I have to do this by XML modification in a bootstrapper.WixSourceGenerated event?

Thanks for hints

**Comment by oleg-shilo** [comment]
It is a mistake. The `Visible` property needs to be a part of `MsiPackage` class.
The problem has been fixed and the fix will be available in the next release.

In a meantime you can use the following work around: 
```C#
new MsiPackage(<path>) { AttributesDefinition = "Visible=yes" },
```

**Comment by juvo64** [comment]
Thank you, Oleg.

**Comment by oleg-shilo** [comment]
Not a prob :)

**Comment by juvo64** [comment]
Should be done with the new release(s)

**Comment by oleg-shilo** [comment]
Yep, done in [Release v1.4.6.1](https://github.com/oleg-shilo/wixsharp/releases/tag/v1.4.6.1)
