### ISSUE TITLE
Question: External UI document

### ISSUE THREAD

**Issue by DimaS86** [oleg-shilo/wixsharp#795]
Hi Oleg! Thank you for such a great product. I have an external UI project with WPF windows. One of the forms has to show some license document (in rtf format). How do I attach it to the bundle or bootstrapper application? I tried to include it into Payloads of the ManagedBootstrapperApplication, as
bootstrapper.Application = new ManagedBootstrapperApplication("%this%", "BootstrapperCore.config") { Payloads = new Payload[] { new Payload("License_12-08-2018.rtf") } },
but this line does something weird to the BootstrapperCore.config file and my app doesn't run anymore. I copy and paste the old bootstrappercore.config and everything is ok. Thanks in advance for your answer.

**Comment by oleg-shilo** [comment]
Thank you, I am glad you like WixSharp.

To be honest I would go with a simple rosource content embedded in your assembly. Read it and display it in your form/wpf_window.

Though I  not sure I fully follow your scenario. You said "External UI project" but but this project is for an external UI of an MSI that has nothing to do with Bootstrapper. In fact Bootstrapper is an alternative stock implementation of an External UI that can handle multiple MSIs.

So I am a bit lost...

**Comment by DimaS86** [comment]
Thank you for your answer. I did a workaround with an embedded xaml resource and it worked fine. 
Just in case there was another solution. I wrote a class, inheriting from BootstrapperApplication, just as in WpfSetup example, with multiple msi and exe packages. As I understand, I needed to somehow embed that resource into that application. And I didn't know how to do it with a .rtf file.

**Comment by oleg-shilo** [comment]
Yes you do need to implement your custom BootstrapperApplication. 
And when you do so you will need to add to your BA assembly a normal resources file with your rtf. The usual way as you do it with any .NET assembly.

**Comment by DimaS86** [comment]
Thank you very much for your help, now I understand what I need to do.
