### ISSUE TITLE
Wix# code that generates typelib tags?

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#797]
What would Wix# code look like that outputs this?

[NeoCalendarReg.txt](https://github.com/oleg-shilo/wixsharp/files/4148756/NeoCalendarReg.txt)

I see a ComRegistration class, but not anything for implementing a TypeLib. Is this supported? If not, how can I inject this fragment into my wix# output?

**Comment by oleg-shilo** [comment]
You can inject raw XML by any of the techniques demonstrated in this sample https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/InjectXML/setup.cs

**Comment by sonicbhoc** [comment]
Thank you!
