### ISSUE TITLE
*.g.wxs file is added twice to solution

### ISSUE THREAD

**Issue by jwfx** [oleg-shilo/wixsharp#799]
Version: 1.14.2

I was wondering why in Visual Studio Solution Explorer the *.g.wsx file was showing up twice.

After building there are two lines added to the .csproj file:
````
    <None Include="wix\`MyProgramSetup.g.wxs" />
    <None Include="wix\$(ProjectName).g.wxs" />
````

This seems redundant. Is this because of misconfiguration somehow?

**Comment by oleg-shilo** [comment]
There was an update to the project templates that addressed some nuget importing side-effects. Can you check please that you are using the latest WixSharp VS project templates (https://marketplace.visualstudio.com/items?itemName=OlegShilo.WixSharpProjectTemplates). If you don't then update the templates. It may just fix the problem.

But if you do then please create a new project and send here the project files. Do this before attempting to build the project.

**Comment by jwfx** [comment]
I have this issue with an existing project. I updated the WixSharp NuGet packages manually to the above version. Right now I don't even have any templates installed after switching VS versions.

Is there a way to tell with which template version the project was created?

**Comment by oleg-shilo** [comment]
>  I updated the WixSharp NuGet packages manually...

I need to clarify. 
- WixSharp NuGet package adds WixSharp compilers to the VS project.
- WixSharp VS extension brings VS project templates for building WixSharp compiled MSIs.

> Is there a way to tell with which template version the project was created?

Not really.

Why don't you just install VS extension, create project from the template, add the nuget package and you are done.

And if you are truly keen to fix your existing project then just remove ` <None Include="wix\$(ProjectName).g.wxs" />` from your project file manually.

**Comment by jwfx** [comment]
A new project does not help me, as I encounter this issue in a production installer project.

If I remove the line ` <None Include="wix\$(ProjectName).g.wxs" />`  and rebuild the project, it is readded after the build finishes.

**Comment by jwfx** [comment]
Looks like this was some conflict with Visual Studio.

When I removed both lines, then both were re-added after building.

When I removed both lines, then closed and relaunched VS and started a build only the line with `$(ProjectName)` was added again.

Just to confirm:

https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp/Compiler.cs#L319

The expectation for this part of the code is that, this line is added to the project
`    <None Include="wix\$(ProjectName).g.wxs" />`
and NOT this
`    <None Include="wix\MyProgramSetup.g.wxs" />`
correct?

**Comment by oleg-shilo** [comment]
>  this line is added to the project ... and NOT this ... correct?

:) Yep, I was relying on my memory in this case. And apparently it wasn't as good as I thoiught.

**Comment by jwfx** [comment]
Great, thank you for your time.
