### ISSUE TITLE
Arguments are not supported on FileShortcut

### ISSUE THREAD

**Issue by lamesjinden** [oleg-shilo/wixsharp#8]
Oleg,

I'm unable to utilize the Arguments property on a FileShortcut instance. I took a peek at Compiler and it looks like the property is not being translated.

Thanks,
-james

**Comment by oleg-shilo** [comment]
Thank you. Indeed it is a defect.
Fixed with commit 6384ad9bccf15e477979f41b1e2b12e1a58523cf.
The fix will be available in the next release. Alternatively you can grab binaries from GitHub sources (samples dir).

**Comment by oleg-shilo** [comment]
Fixed in release v1.3
