### ISSUE TITLE
No FileSearch example or DirectorySearch element?

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#800]
I see that there is a FileSearch class, but no DirectorySearch. In the Wix schema, FileSearch has to be nested under a DirectorySearch which must be nested under a Property to find a file and store its location (which is what I'm trying to do).

Is this functionality in Wix# or does it need to be added? I need it because I need to target an executable outside of my msi project for a shortcut I'm making and Light does not like that. I was told to store the path in a FileSearch property.

**Comment by oleg-shilo** [comment]
`FileSearch` class is used in "RegistrySearch" sample.
Unfortunately you have to use XML injection to achieve `DirectorySearch` functionality as it is not implemented directly.

If you have time you can try to implement the class by yurself directly in your project. Just follow the same approach as in `FileSearch` class.

**Comment by sonicbhoc** [comment]
I can't use company time for that. I'll have to look at it in my free time, which is quite limited. But I'll do what I can.

**Comment by oleg-shilo** [comment]
If it helps... you probably noticed that I have marked this item as "enhancement" and "help wanted". Meaning that I an asking WixSharp users (who have free time) to look at it.

**Comment by sonicbhoc** [comment]
I have started work on this.

**Comment by sonicbhoc** [comment]
Is there a style guide for the coding standards in this repo? Which Properties are generally set in constructors and which are only available through property accessors?

**Comment by oleg-shilo** [comment]
Great.

Yes there is a contribution guideline:
https://github.com/oleg-shilo/wixsharp/wiki/Code-Contributions-Guideline

As for constructors vs property initializers, there is no strict rules but I personally prefer to include the most frequently used props in the constructor args while leaving more exotic ones for the explicit initialization via property assignments/initializers.

With validation it's simple. WixShar only implements validation of WixSharp logic but pure WiX constrains (your case of `DirectorySearch` parent) is responsibility of WiX compilers.

Thus your code should be reasonably straight forward.

**Comment by oleg-shilo** [comment]
Closing as expired.
