### ISSUE TITLE
CopyFile element not implemented

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#801]
It appears that CopyFile is not implemented. If this is the case, I will create a class for it when I have the time. If it exists and I missed it, let me know how to do it.

**Comment by oleg-shilo** [comment]
No it does not exists.

BTW in many cases WixSharp contentiously avoids implementing some WiX features even though it's possible. 

Of course it may not be your case, but you have way more flexibility and control over copying files by using C# (from CA) comparing to raw WiX.

But should you implement `CopyFile` then you can share it and I will include it in the codebase.

**Comment by Xaddan** [comment]
I use this implementation.
[CopyFile.txt](https://github.com/oleg-shilo/wixsharp/files/4181057/CopyFile.txt)

**Comment by oleg-shilo** [comment]
Fantastic. Txs. Goes to the code base.

------
Just re-posting @Xaddan's implementation so it can be used befre the next release. 

```C#
public class CopyFile : WixEntity, IGenericEntity
{
    public CopyFile(Id id)
    {
        Id = id;
    }

    public CopyFile(Id id, Feature feature, string destinationDirectory, string sourceDirectory, string sourceName)
    {
        Id = id;
        Feature = feature;
        DestinationDirectory = destinationDirectory;
        SourceDirectory = sourceDirectory;
        SourceName = sourceName;
    }

    [Xml]
    public new string Id { get { return base.Id; } set { base.Id = value; } }

    [Xml]
    public string DestinationDirectory;

    [Xml]
    public string SourceDirectory;

    [Xml]
    public string SourceName;

    public void Process(ProcessingContext context)
    {
        XElement component = this.CreateAndInsertParentComponent(context);
        component.Add(this.ToXElement("CopyFile"));
    }
}
```

**Comment by gopikrishna456** [comment]
Hi, I am trying to use CopyFile class to copy the file to destination directory
But I keep getting "is not a legal identifier.  Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every identifier must begin with either " error

Do you have any samples on how to use CopyFile class ?

Thanks
