### ISSUE TITLE
SuppressOptionsUI property missing from WixStandardBootstrapperApplication

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#803]
Unless I missed the property elsewhere, it appears that SuppressOptionsUI has no equivalent in Wix#. I was able to add the attribute manually by using the Attributes property. Should this be added or was it omitted intentionally?

**Comment by oleg-shilo** [comment]
It's there. You probably just missed it:
https://github.com/oleg-shilo/wixsharp/blob/27d131662de3d2bd8eebbc373510ae0ff7622a54/Source/src/WixSharp/Bootstrapper/BootstrapperApplication.cs#L233

**Comment by sonicbhoc** [comment]
For some reason, I can't access it from the WixStandardBootstrapperApplication class though, and it doesn't appear that WixStandardBootstrapperApplication inherits from BootstrapperApplication.

**Comment by oleg-shilo** [comment]
Oh, that is a mistake.

Corrected now. Will be available in the very next release.

**Comment by sonicbhoc** [comment]
Thank you!

**Comment by yurislav** [comment]
Until new version is released, you can use following hotfix:

```
Bundle bootstrapper = ...; // create the bootstrapper
bootstrapper.WixSourceFormated += SuppressBootstrapperApplicationOptionsUI;

private static void SuppressBootstrapperApplicationOptionsUI(ref string xmlContent)
{
    xmlContent = xmlContent.Replace(
        ":WixStandardBootstrapperApplication ",
        ":WixStandardBootstrapperApplication SuppressOptionsUI=\"yes\" ");
}
```
