### ISSUE TITLE
How to add a check box to create a  desktop shortcut

### ISSUE THREAD

**Issue by ju2pom** [oleg-shilo/wixsharp#804]
Hi,
I have build an installer using wix# (thank you for this great library) and I wonder how I could add a checkbox at the final page to let the user choose if he wants a desktop shortcut or not.
I already make use of the `WIXUI_EXITDIALOGOPTIONALCHECKBOX` option to launch the application at the end (inserting xml using WixSourceGenerated event).

I don't really know which kind of UI I use, here is how I set it up:
```csharp
project.UI = WUI.WixUI_InstallDir;
      project.CustomUI = new DialogSequence()
        .On(NativeDialogs.WelcomeDlg, Buttons.Next, new ShowDialog(NativeDialogs.InstallDirDlg))
        .On(NativeDialogs.InstallDirDlg, Buttons.Back, new ShowDialog(NativeDialogs.WelcomeDlg));
```

**Comment by oleg-shilo** [comment]
This means you are using native WiX UI. Me personally..., I cannot customise it effectively even if I want to. It's too difficult to keep it all together unless you do it everyday.

That's why I always prefer managed UI where the only skill you need to have is the ability to develop with WinForms. 

If you want to try it then just create your WixSharp project form "WixSharp - Custom UI" project template and you will be able to put a check box on the desired dialog and simply tunnel the `IsChecked` state to the MSI session property that is a condition for your installable shortcut.enam this

**Comment by Grandik7** [comment]
Could you clarify how to 'tunnel the state to the MSI session', please?

**Comment by oleg-shilo** [comment]
Add a condition to your shortcut:

```C#
new FileShortcut("MyApp", @"%Desktop%") { Condition = "ADDDESKTOPSHORTCUT=\"yes\"" })
```

In the check-box handler or on exit from dialog just add

```C#
Runtime.Session["ADDDESKTOPSHORTCUT"] = IsChecked  ? "yes" : "no";
```

**Comment by Grandik7** [comment]
Beautiful - thank you very much!

**Comment by Grandik7** [comment]
Unfortunatelly, I've got following exception:
![image](https://github.com/oleg-shilo/wixsharp/assets/38108481/c134f5d9-d79a-45f2-b1f1-ca0c91708f02)

**Comment by oleg-shilo** [comment]
My bad. My memory did not serve me well.
I described the generic process of adding conditions to the file being installed. While this technique is generic it's not applicable to the `FileShortcut` (shortcut that is a child of a File element)\. It is a WiX limitation. There is no workaround.

I should have provided a slightly different example based on `ExeFileShortcut`:
```c#
new Dir(@"%Desktop%",
   new ExeFileShortcut("MyApp", "[INSTALLDIR]MyApp.exe", arguments: "")
   {
       Condition = new Condition("INSTALLDESKTOPSHORTCUT=\"yes\"") //property based condition
   }),
```  
The complete example for your very scenario already exists and can be found here: https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Shortcuts-2/setup.cs

**Comment by Grandik7** [comment]
This works well, thank you. 

Maybe your memory is not the best, but this project is great piece! 
Thank you very much for that. Also for quick and willing support <3

Regards,
Michal
