### ISSUE TITLE
Call CustomAction Before RemoveExistingProducts

### ISSUE THREAD

**Issue by juliuzcb** [oleg-shilo/wixsharp#808]
Hi,
I have build an installer using Wix# that have a few Windows Service installations on version 3.7.0, and now on upgrade version (3.8.0) I want to remove some of than.
When I tried to remove "after InstallFiles Step", I had an error on InstallUtil.exe that I don't have an .exe file of the service anymore and when I try to use the "before RemoveExistingProducts Step" I had the following error:

![image](https://user-images.githubusercontent.com/45761502/74932313-45513e80-53c0-11ea-8e2e-630de174e039.png)

Can you help me with this?

Best regards,
Julio

**Comment by Torchok19081986** [comment]
Hallo,  first - 2613 error of windws installer according to ms ist "RemoveExistingProducts action sequenced incorrectly " found it on https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-error-messages":
second - try a sample of oleg of install win services with installuitl in sample in folder  Winservice -> With_Installutil. Work always on my win services.  How do you create your exe file ? Was a project as Windows Service or something else ? 
Maybe a look in your generated .wxs file can you help .

as starthelp : in samples it looks lke 

<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="6fe30b47-2577-43ad-9195-1861ca25889c" Name="My Product" Language="1033" Codepage="Windows-1252" Version="1.0.0.0" UpgradeCode="6fe30b47-2577-43ad-9195-1861ba25889b" Manufacturer="oleg.shilo">
    <Package InstallerVersion="200" Compressed="yes" SummaryCodepage="Windows-1252" Languages="1033" />
    <Media Id="1" Cabinet="My_Product.cab" EmbedCab="yes" />
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
        <Directory Id="ProgramFilesFolder.My_Company" Name="My Company">
          <Directory Id="INSTALLDIR" Name="My Product">
            <Component Id="Component.MyApp.exe_1864749224" Guid="6fe30b47-2577-43ad-9195-18618cb1a091">
              <File Id="MyApp.exe_1864749224" Source="..\SimpleService\MyApp.exe" />
            </Component>
          </Directory>
        </Directory>
      </Directory>
    </Directory>
    <UI />
    <CustomAction Id="Set_InstallService_Props" Property="InstallService" Value="INSTALLDIR=[INSTALLDIR];INSTALLDIR=[INSTALLDIR];UILevel=[UILevel];ProductCode=[ProductCode];ADDLOCAL=[ADDLOCAL];ADDFEATURES=[ADDFEATURES]" />
    <CustomAction Id="InstallService" BinaryKey="InstallService_File" DllEntry="InstallService" Return="check" Impersonate="no" Execute="deferred" />
    <CustomAction Id="Set_UnInstallService_Props" Property="UnInstallService" Value="INSTALLDIR=[INSTALLDIR];INSTALLDIR=[INSTALLDIR];UILevel=[UILevel];ProductCode=[ProductCode];ADDLOCAL=[ADDLOCAL];ADDFEATURES=[ADDFEATURES]" />
    <CustomAction Id="UnInstallService" BinaryKey="InstallService_File" DllEntry="UnInstallService" Return="check" Impersonate="no" Execute="deferred" />
    <Binary Id="InstallService_File" SourceFile="%this%.CA.dll" />
    <UIRef Id="WixUI_Minimal" />
    <UIRef Id="WixUI_ErrorProgressText" />
    <Feature Id="Complete" Title="Complete" Absent="allow" Level="1">
      <ComponentRef Id="Component.MyApp.exe_1864749224" />
    </Feature>
    <InstallExecuteSequence>
      <Custom Action="Set_InstallService_Props" After="InstallFiles" />
      <Custom Action="InstallService" After="Set_InstallService_Props"> (NOT Installed) </Custom>
      <Custom Action="Set_UnInstallService_Props" Before="RemoveFiles" />
      <Custom Action="UnInstallService" After="Set_UnInstallService_Props"> (REMOVE="ALL") </Custom>
    </InstallExecuteSequence>
  </Product>
</Wix>

Best regards.

**Comment by juliuzcb** [comment]
Hi, 
I looked into your link and the description of the error do not helped me as I expected.
I already try the oleg sample, but my situation is different from that sample. 
My msi is working fine for install and unistall services on the first install of my application, my problem is because now I want to remove a windows service installed from previous version and I can't remove because the ".exe" file is not there anymore.
For your information, I am using CustomAction and InstallUtil to try unistall the previous version of the windows service.
Looking to my generated .wxs file I have the following steps

[InstallExecuteSequence.txt](https://github.com/oleg-shilo/wixsharp/files/4249957/InstallExecuteSequence.txt)

Thinking about the sequence I want to execute the Custom Actions, before the msi starts remove the previous version files, I want to execute the Custom Actions StopWebsites and RemoveWindowsService, after that the msi can replace the application files and go on the others Custom Actions.

**Comment by Torchok19081986** [comment]
Hallo, if i understand correctly, you installed a windows service in previous version and now you can not remove it, cause your exe for service not exists anymore, right ?  
I had same problem in my first exprience with windows service. I solved my problem with removing / delete -  service from windows registry in following path manually. 
"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services".  Maybe you will need  to rebot system , after delete it. (Windows and msi decided self to reboot system, after windows servies install/uninstall)
And try call it in your Installer. I´m only not sure for entypoint in CA. Maybe oleg can you help with or you try set various values in CA for execution, There is example of call CA before in set all values with Installpath and Id. I only know, that this call happns BEFORE msi set all values for install.
