### ISSUE TITLE
Uninstall Windows service after install

### ISSUE THREAD

**Issue by ju2pom** [oleg-shilo/wixsharp#812]
Hi,
My installer has a custom action to install a Windows service after install and another one to uninstall this service before install (so I can update the service if needed).
The problem seems that I can't get the service to be uninstalled.
Here is the simplified code I use to uninstall the service. Note that I didn't even started the service.
```csharp
private static void OnBeforeInstall(SetupEventArgs e)
{
  var installDir = e.Session.Property("INSTALLDIR").TrimEnd('\\');
  Tasks.StopService(ServiceName);
  var result = Tasks.InstallService(Path.Combine(installDir, ServiceName), false);
  e.Session.Log($"Uninstall service result: {result}");
}
```

Even if the program is uninstalled, the service remains installed and by the way I don't know where to find the logs since the uninstall is run completely silently.

**Comment by oleg-shilo** [comment]
You can implement your own installer and just debug it during the installation. Then you will know exactly what is happening:

```C#
class YourTasks
{
    static public string InstallService(string serviceFile, bool isInstalling, string args = null)
    {
        var util = new ExternalTool
        {
            ExePath = IO.Path.Combine(CurrentFrameworkDirectory, "InstallUtil.exe"),
            Arguments = string.Format("{0} {1} \"{2}\"", isInstalling ? "" : "/u", args ?? "", serviceFile)
        };

        var buf = new StringBuilder();
        int retval = util.ConsoleRun(line => buf.AppendLine(line));
        string output = buf.ToString();

        string logoLastLine = "Microsoft Corporation.  All rights reserved.";
        int pos = output.IndexOf(logoLastLine);
        if (pos != -1)
            output = output.Substring(pos + logoLastLine.Length).Trim();

        if (retval != 0)
            throw new Exception(output);

        return output;
    }
}
```

**Comment by ju2pom** [comment]
Thank you for your help, sadly I'm still stuck with my service uninstallation.

- I could not find a way to debug my custom action. I've tried Debugger.Launch() and attach to msiexec. The only info I could get was using a message box :(
- According to what I understood it seems I need elevated privileges to uninstall the service, which makes sense since it's also required to install it (but as it's done in the AfterInstall custom action it's all good)
- Following your advice in another thread I created a ElevatedManagedAction to execute the uninstalling code. Sadly it seems that when using custom UI I must move that custom action in a separate assembly (am I correct?)
- I moved this simple custom action in another assembly (class library based on .Net Framework) but now I can't compile it because of the following error (sorry it's in french but basically it says it cannot find associated application to execute this action)
![cmd_oVcrTlHJng](https://user-images.githubusercontent.com/3799294/75595465-d1ccc280-5a8c-11ea-9433-2b1b2227a3a6.png)
For your information if I manually run the exact same command line as done in Tasks.InstallService with admin privileges the service is correctly removed.

There must be something I did wrong with my custom action assembly, isn't it?

**Comment by oleg-shilo** [comment]
1. I think the problem with attaching the debugger is that you need to run VS elevated. Then you can attach it. 

You can also use `Debug.Assert(false)`. This way itr will offer you to select the running (elevated) VS instance.

2. Yes you do need to be elevated.

3. Not really. Your custom UI, msi builder and the event handlers and all custom actions can be (and it is the default behavior) in the same assembly. 

4. I think if you move to the "single assembly" model you will get it right. Have a look at "CustomUIDialog" sample.

**Comment by ju2pom** [comment]
Thanks again for you answer.
I've found the problem, it was VS that was not configured to handle Just-In-Debugging for managed and native code.

About the custom action it really seems that something related to the existence of this class `public class SampleEmbeddedUI : IEmbeddedUI` prevents wix# from correctly retrieving CA.
See the run time error I get:
```
OnInstall=MyInstaller!MyCustomActions.CustomActions.OnInstall
Searching for an embedded UI class in MyInstaller.exe
Error: System.NotSupportedException: CA and UI entry points cannot be in the same assembly: C:\code\MyInstaller\bin\Debug\MyInstaller.exe
   à Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Build(String output, String sfxdll, IList`1 inputs, TextWriter log)
   à Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Main(String[] args)
```
Though the SampleEmbeddedUI class is the same file as the one provided in the samples.

**Comment by oleg-shilo** [comment]
Yes this WiX restriction is one of those mind bending constrains that exist in WiX for no good reason whatsoever. And... we have to dance around them.

WixSharp is split into two assemblies so you don't need to feel the pain of this constrain. But it looks like you have implemented `IEmbeddedUI` by yourself and do not use WixSharp stock implementation. That's fine but it means that you now will need to ensure the separation of your _custom actions_/_project events_ and your _embedded UI_ into separate assemblies.

Again, I personally see no valid reason for this WiX constrain to exist but it looks lake WiX team has different opinion :)
