### ISSUE TITLE
How to let CustomAction (not AfterInstall)  run after all files have been copied and just before the product is added to the Uninstall Program List of Control Panel

### ISSUE THREAD

**Issue by milhousemanastorm** [oleg-shilo/wixsharp#815]
I am trying to set a Custom Action which runs after all files are copied to its destination folder and before the product is added to the Uninstall Program List of Control Panel.

I tried:

new ManagedAction(action, Return.check, When.After, Step.InstallFinalize, Condition.NOT_Installed);

The custom action runs after the product is added to the uninstall program list.

I tried these five ways:
new ManagedAction(action, Return.check, When.Before, Step.InstallFinalize, Condition.NOT_Installed);
new ManagedAction(action, Return.check, When.Before, Step.PublishProduct, Condition.NOT_Installed);
new ManagedAction(action, Return.check, When.After, Step.PublishProduct, Condition.NOT_Installed);
new ManagedAction(action, Return.check, When.Before, Step.PublishFeatures, Condition.NOT_Installed);
new ManagedAction(action, Return.check, When.After, Step.PublishFeatures, Condition.NOT_Installed);

The custom action runs before all files are copied to the destination.

I saw the answers for issue #769, but I don't know how to let SetupEventArgs pass key-value variables during installation (e.g. I set  MsiRuntime.Session["CONFIG_FILE_TEMPLATE"]=PATH  ).

So is there a way to let a CustomAction runs after all files have been copied and just before the product is added to the Uninstall Program List of Control Panel?

 Or is there a way to let SetupEventArgs  pass Session key-value variables?

Thanks

**Comment by oleg-shilo** [comment]
> So is there a way to let a CustomAction runs after all files have been copied and just before the product is added to the Uninstall Program List of Control Panel?

Really don't knew. These are the intricacies of MSI/WiX that I am trying to avoid. When possible. :)

>   Or is there a way to let SetupEventArgs pass Session key-value variables?

Yes, you just need to declare that your property needs to be tunneled to the deferred action (awkward MSI concept) and the rest will be done by WixSHarp:

```C#
project.DefaultDeferredProperties += ",YourPropertyName";
```

see https://github.com/oleg-shilo/wixsharp/blob/4fefacc75944a7b8cae0eb1a6ed9d7827e7d2ae2/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/SetupEvents/setup.cs

**Comment by oleg-shilo** [comment]
Using `e.Data` even simpler

**Comment by milhousemanastorm** [comment]
THX
