### ISSUE TITLE
Track (catch, subscribe) user canceled installation event

### ISSUE THREAD

**Issue by constant-arapov** [oleg-shilo/wixsharp#816]
I'm developing the installer using WixSharp. I want to track (catch, subscribe etc) the event when user clicks the cancel button (cancel / abort installation).

I want to track during the stage user inputs the data and during the installation files process as well. It's better no changing the standard UI dialogs but using custom action or something. But if changing UI is the only way it's OK.

**Comment by oleg-shilo** [comment]
Native UI is a bit painful to customize. But probably possible. 
I personally would g with managed UI, which is a copy of a standard UI  appearance wise but it allows you to hook up to the button on-click event and do whatever you want. It's just a simple WinForms UI.

If you want to go/explore this way just create your WixSharp project from "Custom UI" template and you are done.
