### ISSUE TITLE
Make Embedded UI with WPF that looks right?

### ISSUE THREAD

**Issue by tig** [oleg-shilo/wixsharp#817]
I have used the WPF Embedded UI sample to create a custom dialog for my installer. When run on Windows 10 I get Windows 7 styles:

![image](https://user-images.githubusercontent.com/585482/76234778-651d9a80-61e7-11ea-9d77-da24af4f4a92.png)

How do I fix this so my installer looks modern?

I tried changing the Target Framework used to 4.7.2 and that just broke the installer:

![image](https://user-images.githubusercontent.com/585482/76235031-c180ba00-61e7-11ea-8ff1-06168a799bb2.png)

**Comment by oleg-shilo** [comment]
I doubt it depends on the target framework runtime. Most likely it's all about the hosting environment. In this case it is MSI runtime so who knows what it does!

The answer will be somwhat similar to the usual WinForm styling initialization:
```C#
Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);
```

You may be able to find something on the WPF forums.

**Comment by tig** [comment]
I've searched and been unsuccessful, which is why I fell back to asking here. 

However, on the point of target framework: Is it possible to use a .NET Framework 4.7+ assembly with MSI as Embedded UI?

**Comment by oleg-shilo** [comment]
I think so.
It will come down to WiX runtime, which is hosting the CLR during setup. It seems like there is no problems there:

![image](https://user-images.githubusercontent.com/16729806/76618336-774b6000-657c-11ea-950f-89b54397fe5c.png)

**Comment by tig** [comment]
Thanks. I dug in more based on your comment and ...

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup useLegacyV2RuntimeActivationPolicy="true" >
      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2"/>
    </startup>

</configuration>
```

I didn't have the `supportedRutime` key before.  It's now working correctly!

**Comment by oleg-shilo** [comment]
Fantastic!
Can I ask you a favor? If indeed you find the time to reflect your experiences on wiki, please describe the details of your solution/workaround.

Cheers
