### ISSUE TITLE
Running a Custom Action before the Launch Conditions

### ISSUE THREAD

**Issue by bfmom** [oleg-shilo/wixsharp#819]
I'm trying to run a custom action before the launch condition in order to create the launch condition at runtime and when trying to debug, I see that the Action is not called. Can you please help me?

**Comment by oleg-shilo** [comment]
"DTF (ManagedCA)" sample shows how to run CA before the Launch Condition

**Comment by bfmom** [comment]
I looked at your examples and tried to replicate but I am having trouble. When I try to debug I see that the custom action does not even happen.
The scenario is as follows:
I have a property and I want to run a custom action before the launch condition to set the value of the property at runtime and have the launch condition check the property and launch/not launch the msi according to the value of the property.
No matter what I have as the custom action, if the default value of the property is false then the msi will launch and if the default value of the property is true then the msi will not launch.
My question is- what is changing the value of the property and why is the custom action not running? in the example below, the msi will launch and if the default value of the property will be "TRUE" it will not launch. Thank you for your help!

Property: 
public PropertyDescriptor MyProperty= new PropertyDescriptor("MYPROPERTY", true, "FALSE");
Declaration of Action: 
new ManagedAction(CustomActions.MyAction, Return.check, When.Before,
                        Step.LaunchConditions, Condition.NOT_Installed)
                    {Execute = Execute.immediate, Impersonate = false}
Custom Action:
[CustomAction]
    public static ActionResult MyAction(Session session)
    {
        session["MyProperty"] = "FALSE";
        return ActionResult.Success;
    }
Launch Condition: 
new LaunchCondition("MYPROPERTY=\"FALSE\"", "cannot run the msi");

**Comment by oleg-shilo** [comment]
Have a look at managed events sample. It uses slightly different approach
bet for the same problem

Though it's  not a canonical msi approach. Which is still possible.... I am
just not sure what is happening there.





-- 
Oleg Shilo
--------------------------------------------------------------------------------------------
Website: http://www.csscript.net
E-Mail: csscript.support@gmail.com

**Comment by bfmom** [comment]
Do you mean managed CA? I am very new to wix#.
how would you change the design to be like the sample?

**Comment by oleg-shilo** [comment]
I mean managed events, which are implemented as CAs under the hood. But they do deliver standard C# event notification mechanism development experience.
