### ISSUE TITLE
Built in Progress Dialog - Can it show which feature it is processing?

### ISSUE THREAD

**Issue by AmosOtis** [oleg-shilo/wixsharp#821]
I have been successful in using wixsharp to create a SqlInstance Custom Dialog that allows me to search for local SQL Instances, login, select a database and continue.  It works great and I'm very pleased with all that has been done to enable this type of customization with WIX.  

Overall, I'm pleased with the resulting msi and install experience however I was wondering if the built in Progress Dialog could be configured to show which feature is being installed.  When a users selects the "Training Data Sets" feature, this takes up to 2 or more minutes to install.  I'd like the user to know that this is the feature that is currently being processed.

How can we do this?

Thanks in advance!

**Comment by oleg-shilo** [comment]
I suggest you create a new project from "WixSharp - Custom UI" VS template. 
Then start experimenting with ProgressDialog. Listen to the progress messages and update the labels correspondingly. 

Though you may find that MSI runtime doesn't report features being installed but only deployable items regardless of the features they belong to.

**Comment by AmosOtis** [comment]
I'm still struggling with this.  I'm not sure I want to alter the built in Progress Dialog.  I just want the status text to be specified appropriately when performing a sqlscript action.  The built in dialog just shows "Status: Copying new files" when I know it is actually running a SqlScript.  It would be nice if on the definition for the SqlScript in the project we could specify a message to be displayed for that script in the default ProgressDialog.  Just a thought.

**Comment by oleg-shilo** [comment]
"Copying new files" is the message that was sent to the MSI session client by MSI runtime. This is how MSI implements communication to the user. Nothing you can change there. MSI does not offer any customization. 

Though what you can do is to use your own MSI session UI client (provided by WixSharp) and then you can modify its progress dialog to display an alternative or/and additional status of the state that you have full power to identify. 

Of course identifying the custom status can still be a challenge.
