### ISSUE TITLE
Environment Variable not set for InstalledFileAction

### ISSUE THREAD

**Issue by miraj** [oleg-shilo/wixsharp#823]
I am setting an Environment variable :
     new EnvironmentVariable("MYDIR", "[INSTALLDIR]") { System = true},

And have this InsalledFileAction : 
                new InstalledFileAction(
                    SetupConstants.NTray_EXE_Id,
                    "",
                    Return.asyncNoWait,
                    When.After,
                    Step.InstallFinalize,
                    Condition.NOT_Installed
                )

But the environment variable is not available when the EXE is executed by the installer. However when execute the application separately, then the Env variable is available. 

This is how I get the Env variable in the application:
Environment.GetEnvironmentVariable("MYDIR")

Why is the emv variable not available when the exe is called from Installer?

**Comment by oleg-shilo** [comment]
I suggest you use events instead:
```C#
project.AfterInstall += project_AfterInstall;
. . .
static void project_AfterInstall(SetupEventArgs e)
{
    if(e.IsInstalling)
        Process.Start($"{e.InstallDir}\myapp.exe");
}

**Comment by miraj** [comment]
But problem with "project.AfterInstall" is that it doesn't support Feature. Or at least I could not figure it out. Can you help?

**Comment by oleg-shilo** [comment]
You can use `e.Session.IsFeatureEnabled("feature name")` based on the value of `ADDFEATURES` property:
```C#
static void project_AfterInstall(SetupEventArgs e)
{
    //Note AfterInstall is an event based on deferred Custom Action. All properties that have
    //been pushed to e.Session.CustomActionData with project.DefaultDeferredProperties are
    //also set as environment variables just before invoking this event handler.
    //Similarly the all content of e.Data is also pushed to the environment variables.
    MessageBox.Show(e.Session.GetMainWindow(),
                    e.ToString() +
                    "\npersisted_data = " + e.Data["persisted_data"] +
                    "\nADDFEATURES = " + e.Session.Property("ADDFEATURES") +
                    "\nEnvVar('INSTALLDIR') -> " + Environment.ExpandEnvironmentVariables("%INSTALLDIR%My App.exe"),
                    caption: "AfterInstall ");
```

**Comment by miraj** [comment]
Thank you for the solution
