### ISSUE TITLE
How to set a Path to exe from registry 

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#824]
Hallo, i have a problem in my installer. I have to set .exe path in windows firewall exception in program property value. I created a CA with AddtoProperty, but CA return null or do nothing  and add to firewall a empty value. 
Windows Firewall exception look following. 
 ```csharp
new FirewallException("Sql Server")
                    {

                        Scope = FirewallExceptionScope.any,
                        Program = @"%ProgramFiles%\Microsoft SQL Server\MSSQL14.<nameofinstance>\MSSQL\Binn\sqlservr.exe", //Here i have to set Property from below CA. not working somehow.
                        AttributesDefinition = "Component:Permanent=yes"
                    }, 
...
```

my new created CA Code looks 
 ```csharp

[CustomAction]
    public static ActionResult AddPathToSqlserverexeWindowsFirewall(Session session)
    {
       session["SQLSERVEREXE"]  = RegistryKey.LocalMachiine.
           OpenSubKey(@"\SYSTEM\CurrentControlSet\Services\MSSQL$" + session["SQLSERVER"] + "").GetValue("ImagePath").ToString();

        return ActionResult.Success;
    }

```
Properties SQLSERVEREXE and SQLSERVER comes from Installsession.  SQLSERVER have a value from current sqlserver. Somehow is SQLSERVEREXE got null or cant be executed. 
Installer was executed on Windows Server 2016 and Net Framework 4.7.2.  Notice: on this envireoment is already installed 2 Sql Server with different Languages . 
Can someone help me with ?

**Comment by Torchok19081986** [comment]
Hallo, oleg. i tried in samples folder , registrysearch example, but unfortunatelly it seems doesnt work,  
in Example there is code with Imagepath and Getvalue method .  Also tried it, not work . It added empty value to Programm Exe path.

**Comment by Xaddan** [comment]
This is my option
```C#
new Property("SQL_SERVER_INSTANCE_NAME", "sqlexpress");
new RegValueProperty("SQL_INSTANCE_ID", RegistryHive.LocalMachine, @"Software\Microsoft\Microsoft SQL Server\Instance Names\SQL", "[SQL_SERVER_INSTANCE_NAME]");
new Property("SQL_SERVER_LOCATION", new RegistrySearch(RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Microsoft SQL Server\[SQL_INSTANCE_ID]\Setup", "SQLBinRoot", RegistrySearchType.directory));

new FirewallException
{
    Name = "Sql Server",
    Program = $"[SQL_SERVER_LOCATION]sqlservr.exe",
    Scope = FirewallExceptionScope.any,
    Profile = FirewallExceptionProfile.all,
    IgnoreFailure = true,
}
```

**Comment by Torchok19081986** [comment]
Hallo, Xadan, thanks for your snippet. Do i have to add it in CA or can i set values in msi description before ?

**Comment by oleg-shilo** [comment]
Usually an empty property is the result of the property being initialized after it's been accessed for the first time.

Ye can test it very ease. Set the property programatically in the `project.Load` event handler and see if `FirewallException` gets created correctly.  If it does then you have your answer.

**Comment by Torchok19081986** [comment]
Hallo, Oleg, Just tested it. Property of SERVER_LOCATION ist really empty. How do i access to property for Firewallexception before or after initialize install ? I tried also in new created CA, but it doesnt work this way .

**Comment by Torchok19081986** [comment]
Close the question.
