### ISSUE TITLE
Finding the the MODIFY_ACTION property in ExitDialog.cs

### ISSUE THREAD

**Issue by miraj** [oleg-shilo/wixsharp#829]
Hi
  I want to find out the setup action type in the Exit dialog. This is what I am doing
        void ExitDialog_Load(object sender, System.EventArgs e)
        {
            string action = Runtime.Session.Property("MODIFY_ACTION");

I am expecting action to be "Repair", "Change", or "Remove". However it is not working. 

Any idea what's wrong?

**Comment by oleg-shilo** [comment]
I am not aware about `MODIFY_ACTION` property. I am not sure MSI maintains this property.

Have a look at "Setup Events" sample it shows how to access the required information. But from my memory it is something like this:
```C#
Runtime.Session.IsModifying();
Runtime.Session.IsRepairing();
Runtime.Session.IsUninstalling();
```
