### ISSUE TITLE
How to replace an installation path with a registry value?

### ISSUE THREAD

**Issue by Ryuya-dono** [oleg-shilo/wixsharp#830]
Hello.

Is there a way to get an installation path from the registry key at the beginning of the installation and replace the INSTALLDIR variable with it?

I have tried this

```c#
// new ElevatedManagedAction(ReadFromRegistry, Return.check, When.After, Step.InstallInitialize, Condition.NOT_Installed)

[CustomAction]
public static ActionResult ReadFromRegistry(Session session)
{
    RegistryKey registryKey = RegistryKey.OpenBaseKey(Microsoft.Win32.RegistryHive.LocalMachine, RegistryView.Registry64).OpenSubKey($@"SOFTWARE\Company\Product", false);
    String installationDirectory = registryKey?.GetValue("InstallationDirectory")?.ToString();

    if (!String.IsNullOrWhiteSpace(installationDirectory))
    {
        session["INSTALLDIR"] = installationDirectory;
    }
    
    return ActionResult.Success;
}
```

and this, 

```c#
private static void Project_Load(SetupEventArgs e)
{
    RegistryKey registryKey = RegistryKey.OpenBaseKey(Microsoft.Win32.RegistryHive.LocalMachine, RegistryView.Registry64).OpenSubKey($@"SOFTWARE\Company\Product", false);
    String installationDirectory = registryKey?.GetValue("InstallationDirectory")?.ToString();

    if (!String.IsNullOrWhiteSpace(installationDirectory))
    {
        e.InstallDir = installationDirectory;
    }
}
```

but the path in an InstallDirDialog did not change.

Is it possible to change the path (regardless of an installation mode (silent or UI)) if the registry key exists?

**Comment by oleg-shilo** [comment]
If you are using ManagedUI then you need to do it earlier, before the UI starts. IE in `project.UILoaded`.

![image](https://user-images.githubusercontent.com/16729806/79851434-a91bd600-8408-11ea-91a2-b3834e53806f.png)

For native UI it is a before `LaunchCondition` custom action:

![image](https://user-images.githubusercontent.com/16729806/79852761-707cfc00-840a-11ea-8523-63fa3d178971.png)


Though if no UI is loaded then `project.Loaded` is the right place to do it.

**Comment by Ryuya-dono** [comment]
Thank you, it works!
