### ISSUE TITLE
session.Property and session.CustomActionData is empty in repair

### ISSUE THREAD

**Issue by TrifonovPN** [oleg-shilo/wixsharp#831]
I have one custom action that is executed all the time. This custom action is "ElevatedManagedAction" and get correctly the value on fresh install, but in repair mode the value passed is empty. Is correct that in repair the value to be always null?

**Comment by oleg-shilo** [comment]
I am not sure what is happening here. 
Check the generated wxs file for a clue.

This is what is yielded by the DeferredActions sample:

```C#
var project =
    new ManagedProject("My Product",
        . . .
        new ElevatedManagedAction(CustomActions.OnInstall, Return.check, When.After, Step.InstallFiles, Condition.NOT_Installed)
        {
            UsesProperties = "CONFIG_FILE=[INSTALLDIR]MyApp.exe.config, ..."
        });
```
`UsesProperties` controls what should be pushed to `session.CustomActionData`.

```xml
<CustomAction Id="Set_OnInstall_Props" Property="OnInstall" Value="CONFIG_FILE=[INSTALLDIR]..." />
<CustomAction Id="OnInstall" BinaryKey="OnInstall_File" DllEntry="OnInstall" Return="check" Impersonate="no" Execute="deferred" />

<InstallExecuteSequence>
  <Custom Action="Set_OnInstall_Props" After="InstallFiles" />
  <Custom Action="OnInstall" After="Set_OnInstall_Props"> (NOT Installed) </Custom>
    . . .    
</InstallExecuteSequence>
```

As you can see iven though in this example `OnInstall` is only to be execute if `(NOT Installed)` the action that inits CustomActionData (`Set_OnInstall_Props`) is to be executed unconditionally.

**Comment by TrifonovPN** [comment]
I have the following code in my project

Program.cs:
`
project.Properties = new Property[] {
    new Property("SERVER_URL", "") { IsDeferred = true }
}


project.Actions = new WixSharp.Action[]
{
    new ElevatedManagedAction(ModifyConfigFileCA.ModifyConfigFile, Return.check, When.Before, Step.InstallFinalize, Condition.NOT_BeingRemoved)
    {
        UsesProperties = "SERVER_URL"
    }
}`

My custom form:
`private void next_Click(object sender, EventArgs e)
{
...
Runtime.Session["SERVER_URL"] = ServerUr.Textl;
...
}
`

Getting a property inside custom action:
`string url = session.Property("SERVER_URL");`

When the program is installed, the url is taken correctly. When the program is updated, the url is empty.

**Comment by oleg-shilo** [comment]
OK, that does change a lot. 

I am only guessing that your `next_Click` is no longer executed in repair mode and somehow that screws the previous value of the property that was set during the installation.

I am not sure what is happening in your case but the scenario you are implementing is not different to setting `INSTALLDIR` from the InstallDir dialog and in this case `INSTALLDIR` is available from repair mode. 

I suggest you try to follow "`INSTALLDIR` + InstallDir dialog" approach exactly as is. Use "Custom UI" project template so you have all source code for dialogs. Also always check produced wxs as it may give you a clue.

MSI magic with properties and deferred actions is quite difficult to deal with.

==================

On a separate note, I would really question the fact that your deployment solution is creating the configuration. This is exactly te reason why you have this problem. Letting MSI to handle deployment of the files and leaving the configuration completely for an application gives you the straight answer to your problem. This way you do not stuff up your configuration if you need to repair your installation. And you don't need to start whole repair if you simply want to update/reset your config.
