### ISSUE TITLE
Build issue when running from command line

### ISSUE THREAD

**Issue by lbova35** [oleg-shilo/wixsharp#832]
I am fairly sure this is actually an issue with either WIX or my environment but I thought the people here may know of a solution better than anyone else.

I am using the Compiler.BuildMsi() command to build a managed project.

When I build or debug the solution in VS everything works great, the program runs smoothly and I get an operational MSI.

However, when I go to run the executable from the command line (or by double click) I wind up with just the .wixobj and .wxs files sitting in my output folder with no MSI. This leads me to believe its WIX that isn't doing something that it is supposed to (or I am missing something obvious in my environment).

My question is why is it working during debug and not in a live environment? Any insights on where to look for an issue would be appreciated, I am currently at a loss for ideas.

I am currently running WixSharp V1.9.2 if that helps.

**Comment by lbova35** [comment]
Looks like I had a missing file that was causing the execution to hang right before the build. Added it back in and it's working fine now.

**Comment by oleg-shilo** [comment]
Thank you for a quick update.
