### ISSUE TITLE
Small suggestion: Show UACWarning only after some delay

### ISSUE THREAD

**Issue by savehansson** [oleg-shilo/wixsharp#838]
I replaced:
```csharp
if (!WindowsIdentity.GetCurrent().IsAdmin() && Uac.IsEnabled())
{
    this.waitPrompt.Text = Runtime.Session.Property("UAC_WARNING");
    this.waitPrompt.Visible = true;
}
```
with:
```csharp
if (!WindowsIdentity.GetCurrent().IsAdmin() && Uac.IsEnabled())
{
    waitPrompt.Text = Runtime.Session.Property("UAC_WARNING");

    var waitMs = 4000;
    var t = new System.Windows.Forms.Timer();
    t.Interval = waitMs;
    t.Tick += (s, e2) =>
    {
        WaitPrompt.Visible = true;
        t.Stop();
    };
    t.Start();
}
```

The idea was that if UAC gets focus within 4 s the user will never see the UACWarning.

**Comment by oleg-shilo** [comment]
This is an excellent idea. Txs
Done. 
Will be available in the next release

**Comment by savehansson** [comment]
Since I posted I enhanced it with `t.Stop();` in "all the places" where the prompt is hidden (`WaitPrompt.Visible = false;`). For this I had to move `t` to "the global scope".

I also increased the delay to 10 s, but that's a matter of taste.

**Comment by oleg-shilo** [comment]
What are these "all the places"?

I thought it was only in the progress dialog

**Comment by savehansson** [comment]
Correct. In two places in the progress dialog, in `OnProgress` and in `ProcessMessage`.
