### ISSUE TITLE
How to impersonate in BeforeInstall event function?

### ISSUE THREAD

**Issue by coderafk** [oleg-shilo/wixsharp#839]
Hello,

we want to replace our CustomActions with event functions (Load, BeforeInstall, AfterInstall) from the "Managed Setup Model". Some of our CustomActions are impersonated (Impersonate = true). 

How can we impersonate event functions?

Best regards,

Frank

**Comment by oleg-shilo** [comment]
The events do not expose their CustomActions properties directly as it takes more than a single CA be configured so events are provisioned

However in your case updating that specific property is quite straight forward:
```C#
project.WixSourceGenerated +=
    document => document.FindAll("CustomAction")
                        .Where(x => x.HasAttribute("Id", "WixSharp_BeforeInstall_Action"))
                        .ForEach(x => x.SetAttribute("Impersonate=yes"));

```

**Comment by coderafk** [comment]
This means that all event functions of **WixSharp_BeforeInstall_Action** are either impersonated or not. Is that correct? Because all event functions are encapsulated in one CustomAction **WixSharp_BeforeInstall_Action**.

**Comment by oleg-shilo** [comment]
Not exactly. All events actions are encapsulated in the corresponding individual CAs:

```C#
WixSharp_Load_Action
WixSharp_BeforeInstall_Action
WixSharp_AfterInstall_Action
```

**Comment by coderafk** [comment]
Many thanks for the explanation.
