### ISSUE TITLE
Shortcut for Website

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#84]
Hallo, i need some Information, how do i create Shortcut or Menupoint for visit homepage. 
I tried InternetShortcut, but nothing happens after Install. In Internetshortcut i can set Name, Id, Target and Type, but not in project object. Is there some posibility to do this  ?
Thanks for answer.

**Comment by oleg-shilo** [comment]
> ...  In Internetshortcut i can set Name, Id, Target and Type, but not in project object. ...
What exactly do you mean by that? Can you elaborate?

In any case have a look at "Shortcuts" sample:
```C#
 new Dir(@"%ProgramFiles%\My Company\My Product",
     new InternetShortcut
     {
         Name = "Wix# project page",
         Target = "https://github.com/oleg-shilo/wixsharp"
     },
```

**Comment by Torchok19081986** [comment]
Hi Oleg, thanks for answer. I tried set InternetShortcut like ExeFileShortcut(...) and this was my mistake. 
Thanks for explanation.

**Comment by oleg-shilo** [comment]
At time of implementing the `InternetShortcut` class these properties (e.g. icon) were not available. But according the current WiX doco there are a few new attributes. Thus you might be able to use these attributes if you use the corresponding WiX compilers. 

And this is how you set the new attributes that Wix# is doe not support directly (`AttributesDefinition`):  
```c#
 new InternetShortcut
 {
     Name = "Wix# project page",
     Target = "https://github.com/oleg-shilo/wixsharp",
     AttributesDefinition = "IconFile=[INSTALLDIR]\\app.ico;IconIndex=1"
},
```

**Comment by Torchok19081986** [comment]
if i understand your example right, i need to install Icon file with my programm, Can i set instead of [INSTALLDIR] my local Path to Icon. Woulr looks like 
IconFile=[INSTALLDIR]\\app.ico;IconIndex=1 -> IconFile=Images\\app.ico;IconIndex=1 ?

**Comment by oleg-shilo** [comment]
No. The icon file is the file on yourv target system and t must be either absolute path ot formatted string containing envars (e.g. INSTALLDIR). 

You need to follow it with WiX doco. I never really used InternetShortcut.

**Comment by Torchok19081986** [comment]
Thanks for quickly answer. Ok, i test this as well.

**Comment by Torchok19081986** [comment]
i tested it now and in testproject works fine and in my mainproject i get error message: "Sequence have more than one element".  
myShortcuts to Exe and Homepage looks like 
... 
new Dir(%ProgrammMenu%\mycompany\myexe.exe,
  new ExeFileShortcut("myexe",@"[INSTALLDIR\myexe.exe]",""),
  new InternetShortcut
  {
    Name = "my homepage",
   Target = "https://www.myhomepage.de/home.html",
    Type = ShortcutType.url
  },
new ExeFileShortcut("Uninstall myexe", @"[System64Folder]msiexec.exe", "/x [Productcode]")))).

Last  " ) " close Sequence in Dir from ManagedProject in var project= new ManagedProject(mycompany,
 new Dir(
and after this i create 2 Registrykey. 
What do i not correct ? both Project are same with details and .exe and files. 
In my testproject run Compile.BuildMsi without error and it works fine, but in mainproject i get always error with Sequence Elements. How do i avoding this error ? Maybe set some new Id for each element ?

**Comment by oleg-shilo** [comment]
I guess it is a brackets-matter. If you need a benchmark look at "AllInOne" sample.

**Comment by jjxtra** [comment]
Just a heads up if you are trying to create desktop shortcuts you must add this to your code or you will get a permissions issue:

`project.InstallScope = InstallScope.perMachine;`
