### ISSUE TITLE
Uninstall Failed

### ISSUE THREAD

**Issue by ju2pom** [oleg-shilo/wixsharp#840]
Hi,
I have changed my installer boostrapper from NSIS to Bundle because I had to install C++ VCRedist with my application and found it was rather simple this way.
It seems to work fine (even if I still need to check if Redist are already installed) but now I'm not able to uninstall anymore.
Here is the error message I got:
![image](https://user-images.githubusercontent.com/3799294/81455138-94706980-918e-11ea-8285-159c585c73f3.png)

Here is the log file:
[MyProduct_20200509005154.log](https://github.com/oleg-shilo/wixsharp/files/4602096/MyProduct_20200509005154.log)

Here is the code that I use to create the bundle:
```csharp
private static void BuildBundleBootstrapper(Version version, string rootPath, string project)
    {
      var vcRedistPackage = new ExePackage()
      {
        Vital = true,
        Compressed = true,
        SourceFile = Path.Combine(rootPath, "ThirdParty", "VC_redist.x64.exe"),
        //DownloadUrl = @"https://aka.ms/vs/16/release/vc_redist.x64.exe"
      };

      var bootstrapper =
                new Bundle(ProductName,
                    vcRedistPackage,
                    new MsiPackage(project)
                    {
                      DisplayInternalUI = true,
                    });

      bootstrapper.IconFile = Path.Combine(rootPath, "logo", "logo.ico");
      bootstrapper.Version = version;
      bootstrapper.Manufacturer = Manufacturer;
      bootstrapper.Compressed = true;
      bootstrapper.UpgradeCode = new Guid(BundleId);
      bootstrapper.Application.LogoFile = Path.Combine(rootPath, "logo", "logo-64.png");
      bootstrapper.Application.LicensePath = null;
      bootstrapper.Application.AttributesDefinition = "ShowVersion=yes; ShowFilesInUse=yes";
      bootstrapper.Include(WixExtension.Util);
      bootstrapper.IncludeWixExtension(@"WixDependencyExtension.dll", "dep", "http://schemas.microsoft.com/wix/DependencyExtension");

      bootstrapper.PreserveTempFiles = true;
      bootstrapper.SuppressWixMbaPrereqVars = true;

      var setup = bootstrapper.Build(Path.ChangeExtension(project, "exe"));
      Console.WriteLine(setup);
    }
```

Note that the BundleID is a new GUID I have generated for this new implementation, but I kept the same ProductID as before.

Do you have any clue why I can't uninstall? Once I'm in this state how can force an uninstall?

**Comment by oleg-shilo** [comment]
There is a chance that one of the packages (either VCdisrt or your msi). But this cause you probably already ruled out by testing the package individually.

It is also possible that NSIS bootstrapper triggers the error but this is something that I cannot help you much with. NSIS support is an extension to WixSharp and I am no expert in NSIS.  Sorry. Hopefully NSIS knowledge base search can revile something.

=======

Interestingly enough your very scenario was the use case for "Simplified Bootstrapper" sample that uses raw MSI+WixSharp. Basically the bootstrapping is mimicked via pre-launch Custom Action.

**Comment by geghamyan** [comment]
MSI uninstall log should give more details about the error.

**Comment by oleg-shilo** [comment]
Yep, this is what I meant "But this cause you probably already ruled out by testing the package individually."

Investigating MSI uninstall logs must be the first step of the investigation.

**Comment by ju2pom** [comment]
Thank you for your help, you were right !
It was due to a custom action that was killing a specific processus, but could throw because accessing to the "MainModule" of a 64 bit process from a 32bit process raises an exception.

**Comment by oleg-shilo** [comment]
Great. Thank you for letting us know.
Thank you Tigran for being on standby 😄

**Comment by alexeygritsenko** [comment]
> Investigating MSI uninstall logs must be the first step of the investigation.

hi, I also have a crash during deletion and there is no information window. Where can I find these logs?
