### ISSUE TITLE
How to send WM_SETTINGCHANGE at end of installation with Wix#?

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#844]
Hallo, i have problem to understand how to send WM_SETTINGCHANGE in Wix#? 
Found at Wix Toolset homepage https://wixtoolset.org/documentation/manual/v3/customactions/wixsettingchange.html .
how can i add it in my Installer ? Comes this CA from Wix Toolset and WixUtilExtension ?

**Comment by oleg-shilo** [comment]
You can simply send the message from your CA or event with `SendMessageTimeout`:

```C#[Flags]
public enum SendMessageTimeoutFlags : uint
{
    SMTO_NORMAL = 0x0,
    SMTO_BLOCK = 0x1,
    SMTO_ABORTIFHUNG = 0x2,
    SMTO_NOTIMEOUTIFNOTHUNG = 0x8
}

[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(
IntPtr hWnd,
uint Msg,
UIntPtr wParam,
IntPtr lParam,
SendMessageTimeoutFlags fuFlags,
uint uTimeout,
out UIntPtr lpdwResult);
 
static void project_AfterInstall(SetupEventArgs e)
{
    SendMessageTimeout(...);

}    
``` 

But you can also call `Environment.SetEnvironmentVariable` that in turn invokes `SendMessageTimeout` anyway.

**Comment by Torchok19081986** [comment]
Hallo @oleg-shilo. Many thanks for answer. I will implent it in my installer.

**Comment by Torchok19081986** [comment]
Moin @oleg-shilo. I implemented CA to setenv in CA. Works really good. Only one thing: somehow  my installed enviroment variable with path cant be removed at uninstall. Do i have to add remove env var CA at uninstall ? i thought, msi does changes at envrioment at uninstall at installpoint msi . Is this idea right?

**Comment by oleg-shilo** [comment]
if you manually create envar on install, then you also need to manually remove it on uninstall.
