### ISSUE TITLE
Broken Wiki Link

### ISSUE THREAD

**Issue by leek9** [oleg-shilo/wixsharp#845]
Found a "broken" link in one of the file I wouldn't want anyone to click on in this file.
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp/Compiler.cs

Keep up the good work.

Thanks,
Kim

**Comment by oleg-shilo** [comment]
OMG
I clicked it. LOL
Who would think that the content of that url would change so much over the years. :)
Thank you so much for letting me know.

Fixed

**Comment by leek9** [comment]
Haha, thanks for prompt response. Closing.
