### ISSUE TITLE
Set INSTALLDIR in bootstrapper ?

### ISSUE THREAD

**Issue by ju2pom** [oleg-shilo/wixsharp#846]
Hi,
I'm trying to get rid of the MSI dialog boxes and implement all user's choices in the bootstrapper's UI (BootStrapperApplication + WPF ). I'm starting with the most basic property: INSTALLDIR but it seems I'm not doing it the right way. The user choice is correctly carried out to the MSI as a variable, but then I don't know how to dynamically change the installation directory.
I tried the following:
```csharp
private static void OnBeforeInstall(SetupEventArgs e)
{
    e.InstallDir = e.Session.Property("DESTINATION").ToString();
}
```
But with no success :-(
What am I doing wrong? Is it possible?

**Comment by vokounjan** [comment]
Hi,

I believe that your issue is that you are setting the InstallDir property too late (it's a special property that needs to be set soon). Can you try to change the InstallDir in UIInitialized, UILoaded or Load event? I'm using the same UI model (BA + WPF) but switched from handlers to custom actions so I'm not sure which one suits the best.

I also believe that if you wanted to make things easier you could just rename your DESTINATION property (if you set it directly from BA) to INSTALLDIR and it would work automatically.

**Comment by ju2pom** [comment]
Thanks, I've got better result now using the Loaded event.
But I think I don't set correctly the path in the files definition.
Here is one of the file to install:
`new Dir(Path.Combine("[INSTALLDIR]", "Resources"), new File(Path.Combine(platformPath, "Resources", "world.xml")))`

Do you have any advice on this?

**Comment by ju2pom** [comment]
All good, I got it right now, I just had to move subfolders declaration inside the main install dir declaration. I'm not sure I'm clear, but your first advice about using the Load event was perfect.
Thanks a lot for your fast and accurate answer !

As you already did it, how do you completely remove any UI for the MSI?

**Comment by vokounjan** [comment]
Glad to help.

What do you mean by completely removing UI? Do you want to run the installer from the command line?

There's Command property in the BootstrapperApplication class which has a GetCommandLineArgs() method so I'm just using something like:

`
Engine.Detect();

if (Command.GetCommandLineArgs().Length != 0)
{
    HandleCommandLineArguments(Command.GetCommandLineArgs()); // plan action there
    return;
}
else
{
    // show UI
}
`

**Comment by vokounjan** [comment]
Looking at the WiX installer example is also adviced quite often. They use the Command.Display property which may be more useful for you but I haven't tried it personally - I just check and parse the arguments and determine what to do.

[Link to Wix BA](https://github.com/wixtoolset/wix3/blob/develop/src/Setup/WixBA/WixBA.cs)

**Comment by ju2pom** [comment]
Thanks again for your help.
Currently the minimum UI I could setup for the MSI (not for the Bootstrapper) is using this piece of code:
`project.UI = WUI.WixUI_ProgressOnly;`
which is acceptable to me.
Actually ideally I'd like to force the msi to install like if I had used the following command line
`msiexec /i {guid-code} /qn`

**Comment by vokounjan** [comment]
Please try setting this ```MsiPackage.DisplayInternalUI = false``` .

I'm using ```ManagedProject``` instead of ```Project``` (inherited) and I'm not setting ```project.UI``` but ```ManagedUI = ManagedUI.Empty```. Not sure if it's really needed though.

**Comment by ju2pom** [comment]
Bingo, exactly what I needed!
I'll have to report installation progress in my UI but I remember having seen such a use case in the samples.
Thanks for your help.

**Comment by vokounjan** [comment]
Glad to help.  :blush: 

```ExecuteProgress``` and ```Progress``` event handlers from ```BootstrapperApplication``` will be your friends.
