### ISSUE TITLE
Download package instead of embedding it

### ISSUE THREAD

**Issue by ju2pom** [oleg-shilo/wixsharp#847]
I'd like to reduce as much as possible the installer size which currently include 14Mb from VC++ redist 2019. I tried the following which does not work because of the SourceFile property:
```csharp
new ExePackage()
{
	Vital = true,
	Compressed = true,
	Id = "VCPlusPlus_Redist_2019",
	SourceFile = @"C:\tmp\",
	Permanent = true,
	PerMachine = true,
	DetectCondition = "VCPlusPlus2015_64 >= VCPlusPlus2015_64_RequiredVersion",
	InstallCommand = $"/install /quiet /norestart /ChainingPackage \"[{ProductName}]\"",
	DownloadUrl = @"https://aka.ms/vs/16/release/vc_redist.x64.exe"
},
```
I tried to not provide a value to SourceFile but it's not working either.
I really don't see what it is used for when the file should be downloaded from the specified URL?

**Comment by oleg-shilo** [comment]
WiX Burn packages support downloading from URL. This is pseudo-code that  shows the idea:

```C#
<ExePackage
    Id="Netfx4FullExe"
    Cache="no"
    Compressed="no"
    PerMachine="yes"
    Permanent="yes"
    Vital="yes"
    SourceFile="C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bootstrapper\Packages\DotNetFX40\dotNetFx40_Full_x86_x64.exe"
    InstallCommand="/q /norestart /ChainingPackage FullX64Bootstrapper"
    DetectCondition="NETFRAMEWORK35='#1'"
    DownloadUrl="http://go.microsoft.com/fwlink/?LinkId=164193" />
```

**Comment by ju2pom** [comment]
Hi Oleg,
Thank you for your answer, I could make it work providing the SourceFile property with the following path:
`SourceFile = "C:/Program Files (x86)/Microsoft SDKs/ClickOnce Bootstrapper/Packages/vcredist_x64/vc_redist.x64.exe",`
But I don't understand what this path is used for, what happens if the computer on which the software is installed does not have this path?
I'd prefer to provide the user's temporary folder `%Temp%`.

Thanks.

**Comment by oleg-shilo** [comment]
yeah t am also puzzled about `SourceFile`. You will need to look at Burn documentation to understand how to deal with this element in case of downloading. 

Remember, WixSharp in many cases (like this one) simply a compiler. It is the underlying component that does the work at runtime.

**Comment by ju2pom** [comment]
Ok, understood. Thanks again :)
