### ISSUE TITLE
MajorUpgrade failing to generate msi

### ISSUE THREAD

**Issue by ju2pom** [oleg-shilo/wixsharp#848]
Hi,
I sadly release a buggy installer recently which prevents my customers to install any version of my product (because it says a newer product is already installed).
I'd like to produce an installer that bypass this restriction, so I though I'd use MajorUpgrade class which seems designed for this purpose.
But sadly when I set `AllowDowngrades = true` it produces the following error:

`setup.wxs(13) : error LGHT0103 : The system cannot find the file 'SourceDir\ProductName'.`

```csharp
    project.GUID = new Guid(ProductId);
    project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
    project.MajorUpgrade = new MajorUpgrade
    {
      Schedule = UpgradeSchedule.afterInstallInitialize,
      AllowDowngrades = true,
      AllowSameVersionUpgrades = true,
      DowngradeErrorMessage = $"A later version of {ProductName} is already installed. Setup will now exit."
    };

    project.ReinstallMode = "a";

    // project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;
    project.PreserveTempFiles = true;
    project.ControlPanelInfo.ProductIcon = Path.Combine(rootPath, "logo", "logo.ico");
    project.ControlPanelInfo.Manufacturer = Manufacturer;
    project.ValidateBackgroundImage = false;
    project.BannerImage = Path.Combine(rootPath, "logo", "banner-installer.bmp");
    project.BackgroundImage = Path.Combine(rootPath, "logo", "background-installer.bmp");
    project.Platform = Platform.x64;
    project.InstallPrivileges = InstallPrivileges.elevated;
    project.InstallScope = InstallScope.perMachine;
    project.Version = version;
    project.OutFileName = $"{InstallerBaseName}_{version.ToNoRevisionString()}";
    project.ManagedUI = ManagedUI.Empty;
    project.Include(WixExtension.Util);
    project.Load += OnLoadMSI;

    var outputFile = Compiler.BuildMsi(project);
```

Is there something I'm doing wrong? Or maybe there's a better way to fix my customer problem?

**Comment by oleg-shilo** [comment]
It looks like a path problem not downgrade.

Try setting 
```c#
Compiler.EmitRelativePaths = false;
project.PreserveTempFiles = true;
``` 
and this will produce the full abs path. This will help you to identify the faulty path that fails your build

**Comment by ju2pom** [comment]
Thanks for your answer, I didn't know about `EmitRelativePaths` propety.
It ended up that the issue was that `AllowDowngrades` and `AllowSameVersionUpgrades` cannot be set to `true` at the same time.
