### ISSUE TITLE
SourceBaseDir not working

### ISSUE THREAD

**Issue by CAIIIA** [oleg-shilo/wixsharp#85]
Hello,
Trying to add absolute path with SourceBaseDir=@"C:\somefolder" to files to be included in msi . 
Resulting wxs   shows just Source="filname.exe" but no no path added. As the result I'm getting 
"error LGHT0103 : The system cannot find the file 'filename.exe"

Digging into wixsharp source code I found that 
While stepping through Comiler.BuildWxs(Project project, string path, OutputType type)
Once doc variable created Source attribute of File elements has full path 
untill method AutoElements.NormalizeFilePaths(doc, project.SourceBaseDir, EmitRelativePaths) called which deletes fullpath for some reason

If commented out normalizing it works fine

**Comment by oleg-shilo** [comment]
`SourceBaseDir` controls only the base (starting point) of your path but not the way it is expressed.
If you want to have absolute path in your WiX then you need to use EmitRelativePaths setting. 
```
Compiler.EmitRelativePaths = false;
```

**Comment by CAIIIA** [comment]
Thanks you. That works
