### ISSUE TITLE
Question: How to create custom WPF BA that only copies files to destination ?

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#851]
Hallo, can someone send me pls link or example, how to create custom WPF BA that only copy files to destination ? I want only copy files from WPF BA to destination with all includes msi´s and exe, and nothing should be installed .

**Comment by geghamyan** [comment]
Hi,
Wix Burn Bootstrapper is not fire-and-forget bootstrapper - it gets installed on a machine. You can explore an option to uninstall itself at the end of the installation, but I have never tried that.
Try using NsisBootstrapper to show your WPF application as a primary payload, which programmatically will copy artifacts to the destination.

References about Wix Burn:
https://stackoverflow.com/questions/20995779/wix-burn-how-to-stop-bootstrapper-from-installing-itself
