### ISSUE TITLE
Obtain INSTALLDIR in Update\Reinstall mode

### ISSUE THREAD

**Issue by meytes** [oleg-shilo/wixsharp#855]
Oleg, hello

Its was not possible to find the answer to the question: "How to get the installation folder (INSTALLDIR) from the previous version of program, without dancing with a tambourine"

My configuration is: Embedded UI on WPF. Update mode is enabled.
MsiExec service itself knows where the program is located and correctry removes\repair it, but how obtain this location?

Прости за мой английский, продублирую подробнее на русском.

Олег, здравствуйте :) 

Искал в интернетах, и в этих issues, но так и не смог найти вразумительного ответа на свой вопрос: "Как получить папку установки предыдущей версии программы, без танца с бубном"

Использую вариант Embedded UI на WPF, обновление включено (MajorUpgradeStrategy), UpdateCode'ы и прочее, всё задано и всё отлично работает.
Необходимо, чтоб на этапе обновления была известная папка установки программы предыдущей версии. 
Очевидно, что сам сервис msiexec знает где находится программа, ведь он корректно её удаляет перед обновлением или восстанавливает, без всяких путёй.  

Сделал дамп сессии, дамп базы с временными таблицами, но нигде этого значения я не нашел (путь куда установленная старая версия программы).
По большей части, все предлагают сохранять параметр INSTALLDIR в реестр, но этот вариант неплох, только когда делается самая первая версия инсталлятора и потом все работают со значением из реестра. Но у меня вариант, когда инсталлятор далеко не 1 версии.

**Comment by oleg-shilo** [comment]
Hi Roman, sorry I can understand Russian but typing for me is a challenge and my technical terminology in Russian is killing me. So will answer in English.

Yes saving the installdir is the only simple and reliable option. And yes again, it will not work if you have no control over the very first installation of the product.

Well, this means that you can only rely on the product installation details in the registry.
It's possible but not trivial. Pretty much like "dancing with a tambourine".

**Comment by vokounjan** [comment]
> Well, this means that you can only rely on the product installation details in the registry.
It's possible but not trivial. Pretty much like "dancing with a tambourine".

I have this extension methods:

```csharp
public static void CreateRegistrySearchValue(this Project project, string registryName, string propertyName)
{
    project.AddRegistryValue(registryName, propertyName.WithBrackets());
    project.AddRegistrySearchProperty(registryName, propertyName, string.Empty);
}

public static void AddRegistryValue(this Project project, string registryName, object registryValue)
{
    var regValue = new RegValue(RegistryHive.LocalMachine, ProjectConstants.RegistryKey + project.Name, registryName, registryValue)
    {
        Win64 = false // I couldn't make Win64 work :(
    };

    project.RegValues = project.RegValues.Combine(regValue);
}

public static void AddRegistrySearchProperty(this Project project, string registryName, string propertyName, string propertyValue)
{
    var registrySearch = new RegistrySearch(RegistryHive.LocalMachine, ProjectConstants.RegistryKey + project.Name, registryName, RegistrySearchType.raw)
    {
        Win64 = false // I couldn't make Win64 work :(
    };

    var registrySearchProperty = new PublicProperty(propertyName, propertyValue)
    {
        IsDeferred = true,
        Secure = true,
        GenericItems = new IGenericEntity[]
        {
            registrySearch
        }
    };

    project.Properties = project.Properties.Combine(registrySearchProperty);
}
```

where `ProjectConstants.RegistryKey` is `@"SOFTWARE\MyCompany\"`.

I'm using them to save web application (web app pool name, web site name, web application name) and windows service (name) information but it could be used for "remembering" INSTALLDIR as well.

**Comment by meytes** [comment]
i am found another soluthion
1. Get 'UpgradeCode' property value
2. Get 'ProductCode' by 'UpgrageCode' (WinApi method `MsiEnumRelatedProduct`s from msi.h) or `AppSearch.GetRelatedProducts(upgradecode)`
3. Gets LocalPackage from ProductCode (WinApi method `MsiGetProductInfo(productCode, "LocalPackage"), ...)`, method return local path to msi file (example: C:\windows\installer\file.msi)
4. open msi database (i am use `Database(file,mode)` class) and read all components in fields: componentId and Direcotory_, with filter by attributes != 0 and directory_ = 'INSTALLDIR'
Query for view:
```
SELECT ComponentId, Directory_ FROM `Component` WHERE Attributes=0 AND Directory_='INSTALLDIR'
```
5. get installation path for each component (WinApi method `MsiGetComponentPath(productCode, componentId, ...)` and check exists file. if file exists we found install dir.

Thanks @oleg-shilo and @vokounjan 
I thought you know Russian, sorry.
P.S. Sorry for my English

**Comment by oleg-shilo** [comment]
Yep :) this was the solution that started describing in my yesterday answer but then decided against it as I am not sure if the db (msi file) will contain the accurate information about the **actual** install dir.

If it does, then it's a perfect solution that I wouldn't mind even incorporating to the codebase. 

Can you do me a favor? A little experiment. 
Install a test msi but ensure you have selected a custom install dir. After that check if the technique you are proposing returns the correct result. My speculation is that irt will return the default install dir but not the one you have selected.

But... I will be thrilled to learn that I am wrong :)
