### ISSUE TITLE
INSTALL_DIR  should be INSTALLDIR

### ISSUE THREAD

**Issue by CADbloke** [oleg-shilo/wixsharp#856]
`INSTALL_DIR` is used in the sample at https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Shortcuts-2/setup.cs but it should not have the underscore in it. The underscore made the shortcut point at the desktop.

Please also check the files in ... https://github.com/oleg-shilo/wixsharp/search?q=install_dir&unscoped_q=install_dir

Sorry no pull request, I wasn't sure about the other files and my brain is maxed out today.

**Comment by oleg-shilo** [comment]
Fantastic, thank you very much. 
All the samples are updated now.
