### ISSUE TITLE
Use WPF External UI when uninstall 

### ISSUE THREAD

**Issue by JasShao** [oleg-shilo/wixsharp#857]
Hello Oleg!
I want to use WPF External UI when uninstall . Do you konw how can I do that ? Thank you

**Comment by oleg-shilo** [comment]
I kind of do :)

Have a look at this sample: https://github.com/oleg-shilo/wixsharp/blob/67c57624b5bc3db389f35ee6dd540da33070409d/Source/src/WixSharp.Samples/Wix%23%20Samples/External_UI/WpfSetup/MyProductSetup.cs

![image](https://user-images.githubusercontent.com/16729806/83511274-bcdf4f80-a511-11ea-9211-01fdccfa5af2.png)

**Comment by JasShao** [comment]
> I kind of do :)
> 
> Have a look at this sample: https://github.com/oleg-shilo/wixsharp/blob/67c57624b5bc3db389f35ee6dd540da33070409d/Source/src/WixSharp.Samples/Wix%23%20Samples/External_UI/WpfSetup/MyProductSetup.cs
> 
> ![image](https://user-images.githubusercontent.com/16729806/83511274-bcdf4f80-a511-11ea-9211-01fdccfa5af2.png)

Hello Oleg!
Thank you for your suggestion.But more specifically,I want to use WPF External UI when uninstall in 'control panel'. I didn't talk this problem clear at first , sorry. :)

**Comment by oleg-shilo** [comment]
Ah, then it is not an external UI :)

External UI is an app that bundles an MSI and fully manages how it is invoked as well as fully handles user interactions. Thus user starts External UI application by running the application executable. 

What you are referring is so called "Embedded UI" - an MSI technology that allows developer to suply an alternative implementation of the UI dialogs but for the install session that is managed by the msi runtime service. And it is the msi service that displays the dialogs of the Embedded UI when user triggers install action via control panel or by opening msi file.

Anyway, you are out of luck :(
Embedded UI is only supported for install/Modify. MSI runtime does not offer any functionality for a custom uninstall UI.

**Comment by JasShao** [comment]
> 嗯，那不是外部用户界面:)
> 
> 外部用户界面是一个捆绑了MSI并完全管理其调用方式并完全处理用户交互的应用程序。因此，用户通过运行应用程序可执行文件来启动外部UI应用程序。
> 
> 您所指的是所谓的“嵌入式UI”-一种MSI技术，它使开发人员可以为UI对话框提供替代实现，但适用于由msi运行时服务管理的安装会话。当用户通过控制面板或通过打开msi文件触发安装操作时，msi服务将显示嵌入式UI的对话框。
> 
> 无论如何，您都不走运：(
> 仅支持嵌入式UI进行安装/修改。MSI运行时不为自定义卸载UI提供任何功能。

That's all right. I know what should I do now. Your answer saved me a lot of time . Thank you :)
