### ISSUE TITLE
NHibernate.dll in Custom Actions

### ISSUE THREAD

**Issue by NikGovorov** [oleg-shilo/wixsharp#86]
Hi Oleg,

I have an issue packing NHibernate.dll to *.CA.dll, it's packed just as NHibernate(without dll extension). I assume we loose the file extension on the following line: https://github.com/oleg-shilo/wixsharp/blob/46758d22bf18576643f8996604e3dc8aaac921eb/Source/src/WixSharp/ProjectValidator.cs#L225. **Probably it happens because NHibernate is ilmerged**. The only workarounds I see now are run-time ones: custom assembly resolver, assemblyBinding/dependentAssembly/codeBase section in CustomAction.config or even just rename 'NHibernate' file to 'NHibernate .dll' before executing a custom action.

Thoughts?

**Comment by oleg-shilo** [comment]
It's a defect. Will look at it.
As a temp work around indeed AppDomain assembly resolver seems to be the most practical approach.

**Comment by oleg-shilo** [comment]
Fixed (commit a248dd643c009cada90ac3832f0ed42c84934f31). The fix will be available with the very next release. There are some pull requests to be released so I will be making a release early next week.

Thank you for reporting the defect.

**Comment by NikGovorov** [comment]
Great job, thanks!
