### ISSUE TITLE
Digitally Sign Bootstrapper and MSIs using SHA256

### ISSUE THREAD

**Issue by jonreis** [oleg-shilo/wixsharp#860]
I was trying to get my Bootstrapper and MSIs to be digitally signed using SHA256. I want to do this because SHA1 is not secure. The installers I have seen from Microsoft seem to all be signed with SHA256 these days.

I was able to get this to work but I had to leave the TimeUrl null and add the command-line arguments manually.

        OptionalArguments = "/du www.HL7Spy.com /v /tr http://timestamp.comodoca.com /td sha256",

For DigitalSignatureBootstrapper I also had to add

      if (typeof(T) == typeof(DigitalSignatureBootstrapper))
        digitalSignature.OptionalArguments += " /fd sha256";

It seems for the DigitalSignatureBootstrapper setting HashAlgorithm = HashAlgorithmType.sha256 does nothing so it always comes out signed as SHA1

I have been using the SignTool command line arguments from the following link that seem to work well for the 3 different cases: SHA1, SHA256, and Dual Sign.

http://www.ssesetup.com/articles/codesigning-sha256.html

It would be great if there were a way of specifying: (1) SHA1Only, (2) SHA256Only, and (3) DualSign in the DigitalSignature class.

**Comment by oleg-shilo** [comment]
Can you please elaborate?

This is how `DigitalSignature` implements `Apply`:

```C#
public virtual int Apply(string fileToSign)
{
    var retValue = CommonTasks.Tasks.DigitalySign(fileToSign, 
                                                  CertificateId, TimeUrl?.AbsoluteUri, Password,
        PrepareOptionalArguments(), WellKnownLocations, CertificateStore, false, OutputLevel, HashAlgorithm);

```

**Comment by jonreis** [comment]
Hello Oleg, sorry for the late response.

Here are the command-line options that seem to work without a signtool error.

1) SHA-1 Sample SignTool line: SignTool.exe /f "C:\MyFolder\MyCert.pfx" /p "PFX Password" /t "http://timestamp.comodoca.com/authenticode" "C:\MyFolder\MyFile.exe"
2) SHA-256 Sample SignTool line (NOT dual signing): SignTool.exe /f "C:\MyFolder\MyCert.pfx" /p "PFX Password" /fd sha256 /tr "http://timestamp.comodoca.com?td=sha256" /td sha256 "C:\MyFolder\MyFile.exe"
3) SHA-256 Sample SignTool line (Dual signing): SignTool.exe /f "C:\MyFolder\MyCert.pfx" /p "PFX Password" /fd sha256 /tr "http://timestamp.comodoca.com?td=sha256" /td sha256 /as "C:\MyFolder\MyFile.exe"

All variations that I have tried with WixSharp produce only the SHA1 signing. Verified by right-clicking on the output and checking the digital signature.

I would like to use option (2) as sha256 seems to be the standard used by Microsoft's packages these days.

To get this to work I need the following in the command-line: /fd sha256 /tr "http://timestamp.comodoca.com?td=sha256" /td sha256 in the commandline, but if you look at the logic for DigitalySign it is not possible to get /tr "http://timestamp.comodoca.com?td=sha256" /td sha256 with dualSign=false.

using the /t option with sha256 generates a signtool error for me.

            if (timeURL != null)
                hash += $" /t \"{timeURL}\"";

I need these 2 lines

            string sha256 = args + " /as /fd sha256";
            if (timeURL != null)
                sha256 += $" /tr \"{timeURL}\" /td sha256";

to get my /tr and /td options for sha256. But these never can get call via DigitalSignature.Apply() or DigitalSignatureBootstrapper.Apply().

It looks like DigitalySign is building up the command-line to always sign using SHA1. If dualsign=true (which it never is), then it attempts to build up a second command line to sign using sha256. DualSign is set to false by both DigitalSignature and DigitalSignatureBootstrapper.

In addition, if you look at the implementation of DigitalSignatureBootstrapper.Apply(), and trace the call down to DigitallySign you will see that it always uses the default HashAlgorithmType hashAlgorithm = HashAlgorithmType.sha1 so the bootstrapper is always signed with SHA1.

>  return DigitalySign(bootstrapperFileToSign, pfxFile, timeURL, password, optionalArguments, wellKnownLocations, useCertificateStore ? StoreType.commonName : StoreType.file, dualSign, outputLevel);

note the missing parameter HashAlgorithmType hashAlgorithm in the call to DigitalySign above. So it picks up the default value of HashAlgorithmType.sha1. So all Wix Bundles are always signed only as SHA1

**Comment by jonreis** [comment]
No problem Oleg. If you like I can take a crack at it and give you a PR, but it probably won't happen until next week because I have a lot going on right now.

**Comment by oleg-shilo** [comment]
>  If you like I can take a crack at it and give you a PR

To be honest I would so appreciate it. Right now my bandwidth is so narrow that I would not be able to approach this task for a week or two.

**Comment by oleg-shilo** [comment]
Thank you for such a detailed report and analysis.
Yes it is a defect.
Will work on it.
