### ISSUE TITLE
Error 1334 when upgrade

### ISSUE THREAD

**Issue by JasShao** [oleg-shilo/wixsharp#861]
Hello Oleg!
I tried to upgrade application. But the msi return error code '1603'.And I found error code 1334 in log file.
`Error 1334. The file 'data.sqlite_3540097125' cannot be installed because the file cannot be found in cabinet file 'vin.cab'. This could indicate a network error, an error reading from the CD-ROM, or a problem with this package.
MSI (s) (80:74) [09:41:37:374]: Product: vin -- Error 1334. The file 'data.sqlite_3540097125' cannot be installed because the file cannot be found in cabinet file 'vin.cab'. This could indicate a network error, an error reading from the CD-ROM, or a problem with this package.`

I checked files in new package(msi). It has a new sqlite file , the other files is same as old package .
Do you konw why this happend? Can't I  package new files in upgrade msi ? Thank you

**Comment by JasShao** [comment]
Hello Oleg!
I found that whatever msi I excute will fail with error code 1334 just now. So....I restart my computer , and the problem is gone . Maybe I trigger some bugs in msi . It's so weird ! Do you have experience like this?

**Comment by oleg-shilo** [comment]
I think I have seen it but do not remember a great deal of details. One thing that I do remember well is that (as you probably already guessed) it has nothing to do with the networking. It's one of those cases when MSI error wording is shockingly misleading.

And, yes it was something that gone as quickly and unexpectedly as it came in the picture :)
