### ISSUE TITLE
How to let the installer run as admin just after double clicking the installer

### ISSUE THREAD

**Issue by milhousemanastorm** [oleg-shilo/wixsharp#863]
I am trying to let the installer ask for admin permission just after double clicking the installer.

By default, the installer only asks for admin permission before ProgressDialog Dialog shows up. Is there a way to let it ask for admin permission before Welcome Dialog?

**Comment by oleg-shilo** [comment]
This probably will help you to achieve that:
```C#
project.InstallPrivileges = InstallPrivileges.elevated;
```
It sets the package attribute:
![image](https://user-images.githubusercontent.com/16729806/83969448-732ca580-a913-11ea-9286-903e4dbdead1.png)

**Comment by milhousemanastorm** [comment]
> This probably will help you to achieve that:
> 
> ```cs
> project.InstallPrivileges = InstallPrivileges.elevated;
> ```
> 
> It sets the package attribute:
> ![image](https://user-images.githubusercontent.com/16729806/83969448-732ca580-a913-11ea-9286-903e4dbdead1.png)

I tried it but the result is still the same.

What I am trying to do is:

This Window:
![Screen Shot 2020-06-07 at 11 34 23 AM](https://user-images.githubusercontent.com/61845485/83973246-11d4ea00-a8b3-11ea-90a6-b895d9f0db70.png)

shows up before Welcome:
![Screen Shot 2020-06-07 at 11 36 47 AM](https://user-images.githubusercontent.com/61845485/83973268-34670300-a8b3-11ea-9772-75361479c933.png)

But the result is (even after I added: project.InstallPrivileges = InstallPrivileges.elevated;)

This Window:
![Screen Shot 2020-06-07 at 11 34 23 AM](https://user-images.githubusercontent.com/61845485/83973246-11d4ea00-a8b3-11ea-90a6-b895d9f0db70.png)

shows up before ProgressDialog:
![Screen Shot 2020-06-07 at 11 34 33 AM](https://user-images.githubusercontent.com/61845485/83973318-9162b900-a8b3-11ea-8b46-1f7f69ba1b6f.png)

Is there a way to do that?

**Comment by oleg-shilo** [comment]
Correct. MSI always pops up all pre-install dialogs (e.g. welcome) before any elevations. That attribute (I suggested) only ensures the install stage is elevated. The starge that starts with the progress dialog. 

You have only two choices then:
- Create a custom or Burn bootstrapper application that is marked as the elevateable with the manifest file.
- In the pre-launch condition check that the process is elevated and if not abort the installation and ask the user to start msi as elevated.

**Comment by milhousemanastorm** [comment]
> Correct. MSI always pops up all pre-install dialogs (e.g. welcome) before any elevations. That attribute (I suggested) only ensures the install stage is elevated. The starge that starts with the progress dialog.
> 
> You have only two choices then:
> 
> * Create a custom or Burn bootstrapper application that is marked as the elevateable with the manifest file.
> * In the pre-launch condition check that the process is elevated and if not abort the installation and ask the user to start msi as elevated.

The first choice works for me, thank you!

**Comment by MANGLARAM** [comment]
how?

**Comment by oleg-shilo** [comment]
Have a look at "Self-executable_Msi" sample:

https://github.com/oleg-shilo/wixsharp/tree/wix-v3-master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/Self-executable_Msi

https://github.com/oleg-shilo/wixsharp/tree/wix-v4-master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/Self-executable_Msi

You only need to add the manifest file with the elevation request. This is a normal .NET task that you will easily find how to do on SO.
