### ISSUE TITLE
How to make maintenance mode be able to select install path

### ISSUE THREAD

**Issue by milhousemanastorm** [oleg-shilo/wixsharp#864]
I am trying to make the maintenance mode the same as install mode. Then I read this:

https://github.com/oleg-shilo/wixsharp/issues/549

After I made both modes have the same dialogs, I found that the maintenance mode always copies files to the original path, even if I selected a different path in InstallDirDialog.

Is there a way to select path under maintenance mode.

Or is there a way not to register the product so that every time the user double clicks the msi file, it is a brand new install ?

**Comment by oleg-shilo** [comment]
> Is there a way to select path under maintenance mode.

I am not sure you can do it. AFAIU MSI workflow does not allow that.

> ... so that every time the user double clicks the msi file, it is a brand new install ?

It's quite an unusual requirement but yest it is possible. Set product identity to a new ID every time you build and you'll have the desired behavior:

```C#
project.GUID = Guid.NewGuid();  
```

**Comment by milhousemanastorm** [comment]
> > Is there a way to select path under maintenance mode.
> 
> I am not sure you can do it. AFAIU MSI workflow does not allow that.
> 
> > ... so that every time the user double clicks the msi file, it is a brand new install ?
> 
> It's quite an unusual requirement but yest it is possible. Set product identity to a new ID every time you build and you'll have the desired behavior:
> 
> ```cs
> project.GUID = Guid.NewGuid();  
> ```

I am trying to make an installer to have multiple-install feature, i.e. an installer can install to C:\A, C:\B, C:\C, C:\Z without uninstalling.

My current plan is that (under install mode):
1. Let it install to a temp folder
2. Copy temp folder and files to the real install path
3. Uninstall, so that the Program will not be listed in "Uninstall or change program" of Control Panel and  the files under temp folder will be removed

Then if the user ran the installer again the mode is still the install mode.

Is there a way to let the installer uninstall after ProgressDialog finishes ?

**Comment by oleg-shilo** [comment]
Yes there is.
You can run an elevated msiexec process in the `AfterInstall` event. Or from the `ExitDialog,OnClose`

Something like that:
```C#
project.AfterInstall += e=>
{
    if (!e.IsUninstalling)
    {
        Process.Start("msiexec.exe", $"/x ""{e.MsiFile}""");
    }
};
```

**Comment by milhousemanastorm** [comment]
Thanks for the author's help.
