### ISSUE TITLE
How to copy msi file to specific location after installation ?

### ISSUE THREAD

**Issue by ypicard** [oleg-shilo/wixsharp#868]
Hi,

After installing my msi, I would like it to copy / move itself to a specific location. This would be to have a folder containing all msis of all versions that were installed on a computer in a specific folder. Is this possible ?

Thank you for your work,

**Comment by oleg-shilo** [comment]
While it is a bit unusual scenario it is possible to implement.

```C#
project.AfterInstall += args =>
{
    if (!args.IsUninstalling)
        System.IO.File.Copy(args.MsiFile, 
                            args.MsiFile.PathChangeDirectory("<destination dir>"));
};

```
