### ISSUE TITLE
How to start PowerShell script after installing the files in the INSTALL folder?

### ISSUE THREAD

**Issue by Alex-fbr** [oleg-shilo/wixsharp#869]
// Check for .NET Framework Version for Installer
            project.SetNetFxPrerequisite("WIX_IS_NETFRAMEWORK_461_OR_LATER_INSTALLED >= '#394254'", "requires .NET Framework 4.6.1 or higher.");

            // При установке продукта
            project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                            .Add<LicenceDialog>()
                                            .Add<InstallDirDialog>()
                                            .Add<ProgressDialog>()
                                            .Add<ExitDialog>();
            // При удалении продукта
            project.ManagedUI.ModifyDialogs.Add<MaintenanceTypeDialog>()
                                           .Add<ProgressDialog>()
                                           .Add<ExitDialog>();

            // Запуск скрипта после установки файлов
            project.Actions = new WixSharp.Action[]
            {???

В оригинальном Wix можно было скачать нугет  и сделать так:

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:powershell="http://schemas.gardiner.net.au/PowerShellWixExtensionSchema">

 <InstallExecuteSequence>
      <Custom Action="PowerShellScriptsDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellScriptsElevatedDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellFilesDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellFilesElevatedDeferred" After="InstallFiles">NOT Installed</Custom>
    </InstallExecuteSequence>
    <powershell:File Id="PSFile1" File="[#ScriptPs1]" />

  </Product>

  <Fragment>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLFOLDER" Name="WixCascana">
          <Directory Id="PUBLISH" Name="Publish"/>
        </Directory>
      </Directory>
    </Directory>
  </Fragment>

  <Fragment>
    <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
      <Component Id="ProductComponent" Guid="{C9987787-CAD0-49BC-9EFE-53F0EF46FA18}">
        <File Id="ScriptPs1" Source="..\Distributive\CopyFilesToRemoteHosts.ps1"/>
      </Component>
    </ComponentGroup>
  </Fragment>
</Wix>

**Comment by Alex-fbr** [comment]
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:powershell="http://schemas.gardiner.net.au/PowerShellWixExtensionSchema">
  <?define UpgradeCode = "{e7f35bef-2be4-40e9-890a-00e165b4db9e}"?>
  <?define ProductCode = "{2908C8B7-36C3-4227-9008-7E7F08278B73}"?>

  
  <Product Id="$(var.ProductCode)"
           Name="!(loc.ProductName_$(var.Platform))"
           Language="!(loc.Language)"
           Version="1.0.0.0"
           Manufacturer="!(loc.Company)"
           UpgradeCode="$(var.UpgradeCode)">

    
    <Package InstallerVersion="200"
             Compressed="yes"
             InstallScope="perMachine"
             Platform="x86"
             Manufacturer="!(loc.Company)"
             Description="!(loc.Description)"
             Comments="!(loc.Comments)"
             Languages="!(loc.Language)"
             Keywords="!(loc.Keywords)"
             />

    <Property Id="VIRTUALDIRECTORYA" Value="xxx"/>
    <Property Id="VIRTUALDIRECTORYB" Value="yyyy"/>

    <MajorUpgrade DowngradeErrorMessage="!(loc.DowngradeErrorMessage)" />

    <MediaTemplate EmbedCab="yes" />

    <Feature Id="ProductFeature" Title="WixCascana" Level="1">
      <ComponentGroupRef Id="PublishedComponents" />
      <ComponentGroupRef Id="ProductComponents" />
    </Feature>

    <UIRef Id="MyWebUI" />

    <InstallExecuteSequence>
      <Custom Action="PowerShellScriptsDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellScriptsElevatedDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellFilesDeferred" After="InstallFiles">NOT Installed</Custom>
      <Custom Action="PowerShellFilesElevatedDeferred" After="InstallFiles">NOT Installed</Custom>
    </InstallExecuteSequence>

    <powershell:File Id="PSFile1" File="[#ScriptPs1]" Arguments="&quot;[VIRTUALDIRECTORYA]&quot; [VIRTUALDIRECTORYA]"/>

  </Product>

  <Fragment>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLFOLDER" Name="xxx">
          <Directory Id="PUBLISH" Name="Publish"/>
        </Directory>
      </Directory>
    </Directory>
  </Fragment>

  <Fragment>
    <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
      <Component Id="ProductComponent" Guid="{C9987787-CAD0-49BC-9EFE-53F0EF46FA18}">
        <File Id="ScriptPs1" Source="..\Distributive\CopyFilesToRemoteHosts.ps1"/>
      </Component>
    </ComponentGroup>
  </Fragment>
</Wix>

**Comment by oleg-shilo** [comment]
You can do it with the runtime event (a special deferred custom action):

```C#
project.AfterInstall += args =>
{
    if (!args.IsUninstalling)
        Process.Start("powershell.exe", args.InstallDir.PathCombine("script.ps1"));
};
```

Have a look at "Managed Events" for more details.
