### ISSUE TITLE
Copying new files File: [1], Directory: [9], Size [6]

### ISSUE THREAD

**Issue by mhwlng** [oleg-shilo/wixsharp#87]
I see during installation in windows 10, texts like :

Copying new files File: [1], Directory: [9], Size [6]
installing Service : [1]
etc.

I found this :

https://stackoverflow.com/questions/44161526/wix-copying-new-files-file-1-directory-9-size-6-shown-during-instal

which states that this line needs to be added to the wxs file :

`<UIRef` Id="WixUI_ErrorProgressText" />`

Is there any way to do that in program.cs ?

**Comment by oleg-shilo** [comment]
Have a look at "XML injection" section in https://github.com/oleg-shilo/wixsharp/wiki/Developer's-Guide

```C#
    ...
    project.WixSourceGenerated += InjectUIRef;
    project.BuildMsi();
}
 
static void InjectUIRef(XDocument document)
{
    document.Root.Select("Product")
                 .AddElement("UIRef", "Id=WixUI_ErrorProgressText"); 
```

**Comment by mhwlng** [comment]
That fixes the problem, thank you

**Comment by oleg-shilo** [comment]
Closing the issue...
Reopen it if further assistance is required.
