### ISSUE TITLE
How can I log the actions of the installer? Where are logs written and where can I search for a file?

### ISSUE THREAD

**Issue by Alex-fbr** [oleg-shilo/wixsharp#870]
session.Log("CopyFilesToVirtualMachine"); -  where will this line be written?

**Comment by vokounjan** [comment]
There should be a file in your `%TEMP%` (by default) with your product name, datetime information and .msi.log extension. Your line should be written there.

If you're using plain MSI, you can specify location and name of this file with this command:

`msiexec /i "C:\MyPackage\Example.msi" /L*V "example.log"`

**Comment by Alex-fbr** [comment]
Thanks!
