### ISSUE TITLE
Add support for TypeLib registration

### ISSUE THREAD

**Issue by sonicbhoc** [oleg-shilo/wixsharp#872]
As of this moment, the `ComRegistration` class is only capable of outputting `Class` WiX XML tags. Type Libraries need to be described with the `TypeLib` WiX XML tag. `Class`es can also be children of `TypeLib`s.

**Comment by oleg-shilo** [comment]
Done. The feature will be available with the very next release.

In a mean time you can use the feature by adding the `TypeLib` class to your project so you can pass it to the `File constructor:

```C# 
new File(@"Files\Bin\MyApp.exe",
    new TypeLib
    {
        Id = new Guid("6f330b47-2577-43ad-9095-1861ba25889b"),
        Language = 33,
        MajorVersion = 23
    }

. . .

public class TypeLib : WixEntity, IGenericEntity
{
    [Xml] public new Guid? Id;
    [Xml] public bool? Advertise;
    [Xml] public bool? Control;
    [Xml] public int? Cost;
    [Xml] public string Description;
    [Xml] public bool? HasDiskImage;
    [Xml] public string HelpDirectory;
    [Xml] public bool? Hidden;
    [Xml] public int Language;
    [Xml] public int? MajorVersion;
    [Xml] public int? MinorVersion;
    [Xml] public int? ResourceId;
    [Xml] public bool? Restricted;

    public void Process(ProcessingContext context)
    {
        XElement element = this.ToXElement("TypeLib");
        context.XParent.Add(element);
    }
}
```

**Comment by sonicbhoc** [comment]
I had already started writing my own, but your implementation is missing the ability to add children. TypeLib should be able to have children of the following types:
AppId (how is this implemented in Wix# if at all?)
Interface
Class (implemented as ComRegistration in Wix#)

If you wish, I can add this functionality for you.

**Comment by oleg-shilo** [comment]
Sure. Go for it.

Add items/children to the `TypeLib` class and then in `Process` method call  their `ToXElement` one by one and add the returned XElements to the TypLib XElement's children.

Then just create PR and we are done.

**Comment by sonicbhoc** [comment]
Is it possible to create a pre-release nuget package with this change in? Or is the release with this change coming soon?

**Comment by oleg-shilo** [comment]
I'll do the pre-release within 1-2 days. Or a release if the changes critical mass is there.

**Comment by oleg-shilo** [comment]
Done. You can grab the package 1.14.7.0
