### ISSUE TITLE
Question: Wpf Setup error

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#874]
Hallo, i have some difficulty to understand, how can i make following scenario works. I tried sample WPF Setup with embeded msi, which going to be installed after extract to temp. This works fine, but i would like to start msi with features tree to select , what should be installed by user. If i try to add msi with feature tree it comes to error "The specified Feature name ('Binaries') not found in Feature Table" . All Code and msi comes from samples folder.  Code
```csharp

base.StartInstall("CUSTOM_UI=true ADDLOCAL=Binaries,Documentation");

```
Inverstigate msi with orca gave me following: 
in msi exists table Binary with elements: WixCA, WixUIWixca, WixUI_Bmp_Banner, WixUI_Bmp_Dialog, WixUI_Ico_Exclaim, WixUI_Ico_Info, WixUI_Bmp_New, WixUI_Bmp_Up. All these elements have datatype [Binary Data].

if i remove this line and add msi with featuretree to wpf-exeinstaller, it works, but doesn't show msi to startinstallation.

**Comment by oleg-shilo** [comment]
Note, you should look at table "Feature" table as the error message suggests. Not at "Binary" table.


Before we proceed any further can you confirm which sample exactly you are referring to?

It seems to me that in stead of "WPF Setup with embeded msi" you are actually trying to use "msi with embedded WPF UI" [sample](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Custom_UI/EmbeddedUI_WPF).

**Comment by Torchok19081986** [comment]
Morning Oleg, Sample i tried is in Sample folder ExternalUI/WpfSetup. This one. Here is sample of wpf with embeded msi and dll.

**Comment by oleg-shilo** [comment]
Sorry I am completely lost. 

You are saying ExternalUI/WpfSetup sample does not work. Great, let's have a look at it.

But you also mentioned working Bootstrapper/WixBootstrapper_UI sample. Why? What does it have to do with WpfSetup?

Does sample ExternalUI/WpfSetup work as is? Without any changes to it's code?

If it does and the failure is triggered by the change then what is this change?

**Comment by Torchok19081986** [comment]
ok, im going to try explain in another way.  Picture of WPFSetup: 
![WPF Setup](https://user-images.githubusercontent.com/25432729/86373884-3474db80-bc84-11ea-88fc-7fa4eaeaa41e.JPG)
if i add embed msi with featuretree , install cant be executed. Error appers from before, but in 
![bootstapper-UI](https://user-images.githubusercontent.com/25432729/86374133-81f14880-bc84-11ea-98e8-78935fe24736.JPG)
project works like expected. I would like to create exe-installer based on wpf window like first one.

**Comment by oleg-shilo** [comment]
> i add embed msi with featuretree

The sample comes with the msi having the `Feature`s that sample expects: `Binaries,Documentation`.

If you use the same sample code then your msi must have the same features. According you it does not: "The specified Feature name ('Binaries') not found in Feature Table"

So either build the msi differently (define `Binaries,Documentation`) or update the `base.StartInstall("CUSTOM_UI=true ADDLOCAL=...` to reflect your actual features' names.

**Comment by Torchok19081986** [comment]
Thats all i had to know. That mean i can create a simple MVVM for my Setup and add msi´s to install if i need pre-installations or .net framework etc. Is there posibility to set some features allways to install like binaries whatever and and another to optional ?
My new Setup should have net framework, mainbinaries like dll´s and exen and optional SQL Server Express as well.

**Comment by oleg-shilo** [comment]
You are welcome.

> Is there posibility to set some features allways

Yes there is. Just always pass the feature name in the `base.StartInstall("CUSTOM_UI=true ADDLOCAL=...`

**Comment by Torchok19081986** [comment]
Hallo Oleg, thanks again. Last question for BA, can this new created exe installer also execute another exe-installer ? AFAIK is SQL Server  have to extract to folder and then start to install. Is it possible to add something like that in BA or do i have to use msi for it ?

**Comment by oleg-shilo** [comment]
Yes you can bootstrap the exe-based setups. Have a look at the Bootstrapper in the samples distro or in the codebase on this site.  

BTW a bootstrapper setup is always executing the embedded setups buy extracting them in tee temp locations.

**Comment by Torchok19081986** [comment]
Hallo Oleg, many thanks again. How do i manipulate sequence which comes at first or do BA set in same sequence which in files was added to BA ? What if i added first SQL Server installation and then my app to install and want to start with app installation at first? Is there possibility to achieve that, somehow ?

**Comment by oleg-shilo** [comment]
Yes the sequence is defined by the order you add the items to your bootstrapper.

>... want to start with app installation at first? 

Then add it to the bootstrapper first.
