### ISSUE TITLE
UI control misplaced with font zoom

### ISSUE THREAD

**Issue by maulik-devitpl** [oleg-shilo/wixsharp#875]
Hello,

I am preparing a setup for one of my application and facing an issue related to UI control misplacement.

below is the details which may help you to inderstand.

I am using ManagerProject with one custom window as below:

project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                            .Add(Dialogs.InstallDir)
                                            .Add<CustomDialog>()
                                            .Add(Dialogs.Progress)
                                            .Add(Dialogs.Exit);

Here, CustomDialog is a custom window prepared by my self and rest are inbuild provided dialogs.

I have tried design changes with all possible resolutions and it seems working fine. But there is an option called "Change size of text, app and other items". 
![image](https://user-images.githubusercontent.com/60770288/86717955-44077200-c040-11ea-84a6-c630460d958f.png)

When i set it to 175%, UI of progress bar is not visible properly.
![image](https://user-images.githubusercontent.com/60770288/86718160-74e7a700-c040-11ea-9db3-97a62685b3bd.png)

How can i fix this UI issue?

**Comment by oleg-shilo** [comment]
Scaling is always difficult. Only WPF addresses it adequately. But still...

To be honest there is nothing to fix. It's just the default layout of all dialogs was designed to satisfy the default scaling 1:1 and any custom layout is to be defined by user (you).  
 
I suggest you create  the project from the VS project template "... Custom UI". This will add to all dialogs as a source code to your project. This way you can have full control over the dialogs layout and adjust it as required for your use-case.

**Comment by maulik-devitpl** [comment]
Thank you for your quick and detailed response. I will give it a try to prepare custom UI for all dialog.
