### ISSUE TITLE
can i show the browse dialog from a WixCLRDialog?

### ISSUE THREAD

**Issue by jtorjo** [oleg-shilo/wixsharp#876]
Hi,

I want to create a custom dialog that would show exactly like the InstallDirDlg dialog, but with an extra checkbox. I managed to do that, but I can't show a browse dialog when user clicks on the "Change Folder" button.

Trying to browse using the FolderBrowseDialog will simply not work, since that would show a window behind my window, and would end up blocking the setup kit.

Handling the button click and doing a `session.DoAction("BrowseDlg")` will throw an exception. 

Can I can show the browse dialog in any way?

**Comment by oleg-shilo** [comment]
Try to use "Custom UI" VS project template. It already has this dialog implemented you only need to put the checkbox there.

**Comment by jtorjo** [comment]
My apologies - didn't mean checkbox, but **button**.

I was using this (Custom UI) from the get go. So, what I want, is an extra button, which when clicked would open the browse dialog.

Handling this event and opening a `FolderBrowseDialog` doesn't work.

Handling this event and doing `session.DoAction("BrowseDlg")` doesn't work.

**Comment by oleg-shilo** [comment]
It's C#, you can just use "System.Windows.Forms.FolderBrowserDialog". Assuming you are indeed using "Managed Setup - Custom UI"  template as you said.

**Comment by jtorjo** [comment]
Please try it - in a button click handler, show a FolderBrowseDialog. 

It will show behind the setup kit, and freeze the setup kit.

**Comment by oleg-shilo** [comment]
> ...Please try it...

Sorry, try what?

Your problem description does not make it easy to follow. 

Did you try my suggestion? Seems like you did not. 
If you do try what I suggested (Managed Sutup with FolderBrowseDialog) you will be able to achieve the desired behavior:

_The `FolderBrowseDialog` from last dialog of the "WixSharp Managed Setup - Custom UI" template_

![image](https://user-images.githubusercontent.com/16729806/87246086-31e96180-c48e-11ea-9dc8-929f93d1bbe5.png)

Try to reproduce it. If you do have problems I will guide you, but you will need to try.

**Comment by jtorjo** [comment]
So, I've attached the project

[CustomCLRDialog.zip](https://github.com/oleg-shilo/wixsharp/files/4912639/CustomCLRDialog.zip)

You'll see that I've placed the .msi file that is generated.

**I'm on Windows 10, version 1909. I have Wixtools 3.11.2 installed.**

When I run it:

![image](https://user-images.githubusercontent.com/13891601/87308274-a8846e80-c523-11ea-9c01-2206d1f95603.png)

First of all - it hangs. Second of all, it shows something BEHIND the setup window. Third of all, the icon is not what it should be.

**Comment by oleg-shilo** [comment]
Yes, as I suspected we were talking about different things.

> I was using this (Custom UI)

Actually you did not. You were using MSI native UI with injected custom CLR dialog. But you need to use _Managed Setup_ with the full Custom UI template:

![image](https://user-images.githubusercontent.com/16729806/87427366-04ceb780-c624-11ea-8513-4ab1bbdf75c5.png)

"Custom CLR Dialog. " model was introduced before full ManagedUI became available. It is a template that is appropriate for a simple customization with limited flexibility. And it delivers somewhat limited result. 

In your case you use UI components that are COM based so they may easily fail if MSI, for example, does not initializes COM apartment threading correctly. Who knows if it does or doesn't! It is completely outside of your control.  

Managed UI from the other hand gives you full control. It was introduced specifically to overcome native UI problems and shield developers from the pain of MSI native UI and replace it with the normal WinForm based UI.

I encourage you to try my initial suggestion - "Managed Setup with FolderBrowseDialog".

The sample project is attached.
[WixSharp Setup14.zip](https://github.com/oleg-shilo/wixsharp/files/4919017/WixSharp.Setup14.zip)

**Comment by jtorjo** [comment]
Oh my - sorry about that. I was looking and modifying one of your examples. Anyway, will try that and let you know.

Best,
John

**Comment by oleg-shilo** [comment]
All good. The sample I have attached does the job.
