### ISSUE TITLE
can i have a custom dialog (WixCLRDialog) as the last step in the UI ?

### ISSUE THREAD

**Issue by jtorjo** [oleg-shilo/wixsharp#877]
No matter what I've tried, I can't get it to be the last dialog. I'd appreciate any input. Thanks!

**Comment by oleg-shilo** [comment]
I think you can but if you use "Custom UI" project template you will have full freedom on dialog and sequence customization.

**Comment by jtorjo** [comment]
That's what I've been using from the get go. I just can't get it to work. Hopefully, I'm doing something wrong?

How would you do that?

**Comment by oleg-shilo** [comment]
I am not sure we are talking about the same things.

WixCLRDialog you are referring is a dialog that is a part of the **native** UI. And "Custom UI" VS project template is for building **managed** UI. They are two mutually exclusive concepts:

![image](https://user-images.githubusercontent.com/16729806/87226903-4b30d600-c3da-11ea-8ad8-d8b17ef1d73b.png)
