### ISSUE TITLE
How to set "Revision Number" when displaying properties of an MSI file

### ISSUE THREAD

**Issue by fschlaef** [oleg-shilo/wixsharp#879]
Hello,

I am trying to have the version string displayed when looking at the "Details" tab, in the "Origin" section when looking at an MSI file properties. 
Currently is displays a random GUID that I can't find how to override.

![image](https://user-images.githubusercontent.com/29452252/87163886-4c71de00-c2c8-11ea-8862-05df8638d818.png)

As you can probably tell I can easily override the "Author" property with this :

```csharp
ControlPanelInfo = new ProductInfo()
{             
    Manufacturer = "My super company" // Displayed in Windows Control Panel
},
```

Any idea on how to set the other values ?

Thanks !

**Comment by oleg-shilo** [comment]
It looks like this is the limitation of MSI (not WixSharp, not even WiX). Look at this discussion: https://stackoverflow.com/questions/28960642/product-version-displayed-in-wix-made-msi-file-properties

You can implemented the suggested solution
 there with this single line:
```C#
project.Package.AttributesDefinition = "Comments=Version: 5.0.1.12345";
```

![image](https://user-images.githubusercontent.com/16729806/87246297-e46df400-c48f-11ea-9bc3-1397c41e4619.png)

**Comment by fschlaef** [comment]
Works for me ! Thank you :)
