### ISSUE TITLE
how to get msi output from bootstrapper project or how to install .net framework from wixsharp project/managed project

### ISSUE THREAD

**Issue by xeveloper** [oleg-shilo/wixsharp#880]
Hi, I need .net framework to run an app, when using wixsharp i make bootstrapper project below code works fine, but i need the output in `.msi` format, can we make msi for bootstrapper project? if yes how? i have search too much online not found anything use full, if not can we install .net framework using managedproject or just project in wix#?

           `var msiPackage = new MsiPackage($"{response.Item3}.msi") { DisplayInternalUI = false, Compressed = true };
            var projGroup = new PackageGroupRef("NetFx40ClientWeb");
            var fileName = Path.GetFileName(response.Item3);
            var bootstrapper = new Bundle(fileName, projGroup, msiPackage)
            {
                UpgradeCode = new Guid("GUID"),
                Version = response.Item4
            };

            bootstrapper.Application.AttributesDefinition = "ShowVersion=yes; ShowFilesInUse=yes";
            bootstrapper.Include(WixExtension.NetFx);

            bootstrapper.OutDir = Path.GetDirectoryName(response.Item3);
            bootstrapper.OutFileName = fileName;
            bootstrapper.PreserveTempFiles = false;
            bootstrapper.Application.LicensePath = null;

            var path = bootstrapper.Build();`

**Comment by oleg-shilo** [comment]
The very nature of a bootstrapper is a container application executable that holds MSI files. Thus the bootstrapper cannot be an msi.

Have a look at "Simplified Bootstrapper" sample it shows the technique of installing the a prerequisite from an msi but... I would really encourage you to use executable bootstrapper. Either NSIS or Burn. The samples are in the codebase.

 This is the most natural approach.
