### ISSUE TITLE
How do I install from an administrator?

### ISSUE THREAD

**Issue by Alex-fbr** [oleg-shilo/wixsharp#882]
How do I install from an administrator? I want all files copied to the destination folder Then depending on the user's choice I want to replace multiple files. However, I get a file access error when replacing.

**Comment by Alex-fbr** [comment]
![image](https://user-images.githubusercontent.com/20184455/87540403-515bd680-c6a8-11ea-96b6-bfc665393111.png)

**Comment by JoppeJoppinger** [comment]
Hi! 
Just got to my issue, Oleg helped me already and I think you have the same problem I had...
[https://github.com/oleg-shilo/wixsharp/issues/897](url)
