### ISSUE TITLE
How to write nested registrykeys during installation.

### ISSUE THREAD

**Issue by Kamalswami** [oleg-shilo/wixsharp#884]
I am converting my WiX project to the WiX# project. I am finding difficulty to convert Registry Components.

My Current Registry Component group in WiX project:

<ComponentGroup Id="RegistryEntries">
      <Component Id="Registry_InstallPath" Directory="INSTALLFOLDER" Guid="{4BCC6D58-ECDF-4F34-BE6B-3CEE53A3F63C}">
        <RegistryKey Root="HKLM" Key="Software\$(var.RegistryCompany)\$(var.RegistryProductCategory)\$(var.RegistryProductName)">
          <RegistryValue Type="string" Name="InstallPath" Value="[INSTALLFOLDER]" KeyPath="yes"/>
        </RegistryKey>
      </Component>
      <Component Id="Registry_Version" Directory="INSTALLFOLDER" Guid="{DB3FFF12-252D-4C7D-8591-110A505ECB4F}">
        <RegistryKey Root="HKLM" Key="Software\$(var.RegistryCompany)\$(var.RegistryProductCategory)\$(var.RegistryProductName)">
          <RegistryValue Type="string" Name="Version" Value="[ProductVersion]"/>
        </RegistryKey>
      </Component>
      <Component Id="Registry_CredentialProvider" Directory="INSTALLFOLDER" Guid="{AC6F5864-9EE3-4ADC-ABF6-407964410AD5}">
        <RegistryKey Root="HKLM" Key="SOFTWARE\Microsoft\Windows\CurrentVersion\$(var.ProductGuid)">
          <RegistryValue Type="string" Value="[Value1]"/>
        </RegistryKey>
      </Component>
      <Component Id="Registry_CLSID" Directory="INSTALLFOLDER" Guid="{412AD29E-0BFB-4DB9-A158-76027FE8C83B}">
        <RegistryKey Root="HKCR" Key="CLSID\$(var.ProductGuid)">
          <RegistryValue Type="string" Value="[Value1]"/>
          <RegistryKey Key="FirstKey">
            <RegistryValue Type="string" Value="[Value1]"/>
            <RegistryValue Type="string" Name="ThreadingModel" Value="[Value1]"/>
            <RegistryValue Type="string" Name="Class" Value="[Value1]"/>
             <RegistryKey Key="SecondKey">
            <RegistryValue Type="string" Value="[Value1]"/>
            <RegistryValue Type="string" Name="ThreadingModel" Value="[Value1]"/>
            <RegistryValue Type="string" Name="Class" Value="[Value1]"/>
            </RegistryKey>
          </RegistryKey>         
        </RegistryKey>
      </Component>
    </ComponentGroup>

My Project object in the WiX# project:

var project = new Project(title,
                                        new Dir(installPath,
                                        Files.FromBuildDir(@"projdirectory", ".html|.png|.config|.dll")),
                                        new RegKey(fullSetup, RegistryHive.LocalMachine, installPath,
                                                        new RegValue("InstallPath", "[INSTALLDIR]"),
                                                        new RegValue("Version", version)),
                                        new RegKey(fullSetup, RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\" + ProductGuid,
                                                        new RegValue("", ObjectName)),
                                        new RegKey(fullSetup, RegistryHive.ClassesRoot, @"CLSID\" + ProductGuid,
                                                                                                new RegValue("", ObjectName)),
                                        new RegKey(fullSetup, RegistryHive.ClassesRoot, @"CLSID\" + ProductGuid + @"\FirstKey",
                                                                                                new RegValue("", "Test"),
                                                                                                new RegValue("ThreadingModel", "Test"),
                                                                                                new RegValue("Class", "Test"),
                                        new RegKey(fullSetup, RegistryHive.ClassesRoot, @"CLSID\" + ProductGuid + @"\FirstKey\SecondKey",
                                                                                                new RegValue("", "Test"),
                                                                                                new RegValue("ThreadingModel", "Test"),
                                                                                                new RegValue("Class", "Test")));

I am building MSI and when I install the MSI it copy files but never make any registry entries. Can you please guide me?

**Comment by oleg-shilo** [comment]
Not sure what happens there but....
Is it possible that it installs in the Win32 roaming registry hive on your Win64 machine?

**Comment by oleg-shilo** [comment]
Remember, by default your msi is a Wib32 process

**Comment by Kamalswami** [comment]
Thank You @oleg-shilo. That was the issue.
