### ISSUE TITLE
hide checkbox on uninstall.

### ISSUE THREAD

**Issue by maulik-devitpl** [oleg-shilo/wixsharp#885]
I have prepared a Custom Managed dialog as exit dialog.

Now i am using that same dialog for  project.ManagedUI.InstallDialogs & project.ManagedUI.ModifyDialogs .

in exit dialog i have added a checkbox to launch application after install. And i want to hide this checkbox when user run msi again after install and choose "remove" from maintenance dialog.

I have tried below logic but this gives invalid handle error.

```C#
 `protected override void OnShellChanged()
        {
                         if (Runtime.Session.IsUninstalling())
                {
                    MessageBox.Show("IsUninstalling");
                }
                else if (Runtime.Session.IsRepairing())
                {
                    MessageBox.Show("IsRepairing");
                }
                else if (Runtime.Session.IsInstalling())
                {
                    MessageBox.Show("IsInstalling");
                }

          

            //this.Localize();
        }`

```

**Comment by oleg-shilo** [comment]
Most likely it is because the MSI session is terminated at that point

You will need to evaluate and the mode and cache it before the install and then use the cached value after the install:

```C#
static class State
{
    public bool IsInstalling;
    public bool IsUninstalling; 
    public bool IsReparing;
}

// in any of the preinstall dialogs cache the state
 
State.IsInstalling = Runtime.Session.IsInstalling();
State.IsUninstalling = Runtime.Session.IsUninstalling();
State.IsRepairing = Runtime.Session.IsUninstalling();

// now you can use `State.Is*ing` in any of the post install dialogs

```

**Comment by maulik-devitpl** [comment]
First of all, thank you for your quick response.
I have tried and it worked like a charm.
