### ISSUE TITLE
Build fails with code -532462766

### ISSUE THREAD

**Issue by JoppeJoppinger** [oleg-shilo/wixsharp#887]
Hello, 
each time I try to access args from main, i get the following error: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\YYY\source\repos\WixSharp Setup3\WixSharp Setup3\bin\Debug\WixSharp Setup.exe" "/MSBUILD:WixSharp Setup3" "/WIXBIN:"" exited with code -532462766.	WixSharp Setup3			

Its simple to reproduce, just open a new WixSharp Bootstrapper project and access args from main, then build it:

```
 static void Main(string[] args)
        {
           var packagePath = args[0] ?? "D:\\Program.exe";
           var bootstrapper = new Bundle("Program 4.0.0",
           new ExePackage(packagePath)
           {
               Name = "Program.exe",
               InstallCommand = "/S /W",
               Permanent = true,
               Vital = true,
               Compressed = true
           });

            bootstrapper.AboutUrl = "https://www.ProgramManufacturer.com/";
            bootstrapper.UpgradeCode = new Guid("D1828776-615E-4024-B4DB-FB7289607A81");
            bootstrapper.Version = new Version("1.0.0.0");
            bootstrapper.BuildCmd("Program 4.0.0");

            bootstrapper.Version = new Version("1.0.0.0");
            bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25844b");
            // bootstrapper.Application = new SilentBootstrapperApplication();
            // bootstrapper.PreserveTempFiles = true;

            bootstrapper.Build("MyProduct.exe");
        }

        
    }
}
```

Is this a bug or ist it my fault?
Thank you very much in advance for your help.
Sincerly, 
Manfred

**Comment by oleg-shilo** [comment]
The application is executed during the build (in post-build event) so it does not receive any `args` that's why it is failing the build.

Your args are expected to be always empty.

BTW you do have your check done a bit wrong anyway. 

```C#
// incorrect, will throw if no args passed
var packagePath = args[0] ?? "D:\\Program.exe";

// correct, will fall back to program.exe
var packagePath = args.FirstOrDefault() ?? "D:\\Program.exe";
```

**Comment by JoppeJoppinger** [comment]
OK, thank you very much. So if I understand you correctly, it's not meant to be built with args?
If this is so, you can close this issue and I will find another solution.

**Comment by oleg-shilo** [comment]
Yes you understood me correctly.
