### ISSUE TITLE
Installing newer versions of fonts already present on target system does not work

### ISSUE THREAD

**Issue by PawelTroka** [oleg-shilo/wixsharp#89]
See my StackOverflow question:
https://stackoverflow.com/questions/44619717/how-to-upgrade-systems-fonts-using-wix
See my commit:
https://github.com/PawelTroka/Computator.NET/commit/8fddf9fe3fe5f9ef65e6f851947a29f28cf35dcd

I think if user has font Cambria v5.00 and I define installation with Cambria v6.82 then font should be updated after installation is done. At least this is how it worked in InstallShield.

Is it a bug or a feature? If a feature then is there any workaround to accomplish what I want?

**Comment by oleg-shilo** [comment]
It is a WiX challenge and I don't have the answer for that. Sorry. Though if you hit the wall with WiX and cannot wind the direct answer in their documentation you can always build the msi with InstallShild and have a look at the result msi in Orca. This will give you a direct clue of what attributes there should be. 

Then implementing the solution with Wix# will be straight forward.

**Comment by PawelTroka** [comment]
Ok, I will take a look at what exactly InstallShield does later on
