### ISSUE TITLE
INSTALLDIR is empty or wrong in ManagedElevatedAction while uninstallation

### ISSUE THREAD

**Issue by abhinav2004** [oleg-shilo/wixsharp#891]
Hey

I am  facing the same issue as #486 . The Install CA gets the correct `INSTALLDIR` but the Uninstall CA does not get the modified `INSTALLDIR`. As mentioned in the issue changing `Dir()` to `InstallDir()` did not help either. Also I cannot use `BeforeInstall` event as its not elevated. 

So tried the example from #469 specifying `Id()` in the directory and setting it in the `Load` event. But weirdly, the paths created according to the MSI uninstall logs don't match:

```
MSI (s) (60:28) [12:13:43:976]: Target path resolution complete. Dumping Directory table...
MSI (s) (60:28) [12:13:43:976]: Note: target paths subject to change (via custom actions or browsing)
MSI (s) (60:28) [12:13:43:976]: Dir (target): Key: TARGETDIR	, Object: E:\
MSI (s) (60:28) [12:13:43:976]: Dir (target): Key: CommonAppDataFolder	, Object: C:\ProgramData\
MSI (s) (60:28) [12:13:43:976]: Dir (target): Key: PRGNAME	, Object: C:\ProgramData\App\
MSI (s) (60:28) [12:13:43:976]: Dir (target): Key: PRGNAME.updater	, Object: C:\ProgramData\MyApp\updater\
MSI (s) (60:28) [12:13:43:976]: Dir (target): Key: PRGNAME.service	, Object: C:\ProgramData\MyApp\service\
MSI (s) (60:28) [12:13:43:976]: Dir (target): Key: PRGNAME.libraries	, Object: C:\ProgramData\MyApp\libraries\
```

The `PRGNAME` is different from `PRGNAME.updater`

Following is the excerpt from the `program.cs`:

```csharp
var project = new ManagedProject("App",
    new Dir(@"%CommonAppDataFolder%",
        new Dir(new Id("PRGNAME"), "App",
            new Files($@"{winFolder}*"))),
    new ElevatedManagedAction(ServiceActions.Install, Return.check, When.After, Step.InstallFiles,
        Condition.NOT_Installed) {UsesProperties = MsiProperties.GetUsesProperties()},
    new ElevatedManagedAction(ServiceActions.Uninstall, Return.check, When.Before, Step.RemoveFiles,
        Condition.BeingUninstalled){UsesProperties = MsiProperties.GetUsesProperties()}
)
{
    InstallScope = InstallScope.perMachine
};
```

Following is the `Load` event:
```csharp
public static void Load(SetupEventArgs e)
{
    if(!e.IsInstalling)
        return;
    
    e.Session["PRGNAME"] =
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), "MyApp");
}
```
The `MyApp` will be fetched from some other source but for this issue I have just hard coded it. Are my `When` conditions and `Steps` wrong?

**Comment by abhinav2004** [comment]
After reading the side note mentioned here: https://github.com/oleg-shilo/wixsharp/issues/865#issuecomment-644054843 
I changed the `program.cs` to: 
```csharp
var project = new ManagedProject("App",
    new Dir(@"App",
        new Files($@"{winFolder}*")),
    new ElevatedManagedAction(ServiceActions.Install, Return.check, When.After, Step.InstallFiles,
        Condition.NOT_Installed) {UsesProperties = MsiProperties.GetUsesProperties()},
    new ElevatedManagedAction(ServiceActions.Uninstall, Return.check, When.Before, Step.RemoveFiles,
        Condition.BeingUninstalled){UsesProperties = MsiProperties.GetUsesProperties()}
)
{
    InstallScope = InstallScope.perMachine
};
```

But it didn't make any difference

**Comment by abhinav2004** [comment]
Ok so I don't know why this is happening but I got this working. To understand what I did let me explain my file structure:

```

**Comment by abhinav2004** [comment]
Ok so I don't know why this is happening but I got it working. To understand what I did let me explain my file structure:

```csharp
Dir("App",
  Dir("service"),
  Dir("updater"),
  Dir("libraries"),
)  
```
If we build the MSI with this structure and set `INSTALLDIR` in the `Load` event then in the `ElevatedManagedAction` during uninstall we do **not** get the modified `INSTALLDIR`.

But if the file structure is this:
```csharp
Dir("App",
  Dir("service"),
  Dir("updater"),
  Dir("libraries"),
  File("test.txt")
)  
```
then we get the modified `INSTALLDIR` in the `ElevatedManagedAction` during uninstallation. I don't know why this happens. I have poor understanding of WiX 😅 

I would like to know why this happens.

**Comment by Torchok19081986** [comment]
Hallo , i had same problem in my msi and in examples folder of Wix# , exists empty directories example. 
there is 2 line of codes, which was helpfull for my installer.
 AutoElements.LegacyDummyDirAlgorithm = true;
AutoElements.SupportEmptyDirectories = CompilerSupportState.Enabled;
Both create same output in wix file. 
After i added this code in msi, i got my msi workerd. Try it in Testsystem somewhere.

**Comment by oleg-shilo** [comment]
This section may provide an initial background content: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#installation-directory

The changes in your code fixed the problem because:
```C#
var project = new ManagedProject("App",
    new Dir(@"App",

// the code above is equivalent of

var project = new ManagedProject("App",
    new Dir(new Id("INSTALLDIR"), "App",
```

And `INSTALLDIR` is a well known ID of the dir that is modified in the IstallDirDialog. Thus if you decided to you a different id (e.g. `PRGNAME`) then you need to ensure that the InstallDirDialog knows which id to use. It is doible but it is much easier to just stick to the default id of the installation directory.
