### ISSUE TITLE
Question: MSI Install or Update for Product

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#893]
Hallo, is there way to always to install or update product, if for example i have installed Version like 2.2.1308 and i need to update 2.2.1477 ? Thought is use last two version of optional update and first two version for mainupdate ?
if i remember correctly msi doesn't check last two version for update. Is it possible to change that behavior somehow?
Many thanks.

**Comment by CADbloke** [comment]
In the version number `A.B.C.D`, `D` is not checked by the MSI installer for updates - only `A.B.C`
