### ISSUE TITLE
Correct way to get InstallDir from Bootstrapper and pass it to Exe-Package

### ISSUE THREAD

**Issue by JoppeJoppinger** [oleg-shilo/wixsharp#895]
Hello again, 
I have another question, I hope you can answer it...
I have a Bootstrapper with x Packages: 

```C#
 public void BuildPackage()
      {
         var bootstrapper = new Bundle("MyBundle", CreatePackageChain().ToArray());
         bootstrapper.AboutUrl = "https://www.manufacturer.com/";
         bootstrapper.UpgradeCode = new Guid("23F452E7-823D-4692-8D4C-095E491344E9");
         bootstrapper.Version = new Version("1.0.0.0");
         bootstrapper.SourceBaseDir = dataProvider.SetupTargetDirectory;
         bootstrapper.Build(Path.Combine(dataProvider.SetupTargetDirectory, "MyBundle"));
      
      }
      private IEnumerable<ChainItem> CreatePackageChain()
      {
         yield return packageGenerator.CreateExePackage();
         yield return packageGenerator.CreatePrerequisitesPackage();
        ...
         yield return packageGenerator.CreateMsiPackage();        
      }

 public ExePackage CreateExePackage()
      {
         return new ExePackage("AnyPath")
         {
            Name = "CoolProgram",
            InstallCommand = "/S /W",
            Permanent = true,
            Vital = true,
            Compressed = true      
          };
      }
```

All what I want is to get the selected user dir from Installer and hold it as variable. The problem is: We have an .exe Setup file from our collegues, and we like to add some assemblies and other stuff to the installer. So at first we run the given .exe, then we do some copy and file manipulations. After all we have a running "basic" software from the original .exe with our additions. 
This works perfectly if we use the default folder, but now we want to change to user selected installation paths.
I'm not sure where to start...can you help me?

**Comment by oleg-shilo** [comment]
My first impulsive answer on that is to use a custom BA and allow user to select INSTALLDIR from it. Then pass this forced INSTALLDIR to all setups in the package chain.

However I am sure Burn has a direct support for your scenario. I am just not aware of it. :(

**Comment by JoppeJoppinger** [comment]
Okay, you're right. 
But there is already an InstallDirDialog in the bootstrapper. Build in. It's callable with the "Options" Button at the start of the installation. 

I just write this because I think you see my problem to complicate: 
I just want to get the path the user chose in the InstallDirDialog. In a normal Msi Project, as seen in your templates, it's no problem, the path is given to the INSTALLDIR property. 
With a "Bundle" that doesn't work. The INSTALLDIR is never set - and at compilation it is set to the default folder - ProgramFolder

**Comment by oleg-shilo** [comment]
The solution is still to use InstallDirDialog (which I am not aware of) to obtain the path and push it to the bundle variable (e.g. `InstallDirDialogVariable`). Then pass this variable to the individual packages as a value of the property `INSTALLDIR`.

As in this pseudo-code:

```C#
var bootstrapper = new Bundle("My Product",
                       new MsiPackage("<masi path>")
                       {
                           DisplayInternalUI = false,
                           MsiProperties = "INSTALLDIR=[InstallDirDialogVariable]"
                       },
. . .
bootstrapper.Variables = new[] { new Variable("InstallDirDialogVariable", @"C:\temp") { Overridable = true } };
```
