### ISSUE TITLE
License file change at runtime based on local language 

### ISSUE THREAD

**Issue by gsvin99** [oleg-shilo/wixsharp#898]
Hi Oleg-shilo,
Thanks. Is it possible to show license file(rtf) based on local language at runtime. 
Kindly suggest, how to replace License source path at runtime.

I'm using Managed Custom UI project. Now i stored binary file to temp folder. but i'm not able to set this path at runtime.

**Comment by oleg-shilo** [comment]
If you are using Custom UI then you can simply set the content of the custom rtf as below:

```C#
oid LicenceDialog_Load(object sender, EventArgs e)
{
    banner.Image = Runtime.Session.GetResourceBitmap("WixUI_Bmp_Banner");

    // here !!!

    // have multiple licence files embedded in msi
    agreement.Rtf = Runtime.Session.GetResourceString("WixSharp_LicenceFile_<detected language>");
    
    // or have them embedded in the project resources 
    agreement.Rtf = (string)ResourceManager.GetObject("WixSharp_LicenceFile_<detected language>", resourceCulture);

    // or from the file in the temp dir
    agreement.Rtf = System.IO.File.ReadAllText("<rtf file location>");


    accepted.Checked = Runtime.Session["LastLicenceAcceptedChecked"] == "True";

    ResetLayout();
}
```

**Comment by gsvin99** [comment]
Thanks you very much. It working fine. 

One more question, Is possible to skip/avoid Exit Dialog, if installation is successful completion (without any error).
I tried, before initialization but exit dialog  not closed properly. Kindly suggest if any other possible to Shell.Exit() before call Exit dialog windows.

 void ExitDialog_Load(object sender, System.EventArgs e)
        {            
            if (!Shell.UserInterrupted && !Shell.Log.Contains("User cancelled installation.") && !Shell.ErrorDetected)
            {                
                Shell.Exit(); //Automatically close after installation successful completion               
            }
            else if (Shell.UserInterrupted || Shell.Log.Contains("User cancelled installation."))
            {
                title.Text = "[UserExitTitle]";
                description.Text = "[UserExitDescription1]";
                this.Localize();
            }
            else if (Shell.ErrorDetected)
            {
                title.Text = "[FatalErrorTitle]";
                description.Text = Shell.CustomErrorDescription ?? "[FatalErrorDescription1]";
                this.Localize();
            }
            image.Image = Runtime.Session.GetResourceBitmap("WixUI_Bmp_Dialog");
            ResetLayout();
        }

**Comment by oleg-shilo** [comment]
TBH I am not sure about your proposal. Having the ExitDialog displaying the success or error message is a standard, expected UI sequence that all users are used to. 

You can always achieve the proposed behavior with just 3 lines of code (your code snippet above).

I am afraid implementing your use case as default behavior will upset many users.

**Comment by gsvin99** [comment]
Thank you very much Oleg-shilo.

**Comment by oleg-shilo** [comment]
Thank you for iunderstanding
