### ISSUE TITLE
how to add file which must be present in msi-temp folder during pre-install in ManagedProject 

### ISSUE THREAD

**Issue by PepiBobanov** [oleg-shilo/wixsharp#901]
My UI uses some files that must be in temp folder before install.
i have tried with Binary( but it doesn't appear in MSI temp folder, and stuck  (2 days read samples)
It is some custom .dll that can not be integrated like RefAssembly , it is not .net assembly

**Comment by gsvin99** [comment]
I hope this may be help you.
Try UIInitialized or UILoad event in ManagedProject and save your binary file into temp folder and then refer temp folder path in your application.

var project = new ManagedProject("MyProduct",
                  . . .
                  new Binary(new Id("myRtf"), @".\files\manual.rtf")
                  . . .

// and then in the runtime handler/action
**session.SaveBinary("myRtf" , <temp file>);**

**Comment by PepiBobanov** [comment]
Don't work with my .dll i changed install strategy to not require this .dll

**Comment by oleg-shilo** [comment]
@gsvin99 answer seems to be the correct answer for this use-case.
