### ISSUE TITLE
feature selection via msiexec

### ISSUE THREAD

**Issue by twegener-mum** [oleg-shilo/wixsharp#904]
I want to install some features via msiexec, so I looked in the wxs file for the feature-id, e.g. "MyExtension"

I defined this feature in this way: new Feature("MyExtension")  {  IsEnabled = false }
so the feature is not selected by default

Then I use the msiexec in this way:  msiexec /i "my.msi" ADDLOCAL="MyExtension"
and silently:  msiexec /i "my.msi" ADDLOCAL="MyExtension" /qn

But in both cases the feature gets not installed (in the UI the feature is not seleced)
Have I to code something, so I get installed the feature silently?
Is there are an example how to do this?

Thanks
Thomas

**Comment by oleg-shilo** [comment]
If you are using native-UI then there is not much you can do for troubleshooting but only change-try-and-see.

Though if you are using managed UI then I suggest you ensure you create your project from the "Custom UI" VS template as it brings the source code of all dialogs to your project. So you can put a break point in your `Features Dialog` and see how the command line property value is propagated to the feature tree.

**Comment by yfolkenflik** [comment]
I am using managed UI and have a similar issue: I'd like to be able to specify features to be installed through command-line parameters when running install in silent mode. My question is: At what stage of silent install that does not involve any UI and how can I change ADDLOCAL property of the session?

**Comment by twegener-mum** [comment]
I haven’t digged in this issue, if you have an easy guidance to solve this issue, it would be nice …

Von: yfolkenflik <notifications@github.com>
Gesendet: Donnerstag, 24. September 2020 23:47
An: oleg-shilo/wixsharp <wixsharp@noreply.github.com>
Cc: Thomas Wegener <thomas.wegener@mum.de>; Author <author@noreply.github.com>
Betreff: Re: [oleg-shilo/wixsharp] feature selection via msiexec (#904)


I am using managed UI and have a similar issue: I'd like to be able to specify features to be installed through command-line parameters when running install in silent mode. My question is: At what stage of silent install that does not involve any UI and how can I change ADDLOCAL property of the session?

**Comment by oleg-shilo** [comment]
Since you are using managed UI digging into the issue is as simple as debugging C# code.
> So you can put a break point (or assertion) in your Features Dialog and see how the command line property value is propagated to the feature tree.

**Comment by oleg-shilo** [comment]
Since you are using managed UI digging into the issue is as simple as debugging C# code.
> So you can put a break point (or assertion) in your Features Dialog and see how the command line property value is propagated to the feature tree.
