### ISSUE TITLE
Error distributing WixSharp and WixToolset

### ISSUE THREAD

**Issue by shardick** [oleg-shilo/wixsharp#910]
Hi,
i'm creating and "installer creator" to build a Wix installer with options and predefined configuration file for the contained application.

When a final user uses the installer creator and try to build the installer, fires this error:

![image](https://user-images.githubusercontent.com/518905/92470249-78c9ae00-f1d6-11ea-9300-3199b320f969.png)

I've created an installer for the installer creator and deployed directory is the bin\Release one.

![image](https://user-images.githubusercontent.com/518905/92470407-a57dc580-f1d6-11ea-84a1-04d14b3639ed.png)

I'm missing something? Need to deploy WixToolset in some way with the application to final users?

Thanks

**Comment by oleg-shilo** [comment]
Yes you need to deploy WixToolset. It is where the actual compilers are. WixSharp uses WiX for building msi files\. And WiX or NSIS for building bootstrappers.

Thus you will need to deploy WiX on your target machine. You can go with choco or include [WixSharp.wix.bin](https://www.nuget.org/packages/WixSharp.wix.bin/) in your application setup.

**Comment by shardick** [comment]
Already included WixSharp.wix.bin in my application via Nuget

![image](https://user-images.githubusercontent.com/518905/92473861-79b10e80-f1db-11ea-9992-94706e0c7082.png)

**Comment by oleg-shilo** [comment]
Then you need to distribute the toolset with the installer creator. Thus your distro would look like this:
- installer creator
- WixSharp (content of WixSharp.bin package)
- WiX toolset (content of WixSharp.wix.bin package) 

At runtime you need to ensure WixSharp compiler can locate WiX compiler and linker. You can do it explicuitly from code in your creator (something like `Compiler.WixLocation = "<path>"` or by setting the envar:
![image](https://user-images.githubusercontent.com/16729806/92487201-4ea4da00-f230-11ea-8239-b0d3bdb1580d.png)

**Comment by shardick** [comment]
It's what i'm doing now,, use a copied WixToolset bin from Nuget package:

Pre-build event
`XCOPY /i /s /y $(SolutionDir)\packages\WixSharp.wix.bin.3.11.2\tools\bin $(TargetDir)\wixtoolset`

And

`WixSharp.Compiler.WixLocation = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), "wixtoolset");`

Then, add the wixtoolset folder inside the installer and distribute the whole package to end user. I think it should work.

**Comment by shardick** [comment]
yes! it worked!

Thank you!

**Comment by oleg-shilo** [comment]
Glad it helped :o)
