### ISSUE TITLE
DirPermission set for wrong dir

### ISSUE THREAD

**Issue by Alvek** [oleg-shilo/wixsharp#911]
Creating dir with target path sets DirPermission for root dir object of specified path.
Sample:
`return new Dir(new Id("MainDir"), feature,  @"%ProgramFiles%\CompanyName\ProductName", mainDirEntitys.ToArray()) 
            {
                IsInstallDir = true,
                Permissions = new DirPermission[] { new DirPermission("Everyone", GenericPermission.All) }
            };`

In this sample Permissions property assined to %ProgramFiles% folder dir object in project.AllDirs.
For now i avoid this with manual creation of dirs in target path.

**Comment by oleg-shilo** [comment]
Added to the todo. 

Sorry. Since there is a work around and I am completely stressed with other OSS projects I am putting it to the lower priority basket and asking for help (label "help wanted").

If now help available then it may take up to a month to address it.

**Comment by jwillsoncw1** [comment]
@oleg-shilo I have just been digging into this one a little and I'm not sure it is a bug.

In the developers guide under 'XDocument style constructors' It states directories are create in a nested fashion when using a path such as the one here, so the return value of `new Dir(new Id("MainDir"), feature, @"%ProgramFiles%\CompanyName\ProductName",...` in this case would be the directory named '%ProgramFiles%' to which the permissions are correctly being assigned.

**Comment by oleg-shilo** [comment]
np. Thank you for letting me know.
