### ISSUE TITLE
Missing application exe file after upgrade

### ISSUE THREAD

**Issue by ju2pom** [oleg-shilo/wixsharp#915]
Hi,

I'm facing a really strange issue. I built a new version of my product (v1.1.1) and when upgrading from v1.1.0 to v1.1.1 only one file is missing in the installation folder: the main executable. 
No code changes in the installer.

I tried to reproduce the issue on a virtual machine but it seems to works fine there.

Do you have any clue on what could be causing such a weird issue?

Thanks.

**Comment by geghamyan** [comment]
We've experienced this type of issue when during a major upgrade one of files had a lower fileversion than the original one. See the relevant discussion here: 
https://github.com/oleg-shilo/wixsharp/issues/636
