### ISSUE TITLE
Question: How to block Installation by OS Type

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#916]
Hallo ,  i need to block my installation on OS Type. 
if executed msi not on ,  not OS Type windows 10 or for example windows server 2016, i need to cancel it. 
I found out, there ist lauchconditions, but i can only add one value to Launchccondition.

![LAunchcondition](https://user-images.githubusercontent.com/25432729/93348740-e7da7e80-f836-11ea-9639-d8e3dd6a249b.JPG)

I would to add it like in picture. Is there way to do it so?

**Comment by oleg-shilo** [comment]
```C#
project.Load += msi_Load;
. . .

static void msi_Load(SetupEventArgs e)
{
    if (e.IsInstalling)
    {
        if (!IsItWindows10)
        {
            string message = "You can install this product only on Windows 10";
            e.Session.Log(message);

            if (e.UILevel > 4)
                MessageBox.Show(message, e.ProductName + " " + e.UILevel);

            e.Result = ActionResult.Failure;
        }
    }
}
```

**Comment by Torchok19081986** [comment]
Morning Oleg, thanks for code sample.  Code looks some different as expected. 
i add new LaunchCondition("VersionNT64 >= 602 ", "message"). Somehow works, but i have to add at sametime if ostype not server version OS . And here i struggle.

**Comment by oleg-shilo** [comment]
Then go with my suggestion :)

**Comment by Torchok19081986** [comment]
your suggestion is works. But i had to change windows10 bool to Environment class. I found p/invoke class. Don't know how to implent it ins project on load.  For https://www.pinvoke.net/default.aspx/shlwapi/IsOS.html give me always correct return value.

**Comment by oleg-shilo** [comment]
Just bring that `OSType` enum to your project. As with any C# code. And then call it form `project.OnLoad`

**Comment by Torchok19081986** [comment]
ok, going to try it at evening. Many Thanks, Oleg. 
Question is Closed.
