### ISSUE TITLE
Problem Starting -> Access Is Denied

### ISSUE THREAD

**Issue by tblong** [oleg-shilo/wixsharp#918]
I have a fairly basic build so far and occasionally I get the following when testing the install of the MSI built after the UAC prompt:
![image](https://user-images.githubusercontent.com/12371929/93484731-43a51600-f8d0-11ea-8f7f-7dc0d6dccb4d.png)

Here are the install logs that go along with the error above:
```
ActionStart: Action 10:23:08: WixSharp_InitRuntime_Action. 
Info: Action start 10:23:08: WixSharp_InitRuntime_Action.
Info: CustomAction WixSharp_InitRuntime_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Info: Action ended 10:23:16: WixSharp_InitRuntime_Action. Return value 3.
Info: Action ended 10:23:16: INSTALL. Return value 3.
....
```

Above I was both building and testing the install on my dev machine.  I then moved the MSI to a virtual machine I have for testing and the install went fine along with the successful install logs below on the VM:
```
ActionStart: Action 10:22:09: WixSharp_InitRuntime_Action. 
Info: Action start 10:22:09: WixSharp_InitRuntime_Action.
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI8B9D.tmp-\
Info: SFXCA: Binding to CLR version v2.0.50727
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_InitRuntime_Action
Info: Action ended 10:22:09: WixSharp_InitRuntime_Action. Return value 1.
ActionStart: Action 10:22:09: AppSearch. Searching for installed applications
Info: Action start 10:22:09: AppSearch.
....
```

Any pointers where I should be looking on my dev machine?  The reason I mention that this only happens intermittently is because if I delete the "obj" folder in my WiX# project directory and then rebuild, the installer works again on my dev machine.

**Comment by oleg-shilo** [comment]
Is it possible that some other projects during the build output in the same obj folder?

**Comment by tblong** [comment]
No only my Wix# project is using the the obj folder and I'm not using that directory for anything custom other than what the build process uses it for on its own.  Might have led you astray too, because it seems it was just a coincidence that one build after deleting the "obj" folder and making an non-code edit to the WiX# project caused the MSI to work again.
