### ISSUE TITLE
Question: How to remove extra files at uninstall?

### ISSUE THREAD

**Issue by tblong** [oleg-shilo/wixsharp#919]
I have a Windows service that will create log files in the install directory once running.  The log files get placed in a "Logs" subdirectory beneath INSTALLDIR.  There are a couple utilities also located in INSTALLDIR that a user may execute that creates additional files in INSTALLDIR that were not a part of the MSI.  These logs and additional files are orphaned and remain after the application is uninstalled along with the INSTALLDIR and parent manufacturer dir.  

**Question:**
What should I be configuring during the MSI build process to ensure that additional files and directories created post install are cleaned up when uninstalled?

**Comment by oleg-shilo** [comment]
You can do it with C# from the elevated `AfterInstall` event.

**Comment by tblong** [comment]
Great thanks for the guidance.  Good to close this one.  I did something along these lines:
```c#
/// <summary>
/// Handle the AfterInstall event during the uninstall process.
/// </summary>
/// <param name="e">The event data.</param>
public static void OnAfterInstall(SetupEventArgs e)
{
    if (e.IsUninstalling)
    {
        DirectoryInfo installDir = new DirectoryInfo(e.InstallDir);

        if (installDir.Exists)
            installDir.Delete(true);
    }
}
```

**Comment by oleg-shilo** [comment]
Great. 
You can also use the extension method `delete if exists` it deletes all nested items too:

```C#
public static void OnAfterInstall(SetupEventArgs e)
{
    if (e.IsUninstalling)
        e.InstallDir.DeleteIfExists();
}
```

**Comment by RachelXGanon** [comment]
@tblong Is this code working for you?
For me it's causing a rollback action and fail the uninstallation.
