### ISSUE TITLE
Error using RegValue with RegistryHive.CurrentUser

### ISSUE THREAD

**Issue by Dimazavrus** [oleg-shilo/wixsharp#92]
Hello.
I'm trying next sample, but get error:
`
Project proj = new Project( "MyProduct",
        new RegValue( RegistryHive.CurrentUser, @"Software\MyCompany\MyProduct", "aa", "bb" ) );
`

error LGHT0204: ICE57: Component 'Registry1' has both per-user and per-machine data with a per-machine KeyPath.

How to fix it?

**Comment by oleg-shilo** [comment]
I've posted the answer 2 days ago but somehow it's not here.
Anyway I'll recapture it again...

-----

Strictly speaking ICE validation failure is not an error but an alert about your setup not fully following the per-user vs. per-machine MS recommended guideline. 

I suggest that you have a look at the emitted WXS file and verify that the misbehaving XML code is in fact what you want. And if indeed it is the case then you can disable the ICE specific test(s) with light.exe command line switches. 
```C#
Compiler.LightOptions = "-sice:ICE57";
```
Note that Wix# already tries to resolve some absurd ICE constrains by auto-injecting ICE required elements, which are strictly speaking unnecessary for your deployment. Thus it is possible that auto-injection conflicts with your code. You can disable auto-injection via AutoElements.DisableAutoKeyPath.

----

However, I would encourage you to review your setup and remove any functionality that writes to user profile registry (e.g. `RegistryHive.CurrentUser`). I agree with MSI guideline on this one. For many good reasons setup should never write into user registry. The warning sign is that "RegistryHive.CurrentUser". Only an actual product application (your exe) should write into the user registry but not the product setup application.

**Comment by Dimazavrus** [comment]
OK Thanks!
