### ISSUE TITLE
How to change User for Win Services after installation

### ISSUE THREAD

**Issue by Saravanan109587** [oleg-shilo/wixsharp#920]
Hi Oleg, I need some help. In my case I have user credential for windows service  log on account in one excel file. While installing I will be reading the details from that file  then user account creation and assign the user as service log on user will take place at run time .

**User creation :**
```C#
 project.Add(new User
            {
                Name = $"[{ username }]",
                Password = $"[{ password }]",
                Domain = "[ComputerName]",
                PasswordNeverExpires = true,
                UpdateIfExists = true,
                CreateUser = true,
                RemoveOnUninstall = true,
                LogonAsService = true
                
            });
```
  **ServiceInstaller with user account**
```C#
            return new ServiceInstaller
            {
                Name = componentConfiguration.Service.ServiceName,
                Description = componentConfiguration.Service.ServiceDescription,
                Start = componentConfiguration.Service.AutoStart ? SvcStartType.auto : SvcStartType.demand,
                DelayedAutoStart = componentConfiguration.Service.AutoStart,
                StartOn = componentConfiguration.Service.AutoStart ? SvcEvent.Install : null,
                StopOn = SvcEvent.InstallUninstall_Wait,
                RemoveOn = SvcEvent.Uninstall_Wait,
                FirstFailureActionType = FailureActionType.restart,
                SecondFailureActionType = FailureActionType.restart,
                ThirdFailureActionType = FailureActionType.restart,
                RestartServiceDelayInSeconds = 30,
                ResetPeriodInDays = 1,
                DependsOn = GetServiceDependencies(componentConfiguration.Service),
                Feature = feature,
                Account =  $".\\[{ username }]" ,
                Password =   $"[{ password }]"  ,
            };
 ```
Using the above code everything works fine in installation scenario.

If I want to change user account for existing  windows service which is installed as part of installation(**this will basically  happen when password expired and user wants to set new credentials** ) , then I will be be updating the excel sheet with new user details, Now is there any way to update windows service account using msi itself? .kind of modification of existing features.
Any way to do that with wixsharp.
can you please help me with this question ?

**Comment by oleg-shilo** [comment]
May be you can use Custom Action for that?

**Comment by Saravanan109587** [comment]
Yes, i am using custom action with 
  **System.DirectoryServices;
  System.DirectoryServices.AccountManagement;** to update user credential as part of installation. and it is working fine. Still i  was curious to know  ,Is there any  way to do these things with Wix sharp itself .
