### ISSUE TITLE
Generate in temp folders rather than execution folder

### ISSUE THREAD

**Issue by DuAell** [oleg-shilo/wixsharp#921]
It would allow concurrent execution of wixsharp, and may avoid problems with user rights on folders.

**Comment by oleg-shilo** [comment]
please elaborate

**Comment by DuAell** [comment]
When WixSharp is launched twice at the same time, it will cause issues as we are generating temporary files in the execution folder.
Using a temp folder would allow to launch concurrently several WixSharp builds.

About user rights, you don't really know where WixSharp is launched, and it might be a protected folder, like program files. Using dedicated temp folders (Path.GetTempPath) would solve this potential issue aswell.

**Comment by oleg-shilo** [comment]
> When WixSharp is launched twice at the same time, 

I do not see any good reason for that unless it is something specific to your use case.

Problem with a temp dir is that you will need to remap all references (your distributable input files) to the path that is relative to that tamp folder.  High risk with no obvious gain.

You can actually do it if you want to. You can assign assign the output folder as anything:
```C#
project.OutDir = Path.GetTempPath();
```
In this case the project application is still executed in the normal VS project folder Debug/Release but the output (e.g. msi file) will be assembled in your temp folder.

You can do even more. You can build your .NET project, which is nothing else but an msi builder. Copy it anywhere you want and then execute it manually.

Currently it is executed in a post-build event.

**Comment by oleg-shilo** [comment]
As for the " with user rights on folders.", I do not see how this can be a problem.
If you use VS and folder permissions is not a problem so why if you are using VS to build MSI with it is. In both cases it is the same file structure (e.g. `bin\Debug`).

**Comment by DuAell** [comment]
Actually problems that I have happens on a Jenkins server. 
I have several software that I build in parallel for which I need an installer. Building them in parallel causes the problem I mentionned.

Side note : I don't see any benefit of the post build event. It is more something annoying for me, as I can't build my wixsharp project without creating the wix file.
Anyway, I build the project, get some errors because everything is not ready yet, and run it after, when I'm ready to create the wix file (i.e. when all my binaries are ready to be packaged).

**Comment by oleg-shilo** [comment]
>... It is more something annoying for me, as I can't build my wixsharp project

Not exactly. You can. Just install `WixSharp.bin` instead of `WixSharp` and this will let you build an ordinary executable (an msi-builder). That is exactly what you call "build my wixsharp project"
See: https://github.com/oleg-shilo/wixsharp/wiki/Developer's-Guide#nuget-packages

After that you can copy your executable anywhere (e.g. temp folder) and then run it at your convenience. Just make sure your msi-builder can find your MSI sources.

**Comment by DuAell** [comment]
Nice, didn't saw that. Thanks.

Do building the msi-builder generate temp files in execution folders ? => Can it be ran in parallel in the same execution folder ?

**Comment by oleg-shilo** [comment]
I think you are giving too much credit to the  msi-builder 😄 
It is nothing else but an ordinary console app of a standard VS project. It is built exactly as a canonical "Hello World!". It does not generate any unusual temp files but normal `.\obj\*`.

Can it be run in parallel? 
Well, parallel with what? If it is parallel with building the executable? No, as with any VS project.
Can you elaborate?

**Comment by DuAell** [comment]
In parallel with another wix build from same project.
I know it seems weird but I'm on a CI build server, so it happens that I'm building a wix installer for my project on branch A and at the same time building a wix installer for the same project on branch B.

With Wixsharp.bin, creating the msi-builder is easy, but running the msi-builder is still a problem because it creates files in execution folder.

Anyway, I managed to get it working by changing the working directory to a temp one before running it.
This way I can run several wix builds at the same time

**Comment by oleg-shilo** [comment]
That's great.
Still curious...
Your CI build server builds branches sequentially. 

1. Start building branch A
2. wait till it's done
3. start building branch B. 

Thus you already have nice sequence resolution.  and if you introduce a blocking action between step 2 and 3 (e.g. building msi) then you are still fine.

"building msi" means executing msi-builder. I never really checked but I assumed that VS code runs executables in the post build event synchronously. Thus until msi-builder execution is done your step 3 will never start. So... it should be no collision.

Anyway, I'll leave it up to you if you want to get done without temp folder.

**Comment by DuAell** [comment]
Well, it's not sequential, it's parallel, that's why I have the problem.
Anyway, I managed to get it working by changing the working directory before executing.
Thanks for your help, I'll close the ticket as I have a working solution.

**Comment by oleg-shilo** [comment]
> Well, it's not sequential, it's parallel, that's why I have the problem.

OK then. It explains. Even though unexpected (for me).
