### ISSUE TITLE
per user/machine install

### ISSUE THREAD

**Issue by Liancee** [oleg-shilo/wixsharp#922]
Hi Oleg,
I have the problem that I had my first setups installing the product per user. The thing is I changed it now so u can install it per machine, but when I already have it installed per user it installs it twice per user and per machine. I know that when u wanna install the per machine setup it looks in the registry if there is already a per machine installation and if not it just installs it without looking for a per user installed product. Can u somehow change that so it looks for both? I got the same Upgrade Code but different GUID for every setup if thats somehow relevant.

**Comment by oleg-shilo** [comment]
Not really. OK, well... not that I know how. 
It is all done by MSI runtime not by WixSharp, which is not involved in the decision making what or how to install the product.  
So the only chance to achieve it (if even possible) is do it via MSI/WiX.

**Comment by NickeManarin** [comment]
`GUID` and an alias for `UpgradeCode`. If no `UpgradeCode` is set, the `GUID` will be used.

Don't you mean, `ProductId`?

----------------

Anyway, I'm facing the same issue.

If the previous install was decided to use a different install mode, two entries of the app will appear on the list.

In my case, I'm doing something different, the user does not decide if it's `PerUser` or `PerMachine`. It's selected based on the location of the install.

    //The value ALLUSERS = 2 enables the system to reset the value of ALLUSERS, and the installation context, 
    //dependent upon the user's privileges and the version of Windows.
    MsiRuntime.Session["ALLUSERS"] = "2";
    MsiRuntime.Session["MSIINSTALLPERUSER"] = _hasRights ? "1" : "";

The `_hasRights` is a boolean which is true whenever the user has rights to save to a given folder.

I wonder if there's any way to trigger a uninstall via a given GUID/ProductId code.

**Comment by oleg-shilo** [comment]
The `project.GUID` is a seeding value to be used to deterministically generate MSI identities if user does not define them. 

Thus if you do not specify `project.ProductId` WixSharp will generate it for you based on the combination the `project.GUID`  and `project.Version`.

And if do not specify `project.UpgradeCode` then WixSharp will generate it as well. By assigning it from the `project.GUID` value.

This is a fall back technique to make it possible to generate upgradable MSIs when used did not define IDs explicitly.

But if you have any doubts or your use-case is not trivial I recommend setting `project.ProductId` and `project.UpgradeCode` explicitly:

```C#
project.ProductId = new Guid("<whatever>");
project.UpgradeCode = new Guid("<another whatever>")
```
This way you are in full control of all your guids.
