### ISSUE TITLE
Show Info for Update exe package

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#923]
Hallo, i have a question and simply don't know if my reqeust belongs to msi or bootstarapplication. 
I have a complex BA where a all my Installfiles in BA going to be installed. Works really good. In my complet installer exists client installation via MSI . I would like to change it to BA with following behavior. 
if client installed, i would like to show if it update or repair on startscreen. I seen some installer from exe if product exists, it happend some kind of reload and on welcomescreen shows package would be updated or uninstalled. 
Is there some way to achieve that with BA or NSIS Bootstrapper ? I don't have any idea where to start. In Basics i need to detect my product installed or not and somehow start exe with info.

**Comment by Torchok19081986** [comment]
Hallo Oleg, after some search, i got some info for my problem. There is detection of product in BA, but it happens during execution of install / update. Is there Possibility to change that behavior , at exe start installation or update  ?

**Comment by oleg-shilo** [comment]
Yeah there is. 
Have a look at `WixBootstrapper_UI` sample. YIt show how to create virtually any UI for your bootstrapper.

**Comment by Torchok19081986** [comment]
Morning Oleg. Thanks for explanation.  I struggle at moment how can i show different start pages after detection complete. 
I add new Model and new window. Just 2 radiobuttons (Update, Uninstall) and one button with action. How do set this window AFTER detection complete and show new creteated window? 
```csharp

void OnDetectPackageComplete(object sender, DetectPackageCompleteEventArgs e)
    {
        if (e.PackageId == "MyProductPackageId")
        {
            if (e.State == PackageState.Absent)
            {
                InstallEnabled = true;
            }
            else if (e.State == PackageState.Present)
            {
                 //Here is package installed. Set new window. 
                UninstallEnabled = true;
            }
        }
    }

```

**Comment by oleg-shilo** [comment]
you can signal to your main window that it needs to change ()e.g. another startup page)  as the result of the detection.

**Comment by Torchok19081986** [comment]
Morning Oleg. Thanks for info .  am i right if i set ondetectioncomplete BA to restart ? Normal Application.Restart  ?

**Comment by oleg-shilo** [comment]
I am not sure what you mean.
I was making a comment about a custom BA that shows the pages and changes the them as the result of user interactions and Burn runtime event detection (`OnDetectPackageComplete`).

This would satisfy your requirement to keep everything as usual ("Works really good") but to have a context specific start page.
