### ISSUE TITLE
Upgrade using Bootstrapper

### ISSUE THREAD

**Issue by sinangok** [oleg-shilo/wixsharp#924]
Hi Oleg,
I am using an installer project which is a bootstrapper with custom user interface. To create new release, version number is increased. After installing the new release, upgrading works fine (all files and applications under the Program Data and Program Files  updated properly )however, Programs and Features windows shows old and new release and I couldn't find how to remove old release from Program and Features. 
I can create same issue using WixBootstrapper_UI sample. I only added MajorUpgrade feature and set project version which is same as bundle's version.
I couldn't find why previous release stay on the Programs and Features, am I doing something wrong?
Thanks

![Programs and Features](https://user-images.githubusercontent.com/6000462/94459568-72b06700-01af-11eb-9cd7-4777d58e4423.png)

[setup.pdf](https://github.com/oleg-shilo/wixsharp/files/5293729/setup.pdf)

`using System;
using System.Windows;
using WixSharp;
using WixSharp.Bootstrapper;
using io = System.IO;

public class Script
{
    //The UI implementation is based on the work of BRYANPJOHNSTON
    //http://bryanpjohnston.com/2012/09/28/custom-wix-managed-bootstrapper-application/

    static public void Main()
    {
        string version = "1.0.2.0";
        
        var productProj =
            new ManagedProject("My Product",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File("readme.txt")),
                    new RegValue(RegistryHive.LocalMachine, @"Software\My Company\My Product","Message","Hello"),
                    new RemoveRegistryKey(RegistryHive.LocalMachine, @"Software\My Company\My Product"));

        productProj.InstallScope = InstallScope.perMachine;
        productProj.GUID = new Guid("6f330b47-2577-43ad-9095-1861bb258777");
        productProj.Version = new Version(version);
        
        productProj.Load += (SetupEventArgs e) =>
        {
            //MessageBox.Show(e.Session.Property("USERINPUT"));
        };

        productProj.MajorUpgrade = new MajorUpgrade
            {
                Schedule = UpgradeSchedule.afterInstallValidate,
                AllowDowngrades = false,
                DowngradeErrorMessage = @"A later version of the software is already installed."
            };

        string productMsi = productProj.BuildMsi();

        //------------------------------------

        var bootstrapper =
            new Bundle("My Product",
                       new PackageGroupRef("NetFx40Web"),
                       new MsiPackage(productMsi)
                       {
                           Id = "MyProductPackageId",
                           DisplayInternalUI = true,
                           MsiProperties = "USERINPUT=[UserInput]"
                       });

        bootstrapper.Variables = new[] { new Variable("UserInput", "<none>"), };
        bootstrapper.Version = new Version(version);
        bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25889a");
        
        // You can also use System.Reflection.Assembly.GetExecutingAssembly().Location instead of "%this%"
        // Note, passing BootstrapperCore.config is optional and if not provided the default BootstrapperCore.config
        // will be used. The content of the default BootstrapperCore.config can be accessed via
        // ManagedBootstrapperApplication.DefaultBootstrapperCoreConfigContent.
        //
        // Note that the DefaultBootstrapperCoreConfigContent may not be suitable for all build and runtime scenarios.
        // In such cases you may need to use custom BootstrapperCore.config as demonstrated below.
        bootstrapper.Application = new ManagedBootstrapperApplication("%this%", "BootstrapperCore.config");

        bootstrapper.PreserveTempFiles = true;
        bootstrapper.SuppressWixMbaPrereqVars = true;
       
        bootstrapper.Build("my_app.exe");
        io.File.Delete(productMsi);
    }
}`

**Comment by oleg-shilo** [comment]
Sorry, I do not know the answer. It might be triggered by the fact that your different versions of MSI do not have the same UpradeCode. It is something that you can check with Orca by inspecting your MSIs

**Comment by sinangok** [comment]
Thank you for help.
I have compared two version using Orca and both versions have same upgrade code.

**Comment by oleg-shilo** [comment]
Then I truly run out of ideas. 

If two MSIs have the same UpgradeCode but MSI runtime cannot detect that the installed MSI is just a previous version of the one being instaled then it is either you have discovered a fundamental MSI bug or there is something peculiar about your experiment.

**Comment by sinangok** [comment]
The new release removes the old one and it works perfectly. The only issue is previous version name stay in the Programs and Features. 
I have attached a pdf file which is one of Wixsharp sample (WixBootstrapper_UI ). I added MajorUpgrade feature and set project version to that sample and it produces same result.

**Comment by yurislav** [comment]
As oleg was saying, this is usually caused by not keeping same upgrade code between versions. So if this is not the case, my other guesses are:

- failure that occurs during uninstaller, some old data were just not cleaned up and the app is still visible in add/remove programs.
- maybe you have used different language codes between old and new version.
- one version of your app was set to install "per user" and other "per machine".

**Comment by sinangok** [comment]
Thank you for your comment. 
Change between two version is only version number.
I have also create similar issue using WixBootstrapper_UI  sample in the WixSharp samples. Please have a look the "setup.pdf" (attached to first post). On this example I only changed version number.

**Comment by Torchok19081986** [comment]
Hallo, i have same problem with my first exe installer. Have same behaviour like sinangok in BA. Whatever, in WPF Installer with embeded MSI package in examples/ External_UI/WpfSetup , update or upgrade runs and it works. 
@sinangok , have you found some info or you could do update in your BA?

**Comment by sinangok** [comment]
@Torchok19081986 , No I haven't found anything yet.

**Comment by Torchok19081986** [comment]
many thanks for info, @sinangok . I think, that only Oleg or Xadan can verify if something wrong in BA with Update.

**Comment by sinangok** [comment]
@Torchok19081986 ,
You should use same guid for upgrade code between two release.

**Comment by Torchok19081986** [comment]
hm.... in prroject msi i set to new guid some value, and in bundle / bootstrapper application i set upgradecode to project.upgradecode.

**Comment by sinangok** [comment]
@Torchok19081986 ,
Could you please show your changes on these sample please [https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Bootstrapper/WixBootstrapper_UI](url)
Thanks.
__setup.cs__
`using System;
using System.Windows;
using WixSharp;
using WixSharp.Bootstrapper;
using io = System.IO;

public class Script
{
    //The UI implementation is based on the work of BRYANPJOHNSTON
    //http://bryanpjohnston.com/2012/09/28/custom-wix-managed-bootstrapper-application/

    static public void Main()
    {
        var productProj =
            new ManagedProject("My Product",
                new Dir(@"%ProgramFiles%\My Company\My Product",
                    new File("readme.txt")));

        productProj.InstallScope = InstallScope.perMachine;
        productProj.GUID = new Guid("6f330b47-2577-43ad-9095-1861bb258777");

        productProj.Load += (SetupEventArgs e) =>
        {
            MessageBox.Show(e.Session.Property("USERINPUT"));
        };

        string productMsi = productProj.BuildMsi();

        //------------------------------------

        var bootstrapper =
            new Bundle("My Product",
                       new PackageGroupRef("NetFx40Web"),
                       new MsiPackage(productMsi)
                       {
                           Id = "MyProductPackageId",
                           DisplayInternalUI = true,
                           MsiProperties = "USERINPUT=[UserInput]"
                       });

        bootstrapper.Variables = new[] { new Variable("UserInput", "<none>"), };
        bootstrapper.Version = new Version("1.0.0.0");
        bootstrapper.UpgradeCode = new Guid("6f330b47-2577-43ad-9095-1861bb25889a");

        // You can also use System.Reflection.Assembly.GetExecutingAssembly().Location instead of "%this%"
        // Note, passing BootstrapperCore.config is optional and if not provided the default BootstrapperCore.config
        // will be used. The content of the default BootstrapperCore.config can be accessed via
        // ManagedBootstrapperApplication.DefaultBootstrapperCoreConfigContent.
        //
        // Note that the DefaultBootstrapperCoreConfigContent may not be suitable for all build and runtime scenarios.
        // In such cases you may need to use custom BootstrapperCore.config as demonstrated below.
        bootstrapper.Application = new ManagedBootstrapperApplication("%this%", "BootstrapperCore.config");

        bootstrapper.PreserveTempFiles = true;
        bootstrapper.SuppressWixMbaPrereqVars = true;

        bootstrapper.Build("my_app.exe");
        io.File.Delete(productMsi);
    }
}
`

**Comment by Torchok19081986** [comment]
morning, @sinangok .  
```csharp

  project.GUID = new Guid("7468C0AA-43F2-47A9-8E37-B24B462D8D37");

            project.UpgradeCode = project.GUID;

            project.UI = WUI.WixUI_InstallDir;

            project.ValidateBackgroundImage = false;

            project.Properties = new[] { new Property("InstallFolder", "[InstallFolder]") };

            project.ValidateBackgroundImage = false;

            project.Version = new Version("1.1.0.0"); 

            project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
            project.MajorUpgradeStrategy.PreventDowngradingVersions.OnlyDetect = false;
            project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;

            //project.Platform = Platform.x64;
            project.InstallerVersion = 450;
            project.InstallScope = InstallScope.perMachine;

  var bootstrapper =
                new Bundle
                ("DatevConnect2cobra",
                    new PackageGroupRef("NetFx40Web"),
                    new MsiPackage
                    (productMsi)
                    {
                        Id = "PackageId", 
                        DisplayInternalUI = true
                    }
                )
                {
                    Version = new Version("1.1.0.0"),          
                    UpgradeCode = new Guid("7468C0AA-43F2-47A9-8E37-B24B462D8D37"),  //same like msi
                    Id = "7468C0AA-43F2-47A9-8E37-B24B462D8D3",
                    Application = new ManagedBootstrapperApplication("%this%", "BootstrapperCore.config"),
                    PreserveTempFiles = true,
                    
                    SuppressWixMbaPrereqVars = true
                };

            bootstrapper.Variables = "InstallFolder".ToStringVariables();

            WixEntity.DoNotResetIdGenerator = true;

            bootstrapper.Build(Application.StartupPath + "\\Installer " + bootstrapper.Version + ".exe");

```
after some tests on developer machine and hyper-v vm, it looks like bundle itself cant be updated, msi will be updated. somehow if you try to run newer version in 3 of 5 tests works and after that not anymore. Bundle does not have update strategy.

**Comment by sinangok** [comment]
Thank you, @Torchok19081986 for the reply. It took me a while to test your answer this morning, it works for me as well.

**Comment by Torchok19081986** [comment]
👍

**Comment by mjanulaitis** [comment]
I see this all the time.  It is not 100% reproduceable.  In fact I see it less often than actually working.  The upgrade codes are always the same as well as the bundle IDs.  There is some sort of bug in the bootstrapper.  I suspect the bug has something to do with the system reboot flag and/or using -q -norestart flags.  This definitely should not be closed because it is a real issue unrelated to guids.
