### ISSUE TITLE
Recognizing of existing install

### ISSUE THREAD

**Issue by yfolkenflik** [oleg-shilo/wixsharp#925]
I previously used a setup project with custom UI and native dialogs that installed all five features that our product consists of without giving a user an option to select what features to install. However, it allowed to use a new version of the setup to uninstall a previous version of the product and install a new one.
Now I switched to managed UI that has feature selection dialog. My problem is that a setup with a newer version of the product does not see an existing installation of the same product. When I right-click on the msi file and select Repair or Uninstall it tells me that this action is valid only for currently installed projects. When I run a setup it shows install dialogs but not modify dialogs. Modify dialogs will be shown only if I use exactly the same package that was used for original install. However, if I put the following code in the Load event it recognizes that the product is installed and gets a list of installed features:
```C#
var upgradeCode = e.Session["UpgradeCode"];
var installedPackage = ProductInstallation.GetRelatedProducts(upgradeCode).FirstOrDefault();
var isInstalled = installedPackage?.IsInstalled;
var installedFeatures = installedPackage?.Features?
                                         .Where(x => x.State == InstallState.Local)
                                         .Select(x => x.FeatureName)
                                         .JoinBy(",");
```
Any help will be greatly appreciated.

**Comment by oleg-shilo** [comment]
Detection of the previously installed product is completely handled by the MSI. Though your problem cannot be caused by the switch to managed UI. UI has nothing to do with that.

Most likely when you migrated your new setup got a new identity (combination of the product IDs). Check this section:
https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming

I suggest you check it by opening the both MSI files in Orca and checking their IDs. There is a good chance that some of the ids  will missmatch.

**Comment by yfolkenflik** [comment]
Following your advice I opened three msi files in Orca and below are
screenshots for each of them. The first one is for version 4.0 of the
product that used custom UI and others are from two different builds of
version 5.0 that  used managed UI. As you can see all of them have the same
UpgradeCode and different ProductCode. However, none of the newer versions
recognizes the presence of the previously installed version. Here is the
code that I used in both, custom UI and managed UI projects for setting IDs:

project.GUID = new Guid("{AC19C6E4-9724-4e90-8AC7-6E69B4AB7562}");
project.UpgradeCode = project.GUID;
project.ProductId = Guid.NewGuid();
project.MajorUpgrade = MajorUpgrade.Default;
project.MajorUpgrade.AllowSameVersionUpgrades = true;

What else could cause my issue?

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by oleg-shilo** [comment]
The images are not there but....your description is sufficient. 
Yes your expectations are correct. The upgrade code supposed to be the same and the product code is different.
Meaning your MSIs are perfectly valid for the upgrade scenario. 

I cannot provide any explanations :(

**Comment by NickeManarin** [comment]
@yfolkenflik Are you changing the value of any of these props?

`MsiRuntime.Session["ALLUSERS"]`
`MsiRuntime.Session["MSIINSTALLPERUSER"]`

**Comment by yfolkenflik** [comment]
@NickeManarin No, I am not changing any of these properties.

**Comment by Torchok19081986** [comment]
Hallo, i had same issue with my uninstaller. somehow it was installed twice, first as user and second in HKLM. Couldnt do nothing and it was always install new version of msi without recognizing old installed versions.

I solved it with following code:
```csharp
 project.InstallScope = InstallScope.perMachine;
project.GUID = new Guid("D01C6691-9CEB-499E-9FBC-78C0570AA4D2");
project.Version = versionToInstalled; 
project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
project.MajorUpgradeStrategy.PreventDowngradingVersions.OnlyDetect = false;
project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;
```
