### ISSUE TITLE
error for locales in FirewallException

### ISSUE THREAD

**Issue by gchahaluipath** [oleg-shilo/wixsharp#926]
Hi,

I am trying to add  support for multi language in our installer/msi. We already have support for ja-jp and en-US. However, I need to add de-De and fr-FR as well.
When I try to add these cultures I get exceptions like these:
```
The localization variable !(loc.msierrFirewallCannotConnect) is unknown.  Please ensure the variable is defined.
The localization variable !(loc.WixSchedFirewallExceptionsInstall) is unknown.  Please ensure the variable is defined.
```	
This is probably due to the lack of support for these locales as can be seen [here](https://github.com/wixtoolset/wix3/tree/develop/src/ext/FirewallExtension/wixlib). I don't see any `.wxl` files mentioned for `de-DE` and `fr-FR`.  
Can we please have support (wxl files created) for these cultures. Or please suggest if there is any other way using which we can accomplish this and get rid of these errors.

Thanks,
Gurpreet

**Comment by gchahaluipath** [comment]
Hi @oleg-shilo 

Any updates on this please.

**Comment by oleg-shilo** [comment]
I don't have a bandwidth to look at this closely and as it does not seem to be a trivial problem.  But you definitely can use a few work around approaches:

```C#
project.LocalizationFile = "WixUI_de-de.wxl"; // a file that has all resources present
project.Language = "de-de"; 
```

Or

```C#
project.LightOptions += $" -loc \"{extra_localization_file_with_missing_entries}\"";
```
Though I assume light allows multiple wxl files

**Comment by gchahaluipath** [comment]
Hi Oleg,

Ours is a multilanguage msi and we are creating msi using 
`project.BuildMultilanguageMsi(DefaultLocalization, ProjectLocalizations);`
default loc is `en-us` and rest of the locales are in other parameter. Please note that we are creating wxl files for other locales. So this means we'll have one created for `de-DE` and `fr-FR` as well. But since we are getting these exceptions its not going through. Are you suggesting to add these keys mentioned [here](https://github.com/wixtoolset/wix3/tree/develop/src/ext/FirewallExtension/wixlib) in the respective .wxl files manually. Would it help? Can you please just let me know the steps I need to try out.

**Comment by oleg-shilo** [comment]
It is a non-trivial scenario that is a bit difficult to handle in a generic way.
Thus I suggest you try to do it manually (steps below) and when you find the solution we may try to find an appropriate API for it.

Define your own experimental `BuildMultilanguageMsiExp` and `BuildLanguageTransformExp`:

```C#
static public string BuildMultilanguageMsiExp(this WixSharp.Project project, string path = null)
{
    project.VerifyLanguage();
    project.SuppressSettingPackageLanguages = true;

    // !!!! 
    // add your custom wxl for the default language either via project.LocalizationFile or project.LightOptions 
    string productMsi = project.BuildMsi(path);

    Compiler.OutputWriteLine("> Preparing language transformations...");

    var additionalLanguages = project.Language.Split(',', ';')
                                        .Skip(1)
                                        .Select(x => x.Trim());

    foreach (string lang in additionalLanguages)
    {
         // add your custom wxl for the default language either via project.LocalizationFile or project.LightOptions 

        string mstFile = project.BuildLanguageTransformExp(productMsi, lang);
        productMsi.EmbedTransform(mstFile);
    }

    productMsi.SetPackageLanguagesFrom(project);

    Compiler.OutputWriteLine($"> Multi-language setup {productMsi} is completed.");
    return productMsi;
}

public static string BuildLanguageTransformExp(this Project project, string originalMsi, string language, string localizationFile = "")
{
    var torch = Compiler.WixLocation.PathCombine("torch.exe");
    var originalLng = project.Language;
    var originalLocalizationFile = project.LocalizationFile;
    try
    {
        project.Language = language;
        project.LocalizationFile = localizationFile;

        string localizedMsi = project.BuildMsi(language).PathGetFullPath();
        string langMst = localizedMsi.PathChangeExtension(".mst");

        torch.Run($"-p -t language \"{originalMsi}\" \"{localizedMsi}\" -out \"{langMst}\"");
        return langMst;
    }
    finally
    {
        project.LocalizationFile = originalLocalizationFile;
        project.Language = originalLng;
    }
}

static int Run(this string exe, string args)
    => new ExternalTool { ExePath = exe, Arguments = args }.ConsoleRun();
```

**Comment by yurislav** [comment]
The content of `wxl` localization file passed to `BuildLanguageTransform` should look like this:

```
<?xml version="1.0" encoding="utf-8"?>
<WixLocalization Culture="sk-SK" Codepage="1250" xmlns="http://schemas.microsoft.com/wix/2006/localization">
    <String Id="msierrFirewallCannotConnect" Overridable="yes">Cannot connect to Windows Firewall.  ([2]   [3]   [4]   [5])</String>
    <String Id="WixSchedFirewallExceptionsInstall" Overridable="yes">Configuring Windows Firewall</String>
    <String Id="WixSchedFirewallExceptionsUninstall" Overridable="yes">Configuring Windows Firewall</String>
    <String Id="WixRollbackFirewallExceptionsInstall" Overridable="yes">Rolling back Windows Firewall configuration</String>
    <String Id="WixExecFirewallExceptionsInstall" Overridable="yes">Installing Windows Firewall configuration</String>
    <String Id="WixRollbackFirewallExceptionsUninstall" Overridable="yes">Rolling back Windows Firewall configuration</String>
    <String Id="WixExecFirewallExceptionsUninstall" Overridable="yes">Uninstalling Windows Firewall configuration</String>
</WixLocalization>
```

Change the language from `sk-SK` to your language, as well as the `CodePage`.

You can check [example setup](https://github.com/ninedigit/wixsharpextensions/wiki/Setup-for-ASP.NET-Core-application) that i put together when i struggled with localizations.

**Comment by oleg-shilo** [comment]
Thank you. Will have a look when I have next opportunity.
Still hope someone can give me a hand :)

**Comment by oleg-shilo** [comment]
It was marked as `help wanted` but did not trigger the interest from the users.
Closing it for now.
