### ISSUE TITLE
File disappears on major upgrade

### ISSUE THREAD

**Issue by Juanflu** [oleg-shilo/wixsharp#927]
We have an installer in charge on deploying the application. Within the files, there's a `docker-compose.override.yml`. This file is used as the configuration for the different services and we should keep it if the user made any change on it. We tried with the `NeverOverwrite` property, but now, when you upgrade the application to a newer version, this file disappear, causing an error when the application tries to run.
I was working on this for several hours, but I can't find a solution that works.

For context: We have al older installer, **version A**, with the following code regarding this file:

```csharp
var CIMProject = new ManagedProject()
{
  Name = "My APP",
  UI = WUI.WixUI_InstallDir,

  Dirs = new[]
  {
    new Dir($@"{Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86)}\APP",
      ...
      new WixSharp.File(@"..\docker-compose.override.yml") { NeverOverwrite = true }`
      ...
  }
};
```

And the `MajorUpgrade` property is set like this:

```csharp
...
project.MajorUpgrade = new MajorUpgrade
{
    Schedule = UpgradeSchedule.afterInstallInitialize,
};
```

Now, we need to make changes in the new installer, **version B**, to solve this.

- **In case of a new installation:** The file should be created.
- **In case of a major upgrade:** The file should not be overwritten if it has changes on it.

I was trying to change the `UpgradeSchedule` to `afterInstallExecute`, or setting the `project.ReinstallMode` to `"pmus"` but it didn't work. Also, I followed the approach explained in #636 

Is there a way to do this?

**WixSharp Version:** 1.13.2.0

Thanks in advance.

**Comment by oleg-shilo** [comment]
Sorry for answering your question not in the way you wanted. :(

> This file is used as the configuration for the different services and we should keep it if the user made any change on it.

This is a clear indication that you are following an anti-pattern here. No customizable configuration should be installed during deployment. Only binaries and fixed configuration. 

All customizable configuration should be created on the first run in the user or application profile. You may still be able to solve you problem but I wold rather avoid it.

**Comment by Juanflu** [comment]
Thanks for your response @oleg-shilo 

You're totally right. I will propose to move the creation of this file to a different workflow. 

Again, thanks a lot and I want to applause you for the work made with this library. It really makes life easier. 👏

**Comment by oleg-shilo** [comment]
Thank you. I am really glad it helps my fellow devs.
