### ISSUE TITLE
Missing util:PermissionEx support on the ServiceInstall element

### ISSUE THREAD

**Issue by candritzky** [oleg-shilo/wixsharp#928]
I'm trying to migrate the following hand-crafted WiX code to a WixSharp based solution:

```
<ServiceInstall Id="ServiceInstall"
                Name="MyServiceName"
                Type="ownProcess"
                Start="demand"
                Account="LocalSystem"
                ErrorControl="normal">
    <util:PermissionEx User="Everyone" ServicePauseContinue="yes" ServiceQueryStatus="yes"
                       ServiceStart="yes" ServiceStop="yes" ServiceUserDefinedControl="yes" />
</ServiceInstall>
```

Problem here is that I cannot find support for generating the nested `<PermissionEx />` element.
We are using this because we want to allow starting and stopping of the service even for non-privileged (elevated) users.

Is this a missing feature in WixSharp?
Or is there a better way to achieve the same result?

I'll try to use XML injection as mentioned in [Question: Registry Key Permissions Handling](https://github.com/oleg-shilo/wixsharp/issues/160) as a workaround.

**Comment by oleg-shilo** [comment]
There is support for `PermissionEx` but it is only integrated with `Directory` element but not `ServiceInstall`.
Will update it as soon as the opportunity presents.

**Comment by oleg-shilo** [comment]
Done in v1.15.0.0.
