### ISSUE TITLE
Wixsharp Dot net framework requirement

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#931]
Hi

Is the dot net framework required in the target machine to run wixsharp generated installer?
I am deploying a dot net core app using batch file which I did successfully in the past. This time there will not be a dotnet framework installed on the target machine.

thanks
Laz

**Comment by oleg-shilo** [comment]
If you are not using managed custom actions or ManagedUI then you do not need to have .NET present on the target machine.

However. Every Windows deployment that is up to date has .NET present. It is a part of every Windows distribution. Unless it is some obsolete version as Windows XP

**Comment by ltemimi** [comment]
Hi Oleg

Thanks for the help I do use managed custom actions and UI. So I will need the dot net framework.
Regards
Laz

**Comment by oleg-shilo** [comment]
No. Because 
> Every Windows deployment that is up to date has .NET present. Unless it is some obsolete version as Windows XP

**Comment by ltemimi** [comment]
Understood. Thanks
