### ISSUE TITLE
Bootstrap does not show license agreement

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#933]
Hi 

I brought this issue a while back and was wondering if the new version of Wixsharp has solved it.
I have a bootstrap that installs two Msi installers. The installation works but the Msi UI is not shown hence users do not see the license agreement.

I was able to do it with Wix in the past where each Msi lunches in turns and all the UI elements are shown.

Also is there a way or replacing the "disc" image on the bootstrap by a custom image
Thanks

Laz
```
  var bootstrapper =
                new Bundle("LogPlc",
                    new PackageGroupRef("NetFx40Web"),
                    new MsiPackage(windowsServiceInstaller) { DisplayInternalUI = false, Visible = true },
                    new MsiPackage(licenseWizardInstaller) { DisplayInternalUI = false, Visible = true })
                {
                    Version = new Version(version),
                    UpgradeCode = new Guid("{AFAD1969-6683-4C45-A392-10D9F20F9351}"),
                    IconFile = iconPath,
                    Manufacturer = "Automation Consultancy Ltd"
                };

            bootstrapper.Build($"{msiPath}\\LogPlc_{activeConfiguration}_{version}.exe");
```

**Comment by admingustshow** [comment]
For the custom image, can you try this line :
`bootstrapper.Application.LogoFile = @"Assets\MyFile.png";`

**Comment by ltemimi** [comment]
Hi

Thanks very much, it does work I just need to get the size right. Do you know the size of the CD logo?
Also as a bonus, it also solved the license agreement not showing there is an Application.License|Path

Laz

**Comment by admingustshow** [comment]
Hi, I have tried with a 64x64 pixels png and it works well

**Comment by ltemimi** [comment]
Hi, Thanks I am glad I am able to use Bootstrapper now.
