### ISSUE TITLE
AVAST blocks bundle installation

### ISSUE THREAD

**Issue by admingustshow** [oleg-shilo/wixsharp#934]
Hello, I've created a Wix bundle with 2 apps to install (one MSI, one EXE), and I signed the bundle and the app with a GlobalSign certificate.
Alas, when I test the installer on a machine with AVAST installed, AVAST blocks the installer during 15 seconds and the installer fails.
Did anyone encounter this problem ? 
Is it possible to extend the timeout on the WixSharp bundle class ?
Thanks

**Comment by yurislav** [comment]
What version of wix toolset are you using? I think that such issues were covered in version 3.14 (you can download development releases here: https://wixtoolset.org/releases/development/).

**Comment by admingustshow** [comment]
Hi, it seems I have the Wix toolset 3.11 installed
I will try with the 3.14, thanks

**Comment by skdutta-ga** [comment]
@admingustshow Did you have a chance to test with 3.14?

**Comment by admingustshow** [comment]
@skdutta-ga hello, yes, tried with 3.14 - I had no problem, but now Avast seems to have white listed my app, so I can not be completely sure.

**Comment by skdutta-ga** [comment]
ok thanks for the input
