### ISSUE TITLE
Install a kernel mode driver

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#935]
Hi Oleg,
maybe you can help me (again). I am currently doing a setup which includes an (kernel mode) driver also. I looked at your DriverSetup sample (DriverInstaller.cs) but I am afraid this is not enough. I have (on the old msi based setup) 5 files. So there is an inf File plus a sys and cat file for 32bit or 64bit. 
I think the cat is needed to deploy this special (kernel mode) driver as the cat should be the containment for the signature - but to be honest no idea :)
The question actually is how to deploy the driver. Do we need to preserve the inf file for the deinstallation ?

best
Carsten

**Comment by oleg-shilo** [comment]
It looks like this is an older deployment model that requires double-clicking the driver file.

You can solve the challenge of deploying the files. Then you can invoke PNPUtil for installing the driver.
```
PNPUtil.exe /add-driver <inf_file> /install
```

This is something that I quickly googled. You will need to do more deep reading of course
 but for the

**Comment by hcarsten** [comment]
Just continue on the task. After a long research I triggered the problem down to the usage of a pinvoke function. So using SetupInfObjectInstallAction seems to run the Installation in most cases. Development is pretty hard as the installation or deinstallation requires once while a reboot. So once I installed the driver, I can in most the cases not start it directly but have to run to a reboot. Pretty much the same for a the deinstallation.

Do we have a "restart and continue" feature within the created MSI ? 
Because what I have to do is pretty much, install the driver first, restart the box and then continue (then without installing the driver). But when deinstalling I have only to the deinstallation completely and do a restart at the far end of the process.

best

Carsten

**Comment by hcarsten** [comment]
p.s. happy to drop the full description here once we have this running, so others can also profit from this.

**Comment by oleg-shilo** [comment]
> Do we have a "restart and continue" feature within the created MSI ?

You can use `ForceReboot` 
Something like this.
```C#
    project.ForceReboot = new ForceReboot
    {
        Step = Step.InstallFinalize,
        Suppress  = false,
        . . . 
    };
```

Though how it works is a complete mystery for me. It is one of the cases of black magic of MSI/WiX: https://wixtoolset.org/documentation/manual/v3/xsd/wix/forcereboot.html

If I were you I would just invoke `Process.Start("shutdown.exe")` frome the `project.AfterInstall` event handler.
