### ISSUE TITLE
Building Bootstrapper for .Net Framework in one line

### ISSUE THREAD

**Issue by HavenDV** [oleg-shilo/wixsharp#936]
Build Bootstrapper for .Net Framework in one line. This includes the NSIS package, the package containing the web installers, and the Core package.
This is a package for myself, but maybe this will help someone. Inspired https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-integration-notes

Usage:
```cs
DotNetBootstrapper.Build(project, WebVersions.Net472);

// This is equivalent to
project.SetNetFxPrerequisite(version.Condition, version.ErrorMessage);
Compiler.BuildMsi(project);

DotNetBootstrapper.BuildExe(project, version);
```

https://www.nuget.org/packages/WixSharp.DotNetBootstrapper.Web/
https://github.com/HavenDV/WixSharp.DotNetBootstrapper/

**Comment by oleg-shilo** [comment]
Excellent. Thank you for sharing

**Comment by iovispot** [comment]
![image](https://user-images.githubusercontent.com/68770854/152690071-c7e9649e-18e1-4e9e-839d-8b7b33cf307b.png)

Getting these errors. I may understand what they mean, but I do not know what to do. What kind of files are these and how to generate the properly? Also, where to put them before running the project?

Originally wanted to submit an issue on that fork, but I believe that this is connected to the original bootstrapper, hoping to get help from more people.

**Comment by HavenDV** [comment]
My package is pretty simple. It simplifies just three lines of code, but also contains binary web installers that you don't have to look for yourself. Therefore, you can easily replace the code to not use WixSharp.DotNetBootstrapper and check if an error occurs or not.

**Comment by HavenDV** [comment]
Unfortunately, I don't use WixSharp that often and the errors above mean nothing to me.

**Comment by oleg-shilo** [comment]
@iovispot, I cannot link the screenshot you provided to any WixSharp VS project template. It seems that your VS project is something that you composed by yourself and some of the resources you added are missing.

I can suggest that you create a project from one of the WixSharp templates. It will be a good start that has a warranty for your project to build.

**Comment by iovispot** [comment]
@oleg-shilo I've used the Managed Setup - Custom UI template for this project. Maybe, I'm not using the bootstrapper thing properly? Judging by how HavenDV described, I tried tying it to my example like this:

`        static void Main()
        {
            var project = new ManagedProject("MyProduct",
                             new Dir(@"%ProgramFiles%\My Company\My Product",
                                 new File("Program.cs")));

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

            //custom set of standard UI dialogs
            project.ManagedUI = new ManagedUI();

            project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                            .Add<LicenceDialog>()
                                            .Add<SetupTypeDialog>()
                                            .Add<FeaturesDialog>()
                                            .Add<InstallDirDialog>()
                                            .Add<ProgressDialog>()
                                            .Add<ExitDialog>();

            project.ManagedUI.ModifyDialogs.Add<MaintenanceTypeDialog>()
                                           .Add<FeaturesDialog>()
                                           .Add<ProgressDialog>()
                                           .Add<ExitDialog>();

            //project.SourceBaseDir = "<input dir path>";
            //project.OutDir = "<output dir path>";

            ValidateAssemblyCompatibility();

            project.BuildMsi();
            DotNetBootstrapper.Build(project, WebVersions.Net451); // IOviSpot
        }

        static void ValidateAssemblyCompatibility()
        {
            var assembly = System.Reflection.Assembly.GetExecutingAssembly();

            if (!assembly.ImageRuntimeVersion.StartsWith("v2."))
            {
                Console.WriteLine("Warning: assembly '{0}' is compiled for {1} runtime, which may not be compatible with the CLR version hosted by MSI. " +
                                  "The incompatibility is particularly possible for the EmbeddedUI scenarios. " +
                                   "The safest way to solve the problem is to compile the assembly for v3.5 Target Framework.",
                                   assembly.GetName().Name, assembly.ImageRuntimeVersion);
            }
        }`

**Comment by iovispot** [comment]
Not sure what you mean. I've ran a new project from your template "Managed Setup - Custom UI", generated the installer and no issue occurs. Then I've added HavenDV's fork via NuGet, and the same function call after buildMSI (to automatically include .NET 4.5.1) and the same errors occur. The fork might be responsible for generating required files, maybe for the .NET installer?

**Comment by oleg-shilo** [comment]
Ah... I missed the point that you are using a third-party fork of WixSharp codebase. 

Sorry in this case I cannot comment on what is happening when you use that package. 
Most likely it modifies the project structure but accidentally breaks some dependencies. @HavenDV will be in a better position to answer that.
