### ISSUE TITLE
Question: Clear Temp for Install

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#937]
Hallo, i have a quesiton about external_ui/wpfs_setup. If i add new msi to exe setup and previous version exists in temp, setup find firstone, not newer one in temp windowsdir and cant update msi version. Only if i delete all previuous versions of msi`s.
Is there posibility to clear msi in temp after installer last action, whatever exit code was?

**Comment by Torchok19081986** [comment]
After some investigations , I tried to set PreserveTempFiles to false, but nothing happens.  in Demo installer msi will be resolved and will be written from installer to temp. works until now. second run with newer version of installer / msi file not working anymore. 
on startpage shows always old version, cause old msi exists. 
Im going to try with afterinstall in msi file generation, but here i struggle, just delete it exists file from temp. 
BA is clearly unknown region for me.

**Comment by oleg-shilo** [comment]
You can specify the name of the output file. There are two ways:
```C#
        project.OutFileName = ...
        project.BuildMsi("...");
```
