### ISSUE TITLE
ErrorDetected is not set when Error message is processed

### ISSUE THREAD

**Issue by dorny** [oleg-shilo/wixsharp#938]
I think I found a bug in [UIShell.ProcessMessage](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.UI/ManagedUI/UIShell.cs#L511) method.

If the `messageType` is `InstallMessage.Error`, processing is delegated to `MessageDialog.ProcessMessage(...)` and result is returned. However few lines later is a code which should set `ErrorDetected = true` for error messages. This will never happen as for error message processing will never get there.

Simplified code:
```c#
if (messageType.IsOneOf(InstallMessage.Error, InstallMessage.Warning, InstallMessage.User))
{
    // ... code omitted
    InUIThread(() =>
    {
        result = MessageDialog.ProcessMessage(messageType, messageRecord, buttons, icon, defaultButton);
    });
    return result; // <= Here we return from the method
}

// ... code omitted

if (messageType == InstallMessage.Error) // <= This will never be true
{
    ErrorDetected = true; 
    Errors.Add(messageRecord.ToString());
}
```

**Comment by dorny** [comment]
Just found out that `ErrorDetected` is later overwritten on `InstallMessage.InstallEnd` message. So setting it before that basically does nothing. 

I was trying to propagate non-fatal error from custom action. It should be displayed on the built in Exit dialog but without failing whole installation. Looks like this is not possible without creating custom dialog.

**Comment by oleg-shilo** [comment]
Agree. 
The error message in `ErrorDetected` is designed to mimic default MSI UI behavior, which is the fatal error message in the exit dialog.

If you need to communicate with the user then a custom dialog the way to go. The easiest way is to create the VS project from "... Custom UI" template, which bring source code for all dialogs.
