### ISSUE TITLE
64-bit package installs in Program Files (x86) after BuildMultilanguageMsi

### ISSUE THREAD

**Issue by snechaev** [oleg-shilo/wixsharp#939]
### Steps to reproduce 
1. Get "[Install on x64](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Install%20on%20x64/setup.cs)" sample  (commit 88fa7f5)
2. Replace `project.BuildMsi();` with `project.BuildMultilanguageMsi();`
3. Build
4. Install on Win10 64bit (RU)
5. Check the install location (`%ProgramFiles%\My Company`)

**Expected**: The application is installed in a 64-bit program files: `C:\Program files\My Company`, because the packages is 64-bit 

**Observed**: The application is installed in a 32-bit folder: `C:\Program Files (x86)\My Company`

### Build environment
* Win 10 Pro RU x64
* Windows Installer XML Toolset Compiler version 3.11.0.1701
* Wix# 1.14.8 from Nuget

### Notes
1 Unchanged sample works fine and installs in 64-bit Program files
2 Specifying languages (`project.Language="en-US"` or `project.Language="ru-RU,en-US"`) does not change situation
3 Approach with a manual mst creation as described in [wiki ](https://github.com/oleg-shilo/wixsharp/wiki/Localization) does not change situation.
4. Manual localization with MsiTran and other tools as described [here ](http://www.geektieguy.com/2010/03/13/create-a-multi-lingual-multi-language-msi-using-wix-and-custom-build-scripts/)works fine

**Comment by snechaev** [comment]
After additional checks I found that problem resides inside SetPackageLanguages. Before calling this function the msi summary indicates that platform = x64, but after the call to SetPackageLanguages, the summary shows platform = intel.

**Comment by oleg-shilo** [comment]
I am reopening it as the fix is not released yet.
BTW thank you for the fix :)
