### ISSUE TITLE
Gather Projectoutput with Code

### ISSUE THREAD

**Issue by emmoemminghaus** [oleg-shilo/wixsharp#94]
Hi,

i am wondering how to add project output to a wixsharp.
Do i have to call heat directly and add the output as include file?

I dreaming of something like this:

```
File primaryoutput;
var project = new Project(
	"Sample",
	primaryoutput = new PrimaryProjectOutput(Projectfile,,...),
	new ProjectOutput(Projectfile, outputgroup,...),
	);
// Do something with primaryoutputfile
primaryoutput.ServiceInstaller = ...

```
(May this question sounds dumb, because it is sooo easy to add files... not in my case
Taking the Files form Outputdirectory of a Project contains a lot of garbage.)

Regards
Emmo

**Comment by oleg-shilo** [comment]
Have a look at "Release Folder" and "WildCard Files" samples. It goes like this:
```C#
var project =
    new Project("MyProduct",
        new Dir(@"%ProgramFiles%\My Company\My Product",
            new Files(@"..\Release Folder\Release\*.*"),
            new ExeFileShortcut("Uninstall My Product", "[System64Folder]msiexec.exe", "/x [ProductCode]")));

project.GUID = new Guid("6f330b47-2577-43ad-9095-1561ba25889b");

project.BuildMsi();
 ```

**Comment by emmoemminghaus** [comment]
Thanks for the quick answer.

I saw this, but i have much noise in the output / release directory.
So i have to cleanup the output / release directory first.

Emmo

**Comment by oleg-shilo** [comment]
Not a problem. Keep in mind that you can specify predicate delegates when resolving wildcards (e.g. to pick only dll and exe files)....
