### ISSUE TITLE
how to show update button in Bootstrapper Application after OnDetectPackageComplete event

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#942]
hallo, i would to implement update button in my installer.exe if package is present then show update button with versions from installer and already installed version on firstpage /  mainwindow. Is there possibility to add this functions?  My Installed based on sample Bootstapper/WixBootstrapper_UI.

**Comment by oleg-shilo** [comment]
The sample includes the present installation detection logic so you can hook into it and update you button accordingly.

**Comment by Torchok19081986** [comment]
Many Thanks @oleg-shilo .  Means, instead of uninstall , i can place my updatebutton, if bundle with msi was found.
