### ISSUE TITLE
How get Condition result in managed?

### ISSUE THREAD

**Issue by apfacc** [oleg-shilo/wixsharp#944]
hi, im use managed ui. so as not to implement checks, how can I get the result of the original conditions?
example:
```
void next_Click(object sender, System.EventArgs e)
{
    var cond1 = Condition.Net45_Installed; //check .net
    bool res1 = cond1.Result;

    if (!res1) { //my custom logic }

    var cond2 = new Condition(@"IISMAJORVERSION <> """); //check iis installed or not
    bool res2 = cond2.Result;

    if (!res2) { //my custom logic }
			
    Shell.GoNext();
}
```

**Comment by oleg-shilo** [comment]
Normally MSI is using C++ routines packaged as CA to do some clever checking (e.g. detect presence of .NET 4.5) and then store the checking result in some session properties so it can be used in as a deployment condition fro your setup items.

WixSharp facilitates the use of such conditions by providing the class `Condition`  the it converted at compile time in the XML element of you WiX definition.  But `Condition` does not do anything at all during runtime. Thus I am not sure your code snippet will even compile.

If you are using managed UI you are better off by simply checking the presence of .NET by youself and using the result in C# condition directly (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed?redirectedfrom=MSDN)

**Comment by apfacc** [comment]
Ok, it's just not just .NET version. There may be other conditions, the result of which would help save time. Maybe there is some kind of hack that allows you to get these values?
example:
```
    public class CustomActions
    {
        public static bool Res1 { get; set; }
        public static bool Res2 { get; set; }

        [CustomAction]
        public static ActionResult MyAction(Session session)
        {
            var cond1 = Condition.Net45_Installed;
            Res1 = session.EvaluateCondition(cond1);

            var cond2 = new Condition(@"IISMAJORVERSION <> """); 
            Res2 = session.EvaluateCondition(cond2);

            return ActionResult.Success;
        }
    }

    class Program
    {
        static void Main()
        {
            var project = new ManagedProject("MyProduct",
                             new Dir(@"%ProgramFiles%\My Company\My Product",
                                 new File("Program.cs")),
                              new ManagedAction(CustomActions.MyAction)
                              
                );

            if (!CustomActions.Res1) { //my custom logic }

            if (!CustomActions.Res2) { //my custom logic }
        }
    }
```

Why doesn't this work for me?

**Comment by oleg-shilo** [comment]
`Main()` is a method that is **building** your MSI. It is only invoked when you build your VS project. `Main()` is not executed during the installation.  Your custom action is.

I am also not sure about you posting the examples of the code that is not supposed to work. Thus your example will never build/compile an MSI file as it does not call `project.BuildMsi()`.

I suggest you follow WixSharp documentation. This is a good starting point: https://github.com/oleg-shilo/wixsharp/wiki/Building-MSI-%E2%80%93-Step-by-step-tutorial.
 
You can implement your custom logic directly in the CA class:

```C#
public class CustomActions
    {
        public static bool Res1 { get; set; }
        public static bool Res2 { get; set; }

        [CustomAction]
        public static ActionResult MyAction(Session session)
        {
            var cond1 = Condition.Net45_Installed;
            Res1 = session.EvaluateCondition(cond1);

            var cond2 = new Condition(@"IISMAJORVERSION <> """); 
            Res2 = session.EvaluateCondition(cond2);

            if (!CustomActions.Res1) { //my custom logic }

            if (!CustomActions.Res2) { //my custom logic }

            return ActionResult.Success;
        }
    }
```

Or in the ManagedProject event:
```C#
        project.BeforeInstall += Project_BeforeInstall;

        project.BuildMsi();
    }

    static void Project_BeforeInstall(SetupEventArgs e)
    {
        var net45_Installed = e.Session.EvaluateCondition(Condition.Net45_Installed);
        var isMajorVersion = e.Session.EvaluateCondition("IISMAJORVERSION <> \"\"");

        if (!net45_Installed)
        {
            //my custom logic
        }

        if (!isMajorVersion)
        {
            //my custom logic
        }
    }
```

**Comment by apfacc** [comment]
okay, i checked both of these. unfortunately they do not give the correct result. Will return 'False' in all cases
```
MessageBox.Show(net45_Installed);
MessageBox.Show(isMajorVersion);
```
although I'm sure I have both installed and should return two 'True'

**Comment by oleg-shilo** [comment]
Since you are troubleshooting a third party routine (WiX) it's hard to find the failure reason. Particularly because it's not clear when the properties in question are initialized by MSI runtime. Thus you might be evaluating the property before it is assigned.

That's why I always prefer deterministic approach that relies on C# (your own custom routine). You know exactly how it works and when it is invoked. And you can also debug it. :)

I would try rely on WiX for the straight forward scenarios when it works really well. For anything tricky or "stubborn" I would use raw C#.

But the choice is yours.
