### ISSUE TITLE
3-rd party nuget libraries don't work in managed

### ISSUE THREAD

**Issue by apfacc** [oleg-shilo/wixsharp#945]
hi, im create default managed UI template (.net 4.0 target) and install to json and async/await support

> Install-Package Newtonsoft.Json
> Install-Package Microsoft.Bcl.Async

but when i use them in forms they freeze. help me, please

**Comment by oleg-shilo** [comment]
You will need to distribute these libraries with your MSi. Embed them into it.
You can do it with the `project.DefaultRefAssemblies`. Have a look at https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#managed-custom-actions

**Comment by apfacc** [comment]
oleg, thanks) yes it works!
