### ISSUE TITLE
Error 1923 when installing service

### ISSUE THREAD

**Issue by maarre** [oleg-shilo/wixsharp#950]
This is probably not a bug. But some help would be appreciated.

From the msi debug log:

```
MSI (s) (84:2C) [12:49:03:241]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI7F8D.tmp, Entrypoint: WixSharp_AfterInstall_Action
SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSI7F8D.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
MSI (s) (84:34) [12:49:03:733]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
MSI (s) (84:34) [12:49:03:735]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (84:34) [12:49:03:736]: Executing op: ServiceInstall(Name=EnrollmentSecureTransportAgent,DisplayName=EnrollmentSecureTransportAgent,ImagePath="C:\Program Files (x86)\EnrollmentSecureTransport\EnrollmentSecureTransportAgent.exe",ServiceType=16,StartType=2,ErrorControl=1,,Dependencies=[~],,StartName=.\LOCAL_ACCOUNT,Password=**********,Description=Automatically reenrolls certificates about to expire. Configured through registry Computer\HKEY_LOCAL_MACHINE\SOFTWARE\EST,,)
Error 1923. Service 'EnrollmentSecureTransportAgent' (EnrollmentSecureTransportAgent) could not be installed. Verify that you have sufficient privileges to install system services.
MSI (s) (84:34) [12:49:06:085]: Product: EnrollmentSecureTransport -- Error 1923. Service 'EnrollmentSecureTransportAgent' (EnrollmentSecureTransportAgent) could not be installed. Verify that you have sufficient privileges to install system services.


```
I am using Windows ® Installer. V 5.0.18362.1

[Program.zip](https://github.com/oleg-shilo/wixsharp/files/5629659/Program.zip)

**Comment by ZeroAbility** [comment]
Does it give the same error if you install it using `msiexec /i` from an Admin command prompt?

**Comment by maarre** [comment]
I get the same popup.

Best regards

Mårten

Från: Nik Reist <notifications@github.com>
Skickat: den 4 december 2020 08:09
Till: oleg-shilo/wixsharp <wixsharp@noreply.github.com>
Kopia: Gustafsson Mårten (4004) <marten.gustafsson@forsakringskassan.se>; Author <author@noreply.github.com>
Ämne: Re: [oleg-shilo/wixsharp] Error 1923 when installing service (#950)


Does it give the same error if you install it using msiexec /i from an Admin command prompt?

**Comment by ZeroAbility** [comment]
Without knowing more about the environment my best guess is the issue is still permissions related. There is more info about the permissions here:

https://docs.microsoft.com/en-us/windows/win32/services/service-security-and-access-rights

Service registration will have to be done either elevated or as a local administrator.

**Comment by maarre** [comment]
I solved it by reverting to plain WiX.

Från: Nik Reist <notifications@github.com>
Skickat: den 4 december 2020 21:28
Till: oleg-shilo/wixsharp <wixsharp@noreply.github.com>
Kopia: Gustafsson Mårten (4004) <marten.gustafsson@forsakringskassan.se>; Author <author@noreply.github.com>
Ämne: Re: [oleg-shilo/wixsharp] Error 1923 when installing service (#950)


Without knowing more about the environment my best guess is the issue is still permissions related. There is more info about the permissions here:

https://docs.microsoft.com/en-us/windows/win32/services/service-security-and-access-rights

Service registration will have to be done either elevated or as a local administrator.

**Comment by oleg-shilo** [comment]
It does look like a permissions issue. Possible around .NET CAS.
WiX is extracting the custom action dll (assembly) to the temp dir in order to execute an entry point from it. And CAS may be configured extremely aggressively so it does not allow the asm execution.  This is my best guess :)

**Comment by maarre** [comment]
Thanks Oleg

A few thoughts.

I am using ILMerge to avoid having to name all dlls in WiX. The build produces a couple of exe-files. So my WiX project is extremely simple now. And it works.

Why use WiX? Two layers on top of Microsof install SDK. Interface the install SDK directly.

Take a look at Shake. Maybe it could be enhanced to output MSI as well. Installers written in Haskell DSL ☺.

Best regards

Mårten Gustafsson

Från: Oleg Shilo <notifications@github.com>
Skickat: den 8 december 2020 14:06
Till: oleg-shilo/wixsharp <wixsharp@noreply.github.com>
Kopia: Gustafsson Mårten (4004) <marten.gustafsson@forsakringskassan.se>; Author <author@noreply.github.com>
Ämne: Re: [oleg-shilo/wixsharp] Error 1923 when installing service (#950)


It does look like a permissions issue. Possible around .NET CAS.
WiX is extracting the custom action dll (assembly) to the temp dir in order to execute an entry point from it. And CAS may be configured extremely aggressively so it does not allow the asm execution. This is my best guess :)

**Comment by oleg-shilo** [comment]
> Why use WiX? Two layers on top of Microsof install SDK. Interface the install SDK directly.

😄 The reasons are here: https://www.infoq.com/articles/WixSharp/
Sorry for shamelessly quoting myself. During that interview Jonathan has asked me the same DSL question.

> Take a look at Shake.

As any SW vendor I have to ask myself "What is the problem that an alternative msi compiling technology would solve? What is the cost and the benefit?" 

None of the answers strongly works against WiX. Though... technically it is probably possible.

**Comment by maarre** [comment]
It is not the same question. Target the install sdk directly instead of generating WiX xml. /M

Från: Oleg Shilo <notifications@github.com>
Skickat: den 9 december 2020 14:21
Till: oleg-shilo/wixsharp <wixsharp@noreply.github.com>
Kopia: Gustafsson Mårten (4004) <marten.gustafsson@forsakringskassan.se>; Author <author@noreply.github.com>
Ämne: Re: [oleg-shilo/wixsharp] Error 1923 when installing service (#950)


Why use WiX? Two layers on top of Microsof install SDK. Interface the install SDK directly.

😄 The reasons are here: https://www.infoq.com/articles/WixSharp/
Sorry for shamelessly quoting myself. During that interview Jonathan has asked me the same DSL question.

Take a look at Shake.

As any SW vendor I have to ask myself "What is the problem that an alternative msi compiling technology would solve? What is the cost and the benefit?"

None of the answers strongly works against WiX. Though... technically it is probably possible.

**Comment by oleg-shilo** [comment]
"the same" it was about DSL.

As for targeting WiX vs SDK I still have to ask the same question. What problem would it sole? 😄 
It would be less dependencies but more difficult to evolve the product. SDK is way more complicated than WiX.
And we would loose all niceties WiX offers on top of SDK. Even though WiX can also be awkward sometimes.

It fills like I am repeating the answers from that interview... It's like to say "Why C# bother with IL Why not to target the native execution directly?" 

WixSharp (similarly to many others) is a transcompiler and as such it capitalizes on converting a more manageable source code into a less manageable but avoiding low level conversion as more effort consuming and more error-prone direction.

**Comment by maarre** [comment]
Well

The problem I got is probably because there are two layers on top of the sdk. Increased complexity.

I wixsharp had worked I would never have looked at wix.

I really like what you do. Keep up the good work!

Best regards

Mårten

Från: Oleg Shilo <notifications@github.com>
Skickat: den 9 december 2020 14:40
Till: oleg-shilo/wixsharp <wixsharp@noreply.github.com>
Kopia: Gustafsson Mårten (4004) <marten.gustafsson@forsakringskassan.se>; Author <author@noreply.github.com>
Ämne: Re: [oleg-shilo/wixsharp] Error 1923 when installing service (#950)


"the same" it was about DSL.

As for targeting WiX vs SDK I still have to ask the same question. What problem would it sole? 😄
It would be less dependencies but more difficult to evolve the product. SDK is way more complicated than WiX.
And we would loose all niceties WiX offers on top of SDK. Even though WiX can also be awkward sometimes.

It fills like I am repeating the answers from that interview... It's like to say "Why C# bother with IL Why not to target the native execution directly?"

WixSharp (similarly to many others) is a transcompiler and as such it capitalizes on converting a more manageable source code into a less manageable but avoiding low level conversion as more effort consuming and more error-prone direction.
