### ISSUE TITLE
Questions about assigning objects to Dir.Files

### ISSUE THREAD

**Issue by ZeroAbility** [oleg-shilo/wixsharp#951]
Greetings,

I am fairly new to using wixsharp and I prefer it to wix proper. I just had some questions about the object that `File` objects get assigned to. Here is the `Files` object for reference:

https://github.com/oleg-shilo/wixsharp/blob/cb8546861900a28394f7281d8573a68f84fbff01/Source/src/WixSharp/Dir.cs#L243

I am using the Traditional C# style, because I would like to keep the names of the files we are packaging in a `string[]` so that when new files need to be added people don't have to write out the `new File()` statement each time. We have several files and this would make things more readable and manageable, as well. I would assume this means that I could assign a value by index to `File[]` the same way I can to `string[]`:
```
var myInstallDir = new Dir(installPath);
myInstallDir.Files = new File[] { };

for(int i = 0; i < myFiles.Length; i++) {
    myInstallDir.Files[i] = new File(@"..\" + myFiles[i]);
}
```
 This doesn't appear to be the case. I am also not able to make a `File[]` object that I can assign values to by index and then assign to `Dirs.Files` explicitly, like:
```
myInstallDir.Files = bins;
```
Both throw an IndexOutOfRangeException. 

My questions are:

- Am I using these objects correctly or is this a bug?
- If I am using them incorrectly, is there a better way to assign the names of files and decorate the `new File()` statement in an iterator instead writing them out individually?

**Comment by snechaev** [comment]
To assign the elements of array (Files[]) by index, you first need to make array of proper size to make such an index valid. 
So
```
//var Files = new File[0];//this will throw IndexOutOfRangeException inside for-loop
var Files = new File[myFiles.Length];//this will work
your-for-loop-goes-here
myInstallDir.Files = Files;
```

**Comment by ZeroAbility** [comment]
Thank you. That seems to allow the `Files` to be created in a loop successfully. The issue I am facing now is they are not being added correctly to `myInstallDir` because the files end up in `%ProgramFiles%`. I have specified `myInstallDir` as object `InstallDir` due to the compiler warning that it will set the value to `ProgramFiles64Folder`. I also cannot add subdirectories to `myInstallDir`. I attempt this like so:
```
var subDirA = new Dir("subA");
var subDirB = new Dir("subB");
myInstallDir.Dirs = new Dir[] { subDirA, subDirB };
```
This breaks the `INSTALLDIR` value assignment somehow. It also ignores `IsInstallDir` and the `Compiler` flag to suppress the auto assign. Any further assistance would be great.

**Comment by ZeroAbility** [comment]
@snechaev I ended up using `Environment.GetFolderPath()` for Program Files and Start Menu. I think based on how my project is set up, I'm not able to access environment variables. We will need to create 2 installers and I am using inheritance to manage things that they share. Hopefully, this helps someone else.

**Comment by ZeroAbility** [comment]
It appears a lot of my path issues had to do with the inheritance I am using. I was able to resolve that in much the same way as the `Files` guidance. It also meant I had to specify every single directory individually in order to get correct install and shortcut paths. Maybe that is a product of the "traditional" paradigm, but I am going to go ahead and close this. I appreciate the help.

**Comment by oleg-shilo** [comment]
> Environment.GetFolderPath() for Program Files and Start Menu....

You should not use actual path that is resolved during building your MSI. If you do then it embeds into your msi the location of the special folder (e.g. Program Files) of your build machine. 

And of course your msi will fail to install on the machine where this directory has different path.

That's why you should use special constants like `ProgramFiles64Folder` or `%ProgramFIles%` to instruct your MSI to install files to the special folder on the target machine.

**Comment by ZeroAbility** [comment]
> You should not use actual path that is resolved during building your MSI. If you do then it embeds into your msi the location of the special folder (e.g. Program Files) of your build machine.
> 
> And of course your msi will fail to install on the machine where this directory has different path.
> 
> That's why you should use special constants like `ProgramFiles64Folder` or `%ProgramFIles%` to instruct your MSI to install files to the special folder on the target machine.

I discovered this through testing. I was eventually able to get `%ProgramFiles%` to work again. If you are interested in seeing what I am working on and how that was achieved you can review it here:
https://github.com/mumble-voip/mumble/commit/a402a81961f3e9d021c98251557c55e78ccfa844#diff-9eac8d51f1017cfd5cdb9b107fcf19c855bd1dd88f4e4f3e9b158ff222fba106
