### ISSUE TITLE
Problem with relative Certificate.CertificatePath

### ISSUE THREAD

**Issue by Juanflu** [oleg-shilo/wixsharp#952]
First of all, I'll explain a bit the scenario: I'm installing an application, that is basically a .NET Core self-contained application running as a Windows Service. I have no problems to deploy all the files (I only have to exclude the `exe` file from the `Files` to be able to call the `ServiceInstaller` method from it).
The issue I'm having is that I can't set a relative path for the `CertificatePath` in the `Certificate` entry. It builds correctly, but when I try to install it I'm getting the following error:

```
InstallCertificates:  Error 0x80070003: Failed to read PFX file: Service\Certificates\certificate.crt
InstallCertificates:  Error 0x80070003: Failed to read certificate from file path.
InstallCertificates:  Error 0x80070003: Failed to resolve certificate: Certificate
```

The code in in the `Main` method is the following:

```csharp
Feature serviceFeature = new Feature("Service", "Service binaries", true, false);
File serviceExe = new File(serviceFeature, @"Service\Service.exe");
Files serviceFiles = new Files(serviceFeature, @"Service\*.*", p => !p.Contains("Service.exe"));

Project project = new Project("Project Name",
    new Dir(@"%ProgramFiles%\Project Name",
        new Dir(serviceFeature, "ServiceFolder", serviceFiles, serviceExe,
            new Certificate
            {
                Name = "Service Name",
                StoreLocation = StoreLocation.localMachine,
                StoreName = StoreName.my,
                CertificatePath = @"Service\Certificates\certificate.pfx",
                PFXPassword = "supersecurepassword",
                Request = false
            }
        ),
    )
);

serviceExe.ServiceInstaller = GenerateServiceInstaller("Service Name");

ConfigureProject(project, version);

project.BuildMsi();
```

The only way I was able to make it work is using an absolute path for the certificate but, of course, this is not the solution. I tried including the file to the project, path relative to the Feature path...

I had to create a `CustomAction` in order to use `certutil` to import the certificate, but it would be nice to be able to handle it directly with WixSharp.

Thanks a lot for your effort and this awesome library 💯 

```
WixSharp version: 1.15.0.0
.NET Framework 4.7.2`
```

**Comment by snechaev** [comment]
As per comments
https://github.com/oleg-shilo/wixsharp/blob/d9c8f5b4437c63f83b6d6c8cf577ec2289758b52/Source/src/WixSharp/Certificate.cs#L180-L185

I can see that a path outside the msi package is required for the `CertificatePath` field. So, there is not obvious which root should be used in case of relative path.

But, as described in [WIX docs](https://wixtoolset.org/documentation/manual/v3/xsd/iis/certificate.html), the variables are allowed inside `CertificatePath`, so you can try something like '@"[INSTALLDIR]\Service\Certificates\certificate.pfx"' value for `CertificatePath` to reference the Certificate, installed along with other app files.

**Comment by Juanflu** [comment]
Thanks for your response @snechaev.

As you said, using the `[INSTALLDIR]` variable I was able to reference the file that will be installed. It resolves the path correctly but I'm getting the same error. 
```
InstallCertificates:  Error 0x80070003: Failed to read PFX file: C:\Program Files (x86)\APP\Service\Certificates\certificate.pfx
InstallCertificates:  Error 0x80070003: Failed to read certificate from file path.
InstallCertificates:  Error 0x80070003: Failed to resolve certificate: Certificate
```
It seems that it's trying to get the certificate before the files are copied to the installation directory, but I don't know how to deal with this issue.

I also tried using the `BinaryKey` as it is here:
https://github.com/lukaswinzenried/WixCustBa/blob/8d7f4162761c16d48ad4831ebd45033075c6b302/test/data/Extensions/IISExtension/IISCertificateTests/product.wxs#L26

My code:
```csharp
Project project = new Project("Project Name",
--> new Binary(new Id("certificate"), @"Service\Certificates\certificate.pfx"),
    new Dir(@"%ProgramFiles%\Project Name",
        new Dir(serviceFeature, "ServiceFolder", serviceFiles, serviceExe,
            new Certificate
            {
                Name = "Service Name",
                StoreLocation = StoreLocation.localMachine,
                StoreName = StoreName.my,
------------->  BinaryKey = "certificate",
                PFXPassword = "supersecurepassword",
                Request = false
            }
        ),
    )
);
```
With this approach, the error changes to the following:
```
InstallCertificates:  Error 0x8000ffff: Unexpected certificate type read from disk.
InstallCertificates:  Error 0x8000ffff: Failed to read certificate from file path.
InstallCertificates:  Error 0x8000ffff: Failed to resolve certificate: Certificate.1
```

I continue digging on it, but maybe I have to find another solution.

**Comment by Juanflu** [comment]
In the end I choose to add a `CustomAction` and use `X509Certificate2` and `X509Store` to import the certificate. If in the future there is a way to use the Certificate class with a relative path, then I'll change it.

```csharp
[CustomAction]
public static ActionResult ImportCertificate(Session session)
{
    string certPath = session["INSTALLDIR"] + @"Service\Certificates\certificate.pfx";
    var cert = new X509Certificate2(X509Certificate.CreateFromCertFile(certPath), "supersecurepassword");

    using (var store = new X509Store(StoreName.My, StoreLocation.LocalMachine))
    {
        store.Open(OpenFlags.ReadWrite);
        store.Add(cert);
    }

    return ActionResult.Success;
}
```

Thanks!

**Comment by oleg-shilo** [comment]
You can also use `project.AfterInstall` event, which is nothing else but a more convenient deferred (elevated) custom action. 
From my memory:

```C#
project.AfterInstall += (SetupEventArgs e)=>
{
    string certPath = e.InstallDir.PathCombine(@"Service\Certificates\certificate.pfx");
    var cert = new X509Certificate2(X509Certificate.CreateFromCertFile(certPath), "supersecurepassword");

    using (var store = new X509Store(StoreName.My, StoreLocation.LocalMachine))
    {
        store.Open(OpenFlags.ReadWrite);
        store.Add(cert);
    }
}
```
