### ISSUE TITLE
Various issues on IIS

### ISSUE THREAD

**Issue by Giangi72** [oleg-shilo/wixsharp#953]
Hi Oleg and everyone,
first of all congratulations for your tool, I tested Wix without Wix# and it was powerful but with an huge learning curve.
With your tool everything is simpler.

My problem is that I need some help with IIS. 
I need to
1. create an application pool and assign a specific user to it
2. create a web site having application pool from point 1
and stop, no Web Application, so in IIS there are no leafs under **Sites**->**MySite**
I used this code
_new Dir(new Id("VIRTUALDIRECTORY"), "VIRTUALDIRECTORY",
       new User(new Id("newUser"), "[UserName]", "[Domain]")
       {
           Password = "[Password]",
           CreateUser = false
        },
        new IISVirtualDir
        {
           Name = "Server",
           AppName = "Server",
           WebSite = new WebSite("[SiteName]", "*:[HTTPPort]") { InstallWebSite = true },
           WebAppPool = new WebAppPool("[AppPoolName]",
               "ManagedRuntimeVersion=v4.0;" +
               "ManagedPipelineMode=Integrated;" +
               "Identity=other;" +
               "User=newUser"
           )
        }
 )_
but it creates the **Server** WebApplication under my site.
If I add 
`project.WixSourceGenerated += doc => doc.FindAll("WebVirtualDir").ForEach(x => x.Remove());`
someone suggested in another topic
the site is created without WebApplication but it is assigned to **DefaultAppPool**

Additionally when I uninstall it, only the folder on disc is deleted, the application pool and Site remain in IIS.

Many thanks in advance for your help

**Comment by onefreddy** [comment]
@Giangi72 I also noticed problems with deleting website after updating the library to 1.15.0. It seems broken there. Try to rollback to version 1.14.8 your nuget reference.

**Comment by oleg-shilo** [comment]
@Giangi72 can you please capture the WiX xml produced with v1.15.0 (does not delete website) and v1.14.8.
If the problem is caused by differently composed xml then it will be very easy to fix. But I need to know what is the difference.
txs

**Comment by Giangi72** [comment]
Hi,
this is the generated code, the parameters are get from managed ui and they work correctly.
Thanks

`<?xml version="1.0" encoding="utf-8"?>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="6fe30b47-2577-43ad-9095-1861ca25889c" Name="SiteSetup" Language="1033" Codepage="Windows-1252" Version="1.0.0.0" UpgradeCode="6fe30b47-2577-43ad-9095-1861ba25889b" Manufacturer="gdelia">
    <Package InstallerVersion="200" Compressed="yes" SummaryCodepage="Windows-1252" Languages="1033" />
    <Media Id="1" Cabinet="SiteSetup.cab" EmbedCab="yes" />

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="VIRTUALDIRECTORY" Name="VIRTUALDIRECTORY">

        <Component Id="Component.VIRTUALDIRECTORY.VirtDir" Guid="6fe30b47-2577-43ad-9095-1861dfeeb5de" KeyPath="yes">
          <WebVirtualDir Id="VirtDir" Alias="Server" Directory="VIRTUALDIRECTORY" WebSite="WebSite" xmlns="http://schemas.microsoft.com/wix/IIsExtension">
            <WebApplication Id="ServerWebApplication" Name="Server" WebAppPool="Server_AppPool" />
          </WebVirtualDir>

          <WebSite Id="WebSite" Description="[SITENAME]" Directory="VIRTUALDIRECTORY" xmlns="http://schemas.microsoft.com/wix/IIsExtension">
            <WebAddress Id="WebSite_Address1" IP="*" Port="[HTTPPORT]" />
          </WebSite>

          <WebAppPool Id="Server_AppPool" Name="[AppPoolName]" ManagedRuntimeVersion="v4.0" ManagedPipelineMode="Integrated" Identity="other" User="newUser" xmlns="http://schemas.microsoft.com/wix/IIsExtension" />

          <CreateFolder />
          <RemoveFolder Id="VIRTUALDIRECTORY" On="uninstall" />
        </Component>

        <Component Id="newUser" Guid="6fe30b47-2577-43ad-9095-1861b221c44b" KeyPath="yes">
          <User Id="newUser" Name="[UserName]" CreateUser="no" Domain="[Domain]" Password="[Password]" xmlns="http://schemas.microsoft.com/wix/UtilExtension" />

          <CreateFolder />
        </Component>

        <Component Id="AppPoolName" Guid="6fe30b47-2577-43ad-9095-18618136250d" KeyPath="yes">
          <Environment Id="AppPoolName" Name="AppPoolName" Value="My name" Action="set" />

          <CreateFolder />
        </Component>

        <Component Id="Domain" Guid="6fe30b47-2577-43ad-9095-1861a460619d" KeyPath="yes">
          <Environment Id="Domain" Name="Domain" Value="-" Action="set" />

          <CreateFolder />
        </Component>

        <Component Id="UserName" Guid="6fe30b47-2577-43ad-9095-186140ff1fca" KeyPath="yes">
          <Environment Id="UserName" Name="UserName" Value="-" Action="set" />

          <CreateFolder />
        </Component>

        <Component Id="Password" Guid="6fe30b47-2577-43ad-9095-1861ac5daa6d" KeyPath="yes">
          <Environment Id="Password" Name="Password" Value="-" Action="set" />

          <CreateFolder />
        </Component>

      </Directory>

      <Component Id="TARGETDIR" Guid="6fe30b47-2577-43ad-9095-18612df5f80e" KeyPath="yes">
        <RemoveFolder Id="TARGETDIR" On="uninstall" />
      </Component>

    </Directory>

    <UI />

    <UI>
      <EmbeddedUI Id="WixSharp_EmbeddedUI_Asm" SourceFile="WixSharp.UI.CA.dll" />
    </UI>

    <CustomAction Id="WixSharp_InitRuntime_Action" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="WixSharp_InitRuntime_Action" Return="check" Execute="immediate" />
    <CustomAction Id="Set_CancelRequestHandler_Props" Property="CancelRequestHandler" Value="UpgradeCode=[UpgradeCode];INSTALLDIR=[INSTALLDIR];UILevel=[UILevel];ProductCode=[ProductCode];ADDLOCAL=[ADDLOCAL];ADDFEATURES=[ADDFEATURES]" />
    <CustomAction Id="CancelRequestHandler" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="CancelRequestHandler" Return="check" Impersonate="no" Execute="deferred" />
    <CustomAction Id="WixSharp_Load_Action" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="WixSharp_Load_Action" Return="check" Execute="immediate" />
    <CustomAction Id="WixSharp_BeforeInstall_Action" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="WixSharp_BeforeInstall_Action" Return="check" Execute="immediate" />
    <CustomAction Id="Set_WixSharp_AfterInstall_Action_Props" Property="WixSharp_AfterInstall_Action" Value="WixSharp_AfterInstall_Handlers=[WixSharp_AfterInstall_Handlers];WIXSHARP_RUNTIME_DATA=[WIXSHARP_RUNTIME_DATA];INSTALLDIR=[INSTALLDIR];UILevel=[UILevel];ProductName=[ProductName];INSTALLDIR=[INSTALLDIR];UILevel=[UILevel];ProductCode=[ProductCode];ADDLOCAL=[ADDLOCAL];ADDFEATURES=[ADDFEATURES]" />
    <CustomAction Id="WixSharp_AfterInstall_Action" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="WixSharp_AfterInstall_Action" Return="check" Impersonate="no" Execute="deferred" />

    <Binary Id="WixSharp_InitRuntime_Action_File" SourceFile="WixSharp.CA.dll" />
    <Binary Id="WixSharp_UIText" SourceFile="SiteSetup.wxl" />
    <Binary Id="WixSharp_LicenceFile" SourceFile="SiteSetup.licence.rtf" />
    <Binary Id="WixUI_Bmp_Dialog" SourceFile="SiteSetup.dialog_bmp.png" />
    <Binary Id="WixUI_Bmp_Banner" SourceFile="SiteSetup.dialog_banner.png" />

    <UIRef Id="WixUI_ErrorProgressText" />

    <Property Id="WixSharp_UI_INSTALLDIR" Value="INSTALLDIR" />
    <Property Id="UAC_REVEALER_ENABLED" Value="true" />
    <Property Id="UAC_WARNING" Value="Please wait for UAC prompt to appear.&#xD;&#xA;&#xD;&#xA;If it appears minimized then activate it from the taskbar." />
    <Property Id="WixSharp_InstallDialogs" Value="WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.WelcomeDialog&#xA;SiteAndAppPoolSetup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|WixSharpSetup.SiteDialog&#xA;SiteAndAppPoolSetup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|WixSharpSetup.AppPoolDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ProgressDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ExitDialog" />
    <Property Id="WixSharp_ModifyDialogs" Value="WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.MaintenanceTypeDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.FeaturesDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ProgressDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ExitDialog" />
    <Property Id="WixSharp_UIInitialized_Handlers" Value="SiteAndAppPoolSetup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|SiteAndAppPoolSetup.Program|Msi_UIInitialized" />
    <Property Id="WixSharp_UILoaded_Handlers" Value="SiteAndAppPoolSetup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|SiteAndAppPoolSetup.Program|Msi_UILoaded" />
    <Property Id="WixSharp_Load_Handlers" Value="SiteAndAppPoolSetup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|SiteAndAppPoolSetup.Program|Msi_Load" />
    <Property Id="WixSharp_BeforeInstall_Handlers" Value="SiteAndAppPoolSetup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|SiteAndAppPoolSetup.Program|Msi_BeforeInstall" />
    <Property Id="WixSharp_AfterInstall_Handlers" Value="SiteAndAppPoolSetup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|SiteAndAppPoolSetup.Program|Msi_AfterInstall" />

    <Feature Id="Complete" Title="Complete" Absent="allow" Level="1">
      <ComponentRef Id="newUser" />
      <ComponentRef Id="AppPoolName" />
      <ComponentRef Id="Domain" />
      <ComponentRef Id="UserName" />
      <ComponentRef Id="Password" />
      <ComponentRef Id="Component.VIRTUALDIRECTORY.VirtDir" />
      <ComponentRef Id="TARGETDIR" />
    </Feature>

    <InstallExecuteSequence>
      <Custom Action="WixSharp_InitRuntime_Action" Before="AppSearch"> (1) </Custom>
      <Custom Action="Set_CancelRequestHandler_Props" Before="InstallFinalize" />
      <Custom Action="CancelRequestHandler" After="Set_CancelRequestHandler_Props"> (NOT (REMOVE="ALL")) </Custom>
      <Custom Action="WixSharp_Load_Action" Before="AppSearch">1</Custom>
      <Custom Action="WixSharp_BeforeInstall_Action" Before="InstallFiles">1</Custom>
      <Custom Action="Set_WixSharp_AfterInstall_Action_Props" After="InstallFiles" />
      <Custom Action="WixSharp_AfterInstall_Action" After="Set_WixSharp_AfterInstall_Action_Props">1</Custom>
    </InstallExecuteSequence>

  </Product>
</Wix>

`

**Comment by oleg-shilo** [comment]
Can you also share the C# code (and ideally the WiX xml) that does not behave as expected. 

So I can see what prevents the correct xml generation.

**Comment by Giangi72** [comment]
I did some little modify so I also updated the wxs code in previous post.
My code, in project section is very simple 


            ManagedProject project = new ManagedProject("SiteSetup2",
                new InstallDir(new Id("VIRTUALDIRECTORY"), "VIRTUALDIRECTORY",
                    new User(new Id("newUser"), "[USERNAME]", "[DOMAIN]")
                    {
                        Password = "[PASSWORD]",
                        CreateUser = false
                    },
                    new IISVirtualDir
                    {
                        Name = "Server",
                        AppName = "Server",
                        WebSite = new WebSite("[SITENAME]", "*:[HTTPPORT]") { InstallWebSite = true,  },
                        WebAppPool = new WebAppPool("[APPPOOLNAME]",
                            "ManagedRuntimeVersion=v4.0;" +
                            "ManagedPipelineMode=Integrated;" +
                            "Identity=other;" + 
                            "User=newUser"
                        )
                    }
                )  
... 
(dialogs, events, ...)


Thanks

**Comment by onefreddy** [comment]
hi.
@Giangi72 I think Oleg does not have time to look at the pieces, it is convenient for him to quickly launch your entire project and check
@oleg-shilo I think I was wrong, I just checked the xml *.g.wxs files v1.15.0 and v1.14.8 is identical. probably the problem does not depend on the version, rather it started for me after replacing constants to [...] variables.

**Comment by oleg-shilo** [comment]
@onefreddy thank you for such an accurate clarification. :)

Indeed I am not spoiled on on time but also, in some cases it is close to impossible for me to identify the problem by simply analyzing the problem description. It is more effective is to compare the actual XML output to the desired one. Then then see why XML generation is changed.

**Comment by Giangi72** [comment]
Hi,
ok I have found a simple prject having the issue.
Look at this code. Uninstall works correctly. Please focus on WebSite and WebAppPool names
`

        static void Main(string[] args)
        {
            ManagedProject project = new ManagedProject("OlegTest",
                new InstallDir(new Id("TestOleg"), "c:\\TestOleg",
                    new User(new Id("newUser"), "[USERNAME]", "[DOMAIN]")
                    {
                        Password = "[PASSWORD]",
                        CreateUser = false
                    },
                    new IISVirtualDir
                    {
                        Name = "Server",
                        AppName = "Server",
                        WebSite = new WebSite("SiteName2", "*:20002") { InstallWebSite = true, },
                        WebAppPool = new WebAppPool("AppPoolName2",
                            "ManagedRuntimeVersion=v4.0;" +
                            "ManagedPipelineMode=Integrated;" +
                            "Identity=other;" +
                            "User=newUser"
                        )
                    }
                )
            );
           
            project.ManagedUI = new ManagedUI();
            project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
                                            .Add(Dialogs.Progress)
                                            .Add(Dialogs.Exit);
            project.ManagedUI.ModifyDialogs.Add(Dialogs.MaintenanceType)
                                           .Add(Dialogs.Features)
                                           .Add(Dialogs.Progress)
                                           .Add(Dialogs.Exit);
            
            project.Load += Msi_Load; 

            project.BuildMsi();
        }

        static void Msi_Load(SetupEventArgs e)
        {
            if (!e.IsUninstalling)
            {
                e.Session["SITENAME"] = "SiteName2";
                e.Session["HTTPPORT"] = "20002";

                e.Session["APPPOOLNAME"] = "AppPoolName2";
                e.Session["PASSWORD"] = "pwd";

                e.Session["DOMAIN"] = "domain";
                e.Session["USERNAME"] = "name";
            }
        }`
and generated .g.wxs file is
`<?xml version="1.0" encoding="utf-8"?>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="25c59aa8-f159-41db-b244-ad162e680f9a" Name="OlegTest" Language="1033" Codepage="Windows-1252" Version="1.0.0.0" UpgradeCode="25c59aa8-f159-41db-b244-ad161e680f99" Manufacturer="gdelia">
    <Package InstallerVersion="200" Compressed="yes" SummaryCodepage="Windows-1252" Languages="1033" />
    <Media Id="1" Cabinet="OlegTest.cab" EmbedCab="yes" />

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="TestOleg" Name="ABSOLUTEPATH">

        <Component Id="Component.TestOleg.VirtDir" Guid="25c59aa8-f159-41db-b244-ad16e4b26560" KeyPath="yes">
          <WebVirtualDir Id="VirtDir" Alias="Server" Directory="TestOleg" WebSite="WebSite" xmlns="http://schemas.microsoft.com/wix/IIsExtension">
            <WebApplication Id="ServerWebApplication" Name="Server" WebAppPool="Server_AppPool" />
          </WebVirtualDir>

          <WebSite Id="WebSite" Description="SiteName2" Directory="TestOleg" xmlns="http://schemas.microsoft.com/wix/IIsExtension">
            <WebAddress Id="WebSite_Address1" IP="*" Port="20002" />
          </WebSite>

          <WebAppPool Id="Server_AppPool" Name="AppPoolName2" ManagedRuntimeVersion="v4.0" ManagedPipelineMode="Integrated" Identity="other" User="newUser" xmlns="http://schemas.microsoft.com/wix/IIsExtension" />

          <CreateFolder />
          <RemoveFolder Id="TestOleg" On="uninstall" />
        </Component>

        <Component Id="newUser" Guid="25c59aa8-f159-41db-b244-ad1616644b49" KeyPath="yes">
          <User Id="newUser" Name="[USERNAME]" CreateUser="no" Domain="[DOMAIN]" Password="[PASSWORD]" xmlns="http://schemas.microsoft.com/wix/UtilExtension" />

          <CreateFolder />
        </Component>

      </Directory>

      <Component Id="TARGETDIR" Guid="25c59aa8-f159-41db-b244-ad1691387f0c" KeyPath="yes">
        <RemoveFolder Id="TARGETDIR" On="uninstall" />
      </Component>

    </Directory>

    <UI />

    <UI>
      <EmbeddedUI Id="WixSharp_EmbeddedUI_Asm" SourceFile="WixSharp.UI.CA.dll" />
    </UI>

    <CustomAction Id="WixSharp_InitRuntime_Action" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="WixSharp_InitRuntime_Action" Return="check" Execute="immediate" />
    <CustomAction Id="Set_CancelRequestHandler_Props" Property="CancelRequestHandler" Value="UpgradeCode=[UpgradeCode];INSTALLDIR=[INSTALLDIR];UILevel=[UILevel];ProductCode=[ProductCode];ADDLOCAL=[ADDLOCAL];ADDFEATURES=[ADDFEATURES]" />
    <CustomAction Id="CancelRequestHandler" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="CancelRequestHandler" Return="check" Impersonate="no" Execute="deferred" />
    <CustomAction Id="WixSharp_Load_Action" BinaryKey="WixSharp_InitRuntime_Action_File" DllEntry="WixSharp_Load_Action" Return="check" Execute="immediate" />
    <CustomAction Id="Set_DirAbsolutePath" Property="TestOleg" Value="c:\TestOleg" />

    <Binary Id="WixSharp_InitRuntime_Action_File" SourceFile="WixSharp.CA.dll" />
    <Binary Id="WixSharp_UIText" SourceFile="OlegTest.wxl" />
    <Binary Id="WixSharp_LicenceFile" SourceFile="OlegTest.licence.rtf" />
    <Binary Id="WixUI_Bmp_Dialog" SourceFile="OlegTest.dialog_bmp.png" />
    <Binary Id="WixUI_Bmp_Banner" SourceFile="OlegTest.dialog_banner.png" />

    <UIRef Id="WixUI_ErrorProgressText" />

    <Property Id="WixSharp_UI_INSTALLDIR" Value="INSTALLDIR" />
    <Property Id="UAC_REVEALER_ENABLED" Value="true" />
    <Property Id="UAC_WARNING" Value="Please wait for UAC prompt to appear.&#xD;&#xA;&#xD;&#xA;If it appears minimized then activate it from the taskbar." />
    <Property Id="WixSharp_InstallDialogs" Value="WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.WelcomeDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ProgressDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ExitDialog" />
    <Property Id="WixSharp_ModifyDialogs" Value="WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.MaintenanceTypeDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.FeaturesDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ProgressDialog&#xA;WixSharp.UI, Version=1.15.0.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2|WixSharp.UI.Forms.ExitDialog" />
    <Property Id="WixSharp_Load_Handlers" Value="OlegTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|OlegTest.Program|Msi_Load" />
    <Property Id="INSTALLDIR_ABSOLUTEPATH" Value="c:\TestOleg" />

    <Feature Id="Complete" Title="Complete" Absent="allow" Level="1">
      <ComponentRef Id="newUser" />
      <ComponentRef Id="Component.TestOleg.VirtDir" />
      <ComponentRef Id="TARGETDIR" />
    </Feature>

    <InstallExecuteSequence>
      <Custom Action="WixSharp_InitRuntime_Action" Before="AppSearch"> (1) </Custom>
      <Custom Action="Set_CancelRequestHandler_Props" Before="InstallFinalize" />
      <Custom Action="CancelRequestHandler" After="Set_CancelRequestHandler_Props"> (NOT (REMOVE="ALL")) </Custom>
      <Custom Action="WixSharp_Load_Action" Before="AppSearch">1</Custom>
      <Custom Action="Set_DirAbsolutePath" Before="AppSearch">(NOT Installed) AND (UILevel &lt; 5) AND (TestOleg = ABSOLUTEPATH)</Custom>
    </InstallExecuteSequence>

    <InstallUISequence>
      <Custom Action="Set_DirAbsolutePath" Before="AppSearch">(NOT Installed) AND (UILevel = 5) AND (TestOleg = ABSOLUTEPATH)</Custom>
    </InstallUISequence>

  </Product>
</Wix>`

Now replace the 2 names, so the rows
```
                        WebSite = new WebSite("SiteName2", "*:20002") { InstallWebSite = true, },
                        WebAppPool = new WebAppPool("AppPoolName2",
```

became
```
                        WebSite = new WebSite("[SITENAME]", "*:20002") { InstallWebSite = true, },
                        WebAppPool = new WebAppPool("APPPOOLNAME]",
```
The web site and application pool are not deleted anymore during uninstall.
In wxs file the only differences are the guids (obviously) and 
```
OK
          <WebSite Id="WebSite" Description="SiteName2" Directory="TestOleg" xmlns="http://schemas.microsoft.com/wix/IIsExtension">
...
         <WebAppPool Id="Server_AppPool" Name="AppPoolName2" ManagedRuntimeVersion="v4.0" ManagedPipelineMode="Integrated" Identity="other" User="newUser" xmlns="http://schemas.microsoft.com/wix/IIsExtension" />

KO
          <WebSite Id="WebSite" Description="[SITENAME]" Directory="TestOleg" xmlns="http://schemas.microsoft.com/wix/IIsExtension">
...
         <WebAppPool Id="Server_AppPool" Name="[APPPOOLNAME]" ManagedRuntimeVersion="v4.0" ManagedPipelineMode="Integrated" Identity="other" User="newUser" xmlns="http://schemas.microsoft.com/wix/IIsExtension" />

```


I also tested fixing web site name and using a variable for application pool = the web site is deleted and application pool is not.

**Comment by oleg-shilo** [comment]
Excellent.
will have a look.
txs

**Comment by Giangi72** [comment]
Many thanks to you

**Comment by Giangi72** [comment]
Sorry to ping but are there any news?

Not related to this issue but Happy Christmas :-)

**Comment by oleg-shilo** [comment]
Thank you @Giangi72. Merry Christmas to you too.

Honestly, I was not able to look at the problem yet. I am still mainly spending time in CS-Script (another project of mine) preparing .NET 5 port.

But I just had a look at you report and did some reading on WiX and these are my findings/conclusions/questions:

`1`

> If I can give a suggest this should be a future development: it should be something like:
`WebSite = new WebSite("[SiteName]", "*:[HTTPPort]") { InstallWebSite = true, ApplicationPool = new WebAppPool(...) }`
or something like that.

I would expect that you don need to have this API as the `WebSite` and `WebAppPool` are associated via parent VirtualDir. Though since you are removing the virt dir in the build event then of course you would need another way to do the association.
Thus my questions are: why do you need to remove virt dir? Is it a valid use case? And why in your latest samples you still use virt dir? Was it wrong when you tried to remove it?

`2`

 Replacing hardcodded element  attributes with ref to the property (e.g. `[SiteName]`) is always tricky as there is no warranty that the corresponding XML attribute supports properties. And WiX did not indicate you can do the property referencing: https://wixtoolset.org/documentation/manual/v3/xsd/iis/webapppool.html
 
 However, the WiX compilation raised no error so may be it is OK. Not sure. 
 
The fact that you were able to install suggests that probably it is OK to use property refs. But... the typical story is that the all properties and their resolved effective (runtime) values are captured and persisted on installation and later used during uninstall. Thus WixSharp does not control it any more and I am not sure WiX does.

I have no solution to your problem but if it does exist then it will probably be in the area of the relationship between WiX entities `WebSite`, `WebAppPool` and `WebVirtualDir`. So WiX forums may have it covered/discussed

**Comment by Giangi72** [comment]
Hi @oleg-shilo,

1) The simply reply to the questions "_why do you need to remove virt dir? Is it a valid use case?_" is: This was the request :-(
I need to create one installer that creates Web site and application pool and two others that create a web application each. I don't know all details.
About "_And why in your latest samples you still use virt dir?_", what do you mean? Is any other way to do what I need?
And "_Was it wrong when you tried to remove it?_", no everything works fine doing that and then using the WixSourceGenerated event.

2) Sigh, I hoped it was a simply bug and not something like that. I'll try to write in wix forum. Thanks

Thanks again for all your support

**Comment by oleg-shilo** [comment]
> About "And why in your latest samples you still use virt dir?", what do you mean? Is any other way to do what I need?

Sorry. All good. I got confused with the samples.

As for ability to bypass the VirtDir parent when expressing the relationship between `ApplicationPool` and `WebSite` it is indeed a bit unusual case and as such it is to be supported via `WixSourceGenerated` event. 

However I prefer to keep this request open and if it gets upvoted I can implement this feature. I suggest you ad a feature request and we will deal with it if it gets the numbers :)

>...I'll try to write in wix forum.

Good luck. let me know if/when you find your answer and we can consider integrating it back to WixSharp.

**Comment by Giangi72** [comment]
Hi, I created the
https://github.com/wixtoolset/issues/issues/6310
I hope to have help about it, otherwise I thought about adding registry keys in order to save the names and do a manual deleting of WebSite ad ApplicationPool. Very rude and ugly but ...

Additionally, is any way to read the installation folder during uninstall? And which is the right event to do that? 
I mean 
1) read the registry keys and delete IIS items 
2) read installation folder (it seems to be always null)

Thanks

**Comment by oleg-shilo** [comment]
Have a look at "Setup Events" sample. It reads and shows all setup information before/during and after install. Check it. I think it does what you need.

**Comment by Giangi72** [comment]
Many Thanks

**Comment by Giangi72** [comment]
The answer is

The windows installer does not store property information during runs.
https://robmensching.com/blog/posts/2010/5/2/the-wix-toolsets-remember-property-pattern/

Sigh
Many thanks for your help
