### ISSUE TITLE
Not able to detect .net framework 4.8 with bundle wix

### ISSUE THREAD

**Issue by radz1** [oleg-shilo/wixsharp#955]
I need to detect .net framework 4.8 which is a prerequisite for my software. I am using 3.11 toolset, I have downloaded netfx48 from here [link ](https://github.com/wixtoolset/wix3/blob/a80818accbf6ee5681fa01bb1da538c7ae5a9b09/src/ext/NetFxExtension/wixlib/NetFx48.wxs) . 

I have added NetFx48.wxs in my project and also added reference of WinNetFxExtension.

After I have update bundle.wxs file with below code,
```
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
     xmlns:bal="http://schemas.microsoft.com/wix/BalExtension"
     xmlns:util="http://schemas.microsoft.com/wix/UtilExtension"
     xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension">
<Bundle Name="software" Version="1.4.0.0" Manufacturer="xyz" UpgradeCode="" IconSourceFile="Assets\dd.ico">     
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense">
      <bal:WixStandardBootstrapperApplication
        xmlns:bal="http://schemas.microsoft.com/wix/BalExtension"
        LicenseFile="Assets\license.rtf"  LogoFile="Assets\dd.png" ThemeFile="Resources\RtfTheme.xml" LocalizationFile="Resources\RtfTheme.wxl"/>  
        
    </BootstrapperApplicationRef>
<netfx:PackageGroupRef Id="NetFx48Web"/>
    <netfx:PropertyRef Id="WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED"/>
    <bal:Condition Message='This application requires .NET Framework 4.8.'>
      <![CDATA[Installed OR WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED]]>
    </bal:Condition>  
</Bundle >
</Wix >
```
But it evaluates false for the condition, event if .net framework is installed.
Is this the correct way to use. Please suggest if i am missing anything

**Comment by Torchok19081986** [comment]
hallo, i downloaded bundle net framework 4.8 wxs file from github for wix toolset. my description looks different. 
<?xml version="1.0" encoding="utf-8"?>


<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">

  

  <?define NetFx48MinRelease = 528040 ?>
  <?define NetFx48WebLink = https://go.microsoft.com/fwlink/?LinkId=2085155 ?>
  <?define NetFx48RedistLink = https://go.microsoft.com/fwlink/?LinkId=2088631 ?>
  <?define NetFx48EulaLink = https://referencesource.microsoft.com/license.html ?>

  <Fragment>
    <PropertyRef Id="WIXNETFX4RELEASEINSTALLED" />
    <Property Id="WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED" Secure="yes" />
    <SetProperty Id="WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED" Value="1" After="AppSearch">
      WIXNETFX4RELEASEINSTALLED >= "#$(var.NetFx48MinRelease)"
    </SetProperty>
  </Fragment>

  <Fragment>
    <util:RegistrySearchRef Id="NETFRAMEWORK45"/>

    <WixVariable Id="WixMbaPrereqPackageId" Value="NetFx48Web" />
    <WixVariable Id="WixMbaPrereqLicenseUrl" Value="$(var.NetFx48EulaLink)" Overridable="yes" />
    <WixVariable Id="NetFx48WebDetectCondition" Value="NETFRAMEWORK45 &gt;= $(var.NetFx48MinRelease)" Overridable="yes" />
    <WixVariable Id="NetFx48WebInstallCondition" Value="" Overridable="yes" />
    <WixVariable Id="NetFx48WebPackageDirectory" Value="redist\" Overridable="yes" />

    <PackageGroup Id="NetFx48Web">
      <ExePackage
          InstallCommand="/q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx48WebLog].html&quot;"
          RepairCommand="/q /norestart /repair /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx48WebLog].html&quot;"
          UninstallCommand="/uninstall /q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx48WebLog].html&quot;"
          PerMachine="yes"
          DetectCondition="!(wix.NetFx48WebDetectCondition)"
          InstallCondition="!(wix.NetFx48WebInstallCondition)"
          Id="NetFx48Web"
          Vital="yes"
          Permanent="yes"
          Protocol="netfx4"
          DownloadUrl="$(var.NetFx48WebLink)"
          LogPathVariable="NetFx48WebLog"
          Compressed="no"
          Name="!(wix.NetFx48WebPackageDirectory)ndp48-web.exe">
        <RemotePayload 
          CertificatePublicKey="D17AFCE951979605250FAEBAFA7AE974899AED22" 
          CertificateThumbprint="C82273A065EC470FB1EBDE846A91E6FFB29E9C12" 
          Description="Microsoft .NET Framework 4.8 Setup" 
          Hash="5A84A8E612E270E27D0061D58DB6B470153BE1F9" 
          ProductName="Microsoft .NET Framework 4.8" 
          Size="1479400" 
          Version="4.8.3928.0" />
      </ExePackage>
    </PackageGroup>
  </Fragment>

  <Fragment>
    <util:RegistrySearchRef Id="NETFRAMEWORK45"/>

    <WixVariable Id="WixMbaPrereqPackageId" Value="NetFx48Redist" />
    <WixVariable Id="WixMbaPrereqLicenseUrl" Value="$(var.NetFx48EulaLink)" Overridable="yes" />
    <WixVariable Id="NetFx48RedistDetectCondition" Value="NETFRAMEWORK45 &gt;= $(var.NetFx48MinRelease)" Overridable="yes" />
    <WixVariable Id="NetFx48RedistInstallCondition" Value="" Overridable="yes" />
    <WixVariable Id="NetFx48RedistPackageDirectory" Value="redist\" Overridable="yes" />

    <PackageGroup Id="NetFx48Redist">
      <ExePackage
          InstallCommand="/q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx48RedistLog].html&quot;"
          RepairCommand="/q /norestart /repair /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx48RedistLog].html&quot;"
          UninstallCommand="/uninstall /q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx48RedistLog].html&quot;"
          PerMachine="yes"
          DetectCondition="!(wix.NetFx48RedistDetectCondition)"
          InstallCondition="!(wix.NetFx48RedistInstallCondition)"
          Id="NetFx48Redist"
          Vital="yes"
          Permanent="yes"
          Protocol="netfx4"
          DownloadUrl="$(var.NetFx48RedistLink)"
          LogPathVariable="NetFx48RedistLog"
          Compressed="no"
          Name="!(wix.NetFx48RedistPackageDirectory)ndp48-x86-x64-allos-enu.exe">
        <RemotePayload
          CertificatePublicKey="D17AFCE951979605250FAEBAFA7AE974899AED22" 
          CertificateThumbprint="C82273A065EC470FB1EBDE846A91E6FFB29E9C12" 
          Description="Microsoft .NET Framework 4.8 Setup" 
          Hash="8DD233698D5EB4609B86C2AC917279FE39E0EF4C" 
          ProductName="Microsoft .NET Framework 4.8" 
          Size="117380440" 
          Version="4.8.3928.0" />
      </ExePackage>
    </PackageGroup>
  </Fragment>
</Wix>

**Comment by snechaev** [comment]
You can also try to use built-in Wix# condition for this task
https://github.com/oleg-shilo/wixsharp/blob/d9c8f5b4437c63f83b6d6c8cf577ec2289758b52/Source/src/WixSharp/Condition.cs#L287
