### ISSUE TITLE
Changing language of ManagedUI

### ISSUE THREAD

**Issue by AndreasFetzer** [oleg-shilo/wixsharp#957]
Hi,

I want to build two installers, one in German and one in English. I do not need to use the `BuildMultilanguageMsi` function. I am fine with executing my project twice, one with `project.Language = "de-de"` and the other time with `project.Language = "en-US"`

However the problem, is that the UI keeps being displayed in english, no matter which project language I set but when I look into the ActionTexts, I see everything translated in German.

![image](https://user-images.githubusercontent.com/1195891/102472548-adab9380-4056-11eb-8ef5-a5ac541bdf22.png)

My problem seems to be similar to #828. But as far as I understood, it should be possible to build ManagedUI for another language by simply setting the project's language.

Here is the code I am using:

```csharp
_project = new ManagedProject(projectName);

            // Setting information about project
            _project.GUID = projectId;
            _project.Version = new Version(GetProductVersion());
            _project.ControlPanelInfo.Manufacturer = GetManufacturer();

            // Defining upgrade strategy
            // => Basically tells MSI: "Upgrade if the installed version is older"
            _project.MajorUpgrade = MajorUpgrade.Default;

            // Setting up projects root directory
            _projectRootDir = new Dir("...");
            _project.AddDir(_projectRootDir);
            _project.SourceBaseDir = GetCurrentBinaryDir();
            _project.OutDir = GetCurrentBinaryDir();
            _project.BackgroundImage = @"assets\logos\background.bmp";
            _project.BannerImage = @"assets\logos\banner.bmp";
            _project.Language = "de-de";
            _project.Encoding = System.Text.Encoding.UTF8;


            // Setting up installer UI dialogs
            _project.ManagedUI = new ManagedUI();
            _project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                            .Add<LicenceDialog>()
                                            .Add<InstallDirDialog>()
                                            .Add<FeaturesDialog>()
                                            .Add<ProgressDialog>()
                                            .Add<ExitDialog>();

            _project.ManagedUI.ModifyDialogs.Add<MaintenanceTypeDialog>()
                                           .Add<FeaturesDialog>()
                                           .Add<ProgressDialog>()
                                           .Add<ExitDialog>();

            switch (languageCode)
            {
                case "de-de":
                    _project.LicenceFile = @"assets\license\DE.rtf";
                    _project.OutFileName = $"{projectName}-{GetInformationalProductVersion()}-de";
                    break;
                case "en-us":
                    _project.LicenceFile = @"assets\license\EN.rtf";
                    _project.OutFileName = $"{projectName}-{GetInformationalProductVersion()}-en";
                    break;
                default:
                    _project.LicenceFile = @"assets\license\DE.rtf";
                    _project.OutFileName = $"{projectName}-{GetInformationalProductVersion()}-de";
                    break;
            }

            /** Adding features and customAction
            * ...
            */
            _project.BuildMsi();
``` 

Am I doing something wrong? Do I need the [workaround ](https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/MultiLanguageUI/setup.cs) descriped in #828?

I am using the latest nuget packages 1.15

**Comment by AndreasFetzer** [comment]
Ok, when I add the localization file (e.g. from this [example](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/Managed%20Setup/MultiLanguageUI) ) it works but then some of the texts are not displayed correctly, e.g. 

![image](https://user-images.githubusercontent.com/1195891/102481440-ff0d5000-4061-11eb-9c02-83091a2a4395.png)

so I have to add some line breaks.

I am still wondering if this is the correct way to get the UI in a different language or if there is a simpler way.

**Comment by oleg-shilo** [comment]
In general, localization is a difficult task to be accomplished in such a generic way so all use-cases (languages) are supported equally well. Particularly with scaling unfriendly UI frameworks like WinForms (your case).

So I suggest that instead of using default managed dialogs you actually customize them to suit better your specific language.

Thus you can recreate your project from "WixSharp - Custom UI" VS template and then you will have in your project all dialogs integrated as source code. So you simply update their layout as you wish. IE make labels bigger

**Comment by AndreasFetzer** [comment]
Hi Oleg,

thanks a lot for your fast reply and your hint about the Custom UI template. For now it was sufficient to modify the texts in the german wxl file ( it have been only two places to modify).

My main concern was that simply changing the project language to "de-DE" did not work. It seems that I simply missed setting the german wxl file.
