### ISSUE TITLE
Alter Name attribute on Directory tag for ProgramFilesFolder

### ISSUE THREAD

**Issue by chrisbbe** [oleg-shilo/wixsharp#960]
Hi,

Due to legacy reasons, I'm forced to give the Directory tag for ProgramFilesFolder an alternative name. After some time crawling the source code, I'm still not sure how to achieve that.

Unfortunately, there is some legacy code that I can't change which depends on the directory **PFiles** being present at the root level after extracting the MSI with the _**msiexec.exe**_ tool. 

I have tried to specify the **_Id_** argument of **_Dir_** explicitly without luck, anyhow method **_GetTopLevelPermantDir(XElement product, bool is64)_** seems to overwrite any **_Id_** specified.

My goal is to change the **Name** attribute of tag with **Id** **_ProgramFilesFolder_**

````xml
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
        <Directory Id="ProgramFilesFolder.MyProduct" Name="MyProduct">
          <Directory Id="INSTALLDIR" Name="Tool">
...
````

**to**

````xml
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="PFiles">
        <Directory Id="ProgramFilesFolder.MyProduct" Name="MyProduct">
          <Directory Id="INSTALLDIR" Name="Tool">
````

**Any thoughts on how to achieve this?**

**Comment by oleg-shilo** [comment]
Achieving it is rather easy:

```C#
var project1 =
    new Project("MyProduct",
        new Dir(new Id("ProgramFilesFolder"), "PFiles",
            new Dir(new Id("ProgramFilesFolder.MyProduct"), "MyProduct",
                new Dir(new Id("INSTALLDIR"), "Tool",
                . . .
``` 

But if the produces msi is going to do what you expect it to do is another story :)
