### ISSUE TITLE
Upgrades howto

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#964]
Hi,
I was just starting to test the upgrade path but I do not got any success yet. As far as I understood the magic should come from using the same UpgradeCode and different ProductIds. So a higher version should upgrade the package.

As this was NOT working in actual setup I just created a small testcase. Just creating a managed setup with the wizard. 
So I created one setup with:

project.ManagedUI = Default;
project.GUID = new Guid(...);
project.version = new Version(1,1,100);

then I created a new Setup with just changing the version to:
project.version = new Version(1,2,101);

Now I was assuming that installing first 1.1.100 and then directly after this 1.2.101 that the second one should give me an "upgrade" option.
Anyway I can only do a second installation but I am not getting a the procedure but I am ending up with both versions to be installed.

When I check with SuperOrca, all data seems to be ok. So same upgradecode, different product-id and version. So where is the magic here ?

best

Carsten

**Comment by onefreddy** [comment]
https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples/MajorUpgrade
but detect IsUpgrading etc dont work currectly

**Comment by oleg-shilo** [comment]
Troubleshooting upgrading scenarios is always difficult. As far as I can tell you are doing everything right. You can also have a look in the emitted WXS for a clue.

I specifically created the working sample @onefreddy shared so users can at least have a benchmark.

@onefreddy is also right about `session.IsUpgrading`. It relies on the MSI property `UPGRADINGPRODUCTCODE` which happens not to be ever set by MSI runtime. I cannot comment on this as it is pure MSI business and WixSharp simply checks the property that supposed to hold the value. But... it does not. :(

Thus with it is up to user to check at the setup startup if the product is already installed. It can be done with `session.LookupInstalledVersion()`.

Saying that I have just did a few experiments with `LookupInstalledVersion` and decided to encapsulate it in the more reliable `session.IsUpgradingInstalledVersion()`, which is based on deterministic `AppSearch.GetProductVersionFromUpgradeCode`. 

And I have marked the `session.IsUpgrading` as deprecated.

The HotFix release is on the way: https://www.nuget.org/packages/WixSharp/1.16.1-HotFix.

You can now rely on new properties (highlighted in yellow):
![image](https://user-images.githubusercontent.com/16729806/107119984-fb1de180-68de-11eb-9a33-42f843fae0d0.png)

**Comment by hcarsten** [comment]
My Problem was and is that "former" solutions we had in use (e.g. Installshield) is presenting a different UI to the user when proceeding an Update but having "first time install". So you will basically have an UI saying "Welcome, this is an update" or "Welcome, this is the initial install". 
In fact you to learn that an update by default is just an uninstall of the old version and an install of the new version.

Just share what we finally have is the following:

```
project.MajorUpgradeStrategy = MajorUpgradeStrategy.Default;
project.MajorUpgradeStrategy.PreventDowngradingVersions.OnlyDetect = false;
project.MajorUpgradeStrategy.RemoveExistingProductAfter = Step.InstallInitialize;

 Compiler.WixSourceGenerated += doc => doc.Root
   .Select("Product/Upgrade/UpgradeVersion")
   .AddAttributes("MigrateFeatures=yes");
```

Another important point is to switching your versioning to a 3-parts version no; instead of the 4-parts Visual Studio does by default.

**Comment by oleg-shilo** [comment]
> ... "former" solutions ... 

Your scenario seems to be possible to implement with very little effort. 
In the Welcome dialog simply check `session.LookupInstalledVersion()` and and update the gritting accordingly. The Welcome dialog is loaded before the old version is uninstalled so you will be able accurately detect the old installation.
 
> ...3-parts version...

Yes, while you can have 4-parts version, MSI only recognizes first 3-parts. It's an old dog that doesn't know new tricks :)
    
> ... MigrateFeatures ...

Do you think it is something that should be enabled by default?

**Comment by hcarsten** [comment]
Hi Oleg,
MigrateFeatures is pretty important, because if not "patched" into the Wix-XML at the end, you have all the detected but nothing will happen. I think I picked this for the samples but tooks a while to find out that this was the missing puzzle piece :)

So maybe you can promote this to a property and default it to yes/true ?

best

Carsten

**Comment by oleg-shilo** [comment]
Great, I will implement it then. Txs
