### ISSUE TITLE
WildCardDedup doesn't work with DirFiles

### ISSUE THREAD

**Issue by gregvis** [oleg-shilo/wixsharp#966]
maybe i'm not understanding how to use WildCardDedup properly. Here is my scenario

I want to install a forms app and a windows service like so (the 2 projects share many of the same dll files):
```
var project = new ManagedProject("myproject",
                           new Dir(@"%ProgramFiles%\Company\MyProgram",
                                     new DirFiles($@"..\WindowsFormApp\bin\Debug\*.*"),
                                     new DirFiles($@"..\WindowsService\bin\Debug\*.*")
project.WildCardDedup = Project.UniqueFileNameDedup;
project.ResolveWildCards();

project.BuildMsi();
```

I just want the files from the output directories, and not the subdirectories. That is why I am using DirFiles. It seems that WildCardDedup is never called when using DirFiles.  Am I not using this correctly?

**Comment by oleg-shilo** [comment]
The usual cause of the problems of this sort is unexpected _current directory_.
Just to check this theory path an **absolute path** in the `DirFiles` constructor and see if it fixes the problem.

If it does then you will need to ensure the relative path is expressed correctly.

**Comment by gregvis** [comment]
putting in the absolute path in DirFiles didn't change anything. WildCardDedup function is never called. 

Does it work for you?

**Comment by oleg-shilo** [comment]
It does at least for the "ReleaseFolder" sample:

![image](https://user-images.githubusercontent.com/16729806/107612905-60852000-6c9b-11eb-98d6-1a75480ddefd.png)

**Comment by oleg-shilo** [comment]
Oh, I just realized... You are not using `Files` but `DirFiles`. Meaning that you are aggregating the files from a single directory so you cannot possibly have a file duplication (file system takes care of that). So WildCardDedup  is not called.

**Comment by oleg-shilo** [comment]
If you are using a single directory wild card `DirFiles` you are better off to do the de-duplication after all files/dirs are resolved.
Or even aggregate the files by yourself. After all `DirFiles` does not do anything particularly clever. You can achieve the same like this:

```C#
var project = new ManagedProject("myproject",
                  new Dir(@"%ProgramFiles%\Company\MyProgram",
                      . . . 
    

var artifacts =  System.IO.Directory.GetFiles(@"..\WindowsFormApp\bin\Debug\", "*.*")
                       .Concat(System.IO.Directory.GetFiles(@"..\WindowsService\bin\Debug\", "*.*"));

Dir installDir = project.FindDir(@"%ProgramFiles%\Company\MyProgram");
foreach (string file in artifacts)
{
    // do your dedup here
    installDir.AddFile(new File(file));
}
```

**Comment by oleg-shilo** [comment]
Or you can truly exclude duplicates. Something like that:

```C#
var project = new ManagedProject("myproject",
                           new Dir(@"%ProgramFiles%\Company\MyProgram",
                                     new DirFiles($@"..\WindowsFormApp\bin\Debug\*.*"),
                                     new DirFiles($@"..\WindowsService\bin\Debug\*.*")
project.ResolveWildCards();

Dir installDir = project.FindDir(@"%ProgramFiles%\Company\MyProgram");

installDir.Files = installDir.Files.SelectOnlyFilesYouNeed().ToArray();  

project.BuildMsi();
```  

That's the beauty of the full scale programming language. You don't need to struggle with the declarative nature of XML :)

**Comment by gregvis** [comment]
Thanks Oleg, 

You've given me a method to solve the issue.
