### ISSUE TITLE
Writing on console during setup execution

### ISSUE THREAD

**Issue by Giangi72** [oleg-shilo/wixsharp#967]
Hi everyone,
maybe I'm completely drunk but I'm not able to write on console during setup execution.
My setup can be executed interactively or by command line command.
If I execute it by command line I hadded an help command in order to show the parameters
msiexec /i "mySetup.msi" HELP="?"
(additionally any idea on how to read the help command without specify **_="?"_**  ?)

On UIInitialized event I read the parameters and, eventually, show a MessageBox with help OK
Now I want to get rid of MessageBox and write on console but the usual Console.Write didn't work
Any idea?
Many thanks

**Comment by oleg-shilo** [comment]
You can try to use:
```C#
[DllImport("kernel32.dll", SetLastError = true)]
[return: MarshalAs(UnmanagedType.Bool)]
static extern bool AllocConsole();
```
and AtatchConsole.....

Google will give you more details

**Comment by Giangi72** [comment]
Hi Oleg, 
I used
```
        [DllImport("kernel32.dll", SetLastError = true)]
        static extern bool AllocConsole();

        [DllImport("kernel32.dll", SetLastError = true)]
        static extern bool AttachConsole(uint dwProcessId);

        const uint ATTACH_PARENT_PROCESS = 0x0ffffffff;
        const int ERROR_ACCESS_DENIED = 5;
```
and then
```
               if (!AttachConsole(ATTACH_PARENT_PROCESS) && Marshal.GetLastWin32Error() == ERROR_ACCESS_DENIED)
                {
                    // A console was not allocated, so we need to make one.
                    AllocConsole();
                }
                Console.WriteLine("message");
                Console.ReadKey(true);
```
This always creates a new console and writes the message but the old console window is never used, I suppose because the parent process is not the console but the msiexec.
Any idea?
Thanks

**Comment by oleg-shilo** [comment]
I think in this case it is trying to attach it to the parent process, which is not your console but a windows (not console) app _msiexec.exe_. Thus if somehow you can discover from your routine the logical parent (your console then you can attach).

One possibility is to enumerate from the desktop windows and pick one that either has user input or the one that has console created. And then attach to it.

**Comment by Giangi72** [comment]
Ok, many thanks
