### ISSUE TITLE
Condition() is running and FeatureCondition() NOT

### ISSUE THREAD

**Issue by fendres82** [oleg-shilo/wixsharp#968]
Hi,

i have problems getting the featureCondition running.
I have some Condition like this  `Condition = new Condition("INSTALLCLIENTONLY <> 1")` which is working.

But my following FeatureCondition is not working:

![2021-02-04 15_17_37-FCIInstallerBundle - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/9702029/106906743-c43ca580-66fd-11eb-93f1-f1162e5d6134.png)

I also tried the spelling of the FeatureCondition() like the Condition().

Any suggestions?

**Comment by oleg-shilo** [comment]
Have a look at the produced WXS, it may give you a clue.

**Comment by fendres82** [comment]
hi,

managed it by creating a default feature and adding my two other feature to the default feature

`            featureDefault.Add(featureFCI);
            featureDefault.Add(featureFCIClient);`
