### ISSUE TITLE
Generate installer run time based on dynamic source.

### ISSUE THREAD

**Issue by shyamsohane** [oleg-shilo/wixsharp#969]
Hi Oleg,

I want to generate the msi based on dynamic source folder which will be known in the build server once final artifact generated. How can i make the source configurable , because msi generates at compile time only and source is configured already. 

Thanks,
Shyam Sohane

**Comment by oleg-shilo** [comment]
Have a look at ReleaseFolder sample: https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples

**Comment by shyamsohane** [comment]
Thanks Oleg for the quick help. Actually when I added nuget packages it added by default target to generate the msi at build time which I discovered in some time:(.  After removing those targets it just compiles the code and generate console app.exe which I am executing later in builder server to make msi.
