### ISSUE TITLE
Question: how to install bootstrapper exe silent

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#975]
Hallo, i want to install my bootstrapper exe with embeded msi silently. If there way to achieve that? Want to add parameters to exe like myexe /s or /silent or also -s and -silent. Many thanks for advice.

**Comment by geghamyan** [comment]
Burn supports the standard parameters:
_-q, -quiet, -s, -silent = silent install 
 -passive = progress bar only install 
 -norestart = suppress any restarts 
 -forcerestart = restart no matter what (I don't know why this is still  around) 
 -promptrestart = prompt if a restart is required (default) 
 -layout = create a local image of the bootstrapper (i.e. download files so  they can be burned to DVD) 
 -l, -log = log to a specific file (default is controled by bundle developer) 
 -uninstall = uninstall 
 -repair = repair (or install if not installed) 
 -package,-update = install (default if no -uninstall or -repair)_ 

https://stackoverflow.com/questions/44332496/comprehensive-list-of-command-line-flags-options-for-burn-bootstrapper-in-wix/44347702

**Comment by Torchok19081986** [comment]
Morning, many thanks for answer. after investiagation my output wxs file, i dont find command in output wxs file. command belongs to Msi / Exepackage, but i cant set command somehow. How can i do that?

**Comment by geghamyan** [comment]
Can you please give an example of what are you trying to achieve.

**Comment by Torchok19081986** [comment]
Morning, i want to silent update my product with exe installer silently. I found some workaround. fullinstaller happens by wix bootstapper.  Bootstrapper installs msi ,  i can generate msi with wixsharp and update my product from msiexec silently with parameters like in your post . All tests runs fine until now. All other things i can investigate in future problems.
