### ISSUE TITLE
How to modify some .config file after install?

### ISSUE THREAD

**Issue by RomanPlekhanov** [oleg-shilo/wixsharp#977]
Hello! I need to modify several files after install by values from install dialog. How can I do it? Thank you!

**Comment by oleg-shilo** [comment]
Have a look here: https://github.com/oleg-shilo/wixsharp/blob/a97b51e58d8713b84eb3be804dc1f9cc6748daa0/Source/src/WixSharp.Samples/Wix%23%20Samples/DeferredActions/setup.cs

**Comment by RomanPlekhanov** [comment]
I put the code in an event handler and it helped! Before that, the code was in a custom action and didn't work from there. It looks like I was incorrectly specifying the execution step for the custom action, so it didn't work. Thanks for the help! :)
