### ISSUE TITLE
Enhancement: Ability to setup service startup type in InstallService

### ISSUE THREAD

**Issue by xplicit** [oleg-shilo/wixsharp#979]
Wixsharp have ability to install service. But this method does not allow to change service startup type (manual|automatic|etc). Propose to add optional parameter which will allow to change startup type for the installed service.

https://github.com/oleg-shilo/wixsharp/blob/1392739ca863a105565cea6e0f0c298f3def4993/Source/src/WixSharp/CommonTasks.cs#L1599

**Comment by oleg-shilo** [comment]
Hm... this seemed to be a simple task but... when I look at CLI of `InstallUtil.exe` (used to install the service) it has no support for the startup type.

It's understandable as this util is a generic assembly entry point launcher that simply "asks" the assembly to install itself. And a self-aware service assembly decided what startup type to configure.

This means that `InstallService` cannot do the task you need it to do and you need to have an additional after-install step where you will configure your freshly installed service:

```C#
project.AfterInstall += e=>
{
    Process.Start("sc", "config <service name> start=<mode>");
};
```
