### ISSUE TITLE
Add different icon to shortcuts

### ISSUE THREAD

**Issue by sommmen** [oleg-shilo/wixsharp#981]
Hello,

First of all, I've been using WixSharp and am so fare quite happy with the product.
The samples and source code are quite comprehensible, my compliments.

I am creating some shortcuts like so;
``` csharp
                new Dir("%Desktop%",
                    new ExeFileShortcut(hmiBinariesFeature, machineProjectName, $"[INSTALLDIR]{machineProjectName}.exe", "")),
                new Dir("%Startup%",
                    new ExeFileShortcut(hmiBinariesFeature, machineProjectName, $"[INSTALLDIR]{machineProjectName}.exe", "")),
```

However i'd like to change the icon of these shortcuts.
Is this possible with Wix/Wix# ? Any ideas on how to approach this?
The ExeFileShortcut did not have any properties regarding the icon file.

Ultimately, I'd like something like this:
![image](https://user-images.githubusercontent.com/8641495/115034219-8a410a00-9ecb-11eb-8927-62b9765a5d14.png)

Where I call the exe with /Start or /Stop.

**Comment by Torchok19081986** [comment]
Morning, according to wix wiki there is Icon / Iconindex. 
https://wixtoolset.org/documentation/manual/v3/xsd/wix/shortcut.html
Just dont know , how to do it in Wix#. Maybe change generated wxs after event sourcegenerated ?

**Comment by sommmen** [comment]
> Morning, according to wix wiki there is Icon / Iconindex.
> https://wixtoolset.org/documentation/manual/v3/xsd/wix/shortcut.html
> Just dont know , how to do it in Wix#. Maybe change generated wxs after event sourcegenerated ?

Good morning, you've pointed me in the right way. Apperently the underlying base type of `ExeFileShortCut` was `Shortcut` which corresponds to the wix type you linked.

So it should be as simple as this;
`new ExeFileShortcut(machineProjectName, $"[INSTALLDIR]{machineProjectName}.exe", "") {IconFile = "..\\test.ico"})` Which i will now test.

**Comment by sommmen** [comment]
Unfortunately it seems that you cannot use icon resources from dlls that are on the target system.
For example `Shell32.dll` holds some embedded icon files but it does not seem possible with wix/wix# to use this.

I therefore extracted the desired icon files with a thirdparty app called IconViewer and then embedded those in the project.
That seems to work okay;
![image](https://user-images.githubusercontent.com/8641495/115208836-50efe080-a0fd-11eb-8075-de0c2af6a299.png)

``` csharp
new Dir("%Desktop%",
    new ExeFileShortcut(hmiBinariesFeature, machineProjectName, $"[INSTALLDIR]{machineProjectName}.exe", "")
    {
        IconFile = "..\\..\\Resources\\Start.ico"
    }),
```

I gues i could also embed the icon file in my exe and reference that instead, but oh well - this works.

**Comment by oleg-shilo** [comment]
You are absolutely right. WiX only supports icons that come from the same msi package that the shortcut is created from.

Technically speaking you can have your custom action at the end of install where you can simply update the icon in the shortcut file, but... I think your solution is pragmatic enough.
