### ISSUE TITLE
MSP Patch Packages and upgrading

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#982]
Hi Oleg,
in some of the files you wrote : "In the future releases the direct support for MspPackage element will be added." No idea from when the entry is.
Any idea if the support for MSP could be done ? In our scenarios we are installing also a Kernel Mode driver which will result to a restart in most of the cases. Anyway the driver it self is pretty much stable so updates adress in 99,9% of the new version only assemblies. So a Patch Package would definetly help.

Another point is the responsibility of an upgrade. As far I understood when I run an upgrade, is that both packages (the old one) and the new one will get invoked. So the new update will span an uninstall on the older package first and then continue with the installation. Is this correct ?

best

Carsten

**Comment by oleg-shilo** [comment]
I am coming back to WixSharp :)
so soon. Probably within a week or so.
The mentioning is in on of the sample files:
```C#
        // Add MspPackage manually (demo only).
        // In the future releases the direct support for MspPackage element will be added.
        // bootstrapper.WixSourceGenerated += (doc) => doc.FindSingle("Chain")
        //                                                .AddElement("MspPackage",
        //                                                            "SourceFile=Patch.msp; Slipstream=no");
```

>  Upgrade... Is this correct ?

Yes it is the case

**Comment by oleg-shilo** [comment]
Done: #982
Waiting for the release.

```C#
. . .
new MsiPackage(crtMsi)
{
    DisplayInternalUI = true,
    Visible = true,
    MsiProperties = "PACKAGE_PROPERTY=[BundleVariable]"
},
new MspPackage("Patch.msp")
{
    Slipstream = false
},
new MsiPackage(productMsi)
{
. . .
```
