### ISSUE TITLE
OPC component not detected by bootstrapper although it is installed

### ISSUE THREAD

**Issue by meidadraz** [oleg-shilo/wixsharp#983]
when running the bootstrapper with the OPC component already installed 
the bootstrapper does not detect it as installed and mark it for installation and run the msi

![image](https://user-images.githubusercontent.com/33197006/115138991-2425c580-a038-11eb-9443-f359761b21f7.png)

Log files:
[Kornit_Atlas_MAX_20210418003644.zip](https://github.com/oleg-shilo/wixsharp/files/6330762/Kornit_Atlas_MAX_20210418003644.zip)
[RemoveSentinelHasp_4-18-2021_12-38-41_AM_Sentinel Runtime_6.60.1.36770_Uninstall.log](https://github.com/oleg-shilo/wixsharp/files/6330763/RemoveSentinelHasp_4-18-2021_12-38-41_AM_Sentinel.Runtime_6.60.1.36770_Uninstall.log)

**Comment by oleg-shilo** [comment]
It's hard to comment based on no description of what you are trying to do. But...with Bootstrapper WixSharp provides an extremely thin layer API and practically exposes that raw WiX API to the developer. Thus if you are using standard stock BA then the cause and the solution resides in WiX land. If you are using Custom BA as in WixSharp samples then indeed the cause may be addressed within your source code -  `OnDetectPackageComplete` event handler.

**Comment by meidadraz** [comment]
Thank you @oleg-shilo  i opened this issue here by mistake, i had 2 github pages open in my browser and i placed the issue in the wrong github page. 
my other github is also WIX related. :-)
