### ISSUE TITLE
[Q] Running app after installing

### ISSUE THREAD

**Issue by sommmen** [oleg-shilo/wixsharp#984]
Hiya,

I am trying to run my app after installing, However i'm getting some errors when i add `LaunchApplicationFromExitDialog` from the all in one sample.
``` csharp
new LaunchApplicationFromExitDialog($"Component.{machineProjectName}.exe", "Launch app")
```

```
 : error LGHT0204: ICE20: Standard Dialog: 'FilesInUse' not found in Dialog table
 : error LGHT0204: ICE20: ErrorDialog Property not specified in Property table. Required property for determining the name of your ErrorDialog
 : error LGHT0204: ICE20: FatalError dialog/action not found in 'InstallUISequence' Sequence Table.
 : error LGHT0204: ICE20: FatalError dialog/action not found in 'AdminUISequence' Sequence Table.
 : error LGHT0204: ICE20: UserExit dialog/action not found in 'InstallUISequence' Sequence Table.
 : error LGHT0204: ICE20: UserExit dialog/action not found in 'AdminUISequence' Sequence Table.
 : error LGHT0204: ICE31: The 'DefaultUIFont' Property must be set to a valid TextStyle in the Property table.
```

I tried with the 'default' Ui and WixUI.FullMondo;

``` csharp
project.ManagedUI = ManagedUI.Default; //all standard UI dialogs

// Custom set of standard UI dialogs
project.ManagedUI = new ManagedUI();

project.ManagedUI.InstallDialogs.Add(Dialogs.Welcome)
    //.Add(Dialogs.Licence) // NOTE we can add a custom license file, but we don't really use licensing.
    .Add(Dialogs.SetupType)
    .Add(Dialogs.Features)
    .Add(Dialogs.InstallDir)
    .Add(Dialogs.Progress)
    .Add(Dialogs.Exit);

project.ManagedUI.ModifyDialogs.Add(Dialogs.MaintenanceType)
    .Add(Dialogs.Features)
    .Add(Dialogs.Progress)
    .Add(Dialogs.Exit);
```

And:

``` csharp
project.UI = WUI.WixUI_Mondo;
```

**Comment by sommmen** [comment]
I just noticed there's another sample that also has the 'Run app at the end' behaviour;
https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/RunAppAtTheEnd/setup.cs

So i'll gues i'll use that.

**Comment by oleg-shilo** [comment]
To be honest I am a big fan of _events_. 
```C#
var project = new ManagedProject("Setup",
                  new Dir(@"%ProgramFiles%\RunAppTest",
                      new File("readme.txt")),
                 new ManagedAction("MyAction"));

project.UI = WUI.WixUI_ProgressOnly;

project.AfterInstall += 
    e => Process.Start("Notepad.exe", e.InstallDir.PathCombine("readme.txt"));

project.BuildMsi();
```

**Comment by sommmen** [comment]
> To be honest I am a big fan of _events_.
> 
> ```cs
> var project = new ManagedProject("Setup",
>                   new Dir(@"%ProgramFiles%\RunAppTest",
>                       new File("readme.txt")),
>                  new ManagedAction("MyAction"));
> 
> project.UI = WUI.WixUI_ProgressOnly;
> 
> project.AfterInstall += 
>     e => Process.Start("Notepad.exe", e.InstallDir.PathCombine("readme.txt"));
> 
> project.BuildMsi();
> ```

Hi Oleg,

Yeah i saw some other samples where you were advocating that,
but i was going through the samples and i already created a large portion in CA's.

I've placed a comment to warn the next programmer to use events.
Anyhow I'll close this issue, i think i can find my way here.

Now that I have you, quick question:
I have a custom CA (I'll rewrite it to use events if you won't help me otherwise ;-) ) that runs a backup script,
This takes about a minute or so, so i'd like to show the script output to the user in the progress window.
I'm using the default UI.
I've read online you should be able to do this but it did not seem trivial,
So is this possible and could you point me in the right direction on how to update the progress text with custom messages?

**Comment by oleg-shilo** [comment]
I think it is in fact reasonably trivial. :)

I assume you run your custom action at the end of install bet before you progress to the ExitDialog.

So in the progress dialog you can place an additional progress bar that you will need to update periodically when you detect the progress in the script execution. 

Detecting technique will depend on the method you choose to communicate. IE you can open the server socke from the ProgressDialog and wait till client (your CustomAction/event) start reporting the progress. If Socket is not an option then you can use any IPC method (even well known folder with the progress file).

Why IPC? Because MSI executes all CA in a separate process(s). Yep, it's not that elegant :)
In the ExitBox source code of the Have a

**Comment by sommmen** [comment]
> I think it is in fact reasonably trivial. :)
> 
> I assume you run your custom action at the end of install bet before you progress to the ExitDialog.
> 
> So in the progress dialog you can place an additional progress bar that you will need to update periodically when you detect the progress in the script execution.
> 
> Detecting technique will depend on the method you choose to communicate. IE you can open the server socke from the ProgressDialog and wait till client (your CustomAction/event) start reporting the progress. If Socket is not an option then you can use any IPC method (even well known folder with the progress file).
> 
> Why IPC? Because MSI executes all CA in a separate process(s). Yep, it's not that elegant :)

I've got these actions:
``` csharp
Actions = new Action[]
                {
                    new ManagedAction(CustomActions.StoreConfigFiles, Return.check, When.Before, Step.InstallFiles, Condition.Always)
                        { Feature = hmiBinariesFeature },
                    new ManagedAction(CustomActions.MergeOldAndNewConfigFiles, Return.check, When.Before, Step.InstallFinalize, Condition.Always)
                        { Feature = hmiBinariesFeature},
                    new ManagedAction(CustomActions.RunFullBackupScript, Return.check, When.Before, Step.InstallFiles, Condition.Always)
                        { Feature = fullBackupFeature },
                    new ManagedAction(CustomActions.RunAppAtTheEnd, Return.check, When.After, Step.InstallFinalize, Condition.Always)
                        { Feature = hmiBinariesFeature }
                },

... And: ...

project.AfterInstall += ProjectOnAfterInstall; // Runs InstallApp.ps1 script

```

Ah okay, that seems a bit too much for my current project (and the state it's in) but I'll keep that in mind.
Anyhow I was reading through these;
https://stackoverflow.com/questions/11722541/wix-dynamically-changing-the-status-text-during-customaction
https://stackoverflow.com/a/44542042/4122889

I thought I could just write messages to the UI or something, I tried it out;
``` csharp
 using (Record record = new Record(0))
    {
        record.SetString(0, "foo");
        session.Message(InstallMessage.ActionData, record);
    }
```
But that did not turn up anywhere in the UI.
I'll take a look at the custom UI samples real quick.

**Comment by oleg-shilo** [comment]
I would expect `session.Message` to work, though i would not bet on it as a default direction :)
Everything that is even slightly non-trivial in MSI is a nightmare to get working if it does not tick from the start. Thus I would go with some custom techniques that are based on a standard SW dev frameworks and tools. Thus if you have a problem you know what to do.

Good luck

**Comment by sommmen** [comment]
> I would expect `session.Message` to work, though i would not bet on it as a default direction :)
> Everything that is even slightly non-trivial in MSI is a nightmare to get working if it does not tick from the start. Thus I would go with some custom techniques that are based on a standard SW dev frameworks and tools. Thus if you have a problem you know what to do.
> 
> Good luck

Thanks, and also thanks for discussing with me.
Using Wix# is kinda fun, there are a lot of caveats to Wix but Wix# really helps in showing the way.
Thanks for your continued work in the opensource domain.
