### ISSUE TITLE
WixBinLocator doesn't find WiX if installed with scoop

### ISSUE THREAD

**Issue by cocowalla** [oleg-shilo/wixsharp#986]
I like to use scoop for scripted installs, especially for build servers - for example, I can install WiX Toolset like:

```
scoop install wixtoolset --global
```

Scoop sets an environment variable, `WixToolPath`, pointing to the install folder, e.g. `C:\ProgramData\scoop\apps\wixtoolset\current`.

Scoop installs all the binaries directly in that directory - *not* in a `bin` subdirectory, and AFAICS, `WixBinLocator` always expects binaries in `MY_ENV_VAR\bin`, regardless of which env var you use (`WixToolPath`, `WIX`, `WIXSHARP_WIXDIR`).

I can work around this by creating a symbolic link, but it's not ideal. Would be great if `WixBinLocator` could look for binaries without the `bin` suffix too  😃

**Comment by oleg-shilo** [comment]
Thank you, Valid point.
I have extended the locator algorithm with support for `%WixToolPath%` (https://github.com/oleg-shilo/wixsharp/commit/237ac64ab176482f64c64a35aacecfa08feab212).

> I can work around this by creating a symbolic link...

You do not need to resort to that. From the start it was clear that there would be the cases when locator would not be able to find WiX so all locations can be set 

```C#
WixSharp.Compiler.WixLocation = @"<wherever_wix>";
WixSharp.Compiler.WixSdkLocation = @"<wherever_wix_sdk>"
```  

You can also have a global wort around by setting `%WIXSHARP_WIXDIR%`  to desired location:
```
set WIXSHARP_WIXDIR=%WixToolPath%
```

`%WIXSHARP_WIXDIR%` was introduced to allow users to fix problems like this.
