### ISSUE TITLE
Question: Net core Installer Net core Projects

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#987]
Hallo Oleg,  i dont know if someone already asked for net core installer wix sharp. I ask anyway. 
I found https://docs.microsoft.com/de-de/visualstudio/deployment/installer-projects-net-core?view=vs-2019
and already tested it. Somehow installer can be created and net core app, net core depend,  is installed. Also check for net core is exists. Investigate of msi with orca, give me following screenshot.
![Net Core Installer](https://user-images.githubusercontent.com/25432729/116688737-65fb2800-a9b7-11eb-8256-79b740b14e12.JPG)
Any way to achieve same , with pure wix or wixsharp?

**Comment by oleg-shilo** [comment]
It is a ClickOnce deployment, which is a MS alternative to MSI. Thus there is no overlap with neither WiX nor WixSharp.

**Comment by Torchok19081986** [comment]
Morning Oleg.  After building the Installer i got like in description on MS , setup.exe and  myproduct.msi. https://docs.microsoft.com/en-us/visualstudio/deployment/installer-projects-net-core?view=vs-2019
The output msi file is same. MS Project installer Type for normal .NET Framework before Net 5.0. There is only one difference to normal Installer. Before Installer do something, CMD Window appears and check with dotnet.exe something . Dotnet.exe comes with Net 5.0 after install windows-runtime prerequires. Maybe some MS "magic".

**Comment by Torchok19081986** [comment]
Morning Oleg, after some research and some thinking .  AFAIK is net 5.0 is both Net Framework and Net Core together. What if we try to create normal msi with Net Framework and check for net core in registry ? All we need to do customize internal checks for exampla installed net core from registry etc. and execute CA normal in Net Framework ? dotnet exe check for net core with publish parameter, why to use it as embeded source and call it in beforeinstall event ? 
What do you think ?  Can this thoughts your agreement?
