### ISSUE TITLE
Create a RestorePoint with a MSI

### ISSUE THREAD

**Issue by hcarsten** [oleg-shilo/wixsharp#989]
Currently we are shipping the product as a MSI only. So no bootstraper at all. Is there a way to a "plain" MSI create a Restore-Point or is there a way to do so ? Maybe a way to create a minimal bundle ?

best

Carsten

**Comment by oleg-shilo** [comment]
As far as I know every MSI installation creates a restore point.
Unless MSI team has changed this behavior...
