### ISSUE TITLE
FindWixSdkLocation in WixBinLocator.cs returning null if SDK found as subfolder

### ISSUE THREAD

**Issue by oOxOvOxOo** [oleg-shilo/wixsharp#990]
Hi,

If Wix Toolset v3.11 is installed in Program Files (x86), the SDK folder is found and this function returns a string:
```
var wixSdkLocation = Path.GetFullPath(Utils.PathCombine(wixLocation, @"..\sdk"));
return wixSdkLocation;

```
But in another machine where Wix 3.11.2 is installed via a NuGet package manager, thus SDK is here found as a subfolder, this function returns null instead of the string!
```
if (!Directory.Exists(wixSdkLocation))
{
   wixSdkLocation = Path.GetFullPath(Utils.PathCombine(wixLocation, "sdk")); //NuGet package shovels the dirs
   if (!Directory.Exists(wixSdkLocation) && throwOnError)
      throw new Exception("WiX SDK binaries cannot be found. Please set WixSharp.Compiler.WixSdkLocation to valid path to the Wix SDK binaries.");

   return null;
}
return wixSdkLocation;
```
The workaround at my side is to rearrange the SDK folder structure so that it returns a string instead of null.
I propose the solution is to remove "return null;"

Regards,
Jef Snellings

**Comment by oleg-shilo** [comment]
Thank you Jef,

Unfortunately it's is not possible to provide an algorithm that would count for all future decisions WiX vendor comes to with regard to internal location of the deployed tools. That's why for any cases of exotics locations WixSharp provides a straight forward work around: you as a user can specify the exact location:
```C#
WixSharp.Compiler.WixSdkLocation = @"<whatever_wix_sdk_location>";
```

**Comment by oOxOvOxOo** [comment]
Hi,

I will use this WixSdkLocation work around, thanks!

Regards,
Jef
