### ISSUE TITLE
Multiple languages support for bootstrapper project

### ISSUE THREAD

**Issue by ruleil** [oleg-shilo/wixsharp#991]
I have two questions about WixSharp bootStrapper bundle project.
1. How to have multiple languages for bootStrapper bundle project? The bundle exe I got always displaying English language.
2. How to disable the "Options" button?
![image](https://user-images.githubusercontent.com/35195892/117938267-6db4b800-b339-11eb-8299-1f5dbc633e44.png)

**Comment by oleg-shilo** [comment]
The Bootstrapper default UI is the UI built with WiX tool Burn. WixSharp only orchestrates the build but does not provide any extra interface on to of what is available with Burn interface.

Meaning that if you want to control appearance of the bootstrapper UI you will need to find the how it's done with WiX syntax and then simply repeat the solution with eiter WixSharp syntax or (if not available) by massaging the produced XML in teh prebuild event handlers.
