### ISSUE TITLE
How to deal with per-user and per-machine installations

### ISSUE THREAD

**Issue by NickeManarin** [oleg-shilo/wixsharp#992]
I have a couple of questions about the install and update process for per-user and per-machine modes.

1) Manually selecting a path.

When selecting a per-user installation mode (`ALLUSERS = 2` and `MSIINSTALLPERUSER = string.Empty`), the install path is set to `C:\Users\[UserName]\AppData\Local\Programs\[AppName]\` when no value is set to `MsiRuntime.Session[INSTALLDIR]`.

When selecting a per-user installation mode (`ALLUSERS = 2` and `MSIINSTALLPERUSER = 1`), the install path is set to `C:\Program Files (x86)\` when no value is set to `MsiRuntime.Session[INSTALLDIR]`.

What's the expected behavior when the user wants to pick an installation folder?
Should I assume that it's a per-machine installation and set `MSIINSTALLPERUSER ` to 1?

-----------------------------------

2) How to detect if the previous installation was per-user or per-machine?

I've tried to use [MsiEnumProductsEx](http://pinvoke.net/default.aspx/msi/MsiEnumProductsEx.html), passing the `MsiRuntime.ProductCode`, but I could not find any previous installation.

**Comment by oleg-shilo** [comment]
Hi Nicke, I was waiting if someone can shed some light on this.

I do not know the answer. It it is pure WiX/MSI question so possibly WiX forums can help.

**Comment by NickeManarin** [comment]
Hi Oleg, I think that I'm on the right track to solve my issues.

Once it gets past my tests, I'll share here with you.

**Comment by NickeManarin** [comment]
Ok, I managed to make it work.

1) 
Basically, I detect the previous install context, install location, and present that to the user.
When selecting an installation directory, I detect if an installation with a different context is using that same folder.
If it's using, I simply uninstall the previous version before installing it with another context on top of it.

2) 
I'm using the `AppSearch.GetRelatedProducts()` passing the upgrade GUID.
When needed, to detect a previous installation based on the folder, I get the installation folder using the components path.

**Comment by oleg-shilo** [comment]
Great, thank you for sharing
