### ISSUE TITLE
How to determine the log level on runtime?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [oleg-shilo/wixsharp#996]
Hi there,

I want to log sensitive information in `AfterInstall` with `Session.Log()` but only when verbose logging is enabled, meaning `/lv` is passed as command line argument to `msiexec`.

My current approach would be to pass an additional parameter to the `msiexec` call and use that parameter to trigger my verbose logging but that feels like a workaround for me.

How can I determine which log level is enabled while the MSI executes?

So lonG
Daniel

**Comment by oleg-shilo** [comment]
I am not sure how log level can be obtained. `Session.Log()` is implemented in the `Microsoft.Deployment.WindowsInstaller` and I do not see any API around logs except these two:
```C#
public void Log(string msg);
public void Log(string format, params object[] args);
```

And I do not feel that this information will be stored in the session properties. 
So I don't really know.

**Comment by ViRuSTriNiTy** [comment]
Thanks for your honest answer. I think I have to continue using an additional parameter then. Closed as there is no solution.
